== BOOK III, Chapter VII.

[.chapter-synopsis]
* Meetings undisturbed for a Season
* Twenty Persons die Prisoners in Newgate
* Amongst them Richard Hubberthorn and Edward Burrough
* Life and Character of Richard Hubberthorn
* Ditto of Edward Burrough
* William Ames
* Samuel Fisher; for refusing to swear, committed to Newgate
* Notes exemplifying sundry suffering Cases

For about six weeks after the violence committed at Bull
and Mouth meetinghouse under major-general Brown,
the meetings in the city were generally undisturbed:
the death of John Trowel (the innocent victim of their cruelty),
the apprehension of trouble which might have followed it,
and the public censure of their inhumanity, having, probably,
damped the ardour of these persecuting magistrates for the present;
who nevertheless soon returned to a repetition of the same practices,
and continued therein to near the end of this year.

By which time no less than twenty persons died prisoners in Newgate,
and seven more by sickness contracted there, soon after their discharge:
amongst those who died there, were Richard Hubberthorn and Edward Burrough,
two well qualified serviceable men, whose exemplary lives, ministerial labours,
active exertions in behalf of their suffering friends,
and remarkable qualifications for usefulness in various respects,
gave them a place amongst the most eminent members of this society,
made their loss very sensibly felt by their friends;
and furnished their enemies and oppressors (whom it ought to have humbled into contrition,
had they retained any tenderness of the christian or the man,
as authors of their untimely death) with an occasion of exultation,
in hopes that the removal of these serviceable members would give such a shock
to the society (whose extinction they desired) as would not be readily got over.

Richard Hubberthorn had his birth in the northern parts of Lancashire,
being the only son of his father, a yeoman of good repute in that country.
From his youth, he was averse to vice and inclined to piety, sobriety and virtue.
Being arrived to years of maturity, he obtained a post in the parliament`'s army,
and from a zeal for promoting righteousness,
preached occasionally to the soldiers and others.
But entering amongst some of the first into the society of the Quakers so called,
agreeable to their principle of peace he quitted his military employment,
as he found it his place to use his endeavours,
by a spiritual warfare with his own lusts and infirmities,
so to walk in obedience to the grace of God, as to obtain favour with that prince,
whose kingdom is not of this world.
And passing through a variety of inward probations,
he attained experience in the work of regeneration,
and received ability to direct others in the sure way to the kingdom of Heaven,
being one of the first of the ministers in this society who travelled
about for the propagation of righteousness.

His bodily presence promised little, being a man of low stature, infirm constitution,
and a weak voice;
so that an acquaintance with his real character was
reserved for an intimate knowledge of his worth,
which lay out of the way of superficial observation,
consisting not in gracefulness of person, but the laudable faculties of the mind:
he was of an excellent natural temper, being a man of much meekness, humility,
patience and brotherly kindness; of distinguished equanimity,
neither easily depressed in adversity, nor elated in prosperity; clear in judgment,
and quick of understanding, he knew his season when to speak, and when to be silent;
and when he spoke, he spoke with plainness and pertinency to the subject before him.

Notwithstanding the weakness of his voice, he was a powerful,
able and successful minister of the gospel;
travelling in the different parts of England in the exercise of his ministry,
mostly for the space of nine years:
great numbers were convinced and brought over to the same faith and practice,
which he preached up, as seals to the power and efficacy of his ministry.

Although he was the very man, that having obtained access to the King,
was admitted to a free conference with him, in which he gave him such satisfaction,
as to the principles and practice of the Quakers, so called,
that he received the royal assurance of protection from suffering for the whole society,
while they lived peaceably: yet this promise was violated,
as well in reference to his own person, as to the society in general.
For in the month called June,
he was haled with violence from the meeting at Bull and Mouth,
and carried before that implacable magistrate alderman Brown, who,
indulging his passion as usual,
pulled him down by the hat with such fury that he brought his head almost to the ground:
in the insolence of office, thus treating with unbecoming indignity a man of consequence,
and good repute, and a much worthier character than himself had any pretensions to;
he then committed him to Newgate; where the throng was so great, and the air so vitiated,
as soon overpowered his infirm constitution; he presently grew sick,
and was taken away by death, when he had scarce been two months in prison.

As his life had been spent in acts of righteousness and the pursuit of peace,
his latter end exhibited the happy effects thereof; the peaceful tenor of his conscience,
stripping death of all its terrors, he was in his last moments supported to look forward,
in full assurance of faith to the near approach of future happiness.
Some of his intimate friends visiting him near his end,
and inquiring if he felt anything on his mind to communicate, he replied,
"`That there was no need to dispute matters; he knew the ground of his salvation,
and was satisfied forever in his peace with the Lord.`"
At another time he expressed himself thus, "`That faith which hath wrought my salvation,
I well know, and have grounded satisfaction in it.`"
But the greatest part of the time of his sickness
he passed in inward retirement and meditation,
so resigned, and so still, that he was not observed to vent a groan through the whole.
The day before he died, he said, "`This night or tomorrow I shall depart hence.`"
And the next morning, to one sitting by him, "`Do not seek to hold me, for it +++[+++the body]
is too strait for me; and out of this straightness I must go;
for I am wound up into largeness, and am to be lifted up on high far above all.`"
So in the evening of that day, the 17th 6th month.
1662, he finished his course in this life,
in a frame of mind well prepared for an entrance into a better.

Edward Burrough was born in or near Underbarrow, a village in the barony in Westmoreland,
of parents in repute for their honest and virtuous conduct in life,
who were possessed of competent substance to give him a
good education in such learning as the country afforded;
which though not furnishing the opportunity of what is termed a liberal education;
yet the soundness of his judgment,
and the maturity of his understanding abundantly
compensating for this deficiency in literature,
even his puerile years exhibited proofs of manly sense,
and he was early distinguished by wisdom and steadiness of conduct,
rarely to be met within one of his age;
employing himself even then in religious thoughtfulness,
and in the conversation of such as were in esteem for piety and virtue:
abstaining from the ordinary pleasures and pursuits of youth,
he placed his satisfaction in perusing the holy scriptures, in which he was well versed.
He was brought up by his parents in the episcopal way of worship;
but at the age of twelve years he began at times to frequent the meetings of the Presbyterians,
because their doctrine appeared to him to approach nearer
to the primitive practice of the christian church;
and continued his attendance of their meetings till about the 17th year of his age,
when his reflection and judgment attaining a greater degree of maturity,
he felt considerable uneasiness and fear,
being led to take a view of the condition of his soul;
and thereby being convinced that notwithstanding his religious appearance,
and good reputation, he had not attained to that knowledge of God,
and that internal purity of heart, which was discovered to his understanding,
as the essential part of true religion.
About this time, being exercised in prayer,
he felt an inward conviction impressing his understanding with this intelligence,
"`Thou art ignorant of God; thou knowest not where he is, nor what he is;
to what purpose is thy prayer?`"
This awakening intelligence excited him to redoubled diligence,
and circumspection of life, so that he was not only very careful in his own conduct,
but upon occasion, was concerned to reprove others for their vain conversation,
impiety or immorality; wherein,
though his charitable endeavours exposed him to contempt and derision,
yet he felt in himself much peace, and enlivening refreshment of spirit,
in a consciousness of his religious life and sincere endeavours to please God.

Notwithstanding which, his mind was often so attended with doubting and perplexity,
that it became greatly darkened,
and in this state he was ready to question his own experience:
Yet sincerely desirous of further discoveries of the way of life and salvation,
and finding the doctrine of the teachers to whom he had attached himself,
defective in profitable instruction, as to the want and desire of his soul,
appearing to him the result of mere speculation,
and a natural comprehension of the scriptures and of the experiences of others,
and not the fruit of their own experience, he discontinued his attention to them;
and was one, amongst the many, that were at a loss in their minds, what guide to follow,
or what society to look to, for the direction they wanted.
At the time when George Fox first came into the parts where he resided,
he went to hear him preach,
and afterwards entered into reasoning with him upon religious subjects
(as before related) where by it pleased the Lord so to open his
understanding into a clear view of his spiritual condition,
that he perceived (as he himself expresseth it) that he was yet in the prodigal state,
above the cross of Christ, and not in the true fear of the Lord:
Yielding to the conviction of truth (as he was fully persuaded)
he was not discouraged from entering into society with the Quakers,
though like the primitive christians, a people despised by the world,
and everywhere spoken against.
For this he was rejected by his relations, and expelled from his father`'s house,
which hardship, with many others he was afterwards exposed to,
he bore with exemplary patience,
and continued steadfast to the last in the doctrines and principles of truth.
Through fidelity to the discovery of duty, by the light in his conscience,
he advanced in the work of sanctification,
and being thereby endued with the best qualification,
became an eminent minister of the gospel, and a most serviceable member of this society.
Indefatigable in the laborious exertion of excellent talents, natural and spiritual,
by word and by writing, for the promotion of righteousness in the earth;
for the propagation of gospel truths; for edifying of the body in love;
and using endeavours for their relief from their grievous sufferings;
he willingly devoted the bloom of his youth, and the succeeding part of life,
to the service of God; of his fellow members in society, and mankind in general,
by unremitted endeavours to prevail upon the inhabitants of his native country,
and other nations, to turn from the evil of their ways;
to encourage them to righteousness and purity of life by example, exhortation,
admonition and reproof.

These religious exercises were as the whole business of his life,
of which he did not appropriate to himself or his
private concerns one week at a time for many years;
but being continually and industriously employed in doing good,
he allowed himself few hours of repose.

His ministry was powerful and reaching, his doctrine sound, and his language eloquent;
for though defective in human literature,
in the estimation of the wise men of this world,
yet he spake as with the tongue of the learned, having learned in the best school,
and been prepared for the ministry by the best instruction, that of the Spirit of truth,
gradually leading into the living experience of holiness,
through the washing of regeneration, he was qualified, like the wise scribe,
out of the treasury of his own experience, to bring forth things new and old;
and to speak with clearness in the demonstration of the spirit,
to the understanding of his auditors.
He spake the feeling and animated language of the heart, aptly applied to the states,
and reaching the divine witness in the hearts of his hearers,
whereby his ministry was made effectual to the turning of many from darkness to light,
and from sin to righteousness and circumspection of life.

His personal conduct gave efficacy to his ministry;
he lived himself as he wanted and advised others to live, viz. in the fear of his Maker,
walking in his presence,
and setting him as at his right hand that he might not sin against him.
His natural disposition was bold and manly, tempered with innocence;
his conversation affable and instructive, circumscribed with watchful care.

That arbitrary stretch of power,
which at this period was so unjustly pointed at Quakers in general,
was like to fall most heavily upon those who were most eminent amongst them.
It might therefore administer occasion of wonder,
if this distinguished young man had escaped the stroke of a persecution
so generally levelled at the body of which he was considered as
one of the principal ornaments and supports.
Under the rigour of an harsh imprisonment, he fell a sacrifice to inexorable malice,
and terminated a life of exemplary virtue and wisdom at an age,
when the generality of mankind scarce think seriously about living.

The preceding pages have informed the reader that he travelled in many parts of England,
through Ireland, in Scotland and Flanders, in the exercise of his ministerial labours,
in which he met with a variety of sufferings, trials and imprisonments;
but his principal field of labour, from the time of his going thither,
was in and about the city of London,
where his ministry had been effectual to the conversion of numbers.
And his affectionate regard was so warm to the inhabitants of that city, that he is said,
when persecution grew hot, repeatedly to have expressed himself thus to Francis Howgill,
his bosom friend: I can freely go to that city,
and lay down my life for a testimony to that truth,
which I have declared through the spirit and power of God.`"
And being this year on a visit to his friends in Bristol, in taking his leave of them,
he said he did not know he should see their faces any more,
and therefore he exhorted them to faithfulness and steadfastness
in that wherein they found rest to their souls.
And to some, "`I am now going up to the city of London again,
to lay down my life for the gospel, and suffer amongst friends in that place.`"

Not long after arriving in London, he attended the meeting at Bull and Mouth,
where as he was concerned in his ministry, he was violently pulled down by soldiers,
and taken before alderman Brown, who committed him to Newgate: Some weeks after,
he was brought to trial at the Old Bailey, fined by the court twenty marks,^
footnote:[The proceedings of the courts at this time seem inexplicable,
as it doth not appear by what law they imposed these arbitrary and exorbitant fines.
The late laws against Quakers limit the forfeiture and imprisonment.
The revived obsolete law of Elizabeth,
of 20£. a month could not lie against a man for being found at one meeting,
and who previously had been travelling in other parts; besides,
I do not find this act gives any power of imprisonment at all.
Neither doth the statute of Premunire reach the present case.
So that it seems as if they acted with or without law at their pleasure,
in harassing an harmless body of men.]
and condemned to lie in prison till he paid the fine:
which amounted to perpetual imprisonment, unless released by the king;
for as the fact for which he, with many of his brethren, were condemned, was,
in their estimation, no crime, but an act of indispensable duty to God,
a voluntary and active compliance with the penalty,
they esteemed a tacit confession of guilt, giving away the cause,
and balking their testimony to the truth, which, for conscience-sake, they durst not do.
This their persecutors well knew,
and took this as another mode to imprison them during pleasure.

Being thus immured in the same prison with six or seven score of his friends,
crowded so many in one room, as was even suffocating, many of them grew sick and died,
of which number he was one.
And though a special order from the king was sent to the sheriffs of London,
for his release and that of some other prisoners,
yet such was the aversion to all humanity,
and so implacable the enmity of some of the city magistrates, especially Brown,
that they exerted themselves to prevent the execution of this order,
and found means to effect it.
By his detention in prison, his distemper gathered strength,
and threatened his approaching dissolution,
the prospect where of the purity of his conscience stripped of all its terrors,
supported by the consolatory review of a life well spent in the service of his Creator,
his friends and fellow-citizens, and exempt from the consciousness of imputed sin,
or wilful omission of duty, he hesitated not to make the following solemn appeal:
"`I have had the testimony of the Lord`'s love unto me from my youth, and my heart,
O Lord, hath been given up to do thy will.
I have preached the gospel freely in this city,
and have often given up my life for the gospel`'s sake; and now, O Lord, open my heart,
and see if it be not right before thee.`"
Again, "`There is no iniquity lies at my door; but the presence of the Lord is with me,
and his life I feel justifies me.`"
His friends about him he counselled to live in love and peace, and love one another.
Praying for his enemies and persecutors, he said, "`Lord forgive Richard Brown,
if he may be forgiven.
And being sensible of his dissolution drawing nigh, he said,
Though this body of clay must turn to dust,
yet I have a testimony that I have served God faithfully in my generation;
and that spirit that hath lived and acted and ruled in me,
shall yet break forth in thousands.`"
The morning before his departure, he said,
"`Now my soul and spirit is centered into its own being with God,
and this form of person must return from whence it
was taken;`" and after a little time expired,
the 14th of the month called February, in the prime of life,
being in the 28th year of his age,
having been a zealous preacher of righteousness about ten years.

William Ames also died in the latter end of this year at Amsterdam.
As soon as the last act against conventicles came in force,
several individuals of bitter spirits, and officious in evil,
seemed waiting with impatience the opportunity of gratifying their inclination to mischief,
without regard to legal forms or the constitutional privileges of the subject;
for such was the temper of this persecuting age,
and such the protection that lawless persons depended upon,
that the principal barriers of the constitution were broken down,
to give illegal effect to iniquitous laws:
So enforcing that when some of this people were seen to enter an house,
though only on a private visit to their friends,
they were pursued into the house by musketeers, without legal authority; and even doors,
of private dwellings were broken open,
under pretence of detecting their meetings (who never met in corners
to avoid detection) and where they found five together,
upon whatever business or occasion, it was a conventicle.
Now it happened that two of these musketeers,
Thomas and John Herbert with other associates,
entering one house according to their custom with drawn swords,
found there Samuel Fisher, William Ames, and three more,^
footnote:[Samuel Goodacre, Henry Green, and J. Grimshaw.]
whom they immediately took prisoners, and being asked for a warrant,
holding up their swords, replied, "`Do not ask for a warrant, this is our warrant.`"
They immediately forced them to Paul`'s yard,
where they were derided and abused by the soldiers,
and afterwards taken before Richard Brown,
who sent them with a mittimus to Bridewell to be kept to hard labour,
where they were required to beat hemp,
and treated so severely that William Ames grew dangerously ill,
and being an inhabitant of Amsterdam,
he was discharged for fear of his dying in prison here;
upon which he returned to the place of his residence, in a weak state of health,
from which he never recovered, but died within the current year.^
footnote:[Sewel, p. 379. et alibi.]

In his youth he was of a cheerful disposition, and delighted in airy company;
but being disquieted in mind by conviction of his folly in misspending his precious time,
he gave himself up to religious exercises,
to a diligent attendance to the doctrine of the priests and teachers,
and to the reading of the scriptures, a practice good in itself,
yet his religion only notional, amusing the understanding, but not cleansing the heart,
brought him not peace with God:
but being of quick understanding he could discourse
readily of those topics which he had heard and read,
and entering into society with the Baptists, became a teacher among them.
He was also a military officer in Cromwell`'s army in Ireland, to which post,
being strict and regular in his own conduct, he exerted himself to introduce,
and preserve the like regularity among the soldiers under his command by a strict discipline:
But still though he had truth in his comprehension,
and could discourse of sanctification,
he perceived he was not come into the experience thereof,
as his passions had still dominion over him; regeneration was yet wanting;
and he was at a loss as to the means of attaining what he stood in need of.
About this time Francis Howgill and Edward Burrough coming into Ireland,
he went to hear them,
and by their doctrine was informed that it was the light wherewith
Christ enlighteneth every man that cometh into the world,
which convinceth man of sin, and giveth him power over it.
This doctrine delivered with a reaching influence, made a deep impression upon his mind,
and produced in him a resolution circumspectly to attend to this inward monitor:
and thus walking in fear, he received power to avoid the evil he was condemned for,
and to advance in the work of sanctification,
and not only joined in profession with the people called Quakers,
but in process of time became a zealous preacher amongst them,
and travelled in the work of the ministry, not only in England,
but much in Holland and Germany, where several were convinced by him,
especially in the Palatinate; and these Palatines removing soon after to Pennsylvania,
escaped the general devastation of their country by the French,
which happened not long after; and at last he settled at Amsterdam,
where he supported himself by wool-combing, and there he died as before related.

Samuel Fisher and the rest committed with him,
at the end of six weeks were brought to the sessions at the Old Bailey, not to trial,
for they had no charge against them, being very illegally imprisoned,
having broke no law: And therefore they were brought to be involved in the breach of law,
by the sure course of tendering the oath of allegiance:
They desired the act might be read, by virtue whereof the oath was required of them.
This was promised by the court to be done;
yet instead thereof they ordered the clerk to read only the form of the oath,
but would not allow the law imposing it to be read.
Before the prisoners had declared their refusal, they were ordered to be taken away,
which the officers did with such rudeness,
that they threw some of them down upon the stones; and thus,
instead of being freed from their illegal imprisonment, they were committed to Newgate.

The relation of the harsh and unjust measures pursued in this year of hot persecution,
we have confined mostly to the city of London, as the principal scene of action;
yet these or the like proceedings, were not confined to the city,
but were too generally carried on in the different counties,
wherever the magistrates were bigots to the church, or sycophants to the court,
of which there were too many in all quarters.^
footnote:[John Grave of Turpenhow, Thomas Watson of Cocker- Cumbermouth,
and John Robinson of Brigham,
taken out of their own houses by soldiers and carried before the governor of Carlisle,
were by him imprisoned in the winter in a cold place over one of the city gates,
where they were denied the visits of their friends,
and had their food frequently kept from them; afterwards the oath was tendered to them,
for refusing which they were removed to the county jail,
where they lay thirty-five weeks.
{footnote-paragraph-split}
George Fletcher, a justice of peace in this county,
with a retinue armed with swords and pistol,
rushed violently into a meeting at Howhill in Sowerby parish,
and finding a person on his knees, he struck him over the head;
and when he continued praying ordered him to be pulled down backward,
and then caused him, with several others,
to be dragged down the hill in a violent and cruel manner,
and afterwards sent them to Carlisle jail.
[.book-title]#Besse.#
{footnote-paragraph-split}
Extract of a letter,
written by some prisoners to the justices of peace at Winchester sessions,
dated the 13th of the month called January, 1662.
{footnote-paragraph-split}
"`We are men that fear the Lord, and follow peace with all men,
amongst whom we have behaved ourselves peaceably and quietly,
labouring with our hands in honest callings, to provide for ourselves and families;
and careful, though we suffer in body and estate,
such sufferings may only affect ourselves and ours,
and that no other person may suffer loss or detriment thereby,
nor we be chargeable to any.
We have not willfully provoked the officers or rulers against us,
nor administered other occasion of offence,
than that we dared not but serve the Lord that made us, by waiting upon him;
for this only, and no other cause on our parts, we have, previous to our imprisonment,
suffered so much cruelty and inhuman usage as almost exceeds belief,
that Englishmen should be so unmercifully abused by soldiers and others,
as we have been for the space of a year and a half in the town of Portsmouth,
the place of our abode: Few first days in that space of time but we were,
by the rudest soldiers chosen out for the purpose, and officers of the like stamp,
either haled from our meetings before the law was made against them,
or forced out with violence, beaten with their muskets,
pushed and punched with the butt-ends thereof;
and in this manner driven out of the gates from our habitation and lawful employments.
Our bodies were sorely bruised, our goods spoiled or carried away,
and our windows battered to pieces after we were forced out.
At other times we were made prisoners in our own meetinghouse,
and armed guards set on every side to keep us in, men and women together,
contrary to the rules of civility or decency.
Food denied to be brought to us, or our food taken away by the soldiers.
Some of us have been kept several weeks in nasty holes,
generally esteemed too bad for felons to be kept in a few days: In Felton`'s hole,
the waves of the sea beat in upon one of us to that degree in the winter season,
that he has stood up to his ankles in water.`"
{footnote-paragraph-split}
"`After we had for the space of
a year and a half suffered such abusive treatment;
the rulers of the nation added affliction to our sorrows,
by making a law that not more than five might depart from their habitations,
and assemble for worship, etc.
Although we were not at this time (for which we are imprisoned)
the number of five who departed from our habitations,
and therefore not transgressors of the law,
which we made appear to the mayor and magistrates who committed us,
and they had no proof to the contrary;
yet notwithstanding they imposed the utmost penalty
of the law by imprisoning us for three months;
and three weeks over the term prescribed by the act are elapsed,
and we are still detained prisoners in Winchester this 13th of 11 month 1662.`"
After an appeal to the mercy and justice of the magistrates,
after claiming the benefit of the king`'s late declaration,
they subscribe in acquiescence to the divine will.`"
John Austin, William Buckland.
Nicholas Complin, Jonas Goff, Thomas Cozens,
William Jennings.
{footnote-paragraph-split}
"`At the same
time was a prisoner with them in Winchester jail,
Humphry Smith, who was kept under close confinement,
and never called to answer at any assize or sessions,
and his friends were frequently denied the liberty of visiting him,
until he died there on the 4th day of the month called May, 1663.
This good man had a foresight of his death, and said to some of his friends,
that he had a narrow path to pass through: And more than once signified,
he saw he should be imprisoned, and that it might cost him his life.
In the time of his sickness he expressed himself thus:
"`My heart is filled with the power of God;
it is good for a man at such a time as this to know the Lord for his friend.`"
And at another time, "`Lord thou hast sent me forth to do thy will,
and I have been faithful unto thee in my small measure which thou haft committed to me,
but if thou wilt yet try me farther thy will he done.`"
Also he said, "`I am the Lord`'s, let him do what he will.`"
And when near his departure he prayed thus:
"`O Lord hear the inward fights and groans of thy oppressed,
and deliver my soul from the oppressor.
Hear me, O Lord! uphold and preserve me.
I know that my redeemer liveth.
Thou art strong and mighty, O Lord.`"
He also prayed, that God would deliver his people from their oppressors.
And for those who had been convinced by his ministry, that God would be their teacher.
He continued sweetly still, and sensible unto the end, and died in perfect peace.]
