== Chapter VIII.

[.chapter-synopsis]
* Declaration of Indulgence
* The Parliament opposes Indulgence to the Dissenters
* Remarks upon the King`'s Declaration from Breda
* Persecution in general moderated
* But grievously carried on at Colchester
* Rumours of a fresh Conspiracy
* George Fox writes a Paper disclaiming all Plots
* Yet is subjected to Prosecution
* Sundry Attempts to take him
* He goes to Colonel Kirby, who treats him with dissembled Kindness
* At a private Meeting the justices grant a Warrant to apprehend George Fox
* Of which he has Notice, but resolves to stand his Ground
* He is committed to Lancaster Castle
* Margaret Fell summoned before the justices
* Who tender her the Oath of Allegiance, and imprison her also
* Their Prison very incommodious
* Francis Howgill taken out of the Market at Kendal and imprisoned

In the latter part of this year, the king, by the advice of his privy council,
issued a declaration, dated the 26th of December, in which after other things,
mentioning the promise of liberty of conscience, contained in his declaration from Breda,
he adds, "`We are glad to renew to all our subjects concerned in those promises,
this assurance, that as for what concerns the penalties on those, who living peaceably,
do not conform to the church of England through scruple or tenderness of misguided conscience,
but modestly and without scandal perform their devotions in their own way,
we shall make it our special care, as far as in us lies,
without invading the freedom of parliament,
to incline their wisdom at the next approaching sessions,
to concur with us for making some act for that purpose, as may enable us,
with a more universal satisfaction, to exercise that power of dispensing,
which we conceive to be inherent in us.`"

In his speech at the opening of the next sessions, the 28th of the month called February,
1662-3, he supported his declaration in the following words:
"`That though he was in his nature an enemy to all severity in religion,
he would not have them from thence infer that he meant to favour popery,
though several of that profession for their services might justly claim
a share in that indulgence he would willingly afford to other dissenters.`"
Then expressing his zeal for the protestant religion and the act of uniformity continues,
"`If the dissenters will behave themselves peaceably and modestly under the government,
I could heartily wish,
I had such a power of indulgence to use upon all occasions
as might not needlessly force them out of the kingdom,
or staying here give them cause to conspire against the peace of it.`"

But the parliament, in their present bigotry to episcopacy,
equally averse to papists and non-conformists, in their address to the king,
delivered it as the opinion of the House, That no indulgence be granted to dissenters;
and as the king pleaded his promises of toleration,
they represented that his declaration from Breda contained no promise,
but an expression of his intentions,
upon the supposition of the parliament`'s concurrence;
and that even if the non-conformists had been entitled to plead a promise,
they had entrusted their claim to the house of commons, who were their representatives.
It was not the weight of argument, but the power of the parliament,
that could give force to such reasoning as this,
and carry conviction to the king or the people.
The king`'s extravagance reducing him to the necessity
of continual applications for supplies,
the commons, by a liberality approaching to profusion,
purchased his assent to feeble arguments and vindictive laws.
The king`'s declaration from Breda I apprehend not only to be a solemn promise,
but a solemn act,
amounting to a treaty or covenant between him and the people of England.
The king proposed terms to the parliament then sitting;
upon these terms he was accepted as their king,
which was as the ratification of the treaty by the representative body: Surely,
if ever there was a compact between king and people,
this was one of the most binding nature.

But although the parliament withstood the king`'s measures in this matter,
yet this declaration of his disposition to moderation,
seems for a season to have retarded the furious career of the persecuting magistrates.
We meet with few instances of sufferings in the metropolis in the succeeding year,
in comparison of those related in the last; yet they did not remain quite unmolested,
for Sir John Robinson succeeding R. Brown in the mayoralty,
a man well nigh equal to him in inveteracy to the people called Quakers,
ordered a guard to be placed at the entrance of the Bull and Mouth meetinghouse,
to prevent any person from going in.
Being thus shut out they met in the street, as near the door as possible,
and there stayed the usual time of their meeting.
When any one preached or prayed, they were generally haled away to prison.
One first day the mayor with his officers and the sheriffs coming thither,
and the people not dispersing at his command, he gave orders to his officers to strike,
who immediately, with their canes and sticks, as usual,
dealt their blows on all sides unmercifully on the heads of both men and women.
The mayor himself also struck several, and spurred on his horse to ride over them,
to avoid which the horse reared himself on his hind legs,
whereby his rider fell off backward into the kennel,
and being helped up again was preparing to repeat his abuses, had not the sheriffs,
who were more moderate, and ashamed of his actions, persuaded him to depart.

In this year also was a grievous persecution of this people at Colchester in Essex.
William Moore, then mayor, came several times to their meetings,
and after having dispersed them sent many to prison.
This method proving ineffectual,
a party of the county troops were employed to go to the meeting,
where they beat some and carried others to prison,
having first broken the seats and windows of the meetinghouse.
After this, being kept out of the house, they met in the street,
sometimes in the cold and rain,
not daring to decline their duty for these inconveniences: Thus they continued,
meeting constantly twice a week, till a troop of horse, just come to town,
armed with swords, carbines, etc. rode in furiously among them,
laying on without mercy on old and young,
some with their swords and some with their carbines, beat and bruised many exceedingly,
chasing them to and fro in the streets; they also committed many to prison.

On the 13th of December the troopers came again,
having added great clubs to their former weapons,
with which they knocked down many in the streets, where some lay as dead,
and many were so disabled and bruised that they could not
get off their clothes nor feed them selves for several years.
Remarkable was the patience and meekness of one of the sufferers, who,
when a trooper was beating him with a sword, and the blade fell out of the hilt,
took it up and gave it him, saying, "`I will give it thee up again:
I desire the Lord may not lay this day`'s work to thy charge.`"
After they had dispersed the meeting,
four of the troopers met a poor sickly man about
a quarter of a mile from the meeting place,
and riding up to him, asked him, Whether he was a Quaker?
He not denying it,
they beat him so that the spectators thought he would have died on the place,
and he had probably been killed, but that he was taken into an house;
however he was disabled from getting his bread or
providing for his family a long time after.

On the 26th of same month thirty-eight of these troopers came riding among the friends,
who were met in the street, and so cruelly beat them with clubs and carbines,
as moved compassion and tears in the standers-by.
As the soldiers forced some away by violence,
they drove them upon others of their comrades, who with clubs beat them afresh,
till the flesh of some of them was become like a jelly,
their blood for the present stagnated, and their limbs deprived of use.

On the 3rd of the month called January many friends being met at the usual place,
the soldiers fell furiously upon them, knocking down several,
one of whom they abused in such a manner that it was very much
doubted whether one of his arms would ever recover its use.
Solomon Fromantle, a merchant,
was so grievously abused and beaten that he lost much blood,
yet the barbarous trooper did not desist; his wife, fearing lest he should be killed,
fell down upon him, to cover and protect him from their blows,
many of which she received on her own body.
Edward Grant, father of Fromantle`'s wife, about seventy years of age, was knocked down,
and survived the blow but a few days.
On the 6th of same month the soldiers had put into their clubs, iron spikes,
sharpened with a file, with which they wounded many, vaunting,
scoffing and jeering them when they started or flinched at the pain;
amongst the rest they wounded an ancient woman in twelve several places.
After this finding the constancy of the sufferers invincible,
they began to relent and abate of their former violence,
so that there was a calm for two or three weeks,
till the mayor and recorder pushed them on again to act against their wills.

These appear the principal sufferings in the city
and neighbourhood on record in this year,
but an incident in the summer thereof, in which they had no concern,
involved George Fox and others in the country in great trouble,
by cruel and long imprisonments, on the following occasion:
The king and queen making a progress into the western counties, during their absence,
rumours of a new conspiracy were set on foot,
said to be formed in the north among the republicans and separatists,
to seize several towns in those parts, and raise a general insurrection.

At this time George Fox was travelling in Yorkshire, where,
when he first heard of this plot, in order to exculpate himself and friends,
and preserve them steadfast in their peaceable principle, he was concerned,
as he had been repeatedly under the preceding government,
to write a paper as his testimony against all plots and conspiracies whatever;
to admonish his friends to circumspection in their words and actions,
and not to intermeddle in any of these commotions;
copies of which be dispersed through the northern counties,
and also sent one to the king and council.
Notwithstanding these precautions he was soon subjected
to a very unjust and rigorous prosecution and imprisonment,
a pretended occasion being taken against him on account of this plot.

It seems as if uncommon pains were used to fix a suspicion
on this people of being parties in the conspiracy,
(whatever it was),
to give a colour of reality to the groundless report of their being concerned therein,
and as if the magistrates of the northern counties
had received directions from above for that purpose,
and particularly to take up George Fox;
for as he passed along from Yorkshire through the counties of Durham,
Cumberland and Westmoreland, several menaces were given out,
and sundry attempts made to take him, but he escaped them all, not by absconding,
(his fortitude founded in integrity disdaining mean evasions) but accidentally or providentially,
till he came to Swarthmore.
In his passing along he was well informed that in Cumberland the
magistrates had offered a crown or a noble a day to any of the
peace officers that could apprehend the speakers among the Quakers,
but at the time of his passing through that part
they were gone to the sessions to receive their wages,
by which means he passed on into Westmoreland unmolested, where he was in jeopardy still,
justice Fleming having in open sessions offered five
pounds to any man that should take him.
When he came forward to Swarthmore he was in formed that Colonel
Kirby had sent his lieutenant to search the house for him,
and that he had been so particular in his scrutiny, as to inspect the trunks and chests.

Upon this intelligence,
and reflecting upon the successive designs he had been informed of to apprehend him,
supported by conscious innocence and to show he was afraid of no scrutiny,
he resolved to face his pursuers.
Accordingly he went the next day to this Colonel Kirby`'s house,
where he found several of the gentry (so called) on a visit,
to take their leave of Kirby, who was about setting off for London,
to attend the parliament, and amongst; them justice Fleming aforesaid.
He addressed himself to Kirby, that understanding he was desirous to see him,
he paid him this visit, to know what he had to say to him,
or whether he had anything against him; to which Kirby replied he had not.
But, said he, Mrs.
Fell must not keep great meetings at her house, being contrary to law.
At parting he shook him by the hand, and repeated that he had nothing against him;
but notwithstanding his fair carriage and apparent civility,
it was understood he left private instructions with the
other justices to prosecute him after he was gone.

In a short time after there was a private meeting
of the justices and deputy-lieutenants at Holker-hall,
the seat of Justice Preston, where they granted a warrant to apprehend him.
Of this transaction, secret as they thought it, he received intelligence,
time enough to have withdrawn out of their reach.
But considering that during this noise of a plot in these parts,
although he had no meeting appointed, and was clear as to his service,
yet if he should go away it might give an advantage to his adversaries
to interpret or represent his retreat as a symptom of guilt,
and thence take occasion to fall with additional severity upon his friends; as,
on the contrary, if he surrendered himself into their hands,
his friends might come off the better;
on these considerations he determined quietly to abide the consequence,
and was apprehended the next day, and brought before the justices Rawlinston and Preston,
and one Sir George Middleton,^
footnote:[This Middleton (a papist) discovered great
bitterness of spirit against George Fox,
but he seemed not to know the man he had to deal with:
He first charged him that he denied God, the church and faith; to which George replied,
"`Nay, I own God, and the true church, and the true faith:
but what church dost thou own?`"
At which query he was greatly incensed, and said, "`You are a rebel and a traitor.`"
George immediately returned upon him, "`Whom dost thou speak to,
or whom dost thou call rebel?`"
Choked with passion, Middleton was awhile before he could speak, but at last got out,
"`I spoke to you.`"
George`'s spirit, roused at the charge, he struck his hand on the table and told him,
"`I have suffered more than twenty such as thou, or any that are here,
having been six months a prisoner in Derby,
where I suffered much because I would not take up arms against the king:
And was afterwards sent up a prisoner out of my native country by Colonel
Hacker to Oliver Cromwell as a plotter to bring in king Charles;
ye talk of the king, a parcel of you, but where were you in Oliver`'s days,
and what did you then for him?
I have more love to the king for bis eternal good and welfare than any of you have.`"
Middleton proposing to tender him the oath of allegiance and supremacy, George asked him,
"`whether he who was a swearer had taken the oath of supremacy
as for us we cannot swear because Christ forbade it?`"]
at Holker-hall aforesaid, by whom being examined, and clearing himself of the plot,
as they had no evidence or foundation for committing him upon that account,
they resorted to the accustomed snare of tendering him the oath of allegiance, and were,
upon his declining it, about making his mittimus;
but upon further consideration they contented themselves
with his engaging to appear at the sessions,
and so dismissed him at that time.

In consequence of his engagement, he appeared at the sessions at Lancaster;
where he was inquired of what he knew of the plot?
He told the justices he heard of it in Yorkshire, by a friend,
who had it from the high sheriff, They then asked him,
whether he had declared it to the magistrates?
He informed them of the aforementioned paper, which he had sent abroad,
and had also sent to them, as soon as he came into the country,
to remove all occasions of jealousy out of their minds concerning him and his friends.
Then they went upon the act against meetings; but upon these subjects,
finding no grounds to effect their purpose of committing him to prison,
they had recourse to the usual means of crimination:
they tendered him the oath of allegiance,
and committed him to prison in a very incommodious room in Lancaster castle,
where he was kept close prisoner till after the spring assizes 1665;
after that removed to Scarborough castle,
where he was detained up wards of a year longer;
when finding means to get his case laid before the king,
he soon after obtained his release,
after an arbitrary and most rigorous imprisonment of more than three years.

About a month after George Fox`'s commitment,
Margaret Fell was sent for by the same justices to Ulverstone,
and questioned about keeping meetings at her house,
at which they seemed to be much offended,
and insisted upon tendering her the oath of allegiance.
In answer, she remarked, that they knew she could not swear,
and why should they send for her, from her own house and her lawful affairs,
to ensnare her, adding "`what have I done?`"
This expostulation, upon their disingenuous procedure, made an impression on them so far,
that they told her,
if she would not keep meetings at her house they would not tender her the oath.
A plain confession that this tender was only a mere pretext
to be vexatious to the subject without real occasion,
and that it was an arbitrary measure assumed for
the mere purpose of persecution for religion,
and nothing else.
To this purpose, she magnanimously replied, She should not deny her faith and principles,
for any thing they could do against her,
and while it should please the Lord to let her have a house,
she would endeavour to worship him in it.
Upon this they tendered her the oath,
and upon her refusal committed her also to Lancaster castle;
which prison was at this time quite crowded by the
numbers of this people taken up and imprisoned there,
some for meeting together, and some for refusing to swear.
And many of them were poor men,
whose families depending on their daily labour for their subsistence,
were in danger of perishing for want, if the sympathy,
affectionate care and charity of their friends had not been exerted to prevent it.^
footnote:[[.book-title]#Besse#]

Such rigorous imprisonments as these people,
particularly George Fox and Margaret Fell were subject to, being in smoky rooms,
in such bad condition, that the rain came in upon them in abundance,
was more than sufficient punishment for petty criminals;
and an evidence of the unfeeling malice of their persecutors,
needlessly to expose Margaret Fell in particular to such hardship, a woman of estate,
the widow of a judge, and a man of consequence in the country,
who had been used to comfortable accommodations in her own house,
and was every way on a level with her persecutors,
except the possession and abuse of power.
But all the hard ships she suffered,
in being arbitrarily forced from her house and family, without cause or crimination,
and hurried to this dismal jail,
was not a sufficient gratification of the groundless enmity of these magistrates,
till they went the farthest length they could go, by prosecuting her to a premunire,
realizing the proverb, Summum jus, summa injuria;
the execution of perverted law is accumulated injury.
The account of the further proceedings against her and George Fox is postponed,
as their trials were put off, and they continued prisoners till next year.

About the same time Francis Howgill met with treatment equally
severe and unjust from one the justices of Westmoreland;
and it is probable, under pretext of the same plot, and in execution of the plan,
adopted amongst these Northern justices of taking up the speakers among the Quakers,
although they had no legal cause against them.

This very respectable member of civil and religious society,
being in the market-place at Kendal upon his lawful occasions,
was summoned by the high constable to appear before the justices then sitting at a tavern:
Whither when he came they tendered him the oath of allegiance,
and because his conscientious scruple to violate a divine command,
obliged him to decline compliance,
they immediately committed him to prison till the
summer assizes to be held in the next month in Appleby:
being brought thither, the oath was again tendered to him, and upon refusal,
an indictment was drawn up against him, which he traversing,
had liberty till next assizes to answer thereto.
Being required to enter into bond for his good behaviour, he refused,
as apprehending therein,
not only a tacit acquiescence in the implication of ill-behaviour,
which he was not chargeable with,
but also perceiving a snare therein to entangle him
further in the perplexities of the law,
because he thought his attendance of meetings,
which the persuasion of duty would not suffer him to neglect, while at liberty,
would by them be interpreted as a breach of his engagement; upon these considerations,
declining to enter into bonds, he was recommitted to prison;
from whence he was not released,
till it pleased divine providence by his death to
remove him beyond the reach of unmerciful men;
of his subsequent trials we propose to exhibit a narration in due course.

The succeeding years affording variety of matter,
this seems a proper period to bring forward the history of this people in other parts.
