== Chapter IX. New England.

[.chapter-synopsis]
* Persecution continued in New England
* Grievous Sufferings of Alice Ambrose, Mary Tomkins and Anne Coleman
* Whipped through three Towns
* Violently abused by two Constables
* Elizabeth Hooton obtains a Licence from the King to settle in any of the Plantations
* With which she returns to Boston, where no regard is paid to the Licence
* At Dover she is set in the Stocks
* Imprisoned at Cambridge
* Whipped through three Towns, and turned into the Wilderness
* Returning into Cambridge, to fetch her Clothes, is again whipped, together with her Daughter and Sarah Coleman
* She is a second Time whipped through three Towns, and turned into the Wilderness
* Whipped again at Boston, and sent away to Rhode Island, with a Warrant to whip her from Town to Town
* Edward Wharton repeatedly whipped in like Manner

Though the government of New England was restrained from putting the Quakers to death,
and granted them liberty for a while, it lasted not long:^
footnote:[Neale winds up his account of these persecutions in New England,
in the like palliative strain we have noticed in many parts of his narration.
"`The court,`" says he,
"`began to be sensible that the putting men to death for their
religious principles was odious in the eye of the world;
that in the case of the Quakers it did not answer their ends,
for the more they persecuted, the more bloody work they had on their hands;
and therefore they resolved for the future,
only to whip them at the cart`'s tail as vagabonds, through all the towns,
out of their jurisdiction.`"
Then after reciting the king`'s mandamus, he adds,
"`This put an effectual stop to the sufferings of the Quakers on account of their principles:
some of them indeed have been punished since as vagabonds
and criminals against the state,
but none that I know of,
purely for their sentiments in religion.`"
{footnote-paragraph-split}
Upon comparing
this account with the present narrative of this and the following cases,
as recorded by George Bishop and others,
it will appear to be no evidence of the author`'s impartiality, or strict regard to truth;
for that this mandamus put an effectual stop to the sufferings of the Quakers,
on account of their principles, is not true,
since their sufferings were continued several years after,
and for their religious principles only;
and what were his humane feelings to term the barbarous usage these poor people met
with ONLY "`whipping them as vagabonds through all the towns out of their jurisdiction.`"
The order to whip three render women through eleven towns was barbarous beyond parallel,
and well nigh equal to capital punishment, and their subsequent abuse by the Roberts`'s,
such as no civilized government would suffer to be given even to vagabonds.
And as to their being punished, not for religion,
but as vagabonds and criminals against the state,
// lint-disable no-undefined
it was easy for malice to give hard names of undefined meaning;
but if to create a criminal appellation were sufficient
grounds to punish the person upon whom it was fixed,
as a real criminal, then, if they had thought proper to call them thieves and felons,
must they be punished as such, because enmity miscalled them so.
It admits of no dispute that they were still punished not simply as vagabonds,
but really as Quakers,
and that they were thus unmercifully whipped and abused for no other cause,
than that for which their friends had been put to death: If the three women above,
by any forced or false construction of the world could be termed vagabonds,
yet how could Elizabeth Hooton be a vagabond,
who came with the king`'s licence to purchase an habitation in the country,
and had substance to purchase it?
Is every one that removes to a new residence a vagabond?
Or was Edward Wharton (a residentiary inhabitant
of Salem) when he came to Boston on lawful business,
a vagabond?
Then every man may be so termed, who doth not confine himself entirely at home,
and make his own house his prison:
Yet we see with what severity they were both treated by cruel whippings frequently repeated.
In their circumstances no man, nay, not even these men,
would ever have thought of terming them vagabonds, only that they were Quakers,
so called.
As to the insinuated charge of their being criminals against the state,
from all that I have heard or read, I am under no hesitation totally to deny the charge,
as a groundless calumny, supported by no matter of fact.
It is evident that it was purely for their sentiments in religion, and nothing else,
that their punishment was continued.
Their testimony against all religion without righteousness touched the demure,
but persecuting priests and magistrates to the quick, and roused them to vengeance:
So that though their hands were tied up from hanging them,
they persisted in punishing them as far as they durst, with unabated malice and cruelty.]
The disposition of the magistrates was still the same;
they returned again to their persecuting measures,
and indulged their propensity to cruelty in the punishment of this people,
male and female, with the utmost severity in their power.

In the year 1662, Mary Tomkins,
Alice Ambrose and Anne Coleman came under a religious
concern to visit their friends about Piscataqua river,
and to confirm them in the truth: They had not been long there before one Rayner,
a priest of Dover, excited the magistrates to persecute them:
He brought them before one Walden, a deputy magistrate,
who telling them of the law they had to punish them, Mary Tomkins answered,
"`So there was a law that Daniel should not pray to his God.`"
He replied, "`Yes, and Daniel suffered, and so shall you.`"^
footnote:[[.book-title]#Besse#]
Also when Alice Ambrose said, her name was written in the Lamb`'s book of life,
he answered, "`Nobody here knows that book, and for this you shall suffer.`"
On this occasion the priest supplying the place of a clerk,
formed for him the following warrant or order:

[.embedded-content-document.legal]
--

[.blurb]
=== To the Constables of Dover, Hampton, Salisbury, Newbury, Rowley, Ipswich, Wenham, Linn, Boston, Roxbury, Dedham, and until these vagabond Quakers are carried out of this jurisdiction.

You and every of you are required, in the king`'s majesty`'s name,
to take these vagabond Quakers, Anne Coleman, Mary Tomkins, and Alice Ambrose,
and make them fast to the cart`'s tail, and driving the cart through your several towns,
to whip them on their backs, not exceeding ten stripes a piece on each of them,
in each town, and so convey them from constable to constable,
till they come out of this jurisdiction, as you will answer it at your peril:
And this shall be your warrant.

[.signed-section-closing]
Per me,

[.signed-section-signature]
Richard Walden

[.signed-section-context-close]
At Dover, Dated Dec.
22nd, 1662.

--

This order was cruelly executed at Dover, while the priest stood by,
looked at it and laughed, for which cruel levity when Eliakim,
Wardel and William Fourbish reproved him the magistrate
caused them to be put in the stocks.
They were then conveyed to Hampton, and then again whipped, and also at Salisbury;
but the constable of that town, deputing a person to convey them farther, he,
moved with compassion, determined to run the hazard of breaking the law,
and set them at liberty, whereby the priest was disappointed of his aim,
which seemed to be to take away their lives,
which in all likelihood had been the case if the constables of
these eleven townships had executed the warrant with such severity
as he had excited the constable at Dover to do,
the distance from Dover to the end of the jurisdiction being about eighty miles.

After a little time they returned again to Dover,
where being met together with other friends on the first day of the week,
whilst Alice Ambrose was at prayer, two constables, Thomas Roberts and John his brother,
came into the meeting, and taking her each by an arm, inhumanly dragged her out of doors,
and then with her face towards the snow, which was knee-deep,
over stumps and old trees near a mile; when they had wearied themselves,
they commanded two others to help them: then they fetched Mary Tomkins,
and treated her in like manner: The next morning, which was excessively cold,
they forced them into a canoe, together with Anne Coleman, who in love accompanied them,
and carried them to the harbour`'s mouth,
threatening that they would now dispose of them so,
as that they would be troubled with them no more.
And because they were not willing to go,
they forced them down a very steep place in the snow,
dragging Mary Tomkins again over stumps of tree to the water side,
whereby she was much bruised and fainted under their hands:
Alice Ambrose they pulled into the water,
and kept her swimming by the canoe in great danger of drowning or being frozen to death.
They would in all probability have proceeded in their wicked design of murdering them,
had they not been prevented by a storm, which drove them back to the house,
where they had kept them all the night before.
They kept them there till near midnight, and then cruelly turned them out of doors,
in the frost and snow, although Alice Ambrose`'s clothes were frozen as hard as boards.
The barbarity exercised on these women was such,
that to all human probability they must have perished,
had not the hand of providence in a signal manner preserved them.
It did not appear these men had any legal warrant or authority to meddle with them,
but that they were animated and encouraged to this wicked abuse
of these harmless women by a ruling elder of their church,
miscalled Hate-evil Nutter.

Amongst the number released from prison along with Wenlock Christison,
were Elizabeth Hooton and Joan Brocksup, two ancient women,
each about sixty years of age, being driven with the rest into the wilderness,
and left there among wolves and bears, without necessary provisions,
they were left to wander through places uninhabited and hardly passable,
in very great danger, until at length they came to Rhode Island, thence to Barbados,
and from thence not long after returned to New England,
for to that province was their message to testify
against the spirit of persecution predominant there.
Upon their coming to Boston they were presently apprehended by a constable,
an illiberal and furious zealot, who declared, It was his delight,
and he could rejoice in following the Quakers to execution as much as ever.
They were immediately sent away to Virginia,
from whence Elizabeth Hooton went back to England.

After some time she felt the impulse of duty to return to New England;
but previously to her going, she made application to the king,
and obtained his licence to purchase for herself
an house and dwelling in any of his plantations:
Thus authorised,
she and her daughter of the same name set sail in a ship bound for Boston, where,
when they arrived, the magistrates,
who zealously kept up all the persecuting laws which they durst,
were determined to fine the master of the ship one hundred pounds,
until they were informed she had a licence from the king,
which deterred them from executing that design;
but in contempt of the king`'s licence and her solicitations,
they persisted in their resolution not to suffer her to purchase any habitation there.
Instead thereof, they let her feel the effects of their malicious disposition,
which had suffered no diminution by the restraint put upon them.
At Dover she was set in the stocks, and kept four days in prison in cold weather.
At Cambridge she was imprisoned in a close stinking dungeon,
without anything to lie down or sit on, two days and two nights without bread or water,
and when a friend in sympathy with her sufferings
brought her some milk when she was ready to perish,
he was fined five pounds and sent to prison.
She was then whipped through three towns, Cambridge, Watertown and Dedham,
with ten stripes in each, with a three-stringed whipped whip and three knots at the end,
and in this through mangled condition she was carried on
horseback in frosty weather many miles into the wilderness,
and left there among wild beasts, in the hazard of perishing there; as her persecutors,
who left her there, expressed their hopes that they should never see her more.
And in all human probability she must have perished,
had not a providential hand preserved her safe through the
dismal desert and many deep waters to a town called Rehoboth,
where she arrived the next day neither faint nor weary,
and thence made her way to Rhode Island, praising and magnifying the name of the Lord,
who had signally supported her through such grievous tortures,
as to her age and sex in all outward appearance were insupportable.

But her sufferings had not yet satiated the vindictive hatred of her persecutors.
As they would not suffer her to take her clothes
with her when they sent her away as aforesaid,
she returned to a place near Cambridge accompanied with her daughter to fetch them;
and as they together were returning with them to Rhode Island, one Thomas Daufort,
a magistrate,
made out a warrant to the constable of Charlestown to apprehend them and Sarah Coleman,
an ancient woman of Scituate, who had met them in the woods as they were going back.
They were taken back to Cambridge, abused by the scholars,
and then all three committed to the house of correction,
and whipped by order of one Daniel Goggin,^
footnote:[The temper of this magistrate may be conceived from hence.
He applied to one William Hathorne, a magistrate of like disposition with himself,
to send him some Quakers that way that he might see them slashed;
which is a clear indication that he was of that temper which could
take delight in the sufferings and torture of his fellow creatures.]
though no just cause could be assigned.
Elizabeth Hooton came at this time on the reasonable errand of reclaiming her property,
her daughter was guilty of no crime or offence but the filial
duty of waiting upon and assisting her ancient mother,
and the other accidentally fell into their company.
The magistrates, not satisfied with this,
sent the constable with an order to take them from constable to
constable toward Rhode Island to be whipped in three towns.
Returning to Boston and preaching repentance,
she was again sent to the house of correction, whipped at the whipping-post as before,
and afterwards at Roxbury and Dedham at a cart`'s tail;
thence she was again taken in a mangled condition into the wilderness,
and left there to make her way twenty miles, the weather still continuing very cold.
Soon after, returning to Boston to visit her friends, she was again cast into prison,
whipped from the prison door to the town`'s end, and then sent away to Rhode Island,
with a warrant to whip her from town to town,
threatening if ever she came thither again they would
either put her to death or brand her on the shoulder.
Thus this good old woman, who was a woman of repute and substance,
perfectly peaceable and inoffensive in her conduct;
no vagabonds no criminal against the state,
was cruelly persecuted with three imprisonments,
nine times was she tortured with severe whippings,
twice exposed to perils in the wilderness, and left to perish,
as far as in the power of these rigid and hypocritical professors of religion.
Whoever can vindicate such proceedings, I should think he either wronged his judgment,
or was as callous to the tender feelings of humanity
as the unmerciful magistrates of New England.
But in her righteous cause as her afflictions abounded,
so her inward consolations did much more abound,
under the enjoyment whereof she testified her willingness
to endure much more for the propagation of righteousness,
and the love she bore to the souls of all men.

The magistrates of this colony had suffered their
spirits to be so embittered against this society,
that the very name exposed those who bore it to punishment,
and it is to be presumed few of them escaped it in a greater or lesser degree;
but some individuals seem to be more peculiarly marked
out by them as objects of their utmost malevolence,
such we have shown were Laurence and Cassandra Southick, and their son Josiah,
such were these innocent women, whose sufferings are just remarked;
and such was Edward Wharton of Salem, whose banishment, on pain of death,
hath been before recited;
but the king`'s mandamus having prevented the persecutors
from carrying their sentence into execution,
(for as he told them, he did not depart from their jurisdiction,
but kept his habitation) they omitted no opportunity to wreak their vengeance upon him,
and make his residence there as uneasy and distressing as in their power.

Being a man of Christian courage,
in the summer of this year he went into the court at Dover,
a place where persecution had been
hotly carried on, and expressed himself in the following terms:
"`Woe to all oppressors and persecutors, for the indignation of the Lord is against them;
therefore, friends, whilst you have time prize the day of his patience,
and cease to do evil and learn to do well:
Ye who spoil the poor and devour the innocent.`"

Having said this, he was immediately apprehended,
and set in the stocks till they might consult what to do with him,
for his expressions had touched them to the quick,
and provoked their resentment against him.
The result of their consultation was,
that he should be severely punished as a vagabond Quaker,
though well known to them as a reputable inhabitant of Salem,
and about his lawful business: The clerk,
who was employed to write the order for his punishment,
was his next neighbour (and consequently as much
a vagabond as himself) as he was drawing it up,
William Hathorne^
footnote:[This Hathorne, before he was a magistrate,
appeared as a professed enemy to persecution,
for when an act was preparing to prohibit any persons from preaching
but such as should be approved by a particular set of men,
he publicly opposed it, saying, He looked upon it as a very bad act,
and a sign that the Lord had forsaken them.
How unstable and contradictory are the sentiments of men in different stations of life?
This man, after long seeking, being advanced to an office of magistracy,
became a violent persecutor of others,
for practising that Christian liberty which himself had asserted and contended for.]
called to him, and bade him write in the king`'s majesty`'s name.
Whereupon Edward Wharton made his objection, "`Friends,
you wrong the king and abuse his name,
for I believe he never gave you order so to abuse his honest subjects.`"
However the court made the following order, viz.

[.embedded-content-document.legal]
--

[.letter-heading]
To the constables of Dover, Hampton, Salisbury, Newbury, Rowley, Ipswich and Wenham.

You and every of you are required, in his majesty`'s name,
to receive into your custody Edward Wharton, a vagabond Quaker,
and convey him from town to town until he come to his habitation in Salem;
and the constables of Dover,
Hampton and Newbury are to whip him through their respective towns at a cart`'s tail,
not exceeding ten stripes in each town,
according to the law of vagabond Quakers in that behalf.
This being the sentence of a court held at Dover the 4th of July, 1663.

[.signed-section-signature]
Elias Stilman, cleric.

--

To which sentence Edward answered,
"`I fear not the worst you may be suffered to do to me,
neither do I look for favour at your hands.`"
The sentence was immediately executed at Dover,
and the executioner told him he must prepare to receive the like at the next town.
But refusing to go, except forced, he was put upon a horse`'s back,
having neither bridle nor halter, nor anything to hold by but the pommel of the saddle.
In this ignominious manner,
one leading the horse and two others guarding him on each side,
he was carried like a notorious criminal from town to town,
and whipped as the warrant directed.

Soon after this two of his friends, John Lyddal and Thomas Newhouse,^
footnote:[Thomas Newhouse was again whipped through the jurisdiction of Boston
for bearing testimony against persecution in one of their meetinghouses;
at which time having two glass bottles in his hands, he threw them down, saying,
"`So shall you be dashed to pieces.`"]
being at a meeting at Salem, were apprehended,
and by Hathorne ordered to be whipped through three towns.
Edward remonstrating against this and other proceedings of this Hathorne,
was sentenced to be whipped with fourteen lashes,
which were inflicted at the whipping-post in the said town.

About the same time Joseph Nicholson,
Jane Millard and Anne Coleman were cruelly whipped through Salem, Boston and Dedham;
the latter of whom, Anne Coleman,
it was thought would have lost her life through the extreme torture she was put to,
by the knots of the whip splitting one of the nipples of her breast;
and it was a considerable time before she recovered.

Edward Wharton went about some temporal concerns to Rhode Island, and from thence he,
with George Preston and Wenlock Christison, went to Boston,
and assembled there with others of their friends to worship God.
Rawson, the secretary, coming to the knowledge thereof,
issued his warrant to take a stranger, a preacher among the Quakers,
etc. but before the constable reached the house, the meeting was ended,
and the stranger gone.
Searching Nicholas Upshall`'s house he found Edward Wharton there,
and insisted upon his going before the governor;
but Edward demanding a sight of his warrant, and not being mentioned therein,
he asserted his right as a subject of England, and refused to go under a warrant,
in which being neither named nor described, it was in no respect a warrant against; him:
But here, the magistrates and their officers being of the same cast,
the constable dragged him by violence out of the house, and took him before the governor,
who immediately, notwithstanding he knew him very well,^
footnote:[[.book-title]#William Sewel,# p.339, writes that Endicot had been formerly in a circumstance
to acknowledge Edward Wharton`'s friendship to him,
when he supplied him with necessaries in his want, promising then,
that if ever it lay in his power he would requite him.
In what manner he made that promise good these anecdotes make manifest.
In a letter to Endicot from one John Smith, recorded by J. [.book-title]#Besse, vol. 2.# p. 209,
and said to be delivered into his own hand, I find this passage:
"`There remaineth in thee a spirit of cruelty and hard-heartedness to thy poor neighbours,
which thou hast been formerly in much beholden to, and relieved by in time of want,
when thou hadst not bread to eat.`"]
had been personally obliged to him, and knew he was an inhabitant of the colony,
a reputable tradesman in good circumstances, told him he should suffer as a vagabond.
To which Edward replied, "`I defy the life of a vagabond; that law is a wicked law,
and very wicked and unrighteous men they are that cause
those who fear the Lord to suffer by such a wicked law.`"
But this remonstrance availed not.
The governor, resolved on rigour, turned a deaf ear to his reasoning,
and reward issued his warrant for him to be whipped in their accustomed
ignominious way at a cart`'s tail through the towns of Boston and Lynn,
and thence passed to Salem, the place of his abode.
If ever the term vagabond was misapplied, as it was in respect to this people in general,
it was most certainly in this case.
A man on his way home from a remoter place, whither his lawful him,
apprehended at random in the breach of no law, not even their law;
was surely neither vagrant (in any accepted sense of the word) nor criminal; no stranger,
but well known in Boston; but he was known to be a Quaker, so called; this was his crime,
and for this he suffered, for his religion and nothing else.
When the warrant was written, Edward was told,
that if he would promise the governor to come no more to the Quakers meeting at Boston,
it was likely he would discharge him.
To which he replied, "`Not for all the world; I have a back to lend to the smiter,
and I have felt your cruel whippings before now,
and the Lord hath made me able to bear them,
and as I abide in his fear I need not fear what you shall be suffered to do unto me;
but surely the Lord will visit you for the blood of the innocent,
and your day is coming as it is come upon many,
who but as yesterday were higher than ever you were or are likely to be,
but now are made the lowest of many, and truly my soul laments for you.`"

The next day he was cruelly whipped through Boston almost a mile, and sent away to Lynn;
but the constable there considering him as a well known inhabitant of Salem,
and the warrant an illegal one, refused to execute it.

Toward the end of the next month Alice Ambrose and
Mary Tomkins being returned from Virginia,
where they had been severely treated, and the latter, being very sick near unto death,
Edward Wharton and Wenlock Christison having intelligence thereof,
came from Salem to Boston to visit their sick friend.
They were no sooner come to the house where she was, than two constables followed,
and forced them all together before the governor, although the sick woman,
through extreme weakness, fell down by the way as dead,
yet they waited over her till she recovered a little, and took her with the rest.
Wenlock and the two women were ordered to be whipped out of the jurisdiction,
but their sentence, through the intercession of Colonel Temple, was remitted.
As for Edward Wharton,
he being an acknowledged inhabitant now (although so lately
a vagabond) they resolved upon another course with him,
and thereupon informed him, that unless he would subscribe to these four propositions:
1st, To promise to come no more to any Quakers meetings in Boston.
2nd,
That when he came to Boston he should acquaint the governor and his deputy forthwith,
and of his business.
3rd, That he would take the oath of fidelity.
And 4th, To give bond for his good behaviour,
he should be tied to a great gun and severely whipped
with thirty stripes on his naked body.
A severe and arbitrary alternative;
yet this conscientious man was not long in determining his choice,
he plainly told them that he would not comply with their proposals;
whereupon Daufort drew up the following warrant, and got Endicot to sign it:

[.embedded-content-document.legal]
--

[.letter-heading]
To the constables of Boston, of Charlestown, warrant Maiden and Lynn.

You are required to take into your custody respectively Edward Wharton,
convicted of being a vagabond from his own dwelling-place;
and the constable of Boston is to whip him severely
with thirty stripes on his naked body;
and from constable to constable you are required to convey him until he comes to Salem,
the place where he saith he dwelleth: And in thus doing this shall be your warrant.
Dated at Boston the 30th of June, 1664.

[.signed-section-signature]
John Endicot.

--

Then they led him to the market place, and bound his arms to the wheels of a great gun,
and barbarously whipped him with thirty stripes,
so that it was testified that peas might lie in the holes,
which the knots of the whip had torn in his flesh;
his body was much swelled and very black from his waist upwards.
In that sad and miserable condition they led him as the warrant directed,
not the nearest way to Salem, but round about the country,
as if to expose him to the people as a spectacle,
to terrify them with the notion of their unlimited power,
and their rigorous cruelty in exercising it.

Soon after the signing this warrant Endicot was deprived of his power,
which he uniformly applied, in concert with other magistrates of similar temper,
to the punishment of those who could not square their religion by his pattern;
being seized with a loathsome disease,
which caused a nauseous putrefaction before his breath left him,
and terminated in his death.

Of his confederates some were gone before, and the rest were taken away one by one,
so that from this time persecution in New England gradually abated,
as the persecutors lost their strength,
and the eyes of the people began to be opened to see the evil of these rigorous measures,
and more generally to condemn them, the magistrates became more cautious; yet we shall,
in sundry instances,
see the vestiges of the persecuting spirit endeavouring to exert its power
for the punishment of divers of this people several years after this,
even till the Indians made destructive incursions into their jurisdiction,
which brought on a war,
and gave them more serious employment--to repel enemies
much more formidable than the Quakers so called.

Edward Wharton, however, did not find all his persecutors removed in Endicot,
for some months after, he was again cruelly whipped and imprisoned one month,
for no other cause than accompanying some of his friends to Boston,
who came thither to seek a passage to England.
Such a series of inhuman whippings and other cruel sufferings for several years together,
is scarce paralleled in history to be inflicted on any one person,
for the cause of religion and a good conscience.
