== Chapter X. DETACHED OCCURRENCES.

Travels of Catherine Evans and Sarah Cheevers into Italy.--On their Way to Alexandria
are put into Malta.--Are put into the Inquisition.--Their Sufferings there.--Released
by the intervention of Lord D`'Aubigny.--John Philly and William Moore travel into Hungary
to visit the Hortesche Brethren.--From thence to upper Hungary.--Put in Shackles.--Rifled
by the Officers.--Brought before the Inquisitor.--Repeatedly examined,
but no cause of Crimination appearing,
they are put to the torture.--William Moore`'s Account thereof
and of their successive Trials and severe Sufferings.

About this period two English women were imprisoned in the inquisition at Malta,
where they were confined above three years;
their names were Catherine Evans and Sarah Cheevers.
These women,
under a religious concern to propagate the doctrine of the
divine light in man in the darker parts of the world,
took their passage to in a ship bound from London to Leghorn, where,
through various trials and storms, they at length safely arrived, and stayed some time,
during which they used their endeavours to answer the end of their coming,
by dispersing sundry books, explaining the doctrines of this people;
and discoursing upon religion with the people who came to them,
of whom curiosity drew numbers of all ranks daily;
and in these their christian endeavours they met with no molestation here.

From hence having got a passage in a Dutch ship, with intention to go to Alexandria,
the master put into Malta, where he tarried some time.
Next day after their arrival, being the first of the week, they went ashore,
where they were met by the English consul, who enquiring the cause of their coming,
they informed him, and gave him some books,
upon which he let them know there was an inquisition there;
and Entertained kindly inviting them to his house, they accepted his invitation.
While they abode here, curiosity drew many to visit them,
whom they found it their concern to call to repentance, whereby several were affected.^
footnote:[At first having learned but little of the language spoken there,
they expressed themselves very defectively; partly in words and partly by signs,
as well as they could: But at the Consuls their language was understood,
and one of the friars who came to them in the Inquisition was an Englishman.]
They went by desire to the nunnery, to see the governor`'s sister there,
where they discoursed with the nuns, and gave them some books.
Here a priest brought them into the chapel, and wanted them to bow to the high altar;
but they refused, with abhorrence of that idolatry, and went back to the consul`'s,
where they continued about three months,
during which time they were repeatedly called before the inquisitors,
and examined by them about their religious principles;
and through the wisdom and integrity they were favoured with,
answered their interrogatories in such manner as not to give them
the advantage against them which they were seeking for,
nor give away the cause of that truth they believed in,
by the least compliance with their requisitions to
adopt their superstitious and showy religion.
The inquisitors,
not adventuring to take them out of the consul`'s house without his consent or acquiescence,
yet desirous to get them into their power,
at length prevailed upon him by their flattery, their menaces,
and (as was afterwards discovered) by bribery, to violate his duty,
and withdraw his protection so far as to suffer them
to be taken by the officers of the inquisition;
for which purpose he confined them in his own house,
though the governor had signified his willingness
that they should retain their full liberty,
as believing them to be honest women.
The con- The consul by fair carriage was desirous to conceal his insincere conduct;
but they being under a sense that measures were in contemplation to their prejudice,
and suspecting the consul to be a party therein, hinted to him their suspicions,
remarking, that Pilate would willingly do the "`Jews a pleasure,
yet wash his hands in innocency`" which remark his
consciousness of his duplicity applied home to himself,
so that he required a sign of them, if they were the messengers of God:
And they signified that this might serve for a sign, "`That it would go well with them,
but it would not go off well with him.`"

Soon after the consul informed them that they were sent for by the inquisition,
in pursuance of orders from Rome, but that he hoped they would be set free;
wherein he still dissembled,
knowing (as they afterwards discovered) that they would be detained in prison.
They were taken into custody by the officers of the inquisition,
and carried before the lord inquisitor, whose first question was,
"`Whether they had changed their minds?`"
To which they answered, "`No, and that they should not change from the truth.`"
Then he asked, "`What new light it was they talked of?`"
They replied, "`It was no new light,
but the same the prophets and apostles bore testimony to.`"
Next he asked "`How this light came to be lost since the primitive times?`"
They answered, "` It was not lost, but men did not comprehend it,
by reason of the night of apostacy which had overspread the nations.`"
Then he threatened them, if they would change their minds they should say so,
or else they would use them as they pleased; but they signified they would not change,
adding, The will of the Lord be done.
Upon this the inquisitor and consul withdrew,
and left them to the officers to conduct them to their prison,
which was a close dark room, with only two little holes for light and air,
and so extremely hot in that warm climate that it seemed as if
the intention of the inquisitor was to stifle them to death.

They were brought under examination again and again,
but no answer could be extorted from them to turn to their disadvantage;
and being still kept close prisoners, the consul,
who had been forewarned that his connivance at their
apprehension would not go off well with him,
The consul came troubled in his mind to that degree
that he came to them with tears in his eyes,
expressing his sorrow for their detention;
and he offered back what he had received for delivering them up,
but could not prevail to have them set at liberty;
and is said to have enjoyed no peace after as long as he lived, which was not very long.

To describe minutely all the sufferings and trials they patiently
endured during a cruel imprisonment for three or four years,
would lead me into too much prolixity.
They were continually beset and perplexed with the impertinences of monks and friars,
to cajole, terrify or beguile them into conformity to their superstitions;
but all their efforts were quite ineffectual.
These innocent women were too well established,
and too steadfast in that purer religion they had experienced the efficacy of,
to be perverted there from either by flattery, by menaces or by terror,
although in apparent jeopardy every day, often threatened,
and often under the dismal apprehensions of being led to the stake,
as numbers before them on the like offence had been.

But it looked as if their design was rather to get them put out of the way without noise,
than to execute them publicly.
They were therefore put into a room so exceedingly hot, close and suffocating,
that it was thought they could most not survive there long;
where moreover they were so excessively stung by gnats that their
faces were spotted and swelled as if they had been in the small-pox.
They were often forced to rise out of their bed,
to He down at the chink of the door for air to draw breath.
By the excessive heat of the room, which was intense beyond conception,
by an internal heat added to that of the climate, their skin was parched,
their hair fell off, and they frequently fainted away.
Their affliction here was too severe for humanity in its best state,
especially in tender women, to support,
so that at times they were tempted to wish for death, to put an end to their sorrows.

It was not admirable that Catharine, by this treatment, fell into a fit of sickness,
and the monks once bringing with them a physician, as they had done several times before,
telling them it was in charity, Catharine asked them,
"`Whether they did not keep them in that hot room to kill them,
and bring the physician to keep them longer alive in torment?`"
To this it was replied, "`It was better to keep them there than to kill them.`"
They wrote to the inquisitor, pleading their innocency,
and complaining of the hardships they sustained, adding,
"`if it was their blood they thirsted after,
they might as well take away their lives some other way as smother them there.`"
This remonstrance he took so ill, that he ordered their ink horns to be taken away.
They asked, "`Why their goods were taken away?`"
and were answered, "`All is ours, and your lives too if we will.`"
He ordered them also to be separated; but when they came to part them,
Catharine`'s disorder had broke out in one continued eruption from head to foot,
whereupon the doctor was sent for, who said, "`They must have air,
or else they would die.`"
This being reported to the inquisitor,
he ordered the door to be set open six hours in the day.

Soon after they were separated, in hopes to make more impression upon them,
by attacking them separately with their artful wiles or dreadful menaces,
in order to bring them to submit to their requisition;
but their assailants were greatly disappointed,
for they found them afterwards as immoveable as before,
being strengthened separately as well as jointly to resist all their attempts.

As a specimen of their manner of making converts,
I shall transcribe one of their dialogues out of many.
One time a friar came to Catharine, and told her,
If she would be a catholic she should say so, otherwise they would use badly,
and she should never see the face of Sarah again, but she should die by herself,
and a thousand devils should carry her soul to hell.
She asked him, If he was the messenger of God to her?
and he said, Yes: Why, what is my sin, or wherein have I provoked the Lord,
that he should send me such a message?
It is, replied he, because you will not be a catholic: Whereupon she said,
I deny thee and thy message too, and the spirit which speaks in thee,
for the Lord never spoke so.
He, growing angry, threatened to lay her in a whole pile of chains,
where she should see neither sun or moon.
Signifying her resignation and trust in divine protection, she said,
he could not separate her from the love of God in Christ Jesus, lay her where he would.
Threatening to give her to the devil, she told him, she did not fear him, for the Lord,
said she, is my keeper; the Lord is at my right hand,
and the worst you can do is to kill the body;
you can touch my life no more than the devil could Job`'s. At this, quite enraged,
he told her, she should never go out of that room alive;
to which she undauntedly replied, The Lord is sufficient to deliver me;
but whether he will or no,
I will not forsake the living fountain to drink at a broken cistern;
and you have no law to keep us here, but such a law as Ahab had for Naboth`'s vineyard.
At this the monk ran off in a rage, and pulling the door, said, Abide there,
member of the devil: To which she said, The devil`'s members do the devil`'s works,
and the plagues of the Lord will be upon them for it.

The house of the inquisition being rebuilding or repairing
in some parts for the space of a year and a half,
furnished them with frequent opportunities, even here,
to incite the people to repentance and to an attendance to the light of Christ in them,
that thereby they might be preserved from evil, not only among the workmen,
who were well affected and obliging to them,
but often with the citizens of better quality who came to view the building.

Sometimes they spoke so effectually to those who came to
see them that they could not gain say the truths they declared,
but were made to confess that God was with them.
And Catharine`'s prison being so near the street that
she could be heard of those that passed by,
she frequently found it her duty,
particularly as they passed to and from the place of worship hard by,
to call them to repentance, and to turn them to the light,
which would lead them from all sinful ways and worships
to serve God in spirit and in truth,
which seemed to have a considerable effect on many,
who would stay to hear as long as they durst, for they were narrowly watched,
and the consequence of their stopping might have been imprisonment at least.
Others, greatly offended, applied to the inquisitor to have them chained,
or punished some other way; and many of the lower order, embittered by the priests,
manifested great malice in their words and actions.

Thus they not only withstood all the efforts of the
monks to beguile them from their faith,
but bore open testimony to the truth they believed in,
and against the superstition and idolatry of the religion established there;
endeavouring, by a faithful discharge of duty,
to keep a conscience void of offence to God as well as man;
and they were supported in resignation to the divine will,
in the midst of surrounding dangers, and in humble confidence in divine preservation,
whereby at last they experienced deliverance.
For which sundry intercessions were made to the inquisitor,
both by their friends and others.
One Francis Stuart, of London, a master of a ship, in company with an Irish friar,
coming to that city, and engaging the assistance of the new consul,
exerted themselves greatly,
and made great interest to get them released by application to the chief magistrate,
to the inquisitor, to the magistrates and friars;
and obtained the consent of all or most of them to their release, except the inquisitor,
who told them, He could not set them free without an order from the pope.
These men were however admitted to see and speak with them (a privilege
rarely granted) the master with tears informed them of the ineffectual
pains he had taken to procure their liberty;
"`It is this inquisitor,`" said he, "`that prevents it;
you have preached to this people.`"
To which they replied, "`That it was to preserve the testimony of a good conscience;
and the truth they had borne witness to amongst them, they should stand to maintain,
even with their blood,`"

The next effort for their liberty was made by Daniel Baker, one of the same profession;
who, under a concern for propagating true religion, in company with John Stubbs,
Henry fell, and Richard Scostrop, had travelled to Leghorn,
whence Stubbs and Fell took their departure for Alexandria;
and Baker and Scostrop for Smyrna and Constantinople,
they preaching everywhere the light of Christ, and exhorting all to obedience thereto,
as the means whereby they might experience salvation from sin,
and a real conversion of their souls to God.
This doctrine, delivered in meekness, and accompanied by inoffensive deportment,
was received with contempt and indignation, more by the professors of Christianity,
than the Turks, Jews and Greeks.
When they arrived at Smyrna, they were sent back by the English consul to Zant,
where Richard Scostrop died.
Daniel Baker got passage from thence to Venice, and so to Leghorn,
and at length to Malta, to visit the aforesaid women,
with whose sufferings he had real sympathy, being engaged in the same cause.
He obtained ac cess to the inquisitor, and addressed him in Italian, thus,
"`I am come to demand the just liberty of my friends,
the two English women in prison in the inquisition.`"
The inquisitor asked, whether he was related to them as an husband or kinsman?
And whether he came out of England on purpose to make this application?
He answered, that he came from Leghorn for that purpose.
The inquisitor told him, they should lie in prison till they died,
except some English merchants, or others of sufficient ability,
would give an obligation of three or four thousand
dollars that they should never return thither.

He repeated his solicitations, but could obtain no other answer.
During his stay of twenty-four days on the island, he frequently visited the prisoners,
at the hazard of his life; administering to their necessities,
and received several letters from them to take over to their friends in England;
and although he was daily threatened with the inquisition,
and their officers watched him narrowly, yet through the favour of divine Providence,
he was preserved out of their hands, and returned safe to England,
where he was soon after taken with others from the meeting at Bull and Mouth,
in the 5th month (July) 1662;
and after being detained for some hours for a gazing-stock to the people in Paul`'s yard,
was taken in the evening before alderman Brown, who ordered his attendants to smite him,
which they did; and pulling him four or five times to the ground,
beat him with their fists, and wrung his neck to gratify the ill temper of their master;
who when he was satisfied with abusing him and his companions, committed them to Newgate:
It was not without reason that Daniel Baker,
reflecting on the treatment he had met with abroad,
told him that Turks and Pagans would be ashamed of such brutish actions.

At last,
after these women had endured the severities of their imprisonment
in the inquisition upwards of three years,
George Fox and Gilbert Latey understanding that the
lord D`'Aubigny could procure their liberty,
applied to him for his friendly interposition,
by writing to the magistrates there in their favour;
which with a laudable humanity he readily promised to do,
and his mediation was so successful as to obtain their release in the following manner.

The lord inquisitor with the chancellor and others came to the prison, and asked them,
When they would return to England to their husbands accordingly and children?
They replied, "`It was their intent, in the will of God so to do.`"
Whereupon they were released, and the inquisitor courteously took his leave of them,
wishing them a prosperous journey to their own country, as did the other officers,
without making any demand of fees for their attendance.
Being thus restored to liberty,
they kneeled down and prayed unto God not to lay
to their charge the evil they had done unto them.
And then they were delivered into the consul`'s hands:
After about eleven weeks residence at his house,
the Sapphire frigate coming to the island took them in,
together with some knights of Malta, one of whom was the inquisitor`'s brother,
who often interested himself with the captain in their favour,
requesting they might want no accommodation the ship afforded.
From Malta they came to Leghorn,
where the merchants treated them with remarkable kindness,
sending them wine and other things for their refreshment.
From hence they passed to Tangier, at that time and besieged by the Moors,
notwithstanding which they went into the town,
and got many opportunities of exhorting the people to an amendment of their lives,
as they flocked greatly to the house where they lodged:
They paid a visit to the governor, who received them courteously,
took their admonition in good part, and signified his purpose to follow their counsel.
He would have given them money, which they were not free to accept,
but gratefully acknowledged his kindness.
From Tangier they went aboard another ship for England, where, after some storms,
they arrived in safety, rejoicing in the Lord,
and magnifying his mercy manifested in their wonderful deliverance.

For some time previous to their discharge their tried integrity and blameless demeanour
had made an impression on both the magistrates and inquisitor in their favour,
so that the latter relaxed in his severity,
and seemed inclined to give them their liberty;
but the friars exerted their endeavours against it.
However, he ordered that they should be supplied again with pens,
ink and paper to write to their friends.
After this they wrote several letters and papers during their confinement.

Severe as the sufferings of the aforesaid women in the inquisition were,
they fell short of those of two men friends, John Philly and William Moore,
who being with other friends in Germany in the beginning of the year 1662,
felt a concern on their minds to proceed farther into Hungary,
on a visit to the Hortesche brethren, who were a kind of Baptists living in a community,
and in imitation of the primitive christians,
having their goods and possessions in common: they also refused to swear or fight,
and dwelt by hundreds of them together in a family.
To encounter the perils of so long a journey, through a tract of country unknown to them,
and where they were unknown, amongst people far differing from them in language,
in sentiments and in manners, was a discouragement,
which nothing could surmount but a firm persuasion of duty,
and in consequence a reliance on divine protection in the way there of.
By the information they had previously obtained, and further directions on the way,
they made a prosperous journey to the nearest body of this people residing near Cushart,
about a day`'s journey from Presburgh,
where they were pretty hospitably entertained by some of them.
They here dispersed some religious books, which they had taken with them for that purpose.
They had afterwards some favourable opportunities
of exercising their gospel labours amongst them,
wherein they endeavoured to promote and advance their
growth and experience in pure Christianity.

After they found themselves clear of their service there,
they inquired after other families of their brethren, and were informed of one,
three hundred miles farther at a city called Pattock, in upper Hungary;
at the same time they were dissuaded by these people from going so far,
but rather stay and visit the families thereabouts.
With this proposal, although William was easy to comply,
yet his companion thinking it his duty to go forward, he had not freedom to leave him,
as John did not understand the language, which he had some knowledge of.

They therefore continued their journey in company to Presburg,
and forward towards Comora,
and on the way finding a boat going with meal to the garrison at Newhausel,
which was on the way to Pattock, they endeavoured to get a passage in it.
The boatmen asking whether they had any acquaintance there, and whether they had a pass?
and being answered in the negative, they told them it would be dangerous going thither,
and also to travel farther in these parts, being tributary to the Turks;
that they would be encompassed with danger on all hands;
in danger of being killed by the country men or Turks;
and in equal danger if they went to Newhausel,
as at that garrison they usually put those to death who
were found on the tributary ground without permission.
John Philly notwithstanding being desirous to proceed,
they went on till they came near Comora, and lodged at an Hungarian`'s;
but not being able to understand one another, they sent for a student from the college,
with whom William conversed a little in Latin.
The student inquiring concerning their country, and the purpose of their journey,
William told him they came from Great Britain, and were desirous to go to Pattock.
Afterwards they entered into discourse about religion, and in conclusion the student,
taking his leave, wished them well, though his sentiments, he said,
differed vastly from theirs.

Comora is in Schut, an island in the Danube,
which river they must therefore cross to get to it;
they made signs to a countryman to put them over, by holding out money to him,
being ignorant of the risk they would run.
He was accordingly getting his boat ready, when a Dutchwoman,
coming up called out to him, What are you about?
and told these strangers the governor would presently cause him to be hanged,
if he took them over.
So they returned to their lodging.
Here William having heard there were many Dutch people on the south side of the town,
went over the next day, and without apprehension of the consequence,
took over some books, in order to seek an opportunity to convey them to Pattock.
Meeting a soldier, and having one of the books in his hand, the soldier,
looking at the title, told him of a certain place in the neighbourhood,
which was in Turkey, whither, if he went, he might have good days there;
to whom William signified his purpose to return back, and proceeded to the water side,
in order to rejoin his companion whom he had left behind.
Here the aforesaid soldier came up to him, and told him, he must come to the captain,
before whom appearing accordingly, he asked for the book, and looking into it,
asked William if he was a Quaker?
to which he answered, Yea.
The captain, in a passion, said, These rogues show no respect,
and that he was a young Hus come to seduce the people, and make uproars.
He then caused him to be stripped and searched, and took away his money from him:
And William giving him to understand he would not like such treatment himself,
he told him, When you get clear you shall have your money;
but that is not like to be the case.
Being sent to the guard, and shackled hands and feet, they endeavoured to terrify him,
by insinuating as if he should be roasted on a wooden spit, as some had been,
who had but just gone to the next village without their order.
He endeavoured to compose himself in resignation to the divine disposal,
expecting little less than immediate death.
He was desirous to convey intelligence to his companion of his situation,
and told some of the soldiers he had a companion in the inn on the other side,
who would wonder what was become of him, if he did not hear.
On this intelligence they went over and apprehended him in his lodgings,
though unconcerned in the crime they imputed to William,
which was his going over into the garrison.
They were committed to separate prisons, William to the Stockhouse,
and John to the room appropriated to the inhuman
purpose of putting the prisoners to the rack,
where he had only the prospect of the implements of torture before him.
After the officers had rifled their persons and port-manteau,
and stripped them of what they pleased,
they were not ashamed to use both threatenings and mean
artifices to discover if they had any money left,
and to extort it from them.

The day following they were brought before the inquisitor to be examined by him,
who demanded of them, Whence they were?
Whither they intended?
Who was the author of their coming forth?
What money they had taken up?
William was farther examined concerning the books, and told it was a capital crime,
and would cost him his life; to which he signified,
What he had done therein he had done in simplicity.
To the next question, Who had spoken to them in their lodging?
he answered, A student.
This student being accordingly sent for, and examined,
his information was taken down in writing;
but it doth not appear that any cause of crimination could be drawn therefrom,
as to their pretended crime of coming as spies, or with treacherous intention,
to the garrison.
At a future examination, the inquisitor had the student`'s information in his hand,
but would not read it openly;
for the proceedings of these courts have been long marked
with infamy in all countries where they are not established,
for their iniquitous mysteriousness,
in concealing from the unhappy prisoner every information
or accusation they have against him,
and proceeding by torture to extort a confession to their purpose,
whether they have or have not any grounds of crimination.
This was the wretched case of these men.
When nothing as to their pretended crime could be made out,
the inquisitor told them the books were enough, though there were nothing else;
and then asked whether they did not know that Catholics
had laws to burn and torment Heretics,
and such as carried such books?
to which William warily replied,
I should not have expected such dealings among good christians.

The inquisitor opening a book, real or pretended, of their corrupt laws,
read or appeared to read therein,
that persons who carry such books and papers are to be put to the rack.
They were repeatedly brought to examination in the first eight days after their apprehension,
and sundry ensnaring questions put to them, as what they thought of the sacrament;
to which William replied, the flesh profiteth little, it is the spirit that quickeneth.
This inquisitor was so strangely unacquainted with the scriptures,
that in a surprise he applied to a priest present, Sir, father, how is that?
who recollecting himself said, he did remember such an expression.
The inquisitor next asked him if he would turn catholic?
to which he made this rational reply, "`If I should do so for fear or favour of you,
the Lord not requiring it of me, I should not have peace in my conscience,
and the displeasure of the Lord would be more intolerable
than yours;`" adding that compulsion might make hypocrites,
but not christians, as it did not change the heart.

Being thus sifted and tempted till the eighth day,
without the discovery of any crime from their own confession,
or the information of others, their persecutors proceeded to their usual resource,
to extort the confession they wanted by torture.
Of this the sufferer, William Moore, gives the following account,
in a letter to William Caton, written soon after his release.

"`Notwithstanding our innocence, the governor would have us racked, which seemed to me,
according to relation, a cruel torment;
and in those days I often poured out my supplications to the Lord with tears.
They made ready the benches, lighted the candles, put John out of his room,
and sent for me, the inquisitor sitting there and two more officers,
and the marshal and executioner by them.
The inquisitor, addressing himself to me, said, William,
that you may not think we deal with you as tyrants,
we will inform you that you may tell what you know in time,
for if you be racked you will be a miserable man,
and must have your head cut off besides.
But I told them I had done no evil that I knew of, nor had any in my heart against them.
Then he read a few lines to this purpose, we Leopold, Emperor,
etc. having understood of two impeached persons, John Philly and William Moore,
found by our frontier garrisons, our desire is they should be racked,
to know their intent.
And then the executioner, by their order, put an iron screw hard upon my thumbs,
and bade me tell out.
Then he slackened them and screwed them harder again;
but their aim not being gained thereby, he was commanded to proceed farther;
upon which he tied a small cord about my wrists behind my back,
and another cord about my ankles, with a battle of wood between my feet,
and forced my body quite from the ladder; and at the first pull,
my left arm being dislocated, gave a loud crack,
then he was ordered to put it in joint again.
So he slackened: And then they told me, they had three things especially,
which they wanted to be informed in,
1st. Why I asked the student if one should come to them,
and say he intended to buy somewhat of them, if they would kill him?
Secondly, Why we had desired to be set over the water, and who was the author?
Thirdly, Why I had written down some of the names of the garrisons and other places,
notwithstanding I had them in the maps?

He further endeavoured to force me to tell whether John Philly was a gunner, an engineer,
or a minister?
Now this suspicion of his being a minister was put into their heads by an Irishman,
who had an irreconcileable hatred or malice against Englishmen,
as I afterwards from his own mouth plainly understood; but I answered and kept to this,
that he was an husbandman and a maltman, and I knew him not till he came to Amsterdam.
He asked me, if I had a mind to go to the Turks, and be one?
I said I had rather die than be one.
In the mean time I was so racked, that my chin was close to my breast,
and my mouth so closed that I was almost choked, and could not well speak any longer;
and I should not wish any to experience the painful torture I endured;
and when they slackened, it was sometimes almost as painful as the pulling,
and yet still they would be questioning me.
Then I asked where is your christian charity?
do ye now as ye would that others should do unto you?
And I cried the louder that the people without might hear,
and bear witness what they were doing to me, for the door was shut and guarded?
but something they would force out of me;
and I told them that by such means they might force men to tell more than they knew,
to be out of their pain, as many had done.
Finally, I told them, it was for love to our religion we were come to those places.
Then they left off, as thinking there was crime enough.
Yet still the inquisitor threatened I should be racked again on the third day.`"

Then they fetched John, who not seeing me,
thought I had been hanged on the private gallows they had there, and put out of the way;
but he was given up, being confident in the Lord, who had fealed to him, he said,
that his life should be given to him for a prey before he came forth;
his thumbs were screwed, and he was drawn up the ladder twice, but cried out innocent;
and they asking the interpreter, what that was?
they seemed smitten in their consciences, and left off; and when all was done,
and they could find no contradiction, they invented a lie.
The marshal came to me, and told me John had said, I had no money by me,
but what I had was his; and bid me tell how it was; which I knew to be false:
thus they sought occasion to torment us the more; but we kept to truth,
and their expectation failed them.

After all, they told me there would be twenty or thirty men or note,
out or the quarters round about, appointed to hold a court of justice upon us,
and to determine what deaths we should die, and to make new laws for our sake;
but in the mean time the inquisitor came,
and would have me write down some of the heads of my religion, which I did,
at some of which he raged very much.

John Philly being suspicious that the inquisitor and priests,
plotting to take away their lives,
might give a false representation of their confession on the rack
called out to the governor as he was passing in his coach,
and upon sending to know his business, he informed him of the questions put to them,
and their answers, which being true, there was not the least contradiction found therein.
He afterwards wrote to him more fully, but the inquisitor, conscious of his evil dealing,
intercepted the letter, and endeavoured to conceal it from the governor,
which John understanding, took another opportunity to call to the governor,
and informed him thereof, who ordered the inquisitor to give it to William to translate,
which he did; soon after the inquisitor came to them,
and informed them he was sent by the governor to let them
know they might go forth to fill some earth in a wheelbarrow,
whereby they might earn two-pence a row a day to buy bread; for, continued he,
that which remains in my hands of your money is little for my pains,
and the marshal and the executioner must have some for theirs.
This offer they willingly accepted, both for the sake of fresh air,
and in hopes that their sufferings, being in open view, might move some compassion,
there being many Lutherans and Calvinists there, who commiserated their condition,
but durst not venture to visit or converse with them in the castle.
Yet sometimes the marshal would not let them go out, and often kept back their wages.

They both wrote again to the governor, in acknowledgment of his moderation,
in preventing the desire of some of their adversaries,
who wanted to proceed to greater severities.
The inquisitor again intercepted their letters; but the governor,
coming to the knowledge thereof, obliged him to give them up,
and soon after their chains were taken off.

After they had been detained here about sixteen weeks, they were conveyed in chains,
by waggon, under a guard to general Nadasti,
who was addressed under the titles of _Judex Curiae Hungariae,_
the Emperor`'s active privy counsellor and lord chamberlain.
The next morning they were brought before him and sundry lords of that kingdom,
by whom they were examined; and although some of them seemed affected with their answers,
and none objected thereto, they passed sentence upon them, that they should be burned,
if they would not be instructed in and embrace the popish religion,
for that their laws tolerated only three religions, their own,
the Lutherans and the Calvinists; and whosoever brought a new religion,
by their laws was to be burned.
Upon receiving this sentence they were sent away.
Under this dismal sentence John was supported, and encouraged his companion,
by a full persuasion of mind,
that the power of the Lord would divide them in their council,
which proved to be the case, as they afterwards understood by an Irish priest,
who was sent to demand an account of their religion in writing,
which they gave him in English, and William having translated it,
gave into Nadasti`'s own hands.

A priest was sent to convert them,
but his endeavours and those of others being ineffectual,
Nadasti sent them to a place within about five German miles of Vienna,
where falling into the hands of the priests, their perils became aggravated.
They were here again searched, their books and papers taken away.
They were threatened with the execution of the sentence passed upon them;
that they could give them a specimen of their strong arguments for convincing heretics,
such as burning under the arms, putting hot irons or copper-plates upon their breasts,
and other methods of torture.
They brought them into their churches (so called) to make
them take off their hats and bow to their images.
They set others to ensnare them, in their words, and strove to do it themselves,
that they might get some occasion to take away their lives.
But their menaces,
and pious frauds (as they have been termed) were frustrated by
the steadfastness of these men to the truth they believed in:
They therefore put manacles on their wrists, so small, as, when locked by main force,
put them to extreme torture, so that they could not help crying out.
This seemed to give much joy to these obdurate ecclesiastics.
Then they were thrust in to a narrow hole with some Turks, that were prisoners,
where they had scarce room to sit down.
Here they were again threatened to be sent back to Hungary to be burned.
One of the priests, being desired to treat them as men and christians,
to allow them a little straw to lie on, and not to use them worse than the Turks,
replied, we prefer them before you.
About the same time they offered them drink, urging them greatly to take it,
which they suspecting to be poison refused; upon this one of the priests said,
suspectum est.
Amongst these priests they had a very uneasy time, being, in addition to their cruelty,
almost continually assaulted by their snares, their taunts or their menaces.
As William under great discouragement was sitting and musing upon their situation,
he said within himself, Lord help us! what will be the end of this?
Will they have power to murder us here, where few may know of it?
(for there were no Lutherans and Calvinists here as at Presburg and Comora
to be witnesses of their treatment:) In this musing state,
he seemed as if he slept,
and on a sudden to his imagination appeared a man all clothed in white,
sitting on a milk-white horse riding in haste towards him,
like one hastening to his rescue; whereby his faith was strengthened,
imagining it was of divine appointment for his encouragement,
lest he should be too much cast down.
The very same day a message came from the Earl,^
footnote:[Who this Earl was, we have no further account in William Moore`'s letter,
from which this narrative is extracted;
but I conjecture he was a person vested with the principal civil authority in this place.]
signifying his displeasure at their proceedings.

There was one Adam Bien, the Earl`'s barber,
who had been educated amongst the Hortesche brethren aforementioned,
and being favoured in his youth with an enlightened
understanding in the nature of true religion,
had been engaged with good to express his dissatisfaction with
the darkness and deadness of the forms of those brethren.
The Earl giving him some account of these prisoners,
and showing him some papers he had received from John Philly,
his religious feelings were thereby revived,
and a strong desire raised in his mind to get an opportunity of conversation with them,
which through his interest with the Earl it was not difficult for him to attain.
By their discourse he was reached and in a good degree
convinced of the truth of their doctrine,
and while they stayed there became a steadfast and very serviceable friend to them.
He told them,
he had it from the Earl that he imagined the priests must have been drunk
when they gave the ill treatment which had displeased him;
they in return informed him, they were so both with rage and wine.
The Earl`'s reproof had such effect as to stop for a season that current of abuse,
that in various channels had hitherto run violently to bear them down:
the streams began to turn, and some of those,
who had distinguished themselves in promoting every
cruel and malicious insult for the season,
were endeavouring to ingratiate themselves with them by flattery,
to wipe off the remembrance of their preceding treatment.
The priests also were restrained from keeping them any longer in their hole of a prison,
and using them with the cruelty they had done before,
which was to them a great mortification.

They seemed now to have a comfortable prospect of obtaining their liberty,
having obtained their certificates of their character from their friends in Holland,
with the King`'s proclamation for setting their friends at home at liberty,
which were of service: but a priest exerted his utmost efforts to prevent it,
by infusing prejudices into the Earl`'s ear,
and influencing him with a bad opinion of them.
And this Earl going to Vienna was there confined by an heavy indisposition,
by which means they were disappointed, for the present, in their hopes of liberty.

Of the spirit of the religion of these ecclesiastics we have several instances.
About this time there came to them a spiritual Lord, (so called) an Englishman,
from Vienna, who asked, if they were come to plant their religion?
adding, Sects have occasioned much mischief in England, but now they will be rooted out.
John remarked to him, the love of God can reconcile them: A pox take that love, said he,
with other unsavory expressions, very unbecoming his character of spiritual,
manifesting him not only carnal but profane.
Another time there came one, who was called Brother Valentine,
and speaking with them concerning the Bible,
said it had brought many thousands into hell.
And reading a paper of John`'s, which he bad written to the Earl and council,
showing that he was an Englishman,
and forasmuch as there was no discord between England and the Empire,
he could not conceive why an Englishman coming thither
to visit a particular class of people,
and spend his money among them, should be used with the cruelty they had been:
upon reading which this Valentine gave vent to the virulence
of his spirit in the following uncharitable expression,
That they ought to be beheaded, for if that had been done to Luther at first,
there had not been so many Lutherans or heretics at this day.
This man`'s bitterness, no less than the other`'s profanity,
discovers a temper very different from the spirit of the gospel, which is pure,
peaceable, gentle, easy to be entreated, full of mercy and of good fruits:
wherefore they took a very absurd method of recommending
their religion to the adoption of the prisoners,
who were better informed of the nature of true religion,
than not clearly to perceive theirs, which allowed these liberties was not so;
and sensible enough to discern,
that although priestcraft might apply to such methods of support,
Christianity abhorred them, as destructive of its essence.

In the mean time Adam Bien had requested, unknown to the prisoners,
liberty for them to reside in his house, during the extremity of the winter;
as their present prison, the guard-room, was very cold, the doors being open all day,
and much of the night, and from the confidence he had in their integrity,
proffered his own person in their stead, if they should make their escape;
but they were not free to add the burden of supporting them to
the obligations they were under for his former acts of kindness,
and therefore chose to stay in the prison appointed for them:
yet they got liberty at times to go to his house,
where they sometimes met with some of the brethren,
and had religious opportunities with them.

But their sufferings were not yet at an end; both the priests and soldiers,
though partly restrained by the awe they were in of Adam,
on account of his intimacy with the Earl,
continued at all secure opportunities they could get to be vexatious to them,
and sought in various ways to ensnare them.
Finally,
they seem by their insinuations to have prevailed upon the Earl
to connive at least at a plot which was laid to separate them,
by carrying William Moore off privately, probably, because,
having some knowledge of the High-Dutch language and Latin,
they might look upon him as the best qualified and most likely to promulgate their doctrines.
For this purpose he was called out clandestine by
one of the men employed to carry him off,
who gave him two glass bottles, under pretence of going with him to fetch some wine;
and when he had drawn him out of the town into the fields,
whither came some sleds (the country being so deeply covered with snow,
that waggons could not travel) being armed with a cudgel,
he forced him on to one of them, and was presently joined by a soldier,
whom William knew to be a desperate sort of a man,
having been much threatened by him before.
Upon his coming, William was sensible mischief was intended him,
and fearing lest they should, under the pretence of his being run away,
vent their vengeance on his companion and Adam too,
to whom they bore a grudge for his kindness to them,
he resolved to endeavour to get back; but was prevented by the wicked attendants,
who beat and abused him greatly, threw him down on the snow, tied him hands and feet,
bound him on the fled, with his face to the hay, and carried him off;
so that he was under apprehension that their design
was to murder him in an adjoining wood.
They afterwards went by a gallows,
where he imagined they might have it in view to execute him; but they passed by both.
Some people coming that way, they covered him with a cloak, and one of them sat upon him,
that he might not be seen.
But hearing them passing by,
he called out to them to let the barber know he was forcibly carried off.
The soldier then again beat him severely,
the other man having charged him not to suffer him to speak.
At night, when they came to their lodging, they fettered his feet,
and put a long chain tied over a beam about his neck.
Next morning, passing through a village, he would gladly have spoke to somebody;
but they forced him to lie down until they had got through the village.
They carried him to a convent or some such place in a wilderness;
but the prior not being at home, the monks would not receive him without his orders;
so that night he was laid in chains as before.
Next morning he was taken up to the monastery or castle,
and his conductor gave directions that they should blindfold him,
and put him in a deep dungeon, and give him only a little bread and water,
and that none should be suffered to give any intelligence of him.
A Jew being there, was prohibited, on pain of death to say any thing of what he had seen.
He was accordingly put into an hole, where there was scarce any light,
and kept there four days and four nights in cold frosty weather,
so that it seemed admirable he was not starved to death.

From the clandestine manner in which he was conveyed hither,
and the mysterious secrecy ordered to be observed,
as to his present place of confinement, it is not to be wondered at,
that he was apprehensive of being privately murdered, or made away with,
so as never to be heard of more;
and it is hard to account for this treacherous project otherwise,
than that the original design of the projectors was such,
or else to bury him alive in a dungeon, till death should release him,
or till he should be wearied out, or terrified into an adoption of their religion:
But the superintendency of divine providence rescued him from the former,
and the well-grounded persuasion of the superior
rectitude of his own religion from the latter.

He had been confined twelve days, when the Prior came home,
who sent for him and examined him, what end they had in view in coming into that country,
and concerning some points of their religion; to which he answered agreeably to truth.
The prior told him that was not enough,
he must also believe that the Pope was Christ`'s Vicar, and that he, and they,
had power to bind and loose in Heaven and on Earth.
He was afterwards again examined on the same subject;
and as his demeanour amongst them was inculpable and circumspect,
consistent with the purity of the profession he made,
they were the more desirous to gain him over as a proselyte,
because they apprehended he would be an ornament to their profession.
And a priest was sent to instruct and convert him, but his labour being ineffectual,
they had recourse to menaces, threatening one while to cut out his tongue,
another to flay him alive, if he would not turn papist.

Adam Bien continued steadfast in his friendship to them in all their afflictions.
After William was carried off, the Earl endeavoured to persuade him he was run away,
which Adam could not believe;
but by some means getting intelligence of the place
of his confinement sent him some necessaries,
and gave orders to supply him with bread on his account.
Soon after the Earl being again seized with an indisposition,
from which his recovery was doubtful, Adam solicited him in their favour,
and obtained his promise to set him at liberty.
But they being building a new cloister,
William was detained by the Prior six weeks after to attend the masons,
promising to tell him a good message when he returned, if he would be diligent.
He afterwards took him aside, and told him the Earl would have him told,
that if he would turn catholic he should have good service and preferment;
but if not he could not detain him, for he had prisoners enough besides;
but that it was concluded, that if he was found afterwards in Hungary or Austria,
he should be burned, and his companion also.

It was on the 4th of 7th mo (September) 1663, he was released,
and his companion two days after,
of whom I find no farther account but that he set forward toward Germany.
William, although set at liberty, yet having at first with his companion,
being stripped of their money,
which seemed more than sufficient for the expenses of their journey,
found himself involved in difficulty still, a stranger in a remote country,
without money and without friends; but having been inured to close trials of his faith,
he set out on his journey homeward,
trusting in the superintending care of divine providence for his sustenance,
from which he had experienced preservation in many straits,
wherein there was little prospect of relief.
Another danger attended him; the Austrians being at war with the Turks,
guards were placed at all the towns thereabout to examine strangers,
and seize or prevent suspicious persons entering into them;
he therefore avoided the garrisoned towns, and inquired the most private ways,
and under the protection of that divine hand in which he trusted,
in about a month he made his way into the Palatinate,
where at Christein he got amongst his friends, who entertained him kindly.
Here he tarried some weeks to rest and refresh himself
after the long continued scene of danger,
terror and distress, which he had just passed through.
