== Chapter XI.

[.chapter-synopsis]
* John Audland`'s Death and Character
* He was a Teacher among the Independents
* Convinced by George Fox
* He travelled much in the work of the Ministry
* First who visited the City of Bristol
* His Widow`'s Testimony concerning him
* George Fox`'s Trial before Judge Twisdon
* He traverses the Indictment
* Indictment quashed
* On his second Trial he is clandestinely condemned in a Premunire
* Severity of his Imprisonment
* Margaret Fell`'s Trial
* Francis Howgill`'s Trial
* At his second Trial condemned in a Premunire also
* Remarks upon his Trial

It was near the close of this year that John Audland was taken off in a consumption,
in an early stage of life.
He was born near Cammsgill in Westmoreland,
the seat of his beloved companion in gospel labour John
Camm (whose character and pious end are before related).
From a child he is described as sharp in apprehension,
of retentive memory and quick understanding; and as he approached a state of maturity,
he applied the attention of his mind to religious thoughtfulness,
and diligent reading the scriptures, and by the strength of his memory,
and the goodness of his understanding, gathered a large treasure of scripture knowledge,
and became an eminent teacher amongst the independents,
of a teacher whom he had a very numerous auditory.
He was one of the principal preachers at Firbank chapel
at the time when George Fox had the memorable meeting there,
and not the least amongst the number then convinced
of the truth and efficacy of the doctrines he published.
Notwithstanding the contemptible light in which learned
prejudice has viewed and represented George Fox,
yet it appears manifest his artless preaching and honest simplicity of style,
conveying heartfelt experienced truth, with gospel authority,
was more conducive to fix the best impressions on the hearts of his auditory,
and to open their understandings into a clear perception
of the emptiness of speculative religion,
unproductive of inward purity and establishment in righteousness,
than most of the elaborate discourses of lettered eloquence.
This was the effect it had upon John Audland,
impressing his mind with such reflections as these; What availeth our great profession?
All our building tumbles down; the day of the Lord is upon it,
and the fire of his word consumes it as dry stubble, and puts an end to all high notions,
and professions without life and substance, to all the wisdom of fallen man.
We must forsake the world and all its glory; it is all but vanity and vexation of spirit.
It is a Saviour I long for.
O that I may be gathered into his life; overshadowed with his glory;
sanctified throughout by his word, and raised up by his eternal power!
Under this view of the necessity of taking up the cross in order to attain peace,
he willingly submitted thereto; and resigning all his own self-righteousness,
acquired wisdom, and the reputation he had attained there by,
he spent many days in silence and solitude, in self-abasement,
humiliation and mental prayer, under the washing of regeneration, of which,
after a season of mournful travail of spirit, he was favoured with the experience.
Through divine condescension he attained the desire of his soul,
that inward peace which exceeds the comprehension of unsanctified men;
and an extraordinary qualification,
with wisdom and lively zeal to promulgate the way of salvation and reconciliation to God,
no longer under the cold influence of barren speculation,
but the animating energy of lively experience.
In the exercise of profitable ministry he zealously
and faithfully exerted his talents for several years,
travelling much through sundry parts of England,
to propagate the doctrines of the gospel maintained by the people called Quakers.
He was early married about the twentieth year of his age, to Anne Newby,
a young woman of a good family, who proved a well suited companion, being a virtuous,
valuable and well accomplished woman: With her he enjoyed much domestic happiness.
But such was the unreserved dedication of heart to the service of God,
and christian fortitude of these professors of the light of Christ within,
that neither the allurements of domestic ease and satisfaction,
nor the dangers and hardships which awaited them everywhere abroad,
were of sufficient consideration with them, to prevent their ready obedience,
when they apprehended the call of duty summoned them
to go forth with the message of the gospel:
Herein approving themselves,
by the same divine spirit to be fashioned after the model of primitive Christianity:
Remembering the time was short, they that had wives, were as though they had none,
they that bought as though they possessed not,
and they that used the world as not abusing it.
Such were this pious pair; closely united at they were in mutual affection to each other,
in similarity of sentiments and disposition,
and of devotion to the service of their creator;
when this service commanded their separation,
he hesitated not to proceed in the line of duty; nor she to give him up freely thereto.
By which means it happened,
that for a considerable part of the time from their marriage to his death,
they were much deprived of each other`'s company.
Although few were happier in each other than they;
yet looking for their principal happiness in futurity,
they were willing to deny themselves of that part of their present satisfaction,
which might be any obstruction to the steady pursuit of the future.

John Audland was one of the earliest preachers of this persuasion,
being the first of them, in company with John Camm, who visited the city of Bristol,
and the western counties; where, as well as at other places,
his powerful ministry was effectual to the convincing of many.
Being fluent in expression, engaging in his manner of delivery,
and abundantly replenished with matter, adapted to the different states of his auditory,
the number of his hearers increased to such a degree,
that for want of an house large enough to contain them,
he and his companion held their meetings frequently in an orchard without the city.
He was not only a partaker with his brethren in gospel labour,
but in the perils and sufferings of that trying day;
in repeated imprisonments and corporal abuses; by which,
with his zealous exertions in these large meetings,
beyond his bodily ability to sustain without injury,
he was affected with a violent cough, which appeared consumptive,
and finally terminated in a slow fever, whereby he was reduced to great weakness of body,
but through the comfortable evidence of inward peace,
in a consciousness of a life well spent, in the service of God and man,
he was preserved easy and lively in his spirit,
and bore his indisposition with exemplary patience.
Reflecting upon his labours and their effects he expressed,
"`that in those great meetings in the orchard at Bristol he often forgot himself,
without considering the inability of his body, from a desire to be heard of all:
But that his reward was with him, and he content to be with the Lord,
which his soul valued above all things.`"

Not long before his decease, being visited by some of his friends,
he addressed them with such encouraging consolation and exhortation
to fidelity under the trials they were exposed to,
and with such pertinency and reaching energy,
as if he was raised above the feeling of his weakness.
In tender sympathy with his beloved and affectionate wife, who was with child,
nigh to her delivery, to encourage her resignation, in case of his removal, he said,
"`My will is in true subjection to the will of the Lord, whether life or death,
and therefore give me up freely to his disposing.`"
And being, through divine assistance, strengthened to comply with this advice,
her sincere resignation under this affliction contributed
greatly to the ease of his mind.
He was net only preserved in peaceful serenity of mind at this solemn period,
but at times even filled with joy in the prospect of approaching felicity,
under the impression whereof, in the time of extreme bodily weakness,
his foul was raised up in praise to the almighty,
and in prayer for the prosperity of his friends in righteousness,
"`That they might be preserved in the truth, out of the evil of the world;
that his gospel might spread and be published to
the gathering of all that pertain to Israel.`"
His strength daily diminishing,
he terminated a virtuous life in great tranquillity at the age of thirty-four years,
which to him was of duration sufficient, being so well spent, as we trust,
ensured him the end of his faith, the salvation of his soul.

His widow (who bore her affliction in trying circumstances,
with remarkable resignation and discreetness) being
about ten days after his decease delivered of a son,
wrote a very pathetic testimony to his memory,
which contains a sensible and lively description of affection, founded in religion,
and christian fortitude, in acquiescing in divine disposal; in which she saith,

[.embedded-content-document.testimony]
--

God, who by his Providence joined us together in marriage in our young days,
in his blessed counsel caused also his day to spring from on high upon us;
in the marvellous light and shining whereof he revealed his son in us,
and gave us faith to believe in him, the eternal word of life,
by which our souls came to be quickened and made alive in him;
and also in and by the quickening of his holy power
we were made one in a spiritual and heavenly relation,
our hearts being knit together in the unspeakable love of truth,
which was our joy and delight, and made our days together exceeding comfortable,
as being that by which our temporal enjoyments were sanctified and made a blessing to us.
How hard it was, and how great a loss to part with so dear and so tender an husband,
is beyond what I can express; the sorrow of my heart,
my tongue or pen is not able to declare; yet in this I content myself,
that it was the will of the Lord that he was taken from the evil, and that my loss,
though great, is not to be compared to his eternal gain.

[.signed-section-closing]
1664.

--

In the last year we left George Fox, Margaret Fell and Francis Howgill in prison,
under arbitrary and illegal commitments; the two former in Lancaster castle,
and the latter in Appleby jail.
George Fox was brought to his trial for refusing
to take the oath of allegiance at the spring assizes,
the beginning of this year, before Judge Twisden;
and after giving his reasons why he could not, for conscience sake,
comply with the requisition to take the oath, he asked the judge, If he owned the king?
Who replying in the affirmative: "`Why then,`" said he,
"` thou not observe his declaration from Breda,
and his promises made since he came into England,
that no man should be called in question for matters of religion,
so long as they lived peaceably?
Why dost thou call me in question, and put me upon taking an oath,
seeing neither thou nor any other can charge me with unpeaceable living?`"
At this the judge was so provoked that he cried out, "`Sirrah, will you swear?`"
To which George boldly rejoined, "`I am none of thy sirrahs, I am a christian;
and for thee who art an old man and a judge,
to sit there and to give nicknames to prisoners,
doth not either become thy grey hairs or thy office.`"
Two days afterward, being brought before the judge again, and asked whether he would
traverse the indictment or submit,
he desired liberty to traverse whereupon he was continued in prison till the next assizes,
and during his confinement writ several papers to the magistrates,
manifesting the evil of persecution, and exhorting to virtue and piety.

He was called again before Judge Turner,
at the succeeding assizes held in the month called August,
where an indictment was found against him for refusing the oath;
and he being brought in guilty by the jury,
in arrest of judgment he pleaded so many material errors in the indictment,
that the court could not get over acknowledging them sufficient to quash it,
and it was accordingly laid aside; whereupon he appealing to the judge,
demanded justice of him, for he did not look for mercy.
The judge told him, You must have justice, and you shall have law.
Asking then, Am I free from all that hath been done against me in this matter?
Yes, replied the judge, but then recollecting himself, and starting up in a passion,
said, I can put the oath to any man here, and I will tender it to you again;
which he did accordingly, and recommitted him to prison till the next assizes,
which were held the 1 6th of March, (so called) 1664-5,
when he was tried on another indictment.

The arbitrary and unjust treatment of this worthy man is very obvious throughout,
being hitherto detained in a very incommodious prison, as before described,
upwards of twelve months, without the least shadow of crime:
a sufficient punishment of itself for evil doing; and when tried for a created offence,
and the indictment was proved erroneous in many essential points,
instead of obtaining his liberty, as of right he ought,
a repeated advantage is taken of his conscientious scruple, to prolong his punishment.
Although the judge confessed him legally at liberty,
yet he contrives to remand him to his severe imprisonment.
Thus justice was perverted under the influence of party-prejudice,
and the law stretched beyond due bounds to punish inculpable demeanour.

In his trial on the second indictment before Twisden he met with still harder treatment;
for although he proved this as well as the former erroneous in sundry particulars,
the judge arbitrarily overruled all his objections, and ordered him to be taken away.
When he was gone the jury brought in a verdict for the king: he was called no more,
but sentence of premunire was passed upon him in his absence.

Colonel Kirby, though seemingly fair and civil in his carriage towards him to his face,
was at the bottom a bitter enemy,
and the chief promoter of his first imprisonment and the severity of this prosecution,
who, having now obtained his desire, ordered the jailer to keep him close,
and suffer nobody to come near him.
The jailer, in compliance with this order, locked him in a smokey tower,
sometimes so filled with smoke that he could scarce see the candle when burning.
Here he was sometimes almost smothered, and in wet weather it rained in upon his bed,
so that his shirt was often quite wet in attempting to stop the rain.
In this distressing condition he lay through a long cold winter,
whereby he was so affected by the cold and wet,
that his body was much swelled and his limbs benumbed.

At the aforesaid assizes, in the month called August,
Margaret Fell was also brought to her trial on the same account,
an abstract of whose trial followeth:

Margaret Fell being brought to the bar, and the indictment read, the judge said, "`Come,
will you take the oath?`"

[.discourse-part]
_M+++.+++ Fell._
There is a clause in the indictment that the church-wardens informed of something,
which seemeth that it should be the ground or cause of this indictment,
I desire to know what matter of fact they did inform of,
for I was lent for from my own house, from amongst my children and family,
when I was about my outward occasions; when I was at no meeting,
neither was it meeting day;
therefore I desire to know what this foundation or matter of fact was,
for there is no law against the innocent and righteous;
and if I be a transgressor let me know wherein?

[.discourse-part]
_Judge._
You say well, the law is made for transgressors: But, mistress, do you go to church?

[.discourse-part]
_M+++.+++ Fell._
I do go to church.

[.discourse-part]
_Judge._
What church?

[.discourse-part]
_M+++.+++ Fell._
The church of Christ.

[.discourse-part]
_Judge._
But do you go to church with other people?
You know what I mean.

[.discourse-part]
_M+++.+++ Fell._
What dost thou call the church, the house or the people?
The house you all know is but wood and stone; but if thou call the people a church,
to that I answer, As for the church of England that now is, I was gathered to the truth,
unto which I now stand a witness, when this was not the established church.
I was separated from the general worship of the nation, when there was another set up,
than that which is now, and was persecuted by that power which then was,
and suffered much hardship; and would you now have us deny our faith and principles,
which we have suffered for so many years,
and turn to your church contrary to our consciences?

[.discourse-part]
_Judge._
We spend time about these things: Come to the matter in hand,
What say you to the oath and to the indictment?

[.discourse-part]
_M+++.+++ Fell._
I say to the oath, as I have said before in this place,
Christ Jesus hath commanded me not to swear at all, and that is the only cause,
and no other, the righteous judge of heaven and earth knoweth.
And this I do testify unto you here, that for the matter or substance of the oath,
and the end for which it is intended, I do own one part and deny the other.
I do own truth, faithfulness and obedience to the king,
and all his just and lawful commands and demands;
and I also deny all plottings and contrivings against the king,
and all popish supremacy and conspiracy;
and I can no more transgress against King Charles
in these things than I can disobey Christ`'s commands.
I do not deny this oath, because it is the oath of allegiance,
but I deny it because it is an oath,
because Christ Jesus hath said I shall not swear at all.
If I might gain the whole world for swearing an oath I could not,
and whatever I have to lose this day for not swearing an oath I offer it up.

[.discourse-part]
_Judge._
What say you to the indictment?

[.discourse-part]
_M+++.+++ Fell._
What should I say?
I am clear and innocent of wronging any man upon
the earth as the little child that stands by me;
and if any here have any thing to lay to my charge,
let them come and testify it before you all;
and if I be clear and innocent you have no law against me.

[.offset]
Then Colonel Kirby and the sheriff whispered to the judge,
whereupon she accosted the colonel:

[.discourse-part]
_M+++.+++ Fell._
Let us have no whispering:
If thou hast any thing to lay to my charge come down and testify against me?

[.discourse-part]
_Judge._
Jury, take notice she doth not take the oath.

[.discourse-part]
_M+++.+++ Fell._
This matter is weighty to me, what ever it be to you,
and I would have the jury take notice of it,
and consider seriously what they are going to do.
I stand here before you on account of the loss of my liberty and my estate; secondly,
I stand here obeying Christ`'s command, and keeping my conscience clear;
but if I keep the king`'s commands in obeying this law,
I defile my conscience and transgress the law of Jesus Christ, who is the king thereof:
And the cause and controversy in this matter that you are all here
to judge of this day is betwixt Christ Jesus and King Charles;
this is his cause, and whatsoever I suffer it is for him,
and so let him plead my cause when he pleaseth.

[.discourse-part]
_Judge to the jury._
Are you agreed?
Have you found it?

[.discourse-part]
_Jury._
For the king.

[.discourse-part]
_M+++.+++ Fell._
I have counsel to plead to my indictment.

[.offset]
The court adjourned till after dinner, when being met again they proceeded.

[.discourse-part]
_M+++.+++ Fell._
I desire we may have time till tomorrow morning to bring in our arrest of judgment?

[.discourse-part]
_Judge._
You shall have it.
Mistress Fell, you wrote to me concerning the badness of your prisons, that it rains in,
and that they are not fit for people to lie in.

[.discourse-part]
_M+++.+++ Fell._
The sheriff knows, and hath been told of it several times, and now it is raining,
if you will send you may see whether it be fit for people to lie in or not.
Then Colonel Kirby standing up to excuse the sheriff,
and to extenuate the badness of the place, M. Fell said,
if you were to be in it yourselves you would think it hard,
but your mind is only in cruelty to commit others, as William Kirby here hath done,
who hath committed ten of our friends and put them into a cold room,
where there was nothing but bare boards to lie on, where they have lain several nights,
some of them above threescore years of age,
and known to be honest men in the country where they live;
and when William Kirby was asked,
Why they might not have liberty to shift for themselves for beds?
He answered, They were to commit them to prison, but not to provide prisons for them.
And being asked, Who should do it then?
He answered, the King.

[.discourse-part]
_Judge._
You should not do so; they ought to have prisons fit for men.

[.offset]
Next morning her counsel pleaded in arrest of judgment,
and found several errors in the indictment, which yet the judge would not admit of,
but passed sentence of premunire upon her.

[.discourse-part]
_M+++.+++ Fell._
The Lord forgive thee for what thou hast done: This law was made for Popish recusants,
but you pass sentence on few of them.
Although I am out of the King`'s protection,
yet I am not out of the protection of Almighty God.

[.offset]
She remained in prison about twenty months before
she could obtain liberty to go to her own house,
which then she got for a little time, and returned to prison again,
where she continued about four years, till released by an order of the king and council

Francis Howgill was also brought to his trial at the spring assizes this year at Appleby,
before Judge Twisden aforesaid.
Coming into Court before the judges sat he inquired of the
clerk whether his appearance was expected then or not?
Who gave him expectation that he would not be called upon that assize.
But Sir Philip influences Musgrave,
a violent man and a principal promoter of the prosecution,
unfairly endeavoured to prepossess the judge against him,
by representing him as a dangerous person, a ringleader of the Quakers,
and a great upholder of their meetings.
Whereupon they resolved to proceed to his trial.
jury.
Judge Twisden, in his preparatory charge to the grand jury,
adopting the pretences and language in fashion, informed them,
There was a fort of people, who under pretence of conscience and religion,
and seeming to build upon the king`'s declaration from Breda,
under colour thereof hatched treasons and rebellions;
charging them inquire after and present such,
that the peace of the nation might be preserved.
The jury was then empannelled, and Francis called to the bar.
The judge proceeding very calmly in the following speech:

[.discourse-part]
_Judge._
The times being dangerous, and things having now a worse appearance than at last assizes,
and people under pretence of conscience violating the laws,
and hatching treasons and rebellions,
although I have nothing of that kind to charge against you;
yet seeing you did refuse to take the oath of allegiance at the last assizes,
the law doth presume such persons to be enemies to the king and government;
however I shall give you time to prepare for your trial till next assizes,
only you must enter into recognizances for your appearance then,
and for your good behaviour in the mean time.

F+++.+++ Howgill having requested and obtained leave to speak, said, "`Thou very well knowest,
Judge Twisden, upon how very slender an account, or none,
I was brought before thee the last assizes,
where thou wast pleased to tender me the oath of allegiance, though,
I believe both thou and the rest of the court did
know that it was a received principle amongst us,
not to swear at all: Many reasons I then gave to show,
that I did not refuse the oath out of obstinacy, but conscientiously,
and that I was none of them, who make religion a cloak of maliciousness,
nor conscience a cloak to carry on plots and conspiracies:
The Lord hath redeemed me and many more out of these things,
I desire therefore that my verbal promise and engagement
to appear at the next assizes may be accepted.`"

[.discourse-part]
_Judge._
You must enter into bond in this dangerous time; I would have you consider of it,
and either give me your answer now, or before we go out of town.

[.offset]
A day or two after he was called again.

Judge Twisden made a speech against treasons and rebellions, saying,
these things were carried on under colour of conscience and religion,
and reflected upon the Quakers.

[.discourse-part]
_F+++.+++ Howgill._
As to those things, I am clear:
I hope neither the court or country have any thing to lay to my charge:
I bless the Lord I have nothing to accuse myself with, for I have peace,
and seek it with all men;
and seeing the court is pleased to give me time to
answer to my indictment till the next assizes,
and since it is a matter of great consequence to me,
on which my liberty and estate depends,
I hope the court will not be against my having liberty
for these five months to prepare for my trial.

[.discourse-part]
_Judge._
We do not desire your imprisonment, if you will be of good behaviour.

[.discourse-part]
_Justice Fleming._
My lord, he is a great speaker, it may be the Quakers cannot do without him.

[.discourse-part]
_Judge._
Let him be what he will, if he will enter into bond.
What do you tell us of conscience, we meddle not with that, but you contemn the laws,
and keep up great meetings, and go not to church.

[.discourse-part]
_F+++.+++ Howgill._
It hath been a doctrine always, and a received principle, as any thing we believe,
that Christ`'s kingdom could not be set up with carnal weapons,
nor the gospel propagated by force of arms, nor the church of God built with violence;
but the Prince of Peace is manifest among us, and we cannot learn war any more,
but can love our enemies, and forgive those that do evil to us;
and though this unhappy contrivance hath fallen among some men,
who have brought trouble on the country and misery on themselves, we have no hand in it.
This is the truth, and if I had twenty lives,
I would engage them all that the body of the Quakers will never have any hand in war,
or things of that nature, that tend to the hurt of others,
and if any such whom you repute to be Quakers, be found in such things, I do,
before the court here, and before all the country, deny them: They are not of us.

[.discourse-part]
_Justice Musgrave._
My lord, we have been remiss towards this people, and have striven with them,
and put them in prison again and again, and as soon as they are out they meet again.

[.discourse-part]
_Sir John Lowther._
My lord, they grow insolent notwithstanding all laws, and the execution of them,
yet they grow upon us, and their meetings are dangerous.

[.discourse-part]
_Justice Musgrave._
My lord, it happened that some of the Quakers being sent to prison,
one of them died there, and they set this paper on the coffin,
"`This is the body of such an one, who was persecuted by Daniel Fleming to death.`"

[.discourse-part]
_F+++.+++ Howgill._
Notwithstanding here has been diligent inquiry made
by the grand jury concerning this plot,
what have you found against the Quakers.

[.discourse-part]
_Justice Musgrave._
There was one Reginald Fawcet, a Quaker, that is run away,
that was an intelligencer from the county of Durham.

[.discourse-part]
_F+++.+++ Howgill._
Fawcet hath been disowned by us these six years,
nor do I believe he hath pretended to come among us these two years:
And if perhaps any by your reputed Quakers should be found offenders in this nature,
I believe they would testify for us against themselves,
that the body of our friends and meetings did disown them.
It is therefore unkind to represent us thus hardly to the country.
God is with us and hath kept us from evils and temptations of this nature,
of plotting and fighting,
notwithstanding all the provocations and sufferings we have pasted through.

[.discourse-part]
_Judge._
The gentlemen and I have spent much time with you,
and I shall not discourse with you any longer.

[.discourse-part]
_F+++.+++ Howgill._
I acknowledge your moderation towards me, and I shall not trouble you much longer.
I shall be willing to appear to answer my indictment at the assizes,
and shall in the mean time live peaceably and quietly as I have always done.

[.discourse-part]
_Judge._
You must enter into bonds, and come at no more meetings.

[.discourse-part]
_F+++.+++ Howgill._
I cannot do that; if I should, I must be treacherous to God and my own conscience,
and even you yourselves and this people would think me a hypocrite.

[.offset]
The court ordered him to prison, and as he was going he turned to the people, saying,
The fear of God be amongst you all.

The people generally appeared very affectionate to him, and pitied his hard circumstances.
At the summer assizes held in the same place the
22nd and 23rd days of the month called August,
he was again brought to the bar, and finally condemned in a premunire,
under which he lay in prison to the end of his days.

Previous to his second trial he caused two papers to be presented to the judges;
one of them was a declaration containing the substance of the oath,
and the other a modest defence of himself for refusing to swear;
both which he was informed the judges read.
Here follows his trial before judge Turner.

[.discourse-part]
_Clerk._
Bring Francis Howgill to the bar.

[.discourse-part]
_Judge._
Here is an indictment against you for refusing to swear,
you must plead guilty or not guilty.

[.discourse-part]
_F+++.+++ Howgill._
May I have liberty to speak and make my defence?

[.discourse-part]
_Judge._
Yes, you may.

[.discourse-part]
_F+++.+++ Howgill._
I will lay the true state of the case before thee, seeing Judge Twisden is not here,
who was privy to all the proceedings hitherto against me.
I was born and brought up in this country; my carriage and conversation is known,
that I have walked peaceably toward all men, as I hope my countrymen can testify.
About a year ago,
being in a neighbouring market-town about my reasonable and lawful occasions,
I was sent for by an high constable out of the market to the justices of peace,
before whom I went: They had nothing to lay to my charge,
but fell to asking me questions to ensnare me about our meetings,
and when they could find no occasion, they seemed to tender me the oath of allegiance,
though they never read it to me, nor did I positively deny it;
yet they committed me to prison.
At next assizes Judge Twisden declared that my mittimus was insufficient:
Nevertheless he there tendered me the oath,
and engaged me to appear the next assizes after, which I did;
and then refusing to give bond for my good behaviour,
and not to be present at any of our meetings, I was committed to prison,
where I have been these five months, some of that time under great restraint,
and my friends not suffered to speak to me.
Now as to the oath, the substance thereof, with the representation of my case,
is already presented to the court, unto which I have set my hand,
and shall in those words testify the same in open court if required;
and seeing it is the very substance of what the law doth require,
I desire that it may be accepted, and that I may be cleared from my imprisonment.

[.discourse-part]
_Judge._
I am come to execute the law; and the law requires an oath, and I cannot alter it:
Do you think the law must be changed for you, or only for a few?
if this be suffered the administration of justice is hindered, no action can be tried,
nor evidence given for the king:
Your principles are altogether inconsistent with the law and government:
I pray you show me which way we shall proceed, show me some reason,
and give me some ground.

[.discourse-part]
_F+++.+++ Howgill._
I shall: In the mouth of two or three witnesses every truth is confirmed,
and we never denied to give,
and are still ready to give evidence for the king in any matter
for ending of strife between man and man in truth and righteousness,
and this answers the substance of the law.

[.discourse-part]
_Judge._
Is this a good answer, think you?
Whether to be given with an oath or without an oath; the law requires an oath.

[.discourse-part]
_F+++.+++ Howgill._
Still evidence may be given in truth, according to the substance of the law,
so that no detriment cometh to any party,
seeing true testimony may be borne without an oath;
and I did not speak of changing the law: Yet seeing we never refused to give testimony,
which answereth the end and substance of the law,
I thought it reasonable to receive our testimony and not expose us to such sufferings,
seeing we scruple an oath only on a conscientious account,
for fear of breaking the command of Christ, the Saviour of the world, which if we do,
there is none of you able to plead our cause with him.

[.discourse-part]
_Judge._
But why do you not go to church, but meet in houses and private conventicles,
which the law forbids?

[.discourse-part]
_F+++.+++ Howgill._
We meet only for the worship of the true God in spirit and in truth,
having the primitive christians for our example,
and to no other end but that we may be edified and God glorified;
and where two or three are met together in the name of Christ,
and he in the midst of them, there is a church.

[.discourse-part]
_Judge._
That is true; but how long is it since you have been at church,
or will you go to the church the law doth allow of?
Give me some reasons why you do not go?

[.discourse-part]
_F+++.+++ Howgill._
I have many to give, if thou hast patience to hear me.
1st, God dwells not in temples made with hands.
2ndly, The parishhouse hath been a temple for idols,
and I dare not have fellowship with idols, nor worship in idols temples;
for what have we to do with idols, their temples or worship?

[.discourse-part]
_Judge._
Were there not houses called the houses of God and temples?

[.discourse-part]
_F+++.+++ Howgill._
Yes, under the law, but the christians who believed in Christ separated from these,
and the temple was made and left desolate; and from the Gentiles temple too,
and met together in houses, and broke bread from house to house;
and the church was not confined then to one place, neither is it now.

[.discourse-part]
_Judge._
Will you answer to your indictment?

[.discourse-part]
_F+++.+++ Howgill._
I know not what it is.
I never heard it, though I often desired a copy.

[.discourse-part]
_Judge._
Clerk read it.

[.offset]
The indictment was read, importing that he had willfully,
obstinately and contemptuously denied to swear when the oath was tendered.

[.discourse-part]
_F+++.+++ H.owgill._
I deny it.

[.discourse-part]
_Judge._
What, do you deny?

[.discourse-part]
_F+++.+++ Howgill._
The indictment.

[.discourse-part]
_Judge._
Did you not deny to swear?

[.discourse-part]
_F+++.+++ Howgill._
I gave unto the court the substance of the oath, as you all know:
I also told you that I did not deny it out of obstinacy or willfulness,
neither in contempt of the king`'s law and government,
for I would rather choose my liberty than bonds,
and I am sensible it is like to be a great damage to me.
I have a wife and children, and some estate, that we might subsist on,
and do good to others, and I know all this lies at stake; but if it were my life also,
I durst not but do as I do, lest I should incur the displeasure of God:
and do you judge I would lose my liberty willfully, and suffer the spoiling of my estate,
and the ruining of my wife and children, in obstinacy and willfulness?
Surely not.

[.discourse-part]
_Judge._
Jury, you see he denies the oath, and will not plead to the indictment:
only excepts against it because of the form of words; but you see he will not swear,
and yet he saith, he denies the indictment, and you see upon what ground.

[.offset]
Then the jailer was called,
and gave evidence that the oath was tendered to him at a former assizes,
which he did refuse to take.

So the jury, without going from the bar, brought in their verdict, Guilty.

The next day, towards evening, he was again brought to the bar, to hear his sentence.

[.discourse-part]
_Judge._
Come, the indictment is proved against you, what have you to say,
why sentence should not be given.

[.discourse-part]
_F+++.+++ Howgill._
I have many things to say if you will hear them, 1st, As I have said,
I deny not swearing out of obstinacy or willfulness,
but am willing to testify the truth in this matter of obedience,
or any other matter wherein I am concerned.
2ndly, Because swearing is directly against the command of Christ; and 3rdly,
against the doctrine of the apostles.
4thly, Even of some of the principal members of the church of England, as Bishop Usher,
sometime primate of Ireland,
who said in his works that the Waldenses denied all swearing in
their age from that command of Christ and the apostle James,
and that it was a sufficient ground.
And Doctor Gauden, late Bishop of Exeter, in a book I lately read,
cites many ancient fathers, proving that the christians,
for the first three hundred years, did not swear, so that it is no new doctrine.

[.discourse-part]
_Judge._
Surely you mistake?

[.discourse-part]
_F+++.+++ Howgill._
I have not their books here.

[.discourse-part]
_Judge._
Will you say upon your honest word that they denied all swearing?

[.discourse-part]
_F+++.+++ Howgill._
What I have said is true.

[.discourse-part]
_Judge._
Why do you not come to church and hear service, and be subject to the law,
and to every ordinance of man, for the Lord`'s sake?

[.discourse-part]
_F+++.+++ Howgill._
I am subject; and for that cause do we pay taxes, tribute and custom,
and give unto Caesar the things that are his, and unto God the things that are his,
to wit, worship, honour and obedience: But if thou meanest the parish assemblies,
I tell thee faithfully, I am persuaded, and that upon good grounds,
that their teachers are not the ministers of Christ,
nor their worship the worship of God.

[.discourse-part]
_Judge._
Why it may be for some small thing in the service you reject it all.

[.discourse-part]
_F+++.+++ Howgill._
First of all it is manifest they are time-servants,
one while preaching that up for divine service to the people,
which another time they are crying down as popish, superstitious and idolatrous;
and that which they have been preaching up twenty
years together they make shipwreck of all in a day,
and now again call divine,
and would have all compelled to that themselves once made void.

[.discourse-part]
_Judge._
Why, never since the king came in?

[.discourse-part]
_F+++.+++ Howgill._
Yes; the same men that preached it down once, now cry it up,
and so unstable and wavering are they that we cannot believe they are ministers of Christ.
2ndly, they teach for hire, and live by forced maintenance,
and would force a faith upon men contrary to Christ`'s and the Apostle`'s rule,
who would have every one persuaded in their own minds, and said,
whatsoever is not of faith is sin; and yet they say faith is the gift of God,
and we have no such faith given; and yet they will force theirs upon us,
and if we cannot receive it, they cry, You are not subject to authority and the laws,
and nothing but confiscations, imprisonment and banishment is threatened;
and this is their greatest plea.
I could descend to more particulars.

[.discourse-part]
_Judge._
Well, I see you will not swear, nor conform, nor be subject,
and you think we deal severely with you; but if you would be subject we should not need.

[.discourse-part]
_F+++.+++ Howgill._
Yes, I do think so indeed,
that you deal severely with us for obeying the command of Christ.
I pray thee canst thou show me that any of these,
for whom the act was made have been proceeded against by this statute,
though I envy no man`'s liberty?

[.discourse-part]
_Judge._
Oh yes!
I can instance you many up and down the country that are premunired.
I have pronounced sentence myself against divers.

[.discourse-part]
_F+++.+++ Howgill._
What, against the papists?

[.discourse-part]
_Judge._
No.

[.discourse-part]
_F+++.+++ Howgill._
What then, against the Quakers?
So I have heard.
It seems then that statute which was made against the papists, thou lettest them escape,
and executest it against the Quakers.

[.discourse-part]
_Judge._
Well, you will meet in great numbers, and do increase,
but there is a new statute which will make you fewer.

[.discourse-part]
_F+++.+++ Howgill._
Well, if we must suffer it is for Christ`'s sake and for well doing.

[.offset]
Then the judge pronounced with a faint and low voice,
You are put out of the king`'s protection and benefit of the law.
Your lands are confiscated to the king during your life,
and your goods and chattels forever, and you are to be prisoner during your life.^
footnote:[This appears to me an evidence that this
judge was sensible this honest man was greatly wronged,
while he was completing his wrong,
and that he palled sentence upon him contrary to the conviction of his own conscience.]

[.discourse-part]
_F+++.+++ Howgill._
Hard sentence for obeying the command of Christ; but I am content,
and in perfect peace with the Lord; and the Lord forgive you all.

[.discourse-part]
_Judge._
Well, if you will yet be subject to the laws, the king will show you mercy.

[.discourse-part]
_F+++.+++ Howgill._
The Lord hath shown mercy to me, and I have done nothing against the king nor government,
nor any man, blessed be the Lord, and therein stands my peace;
and it is for Christ`'s sake I suffer, and not for evil doing.

[.offset]
So he returned to prison, where he continued to the end of his days.

I thought it worth while to insert these successive trials of this worthy man at large,
as exhibiting a specimen of the solidity of that religion,
which preserved him in so much tranquillity, meekness,
and command over his passions in the most affecting circumstances
of accumulated injury and unmerited severity.
Modesty, equanimity, good sense and sober reasoning on his part,
seem to soften the sternness of judges (habituated
to menacing and reproach) into apparent moderation,
though not to justice or clemency;
and his unprejudiced countrymen into a commiseration of his wrongs.
On the other hand,
when we view the pointed malevolence of the persecuting justices in Westmorland,
without any real cause administered by him, to send for him,
when engaged in his lawful affairs, on purpose to entrap him,
on account of a religious scruple, and taking advantage thereof,
to commit him to prison several miles from home, and confine him there.
When we see them unfairly endeavouring to prepossess the judge in the
prejudice of an honest inoffensive neighbour by invidious calumnies,
and to precipitate his ruin as to his outward circumstances,
by the weight of their joint influence and enmity; in short,
when we review all the cruel treatment of a worthy and respectable character,
whose moral conduct and peaceable demeanour were unimpeachable;
whose virtues were conspicuous and reputation in his neighbourhood untainted,
we are naturally led to regret the pernicious effects
of a religious or a political party spirit,
which blinds the judgment to such a degree,
that the most conspicuous virtue in one of opposite sentiments loses its complexion,
and is misconstrued into vice.
That in mistaken zeal for religion the plainest rules of morality are violated,
and in forcing uniformity in unessential points, the substantial parts, mercy,
justice and truth are obliterated.
