== Chapter XII.

[.chapter-synopsis]
* Act against Conventicles
* Quakers the greatest Sufferers
* Remarks on this Act
* Eight Persons tried on this Act and sentenced to banishment
* Customary to commit fora few Days to expedite their Banishment
* The Bill returned Ignoramus
* The jury sent out again and find the Bill
* Offered to be released upon paying the Penalty, which they refuse
* The Jailer contracts with Thomas May to transport them in his Ship
* He refuses to take them
* But is compelled
* He dismisseth them
* Returning they acquaint the King and Council, who order them to Prison
* They are confined seven Years
* In London great Numbers imprisoned
* Alderman Brown very abusive
* Speech of Judge Keeling
* Remarks thereupon
* Sixteen tried at Hicks`'s-hall
* Hard Case of Hannah Trigg
* Forty more tried
* Jurymen, for objecting to the Evidence, menaced
* For refusing to alter their Verdict bound over to the King`'s Bench
* Edward Brush and James Harding transported to Jamaica
* Robert Hayes, put aboard with them, dies there
* His Character

The statute which judge Turner, in the aforesaid trial, seemed to exult in,
as one he was confident would certainly reduce the numbers of this people,
was entitled to prevent and suppress seditious conventicles.

Every rumour of a plot (real or pretended) seems, under this administration,
a prelude to an additional penal law against nonconformists.
The plot alleged to be formed in the North, of which mention hath been made,
and on the pretended account whereof the three forementioned persons were taken up,
and premunired, was made a pretext for this new act,
whereby the act of 35 Elizabeth was declared to be in full force.
It further enacts,

[.embedded-content-document.legal]
--

That if any person of the age of sixteen years or upwards,
after the first of July 1664,
shall be present at any meeting under colour or pretence of any exercise of religion,
in any other manner than is allowed by the liturgy or practice of the church of England,
where shall be five or more persons beside the household,
shall for the first offence suffer imprisonment not exceeding three months,
or pay a sum of money not exceeding 5£. upon record made upon oath,
under the hands and seals of two justices of peace: for the second offence,
the penalty to be doubled: and for the third offence,
being convicted before the justices at their quarter sessions) or judge of assize,
by the verdict of a jury,
to be transported to some of the American plantations
(excepting New England and Virginia) for seven years,
or pay 100£. etc.
And in case they return, or make their escape, such persons are to be adjudged felons,
and suffer death.
Sheriffs or justices of peace, or others commissioned by them, are empowered to dissolve,
dissipate and break up all unlawful conventicles,
and to take into custody such of their number as they think fit.
Persons who suffer such conventicles in their houses or barns are
liable to the same penalties and forfeitures as other offenders.
Persons convicted the third offence to be transported at their own expence,
and in default of ability to pay the same,
to be made over to the master of the ship or his
assigns to serve them as labourers for five years.
Married women taken at conventicles are to be imprisoned
for a term not exceeding twelve months,
unless their husbands pay a sum not exceeding forty pounds for their redemption.
This act to continue in force for three years,
and to the end of the next session of parliament.

--

It is observable, that the former act passed in 1661 enacted the same penalties,
though not so largely or particularly expressed as this:
nor doth it appear that it was rigorously enforced, as this was.
The penalties of that act affected the Quakers only;
but this extending them to all who meet in any other manner than
is allowed by the liturgy or practice of the church of England,
reached all the nonconformists of every class.

But although it appears levelled at every body of dissenters,
still the greatest weight of sufferings fell upon the people called Quakers.
I have met with no account of any others condemned to transportation upon this act,
but with numbers of these who were.
Other classes of dissenters could dissemble,
temporize or meet clandestinely to avoid the force of the law;
than to evade sufferings by insincerity,
more regardful of the reputation of their religious persuasion,
than to give an advantage against it by mean subterfuges,
and more zealous in the conscientious discharge of duty to God,
than to be deterred from paying him the reasonable service of united worship,
for fear of human penalties.^
footnote:[Before the conventicle act took place, the laity were courageous,
and exhorted their ministers to preach till they went to prison;
but when it came home to themselves, and they had been once in jail,
they began to be more cautious,
and consulted among themselves how to avoid the edge
of the law in the best manner they could;
for this purpose their assemblies were frequently held at midnight,
and in the most private places: and yet notwithstanding all their caution,
they were frequently disturbed.
But it is remarkable,
that under all their hardships they never made the least resistance,
but went quietly with the soldiers or officers when they could not fly from them.
The distress of so many families made some confine themselves to their own houses,
some remove to the plantations, and others have recourse to occasional conformity,
to avoid the penalties of not coming to church.
{footnote-paragraph-split}
Indeed the Quakers gloried in their sufferings,
and in short gave such full employment to the informers about London,
that they had less leisure to attend the meetings of other dissenters.
{footnote-paragraph-split}
In London where the houses joined,
it was thought the law might be evaded if the people met in several
houses and heard the minister through a window or hole in the wall;
but it seems this was over-ruled.
Neale`'s history of the Puritans, vol.
ii. p. 650,
651.
{footnote-paragraph-split}
In the year 1666 a proclamation was issued against meetings.
In Herefordshire, George Fox writes, we were told of a great meeting of Presbyterians,
who had engaged themselves to stand and give up all rather than forsake their meetings.
When they heard of the proclamation the people assembled, but the priest was fled,
and left them to themselves.
Then.
they met in Leominster privately, and provided bread, cheese and drink,
that if the officers should come they might put up their bibles and fall to eating.
The like contrivance they had in other places.]

It is not wonderful that a law of such pernicious tendency to the liberty and security
of so large a body of the people should become the subject of severe criticism,
and give occasion to free animadversion.
An anonymous pamphlet, soon after published,
set forth the absurdity and severity thereof in cases like these.^
footnote:[It doth not appear that these probable consequences were merely imaginary.
Neale relates that such was the severity of these times,
that many were afraid to pray in their families,
if above four of their acquaintance that came to visit them were present.
Some families scrupled to ask a blessing on their meat, if five strangers were at table.
And in George fox`'s journal I meet with the following remarkable passage:
As the great professing Jews "`did eat up God`'s people as bread,`"
and the false prophets and priests then preached peace to the people,
so long as they put into their mouths; but if they fed them not,
they prepared war against them:
so these that profess themselves christians now (both
priests and professors) stirred up persecution,
and set the wicked informers at work;
so that a friend could hardly speak a few words in
a private family before they sat down to eat,
but some were ready to inform against them:
a particular instance of which I have heard as follows.
At Droitwich, Jo. Cartwright came to a friend`'s house,
and being moved of the Lord to speak a few words before he sat down to supper,
there came an informer, and stood hearkening under a window.
When he had heard the friend speak, he went and informed,
and got a warrant to distrain the friend`'s goods,
under pretence that there was a meeting at his house:
whereas there were none present in the house at that time, but the man of the house,
his wife and servant maid.
But this evil-minded man, as he came back with his warrant in the night,
fell off his horse and broke his neck.]
Since all religion exercised by six persons,
not according to the formality of the church of England was forbidden,
if a woman being in travail, and her life in danger, one of the company said a prayer;
or if any one spoke any thing to comfort the near relations of a person deceased;
or prayed for the health or happiness of a new married couple,
etc. it might happen that some, by the malice of their enemies,
might not only incur imprisonment for three months,
but by the repetition of such friendly offices be condemned to transportation.

George Whitehead also (one of the people called Quakers) took up his pen
upon this occasion to expose the unreasonable severity of the persecutors;
to strengthen his friends to steadfastness in their christian testimony;
to exculpate them from the charge of obstinacy, and to answer some specious objections,
particularly the following one, "`That the Quakers might keep small meetings,
and so not fall under the lash of the law;
for if they did not meet above five in number they would keep above the reach of the law,
and might also acquit their consciences before God.`"
To this he answered, "`That it might have been objected to the prophet Daniel,
that he might have prayed secretly and not with open windows and thrice a day,
after King Darius had signed the decree,
That whosoever should ask a petition of any God or man for thirty days, save of the King,
should be cast into the lion`'s den;
but that Daniel notwithstanding that decree continued to pray as aforetime.`"

And as to the judges continuing to enforce this act
in their customary unequal and arbitrary manner,
he represented "`How unreasonable it was to influence the jury on ill-grounded suspicion,
without leaving them the liberty of their own judgment: how unequal it was that soldiers,
who abused his friends in their meetings, should be called as witnesses against them;
and that they should be locked up with thieves and felons,
since this was contrary to the right of a free-born Englishman?`"
Josiah Coale likewise about this time published a remonstrance
to the King and both houses of parliament against persecution;
but remonstrances however reasonable had little effect
upon the men now possessed of power,
and previously determined to exert it with vindictive violence in punishment of nonconformists,
some in favour of uniformity, and others to promote less obvious designs.
Persecution to banishment was resolved on,
and almost immediately endeavoured to be put in execution.

For at the assizes at Hertford in the very next month
(August) the following eight persons of this profession,
viz. Francis Prior, Nich.
Lucas, Henry Feast, Henry Marshall, Jeremy Hern, Thomas Wood,
John Blendale and Samuel Trahern were brought to their trial before judge Orlando Bridgeman,
and indicted for the third offence against the conventicle act.
This is a remarkable instance of the precipitant eagerness of the persecutors;
for this act was not in force until the first of the month called July,
and these persons were arraigned for the third offence
on the 12th and 13th of the succeeding month.
Now as the penalty for the first offence was imprisonment
for a term not exceeding three months,
and for the second not exceeding six, at the arbitrary discretion of two justices,
it was usual with these justices to commit them for
a few days for the first and second offence,
not out of tenderness,
but in order to subject them more speedily to the
penalty of transportation for the third offence.^
footnote:[Of this we meet with the following account in George Whitehead`'s journal,
part 2. p. 283. On the 16th of 8 month 1664, being the first day of the week,
our friends were met together according to their usual manner
at their meeting place at Bull and Mouth near Aldersgate,
London, and Geo.
Whitehead being there was concerned to preach:
after some time a great company of men with halberts came into the meeting,
but gave him no interruption, until the mayor and Richard Brown, with a great company,
came in;
then in a short time a rude fellow pulled George
Whitehead down and haled him near the door.
The halbert men took George Whitehead and forty-three
others men and women into the street,
where after they had kept them some time they were
sent in companies to Newgate without warrants,
being fined one shilling each, or six days imprisonment.
At the same time a particular warrant was sent to detain five of them for a third offence.
And the shortness of our imprisonment (saith he) as well as the smallness of the fines,
seemed designed to dispatch us sooner out of the land by banishment.
On the 24th of the month called July,
twenty-seven persons were taken from the meeting in Wheeler-street,
and committed to Newgate for three days; from Mile-end twenty-two for six days;
and on the 31st fifteen for five days;
on the 7th of August (so called) twenty from Wheeler-street,
and thirty-two from Mile-end-green for four days;
on the 14th nineteen more sent for two days,
and two for the third offence. [.book-title]#Besse,# vol. 1. p. 394.]
For, from their long approved constancy,
they promised themselves an assurance of finding them again at their religious assemblies,
as soon as at liberty.

An indictment was drawn up against the aforesaid eight persons, expressing,
That they had been at an unlawful meeting three sundry times, at such times and places,
and being delivered to the grand jury, they could not agree in their verdict;
for there were some among them whose consciences would not so easily
allow them to be accessory to the condemnation of the innocent,
and therefore they returned the bill Ignoramus.
Now although this was a legal verdict, and the court by law had no right to reject it,
yet the privileges of the subject were held by so precarious a tenure at this time,
and the judges were so inured to go over every barrier of the constitution
to gratify the partial views of themselves or others,
that instead of accepting this return of the grand jury,
Bridgman addressed the jury with this angry speech, "`My masters, what do you mean to do?
Will you make a nose of wax of the law, and suffer the law to be baffled?
Those that think to deceive the law, the law will deceive them,
Why don`'t you find the bill?`"
With this menace and fresh instructions he sent them out again,
The jury they then found the bill, with which the court seemed well pleased.
Four of the prisoners were then brought to the bar, who pleaded not guilty, and added,
we have transgressed no just law: but replied the judge,
you have transgressed this law (holding the conventicle
act in his hand) and you have been twice convicted already.
If you be now found guilty, I must pass sentence of transportation against you:
but if you will promise to have no more such meetings, I will acquit you of what is past.
This favour you may receive before the jury is charged with you, but not afterwards.
What say you, will you meet no more?
They answered with one accord, We can make no such promise.
Upon which the jury was sworn, and witnesses examined,
who deposed that they found those persons assembled
above five together at certain times and places,
but that they neither heard any of them speak, nor saw them do any thing.

The judge then summed up the evidence, and gave his charge to the jury,
in which he told them,
"`You are not to expect plain punctual evidence of any thing said or done,
a bare proof of their being met for worship in their manner,
not being according to the liturgy and practice of the church of England,
is sufficient for their conviction.
`'Tis not your business to enter into the meaning of the law,
but singly determine the fact.`"
The jury, with these instructions, went out, and soon brought them in guilty,
and the judge forthwith passed sentence upon them,
viz. You shall be transported beyond these as to the island of Barbados,
there to remain for seven years.

Then the other four were sent to the bar, and tried in like manner,
and condemned to be transported to Jamaica; and a fifth, John Reynolds,
was tried along with them;
but the witnesses deposing they had not seen him in the meeting,
but within a yard of the door, with his face from it, he was brought in not guilty,
and accordingly acquitted.
The eight persons convicted were informed by the judge of that clause in the act,
which provides that upon paying 100£. each, before the rising of the court,
they might be discharged.
The court adjourned, and when they met again,
sent to the prisoners to know whether they would pay the 100£,
to which they unanimously answering No, the court broke up.

Pursuant to the sentence, the jailer, by the sheriffs order, as he said,
applied to one Thomas May, master of a ship, called the Anne,
and contracted with him to carry them to Barbados at 5£. per head,
and those to Jamaica at 6£. telling him they were freemen,
and that six of them would carry goods.
When they were brought to the master, and he found they were under compulsion,
he refused to receive them,
as his who refuses contract was to carry freemen and no others.
The jailer, vexxed at the disappointment, betook himself to the secretary of state,
and made oath, that he had contracted with Thomas May for the prisoners passage,
as persons convicted by the act.
May being sent for, took with him witnesses of his contract; but the secretary told him,
oath having been already made for the King, his witnesses could be of no use,
he must carry the prisoners.
During this time they were closely confined,
and but few of their friends admitted to see them.

The master being thus compelled to transport them, they were put on board;
but put on more by the master,
and taken in again sundry times between London and Gravesend; it being very remarkable,
that although many other vessels passed them down the river, this ship could make no way,
nor with the utmost application of the seamen make sail to any purpose.
Having by the master`'s orders followed him from place to place,
at last he met them all together at Deal, and before several witnesses declared,
that though they had followed the ship so long, yet he was resolved not to carry them.
Here he finally dismissed them, with a certificate,
to show that they did not make their escape, but were freely put ashore by him,
assigning for his reasons,
that seeing the adversities and various disappointments he had hitherto met with,
he concluded the hand of the Lord was against him.
That therefore he durst not proceed on his voyage with these prisoners,
they being innocent persons, and charged with no crime worthy of banishment.
That there is a law in force,
that no Englishman shall be carried out of his native country against his will.
That his men refused to proceed on the voyage, if he carried them.

There was on board one Manning, a man of a different disposition from the rest,
who had been very officious in getting them aboard,
and desirous of detaining them there with design, as was thought,
of making a market of them beyond sea.
This Manning, disappointed in his views,
carried a complaint to the deputy or principal officer at Deal,
that the prisoners had made their escape from the ship;
but they producing the master`'s certificate, he refused to concern himself in the matter.
Then Manning with two others forced four of them into a boat which he found on the beach,
to put them again on ship-board; but as nobody would assist him to row it,
he was forced to let them go.
The master sailed that night, and so left them behind.
The relation of the manner in which the ship left them was attested by eleven persons,
who were eye-witnesses thereof.

Being thus set at liberty they returned home,
and by letter acquainted the king and council thereof,
which letter being read at the council board,
under pretence that their liberation was effected
by a collusion concerted between the master and them,
by order of council they were again committed to prison,
until means of transporting them by some ship to those parts could be found,
and were continued in prison until released by the king`'s
letters patent more than seven years after.

On their return to prison they found twenty-one more
of their friends lying there under the like sentence,
who, at the quarter sessions held at Hartford the 3rd, 4th and 5th of October this year,
were condemned to banishment;
under which sentence most of them lay there till
released by the same letters patent in 1672.

In London this conventicle act was no sooner in force than multitudes
were imprisoned for the in London first and second offence,
which (as hath been noticed) was usually for a few days.
On the 14th of the month called August the sheriffs, with many officers and others armed,
entered the meeting-house at Bull and Mouth,
and ordered the person who was preaching to come down,
after which two of the officers stepped on a form near him, drew their swords,
and struck him and another friend with such force that one of their swords was broken;
then they laid hold both of men and women,
and haling out near two hundred drove them to Guildhall,
where they were kept prisoners till near midnight, and then, by the mayor`'s orders,
conducted with lighted torches by a guard of halberdiers to Newgate,
where they were thrust up among felons.
On the 15th about twenty were fined and committed, as were twelve more on the 17th,
and about sixty others on the 19th, some for fourteen and others for nine days.

On the 21st the mayor with the sheriffs and alderman
Brown came again to the meeting at Bull and Mouth.
This officious Brown, with his usual rudeness, kicked some, pulled others by the hair,
and pinched the women`'s arms until they were black:
by this rude behaviour and shameful abuse, degrading the dignity of his office,
and proving himself too vulgar for, and absolutely unworthy of,
the magistracy he bore in any well regulated government.
The mayor causing the doors to be shut sent about one hundred
and fifty-nine of them to Newgate for four days,
where they had not room to sit down nor scarce to stand,
being close shut up among the felons, without respect to age or sex.
On the 28th one hundred and seventy-five were also sent to Newgate as privately as possible,
the magistrates, its probable,
being ashamed to expose their unrelenting severity to the public eye.
On the 4th of September two hundred and thirty-two more were committed.

By such commitments the prisons being soon filled,
it was intended to proceed to the trial of such as were in for the third offence,
preparatory whereto Judge Keeling,
at the sessions at the Old Bailey on the 7th of September,
made the following speech to the grand jury:

[.embedded-content-document]
--

Because this day was appointed for the trial of these people,
and inasmuch as many are come hither expecting what will be done,
I shall say something concerning them and their principles,
that they might not be thought worthy of pity, as suffering more than they deserve,
for they are a stubborn sect, and the king has been very merciful to them.
It was hoped that the purity of the church of England would,
ere this have convinced them, but they will not be reclaimed.

They teach dangerous principles; this for one, That it is not lawful to take an oath.
You must not think their leaders believe this doctrine,
only they persuade these poor ignorant souls so;
but they have an interest to carry on against the government,
and therefore they will not swear subjection to it; and their end is rebellion and blood.
You may easily know that they do not believe themselves what they say,
when they say it is not lawful to take an oath, if you look into the scriptures.
That text (Mat.
5th) where our Saviour saith, Swear not at all,
will clear itself from such a meaning as forbids swearing,
if you look but into the next words, where it is said, Let your communication be yea,
yea, nay, nay; and it is said, An oath is an end of all strife:
this for the new testament: And the old is positive for swearing;
and they that deny swearing deny God a special part of his worship.

Now you shall see how this principle of not swearing
tends to the subversion of the government:
First,
It denies the king the security he ought to have of his subjects for their allegiance,
which oath they deny, and security by bond is not so good,
for thereby they are not engaged in conscience,
and they will only wait for a convenient season to forfeit their bonds without hazard,
and make sure work in overthrowing the present government and secure their own securities;
but an oath binds the conscience at all times, and that they cannot abide.
Again, this principle tends to subvert the government,
because without swearing we can have no justice done, no law executed; you may be robbed,
your houses broken open, your goods taken away and be injured in your persons,
and no justice or recompense can be had, be cause the act cannot be proved: The truth is,
no government can stand without swearing,
and were these people to have a government among
themselves they could not live without an oath.

Whereas they pretend in their scribbles that this
act against conventicles doth not concern them,
but such as under pretence of worshipping God do, at their meetings,
conspire against the government: This is a mistake, for if they should conspire,
they would then be guilty of treason, and we should try them by other laws;
but this act is against meetings, to prevent them of such conspiracy,
for they meet to consult to know their numbers, and to hold correspondence,
that they may in a short time be up in arms.

I had the honour to serve the king at York upon the trial of those wicked plotters,
and we found those plots were hatched and carried on in these meetings,
and we hanged up four or five of the speakers or praters,
whom we found to be chief leaders in that rebellion.
I warrant you their leaders will keep themselves from the third offence,
we shall not take them.
If we could catch their leaders we should try them by some other law, which, if executed,
will take away their lives.
This is a merciful law, it takes not away their estates, it leaves them entire,
only banishes them for seven years if they will not pay an hundred pounds;
and this is not for worshipping God according to their consciences,
for that they may do in their families, but forsooth they cannot do that,
but they must have thirty,
forty or an hundred others to contrive their designs withal.

--

One might imagine this judge looked upon the bench as a privileged place to utter falsehoods,
and because his office and power exempted him from detection there,
he might take the liberty not only of misrepresenting fact,
but in order to deprive honest people,
whom he was determined to punish with the utmost rigour of this unrighteous law,
of compassion, and to add public odium to exorbitant severity,
to bring any aggravating accusations against them without regard to truth.
But his false assertions were detected in a reply
to this notable speech published soon after.
He intended immediately to have proceeded to the trial of some of them:
for which purpose a young lad was brought from Newgate,
who being asked if he were not at the Bull and Mouth meeting such a day, he replied,
I was not;
whence the judge took occasion to reproach the Quakers with common place reflections,
saying, that for all their pretensions to truth, they could lie for their interest,
and to evade suffering.
But this youth persisting in his denial, witnesses were called for,
to prove his being there, but none could be found; which the judge observing, said,
Here is a disappointment; threatened some should suffer for it,
and so dismissed the jury.
This disappointment was want of evidence to answer the purpose of the court,
to prevent which in future, orders were issued that the jailer of Newgate,
the marshal and his men should attend the meetings,
and be prepared to give evidence against the next sessions.

On the 10th of October the sessions began at Hicks`'s-hall before Sir John Robinson,
and on the 1 3th a bill of indictment was preferred
against sixteen Quakers for the third offence,
about which the grand jury could not agree that night, but next morning,
at the importunity of the justices, found the bill by a small majority.

They were tried and convicted, and twelve of them received sentence of transportation,
amongst whom was a young woman named Hannah Trigg,
whose treatment was unreasonably tyrannical and illegal, even by this severe law:
for of Hannah being asked in form, why sentence should not be passed upon her,
and she replying, she was not sixteen years of age,
one of the justices told her she lied: And although a certificate of her birth,
signed by two women present thereat, was produced,
asserting she was born the 20th day of August 1649,
it was arbitrarily rejected by the justices, who were so intent on multiplying convicts,
that they seemed determined to go over all objections legal or illegal,
whereby any might escape the designed punishment.
The case of this young woman was yet more severe in this:
that soon after she was sentenced to banishment, she sickened in Newgate,
and dying there, the same unfeeling inhumanity, insatiate with her life,
was extended to her lifeless corpse;
her relations were debarred even of the consolation
of paying the last office of natural affection,
by interring her as they desired:
but she was carried to the burying place where they
usually inter felons and others who die in the jail.
When the bearers came to the ground, finding no grave made,
they left the corpse unburied, saying, they would make a grave next morning.
The girl`'s mother attending the funeral,
had the grief and anguish to behold this inhuman usage of her daughter`'s remains,
in silent sorrow without the power of remedy.
The other four being married women,
were sentenced to eleven months imprisonment in Bridewell.

On the 15th above forty more were brought to the sessions at the Old Bailey,
and called to the bar, one, two, three or four at a time,
as they were included in one indictment.
About sixteen, considering the indictment as a charge of contemning the law,
and acting contrary to the king`'s peace, pleaded Not guilty.
Others giving general answers, such as, I have wronged none, I am innocent,
etc. were set by as mute, and the fact taken pro confesso.
Then the court, at which Judge Hide presided, proceeded to try the former sixteen.
The witnesses against them were the under-keepers of Newgate and the marshal-men.
The first was one Dawson, a turn key, who was greatly confounded in his testimony,
for having sworn that he took John Hope,
who had been in prison three weeks at the Bull and Mouth last Sunday,
and the court endeavouring to set him right, he correcting himself,
said the Sunday before, which was equally false.
Afterward he said the prisoner was brought out to him,
and that he did not see him in the meeting.
Upon which one of the jury, addressing himself to the judge said, "`My lord,
I beseech you let us be troubled with no more such evidence,
for we shall not cast men upon such evidence as this;`"
but the judge endeavoured to palliate it,
and reproved the juryman for being too scrupulous.

Another evidence was William Turner, a turnkey too,
who being asked if the prisoner was at the Bull and Mouth, answered,
he was there that day, he came with the constable; whence it appeared he did not see him,
till he came to Newgate.
So one of the jury objecting to this witness, the judge grew angry,
and threatened him for undervaluing the king`'s witnesses,
and told him the court had power to punish him and would do it.
After some time the jury was sent out, who brought in their verdict,
that four of the prisoners were not guilty, and the rest they could not agree on.
The judge being much displeased sent them out again with fresh instructions,
and they returned with this verdict, guilty of meeting, but not of fact.
The judge inquiring what they meant by not guilty of fact, the jury replied,
"`Here is evidence that they met at the Bull and Mouth,
therefore we say guilty of meeting: but no evidence of what they did there,
therefore we say,
not guilty of meeting contrary to the liturgy of the church of England.`"
The judge asked some of the jury,
Whether they did not believe in their consciences that they
were there under colour and pretence of worship?
To which one of them replied, "`I do believe in my conscience,
that they were met to worship in deed and in truth.`"
Another said, "`My lord,
I have that venerable respect for the liturgy of the church of England,
as to believe it is according to the scriptures,
which allow of the worship of God in spirit;
and therefore I conclude to worship God in spirit is not contrary to the liturgy;
if it be, I shall abate of my respect to it.`"
In short, neither persuasions nor menaces could induce the jury to alter the verdict:
whereupon six of them were bound in 100£. each to appear at the
King`'s Bench bar the first day of the next term.

On the 17th, those who had been set by were brought to the bar to receive sentence:
First, four married women condemned to the house of correction for twelve months,
the rest to banishmernt; the men to Barbados, and the women to Jamaica,
there to remain seven years.

Thus the persecuting magistrates and judges to the house continued to imprison,
try and condemn to banishment the members of this society in great numbers, there being,
by an account published at this time, upwards of fix hundred in prison.
All the absurdity and arbitrariness of their proceedings particularly
to recount would lead me into a disagreeable prolixity;
suffice it to observe,
that by authentic records I find that upwards of two hundred
were sentenced to banishment in different parts of the nation,
in this and the succeeding year,
of whom upwards or one hundred and fifty were condemned
at the Old Bailey and Hicks`'s Hall;
and what is very remarkable out of all this number,
I find no particular account of more than two at one time and about fifteen at others,
who were actually transported,
which was not owing to any relaxation of severity in the government or subordinate magistrates,
but the disappointments they met with of the means of transporting them,
as hath been observed with regard to those condemned at Hertford,
and will further appear in the process.

These two were named Edward Brush and James Harding,
who on the 24th of the month called March, very early in the morning, were,
without any warning, hurried from Newgate by some of the turnkeys to Blackfriars,
and thence to Gravesend, where they were forced on board a ship,
which carried them to Jamaica, where it pleased God to prosper them,
so that they lived there in good circumstances: and Edward Brush,
who was at that time a grey-haired aged man,
a citizen of good repute among his neighbours,
and well esteemed by many persons of consequence,
after suffering the anguish of being thus violently
separated from a beloved wife and only child,
aged as he was, survived the term of his exile, lived to come back,
and end his days in peace at home.

Along with these two, a third named Robert Hayes,
was also in like manner put on shipboard;
in whom we have a fresh instance of the unfeeling barbarity which actuated his persecutors,
for being taken fasting out of prison, though in a weak state of health,
and under a course of physic,
and carried down the river on a very cold day without any refreshment afforded him;
within a little time after he was put on on board, he died there.
His body was brought back to London,
and interred in the burying ground belonging to his friends.
George Whitehead, who knew him, gives the following account of Robert Hayes:
"`He was a very innocent loving man, a good-like person, of fresh comely countenance,
seemed healthy, and in the prime of his strength when first imprisoned.`"
And adds, "`I was very sorrowfully affected,
when I heard how quickly he was dispatched out of the world by the shameful
cruelty and inhuman usage of these merciless persecutors.`"
