== Chap XIII

Exemplary Patience of this People under Suffering.--Sundry Friends by
Example and Precept encourage them to Steadfastness.--George Fox,
jun.
his Warning to England.--George Bishop`'s to the King and
Parliament.--Reflection on the Manners of the Age,
which are thought to draw down the Judgments of Heaven upon it.
1+++.+++ The Dutch War.
2+++.+++ A depopulating Pestilence.--More than one hundred and twenty condemned
to Transportation in London.--An Embargo laid on the Shippings in order
to oblige the Masters to transport the Prisoners.--Fifty-five taken from
Newgate to be transported.--The Plague breaks out in the Ship and carries
off twenty-seven of the Prisoners.--The Ship taken by a Dutch Privateer,
and the surviving Prisoners set at liberty.--The Plague increases.--Fifty-two
of the People called Quakers die in Newgate of the Pestilence,
notwithstanding which the Prisons are crowded with
fresh Prisoners.--Death of Samuel Fisher,
Joseph Fuce, and William Caton.

Exposed as this people was to multiplied penalties and severe execution of unequal laws,
yet through all the exertions of malicious violence,
wanton despotism and manifest injustice, during the heat of the persecution,
they fainted not in their minds;
strengthened by divine support and the testimony of a pure conscience,
they were enabled to endure sufferings exceeding
the patience of mere humanity with meekness,
and without repining, in resigned acquiescence to divine permission,
and in humble dependence upon divine protection and support,
under the arbitrary deprivation of the protection of the king,
the laws and immunities of their native country.
There were among them some,
who were not only examples in steadfastness in suffering themselves,
but by their exhortations in word and writing, as well as example,
encouraged their brethren to steadfastness therein;
so that through all these efforts of the persecutors to abolish this society,
they increased notwithstanding in strength and in numbers.
George Fox, George Whitehead, Francis Howgill and Josiah Coale were of this number.
Others were engaged to bear testimony against persecution by their epistles,
remonstrances and prophetic warnings,
addressed to the king and parliament in much plainness;
and yet (what was very remarkable) amongst the great number condemned to banishment,
not one of these eminent and active members was included,
although they never sought to escape by subterfuge, but continued, when at liberty,
to example their brethren to an open and diligent attendance of meetings,
as well as to encourage them thereto.

Two of these prophetic warnings are too remarkable to be passed over unnoticed,
although lettered pride, which reluctantly admitting of any divine revelation,
considers all modern claim thereto as enthusiasm,
and Quakerism in particular as founded therein; yet other readers,
who with me may not be quite so sceptical,
may perhaps be modestly backward to decide upon a
point above the determination of human wisdom,
especially when the predictions appear to be fulfilled:
So leaving the reader to make what comment seems good,
I shall proceed to transcribe them as I find them recorded in the authors before me.

The first is extracted from a publication of George Fox the younger in 1661,
wherein lamenting England,
because of the judgments that were coming upon her
inhabitants for their wickedness and persecutions,
he saith, "`The Lord had spoken in him concerning the inhabitants,
The people are too many, I will thin them, I will thin them!`"
Further, That an overflowing scourge,
yea even a great and terrible judgment was to come upon the land,
and that many in it should fall and be taken away.`"

The next is a short admonitory caution from George Bishop, of Bristol, addressed

"`To the King and both houses of parliament.

"`Thus saith the Lord,

"`Meddle not with my people, because of their conscience to me,
and banish them not out of the nation because of their conscience;
for if you do I will send my plagues upon you, and you shall know that I am the Lord.

"`Written in obedience to the Lord by his servant,`"

Bristol 15th 9mo 1664.

G+++.+++ BISHOP.`"

Yet whilst these rigorous measures were thus rigorously executed,
for forcing uniformity in the age: religion,
true religion perhaps was never less cultivated or promoted than at this time,
by the ruling party.
The manners of the age were corrupt and immoral to a scandalous degree.
Through the example of their superiors, and the pliant doctrine of their teachers,
adapted to flatter the great,
and in general more pointed against nonconformity than vice,
"`the common people (says Neale) gave themselves up to drunkenness, profane swearing,
gaming lewdness, and all kinds of debauchery,
which brought down the judgments of heaven upon the nation.`"^
footnote:[Neale, vol. 2. p. 651.]

The people called Quakers also of this age,
looked upon the train of succeeding calamities as divine
judgments inflicted upon a sinful and persecuting generation;
and although the secrets of the Almighty are a great deep,
and his ways above the investigation of human wisdom,
yet I think scripture warrants us to consider signal national calamities in this light,
when national corruption becomes remarkably general as at this time.

The first of those evils, mentioned by Neale, was a war with the Dutch,
wantonly and in unjust policy commenced by the English court,
and promoted by the selfish policy of France,
which cost the nation much blood and treasure,
and many lives were lost on both sides and no advantage gained by either.

The next general calamity which befel the nation,
had more the appearance of a divine visitation for the sins of the people;
it was the most dreadful plague that had been known in the memory of man.
Neale writes "`that it was preceded by an unusual drought;
the meadows were parched and burnt up like the highways,
insomuch that there was no food for the cattle,
which occasioned first a murrain among them,
and then a general contagion among the human species,
which increased in the city and suburbs of London,
till eight thousand or upwards died in a week.
The wealthier inhabitants fled into the remoter counties;
but the calamities of those who stayed behind,
and of the poorer sort are not easily described.`"
Trade was at a full stand.
Intercourse between London and the country was much interrupted.
In London the shops and houses were quite shut up,
and grass was growing in the most populous streets, now become a scene of solitude,
silence and gloom; and it was remarked that the first house in which it broke out,
and was shut upon account of the infection,
was the very next door to the late dwelling of Edward Brush,
lately transported on the conventicle act.

It was certainly a most awful and awakening visitation,
sufficient one would think to rouse the most inconsiderate souls to serious thoughtfulness,
and close consideration of their ways and of their latter end,
when the examples of mortality were daily multiplying before their eyes,
and none could be certain, whose turn it would be next,
or whether himself had many days to live: yet such was either the hardness of heart,
or the mistaken persuasion of their doing well, in the persecuting magistrates,
that unawed by these symptoms of divine displeasure,
not softened to companion by the common calamity,
they proceeded for a season to carry this conventicle act into force,
by increasing the number of Quaker prisoners and exiles,
as if nothing extraordinary had fallen out.

In the month called April 1665,
twelve more of this society were sentenced to transportation, and seven more taken,
from Newgate to Gravesend, and there put on shipboard,
to be transported to the plantations, and in the succeeding month eight others.
And a few days after their embarkation, judge Hide,
who had been an active man in promoting the conviction and sentencing of many to banishment,
was suddenly taken off, being in health in Westminster in the morning,
and found dead in his closet the same day at noon.

At the next sessions at the Old-Bailey four more were condemned to transportation,
under which sentence there remained in Newgate more than 120 persons,
whom the sheriffs knew not how to get rid of; for the masters of ships,
persuaded of the men`'s innocence, generally refused to carry them,
and the increasing pestilence confirmed them in their refusal,
it being esteemed by them and many others as a judgment
on the nation for its persecuting laws.
To remedy this difficulty, an embargo was laid on all merchantmen,
with an order that none should go down the river without a pass from the Admiral;
and this would be given to no master going to the West-Indies,
but on condition of his engaging to carry some Quakers.
Remonstrances of the illegality of carrying Englishmen
out of their native country by force were vain.
At length they found a man for their purpose, one Fudge, a person so hardened as to say,
be would not stick to transport his nearest relations.
With this man the sheriffs agreed to carry the prisoners to Jamaica,
and in pursuance thereof fifty-five were taken out of Newgate,
put into a barge and carried down the river to his ship, lying at Bugby`'s-hole,
a little below Greenwich.
When they came to the ship`'s side, the master being absent,
the seamen refused to assist in forcing them on board,
and the prisoners were unwilling to be active in their own transportation.
The turnkey and officers used high words to the seamen,
insisting that the prisoners were the King`'s goods,
and that they ought to be assistant in taking them aboard: the mariners were inflexible,
and would not move a finger in that work.
At length with much difficulty they got only four on board, and being weary,
returned with the rest to Newgate, where they lay about two weeks,
and then were again carried to the barge, soldiers were sent from the Tower in boats,
to be assistant in putting them on board.
Several of their friends in other boats accompanied them,
though the soldiers threatened to sink them, if they would not be gone.
The commander of the soldiers called to the seamen to assist, but few of them regarded.
Then the soldiers in the barge laid hold on the prisoners, dragging some,
kicking and punching others, heaving many by the legs and arms,
and in this manner got them all on board in about an hour`'s time,
being thirty-seven men and eighteen women.

On board, the men were all thronged together between decks,
where they could not stand upright.
The master of the ship being in the meantime arrested for debt, and cast into prison,
the ship was detained so long in the river,
that it was about seven months before they reached the land`'s-end:
and in the intermediate time, the pestilence breaking out in the ship,
carried of 27 of the prisoners.
At last another master being procured, on the 23rd of the month called February,
the vessel sailed from Plymouth,
and was the next day taken by a Dutch privateer off the Land`'s-end,
and carried to Hoorn in North -Holland.
When the commissioners of the admiralty there understood
that they would not be exchanged as prisoners of war,
they set them at liberty, and gave them a passport and certificate,
"`That they had not made their escape, but were sent back by them.`"
From Hoorn they made their way to Amsterdam,
where they met with a kind reception from their friends,
who provided them with lodging and clothes,
their own having been mostly taken from them by the privateer`'s crew.
From hence they all returned to England, except one,
who being a foreigner stayed in Holland.
By these means the exiles were delivered,
and the design of the persecutors was frustrated
by the ordering hand of divine providence.

In the same week that these 55 persons were put on shipboard,
the bills of mortality in London amounted to upwards of 3000,
and in the next week to 4030,
and went on increasing till in the month of September
they increased to up wards of 7000 in the week.
Persecution not withstanding continued, and the meetings to be disturbed as before.
As this destructive pestilence was esteemed to be a sore and heavy judgment on a wicked,
profane and persecuting generation,
who had long sported themselves in oppressing the innocent,
so it might be reckoned a merciful visitation to the faithful and conscientious prisoners,
in releasing them from a life worse than death in the filthy holes of Newgate.
For a contagion which spread through all the city with unabated violence,
must naturally be supposed to infect the jails (at all times liable to infection,
where numbers are pent up together in a polluted air, in close,
damp and filthy rooms) with an additional baneful effect.
In the aforementioned prison no less that fifty-two of the people
called Quakers laid down their lives in testimony of a good conscience,
twenty-two of whom lay there under sentence of transportation.

But what must fix an indelible stamp of utter insensibility to every motive of humanity,
of civility or common decency, on the characters of those magistrates,
to the disgrace of the government,
and of that church with which they were so zealous to force conformity, was,
that during the very height of the contagion they continued
to crowd the infected prisons with fresh prisoners.
On the 9th of the month called August, Sir John Robinson, lieutenant of the Tower,
sent a body of soldiers to break up the meeting at the Peel,
who entered it in the accustomed hostile manner, crying to the assembly,
"`They were all their prisoners.`"
John Eldridge asking by what authority they came,
was answered by a blow on the head with a musket;
and another for asking the same question was knocked down.
The soldiers carried away thirty-two of them to Newgate,
without paying any regard to the perilous situation of that prison,
which bears an aspect of barbarity insatiable in punishment short of death;
as there was at the time of their imprisonment no
human probability of their all coming out alive;
nor did they;
some of these being in the number of the prisoners
carried off by the plague in that prison.

In the same month eighteen others were committed to the Gatehouse Westminster,
by warrants from the Duke of Albemarle,
four of which number died there of the contagion.

But now having prosecuted their vindictive measures to imprisonment,
little short of murder,
the devouring pestilence continuing to cut off multitudes of the citizens,
and little or no trade stirring, the poorer people grew discontented.
The melancholy state of the city, and general distress of the citizens,
damped the fury of persecution in the city for the present;
and this calamity of the plague being the next year
succeeded by another little less distressing,
a destructive and extensive conflagration,
the successive and extraordinary symptoms of divine displeasure discouraged (or the
necessary care for the relief of the distressed citizens diverted the attention of)
the government and magistrates from prosecuting the dissenters as hitherto,
in order to apply it to more pressing exigencies;
so that this people in the city of London had a respite of some years,
wherein they were suffered to hold their meetings with less disturbance.

Amongst the great numbers who laid down their lives in prison in the course of this year,
was Samuel Fisher, with whom the reader hath before made acquainted;
that he was a man of great parts and literature, formerly a preacher at Lydd in Kent,
but voluntarily relinquished his benefice of near two hundred pounds per annum,
and joined in society with the baptists.
In the year 1655 he was convinced of the truth, as held by the people called Quakers,
and through obedience thereto became a faithful minister of the same,
and travelled much in the exercise of his ministerial labours for
the propagation of righteousness both in Engiand and foreign parts.
At Dunkirk in Flanders he had good service in testifying
against the idolatry of the priests and friars,
and preaching to the English garrison there.
He afterwards travelled on foot, in company with John Stubbs, over the Alps,
and through Italy to Rome, where they bore faithful testimony to the simplicity of truth,
and against the superstitions of the religion of that place;
they also distributed some books amongst the ecclesiastics there,
and when their service was over passed away without molestation.
But although he escaped persecution abroad amongst
the Romanists (amongst whose pernicious tenets,
Protestants have ranked the persecution of Heretics) he met with
his full share of it amongst the professed protestants at home,
his sufferings being very great after his return to England.
The greatest part of the four last years of his life he spent in prison;
for in 1661 he was several months a prisoner in the Gatehouse in Westminster:
Soon after his release he was illegally apprehended, as before related,
sent to Bridewell, and after some time brought to Guildhall,
where refusing to take the oaths he was committed to Newgate,
and confined there about twelve months.
And in a short time after his discharge was taken again at Charlewood in Surry,
and committed to the White-Lion prison in Southwark,
where after near two years imprisonment, on the last day of the month called August,
he finished his course in this life, in perfect peace with God;
in good esteem both with his friends and many others,
not more on account of the eminence of his natural parts and acquired abilities,
as a scholar, than of his exemplary humility, social virtues,
and circumspect conversation as a christian:
In meekness instructing those who opposed him,
and labouring incessantly by his discourses and by his writings
to propagate and promote true christian practice and piety.

Along with him was taken at the same meeting, and committed to the same prison,
Joseph Fuce, who also laid down his life there, a prisoner,
for the testimony of a good conscience.
In the work of the ministry he had travelled through several countries;
his gift being in a peculiar manner adapted to the convincing of gainsayers,
he was frequently engaged in disputes with independents, baptists and other preachers.
He was a man of a patient and meek spirit; very laborious in the work of the ministry;
and, as well as his brethren, a deep sufferer on account of his religious persuasion,
and religious discharge of duty: In the year 1655,
being on his travels in the exercise of gospel labour,
he was taken up by order of the mayor of Arundel,
and sent to Portsmouth to be shipped for Jamaica, among a company of disorderly persons,
who had been convicted and sentenced to transportation for their vicious courses.
By what means he escaped this undeserved punishment doth not appear,
but it is reasonable to suppose, that,
in consideration of the barefaced illegality of banishing a subject not only unconvicted,
but legally charged with no crime,
some of the more temperate and prudent magistrates must have released him.
In 1660, being at a meeting at Deal, after the insurrection of the fifth-monarchy men,
several armed men and others rushed in,
and took thence Joseph Fuce and twenty-three others;
they were the fifth all committed to Sandown castle,
and there kept several days and nights,
their friends not being allowed to bring them either food, to eat, or straw to lie on.
Afterwards he and another friend were removed to Dover castle,
where their treatment was still more barbarous.
They were kept locked up with five others of their
friends within two or three doors in one room,
from which they were permitted no egress on any emergency, however urgent,
not even to answer the necessities of nature;
neither were their friends allowed access to them to bring them necessaries;
for the marshal had charged his servant that he should permit nobody to come near them,
and the man having shown them some little favour, was turned out of his place,
and another substituted therein more suited to the
marshal`'s disposition in a similarity of temper;
for when one of their wives had come six miles to bring her husband some necessaries,
he would not suffer her to see him.
Joseph Fuce,
taking an opportunity to remonstrate to the marshal
against the unreasonableness of this cruel usage,
was answered with a volley of oaths and execrations,
which profanity being very wounding to the ears of this religious man,
he thought himself in point of duty obliged to bear his testimony against it,
by a serious reproof, for which he met with treatment more cruelly severe.
The marshal, exasperated to rage,
caused him to be dragged headlong down several stone steps,
into a dungeon under the bell-tower, overrun with filth and with vermin,
to a degree which decency recoils to describe, without aperture for light or air,
only some holes cut in the door.
There he was kept two days and two nights without fire, candle, straw,
or any thing to lie on but an old blanket.
Afterward when he got some straw for a bed, for want of air,
through the damp and stench of his dismal lodging, it was no Wonder he fell sick;
and after nine days confinement in this contagious hole, he seemed at the point of death,
when the fear of being questioned for murdering him,
incited the cruel marshal to let him out,
and suffer him to return to his fellow-prisoners, with whom he continued several months,
till released by the king`'s proclamation.
He was also confined in Ipswich jail some time,
for refusing to take the oath of allegiance,
and at last laid down his life in the White-lion prison, Southwark, as above related.

In this year also William Caton departed this life at Amsterdam.
His service was much in that country; of his religious disposition,
convincement and qualifications for usefulness in society,
a pretty full account having been given, at his first introduction into this history,
it seems unnecessary to enlarge thereupon here,
further than to remark that besides his literary accomplishments and religious conversation,
being remarkable for the courteousness and affability of his disposition,
he engaged the general esteem of those who were acquainted with him.
His person while living, and his memory after his removal, were much respected,
even by persons of consequence in that state.
