== Chapter XIV.

[.chapter-synopsis]
* The Parliament convened at Oxford, pass the Five-mile Act.
* Friends suffer by this Act though not made against them
* Several Friends come from the Country to London, to visit and help their Brethren in this calamitous Season
* George Fox still a Prisoner at Lancaster
* From thence removed to Scarborough Castle
* Where his Imprisonment is very severe
* His Friends debarred from visiting him
* Several Persons come to dispute with him
* Menaces added to the Rigour of his Imprisonment
* At last by Application to the King he obtains his Release
* The City of London laid waste by Fire
* Bull and Mouth Meeting-house destroyed
* Grace Church-street Meeting-house built
* George Fox travels through several Counties to London
* His Labour and Travels in establishing Discipline amongst his Friends
* Dissertation on Discipline.

As the plague still continued its ravages in the city of London,
the parliament was convened this year at Oxford:
but the joint calamities of war and pestilence,
which at this time distressed the city and the nation,
seem to have made no profitable impression on the members of this parliament,
so as to incline them to a better temper towards the non-conformists;
for instead of being humbled in their minds, or mollified in their tempers;
instead of sympathizing in the general distress, or conforming to the occasion,
and attempting a reformation of the dissolute manners of the age, as if neither war,
pestilence, or any symptom of divine displeasure, were calamities of equal magnitude,
with the existence of non-conformity, they proceeded to enact a fresh penal law,
commonly known by the name of _The Oxford five-mile Act,_
which received the royal assent October the 31st, 1665.
It was entitled, _An Act to Restrain Non-conformists from Inhabiting Corporations;_
the preamble to which sets forth,

[.embedded-content-document.legal]
--

&hellip;that divers Parsons and others in holy orders,
not having subscribed the act of uniformity,
have taken upon them to preach in unlawful assemblies,
and to instil the poisonous principles of schism and rebellion
in the hearts of his Majesty`'s subjects to the church and kingdom:
Be it therefore enacted,
that all such non-conformist ministers shall take the following oath,

_I, A. B. do swear that it is not lawful upon any pretence whatsoever;
to take up arms against the king;
and that I do abhor that traiterous position of taking
arms by his authority against his person,
or against those that are commissioned by him, in pursuance of such commissions;
and that I will not at any time endeavour any alteration
of government in church or state._

And all such non-conformist ministers shall not after the 24th of March,
unless in passing the road, come or be within five miles of any city,
town-corporate or borough, that sends burgesses to parliament,
or within five miles of any parish, town and place, wherein they have,
since the act of oblivion, been parson, vicar or lecturer, etc.,
or where they have preached in any conventicle, on any pretence whatsoever,
before they have subscribed the abovesaid oath,
before the justices of peace at the quarter sessions for the county in any court,
upon forfeiture for every such offence of forty pounds, one third to the king,
another third to the poor, and a third to him that shall sue for it.
And it is further enacted, that such as shall refuse the oath aforesaid,
shall be incapable of teaching any public or private schools,
or of taking any boarders or tablers to be taught or instructed,
under the penalty of forty pounds, to be distributed as above.
Any two justices of peace,
upon oath made before them of any offence committed against this act,
are empowered to commit the offender to prison for
six months without bail or mainprize.

--

This bill met with great opposition in the house of lords,
upon account of its enforcing an unlawful and unjustifiable oath.
Even the Earl of Southampton (Clarendon`'s intimate friend,
who in concert with Archbishop Sheldon, Ward, Bishop of Salisbury, and their creatures,
is said to be the contriver and promoter of this.
act) was strenuous in the opposition,
declaring the oath to be such as no honest man could take:
But the heat and passion of party prejudice prevailed against propriety,
reason and humanity, and the bill was passed into a law.

Now though this act was principally aimed at the Presbyterians and Independents,
who had formerly enjoyed the emoluments of the church, suffer by so called,
and been incumbents of parishes,
yet it was also frequently enforced against the people called Quakers, who,
because for conscience sake they could not swear,
were upon this law prosecuted and imprisoned,
as well as the other numerous penal laws of this reign.

The pestilence having carried off,
according to most accounts near one hundred thousand of the inhabitants of London,
in the course of this year; and amongst them many of the people called Quakers,
who left many poor widows and fatherless children; and this people,
from their first existence having been distinguished for their charitable regard towards,
and care of each other, this calamity of consequence must awaken their tender feelings:
But the number of objects demanding their brotherly
assistance and attention at this period,
proving too burdensome for the men, who held occasional meetings in the city,
for the purpose of providing for the necessity of the poor:
they called upon some of the most grave and tender-hearted of their
female friends to be assistants to them in this necessary care,
who readily complying, met for this purpose once a week at London.

Such was the fraternal regard,
and feeling of sympathy which prevailed amongst this people, come out of at this time,
that not only the resident inhabitants were exercised in this care; but several,
as George Whitehead, Alexander Parker, Josiah Coale and others felt themselves incited,
by the pointings of duty, to come out of the country to London,
as with their lives in their hands, in faith in divine protection,
and resignation to the divine will, to suffer with their friends there,
whatever might be permitted to befal them;
to strengthen and encourage them by their examples
and exhortations to keep up their meetings;
to edify them with their gifts; and to visit and comfort the sick and imprisoned;
and through all were mercifully preserved from the infection,
and from imprisonment in the season of danger.

In the mean time George Fox,
whose solicitude for the welfare of the society which he
had been first made instrumental to gather and establish,
was unremitted,
found himself secluded from the opportunity of extending his pastoral
and parental care towards them in this season of their accumulated distress;
having been for three years kept a prisoner so close,
that to his friends he was as a man buried alive,
We left him a prisoner in Lancaster castle,
under a clandestine sentence or record of premunire, whence the neighbouring justices,
who had been active in his prosecution,
perceiving that the arbitrary proceedings against him at the assizes,
being publicly known, and freely canvassed, exposed them to public censure and disrepute,
determined to exert their endeavours to procure his removal to some remote prison
as the most probable means to make the general dislike of their conduct die away.
In order to effect their purpose, it seems they sent up some virulent, though groundless,
accusations to the king and council,
and obtained an order from them to remove him from Lancaster,
accompanied with a letter from the Earl of Anglesey, importing,
"`that if those things were found true against him, with which he was charged,
he deserved no mercy.`"
Thus when men are once tempted to transgress the bounds of rectitude,
they too frequently endeavour to cover their former
errors by the commission of more and greater.
These men well knew they could convict him of no offence,
but his conscientious declining an oath,
or their present ill-will would have incited them to have done it;
yet to erase the memory of their past injurious conduct, they added wrong to wrong,
by hidden misrepresentations,
rendering him obnoxious to government in order to screen their own misconduct,
and satiate their malice,
by aggravating the unmerited sufferings of a man who had done them no wrong.

When they were prepared for his removal,
the under-sheriff and bailiffs fetched him out of the castle,
when he was so weakened by lying in that cold, wet and smoky prison,
that he could hardly go or stand.
They took him into the jailer`'s house to Colonel Kirby and others,
who called for some wine to give him;
but considering them as the principal authors of his imprisonment, he,
who detested all insincerity, would not accept their show of kindness,
when suffering so severely under the effects of their malice.
The horses being ordered out, he desired to see their order,
if they intended to remove him, insisting "`that he was not the king`'s prisoner,
but the sheriff`'s;
for they and all the country knew he was not fully heard at the last assize,
nor suffered to show the errors in the indictment, which were sufficient to quash it:
But they all knew there was no sentence of premunire passed
upon him therefore being still the sheriff`'s prisoner,
he again desired to see their order.`"
But they would show him none but their swords, and instead thereof haled him out,
and lifting him upon one of the sheriff`'s horses,
hurried him that night fourteen miles to Bentham, though he was so very weak,
that he was hardly able to sit on horseback;
he was treated with much rudeness and incivility,
which gave him occasion to remark to the officers, that he received neither Christianity,
civility nor humanity from them.

At Bentham being delivered into the custody of a fresh guard,
he was taken on to Giggleswick that night, although exceeding weak and weary:
All this while he was kept in ignorance of the place of his destination;
and upon his inquiry of some of the soldiers, who guarded him, whither he was to be sent?
Some of them told him "`beyond sea;`" others "`to Tinmouth castle.`"
Being guarded thence to York, by troopers under Lord Frecheville,
he fell into better hands, for they treated him with civility;
admitted his friends to visit him on the way, and allowed him two days rest at York,
from whence the marshal and four or five soldiers conveyed him to Scarborough castle,
his appointed prison.

One may naturally imagine the Lancashire justices must have made
a dreadful representation of the danger to be apprehended from
him (although they had no matter of fact to support their charge),
for he was here closely confined like a prisoner of state, under a military guard,
a sentinel being placed on his room in the castle;
but he being so weak as frequently to faint,
for a while they permitted him at times to walk out for air,
with a sentinel to attend him.
He was soon removed from his first room to another little better, if not worse,
than that in which he was confined at Lancaster, being so open as to admit the rain,
and exceedingly offensive with smoke.
Insomuch that the governor, Sir Jordan Crofland, in company with Sir Francis Cobb,
coming one day to see him, having a little fire, the room was so filled with smoke,
that they could hardly find their way out.
He laid out about fifty millings to keep out the rain, and prevent the smoke;
which when he had done, and thereby made it tolerable,
he was removed into another still worse, without chimney or fire-place,
so open to the sea-side, that the wind drove in the rain so violently,
that the water poured in upon his bed and about the room,
till he had it to skim up with a platter.
And when his clothes were wet, being without fire to dry them,
his body was benumbed with the cold,
and his fingers swelled to double their natural size.
Few or none of his friends would be suffered to come to him, even to bring him food,
wherefore he was under the necessity of hiring others to do it.
Against this hard treatment he pleaded the indulgence which Paul received from the Romans,
who were not christians but heathens.
But at the same time whilst his friends were debarred from admission to him,
numbers of others were freely admitted, whom curiosity drew to gaze upon him,
or who came to dispute with him.

Of these latter he had visitants of most denominations, Episcopalians,
Presbyterians and Papists,
particularly of the last (the governor being of that persuasion)
by whom he was much teased with the advancing of their doctrines,
as the infallibility of the Pope, and such like;
but he seemed seldom at a loss for a suitable reply
to all that came to discourse or dispute with him,
being actuated through all with an innocent boldness in confuting error,
and contending for the true faith according to scripture testimony.

To the rigour and hardships of his imprisonment,
his keepers added frequent menaces in order to terrify him.
The deputy governor once told him, That the king,
knowing he had a great interest in the people, had sent him thither;
that if there should be any stirring in the nation, they should hang him over the wall.
He replied to this menace, If that was what they desired, and it was permitted them,
he was ready, for he never feared death or sufferings in his life;
but was known to be an innocent, peaceable man, free from stirrings and plottings,
and one that fought the good of all men.

At length his patience having surmounted the hardships he was exposed to,
and his innocence pleading in his favour with his keepers, they gradually relented,
relaxed their severity, and finally became favourable and respectful to him.
The officers would frequently say, he was as stiff as an oak, and as pure as a bell,
for we could never bow him.

After he had been a prisoner in Scarborough castle above a year,
he laid his case in writing before the king, relating the manner of imprisonment,
and the hard treatment he had met with; subjoining,
that he was informed that no man could deliver him but the king himself.
His friend Esquire Marsh exerted his endeavours to procure success to his application,
and through the master of requests, obtained the king`'s order for his release,
the substance whereof was,
"`that the king being certainly informed that George
Fox was a man principled against plotting and fighting,
and had been ready at all times to discover plots rather than make any,
etc. therefore his royal pleasure was that he should be released from his imprisonment.`"
As soon as this order was obtained, it was quickly brought to Scarborough,
and delivered to the governor, who upon receipt thereof immediately discharged him,
and gave him the following passport.

[.embedded-content-document.legal]
--

Permit the bearer hereof George Fox, late a prisoner here,
and discharged by his majesty`'s order, quietly to pass about his lawful occasions,
without molestation.
Given under my hand at Scarborough castle this 1st day of September, 1666.

[.signed-section-signature]
Jordan Crosslands

[.signed-section-context-close]
Governor of Scarborough Castle.

--

George Fox when he received his release was willing to make the governor
an acknowledgment for the civility and kindness he had lately shown him,
who would not receive anything, but told him,
"`Whatever good he could do him or his friends, he would do it,
and never do them any hurt:`" which promise his consequent conduct made good,
being humane and favourable to his friends through the remainder of his life.

It was just at this time (after the city and suburbs of London were so greatly depopulated
by the plague) that the said city was laid in ashes by a dreadful conflagration,
which broke out in Pudding-lane, over against the place where the Monument is erected,
whereby in a few days time the greatest part of the city within the walls was consumed:
The inhabitants, in amazement, terror and despair, were forced to flee for their lives,
with what goods they could save, into Moorfields, where they lodged in huts and tents.
Many families, who were last week in opulence, were now reduced to great distress;
and for the space of three days it spread devastation,
and baffled all human exertions to stop his progress.
At last it ceased almost as wonderfully as it began, when all human efforts failed,
it seemed to die away, and be extinguished on every side,
as by a peculiar interposition of providence;

Various were the conjectures formed concerning the causes and authors of this conflagration;
but as no investigation led to certainty, what cause it arose from;
why may we not safely acquiesce in the opinion of
the most pious and religious sort of that age,
who ascribed it to the visitation of heaven upon
a city shamelessly immersed in vice and immortality,
and which had not been sufficiently humbled by the pestilence of the foregoing year?

The Bull and Mouth meeting-house being destroyed by the fire,
the meetings of this people continued to be held regularly
as they fell in course in their other meeting-houses,
which had escaped, viz. Wheeler-street, Peel, Devonshire-house,
etc. and they had some respite and ease from violent
persecution and disturbance for a season,
until the city was in a great measure rebuilt.

But their numbers increasing, they had the courage and resolution, in faith,
to build a new meeting-house this year in White-hart court, Grace-Church-street,
which from its central situation became afterwards the place for their yearly meetings.
Here, as well as in other places,
they met with frequent disturbance by the trained bands and informers,
being many of them often haled out by force, and often forcibly kept out,
they were obliged to hold their meetings in the street.

It appears a manifest evidence of divine protection,
supporting and prospering this society,
that they were not only preserved steadfast to the truth in which they believed,
in patient resignation to the divine will, and a blameless demeanour toward mankind,
under a successive train of severe trials; but continually increased their numbers,
with the powers of the world against them.

The history of this people from their first rise to this
time presents one continued series of persecution,
through the successive revolutions of government; the secular powers,
urged on by the ecclesiastics,
to whose power and emolument their principles were adverse, exerted every effort,
short of capital punishment, to lessen their numbers, and stop their progress,
and from man they had little countenance; yet notwithstanding,
by the support of the divine hand, the society increased,
so that they were now become a numerous body.

As soon as George Fox was freed from his long confinement,
he proceeded as usual in his religious labours and services.
He passed through part of Yorkshire, Derbyshire and Nottinghamshire,
visiting his friends, and having many large through and edifying meetings amongst them;
notwithtstanding some attempts to have him taken again, which were frustrated,
for persecution was still hot in some counties.
So proceeding southward through divers counties, he came to London;
but he was so weak with his cruel and hard imprisonments
for the greatest part of three years,
and his joints so stiff and benumbed,
that it was with difficulty he could mount his horse or alight.

The numbers and the exigencies of the society of meeting being increased,
as before remarked, he saw it necessary to increase the number of meetings of discipline,
for the good government of the church.
The service of these meetings seems to have gradually opened,
as the state of the society required.
In the year 1660 we have taken notice of a general meeting for church affairs,
held at Skipton in Yorkshire, which had then been held some years,
wherein the business was confined to the taking an account of their sufferings,
and to the making collections for the relief of their poor.
Afterwards quarterly meetings were established in London and in other parts,
which in addition to the former subjects of attention,
had the charge of the reputation of the society, to watch over the members,
and admonish and exhort such as might appear disorderly and uncircumspect in their conversation,
not agreeable to the strictness of their religious profession;
besides the women`'s meetings, which had chiefly the care of poor widows and orphans.
But during his stay in London at this time,
he felt it his concern to recommend the establishing
five monthly meetings of men and women in that city,
to transact such meetings,
matters as had before been the employment of the quarterly meeting,
and to unite in a general meeting once in three months as before, for mutual counsel,
advice and deliberation,
in relation to the common affairs and care of the whole body in the city.
Having stayed here to see his recommendation in part reduced to practice,
and his friends settled in comely order;
the advantage resulting therefrom appeared to him so evident,
that he found it his duty to make a progress, first through the adjacent counties,
afterwards many of the more remote,
to dry places get these monthly meetings in like manner
established amongst friends throughout the nation;
having a clear view opened to his mind of the monthly meetings.
method and order,
wherein the monthly and quarterly meetings were to be established and conducted,
which he communicated by letter to such counties as he could not visit in person,
and to his friends in Scotland, Ireland, Holland, Barbados,
and the continent of America; whom he afterwards, visited in person,
to assist and promote the regular establishment thereof.

After monthly meetings were established, the service of them still extended.
George Fox after his circuit through the counties, returned to London;
there he perceived the expediency of of the monthly
meetings taking cognizance of the marriages,
orderly proceedings towards marriage, and therefore recommended,
"`That proposals of marriage should be laid before the men`'s monthly meetings,
that friends might see,
that the relations of those who proceeded to marriage were satisfied,
that the parties were clear from other engagements,
and that widows had made provision for their first
husband`'s children before they married again,
and whatever other inquiries were necessary for keeping all things clean and pure,
in good order and righteousness, to the glory of God.`"

Thus was this valuable man engaged in long and painful travels,
under great infirmity of body in consequence of the hardships
he had lately passed through in his dismal prisons,
as himself expresseth, "`I was so exceeding weak,
I was hardly able to get on or off my horse`'s back;
but my spirit being earnestly engaged in the work the Lord had concerned me in,
and sent me forth about, I travelled on therein, notwithstanding the weakness of my body,
having confidence in the Lord that he would carry me through, as he did by his power.`"
From London he continued his travels to other counties,
till the meetings for discipline were settled in all, or most parts of the nation,
where by the care over the members of the society was widely spread,
and the body became compacted together in a mutual concern
for each others temporal and spiritual prosperity.
The discipline which George Fox was singly instrumental thus to establish,
notwithstanding the contemptuous light in which he has been viewed,
and represented by sundry writers,
bearing the marks of a peculiar wisdom in the contrivance,
and goodness of heart in the ends in view,
realized in the beneficial effects it then had, and hath since continued to produce,
seems to demand a particular disquisition in a work of this nature,
and this appears the proper place to introduce it.

[.old-style]
=== A Dissertation on the Discipline exercised amongst the People called Quakers

[.alt.centered]
Sect. I

[.small-break]
'''

The first meeting for church affairs that I find any clear account of,
was held at Skipton in Yorkshire, whether occasionally by particular appointment,
or at certain stated times, doth not appear.
Of this meeting, the nature and use is described by George Fox in his journal as follows:

[quote]
____
To this meeting came many friends out of most parts of the nation;
for it was about business relating to the church,
both in this nation and beyond the seas.
Several years before, when I was in the North,
I was moved to recommend to friends the setting up of this meeting for that service;
for many friends suffered in divers parts of the nation,
their goods were taken from them contrary to law,
and they knew not how to help themselves, or where to seek redress;
but after this meeting was set up, several friends, who had been magistrates,
and others who understood something of the law, came thither,
and were able to inform friends, and assist them in gathering up the sufferings,
that they might be laid before the justices, judges or parliament.
This meeting had stood several years,
and divers justices and captains had come to break it up;
but when they understood the business friends met about,
and saw friends books and accounts of collections for the relief of the poor:
how we took care, one county to help another, and help our friends beyond sea,
and provide for our poor, that none of them should be a charge to their parishes,
etc. the justices and officers confessed that we did their work,
and would pass away peaceably and lovingly, commending friends practice.
____

By this account it appears as if this was a general meeting for the whole nation,
or a great part thereof, and fixed in this town as a central situation,
the greatest body of this people in the earliest times being in the North.

But about the year 1666, the society being increased, and their sufferings multiplied,
it be came requisite to establish a meeting of discipline in each county,
to be held once a quarter;
and afterwards again to subdivide these into several monthly meetings,
which order is continued to this day.

These were termed monthly meetings, because in the most general way,
they were appointed to be held once a month; yet as exigency,
and multiplicity of business, in large cities particularly,
pointed out the necessity of shorter intervals, some are held every two or three weeks,
and some at greater intervals.
They are also in such places composed sometimes of
the members of one particular meeting only;
but most generally through the counties consist of several contiguous meetings;
and in this case it is the practice in many places for friends
of each particular meeting to hold a preparative meeting,
to inquire into the state of the society in that meeting, in respect to want,
to general conduct, or to the sufferings of their members;
and to appoint representatives to report what may appear needful to the monthly meeting.
Four or six particular meetings usually compose a monthly or general men`'s meeting.

These monthly meetings are fewer or more in number in each respective county,
as the number,
situation and circumstances of the members in each might render most expedient.

The setting up of monthly meetings did not Quarterly
occasion the abolition of quarterly meetings;
but the former taking upon them the executive part of the discipline,
which had before employed the latter, it appeared conducive to general benefit,
that the quarterly meetings should still continue,
as superintendent and assistant by ad vice to the monthly meetings.
It was therefore agreed, that all the monthly meetings in a county should,
by their representatives, and other members,
constitute the quarterly meeting for that county, which all the most zealous,
and judicious friends, in a general way thought it their duty to attend,
for the mutual communication of their sentiments, the advice and help one of another,
especially when any business seemed difficult,
or a monthly meeting was tender of determining a matter.
These monthly and quarterly meetings in some counties were fixed,
or held mostly in the same place;
in others they were held in rotation at different
places as the members found it most convenient.

Sometime after monthly and quarterly meetings were established, viz. in the year 1669,
it was found expedient, and agreed upon, to hold a general meeting in London,
representative of the whole body in England,
and all other parts where any of the society were settled,
which having been thenceforward held annually,
is denominated the yearly meeting in London.

This meeting is constituted of representatives deputed
from each quarterly meeting in England,
from the half-years meeting in Ireland, and sometimes from other parts,
yet without restraining any member in unity with the society from attending.
And such places in Europe and America,
as by their remote situation cannot conveniently send representatives thereto,
keep up a correspondence with this meeting by epistles.

But as the first establishment of the yearly meeting was in a time
of great suffering under a multiplicity of penal laws,
the collecting accounts of these sufferings in order
to lay them before government and seek redress,
took up much of the attention of that meeting at that time,
as appears from the queries of that meeting, the three first of which are,

[.numbered-group]
====

[.numbered]
1+++.+++ What present prisoners?

[.numbered]
2+++.+++ How many discharged last year?
When, and how?

[.numbered]
3+++.+++ How many died prisoners?
As many exigencies in suffering cases might arise
in the intervals between the yearly meetings,
demanding a more speedy application for relief than the delay in
waiting for the succeeding yearly meeting might occasion,
pointed out the expediency of establishing a committee of correspondence
in London and the several counties and other places,
to be consulted in the intervals between the yearly meetings up on any emergency:
The members appointed correspondents in London, with others who may be in the city,
meet the sixth day in every week,
for the purpose of considering and consulting upon such matters
as may be laid before them by any of the country correspondents;
particularly any suffering cases of friends that may want their counsel or assistance:
and from thence is called the meeting for sufferings, and is a meeting for record.

====

This economy hath ever since subsisted amongst this people,
whereby the great ends of religious society, real devotion of heart towards God,
a careful and circumspect conversation in righteousness and honesty amongst men,
and the mutual edification of each other in love, have been materially promoted,
and a people dispersed in sundry quarters of the world rendered a compact body,
engaged in a zealous and mutual concern for the promotion of peace
and piety amongst themselves and mankind in general.

For by this economy the care of the body at large
may be conceived to extend to every member;
and on the other hand,
every member to become accountable for his conduct to the body at large,
as well as the object of their brotherly aid, if his sufferings or want demanded it.
For the part being always considered as subordinate to the whole,
and the lesser meetings to the more general for direction, assistance and advice;
particular meetings to the monthly meetings, monthly to quarterly,
and the quarterly meetings of the counties to the yearly meeting in London:
And the religious care devolved upon each meeting over its own members,
operating within its own sphere;
that of particular meetings exercised in the inspecting of the state,
the conduct or the necessities of the members and families belonging to them respectively:
Again,
the quarterly meetings taking cognizance of the state and reports of the monthly meetings,
giving them counsel and instructive advice, according as exigency required;
and collecting from their report,
a general report of the state of the society in the county, to the yearly meeting,
by which intelligence the said meeting is furnished
with the subjects of their deliberation and advice:
The result of which deliberations,
and the advice appearing requisite to the state of the society,
are generally transmitted to the counties in an epistle from the said yearly meeting.

[.small-break]
'''

[.alt.centered]
Sect. II.

[.alt.centered]
Of the Manner of conducting these Meetings.

[.small-break]
'''

From these meetings of discipline no members of the society are excluded;
but every one in unity hath liberty to attend and express
his sentiments with freedom in the fear of God,
upon the subject matters of deliberation; but the sense of the subordinate meetings,
in particular cases,
is generally understood by the representation of their deputed representatives.
No chosen or deputed officers preside in their meetings,
after the manner of the assemblies of other societies,
"`Christ only being their president,
as he is pleased to appear in life and wisdom in any one or more of them;
whatever be their capacity or degree, the rest adhere with a firm unity,
not of authority, but conviction, which is the divine authority,
and the way of Christ`'s power and spirit in his people; making good his blessed promise,
that he would be in the midst of his,
where and whenever they were met together in his name, even to the end of the world.`"^
footnote:[William Penn`'s [.book-title]#Rise and Progress#]

Yet they have a clerk in each meeting,
who generally undertakes the office voluntary at the desire of the meeting,
whose business is to take minutes of their proceedings: For in all those meetings,
yearly, quarterly and monthly, a regular record is kept of all their proceedings,
appointments and subjects of deliberation;
of their collections and disbursements generally in a distinct book;
of the sufferings of their members and other necessary matters;
and as for these purposes they have several separate records in sundry parts,
different members are engaged in keeping them in regular order,
one undertaking the care of one record, and another of another.

And as the business of these meetings is of a solemn and religious nature,
they are preceded by a solemn meeting of worship; that friends by united worship,
and waiting in conjunction for the influence of divine wisdom and power,
may thereby feel their minds properly prepared to
assist in the weighty business of the day;
for it is a principle of belief with them,
that under the influence of the holy spirit this discipline was originally established,
and that the same divine influence is the requisite qualification
for conducting it with propriety to edification,
as well as for the work of the ministry, and every other service of the church.
William Penn, in the treatise before quoted, records his experience,
"`That these meetings being opened, and usually concluded in solemn waiting upon God,
he is sometimes graciously pleased to answer them
with as signal evidences of his love and presence,
as in any of their meetings of worship.`"
And it appears almost self-evident,
that a number of men sitting down together under an awful
sense of the presence of the All seeing eye,
the witness of their transactions, and of the frame of their hearts,
are under the properest temper of mind for deliberating and deciding
upon the subject of religion and its concerns.

[.small-break]
'''

[.alt.centered]
Sect. III.

[.alt.centered]
Of the Objects of Discipline in the sundry Meetings.

[.small-break]
'''

The monthly meetings may not be improperly termed the executive power of this society,
as it is their business to apply the rules of the discipline
to the particular cases and exigencies of the individuals.
The subjects of their inquiry and dealing will not improperly be described in
the order that the inquiries of the quarterly meeting are made into their care;
as contained in the following queries,
which are answered by each monthly meeting to the quarterly meeting.

[.numbered-group]
====

[.numbered]
1+++.+++ Are meetings for worship and discipline duly attended;
and do friends avoid all unbecoming behaviour therein?

[.numbered]
2+++.+++ Are love and unity preserved amongst you,
and do you discourage all tale-bearing and detraction?

[.numbered]
3+++.+++ Is it your care by example and precept to train up your children in a godly conversation,
and in frequent reading the holy scriptures; as also in plainness of speech,
behaviour and apparel?

[.numbered]
4+++.+++ Do you bear a faithful and christian testimony against the receiving or paying tithes,
priests demands or those called church rates?

[.numbered]
5+++.+++ Are friends careful to avoid all vain sports, places of diversion, gaming,
and all unnecessary frequenting of ale-houses or taverns, excess in drinking,
and intemperance of every kind?

[.numbered]
6+++.+++ Are friends just in their dealings,
and punctual in fulfilling their engagements and are they advised
carefully to inspect the state of their affairs once in the year?

[.numbered]
7+++.+++ Is early care taken to advise and deal with such as appear
inclinable to marry contrary to the rules of our society;
and do none remove from or into your monthly or two weeks-meetings without certificates?

[.numbered]
8+++.+++ Have you two or more faithful friends deputed in each
particular meeting to have the oversight thereof?
and is care taken when anything appears amiss that
the rules of our discipline be put in practice?

====

Of the zeal of the members of this society in the attendance or their religious meetings,
this history abounds with remarkable instances: neither penal laws, personal abuse,
long and hard imprisonments, loss of substance, nor the prospect of banishment,
could damp the ardour of their zeal in keeping them up, evidencing, that peace of mind,
resulting from discharge of duty, was of more consideration with them,
than fleshly ease or worldly enjoyments.
At this time the society being composed of members, who, having received their religion,
not by tradition or education, but by convincement of their understandings,
and conversion of heart, acted upon principle, and attended meetings,
from a conscientious persuasion of duty.
Although in these perilous and suffering times some were
concerned to encourage and strengthen their brethren herein,
yet I apprehend at this time it was not needful to engage much care of the monthly meetings,
to incite them to a duty, of the obligation whereof they were inwardly convinced.
But in process of time, individuals falling from their first love,
were for introducing flesh-pleasing doctrines and
a temporizing disposition to evade suffering,
which occasioned the following minute of the yearly meeting, 1675.

[.embedded-content-document.minute]
--

It hath been our care and practice from the beginning,
that an open testimony for the Lord should be borne,
and a public standard for truth and righteousness upheld in the power and spirit of God,
by our open and known meetings,
against the spirit of persecution that in all ages hath sought to lay waste God`'s heritage,
and that only through faithfulness, constancy and patience,
victory hath been and is obtained:
So it is our advice and judgment that all friends gathered in the name
of Jesus keep up these public testimonies in their respective places,
and not decline, forsake or remove their public assemblies because of informers,
or the like persecutors;
for such practices are not consistent with the nobility of truth,
and therefore not to be owned in the church of Christ.

--

Others afterwards born in the society,
and holding the profession of their religion in the form,
as the religion of their education,
without effectually submitting to the converting power thereof,
giving way to thoughtlessness, or secular engagements,
grew remiss in this reasonable service,
the neglect whereof gave occasion to its becoming an especial part of the care
of monthly meetings to apply their endeavours to remedy this deficiency.
The means they employed for this purpose were earnest exhortation,
directed to convince them of the reasonableness and obligation of this duty;
exciting them by powerful persuasions to a diligent attendance of religious meetings,
not only on the first day of the week,
whereon even the laws of the land prohibit us to transact world affairs;
but to manifest their love to God and devotion to duty by
sacrificing that portion of time on other days,
set apart for the important purposes of worshipping God, and edifying the body in love.
These endeavours were frequently used by members deputed by the monthly meetings,
when the deficiency of any member was obviously remarkable,
and sometimes in a more private way, as any friend found a concern on his mind,
to labour with a brother for his good.

Love, the characteristic of discipleship, and unity, the bond of society,
were cultivated with uncommon care amongst them,
and eminently distinguished those of the first generation,
"`it being`" (as William Penn testifies) "`a common remark
in the mouths of all sorts of people concerning them,
they will meet, they will help and stick to one another:
look how the Quakers love and take care one of another: And if loving one another,
and having an intimate communion in religion, a constant care to meet and worship God,
and help one another, be any mark of primitive Christianity,
they had it in an ample manner.`"
In this age they had many skilful watchmen, and especially George Fox,
who were diligent in detecting the approach of every danger
of weakening or dissolving the bonds of amity and unity,
and faith fully warning, and carefully guarding,
the different classes of the society against the danger,
as we have seen in the case of James Nayler,
and shall further have occasion to remark in the sequel.

As to the preservation of love and unity in general,
the discipline of this society extends only to caution and admonition;
but in some cases where ambitious,
envious or refractory spirits have arisen to head a party,
and cause rents and divisions in the society, they have been constrained,
for preventing the evil consequences,
publicly to testify against them and their practices; but such instances have been rare,
there being, I believe, no society that havc been more careful to maintain unity,
or avoid the occasions of contention than this.

And as to differences about matters of property,
it is an established rule with them that all disputes on this account
between two members be referred to the determination of judicious
and impartial men chosen by the parties from among their brethren.
For brother to go to law against brother amongst them, is deemed utterly a fault,
as among the primitive christians, and commencing suits at law,
except in cases of necessity, and with the consent of the monthly meeting,
is deemed an absolute breach of good order, cognizable to the society.
By this branch of discipline much expence,
perplexity and vexation is saved to individuals, and matters as justly determined,
as by pursuing them through the intricacies of the law.

And as private animosities and differences about matters
of property have a tendency to interrupt unity,
introduce contention and propagate parties and divisions in the church,
it hath been the care of this society in their collective
capacity to give warm and pressing advice to monthly meetings
to put a speedy end to all difference arising amongst them;
and as the original of private animosities or dislike is often from reflections
and insinuations tending to injure the reputation one of another,
the latter part of the query is properly subjoined,
directing to the discouragement of tale-bearing and detraction,
as being an unchristian-like practice, having a tendency to sow discord among brethren.

We come now to the third head of discipline, and that very important one,
the religious education of youth, which appears, especially in these early times,
to have engaged the care and attention of the church
in a degree proportioned to the importance thereof,
both by a constant recommendation,
that parents should instruct their children in the principles of the christian religion,
inure them to a frequent reading of the holy scriptures, to habits of industry,
temperance and sobriety; preserve them from corrupting company,
and instil into them sense of the necessity and advantages
of a religious circumspect conversation;
as also train them up in plainness of habit and speech,
agreeable to the simplicity of their profession,
as well as in necessary and useful learning;
and by a constant inquiry how this advice is put in practice.
The direction of the yearly meeting on this subject is,
"`wherever a deficiency of this sort appears,
that monthly and quarterly meetings stir up those concerned to their duty therein.`"
Particularly in the year 1731 this weighty subject
seems to have engaged their very serious consideration,
which produced the following lively recommendation.

[.embedded-content-document]
--

Inasmuch as we have a large body of youth growing up, the offspring of friends,
these call for our especial care and concern,
that they may be preserved in the way of truth, in which our forefathers walked;
and in order thereto, we tenderly recommend to all parents and guardians, First,
that they take heed to themselves,
that their own spirits be rightly seasoned and directed
for the help and good government of their children,
and then, that they have a constant watchful eye in love over them for their good,
and keep them as much as possible within their notice and observation;
for this we are sensible of,
that the miscarriages of youth have very much proceeded
from their being imprudently indulged,
or left to themselves;
by which means they become exposed to the danger of evil examples on the one hand,
and vicious corrupt principles on the other,
with which the world too much abounds and therefore we earnestly and tenderly
advise all parents and guardians to be watchfully concerned in this respect,
and that they take all proper occasions, both by example and instruction,
to help their children: And that mothers of children, as well as fathers,
(as they have frequently the best opportunities) would take particular
care to instruct them in the knowledge of religion and the holy scriptures;
because it hath been found by experience,
that good impressions made early on the tender minds of children,
have proved lasting means of preserving them in a religious life and conversation.
This practice was enjoined strongly upon the people of Israel by Moses and Joshua,
the servants of the Lord, who required them to read, or repeat,
the law to their children;
and the apostle Paul takes notice of Timothy`'s being
well instructed in the holy scriptures from a child,
and of the unfeigned faith which dwelt in his grandmother Lois and mother Eunice, 2 Tim. 1:5.
who no doubt had a religious care of his education.

But where parents or guardians are deficient in such their care,
we recommend monthly meetings, that they stir them up thereto,
either by visiting them in their families,
or in such manner as in the wisdom of God they may see meet,
that so the doctrines of the gospel, and a conversation agreeable thereunto,
may be maintained unto all generations.

And in order to render this advice more effectual,
we farther tenderly recommend to all heads of families,
that they do frequently call their children and servants together,
and in a solemn religious way cause them to read the holy scriptures, and in so doing,
that they humbly wait upon God with their families, for instruction and counsel to them,
respecting christian faith and practice according to the former advice of this meeting,
particularly that in the year 1706,
to which in an especial manner we refer on this occasion: which is as follows, viz.

Forasmuch, as next to our own souls,
our children and offspring are the most immediate objects of our care and concern,
it is tenderly recommended to all that are or may be parents or guardians of children,
that they be diligently exercised in this care and concern,
for the education of those committed to their charge,
that in their tender years they may be brought to a sense of God, his wisdom,
power and omnipresence, so as to beget an awe and fear of him in their hearts,
(which is the beginning of wisdom) and as they grow up in a capacity,
to acquaint them with,
and bring them up in the frequent reading of the scriptures of truth;
and also to instruct them in the great love of God, through Jesus Christ,
and the work of salvation by him, and of sanctification through his spirit;
and also to keep them out of the vain and foolish fashions and ways of the world,
and in plainness of language, habit and behaviour,
that being thus instructed in the way of the Lord when they are young,
they may not forget it when old; or however,
that all concerned may be clear in the sight of God,
that they have not been wanting in their duties to them.
And that the labour and travail of friends therein may be more effectual,
it is our tender desire that seasonable opportunities may be taken to wait upon the Lord,
with your children, in your families, for the manifestation of his blessed power,
to make them sensible of his witness and feed of life and grace in their hearts,
in order to beget in them the living knowledge and
love of the truth as it is in Jesus.

--

As to the subject of the fourth query, the receiving or paying of tithes,
I have before explained the grounds of their declining the payment thereof,
and therefore shall not enlarge upon it here, further than to observe,
that being a term of communion, and in their view a testimony of importance,
the violation of this testimony is a breach of unity;
but monthly meetings are instructed to take great pains
to convince the delinquents (who are most commonly such,
not from a persuasion of the claimant having any just right to these demands;
but merely to evade suffering) of their weakness or error,
before they proceed to pass any censure upon them.

A people honestly directing their researches after pure religion,
and the first principles of Christianity,
could not be long in discovering the inconsistency of vain sports and diversions,
such as theatrical exhibitions, horse-racing, dancing, musical entertainments, cards,
dice, and other species of gaming, with the precepts and spirit of the gospel;
to which they are diametrically opposite in their root and origin, nature and tendency;
being not the genuine growth of Christianity,
but a branch from the corrupt root of gentilism,
adopted by professed christians to their hurt.
This people in their search after primitive Christianity,
recurring to the example and precepts of Christ and his apostles,
could not reconcile these diversions to their practice, nor to such precepts as these,
"`For every idle word you must give an account.`"^
footnote:[Matt. 12:36]
"`Pass the time of your sojourning here in fear.`"^
footnote:[1 Pet. 1:17]
"`Use all diligence to make your calling and election sure.`"^
footnote:[2 Pet. 1:10]
"`Let no corrupt communication proceed out of your mouth, but that which is good,
to the use of edifying, that it may minister grace to the hearers; neither filthiness,
nor foolish talking, nor jesting, which are not convenient, but rather giving of thanks.
Let no man deceive you by vain words;
for because of these things cometh the wrath of God upon the children of disobedience.`"^
footnote:[Eph. 4:29-5:4, 5:6]

For these and other reasons,
they thought it their duty both to disuse the attendance of vain sports themselves,
bear their testimony against them, and make it a point of communion,
and an object of discipline, that their members should refrain the attendance thereof,
or be dealt with as transgressors; because they looked upon them to be unlawful,
and evil in themselves, and frequently an inlet to grosser evils,
esteeming them as inventions of Satan or degenerate men,
to draw the minds of mankind out of themselves, throw them off their guard,
deaden the convictions, and stifle the voice of God`'s witness in their consciences,
set them at ease in their sins,
and lay them open to the destructive snares and temptations
of the great enemy of their eternal happiness.

The unnecessary attendance of taverns and alehouses
having a like tendency to draw into unsuitable company,
unsavory discourse, riot and excess of drinking,
is esteemed an equal object of the church`'s care,
to guard every avenue to evil by timely caution and admonition; which if it fail,
and habitual drunkenness overtake any of their members,
if repeated gospel labour to reclaim them prove ineffectual,
the party is to be testified against and disowned.

Justice in trading and dealing was perhaps amongst
no people practised with more scrupulous punctuality,
and conscientious regard, than amongst this people in the beginning;
such a thing as a failure in the punctual payment of their debts according to contract,
much less a bankruptcy, was scarce known amongst them.
Being daily liable by unreasonable fines and forfeitures and exorbitant distraints,
to be stripped of all they had, they were extremely cautious of contracting debts at all;
that the losses they might be exposed to might be purely their own property,
and not that of others; when they contracted them,
they were on this account very solicitous to pay them at a short time.
Their religious principle against every species of luxury,
and superfluity in eating and drinking; in their apparel,
and the furniture of their houses; against frequenting alehouses and vain sports;
reduced their expenses to the necessary support of nature,
which they found did not require much:
And esteeming it a point of duty (when not engaged in higher
service) to be diligently employed in their lawful callings,
they procured thereby more than a sufficiency for their own wants,
without invading any man`'s property.
And it had been well for their posterity,
if they had more universally adopted these prudent maxims of conduct,
and carefully trodden in their footsteps; but too many of the succeeding generations,
giving way to an aspiring spirit, aiming at great things in this world,
and directing the bent of their minds to the amassing of riches,
gave occasion to lively and warm admonitions of the yearly meeting to recur back to,
and imitate the honourable examples of their worthy predecessors,
particularly to the following minute of 1732.

[.embedded-content-document.minute]
--

We find it our duty to remind our respective members,
of the remarkable uprightness and honesty of our friends in the beginning,
in their commerce and converse.
How exact were they in performing their words and promises,
without evasive excuses and insincere dealings!
How careful not to involve themselves in business which they understood not,
nor had stock of their own to manage!
How circumspect not to contract greater debts than they were able to pay in due
time! which brought great credit and reputation to our religious society.
But with sorrow we observe, that, contrary to their example,
and the repeated advice formerly given by this meeting
against an inordinate pursuit after riches,
too many have launched into trades and business above their stocks and capacities;
by which unjustifiable proceedings, and high living,
they have involved themselves and families in trouble and ruin,
and brought considerable loss upon others,
to the great reproach of our holy profession.`"

We therefore recommend to friends in their respective quarterly and monthly meetings,
to have a watchful eye over all their members;
and where they observe any deficient in discharging
their contracts and just debts in due time,
so as to give reasonable suspicion of weakness or negligence,
that friends do earnestly advise them to a suitable
care and necessary inspection into their circumstances,
in order that they may be helped; and if any proceed contrary to such advice,
and by their failure bring open scandal and reproach on the society,
that then friends justifiably may, and ought to testify against such offenders.

--

In the times whereof I am now writing,
there seems to have been little or no occasion for admonition,
this people proved by an undeviating regard to an internal monitor,
that they were shewn what they should do, and what the Lord their God required of them,
to do justly, love mercy, and walk humbly with their God;
so that the first advice we meet with on this subject is in the year 1688,
near twenty years after the establishment of the yearly meeting,
and exhibits a specimen of their watchful care against everything that
might dishonour or defile the reputation of their society.

[.embedded-content-document]
--

Advised that none launch into trading and worldly business
beyond what they can manage honourably and with reputation;
so that they may keep their words with all men, that their yea may prove yea indeed,
and their nay, nay; for whatsoever is otherwise cometh of evil:
and that they use few words in their dealings,
lest they bring dishonour to the truth of God through their forwardness;
and the holy profession of his name and truth; Such are for judgment,
and the judgment of truth ought to be set over them,
that those who abide and walk in the truth may be clear of their iniquities.

--

Their ideas of justice in commerce were not confined
to the regular payment of their just debts;
but extended to prevent all deceit or dishonesty in every shape;
that the fabric of their manufactures should be made
good and substantial in their respective kinds;
of just and lawful measure; and to answer the expectations of the purchaser.
They looked upon it inconsistent with strict justice
to launch into trade beyond their own capitals,
or risk any man`'s property but their own,
on the uncertain probability of future contingencies.
The same religious care to their words and actions
circumscribed them in their commercial engagements,
as in every other part of life.
They found themselves restrained from the too common practice of dealers,
in using a multiplicity of words in their dealing, in which there wanteth not sin,
nor very often deceit.
They trusted to their goods (by the care and honesty employed
in fabricating them) to recommend themselves by their service,
and were very sparing in their verbal recommendations.
They were at a word in buying and selling.
Seeking no unfair advantage; in buying they at once offered what they thought the value,
in selling, at the first word, told the lowest price they would accept,
nor would the habitual method of bargaining in those they had to deal with,
tempt them to vary from their settled rule.

Foreseeing the manifest ill consequences, temporal and spiritual,
which might result from intermarriages with those of different persuasions,
both to individuals, to families, and to religious society; that,
if the apostle thought it expedient for christians all to walk by the same rule,
and mind the same thing; much more those who are connected in this close alliance,
which makes two as one:
But where there is a difference of sentiment and
persuasion about religion and religious worship,
it hath a tendency to divide asunder those who ought to
be united in the closest bonds of affection and unanimity;
to introduce confusion and perplexity in the place of harmony and satisfaction;
to interrupt the peace of families,
and introduce distraction in the great concern of the religious education of children:
On these important considerations,
this society thought it requisite to make it a point of communion,
that their members should marry among themselves,
according to the good order established amongst them;
and in order to prevent the consequences to themselves and the society,
of individuals violating this rule of discipline,
an early care and vigilance is recommended to give suitable attention, by over sight,
timely admonition and zealous endeavours to preserve youth and
others from entangling themselves in improper connections,
or joining in marriage by a priest or otherwise,
contrary to the good order established in the society,
in order to avoid the disagreeable necessity (to preserve their regularity)
of testifying against them as transgressors thereof.

And order to a proper knowledge of their own members, it is a rule with them,
that every professor amongst them,
who removes his or her place of residence shall apply for
a certificate of his or her conduct and conversation,
and their right to fellowship with the society,
from the monthly meeting they remove from, to that they remove into;
and in case of neglecting such application,
the monthly meeting they remove from is to send such recommendation as they can give;
or the monthly meeting they remove to,
upon the observation of a stranger or strangers coming
to reside amongst them and frequenting their meetings,
is to inquire of them whence they came,
and to write for a certificate or character for them.

[.embedded-content-document]
--

Their way of marriage is peculiar to them; and shows a distinguishing care,
above other societies protesting Christianity.
They say that marriage is an ordinance of God,
and that God only can rightly join man and woman in marriage.
Therefore they neither use priest or magistrate; but the man and woman concerned,
take each other as husband and wife, in the presence of divers credible witnesses,
promising to each other, with God`'s assistance, to be.
loving and faithful in that relation, till death shall separate them.
But antecedent to this, they first present themselves to the monthly meeting,
for the affairs of the church where they reside;
there declaring their intentions to take one another as husband and wife,
if the said meeting have nothing material to object against it.
They are constantly asked the necessary questions, as in case of parents or guardians,
if they have acquainted them with their intention, and have their consent.^
footnote:[If it be discovered that any man hath proposed marriage without
first obtaining the consent of the young woman`'s parents or guardians,
he is obliged to condemn such proceeding in writing,
previous to the meeting taking cognizance of the marriage.]

The method of the meeting is, to take a minute thereof,
and to appoint proper persons to inquire of their
conversation and clearness from all others,
and whether they have discharged their duty to their parents or guardians;
and to make report thereof to the next monthly meeting,
where the same parties are desired to give their attendance.
In case it appears they have proceeded orderly, the meeting passes their proposal,
and so records it in their meeting-book.
And in case the woman be a widow and hath children, due care is there taken,
that provision also be made by her for the orphans,
before the meeting pass the proposals of marriage:
advising the parties concerned to appoint a convenient time and place,
and to give fit notice to their relations, and such friends and neighbours,
as they desire should be witnesses of their marriage;
where they take one another by the hand,
and by name promise reciprocally love and fidelity, after the manner before expressed.
Of all which proceedings, a narrative in way of certificate is made,
to which the said parties first set their hands,
thereby confirming it as their act and deed; and then divers relations,
spectators and auditors set their names as witnesses of what they said and signed.
And this certificate is afterward registered in the record
belonging to the meeting where the marriage is solemnized.
Which regular method,
where it hath been by cross and ill designing people for
want of the accustomed formalities of priest and ring disputed,
has been, as it deserves, adjudged in courts of law a good marriage.^
footnote:[In the year 1661, a cause was tried at the assizes at Nottingham,
respecting the validity of a friend`'s marriage.
The case was this: Two friends having been married amongst friends,
lived together as man and wife about two years,
when the man died leaving his wife with child, and an estate in lands of copyhold;
afterwards another friend married the widow.
A person near of kin to her former husband,
brought his action against the present husband with
a view to dispossess them of the land,
deprive the child of its inheritance,
and possess him self thereof as next heir to the woman`'s first husband,
under the plea "`That the child was illegitimate,
as the parents had not been married according to law.`"
In opening the cause, the plaintiffs counsel taking an indecent liberty of expression,
too common in such cases, asserted, that the Quakers went together like brute beasts,
with other unseemly expressions concerning that people.
After the counsel on both sides had pleaded,
judge Archer opened the cause to the jury in the following manner:
"`There was a marriage in paradise when Adam took Eve and Eve took Adam,
and it was the consent of the parties that made a marriage.
As for the Quakers he did not know their opinions,
but he did not believe they went together as brute beasts, but as christians,
and therefore he did believe the marriage was lawful, and the child lawful heir.`"
To confirm his judgment he related this case:
"`A man that was weak in body and kept his bed, had a desire to marry,
and did declare before witnesses that he did take such a woman to be his wife,
and the woman declared she took that man to be her husband.
This marriage being afterward called in question,
all the bishops (he said) did conclude it to be a lawful marriage.`"
Whereupon the jury brought in their verdict in favour of the child, George Fox`'s [.book-title]#Journal.#]

The observance of the aforesaid ceremonies they have refused: not out of humour,
but conscience reasonably grounded; inasmuch as no scripture- example tells us,
that the priest had any other part of old time, than that of a witness among the rest,
before whom the Jews used to take one another: and therefore this people look upon it,
as an imposition to advance the power and profits of the clergy:
and for the use of the ring, it is enough to say,
that it was an heathenish and vain custom, and never in practice among the people of God,
Jews or primitive Christians: the words of the usual form,
as with my body I thee worship, etc. are hardly defensible.
In short, they are more careful, exact and regular, than any form now used;
and it is free of the inconveniencies with which other methods are attended:
their care and checks being so many, and such,
as that no clandestine marriages can be performed among them.

It may not be unfit to say something here of their births and burials,
which make up so much of the pomp of too many called christians.
For births, the parents name their own children;
which is usually some days after they are born, in the presence of the midwife,
if she can be there, and those that were at the birth,
who afterwards sign a certificate for that purpose prepared,
of the birth and name of the child or children; which is recorded in a proper book,
in the monthly meeting to which the parents be long,
avoiding the accustomed ceremonies and festivals.

Their burials are performed with the same simplicity.
If the body of the deceased be near any public meeting-place,
it is usually carried thither,
for the more convenient reception of those that accompany it to the burying-ground.
And it so falls out sometimes, that while the meeting is gathering for the burial,
some or other has a word of exhortation, for the sake of the people there met together.
After which the body is borne away by young men,
or else those that are of their neighbourhood,
or those that were most of the intimacy of the deceased party:
the corpse being in a plain coffin, without any covering or furniture upon it.
At the ground they pause some time before they put the body into its grave,
and if any there should have any thing upon them to exhort the people,
they may not be disappointed;
and that the relations may the more retiredly and solemnly
take their last leave of the body of their departed kindred,
and the spectators have a sense of mortality,
by the occasion then given them to reflect upon their own latter end.
Otherwise they have no set rites or ceremonies on those occasions.
Neither do the kindred of the deceased ever wear mourning;^
footnote:[N.B. Since the time this account was first published, Anno 1694,
some of the posterity of this people have visibly degenerated from
the primitive plainness of their predecessors in this respect;
nevertheless the collective sense and judgment of the church herein, remains the same,
as is manifest by the frequent advice given forth from their yearly and other meetings.]
they looking upon it as a worldly ceremony and piece of pomp;
and that what mourning is fit for a christian to have,
at the departure of a beloved relation or friend, should be worn in the mind,
which is only sensible of the loss: and the love they had to them,
and remembrance of them to be outwardly expressed by a respect to their advice,
and care of those they have left behind them, and their love of that they loved.
Which conduct of theirs, though unmodish or unfashionable,
leaves no thing of the substance of things neglected or undone:
and as they aim at no more,
so that simplicity of life is what they observe with great satisfaction;
though it sometimes happens not to be without the
mockeries of the vain world they live in.
__Thus far William Penn.__^
footnote:[Penn`'s [.book-title]#Rise and Progress#]

--

However obnoxious this society may have been to unmerited calumny on other accounts,
their charity hath been too obvious not to pro cure general approbation;
for while they have been particularly attentive that nothing
should be wanting to the necessary supply of their poor,
that there should be no beggar amongst them, nor any sent to the parish for relief;
and that their children should partake of necessary learning,
and be put out apprentices to suitable trades;
at the same time they have cheerfully paid their
quota to the poor of their respective parishes;
besides private donations by many amongst them to proper objects of any denomination,
which they never desired should be known; their religion being of that cast,
which instructed them to do good to all, but especially to the household of faith.

The sentiments of these people on this subject may be perceived
from the following extract from an epistle of Stephen Crisp.

[.embedded-content-document.epistle]
--

Concerning practical charity ye know it is supported by liberality,
and where liberality ceaseth, charity waxeth cold;
where there is no contribution there is no distribution;
where the one is sparing the other is sparing;
and therefore let every one nourish charity in the root, that is, keep a liberal mind,
a heart that looks upon the substance that is given him,
as really bestowed upon him for the support of charity,
as for the support of his own body; and where people are of this mind,
they will have a care of keeping back any of God`'s part;
for he hath in all ages in a most singular manner espoused the cause of the poor,
the widow and the fatherless,
and hath often by his prophets and ministers given a special charge to rich men,
that they should look to it, that they were faithful stewards of what they possessed.

Now as concerning the necessities of the poor, there is great need of wisdom,
when ye meet together about that affair;
for though the worthiness or unworthiness of persons is not to be considered in judgment,
yet in this it is; and you will find some that men have made poor;
some that God hath made poor, and some that have made themselves poor,
which must all have their several considerations,
in which you ought to labour to be unanimous,
and not one to be actuated by an affection to one more than another,
but every one to love every one in the universal spirit,
and then to deal out that love in the outward manifestations thereof,
according to the measure that the Lord in his wisdom working you,
shall measure forth to them.

And as to those who by sickness, lameness, age,
or other impotency are brought into poverty by the hands of providence,
these are your peculiar care, and objects pointed out to you to bestow your charity upon,
for by them the Lord calls for it;
for as the earth is the Lord`'s and the fulness thereof,
he hath by his sovereign power commanded that a part
of what we enjoy from him should be thus employed.
The Israelites were not to reap the corners of their fields,
nor gather the gleanings of the corn or vintage, these were for the poor.
And in the time of the gospel, they were,
on the first day of the week to lay by a part of what God had blessed them with,
for the relief of those that were in necessity; nay,
they did not confine themselves in their charity to their own meetings,
but had an universal eye through the whole church of Christ,
and upon extraordinary occasions,
sent their benevolence to relieve the saints at Jerusalem in a time of need:
and all that keep in the guidance of the same universal spirit,
will make it their business to be found in the same practice of charity and good works:
to do good, and communicate, forget not, saith the apostle.
They then,
that forget not this christian duty will find out the poor`'s part in the
corners and gleanings of the profits of their trades and merchandizings,
as well as the old Israelite did in the corners and gleanings of his field;
and in the distribution of it,
will have a regard to comfort the bowels of such who are by the divine providence of
God put out of a capacity of enjoying those outward comforts of health and strength,
and plenty which others do enjoy; for while they are partakers of the same faith,
and walk in the way of righteousness with you,
they are of your household and under your care, both to visit,
and to relieve as members of one body, of which Christ Jesus is head,
and he that giveth to such poor lendeth to the Lord and he will repay it.

But there is another sort of poor,
who make themselves poor through their sloth and carelessness,
and sometimes by their willfulness; being heady and high-minded,
and taking things in hand that are more than they can manage,
and make a flourish for a season,
and through their own neglects are plunged down into great poverty;
these are a sort the primitive churches began to
be troubled withal in the early days of the gospel;
for the apostle took notice of some that would not work at all,
and sharply reproved them, and said, They that would not work should not eat :
and these are commonly a sort of busy-bodies, and meddlers with others matters,
while they neglect their own, and run into a worse way than unbelievers,
while they profess to be believers,
yet do not take due care for those of their own household.

The charity that is proper to such, is to give them admonition and reproof,
and to convince them of their sloth and negligence; and if they submit to your reproof,
and are willing to amend,
then care ought to be taken to help them into a way to support themselves;
and sometimes by a little care of this kind, some have been reclaimed:
but if they will not receive your counsel and admonition,
but kick against it either in their words or actions,
friends will be clear of such in the sight of God ;
for it is unreasonable in them to expect vou should feed them,
who will not be advised by you,
because they dissolve the obligation of society by their disorderly walking;
for our communion doth not stand only in frequenting meetings,
and hearing truth preached,
but in regulating the life and conversation by the principle and spirit of truth,
and therein both the rich and the poor have fellowship one with another.

--

There is another sort that are made poor by cruelty and oppression;
by long imprisonments, and spoiling of their goods:
These oppressed poor cry loud in the ears of the Almighty,
and he will in his own time avenge their cause:
But in the mean time there is a sympathetic tenderness to be extended towards them,
not knowing how soon it may be our turn; and if there be need of counsel and advice,
or if any applications can be made to any that are able to deliver them from the oppressors,
let all that are capable be ready and willing to advise, relieve and help the distressed:
This is an acceptable work cf charity, and a great comfort to such in sharp afflictions,
and their souls shall bless the instruments of their ease and comfort.

[.small-break]
'''

[.alt.centered]
Sect. IV.

[.alt.centered]
Of their Method of Dealing with Transgressors.

[.small-break]
'''

Having given a general view of the subjects of the
christian discipline amongst this people,
I proceed to their method of dealing with such as violate the laws of virtue and morality,
and the rules of this society founded thereupon.

In every external society of men there must be some rules,
principles or laws accommodated to promote the ends of their confederacy,
for the regulation of the members thereof,
to which in proportion to their conforming their conduct and conversation,
they are entitled to the benefits and privileges of membership in that society.

Rules and laws are in themselves only a dead letter.
Sanctions are necessary to make them obligatory.
The law, saith the scripture, was added because of transgression,
i.e. sanctions and penalties were annexed to prevent transgression,
or declare how the transgressors are to be treated,
more or less of which are in every society.

In civil society,
laws for the preservation of peace and property are
established by human policy with temporal coercion,
confiscation, or corporal penalties,
the same principle mistakenly applying these penalties
to transgressions in religious society,
is persecution, at this day very justly and very generally exploded.
The sanctions of the laws or rules for the government of
religious society are to be drawn from the fundamental code,
the bible, especially the new testament,
which restricts the utmost penalty merely to exclusion,
without any temporal penalty what ever.
The prescription of the highest authority was this, "`If thy brother offend thee,
tell him between him and thyself; if he hear thee, thou hast gained thy brother;
but if he will not hear thee, take with thee one or two more, that,
in the mouth of two or three witnesses, every word may be established:
And if he shall neglect to hear them, tell it to the church;
but if he neglect to hear the church,
let him be unto thee as a heathen man and a publican.`"

To this may be added the following precepts of the apostle, 2 Thess. 3:6.
"`We command you, brethren, in the name of our Lord Jesus Christ,
that ye withdraw yourselves from every brother that walketh disorderly.`"
And 1 Cor. 5:11. "` I have written unto you not to keep company, if any man,
that is called a brother, be a fornicator, or covetous, or an idolater, or a railer,
or a drunkard; or an extortioner, with such an one no not to eat.`"
These rules and precepts authorize and regulate the proceedings
of this society with those who transgress their rules.

These things premised;
I proceed to lay before the reader a more particular account of the method
of their proceedings in the word`'s of William Penn.

[.embedded-content-document.letter]
--

It may be expected,
I should here set down what sort of authority is exercised by this people,
upon such members of their society as correspond not in their lives with their profession,
and that are refractory to this good and wholesome order settled among them;
and the rather,
because they have not wanted their reproach and sufferings from some tongues and pens,
Upon this occasion, in a plentiful manner.

The power they exercise, is such as Christ has given to his own people,
to the end of the world, in the persons of his disciples, viz. To oversee, exhort,
reprove, and after long suffering and waiting upon the disobedient and refractory,
to disown them, as any longer of their communion,
or that they will stand charged with the behaviour of such transgressors or their conversation,
as any of them, until they repent.
The subject matter about which this authority, in any of the foregoing branches of it,
is exercised, is first in relation to common and general practice.
And, secondly,
about those things that more strictly refer to their own character and profession;
and which distinguish them from all other professors of Christianity;
avoiding two extremes upon which many split, viz. Persecution and libertinism, that is,
a coercive power to whip people into the temple; that such as will not conform,
though against faith and conscience, shall be punished in their persons and estates:
Or leaving all loose and at large, as to practice;
and so unaccountable to all but God and the magistrate.
To which hurtful extreme, nothing has more contributed than the abuse of church power,
by such as suffer their passions and private interests to prevail with them,
to carry it to outward force and corporeal punishment.
A practice they have been taught to dislike, by their extreme sufferings,
as well as their known principles for an universal liberty of conscience.

On the other hand, they equally dislike an independency in society.
An unaccountableness in practice and conversation
to the rules and terms of their own community,
and to those that are the members of it.
They distinguish between imposing any practice that immediately regards faith and worship,
which is never to be done or suffered, or submitted unto,
and requiring christian compliance with those methods that only
respect church business in its more civil part and concern;
and that regard the discreet and orderly maintenance of
the character of the society as a sober and religious community.
In short, what is for the promotion of holiness and charity,
that men may practise what they profess, live up to their own principles,
and not be at liberty to give the lie to their own profession without rebuke,
is their use and limit of church power.
They compel none to them, but oblige those that are of them to walk suitably,
or they are denied by them: That is all the mark they set upon them,
and the power they exercise,
or judge a christian society can exercise upon those that are members of it.

The way of their proceeding against such as have lapsed or transgressed, is this:
He is visited by some of them, and the matter of fact laid home to him,
be it any evil practice against known and general virtue,
or any branch of their particular testimony, which he in common professeth with them.
They labour with him in much love and zeal, for the good of his soul, the honour of God,
and reputation of their profession, to own his fault and condemn it,
in as ample a manner as the evil or scandal was given by him; which for the most part,
is performed by some written testimony under the party`'s hand: And if it so happen,
that the party prove refractory, and is not willing to clear the truth they profess,
from the reproach of his or her evil doing or unfaithfulness,
they after repeated entreaties and due waiting for a token of repentance,
give forth a paper to disown such a fact, and the party offending:
Recording the same as a testimony of their care for
the honour of the truth they profess.

And if he or she shall clear their profession and themselves,
by sincere acknowledgment of their fault, and godly sorrow for so doing,
they are received and looked upon again as members of their communion.
For as God, so his true people, upbraid no man after repentance.

--

I have already observed that the executive part of
the discipline is vested in the monthly meetings:
But if any person censured or disowned be dissatisfied,
or think himself injured by the judgment of any monthly meeting,
he may appeal to the quarterly meeting of the county
or province to which the monthly meeting belongs,
where the case is heard generally by a committee,
composed of members of all the monthly meetings,
except that from whose judgment the appeal is made.
And if the quarterly meeting confirm the judgment
of the monthly meeting and he be still dissatisfied,
he may appeal from their judgment to the yearly meeting of London,
or in Ireland to the national half-year`'s meeting in Dublin,
where the matter is again heard by a committee,
from which the members of the meeting appealed from, are excluded.

It is further to be observed, that in all their proceedings,
they endeavour to exemplify the spirit of the gospel which is love,
in earnest entreaties to restore them,
or bring them to a feeling sense of their misconduct,
that they may experience a proper temper of mind to condemn it
honestly and sincerely for removing the reproach occasioned thereby,
and when this is the case, such condemnation is frequently accepted,
and published instead of a paper of denial, as before observed by William Penn.
And when they find it necessary to publish a testimony of disunity,
it contains no tincture of the spirit of the excommunications of the Romish hierarchy,
no thing like an anathema or curse;
but in the pure spirit of Christianity is concluded with an earnest desire or prayer,
that may timely come to a feeling sense of their misconduct,
and be favoured with repentance unto salvation.
