== Chapter XV

[.chapter-synopsis]
* Violent Proceedings of William Armourer in Berkshire
* Abingdon Session
* Thomas Curtis`'s whole Family in Prison
* Trial of fifty Prisoners
* The jury bring them in not guilty
* Some of the Prisoners remanded and the Oath tendered
* The Oath tendered to Anne Curtis, who remonstrates against it
* Twenty premunired, and two sentenced to banishment
* Trial of Joseph Phipps on the Act for Banishment
* Persecution in Northamptonshire.

During the rebuilding of London after the fire,
the heat of persecution abated for a season, not only in the city,
but through the nation in general:
Yet in some parts it was kept alive in the breasts of some magistrates,
who still continued to harass the members of this society
with persevering violence and rigorous treatment.

In Berkshire in particular,
they had been grieviously persecuted and grossly
abused for a series of time from the year 1663,
principally through the antipathy of William Armourer, a justice of peace,
and a man of a violent turn of mind his implacability to them instigated
him to extend the persecuting laws of this reign to their utmost severity,
and in cruelty of execution to exceed the bounds of the law,
in endeavours to effect the ruin of his quiet and peaceable neighbours,
who had done him no wrong.

From a meeting at Thomas Curtis`'s at Reading, the 27th of the month called March, 1664,
having sent thirty-four men to the county jail for being at an unlawful assembly,
he came again that day week, and finding only two men there, Robert Paine and John Boult,
he committed them to prison after the rest.

He continued to visit their meetings from time to time,
till he had imprisoned most or all the men,
and then he proceeded to imprison the women also.
And afterwards coming with his usual rage,
and finding only a few children and young maidens in the meeting,
he struck one of them with his staff, ordered them to be pulled out,
and threatened to send them to prison, if they should come thither any more.

At the quarter-sessions at Abingdon, the prisoners were called to the bar;
but instead of a legal trial, upon the cause of their commitment,
the accustomed snare was resorted to, the tender of the oath of allegiance: The first,
who was called, was James Whiteheart, who, coming with his hat on,
was by the angry justices ordered to be taken away, without being questioned,
whether he would take the oath or not.

The next was Henry Fizeing, not a Quaker, Henry who coming to the bar, with his hat off,
and bowing, the judge, Thomas Holt, said, "`Here`'s a man has some manners, and asked him,
whether he would take the oath of allegiance?
to which he replied, "`I have taken it already.`"
But, said the judge, "`you were no Quaker then.`"
Henry replied, neither am I now, but have been many weeks among them,
and I never saw any hurt by them; but they are an honest civil people.`"
Upon which Armourer stood up and said, "`Why did you not tell me so before?`"
Henry answered, "`Your worship was so wrathful, that you would not hear me.`"
The cash being then tendered, he took it, and was discharged.

Several other prisoners being called and interrogated in like manner, answered,
they were not committed on account of the oath, but for being at a meeting.
But the oath being insisted upon,
Thomas Curtis informed the courts that he did not refuse the oath,
through any default of allegiance to the king,
but because Christ commanded me not to swear at all;
that he had proved himself a faithful subject to
the king and would take that oath as soon as any;
and therefore desired the court to direct one of their ministers
to inform him from scripture how he might take it,
and not break the command of Christ.
Upon this a priest sitting by was desired to satisfy Thomas in that point:
But being cautious of entering into debate upon a subject,
wherein he might doubt the validity of his argumentation, he put if off,
under the pretence that they were an obstinate people and not to be satisfied.
At length Armourer ordered them to be taken away, saying, "`I know they will not take it;`"
although many of them did not refuse it.

Thomas Curtis, against whom and his wife Anne (whose father it hath been remarked,
lost his life for his fidelity to the king) Armourer bore a particular ill-will,
having obtained liberty from the sheriff, whose prisoner he was,
to attend Bristol fair on his trading concerns, this Armourer hearing of it,
sent for him to an inn, and addressing himself to him, said,
"`I hear you are going to Bristol fair,
but I will stop your journey:`" And by arbitrary compulsion, without legal authority,
removed him out of the sheriff`'s custody to the town prison of Reading.

Having gratified his malice so far as to have Thomas
Curtis and his wife both shut up in prison,
Thomas`'s trade and house were under the care of a man and maid servant,
whom he threatened also to send to jail, and nailed up the doors,
to prevent any more meetings to be held there.
Soon after he sent his warrant to take the man servant, to whom,
when brought before him and the mayor, they tendered the oath of allegiance,
and upon his declining it, committed him also to prison;
but could not accomplish their design of preventing the continuance of meetings there.
Some time after he committed the maid servant to
the house of correction for forty-eight hours.
At which time the whole family were in prison.

It is really astonishing to see what lengths,
party resentments will carry men pretending to rationality and Christianity,
in opposition to the plainest principles of reason and equity;
and the unjust use made of this oath of allegiance,
not to secure government against danger;
but merely to bring innocent people under the lash of a law never intended against them;
and for their being subjected to the severe penalties of it,
though they had given no just occasion.
It seems manifest that Armourer, in defiance of every sentiment of justice and humanity,
aimed at the ruin of this couple as to their outward circumstances,
by thus obliging them to shut up their shop,
and disabling them from carrying on their business, while thus pent up in prison;
perverting law and government, to the destruction of property,
which ought to be directed to the security of it.

Whilst Thomas Curtis, his wife and man servant were in prison,
Armourer sent his man to inquire if there were any in the house beside the family,
and the maid informing him there were not, he came in person a little after,
and knocked at the door, which the maid, being in fear, was not forward to open.
Armourer then drawing an instrument from his pocket, picked the lock, entered the house,
and searching it from room to room, found Joseph Cole, whose dwelling was there,
and who was confined by indisposition.
Armourer taking him by the arm, and dragging him downstairs, asked him,
if he Thomas would take the oath of allegiance,
which he refused and was sent to the house of correction.
From the prison the said Joseph wrote a letter to
the justices exhorting them to the fear of God,
to righteousness,
justice and a temperate consideration of their proceedings towards their neighbours,
how inadequate their imputed offences were to the
severity of the punishments inflicted upon them,
in terms conceived in the meekness of wisdom, and arguments founded in right reason:
But these intemperate magistrates were not to be diverted by reason or argument,
from their determined purpose to prosecute the Quakers even to their ruin.
This honest man was kept in prison till his death, which happened in 1670.

At the quarter-sessions held at Reading the latter end of the year 1664,
about fifty prisoners were brought to the bar,
and an indictment read against them for willfully refusing the oath,
to which at Newbury sessions they had pleaded not guilty.
The evidences were Sir William Armourer and the clerk of the peace,
who swore that the oath had been tendered, and read to them at last Abingdon sessions.
The counsel for the king insisted much on the credit of the witnesses, telling the jury,
they must either bring in the prisoners guilty,
or they would make Sir William Armourer and the clerk as perjured persons.
Nevertheless the jury on strict inquiry,
perceiving that the tender of the oath was irregular,
and the clerk acknowledging he could not tell whether
it was read before or after they were called over,
brought in their verdict, not guilty.
Upon which the court broke up, and many of the prisoners being discharged by the jury,
went away.
But Armourer and some others staying behind, ordered the jailer to call back the Quakers.
Thomas Curtis, George Lambold and their wives with three others appeared,
the rest being gone away.

To these they proceeded to tender the oath afresh;
whereupon Thomas Curtis remarked it remanded, was not the part of men of honour,
to endeavour to ensnare those whom the jury have cleared;
but such proceedings will appear as blots in your escutcheons:
We do believe you aim to ensnare us, and it is our estates you are seeking after.
It is well if some of you have not begged them already.
George Lambold being next required to take the oath, answered,
as to the oath of obedience, he could promise very much and should keep his promise.
Not content with administering the oath to the men,
they proceeded to do the same to their wives, to which Anne Curtis remonstrated,
that it was a very hard tendered to case, she should be required to take the oath,
being under covert,
"`and my husband here a sufferer for the very same thing;`" "`for,`" added she,
"`there is no other woman in England under covert (that
I have heard of) who is required to take that oath,
and kept in prison on that account.`"
But Armourer in a passionate vulgarism, cried out, "`hold your tongue, Nan,
and turn your back.`"
And so she with the rest was sent back to prison.

Thus the arbitrary magistrates of this reign broke every barrier of the
constitution to wreak their vengeance on a harmless body of men.
We have seen juries overawed and menaced, their verdicts refused,
themselves bound over to the King`'s Bench, and here their verdict made of none effect;
by contriving to remand to prison the persons whom they had just acquitted:
What availed this boast of the Englishman`'s privilege,
while he could be alternately imprisoned and tried,
tried and imprisoned on new created of fences,
until a jury could be found to condemn him.

By the time of the succeeding session at 1665.
Newbury,
Armourer had got in prison again a considerable number
of those who were released at last sessions,
and at that time escaped his hands:
The prisoners to the number of twenty-six were continued from sessions to assizes,
and from assizes to sessions until near the end of the year,
when at the session at Reading twenty were condemned in premunire,
and remanded to prison, and two women convicted of meeting,
the third time were sentenced to be transported to Barbados.

Such a specimen of premunire by wholesale seems to confirm Thomas Curtis`'s observation,
that it was their estates they wanted; and himself,
as one possessed of the greatest property was not passed by.
For on the 19th of the month called June, this year, John Witham under-sheriff,
and Thomas Ross, the Duke of Monmouth`'s tutor,
came to the jail and told Thomas Curtis and George Lambold,
they had a warrant from the king to seize their estates.
They seized their books, papers and writings,
and one hundred and fifty pounds in money of Thomas Curtis`'s;
then they went to their houses, and took an inventory of what they could find,
but on their promise to be answerable for the goods, they did not remove them.

Anne Curtis and Sarah Lambold were brought to the sessions at Newbury,
but their trial was put off.
However Armourer their professed adversary not being present,
the justices granted them their liberty, upon promise of appearing at the next sessions.
This displeased Armourer,
who presently sent the jailer`'s man to fetch them to prison again:
The man told him that the justices had given them liberty until the next sessions:
To which Armourer replied, "`What have the justices to do with my prisoners?`"
and threatened to lay the man by the heels if he did not obey his orders:
So he fetched Sarah Lambold back to prison; but Anne Curtis being gone to Bristol,
was for the present out of his reach.

But on the same day her husband`'s effects were seized as above related,
she was by Armourer`'s warrant carried again to prison,
where after she had been detained about two months,
at the intercession of the persons who had the charge of her husband`'s estate,
who it is likely judged it too unreasonable even
in this unreasonable age to premunire the husband,
and imprison the wife at the same time, for the same offence;
she was set at liberty by a discharge under Armourer`'s hand and seal;
notwithstanding which he sometime after remanded her to prison upon her former commitment,
at a time when she was confined to her chamber through indisposition.
Acting thus arbitrarily, without fear or control.

But to recite the whole catalogue of this man`'s cruelties in violation of justice,
of law, of humanity, and of a good conscience would draw me into a tedious detail;
so I shall only just touch upon some other instances of his rude and indecent behaviour.
He threatened to gag a prisoner for speaking in his own defence.
He sent young girls to the house of correction, where they lay a long time.
He came to a meeting, and finding only four young maids there, he sent for water,
which he threw with great violence in their faces until one of them was almost suffocated,
and then turned them wet out of the meeting.
On another occasion the profaneness and obscenity
of his language was such as decency recoils at.
By his words and actions proving himself ill qualified
to support the dignity and repute of his station,
as such conduct would disgrace an office much inferior to that of a justice of the peace.
To Anne Curtis he bore a peculiar animosity, because being a woman of good sense,
she was qualified to make some pertinent observations on the impropriety of his conduct.

But before I leave this county,
as a further illustration of the lawless proceedings of this man and his associates,
I shall take notice of another trial at their sessions at
Reading on the 16th of the month called January this year.
It was that of Joseph Phipps for the third offence on the act of banishment.
A Quaker who had been just before tried was acquitted;
where upon the court dismissed the jury and impannelled another.
Armourer`'s direction to the bailiffs being Go out and pick a jury,
you know there are honest men enough in the town, one of the bailiffs answered, Yes,
Sir William, I`'ll fit you.
Another jury being sworn, Joseph was set to the bar, and having pleaded not guilty,
he insisted there were not five persons of sixteen years of age at the meeting,
and therefore he was not within the act.
Edward Dolby answered, if there were but one of that age, yet if there were five present,
he would send that one to prison as a breaker of the law;
for though the rest were not punishable by the act,
yet they would serve to make up the number.
This unequal construction of the law was pressed upon the jury;
as was also the confession of the prisoners, that they were met to seek the Lord.
And when one of them asked whether to seek the Lord was a crime worthy of banishment?
the judge answered, yes.
The jury went out but could not agree:
Such as favoured the prisoners cause were threatened;
and they were ordered to be kept up all night without fire or candle.
Next morning the court sat again, and sent to know whether they were agreed;
one of them said, I am not satisfied: Yet the Foreman said guilty,
although four of the jury had not agreed to the verdict:
However the judge passed sentence on Phipps,
that he should be transported to some of his Majesty`'s plantations,
there to remain seven years; under which sentence he was returned to prison,
and lay there until discharged by the King`'s letters patent, about fix years after.

In Northamptonshire also,
persecution was carried on without relaxation through this and the succeeding year.
Several were tried on the act of banishment,
of whom four were sentenced to transportation.
One William Smith, foreman of the jury, was a very active man in their conviction,
and exerted his influence over the other jurors to
join with him in bringing them in guilty,
to display his zeal in forcing a conformity to the liturgy of the church of England,
when now the church of England had the upper hand:
having been equally zealous against it in Oliver Cromwell`'s days,
and equally forward to promote persecution.

Imprisonments were frequent and numerous.
At one time a constable came with a rabble of assistants
to a meeting at the house of John Mackerness in Findon,
took about forty of the persons assembled, detained them in an alehouse all night;
and next day conveyed them like criminals in a cart and wagon to justice Yelverton`'s,
who in conjunction with another justice fined them forty shillings,
and for non-payment sent them to the county jail for six weeks.
Another time fifteen men and ten women were carried before the same justice Yelverton,
who signed a mittimus for committing ten of the men to prison;
but another justice`'s hand being necessary,
he directed his clerk to carry it to justice Ward.
The ten men were again put into the cart,
and conveyed with the mittimus to the said justice, but he refused to sign it,
and no other justice was found willing to do it,
nor could the jailer legally receive them without the signature of two justices.
So the prisoners, after being thus driven from justice to justice,
were permitted to return home.
But some time after, six of them were taken by another warrant, and sent to jail;
three of whom were afterwards sentenced to transportation.
The number of persons of this persuasion at one time under close
confinement in the county jail were more than four score,
of whom many were husbandmen, locked up from their business both in hay time and harvest,
to their great loss and detriment,
