== Chapter XVI.

[.chapter-synopsis]
* William Penn`'s Birth and Education
* At the College he is partly convinced
* His Father in Resentment banishes him from his House Sends him to France
* He goes to Ireland
* Where he is thoroughly convinced by the Ministry of Thomas Loe
* His Father endeavours to bring him off from joining with friends
* Banished from his Father`'s House a second Time
* Called to the Work of the Ministry
* Robert Barclay`'s Birth and Education
* Convinced of the Principles of the People called Quakers
* He receives a Gift in the Ministry
* Roger Haydock convinced
* Miles Halhead taken up in Devonshire
* Death and Character of Richard Farnsworth
* Further Instances of Armourer`'s rude and arbitrary Proceedings
* Unjust Verdict.

In this year and the next, two members eminent for their virtue and piety,
as well as for their natural abilities, were added to this society,
viz. William Penn and Robert Barclay,
who for their very great usefulness and services therein claim a particular attention.

William Penn was born in the city of London 24th of 8mo 1644.
His father of the same name, a man of good estate and reputation,
in the time of the Commonwealth had filled some of the highest stations in the navy,
viz. those of Rere Admiral, Vice Admiral, Admiral of Ireland and Vice Admiral of England,
with honour and fidelity.
He retained his post after the Restoration,
was knighted by Charles II. and was peculiarly distinguished
as a favourite by the Duke of York.
His father`'s affectionate attention,
and the promising prospect he entertained of his son`'s advancement,
procured him a liberal education;
and by the acuteness of his genius and diligent application to his studies,
he made such proficiency in learning,
that about the fifteenth year of his age he was entered a student
in that called Christ Church College in Oxford.

Some time after his removal to the college, at a meeting of the people called Quakers,
through the reaching ministry of Thomas Loe,
he received some relish of pure and spiritual religion,
and was impressed with an ardent desire after the experimental attainment thereof.
In consequence, he, with certain other students of that university,
withdrawing from the public worship, held private meetings for the exercise of religion,
where they both preached and prayed among themselves.
This gave great offence to the heads of the college, and he, at sixteen years of age,
was fined for non-conformity; but this punishment not abating the fervour of his zeal,
he was at length, for continuing in the like religious exercises, expelled the college.

From thence he returned home;
but still took great delight in the company of sober and religious people,
from whom his father fearing he might contract a turn of mind little
accommodated to advance him to that preferment in the state,
which he fondly flattered himself, his interest might procure him, he endeavoured,
both by words and blows to deter him therefrom; but finding those methods ineffectual,
he was at last so incensed, that he turned him out of doors.

Patience surmounted this difficulty, until his father`'s affection subdued his anger;
who then sent him to France, in company with some persons of quality,
that were taking a tour thither.
He continued there a considerable time,
until his conversation amongst that gay and volatile people
diverted his mind from the serious thoughts of religion.
At his return, his father finding him not only a good proficient in the French language,
but polite and courtly in his behaviour,
flattering himself with the success of his scheme, as having gained his point,
welcomed him with a joyful reception.

For some time after his return from France his genteel and complaisant
behaviour procured him the character of an accomplished young gentleman,
and of consequence the estimation and good opinion of his acquaintances,
and the world around him: but amidst the caresses and flatteries of men,
he found a disturber of his satisfaction therein, within his own bosom,
reminding of his former seriousness and good resolutions; of a state of futurity,
and the certainty of a day of strict account: And although guilty of nothing,
which the world terms criminal, yet by the light, with which his mind was illuminated,
he was sensible he had lost ground, as to the attainment of that inward purity of heart,
in which he had seen the substance of religion to consist;
and was renewed into an earnest desire of regaining what he had lost,
and applying his mind to the pursuit of pure religion,
as the same had been manifested by the divine light to his understanding.
But in directing his attention this way, he suffered a painful spiritual conflict:
His natural inclination, his lively and active disposition, his acquired accomplishments,
his father`'s favour, the respect of his friends and acquaintance,
were so many strong incentives to embrace the glory and pleasures of this world,
then even courting his acceptance;
and mountains of opposition in his way to adopt that pure religion,
which might endanger his relinquishing them all.
Mountains of this magnitude might seem almost insurmountable;
but the earnest supplication of his soul being to
the Lord for preservation in the way of duty to him,
he was pleased to grant him such a portion of his grace and good spirit,
as enabled him in due time to overcome all opposition,
in a holy resolution to follow Christ,
whatsoever reproaches or persecutions might attend him.

In the course of the year 1666 his father having committed to his
care and management a considerable estate he had in Ireland,
he went over to that kingdom, and being in the city of Cork,
he was informed that Thomas Loe was likely to be at a meeting there: he went to hear him:
who began his public testimony in these words,
There is a faith that where he overcomes the world,
and there is a faith that is overcome by the world;
upon which subject he enlarged with great clearness and energy:
And by the reaching powerful testimony of this man (whose ministry had made profitable
impression upon him several years before) he was so thoroughly reached and convinced,
that from this time he joined the society of the Quakers,
and constantly attended their meetings through all the heat of persecution.

It was not long before his father was informed by a nobleman of his acquaintance,
what danger his son was in of being proselyted to Quakerism,
whereupon he remanded him home: and although there was no great alteration in his dress,
yet the seriousness of his deportment,
and the solid concern of mind he appeared to be under,
were manifest indications of the truth of the information his father had received,
who thereupon renewed his efforts to bring him off from a way of thinking and conduct,
which would disappoint all his sanguine hopes,
and baffle his fond schemes of seeing him advanced at court.
But his efforts proved in vain;
for although his son felt all the force of natural affection and filial duty,
and would have been far from offending him in any case,
wherein the peace of his conscience was not concerned;
yet in this case he durst not comply with the requisition of his earthly father,
to disobey, as he thought, the requiring of his heavenly father.

At length, after much striving with him,
finding him too firmly fixed in these principles to be brought
to a general compliance with the customary compliments of the times,
his father seemed inclinable to have borne with him in other respects,
provided he would appear uncovered in the presence of the king, the duke and himself,
which being proposed to him, he desired time to consider of it,
and retiring to his chamber,
humbled himself with fasting and supplication to receive divine direction,
and was so strengthened in his mind, that, returning to his father,
he humbly signified that he could not comply with his desire therein.

When all endeavours proved ineffectual and his father
found himself utterly disappointed of his hopes,
he could no longer endure him in his sight, but turned him out of doors the second time,
whereby he was exposed to the charity of his friends, having no other subsistence,
except what his mother privately sent him.
Thus he endured the cross with christian patience and magnanimity,
and evinced the sincerity of his conversion,
by a voluntary relinquishing of every tempting worldly prospect,
in order to attain the favour of Heaven and solid peace of mind.

Having thus bought the truth by parting with all for its sake,
and abiding under the enlivening influence thereof,
he received qualification to incite others to do likewise,
being called to the work of the ministry about the twenty-fourth year of his age,
in which he approved himself a workman that need not be ashamed.
Nor was he only eminently distinguished for his qualifications and labours in the ministry,
but also for his writings in defence of the principles he had adopted,
and for propagating religious thoughtfulness,
and the practice of piety among mankind in general, which being collected,
compose two volumes in folio.

Robert Barclay was exempted from the severe obstructions and discouragements
which stood in the way of William Penn`'s embracing this profession,
his father having adopted it before him.
He also was well descended, and had received the advantage of a good education.
He was the son of colonel David Barclay of Ury near Aberdeen,
descended from the Barclays of Mathers in the kingdom of Scotland,
an ancient and honourable family among men, and of Catharine Gordon,
of the house of the duke of Gordon.
Yet it was not from his descent he received his principal honour,
and the degree of estimation he attained both within the society and without;
but from his personal merit and inherent good qualities.
His native city was Edinburgh, being born there in 1648,
and in his infancy he was educated among the Calvinists in his own country;
but being early removed from thence,
for the sake of an opportunity of a more extensive
education under the tuition of his uncle,
who was president of the Scotch college at Paris,
where the learning common to our schools and universities was taught,
he attained a proficiency in the French language as well as the Latin,
with other branches of literature.

The Papists, taking advantage of the immaturity of his judgment in his minority,
endeavoured to make a proselyte of him.
Their endeavours in that tender age made some impression upon him,
but as his judgment ripened,
he soon clearly discovered the errors of their religious system.
He returned home about 1664, in the 16th year of his age,
and during his absence his father having joined himself
in fellowship with the people called Quakers,
by his religious conversation and circumspect example,
as well as the converse and conduct of others of that profession,
he was impressed with a perception and relish of the excellency of that religion,
which produced so remarkable a consistency of conduct in life and
conversation with the spirit and precepts of the gospel,
amongst its professors in a general way.

Under this impression he was induced to attend the religious meetings of this people,
whereby he felt his inclination towards them strengthened, and his convincement promoted,
// lint-disable invalid-characters
of which he himself hath left us this account.footnote:[Barclay`'s Apology, prop. 2. ยง7.]
"`It was not by strength of argument, or by a particular disquisition of each doctrine,
and convincement of my understanding,
that I came to receive and bear witness of the truth;
but by being secretly reached by the principle of light and life,
to which they were gathered for when I came into the silent assemblies of God`'s people,
I felt a secret power among them, which touched my heart, and as I gave way to it,
I found the evil weakening in me, and the good raised up,
and so I became thus knit and united unto them,
hungering more and more after this power and life,
whereby I might feel myself perfectly redeemed.`"

In the year 1667 he was thoroughly convinced and
made public profession of the principles of this society,
taking up his cross to the glory and friendship of the world, and despising the shame,
he esteemed the reproach of Christ greater riches than the treasures of Egypt,
manifesting to the world that the contemptible name
of a Quaker could not deter him from following,
owning and defending truth, wherever to be found,
counting all things as dross in comparison of the knowledge of Christ,
which he intently sought after and embraced as his crown,
and received a gift in the ministry as his greatest honour,
in which he laboured to bring others to the knowledge of God,
and his labour was not in vain in the Lord.
Besides his ministerial labours,
he was much engaged in controversy with the opponents and slanderers of the society,
(chiefly his own countrymen), both verbally and in writing;
for which business his qualifications were remarkably eminent,
being not only master of useful literature, but of a clear comprehension,
a capacious reach of thought, a close and convincing manner of reasoning,
delivered in a neat style, though plain and unaffected;
to which adding the excellency of his temper from the prevalence of religion in his mind,
whereby he was so preserved in coolness,
that passion (so general in controversial writers) did not blind his judgment,
or lead him into indecent reflection,
whilst his regard to plain truth prevented him from flattering error or excusing calumny.
His reach of thought penetrated to the bottom of his subject,
and pointed out clearness of method,
and the weight of his arguments proved him an over match for his antagonists.
In short, by means of his essays,
and those of William Penn and some other contemporary writers, as George Whitehead,
Thomas Ellwood, Isaac Penington, etc.
Quakerism (so called) hitherto exposed to contempt and odium,
by the hideous form where in their adversaries (particularly the priests
of various denominations) had misrepresented and exposed to public view,
began to put on a more pleasing appearance,
and to be exhibited in its native and genuine complexion,
whereby the candid and dispassionate part of mankind were
ready to own it to be no absurd combination of wild notions,
but a regular system of important, rational and practical truths.

Yet it is not from hence to be conceived that they
introduced any new doctrines into this society,
or modelled a new system of principles,
for these had been their tenets from the beginning;
but through a candid examination of their doctrine and practice, they were convinced,
and induced to join the society,
amongst whom they found these doctrines received
as articles of faith and rules of practice.

About this time Roger Haydock of Lancashire came over to this society,
whose conversion had something peculiar in it.
His elder brother John having joined their communion,
occasioned considerable uneasiness to his mother, a zealous Presbyterian;
when Roger coming to his father`'s house, and being reputed a learned intelligent man,
she prevailed upon him to use his endeavours to convince
his brother of the absurdity of his choice,
and dissuade him from persisting therein:
he accordingly entered into discourse with him upon the subject,
when John gave him such cogent reasons for his change, as soon put him to silence;
his mother being displeased that he did not hold out the argument more stoutly,
he told her, it was truth, and he could not gainsay it.
Being thus brought to the acknowledgment of the truth,
he soon came to make public profession thereof,
and in process of time became an eminent minister
and a very serviceable member of this society.

Miles Halhead travelling this year in Devonshire,
and being taken up and brought before the magistrates, asked,
what business he (who dwelt in Westmoreland) had in Devonshire?
To which he answered, that he was come to see some of his old friends,
whom formerly about ten years ago he had acquaintance with.
One of the magistrates asked him what were the names of his friends he meant,
upon which he named several former magistrates of that county:
one of the present magistrates remarked, "`Truly, gentlemen,
though this man calls these his friends, yet they have been his persecutors.`"
Another of the magistrates then gave him an account
of the disasters which had befallen them,
and how they had lost their estates;
that one of them had been imprisoned for high treason,
and was escaped out of jail and had fled the country, adding,
"`if these men were your persecutors, you may be sure they will trouble you no more;
for if they that persecute you have no better fortune than these men,
I wish that neither I nor any of my friends may have any hand in persecuting you.`"

In this year Richard Farnsworth laid down the body in the city of London.
He was one of the first that received George Fox`'s testimony
soon after his release from his imprisonment at Darby,
while the name of Quaker was but just known;
and joined him in society and ministerial labour,
which was attended with such a convincing power,
that many were converted by him from the evil of their ways;
and he was not only admitted to a part in the ministry of the gospel with his brethren,
but partook in the sufferings to which they were exposed.
About the year 1656, walking with one of his friends in the street of Banbury,
he met the mayor and a justice of peace whose name was Allen.
And because he did not put off his hat to them, Allen in a passion struck it off his head.
They afterwards sent for him and committed him to prison.
Next day when their pride and passion were a little abated, they sent for him,
and told him,
if he would pay the jailer`'s fees and promise to go out of the town that night,
he should have his liberty: but he would promise nothing,
knowing that they had committed him illegally; Wherefore,
to cover their unlawful procedure, they tendered him the oath of abjuration,
and his refusal furnished them with a pretence for his recommitment to prison,
where he lay about six months.

After about fifteen years spent in acting and suffering for those doctrines,
he had received as truth, he was taken ill in London,
and a short time before his departure out of this life,
gave the following evidence of his full assurance of faith,
and exhortation to his friends with affecting energy and strength of spirit,
as if he were in full health.

[quote]
____
Friends, God hath been mightily with me, and supported me at this time,
and his presence and power have encompassed me all along;
God hath appeared for the owning of my testimony.--I am filled
with his love more than I am able to express.--God hath really
appeared for us.--Therefore I beseech you friends,
here of the city of London, whether I live or die,
be you faithful to the testimony which God hath committed to you.
____

The Earl of Clarendon, prime minister to King Charles,
and reputed to have been a principal promoter of all the
severities hitherto inflicted on the dissenters,
and contriver of the penal laws, by raising and exaggerating rumours of plots,
about this time lost; his influence,
and became himself obnoxious to popular odium and unmerited prosecution:
this gave the dissenters encouragement to hope for more ease,
which they enjoyed for a season: and perhaps it may not be unworthy of remark,
that with what measure he had meted, it was measured out to him again: for he,
who had been instrumental to the imprisoning and banishment
of numbers of innocent persons for no cause,
or on trivial grounds,
was himself at last condemned to banishment on groundless or frivolous accusations.

In Berkshire, Armourer continued his arbitrary proceedings through this year,
while persecution subsided in a great measure in most other parts.
Coming with his man to the meeting, the man looking in at the door and going out again,
pulled the door after him, which having a spring lock shut them out.
His master finding the door fast, called for a sledge to break it open;
but one within opening it,
that no handle might be made thereof to throw a suspicion of plotting upon them,
he manifested the violence of his temper by saying,
if it had not been opened for him he would have broken it open.
Upon his being let in, he sent nine of the persons assembled to prison; one of them,
Mary Coale (whose husband was under sentence of premunire) he committed for six months;
three women were committed on the third offence in order to banishment.

At the succeeding assizes at Abingdon, they were arraigned, and pleaded not guilty,
but their trial was postponed.
Henry Adams on a like indictment was tried,
but no record of his first or second offence could be produced,
nor did any witness appear to prove a third unjust offence,
so that the jury brought him in not guilty.
This verdict being displeasing to the court, the jury were sent back,
and by Armourer`'s influence and menaces, who swore that the records, though lost,
were true, some of the jury brought in a contrary verdict, which the rest, through fear,
did not oppose.
Upon which the prisoner was remanded to jail;
but no sentence pronounced against him in court.
When he afterwards asked the jailer, what order he had concerning him?
His answer was, "`Henry, thee art for transportation;
they have done it since among themselves.`"
He continued in prison five years till released with others in 1672.
