== Chapter XVII.

Thomas Vincent, a Presbyterian Preacher, vilifies Friends,
who demand a public Meeting to vindicate themselves.--The Meeting held,
but interrupted by the Rudeness of the Auditory.--William Penn appeals to the
Public in a little Tract.--For which he is imprisoned in the Tower.--Where he
writes No Cross no Crown.--Death of Thomas Loe,
Josiah Coale, and Francis Howgill.--Account of Josiah Coale and Francis Howgill.

Although the Quakers (so called) were freer from disturbance
by the government than in the foregoing years,
yet they met with some uneasiness and trouble from another quarter.
The other societies of Dissenters were, some of them, during the heat of the persecution,
ready to acknowledge the christian courage of this people, in standing in the gap,
and bearing open testimony to the truth they believed in, in opposition to human laws;
as by this means, while the weight of sufferings fell upon them,
these other escaped more easily: but as these other societies at bottom,
bore them no good will,
as soon as the suspension of persecution encouraged their preachers to officiate publicly,
they returned to promulgate their invectives against the Quakers.
Thomas Vincent, a Presbyterian preacher, in London, losing two of his hearers,
who going to the Quakers meetings, to see for themselves,
whether they were so erroneous in principle and practice, as they had been represented,
were convinced, and joined their society: this so irritated Vincent,
that he indulged his passion in a licence of expression,
not only beyond the bounds of christian moderation, but of common decency,
telling his hearers, that he had as lief they would go to bawdy-house,
as to frequent the Quakers meetings, because of their erroneous, damnable doctrines;
and pointing to the window said, if there should stand a cup of poison,
I would rather drink it, than suck in their damnable doctrines.
He farther expressed himself in this manner to one of them, if ever you go again,
I will give you up, and God will give you up, that you may believe a lie and be damned.

These railing accusations coming to the ears of some
of the people at whom they were cast,
they demanded of him a public meeting:
to vindicate themselves from these foul aspersions,
or themselves give him an opportunity to prove them, if he were able; which,
after some demur, he agreed to;
but took care to have the house filled before the
hour appointed with his own hearers and partisans,
also to procure three assistants, Thomas Danson, Thomas Doolittle and ------ Maddocks.

George Whitehead and William Penn attended this meeting,
to hear what erroneous doctrines Vincent could charge the Quakers with,
and what proofs he could bring;
but instead thereof he took upon him the office of a catechist,
opening the conference with this question,
Whether they owned one Godhead in three distinct and separate persons?
On which subject framing an inconclusive and unintelligible syllogism,
after the manner of argumentation then in use,
George Whitehead rejected his terms as not to be found in scripture,
nor deducible from the text he instanced;
wherefore he desired him to explain the terms so that they might be understood,
inasmuch as God did not use to wrap his truths in heathenish metaphysics,
but deliver them in plain language; but they would neither keep to scripture terms,
nor allow them in their antagonists,
calling George Whitehead`'s explanation and reduction of their matter to scripture sense,
to suit it to the auditors apprehension, and indirect way of answering;
and after many rude insults offered them by ridiculing, hissing,
moving and stigmatizing with opprobrious nicknames,
Vincent abruptly broke up the meeting by falling to his prayer,
wherein with an affected tone he accused them as blasphemers;
and then to deprive them of an opportunity of clearing themselves,
he desired the people to withdraw,
giving them an example by retreating himself with his three coadjutors.
But some of the people staying,
they found an opportunity of vindicating themselves
from the invectives of their adversaries.

They applied to Thomas Vincent for another opportunity, but he evaded it.
Wherefore William Penn appealed to the public in a little piece, entitled,
The Sandy Foundation Shaken, which gave great offence to some powerful ecclesiastics,
who presently applied to their accustomed method of refuting what they call error,
viz. for an order for imprisoning him in the tower of London.
There was he under close confinement, and even denied the visits of his friends;
but yet his enemies attained not their purpose.
For when his servant brought him word,
that the bishop of London was resolved he should either publicly recant,
or die a prisoner, he signified his resolution also that his prison should be his grave,
before he would yield the least compliance in violation of his conscience;
for he owed his conscience to no mortal man.

A spirit warm in the cause of religion, the love of God, and the welfare of mankind,
ever pursues its main design.
This worthy person,
precluded from the opportunity of promoting piety by his ministerial labours,
was not in his confinement unmindful of this great purpose of his life,
he applied himself to promote it by writing:
Several treatises were the fruits of his solitude, particularly that excellent one,
entitled "`No Cross no Crown,`" a book tending to promote the general design of religion,
was well accepted, and hath passed sundry impressions.

And in order to clear himself from the aspersions cast upon
him in relation to the doctrine of the Trinity,
etc. he published a piece called "`Innocency With Her Open Face,`" by way of apology
for "`The Sandy Foundation Shaken,`" in which he so successfully vindicated himself,
that soon after he was released from his imprisonment,
which had been of seven months continuance.

The latter part of this year and beginning of the next deprived
this society of three eminent and serviceable members,
viz. Thomas Loe, Josiah Coale and Francis Howgill.
With the abilities and qualifications of Thomas Loe,
the reader hath been partly made acquainted at his first introduction into this work.
He visited Ireland several times, and having an excellent gift in the ministry,
was much followed, and had generally crowded audiences,
amongst whom his ministry was effectual to bring many over into the society of his friends.
We have just observed it was by his powerful ministry, as the instrumental means,
that William Penn was first reached and afterwards convinced.
He was a man of a fine natural temper, easy, affable and pleasing in conversation,
benevolent in his disposition, and tenderly sympathizing with his friends in affliction,
which made his company not only profitable from the subjects of his instructive observations,
but desirable and agreeable from the manner of them;
whereby he gained the affection and esteem of those he conversed with,
and opened a door for the readier reception of his ministry.

He also travelled in divers parts of England,
and was several times imprisoned for his testimony.
By his travels and labours his natural strength was impaired,
and coming to London this year in the course of his travels,
he was there seized with that disease,
which terminated his labours and his existence in the body.

His pious end was agreeable to the tenour of his life, having in the time of health,
chosen and steadily pursued himself (and zealously exhorted others
to choose that good part which should never be taken from him,
he felt the consolation thereof in his bodily weakness.
At which time being visited by William Penn,
for whom he cherished the best desires to the last,
he addressed to him the following exhortation: "`Bear thy cross,
and stand faithful to God;
then he will give thee an everlasting crown of glory that shall not be taken from thee.
There is no other way which shall prosper than that which the holy men of old walked in.
God hath brought immortality to light, and life immortal is felt.
His love over comes my heart.
Glory be to his name forever more.`"
This dying testimony of his honoured friend to the virtue of that grace and truth,
through fidelity to which he was enabled to attain victory over death,
and triumph over the terrors of the grave,
must have been a comfortable and confirming evidence
to William Penn of the solidity of that religion,
of which he had been effectually convinced by the same worthy man.
At another time Thomas Loe said to his friends that stood by his bedside,
Be not troubled, the love of God overcomes my heart.
And to George Whitehead and others, the Lord is good to me,
this day he hath covered me with his glory, I am weak but am refreshed to see you.
Another friend asking him how he was, he answered, "`I am near leaving you, I think,
but am as well in my spirit as I can desire, I bless the Lord;
I never saw more of the glory of God than I have done this day.`"
Thus rejoicing in hope till his end;
his parting breath expressed a song of praise to that Almighty Being,
whose goodness preserved him through life, and deserted him not in his end.

Josiah Coale was born at Winterborn, Gloucestershire, near the city of Bristol,
and was one amongst the great number of those, who were reached,
and turned to a close attention to the light of Christ in their own hearts by
the powerful and effectual ministry of John Audland about the year 1655;
whose testimony made so deep an impression on him,
as produced a solid and earnest desire after redemption and salvation:
And from the clear sense of his condition and deficiency of that state of purity
which by the light in his conscience was discovered necessary to be attained,
in order to peace and happiness, he walked for a time mournfully under judgment for sin,
and that godly sorrow, which worketh true repentance;
and by taking heed to that which reproved him for evil,
he received strength to get the victory over it;
being purified by the washing of regeneration,
he be came well prepared for the reception of a gift in the ministry,
and proved an able and zealous minister of the gospel;
to this service he devoted his whole life:
Few spent themselves more in the service of God and man than he did;
it being the delight and principal engagement of his soul,
from the time of his conversion, to testify with zeal against iniquity,
and promote truth and righteousness amongst mankind;
for which he was well qualified by a peculiar talent;
his testimony being as a sword sharp and piercing against the workers of iniquity,
attended with an eminent power penetrating the very souls of the auditors.
At other times flowing in a stream of life and encouraging
consolation to the pious and virtuous.

To him, with his brethren, it was given not only to believe in the truth,
but to suffer for it.
He was hardly distinguished as a member of this society,
until he was imprisoned in 1656 in New gate in Bristol, along with Thomas Robertson,
for bearing testimony to the truth in one of the public places of worship,
having been first grievously abused by the populace,
and dragged bareheaded under the spouts in a time of rain.
In the same year at Melcomb-Regis in Dorsetshire, Josiah with three other friends,
for their christian intention of exhorting the people to piety,
met with severe and despiteful abuse from them, and after being violently beaten by them,
were by the mayor committed to prison.

In the year 1658 believing it his duty to pay a religious
visit to the English Colonies in America,
and not being able to procure a passage to New England
(no master of a ship being willing to take him,
for fear of the penalties enacted in through the that state against such of them as
should bring in any Quakers) he in company with Thomas Thirston got a passage to Virginia,
whence they made their way on foot through a tract
of wilderness of several hundred miles,
until then deemed impassable for any but the Indians, a hardy race of men.
By the Indians +++[+++of the Susquehana Tribe]
these strangers were treated with remarkable attention and hospitality,
being not only entertained by them with the best lodging and provisions which they had,
but provided with guides to conduct them to the Dutch plantations,
from which they proceeded to New England.
Yet the journey of these travellers, through that large uncultivated wilderness,
was attended with much hardship and danger,
for they had not only pinching cold to encounter with in the winter season,
but were often in danger of being devoured by wild beasts,
or perishing in unknown waters, marshes and bogs.
So that even their adversaries, admired at their preservation,
in which more than human power was manifested.

In New England he partook of the treatment usually given to his friends in that jurisdiction.
Being in company with John Copeland in a friend`'s house at Sandwich,
they were both seized there, haled out in a violent manner and sent to prison.
He was some time after banished from Maryland.
The comparing of his treatment here with that which
he received amongst those generally termed savages,
as supposed destitute of religion and civilization,
gives them the advantage as to civility and humanity
above those lofty professors of New England,
whose natural tempers had been embittered by false principles of religion,
to the eradication of all tenderness,
and compassion towards those who differed from them.
He travelled also through Maryland and Barbados;
and in Europe through most parts of England, and in Holland and the Low Countries,
in the work of the ministry, which being animated by a divine power,
was effectual to the conversion of many.
To this service he devoted the prime of his life and strength, and continued unmarried,
that, being disengaged from worldly cares,
he might be more at liberty to attend to his ministry.
And though be went through many perils, imprisonments and persecutions,
he was valiant in the cause of truth, undaunted in danger,
and by the support of a peaceful conscience borne up above the fear of man.
Disinterested in his endeavours to promote pure religion,
he was careful not to make the gospel chargeable; but having an estate of his own,
he freely spent it in the best service:
And not only in his travels bore his own charges abroad,
but was an exemplary pattern of liberality at home.

His natural temper was cheerful; but religion tempering it with seriousness,
and his unaffected affability being mixed with a circumspect and exemplary demeanour,
his whole conversation illustrating the purity of his religion,
was an ornament to his profession,
and a confirmation in the truth to those whom his ministry had converted thereto.

Having by hardships in his travels and imprisonments,
and his zealous ministerial services for the space of twelve years,
wasted his natural strength, he finished an honourable,
useful and virtuous life at a middle age by a gradual decline;
but the warmth of his zeal and the firmness of his spirit
bore him up in the exercise of his ministry for a season,
until the increase of his distemper obliged him to submit to confinement.
During which George Fox visiting him,
inquired whether any thing lay on his mind to the friends in England?
But he signified, that having discharged his duty fully in his travels amongst them,
he had nothing on his mind to write.
George, after praying by him, seeing him grow heavy, advised him to lie down,
which he did; but being more uneasy in this posture,
he soon rose again with the help of his friends, and sitting on the side of the bed,
with an affecting power he addressed his friends sitting by with the following exhortation,
"`Well, friends, be faithful to God, and have a single eye to his glory,
and seek nothing for self or your own glory: And if anything of that arise,
judge it down by the power of the Lord God, that so you may stand approved in his sight,
and answer his witness in all people: then will you have the reward of life.
For my part I have thus far finished my testimony, and have peace with the Lord:
His Majesty is with me, and his crown of life is upon me.
So mind my love to all my friends.`"
He said to Stephen Crisp, "`Dear heart, keep low in the holy seed of God,
and that will be thy crown forever.`"
A little afterwards fainting, and being supported by his friends,
he departed in their arms, as one falling into an easy sleep;
full of consolation he passed into immortal life
at the age of thirty-five years and two months.

Francis Howgill was one of the principal persons amongst
the first promulgators of the doctrines of this society,
his qualifications, his virtues,
his services and his sufferings have been in various instances laid before the reader.
We left him confined in prison under a rigorous and undeserved sentence of premunire,
from which he was only released by death: He lay near five years under this sentence,
deprived of every comfort and convenience in the
power of his persecutors to take from him;
but the freedom of his spirit and the purity of his conscience
(possessions beyond the reach of human powers he retained unimpaired,
remembering, doubtless, that gracious promise of the hundredfold in this life,
and in the world to come life everlasting.

This valuable member of society was a native of Westmoreland,
educated in the profession of the established religion, and trained up at the University,
in order to be ordained to the priest`'s office in the church;
but being scrupulous of complying with the ceremonies thereof,
he with drew from that communion, joined in society with the independents,
and became a preacher of eminence among them,
being in esteem no less for his virtue and exemplary conversation,
than for a zealous and laborious discharge of his duty as a minister.
Yet still he found not that satisfaction in himself which he desired, feeling,
notwithstanding his punctuality in fasting, praying and other religious exercises,
the root of sin still remained in him.
The prevailing opinion that Christ had taken the guilt of sin upon himself,
he was afraid to repose his dependence upon, his conscience suggesting to him,
his servant thou art whom thou obeyest.
Increasing in understanding, it was revealed in him,
that the Lord would teach the people himself, and that the time approached nigh.
It was not long till George Fox had that remarkable meeting at Firbank chapel,
where Francis officiated, and hearing him assert that,
the light in man shews the way to Christ, he was deeply affected thereby,
believing it to be a certain truth.
And in consequence attending to the reproofs of this inward light,
he perceived the unfruitfulness of all his own righteousness, and his labour therein:
He now forsook the independents, and taking up the cross,
joined himself to the despised and persecuted society of the people called Quakers,
and in silence and patient resignation,
bearing the administration of condemnation for sin,
in due time he was favoured with the experience of a happy transition
to the more glorious dispensation of justification in righteousness,
and fitted by previous sanctification for the reception of a gift in the ministry.
But upon his public appearance as a minister prominent among this people,
both the priests and magistrates, his former friends and admirers, turned his enemies;
and almost as soon as he was known as such he was confined by their means
(as we have seen) in a very filthy uncomfortable prison in Appleby,
and detained there for some time with out any legal cause.
After his release, he prosecuted his service in the ministry with zeal and diligence,
travelling about mostly on foot to promote righteousness,
or to serve the society of which he was a member.
He and Edward Burrough were almost constant companions in gospel labour,
closely connected in unity of spirit and sentiment,
in similarity of abilities for service, and in the pure bonds of gospel fellowship;
which drew from Francis a very pathetic testimony
to the memory and worth of his beloved companion,
when so suddenly taken away.

In the year 1661 being in London,
he suffered imprisonment amongst the multitude of his friends taken
up in consequence of the insurrection of the fifth-monarchy men.
And after he was set at liberty, continued his labours and travels as before,
till the year 1663, that he was summoned to appear before the magistrates at Kendal,
as before related, and in consequence premunired and imprisoned for life.
On the 20th of 11 mo.
called January 1668-9 he finished his course in this life, in his prison at Appleby,
after a sickness of nine days.
During his imprisonment, he evinced the peaceful and easy tenour of his soul,
by his patience, and resigned acquiescence in all his sufferings;
and that his outward losses were abundantly compensated by that inward peace,
which he was favoured with in reward of fidelity to manifested duty.
Whereby in his sickness he was preserved to the last in that amiable equanimity;
which had so remarkably characterized him through life.
As he approached the verge of time,
he felt the full benefit of his having passed the time of his sojourning here in fear;
being, through this last scene of mortality,
borne up in his spirit superior to his sufferings, by the serenity of his conscience;
and above the fear of death, by feeling the sting thereof taken away.
Expressing himself in his sickness; That he was content, and ready to die;
praising the Almighty for the many sweet enjoyments and refreshing seasons
he had been favoured with on that his prison-house bed whereon he lay,
freely forgiving all who had an hand in his restraint.
"`This, (said he,) was the place of my first imprisonment,
and if it be the place of my laying down the body, I am content.`"
Two days before his death, his wife and friends being present,
he addressed himself to them as follows, "`Friends, as to matters of words,
you must not expect much more from me, neither is there any great need of it;
as to speak to matters of faith to you, who are satisfied,
only that you remember my dear love to all friends who inquire of me,
for I ever loved friends well, and any others in whom truth appeared;
and truly God will own his people as he hath ever hitherto done,
and as we have daily witnessed:
For no sooner had they passed that act against us for banishment,
to the great suffering of many good friends, than the Lord stirred up enemies,
even three great nations, whereby the violence of their hands was taken off.
As for me, I am well, and content to die: I am not afraid at all of death: And truly,
one thing I have observed, which is,
that this generation passeth away--many good and valuable
friends have been within these few years taken from us,
and therefore friends had need to watch and be very faithful,
so that we may leave a good and not a bad favour to the succeeding generation;
for you see, it is but a little time, that any of us have to stay here.`"

Several of the principal inhabitants of Appleby, and particularly the mayor,
visited him in his sickness,
and some of them praying that God might speak peace to his soul, he answered,
He hath done it.
A few hours before he departed, some friends from other places being come to visit him,
he inquired after their welfare, and prayed fervently,
That the Lord by his mighty power might preserve
them out of all such things as might spot and defile.
His voice then, by reason of weakness failed, yet recovering again he said,
"`I have sought the way of the Lord from a child, and lived innocently as among men;
and if any inquire concerning my latter end,
let them know that I die in the faith in which I lived and suffered for.`"
After these words, he uttered some others in prayer to God,
and so finished his life in perfect peace in the fiftieth year of his age.

The efforts of his enemies (causelessly such) exerted
with severity on his person and property,
could not sully his reputation any more than his conscience: Conspicuous for his virtues,
and the innocency and integrity of his life,
he was as generally respected and spoken well of amongst most who knew him,
as his sufferings were commiserated,
and the unmerited enmity and cruelty of his persecutors condemned.
In his outward confinement his free spirit, his love to the brethren,
and his zeal for the cause of truth, remained unconfined,
whereby his persecutors were frustrated in their designs,
as far as they expected by his imprisonment to deprive the society of his useful services;
for although he was restrained from travelling and edifying his friends by his ministry,
yet he neglected not, by his pen, to strengthen and comfort them under their deep trials,
in which he was their companion; to defend their doctrine against those who opposed it,
and his own practice, for which he suffered, in a copious treatise against oaths,
wherein he maintained the unlawfulness of swearing under the gospel.

Some time before his decease he made his will,
wherein he bequeathed a token of his affectionate remembrance to
several of his brethren and fellow-labourers in the ministry.
He also left a legacy to his poor friends in those parts where he lived.
For although his personal estate was forfeited to the king forever,
the confiscation of his real estate was only during his life;
so from thence having something left, he ordered the disposal thereof by will.

He writ also an Epistle of Advice and Counsel as
his last will and testament to his daughter,
imparting directions for her future conduct in life,
which conveying useful instructions to young people,
more peculiarly those of the female sex,
it may not be useless to annex the following abstract thereof.

"`Daughter Abigail, This is for thee to take heed unto and observe,
for the regulating thy conversation in this world,
so that thy life may be happy and thy end blessed,
and God glorified by thee in thy generation.
I was not heir to great possessions; but the Lord hath endowed me with a competency,
and hath been as a tender father to me, because I trusted in him,
and loved righteousness from a child.

"`My counsel to thee is, that you remember thy Creator in the days of thy youth,
fear him and serve him all thy days:
First seek the kingdom of God and the righteousness thereof.
Though thou be born into the world a reasonable creature,
yet thou must be born again into God`'s image.
Seek and thou shalt find; wait and thou shalt receive.
If thou ask, in what and how must I seek and wait?
I inform thee that thou must silence all thy own thoughts,
and thou must turn thy mind to that which is holy and good within thyself,
the light of Christ Jesus, wherewith thou art enlightened,
which shews thee when thou dost evil, and checks and reproves thee for it:
Take heed unto that, and it will show the evil motions and thoughts;
and as thou lovest it, it will subdue them,
and preserve thee for the time to come out of the evil;
and thou wilt feel thy heavenly father working in thee, and begetting thee into life,
and thou wilt feel the power of the Lord strengthening thee in thy little,
and making thee grow in the immortal seed, and outgrow all evil,
so that thou wilt daily die to it, and take no pleasure in it, but in the Lord,
and his goodness and virtue shed abroad in thy heart.
Love the Lord with thy heart and soul, even him that made thee,
and gave being to thee and all things in heaven and on earth.
And do thou inquire of thy dear mother, she will inform thee,
she knows him and the way to life and peace, and hearken to her instructions.

"`Be sober-minded in thy youth, and delight to read the scriptures and friends books,
and take heed to what thou readest, to conform thy practice thereto,
as far as thou understandest, and pray often to the Lord,
that he will increase thy knowledge in his law,
and open thy understanding in the things of his kingdom.
Search thy heart often by the light of Christ in thee, bring thy deeds to it,
that they may be tried thereby; and examine thyself,
how the case stands between the Lord and thee:
And if thou feel conviction for any wrong thing, regard the reproofs of instruction,
they are the way of life; humble thyself in sorrow,
and turn unto the Lord and he will show thee mercy,
and take heed for the time to come that thou run not into the same evil again:
Keep thy heart clean; watch against the evil in thyself, in that which shews it,
wherein there is power, and thereby thou hast power to overcome all evil.

"`Dear child, avoid sensual and sinful pleasures,
which are but transient delights terminating in misery;
but keep under the cross to the carnal will and affections; avoid evil and loose company,
for evil communications corrupt good manners; and associate with those who fear the Lord,
who worship in spirit and in truth, whose lives are holy and exemplary,
and whose conversation is pure and blameless.

"`And now, Abigail, as to thy well being in this life,
this is my advice and counsel unto thee; love thy dear mother; ever obey and honour her,
and see thou grieve her not; be not stubborn or wilful,
but submissive to her instruction, and obedient to her commands,
whose love hath been too great over thee and thy sisters,
which hath brought too much trouble upon herself.
Do thou always live with her, and be an help unto her,
and cherish her in her advanced years, that she may be comforted in thee,
and her soul may bless thee.
Love thy sisters, and be always courteous unto them and thy brother:
encourage one another to good.
Learn in thy youth to read, write, sew and knit,
and all points of honest labour and good housewifery that become a maid,
and as thou growest up in years labour in the affairs of the country.
Flee idleness and sloth as the nourishers of evil,
and beware of pride and vain curiosity;
be well content with such apparel as thy mother will permit thee,
and as thou mayest be a good example unto others.
And if thou live to be a woman, keep thyself unspotted,
and let not thy mind out after vain sports and pastimes; the end of all these is sorrow.
And in thy converse with young men be very discreet and watchful over thy affections,
not to be unwarily drawn in to any imprudent or unhappy attachment.
Preserve the modesty of thy sex inviolate: If thou incline to marry, seek not an husband,
but let an husband seek thee: And if thou live in the fear of God,
and lead an honest and virtuous life, they that fear God will seek unto thee.
Let not out thy affections to every one that offers, but be very considerate;
and above all things (if thou dost marry) choose a religious man,
and make thyself thoroughly acquainted with his conversation
and course of life before thou give consent.
Be discreet and wise, hide nothing from thy mother, and if she be living,
marry not without her consent.
And if thou join thyself to an husband,
let it be thy especial care to preserve thy affection to him unimpaired;
be compliant to his desire, and honour him before all;
give him no occasion of uneasiness or dissatisfaction but be gentle and easy to be entreated,
and mind thy own business: By these means thou wilt engage his heart,
and increase his affection to thyself: And if the Lord give thee children,
bring them up in his fear, and in useful employment,
that thou mayest be favoured with the Lord`'s blessing in thy youth,
in thy advancing years, and all thy life long.
These things I give thee in charge to observe as
my Mind and Will and Counsel unto thee unalterable,

Thy dear father,

"`FRANCIS HOWGILL.`"

26th, 5 mo.
1666.`"

The people called Quakers appear to have been pretty much
undisturbed by the civil power through this year,
in comparison of the former, their sufferings being mostly by excommunications,
imprisonments and distraints for their conscientious
scruple against paying ecclesiastical demands,
several of which however were unreasonably severe.^
footnote:[Robert Goodes of Wraslingworth in Bedfordshire,
was prosecuted in the King`'s Bench for tithes of 45£. value,
at the suit of one Goodchild a tithe-farmer,
who obtained a verdict for 135£. treble value;
for which his goods were taken by an execution to the value
of 200£. but so undervalued by the she riff`'s officers,
that they pretended yet to want 41£. 3s. 4d. of their demand,
for which they took away his bed, and committed him to prison.
[.book-title]#Besse,# vol. 1. p. 7.
{footnote-paragraph-split}
From Thomas Cole of Lexden in
Essex nine cows worth 30£. were taken by distress for tithes.
[.book-title]#Besse,# vol. i.£. p. 202.
{footnote-paragraph-split}
Robert Latche of Cherinton in Kent,
had his corn seized and taken off his wagon, as he was bringing it home,
by a person employed by an impropriator, who had before taken his tithe off the land.
This proceeding was without any colour of law, and was so rudely acted,
that the said Robert`'s wife, being with child, was inhumanly abused,
thrown into a ditch among the bushes, and stamped upon.
[.book-title]#Besse,# vol. 1. p. 294.
{footnote-paragraph-split}
John Sagar of Lancashire,
prosecuted in the ecclesiastical court,
was excommunicated for not appearing there at a time when he was close shut up in jail,
and in consequence of that excommunication was detained in prison four years and an half.
His wife, afflicted at the loss of her husband,
and the difficulty of supporting four children in his absence, became distracted:
The prosecutor would not permit him the liberty of so much
as once visiting his wife in that doleful condition.
[.book-title]#Besse,# vol. 1. p.317.
{footnote-paragraph-split}
George Craggs, priest of Anderley in Lincolnshire,
with three servants, came to William Cliff of that town, as he was loading his corn,
and demanded tithes, which because William refused to give him,
the priest ordered his servants to strike him and his wife, saying,
they are excommunicated persons and if you knock them on the head,
there is no law against you: I will be your warrant; the way is clear.
His servants not answering his purpose, he himself struck the man`'s wife with a fork,
and the husband desiring him to forbear, and not abuse his wife, who was then with child,
the priest, enraged, pushed her violently on the body several times, and threw her down;
he also said to his servants, fetch my sword, I will revenged of them.
In short, the poor woman was so affrighted, and sorely hurt and bruised,
that she soon after miscarried of two children,
one of which had plain marks of the blows received,
and she herself was in great danger of her life.
Within a few days after this barbarity to the woman and her unborn babes,
the priest cast her husband into prison by a writ de excommunicate copiendo,
by that means as it were burying the man alive,
whom he could not excite his servants to kill.
[.book-title]#Besse,# vol. 1. p. 350.
{footnote-paragraph-split}
William David of Cardiganshire, a poor man,
who rented some land at 50s per annum, was annually demanded 20s. for tithe,
for which five times the value was constantly taken,
so that his tithe amounted to double his rent.
One year the tithe-mongers took from him two cows, whose suckling calves
for lack of sustenance died. [.book-title]#Besse,# vol. 1. p. 742.]

In the spring of this year,
George Fox travelling in the northern countries received intelligence,
when he came into Lancashire, that his old adversary, Colonel Kirby,
had thrown out threatenings,
that if he came into those parts he would call him into prison;
but at the time of his coming, Kirby being confined by the gout,
he escaped out of his hands, continued his journey to Liverpool,
and embarked from thence in company with John Stubbs and Thomas Briggs for Ireland,
spent some time in visiting his friends in that nation,
and soon after his return married Margaret Fell.
