== Chapter XVIII. WALES.

[.chapter-synopsis]
* Abuses of Friends previous to the Insurrection of the Fifth-monarchy-men
* Unlawful Seizure of Cattle
* Sufferings of Francis Winson
* Of Several Friends consequent to the Insurrection
* Of Friends of Shrewsbury

The number of the people called Quakers in many parts
of this principality being considerably increased,
they were exposed to the like severities with their friends in England,
even before the insurrection of the fifth-monarchy-men had furnished a
palliative for violating the king`'s promise of protection to tender consciences.
We meet with the following specimen of the malicious
disposition which actuated their adversaries,
and of their precipitancy, in these remote parts as well as many others,
hurrying them into persecution without waiting for
any apparent cause or colourable pretence,
except that of holding their religious meetings.

In Merionethshire, in the month called August,
about fourteen friends being met for religious worship, were assaulted by Alban Vaughan,
and several rude persons armed with swords, who haled them out of the meeting place,
and threatened to carry them to Carmarthen castle twenty-six miles off;
but after they had driven them about two miles,
frequently striking them with their swords, they let them go.
A few days after the same body of armed men on horseback came to
the several dwelling houses of those they had thus abused,
and haled them out by violence, some out of their beds, wounding,
beating and bruising several;
and drove them on foot before their horses twenty miles to Bala:
Four of them were required to take the oath of allegiance,
and for refusing it were committed to the jailer`'s custody, who put them in irons,
and caused them to go fettered twelve miles to prison,
where he kept them with others of their friends, above twenty in all,
about fifteen or sixteen weeks,
not suffering any to carry them food or other necessaries, and taking away their bibles,
inkhorns, knives and money, and daily insulting and abusing them in a barbarous manner.

Nor was the corporal abuse and imprisonment unlawful of their persons
a sufficient gratification of the malignity or avarice of their persecutors,
exorbitant depredation was added to personal injury; for several of said persons,
during their imprisonment, had their cattle seized in great numbers,
about six hundred and fifty head in all, which were driven to Bala, there sold,
and the amount disposed of at pleasure,
without rendering any account there of to the owners.

They continued to be harassed in like manner in different parts of this principality;
their meetings being illegally broken up by soldiers with swords drawn and lighted marches;
they generally took the men to some justice to tender them the oaths,
and for their conscientious refusal drove them in crowds to prison,
until the insurrection of the Millenarians or fifth-monarchy-men broke out,
upon which the friends in Wales suffered equally
with their brethren in the different parts of England.
Francis Winson was taken out of his own house by soldiers, kept two days upon guard,
and sixteen days at the marshal`'s house, where he was hardly used;
after which he was brought before the commissioners, who tendered him the oath,
and sent him to prison, where he was shut up in a dungeon.
He was a poor labouring man, had a wife and five small children,
whose subsistence depending upon his labour,
they suffered much hardship by means of his confinement.

On the 31st of the month called January, Walter Jenkins, John Williams,
Philip Williams and Charles Jenkins were forcibly taken out of their beds,
their doors being broken open by a party of horse,
several of whose officers were papists.
They broke open their coffers and trunks under pretence of searching for arms,
and though their violent search discovered none,
they drove these inoffensive men several miles, through mire and dirt, to an old castle,
where they were detained until the next morning, when the captain of the troop came,
and ordered a party of rude soldiers to conduct them to Monmouth,
who drove them thither most inhumanly along the dirty road,
not suffering them to walk on the foot-way.
The mayor of Monmouth committed them to prison for refusing to swear,
where they were confined in a place noisome and offensive
by its filthiness to an extraordinary degree.
Hither William John, who was taken from his business in the field,
was sent to bear them company, where being confined together several of them fell sick,
though the noisomeness and unwholesome air of their prison,
upon which the jailer removed them to his own house.
Several were taken travelling on the highway about
their lawful occasions and sent to prison,
and in some parts watches were set with orders to suffer
no Quaker or Anabaptist to go from one parish to another,
or gather together to any meeting or conventicle,
but to take especial care to secure all Quakers in their respective parishes.
Such was the violent bitterness of the persecutors here,
that the mere name of Quaker exposed those that bore it to the loss of their liberty,
and in consequence of these orders forty persons of this denomination were taken,
some from their own houses, some on the highway,
and others from their religious meetings, and sent to prison at Cardiss.

At Shrewsbury the number of prisoners being also large, many of their friends,
from the impulse of christian love, came to visit and assist them.
As soon as the soldiers who kept guard at the prison discovered
any of these persons coining to visit the prisoners,
they immediately apprehended them, and carried them to the mayor,
who tendered them the oath and sent them to prison.
To recite at full length all the severity and abuse
they underwent in the different parts of Wales,
similar to the inhuman treatment they suffered in different parts of England,
would be tedious and irksome to write and to read; suffice it therefore to remark,
that the same vindictive spirit, which hunted them from their meetings, their houses,
their lawful employments, to prison, was manifested in the usage they met with there,
shut up in filthy close rooms, seven in a hog-house,
exposed to all weathers without sufficient shelter;
others thrust among felons and murderers, who robbed them of their food and money,
and otherwise abused them with impunity;
aged and sickly people kept whole winters without fire,
whereby their hands and feet were much swelled;
wives who had come many miles through great difficulty to see their imprisoned husbands,
prohibited from seeing them or carrying them provisions, and forcibly sent away.
One of them, Elizabeth Holme, only for this office of affection and duty,
had her horse and saddle seized, and herself detained in prison with her husband.
Many of those at liberty were grievously beaten and abused
to the hazard of their lives by wicked persons on the road,
who on presumption of impunity made it their sport to insult and abuse them.

Thus in time of peace,
they were exposed to all the evils of war (except a violent death,) for what
usage more inhuman could they experience from the invasion of a foreign enemy,
than they did from their own neighbours in this heat of party-rage and civil tumult,
artfully kindled for the mere purpose of forcing conformity against conscience,
or punishing conscientious non-conformity?
