== Chapter XIX. Scotland.

[.chapter-synopsis]
* Convincement of Alexander Jaffray and Margaret Molleson, James Urquhart, Robert Gordon and John Robinson
* William Forbes, contrary to conviction, publishes an Excommunication against Urqubart
* Next under the like Conviction, being about to publish one against his own Daughter, is prevented by sudden Death
* George Gray and Agnes Simon convinced
* The Priests of Aberdeen endeavour to stir up Persecution
* The Populace excited to riot
* The Priests by application to the Bishop get Andrew Jaffray fined and imprisoned
* David Barclay convinced
* And soon after his son Robert
* And Lilias Skein

In 1659, Stephen Crisp, a man well qualified for that work,
travelled into Scotland to preach the gospel there, and some time after William Dewsbury;
the gospel testimony of these faithful witnesses
did reach the consciences of many who heard them,
and amongst these some noted professors in Aberdeen, particularly Alexander Jaffray,
who had been chief magistrate of that city,
a man in high repute amongst the highest professors of religion,
and Margaret Molleson wife of Gilbert Molleson, a magistrate of Aberdeen,
a woman of distinguished character amongst the better sort for her religious endowments.

The said Alexander Jaffray, soon after his convincement, removed to Inverary,
and was instrumental to settle a meeting there:
By means whereof several thereaway having the opportunity
of hearing the doctrines of this people declared,
were convinced: Of these were James Urquhart and his wife,
Robert Gordon and John Robinson.
After some time James Urquhart fell under the censure of the presbytery and was excommunicated;
the excommunication was sent to William Forbes,
priest of the place of Urquhart`'s residence,
with an injunction from the presbytery for him to publish it from the pulpit.
To complying with this injunction he felt great reluctance,
from a conviction of the worth and integrity of the
person he was enjoined to read the sentence against;
but under the prospect of the probable loss of his stipend,
in case of his disobeying the presbytery,
interested considerations overcame his convictions,
and he publicly pronounced the sentence against him,
in direct opposition to the dictates of his own conscience.
He afterwards fell under great uneasiness and anxiety of mind,
which discomposed him to so great a degree,
that for some time he was disqualified from performing the offices of his function,
until at length he made this ingenuous confession,
That his discomposure was a just judgment upon him,
for cursing with his tongue a person whom he believed
in his own conscience to be a very honest man.
But notwithstanding the strength of his convictions at that time,
he afterwards fell into the like error in a case more nearly affecting him;
his own daughter Jane Forbes was convinced of the principled of the people called Quakers,
and joined them in society:
Church proceedings were carried on against her to an excommunication,
which her father was required by the presbytery to pronounce.
It is easy to imagine in how distressing an alternative he must be thereby involved,
under the prospect of either wounding his conscience and parental feelings,
by pronouncing excommunication against his own daughter,
whom he knew to be an honest woman,
or to be ejected from his living for disobeying the presbytery.
Again the latter consideration preponderated against conscience and natural affection:
But, alas,
the anxious conflict between conscience and self-interest
was too oppressive for nature to support;
he determined to read the excommunication, but was suddenly struck with death,
at the very time he purposed to do it.

About the same time with James Urquhart before-mentioned,
George Gray and Agnes Simon were convinced,
two persons so highly thought of for their religious attainments and circumspect conversation,
that the priest of the parish whereto they belonged made it his boast,
that he had a weaver and a poor woman whom he would deny any of the Quakers to equal,
either in knowledge or a good life: but when shortly after, both these hearers,
withdrew from under his teachings, and joined the Quakers,
the priest was exceedingly enraged thereat.

The said Agnes Simon, after her convincement,
readily opened her house for the keeping of religious meetings,
and the neighbouring people flocked to the assemblies held there in such numbers,
that her house could not contain them, wherefore they met in the open field,
where Patrick Livingstone was made instrumental, with some others,
to the convincement of many in those parts.
This convincement drawing away many of their hearers,
mightily alarmed the priests of Aberdeen,
viz. George Meldrum and John Menzies and others,^
footnote:[The ministers resisted them and their testimony,
by aspersing them with many gross calumnies, lies and reproaches, as demented,
distracted, bodily possessed of the devil,
practising abominations under colour of being led to them by the spirit;
and as to their principles, blasphemous deniers of the true Christ, of heaven, hell,
angels, the resurrection of the body, and day of judgment.
This was the vulgar and familiar language of the pulpits,
for a time received as unquestionable truths,
till about the year 1663 some sober and serious persons in and about Aberdeen
began to examine the ways and principles of this people more narrowly,
which proving upon inquiry to be far otherwise than they were represented,
their inquiry let them see the integrity and soundness of this abused people,
and the prejudiced disingenuity and enmity of their accusers.
R+++.+++ Barclay`'s preface to Truth cleared of calumnies.
{footnote-paragraph-split}
1666+++.+++ George Meldrura preached a most virulent sermon against the Quakers,
wherein he represented them in such colours as he thought
most adapted to excite his hearers indignation against them,
and conscious of the possible groundlessness of his accusations,
to secure his calumny from confutation, enjoined his auditors,
who had taken it down in writing, not to let the Quakers have a copy:
But Alexander Jaffray and George Keith obtained a copy,
which they found easier to answer than to procure. [.book-title]#Besse,# vol. 2. p. 498.]
who in consequence thereof exerted their endeavours
to prevent the progress of this people,
by aspersing them from the pulpit with undeserved calumnies and reproaches,
in order to incense the magistrates to suppress them,
and to raise among the ruder and less intelligent part of their hearers,
a spirit of riot and indignation, prone to abuse and vilify them on all occasions.
Their efforts to excite the magistrates against them met not, as yet,
with the success they wished for,
their violent attempts being in several instances frustrated;
for they could not by their utmost endeavours prevail upon the secular
power to exert itself to the height of persecution they aimed at,
which was the total suppression of that people.
But with the ignorant and ill-judging populace,
their slanders had a more effectual influence,
for it frequently happened that as soon as any of
this persuasion appeared in their streets,
a mob gathered about them, stoning,
beating and abusing them as they passed quietly along:
and so deeply was this spirit of riot and mischief implanted in them,
that this species of persecution and lawless abuse
was continued in many parts of this nation,
long after legal persecution was abolished by the act of toleration.

Being less successful with the secular power than they desired,
inimical as their principles were to the power and office or bishops, these priests,
to compass their aim, made no scruple to excite the bishop of Aberdeen,
and by his means archbishop Sharp,
to exert their power against the people called Quakers.
Andrew Jaffray, a man of a blameless life,
and of good esteem among the sober and serious inhabitants,
at the suggestion of these priests,
was summoned to appear before the high commission court,
before which he was enabled to bear a faithful testimony to the truth;
and although the archbishop himself entered into a conference with him,
he could gain no advantage in argument against him; yet to satisfy the priests,
the court passed sentence upon him,
"`That he should be confined to his own dwelling house, and keep no meetings therein,
nor go any whither without the bishop`'s license,
under the penalty of a fine of 600 marks,`" which
they esteemed to be one fourth of his yearly rents.
By the like means, at the suggestion of James Gordon, priest of Alford,
to the bishop of Aberdeen, Alexander Forbes of Archinhamper, and Alex ander Gelly,
were apprehended, carried away to Edinburgh,
and imprisoned in the Cannongate Tolbooth some time.

But by these rigorous proceedings the priests did not attain their desire,
others from time to time fell off from them, and joined the Quakers by convincement,
and amongst them some persons of note. In the year 1666 David Barclay of Ury,
adopted their profession, and steadfastly continued therein the remainder of his days.
And in or about the next year his son Robert was also convinced as before remarked.
As was Lilias Skein wife of Alexander Skein, one of the magistrates of Aberdeen,
a woman much esteemed for her religious accomplishments,
and in a particular manner by the aforesaid George Meldrum their priest.
She was convinced or confirmed in her convincement by a very remarkable circumstance.
She was actuated by an earnest desire to find out the way of truth,
but discouraged from looking towards this society by notions and
prepossessions industriously instilled into her mind and that of
others of their hearers by the priests against that people,
that they denied the scriptures, and did not pray in the name of Jesus,
of whom the scriptures testify.
But being visited with indisposition,
she kept her chamber in an apartment under the same roof with Barbara Forbes,
one of that society, at whose dwelling the Quakers sometimes met,
so near the said Lilias`'s apartments that she could distinctly hear what passed: here,
attentively listening, she heard two Englishwomen exercise both in preaching and praying,
whose testimonies she observed to be replete with scripture expressions,
and their prayers put up in the name of Jesus, and attended with life and power.
From this demonstrative confutation of the calumniating accusations of these priests,
whom she formerly admired, and to whose representations she had given entire credit,
she was freed from her prepossessions; and discovering the falsehood of their assertions,
she withdrew from their communion,
and in consequence of this discovery and the effectual
reach of the testimony she had heard,
she was fully convinced and joined in society with that people.
And not long after her husband, who had been a zealous opposer of them,
became a sincere convert to their christian principles.
This added fuel to the passion of the priests,
who renewed their exertions to excite the magistrates against them, but still,
as yet without attaining the full gratification of their wishes.
