== Chapter XX. Ireland.

[.chapter-synopsis]
* Great Numbers imprisoned in consequence of the Rising of the Fifth-monarchy Men
* William Edmundson solicits and obtains their Release
* Several Friends fined by Judge Alexander
* Sufferings for Tithe
* Extreme Virulence of George Clapham, Priest of Mountmellick
* Ireland governed by Men of Moderation
* William Edmundson lays a Narrative of Clapham`'s Proceedings before the Government
* Who is summoned before the Privy Council and sharply rebuked
* His malignant Proceedings in revenge
* Sufferings of Friends in Cork through the Rancour of Christopher Rye, Mayor
* Richard Pike dies in jail
* Meetings of Discipline settled
* George Fox arrives in Ireland.

Robert Turner having about the year 1657 been instrumental to the
convincement of some persons who resided about Grange near Charlemount,
and by means of the labours of other friends,
who travelled in the exercise of their ministerial gifts, their numbers increasing,
a meeting was settled there this year,
which continues a large meeting at the present time.

Upon the revolution of government which took place at the King`'s restoration,
and the rising of the Fifth-monarchy-men, the people called Quakers in Ireland,
shared deeply in the like severities with their brethren in England;
their meetings were broken up with violence, they were taken out of their houses,
out of their fields, on the public roads, and haled to prison in such numbers,
that before the end of the year there was a general
imprisonment of friends through the kingdom.
William Edmundson hath left an account in his journal that
he with many more friends was prisoner at Maryborough,
but that the Lord supported them,
and bore up their spirits above their sufferings
and the cruelties to which they were exposed,
that friends were fresh and lively, contented in the will of God;
that they had many good meetings in prison, the Lord`'s presence being with them,
to their great consolation in him, who wrought liberty for them in his own time.

They continued under suffering through this year and part of the next;
but neither the governors nor inferior magistrates in general seem to have been
influenced against them to an equal degree of animosity with those in England.
Several of them on the contrary discovered an amicable
disposition and readiness to relieve them.
For after the nation became settled, and the passions of the people began to cool,
William Edmundson, being then a prisoner,
obtained his liberty for about twenty days from the sheriff,
whereupon he went immediately to Dublin and solicited the lords justices,
the earls of Orrery and Mountrath and Sir Maurice Eustace to set his friends at liberty,
who were imprisoned in different parts of the nation,
and was so successful as to obtain an order for their release.
Several copies of the order being procured and signed by the lords justices,
were forwarded to the sheriffs of the several counties,
where any of his friends were prisoners.

And soon after he visited the meetings of his friends through the nation,
and inquired whether the sheriffs had complied with the order,
which appeared to be generally done.
In about six weeks he accomplished the business and returned home;
but found his friends in the Queen`'s county, where he resided, still detained in prison;
wherefore at the ensuing quarter sessions he went to Maryborough,
to demand of the justices and high sheriff the reason
why the order of the lords justices was not obeyed;
the sheriff replied, they were detained for their fees, and they should pay them,
or lie there and rot.
This circumstance occasioned him another journey to Dublin,
But previously perceiving the justices did not approve of the sheriff`'s conduct,
but sympathized with the prisoners,
whose innocence had begot compassion in the minds of them and others,
he procured from them a certificate of the reason of their detention,
which was signed by three of the justices present.

Thus provided he renewed his application to the lords justices,
and through the particular favour of the earl of Mountrath (who,
as well as his son after him, entertained a personal regard for William Edmundson,
and a benevolent disposition towards his friends in general) he readily procured a positive
order to the sheriff to set friends at liberty without paying fees to any person:
with this order he hastened back, and delivered it to the sheriff,
who immediately complied in releasing them, but with an ill-grace;
for being greatly exasperated at the deprivation of this perquisite,
he could not refrain from venting abusive language and hard names at William
Edmundson for his intercession in favour of the prisoners.

The good effect of this order, and the benevolent disposition of many magistrates,
is farther evinced by the testimony of Edward Cooke,
in a letter from Dublin dated the 29th of 9 mo.
this year, in which he writes, "`Friends are generally well,
and none in prison but in Cork, where we expect shortly to be released;
the justices are very ready to help us at their sessions,
so that at present we have no just cause to appeal any where else.`"^
footnote:[[.book-title]#Besse.#]

Yet there were some magistrates whose treatment of this people was marked with a malevolence,
exciting them to illegal severity and injustice resembling
the persecuting measures we have noticed in England,
particularly in this year judge Alexander, who caused Henry Rose,
Thomas Shannon and nine others,
who had been apprehended at a meeting and committed to prison at Carlow by John Masters,
Portrieve, without examination or mittimus in writing,
and had been indicted at the quarter sessions, and by the jury found not guilty,
to be again indicted at the assizes, and being found guilty of meeting,
he fined them 320£.

At Cork he fined Alexander Atkins, Philip Dymond,
Thomas Cooke and several other prisoners 1190£. on the same account.
And at Waterford, upon William Blanch,
William Wright and eight others he imposed a fine of 580£. And at Limerick
sundry friends being prisoners for the same cause of simply meeting together,
he fined them 40£. a piece, and remanded them to prison,
where they continued four months, till released by an order from the lords justices.

They were also here as well as in England liable to grievous sufferings and spoil of
goods from the covetousness and malevolent disposition of self-interested ecclesiastics,
who by themselves or agents frequently took distresses from them manifold their demands,
which for conscience sake they could not pay.
Many were imprisoned,
and long continued in prison on definitive sentences and writs of excommunication,
to which some of the clergy, in the true spirit of priestcraft,
endeavoured to give the force and extent of an outlawry,
and annex all the dreadful consequences with which
they were attended in the darkest ages of popery.
George Clapham, priest of Mountmellick in the Queen`'s county,
having procured the excommunication William Edmundson and several others,
endeavoured to deter the millers from grinding their corn for the use of their families,
or any to speak or trade with them: he watched the markets and the Quakers shops,
and to those he saw or knew to deal with them,
he would send an apparitor to summon them to the bishop`'s court,
the apprehension whereof generally terrified them into a pecuniary
composition both with the mercenary priest and apparitor,
to get free from the effects of a prosecution in this dreaded court.

This same priest degraded the dignity of his function of a minister so far,
as to tell his hearers,
That if they met any of the excommunicated Quakers on the
highway they should shun them as they would shun the plague;
that if they owed them any debt, they need not pay it;
or if they knocked them on the head, the law would bear them out.
Strange doctrine indeed from one assuming the character of a minister of the gospel!
His doctrine however had not the desired effect upon his hearers;
they received it with abhorrence,
and knowing the integrity of their peaceable neighbours,
this specimen of his malignity lessened their reverence to their minister,
and awakened their sympathetic feelings for the sufferers,
they offered their servants to carry their corn to
the mill to supply them with bread for their families,
or any other kindness in their power,
and by their humanity frustrated so far the evil designs of this envious priest.

It was the happiness of Ireland at this time to be
governed in church and state by men of more moderation,
and less biassed by the influence of a party spirit and partial political designs,
than several of those in high stations in England seem to have been.
The primate Boyle, who was also chancellor,
appears to be actuated by a very different temper from archbishop Sheldon:
I conceive from his conduct in this business the discreet and judicious governor,
who knew how to distinguish between real and imputed disloyalty;
between the administration of legal and arbitrary rule;
and to establish the authority of the governor in the justice and humanity of the man.
William Edmundson drew up a narrative of Clapham`'s gross proceedings,
and got it attested by the signature of several of his own people,
with which he went to Dublin, and petitioned the government upon the subject thereof.
The primate, as well as the privy council, before which it was laid,
expressed his indignation at his proceedings,
as contrary to all law and rule and immediately an order was issued
for the priest and apparitor to appear before the council.
They appeared accordingly, and met with severe reproof.
The primate said he would make examples of them, and would have had them punished;
but William Edmundson informed him that he and his
friends wanted no thing more by their application,
than a stop to be put to such cruelty as they had suffered under,
in order that they might live peaceably in their callings without molestation.
The primate bade William, If they did not desist from such proceedings,
only write to him, and be would make them examples to the nation.
So William forgave them, and let the matter drop.
This instance of his pacific and forgiving spirit further conciliated
the good opinion of many principal men in authority of his principles,
and a favourable regard towards him and his fellow professors in general.

But Clapham being mightily incensed against William Edmundson,
for exposing his proceedings, and bringing him under the censure of his superiors,
continued to be vexatious to him and his friends, as far as in his power.
Having procured a neighbour`'s horse and car, he came to William`'s house,
loaded and carried away a considerable quantity of cheese from him, and much goods,
corn and even wearing apparel from other friends of the meeting he belonged to,
for some church rates, as he said; and not satisfied herewith, he,
being a justice of peace,
sent a constable to apprehend William Edmundson (from a meeting at Mountmellick)
and made a mittimus to send him to Maryborough jail;
but the earl of Mountrath superseded his warrant,
and set William at liberty till the ensuing assizes,
at which the earl patronizing his cause, and four lawyers pleading for him unfeed,
against two indictments which the priest had preferred against him,
the indictments were quashed,
and the priest gained nothing by this vindictive at tempt against
his peaceable neighbour but flume and disgrace.

Yet notwithstanding these repeated disappointments,
he continued to discover his propensity to persecution by various efforts to bring both
William Edmundson and several others of the people called Quakers into trouble.
He indicted William for not paying an assessment
towards the repairs of the public worship house,
although he had been distrained by the wardens and constable for the same before,
who took a mare away from him worth 3£. 10s. He again indicted
several friends for being at a meeting on a certain day,
and for not being at church (as he termed it) the same day;
in consequence of this prosecution several were fined,
and warrants issued for levying the fines by distraints.
In order to use endeavours to rescue his friends from suffering
for the conscientious discharge of apprehended duty,
from the malice of unreasonable men.
William Edmundson went again to Dublin,
and presented a petition upon the subject to the lord lieutenant and council:
himself and another friend were admitted into the council-chamber to state their grievance;
and after a patient and candid hearing the council gave
judgment that the proceedings against them were illegal.
The lord lieutenant being desirous to be informed
why they did not pay tithes to the ministers,
William Edmundson informed him from the Scriptures,
that the law was ended that gave tithes, and the priesthood ended that received them,
by the coming and suffering of Christ, who had settled a ministry on better terms,
and ordered them a maintenance:
he then inquired what maintenance the ministers must have?
and William replied, Christ`'s allowance, pointing out from the Scriptures what that was;
as the Lord, he saith, opened them to him,
and gave him wisdom and utterance to treat the subject clearly to their understandings.
There were three bishops present, but none of them made any objection in reply.
The lord lieutenant, in conclusion, bid God bless them;
adding that they should not suffer for not going to the public worship,
nor for going to their own meetings.
This favourable disposition of the chief ruler awed the priest into quietness,
and occasioned a public opinion that the Quakers
had received a toleration of their religion,
which was productive of much ease to the members of this society,
who had suffered greatly both by imprisonments and
loss of substance on a religious account.

In effect of this moderation in the governors,
the sufferings of the Quakers (so called) were inconsiderable
through the course of the succeeding year,
and longer in most parts; but in the year 1667 persecution grew hot in Cork,
through the intemperate rancour of Christopher Rye, mayor of that city,
to the members of this society, who imprisoned them in great numbers,
only for keeping up their religious meetings,
and caused their imprisonment to be particularly rigorous and severe; and amongst:
other respectable inhabitants of the city, Richard Pike,
who lost his life by cold and distemper, contracted in the jail; and William Penn,
lately convinced there, as before related, who during his residence in these parts,
having contracted an intimate acquaintance with many of the nobility and gentry,
wrote to the earl of Orrery, lord president of Munster,
acquainting him with the cause and manner of their imprisonment,
and soliciting him to interpose his authority for restoring them to their liberty,
which request, so far as related to himself, was readily granted,
the earl immediately ordering his discharge.

The society being now greatly increased in number,
upon the receiving of George Fox`'s epistle of advice to set up meetings of discipline,
the usefulness and necessity thereof appearing manifest to friends in Ireland,
they proceeded in Ireland to establish them,
in the same manner as their brethren in England had done.
The care whereof rested principally upon William Edmundson,
who had been chiefly instrumental to the gathering of the society in that nation,
and preserving them in fidelity to their principles.
They began with establishing provincial meetings to be held once in fix weeks;
for these were prior to the monthly meetings,
as the quarterly meetings in England were prior to the monthly meetings there;
and those affairs which have since been the subjects of deliberation in monthly
meetings at first fell under the cognizance of the provincial meetings,
because in these times of infancy and sufferings the mutual help
and advice of friends assembled from different parts appear necessary,
when some particular meetings were weak and small.

In the forepart of the succeeding year George Fox landing in that
nation in company with Robert Lodge and some other friends,
seconded his epistolary advice,
by his presence and personal assistance and directions
in settling men`'s and women`'s meetings.
At Dublin he recommended the holding of their men`'s
and women`'s meetings once in two weeks,
which hath continued ever since; in some places they were agreed to be held monthly;
in others once in six weeks, as exigency or convenience required:
He likewise recommended the establishment of a general national meeting
to be held half yearly in Dublin in the third and ninth months.
The first meeting of this sort was held there in the third month 1670,
O+++.+++ S. and this settlement still continues.

By which establishment the society in that nation
(as well as in England) became a compact body,
united in a benevolent concern for the mutual help and edification one of another,
and of the body in general,
as the exigencies of individuals or the society at large might render requisite.

In those early days the principal employment of these meetings was the collecting
and recording the sufferings of the respective members of the society,
and the account upon which they suffered;
and to make proper application for the relief of friends,
or for their release from imprisonment.

But in process of time many other weighty affairs,
respecting good order and discipline in the church,
seemed necessary subjects for consideration in these meetings;
and friends in that nation became eminently conspicuous
for their zeal and diligence in the supporting thereof;
the same spirit of wisdom and sound understanding leading them
and their brethren in England into the same salutary rules,
excellent in themselves,
and highly conducive to the preservation of the community in a life and
practice consistent with the purity of their profession.

George Fox travelled over several parts of the nation,
visiting his friends in their meetings of discipline, as well as worship,
to set a-foot those meetings in the different quarters;
and when he had accomplished his service, he took leave of his friends in much affection,
in the sense of the heavenly life and power that was manifested among them,
and with his companions returned to England.

Of this visit George Fox himself gives the following account.
"`The priests and magistrates were envious, but the Lord disappointed their counsels,
and gave us many blessed opportunities to visit friends, and spread truth in that nation.
Meetings were large, friends coming to them far and near:
Many were reached and convinced, and gathered to the truth,
and friends greatly refreshed.`"
