== Chapter XXI. ISLE or MAN.

Persecution in the Isle of Man exceedingly grievous.--William Callow and
Evan Christen suffer severe Imprisonment for very trivial Demands.--Warrant
issued by two Priests for committing the Quakers,
so called, to prison.--They are excommunicated without Process,
and delivered over to the secular Power.---Order for their
Transportation.--Put on board a ship to be transported,
upon which the Sailors leave the Ship.--Forced on board other Ships and taken to Dublin,
and sent back by the Mayor.--William Callow and Evan Christen have
a long Conference with the Bishop and Dean.--They go to the Island,
but are not suffered to land.--Their Estates seized.--William Callow,
after an ineffectual Application to the Earl of Derby,
solicits the Intercession of the Duke of Tork and Prince Rupert.--The Bishop`'s
Inhumanity.--Four Women banished with Circumstances of Barbarity.--Attempt to
transport William Callow to Virginia.--Is landed in Ireland.

Persecution in this sequestered island,
under the arbitrary rule of the lord of the land (the Earl
of Derby) and the uncontrolled power of a rigid prelate,
whose intemperate bigotry excited his blind zeal more to force
uniformity in religious profession and ceremonious worship,
than to cultivate in himself or his flock the essentials of true religion,
viz. the fear and love of God, and benevolence to mankind;
was continued with additional severity after the restoration,
even beyond the severity of the rulers under the long parliament and commonwealth,
before related, against the few residents in this island,
who went under the denomination of Quakers.

The number of them here was very small;
the power and influence of the clergy being more prevalent in this dark corner,
where the ignorance and rudeness of the inhabitants furnished opportunity,
than in the more enlightened nations.
This power and influence they have uniformly exerted,
rivalling popish ecclesiastics in the darkest ages,
to prevent the introduction of any other doctrines
than those themselves have adopted and taught;
but particularly such as to prevent are adverse to their interest and authority;
so that through the awe with which the generality of people regarded these teachers,
they were deterred from attending to or receiving any doctrines different from theirs,
and the more so still from the observation of the unfeeling cruelty,
with which those few, who had received those of the people called Quakers, were treated.

William Callow and Evan Christen, the former for refusing to pay sixteen-pence,
and the latter two-pence, demanded by a priest for bread and wine for the sacrament,
were committed to the prison called St. Germain`'s in Castle Peel,
and were close shut up in a dismal dungeon without fire, candle or bedding,
having only straw to lie upon and a stone for their pillow: Here they lay sixteen days,
until some of their neighbours, out of mere compassion, unknown to them, paid the money,
otherwise they might have perished there, their rigid persecutors, two priests,
one the complainant, the other the judge of the bishop`'s court,
who granted the warrant for their commitment,
appearing by their actions to value the lives of
two honest innocent men at less than eighteen-pence.
They were again, with several others,
imprisoned ten days for absence from the public worship, and a third time,
with six others, for being at meeting, were confined in a high tower at Castle-Rushen,
without fire or candle, fifteen weeks in the cold winter, only William Callow,
after a month`'s imprisonment, appealing to the Earl of Derby,
obtained permission to go to London,
where at length he procured the Earl`'s warrant for
the discharge of himself and the rest.

They were imprisoned again the succeeding year, together with Evan`'s father,
eighty years of age;
and the following year presents us with the extent and independency
to which ecclesiastical power was stretched in this wretched island,
by the following order issued by two priests, judges of the Bishop`'s court,
for imprisoning the Quakers.

"`We have received orders from our reverend ordinary
to admonish the Quakers to conform and come to church,
or be committed until they submit to law and forasmuch as they refuse,
after several charges and publications in the parish church,
but continue their refractoriness to all government of the church,
and are therefore censured to be committed into St. Germain`'s prison,
and there let them remain till orders given to the contrary,
and for so doing this shall be your discharge.`"

"`ROBERT PARR.

"`JOHN HARRISON.

"`P. S. If they refuse to be committed by you,
call for the assistance of a soldier from Captain Ascough.
Let the fumner put this in execution immediately.`"

By this order the said William Callow,
Evan Christen and some others were again lodged in their former dismal mansion of Germain`'s,
and in about four months after all the women of this
profession were arrested by a fumner or apparitor,^
footnote:[These were the wife of said William Callow,
(who being just recovering out of a fever, and unable either to walk or ride,
was suffered to stay at home for the present) Jane Christen, Jane Kennell, Anne Christen,
Mary Callow and Mary Christen;
one of whom was seventy -four and another sixty-seven years of age,
a third a poor serving man`'s wife, who had three children, the youngest at her breast;
the fourth, the wife of one not called a Quaker, had a large family and many children,
and the fifth a servant of William Callow,
who was forcibly taken from her sick mistress.]
by virtue of an order of the bishop to carry them all to prison, they being, he said,
both men and women excommunicated,
of which excommunication they had not the least intelligence,
before he now declared it to them.

The prison allotted them was the same gloomy dungeon in which the men were confined,
whither when the apparitor had brought them, he took off his hat,
and formally pronounced what he called the bishop`'s curse, to this effect,
"`I do here before the standers-by deliver you up into St Germain`'s prison,
by the law of my lord the bishop and his clergy,
you being cast out of the church by excommunication,
and I do take witness that I do deliver you over
from the power of the bishop and his law,
to be and continue the Earl of Derby`'s prisoners.`"
What he meant by this reverie, the prisoners could not devise,
as there was none present but himself and they.
Having finished his speech he left them, and they continued there many months,
enduring the hardships of a close and unhealthy confinement,
the cruel mercies of the bishop and his clergy.

Being thus after the example of Romish priestcraft turned over to the secular power,
which appears here as arbitrary, as that of the ecclesiastics was exorbitant,
seeming to be exercised by the mere will and pleasure of the Earl of Derby,
in the month called June, 1665, Henry Nowell, deputy governor, came to the castle,
and read to the prisoners an Order from the Earl,
that they must be forthwith transported to some other land:
And near the end of the month two priests came to them,
and informed them they were come by the deputy governor`'s
order to admonish them to come to church,
otherwise they must be banished forthwith.

On the 5th September the commander of the castle received
an order to send all the Quakers prisoners to Douglas,
which was done on the 7th:
And there they were kept under a guard of soldiers until the 14th,
when they were put on board a ship of which Thomas Brittain was master;
but as the prisoners entered on one side of the ship,
the seamen went out at the other into the boat,
telling the master they were not hired to carry people
out of their native country against their wills,
and that they would not go leave the with him if he carried them, so went on shore,
leaving him only a boy or two.
The master finding his men determined,
and himself unable to proceed on his voyage without them,
set the prisoners on shore again, which being done, the sailors returned,
and the ship set sail.

About three days after several vessels came into the road;
but all refused to carry the prisoners.
The soldiers endeavoured to force them on board the ship of Anthony Nicholson,
of Whitehaven; but he strenuously opposed it, insisting that he would carry no prisoners,
except they would send a guard of soldiers, and money masters,
to maintain both the prisoners and them,
and also to signify in writing the crime laid to their charge.
However, on the 18th, about midnight, four of the prisoners, viz. William Callow,
Evan Christen, Jane Christen and Mary Callow,^
footnote:[They purposed also to have sent another woman of seventy-four years of age,
but left her, being loo weak to remove, lying, as they thought,
at the point of death on a bed of straw.]
were hurried out of their beds with such precipitancy,
that they were not allowed time to put on their clothes,
but obliged to leave some of them behind;
two of them were forcibly put on board Nicholson`'s ship,
and the other two on board William Crossthwaite`'s against the will of the masters.
They sailed to Dublin,
where neither the seamen nor prisoners were suffered
to land until Crossthwaite was examined by the mayor,
who demanded his warrant for bringing the prisoners without their consent,
to which he answered, that he had no warrant,
but was compelled to take them on board by one Quail, an officer,
who took away his sails, and would not let him put off without the prisoners,
and his vessel was in danger of breaking.
Upon which the mayor gave him the following order.

"`SIR,

"`You are hereby required to take back in your own vessel, the prisoners called Quakers,
which you brought against their voluntary consent out of the Isle of Man,
and them to put on shore on the said island, to follow their necessary occasions;
of which you may not sail at your peril.

"`Dated the 27th of September, 1665.`"

Pursuant to this order he brought them back, but either being, or pretending to be,
driven by the island by contrary winds, he carried them to Whitehaven,
and there put them on shore; but Carried to John Lamplugh, a justice of peace,
issued his warrant to the constables of Whitehaven
to cause them to be put on board Crossthwaite`'s ship,
to be carried back to the isle,
as no order or legal proceedings appeared to authorize him to bring them into that country.
So on the 12th December Crossthwaite took them on board again,
but instead of carrying them to the island, carried them again to Dublin,
but would not be suffered to land them there until he had
given security to convey them to the island on his return.
But in violation of his engagement he returned with them to Whitehaven.
Thus were these innocent persons harassed and tossed
back ward and forward in the cold winter season.
Being landed again in England, the two men went to the Earl of Derby,
and while they were employed in fruitless solicitations to him and the bishop,
for liberty to return to their places of residence and lawful occupations,
Crossthwaite carried the two women back to the island,
where they were again shut up in prison.

These two men after long attendance upon the Earl of Derby, were by him referred to shop,
to the bishop, to whom (after some time coming to Knowlesly Hall in Lancashire,
the said earl`'s seat) they got admittance,
and had a long conference with bishop and him and the dean,
wherein they endeavoured to move him to compassionate their case,
and give an order for their return to their wives and children,
and to their honest labour at home;
but he appeared callous to every sensation of clemency,
he would by no means admit of their return,
and by his influence the earl was also hardened against them;
for although his officer had pretended to deliver them over from the bishop`'s power,
as excommunicated persons, to the civil power,
and this bishop himself pretended he had done with them;
yet it appears by his own acknowledgment in their conference with him,
and by their subsequent sufferings, that so far from having done with them,
he was the principal instrument in promoting all the persecuting measures against them.
The conference itself is too prolix to be introduced here at full length;
But a small part thereof, as conveying an idea of this bishop`'s spirit,
may not be impertinent to lay before the reader.

Bishop.
What have you to say to me?

Answer.
We have to say to thee, viz, to let thee know that we are persecuted,
and banished from place to place for conscience-sake, and most of it long of thee.

Bishop.
I did not banish you--I left you fast enough when I left the island.

Answer.
Yet notwithstanding we know that our banishment is long of thee,
or else the earl would be loath to use us there worse than his tenants in this country.

Bishop.
I have no more to do with you or say to you; but what I told you before,
that if I can persuade my lord to the contrary, you shall not go again to the island.

Answer.
Indeed we expect no better from the spirit of persecution in any whomsoever;
but thou art contrary to the spirit of Christ, who laid,
do unto all men as you would be done unto,
who taught to love our enemies and not to persecute.

Bishop.
Yon are not persecuted but banished, because you do not come to church.

How easily men suffer themselves to be imposed upon,
and run into weak and absurd reasoning, by using unmeaning expressions,
or giving wrong names to things.
If banishing men because they do not come to church be not persecution,
I would fain know what is?

After their ineffectual conference, these exiles returned into Cumberland;
and although they could not obtain the earl`'s or bishop`'s permission to return home,
the distressed state of their families, in their absence,
from which they had forcibly separated, determined them at any risk to return to them,
and accordingly they took shipping again for the island;
but before they could get on shore,
the master of the vessel received orders not to suffer them to land;
in consequence whereof they were detained on board until the 1st of September,
when the master sent a petition to the bishop,
requesting that they might go on shore until he was ready to return, and then,
if required, he would carry them back to England, whereunto the bishop replied,

"`I am content that the Quakers be secured on shore until the return of the vessel,
upon security given by the owner of the vessel and the Quakers
for their return upon his departure from the island.

"`ISAAC SODER and MAN.`"

They continued at home about a month, when they were brought to Ramsey,
and forced again from wife and relations.
William Callow`'s wife taking her leave of him with tears,
so affected the master of the ship, that he wept too,
endeavouring to comfort the poor woman with promises of kindness to her husband.
But this obdurate bishop, contrary to his assertion, had not done with them yet;
for one Qualtrop, an attorney, just about the same time they were sent off,
took possession of their estates,
and an inventory of all their substance real and personal,
by virtue of an order signed by the said bishop and others.
It is difficult to conceive a more arbitrary government
than seems at this time to have subsisted in this island,
where men could be deprived of both their liberty and property,
at the mere will of their governors, without conviction of any crime,
or even being brought to a legal trial.

Upon their being landed again in England, William Callow went into Lancashire,
and renewed his application to the earl, for his permission to return home,
but with no better success than before: Wherefore he went to London,
William represented his case to the Duke of York and Prince Rupert,
the latter of whom compassonated it so far, as to intercede by letter in his behalf,
wherein, after reciting the account he had of his character,
as a quiet inoffensive person, he presumes,
that if there was nothing solicits the more against him than his being a Quaker,
the earl might be inclined to restore him and his family to their ancient possessions,
and to prevail upon him to do so (he says) was the reason troubling him with that application.
But even this powerful solicitation proved less effectual with the earl,
than the bishop`'s influence,
and for his declining compliance with which he gives the following reason.
"`There is not now in the island one Quaker or dissenting
person of any persuasion from the church of England,
and I humbly conceive your highness, for that one man`'s concern,
would not have that place endangered to be infected with schism or heresy,
which it might be liable to, if Quakers were permitted to reside there.`"^
footnote:[This was a mistake,
there being three women of that denomination prisoners in the island,
and as this island was a kind of asylum for bankrupts
and other fugitives both from Britain and Ireland,
it seems probable there might be many dissenters
from the former and many papists from the latter;
but the fear of the bishop`'s court,
and the consequential severities might awe them to
conceal their dissent under an occasional conformity,
which to men of no principle was a temporary evil not hard to endure.
In every view it is a proof of the exorbitant stretch
of ecclesiastical power in this barbarous isle.]

While William Callow was occupied in London in soliciting for liberty to return home,
he received intelligence from his wife, that she, his daughter Anne,
her sister Jane Christen and Mary Callow had been
prisoners in Castle-Peel five or six weeks,
and that all their estates, real and personal, were seized,
and that she heard the attorney would shortly come and take away all their goods;
that she and Jane Christen being with child,
they had applied by letter to the bishop for leave
to return to their houses until the The spring,
and then return to prison, they not having wherewith to subsist during the winter,
nor necessaries for persons in their condition, but that the bishop,
deaf to their entreaties, had re turned the following severe answer.

"`If upon releasement they will put in security to promise
to come to the service and conform to the order of the church,
and all such as are excommunicated to acknowledge their schisms, and receive absolution,
I shall so far presume upon my lord`'s favour, as to grant them liberty;
otherwise I have no power to meddle with them, they being my lord`'s prisoners;
and if they miscarry in their health or lives,
it is wholly imputable to their disobedience,
and they must be accounted their own murderers; and this is all I can say to them.

"`ISAAC SODER and MAN

"`Castletown, 15th December, 1666.`"

Thus the bishop, who had power and influence to persecute with cruelty,
but pretended want of power to relieve, while he wanted only tenderness to feel,
hardened his heart against every remonstrance,
and persisted in his obstinacy to force these unhappy
persons into conformity against their consciences,
or leave them in danger of starving and perishing in jail.
And William Callow, who upon the receipt of this affecting intelligence,
determined at all events if possible to visit his wife in her weak and distressed condition,
and endeavour to give her such relief as Callow was in his power,
accordingly returned home, where, although he found his wife in a weak condition,
as he expected, he was not suffered to give her any effectual assistance;
for the very day he came home he was sent to prison by order of the bishop,
where he was detained seven days, and then put on board a vessel again,
and sent off to England.
He then wrote a moving account of his hard usage to the Earl of Derby,
and waited personally upon him with it; but he turned a deaf ear to his complaints,
resisted to receive his paper, and dismissed him with this rude answer,
"`If he would not conform, he should not return to poison his island.`"
The bishop had before used the like argument in defence
of his persistance in refusing them liberty return,
alleging, if they had their liberty, they would corrupt all the neighbours about them.
To which they answered, "`Nay, we would not corrupt them, they are corrupted enough,
swearers, liars, whoremongers, are all corrupted.`"

In the year 1668 those four women were imprisoned again and banished with
such circumstances of barbarity as even drew tears their neighbours,
who were commanded to be assistant in taking them.
Two soldiers came to William Callow`'s house,
with an order from the bishop to take his wife to prison,
and they said the order from the bishop was peremptory
to take her and the others to prison,
though they should die by the way.
William`'s wife being very weak in bed, they took her each by an arm,
and endeavoured to pull her out of the bed; but her children crying round her,
and the neighbours also at the sight of their cruelty, moved them to desist at that time,
but they returned the next day and took her, Evan Christen`'s mother,
an ancient woman between seventy and eighty years of age, Jane Christen and Mary Callow,
all to Castle-peel.
The very next day an order came from the bishop to send them back again to Ramsey,
where they were detained several weeks until a vessel was ready to take them away;
when one Captain Ascough, in whose custody they were,
brought them to the boat with their children weeping after them, whom he,
cruelly separated from them, not suffering, though desirous,
to take any but the youngest along with them.
So William Callow`'s wife, to her other painful sufferings,
had the piercing mortification to leave four children behind her
without father or mother to provide for or take care of them.
Jane Christen in like manner was forced to leave five.
They being forced on board were landed at Whitehaven.
After some stay there,
they together with William Callow were sent back by order of two Cumberland justices.
The day after their arrival at the island they were forcibly
taken out of their beds by order of the deputy governor,
and put on board the ship in such hurry,
that the women were obliged to take their children naked in their aprons,
crying through the streets, in the night.
They were now taken to Dublin,
whence a ship was pressed to take them back again by order of the mayor.
The passage was tedious by reason of contrary winds,
and the women suffered much for want of provisions and necessaries,
William Callow`'s wife being near the time of her delivery.
As soon as the bishop and governor were informed of their arrival,
they set a watch upon the vessel to prevent William Callow`'s landing,
and the women having been landed before,
were soon forced again on board by soldiers by their orders,
with aggravated circumstances of inhumanity.
The master of the ship being brought before the governor and the bishop,
represented the weak condition of the women, and what they had suffered at sea,
and the danger to which they must certainly be exposed by being hurried again on board;
but the bistiop, whose heart seems steeled against every impression of humanity,
unmoved by the representation,
sent an order to raise the parish people to put William Callow`'s wife on board.
The messenger informed him she was very weak, and they did not know but in labour.
The bishop, nevertheless, renewed his orders, and the soldiers coming to her bed side,
ordered her to get up and go with them, swearing that they had orders from the bishop,
if she would not go, to carry her in a cart or across a horse`'s back.
They took her children out of bed from her,
and scarce giving her time to put on her clothes, hurried her to Ramsey;
they rifled her pockets of 4s; they took away her box of clothes and linen,
leaving the poor woman neither linen nor anything else but what she had on her,
alleging they seized her goods by the bishop`'s warrant.
Three of the neighbours who refused to assist in
this cruel treatment of an helpless woman,
were by the bishop`'s order committed to prison, as if, in his estimation,
compassion were a crime.
The exiles were detained on board an open boat half decked,
and that badly that when it rained they could not sit dry,
which landed them at Peel in Lancashire; but upon their landing,
two justices of peace made an order to send them back again;
pursuant to which order they were all sent back (except Anne Callow,
who being in childbed was left behind) and on their arrival at Ramsey,
were detained prisoners on ship-board from the 8th of the
month called August till the 1st of September.

Thus were innocent persons, legally convicted of no crime,
a second time tossed from shore to shore, as if unfit to live on the earth;
though they had injured no man, nor were burdensome to any,
but able to support their families reputably,
while they were suffered quietly to follow their lawful occupations.
But it seems proper to remark that the magistrates of Dublin, and of the British ports,
where they were landed, appear not to have sent them back in any ill-will to them;
but rather in testimony of abhorrence of the bishop`'s arbitrary and illegal proceedings.
The reasons assigned by the Lancashire justices in
their warrant for the taking them back are,
that they had all estates in the Isle of Man, but had none elsewhere,
that +++[+++stripped of all their property]
they were like to be burden some to the King`'s subjects in these parts,
if they should be permitted to settle--that they had been banished out of the island,
the place of their habitation, without any legal proceedings, that do any way appear,
and not lent or confined to any certain place of banishment by any legal authority,
but turned out as vagabonds to the wide world,
to the scandal of the laws and the King`'s government.

Finding that both from England and Ireland the banished were continually sent
back with a censure of the illegality and unreasonableness of their proceedings,
in order to free themselves from the like trouble and reproach for the future,
they determined to transport William Callow to Virginia by a London ship,
then anchor in Ramsey bay, bound thither, of which Ralph Harwood was master.
On the 1st of September an order was sent to captain Ascough to
send William Callow under the conduct of a soldier to the governor,
who upon his appearance inquired of him, if he was willing to go to Virginia?
to which he replied, "` I have no business there; but, replied the governor,
We will send thee thither.`"
William inquired by what law?
Answer.
"`By my lord`'s order.`"
William desired a fair trial, insisted that he had never been tried;
never been brought before any court; demanded to be tried by the laws of his own country,
or by the laws of England; he appealed to the laws of his country;
unto the king and council, before whom, he said his cause was already.
The benefit of the law was refused, and his appeals rejected by this insolent governor,
who was resolved, by the wanton exertion of illegal violence,
to put it out of his power to avail himself of legal redress for the wrongs he received,
or prosecute any appeal to effect.
After a short conference, in which William,
with a fortitude founded on innocence and conscious integrity,
strenuously maintained his right to exemption from the proposed banishment,
and denying the legality of the governor`'s power to transport him,
against which the governor had little farther to advance than,
"`Upon my credit thou shalt go to Virginia--I deny thy appeal--What
I do I will answer it,`" he ordered the soldiers to take him away,
upon which two of them, taking each an arm, haled him to the boat,
and then left him on shipboard.
When he was put on board, the sailors aboard the refused to go the voyage,
if he was to be carried with them, saying,
they never heard of a ship refuse to which carried
Quakers against their will that ever prospered.
Whereupon the master promised them, that he would carry him no further than Ireland,
and accordingly the next day set him on shore about forty miles north of Dublin.
William went directly to Dublin, took shipping and landed at Whitehaven;
also about the same time Evan Christen, his aged mother, and Alice Coward,
arrived in England from the Isle of Whitehorn in Scotland,
whither they had been carried in an open fishing boat,
after long confinement on hoard the vessel, which brought them back out of Lancashire,
as before related.
