== Chapter XXII.

[.chapter-synopsis]
* Persecution relaxed in England
* A Design to tolerate Dissenters
* Opposed by the Bishops
* The Parliament address the King for a Proclamation against Dissenters
* Conventicle Act
* Remarks thereupon
* Ecclesiastics promote the severe Execution thereof
* The People called Quakers the greatest Sufferers
* Many of them greatly spoiled
* Informers profligate and infamous
* Many of them perjure themselves by false Information
* Exorbitant in their Distraints
* Justices and Informers frequently exercise their Power beyond the Law
* Yet Appeals are generally ineffectual
* Arbitrary Misconstruction of the Word Conventicle
* Unfair Method of fining for a Preacher
* Some Justices discourage the Informers
* George Fox writes against the Act, and encourages his Friends to faithfulness.

Persecution in England seems to have been some time considerably relaxed,
although not totally put a stop to, particularly in the city of London,
to which various causes appear to have conspired, the Dutch war,
the depopulating pestilence, the destruction of a great part of the city by the fire,
more immediately demanding the care and vigilance of the government and magistracy,
drew off their attention from the dissenters for a season.
And the Duke of Buckingham succeeding Clarendon in the station of prime minister,
whether in order to confirm the opinion that his
predecessor had been the author of all their hardships,
or that he really held more liberal sentiments in respect to religious liberty,
showed more lenity to the non-conformists than his predecessor had done,
and by connivance suffered them to hold their meetings without molestation;
the discourse of a toleration began to revive,
and the question concerning the reasonableness thereof
to be more freely agitated in sundry publications.
The king also in his speech at the opening of the parliament in 1668,
expressed his desire that they would take into their serious deliberation
the means of affecting an union amongst all his protestant subjects,
whereby they might be induced not only to submit quietly to the government,
but cheerfully give their assistance to its support.
But the majority of the House of Commons,
under the influence of the same party spirit which had stimulated
them to enact the severe laws of this reign,
appeared much disturbed,
and in return petitioned the king to issue out a
proclamation for enforcing the laws against conventicles,
and for preserving the peace of the kingdom against
unlawful assemblies of papists and non-conformists.
The king issued the proclamation accordingly,
yet it appears not to have been attended with very heavy consequences to the dissenters.
For in the course or the succeeding year their hopes were again revived,
those sects who to avoid persecution had usually met clandestinely,
now appeared more openly, and ventured to assemble publicly for religious worship.
A more generous way of thinking seemed to be adopted by some leading men among the episcopalians.
A scheme was set on comprehending the presbyterians in the body of the established church,
and granting a toleration to other dissenters.
The Lord Chief Justice Hale undertook to draw up a bill for this tolerate purpose,
and Sir Orlando Bridgeman to support it with his whole interest.
But the design coming to the cognizance of some of the bishops,
they quickly took the alarm and spread it to the rest.
Archbishop Sheldon wrote a circular letter to his suffragans,
enjoining them to make a minute inquiry touching
the conventicles in their respective dioceses.
Having received all the in formation he could procure,
he exaggerated every circumstance to the king,
and obtained from his easy temper a fresh proclamation
to put the laws in force against the non-conformists,
and particularly against the preachers, according to the Statute of 17 Car.
II. which prohibits their residing in corporations.

The parliament, upon their meeting after the addresses prorogation,
seconded the efforts of the bishops,
the king by an address of thanks to the king for his proclamation;
by a vote prohibiting any member from bringing in the proposed bill in favour of non-conformists,
and by appointing a committee to make exact inquiry into their conduct;
who in result of their inquiry reported,
that divers conventicles and seditious assemblies
were held in the neighbourhood of the parliament,
so as to insult the government, and endanger the public tranquillity;
the house immediately declared,
that they would adhere to the king for the support of government in church and state,
against all adversaries whatsoever.
These measures might be justly looked upon as a prelude
to fresh persecution under additional penal laws;
for although the behaviour of the different classes of non-conformists
had administered no foundation for raising any rumour of a plot in agitation,
as had been generally done,
this vote seems intended to create an alarm of danger notwithstanding,
requiring the joint exertion of the different branches
of the legislature to guard and provide against,
and to point out all dissenters as persons seditious and dangerous to the state.

And the former act against conventicles, upon which so many were condemned to banishment,
being expired, in the next session, in 1670,
they proceeded to make a third act against them;
but having found repeated and long imprisonments, and even banishment,
ineffectual to deter those called Quakers in particular from keeping
up their religious meetings for the worship of God,
they seemed resolved now to try the force of depredation
and impoverishing them in their estates,
like the persecutor of Job,
essaying various modes of distress to accomplish their purposes,
and force them to defile their consciences in declining their duty of divine
worship according to their persuasion of the divine requirings.

The title of this third act, was,
"`An Act to Prevent and Suppress Seditious Conventicles,`" 22 Car.
II. which received the royal assent the 11th of the month called April, 1670,
and was to the following effect,

[.embedded-content-document.legal]
--

That if any persons upwards of sixteen years of age shall be present at any assembly,
conventicle or meeting, under colour or pretence of any exercise of religion,
in any other manner than according to the liturgy and practice of the church of England,
where there are five persons or more present besides those of the said household,
in such cases the offender shall pay 5s. for the first offence; and 10s. for the second.
And the preacher or teachers`' in any such meetings shall forfeit 20£. for the first,
and 40£. for the second offence.
And those who knowingly suffer such conventicles in their houses, barns, yards,
etc. shall forfeit 20£. Any justice of peace on the oath of two witnesses,
or any other sufficient proof, may record the offence under his hand and seal,
which record shall be taken in law for a full and perfect conviction,
and shall be certified at the next quarter sessions.
The fines may be levied by distress and sale of the offender`'s goods and chattels,
and in case of the poverty of such offender,
upon the goods and chattels of any other person or persons that
shall be convicted of having been present at the said conventicle,
at the discretion of the justice of peace,
so that the sum to be levied on any one person, in case of the poverty of others,
do not amount to more than 10£. for any one meeting: The constables, headboroughs,
etc. are to levy the same by warrant from the justice, and to be divided,
one third for the use of the king, and another third to the poor,
and the other third to the informer or his assistants,
regard being had to their diligence and industry in discovering,
dispersing and punishing the said conventicles.
The fines upon ministers for preaching are to be levied also by distress;
and in case of poverty, upon the good and chattels of any other present;
and the like upon the house where the conventicle is held,
and the money to be divided as above.

And it is further enacted, that the justice or justices of the peace, constable,
headboroughs, etc. may by warrant,
with what aid and assistance they shall think necessary,
break open and enter into any house or place where they shall be informed of a conventicle,
and take the persons assembled into custody.
And the lieutenants or other commissioned officers of the militia
may get together such force or assistance as they think necessary,
to dissolve, dissipate and disperse such unlawful meetings,
and take the persons into custody.
Then follow two extraordinary clauses,
that if any justice of peace refuse to do his duty
he shall forfeit 100£. and every constable, etc.
5£. And be it further enacted,
that all Clauses in this act shall be construed most largely
and beneficially for the suppressing of conventicles,
and for the justification and encouragement of all
persons to be employed in the execution thereof.
No warrant or mittimus shall be made void or reversed for any default in the form;
and if a person fly from one county or corporation to another,
his goods and chattels shall be seized wherever they are found.
If the party offending be a wile cohabiting with her husband,
the fine shall be levied on the goods and chattels of the husband,
provided the prosecution be within three months.
Parties aggrieved may appeal to the quarter sessions
if the fine amount to 10£. and to no other court,
and if cast to pay treble damages.

--

The palpable injustice of this iniquitous law upon this did not escape
the notice of these who were exposed to the danger of suffering thereby;
they in their own behalf remarked with freedom upon this flagrant violation
of the established privileges of the people of England.

That it destroyed the bulwark of the English man`'s liberty, property and life,
viz. Trial by Jury; authorizing a single justice out of sessions to convict, fine,
and by warrant levy it upon the offender contrary to Magna Charta.

By this act the innocent might be punished for the offence of the guilty,
contrary to natural justice.
If the wife or child was convicted of being present at an assembly termed unlawful,
the fine was to be levied on the goods of the husband or father,
whether he was of the same persuasion or no.
It was left to the arbitrary discretion of the justices to lay
half the fine for the house or ground where such assembly was holden,
and half the fine for a pretended unknown preacher,
and the whole fines of such of the meeters as they should account poor,
upon any other who was present at the meeting (not exceeding the limited
sum) which vested the justices with power to harass and oppress with dreadful
severity those to whom they might owe no good will,
and was in itself an infringement of the immutable laws of equity and reason.

The clandestine mode of conviction (which frequently
took place) by the oath of two informers,
(who had an interest therein,
and sought their gains from a multitude of convictions) before a justice;
so that men might be, and often were,
convicted and fined without any notice or knowledge thereof,
until the officers came and took away their goods,
and even then they were ignorant by whose evidence they were convicted; than which,
what could be more opposite to the privileges of the subject;
to the spirit of the great charter; to the jurisprudence of England or common justice?
which require that every man should be openly charged, and have his accuser face to face,
that he might have a fair opportunity, both to answer for himself,
and object to the validity of the evidence against him.

The fines imposed on justices and other officers, and the clause directing in effect,
to construe every part of the act in favour of the prosecutors,
appears to corrupt justice in its very source:
To instruct and influence the magistrates to partiality in their judgments,
to apply power only to oppress, and reverse the scriptural qualification for magistracy,
to the encouragement of evil-doers, and the punishment of those that do well;
and that many of them actually did so abundantly
appeared in divers prosecutions by this act.
As to oppress, and reverse the scriptural qualification for magistracy,
to the encouragement of evil-doers, and the punishment of those that do well;
and that many of them actually did so abundantly
appeared in divers prosecutions by this act.

As an act of such flagrant injustice and pernicious tendency to
so great a body of the people must bring discredit to the framers,
promoters and partisans thereof, the greater part of the historians,
who are more attached to the church of England, endeavour to excuse its severity,
by alleging that politics and the care of government
were the occasion of it more than religion.
Echard (according to Neale) says,
"`that this and all the penal laws made against the dissenters
were the acts of the parliament and not of the church,
and were made more on a civil and political than upon a moral and religious account;
and always upon some fresh provocation in reality or appearance.`"
Persecution ever endeavours thus to hide its deformities
under the garb of political caution;
but I think in the present case the covering is too transparent;
for at this season it doth not appear that any class of dissenters by
their conduct had given the least disturbance to the peace of the nation,
or could be charged with any design against the state.
The committee of parliament appointed to inquire into their
conduct discovered no misconduct amongst them,
nor had they given any fresh provocation, but that of attending their meetings openly,
to which they had been encouraged by the connivance of government.
The preamble to the act doth not charge them with disloyalty, only says,
"`That for providing speedy remedies against the
practices of seditious sectaries and others,
who under pretence of tender conscience have or may at their meetings contrive insurrections,`"
which by the way there was little danger of their doing in their public assemblies,
in a miscellaneous company of women, servants, strangers, and probably spies.
The act points them out a likelier method of contriving plots,
as it would appear more feasible to combine with success between three or four,
if they had any such design in view;
so that if the guarding against insurrections was the only object proposed,
this parliament seems to have wanted wisdom in concerting the measures to prevent them:
But it appears too evident that the reasons assigned
in this weak preamble are only a pretence,
and that the only object in view was upon a religious account to inflict new
punishments upon the dissenters for their dissent from the national church,
and nothing else.

And although the penal laws were the acts of the parliament,
as no other body had the power of making laws,
yet it will be a difficult under taking to exculpate the church, that is the clergy,
from a considerable share therein:
The weight of their influence and interest was not wanting to procure
penal laws and proclamations in favour of their own emoluments
and power (as appears by the exertions of Sheldon and others against
the comprehension) nor to the rigorous execution of them when made:
And that many others of them looked upon this act
as a considerable acquisition in their favour,
appears from the following extract from Archbishop
Sheldon`'s circular letter upon the occasion,^
footnote:[Copies of this letter were sent by the archdeacons to
the officers of the several parishes within their jurisdictions,
earnestly exhorting them to take special care to perform what is therein required,
and to give an account at the next visitation.
John Chapple, priest of Brant-Broughton in Lincolnshire,
perceiving the constable not forward in making distresses
and breaking up meetings sent him the following letter:
{footnote-paragraph-split}
Thomas Kelsey,
I cannot but wonder that any king`'s officer should
be so backward in executing the king`'s laws,
as I find you to be: Methinks you should have gone to Sir Christopher Nevile,
had you no other inducement thereto save only civility to Sir Francis Fane,
who desired you so to do: You cannot now as you did then pretend the want of any horse.
I have sent my man on purpose to join with you in giving information
to the justices concerning the late conventicle at Broughton,
and if you refuse to act I have ordered my man to make his complaint to the bench.
If your landlord Mr. Pierpoint,
be informed how you and others have behaved yourselves in this business,
I know that he will not thank you for your remissness;
for whatever his tenants at Broughton may be,
sure I am he is a person more zealous for the church.
No more at present from
{footnote-paragraph-split}
Your friend,
{footnote-paragraph-split}
John Chapple.]
in which he directs all ecclesiastical judges and officers,

[.embedded-content-document.letter]
--

to take notice of all non-conformists, holders, frequenters,
maintainers and abettors of conventicles,
especially of the preachers or teachers in them, and of the places wherein they are held;
ever keeping a more watchful eye over the cities and great towns,
from whence the mischief is for the most part derived,
unto the lesser villages and hamlets.
And wheresoever they find such wilful offenders,
that then with a hearty affection to the worship of God,
the honour of the king and his laws, and the peace of the church and kingdom,
they do address themselves to the civil magistrate, justices and others concerned,
imploring their help and assistance for preventing and suppressing the same,
according to the late act in that behalf made and set forth.

What the success will be we must leave to God Almighty;
yet I have this confidence under God, that if we do our parts now at first seriously,
by God`'s help, and the assistance of the civil power,
considering the abundant care and provision the act contains for our advantage,
we shall in a few months see a great alteration in the distractions of these times.^
footnote:[[.book-title]#Neale#]

--

The bishop of Peterborough declared publicly in the steeple-house at Rowel,
after he had commanded the officers to put this act in execution,
"`Against all fanatics it hath done its business, except the Quakers;
but when the parliament sits again, a stronger law will be made,
not only to take away their lands and goods, but also to sell them for bondslaves.`"^
footnote:[[.book-title]#Sewel,# p. 506]
Who can acquit the church, so called, of their share in the persecution,
when the rulers thereof were so intemperately warm and active in it,
and still insatiate with all these severities, inhumanly planning more and greater?
Ward of Salisbury and Gunning of Ely,
are also said to have been very zealous abettors of severity,
though many of the bishops had the prudence to lie by,
and resign the odium of enforcing the law to the civil magistrate.

There is no doubt but the clergy in general paid strict
attention to the mandates of the archbishop before recited,
as they were generally encouragers of,
(and many of them were not ashamed themselves to turn) informers.
Thomas Elwood, a contemporary writer, informs us,

[quote]
____
That some of the clergy of most ranks, and others,
who were excessively bigotted to that party,
used their utmost efforts to find out and encourage
the most profligate wretches to turn informers;
and get such persons into parochial offices as would be most obsequious to their directions,
and prompt, at their beck, to put this law into most rigorous execution.

In some parts care had been timely taken, by some not of the lowest rank,
to choose out some persons properly qualified, men of acute parts, close countenances,
pliant tempers and deep dissimulation and send them forth as spies among the sectaries,
so called, with instructions to thrust themselves into all societies;
conform to any religious profession;
and transform themselves from one religious appearance to another,
as occasion should require.
In a word, to be all things to all men; not that they might gain some,
but that they might ruin as many as they could.
The drift of this design was,
that their employers might by these means get a full account what number
of dissenters meetings of every sort there were in each county,
and where kept; what number of persons frequented them, and of what ranks;
who among them were persons of estate, and where they lived;
that when afterwards they should have troubled the waters,
they might the better know where with most advantage to cast their nets.`"^
footnote:[The same author gives this account of one of these emissaries.
He whose post was assigned him in the county of Bucks,
thrust himself upon a friend under the counterfeit appearance of a Quaker;
but being by the friend suspected, and dismissed unentertained,
he was obliged to betake himself to an alehouse for accommodation,
where not being able to bear the curb of his feigned sobriety,
he indulged himself in drinking too freely with the company he found there; in his cups,
he was thrown so far off his guard, that to magnify himself among his companions,
he let them know the quality of their new associate, that he was sent out by Doctor Mew,
Vice Chancellor of Oxford, on the design before related,
and under the protection of justice Morton,
a warrant under whose hand and seal he produced,
by which discovery he got the name of the Trepan,
and as such being known and generally avoided, he went to another part of the country,
and insinuated himself among the baptists,
having wrought himself into their good opinion,
and wilily drawn one of them into an in cautious openness
and freedom of conversation upon the severity of the times,
he villianously impeached him, who was a man of reputation,
of having spoken treasonable words,
and brought him into danger of losing both his estate and life,
had not a seasonable detection of his vicious practices elsewhere,
caused him to fly out of the court and country at
the very time when the honest man stood at the bar,
ready to be arraigned on his false accusation.
This discovery of his villainy leaving no further room to play the hypocrite,
he threw off the mask, and openly appeared in his proper character, that of an informer.]
____

Doth not this proceeding seem to be in consequence of the archbishop`'s instructions?

The execution of this act exposed every body of dissenters to great damage and hardship;
but this as well as the former fell with the greatest
weight upon the people called Quakers,
for the same cause.
Other dissenters could take the liberty of acting by the maxims of human prudence;
and use various means to keep themselves beyond the reach of the law,
or to prevent their being detected in the violation of it.^
footnote:[The ministers would preach in large families with only four strangers,
and as many under the age of sixteen as would come, and at other times,
where people might hear in several adjoining houses;
but after all infinite mischief`'s ensued; families were impoverished and divided;
friendship between neighbours interrupted, and general distrust and
jealousy succeeded. [.book-title]#Neale,# v. 2. p. 675.]
Yet they could not by any contrivance entirely escape the vigilance of the informers,
or the vigorous pursuit of the justices and their officers.
But the Quakers, who had no freedom,
to desert their public meetings for fear of human penalties,
continued to frequent them at the accustomed places and hours,
whereby they were open to the detection of the persecutors of all ranks,
who were highly provoked against them, particularly on this account;
as their steadfastness in duty very much broke their measures.

Exasperated at their open violation of these laws,
in obedience to the divine law of God in their consciences,
many of the executors of this severe law acted up fully to its
spirit in their severity and injustice in the execution thereof,
whereby many an honest and industrious family was stripped of the fruits of their industry.
At London, and in several other places, many were cruelly spoiled of their property;
people of considerable substance reduced to extreme poverty shop goods
and household goods so thoroughly swept away by the hardhearted spoilers,
that the sick have had their beds taken from under them,
and they themselves laid upon the floor.

For upon the passing of this law, many justices,
who were too honest to be instruments of such severities, quitted the bench,
and many of those that remained seem to have been of that kind,
who go under the denomination of trading justices,
mercenary enough to look for their share of the booty.
And the informers in general were men of the vilest characters, and of the meanest class,
idle, prostigate and infamous; extravagant, needy and rapacious.
Such justices and such assistants were not only prompt to plunder,
but dextrous in the dividing of the spoil; so that it is said,
the king and the poor frequently got but little for their share.
These unprincipled informers, taking up the infamous office to make out a living,
(being too idle to earn it by honest means) were
not very scrupulous in the evidence they gave;
the prospect of booty being the object in view, they, too often,
encouraged by the clandestine manner of conviction,
were tempted to swear home at a venture;^
footnote:[In Buckinghamshire two noted informers, Lacy and Aris,
swore before justice Clayton that Thomas Zachary and his
wife were at a meeting at Jordan`'s the 21st of August 1670,
whereupon the justice, as forward to convict as they to inform,
fined him 30£. for himself and his wife and a pretended preacher,
and issued a warrant for distress.
Thomas and his wife were then both at London,
wherefore he appealed to the quarter sessions.
The justice, to screen the informers, telling Thomas he suffered justly,
and he in his own defence answering that the righteous were oppressed,
and the wicked went unpunished, pretended to interpret these words,
as a reflection on the government,
and for refusing sureties for his appearance at the next sessions,
committed him to Aylsbury jail.
This was done to prevent him from prosecuting his appeal; but some of his friends,
especially Thomas Ellwood, prosecuted it,
and at the next sessions produced incontestable evidence that Thomas
Zachary and his wife were in London all that day;
so that, notwithstanding all endeavours to the contrary,
the jury found for the appellants; the conviction was set aside,
and the money deposited at entering the appeal ought to have been returned,
but they could never get more than 10£. of it,
the rest being detained by the clerk of the peace.
But so angry was the convicting justice,
that he persuaded the rest to tender Thomas Zachary the oath of allegiance,
for refusal whereof he was kept in prison a long time after.
{footnote-paragraph-split}
In Somersetshire the informers
swore against six persons for being at a meeting at Yeovil,
where they had not been at all.
Others swore Thomas Gally was at a meeting at Gregorystoke in said county,
when he was sick in bed, and died soon after.
They swore against William Lea, the younger,
as being at a meeting five weeks after his death.
In Westmoreland Richard Holme and several others were fined, as for being at a meeting,
which they were not at, the informers having sworn at random.]
being prosecuted by other dissenters,
divers of whom upon trial were found guilty of perjury, and suffered for it;
others by the partiality and protection of the magistrates, though proved guilty,
escaped the punishment due to their crime.

Nor were they more scrupulous in proportioning the
distraints to the value of the fines imposed:
Rapine being their trade,
they did not hesitate in the least to make much more
in value than the amount of the fines,
while they could find any thing to take,
encouraged by the instructions and assistance of justices,
who frequently gave them directions to be sure to take enough,
they often sold the distresses for less than half value, and would then come for more.
To recite all the instances of cruel plunderings on one hand,
and distressing sufferings on the other, even in this year,
recorded in Besse`'s [.book-title]#Account of the Sufferings of This People,#
would even make a volume; wherefore I shall content my self with a few notes
exhibiting some cases in confirmation of these remarks.^
footnote:[In Wiltshire the fines of sundry friends amounted to
99£. 10s. from whom were levied by distress goods to the value
of 213£. 9s. Robert Stevens was fined 10£. for an unknown preacher,
and 5s. for himself, though there was no preacher there; he was a very poor man,
and all his goods were valued at 40s. which being reported to the justice,
he ordered the officers to take away the little all.
Three others were in like manner unjustly fined the like sum for the unknown preacher,
who was not there.
In Bedfordshire the officers were incited to rapacity by justice Charnock,
telling them they might take 100£. for 20£. and bring him the money,
for his clerk should have some of it for his pains; and that they must take the more,
because few would buy the goods.
Richard Milner, for a fine of 20£. for a meeting at his house,
had goods taken from him worth 37£. Richard Smith of Chester had his goods seized
several times for meetings at his house far exceeding the fines imposed,
which were usually 20£. by the encouragement of the mayor,
bidding the officers take enough;
several were distrained to five or six times the value of the fines.
{footnote-paragraph-split}
Thomas Green being on his
knees in prayer at a meeting in Sabridgeworth,
Hertfordshire,
was dragged out and fined by two justices 10£. for which his goods were taken
by distress to the value of 50£.
{footnote-paragraph-split}
Charles Barnet,
a baker of Leominster, was fined 20£. for preaching,
and afterwards 40£. for a second offence; for which all the goods in his house,
and all the wood in his yard, were taken away.
After which warrants being again issued against him,
the officer reported to the justice Booth he had nothing left but bread,
which would spoil before it could be sold; the justice answered, if you cannot sell it,
you may bring it me to give to my horses.
{footnote-paragraph-split}
Theophilus Green, preaching at a meeting at Uxbridge,
was fined 20£. and under pretence that he had uttered seditious expressions,
because he exhorted his friends to keep their meeting in the name of Jesus,
notwithstanding the laws of man to the contrary, he was sent to Newgate.
For this and other fines for meeting,
warrants of distress were issued against him for 100£. for
which they took away all his household goods.
{footnote-paragraph-split}
In Nottinghamshire in 1669, Peniston Whaley, chairman,
in his charge to the grand jury,
endeavouring to incense them against the Quakers so called, manifested his absurdity,
ignorance and malevolence together, by telling them in effect; the act of 35 Eliz.
was not made against the Papists but the Quakers for, said he,
the church of Rome is a true church, as well as any other;
for a man though he be a lame or ill- favoured man,
yet he is a man as well as a lord or an earl. And
though the church of Rome have some corruptions,
yet it is a true church as well as any other, and so it could not be made against them;
therefore it must needs be against these people.
You ought to put it in force and not pity them.
Extraordinary reasoning indeed!
{footnote-paragraph-split}
On the 6th,
8th and 9th of the month called August this year, one Bumstead, a bailiff`'s follower,
with others, came to the house of William Albright of Wooburn in Bedfordshire,
at whose house a meeting was kept,
and by a warrant from justice Charnock broke open his doors, and took away timber, malt,
oats and other things to the value of 70£. Howbeit the said Albright
continued stedfast in permitting meetings at his house,
until by repeated seizures he was so impoverished,
that having nothing left to satisfy the fines,
he was finally cast into prison about the month of October.
{footnote-paragraph-split}
Sarah Baker, a poor widow, for 15s. fine,
suffered distress of what household goods she had,
amongst which having boiled milk in a skillet for two sick children,
the informers threw away the poor children`'s sustenance, and took the skillet away.
George Thorowgood, of Ely, had all his household goods, beds and bed-clothes taken,
and was forced to lodge on straw; after which, when sick,
his prosecutors took away his sheets and shirt.
Edward Crooke had the bedding for himself and family taken away,
with the children`'s cradle,
so that one of them died with sickness contracted by lying on straw.
Samuel Bates of Cranbrook,
having had all his goods seized for a fine for suffering meetings at his house,
awhile after when he had gotten a few more household goods,
some of which were lent him in his distress.
One Culpeper, a justice of peace, got in at a window,
and with an axe broke open the door, and let in the constable,
whom he charged to clear the house of all that was in it;
but the constable pitying the poor man`'s case, did not execute the order,
for which the justice fined the said constable 5£. who had two oxen taken from him worth
15£. For a meeting at Long-Claxton in Leicestershire four persons were sent to prison,
and so many goods at divers times taken from some of that meeting,
that they had not a cow left to give their children milk; their bed clothes,
working-tools and wearing apparel escaped not the violence and avarice of the persecutors;
the sum total amounted to above 236£. besides which
the informers gave them much personal abuse,
and robbed one of the prisoners of his purse and money.]

Severe as this act against conventicles was,
yet the villainy and perjury or the informers,
and prejudice of sundry justices against this people frequently urged
them to acts of severity and injustice beyond the letter of the law;
which excited some of the sufferers to appeal,
according to the privilege allowed them by the act;
but in a general way they got little by the appeal but additional loss,^
footnote:[Ten persons having taken from them for fines,
for a meeting at West-Alvington in Devonshire,
goods amounting to 81£. 21s. 8d. amongst which was comprised 20£. for a preacher,
though the meeting was held in silence, and fines upon others for two persons,
one of which was absent, and the other had been dead sometime,
some of them brought their appeal to the quarter sessions,
where the informers in concert swore for their gain,
that they saw a man standing up with a bible before him (a practice not in use
with this people) which was clearly disproved by the witnesses for the appellants,
and amongst them the constable.
The chairman summing up the evidence declared it was an equal balance,
the jury brought in their verdict for the king,
and the appellants thus wrongfully were cast in treble costs.
{footnote-paragraph-split}
At the same sessions Mary Randal brought her appeal
for being distrained for fines for the absent and deceased persons abovementioned,
which being clearly proved, the warrant was judged illegal,
and the court ordered the money to be returned,
which the convicting justice promised to do, but never did:
Instead of restitution he shortly after granted another warrant
against her for a pretended offence of the like nature.
{footnote-paragraph-split}
Nathaniel Smith, by advice of counsel,
brought his appeal before the quarter sessions of Herefordshire; the case being heard,
the jury went out, and returned with a verdict for the appellant;
the court refused to accept it, and sent them out again;
they repeated the same verdict six times successively,
and were as often repulsed by the court;
but the jurors continuing steadfast in their opinion, the verdict was at length recorded;
but the court at the same time directed the officers to empannel another
jury for the next trial They also sent an officer to prison for procuring
the jury a copy of the king`'s proclamation at their request.
But though the verdict had been recorded,
yet afterward the justices knowing one of the jury to be of a timorous disposition,
prevailed on him to say, he had not consented toil,
and on that pretence sent out the jury again,
with such threats as produced a contrary verdict,
the men being overawed by the court to act against their consciences.
Thus the verdict six times given for the appellant was annulled,
and he obliged to acquiesce under the charges of the appeal,
added to the injustice of his first suffering.
In like manner at the same sessions the appeal of William Owen was also frustrated,
the justices telling the jury that the case was like Smith`'s,
peremptorily directed them to find for the king, which was done accordingly,
one of the jury being heard to say, the court is lord of our consciences.
{footnote-paragraph-split}
Francis Plumstead of London was sworn against by two
informers for preaching at a meeting in Devonshire buildings on the 25th of November,
1683, and for being at another meeting there on the 15th of the same month,
whereupon one Dudley North, justice,
had issued warrants of distress for 30£. He deposited that sum in the hands of the constable,
and appealed.
His appeal was prosecuted from sessions to sessions;
at length affidavit was made that the said two informers
within a month after the warrant was granted,
came to a neighbour`'s house, and sent for the said Francis Plumstead,
and before witnesses confessed they had been drawn into that wicked act,
asked forgiveness, and offered to kneel down and beg his pardon,
owning then and several times after, that they had done him wrong,
and sworn falsely against him.
He also proved by two witnesses, present at the meeting, that he did not preach there.
Nevertheless, and though no evidence appeared against him,
the Recorder endeavoured to invalidate the testimony of his witnesses,
and so wrought upon the jury that they brought him in guilty of being at the other meeting,
for which he was fined 10£. By which fine and the charges of his appeal,
he computed the damage by him sustained to be at least 40.
{footnote-paragraph-split}
Henry
Kendon of London,
had distress made on his goods for 50£.£. being the contents of
five several warrants granted against him in one and the same day;
he appealed, and was cast on three of these indictments, by the evidence of a woman,
who was afterwards proved to be perjured,
for he had three substantial witnesses to testify the contrary of what she swore.
The other two appeals he gained;
but the whole of his loss and charges amounted to 72£.
{footnote-paragraph-split}
William
Collard of Southwark,
had his goods seized by a warrant with a wrong name, where upon he appealed;
but the jury upon trial, though inclined to acquit him,
being sent out three times by the bench with threatening words, at last said,
they thought it must be for the king;
so that he lost his cause with the additional charges to the value of about 17£.]
for as the dernier or only resort was to the quarter sessions,
the influence of the convicting justice, the partiality of of the bench, corrupt juries,
or the neglect of the justices in putting their decrees into due execution,
when in favour of the appellant, mostly left them unredressed,
or suffering under additional grievances in many very clear causes of just complaint,
whereby others who had just cause were discouraged
from trying this ineffectual mode of relief,
apprehending it more eligible to acquiesce under the first illegal wrong.

This people were often informed against and illegally
fined by a misconstruction of the word Conventicles,
which though limited in the act to meetings for worship
contrary to the liturgy of the church of England;
yet by mercenary informers,
and mercenary and partial justices was extended to
comprise all assemblies of any of those people;^
footnote:[A meeting was held for church affairs,
and to relieve the necessities of the poor,
at the house of John Penford at Kirby-Mucklow in Leicestershire.
Thither came the informers, and found them in consultation about works of charity.
John Penford bid them look into the books of accounts then lying open,
that so they might not misrepresent the cause of their meeting.
Four of them were summoned to appear before the justices at Market-Bosworth, who,
appearing accordingly, were charged with being at a seditious conventicle;
they desired that the informers might give in their depositions in their hearing,
but the justices would not grant it; for they were so partially disposed,
that one of them told John Penford, who had a considerable estate,
that he would reduce him to poverty.
They fined John Penford 30£. 20£. for the house, and 10£.£. for a preacher,
though no preacher was there; they also fined several others 3£. 6s. 8d. each,
so that the whole amounted to 50£. Penford and another appealed to the quarter sessions,
and retained counsel to plead their cause.
But so arbitrary were the justices,
that they refused to try the appeal unless the appellants would take the oath of allegiance;
upon their refusal the court awarded treble damages against them,
as if they had been cast on the trial,
though it is apparent they had law and equity on their side.
{footnote-paragraph-split}
It was usual with the people called Quakers, once a quarter,
to have a meeting at Ilchester for their church affair,
and making provision for their poor, which meeting they sometimes held at the Friary,
where many of their friends were prisoners.
In September 1680, they came from several parts of the county,
in order to hold such a meeting; but Henry Walrond,
a justice of the peace and captain of a troop of horse, prevented them,
by causing the doors of the Friary to be locked,
so that neither the prisoners could go out, nor their friends come in,
for which reason they were obliged to go to the George Inn,
the house of one Robert Abbott, where many of their horses were:
there they held their meeting, the men in one room and the women in another.
But though there was neither preaching nor praying at that time,
yet the said justice Walrond fined the said Robert
Abbott 40£. for two meetings held in his house,
and issued a warrant to distrain his goods, which was done;
but Abbott to prevent their being carried away,
paid down the money and appealed to the quarter sessions,
the charge of which appeal came to 20£. more.
He was there cast, so that the whole charge amounted to 60£.£. Abbott was not a Quaker,
but a civil, friendly man,
and those who met at his house would not let him be a sufferer for entertaining them,
but repaid him his fine and costs.]
if they met merely to provide for their poor,
the number of whom daily increased by the severity of this act,
and the more severe execution thereof;
whose accumulated distress necessarily engaged their
sympathetic tenderness and friendly assistance;
or if they paid a visit to a friend in his sickness;
or if they gathered to pay the last office of respect,
in attending the funerals of their deceased friends,
there were not wanting informers hardy enough to swear such meetings conventicles,
nor justices prejudiced against them to issue their warrants to levy fines accordingly.^
footnote:[On the 26th of the month called August,
Samuel Clothier in Somersetshire died a prisoner,
after suffering upwards of ten years imprisonment for not paying tithes.
He finished his life in peace, and left a good reputation behind him.
Several persons were fined for attending his funeral at Alford; Robert Hunt,
a justice of peace, calling this office of respect to the deceased a conventicle,
though nothing was spoken at the grave: the widow was fined 40s. for herself,
her son and four relations.
His brother for himself and others 1£. 7s. Several neighbours
who were not Quakers were fined for going to the funeral,
and paid their fines to prevent the seizure of their goods.
{footnote-paragraph-split}
There dwelt at Buckenham in Norfolk, one Robert Tiller,
an ancient man, very weak and consumptive,
whom some of his friends came to visit in his sickness: two informers observing this,
crept into their company, and while they were sitting together,
the sick man spoke a few words to his friends concerning
his own experience of the work of religion.
This the informer swore to be a conventicle,
and the sick man was fined 20£. for which they took away six of his cows.
{footnote-paragraph-split}
In Somersetshire,
the widow of Philip Tyler was fined for being at his funeral,
and suffered distress of two cows worth 9£. from sundry others,
for being at said funeral, goods were taken to the amount of 82£. and upwards.
{footnote-paragraph-split}
An honest woman at Keel in Staffordshire, being dead,
her husband intended to bury her in friends burying ground;
but the priest of the parish sent him a threatening message,
that if he did not pay his fees, he would arrest the corpse,
and cause it to be buried in a ditch,
saying be had rather see all the heretics hanged than lose one sixpence by them.
In short, the priest and some others sat up all night in an house drinking,
in order to watch the corpse: so that the poor man,
to keep his dear wife out of their hands, determined to bury her in his own garden,
and did so accordingly: and he himself died six days after and was buried beside her.
Several of the neighbours came to his funeral, and amongst the rest the church-wardens;
the corpse being interred, a friend kneeled down to prayer:
upon this the church-wardens grounded an information,
upon which the said friend was fined 20£. and several others in other sums;
which upon appeal being returned to some of them, so irritated the priest,
that he endeavoured to prevail upon the magistrates of the town,
where the friend who prayed at the funeral dwelt, to tender him the oath of allegiance,
but without effect; whereupon he applied to some country justices, who sent for him,
tendered him the oath, and upon his refusing to take it sent him to prison.]
And it is to be observed that where the fines imposed
did not exceed 10s. there lay no appeal,
although judgment were ever so partial, or the distress ever so exorbitant.

The penalty for the preacher being 20£. For the first offence, and 40£. for the second,
was,
in the view of these unconscientious informers too valuable an
acquisition to the fines of 5s. And 10s. not to be brought in,
in addition thereto;
for this purpose they often swore against a preacher when there was none there,
nor a word spoken in the meeting;
at other times they would by impertinent questions
extort an answer from some one or other present,
and if a word was spoken, though on subjects foreign to religion,
they termed it preaching, and swore accordingly;^
footnote:[Two informers came to the house of Abraham Hayworth of Rosendale in Lancashire,
when the meeting there was breaking up;
they went and made information that James Radcliff preached there,
who was not at that meeting;
however the justices upon this evidence fined him
20£. for which the officers broke open five doors,
and took away twelve kine, and an horse worth 39£.£.
{footnote-paragraph-split}
William Claytor of Elton in Nottinghamshire,
and John Barker of Bingham, were together at a friend`'s house,
where were no others but the family; an informer came in,
and asked William some usual familiar questions, to whom he gave him proper answers:
upon which he gave information to a justice, that there was a meeting,
and that William Claytor spake,
whereupon the justice fined William 20£. and John Barker 12£. [.book-title]#Besse,# v. 1. p. 555.
{footnote-paragraph-split}
Another time William Claytor and some others being assembled,
and sitting together in silence, two informers came in,
and with them some of the town officers: one of the informers said, take their names.
William Claytor asked, What will you take our names for?
The informer said, for silent meeting; Nay, said the other informer,
put him down for a speaker; which they did accordingly,
and he was fined by justice Whaley for speaking or preaching 40£. for a second offence,
having been formerly convicted on a like stratagem as before-mentioned.
{footnote-paragraph-split}
A parallel case to this was that of Joseph Wallis,
who fitting silent in a meeting, one Walker, an informer, came in, and asked him,
When will you give over this?
Joseph answered, When wilt thou give over thy trade?
Walker returned, Not till you give over yours.
Joseph replied, thine will not bring thee peace at thy latter end.
For this Joseph Wallis was fined 20£. as a preacher.]
and the information being generally made before magistrates
as ready to fine as these informers were to swear,
by this iniquitous combination were many of this
people plainly robbed by +++[+++the misapplication of]
an act of parliament.

But some well disposed justices,
apprized of the villainy and infamous characters of these informers,
and their readiness to swear at all adventures, to plunder without mercy,
to enhance their ill-got gains,
had too much honour to encourage such a vicious disposition;
with such it hath frequently happened that those informed against have been cleared,
when the informer missed in his evidence either in
the day of the month or the like in the complaint.
In London, the lord mayor sitting in a court of aldermen,
an impudent informer made his appearance,
with such a number of information as would have wronged
the parties informed against of 1500£. but the mayor,
in abhorrence, adjourned the court.
Yet this hardy informer, not satisfied to let the matter fall,
appeared before the court again and again, and was as often put off,
till at last he was arrested for debt, and ended his days in prison.

George Fox being at this time in London,
published remarks upon the injustice of this law, in order, if possible,
to move the government to moderation:
but at the same time being apprehensive of an impending storm,
he wrote epistle to his friends,
to exhort them to faithfulness and steadfastness in their testimony to the truth,
and to christian patience,
in bearing the sufferings which might be permitted to try their faith.
