== Chapter XXIII.

[.chapter-synopsis]
* Meetinghouses in London shut up
* George Fox taken before the Mayor and dismissed
* An episcopalian Priest brought to preach at Gracious-street
* George Whitehead preaches after him
* Proceedings at Peel-meeting
* Trial of William Penn and William Mead for a Riot
* Acquitted by the jury
* The jury fined and imprisoned
* Trial of Thomas Rudyard and others
* Sentence passed on the Prisoners clandestinely
* Imprisonment in an infected jail
* Accounts of these Trials published
* The Recorder rewarded for his Service

Upon the commencement of this act`'s taking place, in London and several other places,
the meetinghouses were shut up, and a guard placed at the door, to keep the people out,
and amongst the rest at the meetinghouse at Grace-church-street,
whereupon the meeting was held in the court.
On the next first day, being kept not only out of the meetinghouse,
but also out of the court, they assembled in the open street,
where George Fox began to preach, but was presently pulled down;
after him another was served in like manner,
and both of them were carried before the Lord Mayor by a constable and an informer,
attended by a guard of soldiers.
As they were pasting along the informer discovered himself by the following expression,
It will never be a good world, until all the people come to the good old religion,
that was two hundred years ago: Upon hearing which, George said, '`What!
A papist informer.`'
When they came to the court before the mayor`'s house,
some of the people asked George Fox why he was brought thither?
he replied, ask that informer, and ask him his name.
Upon this one of the mayor`'s officers said, he should tell his name before he went away;
for the Lord Mayor will know by what authority you intrude yourself with soldiers
into the execution of those laws which belong to the civil magistrate to execute.
The informer unwilling to abide the examination, slipped out of the court,
and was received by the populace in the street with aloud cry of,
'`a papist informer! a papist informer!`' who were like to have handled him roughly,
had not George Fox persuaded the constable and soldiers to rescue him out of their hands.
By which means he got into an house, changed his periwig, and made his escape.
The informer being fled, and nobody appearing in that quality, the Lord Mayor,
after some discourse with George Fox and his friend, set them both at liberty.
In like manner on the same day, at Devonshire house,
many friends were by compulsion kept out of their meetinghouse.
But John Burnyeat and others having assembled in the meeting, he began to speak,
but was quickly pulled down, and carried before the Lord Mayor,
who fined him 20£. At Westminster several were grievously abused,
some having their clothes taken from them, as cloaks, coats, hoods, scarves,
etc. some kept prisoners several hours, and afterward taken before two justices,
who fined them, both men and women.

Various were the measures adopted by the magistrates to perplex the Quakers,
and deter them from keeping up their religious meetings;
but standing upon a solid foundation, a conscience void of offence,
and a dependence on divine protection,
they were preserved through all their severe trials, steadfast and undismayed,
whereby their adversaries were frustrated through
all their efforts to distress them to dispersion.
The mayor first set guards upon their meetinghouses;
and they resorting thereto in point of duty, and being by force kept out,
held their meetings in the street, as near thereto as they were permitted to come.
Next, viz. on the 26th of the month called June,
he suffered them to assemble in the meetinghouse in Whitebait court; but when assembled,
he contrived to procure an episcopalian priest to
go thither and officiate according to to their liturgy,
and sent a band of soldiers to guard him in the performance of his office,
who accordingly read the common prayer, and preached a sermon in the gallery,
exciting to love and forbearance, from Eph. 4:15-2;
but at the same time by his conduct did not confirm his doctrine;
for the soldiers who guarded him were rude and abusive to some of his auditors by compulsion,
for making some observations on the inconsistency
of the measures of the church party with his doctrine,
and he neither repressed nor rebuked their rudeness and violence,
which they dealt freely to women as well as men.

As the novelty of the transaction drew many people together,
after the priest had ended his sermon, George Whitehead stood up,
and preached on the same subject,
taking occasion to demonstrate the inconsistency
of persecution therewith and with the gospel of peace.
The mixed auditory listened with attention,
and before the meeting continued in an agreeable state of quietude,
until two rude fellows with soldiers at their heels,
laid violent hands on him and pulled him down,
by their violence pushing down some women present, and carried him to the mayor`'s,
keeping him some time in his yard.
His name and the information against him being given to the mayor,
he presently sent out a warrant to commit him to the
compter at the gatehouse in Bishopsgate-street, for making a disturbance,
etc. until he should find sureties or be delivered by due course of law,
without examining the case,
or admitting George Whitehead to be heard in his own defence.

George Whitehead seeing the warrant, requested an audience of the mayor,
which being obtained, he informed him,
that he apprehended there was a mistake in the warrant,
in charging him with making disturbance, for that there was no such thing,
until the informers and soldiers came in; that he made none,
but on the contrary quieted the people by seasonable advice and counsel.
He was sent to the compter until the evening,
and then sent for to appear before the mayor again;
and after some discourse the mayor in conclusion
signified he must fine him 40£. for a second offence,
as having been, he said, convicted before Sir Joseph Sheldon before;
but it seems the fine was never levied.^
footnote:[The substance of the discourse between
George Whitehead and the Mayor was as followeth:
Information being given that George Whitehead stood
up and preached after the minister had ended,
but what he preached the witnesses could not tell,
{footnote-paragraph-split}
The _Mayor_ said, if the minister had done it was a conventicle.
{footnote-paragraph-split}
_G+++.+++ Whitehead._
If I had preached sedition or discord against either
the government or peace of the nation,
I might justly suffer by this law;
being an act to prevent and suppress seditious conventicles.
But it was no other but the gospel of peace and salvation by Jesus Christ that I preached,
to exalt the power of godliness, directing the people thereto,
that they may not remain under empty and dead forms of profession.
{footnote-paragraph-split}
_Mayor._
I believe both you and others have done good--Well,
I must fine you 40£. this being for the second offence;
you were convicted before Sir Joseph Sheldon once before.
{footnote-paragraph-split}
_G+++.+++ Whitehead._
Must I suffer for preaching the gospel, as if I had been preaching sedition?
Doth the law make no difference?
Besides I was not convicted according to this law before justice Sheldon,
for it was there made appear that the witness forswore himself;
for he swore that he took me preaching,
when many could testify (as some did) that I was praying, and not preaching at that time.
{footnote-paragraph-split}
_Mayor._
But were you on your knees with your hat off when they took you?
{footnote-paragraph-split}
_G+++.+++ Whitehead._
Yea, I was, and the meeting was in a solemn posture of prayer,
the men with their hats off: And the soldiers pulled me down when I was praying.
{footnote-paragraph-split}
_Mayor._
However, you were in a religious exercise.
{footnote-paragraph-split}
_G+++.+++ Whitehead._
If preaching must be accounted a religious exercise, not allowed by the liturgy,
yet I do not understand that prayer is included in the clause.
"`Every person who shall take upon him to preach or teach in any such meeting,
and shall be thereof convicted, shall forfeit 20£`" Now here is no praying mentioned.
Now I desire thy judgment, whether preaching or teaching can be meant praying?
{footnote-paragraph-split}
_Mayor._
No, praying is not here mentioned; however your conviction is recorded,
you may make your appeal.
{footnote-paragraph-split}
_G+++.+++ Whitehead._
To whom shall I make my appeal but to those that wrong me.
{footnote-paragraph-split}
_Mayor._
I must do according to law; I must fine you 40£.
{footnote-paragraph-split}
_G+++.+++ Whitehead._
That law which makes no distinction between preaching sedition
and preaching the gospel of peace I must deny,
as being both against reason and against God, and God, who judgeth righteously,
will judge between thee and us in this thing.]

They pursued the like plan at the same meetinghouse for three or four first days successively;
but whatever their view might be in this intrusion
of their liturgy within unconsecrated walls,
they soon grew tired,
and returned to the practice of placing guards at the meetinghouses,
and keeping the assemblies of this people out in the streets.

Upon the 17th day of the 5th month, O. S. called July,
friends were kept out of their meetinghouse at Peele in the street,
by a band of soldiers and a constable,
and two women friends being concerned to speak a few words of exhortation,
the soldiers came and violently pulled them away,
pushed down both men and women with their muskets, bruised several,
and tore Mary Wicks`'s scarf and apron,
whereupon one of the friends called to the constable to keep the peace.
Toward the conclusion of the meeting George Whitehead felt his
heart animated with fervency to call upon the Lord by prayer,
in which as he was exercised, the soldiers with violence pulled him away into the entry;
George then reasoned with them concerning their rudeness
and incivility towards the women;
remarking how much below the manly spirit of soldiers
they acted in abusing peaceable men,
and women of repute, as they had done.
Presently after they pulled John Scot and Samuel Richardson into their guard-room,
and detained those three in their custody near three hours;
and then a great company of soldiers conducted them to an ale-house near Clerkenwell,
where two justices, Foster and Bowles, were,
with a body of the king`'s horse-guards before the door.
Upon their appearing before the justices,
George Whitehead addressing himself to the justices said,
"`I am glad we are come before the civil magistrates:
We desire justice of you against the soldiers,
who have kept us out of our meeting in the street, and taken us contrary to law,
even contrary to the present act of parliament,
which requires not them to meddle with meetings, but where resistance is made,
and upon certificate thereof as the act mentions: Besides,
some of these soldiers behaved rudely, and abused several of our friends,
and hurt some of the women by punching them with their muskets.
In the next place, we except against these soldiers as witnesses,
looking upon them as improper witnesses against us,
who have broken the law themselves.`"

Nevertheless they were put to their oaths to give testimony against the prisoners,
whom they had abused and illegally apprehended,
the justices not cautioning them to take heed what they swore,
although the major (who was present) did.
Their information against George Whitehead, imported,
That there were about 300 in the street, that they took him preaching,
standing on a bulk or stall.

George Whitehead answered, That is not true: I was praying, standing on the ground,
but leaning on a stall.

[.discourse-part]
_Soldiers._
We took him praying, but leaning on a bulk.

[.discourse-part]
_George Whitehead._
See how confused and contradictory they are in their evidence,
for preaching and praying are two things;
neither is praying mentioned in the clause of that act which
is made against such as take upon them to preach or teach.

[.discourse-part]
_Justice Foster._
You conjured them together to the meeting.

[.discourse-part]
_George Whitehead._
That`'s not true, for they were gathered before I came to the meeting.

[.small-break]
'''

The major reproving the soldiers for going beyond his order,
which was to keep friends in the street, and to keep sentry at the door,
but not to take them prisoners.

Justice Bowles, in excuse of the soldiers, said, Sir,
after you were gone I ordered them to take those that preached, and I thank them.

[.discourse-part]
_Justice Foster._
What a devil did you come there to pray for?

[.discourse-part]
_George Whitehead._
Do these words become a magistrate?
We did not meet to hear or sing ballads in the street, nor do we meet at play houses,
nor at bawdy-houses, nor at drinking-houses, to be drunk, where the devil is served;
but singly to serve and worship the living God.

[.small-break]
'''

The major and some more with him seemed highly offended at these expressions,
calling out, '`Whom do you accuse?
whom do you accuse for going to bawdy-houses?`'
Whereupon some of the company present smiled one upon another.

[.discourse-part]
_George Whitehead._
I accuse none, but tell you what meetings we do not come at, nor own;
and for what end we do meet.

[.small-break]
'''

The information against John Scot was, that they took him preaching, which was,
that when they were behaving with rudeness and violence he desired them to be moderate.
And Samuel Richardson, that he laid violent hands on one of their muskets;
but this was utterly false, and denied by Samuel Richardson,
for he was standing peaceably (as he said) with his hands in his pockets.
They were all committed to New-prison, guarded by a constable, and a guard of soldiers.
And the next evening they fined George Whitehead 20£. (but
it was not levied) and Samuel Richardson five shillings,
and discharged them.
But imprisoned John Scot six months on the Oxford act against nonconformist preachers,
although he was no preacher,
nor in any respect justly liable to be punished by the said act.

The magistrates of London next conceived a new plan, to imprison them,
in order to bring them to trial for a riot,
and exert their utmost endeavours to get them convicted thereupon.
They began with two very eminent members of this society, William Penn and William Mead,
who were taken as William Penn was preaching in Grace-church-street
on the 14th of the month called August,
and both committed to Newgate,
from whence they were brought to their trial at the
sessions at the Old Bailey the 1st. 3rd,
4th and 5th of September,
wherein is exhibited a remarkable specimen of the
violent exertions of arbitrary power in the magistrates;
and of intrepid fortitude in defence of the ancient and fundamental
privileges of the people in the prisoners and the jury.

The indictment set forth, that William Penn and William Mead,
with divers other persons to the number of 300,
at Grace Church-street in the city of London, on the 15th of August,
with force and arms tumultuously assembled together, and that William Penn,
by agreement between him and William Mead, had preached there in the public street,
whereby was caused a great concourse of people.
To this Indictment they severally pleaded not guilty.
After which they were detained there five hours, waiting upon the trial of felons,
and then returned to Newgate: and two days after were brought before the court again,
when the court more openly manifested a preconcerted
design to treat them with the utmost severity,
and take every unfair advantage against them;
for coming into court after their accustomed manner with their hats on,
and the officers having taken them off, the lord mayor, Samuel Starling,
reproved them sharply, and ordered them to put them on their heads again.
Whereupon the recorder, Howel,
who appeared through the whole trial implacably determined against them,
fined them forty marks each, for not taking off their hats.
Which occasioned William Penn to remark, That they were in the court with their hats off,
(i. e. taken off) and if they have been put on since, it is by order of the bench;
and therefore, (if any) the bench, not the prisoners, ought to be fined.

The jury being sworn, and the witnesses being called,
deposed that they saw William Penn speaking to the people
assembled in a great number in Grace-church-street,
but they could not hear what he said.

The recorder then asked William Mead if he was there?
Who replied, "`It is a maxim in your own law that no man is bound to accuse himself,
why then dost thou go about to ensnare me?`"
The recorder, in resentment, returned, "`Sir, hold your tongue,
I did not go about to ensnare you.`"
Then William Penn freely declared, '`we confess ourselves so far from recanting
or declining to vindicate our assembling ourselves to preach,
pray, or worship the eternal, holy, just God,
that we believe it to be our indispensable duty to meet upon so good an account;
nor shall all the powers upon earth be able to divert
us from reverencing and adoring God,
who made us.`'
Richard Brown alledged, '`you are not here for worshipping God, but for breaking the law;
you do yourselves a great deal of wrong in going on in that discourse.`'^
footnote:[This appears to me a nice distinction in terms, without a difference in effect.
The law alluded to by Brown was made against all worship not according to the liturgy, etc.
The Quakers worship was from conscientious conviction, not according thereto,
but such as they believed most acceptable to God:
Their worship being then a breach of the law,
is not then their worshipping God and breaking the law one and the same thing?]
To this William Penn answered, "`I affirm I have broken no law;
nor am I guilty of the indictment that is laid to my charge.
And to the end the bench, the jury and myself, with these that hear us,
may have a more direct understanding of this procedure,
I desire to know by what law you prosecute, and upon which you ground my indictment?`"
The recorder answered, "`upon the common law.`"
William Penn desired that common law might be produced,
as it would be impossible for the jury to determine, or agree in their verdict,
under ignorance of the law, by which they should measure the truth of the indictment,
and the guilt or contrary of the fact.
The recorder, provoked at his persistance in demanding a specification of the law,
which he could not tell where to find,
suffered his passion to transport him beyond the bounds of decency,
and treat a man on every account as respectable as himself with ill language,
in this laconic reply to his just requisition, "`You are a saucy fellow,
speak to the indictment:`" But William Penn insisting his right
to have the law produced on which the indictment was founded,
and the court evading it, and insisting on his pleading to the indictment as it stood:
At last the recorder, losing all patience,
to abusive language added a plain confession that
he did not know were the law was to be found:
"`You are,`" said he, "`an impertinent fellow; will you teach the court what law is?
Its Lex non scripta, that which many have studied thirty or forty years to know,
and would you have me tell you in a moment?`"

[.discourse-part]
_William Penn._
If the common law be so hard to be understood, it is far from being common;
but if Lord Coke in his institutes be of any authority, he tells us,
that common law is common right, and that common right is the great charter privileges.

[.discourse-part]
_Recorder._
You are a troublesome fellow,
and it is not for the honour of the court to suffer you to go on.

[.discourse-part]
_William Penn._
I design no affront to the court, but to be heard in my just plea;
and I must plainly tell you, that if you deny me the oyer of that law,
which you suggest I have broken, you do at once deny me an acknowledged right,
and evidence to the whole world your resolution to sacrifice the privileges
of Englishmen to your sinister and arbitrary designs.

[.small-break]
'''

This exasperated the recorder to that degree that
he called to the officers to take him away.
And addressing himself to the mayor, said, my lord,
if you do not take some course with this pestilent fellow to stop his mouth,
we shall not be able to do anything tonight.
Upon which the lord mayor ordered him to be haled from the bar into the bail-dock.
As he was going away, he made the following address to the jury.
This I leave upon your consciences, who are my jury, and my sole judges,
that if these ancient fundamental laws, which relate to liberty and property,
and are not limited to particular persuasions in matters of religion,
must not be indispensably maintained and observed,
who can say he hath a right to the coat on his back?
Certainly then our liberties are to be openly invaded; our wives to be ravished,
our children enslaved, our families ruined,
and our estates led away in triumph by every sturdy beggar and malicious informer,
as their trophies, by our pretended forfeitures for conscience-sake.

William Mead, being left alone at the bar,
also addressed the jury in the following speech:

[quote]
____
Ye men of the jury, I now stand here to answer to an indictment against me,
which is a bundle of stuff, full of lies and falsehoods;
for therein I am accused that I met with force and arms unlawfully and tumultuously.
Time was when I had freedom to use a carnal weapon, and then I thought I feared no man:
But now I fear the living God, and dare not make use thereof, nor hurt any man;
nor do I know that I demeaned myself as a tumultuous person:
Therefore it is a very proper question that William Penn demanded,
an oyer of the law on which our indictment is grounded.
If the recorder will not tell you what makes a riot, etc.
Coke tells us, a riot is, when three or more are met together to beat a man,
or to enter forcibly into another man`'s land, to cut his grass, his wood,
or break down his pales.
____

The recorder, pulling off his hat in a contemptuous manner, said, "`I thank you, Sir,
for telling me what the law is.`"
William Mead replied, "`thou mayst put on thy hat, I have never a fee for thee now.`"
The lord mayor saying,
"`you deserve to have your tongue cut out;`" and the recorder
threatening to take occasion against him,
he pleading his privilege as an Englishman, the recorder rejoined,
"`I look upon you to be an enemy to the laws of England,
nor are you worthy of such privileges as others have.`"
Then he was likewise ordered into the bail-dock.

When the prisoners were gone, the recorder proceeded to give the jury their charge;
which William Penn observing, remonstrated against as an irregular proceeding,
raising himself up by the rails of the bail-dock, that he might be heard,
with a loud voice spoke thus: "`I appeal to the jury, and this great assembly,
whether it be not contrary to the undoubted right of every Englishman to give the jury
their charge in the absence of the prisoners`" The recorder answered sneeringly,
"`ye are present, ye do hear, do you not?`"

[.discourse-part]
_William Penn._
No thanks to the court that ordered me into the bail-dock: And you of the jury,
take notice that I have not been heard,
neither can you legally depart the court before I have been fully heard,
having at least ten or twelve material points to offer,
in order to invalidate the indictment.

[.small-break]
'''

This speech being very unpalatable to the court, the recorder cried out,
pull that fellow down, pull him down.
William Mead thereupon exclaimed against their proceedings as barbarous and unjust;
upon which, by order of the recorder,
they were thrust into a stinking hole and detained there,
while the jury went up to agree upon their verdict;
after staying about an hour and an half, eight came down agreed;
but four being dissatisfied remained above.
The bench, highly provoked at these jurymen, who obstructed their designs,
threatened them with the like domineering in civility as they had the prisoners before,
particularly Edward Bushel, whom they charged with being the cause of this disagreement,
and an abettor of faction, with more imperious and menacing language,
unbecoming persons in the seat of justice, or those of a liberal education.
After much abusive treatment they sent them to consider of bringing in their verdict,
which after some time they agreed to bring William Penn guilty of speaking in Gracious-street.
This the court refused to accept as a verdict:
And strove unfairly to extort expressions from some of them,
to procure a verdict more to their purpose,
as that he was speaking to an unlawful assembly; but Bushel, Hammond,
and some others bravely maintained their right,
and refused to admit any alteration in their verdict; at which the recorder, mayor,
and others took occasion to abuse them with most opprobrious language,
and forced them up again to bring in a verdict they would accept.
Upon their return they produced their verdict in writing, signed by them all, as follows,
viz.

[.embedded-content-document.legal]
--

We the jurors hereafter named do find William Penn guilty of speaking or preaching
to an assembly met together in Gracious-street the 14th August 1670,
and that William.
Mead is not guilty of the said indictment.

[.signed-section-signature]
Thomas Veer, foreman.
Charles Meilson.
Edward Bushel.
Gregory Walklet.
John Hammond.
John Bailey.
Henry Henley.
William Lever.
Henry Mitchel.
James Damask.
John Brightman.
William Plumsted.

--

This both the mayor and recorder resented so highly
that they exceeded the bounds of moderation,
reason and civility, which drew the following remonstrance from William Penn.
"`My jury, who are my judges, ought not to be thus menaced; their verdict should be free,
and not compelled: The bench ought to wait upon them, but not forestal them:
I do desire that justice may be done me,
and that the arbitrary resolves of the bench may
not be made the measure of my jury`'s verdict.`"
This poignant vindication of his right exasperated
the recorder to the following illiberal exclamation:
"`Stop that prating fellow`'s mouth, or put him out of the court.`"
And the mayor telling the jury, "`That he had gathered a company of tumultuous people.`"
William Penn, in explanation, replied, It is a mistake, we did not make the tumult,
but they that interrupted us;
the jury cannot be so ignorant as to think we met
with any design to disturb the civil peace:
We were with force of arms kept out of our lawful house,
and met as near it in the street as the soldiers would give us leave: It is no new thing,
nor with the circumstances expressed in the indictment, but what was usual with us:
"``'Tis very well known that we are a peaceable people,
and cannot offer violence to any man.`"
He insisted that the agreement of twelve men is a verdict;
required the clerk of the peace to record it; and addressing himself to the jury, said,
"`You are Englishmen, mind your privileges; give not away your right.`"
To which some of them replied, "`Nor will we ever do it.`"

The prisoners were now sent back to jail, and the jury to their chamber,
where they were shut up all night without victuals, fire, or any accommodation,
not even a chamber-pot,
the recorder having declared he would have a verdict or they should starve for it.

The next morning they brought in the same verdict;
and neither the passionate resentments, the opprobrious reflections,
nor the repeated menaces of the bench, could prevail upon them to alter it in the least.
Their steadfastness, and the manly defence of William Penn,
made the recorder`'s passion get the better of his prudence so far as to extort sentiments,
which policy would conceal.
Till now,
I never understood the reason of the policy and prudence
of the Spaniards in suffering the inquisition among them;
and certainly it will never be well with us,
till something like the Spanish inquisition be in England.
You will find next sessions of parliament there will be a law made,
that those who will not conform shall not have the protection of the law.
The jury after repeated menaces, were forced up again,
and spent a second night without accommodations as before;
no regard being paid to their remonstrances, that they had all agreed,
and in confirmation thereof had set their hands to the verdict.
Next morning the prisoners being brought to the bar,
and the jury called upon to bring in their verdict,
returned both the prisoners not guilty;
for which they the prison- were fined forty marks a man,
and ordered to be imprisoned till the fines were paid;
but some time after were discharged by _habeas corpus_ returnable in the common-pleas,
where their commitment was judged illegal.
The prisoners upon being cleared by the jury, demanded their liberty;
but they were remanded to prison for their fines for not taking off their hats,
to which they excepted, as being arbitrarily imposed,
in violation of the great Charter of England, which saith, "`No man ought to be amerced,
but by the oath of good and lawful men of the vicinage.`"
Thus ended this memorable trial,
wherein a noble stand was made against the illegal proceedings
of despotic magistrates in dangerous times,
when reason, law and equity were equally disregarded.
The conventicle act was made to encourage prosecutions;
whereby honest people in various parts were greatly oppressed by the informers and justices;
but the courts of judicature outrun the law itself.

At the same sessions thirteen more of said people having been sent to prison,
partly from Grace-church-street, and partly from the meeting near Bishop`'s-gate,
(amongst whom was Thomas Rudyard, a man well skilled in the laws of the land,
and a strenuous vindicator of the liberties of the people^
footnote:[This Thomas Rudyard was particularly obnoxious to the magistrates of London;
because, as a lawyer,
he had successfully pleaded the cause of the oppressed against their tyrannical measures,
he was marked out by them as a peculiar object of their vengeance.
Previous to his trial at this sessions,
they issued a warrant to break open his house in the dead time of the night,
to apprehend him, which warrant was executed by soldiers,
and the next day he was sent to Newgate, under pretence,
that he stirred up persons to disobedience to the laws,
and abetted and encouraged such as met in unlawful and seditious conventicles,
contrary to the late act:
But his case being brought before the court of common-pleas by _habeas corpus_,
that court gave judgment, that he was unjustly imprisoned and unlawfully detained.
Whereupon he was set at liberty.
The magistrates, mortified at their disgrace and disappointment,
caused an indictment to be framed against him,
for hindering due course of law against one Samuel Allenbridge.
On this trial he so well defended his cause that he was acquitted.
Their efforts to punish him on these accounts failing them,
they next availed themselves of his religious profession,
and committed him to Newgate from a meeting at White-hart
court.]

were brought to trial upon like indictments,
for meeting in a riotous manner.
The same jury, who acquitted Penn and Mead,
had been also sworn in court to try these other Quakers;
but were incapacitated by that extraordinary proceeding
of the court in fining and imprisoning them.

Their treatment was as arbitrary and over bearing from the recorder and the rest,
as that of Penn and Mead had been: They were used unjust in the same manner,
and fined for not taking off their hats, which had been taken off by the officers,
and put on their heads again by order of the court: a second jury was packed to try them,
against which they protested,
desiring to be informed by what law or precedent two juries
could be sworn to try one and the same fact?
received for answer, "`The court over-rules you.`"
They yet urging that the law ought to be the rule and guide of all courts of justice,
and that arbitrary answers were not sufficient to satisfy their reasonable demands;
the recorder, greatly enraged, told one of the prisoners he should be gagged,
and deserved to have his tongue bored through with a red hot iron.
They objected to several of this second jury;
but their lawful challenges were rejected by the bench,
for no better reason than that the court over-ruled them.

The substance of the evidence against them was,
that they were seen in Grace-church-street among an assembly of people,
and that they stayed there after proclamation was made for all persons to depart.
They freely confessed they were met at Gracious-street to worship God;
but denied that they were met for the purposes alleged in the indictment,
and designing to know upon what law the indictment was grounded,
received similar answers to those before given to Penn and Mead.
The indictment having set forth, that three several proclamations were made,
the prisoners alleged this to be a mistake, for there was but one made that day.
Upon which the mayor demanded of one of the witnesses,
whether oyez was not repeated three times?
The witness answered in the affirmative.
Then said the mayor, that was three proclamations.
Thus by forced constructions, as by other parts of their conduct,
the members of this court discovered their partiality
and inclination to convict the prisoners.
The prisoners urged farther their peaceable principles and demeanour;
and that the law against riots was never designed against them,
but against popish and other disturbers of the public peace.
To which the recorder answered, according to the court maxims of that time,
That the papists were better subjects to the King than they,
and that they were a stubborn and dangerous people, and must either be brought under,
or there would be no safe living by them.
As this speech of the recorder`'s was a mere effusion
of malice and undeserved dislike to this people,
a charge against the prisoners, supported by no fact,
but disproved by the whole tenour of their conduct,
they offered to vindicate themselves from his aspersions,
for which they were treated just as their friends had been before them,
ordered into the bail-dock;
in their absence the jury received their charge from the recorder,
not so much a summing up of the evidence, as a virulent accusation against them,
concluding with a direction that they must bring them in guilty; which this jury,
packed for the purpose, readily did.

The next that were brought to their trial were Ezekiel Archer and Margery Fann,
who having been indicted as rioters the sessions before,
and the evidence being insufficient to convict them,
were detained in prison on an indictment for felony;
but this attempt against them was so manifestly unjust and malicious,
that even this jury brought them in not guilty;
and yet Ezekiel Archer was fined and imprisoned with the rest.

The conclusion of their trial was of a piece with the conducting thereof:
At the close of the sessions these prisoners were called down to the sessions-house,
as they expected, to receive judgment,
and had accordingly prepared exceptions in arrest
of judgment to be delivered to the recorder in writing;
but they were precluded from the opportunity of making their defence;
the bench passing sentence without any of them hearing it:
So determined were they to effect their purpose of punishing them,
that they went over all forms of legal proceedings in favour of the prisoners.

It appeared by the Newgate book that this clandestine
sentence condemned them in sundry fines,
some forty marks, some twenty;
and as a special mark of their vindictive disposition towards Thomas Rudyard,
he was fined 100£. and all to be committed to prison,
until they should pay their respective fines.

But it appearing that Newgate was so full of prisoners that there
could not be convenient room for this additional number;
the court entered into a consultation where to imprison them,
and being informed that during the sessions the master of the house
and one of the prisoners had died of the spotted fever,
out of the _dog_ by Newgate, they ordered these friends to be imprisoned there;
and a keeper was appointed to prevent their going out on any occasion.
Yet through the goodness of divine providence they were preserved in health,
beyond the expectation of their friends or hope of their enemies,
who by the series of their carriage, through the whole of their proceedings against them,
gave occasion to suspect they shut them up in that
infected house with no friendly design.

An account of both these trials was published soon after, the first by William Penn,
under the title of The People`'s Ancient and Just Liberties Asserted.
To which is added, an appendix, exhibiting at large the invalidity of the evidence;
the falsity and absurdity of the indictment; the arbitrary measures of the court;
their repeated violations of the great charter,
in particular the absolute illegality of their treatment of their jury;
in confirmation whereof he cites Judge Keeling`'s case,
who about three years before had fallen under the
censure of the House of Commons upon this very account.
Whereupon they passed the following resolutions:

That the proceedings of the lord chief justice, in putting restraints upon juries,
are innovations in the trial of men for their lives and liberties
and that he hath used an arbitrary and illegal power,
of dangerous consequence to the lives and liberties of the people of England,
and tending to the introducing of an arbitrary government.

Secondly, that in the place of judicature, the lord chief justice hath undervalued,
vilified and condemned, the great preserver of our lives, freedom and property.

Thirdly, that he be brought to trial in order to condign punishment,
in such manner as the house shall judge most fit and requisite.
And two days after, "`__Die Veueris,__ 13th December, 1667, resolved,
that the precedent or practice of fining or imprisoning
jurors for verdicts is illegal.`"

The account of the succeeding trials of these people
at that session was published by Thomas Rudyard,
under the title of, [.book-title]#The Second Part of the People`'s Ancient and Just Liberties Asserted,#
who as a lawyer was well qualified with precision to point out the right of juries,
and the unlawfulness of the proceedings then in vogue.
These pieces were well accepted by the public, particularly the former,
which passed sundry impressions;
for the people began now to be suspicious of ill designs carrying on underhand,
and that the established church was let loose to worry and persecute the dissenters,
in order that popery and arbitrary power hand in hand might seize the
favourable opportunity to establish themselves on the ruins of both.

When or by what means they were released I find no particular account;
but William Penn`'s imprisonment at this time was of no long continuance;
it appears he was at liberty at the time of his father`'s decease,
which happened the 16th of the same month, viz. September 1670.
His father was at this time perfectly reconciled to his son,
and left him both his paternal blessing and a plentiful estate:
And seems to have conceived a favourable opinion of his friends,
as appears by his deathbed expressions, recorded by his son in that
excellent treatise, [.book-title]#No Cross No Crown.#

But the intemperate and extrajudicial proceedings of the recorder were
looked upon in a different light by his colleagues of the bench.
Alderman John Robinson made a motion in the succeeding court of alderman,
"`that the recorder deserved 100£. for his service done at the Old Bailey the last sessions;
which motion was agreed to, and an order issued to the chamberlain to pay it.
Thomas Rudyard, coming to the knowledge thereof,
as also of 200£. more he had received in like manner, within eight months last past,
thought these transactions worthy of publication to his fellow citizens,
to apprize them of the disposal of the public stock,
with this ironical reflection upon it,
"`an excellent way to ease the treasury of being overburdened with orphan`'s money,
by which sinister means of disposing of its cash,
the chamber was so deeply in debt as was almost incredible.`"
