== Chapter XXIV.

[.chapter-synopsis]
* Illegal Proceedings at Horsly-down
* Order of Council for demolishing the Meetinghouse there
* Cruel Abuse by Soldiers
* The civil Officers endeavour to prevent their Abuses ineffectually
* Remark thereupon
* Proceedings at Ratcliff
* At Wheeler-street
* William Penn taken from thence, and after an Examination before Sir John Robinson and others committed to Newgate on the Oxford Five-mile Act
* George Fox takes a Journey into the Country and is taken ill
* Exerts himself to procure his Wife`'s Liberty with Success
* Sails for America

Having traced the arbitrary proceedings of this session,
and the consequent transactions thus far, we are to view measures still more violent,
tyrannical and illegal,
adopted against this people in other parts of the city or suburbs in these strange times.

They had a meetinghouse at an extremity of the city, viz at Horsly-down,
in the borough Southwark: Here,
from the very beginning of the persecution under this last act,
the members of this meeting were not only prosecuted thereby in heavy fines and distraints,
but personally abused by soldiers,
who were appointed to keep them out of their meetinghouse, in a very barbarous manner:
And the repeated abuses they received not answering the end intended,
of deterring them from keeping up their religious meetings,
in performance of their religious duty, in the month called July,
the following order was issued by the king and council
for demolishing the said meetinghouse.

[.embedded-content-document.legal]
--

[.blurb]
=== An order of the king and council for demolishing the meetinghouse at Horsly-down in Southwark. At the court at Whitehall, 29th July, 1670.

[.no-indent.emphasized]
Present:

The King`'s most excellent Majesty.

His Highness Prince Rupert.

Lord Archbishop of Canterbury.

Lord Keeper.

Duke of Monmouth.

Duke of Ormond.

Earl of Ossory.

Earl of Oxford.

Earl of Anglesea.

Earl of Bath.

Earl of Craven.

Lord Ashley.

Mr. Treasurer.

Mr. Vice Chamberlain.

Mr. Secretary Trevor.

[.small-break]
'''

His Majesty being informed that there have been
of late frequent conventicles and seditious meetings,
under pretence of religious worship,
contrary to and in contempt of the laws established,
at an house or building at Horsly-down, adjoining to the Artillery garden,
and that the persons who there assemble behave themselves
in such a riotous and tumultuous manner,
that if their meetings be any longer endured,
his Majesty`'s peace and the quiet of his government will thereby be manifestly endangered:
For prevention whereof, it was this day ordered, his Majesty present in council,
and by his express command, that Christopher Wren, Esq;
surveyor general of his Majesty`'s works,
do cause the said house or building to be pulled down and demolished,
in case from henceforth any persons whatsoever shall presume to meet or hold
any conventicle or unlawful assembly therein under colour of religious worship:
And it was farther ordered by his Majesty,
that this signification of his royal pleasure be affixed on the said building,
to the end that the owners and occupiers of the same may take notice thereof,
to prevent and hinder said meetings at their peril.

[.signed-section-signature]
John Nicholas.

--

The execution of this order, which was grounded upon no legal process or judicial trial,
was not committed to the civil power,
but the whole of the despotic treatment of this assembly
was put into the hands of the military,
who behaved themselves with such savage barbarity,
as if they had been let loose to execute martial law upon them.
The troopers came twice to the meeting there,
after the affixing up of the order to disperse the assembly:
A sergeant plucked them out of the meetinghouse, and when forced out,
the troopers rode amongst them to disperse them, and wounded several of them.
The third time, on the 20th of August so called, being the seventh day of the week,
a party of soldiers with carpenters and others came and pulled down the meetinghouse,
carried away the boards, windows, benches and forms, and sold them.
On the next day the friends came as usual,
and met upon the rubbish of the demolished house,
but the soldiers came and dragged them into the street:
On the 20th a captain ordered his soldiers to knock their brains out;
they pulled and haled them from the place, and having kept them until near sunset,
carried them to the marshalsea prison,
and lodged them there without any warrant from a civil magistrate.

This dragooning of this meeting was continued weekly
for the greatest part of three months,
with increasing aggravation;
the foot soldiers beat and abused both men and women in outrageous manner
with their muskets and pikes until they broke several of them;
a sergeant with his halbert laid about him like a madman, striking and wounding several.
After the foot had perpetrated their abuse,
a party of horse came furiously and endeavoured to ride over them; but the horses,
less savage than their riders, being unwilling to go forward, they turned them about,
and by curbing and reining them endeavoured to force them backward,
and in that manner do the people what mischief they could.

Finding this people, though thus grievously abused,
not yet deterred from keeping up their religious assemblies,
being supported through all by the consciousness
of the sincerity of their hearts towards God,
and placing their confidence in his divine protection,
for the sake of performing their duty to whom,
they were exposed to this unmerciful treatment,
these military executors of illegal punishment changed their method of attack;
one of them having provided himself with a shovel,
threw the dirt out of the channels upon men and women promiscuously,
in a shameful manner;
after him advanced horse and foot in a furious onset
upon an harmless unresisting body of people,
and dealt about their blows with remarkable outrage,
were they knew they would meet with no repulse,
striking and knocking down all before them without regard to age or sex,
to the shedding of the blood of many.
And when some of the inhabitants,
in compassion took them into their houses to save their lives,
the soldiers forced open the doors, haled them out into the streets,
and plucked off their hats, to strike on their bare heads,
whereby many went away with heads grievously broken;
they tore both men and women`'s clothes off their backs,
dragged women through the mire by the horses sides;
used modest and religious women with brutish indecency of action and expression,
One woman with child was struck on the belly and breast,
in consequence wereof she miscarried, and her life was in great danger.
A man friend was dragged, after being severely beaten,
into the ruins of the meeting-bouse by one of those cruel men, who demanded his money,
and endeavoured to rifle his pockets,
threatening with execrations he would stab and pistol him if he would not deliver it.

At one of these assaults above twenty persons were wounded and sorely bruised;
at the succeeding one upwards of thirty;
and at this last the number of wounded and bruised exceeded fifty.
At length these military violations of the peace of the
city roused the civil officers to interpose their authority;
but it was too weak to protect this unarmed body against
the number prevent of armed men let loose upon them:
The succeeding first day, the 16th of October, being again met,
and kept out of their meeting-place,
there came again a party of horse and foot prepared to fall upon them;
but a party of constables being there before them to preserve the peace,
kept them at bay for a short time, it being conceived, it is like,
a more serious affair to trample upon the legal authority of the
civil power than upon the immunities and persons of private people;
but their thirst of mischief soon got the better of any
slight scruples they might entertain on this account;
they quickly broke over the barriers of civil restraint,
and fell upon the poor defenceless people with their accustomed rage and inhumanity:
Many of them had their blood spilled plentifully about their ears and faces,
and one of the constables interposing in endeavours to prevent the shedding of blood,
and to keep the peace, was a sharer with them in this indiscriminate abuse,
receiving a broken head for his pains.
Being reprehended for their cruelty, some of them answered,
If you knew what orders we have, you would say we dealt mercifully with you;
others being asked,
how can you deal thus with a people that have love and good will to all men,
and make no resistance or opposition?
returned for answer, We had rather, and it would be better for us,
if they did resist and oppose.
This was looked upon by the sufferers,
as if they sought occasion to embrue their hands more deeply in blood,
and take the lives and estates of honest people for their prey.

The substance of this narrative of the gross proceedings of the
soldiers towards this people was presented to the king and council,
which produced the cessation of these cruelties for a season,
though they were not altogether discontinued.

Hitherto while the persecuting measures against the dissenters in general,
and the people called Quakers in particular,
had been ostensibly carried on by the parliament and the inferior magistrates,
the king appeared inclined to lenity and used repeated endeavours
to procure a relaxation of the severe laws enacted against them,
to which it is pretended the liberality of the commons in supplying
aids to his extravagance purchased his assent against his judgment,
his inclination and his honour.
But this last severe blow appears plainly to have been inflicted directly from the court,
and by direction or assent of the king himself,
upon pretences so groundless and frivolous as show an occasion was sought and not given.
But what should incite him, contrary to his usual lenity and easiness of temper,
to authorize actions of such glaring injustice and severe
inhumanity against an harmless body of his own subjects,
who had never combined against, or molested his government in the least,
we may now be at a loss to determine.
It was just about this time that through the advice and suggestions of evil counsellors,
and roused by the more active spirit of his brother,
he is reported to have entered into a design to change the measures of his government;
to free himself from his dependence upon parliaments, and the fetters of their restraint;
and with the assistance of those ministers, advisers and abettors of his design,
who are well known in English history by the denomination of the Cabal,
to make himself absolute, and reinstate the Roman Catholic religion in these kingdoms.
Now, how far it might be judged conducive to such designs,
to turn the army loose upon a defenceless and unresisting part of the people,
in order to inure them to acts of rapine and hostility against their fellow-citizens: or,
secondly, to aggravate the sufferings of the subjected party,
to sharpen their desire of ease by any means, or from any quarter, in order,
by relaxing the persecution solely by the prerogative,
to gain the dissenters to the court interest,
and at the same time open a door for the gradual introducing of popery,
under the plausible pretext of a general indulgence to liberty of Conscience:
Whichever of these designs (or whether both together) was the moving
cause to these arbitrary orders and unwarrantable proceedings,
they were the effects of a barbarous and unjust policy, wherein the bounds of all laws,
human and divine, were wantonly transgressed, and religion,
morality and humanity forced to give way to the sinister
views and deceitful measures of a vicious court,
who seemed at this time to have thrown off all the restraints of honour, conscience,
and regard to reputation.

Yet I am apprehensive the agents in these extravagant abuses might,
through party resentments or evil instigation,
carry these oppressive and injurious measures much further than the king`'s intention,
for when a narrative of these violences of the soldiers was presented to him,
a stop was put thereto for the present.

There was another meetinghouse belonging to this society at Ratcliff,
(also at an extremity of the city.) which soon after was
subjected to the like violence with that of Horsly-down,
and by Sir John Robinson, lieutenant of the tower,
without any legal process or lawful cause, ordered to be demolished.
On the 2nd of September, he came thither attended by one Captain Taylor,
and a party of soldiers belonging to the king`'s regiment,
and caused the said meetinghouse to be pulled down.
That day and the night following twelve cartloads of doors, windows and floors,
with other materials, were carried away.
Some of the materials were sold on the spot for money and strong drink.
Thus were an offensive and peaceable class of subjects,
not only exposed to grievous sufferings under severe laws,
but to exorbitant spoil and depredation without, or even contrary to law,
by officers under the government,
whose duty it was to protect the subjects in possession of their rights and property,
to execute justice, and exercise legal rule,
all of which we see in these instances grossly violated by them.

When their meetinghouse was pulled down, friends of Ratcliff met on the ruins,
or as near them as they would be permitted,
being generally kept off by constables or other officers,
who mostly either took some of them prisoners;
or by information procured them to be fined and distrained on the conventicle-act.

Robinson intended to have proceeded next to pull down the meetinghouse at Wheeler-street;
but Gilbert Latey, in whom the title was vested, and who was then in the West of England,
upon intelligence thereof returned to London,
ordered a poor friend to be put into the meetinghouse; made a lease to him,
and soon after waited on the governor of the tower, Sir John Robinson,
who looking sternly upon him, asked him, if he owned the meetinghouse in Wheeler-street?
to which Gilbert replied, he did, and several more too.

[.discourse-part]
_Robinson._
And how dare you own any meetinghouse contrary to the king`'s laws?

[.small-break]
'''

G+++.+++ Latey answered, he owned that meetinghouse before the king had any such law.

[.discourse-part]
_Robinson._
I find you are a pretty fellow; pray who lives in that house?

[.discourse-part]
_G+++.+++ Latey._
My tenant.

[.discourse-part]
_Robinson._
Your tenant! pray what is your tenant?

[.discourse-part]
_G+++.+++ Latey._
One that I have thought fit to grant a lease to.

[.discourse-part]
_Robinson._
Then you have a tenant, that has taken a lease from you?

[.discourse-part]
_G+++.+++ Latey._
Yes.

[.small-break]
'''

Upon this the governor looked displeased,
and addressing a friend who accompanied him by name, said,
I think you have now fitted me, and brought a fellow to the purpose;
had your friends been as wise as this fellow you might have had your other meetinghouses,
and so dismissed them.

After this, friends taking the same care, have generally preserved their meetinghouses.

William Penn, during the short interval of liberty and leisure he enjoyed this winter,
published a book, he entitled,
"`A seasonable Caveat against Popery,`" wherein he both exposes
and confutes many erroneous doctrines of the church of Rome,
and establishes the opposite truths by found arguments:
a work alone sufficient on one hand to wipe off the calumny
cast upon him of being a favourer of the Romish religion;
and on the other to manifest that his principle for liberty of conscience was universal,
as he wished it to be extended even to the papists,
under the security of their not persecuting others.

But he was not suffered to enjoy his liberty long.
Sir John Robinson, lieutenant of the tower,
who early distinguished his disposition to persecute (having
succeeded Brown in the office of lord mayor of the city,
and endeavoured to rival this intemperate magistrate in all his boisterous
and rigorous conduct) had all along shown an equal aversion to dissenters,
and Quakers particularly; was one of the bench of justices on the trial of Penn,
Mead and the rest at the Old Bailey,
an active promoter of all the arbitrary proceedings of that court,
and the mover for a reward to the recorder for trampling upon the rights of the subject.
This man, actuated by personal pique against William Penn,
had been some time watching the meetings to take him, and at last,
on the 5th of the 12th month (February) having information of his being to be at Wheeler-street,
sent a sergeant and soldiers, who planted themselves at the door,
and waited there until he stood up and preached;
and then the sergeant pulled him down and led him into the street,
where a constable and his assistants standing ready to join,
they carried him away to the Tower by order from the lieutenant;
a guard was there clapped upon him,
and a messenger dispatched to the lieutenant then at Whitehall,
to inform him of the success.
After keeping him upon guard near three hours, he came home,
and sent for William Penn from the guard, by an officer with a file of musketeers.
There were several other magistrates of the same cast present, namely,
Sir Samuel Starling, Sir John Sheldon, Lieutenant Colonel Rycraft and others.
Orders being given that no person unconcerned in the business should be admitted up,
they proceeded to the examination, of which we find the following account.

Although Robinson had the mittimus already made, and his name put in,
he pretended not to know him, but applying himself to the constable, asked,
what is this person`'s name?

[.discourse-part]
_Constable._
Mr. Penn, Sir.

[.discourse-part]
_F+++.+++ Robinson._
Is your name Penn?

[.discourse-part]
_W+++.+++ Penn._
Dost thou not know me?
Hast thou forgot me?^
footnote:[He might well ask this question,
since it was but a few months since his remarkable trial at the
Old Bailey when he gave them just occasion to remember him;
and it is probable the remembrance stirred up this fresh persecution of malice prepense.]

[.discourse-part]
_F+++.+++ Robinson._
I do not know you, I do not desire to know such as you are.
Is that your name, Sir?

[.discourse-part]
_W+++.+++ Penn._
Yes, my name is Penn, I am not ashamed of my name.
Next he proceeded to examine the constables and others who gave evidence,
that they found him at a meeting at Wheeler-street, speaking to the people.

[.small-break]
'''

Upon which Robinson said, Mr. Penn, you know the law better than I can tell you,
and you know these things are contrary to the law.

[.discourse-part]
_W+++.+++ Penn._
If thou believest me to be better versed in the law than thyself,
I know no law I have transgressed.
Now, whereas I am probably to be tried by the last act against conventicles,
I conceive it doth not reach me.

[.discourse-part]
_F+++.+++ Robinson._
No, Sir, I shall not proceed upon that law.

[.discourse-part]
_W+++.+++ Penn._
What law then?
I am sure that was intended for the standard on these occasions.

[.discourse-part]
_F+++.+++ Robinson._
The Oxford act of six months.

[.discourse-part]
_W+++.+++ Penn._
That of all acts cannot concern me; for I was never in orders,
neither episcopally nor classically,
and one of them is intended by the preamble of the act.

[.discourse-part]
_F+++.+++ Robinson._
No, no, any that speak to an unlawful assembly; and you spoke to an unlawful assembly.

[.discourse-part]
_W+++.+++ Penn._
An unlawful assembly is too general a word,
the act doth not define what is meant by an unlawful assembly.

[.discourse-part]
_F+++.+++ Robinson._
But other acts do.

[.discourse-part]
_W+++.+++ Penn._
That is not to the purpose.
It is hard that you will not stick to some one act,
but to accomplish your ends borrow a piece out of one act to supply the defects of another,
and of a different nature from it.

[.small-break]
'''

F+++.+++ Robinson next proceeded to require him to take the oath prescribed by the act;
and upon his refusing, said, '`I am sorry you should put me upon this severity,
it is no pleasant work to me.`'
To this William Penn replied, '`not without reason: these are but words,
it is manifest this is a prepense malice;
thou hast several times set the meetings for me, and this day particularly.`'

[.discourse-part]
_F+++.+++ Robinson._
No, I profess, I could not tell you would be there.

[.discourse-part]
_W+++.+++ Penn._
Thy own corporal told me that you had intelligence at the tower,
that I would be at Wheeler-street: It is disingenuous and partial:
I never gave thee occasion for such unkindness.

[.discourse-part]
_Robinson._
I vow, Mr. Penn, I am sorry for you; you are an ingenious gentleman all the world allows,
and you have a plentiful estate;
why should you render yourself unhappy by associating with such a simple people.

[.discourse-part]
_W+++.+++ Penn._
I confess I have made it my choice to relinquish
the company of those that are ingeniously wicked,
to converse with such as are more honestly simple.

[.discourse-part]
_F+++.+++ Robinson._
Well, Mr. Penn, I have no ill will towards you; your father was my friend,
and I have a great deal of kindness for you.

[.discourse-part]
_W+++.+++ Penn._
But thou hast an ill way of expressing it.

[.small-break]
'''

Which was really the case, for notwithstanding this profession of kindness,
after months on some further discourse he committed him, as was before determined,
to Newgate for six months, upon an act which had no relation to him,
but fixed on as inflicting the severest punishment;
the remembrance of the trial at the Old Bailey,
and the publication of their arbitrary exertion of power against law,
operating more powerfully on his passions to avenge himself of him,
than the remembrance of his father`'s friendship to
requite it with acts of kindness to the son.
Upon Robinson`'s signifying he must send him to Newgate for six months,
and when they are expired that then he might come out, William Penn,
like a man and a christian, replied, "`Is that all?
thou well knowest a larger imprisonment hath not daunted me:
I accept it at the hand of the Lord, and am contented to suffer his will.
Thy religion persecutes, and mine forgives:
I desire God to forgive you all that are concerned in my commitment,
and I leave you all in perfect charity, wishing your everlasting salvation.`"

Being thus committed to prison, he employed the time of his confinement
in writing. [.book-title]#The Great Cause of Liberty of Conscience Briefly Debated
and Defended,# with several other occasional pieces,
were the production of his pen at this time.

After some time the heat of this persecution abated in the city;
but in some other parts it was carried on with unrelaxed violence,
which occasioned George Fox to leave the city to
visit his persecuted friends in the country,
to sympathize with and comfort them in their grievous sufferings,
and encourage them to steadfastness in their religious duties,
relying on divine protection under all the afflictions permitted to befall them,
for the trial of their faith and patience; reminding them,
that their severe trials were but for an assigned time;
the period whereof was determined in the divine counsel;
that the truth is without limitation of time;
and advising them to live in that which doth not think the time long.

In this journey he fell ill of a distemper which
deprived him of his sight and hearing;
and to several that came to visit him seemed to threaten his dissolution;
but after some time he recovered gradually;
and although persecution was so hot in divers places,
and in some places there was much threatening,
and some attempts to break up the meetings, yet he escaped unmolested,
and having finished his service returned to London,
and although still weak in body he was diligently exercised
in his ministerial labours amongst his friends.

Having soon after his marriage received information of his wife`'s being
imprisoned (as before-noticed) he thereupon incited her daughters,
who were in London, to apply to the king, who were so successful,
as to procure his order to the sheriff of Lancashire for her discharge,
which he hoped would be obeyed.
But upon this fresh storm of persecution breaking out, her enemies, he understood,
had found means to detain her still in prison:
Wherefore he now renewed his endeavours for her release, and by the assistance of others,
obtained from the king a discharge under the great seal,
to clear both herself and her estate, after she had been ten years a prisoner,
under an unjust sentence of premunire.
This mandate he sent down immediately, whereby her liberty was obtained.

And now the heat of the persecution beginning to cool,
he felt a draught of duty inclining him to pay a religious visit to his friends in America;
and apprizing his wife by a letter of his intention, desired her to come up to London,
which she did accordingly:
And having taken leave of her he set sail the latter part of the summer for America,
in company with several other friends,
and after a passage of something more than seven weeks landed at Barbados.
