== Chapter I.

[.chapter-synopsis]
* The King publishes his Declaration of Indulgence to Dissenters
* Heads thereof
* Measures adopted by the People called Quakers to procure the release of their Friends
* Thomas Hicks calumniates the Quakers, so called
* Answered by William Penn
* Partial Proceedings of the Baptists
* Public Affairs
* Declaration of Indulgence revoked
* Change in the Disposition of the Parliament

The people called Quakers enjoyed little ease to their persons or security
of their property from their first appearance to this time;
and particularly during the twelve.
years of this reign, we have seen persecution succeeding persecution,
and one penal law added to another, whereby they were exposed to imprisonment, premunire,
exile and woeful depredation;
but now the Dutch war being resolved upon and ready to break out, the King,
by the advice of his counsellors, seizes the opportunity,
under colour of promoting domestic peace, while engaged in a foreign war,
by virtue of his prerogative, as supreme in ecclesiastical affairs,
to issue his proclamation for suspending the execution of the penal laws against nonconformists,
in substance as follows:

[.numbered-group]
====

[.numbered]
1+++.+++ The King publishes it, in virtue of his supreme power in ecclesiastical matters,
which is aright inherent in his person, and acknowledged by several acts of parliament.

[.numbered]
2+++.+++ He declares his express resolution to be,
that the church of England be preserved and remain entire in her doctrine,
discipline and government, as now it stands established by law.

[.numbered]
3+++.+++ That no person shall be capable of holding any sort of
ecclesiastical benefice or preferment of any kind,
who is not entirely conformable.

[.numbered]
4+++.+++ That the execution of all penal laws in matters ecclesiastical
against whatsoever class of nonconformists or recusants,
be immediately suspended.

[.numbered]
5+++.+++ He declares that he will from time to time allow such a sufficient number of places,
as shall be desired in all parts of his kingdom,
for such as did not conform to the church of England, to meet and assemble in,
in order to their public worship and devotion.

[.numbered]
6+++.+++ That none of his subjects do presume to meet in any place,
until such place be allowed, and the teacher of that congregation be approved by him.

[.numbered]
7+++.+++ That this indulgence,
as to the allowance of public places of worship and approbation of teachers,
shall extend to all sorts of nonconformists and recusants,
except the recusants of the Roman Catholic religion,
to whom he will no ways allow public places of worship;
but only indulge them their share in the common exemption from penal laws,
and the exercise of their worship in private houses only.

====

This declaration of indulgence, apparently humane and laudable in itself,
is stripped of all its merit by the unanimous suffrage of all our historians,
from the consideration of the motives thereto,
which they consider as an open assertion of arbitrary power,
in disannulling the laws of the whole legislature,
by the exertion of an illegal prerogative assumed by one branch;
and not so much designed in favour of the dissenters,
to whom he bore no hearty good will, as of the papists,
to whose religion he was supposed to be privately reconciled.
It is alleged, "`the dissenters did not approve of this dispensing power,
nor were forward to accept their liberty this way,
being sensible the indulgence was not granted out of love to them,
nor would continue any longer than it would serve the interest of popery.
Many pamphlets were written for and against the Dissenters accepting it,
because it was grafted on the dispensing power.
Some maintained they should accept of nothing but a comprehension.
Others endeavoured to prove that it was the duty of the Presbyterians
to make use of the liberty granted them by the King,
because it was their natural right,
which no legislative power upon earth had a right to deprive
them of as long as they remained dutiful subjects.`"^
footnote:[Neale, v. 2. p. 684.]
The latter reason seemed to prevail, and most of their ministers took out licenses,
as prescribed in the declaration.

After a view of the grievances which had so long afflicted the people called Quakers,
who affected not the reputation of politicians, nor ranked with any political party,
and only wished to lead a quiet and peaceable life, in all godliness and honesty;
it is not to be wondered at,
if they readily accepted the ease and liberty granted by the King`'s declaration,
to which as peaceable subjects they had an undoubted right,
But for this temporary exemption from persecution they were
principally thankful to that providential hand,
which over-rules the kingdoms of this world; superintends and directs the actions of men,
to bring about his own wise and good purposes.

And in this transaction we have a fresh instance of the
affectionate sympathy and tender brotherly concern,
which the members of this society at this period entertained for each other.
Those who were at liberty, and set free from the oppression of the penal laws,
could not help feeling for their brethren under restraint,
many of whom had been kept immured in uncomfortable prisons for several years.
And as the present disposition of government in favour of nonconformists
presented an inviting opportunity to intercede in their behalf,
some of the principal members in London, viz. George Whitehead,
Thomas Moor and Thomas Green,
attended the King and council to solicit the discharge
of their suffering friends in prison,
and were so successful as to obtain the King`'s letters patent under the great seal,
containing a pardon and discharge for all such to whom he might legally grant the same,
whereby all that were convicted for transportation, upon premunire,
or in prison for fines, confiscations, or fees,
were discharged and restored to their families and their employments,
from which many of them had been cruelly and unjustly
separated for six or seven years or upwards.

When the warrant to the Attorney-general to make out the letters patent was obtained,
the friends concerned in the solicitation thereof found themselves in a difficult dilemma
in respect to the fees to be paid in the sundry offices they were to pass through,
understanding they would amount to a very great sum by reason
of the great number (upwards of 400) to be included in them.
The Lord Keeper, Sir Orlando Bridgeman, generously and voluntarily remitting his fees,
they thought themselves under a necessity to make
further application to the King to moderate the rest,
who accordingly issued his order, That the pardon,
though comprehending a great number of persons, do yet pass as one pardon,
and pay but as one.`"

Their success in this application furnished these friends with an opportunity
of giving a remarkable specimen of the universality of their charity,
and disposition to perform good offices to all, as far as in their power:
There were some other dissenters besides Quakers confined in prison,
and their solicitors observing the success of this application, applied to Geo.
Whitehead for his advice and assistance to get their
imprisoned friends discharged with his,
by procuring their names to be inserted in the same instrument;
he advised them to apply to the King for his warrant for that purpose,
which was accordingly obtained,
and these were by the same instrument restored to liberty.
George Whitehead adds, "`this I was glad of,
that they partook of the benefit through our industry.
And indeed I was never backward to give any of them my advice for their help,
when any of them in straits have applied for it;
our being of different judgments and societies did not abate my sympathy or charity,
even towards them, who in some cases had been our opposers.`"

The King`'s pardon being thus procured, those Quakers,
who were shut up in the different prisons in London,
were almost immediately set at liberty:
But how to extend the benefit thereof to those imprisoned in the country,
and particularly the remoter counties,
occasioned the friends concerned considerable thought and trouble;
for the patent-containing no less than eleven skins of vellum,
was too long to take many copies, and too cumbersome to be easily carried far;
yet being heartily engaged for the speedy release of all their friends,
who had been long confined, their care and industry surmounted all difficulties,
and procured the liberation of their friends in a general way,
even to the remotest part of the kingdom.

The people called Quakers being by these means freed from the severities of persecution,
and left to the enjoyment of the liberty of their
consciences without molestation from the government,
were not long left to enjoy that ease resulting from the King`'s
declaration before they were attacked from another quarter.
During the heat of persecution,
we have had repeated occasion to remark that other dissenters, by a temporizing conduct,
endeavoured to secure themselves from the storm.
And the Quakers only bore their testimony publicly
to that religion which they received as truth,
and that worship they conceived to be most acceptable to God,
as being the effect of conscientious conviction;
and against the unreasonableness of human laws,
prescribing or prohibiting a mode of worship in violation
of the freedom or the persuasions of tender consciences;
by keeping up their meetings duly and fully at the accustomed times and places,
as long as they were suffered to enjoy the use of their meeting houses:
And when they were kept out of them by force,
they assembled in the streets as near to the meeting houses as they could.

While this manly and open testimony of this society in their
conduct gave great offence and vexation to the persecutors,
as baffling their scheme of establishing uniformity,
and warding off the blow from the other sects of dissenters, who,
as most feared and heated for the severities they had suffered under their hands,
were principally aimed at;
it procured them the esteem and grateful regard of
the more ingenuous part of other dissenters,
who were sensible of the ease they enjoyed by the intrepidity and firmness of this people,
which abated the heat of persecution, and blunted the edge of the sword,
before it reached them;
owning those as the bulwark that kept off the force of the stroke from them,
and praying that they +++[+++the Quakers]
might be preserved steadfast, and enabled to break the strength of the enemy.
And some, especially among the Baptists,
expressed an high opinion both of the people and their principles,
which sustained them in undergoing sufferings,
which were a terror to others to think of.

These favourable sentiments in the hearers raised the jealousy of some of their teachers;
who in the time of persecution had lain by in cautious privacy,
and taken the advantage of a secure retreat behind them, while the Quakers, so called,
weathered out the storm:
But under the sun-shine of the King`'s indulgence they began to quit their covert,
and appear openly when they had nothing to fear; and either from envy,
or the fear of losing some of their hearers,
who had discovered these favourable sentiments of this body of people,
they soon made their public appearance in an hostile attack upon this inoffensive society,
in vilifying that virtue, which they had not the courage to imitate.

One Thomas Hicks, a preacher among the Baptists in London,
employed his pen in writing several pamphlets successively,
under the invidious title of [.book-title]#A Dialogue between a Christian and a Quaker;#
which (as usual in that unfair method of handling polemical
subjects) makes the fictitious Quaker speak in character,
or out of character, as best answered the author`'s design;
which appears not to have been to investigate truth,
so much as to represent his Quaker a deformed, ridiculous and erroneous being,
and for that purpose make him (says Thomas Ellwood) utter
"`some things abominably false;
others so ridiculously foolish,
as could not reasonably be supposed to come into the conceit,
much less have dropped from the lip or pen of any
that went under the name of a Quaker.`"

The unfair dealing and perverse misrepresentations
of this antagonist making a defence necessary,
this business was undertaken by William Penn, in two books,
the first entitled [.book-title]#Reason against Railing;# the other, [.book-title]#The Counterfeit Christian Detected.#
In which Hicks is not only convicted of publishing many palpable forgeries,
unfair perversions, and groundless calumnies against the people called Quakers at large,
but having indulged his invidious disposition so
far as to vilify sundry particular members by name,
as William Penn, George Whitehead and others,
an appeal was made to the society of Baptists in and about
London for justice against Thomas Hicks.

The principal Baptists, being partisans of Hicks,
did not discover that regard to truth and justice
which might reasonably be expected Baptists,
from a society professing reformed religion,
but seemed chiefly inclined to screen a brother from detection,
more than to do justice to the injured parties for his undeserved defamation:
They very disingenuously appointed a meeting in one of their meetinghouses,
under pretence of hearing the charges against Thomas Hicks, and calling him to account,
at a time when the complainants William Penn and George Whitehead were both absent
from the city in places too remote to be timely apprized of the intended meeting;
wherefore some of their friends desired it might
be deferred '`till they could be informed thereof,
and have time to return: But the Baptists,
seemingly of opinion that the meeting might be held more to their satisfaction,
and more accommodate to their views in the absence than the presence of the complainants,
could not be prevailed upon to defer it; but making a show of examining Hicks,
and hearing his defence, acquitted him; like the judge,
who having heard one side of the question, declined hearing the other,
for fear of puzzling the cause.

This partial decision furnished just occasion for a new complaint and demand of justice.
For as soon as William Penn returned to London,
he in print exhibited his complaint of their unfair proceedings,
and demanded a rehearing in a public meeting by joint agreement, which the Baptists,
quite averse to, with much importunity, and after many evasions,
were hardly prevailed upon at last to comply with, and even when constrained thereto,
Hicks would not appear, but sent Ives with some others of the party,
by clamours and rudeness to divert the complainants
from prosecuting the charge against him,
and carried their point, so far as to prevent the charge being heard,
though frequent attempts were made to read it.

The people called Quakers, despairing of obtaining satisfaction in this line,
Thomas Ellwood, on the behalf of his friends, appealed to the public in a single sheet,
in which he restated the controversy,
and reinforced the charge of forgery against Thomas Hicks and his abettors:
And one of the Baptists, Thomas Plant, a teacher, and one of Hicks`'s compurgators,
publishing an apology for their conduct, under the title of A Contest for Christianity,
was also answered by Thomas Ellwood, in a piece entitled Forgery no Christianity,
who in conclusion of both these productions offered a challenge
to make good the charge against Hicks as principal,
and his compurgators as accessaries, before a public and free auditory;
but they were too wary to appear further either in person or print.

Thus ended this controversy, which was at tended with this consequence,
that the aim of this unprovoked assault upon the principles
and reputation of this society was remarkably frustrated,
and these dialogues,
with their ungenerous and unequitable method of defending them and their author,
promoted what they were designed to prevent; for not a few of their members,
offended at their proceedings, deserted their meetings and society,
went over to the injured party, and joined them in religious fellowship.

About this time, as well as formerly, they were much engaged in controversy,
being exposed to the invidious attacks and calumniating
misrepresentations of adversaries of different denominations,
who readily took up, and published as truth,
every reproach that public rumour or private prejudice loaded them with;
which obliged them in self-defence to vindicate themselves from such groundless calumnies,
to detect the falsehoods and perversions of these adversaries,
and they generally cleared themselves and their principles
from the absurdities charged upon them;
and yet we have occasion to complain of these refuted misrepresentations,
picked out of the works of their bitterest adversaries, being revived,
and delivered to the world as authentic history by sundry modern writers of some note.

The measures of the court, in entering into hostilities with the Dutch,
and the confederacy with the French monarch, were both highly disgusting,
and reprobated by the most considerable part of the nation,
who looked upon them as a desertion of the interest of England, and of all Europe,
and a plain indication of the King`'s aversion to public liberty,
and predilection in favour of arbitrary rule.
So that fearing their own privileges were in danger of being wrested from them,
they were not backward in their discourses to express their fears,
and narrowly to canvass, and criticise upon, the proceedings of the court,
as replete with danger and bad designs.
This temper in the people was reciprocally offensive to the court,
and produced a proclamation prohibiting all unlawful and undutiful conversation,
spreading false news, intermeddling in affairs of state,
or promoting scandal against the King`'s counsellors.

Discontents having more or less affected all ranks of the people,
the consideration thereof, and the unconstitutional,
fraudulent and unjust measure the king had lately
adopted by the advice of his treacherous counsellors,
of raising money without parliamentary aids,
by shutting up the exchequer to the distress and ruin of many of the subjects,
made him and his ministers, by successive prorogations,
evade the meeting of the parliament, which they dreaded, for near two years;
and during this recess of parliament the declaration of indulgence continued in force,
and the Dissenters held their meetings without molestation.

But at length, when the parliament met, the King in his speech informed them,
that in order to have peace at home while he had war abroad
he had issued his declaration of indulgence to Dissenters,
and had found many good effects to result from this measure.
That he was resolved to stick to his declaration;
and would be much offended at any contradiction.
Notwithstanding which menace,
a remonstrance was drawn up by the commons against the said declaration,
insisting that the penal laws could not be suspended but by act of parliament;
that this indulgence was illegal, as tending to subvert the constitution,
by rendering the other two branches of the legislature useless,
while the acts of the three conjointly could be superseded
by any prerogative claimed by one of them.

When they presented this remonstrance to the King,
he defended his right to issue the declaration,
by virtue of his acknowledged prerogative of supremacy in matters ecclesiastical,
which he did not claim in matters of property or civil rights.
But the commons having in their hands a stronger argument than words,
viz. the power of granting money,
the want of which only obliged the King to convene them, knew where their strength lay,
and used it accordingly,
resolving that the money bill should not precede the redress of grievances,
of which they seemed to consider this declaration as the principal.
The commons appearing determined, the King gave up the contest, revoking the declaration,
and breaking the seal with his own hands.

The conduct of the commons in this case hath procured
the general voice of our historians in their favour,
and it must be acknowledged that they acted consistently
with their duty in opposing the infringement of the constitution.
That in the present contest they acted a more manly and honourable
part than in these preceding on the like subject in 1662,
and as late as 1668, as proceeding upon sounder and more universal principles.
Yet as the King`'s apparent inclination to have the Dissenters
exempted from penal laws would have merited praise,
if it had been sincere, and attempted in a legal way,
so the opposition of the parliament would have been
entitled to the claim of greater merit,
if it had not originated with many of them in an aversion to the principles of the declaration,
(impunity to the nonconformists) as much as the grounds upon which it was published;
and if they had not laid the foundation for this contest in the various penal laws,
which, under the influence of party pique, they had undeservedly enacted and revived;
and on all occasions manifested a determined enmity
to all dissenters from the established religion;
for if they had not an aversion to the principles of the declaration,
they had now a fair opportunity of legalizing it,
by converting it into an act of parliament.^
footnote:[It is remarkable that the parliament, even yet,
seem to consider impunity to Dissenters at the greatest grievance;
for although there were far greater to complain of,
particularly the violation of public credit, in shutting up the exchequer,
to the irreparable injury of numbers,
yet after the point was carried for rescinding the declaration,
we hear nothing further of grievances.]

Yet this parliament having kept their seats from the restoration,
many of the most intemperate spirits and most rigid in their enmity to
the Dissenters had during the length of time been removed by death,
and men of more moderation and better temper chosen in their room,
whereby the house of commons had undergone a change for the better, and were now roused,
by a detection of the insidious designs of the court,
in favour of popery and arbitrary power,
to make a distinction between Protestant Dissenters and Popish Recusants,
and to endeavour to give ease to the former, without including the latter.
It is supposed the court had relied upon gaining the interest of the Presbyterians
to support their measures by the declaration of indulgence;
but that perceiving the drift thereof was, under shelter of them,
principally to favour the Roman Catholics, to whom they had the strongest aversion,
they appeared far from sanguine to accept of liberty by the dispensing power.
Alderman Love, one of the chief of that party,
and member of parliament for the city of London,
was amongst the foremost to condemn the declaration,
signifying that he had rather go without his own desired liberty,
than receive it in a way so destructive to the liberty of his country,
and the protestant interest, and that this was the sense of the main body of Dissenters.
Which, it is said, made an impression on the commons in their favour,
even upon those who for ten years together had been
oppressing them with one penal law after another:
Insomuch that they now resolved unanimously that a bill
be brought in for the relief of Protestant Dissenters.
But this conduct of the Presbyterians, while it reconciled the parliament,
exposed them to the resentment of the court,
who had reckoned upon their hearty support in a measure apparently so favourable to them,
and were greatly chagrined at their disappointment;
and the parliament having this session passed the Test Act,
whereby the Romanists were disqualified from holding any office,
the court too evidently manifested, that their generous attempts,
in favour of nonconformists,
were centered chiefly in procuring indulgences in favour of this class.
For from this time the court interest was not only
withdrawn from yielding protection to other dissenters,
but turned against them;
whereby the endeavours of the commons for their ease were frustrated,
and encouragement given to the whole train of informers,
and others (who were only waiting for the signal)
to put the penal laws in rigorous execution;
and although the Quakers had no concern in any of these political contests,
yet being subjects of these penal laws,
and continuing to maintain their testimony publicly, they still suffered most,
as most open to the iron claws of persecution,
and standing in the way of coming at the others,
of whom they wanted most to get satisfaction.
