== Chapter II.

[.chapter-synopsis]
* Persecution recommenced
* George Fox imprisoned at Worcester, together with Thomas Lower
* Brought to trial at the Sessions
* Oaths of Allegiance and Supremacy required of George Fox
* For refusing he is remanded to Prison
* Thomas Lower discharged
* And solicits his Father`'s Discharge in vain
* George Fox removed by _habeas corpus_.--By Parker`'s Contrivance remanded to Worcester
* Brought again before the Sessions
* George Fox`'s Vindication
* Clandestinely condemned in a Premunire
* Falls sick in Prison
* The King offers him a Pardon; which he is not free to accept
* Removed again by _habeas corpus_ and released
* After his Release goes down to Swarthmore to reside

For the indulgence was hardly sooner revoked, than the informers,
priests and magistrates busied themselves in stirring up fresh persecution.
A remarkable unjust prosecution of George Fox, almost immediately succeeded,
who having returned from his visit to America,
and landed near Bristol about the middle of this summer, was met there by his wife,
accompanied by her son-in-law, Thomas Lower, and two of her daughters: Her son-in-law,
John Rous, William Penn and other friends from London also met him there,
and it being the time of the fair,
many friends came to it from different parts of the nation.
By the general resort of traders of all denominations,
the meetings were much crowded at that time (as they continue to be during
the time of the fair) which occasioned his stay in that city some time;
from whence he went through Gloucestershire and Oxfordshire to London,
and after staying there a while, visiting his friends in their meetings,
and their children in their schools, he set forward with his wife and Thomas Lower,
with intention to accompany her on her way home,
and to visit his mother on her deathbed; but when they came into Worcestershire,
he signified to his wife his apprehension that a prison would be his lot there,
which filled her with sorrow.
And soon after, having had a meeting at John Halford`'s, at Armscot,
in the parish of Tredington, Henry Parker, a justice of the peace,
getting intelligence thereof, by means of a woman friend,
who being employed as nurse to a child of his, asked leave to go to the meeting;
having at that time in company with him a priest, named Rowland Hains,
upon hearing of the meeting they plotted together to break it up;
but it being the festival of sprinkling the infant,
they could not prevail upon themselves to leave the
feast until after the meeting was over.
When they came they found him and Thomas Lower in
conversation with some friends in a parlour,
and under pretence of their having had great meetings,
which might be prejudicial to the public peace, Parker,
without any just cause or legal information, took them both prisoners,
and sent them to Worcester jail.
Being thus by compulsion restrained from their purpose of
conducting George`'s wife and daughters on their way,
they were under a necessity to procure a friend to accompany them,
with whom they returned to their habitation at Swarthmore.

Being imprisoned very wrongfully,
and causelessly interrupted in their journey upon their lawful occasions,
they applied by letter to the lord lieutenant and deputy lieutenants of
the county for the interposition of their authority for their release,
laying before them the state of their case, and illegal manner of their imprisonment,
not from any meeting, but from an house where they had business;
that George Fox was on his way to visit his mother, who was desirous to see him,
not being likely to live long,
and by his imprisonment was restrained from paying this
debt of duty and affection to his aged and sick parent.
But this application was ineffectual, the power being too generally vested in those,
who were most destitute of compassion and tenderness to any who were guilty of nonconformity:
Yet Thomas Lower might have obtained his liberty by means of his brother`'s intercession,
who was one of the king`'s physicians, and had procured a letter from Henry Savil,
gentleman of the bed-chamber to lord Windsor, for his release,
if he had been willing to accept it singly;
but bearing too great a respect to his father-in-law to leave him in prison alone,
he suppressed the letter, and voluntarily continued his companion there.

On the 21st of the month called January 1673,
being the last day of the quarter sessions, they were brought to the court.
At their entrance, the justices,
as if convicted in themselves of their unjust and injurious treatment,
appeared confused and pale, and were for some time silent,
insomuch that a person in the hall asked, What! are they afraid?
Dare not the justices speak to them?
At length justice Parker made a long but very weak apology for his conduct,
purporting that he thought it a wilder course to send those two to jail,
than to put his neighbours to 200£. charge,
by putting the law against conventicles in force;
as if he was under an obligation to do the one or the other,
although he could do neither legally;
for there was no conventicle in the house when he came,
nor had he any evidence to convict them by.
The chairman, one Simpson,
proceeding to examine them concerning the occasion of their coming thither;
they gave so clear an account of themselves, and the reasons of their journey,
as obliged him to own, their account or relation was very innocent;
which as they had no evidence to contradict it, nor cause to doubt the truth thereof,
was a plain acknowledgment, that they had been causelessly imprisoned,
and had a right to their immediate release from their false imprisonment.
But as this act of justice would have been a censure
upon Parker`'s irregular exertion of his power,
they resorted to the usual sure mode of finding occasion of crimination
against George Fox from the tenderness of his conscience,
which they could not from the tenour of his conduct; for Simpson,
after whispering to Parker, addressed himself to George Fox after this manner.
Mr. Fox, you are a famous man, and all this may be true which you have said;
but that we may be better satisfied, will you take the oaths of allegiance and supremacy?
To which which George replied, I never took an oath in my life;
but I have always been true to the government; asserted his allegiance in full terms;
showed he had been twice imprisoned,
first at Derby for not taking up arms against the king;
and the second time sent up prisoner to Oliver Cromwell
under pretence of plotting to bring him in;
that they knew in their consciences the people called Quakers could not take an oath,
because Christ had forbidden it.
And as to the oath of supremacy, he said, I deny the Pope and his power,
and deny it with my heart.
While he was speaking, they cried, give him the book.
He answered, "`the book saith, swear not at all.`"
He was then ordered to be taken away; but the jailer not being hasty,
they were very urgent with him, crying, take him away, we shall have a meeting here,
the fellow loves to hear him preach.
The jailer then drawing him away, he said, "`the Lord forgive you,
who cast me into prison for obeying the doctrine of Christ.`"
After George Fox was taken away, the justices,
afraid to proceed with equal rigour against Thomas Lower,
on account of his more powerful connections, told him, he was at liberty.
Upon which he queried of them, "`Why his father-in-law might not be set at liberty,
as well as he, since they were taken together for the same pretended offence.`"
But as a proof that lawless power and not reason or equity was the rule of their conduct,
they told him they would not bear him, "`You may go about your business,
for we have nothing more to do with you, seeing you are discharged.`"

But Thomas not being easy to leave his father in prison,
without further solicitation for his release, went to the justices at their chamber,
desiring to know, "`what cause they had to detain his father,
that they had not against him; and why one should be discharged and the other not?`"
wishing them to consider,
whether this distinction in their treatment of persons in the very same
circumstances might not be looked upon as an indefensible partiality.
The justices not relishing such close reasoning, Simpson,
thinking to deter him from further remonstrances, told him, "`if he was not content,
they would tender him the oath, and send him to his father.`"
A plain evidence that it was not for a security to
government that they tendered the oath;
but in the caprice of power, at their mere will and pleasure,
to gratify private ill will in the execution of partial laws,
or laws not originally intended against a people not in being.
Lower replied, "`Ye may do that if ye will, but whether ye send me or no,
I intend to go and wait upon my father in prison,
for that is now my business in this country.`"
Justice Parker then made an apology for his conduct in the following terms,
"`Do you think, Mr. Lower, that I had no cause to send your father and you to prison,
when you had so great a meeting; insomuch that the parson of the parish complained to me,
that he had lost the greatest part of his parishioners;
so that when he comes amongst them, he hath scarcely any auditors left.`"
To this Thomas Lower returned,
"`I have heard that the priest of that parish comes so seldom to visit his flock,
but once, it may be, or twice in a year to gather in his tithes,
that it was but charity in my father to visit so forlorn and so forsaken a flock.
And therefore thou hadst no cause to send him to
prison for visiting and instructing them,
who had so little comfort from their pastor,
who comes among them only to seek for his gain from his quarter.`"^
footnote:[This priest, called Doctor Crowther, though thus regardless of his flock,
appears to have been a rigid exactor of their tithes;
of which we meet with the following instances in [.book-title]#Besse`'s Sufferings.#
In 1676 he prosecuted John Halford aforesaid, on the statute for treble damages,
for a claim of seven year tithes, worth about 5£. per annum,
who by execution at several times had taken from him goods and chattels to the
value of 158£. In 1678 William Banbury was arrested for tithes at his suit,
and committed to Worcester jail, afterward removed to London,
and committed to the Fleet prison; and the same year his mother, Mary Banbury,
was cast into the same prison at his suit, on the same account.
He prosecuted William Parr of Shipston several times.
Upon one of these prosecutions he was imprisoned above a year at Worcester,
and a judgment being obtained against him for 8£.£. he lost by distraint
four cows worth 14£.£. At another time for the like demand of 8£. he
suffered by distraint of four cows and two horses 30£.£. Crowther had
the power of holding an ecclesiastical court once in three years,
to which the said William Parr was cited for not coming to hear common prayer,
was committed to prison by writ _de excommunicato capiendo_,
and detained in prison upwards of two years and an half.]
At this the justices broke into a laughter; for Doctor Crowther, the priest spoken of,
was then sitting with them in the room, unknown to Thomas Lower,
and he had the sense to let it pass without any reply,
either of resentment or vindication.
But when Thomas Lower was gone, the justices,
highly diverting themselves at Crowther`'s expence, he was so nettled,
that he threatened to sue Thomas Lower in the Bishop`'s court, on an action of defamation;
which coming to Thomas`'s ears, he sent him word, and afterwards told him to his face,
"`that he might commence his suit as soon as he pleased; that he would answer it,
and bring his whole parish in evidence against him.`"
So the priest in conclusion thought it the wisest course to let it drop.

Some days after an _habeas corpus_ came down for removing
George Fox to the King`'s Bench bar at Westminster.
On receipt whereof the under sheriff made Thomas Lower his deputy to convey him to London,
where they arrived on the 2nd of the month called February, and appearing in court,
his case was argued, but no determination come to at that time;
he was ordered into the custody of the marshal of the King`'s Bench,
and another day appointed for hearing it.

In the meantime Parker, who had grossly injured him in his causeless imprisonment,
with persevering enmity, to prolong his imprisonment, and cloak his own illegal conduct,
had, in concert with other adversaries, dispersed a malicious report,
"`that there were many substantial men with George Fox, out of many parts of the nation,
when he was taken, and that they had a design or plot in hand;
and that Thomas Lower stayed with him in prison, long after he was set at liberty,
to carry on the design.`"
By which, and other false reports, the judges,
who seemed inclinable to set George Fox at liberty,
were prevailed upon to remand him to Worcester, only this favour was granted him,
that he might go down his own way, and at his leisure,
provided he would not fail to be there by the assizes,
which were to begin on the 2nd day of the month called April following.
He appeared accordingly at the said assizes before judge Turner,
who formerly passed sentence of premunire against him at Lancaster.
That judge was now more favourable, and seemed inclined to release him;
but Parker endeavoured to prevent it, by insinuating "`that he was a ringleader,
that many of the nation followed him, and that nobody knew what it might come to.`"
The judge, though he knew better, being willing to ease himself,
referred the matter back to the sessions again, bidding the justices terminate it there,
and not trouble the assizes any more.
So he was continued a prisoner,
but by the favour of some of the justices had the liberty of the town granted him,
and leave to lodge at a friend`'s house until the sessions.
The justices of this county appear to have been of
different sentiments and dispositions at this time,
and on this occasion; one party entering into all Parker`'s arbitrary views,
and joining him in going any length to screen his palpable abuse of power,
and manifest injustice, from meeting with deserved censure;
the other party actuated by principles of more honour and moderation,
and convinced that George Fox was very unjustly treated with this severity,
endeavoured to moderate the malicious temper of his adversaries,
and to prevent them from proceeding to extremities with him,
but were not able to dissuade them therefrom.

The time of the sessions being come, George Fox was called before the justices.
One Street being chairman of the sessions, opened his trial session.
with a speech of the like tenour with Parker`'s vain
pretences for committing him to prison,
and it is probable suggested by him,
where by magnifying and misrepresenting the circumstances of their religious meeting,
in order to infuse into the people a notion of danger to be feared therefrom,
and to give a colourable pretext for their proceedings,
he said "`That George Fox had a meeting at Tredington from all parts
of the nation to the terrifying of the king`'s subjects,
for which he had been committed to prison,
and that for the trial of his fidelity the oath had been tendered to him.`"
Then turning to George Fox, he asked him, "`since he had time to consider of it,
whether he would now take the oaths?`"
George Fox first vindicated himself from the misrepresentations of the chairman,
repeated the relation of his journey, and the cause of it,
as he had done at the former sessions,
when they could not help acknowledging his account to be clear:
That as to some being there from different parts of the nation,
they were principally of one family, and in one company, except a friend from Bristol,
who came accidentally or providentially,
as it was to him they were obliged for attending
his wife and daughters on their way home,
when Thomas Lower and he were intercepted by Parker.
That it was not true that there were persons from all parts of the nation,
nor that their meeting was to the terrifying of the king`'s subjects,
desiring them to produce one evidence, who could say, they were terrified thereby:
That as to the oaths they knew he could not take them,
and they knew it was from a conscientious scruple
of violating Christ`'s command he could not.
That he could honestly declare his allegiance to the king
in clear and plain terms in any assertion short of an oath.
But the most reasonable pleas find little entrance through the veil of prejudice,
to avert predetermined resolutions.
For upon his refusal of the oaths they proceeded
in their preconcerted plan of trial to condemnation:
An indictment, ready drawn up, was read to him, and the chairman asking him,
if he was guilty?
He replied, "`No, for the indictment is a bundle of lies.`"
The indictment was delivered to the jury,
who under the instructions of the chairman found the bill against him,
which he determined to traverse,
and then was required to put in bail until the next sessions,
but he refused to be bound any otherwise than by his promise to appear,
if the Lord gave him health and strength, and he were at liberty.

So he was sent back to prison;
but by the interposition of the more moderate justices (who
had manifested a favourable disposition in the court,
endeavouring to prevent the tender of the oath and the indictment) in about two hours
after he had liberty given him to go at large until the next quarter sessions.

The yearly meeting in London falling out in the intermediate time, he attended it.
And at the instance of some of his friends he appeared
before some of the justices of the King`'s Bench,
and delivered to them a declaration of his fidelity to the king,
and denial of the Pope`'s supremacy and power,
as what he could promise in lieu of the oaths;
but as his case was under cognizance of the quarter sessions at Worcester,
the judges were unwilling to meddle with it, not being regularly before them.

Wherefore when the yearly meeting was over he returned to Worcester,
and appeared at the succeeding quarter sessions to traverse the indictment;
but when he proceeded to show the errors, which were sufficient to quash it,
he was stopped, the oath required of him again, and upon his refusal to take it,
the jury found him guilty.
And an admonition of the consequence of a premunire being given him in court,
this was clandestinely recorded for the sentence thereof, in his absence,
after he was sent out of court,
to evade the reproach and censure due to their illegal proceedings,
as several of the justices, and the generality of the people condemned them: Nay,
his persecutors themselves seemed at last affected with uneasy
sensations of compunction for the wrong they had done him,
and wished he had never come thither to trouble them,
upon which George Fox observed they had brought the trouble upon themselves:
but they had gone too far to make a handsome retreat,
and therefore thought it less dishonourable to persevere in the wrong,
than to right the injured, by owning and reversing the wrong.

Under the hard sentence of premunire he was remanded to prison,
where he was soon after seized with a dangerous fit of sickness,
which reduced him to great weakness of body, so that his recovery seemed doubtful.
Upon this account application was made to justice Parker,
for liberty for him to be removed out of the jail into the city,
who after much importunity wrote the following note to the jailer,

[.embedded-content-document.letter]
--

[.salutation]
Mr. Harris,

I have been much importuned by some friends of George Fox to write to you:
I am informed by them that he is in a very weak condition, and very much indisposed.
What lawful favour you can do, for the benefit of air for his health, pray show him.
I suppose next term they will make application to the king, I am, Sir,

[.signed-section-closing]
Your loving friend,

[.signed-section-signature]
Henry Parker

--

George Fox`'s wife finding him fixed in prison under the sentence of premunire,
came up from the north to attend him, and also to solicit his discharge,
and after staying with him three or four months,
and seeing no discharge like to be obtained for him,
she took her journey to London to solicit the king in person, was kindly received by him,
and referred to the Lord Keeper, who told her,
the king could not release her husband any otherwise than by a pardon,
which the king would readily have granted;
but George Fox was not easy to obtain his liberty in that method;
for knowing his own innocence,
he thought the acceptance of a pardon would be a tacit acknowledgement of guilt;
wherefore he declared, he had rather lie in prison all his days,
than come out in any way dishonourable to the truth he made profession of.
He rather chose to have the validity of his indictment tried before the judges;
and accordingly procured an _habeas corpus_^
footnote:[The _habeas corpus_ being readily procured and sent down to Worcester,
his adversaries,
as conscious of having exerted a power which would not stand the test of examination,
were reluctant to comply therewith, and endeavoured to evade it,
pretending he was premunired, and of consequence deprived of the benefit of the law;
whereupon a second order was procured and sent down,
and then he was brought up by the sheriff.]
to remove him once more to the King`'s Bench bar, where appearing before the four judges,
Counsellor Thomas Corbet was employed to plead for him,
who acquitted himself with great honour.
He advanced a new plea,
"`that by law they could not imprison any man upon
a premunire,`" upon the hearing this unexpected plea,
the judges required time to consult their books and the statutes,
and postponed the hearing until next day.^
footnote:[Sewel, p. 504.]
When finding Corbet`'s opinion was well founded, they,
it is probable for fear of ill consequences, chose to omit further notice of the plea,
and proceeded to examine the indictment,
in which the errors appeared so many and so gross,
that the judges were unanimous in opinion, that the indictment was quashed and void,
and that George Fox ought to be set at liberty.
And as the oaths were tendered to sundry great men that day in court,
there were not wanting some adversaries to George Fox,
who moved the judges that the oaths might be tendered to him again,
insinuating he was a dangerous man to be at liberty.
But that upright and conscientious judge Sir Matthew
Hale at this time presided at the King`'s Bench,
who was too honest to lend an ear to such suggestions,
saying he had indeed heard some such reports of George Fox,
but he had also heard more good reports of him.
So after a full hearing before the four judges he was discharged by proclamation,
after he had suffered an unjust imprisonment of a year and almost two months,
and thus obtained his liberty in an honourable way,
without impeachment (by implication) of his innocence.
And Corbet his advocate obtained great credit by his manner of pleading his cause;
the lawyers alledging he had brought that to light which had not been remarked before.
And after the trial one of the judges complimented him upon it, saying,
you have obtained a great deal of honour,
by your way of pleading George Fox`'s cause in court.

After his release he went to London,
and thence to Kingston for the recovery of his health,
and stayed in and about the city until the yearly meeting,
where he had the opportunity of seeing friends from most parts of the nation,
and of edifying and being edified amongst them.
When the meeting was over, having taken leave of his friends,
he went down with his wife to her habitation at Swarthmore, by coach,
not being able to ride on horseback, where he continued for a considerable time,
without going much abroad, in order to recruit his strength;
the indisposition he contracted in his late imprisonment having reduced him to
a state of great weakness from which he was some time in recovering.
