== Chapter III.

[.chapter-synopsis]
* Persecution renewed
* Ineffectual application to the Judges for relief
* The Parliament jealous of the Court
* Bishops promote persecution
* William Penn publishes England`'s present Interest
* Robert Barclay`'s Apology published
* Animadversions on Mosheim`'s Reflections upon it
* Sufferings of William Hall
* Of Friends of Namptwich
* Sufferings and Death of William Bailey

The revocation of the indulgence and the displeasure of the court against the dissenters,
let loose the whole tribe of informers,
and gave fresh spirit to the persecuting magistrates.
Persecutions now began to be renewed against the people
called Quakers in all the various modes of distress;
and by all the variety of penal laws at the capricious will of every justice;
they continued to be prosecuted upon the statute
of premunire of Jac I. for refusing to swear;^
footnote:[On the 21st of the month called July, 1675, John Anderdon, of Somersetshire,
for refusing to take the oath of allegiance had sentence
of premunire passed upon him by Judge Rainsford,
etc. etc.]
upon the obsolete statute of 20£. a month for absence
from the parish church (so called) and the said penalty,
or two-thirds of a person`'s estate seized by Exchequer process;^
footnote:[Thomas Bennet and Thomas Tyler and others
were imprisoned for absence from the national worship,
where they lay eight months.
The said Thomas Bennet had also two-thirds of his estate
seized by exchequer process by the statute of 23 Eliz.
against popish recusants.
{footnote-paragraph-split}
Several of the people called Quakers in Herefordshire
being prosecuted in the Exchequer on old statutes against popish recusants,
suffered much by distresses made for pretended forfeitures,
of the two-thirds of the yearly value of their estates.
{footnote-paragraph-split}
Edmund Peckover of Fakenham, Norfolk,
was prosecuted on the statute for 20£. a month,
of which his son gave the following account.
"`Our adversaries are wholly bent to ruin us;
they have distrained for 120£.£. for the king`'s use, as they say,
upon the statute of 20£. a month,
and have taken above forty pieces of serges and stuff, some whole and some cut;
also seventeen pieces of linen, callicoes and Scotch cloth;
but would not let us measure any, so that we know not what they amount to:
We have shut up shop to secure our creditors,
and if there be no likelihood of a stop to their proceedings,
we intend to keep open shop no more; but to pay where it is owing.`"
{footnote-paragraph-split}
George Gates of Buntingford, Hertfordshire,
was arrested on the statute of 20£. a month, for absence from the national worship,
and committed to prison, where he continued until he died on the 5th of the 3rd month,
O+++.+++ S. called May, 1680.
{footnote-paragraph-split}
John Taylor of York, a man well beloved of his neighbours,
was committed to prison, being prosecuted on the aforesaid statute of 20£. a month,
on the information of John Hemmingway, by one Jonas Rigdon, attorney,
who got much discredit by it.
The informer publicly declared his repentance,
and said he could not rest day or night for trouble at what he had done.
]
but the prosecutions by the priests for their tithes were enormous and unceasing,
taking from them frequently far more than their pretended due,
prosecuting them in the ecclesiastical courts to excommunication,
and procuring writs de excommunicato capiendo to be issued, to throw them into prison.
For keeping up their religious meetings they were
still prey to idle and profligate informers;
men divested of every principle of humanity or common honesty,
delighting in cruelty and living by plunder; made no conscience,
were restrained within no bounds of reason or moderation
in the spoil they made of their goods;
and what rendered their sufferings the more severe,
they had no grounds to hope for redress whilst these plunderers
were encouraged and urged on by their superiors,
whose duty it was to protect the subjects in the unmolested possession of that property,
which their honest industry had earned.

Under the heavy presser of their grievous sufferings,
application was made to the judges (before they went their several circuits)
for their compassionate attention to the hard cases of several of the sufferers,
and to interpose their authority for their relief, in the following address.

[.embedded-content-document.address]
--

[.letter-heading]
To the King`'s justices appointed for the several circuits throughout England.

Many of our friends called Quakers being continued prisoners,
many prosecuted to great spoil by informers, and on qui-tam writs,
and by presentments and indictments for 20£. per mensem,
in divers counties through England,
only on the account of religion and tender conscience towards Almighty God,
we esteem it our duty to remind you of their suffering condition,
as we have done from time to time;
humbly entreating you in the circuits to inquire into the several causes of their commitments,
and other sufferings, which they lie under,
and to extend what favour you can for their ease and relief.
Praying the Almighty to preserve and direct you.

--

But little redress could be obtained from the judges at this time,
nor it is surprising it could not, if the assertion of one of our historians be true,^
footnote:[[.book-title]#Neale, v. 2,# p. 697.]
that the papists being excluded from places of trust,
the court had no tenderness for non-conformists;
the judges therefore had orders to quicken the execution of the laws against them.
The high-churchmen in their pulpits were encouraged to open
their mouths as loudly as possible against them.
One in his sermon before the house of commons told them,
that the non-conformists ought not to be tolerated, but to be cured by vengeance;
the king issued out a proclamation for putting the penal laws in full execution,
which had its effect.

The parliament, from the Restoration to their last sessions,
had manifested the warmest zeal for the king and church of England,
and from time to time had gratified the former by
complying with all his demands for money,
and the latter by passing one severe law after another against non-conformists;
whereby there appeared a great cordiality to subsist between the king, the parliament,
and the bishops; but now from their discovery of the bad measures,
and their apprehensions of worse designs of the court,
had conceived an incurable jealousy of the king, his brother and his ministers;
who in return entertained a reciprocal aversion to the meeting of the parliament,
as they now began to turn the tide of their zeal against the papists singly;
and were desirous to protect the other dissenters,
as confederates in the support of the protestant cause:
Upon this account the king was very unwilling to meet the parliament,
but his necessities obliged him to convene them;
and presently after their meeting they presented
an address desiring the king to banish all papists,
who were not housekeepers, or menial servants to peers, ten miles from London,
and to appoint a fast for the calamities of the nation.
Misunderstandings and jealousies on both sides by these means gathering strength,
divided the people of all ranks more than ever,
and added fuel to the intemperate warmth of party rage,
which had so long distracted the nation.
No sooner had the parliament undertaken the protection of the dissenters,
and the persecution of the papists,
than the court to thwart their measures promoted the persecution of the former:
The king commanded an order to be made public,
"`that effectual care be taken for the suppressing conventicles;
and whereas divers pretend old licenses for preaching,
and would support themselves by that pretence,
the king declares that long since all his licenses were recalled,
and that no conventicle hath any authority, allowance or commission from him.`"

The bishops also continued their exertions to promote the execution
of the penal laws against them in common with the papists.
Sheldon wrote circular letters to the bishops of
his province to cause inquiry to be made,
1st,
What number of persons by common estimation reside
within the respective parishes under their care?
2ndly, What number of popish recreants, or persons suspected of recusancy?
3rdly, What number of other dissenters of what sect soever,
which either obstinately refuse,
or wholly absent themselves from the communion of the church,
at such times as by law they are required?

So that no change in the temper of the times brought as yet any
durable or effectual relief to the sufferings of this society:
they rather grew heavier and more aggravated during the remainder of this reign,
to the end thereof.

Many of them continuing to be imprisoned for refusing the oath of allegiance,
William Penn this year wrote his Treatise of Oaths,
wherein he shows their reasons for not swearing at all,
and confirms them by numerous authorities.

And in consideration of the unhappy divisions and animosities prevailing in the nation,
he also wrote this year, an excellent treatise,
under the entitled title of England`'s Present Interest Considered, wherein,
to allay the heats of contending parties,
he shows the consistency of a general liberty of conscience with the peace of the kingdom:
A work wherein the liberal charity of real Christianity and the
candid spirit of genuine patriotism are eminently conspicuous.
The introduction to which treatise is addressed to the consideration of our superiors,
and proceeds,

[.embedded-content-document.treatise]
--

There is no law of nature or of grace that forbids men to deal honestly and plainly
with the greatest in matters of importance to their present and future good;
nor do worthy minds think less favourably of honest and humble monitors.
Oftentimes princes are deceived, and kingdoms prejudiced for want of them.
Certain it is that there are few kingdoms in the world more divided within themselves,
and whose religious interests lie more seemingly cross to accommodation,
than that we live in; which renders the magistrate`'s taste hard,
and occasions him a difficulty almost invincible.

Your endeavours for an uniformity have been numerous;
your acts to enforce it multiplied; but the consequence, whether you intended it or no,
hath been the spoiling of several thousands of the freeborn
people of this kingdom of their unforfeited rights.
Persons have been flung into jails; gates and trunks broken open; goods distrained,
until a stool hath not been left to sit down on; flocks of cattle drawn off;
whole barns of corn seized, thrashed and carried away;
parents left without their children; children without their parents,
and both without subsistence.

But that which aggravates the cruelty, is,
the widow`'s mite hath not escaped their hands;
they have made her cow the forfeiture of her conscience;
not leaving her a bed to lie on nor a blanket to cover her.
And what is yet more barbarous, and helps to make up this tragedy,
the poor orphan`'s milk, boiling over the fire, hath been flung to the dogs,
and the skillet made part of the prize:
So that had not nature in neighbours been stronger than cruelty in such informers,
to open her bowels for their relief and subsistence, they must have utterly perished.

Nor can these inhuman instruments plead conscience, or duty to those laws,
who have abundantly transcended the severest clause in them;
for to see the imprisoned hath been crime enough for a jail; and to visit the sick,
to make a conventicle; fining and distraining for preaching and being at a meeting,
where there hath been neither,
and 40£. for 20£. hath been a moderate advance with some of them.

Others thinking this way too tedious and inadequate to
the purpose of a speedy stripping them of their substance,
alter the question from, have you met?
to will you swear?
So that it hath been, in some places, esteemed a sufficient reason for a premunire,
that men have estates to lose;
although they bear as true allegiance to government as their adversaries;
and only through tenderness of conscience refuse the oath.

Finding then by sad experience, and a long tract of time,
that the very remedies applied to cure dissension increase it;
and that the more vigorously an uniformity is coercively prosecuted,
the wider breaches grow, and parties become more inflamed;
that the compulsory measures have always procured to the
actors the judgments of God and the hatred of men;
to the sufferers misery; to their country, decay of people and trade;
and to their own consciences, extreme guilt;
I hope to be excused in offering my mite for the increase of your true honour,
and the felicity of my dear country, by proposing the following question,
and the solution thereof.

[.old-style]
=== Question.

What is most fit, easy and safe, in this present juncture of affairs, for composing,
at least quieting, differences; for allaying the heat of contrary interests,
and making them subservient to the interests of government,
and consistent with the prosperity of the kingdom?

[.old-style]
=== The Answer.

[.numbered-group]
====

[.numbered]
_1st,_ An inviolable and impartial maintenance of English rights.

[.numbered]
_2nd,_ Our superiors governing themselves upon a balance, as near as may be,
towards the several religious interests.

[.numbered]
_3rd,_ A sincere promotion of general and practical religion.

====

--

These propositions are the groundwork of this treatise,
which the author proceeds to establish by sound reasoning,
and a multitude of authorities: but reasons of state, however unsound, and unjust,
were more forcible at this time than the soundest reasoning which
thwarted the pre-concerted and pre-determined measures of government,
persecution continued, and civil dissensions daily acquired new force.

While William Penn was thus employed in pointing out the true interests of the nation,
Robert Barclay was appropriating his labours to the service of truth,
and of the society of which he was a member;
it was in this year he published his Apology for the true Christian Divinity,
in being an explanation and vindication of the principles
and doctrines of the people called Quakers;
to which he prefixed an epistle to King Charles II. remarkable
for the plain dealing and honest simplicity of address,
conscientiously in use among this people at that time;
free from the servile adulation too generally used
towards princes from those they converse with,
this epistle presents him with plain truth and pertinent reflections,
worthy of his observation, to which however, he seems to have paid less regard,
than to the pernicious plans and counsels of the court parasites.

The people in whose behalf this apology was written
had been from the beginning grossly abused,
and their principles misconstrued and misrepresented
by the priests and teachers of most denominations,
both from the pulpit and the press;
the consideration whereof excited him to undertake and publish
this discourse as an essay to prevent future controversy;
to strip Quakerism of the disguise in which enmity or ignorance had dressed it up;
and present it to the world in its genuine shape and complexion.
A work, which with unprejudiced readers answered the end of its publication,
and gained the author the approbation of the ingenuous in general,
for presenting the world with a rational and consistent
system of the christian religion according to the scriptures,
and doctrines of the primitive church therein recorded;
and although objections may have been advanced against some particular parts,
yet as a system it remains unrefuted to this day.

Yet Mosheim, who in his whole account of the Quakers,
treats them without mercy or charity,
as if his business as an historian was only to revive every obsolete and invidious calumny,
but not one testimony in their favour;
as if he was mortified to find that any one amongst
them could defend their cause so well,
very disingenuously endeavours to depreciate this work,
and to asperse the author unjustly, by ascribing to him a duplicity,
which (by the testimony of those who knew him well) was most foreign to his real character;
and to insinuate that he had given a fallacious account of the Quakers principles,
as if they were in reality not those which he had delivered to the world as such.
For he insinuates that we are not to "`learn the true doctrine and sentiments
of Quakerism from his apology for the true christian divinity;^
footnote:[His history would have been more instructive,
if he had informed us from what other source we might draw
a more satisfactory knowledge of their doctrines and sentiments;
I am certain it is not from Doctor Mosheim`'s account of them.]
this ingenious man appeared as a patron and defender of Quakerism,
and not a professed teacher and expounder of its various doctrines;
and he interpreted and modified the opinions of his
sect after the manner of a champion or advocate,
who undertakes the defence of an odious cause.^
footnote:[This extraordinary paragraph wants explanation, to me at least;
for I can investigate no meaning in it,
which I can reconcile to truth or reality of fact:
That Robert Barclay did really appear as an expounder,
and an honest expounder of this people`'s doctrines,
I believe very few who have read his Apology can entertain a doubt;
that he modified the opinions of his sect after a manner inconsistent with truth,
implied; but not admitted or proved; but admitting he was an advocate of his own cause,
and that of his fellow members of a society (not odious,
unless innocence and rigid virtue deserve that epithet) he is still as
defensible in standing forth a champion in the defence of the injured,
as those who unprovoked appear as champions against them,
to render them on groundless accusations odious to the world.]
He observes an entire silence in relation to the fundamental principles of Christianity,
concerning which it is of great consequence to know the real opinions of the Quakers,
and thus he exhibits a system of Theology that is evidently lame and imperfect.^
footnote:[If this Doctor also had not observed an entire silence,
what in particular these fundamental principles of Christianity are which he hints at,
which those tenets Robert Bar clay touches in a slight and superficial manner,
etc. his meaning might have been better understood,
and the truth or error more certainly owned or refuted,
but as he hath thought proper to veil his subject in mystery,
I own myself unequal to the talk of unriddling his enigmatic assertions.]
It is observable that Barclay touches in a slight, superficial and hasty manner,
some tenets, which when amply explained, exposed the Quakers to severe censures;
and in this he discovers plainly the weakness of his cause.
Lastly, to omit many other observations that might be made here,
this writer employs the greatest dexterity and art in softening
and modifying those invidious doctrines which he cannot conceal,
and dare not disavow;
for which purpose he carefully avoids all those phrases
and terms that are made use of by the Quakers,
and are peculiar to their sect, and expresses their tenets in ordinary language,
in terms of a vague and indefinite nature,
and in a style that casts a sort of mask over their natural aspect.^
footnote:[I dare appeal to every dispassionate reader of Robert Barclay,
whether in any part of his Apology he hath made use
of terms of a more vague and indefinite nature,
than these very strictures upon him are couched in.]
At this rate the most enormous errors may be held with impunity;
for there is no doctrine, however absurd,
to which a plausible air may not be given by following the insidious method of Barclay;
and it is well known that even the doctrine of Spinosa was, with a like artifice,
dressed out and disguised by some of his disciples.`"

Here again we have a specimen of Mosheim`'s dogmatical talent,
wherein the want of candour, of charity or decency, is too apparent.
What could more plainly discover the _aerugo mera,_ the malice and prejudice,
he had imbibed against a people concerning whom he was ignorant,
or knew only by the pictures or caricatures drawn by their adversaries,
than to indulge his spleen so far,
as to compare Robert Barclay to the disciples of Spinosa.
The comparison is odious; and it is to be feared,
if he could have thought of one more odious, he would have adopted it.
For it must be manifest to every person,
who hath considered the wide difference of their sentiments,
that there is no more affinity between them,
than the site of the arctic and antarctic poles.
After all, what do we find in these remarks but mere declamation without argument;
opinion without foundation, and assertion without proof?
And as a balance against this doctor`'s opinion,
we can produce the opinions of other writers,
not a whit inferior in soundness of judgment, in mental abilities, or in literary fame;
and much superior, in my opinion, in justice and liberality of sentiment.

[quote, Norris, Treatise of Divine Light Tract 2, p. 32]
____
I cannot think Quakerism inconsiderable,
as the principles of it are laid down and managed by Mr. Barclay.
That great and general contempt they lie under does not hinder me from thinking the
sect of Quakers to be far the most considerable of any that divide from the church,
in case the Quakerism that is generally held be the same with that
which Mr. Barclay has delivered to the world as such;
whom I take to be so great a man,
that I profess freely I had rather engage against an hundred Bellarmins,
Hardings and Stapletons, than with one Barclay.
____

[quote, French Encyclopedie, word Quaker]
____
_Je n`'ai point de honte d`'avouer que j`'ai lu avec un plaisir singulier,
L`'Apologie du Quakerisme par Robert Barclay: il m`'a convincu que c`'est tout calcule,
le system le plus raisonable, et le plus parfait qu`'on ait encore imagine._

I am not ashamed to own that I have read Robert Barclay`'s Apology
for Quakerism over and over again with singular satisfaction:
And I am convinced that, taken altogether,
it is the most reasonable and most perfect system, which hath ever been conceived.
____

[quote, Cato's Letters Vol. 4. p.226]
____
I am not ashamed to own that I have with great pleasure
read over Mr. Barclay`'s Apology for Quakerism,
and do really think it the most masterly,
charitable and reasonable system that I have ever seen:
It solves the numerous difficulties raised by other sects,
and by turns thrown at one another,
and shows all parts of scripture to be uniform and consistent.`"
____

In the course of this year William Hall, of Congleton in Cheshire,
being fined 20£. for a meeting at his house,
had his dwelling house broken open and two cart loads of goods carried
away worth 40£. Besides which they took away a mare of his,
which mare after some time came home again:
Upon which he went with two of his neighbours to the chief magistrate of the place,
and gave him information of her return, and what field she was in.
Notwithstanding this they caused him to be arraigned for felony,
on an indictment for stealing the mare: But he was acquitted upon his trial,
this malicious attempt to commit murder by law,
being too barefaced to prevail upon any judge or jury to bring him in guilty.

About the same time cattle and goods to the value of 100£.
were taken from sundry persons in and about Namptwich:
From Randal Elliot they took the bed he lay on, and even the dung hill in his yard.
When some of the sufferers on an appeal were acquitted by the jury,
the justices would not accept their verdict,
but at the next sessions gave treble costs against the appellants.
The chief informer was one called John Widdobury of Hanklow, Esq;
who being in debted 40£. upon bond to Thomas Brassley, a member of that meeting,
upon his demand of payment, was incensed against him,
and thus vented his wrath upon his friends.
He also got an old excommunication revived against Thomas Brassley,
and sent him to prison, threatening to send his wife after him, for asking for his own.

This year William Bailey died at sea, in his voyage from the West Indies.
He had been a teacher among the baptists at Pool in Dorsetshire,
where he was convinced by the ministry of George Fox in 1655,
and entered into society with the people called Quakers,
amongst whom he became a zealous preacher,
and travelled abroad in the exercise of his ministerial gift,
to bring others to the truth he had been convinced and experienced the advantage of.
In which religious exercise of love to his fellow citizens
it was his lot to participate in the sufferings of his brethren,
in frequent imprisonments,
both during the time of the commonwealth and after the restoration.
First, he was one of the number of those, who, by an order of the justices in Devonshire,
in 1656, (before taken notice of in its place) were taken up,
in the progress of their religious visits, for vagrants, and committed to Exeter jail,
at the assizes fined forty marks apiece for not putting off their hats,
and remanded to prison until payment.
Again in 1657 he was imprisoned in Hampshire, by a mittimus founded in falsehood,
alledging he and others were charged with several misdemeanours;
whereas nobody had accused them of any:
At the next assizes they were sent to the house of correction,
and detained there fourteen weeks,
until they were discharged by an order of a committee of parliament.

In 1662 he and five others standing quietly in the
street near the Bull and Mouth meeting house in London,
were taken by soldiers and carried before Richard Brown,
who with his accustomed rudeness ordered their hats to be pulled off with violence,
struck William Bailey several blows with his fist,
and when William`'s wife reproved him for abusing her husband, he struck her also,
and threw her down on the ground;
whereupon William cautioned him to beware of abusing her, she being with child;
he nevertheless repeated his abuse to her in like manner,
and then ordered his man and other rude fellows to take William to Newgate,
in mere wantonness of office,
committing him to prison without the least shadow
of legal cause or accusation against him.
In the beginning of the year 1663 he was again taken at a meeting at King`'s Langley,
and sent to Hertford jail, and at the quarter sessions,
for refusing to take the oath of allegiance, was recommitted,
and continued prisoner some years after.
In 1670 he was again committed to Newgate on the following occasion.
In the time of the meeting at Grace Church-street,
a second attempt was made to bring a priest to officiate there;
who coming from an adjacent alehouse, guarded by soldiers,
as they came toward the meeting-house, slipped away into the street;
the sergeant pursued him, and prevailed with him to return, which he did,
with a double guard to the door; but his heart failing him, he turned away a second time,
with the derision of the people.
William Bailey was then preaching,
whom the soldiers took and carried before the Lord Mayor,
who committed him to Newgate for abusing the priest and disturbing him in his office,
though he had not spoken a word to the priest,
nor had the priest attempted to officiate at all, but made his retreat as aforesaid.
He was brought to trial at Hicks`'s-hall at the same session with Penn and Mead;
and with the other prisoners was fined in.
31£. 13s. 4d. for a pretended charge of divers evil
carriages and contempt in words and deeds,
by them severally committed in and towards the court;
and the court gave further judgment, that he should pay a second fine of twenty marks,
as being convicted of several trespasses and contempt,
and to be committed to prison until he should pay his fines.
And besides his frequent imprisonments he suffered much corporal abuse by blows,
by being thrown down and dragged along the ground by the hair of his head;
his mouth and jaws attempted to be rent asunder,
and otherwise abused until the ground where he lay was stained with his blood;
trampled upon by an heavy corpulent persecutor,
who after he had partly satiated his spite by his endeavours to deprive him of breath,
committed him to a filthy jail, a poor place for his cure.
John Crook gives him this character, "`that he was bold and zealous in his preaching,
being willing to improve his time, as if he had known he had no long time to live,
and he was as valiant in suffering for his testimony, when called thereunto.`"

He had for some time followed a seafaring life for the maintenance of his family,
and was instrumental by his ministerial labours to convince and
confirm in the truth many inhabitants of distant countries,
being concerned to propagate righteousness, wherever an opportunity presented itself.
In this his last voyage, on his way from Barbados, he was visited with a disease,
which terminated his existence in this life.

When he perceived the approach of his dissolution,
addressing himself to the master of the vessel, he said,
"`shall I lay down my head in peace upon the waters?
Well, God is the God of the whole universe; and though my body sink,
I shall swim a top of the waters.`"
Afterwards,
under the comfortable sense of divine support bearing him up in this trying scene,
he said, "`the creating word of the Lord endures forever.`"
He took several that were about him by the hand, exhorting them to "`fear the Lord,
and then they need not fear death: Death, said he, is nothing in itself,
for the sting of death is sin.
Tell the friends in London, who would have been glad to see my face,
I go to my father and their father, to my God and their God.
Remember my love to my dear wife; she will be a sorrowful widow;
but let her not mourn too much, for it is well with me.`"^
footnote:[He married Mary Fisher, of whom an account hath been given in this work,
of her being the first of this people who in company with Ann Austin, visited Boston;
and afterwards travelled to Adrianople to visit the Turkish emperor,
by whom she was well received.
She seems to have been a woman of good sense,
and being much affected with the melancholy event of her husband`'s removal,
she expressed her affection to his memory, in an excellent testimony to his worth.
Sewel.]
Then having given the master some instructions about his outward affairs,
he expressed that as to his wife and children, he had left them no portions;
but had endeavoured to make God their father.`"
Then taking his leave of the company, he said, "`I cannot see one of you,
but wish you all well.`"
And after more sensible observations, expressive of the serenity of his mind,
he quietly departed this life on board the Samuel of London, in the latitude of 46°.
