== Chapter IV.

[.chapter-synopsis]
* Public Affairs
* Duke of Buckingham`'s Speech in favour of Dissenters
* Prosecutions on the Conventicle Act subside; but not for ecclesiastical Demands
* Case of Robert Cooper
* Informers generally poor
* Violent proceedings in Herefordshire

The Parliament, upon their being convened this year,
continued to discover that their jealousy of the king, his counsellors and partisans,
was in no wise cured or decreased; they drew up a new bill against the growth of popery,
and the persons of popish priests: they presented addresses against Lauderdale;
moved an accusation against Danby;
and by all their proceedings manifested they were quite out of humour with the court.
The courtiers, to make reprisals, brought a test act into the house of peers,
which if it had passed into a law would have been a new
source of more general sufferings to the Quakers,
extending the oath prescribed by the five-mile act, to be taken by dissenting ministers,
not only to the members of both houses, and all public officers,
but to the electors of parliament men.
It was no wonder that a bill so universally affecting the privileges
of the people and the parliament should meet with great opposition:
It is said to have been warmly debated for seventeen days,
and that the heats occasioned thereby, and by other matters, were so violent,
that the king suddenly prorogued the parliament, and so the bill was dropped.

The parliament upon reassembling,
being jealous of the increase of the number and power of the papists,
began now more clearly to see the necessity of a coalition with the dissenting protestants,
though it is said the high church bishops were inflexibly determined against it.
The Duke of Buckingham, who was now detached from the court,
introduced a bill for granting an indulgence to protestant dissenters,
with a speech in favour thereof, wherein with strength of reasoning and sound argument,
he evinces the reasonableness of this proposed indulgence,

[.embedded-content-document]
--

My lords, [says he,] there is a thing called liberty,
which (whatsoever some men may think) is that the people of England are fondest of;
it is that they will never part with,
and it is that his majesty in his speech hath promised to take particular care of.
This in my opinion can never be done without giving
an indulgence to all protestant dissenters.
It is certainly an uneasy kind of life to any man, that hath either christian charity,
humanity or good nature, to see his fellow subjects daily abused,
divested of their liberty and birthrights,
and miserably thrown out of their possessions and freeholds,
only because they cannot agree with others in some opinions and niceties of religion,
which their consciences will not give them leave to consent to, and which,
even by the confession of those who would impose them,
are no ways necessary to salvation.

But besides this, and all that may be said upon it,
in order to the improvement of our trade, and the wealth and greatness of the nation,
there is methinks in the notion of persecution a very gross mistake,
both as to point of government, and the point of religion;
there is so as to point of government,
because it makes a man`'s safety depend upon the wrong place, not upon the governors,
or a man`'s living well towards the civil government established by law,
but upon his being transported with zeal for every opinion, that is held by those,
that have power in the church that is in fashion.
And I conceive it is a mistake in religion,
because it is against the express doctrine and example of Jesus Christ.
Nay, as to our protestant religion, there is something in it yet worse,
for we protestants maintain that none of those opinions
about which christians differ are infallible,
and therefore in us it is somewhat an inexcusable conception,
that men ought to be deprived of their inheritance,
and all certain conveniences and advantages of life,
because they will not agree with us in our uncertain opinions of religion.

--

Moving then for leave to bring in the bill, it was granted;
but a quarrel reviving between the two houses, occasioned an hasty prorogation,
whereby this bill with some others was lost.

In the latter part of this year one Matthew Hyde,
a person who had been very troublesome in the meetings of the people called Quakers,
by opposing their ministers in their testimonies, and disturbing them in their worship,
was taken sick; and apprehending his death approaching,
was seized with great remorse of conscience for what he had done;
so that he could not be easy, until he had sent for some of that people,
particularly George Whitehead,
to whom he expressed great sorrow for the wrong he had done them,
acknowledged them to be the children of God,
earnestly begged mercy of the Lord for his wilful opposition to known truth,
in gain saying them; and died very penitent.

In the city of London prosecutions on the conventicle
act seem to have subsided during this year;
but the distresses and prosecutions for
ecclesiastical demands were numerous, and many of them exorbitant;
for although the prosecutions upon other accounts seem at times to have been
relaxed through the lassitude of the magistrates in imprisoning and punishing,
and other causes;
yet the rigorous enforcing of the ecclesiastical laws was rarely or never suspended;
self-interest and antipathy to a people whose principles
and doctrine struck at the root of priest craft,
and at mercenary ministers,
excited the priesthood incessantly to the execution of the severest laws in their favour.
The number plundered, excommunicated, imprisoned,
and of those who laid down their lives in prison, in consequence of these prosecutions,
is too large to recite particularly;
every year from the time of the Quakers being known as a people to this period,
and long after, furnish abundant instances of disastrous sufferings on one hand,
and prosecutions disgraceful to Christianity, and the church, so called, on the other.

Robert Cooper of Cheshunt, Hertfordshire,
was this year imprisoned at the suit of Robert Winchestly, priest, a prosecutor so rigid,
that he gave special orders to the jailer to keep him close,
and not let him go into the town for any refreshment: To some friends pleading for him,
that he was a poor man, had a wife and many children, this priest returned this answer,
"`if his children starve it is none of my concern: He shall lie there and rot:
I will have no more mercy on him than on a thief; if the law would hang him, I would:
Tithe is my due, and I will have it.`"

Priests of this insensible cast were a reproach to the order;
and yet it seems as if at this time much the greater number were of this cast:
The clergy began now to be distinguished into two classes,
which afterwards gave rise to the denominations of high church and low church:
These of the former class were rigid sticklers for uniformity,
for reverence to the church, that is to themselves;
for the indignity of their own indelible character;
for unlimited submission to kingly power; and for the divine right of tithes:
In the pulpit nonconformity was more the subject of their invectives than vice;
and a churchman of loose morals, in their view,
seemed a better man than the most virtuous dissenter.
They promoted the enacting penal laws, and the severe execution of them,
to the utmost of their power; to the church of Rome,
through which they derived their pretended uninterrupted succession from the apostles,
and to the relics of which they were obliged for the possession of their power and emoluments,
they bore much more good will than to those dissenters
whose principles were adverse to both.
The priests of this class were now the more numerous by far;
church preference lying on their side,
and their doctrines being most fashionable at this time.

But there were others of this order, although the fewer in number, of a different spirit;
these went under the denomination of low church men,
being more disposed to moderate measures toward the dissenters;
more rational in their principles, and less assuming in their claims.

Although the penal laws were suffered at present to lie dormant in London,
yet in several parts of the nation they were enforced with rigorous severity,
by the arbitrary proceedings of some inveterate magistrates.
In Norwich, Thomas Wilson, a very poor man,
who by hard labour supported his wife and five small children,
was fined for being at a meeting.
The officers, pitying his circumstances,
reported to the justice that the man had little in
the house except the bed he and his family lay on.
The obdurate magistrate ordered them to take his bed, which they did the next day,
and left him and his family to lie upon the straw.
His wife after this, endeavouring to maintain her children by baking a little bread,
and selling it in the market, the officers made a seizure even of that,
at one time to the value of nineteen-pence, at another to the value of fourteen-pence.
So destructive to humanity is an ignorant and furious zeal!

When the officers came to Anthony Alexander`'s house to make distress, one of them,
Erasmus Cooper, told his wife, who was big with child, he was come to seize all they had,
and that he would not leave her a bed to lie on.
They broke the doors with a pick-axe; their behaviour was so brutal,
that the observation thereof drew tears from the compassionate neighbours.
And in the insolence of office, commanding Alexander`'s man to help them,
and being told how unreasonable it was to require
a servant to take away his master`'s goods,
one of them churlishly answered, they are our goods.
For a fine of 7£. they took away goods to near the value
of 18£. The same officers came to the house of Samuel Duncan,
bringing with them Tennison the informer, and the hangman;
here they stayed several days and nights, keeping Samuel`'s wife, who was big with child,
a prisoner in her own house, not suffering her to speak to any person even at the door,
nor admitting any access to her.
They broke open all the doors which were locked,
and carried away goods to the value of 42£. These pestilent informers,
being now encouraged and incited by the court, and by the bishops,
to prosecute their infamous occupation to the utmost prejudice of the non-conformists,
were so elevated with insolence, in their own imagined importance,
that one of them vauntingly said, I`'ll make the mayor wait upon me as often as I will,
at my pleasure.^
footnote:[[.book-title]#Sewel#]
For both the magistrates and peace officers,
well knowing the penalties they were subjected to,
and the advantage given to these informers by the last act against conventicles,
in case of any backwardness or omission on their part in executing it to the full,
were often for fear of them urged to severities to
which their natural feelings were reluctant,
and were frequently fined upon complaints of these informers, especially now,
when they were favoured by the court.
Of this we meet with an instance at this time and place.
William Poole, a constable of Norwich, coming unwillingly with an informer,
who compelled him to accompany him to the Quakers meeting,
and being affected with the doctrine he heard preached there,
cried with tears in his eyes, What shall I do?
I know the power of God is among you.
And turning to the informer said,
"`if there was a curse hanging over any people upon earth it was upon the informers.`"

Which remark seems verified by the event;
for their ill-gotten plunder did them little service; being mostly profligates,
it was generally as ill spent, as it was attained, in bad houses, taverns,
gaming and debauchery.
An informer was withal, but a degree above a beggar,
a remarkable blast attended them and their property: many of them,
as they lived in infamy, died in misery and extreme poverty; some came to untimely ends,
and many of them were thrown into jails, and ended their lives there.^
footnote:[John Jackson,
who had busied himself as an informer in Westmoreland on every act against the Quakers,
notwithstanding his ill-gotten gains this way,
was reduced to such extreme poverty as to beg his bread.
[.book-title]#Besse.#
{footnote-paragraph-split}
William Watt of Norwich
had several years followed the trade of informing,
but what he got by it turned to no account;
he was often seized with such fits of weakness that he could not stand on his legs;
at last he was very suddenly removed out of this life; he was apparently quite well,
and on a sudden sunk down to the ground, his daughter shrieking out,
he just looked at her, and immediately expired.
But what was most remarkable, his corpse was so very offensive by its smell,
that none being willing to come near it,
the overseers of the poor were necessitated to hire four men to bear it to the grave.
{footnote-paragraph-split}
John Smith, a very busy informer in Yorkshire,
was lost in a great snow in Eastby Pastures, and after about five weeks was found,
having his eyes and tongue picked out by vermin, and he stunk so,
that the men who brought him home, complained of the nauseous scent for many days after.
{footnote-paragraph-split}
John Cullington, fisherman, of Harwich,
and a noted informer against meetings there, was found drowned,
whether by accident or through despair is uncertain, but the latter is not improbable;
for he had expressed himself to be under grievous
trouble and concern of mind for what he had done.
His dead body was cast on shore at a common landing-place near the seaside.
{footnote-paragraph-split}
Randal Pool, a taylor, of the same town,
a man who had been in good credit, took up the business of an informer,
to follow which he neglected the care of his lawful vocation.
After which he habituated himself also to gaming and drinking,
striving by those means to stifle the checks of conscience,
which nevertheless grew so strong,
that he was constrained to acknowledge that he was so troubled
in mind that he was afraid he should be distracted.
This trouble produced repentance, so that he afterwards desisted, and lived quietly.
{footnote-paragraph-split}
John Hunwick, an informer, of Braintree,
had been a shopkeeper of good reputation there,
but seeking to enrich himself by the spoil of his neighbours,
he proceeded with much uneasiness.
At length, when on his deathbed, he sent for Solomon Skinner and others,
whom he had prosecuted, entreating them to forgive him, and to pray to God for him,
telling them he was so troubled in conscience he could not die in peace.
]
Tennison before-mentioned was of the number of those who were cast into jail,
where he confessed, he had never prospered since he undertook that work and that,
if be obtained his liberty, he would never be concerned in it again.

The distresses made this year in Nottinghamshire, upon the members of this society,
for their religious assemblies only, amounted to 712£. and upwards,
many of which were exorbitant, and the fines frequently imposed and levied upon slight,
and sometimes false, information:
And although the law admitted of an appeal to the quarter sessions,
we are here presented with a fresh instance of the ineffectual
relief to be attained by an appeal to justices,
more tender of one another`'s honour than the grievances of the sufferers.

One John Sayton was informed against and fined by justice
Thoroton 20£. for being at a meeting in the parish of Blythe,
at a time when he was sixty miles from thence: He appealed to the quarter sessions,
and with much difficulty obtained a hearing of his case:
The jury finding the matter clear, brought in a verdict for the appellant;
whereupon Penniston Whaley, one of the justices, who had before manifested his virulence,
and ignorance of the Quakers and their principles,
in his endeavours to enforce the act 35 Eliz.
ordered them out again, whereunto one of them replied, we are agreed,
and have well considered the matter.
Unable to restrain his wrath within any bounds of decency,
he flung off the bench in a rage,
expressing his indignation at this bulwark of the
subjects`' privileges in such terms as these,
"`You deserve to be hanged, you are as bad as highwaymen;
I hope the king will take away juries, for this will not do.`"
Thus Sayton was acquitted,
and this jury dismissed to make way for another more
pliant to the instructions and temper of the court.
Next morning another jury was empannelled, and another appeal of the like nature came on.
The case was that of William Hudson,
whom the evidence could not prove to have been at the meeting he was charged with,
and though eight of the jury were picked men known to be adverse to the appellant,
yet the other four stood out, and no verdict was agreed upon until eight at night,
when one of the four being taken ill and wanting refreshment, justice Whaley told them,
if they did not agree, they should stay there until they died,
and as one of them died the court would choose another.
They were over-awed into a compliance, and after the court was adjourned,
privately gave a verdict against the appellant; when one of the jurymen said,
he would gladly do equity, Thoroton, another persecuting justice, replied,
You have nothing to do with equity.

In the city of Hereford,
the severe prosecution of the late law against sundry members of this society,
the partiality of the justices in frustrating appeals to the sessions for redress,
by refusing to accept the juries verdicts for the appellants,
being found insufficient to deter this people from keeping up their meetings,
the magistrates and priests,
seeing they could not suppress them by the rigorous enforcing of rigorous laws,
violent seem to have combined to attempt it by lawless violence,
by stimulating the populace, prone to mischief, to the gross abuse of them.

On the 20th of the month called August, Henry Caldicott, mayor of this city,
with his officers, came to the meeting there,
and warned the assembly not to meet any more, telling them, they did,
let it be at their peril.
The sequel fully explained the meaning of this menace,
being followed for several months with outrageous insults and abuses from the populace.
They first beset the meetinghouse with confused noise and
shouting to terrify the people assembled within it;
next, some broke the windows; others with staves struck the men`'s hats off their heads,
threw stones among them, and one of them, said to be the mayor`'s son,
broke John Rea`'s head with a stone.
At another time they fired squibs, and threw them into the meeting,
cast stones through the broken windows, and struck a woman on the head.
When complaints of these abuses were made to the mayor,
the complainants were dismissed with threats.
The next time the outrageous mob,
part of which were choristers or singing boys of the cathedral, encouraged, as reported,
by their superiors the college priests,
broke in pieces the remainder of the glass windows,
with the window-frames and some of the walls of the house.
After the meeting broke up, they pursued the country friends,
pelting them with stones near a quarter of a mile.

The next day a meeting was held in their battered house for church affairs,
such as relieving the poor, the widows and the fatherless,
and other acts of pure and undefiled religion:
Then they assembled the rabble by sound of horn, throwing dirt,
stones and filthy excrements amongst them and upon them, whereby several were much hurt,
and all grievously annoyed.
Some mounted on the roof of the house and untiled part of it,
tumbling down stones on one going in.
In the midst of these disorders Edward King and Robert Simonds, justices,
and Abraham Seward, mayor elect, came, not to quell the fury of the rabble,
but to send the abused to prison, to effect which,
after threatening the women and children,
they tendered the oaths of allegiance and supremacy to eight of the men,
and for refusing to swear sent them to jail.
A day or two after this Walter Rogers, a prebendary, passing by the meetinghouse,
and observing the ruins, said, they that did it were very good boys,
and had done their work better than he expected.
Thus evidencing plainly under what kind of influence the
mob committed these acts of violence and outrage.

They continued the like abuses through the remainder of this year and a part of the next.
The sufferers having got the house repaired and habitable again;
it was again beset by the rude multitude, who threw stones as before,
being reported to be instigated by the mayor`'s officers, who are said to have bade them,
knock out the Quakers brains, if they did not depart.
They also threatened the inhabitant to pull the house down over his head.
At another time one of these officers threatened, they would fire the meetinghouse,
and broil them in it.

These were certainly times in which justice was perverted, and equity could not enter,
when peaceable dissenters were tried and punished as rioters for worshipping God,
without injury to any man, and real riots not only passed by with impunity,
but were promoted and abetted by those,
the duty of whose office and their oaths should have obliged them to preserve the peace.
