== Chapter V.

[.chapter-synopsis]
* George Fox leaves Swarthmore
* Travels by easy Journeys to London
* Goes over to Holland
* Instances of abuse of the Conventicle Act
* In Cheshire, by Peter Leicester
* In Gloucestershire, by John Meredith
* At Plymouth, by Anthony Horseman and William Tomes, Mayors
* Death of William Dobson.--Of Richard Ashfield
* Marriage of the Princess Mary to the Prince of Orange
* Violent Party Dissensions
* Persecution continued
* Fresh Solicitation for Relief

In the beginning of the year 1677, while the roads were yet covered with snow,
George Fox left Swarthmore,
where he had mostly resided ever since his release from his imprisonment at Worcester,
and passing over into Westmoreland, several friends met him at Thomas Camm`'s at Camsgill,
to take their leave of him before he left the country,
where the next day he had a very large meeting,
and was largely opened in doctrine therein.

From thence he proceeded on his journey, visiting the meetings of his friends,
and edifying them with his ministry, through the counties of York, Derby, Nottingham,
etc. passing through the counties to London; he had not yet recovered his strength,
since his indisposition at Worcester, so far as to bear continual travelling,
even by short journeys, without inconvenience and fatigue,
being also much deprived of rest at nights by reason
of cold contracted by riding in frequent rains;
but being engaged in a good cause, and depending upon divine support,
he was not discouraged from steadily pursuing the line of his duty,
and was safely carried through all attendant difficulties.
As he had spent near two years at Swarthmore for the recovery of his health,
and been little abroad amongst his friends,
he was received with much gladness by friends at London,
where he stayed the yearly meeting, which was then approaching.

As in those early times most of the business of the yearly
meeting was to receive account of friends sufferings,
and take measures for their relief;
so at this time accounts were received of the heavy sufferings
which friends in many parts were exposed to (as well as by other
laws enforced against them) by prosecutions on the act of 23 Eliz.
as popish recusants,
by which they suffered the confiscation of the two-thirds of their estates,
whilst real recusants were little molested: The parliament then sitting,
a specification of this grievance was drawn up, and laid before them,
with a petition for relief; but they obtained no redress thereby.
The meetings however were comfortably conducted in brotherly unity,
to the mutual edification of the body assembled on that occasion.

Soon after the yearly meeting, George Fox, accompanied by William Penn, Robert Barclay,
George Keith and some others,
went over to Holland to visit their friends in that republic, of whose service there,
an account may be found in the process of this work,
when we come to treat of the state of the society in these parts.

In Cheshire we meet with a fresh evidence this year of the
unreasonable use made of the last act against conventicles,
and the invidious instance,
of propensity of some magistrates to plunder the members or this society,
Peter Leicester, a justice of peace, acting the part of an informer,
came to a meeting at the house of William Gandy, shut the doors,
and placed a guard of soldiers at them, while he took a list of about two hundred names;
fined Margaret Fox and Thomas Docwra each 20£. for preaching,
and 20£. to be levied on several of the assembly for the house they met at,
besides their own particular fines; for which he issued his warrants of distress,
threatening the constables,
that if they did not execute them to the utmost he would bind them to their good behaviour;
bidding them sell a cow for 5s. and to take enough for themselves.
The officers, thus encouraged, took away for that one meeting,
goods and cattle to the value of 200£, from six friends.

In Gloucestershire, John Meredith, a justice of the peace,
signalized himself by fiercely prosecuting friends:
He caused twenty-seven of them to be indicted at Gloucester sessions,
for absence from the national worship,
though he knew that most of them had deeply suffered before by the act against conventicles:
He arbitrarily required of Henry Pontin and Nathaniel
Hefkins sureties for their good behaviour,
when no complaint was made against them, and kept them in prison three months;
after which he indicted them at the sessions for meetings, and had them fined 40£. each,
and continued in prison:
He beat William Bennet and William Wade unmercifully with his own hands:
He took John Selcock by the hair of the head,
and plucked him out of the meetinghouse at Frenchhay, into the yard:
then drew his knife, and said he would mark him,
but was prevented by the interposition of his clerk and others:
He drew his knife at George Peace,
and probably had done him mischief had not one of his own servants restrained him:
He plucked John Bawn out of a meeting by the hair of his head,
and after that finding him in the highway, he fell upon him, and beat him barbarously:
He also beat John Fryar and Joseph Glover, two officers,
because they would not abuse people as much as he would have them.
When Samuel Simmons, being wrongfully fined, appealed to him for justice,
he fell furiously upon him and beat him inhumanly:
He also caused the forms and benches of the meetinghouse to be cut in pieces;
and with his staff broke five glass windows to pieces, not leaving one whole quarry.

At Plymouth, on the 5th of the 2nd month called April, Andrew Horseman, mayor,
with three other justices, and constables attending them, forcibly dispersed the meeting,
and fined Richard Samble 20£. for preaching.
On the 7th of the same month, the first of the week,
the mayor and two other justices took the names of those who were met,
haled them into the street, set a guard at the meetinghouse door to keep them out,
detained Richard Samble until evening, and then fined him 40£. for preaching.
From that day forward they were kept out of their meetinghouse,
and obliged to meet in the street, until the 29th of September following,
when another mayor, William Tomes, entered upon office.
The next day they met peaceably in the house;
but afterwards this mayor followed the example of his predecessor, and kept them out,
and they assembled in the open street three times in a week,
enduring the extremity of cold, and inclemency of the weather all the winter;
abused by the rabble of the people,
and sometimes by the officers and soldiers of the garrison,
who threw squibs of fire and hot burning coals upon them,
pushing them up and down the street, and bedaubing them with filthy excrements;
all which and much more they endured with unwearied
patience for the space of more than twelve months.
Several warrants also were granted for distraining their goods,
by one of which the constables forcibly entered the shop of Robert Cary,
and took away from him sugars and strong waters to the value
of 24£. all which they sold for 4£. 13s. In many other parts
the members of this society were treated with no less severity:
but it would be disagreeably tedious to give a detail of every particular.

This year William Dobson of Brightwell in Berkshire died a prisoner
for his conscientious testimony against the payment of tithes,
upon which account he had been a remarkable sufferer,
having been spoiled of his goods from time to time, during the space of thirteen years,
and most of the time a prisoner.
For tithes the value of about 4£. 10s. he had goods taken from
him worth 40£. He was imprisoned the succeeding year at Reading,
and removed thence to the Fleet in London, where he lay a considerable time;
and lastly he was prosecuted in the Exchequer, and committed to prison in September,
1675, and kept there until he died in the third month called May this year.
He had also taken from him by Ralph Whistler, his prosecutor,
goods worth 156£. for five or six years tithes of a farm,
the yearly value of which tithe had been formerly estimated at no more than 4£.

This year died also in Newgate, Richard Ashfield of Stanes in Middlesex,
of whom his widow gave the following account:^
footnote:[[.book-title]#Besse#]

[.embedded-content-document.testimony]
--

After my dear husband Richard Ashfield was convinced of the blessed truth,
as it is in Jesus, he was often prosecuted, by excommunications and sessions process,
for non-conformity; and in obedience to the command of Christ,
refusing to take the oaths, was several times imprisoned,
on which account he also suffered a year`'s imprisonment in 1665.
In the year 1676 he was again excommunicated for non-conformity,
and refusing to pay church rates (so called.) By
the vehement instigation of Edward Kempshall,
a _writ of capias_ was served on him, and he carried to Newgate in the 11th month, 1676,
to the great grief of many honest people, who wept when they took their leaves of him,
it being then a very cold season, and he aged about sixty-five years,
and much troubled with a cough and phthisic; this, to use his own words on his dying bed,
was the occasion of shortening his days.
On the 11th of the 10th month, 1677, he laid down his head,
and resigned his soul and spirit in perfect peace and joy of the Lord,
into the hands of his faithful Creator.

--

The nation in general appeared entirely dissatisfied with the government.
The parliament was divided into two parties, the court and the country;
some were insisted into the court-party by offices; some by pensions,
and some by inclination.
These who were for supporting the measures of the court,
were now sanguine for enforcing penal laws against non-conformists.
The most active justices were of this party,
and in the execution of the laws seem to have considered the disposition
and mandates of the court as the principal rule of action,
without giving much attention to the superior rule of right and equity.
The country party, backed by popular favour,
had got the ascendency in the house of commons, and carried an address to the king,
disapproving of his attachment to France,
and requesting him to enter into an alliance with Holland,
which he resented as an invasion of his prerogative, and ordered them to adjourn.

However being sensible that violent discontents prevailed in the nation,
and seemed daily of increasing,
he resolved by a popular act to attempt allaying the ill humour,
which his mistaken politics had produced, by marrying the Princess Mary,
eldest daughter of the Duke of York,
(whom he had caused to be educated in the protestant religion) to the Prince of Orange,
afterwards King William III.
whereby a foundation was laid for the preservation of the protestant Religion,
and an exemption of the dissenters from the penalties to which they were now subject.

This year also died Archbishop Sheldon, a determined enemy to non-conformity,
and a principal promoter of the penal laws of this reign,
and of their rigorous execution.
He was succeeded by Sancroft,
who seemed on some occasions too much to copy after the spirit of his predecessor.
George Whitehead gives account of a conference which he
and William Crouch had with this last named prelate,
in relation to the great sufferings of their friends by informers;
that describing the infamy of their characters and conduct;
how numbers of them had forsworn themselves, and deserved to be indicted for perjury;
adding, what a dishonour it was to their church to employ such agents;
to force conformity by plunder;
and how opposite to the nature and design of religion to give encouragement to villainy.
Instead of condemning and giving expectation of discouraging their vile practices;
he seemed rather to apologize by his reply, which was,
that there must be some crooked timber used in building a ship.
Upon which George Whitehead aptly remarked, that the parallel was by no means just:
Crooked timber is most useful in building a ship;
but vicious characters are so far from being of use in building the church of Christ,
that they have no place there in.
What church is it (saith he) which is in danger (as the cry is) when it
wants such crooked timber as rapacious informers to support it?

Plenipotentiaries from the different states at war being
convened at Nimeguen this year to treat of a peace,
which after some time took place, Robert Barclay wrote an epistle to them in Latin,
containing an exhortation to promote the desirable end of their meeting,
and there with sent his apology in Latin,
to be delivered one to each of the said plenipotentiaries,
and one for each of their principals.

From this time to the end of the king`'s reign, party heats grew more and more violent;
plots real or fictitious prosecuted with acrimony by the opposite parties;
a spirit of intrigue and hostility influencing both court and country;
continual dissensions between the king and parliament, both struggling for power,
which both carried too far; furious sallies of rage and revenge,
to the almost entire extirpation of temper, sound judgment,
wisdom and justice private animosities and public confusion
deform the history of the latter years of this reign.
In the meantime the dissenters in general and friends in
particular felt the hand of persecution heavier than ever;
the penal laws being in full force,
and the execution of them in the hands of their inveterate enemies,
whose hatred was new edged by this temper of the times;
for although the society attached themselves to no particular party,
yet the parliaments taking their severe sufferings under deliberation,
especially those inflicted on them as popish recusants, and intending their relief,
was a sufficient reason to magistrates subservient to the court; as well as to the court,
bishops and clergy to consider them of the opposite side, and treat them accordingly.
