== Chapter VI.

[.chapter-synopsis]
* Fresh Solicitation for relief of Friends
* Discovery of the Popish Plot
* Roger Longworth committed to Prison under pretext of being a concealed Papist
* Privately discharged
* Successive Disappointments in the Sale of distrained Cattle
* Account of Isaac Penington
* Parliament dissolved
* New Parliament summoned.

George Fox, after his return from Holland,
and visiting the meetings of his friends in various parts of England,
came to London during the sitting, of the parliament last year,
and found his friends there engaged in fresh solicitations to them for
relief from prosecutions by the laws made only against popish recusants;
which although they were well known not to be,
yet several malicious magistrates took the advantage thereof,
to prosecute friends with severity upon these statutes.
George Fox, upon his arrival, joined these friends in their application,
but a sudden prorogation put a stop to their proceedings at that time.
When the parliament met again, George Fox, William Penn, George Whitehead and others,
renewed their application for exempting their friends
from the severe penalties of these obsolete laws,
which were never intended against them; and they conceived some hopes of relief,
many of the members manifesting a tender and compassionate regard toward them,
and a disposition to relieve them,
as being convinced they suffered grievously and very unjustly,
and that they were much misrepresented by their adversaries.

But the attention of the parliament was soon called off to a subject of greater emergency,
or such as they looked upon in that light:
It was about this time a discovery was made of that called the popish plot.
When the parliament met, they made inquiry into the matter, and voted their sense,
"`that there was a damnable hellish plot contrived and carried on by popish
recusants against the life of the king and the protestant religion.
Whatever objections may be advanced to the characters and credibility of the witnesses,
as to many circumstances of this plot,
yet it soon appeared that whilst the peaceable society of the Quakers,
in common with other dissenters, were persecuted under pretence of being seditious,
riotous, contrivers of plots in their religious assemblies, without the least cause,
and subjected to the penalties of laws made against popish recusants,
from whom their principles were most remote;
and while the church (so called) was railing.
a cry of its danger from the increase of sectaries;
that its real danger arose from this party, who,
under the favour and protection of the court were meditating,
and sanguine in their hopes,
to reestablish themselves and their religion in England in its full power and splendor.
To the sense of their danger the established church at length began to be awakened and
after a series of oppression and persecution in the exercise of the power in their hands,
which they fondly thought they were establishing, in the humbling of their antagonists,
they had the mortification to find they had been only tools
to advance the views and hopes of this party,
in dividing and weakening the protestant interest, and upon the discovery,
the moderate part were inclined to coalesce with the dissenters,
in opposition to the establishment of popery, when it had like to have been too late.

But the magistrates, who were of the high-church party,
retained their malignity to dissenters, until their hands were manacled by law.
Informers were encouraged to hunt after their prey, and the justices as ready to convict,
as they to inform.
Prosecutions by the acts of Eliz.
for 20£. a month, and the seizure of two- thirds of the annual rents,
were multiplied against the people called Quakers,
as the most expeditious mode of impoverishing men of estates.
Advantage was taken of the alarm occasioned by the rumour of the popish plot,
to increase the rigorous persecution of a people of opposite principles and conduct;
under the specious pretext of the necessity, in this season of danger,
to exert additional vigilance in guarding against seditious assemblies.
And in order to turn the tide of the public temper against them,
and expose them to the resentment and abuse of the undiscerning populace, some members,
whose residence, occupations and manner of life were well known, were imprisoned,
under a pretended suspicion of being papists or concealed Jesuits, a character which,
at this season, was in a peculiar manner the object of popular odium and aversion.

Thus, while the nation in general was in consternation at the discoveries
of the plots the informers were pursuing their infamous occupation,
to the great detriment and oppression of honest men,
which gave occasion to a writer of that time,
who published many particular instances of their management, to remark, that,
truly the papists may laugh because of their victory, now they have a law,
whereby one protestant fights against another.
Roger Longworth, of Bolton in Lancashire, occasionally travelling into Cheshire,
was by two officious justices sent to prison by the following mittimus.

[.embedded-content-document.legal]
--

[.letter-heading]
Com. Chester Ss.

Forasmuch as by reason of several expressions, which we have,
in Holme in the county of Chester, heard from a strange person,
who calls himself Roger Longworth, of Bolton in the county of Lancaster,
we do suspect the said Roger Longworth is a papist,
and thereupon we have tendered unto him the said Roger Longworth
the oath of obedience and the oath of supremacy,
both which oaths the said Roger Longworth, being above the age of eighteen years,
hath this day refused to take.
These are therefore in his Majesty`'s name to command and require you forthwith,
upon sight hereof, to receive into your custody the body of the said Roger Longworth,
whom we have herewith sent you,
"`and him therein safely keep until the next general quarter sessions
of the peace to be held in and for this county of Chester,
without bail or mainprize.
For so doing this shall be your warrant.
Given under our hands and seals at Holme this 20th day of February,
_Anno rni Caroli fecundi, etc. tricesimo, Annoq.
Dom._ 1678-9.

[.signed-section-signature]
Thomas Manwaring, Bart.

[.signed-section-signature]
Jeffry Shackerly, Knt.

[.signed-section-context-close]
To the Keeper of Chester Castle.

--

After he had been left in prison about two months he was set at
liberty by a private order from the said justice Manwaring.

In Lincolnshire we meet with a remarkable instance this year,
of the light in which the spoil made under the conventicle
act was looked upon by many people,
in the case of Thomas Robinson of Brant-Broughton,
who was fined by Sir Christopher Nevill 40£. for being at a meeting at Beckingham,
by whose warrant he had taken from him eighteen of his best young sheep,
one pair of steers, four draught bullocks, and four fat bullocks;
worth 44£. 11s. The four fat bullocks were sold to a butcher, who,
hearing on what account they were taken, declined the bargain.
Next all the steers and bullocks were driven to Grantham market,
but nobody would buy them; again the bullocks were sold for 27£. to one Parker,
but when he understood, how they were come by, he would not be concerned with them.
Then they drove the beasts to Lincoln, but could find no purchaser, for the people,
esteeming them the spoil of conscience, would not buy them.
At length the constable drove them all to Sir Christopher Nevill,
by whose warrant they were taken, who, finding no purchaser,
and being unwilling to take them himself, restored them to the owner;
for although he might think himself obliged by the duty of his office,
and to avoid the penalty, to execute the law,
he appears different from many other justices of this age,
to have been a man of too much honour,
to seek his own advantage by the loss of his neighbours.
The chief promoter of this prosecution was John Chappie, priest of Brant-Broughton,
who perceiving the constable not forward in making distresses, and breaking up meetings,
sent him the before recited menacing letter.^
footnote:[See note, page 302.]

By such means the parish officers were sometimes impelled to act against their inclination,
the priests exciting the justices to punish by fines
and imprisonment for neglect of duty,
such of them whose moderation and humanity rendered them
reluctant to prosecute or plunder their conscientious neighbours.
The repeated instances of such busy interference of priests,
in promoting the execution of these penal laws, leave no room to doubt, that,
notwithstanding the endeavours used to exculpate the church,
by throwing the odium of those persecuting laws on the parliament, who enacted them,
the clergy were deeply concerned, both in the promotion of these laws,
and the severe execution there of.

In this year Isaac Penington, of Chalfont in 1679.
Buckinghamshire, an honorable, useful and virtuous member of this society,
departed this life.
He was the eldest son of Alderman Penington of London,
a noted member of the long parliament,
who was nominated (but never sat) amongst the King`'s judges.
And being heir to a fair inheritance,
his education was suited to his quality and expectations in life,
having all the advantages which the schools and universities
of his own country afforded him;
and by his station in life at that time had the additional advantage of improving himself
in the conversation of some of the most knowing and most considerable men of the age:
His natural abilities enabled him to avail himself of these advantages;
being a man of quick apprehension, an acute genius,
sound judgment and good understanding.
His disposition was mild and affable, free from pride and affectation;
his common conversation cheerful but guarded; equally digested of moroseness and levity;
tempering easy affability with serious gravity, he was no less pleasing in the manner,
than instructive in the matter, of his discourse.

His father`'s station in public employments, and his rank in life,
opened him a fair prospect of worldly greatness, if his views had been turned that way;
but actuated by higher and nobler considerations,
he was induced to relinquish the short-lived glories of this world,
as unworthy to engage the principal attention of man born to immortality:
he steadfastly believed in a future state;
was early impressed with a lively conception of the value of everlasting happiness,
and early engaged in the arduous pursuit of it.
With Moses he chose rather to suffer affliction with the Lord`'s people,
than enjoy the pleasures of sin for a season.

For from his childhood he was religiously inclined,
and incited in heart to a diligent search after the way to salvation.
He prayed for what testimony he felt he wanted:
He was frequent in reading the scriptures, and faithful in practising,
what thereby was manifested to his understanding, as the way he was seeking after,
notwithstanding he met with much reproach, opposition and other trials;
for he became the wonder of his kindred and familiars for his awful frame of mind,
and his retired life;
he much declining company that might interrupt his meditations
and serious attention to the great concern of his soul`'s well-being:
Yet he found peace and acceptance in a life and practice of sincerity,
according to that degree of knowledge of the divine will, which he had attained unto.

But in reading the scriptures he perceived in himself,
and the generality of professed christians, a great falling short of the power,
experience and spiritual attainments,
the scriptures testified to have been acquired in former times;
so that the religion of that age, although high in profession,
appeared to him (for the most part) but a talk, in comparison of what was enjoyed,
possessed and lived in by the primitive believers.

Under this view he was led to separate himself from
the public worship he had usually frequented,
and join a select society, amongst whom he found a good degree of sincerity,
and divine help near them in many cases; but, he writes, there was something wanting,
and that they fell into a mistake;
for that whilst they should have pressed forward into the spirit and power of godliness,
they ran too much outward into the letter and form;
in consequence whereof they became darkened in their minds,
and confusion and a dissolution succeeded.

Being now left alone, and connected with no visible society,
in a state of darkness and uncertainty,
he fell under great trouble of mind for a long season,
secretly mourning and praying to the Lord night and day.
At last he met with some of the writings of the people called Quakers,
which he cast a slight eye over, and threw aside with disdain,
as falling very short of that wisdom with which, he apprehended,
the living faith he was searching after, would be attended.
At some distance of time he had the opportunity of conversing with some of them;
and although (to use his own expressions) they reached the life of God in him,
which life answered their discourse, and engaged his affectionate regard toward them,
yet he seemed to have that advantage over them in the power of reasoning,
and superiority of understanding,
that he could not but view them in a contemptuous light, as a poor,
weak and despicable generation, that had some smatterings of truth in them,
and some honest desires towards God,
but very far off from the full understanding of his way and will.

After a considerable time of solitude,
being invited to a meeting of this people at John Crook`'s in Bedfordshire,
he went with a fixed disposition and desire of heart to receive nothing as truth,
which was not of God, nor withstand anything which was.
George Fox was at that meeting, who spoke so clearly to his state,
in expounding the mystery of iniquity, and the gospel of peace and salvation,
and with such energy, as gained his full assent;
and from that time forward he joined the people called Quakers in society,
wherein for a season he underwent great spiritual conflict,
and much outward opposition and reproach from his father, his relations,
the people and powers of the world;
yet through the virtue of that religion which he possessed,
he was strengthened to retain his love and affection
to them under all that he suffered from them.

It was in the year 1658 that he joined in community with this society,
and being well prepared by the religious exercises he had passed through,
previous to his convincement, as well as after,
he soon became a very eminent and serviceable member therein.
His piety was manifested in his humble and reverent adoration of God,
and circumspect conversation, as in his presence; his benevolence and christian charity,
in his diligence in visiting and administering to
the distressed and afflicted in body or mind;
his hospitality in opening his heart and house for the reception of the
messengers of peace and for the religious meetings of his friends.
Through his ministry many were converted to the truth he had received,
and many confirmed in it, his preaching being with divine authority,
in the demonstration of the spirit and of power.
He was manifestly endowed with the apostolic qualification of a bishop,
given to hospitality, apt to teach.

His conduct and conversation were a seal to his ministry,
being an excellent pattern of piety, virtue and the strictest morality,
in every relation and circumstance of life.
In his own family he ruled well, and maintained his authority, not by austerity,
to which his mild temper was averse, but by an example of gravity,
steadiness and circumspection of life,
joined to seasonable instructions and affecting exhortations
to godliness in the meekness of wisdom.
He was a most affectionate husband; a careful and tender father;
a mild and gentle master; a sincere and faithful friend;
compassionate and liberal to the poor;
and affable and kindly disposed to all he conversed with; ready to do good to all men,
and careful to injure none.

In this age, when virtue without conformity was treated as a crime,
neither his rank in life, the benevolence of his disposition, the integrity of his heart,
the inculpable innocence of his demeanour, nor the universal esteem of his character,
had sufficient merit with those in whose hands the power was lodged,
to exempt him from the sufferings attendant upon the profession he made.
His imprisonments were many, and some of them long and severe,
which he bore with great firmness and serenity,
being supported by the testimony of an approving heart,
and the consciousness of suffering in a good cause.

His first imprisonment was in Aylesbury jail, in the year 1661 and 1662,
being committed from a meeting in his own house, where he was confined seventeen weeks,
mostly in winter, in a cold and very incommodious room, without a chimney;
from which hard usage his tender body contracted a distemper, so violent,
that for several weeks after he was not able to turn in his bed.

His second imprisonment was in the same jail, for the like cause,
viz. meeting with his friends for divine worship,
where he was again detained a prisoner about the same space of time.

He was next imprisoned with sundry other friends upon an occasion,
which gives us a renewed instance of the arbitrary temper,
and illegal exertion of power of many of the justices of this age.
A friend of Amersham being to be buried,
several friends and others of the neighbourhood assembled, as usual,
to attend the funeral.
It happened that one Ambrose Bennet, a justice of peace,
accidentally riding through the town, and hearing of this funeral,
alighted and stayed until the corpse was carrying to the grave
with the company attending it in a peaceable and solemn manner,
becoming the occasion.
Upon which he rushed out of the inn, attended by some constables and rude people,
whom he had gathered about him, and having his sword drawn in his hand,
struck one of the foremost of the bearers with it,
commanding them to set down the coffin;
but they not being forward to comply with an order, for which he had no legal authority,
as they were in no unlawful act;
he violently pushed it off their shoulders into the street,
and there left it to the annoyance of all passengers until the evening,
when it was forcibly taken from the widow,
and buried in the unconsecrated part of the churchyard, as it is termed.

Immediately after he had thrown down the coffin he ordered
the constables and rabble to apprehend the company,
whereupon they dragged or drove several of them to the inn:
Then sending for another justice to join him, they picked out ten of them,
of which number Isaac Penington was one, and committed them to Aylesbury jail,
though the justices or prisoners could hardly tell for what.

Here they were detained until the assizes,
during which they were brought before judge Morton, who being a morose passionate man,
treated them with rude and reviling language;
but would neither hear them nor their cause,
referring their case to the justices who committed them,
who after the assizes sent for them to their inn,
and committed them again to prison for one month, on the act of banishment.

He had scarce enjoyed his liberty more than a month when he was taken out of
his own house in a manner even more arbitrary and groundless than before,
by military force.
A rude soldier, without any other warrant than what he carried in his scabbard,
took him before Sir Philip Palmer, one of the deputy lieutenants of the county,
who sent him with a guard of soldiers to Aylesbury jail,
with a very unusual kind of mittimus,
importing that the jailer should receive and keep him in
safe custody during the pleasure of the Earl of Bridgewater.
This Earl of Bridgewater had very causelessly imbibed
a particular antipathy to this inoffensive man,
to that degree, that although it was the year of the plague, which had reached that town,
and the jail was supposed to be infected, he could not be prevailed upon,
by the intercession of a person of considerable rank and authority in the county,
to permit him to remove to another house in the town,
until the jail was free from infection:
Afterwards a prisoner dying in the jail of the plague, the jailer`'s wife,
in the absence of her husband, gave him liberty to remove into another house.
At last, by the interposition of the Earl of Ancram, he was discharged,
after suffering an imprisonment of three quarters of a year,
at the apparent hazard of his life.

But before the end of a month another party of soldiers from the said Philip Palmer,
as reported, by order of the Earl of Bridgewater, came to his house, seized him in bed,
and carried him to the same jail again, where without any apparent cause,
or any offence objected to him,
he was imprisoned in rooms so damp and unhealthy as greatly endangered his life,
throwing him into a distemper in which he lay weak several months.
During his long confinement he was never called for at the sessions or assize,
but by some illegal means returned on the calendar to remain in prison.
At length being removed by _habeas corpus_ to the King`'s Bench Bar, when he appeared there,
and no cause of his imprisonment appearing, the court released him in 1668,
with plain indications of surprise, that a man should be imprisoned,
and so long kept in prison, for nothing.

Last of all he was imprisoned at Reading in 1670.
In the exercise of christian charity and fraternal sympathy,
he had come thither to visit his friends in prison there;
and report of his visit being made to that rigid
and implacable magistrate Sir William Armourer,
he caused him to be brought before him, and committed him to prison,
in company with his friends, whom he came to visit.

Here he continued a prisoner a year and three quarters,
being condemned in a sentence of premunire, under which he lay, it is probable,
until released by the king`'s letters patent in the year 1672.

Being through divine assistance preserved steadfast in the faith, through all his trials,
inward and outward, in a life and conversation blameless among men,
and in the faithful discharge of a good conscience in the sight of God,
by a long life of virtue and piety, he was well prepared for his dissolution,
which happened on the 8th of the 8th month, 1679, in the sixty-third year of his age,
at Goodnestone Court in Kent, being a farm belonging to his wife,
where he was taken ill of a sharp and painful distemper,
which terminated his existence in the body:
But the anguish of his bodily pain gave no shock to his internal peace,
so well established before; he died, as he lived, in the faith that overcomes the world.
His body was conveyed to London, and from thence to his house in Buckinghamshire;
from whence his funeral was attended by a great number of his friends and neighbours,
whose affectionate esteem, on account of his innocent and virtuous demeanour,
he had generally engaged.

The jealousies and mistrusts which the parliament, with the rest of the nation,
had imbibed, of the measures and designs of the court,
from the time of the confederacy with France, which had been increasing ever since,
were well-nigh blown into a flame, by their inquiry into, and the evidence they received,
of the popish plot.
They passed a new test act this year,
disabling all persons of that religion from sitting in either house of parliament.
The Duke of York with difficulty got himself exempted;
but their fears of popery had made such impressions on the minds of the parliament,
that they conceived a design to exclude the Duke
from succession to the crown as being a papist;
upon this count and their succeeding steps in the prosecution of Danby,
the king finding the opposition in the two houses was grown too strong for control,
prorogued the parliament, and afterwards dissolved it,
near eighteen years after it was chosen.

A new parliament was summoned to meet early this year.
The king exerted his endeavours to influence the elections,
but the temper of the times defeated his utmost efforts.
The fears of popery so thoroughly possessed the people,
and the jealousy of the king and duke`'s having a design to introduce it,
that they thought the safety of the nation depended upon the election of a parliament
that would have spirit and abilities to counteract such pernicious projects.
The presbyterians were still numerous in the corporations,
and are represented to have been very active in conjunction with the anti-courtiers,
in turning the elections against the court interest.
This conduct seems to have increased the king`'s disgust
against them and the dissenters in general,
and to have sharpened the execution of the penal laws.
The new parliament proceeded in the design of excluding the Duke of York from the crown;
the king proposed expedients to moderate their warmth,
by offering to agree to almost any restrictions but altering the succession.
The commons, not to be satisfied with any expedients short of a total exclusion,
passed a bill for that purpose, which the lords rejected by a considerable majority;
the bench of bishops, less afraid of popery, which dignified their order,
than of the presbytery, which rejected it entirely,
were most of them on the side of the court.
