== Chapter VII. Scotland.

[.chapter-synopsis]
* Priests of Aberdeen endeavour to stir up Persecution in vain
* Alexander Skein and John Messer convinced
* New Efforts of the Priests to stir up Persecution
* The King`'s Declaration of Indulgence stops their Proceedings
* Account of Alexander Jaffray
* Public Dispute at Aberdeen
* Advantage taken of an Order of Council, to imprison Friends
* The Prisoners called before the Commissioners
* Their Defence
* Several fined one quarter of their valued Estates
* Others in different Sums of Money.

The priests of Aberdeen,
whose repeated attempts to stir up the magistrates to persecute the Quakers, had been,
by the moderation of the latter, mostly frustrated,
continued their virulent endeavours to excite the
civil power to proceed against them with rigour;
but had still the mortification to meet with a disappointment of their aim and wishes.
For upon the coming of the judges to Aberdeen in their circuit, the priest Meldrum,
of whose inimical disposition to this people several instances are already related,
in his sermon before the judges, at the opening of the court, represented them,
in his usual manner as a most dangerous and pernicious sect,
endeavouring to prepossess the judges and excite
them to exercise the utmost severity against them.
Not satisfied with this, he, in company with his colleague, John Menzies,
waited upon the judges at their chambers; where they met with the bishop:
To them they complained that the magistrates of Aberdeen
had several times broke up the Quakers meetings,
had imprisoned fined and even banished some of them;
and yet were not able to suppress them.
Upon which the judges asking, "`What they would have them do farther?`"
Menzies made a proposal so cruel, that the bishop was ashamed,
and the judges would return no answer.
And. when some of the said people, who were cited, did appear before them,
they declined passing any sentence concerning them,
or to give any countenance to the purposes or designs of the priests,
which they clearly saw to be malicious.

When Alexander Skein, together with John Alexander Messer,
who was convinced about the same time, left the communion of their church,
the four priests of Aberdeen were greatly alarmed,
insomuch that upon their joint solicitations the bishop convened a sub-synod,
who met shortly after, and drew up an address to the king`'s council at Edinburgh,
and sent two of their number to present it,
petitioning the council to take some effectual course
to curb and rid the land of the Quakers,
who were increasing among them.
The deputies from the synod spared not their utmost endeavours
to obtain some fresh order from the council against the Quakers,
but met with fresh disappointment,
the council only referring them to a precedent act
of parliament which ordained that "`all,
who withdrew from their parish church,
be admonished by the preachers before two sufficient witnesses,
and then after three first days absence they be fined one eighth of their valued rents.`"
Returning to Aberdeen,
these deputies reported the issue of their application to the town-council,
upon hearing which the provost made this remark, "`What signifies all this?
we had this before: Take you care to do your own work, and we shall do ours.`"
Two of them, George Meldrum and David Lyall,
therefore immediately set about declaration their part of
bringing this act into force against this people,
and were busily engaged in performing their monitory office from house to house,
when the king`'s declaration of indulgence to all non-conformists in 1672 reached Aberdeen,
and put a stop to their proceedings at that time.

The said declaration of indulgence came very seasonably
to prevent the execution of an act of council,
which the priests had prevailed upon the magistrates of Aberdeen to pass,
by which they had resolved "`that no Quaker should be made a burgess or freeman of that
city,`" and that whosoever received a Quaker into his house without leave of the magistrate
should be fined 5s. And that if any person should let an house for Quakers,
either to meet or dwell in, he should be fined five hundred "`Scottish marks.`"

About the same time, the Quakers in Scotland received relief from suffering,
in a case wherein their brethren in other parts were greatly exposed thereto,
it having been the settled custom and legal practice in that nation in suing for a debt,
where proof failed, to put the defendant to clear himself upon oath:
This custom exposed the Quakers, who could not swear in any case,
to be made a prey by ill designing persons prosecuting them frequently for unjust claims.
The judges,
perceiving the advantage this conscientious scruple gave their antagonists in such suits,
regarding their case with the equity becoming their station,
humanely determined that a simple declaration of the truth
should be accepted from that people in such causes.

The priests of Aberdeen disappointed in their vindictive endeavours against the living,
vented their senseless indignation against the dead.
By their influence on the magistrate they procured
the demolishing the walk of a burying ground,
which the people called Quakers had purchased with their own money,
and wherein a child had been buried a few days before.
The body of this child, after three Hays interment, by order of the provost and bailiffs,
was taken out of the ground, carried to a village called Futtie, and interred there.
But an idle rumour being raised among silly people,
as if the Quakers had imposed upon the magistrates, by taking out the child`'s body,
and filling the coffin with something else, they ordered the coffin to be broken open,
and the child`'s body, though so long dead, was observed to bleed.
A wonderful business truly to engage the attention of magistracy!
as it little imported to the preservation of peace or the
public where the remains of an innocent child was laid.
They nevertheless continued this unmeaning and offensive
practice of removing every body that was interred,
until a represenration being made to the king`'s council,
a private check was given thereto, by which a stop was put to this uncommon inhumanity,
and the dead bodies suffered to lie undisturbed.

Notwithstanding all the endeavours of the priests
to suppress the growth of this rising society,
and to excite the civil power to rigorous measures against them,
to the repeated disappointments of their desires,
they had the additional mortification to see several
more of their hearers falling off from them,
and increasing the number of this hated society.
For about the beginning of this year,
Andrew Jaffray and several others of Aberdeen and parts adjacent,
being convinced of this people`'s principles joined themselves to their society.
This fresh provocation incited the priests to renew
their attempts to subject them to persecution;
by their instigations the provost and other magistrates
came to the meeting on the 6th of the 3rd month,
and took the names of all present, both men and women,
sending a list thereof by William Gordon, their agent, to the king`'s council.
He executed his commission with the utmost assiduity.
But shortly after he went from Aberdeen to Leith to hear a sermon,
in the time where of he was necessitated to go out
and at the end thereof was found dead.

Upon the solicitations of the said William Gordon,
the council sent a summons by a messenger to nineteen
of the said people to appear before them,
and fined them; the several fines being assigned to one Hugh Nelson,
an apothecary in Edinburgh,
while he was busy in a process at law for the recovery thereof,
a proclamation was issued by the king`'s commissioners and council,
remitting all penalties or fines for non-conformity,
except such as were already paid or secured.
This cleared the Quakers, for their principle prevented them from paying their fines,
or in any manner compounding for them.
Thus the malicious attempts of their adversaries were still frustrated.

The magistrates notwithstanding continued their application to the council;
and the priests strenuously solicited Archbishop Sharp`'s patronage;
alledging that the Quaker`'s schism was "`prejudicial to the interest of the church,
and that by using a separate burying place they prevented
the payment of the fees customary on these occasions.`"
But this complaint, when laid before the council,
was effectually obviated by the representation of the said people,
concerning the inhuman practice of their adversaries
in taking the dead bodies out of their graves,
as before related.
The council, upon hearing both sides,
did not think proper to interpose their authority in this case;
so the priests were dismissed, and returned home again, without attaining their purpose.

This year died Alexander Jaffray of Kingswell, who was born in the city of Aberdeen,
where he became in process of time a citizen of the first rank;
served the office of chief magistrate and was one of the commissioners
deputed to treat with Charles II. at Breda in Holland in 1673.
Being religiously inclined from his youth,
he early in life departed from the religion of his education,
and joined in fellowship with the presbyterians from conscientious motives;
but observing the difference of their conduct,
when they had wrested the government into their own hands,
from what it appeared to him when he first joined with them,
that instead of that apparent humility and detestation of persecution,
which they seemed to discover while suffering under it from the former powers,
they in their turn also betrayed a spirit of arrogance,
rigidness and intolerance towards others,
in the exercise of the power they had got into their hands;
from the like conscientious motive he left them, and went over to the independents;
but their ambition, their eager grasping at power and abusing it,
betraying the insincerity of their specious profession of purity in religion,
gave him such disgust that he left them also, And thus discovering,
in the various professions, more of the plausible appearance,
than the reality of pure religion,
he detached himself for some years from joining in any religious society,
walking alone in solitary anxiety until he heard of a people newly raised up in England,
who preached up the light, grace and good spirit of Christ in their own hearts,
as the most certain teacher and leader into all truth,
the tidings whereof gave him great joy.
And after deliberate inquiry concerning the tenets and manner of life of this people,
he felt his heart much possessed with sentiments in their favour.

In this disposition of mind he heard William Dewsbury,
by means of whose ministry and conversation,
being more fully satisfied that the practice of this
people corresponded with their profession,
as their principles did with truth, he joined them in society,
which nothing short of real conviction of the rectitude of their principles and practice,
and a persuasion of duty could have prevailed with him to do,
in a time and place where he was held in high repute and esteem,
and this people in as great contempt and (through misrepresentation) in disrepute.
So that in joining them his sincerity was put to a severe trial,
it being a cross even as bitter as death:
Yet for the preserving inviolate the testimony of a good conscience,
he was indued with fortitude to relinquish his power, honour and repute,
possessions of high estimation amongst men, for sufferings, contempt and persecution,
in order to embrace truth and procure lasting peace to his mind.

His defection from them alarmed and exasperated the priests,
who were almost incessant in their endeavours to excite the magistrates
to exert their authority to repress the rising sect;
the rank he had before held in their city, and in their estimation,
did not exempt him from his share in the sufferings
to which this people was exposed at that time;
but he stood faithful to his testimony to the last,
and valiantly contended for the truth he professed,
in sundry conferences with the bishop of Aberdeen, and the preachers of that city.

He was taken sick the latter end of the 4th month, 1673,
and during his sickness expressed his joy and comfort in that trying season,
"`that he had been counted worthy to bear testimony to,
and suffer for the precious testimony of Christ`'s inward appearance, by his light,
grace and good spirit, which convinceth of fin,
and that it was and would be the condemnation of many, particularly of the professors,
that they had flighted, despised and hated the light, and the witnesses thereunto.`"

He also left this prediction among his friends,
that a winnowing and trying time was coming among them,
whereby hypocrites should be discovered and made manifest,
but that a faithful remnant should be preserved, and brought through the fiery trial.
This was judged to be plainly verified in the sufferings,
which with in three years happened to the said people at Aberdeen.
He signified that the sting of death was taken away;
being through his mercy who loved him, made easy to him,
as a desirable passage to a better state: A little before his departure,
his expressions and the comfortable frame of his mind, expressive of his lively hope,
under the feeling of divine goodness, owning and supporting him in his last moments,
greatly affected those who were present, and soon, by a very easy passage,
he was removed out of this life,
and laid down his head in full assurance of a glorious immortality.

On the 14th of the 2nd month, 1675,
a public dispute was held at Aberdeen between Robert
Barclay and George Keith on one part,
and some students of divinity, so called, on the other: The occasion whereof was this,
Robert Barclay, in order to rescue the society, of which he was become a member,
from the odium under which they lay,
through misrepresentations of their principles from the pulpits,
as erroneous and heretical, published his Theses,
which were the groundwork of his apology,
giving a brief and plain account of the principles of the said people,
that the public might have a fair opportunity of
considering those principles candidly in themselves,
and not under the veil of misrepresentation, in which they were dressed by adversaries;
at the end of which he made a proposal,
offering to defend these principles in those places,
where they had been so misrepresented, and against:
those persons who had so often traduced them.
But none of these, viz. the public preachers, choosing to accept the proposal,
as beneath them to concern themselves therein, that is,
by a sober and fair discussion of these principles
to inform themselves what they really were,
although it was not beneath them to misrepresent them unknown,
and vilify those who professed them behind their backs,
where they could have no proper opportunity to vindicate themselves.
Therefore this method seems to have been pitched upon,
to select some from among the students, to take up the cause, as of themselves,
that if the Quakers should have the advantage, the consequence would be immaterial,
in a contest with young men.
The Quakers were under no obligation to join issue with these youths,
as it was not to them, but to the public preachers,
who propagated the misrepresentations, the proposal was made.
But as they were not afraid of meeting the greatest and ablest of their preachers,
so the truth, they thought, led them not to despise any,
who might be inclined to treat with them on the reason of their hope,
with the sobriety becoming the seriousness of the subject.
The dispute was accordingly held; but terminated, as such disputes generally do,
in tumult and disorder, the students handling serious subjects with unbecoming levity,
and vainly triumphing in a victory they had not obtained;
but having numbers on their side, used clamour and personal abuse,
by wounding them with clods and stones, arguments too hard for them to with stand,
finished the debate for that time.
But the result proved on which side the advantage lay, for four of the students present,
but not disputants,
were at that time so fully convinced of the reasonableness of the Quakers principles,
that they joined them in society.

The council at Edinburgh having issued a declaration,
reinforcing former acts of parliament against against conventicles,
and recommended the execution to the sheriffs and magistrates of corporations,
although the proclamation was expressly relative to such as were outlawed by the council;
yet the priests and rulers of Aberdeen made an handle thereof to oppress the Quakers,
whom they well knew to be none of the persons intended therein.
So rash and precipitate council was their malice,
that as soon as they had information of the council`'s declaration,
they had not patience to wait for the regular notification thereof;
but before it came into their hands, or was proclaimed at Aberdeen,
they took from the meeting, there, on the 12th of the month called March,
twelve of the members, and committed them to prison in the new Tolbooth;
and continued the like practice from time to time afterwards for the space of two months,
by which time they had increased the number of prisoners to thirty-four.^
footnote:[The Duke of Lauderdale,
one of Charles`'s ministers distinguished by the name of The Cabal,
a man represented tyrannical, vindictive and implacable,
was at this time vested with the character and the power of king`'s commissioner,
in which capacity he conducted himself with arbitrary sway,
and influenced the parliament to pass two acts,
which were of the utmost consequence to the civil and religious liberties of the kingdom,
By the one, it was declared,
that the settling all things with regard to the external
government in the church was in the crown.
That whatever related to ecclesiastical meetings, matters and persons,
were to be ordered according to such directions,
as the king should send to his privy council:
And that these being published by them should have the force of laws.
The other act related to the militia.
Lauderdale by degrees became absolute minister in Scotland,
and in 1670 had a severe law enacted against conventicles.
Ruinous fines were imposed both on the preachers and hearers in meetings held in houses;
but field conventicles were subjected to the penalty of death and confiscation of goods.
It is to be observed by these conventicles were principally meant the covenanters,
and that the Quakers (who were an inconsiderable number) did not esteem themselves included.
Hume.]

After some time the prisoners received a summons to appear before the Earl of Arrol,
the Earl Marshal, and Sir John Keith,
three of the privy council appointed commissioners to put in execution
the act of parliament made against the keeping conventicles,
before whom being called accordingly, a long libel was exhibited against them,
reciting the heads of the acts of the parliament convened the 18th of June 1670,
against conventicles and withdrawing from the public worship.
The libel being read,
was to be enforced by Patrick Hay (the only lawyer who could be
procured to plead against them) but his oratory failing him,
his plea was confined to this brief query, who gave you leave preach?
which, for want of pertinent matter, he repeated several times over.

The witnesses produced against the prisoners were partly divinity students of Aberdeen,
who came to their meetings on purpose to inform against them,
and partly the magistrates who took them into custody.
Against both these David Barclay objected, as insufficient evidence;
the former as parties in the crime,
and as having manifested themselves to be prejudiced persons by a late publication,
wherein they had maliciously and unjustly accused them of blasphemy and treason;
and the latter as being those who put the law in execution,
and therefore ought not to be accusers in the same cause.
The commissioners however over-ruled these objections,
and accepted the evidence of those witnesses.

The prisoners in consequence exhibited their defence in writing to the court;
signifying that they apprehended themselves not to
be comprehended in the acts recited in the libel,
as not falling under the description of those intended by the act;
the reason assigned for which being to prevent sedition and rebellion,
and for that part which prohibits field conventicles,
because they are termed a rendezvous of rebellion,
tending in an high measure to the disturbance of
the public peace did not comprehend them,
who are a peaceable people in principle and practice;
that they were well informed that when the act was framing,
inquiry was made whether the Quakers were to be comprehended in the act?
And that the Duke of Lauderdale said it was only to curb the presbyterians in the west.^
footnote:[While this appears as an instance of that absolute sway
which the Duke of Lauderdale had established to himself in Scotland,
over a parliament which was so abject as to frame and model their acts at his nod,
and adapt them rather to his will and pleasure than the public good,
it may appear perhaps also, as if the Quakers, to save themselves,
were pointing out these presbyterians as proper object of persecution:
But it is certain they were enemies to persecution in every shape,
against others as well as themselves; and although they thought it hard,
and not without reason, that they were not only punished by laws made against them,
but also by laws never meant against them;
yet they frequently declared that they envied none the liberty they enjoyed,
nor wanted the penal laws to be turned against any but wished
to all the full enjoyment of liberty of conscience.]
That the king`'s council did never execute any of the said
acts against any of their friends in that city;
nor in any place in the south and west of Scotland,
where there were frequent meetings of their friends in several places,
which had been held unmolested ever since the acts were made.
That although several of their friends were apprehended
and imprisoned upon the issuing of the late proclamation,
yet they were set at liberty a few days after, upon surety to appear when called for,
and have ever since kept their meetings, in Edinburgh particularly,
without being called in question by the council;
that they presumed therefore they would meet with
no other measure from the king`'s council there.
That the magistrates of Aberdeen had kept them near three months in prison,
without proper authority from any act of parliament cited or proclaimed since,
of which illegal restraint they hope the king`'s counsellors will take notice,
and prevent the like for the future.
That their meetings have no tendency to sedition, rebellion or violence;
but are held merely from duty to God,
who had forbidden them to forsake the assembling themselves together;
had commanded them to stand steadfast in the liberty wherewith Christ had set them free,
and to pray everywhere.
It was from conscientious persuasion alone that they durst not forsake their meetings,
and not out of any contempt of authority.

After an hour or two spent by the court in deliberation on this defence, the prisoners,
who had been ordered to withdraw, being called one by one, were severally asked,
whether they would oblige themselves not to go any more to meetings,
which every one of them refusing to do, they were again ordered to withdraw,
and after some time being called again, the sentence of the court was read to them,
whereby David Barclay, Alexander Gellie, Robert Burnet, Alexander Harper,
Alexander Skein,
Andrew Jaffray and Alexander Forbes were fined each in one-fourth
of their respective valued rents for their own keeping conventicles,
and an eighth part of their said valued rents each,
for withdrawing from the public worship.
Also the said Andrew Jaffray,
Alexander Skein and Alexander Harper to pay an eighth part for their wives transgressions,
conformable to the tenour of the act of parliament.
And the following, not being landed persons, were fined in the following sums,
Andrew Galloway, Thomas Mills George Keith 30£. each; William Sparke 40£.+++;+++
James Forbes 25£. and the rest twenty marks a-piece.
And over and above, John Skein and George Keith,
because they were found to have preached and prayed at these meetings,
were to find caution, under pain of five thousand marks, not to do the like hereafter,
or enact themselves to move out of the kingdom, conform to the tenour of the act.
And all to remain in prison until they made payment of their respective fines.

The sentence being read, the prisoners were remanded into prison,
where their number was increased by the repeated imprisonment of others of their friends,
from their religious meetings.
While they were kept here under close confinement,
some of them were concerned at times to preach to the people,
who would come up to the windows of the prison to hear them;
but the magistrates of Aberdeen, to prevent this, and to incommode the prisoners,
caused the windows to be nailed up for a whole week together,
and also removed several of them into the higher prison.
