== Chapter VIII.

[.chapter-synopsis]
* Robert Barclay applies to the King for relief
* Earl of Arrol requires Bonds, which the Prisoners refuse
* Ordered to pay their Fines to George Melvil
* Who makes excessive Distraints
* Distrains David Barclay`'s labouring Oxen, for which he can find no Purchasers
* George Skein, Provost, unreasonably severe
* Alexander Burnet, Bailiff, an active Accomplice in Persecution
* Receives Orders to remove sundry Prisoners to a more commodious Prison but declines Compliance
* Strait and hard Imprisonment
* Some ordered to be removed, and some released
* Their Treatment at Bamff more liberal and humane

During this time Robert Barclay being in London, and gaining admittance to the king,
delivered him a narrative of these proceedings,
and of the severity of the magistrates of this city to his imprisoned friends,
interceding with him to recommend their case to the
favourable notice of the council of Scotland,
which narrative the king ordered the Earl of Lauderdale to recommend to their consideration.
The council at Edinburgh referred it to their former
commissioners in conjunction with three others;
but the Earl of Arrol, who was president,
resolved their deliberations in this single inquiry of the prisoners,
"`Whether they were yet better advised than when they were last before them,
and would give bonds not to hold any more meetings?`"
In reply thereto, after pointing out the hardship of their imprisonment for seven months,
when no seditious act could be proved against them,
nor any other cause assigned than meeting in a peaceable manner to worship God,
they intimated, that they durst not be so unfaithful to God, as to give any bond,
whereby they should bind themselves not to worship him.
In the conclusion the Earl of Arrol repeating,
"`it seems then you will not give bond,`" John Skein answered,
"`let never that day dawn in which we shall be so unfaithful to the Lord:
But if any should prove so, let neither the king nor his council trust that man,
for he that is not faithful to the Lord,
will never be faithful to his king or country.`"

The Commissioners decreed they should pay their respective
fines to one Captain George Melvil,
and that upon paying they should be set at liberty;
and that in default of payment in the limited time,
the said Melvil was empowered to distrain them for the same,
and that when the fines were levied the prisoners should be released.
The Earl of Arrol, departing out of town the next morning,
all those who had been imprisoned since the rest were fined,
were released by the remaining commissioners.

Melvil soon after applied himself to the execution of his commission,
and from some took goods or cattle to double,
and from others to who makes treble the value of their respective fines.
Coming to John Skein`'s shop, under pretence that there were not goods sufficient,
though three times the value of his fine, he went to his dwelling house,
where entrance being refused him,
he applied to the provost for a warrant to break open his doors,
and next day came with smiths and hammers to break them open;
but James Skein went to the magistrates,
and made a legal protest against this proceeding, and that,
if the doors were broken open, they must expect to be accountable for the damage.
Whereupon they desired Melvil to desist, and seize on the shop goods,
which he did to the amount of 130£. by their own valuation;
all which were carried away to his house.
But his career was now stopped for a season,
being obliged to secrete himself from the messenger and
sergeants who were in quest of him for a just debt so that
he durst not appear till that demand was compromised.

When he had got this effected,
he returned to the prosecution of his commission in the like unreasonable manner;
he returned to John Skein`'s shop,
on pretence of the former seizure being defective and took away more goods,
taking in the whole 230£. for a fine of 100£.

In distraining David Barclay he exceeded his commission,
the said David living in the shire of Merns,
which was out of the precinct of the commissioners authority,
under whose warrant he acted, of which David was not wanting timely to apprize him.
But it looks as if officers of the lowest rank, as well as the highest, in this age,
thought it beneath them to regard the punctilios of law;
for he proceeded notwithstanding to execute his purpose
by adding one illegal act to another.
He took away ten labouring oxen,
in the plowing season (which was by act of parliament prohibited,
even in case of a just debt) with other cattle and corn.
But these cattle proved a troublesome acquisition,
for he could find no man that would buy them,
and the expense of keeping them was a continual burden to him;
so that he seems to have been tired of them,
before he could get them disposed of at any rate:
At last a remarkable opportunity presented itself to clear his hands of them.

The friends engaged,
looking upon themselves to have been unhandsomely treated
in the dispute they held with the students of Aberdeen,
and also in the reports thereof, published an account of it.
The students thought it necessary for their reputation to publish an answer,
which when they had completed,
they could find no printer who would undertake the publication at his own risk,
whereby they were obliged to let their performance lie dormant,
or print it at their own expense.
Having with some difficulty raised the money in hopes
of being reimbursed by the sale of the book,
they had the mortification to find almost the whole
impression left on their hands for want of purchasers.
In this dilemma they presented a petition to the commissioners, representing their lose,
and requesting some relief out of the Exchequer, which request,
through the archbishop`'s influence, they so far obtained,
as that the commissioners issued an order upon Captain Melvil,
to pay them a part of the Quakers fines in his hand;
upon which he gave them David Barclay`'s oxen,
which were at length sold to raise the money they wanted.

The magistrates of Aberdeen seem now for some time
to have been effectually brought over by the priests,
to exert their power in oppressing and persecuting this society.
But George Skein, the provost of the present year, even exceeded his predecessors.
in malice and cruelty to this people;
almost immediately upon his entering into office
he caused the prisoners to be more strictly kept,
debarring them the liberty of going into the lower council house,
a privilege which they had at times been permitted to enjoy before,
and threatened some of the officers with the loss of their
places for not acting up to the rigour of his orders.
And now observing that the loss of their substance did not deter
the members of this society from returning to their meetings,
he not only continued to send them again to prison,
but to render their imprisonment as severe and incommodious as he possibly could;
for which purpose he would frequently remove them from one room to another,
just to perplex them with the trouble of removing their bedding and utensils:
His evil disposition prompting him to be still more vexatious to them,
he made a proposition for petitioning the commissioners to give orders for the
close shutting up of all the prisoners in the higher part of the jail,
but he could not obtain the concurrence of the other
magistrates in that piece of cruelty.

During these transactions Patrick Livingstone and James Halliday, from England,
in the course of a religious visit to their brethren in this nation, coming to Aberdeen,
were there apprehended, and imprisoned in the upper prison,
where they had frequent opportunities, especially on market days,
to publish their doctrine out of the prison windows, and had more hearers,
than probably they would have had in their own meeting places,
so that even their confinement, designed to prevent it,
tended to promote the testimony they had to bear.
At this the provost and others of their adversaries were greatly exasperated,
and held several consultations upon the means to prevent it;
but were at a loss to devise any feasible expedient,
fearing to give umbrage to the people, who seemed desirous to hear them,
if they should proceed in any unusual method of severity against them.

Alexander Burnet, one of the bailiffs Aberdeen,
a man of like disposition with the provost,
and an accomplice in his persecuting measures,
being deputed to attend at a meeting of the commissioners,
seized the opportunity to apply his utmost efforts to incense them against the Quakers,
and to prevail with them to take some measures to prevent their
preaching to the people out of the windows of the prison.
The commissioners, willing to prevent the supposed danger of their preaching,
gave the said bailiff an order to remove Patrick Livingstone, George Keith,
Robert Barclay, John Skein and Andrew Jaffray out of the prison they were in,
to another out of the town, called the chapel, where the commissary courts, used to sit,
and where the prisoners might have better accommodation.
This order was in nowise agreeable to the views of the provost and bailiff,
whose aim was not to alleviate, but aggravate their punishment;
instead of procuring them ease, to incommode them in a greater degree; therefore,
although the order was issued in consequence of their solicitation,
they were not very forward to execute it: Instead thereof,
they set workmen to nail up the windows of the upper prison,
and stop up the very chinks that were made to let in light to the stairs.
Afterwards, when, in compliance with the commissioners order,
some of the prisoners were removed to the chapel,
which was intended for their better accommodation,
these ill-disposed magistrates contrived to make it as distressing as in their power,
by putting them into a cold, narrow, dark room,
where there was little more than space for their beds;
they applied for room to lay up a little firing,
and although it might have been well spared them, the provost refused their request:
A proposal was made for a window to give them light, which he rejected with indignation.

The case of those confined in the higher prison at the Tolbooth was yet more grievous;
They were so straitened for room,
that they were obliged to lay their beds one above another on boards.
The unwholesome closeness of the prison, its darkness,
the length of their hard imprisonment, greatly endangered their health and their lives,
in the opinion of the physicians.
Their relations, acquaintances and many of the sober inhabitants of the town,
commiserating their inhuman usage, applied to the magistrate to prevent the danger,
by removing them to the great room in the chapel; but this,
these two men of power for a year, would by no means admit of.

These magistrates,
perceiving that their undeserved cruelty in the treatment of these Quakers,
drew upon them the censure and disapprobation of the sober and humane part of the inhabitants,
endeavoured to palliate the persecution,
under pretence that they were represented by the ministers as seducers;
that they were popishly affected, and advancers of the interests of the church of Rome.
A pretence altogether false and groundless: and had they been so in reality,
in all probability they would have remained unnoticed and unmolested by those magistrates,
who at the same time were flattering and caressing the most eminent papists in the nation.

But that favour,
which could not be obtained by any solicitations from these subordinate magistrates,
was more easily obtained from their superiors.
The commissioners of the council, meeting again at Elian,
Burnet was again deputed to attend them,
who strenuously endeavoured to justify their proceeding,
under the false pretence that they had not room for their better accommodation.
But several persons appearing on behalf of the prisoners,
and representing the cruelty of their confinement,
the commissioners issued an order for the removal of part of the prisoners to Bamff,
and for the release of part of them from prison,
confining them to their own houses and parishes: These last said,
"`they did accept of their liberty; but as to the restrictions enjoined,
they should not esteem themselves under an obligation to submit thereto.`"
And those who were ordered to be removed to Bamff, being delivered over to the sheriff,
he also gave them their liberty,
on condition of their being forth-coming when he should appoint,
in order to be conveyed thither.

This deputy sheriff, John Forbes, was of a different temper from these magistrates,
whose severities have justly merited censure, for he was humane,
and utterly averse to persecution: Being obliged,
in pursuance of the order of the commissioners,
to take several of those who had been discharged,
and remove them to the Tolbooth at Bamff, he treated them with the utmost civility,
ordering a guard to attend them thither,
with directions to let them have all suitable accommodations on their way,
and to take their own time,
whereby they had the opportunity of several religious meetings,
where they had such remarkable service,
that some of their conductors were thereby effectually converted to the truth they promulgated.

At Bamff also they found the magistrates of a very different spirit from those of Aberdeen,
humane, liberal and courteous;
they not only gave them the best accommodation in their power, in the Tolbooth,
but also free permission to make use of an inn in the town at their pleasure,
for their better accommodation.
The said magistrates moreover used all their interest and influence with
the commissioners and sheriff to procure the release of the prisoners,
and ceased not,
until they obtained liberty for them to return again to their several habitations.

But the magistrates of Aberdeen had suffered their
spirits to be embittered against this people,
who had done them no wrong, to that degree, that neither the examples of others,
the plain dislike of the sober and moderate inhabitants,
the shame they had incurred by their cruelty, nor a regard to justice and equity,
had any power to move them to the sentiments of humanity.
They proceeded to imprison these people from their meetings again, and again,
and to render their imprisonment grievous,
even to the extreme danger of their health and lives.
They continued to be vexatious to them more or less for the space of three years,
until near the end of 1679,
by which time some of the bitterest of their adversaries were removed out of life,
or out of office, the priests, George Meldrum, John Menzies and William Mitchel,
one of them by death and the other two by law,
were deprived of their influence and silenced from preaching: The lord of Hudda,
who had threatened by his own authority to pull down their meetinghouse,
was turned out of his office.

The dismal catastrophe of Archbishop Sharpe,
of whom the priests and magistrates of Aberdeen made use, as their principal instrument,
by his power in the council, to crush the people called Quakers,
is too well known to be repeated here.
And it is probable their successors were men of more moderation and better tempers;
for from the time above mentioned the religious assemblies of this
society were held at Aberdeen (as they generally appear to have
been in other parts of Scotland) without molestation.

It may not be improper to add, that by the accounts they have left,
these prisoners at Aberdeen, in their deepest sufferings,
felt divine favour attending them, and the good hand of providence supporting them,
so that not only their spirits were kept cheerful,
but also their bodies preserved in health and strength,
under the most unhealthy confinement, beyond all human probability or expectation.
And even the malice of their adversaries became, against their wills,
subservient to the spreading of their doctrines,
by means of the opportunities they found of preaching from those prisons,
into which they were thrust on purpose to prevent them from preaching.
And that during the persecution the appointed meetings
were not only constantly held at the usual times,
but greatly increased in the numbers attending them.
