== Chapter IX. Ireland.

[.chapter-synopsis]
* Persecution in Cork, by Matthew Deane, Mayor
* William Penn interposes in favour of Friends--John Banks visits Wicklow
* The Priest endeavours to prevent his holding a Meeting there
* He is brought before the Governor, and virulently accused by the Priest
* Is committed to Prison, where he preaches to the People and discourses on religious Subjects
* A Meeting established there
* Friends present to Government their suffering Case in respect to Suits in Chancery
* Oliver Sansom`'s Account of the half Year`'s Meeting
* Account of Katharine Norton

This society still continued exposed to sufferings in the city of Cork; Matthew Deane,
who succeeded Christopher Rye in the mayoralty of that city,
being of the like persecuting spirit.
Samuel Thornton lodged at Elizabeth Erberry`'s, on his travels in religious service,
some friends came to visit him, where, as they were sitting together after supper,
the said Samuel, being concerned to pray, was overheard by some evil-minded persons,
who caused him to be taken by a constable, and carried before the mayor,
who committed him to prison, where he was confined eight weeks.

The same mayor caused George Webber,
Stephen Harris and several others to be sent from their meeting to prison,
with an order that they should have neither meat, drink nor bedding brought them,
and caused a maid servant of the said Stephen Harris,
who was carrying a bed to her master in prison,
to be set in the stocks and the bed to be taken from her:
And the said George Webber`'s servant carrying food to her master,
the mayor commanded his sergeants to take away the food, and set her in the stocks,
but she prevented them by hastening to the prison, before they could overtake her.

While Samuel Thornton was prisoner there,
many of his friends came on a first day of the week, and held a meeting of worship:
They locked them all in, being about eighty persons;
they were kept about twenty-four hours, having no food but what they drew up by a cord:
Under the room they were in, the soldiers kept guard, and having made a fire,
the smoke there of was like to suffocate them; upon which,
when application was made to the mayor, he scoffingly replied,
"`they are brothers and sisters, let them lie one upon another, and if they are choked,
it is their own faults.`"

On another first day, some friends going to visit the prisoners,
were by the said mayor`'s orders detained in prison, where they lay several weeks,
until released by the lieutenant and council.

This people were exposed to sufferings by imprisonment
and fines at this time on divers other accounts,
in common with their brethren in England, for their testimony against tithes,
for refusing to swear, for not observing the days called holidays.
William Edmundson,
who had frequently and successfully interested himself in behalf of his suffering friends,
was at this time travelling in America.
But William Penn coming over to Ireland this year,
frequently visited his friends in prison,
and omitted no opportunity he had with those in authority,
to solicit their favour in behalf of the sufferers.
And the half year`'s meeting, in the ninth month being held in his lodgings,
an account of the sufferings of the members of the society was drawn up,
in an address to the lord lieutenant, presented to him,
and an order of council obtained for the release of those who were imprisoned.

This year John Banks of Pardshaw in Cumberland came
over on a religious visit to his friends in Ireland.
He landed in Dublin at the low from beginning of
the half year`'s meeting in the 3rd month,
and after it was over, went from a particular concern to Wicklow,
to get a meeting appointed there the succeeding first day,
being a place where no meeting of friends had been kept before.
Notice of the meeting to be held that day being circulated over night,
the report that an English Quaker was come to preach
there raised a general curiosity in the people,
and great indignation in the priest of the parish; who, as usual,
applied himself to the secular power, one Hammond,
governor of the castle and commander of the garrison kept there,
to prevent the appointed meeting.
John and the Friends along with him took up their lodging at an inn, from which,
as they were about going out to the meeting,
the landlady with some concern entreated them not to go along the streets for
that there was a guard of musketeers waiting at the cross to take him,
and proposed to show them a back way: But John replied, I accept of thy love,
but I must not go any private way,
for I have a testimony to bear for the Lord in love to the people.
However, they passed along to the meeting unmolested; but were hardly well settled,
when a sergeant with a file of musketeers made his entrance,
and demanded him to go with them before the governor;
John inquired of him for his authority and his warrant; he held out his halbert,
and said this is my warrant.
He took him before the governor, with whom was the priest and others.
The priest was so disturbed with passion and bitterness,
that immediately upon his coming in, unable to repress his wrath,
he addressed himself to the governor in these reviling expressions, Sir,
this is the deceiver, this is the deluder,
that is come from England to delude the people;
I hope you will do justice and execute the law.
To this the governor, being a moderate man, made no immediate reply;
and John Banks thinking it most prudent to give time for his passion to vent itself,
forbore awhile making any remarks: But at length spoke to him in reply, thus,
"`Thou sayest I am a deceiver and deluder.`"
The priest interrupting him with great violence, cried, "`so thou art! so thou art!`"
John proceeded, "`Have patience, and let thy moderation appear,
and hear what I have to say in my own vindication,
for I shall not admit thy assertion as proof: I have had patience to hear thee:
Art thou a minister of Christ?`"
"`Yes;`" said he, "`I am`" John replied, "`but if I prove thee a liar,
as by the witness of this people thou art in charging
me with what thou canst bring no proof for,
thou art out of the doctrine of Christ, and of consequence no minister of his,
but of antichrist, and therefore thou art the deceiver and deluder of the people.`"
To which the priest made no reply.

Several people having pressed in at the door, out of curiosity, as is usual,
to hear the examination,
furnished John with an opportunity of opening to them the doctrine of this people,
and exhorting them to sobriety.
Yet the governor committed him and two more to prison; the jailer was very civil,
and allowed them the use of a room, and the people liberty of access to them,
to whom John preached the way of life and salvation,
and several were convinced by his ministry.
He was kept in prison three days, during which time he was visited by many people,
who came to discourse with him about principles of religion.
After his return to Dublin, from visiting his friends in the north,
he visited Wicklow again, being informed by a letter from thence,
that the people were desirous of another meeting, which,
notwithstanding the opposition of the priest, was held peaceably,
and a meeting was established in the town.

The government having on many occasions manifested
a regard to the application of this people,
by granting them redress in many cases of sufferings,
encouraged them about this time to present to their consideration a case
whereby they were liable to be greatly wronged in their property,
through the dishonesty of some people, with whom they had dealing.
The case was this: That as they had a conscientious scruple against taking an oath,
as being forbidden by Christ, such people caused them,
in case of claiming their just demands, to be subpoenaed into Chancery,
where their answers would not be admitted but on oath,
and by those means evaded the payment of their just debts; for instance,
in the county of Wexford,
Thomas Holme having about 200£. due to him from one Captain Thornhill,
for which judgment was obtained at common law,
was subpoenaed into Chancery by the said Thornhill,
where he well knew Thomas could not answer upon oath,
by which proceeding the Friend was defrauded of his debt.
And James Fade of Dublin, having about 40£. due to him from one Ezekiel Webb,
was by said Webb subpoenaed into Chancery, and because he could not answer upon oath,
he not only lost his debt, but 70£. more to get clear of the debtor.
But, it is like,
the government thought the subject of too much consequence
to comply with their request of redress,
not being as yet sufficiently freed from inveterate prejudice, to make such a concession;
neither was it in their power, I apprehend without an act of parliament,
to alter the settled course of proceeding in this court.
The members of this society continued exposed to such injuries,
until the reign of George I. when they were redressed
by an act of parliament in their favour.

Oliver Sansom from Berkshire came over from England
on a religious visit to his friends in Ireland,
and in his journal gives an account of the half year`'s meeting there,
whereby we may conceive an idea of the devotion of our ancestors in those days,
and the prevalence of divine power,
which through the dedication of their hearts to the divine will,
and their religious exercise therein, covered their religious assemblies.
He relates that after the previous meeting of worship,
they met as usual in the meeting of discipline,
to deliberate on the affairs of the church;
but the power of the Lord was felt so mightily amongst them,
and their minds so raised thereby, into acts of solemn worship, in testimonies,
prayer and praises to the divine being,
that no time remained to enter upon the business of the day.
When they met the next day for the same purpose,
their meeting of business was again converted into a meeting of worship,
from the same cause.
That the third day of the meeting they proceeded to the business thereof,
which took up that day and part of the next, when it was concluded,
having been transacted in much unity and harmony.

In the year 1678 the meetings of this people were visited by Katharine Norton,
whose maiden name was McLoughlin; she was born of Irish parents, near Colerain,
from whence she was sent to Londonderry for education: While she lived there,
a ship coming to that city, to take in passengers for Barbados, she embarked in it,
and arriving at that island, was some time after married there.
When that island was visited by George Fox and others,
she was convinced by their ministry,
and afterwards became herself an able minister in this society.
She visited the meetings of her friends in the north; preached in Lurgan market in Irish,
and had several meetings near Colerain, where her relations lived.
From thence travelling southward, as far as Dublin, she took shipping there for England.
The character given of her is,
that she was a woman well qualified for the service in which she was engaged,
being of a sound judgment, copious in matter, fluent in expression,
and agreeable in her utterance; had of her own to distribute,
and did not make the gospel chargeable.
