== Chapter X. Holland and Germany.

[.chapter-synopsis]
* Sundry Friends pass over to Holland
* Meetings of Discipline established there
* Robert Barclay and William Penn visit Elizabeth, Princess Palatine, and the Countess of Hornes
* William Penn travels further into Germany
* Writes to the Prince Palatine in favour of his Friends
* The Vaught having heard William Penn preach, refuseth the Priest to suppress the Quakers
* Epistle from the Princess to William Penn
* William Penn visits Labadie`'s Disciples Goes to Embden, and solicits the Burgomaster in favour of his Friends Returns to Herford
* These Friends return to England.

Soon after the conclusion of the yearly meeting at London in the year 1677, George Fox,
William Penn, Robert Barclay, George Keith, and some others,
went over to Holland to visit their friends in the
United Provinces and some parts of Germany.
From Harwich they had a prosperous and easy passage to Briel, where they landed;
from whence they went directly to Rotterdam,
where they were received by their friends with gladness,
and had two meetings with them and many of the town`'s-people;
and after spending another day in visiting their friends,
George Fox and William Penn proceeded to Amsterdam,
taking a meeting in their way at Haerlem, which proved very large and satisfactory,
after which meeting they went to Amsterdam,
to be present at the quarterly meeting to be held there the next day,
for the meetings of that city, Haerlem and Rotterdam,
to which Robert Barclay and the other friends they left there,
came directly from the last-mentioned place.

As the friends in Holland had only had a general advice
in writing respecting the establishing meetings of discipline,
George Fox and William Penn found occasion to explain the subject more fully,
and to show them the nature, end and use of yearly,
quarterly and monthly meetings of men and women.
Next day they had a large public meeting, in which the people were attentive and sober;
and the day after, a select meeting,
wherein by joint agreement were settled monthly and quarterly meetings,
and a yearly meeting to be held at Amsterdam for the United Provinces,^
footnote:[About the year 1662 some persons in East Friesland were
convinced of the truth as professed by the people called Quakers.
The papists, alarmed at the intelligence thereof, convened a synod of ecclesiastics,
which drew up a petition to the court, in which were the following expressions:
"`Whereas the wicked sect of the Quakers are found in these United Provinces,
and also sprung up here in East Friesland, you are desired to watch against it in time,
that, that devilish error might not creep in farther.`"
This petition procured a proclamation from the civil magistrate,
forbidding Quakers to come into the country,
under penalty of being confined to hard labour in the rasp-house for five years, etc.;
but the law being found inconvenient was not long after repealed.
{footnote-paragraph-split}
About 12 years after,
the senate and council of the city of Embden were influenced by the popular prejudices,
which, through the subtle and false insinuations of the priests,
were spread and promoted, to put in practice much severity against this people,
some of whom were cruelly beaten, some banished, imprisoned in a dungeon,
fed only on bread and water,
fined in greater sums of money than they were thought able to pay.
William Penn ever ready to advocate the innocent cause of his afflicted brethren.
wrote a very pathetic letter to the senate and council of that city in Latin,
in behalf of his persecuted friends.
But the persecution there continued several years after, until the year 1686,
when the magistrates perceiving their error, put a stop to persecution,
finding by the decay of their trade the pernicious
consequence of compulsory measures in religion;
they opened their eyes to their true interest, and instead of banishing useful citizens,
published an invitation to Quakers as well as others to reside in their city,
signifying they had resolved to give them free liberty to live, trade and traffic there,
which grant they offered to confirm under the seal of their city.]
Embden, the Palatinate,^
footnote:[In the year 1657 several persons were convinced
of the doctrine of the people called Quakers about Crisheim,
in the Palatinate, through the ministry of William Ames and George Rolfe; they also,
through the instigation of priests, were abused by the rabble,
and punished by fines and imprisonment by the magistrates;
'`till at the intercession of William Ames,
the prime superseded the orders of the inferior magistrates,
and gave liberty to Quakers to travel in his country or reside there.]
Hamburgh,^
footnote:[At Hamburgh some of the inhabitants made public
profession of the principles of the people called Quakers,
upon which account they were banished the city, and retired to Altena,
where the magistrates would not admit them, but drove them out of their town;
whereupon returning to Hamburgh, they were punished with a very severe imprisonment,
put in irons, debarred from company, and otherwise hardly treated,
to force them to leave the city;
during their imprisonment the wives of some had been
persuaded to remove in to other dominions;
others continued in the city,
and it doth not appear they met with any further molestation.]
Dantzick,^
footnote:[At Dantzick were a few who were convinced in 1677,
which no sooner became known to the magistrates than they imprisoned them,
and afterwards procured an order of senate to banish them,
and they were accordingly sent away.]
and other places in or bordering upon Germany.

The quarterly meeting at Amsterdam being concluded,
the friends from England separated on their respective services.
George Fox spent some days at Amsterdam in visiting his friends there,
and assisting them in some business relating to their meetings;
and afterwards travelled through N. Holland, into the northern parts of Germany,
to Embden and Hamburgh, holding meetings with friends and others as opportunity offered.
William Penn, Robert Barclay and George Keith set forward towards other parts of Germany,
with a particular view to pay a visit to the Princess Elizabeth, daughter to Frederick,
Prince Palatine of the Rhine, sister to Sophia, Dutchess of Hanover,
and aunt to King George I. who being, beyond most of her rank,
under a solicitous concern of heart to seek after and acquire
an acquaintance with that pure and undefiled religion,
whereby future happiness is attained to,
a correspondence by letter had commenced between her and William Penn;
George Fox also wrote her an encouraging epistle by his step-daughter, Isabella Yeomans,
who in company with George Keith`'s wife paid her a visit about this time,
to which she returned the following answer:

[.embedded-content-document.letter]
--

[.salutation]
Dear Friend,

I cannot but have a tender love to those who love the Lord Jesus Christ,
and to whom it is given not only to believe in him, but also to surfer for him;
therefore your letter and your friends visit have been both very welcome to me.
I shall follow their and your counsel, as far as God shall give light and unction,
remaining still,

[.signed-section-closing]
Your loving friend,

[.signed-section-signature]
Elizabeth.

[.signed-section-context-close]
Herford, the 30th of August, 1677.

--

William Penn and Robert Barclay proceeded to Herford, the residence of the Princess,
by whom they were kindly received.
She had with her as a companion, a woman of quality,
who also was influenced with an earnest desire after the attainment of pure religion;
her name was Anna Maria de Hornes, Countess of Hornes, an adherent of John Labadie.
The first meeting they had with them was in one of the princess`'s apartments,
to their great satisfaction.
After which the Countess expressed a wish that a meeting might be held,
where the inferior servants of the Princess`'s household might have free access,
to partake of the benefit of their doctrine.
With this proposal they were ready to comply, and the Princess willingly consenting,
the meeting was held accordingly.
The Princess did not appear in that meeting,
in order that her servants might not be discouraged by her
presence from giving their attendance in a general way;
but after the meeting expressed much satisfaction
in their being favoured with that good opportunity.
She detained William Penn and Robert Barclay to supper,
although they modestly endeavoured to excuse themselves,
proposing to return to their inn;
but as they could not handsomely resist her pressing solicitations,
they consented to stay.
The next day, being the first of the week,
and another meeting being agreed upon between them and the Princess,
William Penn desired that not only as many of her own family,
but as many of the town as were desirous, might be admitted.
To this she readily consented,
which afforded William Penn and Robert Barclay an open opportunity
to propagate the doctrines of the gospel,
and discharge the service they were engaged in.
Through divine favour and assistance,
the opportunity proved remarkably relieving to them, and edifying to the auditory.
At the conclusion the Princess taking William Penn by the hand,
in an affecting manner expressed her sense of the divine
power and presence evidently felt amongst them;
but her feelings were too affecting for utterance, for attempting to proceed, she cried,
"`I cannot speak to you, my heart is full.`"
William Penn, in sympathy with the sensible impressions upon her spirit,
imparted tender counsel, from his feeling sense of the state of her mind,
and then taking leave of her,
she expressed her desire of further opportunities of the like kind, saying,
"`Will you not come hither again?
Pray call hither as you return out of Germany.`"
To which he returned answer, "`We are in the hand of the Lord,
and moving under his requirings, cannot so fully dispose of ourselves.`"
There was also a French woman of quality with the Princess,
who had imbibed the prevailing sentiments concerning the Quakers,
looking upon them in a contemptible light; but being powerfully reached,
and deeply affected under the heart-tendering ministry of these experienced preachers,
she became very affectionately kind and respectful to them.
Upon their departure from Herford they separated; Robert Barclay returning to Amsterdam,
and William Penn travelling farther into Germany to Cassel and Frankfort.
Here he had several meetings with persons of note,
amongst the rest one at the house of a young woman of noble birth,
Johanna Eleanora Merlane, who was so reached by his doctrine, that she said,
"`Our quarters are free for you; let all come that will,
and lift up your voices without fear.`"

From Frankfort he went to Chrisheim, where a body of his friends dwelt,
who afterwards removed among the first emigrants to Pennsylvania, and settled there;
and finding them subject to sufferings both on account of their tithes,
which were claimed from them, both by the protestant and popish priests,
and also on account of the religious meetings,
which the vaught or chief magistrate endeavoured to prevent their holding,
William Penn went to Heidelburg to intercede with the Prince Palatine in their favour;
but his absence at that time deprived William of
an opportunity of making his personal application,
he addressed an epistle to him in their behalf, which, with other applications,
had a good effect upon this prince, who seems to have been no friend to persecution.
William Penn returned to Chrisheim, and being at a meeting there with his friends,
the vaught indulged his curiosity to go to hear him,
taking his stand at the back door that he might not be seen; and William`'s Penn,
regaining his assent and approbation, he afterwards told the parson,
who had endeavoured to persuade him that it was his duty to suppress heresy,
That it was his business, if the Quakers were Heretics, to discover them to be such;
but for my part, continued he, I heard nothing but good and sound doctrine,
and therefore I will not meddle with them.
William Penn having discharged his duty here, returned by Frankfort, Cologn, Cleves,
etc. to Amsterdam.
At Cologn he received the following letter from the Princese Elizabeth,
in answer to one he had written to her from the Palatinate:

[.embedded-content-document.letter]
--

[.signed-section-context-open]
The 4th of September, 1677.

[.salutation]
Dear Friend,

I have received your greetings, good wishes and exhortations, with much joy,
and shall follow the latter as far as it will please
our great God to give me light and strength.
I can say little for myself, and can do nothing of myself;
but I hope the Lord will conduct me in his time, by his way, to his end,
and that I shall not shrink for his fire.
I do long for it; and when he assures my ways,
I hope he will give me power to bear the cross I meet therein;
I am also glad to hear the journey hath been prosperous
both in the constitutions of your bodies,
to withstand the badness of the weather, and in the reception you had in Cassel,
Frankfort and Chrisheim.
Nothing surprised me there but the good old Dury,
in whom I did not expect so much ingenuity, having lately writ a book,
entitled [.book-title]#Le veritable Chretien,# that doth speak in another way.
I wish to know what reception you have had at Fredericksburg,
and if this find you at Cleves,
I wish you might take an occasion to see the two Pastors of Mulheim,
which do really seek the Lord, but have some prejudice against your doctrine,
as also the Countess there.
It would be of much use for my family to have them disabused;
yet God`'s will be done in that, and all things else concerning

[.signed-section-closing]
Your loving friend in the Lord Jesus,

[.signed-section-signature]
Elizabeth.

--

From Amsterdam William Penn went into Friesland,
and met George Fox at Leewarden in his return to Holland.
From whence he proceeded to Wiewert, where a society of the disciples of Labadie resided.
Here he had an interview with Anna Maria Schurman, the Somerdykes, the French Pastor,
Peter Yvon and others.
In their conference Yvon gave the following account of Labadie:
That he received his education among the Jesuits, deserted them,
and embraced the Protestant religion;
that being dissatisfied with the formal Protestants,
he with some adherents formed themselves into a separate society.
Afterwards Anna Maria Schurman, the Somerdykes and others,
related something of their religious experience,
and the means where by they were induced to join that family, retired from the world.
When they had done, William Penn,
who with his fellow-labourers had under taken this journey solely
with the view of discharging their duty in propagating pure religion,
and to encourage an advancement therein, condescended, in compliance with their practice,
to give an account of his convincement,
and thence took occasion to persuade and instruct them to pursue after superior attainments,
and additional growth in the experience of the true knowledge of God,
and more perfect obedience to the law written in the heart.
At parting, one of their pastors inquired of him,
if the truth rose not first among a poor and illiterate sort?
"`Yes,`" replied William Penn,
"`and it is our comfort that we owe it not to the learning of this world.`"
The pastor rejoined, "` Then let not the learning of this world be used,
to defend that which the spirit of God brought forth,
for the mixture thereof will be apt to obscure the brightness of your testimony.`"

William Penn having taken leave of them, travelled by Groningen to Embden,
where his friends laboured under severe oppression by imprisonments and banishments:
He had before interested himself on their behalf in a spirited letter to the magistrates,
showing the unreasonableness of Protestants,
who protested against impositions and persecutions,
themselves imposing their religion upon others by persecution.
And now he waited upon the burgomaster at his house and inquired of him,
if he and the senate had not received a letter in Latin from an English
man concerning their severity towards the people called Quakers?
the burgomaster owning the receipt thereof, William Penn said, "`I am that man,
and I am constrained in conscience to visit thee on their behalf.`"
The burgomaster was more complaisant than was expected,
and gave some faint hope of changing their measures;
but the sequel discovered the aversion of the senate to moderate their proceedings,
for the persecution was continued there a considerable time after.

From Embden, William Penn returned back kindly to Herford,
and met with a very kind reception from the Princess and the Countess of Hornes,
with whom he had a meeting in the Princess`'s apartment more than once;
when the deep impressions made on her mind,
through the affecting power attending his ministry, drew from her this acknowledgment,
"`I am fully convinced; but oh, my sins are great!`"
Hereupon William Penn took an opportunity to impart to the Princess and Countess,
separately, such counsel as appeared to him suitable to their respective conditions,
which had a reaching effect upon their minds,
especially the Countess`'s. At the Princess`'s pressing invitation he stayed to supper.
When the Countess from the present religious impressions on her mind,
perceiving the hurt accruing from those compliances with the world,
to which her rank in life accustomed her, said, "`Il faut queje rompe, I must break off:
Oh the cumber and entanglements of this vain world! they obstruct all good.`"
The Princess also made this sensible reflection,
"`It is an hard matter to be faithful to what one knows;
I fear I am not weighty enough in my spirit.`"
The favourable opinion she had conceived of William Penn`'s ministerial labours,
in consequence of the impressions she had felt under them,
is plainly expressed in the following remark which she made to him:
"`Among my books I have records that the gospel was
first brought from England into Germany,
and now it is come again.`"

Having finished his service here, and taken a solemn leave of these eminent persons,
he departed for Wesel: On his way he endeavoured at Mulheim,
to procure an interview with the Countess of Falkenstein,
who had the reputation of a very religious person,
on which account the Count her father kept her in confinement, calling her Quaker,
though she had no correspondence with any of that society.
He had before used William Penn very roughly, when passing by his castle on his way,
he inquired of him and his friends from whence they came, and whither they w ere going;
to which they answered, they were Englishmen come from Holland,
and going no further in those parts than his town of Mulheim:
But as they did not take off their hats, he thereby perceiving they were Quakers, said,
"`We have no need of Quakers here; get you out of my dominion,
you shall not go to my town.`"
He immediately commanded some of his soldiers to see them out of his territory;
whereby William Penn and his companions were obliged to lie that night in the open air.
But the next day he writ to the said Count, and therein told him, "`For thy saying,
we want no Quakers here, I say, under favour, you do;
for a true Quaker is one that trembleth at the word of the Lord,
that worketh out his salvation with fear and trembling.`"
William Penn being now come again to Mulheim could get no opportunity
to accomplish his purpose of a conference with the Countess,
and therefore prosecuted his journey to Duisburgh, Wesel and Cleves,
holding conferences with religious people as he passed along,
and returned by Utrecht to Amsterdam, where George Fox had arrived before him.

Not long after, they returned for England,
and after a dangerous and tempestuous passage they arrived at Harwich;
and going from thence to London,
William Penn received there the following letter from the Princess Elizabeth,
in answer to one of his.

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Herford, Oct.
29, 1677.

[.salutation]
Dear Friend,

Your tender care of my eternal well-being doth oblige me much,
and I will weigh every article of your counsel to follow it as much as lies in me,
but God`'s grace must be assistant, as you say yourself,
'`he accepts nothing that does not come from him.`'
If I had made me bare of all worldly goods, and left undone what he requires most,
I mean, to do all in and by his son,
I shall be in no better condition than at this present.
Let me feel him first governing in my heart, then do what he requires of me;
but I am not able to teach others, being not taught of God myself.
Remember my love to G. F., B. F., G. K., and dear Gertrude.^
footnote:[This was Gertrude Dericks, who had visited the Princess,
and afterwards came to live in England, and was married to Stephen Crisp.]
If you write no worse than your postscript, I can make a shift to read it.
Do not think I go from what I spoke to you the last evening;
I only stay to do it in a way that is answerable before God and man:
I can say no more now, but recommend to your prayers,

[.signed-section-closing]
Your true friend,

[.signed-section-signature]
Elizabeth.

[.postscript]
P+++.+++ S. I almost forgot to tell you,
that my sister writes me word she had been glad you had
taken your journey by Osenburgh to return to Amsterdam.
There is also a Drossard of Limburg near this place,
(to whom I gave an exemplar of R. B`'s Apology) very
desirous to speak with some of the Friends.

--
