== Chapter XI.

Account received of the continued Persecution in New England.--Public
Affairs.--Party Animosities increase.--New Parliament not suddenly convened.--Party
Distinctions.--Petitioners and Abhorrers.--Whig and Tory.--George Whitehead
and Thomas Burr imprisoned and prosecuted at Norwich by Francis Bacon,
Recorder.--Informer disappointed.--Major Part of the Magistrates moderate.--The Recorder
displaced.--Whereby they obtain their Release.--Sufferings continued.--George Fox`'s
Declaration.--Fresh Application for Relief from Acts against Popish Recusants.

George Fox, on his return to London, received letters from New England,
with an account of the renewed cruel proceedings
of the magistrates against his friends there.
It is probable the present severe persecution in England,
discovering them to have no patrons in the English government at home,
but that the king and court, by connivance at least, if not by open encouragement,
left them exposed to the arbitrary abuse of every inferior magistrate,
might give new vigour to the malignant enmity of their adversaries in New England,
as removing their apprehensions of being called to account
by the government here in their present disposition,
for any severities they might inflict upon this people
within the limits of the king`'s prohibition.
So they proceeded not only to whip the Quakers, so called,
but also some masters of ships, that were not of that society,
only for bringing some of them thither.
But the Indians about this time making an inroad upon them,
and slaying several of their people, diverted their attention,
to remove from them a more formidable enemy than the people called Quakers.

There was yet no relaxation of the persecution of dissenters in England;
but the rigour where with they were treated received
new force every succeeding year of this reign.
Such was the fierceness of parties against each other,
and so generally was the nation divided, that there was no class, but what either was,
or was reckoned, of one party or the other.
And although the general history of England be out of my line,
yet a view of the state of the nation appears occasionally requisite to
elucidate the history of that part of it in which I am engaged.

Although a new parliament was elected early in the last year, yet, as the elections had,
in very many places, been carried against the court interest, the king,
fearing the like opposition from this as he had experienced
from the latter sessions of the last parliament,
was not hasty in convening them, but had prevented their sitting by sundry prorogations.
The interval betwixt the dissolution of the late
parliament and the convening of this for business,
increased the jealousy of that part of the nation,
which had entertained suspicions and fears of the designs the court;
these distrusts excited many corporations to present
petitions to the king to assemble the parliament;
and notwithstanding the king`'s displeasure thereat,
and his publication of a proclamation prohibiting them,
petitions were sent up from all parts, earnestly soliciting for a session of parliament.

The king and his partisans,
finding his displeasure and his proclamations ineffectual to put a stop to the petititons,
had recourse to the like popular arts by which many of them were procured,
to procure petitions of a contrary tendency from divers parts of the nation,
expressing their detestation and abhorrence of the seditious practice of the late petitioners,
referring the sitting of the parliament absolutely to the king`'s pleasure.
This sharpened the edge of party rancour, and ranged the people into two hostile parties,
distinguished by the names of petitioners and abhorrers.
These names were soon lost, through virulence of party,
in the more reproachful distinctions of whig and tory,
appellations affixed to each party by the hatred of their adversaries,
the former being the name ot contempt applied to
the Scotch Covenanters of the last reign,
and the latter a denomination of infamy applied to the bands of Irish Robbers.

The former party distinctions were absorbed in these;
the low-churchmen and the country party were included among the whigs,
and as they were more moderate in their sentiments towards Dissenters,
and averse to persecution, the Dissenters inclined to them,
and were generally comprehended in this party.
On the other hand, the high-churchmen,
the court-party and the papists composed the body of the Tories:
these in the event had the ascendency during this reign,
having the court preferments on their side, and the king at their head;
to their superior influence the great severities,
to which the Nonconformists were exposed in the latter end of this reign,
seem principally owing.

As the people called Quakers were by principle disengaged from all political parties,
one might have expected they would have been less
obnoxious to the resentment of every party;
but they still continued to be harassed amongst the most hated classes
of Nonconformists with prosecutions by all the variety of penal laws.
The first we meet with in this year is the prosecution
of George Whitehead and Thomas Burr at Norwich,
principally carried on by Francis Bacon, the Recorder.

These two men being on their travels met accidentally
or providentially near the city of Norwich,
being both on their way from different quarters to pay a religious visit
to their friends in that city on the succeeding first day of the week;
where being arrived, they held the morning meeting without interruption,
and that in the afternoon, for about half the usual time,
when George Whitehead being preaching, a rude company, chiefly informers,
rushing into the meeting with tumult and violence, pulled him down,
who requiring them to show some legal authority for their proceedings,
received only abusive language from them, with an insinuation to the people,
that he might be a Jesuit.
The sheriff coming afterward took them prisoners; they were brought before the Recorder,
who was a justice of peace, who examined them, of their names, habitations and trades;
If they were in orders, or had orders from Rome.
Then questioning them about their preaching, demanded of them 20£. apiece,
with which refusing to comply, he next asked them,
whether they would take the oath of allegiance?
They replied they could take no oath for conscience sake.
While this examination was going on, the informer,
whose interest lay more in the convicting of them for their fines,
than upon refusing the oath, whispered the justice, who thereupon asked them,
where they lodged, and where they set up their horses?
In reply to which, giving the intelligence they wanted, the informer went off to the inn;
but was disappointed of his prey, the horses being, unknown to the prisoners,
removed from the inn where they left them.
The Recorder was very liberal of his invectives, terming them seducers and seditious.
And discovered the bitterness of his enmity by telling them there was a statute,
made in Queen Elizabeth`'s time, yet in force, to hang such persons as they were; and,
being interrogated, "`If he could prosecute them upon that law,`" he answered, "`Yes,
if the king should give orders to have it put in execution I would do it,
and have you hanged, if you would not abjure the realm.`"^
footnote:[The whigs (so called) were for confining
the prerogative within the limits of the law,
and therefore were suspected by their antagonists of adopting republican principles:
the other party, on the contrary, were for placing the king above the law,
or making the law subservient to his will,
of which this declaration of the recorder is an evident instance; for, according to him,
the laws were to operate, nor on account of their fitness or unfitness,
but the king`'s pleasure; to lie dormant or to be put in force,
not as being unjust or just, but as the king should issue his orders,
which is making them laws or no laws at the sole will of the king.]
He then committed them to jail '`till the ensuing sessions,
which were held about a month afterwards, when they were summoned to their trial;
and being brought to the bar, George Whitehead addressing himself to the court said,
"`We have been five weeks in prison, it is proper the court should know for what;
pray let our mittimus be read.`"
The Recorder replied, "` There is no need of your mittimus being read here;
I`'ll give an account of the cause.
They had gathered together a company of about two hundred,
and officers went from me to dissipate them but could not,
and thereupon I sent the sheriff, who took them away; and they being brought before me,
I proffered them, "`if they would pay their fines, I would not commit them;
and upon their refusal, I tendered them the oath of allegiance, which,
as they were not willing to take, I sent them to jail.`"
George Whitehead remarked,
that they being Englishmen had a right to travel in any part of the nation:
And Thomas Burr added that he being a person that was concerned in dealing in corn,
by the law of England he might travel from place to place about his concerns.
Upon which the Recorder made this taunting reflection,
expressive of his immoderate aversion to this people.
"`Had you not better have been turning your malt at home, than come hither to preach.
The scripture saith, God added to the church such as should be saved;
but ye draw from the church;
and the church of England will never be quiet '`till some of you be hanged.`"
George Whitehead then observing, how unbecoming it was,
and derogatory to his office as a judge,
to discover himself so plainly to be a party against the prisoners,
and to prejudge the cause before it was regularly before him as a judge;
and as a precedent, relating the circumspection of chief justice Hussey, who,
being applied to by the king for his opinion in the case of a traitor,
declined delivering it '`till it came judicially before him,
he defended his cause so well,
and represented the unequal proceeding of the Recorder in so clear a light,
that upon his appeal to the mayor and justices, the mayor replied,
"`You have appealed to me; truly we are tradesmen and no lawyers:
We leave matters of law to the Recorder:
He knows the law and we must acquiesce in his judgment.`"
The major part of the justices did not seem to approve of the Recorder`'s conduct,
but inclined to set them at liberty.
The recorder, piqued thereat, as a tacit censure on his conduct,
infilled upon administering the oath, and prevailed so far,
that both by the prisoners being discharged by the
court from the matter contained in the two mittimuses,
had the oath tendered to them,
and for refusal thereof they were committed again '`till the next quarter sessions.
As the recorder and his agents had endeavoured to
insinuate suspicions of their being probably Papists,
they procured certificates,
signed by the parish officers and several responsible
neighbours of their respective parishes to the contrary,
which they would gladly have had read in the court, but the recorder would not permit it.

Soon after the termination of the past sessions,
the recorder was deprived of his office by a vote of the common council,
and a person of more equity and moderation was elected in his place;
in consequence of which change, and the interposition of their friends,
at the next sessions they were cleared by proclamation,
and discharged from their imprisonment, after a confinement of sixteen weeks.

To recite the various cases of sufferings would appear
a needless repetition of similar occurrences;
in this year, as in the former, they were prosecuted for not taking oaths;
as Popish recusants; on the statute for the forfeiture of 20I a month,
or two-thirds of estates for absence from the public worship;
hunted and spoiled by informers;
subjected to excessive distraints for ecclesiastical demands;
run to excommunication in the bishop`'s court;
and imprisoned for contumacy (as it was termed) or on writs de excommunicato capiendo;
and notwithstanding their sufferings were severe enough this year,
yet the struggle between the contending parties,
into which we have observed the nation was divided, being yet undecided,
the sufferings of this year fell short of the succeeding years,
after victory declared for the court party.

The parliament, after a long interval, were suffered to meet, and when met, they went,
with the spirit of their predecessors, into an inquiry concerning the Popish plot;
and because some malicious episcopalians were very
forward to rank the Quakers amongst the plotters,
George Fox, who was then in London,
thought it necessary to publish the following declaration on behalf of himself and friends,
to remove such groundless suspicions from the parliament.

"`It is our principle and testimony to deny and renounce
all plots and plotters against the king,
or any of his subjects; for we have the spirit of Christ,
by which we have the mind of Christ, who came to save men`'s lives,
and not to destroy them: And we would have the king and all his subjects to be safe.
Wherefore we do declare, that we will endeavour, to our power,
to save and defend him and them,
by discovering all plots and plotters (which shall come to our
knowledge) that would destroy the king or his subjects:
This we do sincerely offer unto you.
But as to swearing and fighting, which in tenderness of conscience we cannot do, ye know,
that we have suffered these many years for our conscientious refusal thereof.
And now that the Lord hath brought you together, we desire you to relieve us,
and free us from those sufferings; and that ye will not put upon us to do those things,
which we have suffered so much and so long already for not doing; for if you do,
ye will make our sufferings and bonds stronger, instead of relieving us.

"`GEORGE FOX.`"

Notwithstanding the former applications on behalf of this society to the late parliament,
in regard to their sufferings as popish recusants,
and the favourable disposition of many of the members to yield them relief,
they were still exposed to ruinous prosecutions on the obsolete statutes of Eliz.
and Jac. 1. and sundry of their members being indicted this year as popish recusants,
the present disposition of the parliament to make
a distinction between these and protestant dissenters,
encouraged the people called Quakers to present their case to the king and parliament.
Representing their complaint against the late prosecutions
in the Exchequer for two-thirds of their estates,
which for two years last past had been seized into the king`'s
hands upon made old statutes made against popish recusants;
levies daily made thereupon by the sheriffs throughout many counties in England;
the unreasonableness whereof they proceed to demonstrate,
by a particular examination of the preambles of these acts, and the occasion thereof;
whereby they hoped it would evidently appear that
these statutes were enacted against recusants only,
and not against protestant dissenters, or any other than popish;
and that the prosecution of protestant dissenters (as it
hath been carried on of late) is a stretching of these statutes
beyond the bounds of reason and the intent of the law makers;
and,
the parliament having appointed a committee to make inquiry into
the prosecutions of protestant dissenters upon these statutes,
copies of the aforesaid case were not only presented to the members of the said committee,
but also supported by the personal attendance of sundry friends
of London or its neighbourhood upon the sittings of said committee,
particularly William Penn,
George Whitehead and William Mead of whom the committee inquired,

1+++.+++ If they owned themselves protestant dissenters?

2+++.+++ How they suffered by laws made against popish recusants?

To both which questions, answering to the satisfaction of the committee,
their treatment was generally resented as unjust and illegal,
in being prosecuted as popish recusants, when they were manifestly real protestants,
while the papists themselves were indulged and exempted from the penalties of these laws;
"`Though,`" (saith G. Whitehead) "`we envied not their liberty nor any people`'s else,
notwithstanding we suffered deeply in their stead.`"

In the course of the committee`'s conference upon this subject, Sir Christopher Musgrave,
though a zealous churchman,
expressed his utter dislike of the severe usage of this people,
acknowledging the prisons were filled with them,
that many of them had been excommunicated and imprisoned for small matters,
and that it was a shame and scandal for their church to
use the Quakers hardly on very trivial occasions.
