== Chapter XII.

[.chapter-synopsis]
* Bill for exempting Dissenters from Penal Laws
* Friends attend the Committee of Parliament to solicit on behalf of their Society
* Terms offered which would not relieve the people called Quakers
* The Bill confined to exempting Dissenters from 35 Eliz
* It passes both Houses, but is clandestinely suppressed
* Resolves in favour of Dissenters
* Persecution continued
* George Fox prosecuted for Tithes
* William Penn obtains a grant of hand in America

In consequence of these inquiries and the report of the committee thereupon,
a bill was brought in for exempting the protestant subjects dissenting
from the church of England from the penalties of certain laws;
being designed to enlarge the borders of the church communion,
so to comprehend one part of the dissenters,
and laws to grant a toleration and exemption from the penal statutes to the more scrupulous,
the Quakers particularly, upon condition of subscribing a declaration of allegiance,
and assembling with open doors.

Notwithstanding the people called Quakers were passive and patient under suffering,
yet they were not so insensible to the benefits of
their own ease in their persons and possessions,
nor to a sympathetic feeling for their friends under persecution,
as to neglect the favourable opportunity, now apparently presented,
for promoting the desirable liberty of conscience
for which they often pleaded and applied in vain.
Divers friends in London, when the bill was committed,
were diligent again in attending the committee early and late,
in order to solicit the insertion of such clauses as might
give ease to the tender consciences of their friends,
whose religious dissent was scrupulous in some matters beyond other dissenters;
and were so successful in their solicitations,
that beside an exemption from the penalties of the
laws against popish recusants and conventicles,
they obtained a clause to be inserted for accepting a declaration
of fidelity instead of the oath of allegiance.

The other bodies of dissenters were solicitous to obtain the privileges they desired;
the presbyterians, keeping an eye to the emoluments of the established priesthood,
wanted to be comprehended within the church;
others were content with a toleration of their religion.
And some of the members of the house being of the presbyterian and independent societies,
or favourers of them, offered terms for the ease of these societies,
which would have left the Quakers, so called, still exposed to persecution,
viz. the taking the oaths of allegiance and supremacy;
wherefore George Whitehead took an opportunity to confer with Colonel Birch and Alderman
Love (the members who had proposed the said terms (representing their proposal as quite
inadequate to the purpose of giving effectual relief to other conscientious dissenters,
as well as to the Quakers,
as he could not apprehend how they could take the oath of supremacy, and thereby swear,
That they solemnly declare and testify,
that the king`'s highness is the only supreme governor of this realm,
as well in all spiritual or ecclesiastical matters, as in temporal,
and at the same time dissent from the church of England;
thereby withdrawing their obedience from him to whom they acknowledge it owing,
which was an inconsistency he knew not how to reconcile.

Although this bill was committed, it was laid aside,
the time being not arrived for perfecting this laudable design,
yet a foundation was laid for reviving and completing
it in the succeeding reign of king William III.
At present the commons contented themselves with confining the proposed bill,
to exempting protestant dissenters from the penalties
of the persecuting statute of the 35th of Eliz.
before noticed more than once, for the repeated attempts to put it in force,
after lying dormant many years.
The repeal of this bill passed readily through the house of commons,
but is said not to have been equally precipitated through the house of lords;
the bishops yielding with reluctance to the rescinding this dreadful penal law,
as apprehending the terror thereof might be of service to their church,
their temper seeming more disposed to compel by terrors and penalties,
than to win by piety, persuasion and good example.
However it passed both houses,
and when it should have been presented to the king for his assent,
it was not to be found; having (as reported) been secreted by the clerk of the crown,
who had been privately directed by the king not to present it to him,
whereby this society, with other dissenters, were disappointed of their hopes;
and their endeavours to procure ease being eluded,
they were left exposed to prosecution by all the penal laws,
the effects of which they felt as severe as ever.

Thus were the nonconformists almost continually harassed during this reign,
and the church (so called) had the gratification of making
ample reprisals upon their antagonists and former oppressors,
for their sufferings under their hands:
For in all the struggling of parties these were the sufferers,
and the people called Quakers, who had merited no such treatment, suffered most of all.
The king repeatedly attempted to grant a general indulgence,
the benefits of which might extend to the papists,
but then parliament actuated by an equal aversion to nonconformists and papists,
opposed it with the weight of their influence;
and when the temper of the parliament was changed in favour of the dissenters,
their strenuous opposition to the court,
their unrelaxed perseverance in promoting the bill of exclusion,
and the supposed activity of the presbyterians in the elections of the obnoxious members,
and favouring the obnoxious measures of this parliament, had incensed the king,
who had no cordial regard to them before, still more against them;
he seemed resolved to keep them and the other sectaries, so called, in awe,
by keeping in reserve, and holding over their heads, this sanguinary law,
which subjected them to banishment or death.
The court bishops were more uniform in their conduct,
adding the weight of their exertions and suffrages
constantly on the side of preferment and persecution,
so that between the king, the bishops and the parliament,
they held their personal liberty and their just property by a very
precarious tenure through the extent of this reign.

The miscarriage of their favourite bill of exclusion,
which they apprehended to be the only effectual security
against the encroachments of popery,
as well as this repeal of 35 Eliz.
increased the mistrust which the parliament and nation
had entertained of the designs of the court,
and engaged them to enter into various measures and resolves,
equally offensive to the king, who thereupon resolved to prorogue them,
of which gaining intelligence,
previous to their prorogation the parliament passed sundry votes,
among which the following, however represented by some writers as the result of an angry,
factious spirit, must meet the approbation of all dispassionate men,
as being in themselves reasonable and just, viz.

[.numbered-group]
====

[.numbered]
1+++.+++ "`Resolved, that it is the opinion of this house,
that the acts of parliament made in reigns of queen
Elizabeth and king James against popish recusants,
ought not to be extended against protestant dissenters.`"

[.numbered]
2+++.+++ "`Resolved, that it is the opinion of this house,
that the prosecution of protestant dissenters upon
the penal laws is at this time grievous to the subject,
a weakening of the protestant interest, an encouragement to popery,
and dangerous to the peace of the kingdom.`"

====

These votes showed the sense of the commons, but did not repeal the penal laws:
They were still in full force,
and continued to be vigorously enforced upon great
numbers of this society for three or four years longer,
by magistrates,
who seemed now to meet with the countenance of their superiors
in proportion to their severity in executing these laws.
But still this persecuted people continued steadfast to their duty,
resignedly suffering the hardships under which unreasonable
men might be permitted to bring them,
for the trial of their faith and patience:
For they did not so much consider these occurrences, as arising from visible causes,
the public temper and state of the nation,
as refer them to the supreme cause and creator of all things,
who they believed ruled in the kingdoms of men; in his will they patiently acquiesced,
relying upon his providential arm for support in all their sufferings,
resting in hope that he would effectuate their release
in that way and time which he should see best.

George Fox, being still in and about London, was under a prosecution,
in which we have a fresh evidence of the avaricious
disposition of the claimants of tithes,
of the exorbitance of the tithe laws then in force and practice,
and of the disinterestedness of George Fox.
He and his wife were sued for small tithes in the Exchequer, and,
although they proved in their answer to the plaintiff`'s bill,
that no such tithe had been demanded or paid off her estate
during forty-three years she had lived there,
yet because they could not answer upon oath, they were run up to a writ of rebellion,
and an order of court was issued to take them both into custody.
George, understanding a warrant was out against him,
waited upon the barons at their chambers,
to lay the hardship of their case and the illegality
of the plaintiff`'s demand before them.
When the cause came to a trial, the barons declared their opinions,
that he was not liable to the tithes in question;
but the other two joining with his antagonist`'s lawyers,
pleaded earnestly for a sequestration, alledging he was a public man.
Here we have a fresh instance of the prevalence of that party-spirit,
which infested the nation at this time to such a
degree as to pollute the streams of justice.
What signified it to the merits of the cause, whether he was a public or private man?
However,
the adverse barons bringing over one of those who had before decided in his favour,
the sequestration was obtained, but with limitation to the sum proved due,
which greatly disappointed the prosecutor`'s aim,
which was to have obtained it without limitation,
that so they might be their own carvers in making distraint.
In the course of the trial,
it being made appear that George Fox had engaged
himself never to meddle with his wife`'s estate,
the judges could hardly be persuaded any man would be so disinterested;
until William Meade, who had given them the information,
produced the engagement under his hand and seal, which raised their admiration,
as being a specimen of self-denial rarely to be met with in these ages.

It was in the early part of this year that the king,
in consideration of the services of Sir William Penn,
and sundry debts due to him from the crown at the time of his decease, by letters patent,
bearing date the 4th of March, 1680-1,
granted to William Penn and his heirs that province lying
on the well of the river Delaware in North America,
formerly belonging to the Dutch, and then called the New Netherlands.
The name was now changed by the king to that of Pennsylvania, in respect to William Penn,
whom and his heirs he made governors and absolute proprietors of it.
This favour of the king is supposed to be principally
owing to the influence of the Duke of York,
with whom, as High Admiral of England, his father, Admiral Penn,
was a peculiar favourite, and who on his dying bed,
considering his son exposed to the danger of suffering for his religious principles,
recommended him to his protection, which the duke promised, and in general performed.
William Penn, from a principle of gratitude, in consequence of these favours,
was attached closely to the duke`'s interest, both during King Charles`'s life,
and after himself mounted the throne,
which drew upon him many severe censures and groundless jealousies,
as we may more particularly observe in due course of time.
