== Chapter XIII.

[.chapter-synopsis]
* Parliament convened at Oxford
* Which is soon dissolved, and succeeded by a severe Persecution
* Change of the Magistrates of London
* Informers encouraged
* George Whitehead informed against and fined
* Cruel Persecution in the City of Bristol
* Chiefly carried on by Sheriff Knight, Helliar an Attorney, and their Assistants
* Meeting-house greatly damaged, and many Persons grossly abused
* Meeting-house at Temple-street damaged in like Manner
* Rude Boys incited to assault the Women
* Helliar`'s vile Conduct
* The Prisons filled
* The Magistrates and Citizens disapprove these Proceedings
* The Mayor protests against the State of the Jail
* Certificates of the dangerous Condition thereof
* Solicitation to the King for Redress
* Order issued for their better Accommodation
* Disregarded by the Persecutors, who continue their Exertions in various Modes of Oppression
* Sufferings at Flamstead-End
* At Broughton, Leicestershire

The king soon after the prorogation of the last parliament dissolved it by proclamation,
and soon after convoked another to meet at Oxford,
which discovering the same temper with the late parliaments,
and persisting in prosecuting the bill convened at of exclusion,
notwithstanding any concessions or expedients the king proposed,
he was at last so provoked, that,
taking the advantage of a misunderstanding between the two houses in Fitz-Harris`'s case,
he abruptly dissolved them.

The non-conformists, through the remainder of this reign,
felt the severe effects of this dissolution, being exposed to the power of their enemies,
and deprived of the protection of a parliament that
was inclined to patronize their cause.
They had been for some time pretty much at ease in the city of London,
the magistracy and the citizens of that city, for the major part,
having connected themselves with the country party;
so that from the year 1672 we meet with few sufferings of our friends
in that city on any other accounts than ecclesiastical demands.
But, according to a late historian,^
footnote:[Smollet]
the king, finding his authority absolute, resolved to humble the presbyterians,
and gratified his revenge by the most unjustifiable methods,
to which he was instigated by the violent counsels of his brother.
The non-conformists were rigorously prosecuted on
the statutes enacted in the reign of Queen Elizabeth.
All the magistrates, judges, justices of peace, and lieutenants of counties,
suspected of leaning to republican principles, were displaced,
and their places filled with approved tories.
The clergy testified their devotion to the court by their writings and sermons.
The mutual animosities between the par ties were now inflamed to rage and rancour,
and the king placed himself at the head of a party.
The city of London still maintained their independency;
and the sheriffs influenced the grand jury in such a manner
as screened the dissenters of that capital from oppression.
To bring the city under the influence of the court, Sir john Moore,
the mayor of this year, had been gained over to the court interest,
who nominated two persons for sheriffs that would be acceptable to the ministry;
and although the citizens disapproved the nomination,
and elected two others by a large majority, the mayor, supported by the court,
forced his sheriffs upon the public;
and in the like irregular manner he secured a succession
in the mayoralty to Sir William Pritchard,
whom he knew devoted to the king`'s commands;
and in order to prevent all future opposition from the city, the next year the king,
on very slender pretences, wrested their charter from them,
and restored it only on condition of his having a
negative in the choice of their magistrates.

The recital of this change of the magistracy of London,
accounts for the reverse of the measures adopted in relation to the dissenters.
The informers, who had been for some time held in detestation by the citizens,
and discountenanced by the magistrates,
began now to return to their prey with fresh vigour and insolence,
under the encouragement of the court and its partisans.
They were lying on the watch in most parts of the nation to make a prey
of the people called Quakers (as well as others) wherever they had meetings;
and vile and infamous as their characters were, they received encouragement,
not only from persecuting magistrates, but from many of the clergy,
who esteemed them useful servants of their church,
to force conformity against conviction.
Several of the priests, even themselves, turned informers,
assisted in disturbing the meetings, and by their personal assistance,
as well as their countenance,
promoted informations ruinous to many innocent persons and families.

George Whitehead in particular soon felt the effects
of the change of temper in the magistracy of London,
being fined three or four times over in this and the succeeding year.
First 20£. by Sir John Moore, for preaching in a meeting in Grace-church-street,
for which he had taken from him goods in grocery ware out of his shop,
by James Holsworth, constable, and others,
to the value of 14£. 6s. 10d. according to the best
estimate the owner and others present could make.
Again, by warrant from Sir William Pritchard for the like fine,
he had his goods seized by the same constable and others,
to the value of 26£. (as the owner estimated) for the distrainers would not suffer
either an inventory to be taken or the goods to be weighed or appraised.
Upon the like pretence,
that George VVhitehead did take upon him to teach
in another meeting or conventicle held the 23rd July,
1682, at the Savoy in the Strand,
on a conviction made and certified by Sir Clement Armiger,
on the information of John Hilton and Gabriel Shad, informers, one Manby constable,
with three others,
came in a violent and furious manner and broke open the back door of his shop,
and several doors of the chambers of his house, seized all his beds and bedding,
a considerable quantity of other household goods and shop goods,
moderately valued at 33£. but neither would these
officers suffer an inventory to be taken,
or the goods to be weighed or appraised,
pretending the seizure to be for a fine of 40£.

Two of his friends, John Edge and Joseph Peckover,
quietly endeavouring to persuade these constables to moderation,
and to surfer an inventory of the goods to be taken before they were removed,
were apprehended by the said Manby, and prosecuted upon his evidence for a riot;
for which they were fined and committed to New gate, and confined there ten weeks,
to the great detriment of themselves and families, being men of considerable trade,
and Joseph Peckover being an inhabitant of Norfolk, and above eighty miles from home.

George Whitehead made his appeal against this last conviction,
and also against another made by Sir Thomas Jenner, Recorder of London,
for a fine of 20£. and upon trial was discharged upon both appeals;
but only recovered 11£. 9s. 6d. on the former,
Manby having fold all his goods for 15£. and returned the justice only the above sum.
The charge of prosecuting the two appeals amounted to 17£. 9s. 8d. so that he computed
his whole loss at 61£. 7s. besides the damage done to his house and goods.

Several others were in like manner despoiled in different parts of the city,
and in most parts of the kingdom;
but in the city of Bristol a persecution of the members of this society
broke out and was carried on with uncommon outrage and cruelty;
principally by the persevering malice of a few intemperate spirits,
who thrust themselves into office,
to distinguish their loyalty by an excess of injustice, and their zeal for the church,
by the enormity of abuse to their inoffensive neighbours;
or busily interfered in molesting, imprisoning and breaking up their meetings,
though invested with no legal authority.
The most distinguished names in this band of officers and informers were Sheriff Knight,
Alderman Ralph Olysse, junior, one Helliar an attorney, with their subordinate agents,
Lugge, Tilley, Casse, Patrick, Hoare, Watkins, Brand and Higgins.
They began under pretence of levying 5£. laid on the meeting-house in James`'s parish,
towards defraying the expense of the trained bands,
under colour whereof they took the seats, forms, stools and chairs,
breaking many of them, took away what they pleased, and burned the rest;
then they encouraged the boys to break the windows A few days after,
Knight and Helliar attacked the people in their peaceable meeting,
threw away the men`'s hats, beat Cananiel Briton an ancient man with a cane,
threw him down and bruised him very much, and afterwards sent him to Newgate.
They broke the galleries, and carried away the partitions of the meeting-house.
They plundered the dwelling of Elizabeth Batho, widow, threw out her goods,
broke her windows, obliged her to quit her house, which she held by lease,
and put another person in possession of it.
Afterwards they seized the meeting-house (as they pretended) for the king,
fastened up the door places with boards, and put in men to keep possession.

Having thus by violence taken possession of one meeting-house,
they proceeded to make the like devastation at the
other meeting-house of this people in Temple-street;
here they tore the windows and galleries to pieces
in so riotous a manner as to terrify the neighbourhood,
and after they raised these riots,
they accused the persons thus insulted and abused as the authors of them.
The damage done to the meeting-houses was computed at 150£. and
all this damage was done at the mere will of Knight and Helliar,
without any just cause or legal authority;
the pretence of charging these houses to the trained bands being
a plain fiction to palliate the illegality of their actions.
They usually were attended with a rabble of rude boys,
whose propensity to mischief and abusive behaviour they wantonly encouraged,
in defiance to every rule of decorum,
inciting them particularly to abuse the female part of the assembly,
even women of repute and consideration.
Helliar, as a signal to the boys to begin the attack, would call out to the women,
"`Have a care of your hoods and scarfs,`" upon which the boys would fall upon them,
and violently tear hoods and scarfs, and otherwise abuse them.
One of them impudently offering a gross indecency to a young woman of delicacy and spirit,
she gave him a box on the ear, for which Helliar sent her to Bridewell.
They took from seven persons in five days above 100£.`'s worth of goods,
fining some for the pretended poverty of others.
They prosecuted fifty as popish recusants, in order to run them to a premunire.
John Moon was committed to prison on the Oxford act, and Griffith Jones,
a trader from London, being taken at a meeting,
had the oath of allegiance tendered to him, at the motion of the bishop,
and for refusing it was sent to jail.
Helliar continued his unmanly insults on the female part of the congregation,
violating every sentiment of liberality and common decency, calling them whores,
tearing their hoods and scarfs as usual, dragging them out,
and sending some of them to Bridewell.
At Temple-street he confined the men and dispersed the women,
driving them as if he had been driving cattle.

Besides the plunder, and personal abuse to which they were subject,
several of them from time to time had been committed prisoners to Newgate,
where they were greatly incommoded, and their health endangered for want of room;
wherefore they represented their case in a petition
or complaint addressed to Sir Thomas Earle,
mayor, and the rest of the justices, where in they complain of being so straitened,
as to have nine beds in one room and seven in another, of thirteen feet square;
that although an order of sessions had been made for enlarging the prison,
it had not been complied with, and requesting,
for the preservation of their health and their lives,
that they would see their order obeyed.

The generality of the magistrates and citizens were more humane
than to approve of the cruel proceedings of these forward persecutors;
the mayor and aldermen seemed mostly disposed to comply with the request of the prisoners,
and declared their dissatisfaction at the state of the jail,
esteeming it an unfit and unhealthy prison,
of dangerous consequence to the lives of the king`'s subjects,
and required the late order of sessions to be put into execution; and Richard Lane,
one of the sheriffs, declared his willingness to yield obedience:
But it was refused and frustrated by sheriff Knight, who,
depending upon superior support in his rigorous measures,
seemed singly invested with power to control the
resolutions of the whole body of the magistrates.

The mayor, not without reason,
being piqued at this overbearing insolence of an inferior magistrate,
declared his resolution that all convictions should be public,
and not made in taverns and alehouses: He entered his protest against such convictions,
and against the jail, as absolutely unfit for such prisoners.
He afterwards demanded an account of the convictions made to that time,
which Knight refused:
Wherefore the mayor caused a record to be made of such demand and refusal.
The mayor further declared that he would have no more private convictions;
and that the goods distrained should be deposited in a public warehouse;
that he would have an account of the sale of them,
that they might be sold to their full value, and justly accounted for.
To be checked in the exorbitance of plunder, and tied down to any degree of justice,
was so highly displeasing to Knight and his band of informers,
that they threatened the mayor with the weight of their
opposition to his interest at the next election.

Instead of complying with the reasonable request of the prisoners,
and the order of the sessions,
these insulting persecutors persisted in incommoding them still worse,
by a continual crowding of the jails with fresh prisoners.
The next opportunity after their dispute with the mayor,
as if to show their contempt of all authority, but that whereby they were supported,
they sent forty-three more to Bridewell and forty to Newgate.

A certificate of their treatment here was certificate drawn up and published
by some of the citizens (not Quakers) who hearing of their inhuman usage,
accompanied sheriff Lane to view the prison,
wherein they declare it altogether unfit for the
uncommon number of prisoners crowded therein,
eighty-five whereof were of the people called Quakers,
who were unreasonably thronged to four, five, six, seven and nine beds in a room,
many necessitated to lie on the ground, in a filthy place, which had been a dog Kennel,
to the hazard of their lives,
which as the heat should increase might breed infectious distempers
to the endangering of the health and lives of the citizens at large.
But remonstrances from every quarter were ineffectual with men void of reason and compassion,
and solely intent on fully gratifying their unfeeling
disposition to vengeance and mischief.

When all rational and humane endeavours at home were
too feeble to give a check to their cruelty,
two friends, Laurence Steel and Charles Jones, junior,
took a journey to London to seek that relief, they could not procure there;
from the king and council,
the only body that were powerful enough to check
the enormities of these persecutors at Bristol.
They were assisted in their solicitations to government by George Whitehead.
Previous application was made to Prince Rupert, and the lord president, who,
discovering a compassionate concern at the unreasonable sufferings of their friends,
procured them at their request, an opportunity to lay their complaint,
the state of their hard usage and petition for relief before the king and council.
Several of the council being averse to the non-conformists,
rather discouraged and opposed their solicitations;
yet their pleading of the cause of the sufferers,
and clear exhibition of the illegality and injustice of the proceedings against them,
made that impression on the king and the generality of the council,
that an order was issued to the magistrates of Bristol
to allow the prisoners better accommodations,
whereupon some of them were removed out of Newgate
to another prison until they were released.

Notwithstanding this order,
their persecutors were in nowise discouraged from harassing them by all manner of abuse,
Helliar and Tilley tore Mary Hooper`'s scarf, and pushed her about to that degree,
that she was ill some time after.
Mary Page, wife of Francis Page, was violently pulled out of the meeting,
to the danger of her life, she being then far advanced in her pregnancy.
Having driven and haled them out of the meeting,
they encouraged the attendant rabble of boys to follow them in their abuse,
by pelting them along with dirt; Helliar, in his accustomed vulgar oratory,
saluting them with the mob-like appellations of ugly whores, bitches, jades and the like.
Thomas Lofty, an ancient man, not going out of the meeting as soon as they bade him,
Helliar delivered him to the boys to carry to Bridewell; they grievously abused him,
throwing him down several times in the dirt.

The imprisonment of this people was still extremely rigorous,
and all their treatment unreasonably illegal and unjust.
Three of the prisoners being dangerously ill,
could not obtain the favour to go home a little for the
preservation of their lives or recovery of their health:
When one of their wives was brought to bed,
her husband requested liberty of the keeper to go but for an hour or two to see her,
but his request would not be granted.
They could get no light of the information or convictions against them,
though they employed lawyers for that purpose; for the records were not in court,
but in the custody of Knight, Helliar, or their agents;
and it was with the utmost difficulty they could procure
copies of the warrants by which the distresses were made.

The repeated complaints of these prisoners to the magistrates,
of the straightness and noisomness of their prison,
gave occasion to several physicians to view and examine the state thereof,
who certified under their hands that the jail was so full and noisome,
and the prisoners so straitened for room to rest,
as had a tendency to the destroying and suffocating of them,
to breed infectious distempers, and to endanger the lives not only of the said prisoners,
but of the numerous inhabitants of the city.

The certificate of the physicians was treated with equal
disregard with the former representations of the citizens.
It seems these men, who appear to have usurped the government of the city,
paid as little regard to the disgust or censure of their fellow citizens,
as they did to law, equity or humanity: Depending upon the support of their superiors,
who doubtless on the whole countenanced their proceedings,
they set censure and contempt at defiance; for about this time the sheriff,
who was at the head of band, was advanced by the king to the dignity of knighthood,
a dignity which he appears to have acquired solely
by his violent prosecution of dissenters.

As the constancy of this people in the great duty of assembling to worship God,
while at liberty, was invincible;
so as a prison could not confine the freedom of their spirits,
or the impulse of their consciences,
they continued the practice of this duty in their imprisonment,
keeping up meeting and sitting down together in reverence and fear;
Being so assembled on the 30th of the month called March, Sheriff Knight, John Helliar,
Edmund Brand and the jailer fell furiously up on them,
and thrust them by violence out of the room, the sheriff protesting unless they departed,
he would put them in irons.
He commanded Roger Holland to be ironed, and put down into the West-house,
the place where condemned felons are usually put.
At another time, being assembled in the common hall, and one of them.
(Allen Hallmark) speaking a few words, the sheriff threw him headlong downstairs,
to the great hazard of his life, after which he was put into the West-house,
and continued there several days.

Friends were not only thus exposed to personal abuse and imprisonment,
but this body of informers, like the rest of their order,
had an eye to the emoluments of office, as well as the gratification of their malice.
From ten of this people fined 79£. 3s. 4d. they took goods to the value of 155£.
14s. 6d. and again for about 79£. they took money and goods worth 153£. and upwards.
Of their conduct in this respect we have the following
account in a letter from some of the sufferers.

[.embedded-content-document.letter]
--

They got into Richard Marsh`'s house and made sad havoc.^
footnote:[In a paper published under the title The
Devouring Vol. II. Informers of Bristol,
dated 22nd of April, 1682,
is the following relation of the havoc made at Richard Marsh s house.
{footnote-paragraph-split}
"`For these two days our old informers,
Mr. Helliar and company, viz. Luggs Tilly, Casse, Patrick, Hoare and Watkins.
and their assistants have been levying distresses upon several protestant dissenters,
and in the management of it behaved themselves with that fury,
and unparalleled degree of violence and arbitrary force,
that it fills our hearts with sadness.
Part of them (for they divide themselves into two bodies) that is Mr. Helliar,
Luggs and Watkins, with their assistant Summers the butcher,
came to the house of Mr. Richard Marsh,
who is known to be one of the most considerable merchants in this city.
These, entering his house, to make a distress for 10£.£. broke open his counter door,
and searched for money, and then went into an inward counter,
and there seized and carried away his journal, ledger cash and invoice books,
and several other books of accounts to the number of thirty, a bundle of written papers,
and several sorts of household goods: Not content with this,
they seized also the provision of victuals in the house, and carried them away,
except some victuals and drink, which they consumed on the place,
spending near three hours time in commanding his house, and ransacking several chambers,
particularly the chamber of his wife then lying in.
During this stay in the house their behaviour was so insolent that
they greatly affrighted not only his servants but all the spectators,
whom business or respect called to his house.
This gentleman, Mr. Marsh,
had formerly taken from him a ton of wine worth 20£. which was fold for 4£. and,
to make up the distress 10£. they forced into his man`'s counter and took from
him upwards of 6£. Their manner of levying the distress is as follows.
When they enter a shop, although there be abundance of goods in view,
yet they break open chests, counters, etc. and thence take away the money;
if no money to be found, then they take either shop or household goods,
and of them generally to double value.]
They took goods from others of our friends, of which we have no account yet,
nor is this account full,
as we may have occasion to mention more of the kind
as they are like to repeat their depredations,
having warrants, for 400£. The quarter sessions are to be next third day,
the bishop is come, and all things seem ready for our ruin.^
footnote:[By the apprehension of this bishop`'s arrival it
seems probable to me that he encouraged the persecution,
and perhaps it might be his support which incited Knight and his associates to their
illegal proceedings and to disregard the dissatisfaction of the other magistrates.]
But our hope is in the Lord, and we commend our cause to him alone.
These distresses are taken for a meeting whereat
was no preaching or praying that they pretend to,
or we can call to mind.

--

The quarter sessions being held in course, several of them were indicted,
found guilty and fined; but the justices, who were not insensible of their wrongs,
nor approved the proceedings against them, inclining to the favourable side,
discharged the greatest part, on promise of appearing at the next sessions;
and by their lenity the majority of the prisoners regained their liberty;
but they did not enjoy it long,
for Knight and Helliar immediately returning to disturb their meetings,
within two weeks after their release,
they committed several of them again to Newgate from their morning meeting,
and then nailed up the doors upon the rest, being fourteen men and eighty-seven women,
and kept them there six hours without any convenience for ease or refreshment.
Their goods were continually taken away for attending meetings, and to those,
who were thought to be men of good estates, the oath of allegiance was tendered,
in order to bring them under the sentence of premunire, and take away all at once.
And as it seems clear that such proceedings were countenanced or concerted by the court,
it is supposed,
that some of this people had given umbrage by giving
their votes at elections in favour of men of moderation,
who, they expected, would be no favourers of popery or persecution;
hints being reported to be thrown out,
that if Mr. Penn or Mr. Whitehead would undertake for the Quakers,
that they should not vote for parliament men,
there should be no further persecution of them.

This year John Whitehead, an eminent friend in the ministry,
of the East riding of Yorkshire,
was committed prisoner to Lincoln castle by justice Burrel, being accused as a Jesuit,
for preaching at a meeting,
and tried at the ensuing assizes at Lincoln before Baron Street;
but as that accusation could not be made good, the customary snare was resorted to,
of tendering the oath of allegiance, for the refusal of which he was indicted,
and though he pleaded ably against the unreasonableness
and illegality of accusing and trying him for one crime,
and then indicting him for another, he was convicted and premunired,
and in consequence cast into prison,
where it is supposed he was detained until the general release in 1686.

The persecution thus encouraged at court, constancy,
and carried on by magistrates devoted to the court party,
with all the rigour of a violent party spirit,
had in a great measure deterred the other classes
of protestant dissenters from keeping up their meetings,
or assembling publicly for worship;
and although many of their ministers had betrayed
an invidious disposition towards the Quakers,
and set them off in unjust and disagreeable colours,
to render them odious and ridiculous,
yet in their nocturnal meetings they would pray God,
that it might please him to keep the Quakers steadfast,
that they might be as a wall about them,
in order that other dissenters might not be rooted out.
And their steadfastness in suffering was such,
that some of their persecutors began now to despair of subduing them to their wills,
being heard to say, that the Quakers could not be overcome,
and that the devil himself could not extirpate them.
Several of their teachers, and particularly George Fox,
were much engaged by their exhortations and epistles
to encourage them to steadfastness and perseverance;
and what was really remarkable, many of those,
who travelled about at this time in the work of the ministry,
escaped the pursuit of the informers,
and accomplished their services without molestation.

Although I have been particular in the narration of the persecution of friends in Bristol,
yet persecution was not peculiar to that city,
but in most parts was carried on with great animosity.
At Flamstead-end in Hertfordshire, the justices and constables broke the forms,
galleries, windows and doors of the meeting-house all in pieces;
and after the door was repaired, they broke it again and burned it,
whereby they set fire to the chimney piece, to the terror of the neighbourhood;
and one of the justices, was heard to declare,
that if he could be sure it would burn nothing but the meeting-house,
it hould not be extinguished.
At Broughton Leicestershire,
endeavours were used by personal abuse and barbarous
cruelty to dissolve the meeting there.
The principal promoters of these abuses were William Cotton, priest of the parish,
and the parish officers,
who encouraged certain rude young fellows to insult and abuse the persons assembled.
Of these, two women, Elizabeth Hill and Elizabeth Hilton, were so grossly abused,
that the former was left for dead,
and the latter so hurt and bruised that she lay there near
three weeks before she recovered strength to go home,
about two miles.
When they were abusing Elizabeth Hill, and dragging her through the dirt,
some of the neighbours asking them, if they meant to kill the woman, they answered,
what care we, Mr. Cotton bade us.
As she seemed expiring, one of them said, let us see if her teeth be set; another,
putting his finger into her mouth, and, perceiving her breathe, said,
let us at her again, the devil is in her yet, and we will squeeze him out.
One of these youths, gathering up dirt, threw it in the face of Elizabeth Hilton,
then took a handful of dirt, and following her, caught her by the hood,
holding her behind the head with one hand,
cramming the dirt into her mouth with the other.
Being with some difficulty got into a neighbour`'s house,
and apprehended to be near expiring, the constable was sent for to keep the peace,
but he came not; but one of the youths coming in, upon seeing her, said,
I think she is dying indeed, but if she do, she is fitter for the devil.

The men, after being spoiled of their substance by one Smith an Informer,
had been almost all sent to prison by the instigation of the same priest.
This is indeed a remarkable specimen of the temper of too
many of these nominal pastors of the high-church party,
and the morals imbibed by their instructions.

Many more extraordinary cases of their sufferings might be produced in this year;
but we suppose the foregoing sufficient.
