== Chapter XIV.

[.chapter-synopsis]
* Seven hundred of the People called Quakers in Prison
* Persecution at Bristol continued
* Cruelty of Isaac Dennis, Jailer
* On his Deathbed is seized with Horror in reflecting on his past Conduct
* Persecution of Richard Vickris on the Statute of 35 Elizabeth
* Removed by _habeas corpus_ to the King`'s Bench Bar, and acquitted
* Persecution in London continues
* Persecution in Somersetshire

In the year 1683, persecution continued rather increasing in many places,
the number of prisoners of the people called Quakers in the different
parts of England being computed upwards of seven hundred.
But still that carried on in the city of Bristol seems as generally
affecting the members of this society as in any part of the nation,
or more so.
They were not only casting into prison in great numbers, but inhumanly treated there,
not only by Knight, Helliar, and their assistants, but the jailer,
whose name was Isaac Dennis, in imitation of his superiors,
made their imprisonment as distressing and uneasy as possible.
Some of the prisoners desiring to work at their callings for their subsistence in jail,
he would not allow them the liberty.
One Richard Lindy, a blind-man near ninety years of age, being carried to jail,
was forced for want of a bed to sit up three nights in a chair,
though others offered to pay for his lodging, if a convenient place had been allowed him.
Some in prison fell sick of the spotted fever, of whom three died.
Whereupon friends desired Dennis that they might go out in order for their recovery;
he pretended he was willing, if the magistrates would consent;
but when they wrote to the magistrates,
he used his endeavours to prevent the success of their application,
and was the means of frustrating them of obtaining their request.
To some friends who were taken sick, he behaved with great inhumanity,
refusing one the use of his friend`'s fire,
to another the liberty of removing out of the distracting noise of swearers and drunkards,
although the new sheriff ordered him to do it,
yet he detained him in his uncomfortable lodging '`till he died.
He, his wife and underkeeper were most rudely abusive to them,
though many of them were people of account, both with hands and tongue,
pulling the men by the hair, throwing them downstairs, rudely haling, and kicking women,
and throwing them down, to the hurting them grievously,
calling them by opprobrious nick-names, rogues, whores, cheats, and such like.

But from the dismal catastrophe of this unfeeling jailer we may draw this inference,
that, although, under the impulse of our passions, and our gratification of them,
we may for the season silence the reproofs of the monitor in our own breasts,
lull conscience asleep, and blunt its stings, yet a time will come, when it will awake,
make itself heard, new point its sting, and strike it to the heart.
This poor man, about the middle of October was taken sick,
when the reflection upon his past life filled him with inconceivable anguish of mind,
under which he expressed his wish, that he had never seen the inside of the jail,
for it had undone him.
He desired the Quaker prisoners, whom he had misused,
to forgive him for what he had done; to which they answered, they did forgive him,
but he should ask forgiveness of God.
But still his anguish increased to torture,
to such a degree as to cause a fear that he would go distracted.
The physicians ordering him to be bled, he signified to this effect:
None of their prescriptions would do him any good,
his distemper being beyond their reach; his day was over,
and there was no hope of mercy from God for him.
Some of the friends, pitying his condition,
charitably endeavoured to administer a ray of comfort, hinting,
that they hoped his day was not over, seeing he was so fully sensible of his condition.
To which he replied, "`I thank you for your good hope; but I have no faith to believe.`"
Whatever was thus spoken to relieve him gave him no ease,
but languishing in the anxiety of despair about a month,
he died without discovering any hope or sign of forgiveness.
Now although we presume to form no judgment upon those,
who are summoned to an higher tribunal than that of fallible man,
yet this passage may furnish us with an estimate of the incomparable
value of a conscience void of offence towards God and man.
A wounded conscience who can bear?

All the abuse and loss of substance this people had already sustained
not being sufficient to satiate the vindictive spirits of their persecutors,
many of them were returned into the Exchequer on the statute
of 20£. for absence from the national worship,
the amount of whose fines came to the enormous sum
of 16,440£. for which several were distrained;
but how much was actually levied of these fines I find no certain account.
Not satisfied with depriving them of their liberty, property and personal ease,
these persecutors proceeded next to essay,
how far they could succeed in an attempt against their lives.
They began with Richard Vickris,
who had before felt the effects of their malevolence in fines,
imprisonments and personal abuse.
He was the son of Robert Vickris, formerly merchant and alderman of Bristol,
and afterward of Chew-magna in Somersetshire:
He was convinced of the principles of this people in his youth;
to divert him from joining in society with whom,
and coming under the opprobrious appellation of a Quaker,
his father sent him abroad to travel in France, but was disappointed of his intention;
for Richard,
through disgust at the superstition of the ceremonious religion of that country,
was more confirmed in his adoption of one, which rejected ceremony and vain show,
in pursuit of the substantial part;
and therefore upon his return openly embraced the profession of that religion,
of the reasonableness whereof he had been convinced.
Herein his sincerity was indisputable,
since with this profession he embraced a variety of sufferings and hardships,
when he might have been otherwise in ease, opulence,
and a distinguished circumstance of life.
In the year 1680, he was imprisoned upon an excommunication;
he was afterwards subjected to frequent fines and distraints for attending meetings;
and now, last of all, they proceeded to put the statute of 35 Eliz.
in force against him, the penalty of which hath been already recited,
and that the last parliament repealed it, but the royal assent was eluded.

At the sessions previous to the time called Easter,
Richard Vickris was indicted on that statute; but,
demurring to the jurisdiction of the court, and refusing to plead,
he was committed to prison.
At a following sessions he was admitted to bail,
on security given to answer the indictment;
between that and Midsummer sessions he procured an habeas
corpus to remove his body and cause out of that court.

At an adjournment of the said sessions, on the 20th of 6th month called August,
he presented his _habeas corpus_, had his recognizance discharged,
and was delivered to the custody of the sheriff.
Yet notwithstanding, at the instigation of Sir John Knight,
he was hurried to his trial at the close of the sessions on the 23rd of the same month,
and though he requested not to be surprised into an unexpected
trial for his life in the absence of his counsel,
but to be allowed time to prepare for his defence, the court,
under the influence of Knight, Helliar and others of the like cast,
would grant him no favour, justice or delay.
He found means however to retain counsel, who ably pleaded his cause,
assigned a variety of errors in the indictment,
showed clearly that the witnesses had not proved him an
offender against the statute upon which he was indicted.
That the witnesses had sworn he was at a meeting on the day mentioned in the indictment;
but he had been punished already by the conventicle act for the same meeting,
which act enacted,
That no person punished by this act shall be punished for the same
offence by virtue of any other law or statute whatsoever.
But the clearest arguments lose their force with men whose passions
are warmly engaged on the opposite side of the question.
The court over-ruled every plea, in the most arbitrary manner,
and the jury selected mostly of men of mean occupation (though
he was a gentleman bred) to answer the purposes of his adversaries,
made no difficulty to bring him in guilty;^
footnote:[Trial by jury is esteemed the bulwark of the English man`'s life and liberty;
but we meet with many instances in this reign that
the forms of a free constitution may be preserved,
and yet under these forms real injustice and arbitrary sway be exercised.
For when corruption generally prevails it saps the foundations of a free government,
and under the shade of the form the substance is frequently lost:
And when the spirit of party is joined to corruption of manners,
small is the security the vanquished party derive from constitutional privileges.
For corruption hardens the conscience, and party rage biases the judgment,
and with juries under this description, too often the popular humour,
the direction of the court, and the gratification of their own prejudices,
are of more consideration than the nature of the
evidence or the obligation of their oaths.
It is a peculiar and valuable privilege to be tried by our peers,
provided they be men of honour, integrity and conscientious regard to equity.
But the juries of this time seem to have been picked from a different class, being,
according to bishop Burner, a shame to the nation and a reproach to religion,
being packed and prepared to bring in verdicts as they were directed,
and not as matters appeared upon the evidence.]
in consequence sentence was passed upon him,
viz. That he should conform or abjure the realm in three months,
or suffer death as a felon without benefit of clergy.
The recorder then admonished him to conform:
Richard Vickris answered, He presumed he would not
desire his conformity against his conscience;
and that to play the hypocrite with man was hateful, much more with God.
He expressed his sentiments with freedom,
and returned to his prison undismayed at his dismal sentence,
being supported above fear by the easy and peaceful tenor of his mind,
in the consciousness that he suffered not for evil doing.
He lay in prison under the aforesaid sentence '`till the next year, when,
the time for his abjuring the realm being expired,
he was liable to the execution of the sentence; for, he,
who in point of conscience could not swear at all,
was necessarily restrained from the abjuration.

His adversaries, having gained their point thus far,
seemed determined to proceed to the execution of the sentence against him:
But being conscious that the iniquity of their proceedings
would not stand the test of candid examination,
and apprehensive of the public odium that might attend
the full execution of this sanguinary law,
they added one injury to another, endeavouring to take away his good name,
before they took away his life;
that by blackening the one they might deprive him of protection and commiseration,
and rescue themselves from the censure and detestation
naturally attendant upon the other.
They very unjustly represented him as a person disaffected to the government.
But it pleased divine providence to deliver him out of their hands.
For his wife in her distress took a journey to London
to make interest with the government in his favour,
and by the assistance of her friends there,
got admission to the Duke of York (who bore the chief sway
at court) and laid her husband`'s hard case before him;
upon hearing which he declared,
"`That neither his royal brother nor himself desired that any of
his subjects should suffer for the exercise of their consciences,
who were of peaceable behaviour under his government,
and there upon gave such directions as were effectual to procure his discharge.
He was now removed by _habeas corpus_ and writ of error from Newgate in Bristol to London,
and brought to the king`'s bench bar, where,
upon the errors assigned by counsellor Pollexfen,
he was cleared of the sentence on the 35th Eliz.
by Sir George Jefferies, lord chief justice, and so was legally discharged,
to the great joy of his aged father, distressed wife and family,
and his friends throughout the nation.
His father lived to see him after his discharge, but survived his return only three days;
by whose will he succeeded to his estate and seat at Chew,
in which he fixed his residence, and lived there in reputation and honour,
conspicuous for his virtue and benevolence, an ornament to his place and station;
when Helliar was no more,
having finished his wretched life in great horror and perturbation of mind,
under the torture of an accusing conscience.
Olisse is reported also to have been so uneasy in his last moments,
in his retrospection of his imprisoning and despoiling this people,
that he wished restitution to be made to them, when it was out of his power;
and so under the sense of the wrong he had done, without the means of rectifying it,
he breathed his last.
And Knight proving himself all along a determined for liberty of conscience,
became disaffected to king James for his dispensing with the penal laws, not so much,
we may judge by his consequent conduct, upon the account of the illegality thereof,
as that his hands were tied up from gratifying his pride and his malice,
in domineering and distressing his fellow-citizens.
Turning with the tide, he favoured the revolution,
but when he found the consequence thereof to be a general toleration,
he ranked with the malecontents in king William`'s reign; and that measure,
he had meted out to others, was more justly measured out to him again, being himself,
for some offence against government,
imprisoned in the same jail to which he had in the
zenith of his power committed so many honest people;
after his release, being reduced in his circumstances,
he lived in obscurity in a village in Somersetshire.

It is not so much from any satisfaction we receive
in these narratives of the catastrophe of our persecutors,
that we preserve them on record,
as that by contrasting them with the peaceful exits of virtuous and religious persons,
who have made it their study through life to preserve a conscience void of offence,
many of which are described herein, we may form a just estimate of human life;
of the value of a good conscience,
and of the inconceivable advantage of a life of self-denial,
even to the suffering of persecution,
over that spent in the full gratification of the sensual appetites, irregular passions,
ambitious lust, and abuse of power,
in that hour which puts a period to our existence here,
and reduces all the ranks of mankind to a level.

This persecution in Bristol continued '`till king
James issued his proclamation for a free pardon,
with his special warrant for comprehending the Quakers therein:
Upon which they were set at liberty,
and from thenceforth the persecution in this city
for their religious meetings entirely ceased.

In London in this year numbers were imprisoned from the sundry meetings,
fined as rioters, and imprisoned again for their fines;
distrained by Exchequer process for absence from the national worship;
harassed and plundered by informers and soldiers; particularly John Elson,
being fined 20£. for the Peel meetinghouse, and 10£. for an unknown preacher,
was distrained by Yates, Headborough of Clerkenwell, and Gabriel Shad,^
footnote:[Not long after I met with the following account of this Shad,
a notorious informer,
that he was committed to Newgate for stealing goods from one William Lemman
to the value of 300£. and upon this trial was found guilty of felony;
but by the favour of his powerful friends he was freed from the gallows,
having obtained the benefit of clergy, he was burned in the hand and discharged.
He then pursued his former occupation;
suchlike infamous characters even at this time being only to be
procured to fill an office too odious and too dishonest for conscientious
and reputable persons to have any concern with.
Sewel, p, 587.]informers and assistants, upon two warrants granted by Peter Sabbs,
justice.
They broke open his doors in his absence, after seven o`'clock at night in October,
kept possession of his house all night, eating,
drinking and carousing to excess of what they found in the house, saying,
all was the king`'s. The woman of the house, Mary Elson, was obliged to sit up all night,
nor would they suffer any neighbour to bear her company,
a soldier of the gang threatening to stab some of them, who were desirous to go in.
They seized four cartloads of household goods, a chest belonging to a lodger,
in which were writings of importance; the servants`' wearing apparel,
and several things belonging to two widows (which Mary Elson apprized them were
not her husband`'s property) and eight loads of timber and boards out of the yard.
The meetinghouse, for which the seizure was made,
not being the property of the said John Elson, he made his appeal,
and got his goods again, upon payment of 30£. into the hands of the said justice Sabbs;
but before the time of trying his appeal, the justice absconded, and the money was lost.

George Whitehead, in his Journal, page 543,
gives the following account of some part of friends sufferings in London at this time:

[quote]
____
The being shut out of our meetinghouses for divers
years in and about the cities of London and Westminster,
and our meetings kept in the streets, in all sorts of weather,
was a trial and hardship upon us, even upon old and young, men and women.
But that trial was not so great as to have our estates and
livelihoods exposed to ruin by a pack of ravenous informers;
although it was no small hardship to our persons to be kept out of doors in the great,
severe and long frost and snow in the year 1683, for about three months together,
when the river Thames was so frozen, that horses,
coaches and carts could pass to and fro upon it,
and a street be erected and stand over it.
____

In Cheshire, Thomas Needham and Philip Egerton, justices,
committed at one time about eighty persons to Chester Castle from a meeting ar Newton,
where they could find neither rooms nor lodging for such a number,
so that they were obliged for two nights, some of them to walk about,
others to lie on tables and benches, and some on flags spread on the floor.
At length thirty of them were put into a filthy dungeon,
out of which the felons were then removed.

But having too many instances of the arbitrary or
cruel proceedings of the justices in this reign,
I am pleased when I meet with accounts of others influenced by temper and moderation,
as in the following case: Robert Blennel, priest of Fen-Stanton in Huntingdonshire,
prosecuted Elizabeth Gray in the ecclesiastical court for tithes.
She was a poor widow of about eighty years of age,
and so infirm that she could scarce go out of her house;
yet the prosecutor was so hard-hearted as to apply to the justices to send her to prison,
she being certified by the ecclesiastical court as contumacious.
But the justices refused in regard of her age, remarking,
that she was an object fitter for her grave than a prison.
The priest being disappointed of his design against the ancient woman,
cited her son William Gray into the court for the same claim of tithes,
and procured a certificate of contumacy against him;
but upon examination before the justices, it appearing,
he was only a servant to his mother, they discharged him,
though the priest`'s advocates exerted their strenuous
efforts with the justices to send him to prison.
Thus both the mother and son escaped, the one an imprisonment unreasonably cruel,
and the other unjust and illegal; which illustrates the advantage derived to the subject,
by having the proceedings of ecclesiastical power
subjected to the control of the civil magistrates,
when they are men of moderation and humanity.

In Somersetshire several of the magistrates and informers were also very hot
prosecutors of the members of this society upon the different penal laws,
and without and beyond the law.
To particularize the various means of vexation they used towards them
would be nearly a repetition of the relation of the persecution in Bristol,
being subjected in some parts to the despotic power of Helliar,
who was under-sheriff of the county this year, and in others to that of Henry Walrond,
a captain of militia and justice of peace,
who was well nigh equal to Helliar in his severity and hatred to this people.
They were imprisoned in great numbers,
informers were encouraged against them and protected in perjury; they were fined,
distrained and excommunicated; their meetinghouses defaced,
and the forms broken or burned.

[.small-break]
'''

1680+++.+++ Giles Barnardiston, of Clare, in the county of Suffolk,
who finished his course in an honourable and serviceable life this year,
was an eminent instance of the efficacy of pure religion
in a heart divinely influenced thereby.
He was born about the year 1624, of parents well descended,
and of considerable account in the world.
He received a liberal education, suitable to his rank in life,
in seminaries of literature, and at the university,
where he followed his studies six years, being designed for the ministerial office.
But when he had acquired the age and attainments reckoned suitable for admittance thereinto,
and had an offer of preferment in the church (so called)
he felt a reluctance in himself to undertake the charge,
from a consciousness of wanting that internal purity and spiritual wisdom which
he conceived the scriptures point out as essential qualifications of gospel ministers;
and looking at the function as too weighty an undertaking
for him to enter upon in the present state of his mind,
he resisted the solicitations of his friends to accept of the place provided for him,
whereby he incurred their displeasure.
But knowing himself unfit for this important charge, he was fearful to take it upon him,
being persuaded that they who do so from lucrative motives,
without the qualifications to discharge the arduous
duties thereof with diligence and propriety,
both by example and precept, have the more to answer for.

Notwithstanding these just and serious reflections respecting the priest`'s office,
he had not yet attained to that stability in religion
as to resist the allurements of pleasure;
indulging for a season in sensual gratifications,
in the pastimes and recreations of the age;
but being followed by the convictions of the grace of God, which appeareth to all men,
these fleeting pleasures conveyed a very transitory satisfaction,
being certainly attended with an intermixture of painful remorse,
and succeeded by the bitterness of anguish.

After the breaking out of the civil war he obtained a colonel`'s commission in the army;
but the military life, attended with violence and bloodshed,
conveyed still less satisfaction, and therefore he soon grew weary thereof,
and laid down his commission.

He then retired to Wormingford Lodge in Essex,
where in privacy and solitude he applied his heart to wisdom,
which Solomon saith is better than weapons of war.
Here, denying himself of his former amusements, he commenced a stricter life than before;
and being incited by a religions regard to the well-being of his immortal part,
he became seriously thoughtful about the way to life and salvation,
and earnestly desirous of associating with some body of people
who were sincerely engaged in investigating the right way.
About the year 1661 he felt an inclination to acquaint himself
with the principles of the people called Quakers,
and invited some of them to his house.
George Fox the younger being then at Colchester,
paid him a visit in company with George Wetherly, and was kindly received;
when entering into religious conversation,
George Fox discoursed concerning the light of Christ Jesus,
who tasted death for every man, and enlightenith every man that cometh into the world,
that they might have life;
this scriptural doctrine agreeing with Giles Barnardiston`'s own experience,
he embraced it as truth, took up his cross to his fondness for sensual delights,
broke off his connection with his former associates,
relinquished the glory and friendship of the world, and despising the shame,
joined himself in society with the people called Quakers,
at the very time when they were exposed to that cruel
abuse in Colchester which is before described,
when neither his rank in life, his qualifications, nor his respectable character,
were of sufficient consideration to exempt him from participating
in the sufferings of that time and place.
He willingly bore his part in that storm of persecution,
in the hottest time of which he constantly attended the religious
meetings of his friends without shrinking at the danger,
and undauntedly hazarded his life for the testimony of a good conscience.

In the year 1669 he removed his residence to Clare in Suffolk, the place of his nativity;
and here also, in conjunction with his brethren, was obnoxious to suffering.
For in the next year, upon the last conventicle act coming in force, Robert Dawkins,
a parish officer of Haverill, and Elias Dowty, an informer,
were very active in coming to the meetings there, which were constantly held,
and taking the names of the persons present, gave information to Gervas Elways,
a justice of peace, who readily granted his warrants for distress,
which were executed with the utmost rigour.
Giles Barnardiston with two others had the value
of 32£. 5s. taken from them in a few months,
Dawkins aforesaid urging on the other informers and officers, saying, Come, Sirs,
let us do what we do quickly, for this trade will not last long.
After suffering spoil of their substance they were debarred of the use of their meetinghouse,
and obliged to meet in the street during the cold winter,
where they received much personal abuse.

In the same year he made his appearance in the ministry,
and proved an able minister of the gospel; not of the letter, but of the spirit;
and in the exercise of his gift he acquitted himself with faithfulness,
fervency and wisdom, whereby many were convinced, and converted to righteousness.
Notwithstanding he had but a tender constitution, yet his devotedness to the divine will,
to the cause of truth, and to the promotion of the eternal well-being of mankind,
animated him to travel many journeys in divers parts of England and in Holland,
for the purpose of propagating pure religion amongst his friends and others.
His motives, and the ends he had in view,
he himself hath declared to the following purport, viz.

[quote]
____
It is but a short time and we shall have done with this world;
and I desire that I may be faithful to the end,
that I may enjoy that of the hand of the Lord, which I received truth for.
If it had not been to obtain peace of conscience while I am in this world,
and hopes of everlasting rest with God in the world to come,
I would never have left the glory and pleasure of this world, which I had,
and might have enjoyed my share of, with those who are delighting themselves therein;
neither would I now leave my habitation, where I have an affectionate wife,
and every domestic comfort, which a man fearing God need desire,
if it was not to obey the Lord, and to make known his truth unto others,
that so they may come to be saved.
For this cause do I forsake father and mother, wife and estate;
and whosoever thinks otherwise of me,
with the rest of my faithful brethren whom God hath called into his work,
are all mistaken concerning us, and I would they knew us better.`"^
footnote:[[.book-title]#Piety Promoted.#]
____

At last, after all his labour, in which he discharged himself with fidelity,
to the spiritual advantage of many, after all his trials, sufferings and travels,
he was taken ill in his return from London to Chelmsford, and after a short sickness,
in which he expressed his resignation, that the Lord was his portion,
and that he was freely given up to die, which was gain to him,
he departed this life in peace the 11th 11mo 1680. O. S. about fifty-six years of age,
leaving behind him deep impressions of grateful respect
and honourabe esteem of his memory,
in the hearts of many of his survivors.

[.small-break]
'''

1681+++.+++ Thomas Taylor, an ancient and faithful minister in this society,
died in the course of this year.
He was born at or near Skipton in Yorkshire about the year 1616,
and received a liberal education at the university of Oxford,
in order to qualify him for the priesthood.
He was first a lecturer at Richmond in Yorkshire,
and after obtained a living in Westmoreland, where he officiated as a national teacher,
and sometimes resigned his pulpit to John Audland and Francis Howgill,
to preach in before they were convinced.
Being, as well as many others at that time,
scrupulous in respect to some ceremonies retained in the established church,
he declined the use thereof; for he would neither baptize children at the font,
nor sign them with the sign of the cross;
and defended his practice in a dispute with the priests at Kendal with success.
He was in consequence numbered amongst the puritans,
and his audience was principally composed of this class of the people:
But the bishops being at this time, in a good measure, deprived of their jurisdiction,
he retained his benefice till the year 1652, when he relinquished it voluntarily.
For George Fox being come into these parts, he, in company with some other priests,
had an inclination to have an interview with him,
and for that purpose went over to Swarthmore.
His companions opposed George Fox`'s sentiments with some marks of resentment;
but Thomas Taylor being convinced of the truth of his doctrine, yielded assent there to,
and joined him as a companion in travel and in ministerial labour:
And being now persuaded of the unlawfulness of preaching for hire,
he resigned his living, and preached Christ freely, according to his divine command.
He travelled in many parts of England,
by his doctrine to propagate pure religion and righteousness.
At Oxford he maintained his principles against the exceptions of John Owen,
at that time vice-chancellor of the university;
and even the scholars admitted Thomas had the advantage in argument,
being sustained by a power and wisdom superior to that of schools and seminaries.

But his travels were interrupted by a succession of imprisonments,
the common lot of the members of this society,
as well under the alledged tolerating government of the independents,
as the succeeding intolerance of episcopacy.
In the year 1657,
conceiving it his duty to deliver an exhortation to the people
assembled in the public place of Worship at Appleby in Westmoreland,
and essaying to discharge himself in this apprehension of duty,
he was apprehended and cast into prison there, in the sixth month, 1657,
and detained till the year 1659.
In the next year, 1660, in the general imprisonment of the members of this society,
upon the insurrection of Venner and his party, he was again imprisoned in York castle,
in company with a very large number of his friends, five hundred and upwards,
taken in like manner as hath been repeatedly remarked
upon that imprisonment in other parts,
many from their peaceable meetings, some on the highway,
some from their lawful occupations, and some out of their beds;
they continued in prison till about the 9th 2 mo.
O+++.+++ S. called April; and after lying in prison, some two months, and some three,
were generally discharged.
In the next year, 1661,
travelling in Leicestershire on the road toward Swanington
he was met by a company of soldiers,
and passing by them without pulling off his hat, some of them cried out a fanatic,
and riding after him brought him back, kept him prisoner all night,
and next day after hurrying him from place to place,
at length met with two country justices, who tendered him the oath of allegiance, and,
for his conscientious refusal to take it, committed him to Leicester jail;
how long he was detained I find no account: But in the succeeding year, 1662,
he was again imprisoned in Stafford jail,
and at the ensuing assizes was indicted for refusing to take the oath of allegiance,
and had sentence of premunire passed upon him,
under which he continued a prisoner about ten years,
till King Charles II. issued his letters patent for
the general discharge of the Quakers from prison, in 1672.
In the year 1679, being occasionally at the house of William Heawood at Keele,
three or four friends and some neighbours came in,
to whom Thomas felt something on his mind to communicate by way of exhortation,
which having done, he afterwards prayed.
One Ralph Bostock, clerk to justice Snead, informed his master thereof,
who sent for two of the neighbours that were present,
and obliged them to make oath of the same; upon which he fined Thomas Taylor,
for preaching, 20£. from William Heawood, Humphry Morgan and John Smith,
he caused distress to be taken to the value of 7£. 10s.

Thus spending much of his time while at liberty in religious labour,
to the spiritual benefit of many people; and in his successive imprisonments,
for most part of twelve years,
being supported by the consciousness of suffering in a good cause,
and in patient acquiescence in divine disposal, he held his integrity to the last,
and finished his course in a virtuous and serviceable life in Stafford,
the 18th 1mo. 1681, O. S. being about sixty-five years of age,
leaving behind him a good report amongst the inhabitants of that town,
where he had resided for several years.

[.the-end]
End of the Second Volume.
