== Chapter XIV.

[.chapter-synopsis]
* Queen Anne ascends the Throne
* Addresses to her
* She declares her Resolution to maintain the Toleration
* Second Address
* Account of Margaret Fox
* G. Keith sent a Missionary to America
* Account of Ambrose Rigge
* His Epistle of Advice.

Anne, the second daughter of King James, who was married to Prince George of Denmark,
succeeded to the throne by virtue of the act of settlement.
Addresses of congratulation were made to her from all quarters upon her accession.
The people called Quakers thought themselves no less
than others called upon to condole the king`'s death,
and testify their fidelity to the new sovereign.
They accordingly drew up an address,
and deputed George Whitehead and some other friends to present it,
who being introduced by the Duke of Ormond and the Earl of Marlborough,
read her the following:

[.embedded-content-document.address]
--

[.letter-heading]
To Queen Anne, over England, etc.

[.salutation]
May it please the Queen,

We thy peaceable subjects cannot but be sorrowfully affected with a deep sense
of the loss sustained by the death of our late King William the third,
whom God made the instrument of much good to these nations;
a prince who indeed desired to be a father of his people,
and as such did by his great example as well as precept,
endeavour to unite them in interest and affection,
and promoted and confirmed a legal liberty to tender consciences,
by all which his reign was adorned, to the renown of his memory.

And it having pleased the all-wise God, the disposer of kingdoms,
to preserve thee to succeed to the government of these nations,
and thereby to the maintaining and consummating those great works so happily begun,
we humbly beg leave to congratulate thy free and peaceable accession to the throne,
from whence we observe the Queen`'s excellent declaration,
manifesting her care for the good of all her people,
and therefore doubt not but we her protestant dissenting
subjects shall partake of her royal favour and protection.

We sincerely declare, that with the assistance of the grace of God we will always,
according to our christian duty, demonstrate our good affection,
truth and fidelity to the Queen and her government,
and heartily pray that his wisdom may direct,
and his blessing be upon the Queen and her great council,
to the suppressing of vice and immorality, and the promoting of piety, peace and charity,
to the glory of God, and the benefit of these nations.

May the King of Kings make thy reign long and glorious,
to which temporal blessing we shall pray for thy eternal happiness.

[.signed-section-context-close]
Signed on behalf and by the appointment of the aforesaid people
at a meeting in London the 10th of 2nd month 1702.

--

This address was very favourably received by the Queen, who, upon its being read to her,
answered:

[quote]
____
I thank you for your address, and I assure you of my protection.
____

The Queen having afterwards publicly declared her resolution
to maintain the act of toleration in favour of dissenters,
friends at their succeeding yearly meeting in London thought it proper
to wait upon her with an address of thanks for her said declaration,
and the following address was drawn up by said meeting,
and presented to her by a deputation of suitable friends:

[.embedded-content-document.address]
--

[.letter-heading]
To Queen Anne, over England, etc.

[.blurb]
=== The humble and thankful acknowledgment of the people commonly called Quakers, from their yearly meeting in London, the 30th day of the third month called May, 1702.

[.salutation]
May it please the Queen,

We thy peaceable and dutiful subjects, met from most parts of thy dominions,
at our usual yearly meeting (for the promotion of piety and charity),
being deeply affected with thy free and noble resolution
in thy late speech at the prorogation of the parliament,
to preserve and maintain the act of toleration, for the ease and quiet of all thy people,
could not but in gratitude esteem ourselves engaged,
both to thank Almighty God for that favourable influence,
and to renew and render our humble and hearty acknowledgments to the Queen for the same,
assuring her (on behalf of all our friends) of our
sincere affection and christian obedience.

And we beseech God, the fountain of wisdom and goodness,
so to direct all thy counsels and undertakings, that righteousness which exalts a nation,
and mercy and justice that establish a throne, may be the character of thy reign,
and the blessings of these kingdoms under it.

[.signed-section-context-close]
Signed by appointment and on behalf of the said meeting.

--

Of those who presented this address, William Penn was the deliverer,
and the Queen was pleased to speak to him in a very kind manner,
and not only received the said address favourably, but after it was read to her,
she was pleased to give the following answer: "`Mr. Penn,
I am so well pleased that what I have said is to your satisfaction,
that you and your friends may be assured of my protection.`"

This year died Margaret, the widow of George Fox,
being in or about the 87th year of her age.
She was the daughter of John Askew of Marsh Grange in the parish of Dalton in Lancashire,
a gentleman of an ancient family and good estate, and conspicuous for piety and charity.
His daughter Margaret was religiously inclined from her tender years,
and was married before she attained the age of eighteen years to Thomas Fell,
who being bred a lawyer, was made a justice of peace,
was a member in several parliaments,
appointed vice-chancellor of the county of Lancaster, and after some time a Welch judge,
in which stations he acquitted himself with honour, being in reputation for wisdom,
justice, moderation and mercy.
He deceased in the year 1658, having been married twenty-six years,
and left behind him a son and seven daughters.
We have seen the means used to exasperate him against the Quakers (so called)
on account of the convincement of his wife and most of his family in his absence,
and the anxiety he conceived on that account; but when he came home,
the discreet and obliging behaviour of his wife, and George Fox`'s discourse,
dispelled the cloud,
and opened his understanding to perceive that the representation
he had received of this people was the effect of antipathy,
and intended to prejudice him against them;
he therefore continued to treat his wife with his usual complacency and affection:
and after he gave up his house for a meeting-place for her and her friends,
he was not observed to give much attendance upon the public worship,
but when the meeting was kept in his hall, he generally sat in an adjoining room,
where he could hear without appearing to join the friends in their worship;
and although he did not profess himself of their society,
he afforded them his protection against the malice of their enemies,
as far as lay in his power.

The principal part of Margaret Fell`'s transactions, as a member of this society,
have been already related in the course of this history;
her frequent applications to King Charles and others in favour of her suffering friends,
(in which her indefatigable perseverance gave her success),
she repeated at times to near the King`'s death,
to her own sufferings we have only to add, that beside her premunire and imprisonments,
she was several times fined for preaching.
After a widowhood of eleven years she was married to George Fox,
and survived him about the same length of time.
That she was a woman of good sense and true greatness of mind,
is evident from her behaviour and defence on her trial for refusing to swear;
that she was a prudent mother and skilful manager of her family
and domestic concerns appeared in the effects thereof in her daughters,
who were all well married, honourable and well accomplished women:
She was conspicuous for virtue in civil society,
but this procured her no respect from those who could
see no virtue without the pale of conformity;
she was eminent for her rank and services in religious society,
and therefore was distinguished by a peculiar severity of persecution;
she was honourable in her life,
and evidenced she was well prepared for her death by the
excellent expressions she uttered near her conclusion.

George Keith,
who had as yet by his conformity obtained no settlement in the church of England,
but preached in different places as the bishops appointed him,
was about this time sent as a missionary to America,
having raised an expectation that he would bring over many
of the Quakers and others to the church (so called);
his success will appear when we come in course to
treat of the state of this society in America,
for there we shall meet with him again.

In the year 1704, Ambrose Rigge of Ryegate in Surrey, departed this life.
He was born at Banton in Westmoreland,
and convinced of the principles of this society about the year 1652,
and was thereupon rejected by his parents and relations.
In some time after, he thought it his duty to appear as a minister amongst them,
and travelled in the exercise of his ministry to London,
and to the southern and western counties of England in or about the year 1655,
in company with Thomas Robertson:
Zealous for the promotion of the testimony of the truth,
his sufferings for his testimony bore proportion to his zeal.
His imprisonment with his companion Thomas Robertson at Basingstoke,
in the course of that year, hath been already noticed.
He was again imprisoned at Southampton in the same year.
In the year 1658, passing through these parts again,
the impulse of christian duty incited him to visit his friends in prison there,
and for this office of brotherly kindness he was seized by the constable and other officers,
and most shamefully abused, being dragged down stairs, seized by the throat,
set on a cowl staff, from which they let him fall;
then they dragged him by the feet to the cage, pulling his hair off his head,
and tearing his clothes.
After all this ill usage, he was, by the mayor`'s order whipped in the market place;
then thrown down backward into a wheelbarrow, carried in that up a part of the street,
and from thence thrown into a dung cart, and so sent away from tithing to tithing,
and threatened, that if he came again he should be whipped twice as much,
burned on the shoulder and banished the land.
At another time visiting a friend in his sickness, he was taken before two justices, who,
because he declined to pull off his hat at their command, sent him to prison,
where he lay five weeks.

This is another specimen of the unchristian treatment,
which this people received from those hands, who,
under pretence of the privileges of the people being infringed by the former powers,
had taken up arms to redress their grievances.
The succeeding revolution of government in the restoration of the monarchy exempted
them from these servile punishments of whipping and passing them as vagrants,
but exposed them to great hardships in long and uncomfortable imprisonments,
and spoiling of their outward sub

This friend seems to have suffered severely under every government,
by most or all the variety of penal laws contrived for the distressing of non-conformists.
The fifth-monarchy men had no sooner made their insurrection,
than he was taken up as he was travelling on horse
back and carried before the lieutenant of the county,
who ordered him to be stripped and searched, sent away his mare,
kept him on guard all night, and next day sent him to Winchester,
where after four days confinement in the marshal`'s house,
the oath of allegiance was tendered him by two justices, who, upon his refusing it,
committed him to the county jail, where he lay above four months.
In 1662 he was committed to prison at Horsham in Sussex,
and at the next assizes indicted, tried immediately,
and sentence of premunire was passed upon him in the usual manner,
under which he was detained in prison ten years and upward.
He was prosecuted in the Exchequer for tithes at the suit of Robert Pepys,
priest of Gatton, who furiously threatened to kill him: Said Pepys prosecuted him,
his wife and two of his servants in the Ecclesiastical court,
and procured their excommunication for absence from the national worship.
Ambrose Rigge was indicted at sessions for not going to hear common prayer,
and was committed to prison, where he lay above a year.
In 1683 he was prosecuted by the aforesaid Pepys on the statute of 20£.
a month for eleven months absence from the national worship.

Having thus passed a life of religious labour in the service of God and man,
whereby many were converted to righteousness;
and endured persecution and affliction with remarkable faithfulness and patience,
whereby his peace was increased, in the time of his last sickness,
he looked forward towards his dissolution as the end of all his troubles, saying,
I am going where the weary are at rest; and having been inured to patience in affliction,
it deserted him not in this last trial of all.
He bore his sickness with much patience and resignation to the Divine Will,
and his love and esteem of the pure truth abode with him to the last,
declaring a little before his departure,
"`If friends kept to the root of life in themselves they would be the happiest
people in the world.`" He departed this life the 30th of 11th mo 1704,
aged seventy years or upward, and a minister forty-nine years.

He lived long enough to see with regret a declension
in some professing the same principle of truth,
in turning their attention more to the pursuit of great possessions in this world,
to aggrandize themselves and families, than to make their calling and election sure,
whereby some meeting with disappointment in their aim,
had deviated from that scrupulous regard to moral justice,
which in the beginning had remarkably distinguished the members of this society;
the deep and affecting concern of his mind drew from
him the following epistle of advice to his friends:

[.embedded-content-document.epistle]
--

Many days and months, yea, some years, hath my life been oppressed,
and my spirit grieved, to see and hear of the uneven walking of many,
who have a name to live, and profess the knowledge of God in words, yea,
and also of some who had tasted of the good word of God,
and have been made partakers of the powers of the world to come, and have chap.
received the heavenly gift and grace of God,
which teacheth all (who walk in it) to deny all ungodliness and worldly lusts,
and to live soberly, honestly and righteously in this present world,
whose faithfulness (with great reason) hath been
expected to God in things of the highest concern,
and to have walked as lights in the world, and in all faithfulness both to God and man,
to have stood as living monuments of the mercies of the Lord,
letting their lights so shine before men, that they might see their good works,
both in spiritual and temporal concerns;
and so might have honoured and glorified God in their day and generation,
and have convinced (or confounded) gainsayers,
putting to silence the ignorance of foolish men,
whereby the worthy name of the Lord (by which they have been called),
might have been renowned through the earth,
and his precious truth and glory spread to the ends of it,
that many through the beholding their good and exemplary conversation in Christ,
(coupled with the holy fear of God) might have desired
to lay hold of the skirt of a christian indeed,
whose praise is not of men, but of God.

These are the fruits which we have laboured and travelled for,
through many and great tribulations, that many might be turned to righteousness,
and that the knowledge of the power and glory of the Lord might cover the earth,
even as the waters do the sea.
This was (and is) our only end and design, which blessed be the Lord,
many are witnesses of, and established in, to our abundant joy and comfort:
But there are some amongst us, who have not walked humbly with the Lord,
as he hath required, nor kept in that low estate, neither inwardly nor outwardly,
which becometh such who are travelling up to Zion, with their faces thitherward,
but have launched from the rock which is firm and sure,
into the great sea of troubles and uncertainty, where some have been drowned,
others hardly escaping, and many yet labouring for the shore,
with little hopes of coming at it;
who have not only brought themselves in danger of suffering shipwreck,
but have drawn in others, and have endangered them also,
which hath opened the mouths of the enemies of Zion`'s welfare,
to blaspheme his great and glorious name,
and hath eclipsed the lustre of the glorious sun of righteousness,
both in city and in country; this is a crying evil, and ought not to go unreproved,
and that with a severe countenance; for God is angry with it,
and will assuredly punish it.

Many have got credit upon the account of truth, because at the beginning it did,
and doth still lead all, who were and are faithful to it, to faithfulness and truth,
even in the unrighteous mammon, and to let their yea be yea, and their nay be nay,
even between man and man in outward things;
so that many would have credited one that was called a QUAKER with much,
and many I believe did merely upon that account, some whereof, I doubt,
have just cause to repent of it already:
but if truth and righteousness had been lived in by all who profess it,
there had been no such occasion given:
For they who still retain their integrity to the truth and life of righteousness manifested,
can live with a cup of water, and a morsel of bread in a cottage,
before they can hazard other men`'s estates to advance their own;
such are not forward to borrow, nor to complain for want,
for their eye and trust is to the Lord their preserver and upholder,
and he hath continued the little meal in the barrel,
and the oil in the cruse hath not failed to such, '`till God hath sent further help;
this is certainly known to a remnant at this day, who have coveted no man`'s silver,
gold or apparel, but have and do labour with their hands night and day,
that they may be without charge.

It is so far below the nobility of Christianity,
that it is sort of common civility and honest society amongst men,
to twist into men`'s estates, and borrow upon the truth`'s credit,
(gained by the just and upright dealing of the faithful) more than
they certainly know their own estates are like to answer;
and with what they borrow reach after great things in the world,
appearing to men to be what in the sight of God and truth they are not,
seeking to compass great gain to themselves,
whereby to make themselves or children rich or great in the world:
This I testify for the Lord God, is deceit and hypocrisy,
and will be blasted with the breath of his mouth, and we have seen it already.

And that estate, that is got either with the rending,
or with the hazard of rending another man`'s, is neither honestly got,
nor can be blessed in the possession: For he that borrows money of another,
if the money lent be either the lender`'s proper estate, or part of it,
or orphan`'s money that he is entrusted withal, or widow`'s, or some such,
who would not let it go but upon certain good security,
and to have the valuable consideration of its improvement; and the borrower,
though he hath little or no real or personal estate of his own, but hath got some credit,
either as he is a professor of the truth, or otherwise,
and hath (it may be) a little house, and a small trade,
it may be enough to a low and contented mind; but then the enemy gets in,
and works in his mind, and he begins to think of an higher trade and a finer house,
and to live more at ease and pleasure in the world,
and then contrives how he may borrow of this and the other,
and when accomplished according to his desire, then he begins to undertake great things,
and get into a fine house, and gather rich furniture and goods together,
launching presently into the strong torrent of a great trade, and then make a great show,
beyond what really he is, which is dishonesty; and if he accomplish his intended purpose,
to raise himself in the world, it is with the hazard (at least) of other men`'s ruin,
which is unjust:
but if he falls short of his expectation (as commonly
such do) then he doth not only ruin others,
but himself also, and brings a great reproach upon the blessed truth he professeth,
which is worse than all; and this hath already been manifested in a great measure,
and by sad experience witnessed.
But the honest, upright heart and mind knows how to want, as well as how to abound,
having learned content in all states and conditions;
a small cottage and a little trade is sufficient to that Mind,
and it never wants what is sufficient: For he that clothes the lilies,
and feeds the ravens, cares for all who trust in him, as it is at this day witnessed,
praises to God on high;
and that man hath no glory in (nor mind out after) superfluous or needless,
rich hangings, costly furniture, fine tables, great treats, curious beds,
vessels of silver, or vessels of gold, the very possession of which creates envy,
as said the ancient christian Clemens Alexandrinus.
Padag. lib. 2. cap. 3. pag. 160-161.

The way to be rich and happy in this world, is first to learn righteousness;
for such were never forsaken in any age, nor their seed begging their bread.
And charge all parents of children, that they keep their children low and plain in meat,
drink, apparel, and everything else,
and in due subjection to all just and reasonable commands,
and let them not appear above the real estates of their parents,
nor get up in pride and high things, though their parents have plentiful estates;
for that is of dangerous consequence to their future happiness:
And let all who profess the truth, both young and old, rich and poor,
see that they walk according to the rule and discipline of the gospel,
in all godly conversation and honesty,
that none may suffer wrong by the in any matter or thing whatever;
that as the Apostle exhorted, they may owe nothing to any man, but to love one another;
for love out of a pure heart is the fulfilling the law:
which law commands to do justly to all men: And he that hath but little,
let him live according to that little, and appear to be what in truth he is;
for above all God abhors the hypocrite,
and he that makes haste to be rich falls into snares, temptations,
and many noisome and hurtful lusts, which drown many in perdition,
and the love of money is the root of all evil, which while some have lusted after,
they have erred from the faith, and compassed themselves about with many sorrows.

For preventing this growing evil for the time to come,
let such by faithful friends be exhorted, who either live without due care,
spending above what they are able to pay for, or run into -great trades,
beyond what they can in honesty and truth manage,
and let them be tenderly admonished of such their undertakings;
this will not offend the lowly upright mind; neither will the honest-minded,
who through a temptation may be drawn into such a snare and danger,
take any occasion to stumble, because his deeds are brought to the light.
And if after mature deliberation,
any are manifested to be run into any danger of falling,
or pulling others down with them, let them be faithfully dealt withal in time,
before the hope of recovery be lost, by honest, faithful friends,
who are clear of such things themselves,
and be admonished to pay what they have borrowed faithfully and in due time,
and be content with their own,
and to labour with their own hands in the thing that is honest,
that they may have wherewith to give to him that needeth,
knowing that it is more blessed to give than to receive.
And if they hear, and are thereby recovered, you will not count your labour lost;
but if they be high, and refuse admonition, it is a manifest sign all is not well:
Let such be admonished again by more friends, and warned of the danger before them;
and if they still refuse and reject counsel and admonition,
then lay it before the meeting (concerned about truth`'s affairs) to which they do belong,
and if they refuse to hear them,
then let a testimony go forth against such their proceedings and undertakings,
as not being agreeable to the truths nor the testimony of a good conscience,
neither in the sight of God nor man; this will be a terror to evil-doers of this kind,
and a praise, encouragement and refreshment to them who do well,
and nothing will be lost, that is worth saving, by this care: for he that doth truth,
whether in spiritual or temporal matters, will willingly bring his deeds to light,
that they may be manifested to all, that they are wrought in God.

These things lay weightily upon me, and I may truly say, in the sight of God,
I writ them in a great cross to my own will, for I delight not, nay,
my soul is bowed down at the occasion of writing such things; but there is no remedy,
the name of the Lord has been, and is likely to be greatly dishonoured,
if things of this nature be not stopped, or prevented for time to come:
Therefore I beseech you all, who have the weight and sense of these things upon you,
let some speedy and effectual course be taken to prevent what possibly we may,
both in this and all other things,
that may any way cloud the glory of that sun which is risen amongst us.
And make this public, and send it abroad to be read in true fear and reverence,
and let all concerned be faithfully and plainly warned
(without respect of persons) by faithful friends,
who have the care of God`'s glory, and his church`'s peace and prosperity upon them:
So will the majesty and glory of God shine upon your heads,
and you shall be a good savour of life, both in them that are saved,
and in them that are lost.

Written by one who longs to see righteousness exalted, and all deceit confounded.

[.signed-section-context-close]
Gatten-place in Surrey, the 16th of the 11th month, 1678.

[.signed-section-signature]
Ambrose Rigge.

--
