== Chapter XV.

[.chapter-synopsis]
* Account of John Blakeling
* Gilbert Latey
* Anne Camm
* Persecuting Act, entitled "`Heretics,`" passed in the Colony of Connecticut
* Repealed by the Queen and Council.

John Blakeling of Draw-well in the parish of Sedbergh in Yorkshire,
on the border of Westmoreland,
was one amongst the earliest professors of the universality
of the light of grace which came by Jesus Christ;
himself, his wife,
his father and mother being people in estimation with most or all who knew them,
for their sobriety and religious conversation,
were all convinced by the ministry of George Fox,
when he first published his doctrine of the divine light in man in these parts,
viz. in the third month 1652.
About the beginning of the year 1655,
John Blakeling appeared as a public minister of the same doctrine,
and soon after travelled into the counties of Durham, Northumberland and Yorkshire.
A few years after that he travelled into Scotland, visiting a great part of that nation,
as also the northern counties of England in his way thither, and in his return.
He likewise travelled through most of the counties of the
nation at different times in the exercise of his ministry,
wherein his labours were very serviceable and very acceptable to his friends,
by whom he was greatly beloved and respected.

Being a man of primitive simplicity in his ministry,
he was more attentive to minister under the influence of divine power
and wisdom to reach and affect the heart with solid impressions,
than to please the ear by elegance of speech; although his testimony was not eloquent,
it was substantial in profound and important matter,
suitable to the states of the auditory to which he ministered.

In the discipline of the society he was eminently serviceable,
being endowed with clear discernment,
sound judgment and a good understanding in spiritual subjects,
as well as in temporal affairs,
whereby he was well qualified to give his sentiments
with pertinence to matters under deliberation;
he was remarkably zealous for the promotion and maintaining of good order in the church,
firm and steadfast in opposing and bearing testimony against contentious,
disorderly and licentious spirits,
against such as occasioned disrepute to the character of the society.
It was at his house at Draw-well,
that the memorable meeting was held for the recovery of John Wilkinson,
John Story and their adherents, as before recited.

His benevolence and charity to the deserving were no less remarkable,
than his zeal for good order.
A tender sympathizer with those in low circumstances,
he frequently assisted them in their difficulties, to the hazard of losing thereby,
and frequently had the satisfaction to see the good
effects of this exertion of his benevolence,
in being blessed with success for their effectual relief.

He had both the qualification and disposition to prevent
misunderstandings and promote peace being possessed of penetration,
judgment and patience, with impartiality,
to determine controversies and reconcile differences about temporal concerns;
his reputation for justice and knowledge in which,
produced the general confidence of his friends and others,
to devolve upon him various trusts for orphans,
etc. which he transacted with unspotted integrity; so that his removal,
even in an advanced age, was reputed a sensible loss,
not only in the society of which he was a member, but in his neighbourhood also.

His unspotted reputation did not exempt him from the sufferings attendant on his profession;
he was a considerable sufferer both in person and property.
In the year 1661, this friend, in company with many more,
was taken from a meeting at South Shields in the county of Durham by Major Graham,
then deputy governor of Tinmouth castle; they were cast into filthy holes there,
where they lay a month, and then he turned them out, having so far as appeared to them,
neither order, authority nor warrant for any part of his proceeding.
In 1664 he was imprisoned in York castle, sixty miles from his habitation,
being taken with about fifty more from a meeting at Thomas Taylor`'s in Sedbergh,
and after being detained some time in the custody of the constable,
they were ordered by the justices to appear at the sessions about a week after,
which they did; and John Blakeling, with about twenty others,
were from thence committed to the aforesaid castle.
In the year 1683 he was prosecuted in the arch-deacons court at Richmond,
and by a writ de excommunicato capiendo committed again to York castle,
where he was confined several years,
as appears by two petitions signed by him in company with other prisoners,
one to the King in 1684, the other to the Members of parliament for the county in 1685.
The following extract from the former exhibits a plain narrative
of the ruinous and unfair modes of plunder adopted by ill-principled
men against this inoffensive body of subjects for the vilest purposes:

[.embedded-content-document]
--

Divers persons convicted, fined and distrained upon the statute of 20£. a month,
were first presented and prosecuted upon the statute of 12d. a Sunday`'s absence,
and at the beginning of the sessions called upon the said presentment and prosecution;
yet during the sessions the prosecution was changed to 20£. a month,
and the informers and bailiffs who were appointed to make the distress, were so cruel,
and so destitute of common humanity,
that where there were not goods sufficient to gratify their avaricious desires,
they have taken the very beds from under the sick, their working tools from tradesmen,
and the entire property of all kinds from others,
so that many families have been totally ruined,
to the great grief of many sober people who had the
opportunity of observing their cruel usage.

Since the prosecution of our friends for monthly absence began by qui tams,
several of the worst sort of men, some who have wasted their own estates,
take this method of repairing them by the spoil of honest people.
Others who owe money upon bonds, being upon for payment, forthwith bring a qui tam,
and by this method discount and pay their debts,
or else clap the just creditor in prison, to lie there unless the bond be given up.
In the year 1671 he was fined 20£. 10s. for a meeting at his house.

--

While of ability of body he was a good example,
in a diligent attendance of religious meetings; but for some time before his death,
he was prevented by the infirmities attendant upon advanced age, during which,
he expressed the comfort,
which he enjoyed in the Lord`'s peace and presence with him in his old age,
that his day`'s work was nigh done, and his reward and rest with God was sure.
He often signified his preparedness to leave the world,
with fervent desires for truth`'s prosperity,
and the preservation of unity and concord amongst brethren,
in a faithful and steady testimony for the same in every part thereof.

He had a short sickness and an easy death,
passing quietly out of this world without a sigh or a groan,
in the eightieth year of his age,
and was honourably interred at Friends burying place at Sedbergh,
the fourth day of the 5th month, 1705.

Gilbert Latey, whom I have had repeated occasion to mention,
for his frequent solicitations to government in favour of his friends under sufferings,
died in the course of this year.
He was born of honest parents in the parish called St. Issey in Cornwall, in 1626.
His father was a reputable man,
his mother a gentlewoman of the principal family in the parish.
Gilbert being their youngest child,
and his elder brothers being settled in business abroad, and in a prosperous way,
he was desirous also to learn some trade; and being a promising youth, a person,
a tailor by trade, was desirous of taking him as an apprentice,
to whom he was bound accordingly, and served a severe apprenticeship with fidelity.

When the term of his apprenticeship was finished,
he removed for improvement in his occupation, first to Plymouth,
and afterwards to London, where he arrived in the 9th month, 1648.
He was a man of a sober conversation, and sincerely religious,
attaching himself to those pastors and teachers who
were in the greatest estimation at that time,
frequenting sermons with remarkable diligence,
and exercising himself much in private prayer: His integrity of heart,
seen by the all-inspecting eye, drew down the divine blessing on the labour of his hands,
which prospered his undertakings in business:
His religious regard to honesty pro cured him reputation,
and his reputation pro cured him the employment and cordial regard
of many persons of considerable rank and station in the world.
But his outward prosperity did not satisfy the desire of his soul,
which was to find peace with his maker:
In search of this attainment he had resorted from one preacher to another,
of those who were accounted the most refined,
and most eminent for piety and religious experience, but in his searching without,
he could not find what he wanted to obtain.

In the year 1654,
he heard that some men out of the North were to have
a meeting at the house of Sarah Mathews,
widow, to which he went; these men were Francis Howgill and Edward Burrough;
by the powerful and convincing ministry of the latter he was so effectually reached,
that he yielded assent to his doctrine of the light of Christ in man;
and not consulting with flesh and blood,
he turned his attention to follow the leadings of the Holy Spirit,
through the illumination whereof he attained a clear and discerning understanding,
and a sound judgment, by which he was qualified to become a serviceable assistant,
in these early times of the society,
previous to the establishing of a regular discipline,
to introduce and preserve order in the church in the city of London and places adjacent,
as well as in settling and keeping up the meetings in those parts,
being exemplary in attending and visiting them, from place to place,
as his concern drew him; although frequently in great jeopardy,
during the time of anarchy between Cromwell`'s death, and the restoration of King Charles,
when the rude populace were broken loose, and stimulated to rage and violence,
and would frequently stone them going to, in, and coming from their religious meetings,
to the shedding the blood and endangering the lives of many.^
footnote:[See vol. I. p. 266 etc.]

About this time I apprehend it was, that he met with a very close trial of his faith,
comparative to the cutting off the right hand:
He was still in a very prosperous way of business,
in which he employed many journeymen to answer the calls of his employers,
many of whom were persons of rank and fashion;
but being by the power of the cross of Christ induced to deny himself
of all superfluity and needless ornaments in his own apparel,
in conformity to the plainness of his profession,
and the doctrine of the apostles of Christ,
which was against the wearing of gold and silver and costly array:
The same principle of light and grace which had instructed
him to lay aside all superfluities in his own person,
instructed him further that he could not keep up his testimony
for the simplicity of the gospel with clearness,
while he was in the practice of furnishing to others those superfluities, which he had,
from conscientious conviction of their tendency to nourish a vain mind,
and their inconsistency with christian gravity and humility, laid aside.
In order to appease his conscience,
he was obliged to submit to the bitterness of the cross, and endure the shame,
by declining to adorn any apparel with superfluous ornaments of lace,
ribbons and such like needless trimming, or suffering his servants to do it;
which occasioned many to imagine he was going beside himself.
His customers left him; his trade declined;
he was obliged to dismiss his journeymen for want of employment;
his outward prospects were so discouraging that he did not know but,
that he might now be reduced to the necessity of
working in the capacity of a journeyman himself,
and of earning his bread by his daily labour:
Yet being thus strengthened to prefer the testimony of a
good conscience to the acquisition of temporary treasure,
and give up all the flattering prospects of this world for solid peace of mind,
possessing his soul in patience, and submitting to be accounted a fool for Christ`'s sake,
he experienced the kindness of divine providence supporting him through his trials;
so that as his outward discouragements abounded, his inward peace did much more abound;
and having faithfully sought the kingdom of God, and his righteousness;
all things necessary, for his accommodation in this life,
were added to his full content.

And although he lost the employment of many of his customers of rank and quality,
he did not lose their respectful esteem of his virtue and his integrity;
this they retained with kindness, which gave him ready access to them,
and others in authority and power;
many of whom were pleased to favour him with their
countenance and friendship on several occasions.
His interest and acquaintance with persons of high rank and station he applied,
not to his own emolument,
but to the relief of his friends under suffering in person or property;
deeply sympathizing with them in their various afflictions,
he was always forward to use his solicitations for their ease,
and frequently with signal success.

When intelligence was received in London of the imprisonment
of Katharine Evans and Sarah Cheevers,
in the inquisition of Malta;
Gilbert Latey (who in concert with George Fox was concerned for their release)^
footnote:[See vol.
2 p. 61.]
applied himself with solicitude to find out some person, if possible,
who had an interest or influence in those parts, and,
after some time and pains spent in the inquiry, he received information, that one,
called Lord D`'Aubigny, who had come over with the Queen Dowager,
and was Lord Almoner to her, had both interest,
power and authority in the island of Malta.
Gilbert upon receiving this intelligence,
thought it his duty to wait upon this Lord D`'Aubigny,
to request his interest and intercession for their release, which he readily promised.

He was a priest in orders according to the canons of the Romish church; yet no bigot,
but a man of a rational, liberal and generous spirit; Gilbert, to satisfy his inquiry,
gave him some information of friends principles and doctrine,
to which he answered to this purport, "`Some of our people think your friends are mad,
but I entertain a very different opinion.`"

Gilbert renewing his inquiry from time to time,
if Lord D`'Aubigny had received any answer to the
letters he had promised to write to Malta,
at length received from him the acceptable account
that his friends were restored to their liberty:
And some time after they arrived in England, and coming to London, paid Gilbert a visit;
and after acknowledging his love in his exertions for their release,
they requested him to introduce them to Lord D`'Aubigny,
whom God had made the instrument of their enlargement out of a severe bondage.
He readily complied with their request, and accompanied them to their benefactor,
to whom Gilbert, as usual, found ready admittance; when introducing his companions,
he said, these friends, who have been partakers of thy kindness,
are come to pay their acknowledgments to thee for the same; whereupon he asked,
if they were the women?
to which they replied they were;
and after their grateful acknowledgment of his great favour and kindness, added,
that were it in their power they would be as ready in all love to serve him:
Upon which he replied, good women, for what service or kindness I have done you,
all that I shall desire of you is, that when you pray to God,
you will remember me in your prayers, and so they parted.

Gilbert Latey was a party in most or all the solicitations to government
for the ease of Friends in the different cases or severe suffering,
through the reigns of King Charles, King James and King William,
as hath been already recited;
but it may not be impertinent briefly to mention two cases of application made by him,
in company with his faithful colleague George Whitehead,
which have not been noticed before.
The first was the suffering case of several Friends in Norwich,
under the cruelty of the sheriff and jailer, who, for attending their religious meetings,
were imprisoned to the number of sixty-three persons, and very severely treated;
ten of them being put into a deep dungeon, twenty-nine steps under ground;
and several others into a hole amongst felons.
An account of their grievous sufferings being sent to friends in London,
and ineffectual endeavours used for their redress,
being defeated by the misrepresentations of the sheriff;
George Whitehead and Gilbert Latey resolved to wait upon the king in person,
whom they met, with several nobles and attendants,
when they delivered the king a petition from Friends of Norwich,
and warmly solicited him in their favour: They had a pretty long conference with him,
and gave him pertinent answers to several inquiries he made
in respect to the singular conduct of Friends in some cases;
yet still keeping the cause of their application in view,
repeatedly entreated him to compassionate the case of their suffering Friends in Norwich:
In fine,
the king being sensible that some of their treatment was not only cruel but illegal,
assured them he would have it searched into, and consider their case.
The assizes coming on soon after, the prisoners were called,
to whom the judges behaved with remarkable moderation,
and released them from their imprisonment, acting, as there was ground to suppose,
according to the instructions they had from the king in consequence of this application.

The other case not before related was concerning the Park and Savoy meeting-houses;
the case of the Park meeting-house was this:

About the month called May, 1685,
the soldiers possessed themselves of this meeting-house,
and converted part of it into a guard-house: Then,
as if their forcible entrance had given them a right of possession,
they made great waste upon the premises, pulling down pales,
digging up and cutting down the trees, tearing down the wainscots,
and burning them and the benches, carrying away the outward door,
and several of the casements.
Afterward, when they were drawn out to the camp,
they left the house open to any intrusion.
John Potter, in whom the title was vested, reentered, enclosed the outward door,
and made other repairs, and had a survey taken of the damages,
which were esimated at 40£.

The soldiers returning again from camp,
a quarter-master belonging to Colonel Haile`'s regiment,
came to the chambers of the said John Potter, and demanded entrance, which was refused:
The quarter-master, assisted by soldiers, broke in, handed away the goods,
turned out three aged women to another house,
and made alterations in the meeting-house for their accommodation,
as if they meant to keep perpetual possession.
John Potter several times showed the colonel his lease, and title to the place;
but it availed nothing, he and his soldiers regarding neither law nor equity,
kept possession, and still continued there.

Gilbert Latey and George Whitehead agreed to join in a solicitation
to King James for redress of this grievance,
and having gained admittance to his presence,
represented to him the hardships Friends were under,
by having their property wrested from them, both at the Park, and at the Savoy likewise,
where Friends had been kept out in the cold yard in the winter many weeks by the guard.
The King, who appears not to have been unconcerned in the matter, would needs have it,
that these meeting-houses were forfeited to him by the conventicle act;
but this they clearly disproved,
and showed so plainly the unreasonableness and illegality there of,
that within a few weeks, he caused both the meeting-houses to be restored,
after the former was damaged, by computation to the amount of 150£.

But it was not only in these solicitations to the rulers,
that the public spirit and brotherly sympathy of Gilbert
Latey were excited to the service and relief of his friends;
they were uniformly exerted in every case,
which might demand his friendly assistance and attentive care, being one of those,
who in early times had tender concern for the poor, fatherless and widows;
the sick and the imprisoned, to inquire into their necessities, and supply their wants;
and when through persecution by imprisonment or distraints, casualties of disasters,
the number greatly increased;
he was amongst the first to see the propriety and necessity
of calling in grave and motherly women to their assistance,
that so none under these descriptions might suffer for want
of attention and care in any part of the city.

In 1665, when the destructive pestilence broke out in the city of London,
and the generality of citizens, who were able,
were fleeing for their lives to the country,
this friend had taken lodgings to retreat to the country also;
but was prevented by the consideration,
that many of his brethren were detained in several
jails for the testimony of a good conscience,
particularly in Newgate and the Gate-house in Westminster, in the midst of the contagion:
For he could now feel no freedom to leave the city,
and desert his friends under their multiplied calamities;
he therefore kept his habitation, and according to his usual custom,
visited those in prison; to comfort them in their distress;
to take care that nothing might be wanting for their relief, support or enlargement,
as far as in his power.

And although his friends in prison in this calamitous season engaged his especial care,
yet as the calamity was general, and not confined to prisons,
neither were his sympathetic feelings;
he was also diligently employed at this season visiting Friends in their families,
both where they were laid up with the sickness, and where they were recovering,
still under a concern nothing should be wanting for their comfort or support.
And the hearts of Friends being opened in brotherly sympathy with those,
who were afflicted with this epidemic distemper,
money was collected and sent up from the country to be distributed, where needful;
the care of this distribution was committed to Gilbert Latey and one other friend,
to divide amongst poor Friends who were lying ill of the contagion;
but more especially those who were shut up in their houses in the out parishes.
This trust they were careful to discharge with diligence and fidelity, inquiring out,
and visiting thole poor, who were confined to their own houses,
and distributing to their necessities; and passing by none that they could hear of,
through all which he was mercifully preserved in health,
till the contagion was much abated, and the mortality was decreasing,
when occasionally taking a cold, it brought on the prevailing distemper;
but the divine providence was over him for good,
brought him safely through the distemper, and restored him to health again,
to persevere in doing good in his generation.

We are now to view him in another light, as a minister of the gospel.
Soon after that close trial of his faith, when in obedience to manifested duty,
he relinquished his worldly prosperity,
and declined to sit out the clothes he had to make with superfluous trimming,
he received a gift in the ministry, in which he also laboured faithfully,
according to the ability received, and some were convinced, and many comforted,
encouraged and strengthened in the way of righteousness and peace.
His service in this line, as well as the former,
was much restricted to the city of London, and the vicinity thereof,
where he was zealously engaged,
in the early times of the society to settle or keep up meetings in convenient places,
as at Kingston, Hammersmith, Westminster and other places;
and was frequent in his visits thereto, as he found his mind drawn to one or another.

Yet he paid two religious visits to his native country, the first in 1670,
being a time of great persecution.
He took the meetings of Friends in his way, Reading, Bristol, Bridgewater, South Moulton,
so into Cornwall, having several good meetings on his journey thither,
as well as in that county.
At John Ellis`'s, near the Lands-end,
he had a comfortable edifying meeting on the first day of the week,
and next morning going to visit some Friends very near the Lands-end,
he met a persecuting justice, who, as Gilbert was afterwards informed,
was highly displeased that his accomplices had neglected to give him timely information,
that he might have seized Gilbert`'s horse, and his man`'s, for that day`'s meeting.

Thence returning by Penzance and Market-jew,
near this latter he had a meeting at a place where no friends were settled,
to the great satisfaction of several present,
who had never been at a friends meeting before.
He proceeded to Helston and Falmouth, and had a meeting there;
and from thence went back to Loveday Hambley`'s, and had a good meeting there,
and at several other places in that country.

Leaving Cornwall he returned towards London by Plymouth,
and having visited Friends there, he proceeded to King`'s-bridge,
and contrary to his own and Friends`' expectation had a peaceable good meeting;
for Friends here were under grievous persecution;
he therefore spent a little time amongst them,
strengthening and tenderly sympathizing with them in their sufferings,
and particularly with two young women who had not been long convinced,
and were committed to prison by a warrant from justice Biere,
(a passionate persecutor of this people) for not coming to church to hear divine worship.
Gilbert from that fraternal sympathy,
which on all needful occasions excited him to use
his endeavours for the relief of his friends,
resolved to renew them in behalf of these young women,
and having an acquaintance with some who were in the lieutenancy,
and men of authority in the commission of the peace, he came to Exeter,
and having visited Friends there,
proceeded to the house of a knight of great influence in the county,
to whom he found ready access, and who expressed himself glad to see him in those parts:
Gilbert let him know the occasion of his visit,
and so warmly solicited his favour to his suffering friends,
and these two young women in particular, that the knight at last replied,
he would do more for him than any other of his friends,
and having by his application brought the knight to that favourable disposition,
which gave him reason to hope he had obtained the end of his visit,
he took his leave of him and his family, with acknowledgments of his kindness;
and after his return, received an account that this knight,
mindful of the expectations given him, had procured the liberty of these young women.

He had now received letters from London, in forming him of the persecution,
which affected Friends there in person and property;
of the demolition of the meeting-houses at Horsly-down and Ratcliff;
and that Wheeler-street meeting house was threatened,
the title of which was vested in him;
he therefore hastened back to London with what expedition he could,
with clearness as to his present service,
and when arrived took the measures already related,
to secure that meeting-house from similar depredation.^
footnote:[See vol. 2. p. 353.]

His second journey was in the year 1679, into the same quarter, visiting his friends,
and appointing or holding meetings with them to mutual
edification in his going and returning,
viz. at Reading, Bath, Bristol, through Somerset shire,
the North of Devonshire to Falmouth in Cornwall,
returning by the South side of Devon shire.
As it seemed to be Gilbert`'s peculiar province to keep up a friendly intercourse with,
and an open door of access to such persons of authority or influence as had been,
or might be disposed to apply them to the relief of Friends.
And Lamplugh then Bishop of Exeter, having granted him several favours,
in respect to Friends under sufferings in his diocese;
and upon a solicitous inquiry now as he passed along,
finding the moderation and tenderness both of himself and the officers of his court,
under his influence, to have been extended to friends in a general way,
he thought it his place to pay him a visit,
to acknowledge his extraordinary kindness to his Friends.
The Bishop received him with remarkable civility and affectionate regard;
their conversation was expressive of sincere friendship and mutual benevolence,
which being ended,
Gilbert took his leave with expressing the grateful
acknowledgments he proposed by this visit.

This Friend, although a resident in London through all the heat of persecution,
and although exemplary diligent in attending meetings in their public meeting-houses,
while they were permitted to meet in them, and in the streets in all weathers,
when they were not;
escaped sufferings and imprisonment beyond most of his brethren of that time;
most of his sufferings appear to have befallen him previous to the restoration;
feeling a concern, with many of his Friends of this age,
to go to several of the places of public worship,
to bear witness to the truth and against error.
Amongst other places, he went one day to Dunstan`'s in the West,
at which +++_______+++ Manton preached on this subject, who might of right call God father,
on which he enlarged first, that they who were born of God,
were his through regeneration, and had a just right to call God father.
To this doctrine Gilbert attended with patience and assent;
but afterwards proceeded to inquire concerning those who were not born of God,
he alleged they were the Lord`'s by generation; and then in answer to this question,
whether they must not call God father, replied,
That they must also pray to God as their father, and to prove his assertion, said,
though Absalom was a wicked son, yet David was his father.
After he had ended his sermon, Gilbert warned the audience to take heed of their ways,
adding, that while people are workers of iniquity,
according to the doctrine of our blessed Lord, they are "`of their father the devil:
and while they regard iniquity in their hearts the Lord will not hear their prayers.`"
The people were immediately all in a ferment, the constable was called for,
who with others haled him out of their place of worship, and took him before a justice,
where he pleaded his cause so well,
that the justice asking the constable if what he said was true,
and if that was the whole matter; the constable answering in the affirmative,
the justice observed that he had heard those people
called Quakers were a sort of mad whimsical folks;
but for this man he talks very rationally,
and for my part I think you need not have brought him before me;
to which the constable replied, Sir, I think so too.
The constable and Gilbert retiring,
the former left him at liberty to go whither he pleased.

He also suffered imprisonment, together with about fifteen or sixteen of his friends,
in the Gate-house in Westminster, for meeting together to worship God:
They were all put into a little dungeon, which was about ten feet in breadth,
and eleven in length, and so dark, that they could see no more by day than by night;
the walls were wet, and they being crowded into so narrow a compass,
had room only to lie down by turns; so that while some lay down to rest,
others were forced to stand:
Beside this the keeper was so cruel as to command the turnkey not
to let a little straw be brought in for them to lie upon;
but the Lord was with them to support them through
all the trials of their faith and patience;
and in his own time delivered them from their sufferings.

During the reign of King Charles I cannot discover that he was ever imprisoned,
notwithstanding the frequent persecutions that raged without restraint.
Being a great supporter and frequent attender of the meeting at Hammersmith,
in the year 1671, having occasion in the way of his trade to wait upon Lady Sawkell;
Sir William Sawkell her husband, who had a command in a regiment of horse,
came into the room; he had a friendly respect for Gilbert,
and was often pretty familiar with him 5 and now asked him what meeting he frequented,
who answered sometime one meeting and sometime another.
The reason is, said Sir William,
be cause I have orders to break up a meeting of your people at Hammersmith next Sunday,
from so high a hand, that I cannot avoid executing them; and therefore, I inform you,
that if at any time you go thither, you may refrain coming on that day.
Gilbert notwithstanding, believing it his duty to attend Hammersmith meeting,
let Sir William know it before they parted.
The day came, Gilbert, not reasoning with flesh and blood, attended the meeting,
in which he was much favoured, and as he was preaching, the troopers came,
and stood for some time to hear his testimony, till one of the ruder sort,
cried out this man will never have done let us pull him down,
and accordingly laid hands on him.
Gilbert sent word to the commanding officer; who coming in, said, Latey,
did not I tell you that I was commanded to be here to day?
Yes, replied Gilbert, and did not I tell thee I was commanded by a greater than thou,
to be here also?
Upon this, said Sir William, go get thee gone about thy business,
and I will take care of the rest who are met here; Gilbert desired him,
if he had any respect for him to discharge the rest, and let him be his prisoner.
After some time the rest were set at liberty,
and Gilbert taken before Lord Mordaunt and Sir James Smith;
the troopers were called in evidence,
and Gilbert made his defence so reasonably and discreetly,
that it seemed to make an impression upon them, yet they fined him and the house,
and distrained some Friends for the fines.
Gilbert got access to the justices again,
and showed them the unreasonableness of that severe law,
which made one man suffer for the offence of another;
that if he had transgressed any law, the Lord had blessed him with a sufficiency,
to enable them to reclaim the penalty from his effects,
and requested that his friends might not suffer for any thing by him said or done;
through his repeated applications, and the interest and influence of others,
their equals and acquaintance, he procured the goods distrained to be restored;
and had the satisfaction to see the sufferings designed to the Friends of that meeting,
through divine goodness, and his solicitous endeavours, prevented.

In his more private transactions in religious society,
he was a lover and promoter of unity and concord;
very zealous against deceit and hypocrisy, the fomenting of divisions and schisms;
but remarkably tender towards those who appeared sincere and humble,
although weak and young in experience, and always ready to lend a hand of help to such:
He had ever an honourable esteem for the elders, who were in Christ be fore him;
and it was his great rejoicing to see the younger members treading in their steps;
and when any of these were raised up in the ministry, as they kept to that power,
which made their predecessors burning and shining lights in their day,
his rejoicing was increased; these he encouraged with affectionate sympathy.

In his own family he was an exemplary pattern of conjugal affection, and paternal care,
being often solicitously concerned to admonish and instruct
his children to live in the fear of their creator,
that they might thereby be preserved from evil.

As age advanced, and subjected him to the attendant infirmities of body,
his mental faculties and religious feelings preserved their usual vigour and liveliness.
His last public appearance in the ministry was in a meeting at Hammersmith;
he was so raised up in his gift, and so supported by divine power,
that with great authority and clearness,
he delivered sound and weighty doctrine for near an hour,
with fervency and his accustomed zeal, as if he had been under no infirmity of body,
to the admiration of many of the auditory.

Towards the latter part of his time he delighted much to be retired,
and dwelt mostly in the country: And having served God and man in his generation,
the review of his life filled him with consolation in his retreat,
having been often heard to say, that he had done the work of his day faithfully,
and was now sat down in the will of God, and his peace he felt abounding towards him;
that he waited the Lord`'s call and time of being removed,
and that there was no cloud in his way.
He was also in the time of his confinement, so strengthened in his spirit,
and his love to his brethren, that he gave them much good counsel,
when they came to see him, with as much energy and liveliness,
as if he was in his health and strength: A very few hours before his departure,
he said to those about him, there is no condemnation to them, that are in Christ Jesus;
he is the lifter up of my head, he is my strength and great salvation:
In this frame of mind he breathed his last, the 15th day of the 9th month, 1705,
in the seventy-ninth year of his age.

This year Anne Camm, late-wife of Thomas Camm,
a woman eminent in her day for the excellency of her qualifications,
and her service in society, died in an advanced age.
She was the daughter of Richard Newby, of the parish of Kendal in Westmorland,
of a family of repute; her parents gave her a good education, proper for her sex,
and about the 13th year of her age sent her up to
her aunt in London for her further improvement,
with whom she resided seven years;
and being favoured with religious inclinations from her early youth,
she formed her acquaintance and connection with the Puritans,
from her apprehension of their being the most strictly religious sect.
And upon her return to Kendal,
seeking still to associate herself with the most serious professors of religion,
she joined a body of people, who frequently met in a select society,
sometimes sitting in silence, sometimes holding religious conferences,
and often exercised in fervent prayer.
About the year 1650 she was married to John Audland,
and was convinced at the same time with him by the ministry of George Fox,
early in the year 1652;
and in the course of the succeeding year they both appeared in the ministry,
to the edification of their friends and convincement of many others;
for she was in all respects a most agreeable help-meet to her valuable husband,
endeared to him by a similarity of disposition, qualifications and pursuits,
feelingly described by her in her testimony concerning him.^
footnote:[See vol. 2. p. 88.]

Her first journey in the work of the ministry was into the county of Durham.
At Aukland,
for preaching to the people on the market day she was imprisoned in the town jail;
but a prison could not confine the freedom of her spirit,
or the charitable concern of her mind for propagating religious truths
and religious thoughtfulness amongst the people assembled there.
Under the influence of gospel love, and in the authority of the gospel,
she continued her ministry from the window of the prison,
whereby many were solidly affected, and confessed to the truth she published.
She was discharged from her confinement the evening of the same day.
John Langstaff, a man of great repute in his neighbourhood,
was so affected by her ministry, that he voluntarily accompanied her in her imprisonment,
and upon her release, took her home with him, in order to entertain her there.
But his wife, offended at her husband`'s conduct and apparent change,
received him and his guest with language,
which plainly discovered her dissatisfaction with them both;
this treatment made Anne quite uneasy to take up her lodging under a roof,
where she found she was no welcome guest to one head of the house;
she therefore walked out into the fields, to seek some covert, to take such lodging,
as she could find there.
But it was providentially ordered that Anthony Pearson, of Rampshaw,
hearing by George Fox, who was then at his house, of her being in that town,
came with a horse, and took her behind him to his house that night.
She continued her travels in those parts some time longer,
in the exercise of her ministry, to the spiritual advantage of many,
and when she apprehended her service accomplished, returned home.

In the succeeding winter she travelled Southward through Yorkshire, Derbyshire,
Leicestershire, and so forward into Oxfordshire, accompanied by Mabel Camm,
wife of John Camm.
At Banbury, Mabel apprehended a call of duty to go to the place of public worship,
to speak to the priest and people; and Anne accompanied her.
The people dragged them out of the house in a rude and violent manner,
and abused them in the yard: The priest passing by, Anne Audland called to him, saying,
"`Behold the fruits of thy ministry.`" Next day they were summoned before the mayor,
where two witnesses were procured to swear that Anne had spoken blasphemy;
and upon their information she was committed to prison, and her companion dismissed.
Some days after,
two inhabitants of the town gave bond for her appearance at the next assizes,
which furnished her with several opportunities of religious
meetings with the people of that town and neighbourhood,
in which she was so favoured with power and wisdom in the exercise of her ministry,
that it proved effectual to convince her two bondsmen, and numbers more,
of the truths she preached to them,
where by they were induced to join in society with her and her brethren,
and in an inward attention to the grace of God which brings salvation,
which she bore testimony of, and recommended them unto.
The establishment of a large meeting in that town,
and several other meetings in the country adjacent, were the fruits of her minis try;
and to her friends here she cherished the most affectionate regard to the last.
Her successful labour provoked the resentment of
the adversaries of the society to that degree,
that they threatened she should be burnt when the assizes came.
Her enemies being numerous, powerful and much exasperated against her,
several of her friends thought it their duty to attend the assizes,
to strengthen her by their sympathy, countenance and assistance,
in maintaining her cause and the cause of truth.

Her husband John Audland, John Camm, Thomas Camm,
with some friends from Londo and Bristol, encouraged her by their presence at her trial.
The charge or indictment of blasphemy was this, that she said God did not live;
which charge was founded on a perversion of a remark
she made concerning the priest of Banbury,
That true words might be a lie in the mouth of some that spoke them:
In proof and explanation whereof she brought the expression of the prophet Jeremiah,
chap.
5:2. though they say the Lord liveth, surely they swear falsely.
Her prudent demeanour, her judicious remarks, her innocent boldness,
tempered with becoming modesty,
and her pertinent and wise answers to his questions inclined
the judge to moderation and sentiments in her favour;
and perceiving the incompetence of the evidence,
that the matter of fact did not come up to the charge,
he expounded her case to the jury thus,
that she acknowledged the Lord her God and redeemer to live,
and that there were Gods of the Heathen that were dead Gods.
Some of the justices hereby perceiving their wishes and intentions to be frustrated,
stepped from the bench to influence and bias the jury to
bring in some verdict whereby their credit might be saved,
who brought in their verdict, guilty of misdemeanour only,
which occasioned one of her friends to observe, that,
"`it was illegal to indict her for one fact, and bring her in guilty of another;
for they ought to have found her guilty or not guilty,
upon the matter of fact charged in the indictment.`" The judge then told her,
if she would give bond for her good behaviour she might have her liberty;
this she refused, for the like reason as her brethren generally did.
Her prosecutors, ashamed of their proceedings,
slipped off the bench one after another in confusion; and the judge,
although in the trial he behaved with candour,
and confessed she should have been discharged;
yet to gratify the disappointed and angry justices,
returned her to prison upon her refusal to give bond.

Being now left in the power of these persecuting magistrates,
she was put into a noisome filthy dungeon, several steps below the ground,
on one side whereof ran a common fewer, which was often very offensive by its smell,
and admitted disagreeable vermin, and there was no fire to qualify the damps.

Jane Waugh, also a minister of this society, from the pure motive of friendship,
affection and sympathy with her imprisoned friend, came many miles to visit her there,
and was rewarded for this christian-like office of love,
with a participation of her suffering, being for this cause only, imprisoned with her.
Here they enjoyed great content, in the consciousness of suffering in a good cause.
In great peace she continued seven or eight months in this noisome dungeon,
and at length was released by the Mayor and Aldermen,
and her companion shortly after at her solicitation.

At her release, being clear of those parts, she travelled through the country to Bristol,
where she met with her husband John Audland, whom I apprehend she accompanied,
and joined in service, to their habitation in Westmorland.
The reader may recollect the reflections suggested by the contemplation
of this amiable couple in the account of her husband`'s decease,
which it is therefore superfluous to repeat They were both engaged
in frequent travels for the purpose of promoting religion,
and righteousness, in most parts of the nation, as far as I can collect,
some times unitedly, and some times separately,
until her husband was disabled by that indisposition,
which terminated in his death in the year 1663.

She continued a widow between two and three years, and in the 3rd mo 1666,
was married to Thomas Camm, son of John Gamin, her former husband`'s faithful companion.
This her second husband was also a man, experienced in religion,
and a minister of eminence in the society of his friends.
Their union being centered in religion and the fear and united service of their maker,
they lived together in the utmost harmony and nearness, of affection forty years,
within a few months.
An union on this certain foundation of happiness,
naturally revives the recollection of the comprehensive
description which the Evangelist +++[+++Luke]
hath left on record, of a religious pain of that, age: They,
were both righteous before God, walking in all the commandments of the Lord blameless.
And here I feel an inclination to say before my young friends,
as I trust this may fall into many of their hands, the wise and solid maxims,
which were adopted by our faithful predecessors for the rule of
their conduct in this very important engagement of marriage,
as that on which not only our peace and happiness in this life very much depends;
but that whereby our efforts in the pursuit of future happiness may frequently,
be very materially promoted or obstructed.
It was a maxim with them, as firmly believed as the most self-evident truth,
that the only sure foundation of happiness was laid in religion, and therefore their,
advice and their practice was, to seek for divine counsel and approbation,
in every step towards forming this indissoluble connection,
and to proceed circumspectly in the fear of their creator.
Both male and female, having their eye principally to an everlasting inheritance,
incorruptible, and that fadeth not away, were exceedingly circumspect in their stepping,
that their growth in pure religion might not be retarded thereby; the former,
by fervent prayers, seeking to the Almighty to be lightly directed in his choice;
and the latter, receiving the proposal with cautious reserve, pondered it in her heart,
and also besought the same divine being to direct her in her determination.
Marriage thus determined in religious fear, and, on religious considerations,
in the divine counsel, is doubtless ratified in heaven,
and draws down a blessing upon the parties thus uniting themselves in one holy disposition,
and one determined resolution to promote their own,
and each others spiritual and temporal advantage.
This pure religion proves a foundation of uninterrupted harmony between themselves,
and a stay and a staff in the vicissitudes of this life, to which all are liable;
in prosperous circumstances a stay to the mind, when riches increase,
not to set their hearts thereupon, nor to consume them on their lusts,
after the manner of this world; but to let their moderation appear,
knowing the Lord is at hand, as stewards only of the good things they possess,
and accountable to the Lord of the universe, whose the earth is and the fulness thereof;
the natural benevolence of their souls, refined by religion into christian charity,
teacheth them to sympathize with, and feel deeply for the poor and needy,
and to communicate freely to their wants;
in adversity and the various trials they are exposed to,
they ever find it a staff to lean upon, sufficiently able to support them,
and bring them safely through all their afflictions and besetments,
and in the end find all things work together for their good,
because they fear and serve the Lord.

This worthy woman, Anne Camm, proved this truth,
for she bore her share of the sufferings of this trying day,
steadfast in her faith in divine support,
in which she found ability to sustain them with patient resignation and religious fortitude.
She was tried with repeated separations from her second husband, as well as the former,
by a succession of tedious and close imprisonments.
He was imprisoned particularly at Kendal for the space of three years,
where his confinement was so close that he was not
permitted to see his family during that time:
Again, at Appleby, near six years;
and in all his sufferings and services she participated with him as a faithful help-meet;
in the former sympathizing with,
and strengthening him in his suffering for the testimony of a good conscience,
supplying his place during his confinement, and without doubt exerting her care,
to keep their outward concerns in the best order in her power,
for she appears to have been a very virtuous and discreet woman.
And in his religious labours and services,
she was not only free to give him up and encourage him to faithfulness,
but often a powerful fellow-labourer in the gospel along with him,
for they travelled together several journeys as companions in the work of the ministry,
in sundry parts of the nation,
and particularly to London and Bristol more often than once,
at the latter of which she was seized with an indisposition,
which appeared to threaten her dissolution; but was raised above the fear of death,
and preserved in a lively frame of spirit,
wherein her expressions were so weighty and affecting,
as to leave a lasting impression on the minds of several of the auditors,
warning all to prize their time, and prepare for their latter end,
as God had inclined her to do, whereby she enjoyed unspeakable peace here,
with full assurance of eternal rest and felicity in the world to come, which, said she,
I have desired to enter into, as gain, rather than live, if God so please.
But the period of her zealous labours for the promoting of righteousness
was not by divine wisdom assigned her at this time;
she recovered her health and strength, to be of great service in society,
for a length of time.

Although she was in honourable esteem, as she deserved, for her accomplishments,
her virtues and her public services, she was preserved in humility,
not affecting to do her works to be seen of men,
but frequently retired alone into her closet or other private place,
in fervent prayer to seek the approbation of her maker,
and the fresh discovery of his will concerning her;
or set apart an hour for perusing the holy scriptures,
and other pious writings for her edification.
And though qualified above many with an excellent gift in the ministry,
she was by no means for ward to appear in preaching or prayer in public meetings;
but when she did, it was with the demonstration of the spirit and with power,
to the refreshment of the church: And especially in large meetings,
where she knew there were brethren well qualified for the service of such meetings,
she rarely appeared as a public minister without an extraordinary impulse,
for she was endued with wisdom and a sound understanding,
to know the season of her service, when to speak and when to be silent,
in which she was a good example to her sex;
and when any of them were too hasty or unseasonable
in their public appearances in such meetings,
being a woman of found judgment, and disapproving thereof,
she frequently found it her concern to hint an admonition to such,
in the authority of the gospel, and in the meekness of wisdom,
which generally had a good effect.

Her last public appearance in the ministry,
was at a monthly meeting at Kendal the 2nd of 9thmo, 1705, at which time,
though far advanced in years,
and affected with the bodily infirmity attendant on old age,
the liveliness of her zeal and her spiritual abilities
maintained their vigour even to admiration.
In this her farewell sermon, with affecting energy,
she closely pressed her friends to faithfulness and diligence in the service of the Lord,
that they might receive their reward with those who had nearly served out their day.

The next day she was seized with that distemper which terminated her labours,
and her end was such as naturally resulted from a well spent life; full of peace,
she resigned her soul to him who gave it,
in humble expectation of reaping the fruit of her labours,
the sentence of approbation--Well done, good and faithful servant,
as manifestly appeared by her expressions on her deathbed.
Her husband, who knew best her worth, impressed with a deep sense of sorrow,
and discovering the natural regret at the prospect
of being deprived of so valuable a companion,
she nobly encouraged to resignation in the following address.
"`My dear, if it be God`'s good pleasure, who joined us together,
and hath blessed us hitherto, to separate us outwardly,
I entreat thee to be content therewith, and give me up freely to the Lord,
for thou knowest we must part; and if I go first,
it is but what I have desired of the Lord many a time;
and I believe the consideration of the desolate condition I should be in,
if left behind thee, will have that place in thee,
that thou wilt the more freely commit me to the Lord, whose I am, and whom I loved,
feared and served with an upright heart all my days: His unspeakable peace I enjoy,
and his saving health is my portion forever.
I pray thee be content with what the Lord pleaseth to do with me, whether life or death,
his holy will be done.`" And when she drew near her end, about ten days before she died;
she imparted profitable counsel to her grand children and servants:
and renewed her request to her husband to give her up freely, adding,
"`If it be the time of our parting, as I think it will,
I pray thee quit thyself of the things of this world, as much as possible,
that thou mayst with the more freedom pursue thy honourable
service for truth to the end of thy days--and warn all,
but especially the rich, to keep low, and not to be high-minded,
for humility and holiness are the badges of our profession.`" Her
distemper increased upon her near a month before her change came,
during all which time, her weighty counsel, her edifying remarks,
and perfect resignation of mind clearly evinced she
was well prepared for her final change,
which happened on the 30th of 9th mo 1705,
and the attendance of her funeral was an evidence of the
universal estimation of her virtues and her services,
her corpse being accompanied to the grave by friends from 13 different meetings.

The persecution of the Quakers in New-England had subsided in a great degree,
since the removal of the principal persecutors by death,
and a train of succeeding occurrences of a very serious and interesting nature,
which necessarily drew off their attention, to provide against more imminent dangers,
and more certain evils.
The Indian wars, the loss of their charter and their power;
their succeeding political contests amongst themselves;
and after their Charter was renewed by King William,
their general infatuations in the business of witchcraft,
had given them sufficient employment;
whereby this peaceable body of people obtained a respite of their sufferings,
till the Act of Toleration set them at liberty to enjoy that peace they desired.
But no sooner had the state recovered from its commotions, and returned to a settlement,
than the colony of Connecticut first discovered a propensity,
notwithstanding the toleration,
to revive the former oppressive measures against this society,
by passing an act entitled Heretics, in relation whereto,
application being made to the Queen and Counsel, it produced the following order,
by which the purport of this act will appear of a
nature similar to their former persecuting acts.

[.embedded-content-document.legal]
--

[.signed-section-context-open]
At the Court of Kensington, the 11th day of October, 1705,

[.no-indent.emphasized]
Present

His Royal Highness Prince George of Denmark

Lord Archbishop of Canterbury

Lord Keeper

Lord Treasurer

Lord President

Duke of Somerset

Duke of Ormond

Earl of Ranelagh

Mr. Boyle

Mr. Secretary Hedges

Mr. Secretary Harley

Lord Chief Justice Holt

Lord Chief Justice Trevor

Mr. Vernon

Mr. Earle.

[.small-break]
'''

A representation from the lords commissioners of trade and plantations,
being this day read at the board,
upon an act passed in her Majesty`'s colony of Connecticut, entitled only Heretics,
whereby it is enacted, that all who shall entertain any Quakers, Ranters, Adamites,
and other Heretics, are made liable to the penalty of five pounds,
and five pounds per week for any town that shall so entertain them;
That all Quakers shall be committed to prison, or be sent out of the colony;
that whoever shall hold unnecessary discourse with Quakers,
shall forfeit twenty shillings; That whoever shall keep any Quakers books, (the governor,
magistrates, and elders excepted) shall forfeit ten shillings,
and that all such books shall be suppressed;
That no master of any vessel do land any Quaker without carrying them away again,
under the penalty of twenty pounds.

And the said lords commissioners, humbly offering,
that the said act be repealed by her majesty,
it being contrary to the liberty of conscience indulged
to dissenters by the laws of England;
as also to the charter granted to that colony.

Her Majesty, with the advice of her privy council,
is pleased to declare her disallowance and disapprobation of the said act;
and pursuant to her majesty`'s royal pleasure thereupon,
the said act passed in her majesty`'s colony of Connecticut in New-England,
entitled Heretics, is hereby repealed, and declared null and void, and of none effect.

--

In gratitude for this repeal,
friends in London thought it their duty to present an address to the Queen,
which address, with her answer, are as followeth:

[.embedded-content-document.address]
--

[.salutation]
May it please the Queen,

We thy protestant dissenting subjects, commonly called Quakers, in London,
having lately been the Queen`'s humble petitioners on the behalf of our friends in New-England,
against a law made in Connecticut colony for their suppression,
which law the Queen has been graciously pleased to disallow and make void,

We now find ourselves engaged in duty and gratitude to make the
just returns of our thankful acknowledgments to the Queen,
for this eminent instance of inviolably maintaining the toleration;
and do therefore humbly crave leave, on this occasion,
to repeat the sincere assurance of our christian and peaceable subjection and.
unfeigned joy for the Queen`'s mild and gentle government,
aiming at the good of all her people.

May the blessing of the Almighty so prosper and accomplish
the Queen`'s just desires of union among her subjects,
of firm peace in Europe, and of the increase of virtue,
that in the delightful fruition thereof, the Queen may enjoy many days,
and after a life of comfort, be translated to a glorious immortality.
Signed on behalf of the said people by

[.signed-section-signature]
John Field,

[.signed-section-signature]
Joseph Wyeth.

--

[.embedded-content-document]
--

[.old-style]
=== The Queen`'s Answer.

Let the gentlemen know I thank them heartily for this address,
and that while they continue so good subjects, they need not doubt of my protection.

--

The repealing of this act put a final period to the persecuting of Quakers in New-England:
And as the rigorous measures pursued against them
at their first appearance in that colony,
and for a series of years after,
may appear to have been treated with some severity of animadversion (as they deserved),
it is but justice to observe, that the descendants of these colonists,
perceiving the enormous mistakes of their predecessors,
have adopted more liberal and humane maxims of conduct;
so that for several years past this body of people have been treated with lenity,
and have been in some respects more easy in the New-England provinces than in most others,
Pennsylvania and Jersey excepted;
particularly in an entire exemption from any contribution
to the support of the established ministry.
