== Chapter XVI.

[.chapter-synopsis]
* Address to Queen Anne on the Prevention of a Rebellion
* Account of Thomas Camm
* His sufferings
* His Death and Character
* Second Address to the Queen on declaring her Resolution to maintain the Toleration
* Account of John Banks
* Account of William Crouch

The incorporation of England and Scotland into one kingdom,
which was a favourite measure with James the First;
and had also engaged the attention of King William,
but which neither of them could get effected, was brought about this year,
under the title of The Kingdom of Great Britain.
The Scotch nation in general being quite averse to this union,
it created great discontents among all the classes of the people.
Lewis XIV king of France,
being at this time unable to cope with his confederated enemies in the Netherlands,
of which the English were amongst the most formidable,
looked upon this disaffection of Scotland to the English government,
to present a favourable opportunity to divide the allied forces,
by giving employment to the British arms, at home.
With this view, he made great preparations to support the Pretender,
in an invasion of England, at the head of the Scotch malcontents;
but the vigilance of the British government was the means of defeating his design.
Addresses of allegiance or congratulation having been sent
up to the Queen from different parts upon this occasion,
the people called Quakers thought it expedient, from their yearly meeting,
to present the following address.

[.embedded-content-document.address]
--

[.letter-heading]
To Anne Queen of Great Britain, etc.

[.blurb]
=== The grateful and humble Address of the people commonly called Quakers, from their yearly meeting in London this 28th day of the third month called May, 1708.

We having good cause to commemorate the manifold mercies
of God vouchsafed to this united kingdom of Great Britain,
believe it our duty to make our humble acknowledgments, first to the divine Majesty,
and next to the Queen, for the liberty we enjoy under her kind and favourable government,
with hearty desire and prayers to Almighty God (who hath hitherto disappointed
the mischievous and wicked designs of her enemies both foreign and domestic)
that he will so effectually replenish the Queen`'s heart,
together with those of her great council, with his divine wisdom, that righteousness,
justice and moderation, which are the ornaments of the Queen`'s reign,
and which exalt a nation, may be increased and promoted.

And we take this opportunity to give the Queen the renewed assurance
of our hearty affection to the present established government,
stations, according to our peaceable principles, by the grace of God,
approve ourselves in all fidelity the Queen`'s faithful and obedient subjects,
and as such conclude with fervent prayer to the Lord of Hosts, that after a prosperous,
safe and long reign in this life, thou, O Queen,
mayst be blessed with an everlasting crown of glory.

--

Seven friends were appointed to present this address, amongst whom was George Whitehead,
who upon presenting it, said, "`We heartily wish the Queen health and happiness:
We are come to present an address from our yearly meeting,
which we could have desired might have been more early and more seasonably timed,
but could not, because our said meeting was but the last week,
and therefore now hope the Queen will favourably
accept our address.`" When he delivered it,
the Queen requested him to read it, which he did, and the Queen answered,
"`I thank you very kindly for your address, and I assure you of my protection;
you may depend upon it.`" To this George Whitehead replied,

[quote]
____
We thankfully acknowledge that God,
by his power and special providence hath preserved and defended
the Queen against the evil designs of her enemies,
having made the Queen an eminent instrument for the
good of this nation and realm of Great Britain,
in maintaining the toleration,
the liberty we enjoy in respect to our consciences against persecution:
which liberty being grounded upon this reason in the late King`'s reign,
for the uniting the Protestant subjects in interest and affection,
the union of Great Britain, now settled, tends to the strength and safety thereof;
for in union is the strength and stability of a nation or kingdom;
and without union no nation or people can be safe, but are weak and unstable.
The succession of the crown being settled and established in the protestant line,
must needs be very acceptable to all true protestant subjects.

And now, O Queen! that the Lord may preserve and defend thee for the future,
the remainder of thy days,
and support thee under all thy great care and concern for the safety
and good of this nation and kingdom of Great Britain,
and that the Lord may bless and preserve thee to the end, is our sincere desire.
____

To this the Queen returned, "`I thank you for your speech, and for your address;
and ye may be assured I will take care to protect you.`" George Whitehead replied,
"`the Lord bless and prosper the Queen in all her good intentions;`"
and then these friends withdrew.

In this year died Thomas Camm of Westmoreland, son of John Camm,
whose life and character is the first recorded in this hisstory.
Both his parents being members of the society, conspicuous for their integrity and piety,
he had the advantage of a religious education in
the principles of the people called Quakers,
their pious counsel and circumspect example made a deep impression on his tender mind;
whereby, from his early youth, he was blessed with religious sentiments,
and delighted in the company of the most religious persons.
And as he grew up, his understanding was illuminated, to perceive,
that besides an education in the most perfect form of religion,
the experience of inward sanctification by that word, which is quick and powerful,
was necessary;
and being humbled into frequent inward retirement to feel after this quickening word,
he was favoured with the attainment of what he saw he stood in need of,
and by the virtue of this refining power being purified,
he received a gift in the ministry, in which his doctrine was sound,
and his delivery agreeable, not in the enticing words of man`'s wisdom,
but in the demonstration of divine power,
reaching the witness of God in the hearts of his hearers,
whereby he was made instrumental to convert many to,
and establish many in the way to righteousness and peace.

He spent much of his time in travelling in various parts of the nation,
in the exercise of his ministry, for the edification of his friends,
while he was left at liberty.
But he bore his share of the sufferings of this age both in person and property,
whereby his travels were repeatedly interrupted.
In the year 1674 he was sued by John Ormrod, priest of Burton,
for small tithes and oblations,
and by a writ _de excommunicato capiendo_ he was cast into prison at Kendal,
where he was detained in a close confinement for a great part of three years.
He was afterwards imprisoned for six years in the county jail at Appleby (as before
I noted in the account of his wife`'s decease) on what account I am not informed,
but most probably for the like demand of tithes,
so that he was imprisoned near nine years in all.

On the 13th of October 1678, after the commencement of the last conventicle act,
Edward Wilson, a justice of peace,
sent several informers to a meeting held in the house of Edward Cragg of Ackonthwaite,
and upon their evidence, convicted several persons without examination,
or summoning them before him, and issued his warrants of distress,
whereby there were taken from Thomas Camm in particular, for preaching at a meeting,
nine head of cattle and fifty-five sheep worth 31£. 10s. When the officers complained
to this rigorous justice that they could not sell some of the cattle,
he charged them to sell at any price, and fetch more till they had enough,
and ordered them to drive them from market to market,
to sell them cheap for the encouragement of buyers; threatening them,
that if they did not raise all their fines,
they should pay the rest out of their own pockets.
There were again, by warrant from the said Wilson,
two oxen taken from him worth 7£. upon an information of being at a meeting at Tarleton;
being with others fined on account of a preacher, who was said in the warrant to be fled,
and his habitation unknown: Whereas the preacher was so far from fleeing,
that he went to the justice`'s house, and left word there,
that his name was Thomas Dowcra, and that he dwelt at Swarthmore near Ulverstone,
in Lancashire, and that he was of ability to pay his own fine,
for which reason he desired it might not be imposed upon others.

All his sufferings, which were many, he bore with fortitude and firmness;
unshaken in his testimony for truth, he maintained it uniformly to the last;
far from being discouraged by suffering in a good cause,
it was his joy and crown of rejoicing,
that he was counted worthy not only to believe in the truth, but also to suffer for it.

He was not only eminent amongst his brethren for his service in the ministry,
but in the maintaining the discipline of the church,
for which he was remarkably well qualified,
being himself a shining example of righteousness in his own conversation,
richly replenished with divine wisdom, and adorned with meekness and humility,
his endeavours to promote an orderly conversation, consistent with their profession,
amongst his friends, were attended with the greater weight and effect;
whether exerted in the meekness of wisdom for the strengthening
and encouragement of the weak and well disposed;
or in a well tempered zeal against every appearance of evil;
especially against that spirit which endeavoured to lay
waste the testimony and religious care of friends,
and foment divisions in the church,
with which we have seen the county of his residence was particularly exercised.
Being a man of peace, he laboured to follow it with all men;
to promote it in the church and amongst all sorts of people.
Love and unity amongst brethren he rejoiced in,
and where anything appeared tending to a breach of it,
he used his utmost endeavours to put a stop thereto.
Benevolent and kindly affectionate to all men, he was beloved and esteemed by the good,
as far as his acquaintance extended.

When he was advanced in years,
and affected with infirmities in consequence of the hardships and
sufferings he had endured in the successive stages of his life,
his zeal for truth, and his love to his brethren,
and concern for the well-being of mankind in a general way,
engaged him in repeated religious labours and visits to his friends in various parts,
to their comfort and edification, to near the termination of his life.

His last journey in religious service was into Lancashire, the west of Yorkshire,
and his own county of Westmoreland, from which he returned on the 17th of the 11thmo,
1707, O.S. to his Son-in-law`'s, John Moor`'s at Eldworth;
and here he was immediately attacked by a return of a distemper
which had been before at times troublesome to him,
viz. the stone and gravel, which continuing to increase upon him,
and affect him with violent pain, so that he could take little food or sleep,
yet he bore it with much patience.
In the prospect of future happiness he was perfectly resigned to the divine will,
frequently expressing his acquiescence therein in these or similar terms,
"`I neither desire to live nor to die, but am well content,
however it shall please the Lord to order it.`" One day sitting alone,
his son John Moor came to bear him company, and asking him how he did?
he answered, "`I am weak in the body, but strong in the inner man, blessed be the Lord,
who hath been my strength and support hitherto,
expressing his humble thankfulness to the divine Being for
his multiplied and unspeakable mercies to him,
in the successive vicissitudes of his life.

About a week before he died, several of his grandchildren being in the room with him,
he said unto them, "`Now I think I must leave you.
If the Lord had seen meet to spare me a little longer,
I might have been of service to you in counsel and advice; but the Lord,
the great and wise counsellor, as you have your eye to him above all things,
will not be wanting in counsel to you; I love you entirely,
and the blessing of the Almighty rest upon you,
if it be his will.`" To John Moor and others present, "`Bear me record,
that I die in perfect unity with, the brethren; my love is as firm and true as ever,
in our Lord Jesus Christ, the author of our salvation.`"

To recount all the solid expressions which this good
man brought forth from the good treasure of his heart,
during a confinement of five or six weeks, might to some readers appear tedious:
The fore-cited expressions appear to bespeak a mind redeemed from the earth,
and looking forward with serenity to an habitation eternal in the Heavens,
for which he had been, through the course of a pretty long life,
careful to make preparation.

He departed this life at Eldworth aforesaid, in much peace and quietness,
the 13th day of the first month 1707-8, in the 67th year of his age.
His body was removed from thence to his late habitation at Camm`'s-gill,
and on the sixteenth from thence to friends burying-ground
at Preston-Patrick to be interred.
The great numbers and decent solemnity of friends of that and other adjacent counties,
and of the neighbourhood of other societies, under a general appearance of sorrow,
demonstrated the respect they bore to his character.
The corpse being interred, most of the attendants drew into the meetinghouse,
and had an edifying season together,
the divine presence eminently overshadowing the assembly,
to the affecting many hearts with reverent solemnity and serious considerations,
under the influence whereof,
divers lively testimonies were borne to the sufficiency
of that universal principle of light and grace,
of which the deceased had been a shining example.

In this year party animosities, which appear to have subsided for some time past,
broke out with remarkable violence.
Sacheverel, a violent high church-man,
inveighed against the dissenters in several harangues;
for two of which he was complained of to the house of commons,
who impeached him of high crimes and misdemeanours,
of which he was found guilty by the lords and silenced for three years;
the clergy and others of the same stamp, who were now become numerous,
patronized his cause as their own, with all the vehemence of a violent party spirit,
pointed their sermons and discourses with intemperate warmth against the dissenters,
and stimulated the populace to riot and outrage against them,
raising a popular cry that the church was in danger.
The Queen also being influenced to change her ministry and measures,
he was used as a tool to turn the passions of the vulgar in favour of the design;
and from the prevailing spirit at this time,
many of the dissenters were filled with apprehensions of
a design to repeal or at least to weaken the act of by some,
of toleration; but a new parliament being elected,
the Queen in her speech declared her resolution to maintain
the indulgence by law allowed to scrupulous consciences,
whereupon a committee of the People called Quakers
waited upon her with the following address;

[.embedded-content-document.address]
--

[.letter-heading]
To Queen Anne of Great Britain, etc.

[.blurb]
=== The humble and thankful Address of the Queen`'s protestant subjects, the people called Quakers, in and about the city of London, on behalf of themselves and the rest of their persuasion.

When we consider the Queen`'s royal regard to protect our religious liberty,
and the fresh assurance from the throne of her christian resolution
to maintain the indulgence by law allowed to scrupulous consciences,
and her tender care that the same may be transmitted to
posterity in the protestant succession in the house of Hanover,
we find ourselves concerned gratefully to acknowledge her goodness there in,
and the ready concurrence of her great council therewith.

Taking this occasion to assure the Queen of our duty and
affection and peaceable behaviour under her government,
as is our principle, and hath always been our practice.

And we heartily desire our fellow-subjects may lay aside all animosities,
and in a spirit of love and meekness,
endeavour to outdo each other in virtue and universal charity.

That it may graciously please almighty God to defend and bless thee,
O Queen! and guide thee by his counsel in a long and prosperous reign here,
and afterwards receive thee to glory, is the hearty prayer of thy faithful subjects.

--

To this Address the Queen answered,

[quote]
____
I thank ye for your address, and ye may depend upon my protection.
____

This year died John Banks, who was born of honest parents,
in the parish of Issel in Cumberland.
In early youth he was convinced of the principle of the divine light in the heart,
not by the preaching of men, but the inward conviction of his own mind,
and brought to an acquaintance therewith before he
had any acquaintance amongst the people called Quakers,
or heard their doctrine preached; but by a motion in his own mind,
he was incited to go to a meeting of the said people,
in consequence whereof he went to their meeting at Pardshaw,
where very few words were spoken; but a paper was read therein,
which had a considerable effect upon him, being pertinently applicable to his condition.
And through diligent attention to the ingrafted word, which is able to save the soul,
he experienced a growth in sanctification,
and was prepared for the reception of the gifts of the spirit:
in the year 1663 he appeared in the ministry and visited
some of the meetings in the neighbouring counties;
and in the year 1668, being more deeply experienced in the work of religion,
he was made willing to forsake all,
to perform his duty in the service of his maker and the cause of truth,
travelling into the southern and western counties,
and in a great degree devoted the future time of his life to the like beneficial purpose.
He laboured zealously in the promulgation of the gospel,
both in several parts of England, in Scotland, and Ireland several times over,
to the edification of the society of his friends and the convincement of others,
who remained witnesses to the efficacy of his ministry and as seals thereof.

In the year 1679,
he felt it his duty to go forth under a pressing
concern of mind into those counties and places,
where the separation begun by Wilkinson^
footnote:[It may be proper so observe,
there were at this time two persons of the name of John Wilkinson in the society,
or under the name of Quakers, viz. John Wilkinson of Cumberland,
who had been a priest of Brigham, and had two parishes more;
he was convinced by the ministry of G. Fox in 1657,
became an approved minister among the people called Quakers,
and many were convinced by him: He travelled into the South and West of England,
with J. Banks for his companion in 1668;
and continued a faithful man till the day of his death in 1675.
The other John Wilkinson of Westmoreland,
principally known in our history fur his opposition and separation.]
and J. Story had got ground,
to bear his testimony against that spirit of separation
which had its life in contention and discord.
He first went with Christopher Story for his companion, to the yearly meeting in London,
where (he writes) "`the love and life of pure religion was in dominion,
so that the opposing spirit was never once able to lift up its head;
an agreeable harmony prevailed throughout,
the power of God being over all.`" From London they turned
westward through Berkshire and Wiltshire to Bristol;
here he passed along under a deep travail and anxiety of soul by day and by night,
that the deceitfulness and error of the spirit of separation,
which sought to divide and make parties in the society, might be made manifest,
and that the innocent might be preserved from being entangled or hurt by it,
insomuch that he could take little refreshment of food or sleep;
notwithstanding which he was so supported with the spiritual
strength and the authority of the gospel in his testimony,
that although some of these separatists were highly provoked,
railed at him behind his back, threatened to give him public opposition,
and for that purpose followed him from meeting to meeting;
yet the power which supported him, and evidently attended his testimony,
chained them down, so that when the time came,
they had no ability to put their threats in execution.
He passed through those parts,
labouring in the ministry to the comfort and edification of the church,
and the increase of peace in his own mind.

He had a share also in the sufferings attendant on
his profession in this persecuting age,
both in imprisonment and the loss of goods.
In the year 1662, George Fletcher, a justice of peace,
came to a meeting at Howhill in Sowerby parish, rustling in a hostile manner,
with a retinue armed with swords and pistols, and finding John Banks on his knees,
the justice struck him over the head, and when he continued praying,
ordered him to be pulled down backward,
and caused him and others to be dragged down the hill, in a violent and cruel manner,
and afterwards sent them to Carlisle jail.
At the ensuing sessions some were fined 10£. and the rest 5£. each,
and distraints made to considerably more than the value.
In the year 1683 several informers came to the meeting at Pardshaw-Cragg,
and found Peter Fearon preaching: They applied to justice Fletcher,
who fined him 20£. and ordered it to be levied on
himself and several others who were present,
among whom John Banks was one:
And although Peter desired the whole might be charged on himself,
he being of sufficient ability, the justice persisted in his design,
and issued his warrants for distraint,
whereby goods to the amount of 7£. 10s. were taken from John Banks.
When these goods were exposed to sale, and no purchasers could be found,
this justice ordered his own servants to purchase some of them,
which they did at a very low price;
and the officers to supply the defect made further seizures,
whereby the value of the distraints at last amounted to 35£.

This justice Fletcher seems to have entertained a
particular enmity against this reputable man,
impelling him to every measure in his power,
to distress him and his family in their outward circumstances:
For at the very time he granted the abovesaid warrant
for distraining his goods for his arbitrary fine,
being an impropriator, he was carrying on a severe prosecution against him for tithes.
John Banks being subpoenaed to answer his bill, because, from his conscientious scruple,
he could not put in his answer upon oath, was run to a contempt,
upon which he was arrested at the very same time,
that the officers and informers with their assistants, to the number of twelve,
came to his house to execute Fletcher`'s warrant of distress.

He was committed to prison in Carlisle jail,
where he was detained six years and nine months,
during which time he received much rude treatment
and abuse from the jailer and his deputy by his order;
being instigated thereto, first by his own vexation,
because John and his friends and fellow-prisoners
hesitated to gratify his avaricious disposition,
in taking chambers from him at his price; and secondly,
by the priests and magistrates of the city,
who were disturbed and exasperated at John Banks,
because the friends in prison keeping up their meetings,
particularly on the first day of the week,
he frequently felt a concern to preach among them, and standing near the casement,
which opened to the street,
his testimony could be heard by the citizens as they came from their worship.
This exasperated both the priests (of which there were a
considerable number in that place) and the magistrates,
as the people in palling would frequently stand to hear him:
In order to put a stop thereto, the mayor of the city,
accompanied by some of the aldermen and others,
came into their meeting in the prison one first day while John was preaching,
and in great passion commanded him to be silent, shaking his wand at him,
and threatening to gag him.
But neither his passion nor his menaces could effect his purpose; John intimating to him,
that he conceived he had his commission from a superior power;
and that as mayor he had no authority to molest him and his companions in confinement;
they were the king`'s prisoners, and in safe custody.
With some further menaces the mayor and his company departed,
and gave them no further molestation in person.

But there is reason to presume they gave a charge to the jailer and his turnkey,
to endeavour to prevent him from preaching, even by violence.
The turnkey generally watched their meetings, and as soon as he heard John Banks`'s voice,
would drag him by force out of the room to some other place,
and confine him there till after the meeting was ended.
The turnkey at other times would endeavour to prevent his speaking,
by putting his hat over his face; hooting to drown his voice;
clapping his hands on his mouth, and such like rough treatment.
Once finding him on his knees at prayer, being urged by the jailer, who was also present,
this turnkey pulled him off his knees, threw him down,
and endeavoured to drag him by force along the ground, which not being able to do,
the jailer came to his assistance, and then they jointly pulled him away,
and shut him up in a noisome smokey room over the brew-house,
in which he was locked up several times;
at one time three days and two nights without a bed of any kind to lie down upon.

The jailer finding these harsh measures ineffectual
to compass their design of silencing him,
had recourse to remonstrance, representing to John that the priests,
mayor and aldermen of the city were greatly displeased,
and threatened to fine him for suffering him to preach,
and his friends to hold conventicles in the jail,
proposing their removal to another house from the street,
or at least to the further end of the room, where he might not be heard.
In reply to this, John Banks,
who conceived his ministry not restricted to his friends and fellow-prisoners;
but that it was to be also exercised to call the
inhabitants to repentance as opportunity offered,
signified, that as his prisoner he should be subject to him,
let him put him where he would;
but as to matters of religious duty he could own no subjection to him or them;
but to the clear discovery of the light in his own mind only.
The jailer and his deputy therefore returned to their former practice of haling,
confining and personal abuse, whereby his body was much bruised and his health impaired.

The jailer, although he pretended at times to palliate his severity,
under the fear of the resentment of the magistrates and priests,
could not forbear at other times to give vent to his own private
resentments on the subject that touched him more closely,
because they did not take their diet and lodgings from him at extravagant rates,
abusing them with opprobrious language, calling them rogues, rascals and cheating knaves,
menacing them with the smokey loft and common jail,
and charging the turnkey to let them out on no occasion, not even to buy victuals,
which charge was pretty strictly observed, insomuch,
that for some time they were hard put to it to provide necessaries for themselves.

The jailer not fully gratified by this severity, or not finding it answer his purpose,
in a few weeks proceeded to put his menace in execution,
by thrusting John Banks and another friend into the
common jail amongst the felons and poor debtors,
at a time when it was so crowded, that there was no convenient room to sit or lie down,
and J. Banks was in an ill state of health, having been indisposed for some time before;
upon which account one of his fellow-prisoners made this remonstrance to the jailer,
"`If this friend shall die through thy cruelty and hard usage,
his blood will be required at thy hands:`" The jailer,
with all the unfeelingness of such officers, replied,
he did not care if J. Banks never stood upon his feet again,
he would put him into the common jail; which he did,
where J. Banks and his companion were obliged to sit all night near the sink,
the common receptacle of the filth and excrements of the prisoners.
And when they got some straw to lie on, they had only the wet ground to lay it on,
close by the noisome sink.
He was confined here sixteen days and nights,
during which time his wife (with other friends) coming
twenty miles to visit him in prison,
she requested of the jailer,
that he would permit her husband to come to her in
some place more convenient than the common jail;
but as divested of all tenderness, he refused her, and sent her word,
"`If she wanted to see him, she might in the common jail,
but nowhere else.`" She continued with him there one night and part of the next day,
a sympathizing witness of the hardships he underwent.

When the jailer found he could not by any contrivance effect his purpose,
to procure chamber-rent from him and his friends,
growing uneasy in his mind from a troubled conscience,
he brought John back to his fellow-prisoners,
after a confinement of two weeks and upwards in the dark dungeon.

And when he could neither by these harsh,
measures make the gain he wanted by these prisoners,
nor hinder John Banks from preaching, he, being much threatened by the priests,
removed himself and them to another house,
and placed them in rooms backward from the street,
where they held their meetings peaceably,
without much further molestation from the jailer or any other;
who after persecuting them as above described for about six months,
seems to have relented,
and in process of time to have indulged them with as much liberty as they could expect.
John Banks was detained in prison till he was released
by King William`'s act of grace in 1690,
seven years wanting three months from his first commitment.

Soon after his release he took another journey into the west,
to pay a religious visit to his friends in that quarter, and thence to London,
where his service was very acceptable and profitable to many,
and the meetings generally very large,
all along his friends were respectful and rejoiced
to see him again after his long imprisonment.

A few months after his return from this journey, he met,
(according to his own expression) with the greatest trial that had ever befallen him,
in the removal of his virtuous and well-beloved wife,
with whom he had lived in great comfort and near affection twenty-seven years;
and whom he characterizes as a meet help to him, a sympathizer in his exercises;
a woman industrious and careful in ordering their outward affairs
and in the religious education of their children in his absence:
That she was well-beloved amongst her friends and neighbours:
bore her sickness with patience; and ended her days in peace the 2nd day of 10thmo, 1691.

In the year 1696 he married his second wife at Glastonbury in Somersetshire,
and fixed his residence in that county, first at Mear, and afterwards at Street.
He continued his travels for the promoting a religious concern amongst his brethren,
even in his advanced years, when affected with great bodily infirmity.
About two months before his decease he paid a religious
visit to several meetings of his friends,
both those for religious worship and those for discipline, in the care of the poor,
widows and orphans, being equally well qualified for service in both;
a man endued with excellent talents for promoting good order,
pursuing those things that were just, pure, lovely and of good report.
In this last journey at Somerton, in a large meeting,
he was raised in his testimony to the admiration of those;
who were acquainted with the infirm state of his health.
He continued a considerable length of time in his
testimony against outside appearances of religion,
destitute of the substance, with perspicuity and just distinction in his doctrine,
demonstrating the strength of his memory and mental faculties,
and the soundness of his judgment in spiritual matters,
being wonderfully supported by divine assistance to preach the word to the consolation,
refreshment and edification of the meeting.

His zeal for the promotion of truth and righteousness removed from
his thoughts the present consideration of his bodily infirmity.
His natural strength was, by his exertion, so far weakened,
that it was a task sufficient for two men to lead him from the meeting to his lodging:
but he was very cheerful under the feeling of an increase of peace in his bosom,
for spending his remaining strength in the best cause,
and signified his inward satisfaction in that day`'s service.
He proceeded in his visit to Puddimore, and from thence to Yeovil,
wherein a large meeting of friends he was afresh
divinely influenced in his public service,
with a lively zeal and quick discerning of the states of several present,
to which he addressed pertinent doctrine; and from thence he returned home,
where he was soon seized with that distemper of which he died.
During the time of confinement he frequently said, "`Though my pain be great,
my soul doth magnify the Lord for his goodness to me.`"
On the 2nd of 7th month several friends being present, after some time spent in silence,
he exhorted them to a diligent attendance of meetings for worship, both on first days,
and other days of the week, set apart for that purpose;
also their quarterly and monthly meetings for discipline,
expressing his great love to friends of Glastonbury and Street,
to whom he had been a good example in the diligent attendance of meetings,
which he now recommended, adding, "`Although I am weak in body,
and know not whether I may live much longer,
yet I am strong in the Lord and the power of his might,
and have nothing to do but to die.`" To a young man
that came with some other friends to see him he said,
"`Art thou the young man that lives at Somerton,
lately convinced of the blessed truth?`" He answered,
"`Yes.`" "`The Lord be with thee,`" continued John Banks,
"`and I desire thee in the love of God to give up in obedience
to the working of the spirit of God in thy heart,
and then he will do great things for thee; and do not thou stumble at the cross,
for the more thou look at it, and puttest it off,
the harder will it be to thee to take it up.`"

Much more good advice, during his sickness, he imparted to those who came to see him,
with a favour of life and power which greatly affected those to whom it was addressed.
His last expressions on record were, "`It is well with me,
I have nothing to do but to die, and I shall end in the truth as I began.`"

William Crouch, according to his best calculation,
was born on the 5th day of the 2nd month called April 1628,
in a small village called Penton by Weyhill, near Andover in Hampshire.
His father was a substantial yeo-man, of good repute in the country,
and well beloved in his neighbourhood.
His mother was a religious woman, and one of the people in that day called Puritans.
She was a watchful guardian over her children,
to preserve them from evil either in word or action;
and would often call them together to pray with them, and for them by day or by night,
as she found seasonable opportunities,
wherein she hath left a good example to others of her sex who are mothers of children.

His father was taken off in the prime of life, leaving his children young;
and the civil war arising soon after unsettled the family,
and deprived him of his share of his father`'s property,
and also of the advantage of learning, which otherwise he might have had.
He removed to London in 1646, and bound himself apprentice there.

His religious education was not lost upon him,
for in all the changes of situation he was preserved in a good degree of innocence
and sobriety from many temptations and evils incident to youth.
Careful of his company, he shunned the converse of such as indulged in excess,
rudeness and dissipation,
and chose for his associates such as were religiously
disposed and sober in their conduct.

He diligently attended the ministry of such public preachers
as were in the greatest reputation for wisdom and piety;
he often wrote their sermons, and was sometimes much affected,
and on his return home would spend his time in retirement and prayer.
Yet not knowing the Lord was so near him as he was,
he witnessed little growth of grace in his heart, or power over his affections and lusts;
but was sometimes overcome by temptation, and allured to vanity and folly,
which afterwards proved a burden and uneasiness to his soul;
yet in great mercy he was followed closely with the reproofs of instruction,
which he found by experience to be the way to life.

In the year 1656 he first began to frequent the meetings of the people called Quakers,
being convinced in his judgment of the truth of their principles;
and as he gave need to that grace and truth which they testified of,
he was not only convinced speculatively of the truth of their testimony,
but experimentally convinced by the operation of this light and grace in himself,
that God, by his good spirit, was nigh at hand,
a discoverer of the thoughts and intents of the heart,
and a reprover in secret for every evil way, word and thought,
and by his light in his conscience a discoverer also of the way to escape temptation.
Through the illumination of this divine light he saw sin to be exceeding sinful,
and that godly sorrow was produced in him,
which brings repentance not to be repented of.

A friend that well knew him testifies, His treasure was in heaven,
and as for the treasure of this world he set no value upon it,
further than to be his servant for necessary uses,
and to extend in charity to the indigent.
His charity was amply and variously diffused, and he was always disposed,
with a ready mind, to assist such as were in affliction or distress of any sort,
where either his advice or purse was wanting.

He looked upon himself not so much a proprietor of the temporal
treasure Divine Providence had blessed him with,
as a steward, and accountable to the Lord of the universe for his stewardship,
and therefore his care and endeavour was to be found faithful
in the discharge of the trust committed to him.

That love of money, which the apostle declares to be the root of all evil,
being the foundation of uncharitableness, he looked upon with such aversion,
that he published a treatise under the title of _The Enormous Sin of Covetousness Detected,_
informing the reader in the preface,
that it was not ambition to appear in print that incited him to that undertaking,
but a sincere and just abhorrence of that crying sin.

And as he was exemplary in showing mercy to the poor,
and in helping and relieving the weak and afflicted,
so he was equally conspicuous for his punctuality and uprightness in commerce,
doing justice to all, fulfilling his contracts, and paying his just debts in due time,
and doing to all men as he would wish others to do to him.
He was clearly shown what he should do, and acted in obedience to the divine discovery,
to do justly, love mercy, and walk humbly before God.

The year before his death he wrote to his children a concise
but comprehensive paper or epistle of christian counsel,
which might remain as a testimony of his paternal regard
and affectionate concern for them when he should be no more,
viz.

[.embedded-content-document.epistle]
--

[.signed-section-context-open]
The 7th 2mo. 1709.

You, my children all, I charge you love God above all; love one another,
live in peace one with another; avoid all appearances of discord;
remember you are brethren;
see that you fall not out by the way in your travel and pilgrimage.
Seek not a rest here,
but pass on to that city of rest which God hath prepared for his people.
Be exemplary in your lives and conversations; keep truth and it will keep you,
and give you an inheritance with the saints in light,
Be watchful over one another for good,
and as much as in you lies live peaceably with all men.
And the God of peace bless you and prosper you, and make you a comfort to yourselves,
and one to another, which is the earnest prayer and cry of my soul to God.

[.signed-section-closing]
Your loving father,

[.signed-section-signature]
William Crouch.

--

He, like most of the rest of his brethren,
was repeatedly a sufferer both in his person and property.
He was once cited to appear at Christ Church (so called)
to answer the presentments of the church wardens,
and for not appearing he understood he was excommunicated,
but they proceeded against him no further.

But not long after, in the year 1661, he was chosen scavenger of Broad-street ward,
and for declining to take the oath of office was committed to the Poultry compter;
and for refusing to pay fees and what they call garnish money,
he was shut up in a hole among the common poor prisoners, where he had no lodging,
and but very little room to walk, when the prisoners were locked up at night.
Some time after he obtained his discharge by an application to John Frederick,
mayor of the city.

In about three months after he was arrested at the
suit of the parish called St. Bennet Fink,
as he was informed, for tithes or wages for the priest Samuel Clark,
and was again committed to the Poultry compter,
where he was continued in confinement about one year and three quarters;
but through favour of the jailer he got liberty sometime
to go home to superintend his business.

In the year 1665, during the time of the plague, the persecution, as hath been observed,
did not cease,
but the jails in and about the city of London continued to be crowded with fresh prisoners,
infected as they were,
and amongst others it fell to the lot of this friend to be imprisoned.
He was at Peel meeting on the third day of the week,
where about the number of sixteen were assembled; for,
what through the number confined by the sickness and in prison,
the meetings were frequently small; for these reasons only,
and no declension in the zeal of friends,
who continued to attend them diligently through all the attendant circumstances of discouragement.
At this time, while a friend was on his knees at prayer,
a company of trained bands came in,
haled the friend from his posture in prayer took the whole
body assembled to the guard-house near Whitehall,
where they were kept all night; next morning, refusing to pay 40s. each,
arbitrarily demanded of them, as the price of their liberty,
they were committed by the Duke of Albemarle to the Gate-house, Westminster,
for three months, by the following warrant:

[.embedded-content-document.legal]
--

You are on sight hereof to take into your custody Solomon Eccles, Robert Towerland,
Thomas Portland, John Bolsover, Humble Fletcher, William Crouch,
John Pierce and Christopher Cooke, who are guilty of being at an unlawful meeting,
and refusing to pay their fines.
Given under my hand this 23rd day of August 1665.

[.signed-section-signature]
Albemarle.

[.signed-section-context-close]
To the keeper of the Gate-house or his deputy.

[.postscript]
====

The officer of the guards is to send a sergeant and four files with them.

====

--

Thus were reputable citizens sent to prison by military authority,
under a military guard, like vile criminals, and confined in an infected prison,
in which, as they were informed, the prisoners were dying of the contagion,
four or five in a night.
One of these friends, Robert Towerland, was taken off; the rest,
through the favour of Divine Providence, escaped.

These appear to have been the last friends imprisoned on
the act for banishment in the city of London.

It hath been before remarked,
that although sufferings on other accounts sometimes subsided,
yet those for tithes and priest`'s wages were very rarely, if ever, intermittent.
This friend had his dwelling-house burned down in the general conflagration,
and during the rebuilding, being as an inmate, he was not liable to these demands.
But after the city was rebuilt, he seated himself in Grace Church-street,
where he was soon called upon for three quarters of a year`'s wages for John Cliff,
called rector of St. Bennet, Grace Church, London,
and for a demand of 1£. 19s. had three pieces of white serge taken from him worth
3£. 10s. Some time after he received 15s. 5d. sealed up in a paper,
with an account,
debiting him with the unreasonable sum of 15s. 7d. for charges of distraining.
When he opened the paper, and found what it contained,
he returned the account and money to the priest, saying in a letter to him,
"`I receive not aught from thee, nor do I want anything which thou sellest.
I never made bargain with thee for aught, nor never consented to pay thee anything,
how then canst thou deem me thy debtor.`"

After the last conventicle-act came in force W. Crouch was exposed
to the depredations of the informers and convicting justices,
as appears by the following warrant:

[.embedded-content-document.legal]
--

[.blurb]
=== To all constables, headboroughs, church-wardens, tithing-men, overseers of the poor, bailiffs, and all other his Majesty`'s officers within the said city whatsoever:

Whereas by the oaths of two credible witnesses before me, Sir Jonathan Raymond,
one of his Majesty`'s justices of the Peace for the city aforesaid,
there was a conventicle or unlawful assembly, held the 13th day of this instant June,
in a certain meeting in Whitehart-court by Grace Church-street, in the aforesaid city,
in the forenoon, wherein were a company of persons, all above the age of sixteen years,
and subjects of this realm,
to the number of above sixteen more than those of the family or household,
contrary to the act of parliament in that case made and provided,
amongst whom was William Crouch, upholsterer,
in Grace Church- street in the aforesaid city.
In which conventicle or unlawful assembly, to these deponents was a person unknown,
who did take upon him to teach and preach under colour or pretence of exercise of religion,
in other manner and form than according to the liturgy
and practice of the church of England,
whereby the penalty of 20£. was forfeited by the preacher or teacher as aforesaid;
who being unknown as aforesaid,
the penalty by him forfeited ought of consequence
to be levied on any one person for any one offence,
for which cause I have imposed the fine of ten pounds for his own offence,
and part of the preacher`'s offence.

These are therefore in his Majesty`'s name, and by virtue of the said act,
to command you or some of you to levy the said sum of 10£. by way
of distress and sale of the said offender`'s goods above-mentioned;
and if you are refused entrance into the house or
houses in possession of the said William Crouch,
after you have declared your business in his Majesty`'s name,
you are hereby required to break open all and every the doors, barricades,
etc. belonging to any house or houses as aforesaid,
and to enter and levy the full contents of what you can find towards
all and every the warrants that you shall be charged with,
during the time you shall be in possession of such
premises in pursuance of the said statute,
and that you return the same to me, to be distributed according to the said act;
and for so doing this shall be your warrant.
Given under my hand and seal this 23rd day of June, _Anno Regni Caroli fecundi_ 35. _Annoq.
Domini_ 1683.

--

Another warrant of the like tenour, bearing date the 21st of April 1684,
was issued against him by Thomas Jenner, Recorder of London,
to levy ten pounds off his goods by way of distress for the like cause,
upon conviction execution issued, without hearing the party informed against.
The law we have seen allowed an appeal, but such was the management of many justices,
and such the temper of the time, that little right could be procured by appealing.

Jenner in particular was a notorious encourager of the informers.
In his hands the distress or amount was deposited, and the money upon appeals;
and being also the sole judge upon these appeals, upon trial of illegal convictions,
he manifested himself a party against the appellant,
and instead of sitting to do right and justice, as he ought by his duty and his oath,
he would employ every effort of chicanery to baffle the appeal.
In this instance, the informers having sworn to a wrong day,
the party aggrieved deposited the money charged upon him, and entered his appeal.
When it came to a trial with others of the like nature, the witnesses being examined,
and the jury gone forth to agree upon their verdict, Jenner also left the bench,
and in some small time returned.
The jury coming in with their verdicts, this appellant found they had dropped his cause,
which was then called over again, in order to a new trial,
upon which his counsel advised him to withdraw his appeal, for, said he,
they are resolved to carry it; so he suffered the loss of the deposit, and all charges.

Upon this transaction the sufferer makes this observation,
"`I have been the more particular in this relation of fact,
that the reader may take notice of the combinations of wicked men,
who joined hand in hand to secure to themselves the gain of oppression;
and according to Isa. 59:13-15,
Conceiving and uttering from the heart words of falsehood: "`Judgment is turned backward,
and equity cannot enter: Justice standeth afar off, and truth is fallen in the streets;
and he that departeth from evil maketh himself a prey, and the Lord saw it,
and it displeased him that there was no judgment.`"

I own I have often been ready to admire how this persecuted body
of men ever struggled through all the hardships and losses,
in person and estate, they sustained for such a length of time,
under the hands of unreasonable men vested with arbitrary power,
that the whole of their substance particularly was not swallowed up by the spoilers:
And how can it be accounted for better than they themselves with thankfulness have done;
acknowledging the goodness of the Divine Being with them in all their sufferings,
and his blessing greatly prospering the labour of their hands in
their outward occupations and their commercial engagements;
favoured with his peace in reward for their patience and fidelity,
hardships were made easy to them;
and his providential hand attending their industry and frugality,
compensated all their losses, so that with many they were soon made up;
and it appears certain that great numbers were, notwithstanding all they lost,
blessed with a sufficiency of the things of this life to content for their own use,
and to spare abundantly for the help of others, of which number this worthy man was one;
while at the same time their spoilers reaped little advantage from their plunder;
it wasted away strangely, as if to them it were an accursed thing.
They lived, many of them, in infamy, and died in poverty and wretchedness.

As he advanced in years he became infirm,
being severely afflicted with fits of the stone for about two years before his death,
which he bore with much patience, meekly submitting to the divine will,
without murmuring or complaining in the least.

About nine months before his own departure,
and at a time when his distemper was sharp upon him,
he met with an additional severe affliction in the removal of his wife,
a woman of singular piety and virtue,
with whom he had lived fifty years and upwards in much comfort,
being united in the fear of their Creator, and sincere affection to each other.
The loss of a relation so well and so deservedly beloved, of whom he gave this testimony,
that she would deny herself to a very great degree to serve him,
beyond what he could ask or expect from her,
could not but make a deep impression upon him;
but such was his resignation to the will of his Heavenly Father,
that he possessed his soul in patience, acknowledging with Job, "`that the Lord gave,
and the Lord hath taken away, blessed be the name of the Lord.`"

And as the time of his own dissolution approached, being, through divine mercy,
well prepared for it, and patiently waiting for the accomplishment thereof,
he often admired the goodness of God to him,
in inclining his mind to seek after righteousness from his youth,
and in preserving him through the whole course of his life to old age.
He often retired in prayer; and when he saw his children in affliction for him,
he exhorted them to desire his life,
for he was through age and weakness incapable of
being serviceable according to his desire;
and that he had done his day`'s work in his day.

The day before he died, a friend who had paid him several visits in his sickness,
went to see him, and sitting sometime with him, was influenced to pray.
on his behalf, and they were greatly comforted together.
William expressed his great satisfaction in that visit,
and said he had nothing to do but to die,
and was waiting for the time when it should please
God to call him out of this miserable world,
and take him to his eternal rest.

The night following he took his solemn leave of his children, who were then present,
telling them, He now thought he had but little time,
and the time which he so greatly desired and waited for was near at hand,
in which he rejoiced, praying that his change might be made easy,
that so his patience might hold out to the end;
and his request was mercifully granted him.

Thus in a good old age he terminated a well spent life, at the age of eighty-two,
the 13th of the 11th month, 1710.

[quote.scripture, , Ps. 37:37]
____
Mark the perfect man, and behold the upright, for the end of that man is peace.
____
