== Chapter XVII.

[.chapter-synopsis]
* Bill against occasional Conformity
* Friends at Frederickstadt under Sufferings by War
* Address upon the Conclusion of Peace
* The Magistrates of Aberdeen make a By-law to disfranchise Quakers
* Order of Privy Council thereupon
* Act against the Growth of Schism
* Representation of the People called Quakers against it
* The Bill passed
* Rendered ineffectual by the Queen`'s Death

The temper of the people and of the new parliament seemed to present a favourable
opportunity again to introduce the bill against occasional conformity,
which after repeated in effectual attempts was passed this year, wherein it is enacted,
"`That if any person in office,
who by the laws are obliged to qualify themselves by taking the sacraments,
shall ever resort to a meeting of Dissenters during
the time of their continuing in office,
they shall forfeit twenty pounds for every such offence,
and be disqualified for any office for the future,
till they have made oath that they have entirely conformed to the church,
and have not been at any conventicle for the space of a whole year.`" Upon this act,
John Penry, a justice of peace of Aldborough in the county of Suffolk,
was prosecuted by one Wall, a bailiff of the place.
The case was this: the said justice going to the parish church, understood by the way,
that there would be no service there that day,
and hearing that there was a meeting of the people called Quakers he went to it.
Wall being informed thereof, and apprehending the justice had transgressed the law,
and expecting to make some gain of the information,
commenced a suit in the name of one that lived upon alms;
but when it came to be tried the man was disappointed.
Baron Lovel, the judge, expounded the meaning of the act,
that it did not affect those who accidentally went into a meeting of Dissenters,
but such as conformed to the church to qualify themselves
for an office without changing their religion.
But this was a different case,
as the priest of the parish gave a certificate that
the said justice was a good member of the church.
Upon the present apparent circumstances the prosecution
was dropped for fear of being condemned in costs,
if a verdict should be brought in.

An occurrence in this year evidenceth the universal sympathy and brotherly kindness
of the members of this society with and towards each other wherever situated,
and the calamitous distresses brought upon innocent
people by the irrational ambition of princes,
in spreading the desolation of war for the sole purpose
of gratifying their lust of power.

Some of the inhabitants of Frederickstadt in Holstein having
been convinced of the principles of the people called Quakers,
and continued in that community, had a pretty large meeting in that town.
The Swedes having broken into Holstein were closely followed by the Muscovites and Danes;
Frederickstadt was full of Russian soldiers quartered upon the inhabitants,
who being greatly distressed thereby, the meeting for sufferings in London,
feeling for their brethren here under their distressing trials,
had written to friends of Holland and Germany to visit them,
and inform the said meeting of their circumstances,
in order that the requisite relief might be administered,
and received a narrative of their sufferings in two letters from Jacob Hagen of Hamburgh,
and also another from friends of Frederickstadt, copies of which are here inserted,
as follow:

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Hamburgh, 24th of 12th month, 1712.

Here follows a short relation of my journey to Frederickstadt.

The Czar is there with his generals,
and about 4000 men are quartered upon the inhabitants of the place, from ten,
twenty to thirty men in a family, and one or two officers, and some less;
they quarter themselves as they please, use great insolence,
and are also a great burden to the inhabitants, hardly tolerable,
in the charge of maintaining them, with provisions, etc. which are very dear,
one pound of butter 10s. and 12s. to 14s. and hardly to be had,
twenty eggs 20s. to 24s. and no firing to be had for money,
which causeth great uneasiness;
the city so dirty that there is hardly any passing the streets without boats:
the horses are kept in the lower rooms of the house,
and above stairs it is full of people and their baggage.
Las first day the Czar acquainted our friends he was desirous to come to their meeting,
but they replied, the meeting-house was taken up with about twenty or thirty soldiers,
who had made it like a stable; we desired that it might be evacuated,
then we might keep our meeting, so he immediately gave orders for them to go out,
and he came in the afternoon with about six or seven of his princes and generals,
and sat with us still, and it seemed with much patience; Philip De Neer had a few words,
and he stayed with us about an hour, to the admiration of many.
So this is a short relation concerning Frederickstadt.

The country people are mostly ruined and destitute, houses and land destroyed,
horses and cattle taken away;
the miserable state is hardly to be written as it is in reality.
The war is likely to be continued longer than was expected
now the Swedes have entered the city of Toningen,
but the King of Denmark hath seized the whole dukedom besides.

--

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Hamburgh, 7th of 1st month, 1712.

The war in Holstein is yet continued,
to the great oppression of the inhabitants both in country and cities,
especially by the Muscovites, who are extremely cruel and turbulent;
and what adds thereto, is their being of different languages,
which makes their conversation very troublesome;
they use great exaction on the country people, many of whom have been so misused,
even some of my acquaintance,
that with wife and children they have left their habitations, having nothing left;
and the longer the Swedes continue in Toningen,
the worse it will be for the country and inhabitants.
They demand of Frederickstadt a contribution of 30,000 rix dollars,
now they are fallen to 20,000; but neither the first,
nor yet the last is possible to be complied with.
Prince Menzikoff hath allowed him for his table 100 per day; it is but a small place,
and the inhabitants have 3 or 4000 men quartered upon them,
so it yet seems total ruin must be the consequence, if no sudden alteration happens,
which is to be desired.
Most of the horses and cattle are ruined or driven away,
and it is impossible to describe the miserable state and sore visitation,
which is over those places.
As to friends in general, I mentioned in mine of the 24th past of my having been there;
they are still pretty well; some have more quartered upon them than others,
but now in this time of continuance every one will find his full share of the burden.
It was not unserviceable to them,
that it came in the Czar`'s mind to go to meeting as he did,
for since that time the meeting-house is kept free, which before was full of Muscovites;
and the Czar, as well as some of his officers, have received of friends books, that is,
Robert Barclay`'s Catechism and another treatise,
so that some begin now to inquire after the Apology,
which I have this day sent for from Holland.
Friends, as well as other inhabitants, have their full freedom,
and the Muscovites make no difference if they get their bellies full,
where they are quartered.
And as concerning your ardour in being helpful and assisting to friends,
I shall endeavour the same further, as I have already done,
in consideration of the great need there was and is,
and shall desire my brother to inform me, wherein I can be most serviceable to them,
and advise you what passeth,
so conclude with my dear love and salutation to you and friends in general.

[.signed-section-closing]
I remain,

[.signed-section-signature]
Jacob Hagen.

--

[.embedded-content-document.letter]
--

[.blurb]
=== A Letter from Friends at Frederickstadt.

[.letter-heading]
To the Friends, Fathers and Elders at London.

[.salutation]
Dear Friends,

We received your letter dated 26th of 12th month, English style,
which was read in our public meeting the 26th, our style,
and we are rejoiced to find your continued love and care for the honour of God,
and our welfare in the Lord,
in this time of deep exercise over this poor country and to us, which yet continueth,
for few people account any thing they have their own,
being dispossessed of house and land,
many houses and dwellings in the country being laid in ruins,
and the country-man is forced to part with his horses and cattle,
and the land unplowed in many places.. By the great number of soldiers that are here
(according to human prospects) there is like to follow nothing but utter ruin and poverty,
except the Lord by his omnipotence make way for us,
whose hand is not shortened nor power bounded.
As to us the Lord hath been very gracious unto this very day,
giving us a heart of resignation, and our daily bread he hath not withdrawn;
also rendering unto us his heavenly mercies daily, blessed be his holy name.
In what manner the Lord pleased to work for the delivering of our
meeting-house from the soldiers who had possessed the same,
we hope, you have had account before this time,
viz. that he inclined the heart of the great Czar to come to our meeting in person,
who immediately ordered the meeting-house to be evacuated by the soldiers,
which was done accordingly, and we had a good comfortable meeting with him,
and several of his princes and great men of his retinue,
whereof an account is given to the friends of Holland;
and our friend Jacob Hagen was here at the same time an eye-witness with us,
and we enjoy our meeting peaceably to this day,
and friends continue agreeably to meet together therein
as much as this time of exercise will suffer us.
We dearly salute you in a feeling sense of that brotherly
union in the everlasting truth of our God,
according to our measures; remember us in your prayers to God,
and it will be very acceptable to receive another letter from you.
We remain your tender friends and brethren,

[.signed-section-signature]
Philip Deneer.

[.signed-section-signature]
Jeronimus Hagen.

[.signed-section-signature]
Razant Cloisum.

[.signed-section-signature]
Jan Van Kemp.

[.signed-section-signature]
Michael Wittenberg, etc.

[.signed-section-context-close]
Frederickstadt, 11th of 4th month, 1713, new style.

--

The war which had been carried on by England,
in conjunction with the Emperor and the Dutch against France,
ever since the beginning of the Queen`'s reign, was terminated this year.
On the 13th of 3rd month, O. S. commonly called May, a treaty of peace between England,
France and Holland, was signed at Utrecht.
The parliament being convened, the Queen in her speech informed them,
that she had now concluded a peace,
had obtained a further security for the protestant succession,
and was in an entire union with the house of Hanover.
Addresses of congratulation being procured and sent
up from all or most parts of the nation,
the people called Quakers,
whose principles led them on all occasions to rejoice
and approve the establishment of peace,
on the present occasion presented the following address to the Queen:

[.embedded-content-document.address]
--

[.letter-heading]
To Anne, Queen of Great Britain, etc.

[.blurb]
=== The humble address of her Protestant Dissenting subjects, called Quakers, met at our annual meeting in London, the 3rd day of the 4th month, called June, 1713.

[.salutation]
May it please the Queen,

We having been sorrowfully affected at the calamity which war brought on Europe,
cannot but express our satisfaction and gladness for the Queen`'s great
care and christian concern for establishing so long desired a peace.
We are also under a dutiful sense of the Queen`'s gracious government
and compassion manifested towards tender consciences at home,
as well as her Christian interposition in favour of persecuted Protestants abroad.

And farther crave leave to assure the Queen, that we shall, as in duty bound,
approve ourselves in all humility and faithfulness the Queen`'s obedient subjects;
and though but a small part of those that enjoy, under thy mild government,
protection in religious and civil liberty,
we cannot but earnestly pray for and desire the quiet and safety of our country,
which evidently appears to be the Queen`'s care to establish,
in having done so much for securing the Protestant interest and
maintaining perfect friendship with the House of Hanover.

That it may please Almighty God in his mercy and goodness
to assist with his wisdom the Queen in all her councils,
and give her long to enjoy the quiet fruit of lasting peace in this life,
and in that which is to come joy and peace everlasting, is our hearty and fervent prayer.

--

Thomas Ellwood of Hungerhill, near Mondesham in Buckinghamshire,
in the course of this year closed a life,
which had been very much devoted to the attainment of religious experience,
and also to the service of religious society,
both in the county of his residence and in the community at large.
He was born at Crowell near Thame in Oxfordshire in the year 1639.
His father, Walter Ellwood, was originally possessed of a competent real estate,
and an equivalent personal property, which he inherited in right of his mother.

Favouring the parliamentary cause, though not openly espousing it in arms,
he thought himself too insecure in the place of his then residence,
as the King`'s garrisons were in possession of that quarter;
he therefore removed with his family to London,
where the parliament had the predominance, as a place of safety;
Thomas was then about two years of age,
and continued in London till after the surrender of Oxford,
when the war being apparently at an end he returned to his estate at Crowell,
by which time the expense of living in London had well nigh
exhausted what money he was possessed of.

After the family`'s return to the country,
Thomas was sent with his elder brother to the free-school at Thame,
(a school at that time in reputation) where he made a speedy proficiency,
having a natural propensity to learning; and if he had been continued there,
and had been advanced to higher studies as his genius should expand,
he would in all probability have made an excellent scholar;
but upon the settlement of the republican government
his father accepted the office of a justice of peace,
and put himself into a manner of living comporting with the dignity of his office,
at the same time removing his elder son from school to Merton college in Oxford,
and entering him there in the highest and most chargeable rank of a fellow commoner,
he found himself obliged to retrench his expenses in some other cases.
One article of retrenchment was very unfavourable to Thomas`'s progress in literature;
for he was brought home to save the charge of maintaining him at school,
and no proper mode of prosecuting his studies provided for him:
He had made a considerable progress in Latin,
and was entered into the study of the Greek language;
but this curtailing of the expense of his education was nearly
a throwing away of the expense already incurred therein;
for being neglected in this business of importance at home,
and left too much to himself to employ himself in study or amusement,
in books or in pleasure at his option,
the propensity of youth carried him with avidity after the latter,
such as the place afforded, and his circumstances could reach,
which drew off his attention from his books, till they were laid aside;
he now lost all he had learned at school to that degree that he could hardly read,
much less understand a sentence in Latin.

He now took his swing in vain courses, (as himself expresses) such, however only,
as were accounted harmless recreations,
entertaining his companions and acquaintance with jocularity and diverting discourses;
but he always associated with persons of ingenuity, temperance and sobriety:
scurrility in conversation he considered as contemptible,
and he had a natural aversion to immoderate drinking, by which means,
in the time of his greatest vanity,
he was preserved from profaneness and gross immoralities:
his reputation was unspotted in the eye of the world, and being naturally of a facetious,
cheerful and liberal turn of mind, of a genteel behaviour and address,
his company was engaging and acceptable to his equals and superiors in rank,
opening him an easy access to persons of the best note in that country.
Lord Wenman in particular, to whose lady his mother was nearly related,
who had bestowed his own name upon him, when he made large promises for him at the font,
always received him as a welcome visitant at his table;
and he had reason to expect some preferment in the
world through the friendship of this lord,
as soon as he should be capable of it,
had he not shortly after been called to a higher service,
and thereby lost the favour of all his friends, relations and acquaintance of this world.
During the residence of his father and the family in London,
he had contracted an acquaintance with the lady Springett,
widow of Sir William Springett, who was afterwards married to Isaac Penington:
In order to keep up the acquaintance,
he continued occasional visits to them in their places of residence in the country,
particularly when he heard of their removal to reside at
their own estate at Chalfont in Buckinghamshire.

Some time after Isaac Penington and his wife had
joined in communion with the people called Quakers,
and when this people was become the subject of much conversation,
Thomas Ellwood`'s father being desirous to inform himself of their principles,
determined on a visit to Chalfont, and took his son and two daughters with him;
they met with a kind reception, and spent some days there,
and during their stay a meeting being appointed about a mile distant,
they were invited to go to it, and readily complied.

To this meeting came Edward Burrough, James Nayler and others;
but Edward Burrough only preached in that meeting, near to whom Thomas Ellwood sat,
who was deeply affected with his doctrine,
for it did not only clearly convince his understanding,
but warmed his heart with animated feelings,
such as he had never before experienced from the ministry of any man.

The next day they returned home;^
footnote:[Except the eldest daughter, who was gone before by the stage coach to London.]
at their departure Edward Burrough accompanying them to the gate,
directed his speech to them severally in a few words,
according to the sense he had of their several conditions;
of which this discerning young man appeared to have a clear comprehension.
After they were gone off and the family returned into the house,
Edward being asked what he thought of them, he answered to this effect:
As for the old man he is settled on his lees and the young woman is light and airy;
but the young man is reached, and may do well if he do not lose it.

The impression made on his mind by Edward Burrough`'s public testimony
and private address was too deep to be readily erased.
In his return home his mind was greatly affected
with serious thoughtfulness and sadness of heart,
although as-yet he could not distinctly understand the cause: However,
he felt a desire to go to another meeting of the Quakers,
and upon inquiry hearing of one appointed at High Wycomb, he went thither.
It was held in the house of John Raunce,
and they had not been long sat in the meeting before a person,
to him at that time unknown, but afterwards his intimate friend, Samuel Thornton,
stood up to speak.
His discourse was suitably adapted to Thomas`'s state,
and reached home as if it had been directed to him.

This meeting he esteemed like the clinching of a nail,
confirming and fastening in his mind those good impressions,
which it had received in the former.
His understanding began to open, and the light, shining out of darkness in some measure,
discovered what it was that had before clouded him,
and brought that sadness and trouble upon him;
that although he had been preserved in a good degree from open immoralities,
and the gross pollutions of the world,
yet the spirit of the world had hitherto ruled in him, and led him into pride, vanity,
flattery and superfluity, all which were naught.
He found there were many plants growing in him,
which were not of the heavenly father`'s planting, and that all these (of every kind,
and how specious soever) were to be plucked up.

To trace the various conflicts he endured,
and the gradations whereby he advanced in the experience of that regeneration,
without which Christ declared to Nicodemus,
"`no man shall see the kingdom of heaven,`" would lead me into an unnecessary prolixity,
after similar accounts of the conversion of divers others, previously given in this work.
In proportion to his ready obedience to the divine will,
manifested by the light in his own mind,
he was favoured with the consolation of inward peace; but from without,
his trials were severe and of considerable duration.

For a season after his convincement,
and after his declining the customary modes of salutation and address
(which he had been before in the practice of) to his associates and others,
the veil was not so rent,
but that there still remained a cloud on his understanding
with respect to his demeanour towards his father,
being willing to persuade himself that he ought to
put that difference between him and all others,
as to deport himself towards him, both in gesture and language, as he had hitherto done.
So that his father observing no alteration in his carriage towards himself,
found as yet no occasion to take offence at it.

But it was not long before he saw more clearly that the honour
due to parents did not consist in uncovering the head,
and bowing the body to them; but in a ready obedience to all their lawful commands,
and in performing all needful services unto them;
under this conviction he believed it his duty to behave to his father in this respect,
as he, from conscientious conviction,
had been persuaded it was right to behave to other people.

His father was in no wise pleased at the first apprehension
he conceived of his son`'s inclining toward this people;
but when he was convinced, by his standing covered before him,
that he was really become one of them, he was transported by passion to that degree,
that he fell upon him with both his hands, and after beating him violently,
plucked off his hat and threw it away.

The like occasions drew upon him a repetition of the like treatment several times over,
till all his hats, one by one, were taken from him; and he was thereby,
and by his father`'s command,
obliged to submit to a kind of imprisonment in his own chamber during a cold winter,
and having no hat to wear within or without he contracted a violent cold in his head;
which kept him in great pain a considerable time.

After some time of this severe treatment, and close confinement,
his kind friends Isaac and Mary Penington returned his father`'s visit,
principally with a view to see how he fared.
They had much discourse with his father in relation to their religious principles,
and close reasoning in regard to his hard treatment of his son,
for which he was quite at a loss to apologize.
In conclusion Mary Penington proposed to his father,
that since his son`'s demeanour was offensive, and his company unacceptable to him,
he would give him leave to go home with them, and spend some time at their house,
where he should meet with a sincere welcome.

Although his father was unwilling to comply, and sought many evasions,
yet she prevailed upon him at length to leave Thomas at his liberty,
whereby he was released from a pretty long imprisonment at home;
and going with his friends,
he had with them the full enjoyment of that liberty he most desired,
the liberty of attending the meetings of his friends,
both at the place of his present residence, and other places in that neighbourhood.

After some weeks stay with them, where he was treated with the greatest kindness,
he returned home, where,
although his father did not proceed to the extremity of assaulting him with blows,
as he had done before, yet he kept him at a great distance,
and through the offence he took at his appearing covered before him,
would not admit him to his table, and as seldom as possible to his presence.
By the interposition however of his sisters, he now enjoyed more quiet,
and took more liberty to go to meetings than he had done before;
he informed himself of the meetings held in that neighbourhood,
and many a hard travel he had in all weathers, two,
four or five miles on foot through dirty roads.
But the ardour of the early members of this society for their own spiritual advantage,
and their progress in religious experience,
which they felt to be especially promoted in their religious assemblies,
as well as their apprehension of duty to worship the supreme Being in that way,
which they thought acceptable to him,
enabled them to encounter and surmount the attendant
difficulties with fortitude and unrelaxed perseverance,
while they were at liberty to attend them.

But this friend, with many others of his brethren of this age,
was frequently deprived of that liberty by the confinement of his person in prison.
His first imprisonment was in the year 1660, upon the following occasion:
He had been in London, and on his return calling at J. Penington`'s,
he met there with Thomas Loe,
and from a desire that his neighbours might have an opportunity
to hear the gospel preached livingly and powerfully among them,
he proposed to Thomas Loe the appointing of a meeting in the town where he lived; Thomas,
not apprehending himself at his own disposal,
did not immediately close in with the proposal, but desired T. Ellwood,
if the matter continued with weight upon his mind, and he could get a convenient place,
to apprize him thereof by a letter directed to him at Oxford.

Thomas Ellwood having soon after a prospect of procuring a suitable place,
wrote to Thomas Loe according to his desire, this being soon after Venner`'s insurrection,
when orders were issued for the stopping and searching of letters,
his letter was intercepted and carried to Lord Falkland, Lord Lieutenant of the county;
where upon he was taken up by a body of troopers
and carried before two of the deputy lieutenants,
who after examination, and tendering him the oath of allegiance,
committed him to prison in Oxford, but I suppose,
in regard to his education and the station of his father, who was their neighbour,
and apparently their equal in rank, he was not committed to the common prison;
but to the custody of the marshal, where his imprisonment was easy;
and not of very long continuance.

Soon after his release from this imprisonment he was left at full liberty to go to meetings,
or whither he pleased; for the time appointed for the King`'s coronation being at hand,
his father with his two sisters went up to London on that occasion.
His sisters were both disposed of in marriage;
his father also took up his residence in the city,
and returned no more to Crowell to settle,
so that Thomas was left in the mansion-house to himself, and almost by himself.

He now paid frequent visits to his affectionate and hospitable friends at Chalfont;
and at this time being sensible of, and lamenting the loss of his learning,
he was incited to employ his leisure time, when, at home at his solitary mansion,
in diligent application to recover it;
but finding it a matter of great difficulty to make the advancement he wished,
for want of an instructor,
he had occasionally expressed his regret at this
disadvantage to his particular friend Isaac Penington,
who thereupon interested himself in his favour to procure him the instruction he wanted,
and through the mediation of an intimate acquaintance of London,
obtained permission for him to attend upon the famous John Milton, at his house,
to read such books as he should appoint, and receive his instructions.
Milton who had filled a public station under the former rulers,
now lived a private and retired life in London, and being deprived of his sight,
always kept a person to read to him,
which was usually the son of some gentleman of his acquaintance,
whom in kindness he took to improve in his learning.
Thomas, as soon as he understood this place was open for him,
hastened to London to put himself under his tuition, and was courteously received by him.
Having provided himself with books and accommodations
for his studies by his intended master`'s rections,
he spent his mornings in studying in his chamber, and in the afternoon attended Milton,
and read to him, and under his instruction was making a speedy proficiency;
but the air of London and close confinement did not agree with his constitution,
he lost his health,
and in less than two months time was obliged to break off his studies,
and return to the country for his recovery.

His recovery was not very sudden,
but at length he was mercifully restored to a good state of health;
and then he returned to prosecute his studies in London,
and was very kindly received by his master,
whose good opinion and cordial regard he had conciliated;
and who was much pleased with his company and conversation,
and expressed his satisfaction at his recovery and return;
with him Thomas went on in his former method of study.

But he soon met with another interruption,
which put the finishing stroke to his studies there.
In the year 1662, as well as the preceding year,
a violent persecution was carried on against the dissenters,
which (as hath been shown) fell most heavily on the people called Quakers:
Their meetings were broken up, and the prisons crowded with prisoners of this society.
On the 26th of the 8 mo.
Thomas Ellwood went to the meeting at Bull and Mouth,
which was suddenly disturbed by a party of soldiers or trained bands,
commanded by one Major Rosewell, an apothecary, a reputed papist.
The soldiers made their entrance, as usual, with noise and clamour;
and further to terrify the assembly, Rosewell commanded his men to present their muskets:
But the assembly kept their places unmoved.
The major commanded them to disperse; but being met,
from a persuasion of duty to worship God ac cording to his requirings, they thought,
with the apostles, they ought to obey him rather than man,
and therefore stirred not at the command of Rosewell; observing this,
Rosewell ordered his soldiers to drag them out, which they did roughly enough.
He took above thirty of them, of which number Thomas Ellwood was one,
and committed them to prison in old Bridewell, which having been formerly a palace,
was no incommodious prison.

This was some time before discipline was settled in the society;
yet an excellent order had been established among friends of that city,
in appointing suitable members of the community, male and female,
to take the oversight of the prisons in every quarter, and to take care of all friends,
the poor especially, that might be committed to any of them.

The prison of Bridewell was under the care of two grave, discreet, motherly women,
Anne Merrick and Anne Travers, both widows,
who as soon as they understood that there were friends committed to that prison,
provided some hot victuals, meat and broth,
and ordering their servants to bring these provisions, with bread, cheese and beer,
came also themselves, and having placed the provision on the table, gave notice,
"`that it was provided for all such as had not others to provide for them,
or were not able to provide for themselves,`" and there wanted
not a competent number of such guests.

Although Thomas Ellwood`'s stock was very low,
yet having had ten pence in his pocket he did not esteem himself
in the description of those for whom the provision was made:
Resolving to husband his scanty stock with the utmost frugality,
and placing his confidence in divine providence for future subsistence,
that good hand in whom he trusted,
awakened the sympathy of some of his particular friends with him under his present trial,
by whose beneficence he was supplied with more than
a sufficiency to support himself during his imprisonment,
and after his release was favoured with the means of returning them their advance,
with grateful acknowledgments of their kindness.

After about two months imprisonment, Thomas and his fellow prisoners,
were brought to the sessions at the Old Bailey.
The prisoners complained of the illegality of their imprisonment,
(for they were committed and detained by arbitrary power,
without the intervention of the civil authority,
having never been brought before a civil magistrate.)
The court paid no regard to their reasonable complaint;
all the satisfaction they received was the following speech of the Recorder,
"`If you think you have been wrongfully imprisoned, you have your remedy at law;
and may take it, if you think it worth your while;
the court may send for any man out of the street, and tender him the oath;
so we take no notice how you came hither; but finding you here,
we tender you the oath of allegiance, which if you refuse to take, we shall commit you,
and at length premunire you.`" Upon their refusal
to take the oath they were committed to Newgate,
and thrust into the common side, which, as well as the other parts of the jail,
was very full of friends, who were prisoners there before,
and the addition of these new prisoners caused a great throng on that side.
After some time they were removed back to Bridewell, their former prison,
where they were much more comfortably accommodated,
till the ensuing sessions at the Old Bailey,
when being called to the bar they were without further question discharged.

After his release Thomas Ellwood went down to pay
another visit to Isaac Penington and his wife,
intending after spending a few days there to return to his studies in London,
but Isaac Penington being in want of a tutor for his children,
prevailed on Thomas to stay with him in that capacity till he could meet with one;
which not readily happening, and both parties being agreeable to each other,
he stayed here till he married, near seven years.

While he lived here he was imprisoned again with his friend and patron Isaac
Penington for his attendance of the funeral of Edward Perrot of Amersham,
and committed to Aylesbury jail for one month, on the act of banishment.

Not long after he was taken with others from a meeting at Hedgerly,
not far from the place of his present residence, by the same justice Ambrose Bennett,
who had committed him and others to Aylesbury jail,
and now again committed to the house of correction at Wycomb, for the second offence,
upon the act of banishment; but although this limits the duration of the imprisonment,
yet this man, although a lawyer,
so far forgot himself as to order them to be kept
until they should be delivered by due course of law.
They were detained above twelve weeks; and then, the rest being released, Morgan Watkins,
a ministering friend of Wales, who had been travelling in those parts,
and Thomas Ellwood were required to find sureties for their appearance at the next assizes,
which refusing, they were recommitted to the same prison.
But the Earl of Ancram interposing in their favour,
discharged them from their imprisonment, upon their promise to appear at the assizes,
which they did, and were there discharged by proclamation.

After his marriage, which was in 1669, he settled at Hunger-hill;
and although he did not appear as a minister amongst his friends,
he be came a very respectable and serviceable member,
and a well qualified elder of their religious society,
being endowed with eminent talents to be useful in supporting
and conducting the salutary discipline established therein,
whether we consider him as holding the pen of a ready writer,
in the capacity of clerk of the monthly, quarterly or yearly meeting;
or with respect to his intellectual faculties, as a man, by precision of judgment,
depth of penetration, and clearness of comprehension,
qualified to speak pertinently to subjects under deliberation,
and with discernment to see the point at which they should be rightly issued;
yet with becoming modesty he did not tenaciously insist on his sentiments being adopted,
but submitted them to consideration,
and left them to make their way by the conviction of their propriety.
Condescending to the weakest,
he was not ready to reject or despise the sentiments of any other,
which appeared to be well intended however weakly expressed;
but would give them due consideration,
and adopt them as far as he thought their weight and pertinence entitled them to approbation.
The monthly meeting was held at his house for the greatest part of forty years,
to which he officiated as clerk,
and took upon him the care to keep the records thereof in good order.

He was also very serviceable to the cause of truth, and of the society,
by his writings in defence of their principles,
and in answering and refuting the calumnies of adversaries ;
as well as by sundry weighty epistles to his friends for their edification,
and preservation from danger of being seduced by
guile from the way of righteousness and peace.

He wrote in a very agreeable, easy and pleasing style, clear and instructive,
being generally a master of the subject he wrote upon;
his pen exercised in defence or for the promulgation of religion and truth,
hath left a standing evidence of the soundness of his understanding,
and of the rectitude of his heart.
After he was released from his office of tutor in Isaac Penington`'s family, and married,
he seems to have been much master of his time,
as it appears to have been very generally employed in serving the society and others,
and in writings of one kind or other.
I do not know that they were ever collected, and published together,
as those of some other friends have been, many of them being of the controversial kind,
might be serviceable and engaging attention at the time they were written;
but the service answered, and the occasion ceasing, became less interesting to posterity,
and therefore not necessary to be revived.
He was much engaged in controversy either with adversaries without,
or opponents within the society, whose endeavours were exerted to lay it waste.
William Rogers and other separatists of that time, and afterwards George Keith,
gave him much employment, to expose their deceit,
and detect the fallacy of their pretensions,
for the preservation of others from being entangled in the like snares;
and his labours were greatly conducive to the good end designed by them.
But some of his writings, being of a more universal nature, are preserved,
as The Foundation of Tithes shaken; The sacred History of the Old and New Testament,
in two volumes folio; and some others.

His private character was amiable and respectable; his countenance manly and cheerful;
his deportment grave; yet affable and courteous even to the meanest;
his conversation pleasing and instructive,
yet marked with disapprobation of everything that
was beyond the circumscription of truth;
of an obliging disposition,
he was ready (and in many cases capable) to serve his neighbours as well as friends,
wherever his service was wanted.
To the poor, the sick and the impotent, who wanted relief,
his house and his heart were open,
being careful to provide medicines and other things useful for such purposes,
begrudging no expense to do good;
these qualities and dispositions procured him a great and general respect
and esteem from most or all who were acquainted therewith.

He lived to a pretty good age, and when advanced in years looked very well,
being of a regular and temperate life, and healthy constitution,
only in his latter years was at times troubled with an asthma;
and at last was attacked with a paralytic stroke,
which he bore with great patience and resignation;
and although his speech was considerably affected,
so as to be understood with difficulty,
yet some of his dying expressions were sufficiently plain to be under stood,
conveying to the hearers a clear indication of the peaceful tenour of his mind,
and perfect resignation to divine disposal.
Being visited by some of his friends, and one of them being concerned to pray by him,
he expressed himself, in much tenderness,
I am sensibly comforted and refreshed in this visit.
At another time he expressed his resignation as followeth:
"`If the Lord hath no more for me to do, I am content and resigned to his will;
and my hearty farewel to all my brethren.`"
And near his end he said, "`I am full of joy and peace; my spirit is filled with joy.`"
In about eight days his disorder put a period to his life the 1st of 3mo. 1713,
in the seventy-fourth year of his age.
Having served his generation according to the will of God, he fell asleep,
and was honourably buried the 4th of the same month,
being accompanied from his own house by a great number of
his friends and others to the meeting-house at Jordans,
and interred in friends burying ground there.
The meeting was very large, in which divers living testimonies were borne to the truth,
he lived and died in, in a lively remembrance of him and his services in the church.

The antipathy which the magistrates of Aberdeen,
through the instigation of their preachers had imbibed
against this society continuing to of Aberdeen operate,
had produced a by-law of the corporation in effect
to disfranchise all who professed Popery or Quakerism,
those of the latter society, inhabitants in and about the city,
presented a petition to the Queen and Council, praying relief,
whereby they procured an order of the Privy Council,
prohibiting the execution of the said by-law,
as far as it affected the people called Quakers.

The Queen`'s health began to decline fast, and tend to her dissolution;
the nation was at this time in a very unsettled state;
party animosities were revived to an excessive degree,
and her very ministers broke out into open dissensions,
which were thought to hasten her end.
The reigning party in the latter years of her reign,
were of that class of the established religion,
which had always manifested a bigotted and intolerant zeal for the hierarchy,
and consequently a fixed aversion to all dissenters.
A fondness for penal laws seemed to revive,
and it looked as if they had now conceived a design gradually
to destroy the benefits of the toleration act;
for after carrying the act against occasional conformity,
they brought in this session an act against the growth of schism,
being designed to prevent dissenters from keeping schools,
and virtually to take out of the parents hands their natural right
in the care and direction of the education of their own children.
The bill met with great opposition in both houses as a species of persecution,
and the people called Quakers presented to the legislature the following remonstrance.

[.embedded-content-document.address]
--

[.numbered]
_1st,_ The church of England hath frequently declared, by several of her members,
in a civil as well as clerical capacity,
by those who framed and espoused one or more of the bills against occasional conformity,
that she is in principle against persecution, and for preserving the toleration.

[.numbered]
_2ndly._
The promoters of this bill may please to remember,
that the Queen hath declared from the throne,
that she will maintain the toleration inviolable.

[.numbered]
_3rdly._
The protestant subjects of this kingdom, who are parents of children,
are supposed to have preserved to them, by the fundamental laws of this kingdom,
the natural right of the care and direction of the education of their own children,
which natural right this bill seems calculated to take away and destroy.

[.numbered]
_4thly._
If the governments which are now Heathen or Mahometan, should take into the same policy,
the society which the Queen hath incorporated for
the propagation of the gospel in foreign parts,
can have very little, if any good effect or success.

[.numbered]
_5thly._
May it not seem an objection and contradiction to the many princely and christian
solicitations which the Queen by her ministers hath made at foreign courts,
on the behalf of protestants,
against the violent intrusions of papists into their rights and just privileges.

[.numbered]
_6thly._
It may be a means to oblige the carrying out of large
sums of money for foreign education.

[.numbered]
_7thly._
It may probably do much hurt to charitable foundations.

[.numbered]
_8thly._
It seems not to be agreeable to the great law of Christ, Matt. 7:12.
"`Therefore all things whatsoever ye would that men should do to you,
do ye even so unto them; for this is the law and the prophets.

--

But opposition or remonstrances avail little against determinations supported by power;
the ministry had managed so as to procure a majority in both houses of parliament;
the act was passed, and received the royal assent.
The state of affairs and prevailing disposition at this time filled many of the dissenters,
particularly, with gloomy apprehensions.
The Quakers (so called) in their epistle from the yearly meeting this year,
from the present prospect of things,
gave forth this caution and exhortation to their friends:
"`There seems at present to hang over us a cloud, threatening a storm.
Let us all watch and pray,
and retire to our strong hold in our spiritual rock and foundation, which standeth sure;
that our God may defend, help and bless us, as his peculiar people,
to the end of our days and time here, and +++[+++with]
the full fruition of the heavenly kingdom hereafter.`"

The Queen was removed by death the very day this act against schism was to take place,
whereby it was rendered ineffectual,
and the princess Sophia having died a little before her, the crown,
by the act of settlement, descended to her son George,
Prince Elector of Brunswick Lunenburgh,
who was proclaimed King of Great Britain the day that the Queen died.
