== Chapter XVIII. America.

[.chapter-synopsis]
* George Keith`'s Party fall into Dissensions and dwindle away
* George Keith is sent in quality of a Missionary to America
* His Endeavours more directed to depreciate the Quakers than to recommend Episcopacy
* His Interview with John Richardson
* Thomas Story meets with him at Shrewsbury
* He challenges a Dispute with Samuel Bownas
* Which being rejected
* George Keith and his confederate Bradford afterwards combine together to try if any Advantage can be taken from Samuel`'s Doctrine
* Bradford lodges an Information against Samuel
* Who is imprisoned
* Brought to Trial, but the Indictment rejected by the Grand Jury
* Confined more closely
* At length cleared by Proclamation
* George Keith returns to England and obtains a Living in Sussex
* Becomes uneasy to his Parishioners about their Tithes

The party who had been drawn aside by George Keith,
were by this time greatly reduced in numbers, during his presence amongst them,
and for some time after he left them, actuated by that spirit of envy and bitterness,
under the influence whereof they had fallen out with their quondam friends,
and detached themselves into a separate society,
they continued to treat the body from which they had separated with great asperity,
and to be very troublesome to them in their religious assemblies and else where.
But in a few years they fell into division and dissension amongst themselves,
whereby they were diverted from their molesting of friends,
to gratify their lust of contention in bitter altercations with each other.
Thus disunited, their society dissolved, their meeting dwindled away,
and in six or seven years their name as a sect sunk into oblivion.
George Keith in the meantime had arrived in New England in quality of missionary, and,
together with one John Talbot,
had received letters of recommendation from the society
for propagating the gospel in foreign parts,
to make what converts they could in those provinces.

Notwithstanding he had given great expectations from
his influence amongst his partisans and others,
of bringing over many from the Quakers and other dissenters to the church of England;
and at his return gave such a flattering account of his embassy,
that it was said he had brought comfort to the church;
yet in fact he was very unsuccessful in answering the design of his mission.
At his leaving his adherents in Pennsylvania, he had hinted to them,
if they should hear of his preaching amongst the presbyterians
or independents they should not term him an apostate for that;
but if ever they should hear of his putting on the canonical robe,
and uniting with the church of England,
he would give them leave to fix that denomination upon him.
When, therefore,
he returned to America in the character and habit of a clergyman of that church,
he effectually lost all his interest and influence with his former adherents;
both those who had withdrawn after him from the people called Quakers,
and the Baptists who had adhered to him, were quite shy of him; and offended with him,
for leading them into a secession, and thus deserting them.

His principal exertions were not I apprehend in Pennsylvania,
where he was known and now generally slighted; but in New England,
and on that side where the people were greater strangers
to his former transactions there;
and still more directed to disturb the Quakers (so called) in their meetings,
and by his accustomed false accusations to make them appear odious,
than to render the church of England amiable,
or pursue rational measures to reconcile dissenters thereto.
His resentment against this society, first for rejecting him as a ruler, and afterward,
as a member, still predominated in his mind, agitated him inwardly,
and aggravated his unreasonable prejudice;
under the impulse where of his endeavours were more employed to vex and harass the Quakers,
than to propagate the gospel amongst them, or any other body of people.

He seems very much to have made it his business to
appoint his meetings or places of preaching,
at the times and places where the people called Quakers held their general meetings;
or where strangers of that society, came to those parts, in which he was,
in the course of their religious visits.
John Richardson of Burlington in Yorkshire, a well qualified minister,
and a man deeply experienced in the work of religion,
was at this time travelling in New England, came to Lynn to their monthly meeting,
and was there informed of George Keith`'s intention to be at that meeting,
which gave him some concern,
under the apprehension of the interruption his presence
might give to the solemnity of the meeting;
he advised to be swift to hear and slow to speak,
as George Keith had a life in disputation.

The evening preceding the meeting,
George Keith came to the house where John Richardson lodged,
with a priest and a great number of people along with him,
and began railing exceedingly against friends, in insult to the stranger:
And then in vain exultation exclaimed, "`Is here a man that is a scholar?
Is here a man that understands the languages amongst you?
If so, I will dispute with him.`"
To this boasting challenge John Richardson replied,
"`It was probable that the English language was most generally understood,
and used amongst that people,
and therefore he thought it most suitable to converse in.`" Then
George Keith proceeded to magnify the dignity of his office,
that he was come in the Queen`'s name to gather the
Quakers from Quakerism to the mother church,
the good old church of England; threatening the next day to convict them of errors,
heresies, damnable doctrines and blasphemies: Adding, "`look to answer for yourselves,
for if you do not, the auditory must conclude,
what I advance against you is true.`" John Richardson roused at this insulting menace,
said to him, "`this is the fruit of malice and envy, and thou art unto us,
but as a heathen man, and a publican.`"

The next day George came to the meeting, where he repeated the purport of his embassy,
and his threats in the same terms as on the preceding evening.
John Richardson, in reply, laid open to the people assembled his conduct;
the proceedings of the society in relation to him; to which George made no objection;
but continuing quiet, the meeting was held peaceably and to edification,
John Richardson appearing in the ministry, and beginning with these words,
"`After the manner that you call heresy do we worship the God of our fathers,
believing all things that are written concerning Jesus Christ,
both as to his Godhead and manhood.`"
The people were attentive and well satisfied;
and George Keith owned he had been refreshed in that meeting,
having heard many sound truths, with some errors;
but that it was not the common doctrine which the Quakers preached.`"

John Richardson,
perceiving that this insinuation was intended to infuse an opinion into the people
that the Quakers did not usually preach up faith in the manhood of Christ,
to obviate the effects thereof, distinguished upon it to this purpose,
that it was the less necessary,
as being a point of faith universally received among christians,
and as clearly demonstrated by the people called Quakers in their testimonies,
and their writings, to be a point of faith with them, as any other people;
but that as his holy spirit is highly concerned in man`'s salvation,
as well as what Christ did for us without us,
and this being yet a mystery to many called christians,
it had pleased God to open them in the course of their ministry,
into the meaning and mystery thereof,
and to insist upon the latter more than the former.

To this George Keith made no reply, but began to exhibit his charges,
and stepped up to the gallery with his paper in his hand.
John Richardson being taller, and standing by him,
could see his quotations and paraphrases upon which he told him,
"`that he offered violence to that sense and understanding which God had given him,
and knew in his conscience we were not the people he through envy endeavoured
to make the people believe us to be.`" The meeting soon after broke up,
and terminated the controversy for that time.

They met again in Rhode-Island, and afterwards at Flushing in Long-Island;
but he gave friends little trouble in either: For at the latter,
particularly John Rodman of that place,
having got intelligence that George had by some means possessed
himself of 50s. out of a considerable legacy left by Col.
West to poor friends of London,
which was ordered to be paid over to some faithful friends of that city,
and it being proved upon him that he had received
the said sum and never accounted for it,
in wrong of the poor, he was sighted by most of the people, as well as friends,
and this detection of his unfair dealing so blocked up his way
that friends had little trouble with him in that quarter.

The next friend who fell in with him on his travels was Thomas Story from Carlisle.
He being come in the course of his visit to Shrewsbury in East Jersey, informs us,
that George Keith, in company with his fellow missionary, story, Talbot,
came to Shrewsbury at the time of the yearly meeting held there for that province.
On the first day of which he sent by said Talbot an advertisement to the meeting,
"`That he purposed to have a meeting at a house in the town,
to begin at the eleventh hour the next day,
then and there to detect out of the books of authors approved among the Quakers,
divers vile errors, contrary to the Christian faith,
and the fundamental principles of the Christian religion.`"
And challenging friends as before,
"`to come and answer for themselves,
or he would judge his quotations and remarks to be true,
and a demonstration to all intelligent people that he had not wronged
them.`" Where it may be proper to observe his subtle management
in appointing his meeting about the middle time of friends meeting,
when it was most likely they might feel themselves more comfortably
and better employed than to desert their own meeting of solemn
worship to perplex themselves with his invidious cavils:
They returned him answer, "`That being to them as a Heathen or a Publican,
they continued to reject him, despising all his works of envy and revenge;
that as he had begun in print, they should (as hitherto) answer him in that way,
as least liable to misunderstanding and misrepresentations.`"

Soon after this Samuel Bownas from Westmoreland landed in Maryland,
and almost immediately after received the following note:

[.embedded-content-document.letter]
--

[.salutation]
Sir,

I intend to give notice after sermon, that you and myself are to dispute tomorrow,
and would have you give notice thereof accordingly.

[.signed-section-closing]
Sir, I am your humble servant,

[.signed-section-signature]
George Keith.

[.signed-section-context-close]
Dated the 1st Sunday in August, 1702.

--

Samuel being previously engaged to go forward to an appointed meeting,
in company with a considerable number of friends,
would have taken no notice of an unprovoked challenge;
but being told Keith would call the country together and make much noise about it,
as if they were afraid of meeting him, and urging Samuel to write him an answer,
he accordingly wrote to the following effect;

[.embedded-content-document.letter]
--

[.salutation]
George Keith,

I have received thine,
and think myself no way obliged to take notice of one who
hath been so very mutable in his pretences to religion;
beside, as thou hast been long since disowned,
after due admonition given thee by our yearly meeting
for thy quarrelsome and irregular practices,
thou art not worthy of my notice, being no more to me than an Heathenman and publican.

[.signed-section-signature]
Samuel Bownas.

--

George Keith and Samuel met sundry times in their travels in those parts,
but had little discourse or debate with each other: But when he came into Long-Island,
a meeting being appointed for him at a village called Hempstead,
here he met with George Keith again,
and William Bradford his late printer in Philadelphia: These two combining together,
Bradford was sent to the meeting to see if any advantage could be taken of his doctrine.

He came accordingly, and when Samuel stood up to speak,
he pulled out of his pocket a small book, with pen and ink,
steadfastly staring in his face to try to put him out of countenance, but in vain:
He then wrote a little, and so continued alternately essaying to write,
and to daunt him by his staring;
but Samuel feeling that animating virtue which bore him up above regarding his attempts,
went through with the subject matter before him: When he had done,
Bradford stood up with this interrogatory,
"`Will you stand by these doctrines in public that
have been now preached?`" To which John Rodman replied,
"`William,
thou knowest what our friend hath been concerned to speak about
this day are such points as have been argued over and over,
and as the controversy hath been some years in print,
it is needless at this time to reduce it to a verbal disputation.`"
But not being satisfied without receiving Samuel`'s answer,
he told him his question being more for contention than edification,
he did not think himself obliged to answer it,
especially to one who for his contentious and disorderly behaviour,
after tender admonition rejected by him, had been disowned;
and for this reason Samuel said, I have no more to say to thee.
Bradford upon this turned away in great wrath,
threatening Samuel should hear of it another way.

In his testimony Samuel had fallen upon the subject of ceremonies,
particularly those of baptism and the use of bread and wine, called the Lord`'s Supper;
and as it seems endeavoured to show their insufficiency to salvation of themselves,
according to the manner of the administration thereof, either by the Papists,
the Church of England or Dissenters.

Keith, and Bradford from his notes, trumped up a long affidavit,
and Bradford attested it before two justices; and then another evidence being requisite,
they met with a young man who had been at the meeting,
from whom Keith extorted some expressions he had heard spoken,
which having done they threatened him with dreadful
consequences if he would not come in and give evidence;
therefore, through fear,
he was prevailed upon to give his evidence upon oath in
the words George Keith had got from him by guile.

Having brought matters to this issue, they procured a warrant to apprehend him,
and put a stop to his travelling;
for he was informed that Keith had proposed the making
a law to restrain friends from travelling,
only to their own meetings;
for it was the travelling preachers that kept the Quakers compacted together.
This by bigots was approved as a likely method to put a stop to their increase,
but by men of moderation treated with the contempt it deserved.
The warrant being procured and delivered to the sheriff,
he arrested him the next day in the meeting at Flushing,
being the half year`'s meeting for New York government;
but being a man of a less implacable disposition than the prosecutors,
he stayed the meeting; after the meeting was over,
having a conference with some of his friends,
he was prevailed upon to give him his liberty till the fifth day of the week,
which gave him the opportunity to attend the remaining
meetings to the end of the said half year`'s meeting,
in which he had good service, to the general satisfaction of crowded auditories.

The meeting being ended, he appeared before the justices, accompanied by several friends,
and after his examination and their consultation among themselves,
he was called in again, when the clerk informed him,
that these honourable justices have agreed that you enter into 2000£. bail,
yourself in 1000£. and two of your friends 500£. each,
or else be committed to the common jail.
Refusing to enter into bail, one of the justices asked him, if the sum was too large,
he replied, "`if as small a sum as three-halfpence would do, I should not do it,
it being of such a nature as I could by no means comply with.`" Jonathan Whitehead,
one of the justices, was very friendly, wanted him to be set at liberty,
offered himself for bail, and took him to his house that night,
where he was very kindly entertained.
The next day he was sent to jail with the following mittimus:

[.embedded-content-document.legal]
--

[.blurb]
=== Queen`'s County S.S.

[.blurb]
=== Joseph Smith, Esq; Edward Burrows, Esq; John Smith, Esq; and Jonathan Whitehead, Esq; justices of the peace, for the Queen`'s County.

[.letter-heading]
To the high sheriff of the Queen`'s County, greeting.

We send you herewithal the body of Samuel Bownas, a Quaker, brought before us this day,
and charged with speaking scandalous lies of,
and reflections against the church of England, as by law established,
and other misdemeanours by him done and spoken at
a public assembly in Hampstead in this county,
on the 21st day of this instant November.
And therefore these are in behalf of her Majesty to command you,
that immediately you receive the said Samuel Bownas,
and him safely keep in the common jail of this county,
until he shall be thence delivered by the due course of her Majesty`'s laws.
Dated under our hands and seals at Jemeca this 30th day of November,
in the second year of the reign of our sovereign lady Anne, etc.
Annoq.
Dom. 1702.

[.signed-section-signature]
Joseph Smith, Edward Burrows, John Smith, Jonathan Whitehead.

--

This proceeding may appear strange at this time, as being supported by no existing law,
and a violation of the act of toleration; but it is to be observed,
that at this very time the high church party were
so considerable a body in the parliament of England,
that they had procured an act against occasional conformity;
and manifested their enmity to dissenters by an acrimony
which indicated their propensity to persecution,
and was by many looked upon as a step to a repeal of the act of toleration.

It was at the same time the lot of New York to be governed by a principal of this party.
Lord Cornbury, son to the Earl of Clarendon, was governor of this province,
who actuated by an hereditary zeal for the hierarchy, and aversion to non-conformists,
had in an arbitrary manner silenced sundry presbyterian preachers,
and placed churchmen in their room,
and on many occasions manifested an inimical disposition to dissenters in general,
and an inclination to revive severe measures against them;
taking liberties in this remote province,
which would as yet have hardly been allowed or endured at home.
Cornbury favoured the prosecution, and it is probable,
that the prospect of his countenance thereto encouraged
these ill-designing men to make the attempt in his government,
which they could expect little success in attempting elsewhere.
Governors are seldom at a loss to find,
or to model magistrates to comply with or promote their measures.
The judges, particularly Bridges the chief justice,
accommodating themselves to the governor`'s intentions,
in imitation of our judges in king Charles the second`'s reign,
directed their endeavours to get him convicted right or wrong.

But although the judges were of this cast,
the temper of the times was considerably changed,
so that it was not easy to get juries equally obsequious with those of that era.
Where men thought for themselves,
and were influenced by the impulse of their own consciences,
they were not so easily warped by the partial instructions of the bench.
When Samuel Bownas had been about three months in prison,
a special commission of Over and Terramer was issued to John Bridges, chief justice,
and other justices.
A bill of indictment was sent to the grand jury against Samuel,
who had prepared reasons to set Bradford`'s evidence aside,
and the same being laid before the grand jury, they had such weight with them,
that they returned the bill endorsed, _Ignoramus,_
at which disappointment the judge was greatly incensed,
and treated the grand jury with indecent asperity,
addressing them in this passionate language:

[.discourse-part]
Gentlemen, surely you have forgot your oaths,
and for so doing I could give you some hard names, but at present shall forbear.
Is this your verdict against the Quaker?

[.discourse-part]
_Foreman._
It is, Sir.

[.discourse-part]
_Judge._
I demand your reasons.

[.discourse-part]
_James Clement, a juryman._
We are sworn to keep the Queen`'s secrets, our fellows and our own,
and therefore we declare no reasons.

[.discourse-part]
_Judge._
Now Mr. Wiseman speaks, but I can tell you, you are not so sworn;
and I could find in my heart to lay you by the heels,
and a fine on the rest of your brethren.

[.small-break]
'''

The judge finding his threats ineffectual with men
who knew they stood on constitutional ground,
and therefore disregarded them, changed his mode of address,
and begged them to take back the bill, and resume the consideration thereof,
which they did,
but could not be prevailed upon by menaces or by flattery to alter their verdict,
which exasperated the judge to that degree,
that he gave strict orders for the prisoner to be confined more closely than before,
that as justice cannot be here come at,
he would send him to London chained to the man of war`'s deck, like other vile criminals,
with his crimes and misdemeanours along with him.
Samuel being a young man, little versed in the law,
or the knowledge of the constitutional power of the judge,
was greatly dejected at the report of this menace,
doubting how far he might be able to support so disgraceful and so humiliating
a punishment with the decorum suiting the dignity of the cause for which he suffered.
His friends had left him alone, and he had lost his faith,
which was worse than being left alone.
His despondency was so great, that he thought himself the most wretched among men,
and scarcely able to live under it.
In this condition he received a visit from Thomas Hicks, an ancient man,
who had borne the office of chief justice in the province some years,
and was well versed in the laws, who gave him great encouragement,
by assuring him the judge could not put his menace in execution,
for that every criminal must be tried where the cause of action lies;
but that the judge and governor also were disgusted by being frustrated in their designs.
Had, said he, the Presbyterians stood as you have done,
they had not so tamely left their meeting-houses to the church.
The discourse of this honest man was the means of renewing his faith,
and of raising him from the state of dejection in which he found himself before.

Being advised to demand his liberty as his right by law, he did so, both of the judge,
and afterwards by petition to the governor, but it was arbitrarily refused.
They were resolved, they said, not to be so baffled by the country,
but they would bring him to justice.
Keith printed some sheets, in pretence to open the eyes of the people,
aggravating the case to the utmost; but it had a tendency to open their eyes,
more to discover his envy and vindictive spirit against the Quakers in general,
and the prisoner in particular,
than to convince them of the justice of their proceedings.

He was now closely confined in a small room made of logs,
which had been protested against as an unlawful prison two years before,
and his friends denied to visit him.
But here we meet with a fresh instance of the care
that rested upon these disinterested men,
not to make the gospel chargeable.
Not knowing how long his imprisonment might continue, he became very thoughtful,
what method to take for supporting himself,
and it was suggested to his mind to try if he could learn to make shoes;
and meeting with a good-natured man of that craft,
he made proposal to him for instructing him in the art,
at the same time acquainting him with his reason for so doing; he replied,
"`It is very honourable in you, but if one of our ministers were in the like situation,
they would look upon it as a disparagement to take
up so mean an occupation;`" yet he acknowledged,
if Samuel could earn his bread with his own hands,
it was most agreeable to Paul`'s practice.
Samuel quickly made so much proficiency in the art,
that he procured thereby more than a sufficiency for his support,
which was not only conducive to make the time of his confinement less irksome,
but administered abundant ease to his mind,
in the reflection of being enabled to procure a support
by the labour of his own hands without charge to his friends,
some of whom were uneasy, supposing it might appear dishonourable in them to suffer it;
but others apprehending it a great honour to the cause of the gospel,
rejoiced that he succeeded so well.

He was detained in prison about nine months longer;
and about the beginning of the eighth month 1703,
the sheriff received an order to summon another jury, to try their success a second time.
He had private instructions to procure such a jury
as might be likely to answer their purpose,
which he showed Samuel with marks of abhorrence, assuring him he would never do it.
So the jury being fairly named, and the indictment sent to them,
they looked upon it too frivolous to engage their serious attention, and returned it,
as their predecessors had done, _Ignoramus._
He was next brought into court, and nothing appearing against him,
he was discharged by proclamation.
Not only his friends,
who came from most parts of the island to wait the issue of his trial,
but the people in general, were exceedingly rejoiced at his acquittal and discharge,
after being invidiously imprisoned,
and arbitrarily detained in prison twelve months wanting about three weeks.

These specimens of George Keith`'s conduct in the capacity of a missionary,
manifest it to be chiefly directed to vent his deep resentment against the Quakers,
whereby instead of promoting, he in a great measure defeated the end of his mission;
for his unreasonable prejudice and unprovoked enmity were so obvious,
that instead of bringing an odium on the Quakers, as he designed,
he brought great discredit and great dislike of his proceedings
from the generality of the people upon himself,
so that he shut up his own way from making many proselytes amongst them.

He spent something more than twelve months in the itinerant exercise of his new function,
and returned by way of Virginia to England,
where he obtained the benefice of Edberton in Sussex,
and there he continued his writings and invectives against his former friends;
but his restless temper was not fully satisfied with venting his passion against them.
It was not long before he began to fall out with his parishioners about their tithes.^
footnote:[These anecdotes of George Keith during his incumbency
at Edberton are taken from some memoirs of John Snashall,
who lived in that neighbourhood, viz. at or near Hurst-pierpoint in Sussex,
who wrote them either of his own knowledge or from the information of his neighbours,
who reported them as truth from their knowledge of the facts.
John Snashall is characterized by his friends as a man of
a very loving and courteous disposition to all:
In charity universal, and a good and kind neighbour; and being a religious man,
was doubtless a man of veracity.
These memoirs he left in manuscript, which were preserved in the family,
and communicated to me by Jeremiah Waring, junior.]
Not content with the accustomed income of his parish,
which was reported to exceed 100£. per annum, he would sometimes take the tithes in kind;
sometimes let them to others to take in kind,
meditating and trying every method to raise the income to the utmost,
and extending his claim to the minutest articles,
even to the tenth of the eggs of one hen,
and of the scanty crops of garden roots of the poorest inhabitants of his parish,
by which he estranged the affections of his hearers,
who were quite disgusted at such instances of his avarice and his meanness.

That he was upon ill terms with his parishioners further appears from hence,
that being affected with lameness and infirmity for three years before his decease,
and disabled from walking to the place of worship,
he was presented by his parishioners for divers neglects;
for letting the parsonage-house go to decay for want of necessary repairs;
for not going to preach himself at the proper seasons,
nor hiring a curate to officiate in his stead.
In short, he had so indulged his propensity to contention,
that he could hardly keep upon good terms with any he had to deal with,
whereby he became despicable and disagreeable in the eyes of his neighbours;
many of whom would declare,
they should be glad that the Quakers would take him back again,
so that they might be rid of so restless a spirit.
Like the salt that had lost its savour,
and was thenceforth good for nothing but to be cast
out and be trodden under feet of men.

Yet after all, there is reason to suppose that he was favoured,
particularly near his latter end, with seasons of serious reflection,
wherein he viewed the peaceful state of his mind whilst
in unity and peace with the Quakers as brethren,
and felt remorse under the loss thereof.
Paying a visit to a gentleman at Hurstpierpoint,
and a conversation arising concerning the Quakers, he owned before several persons,
"`That since he had left them he had lost one qualification they had among them,
that in their religious meetings they could stop all thoughts which hindered their devotions,
which he very much admired he could never attain to since.`"

I have already related from Alexander Arscott the acknowledgment
George Keith made to Richard Hayler on his death bed,^
footnote:[See vol.
3, p. 452.]
which passage is also thus related by John Snashall aforesaid:
The 16th 1mo 1703 George Keith, as he lay sick in bed, said,
that he did believe if God had taken him out of the world when he went among the Quakers,
and in that profession, it had been well with him;
which words he spoke before Richard Hayler of Stepning, who went to see George Keith,
hearing he was sick.

In order to bring this disagreeable subject to a conclusion,
I am considerably advanced in time,
and in the description of the whole of this man`'s transactions,
I am not conscious of exaggerating any circumstance beyond a true state thereof,
according to the authorities of contemporary writers, some of whom, with myself,
regret the occasion of dwelling upon the subject,
and express the great respect they had had for him
on account of his qualifications and services,
believing him to have been a man truly convinced and enlightened, and in a good state,
(which his aforesaid confessions plainly imply),
but that through ambition and self-exaltation, he fell away therefrom;
it being our persuasion, that a righteous man may turn from his righteousness,
and that we are no longer safe than whilst we are watchful.

Now as there have been many bright examples of virtue
and pure religion exhibited in this work,
showing what is most worthy of our endeavouring to attain;
so here we have an example of caution, what is most carefully to be avoided,
in order to preserve divine favour, the unity of the brethren,
and respectful esteem of all good men:
A powerful caution not to indulge a disposition aspiring
above our proper places in religious society,
but whatever our abilities or attainments, natural or spiritual, may be,
to keep in the humility becoming dependent beings, who have nothing good,
but what they have received from the fountain of all good;
and if we conceive we have in any respect an advantage over some others,
let us remember the apostle`'s reasoning, "`Who made thee to differ from another,
or what hast thou that thou had not received?`"

I have ever looked upon it as a great enormity to deck ourselves with the Lord`'s jewels,
to suffer the talents and gifts bestowed upon us, (it may be not for our own sakes,
but the edification of the body),
to occasion an exalted opinion of ourselves in the contemplation thereof;
and still more enormous to apply the place they have
given us in the estimation of our friends,
to the low purposes of promoting our own interests, or seeking preeminence,
dominion or lordship in society.
May I, may my brethren and sisters in profession and in usefulness,
take warning from the miscarriages of others, and be so preserved in humility,
circumspection and fear,
as never to exemplify in our conduct the expression of the wise man,
that pride goes before destruction, and an aspiring spirit before a fall.
