== Chapter XIX.

[.chapter-synopsis]
* John Estaugh and Richard Gove taken by a French Privateer in their Passage to Barbados
* Taken into Martinico, and Occurrences there
* Thomas Chalkley visits the Shawanese and Seneca Indians
* William Penn`'s Epistle to the Settlers in Pennsylvania

John Estaugh from Haddenfield, New Jersey, in company with Richard Gove,
embarked at Philadelphia this year,
to pay a religious visit to their friends in Barbados, being arrived near that Island,
the ship was taken and by a French privateer and carried into Martinico:
They were fifteen days in reaching that place, at which the master of the prize,
on board of which these friends were detained, was French so disturbed,
that he said the hand of God was against them;
and his superstitious bigotry attributed the tediousness
of the passage to these two passengers,
because they frequently employed the intermediate time in reading their bibles, which,
therefore, he would sometimes threaten to throw overboard.
The morning after their arrival at Martinico, an officer,
attended by some persons of seeming rank in the island, came on board,
who getting a sight of the certificates which they
had received from their respective monthly meetings,
according to the good order used in this society,
and which one of the company interpreted to the rest,
their friends therein having expressed their desire,
"`that they might be preserved out of the hands of
unreasonable men;`" upon the reading of this passage,
some of them cried out, "`see now the spirit hath deceived you,
for you are not preserved as they would have it.`" One of them answered,
"`the spirit had not deceived them,
that what was mentioned there was the desire of their friends for them,
and that probably there might be some service for them even
there.`" Upon which they continued their humourous raillery,
crying out, "`See now! they are now come to convert the fathers,
we will bring you together and you shall dispute it out.`" But of the fathers, so called,
none came near to them except an old Irish priest,
whose province it seems was to endeavour to convert
the prisoners at 40s. a head for every convert:
The other prisoners wanted him to dispute with the Quakers,
but he evaded it for some time; yet at length entered into discourse with John Estaugh,
whom he found too well furnished with matter for him to make much impression upon.
He called him a heretic, and turned to his companion, who taking his bible,
opened it in the text, beware of false prophets`" Which provoking the priest,
he endeavoured to wrench the bible with violence out of his hands,
not without leaving marks of his violence behind, which ended the dispute;
but the other prisoners determined it plainly in favour of the Quakers,
with whom they said he was not able to dispute.

The French nation in general have appeared more humane and
less bigotted than most others of the Romish communion.
It doth not appear that these friends, while in their hands,
suffered at all upon account of their religion, or that their confinement was very rigid;
they seem to have enjoyed full liberty of holding meetings,
I suppose chiefly with English prisoners.

Before they came to the island, the protestant prisoners there, we may presume,
had no minister to officiate amongst them;
but there was a major in one of the English regiments,
who had been a prisoner there a considerable time,
without being able to obtain his liberty;
probably for want of a prisoner of equal rank in exchange.
He had been engaged in supplying the place of a priest,
by reading prayers two or three times a week to his fellow-prisoners:
But since these friends arrived and held their meetings,
his auditory was considerably decreased, which giving him much uneasiness,
he reprimanded the people sharply for going to the Quakers meetings;
but still their meetings continuing to increase,
he determined at last to enter into a dispute with them.

He began with high charges,
but J. Estaugh replied with a firmness and freedom which provoked the major,
instead of arguments to use unhandsome menaces, which the other disregarding,
continued his argument for the information of the auditors,
with so much prudent coolness and command of his temper,
as conduced to allay the passion of his antagonist; and as he be came moderate,
the controversy grew more satisfactory:
But J. Estaugh appearing better versed in the scriptures than the major,
and quoting some text which the latter had no recollection of,
he conceived an apprehension that the Quakers bibles were not the same with his;
but upon the comparison finding them perfectly to agree,
and that the texts quoted were alike in both, he gave up the contest, grew friendly,
they parted in mutual good-will,
and he treated them with much civility and respect during their stay in that island.

When the cartel for the exchange of prisoners was settled,
none bound to or from Barbados were to receive the benefit thereof.
But Jonas Langford, a friend of Antigua, having requested Colonel Byham,
who went to Martinico for the purpose of exchanging them,
that if any of his friends were there, he would use his interest for their release;
he at his arrival finding these friends, applied to the governor,
and asked it as a favour from him, that the two Quakers, though bound to Barbados,
might go with him to Antigua; "`What, the two apostles,`" said the governor,
(for they had given them that name in Martinico) and he consented.
So they obtained their liberty after a captivity of about two months, in,
which they thought they had as great service as in any other part of their journey,
although they had good satisfaction in Antigua,
where two persons were thoroughly convinced by their ministry.
From Antigua they went by Bermudas to Barbados, and having finished their service there,
returned home.

In this year Thomas Chalkley returning from a visit to friends in Maryland,
and having a concern on his mind to pay a religious visit to the Indians at Conestigo,
laid his concern before the elders of Nottingham meeting,
with which they expressed their unity, and encouraged him to the undertaking.
He was joined by twelve or thirteen more and an interpreter,
who took their journey about fifty miles through the woods,
carrying their provisions along with them.
They were kindly received by the Indians, and upon their application,
for the opportunity of a religious meeting, they called a council,
which they conducted with great gravity,
and in their deliberation expressed their sentiments coolly one after another.
Some of their women being present, T. Chalkley, who was admitted to the council,
inquired of the interpreter, Why they introduced women into their councils?
to which he replied, some women are wiser than some men.
Observing an ancient grave woman who spoke frequently,
it excited his curiosity to make particular inquiry concerning her.
The interpreter informed him that she was an empress,
and a woman of such authority among them,
that they undertook nothing of consequence without consulting her.
That she then said, she looked upon this visit to be of an extraordinary nature,
as the persons were not come to buy or sell or get gain, but in love and regard to them,
from a desire of their well doing both here and hereafter,
and that a meeting among them might be beneficial to their young people.
There were two tribes of them, the Seneca`'s and Shawanese.
They had first a meeting with the Seneca`'s,
who were much affected with what they heard and understood,
and calling the other tribe they interpreted what they had heard to them.
These friends had also another meeting with the Shawanese Indians:
Their visit was gratefully accepted,
and the Indians expressed their desire of more opportunities of the like kind,
which it is hoped divine providence will afford them.
The gospel was preached to them freely, and faith in Christ,
who was put to death by the unbelieving Jews;
and that Jesus is come the second time without sin unto salvation;
and by his grace and light in the soul, showeth to man his sins, convinceth him thereof,
and delivereth him out of them, and giveth inward peace and comfort for well-doing.
To which doctrines they gave a public assent,
but in a particular manner to that of the light in the soul.
They seemed much affected and listened with much seriousness.
The benefit of the holy scriptures was also largely explained and expatiated upon.

In the year 1708,
William Penn visited the settlers with a letter by his new governor Gookin,
of which the following is an extract:

[.embedded-content-document.letter]
--

[.signed-section-context-open]
London, 28th 7mo, 1708.

[.salutation]
Dear Friends and Brethren,

My ancient love, if you can believe it,
reacheth to you as in times past and years that are gone,
even in the divine root and principle of love and life,
that made us near to one another above all worldly considerations, where our life,
I hope is hid with Christ in God our father,
so that when he appears we shall also appear with him in glory,
and in the mean time through us to those that love and wait for his appearance,
as the desire of nations; that we may glorify God his and our everlasting father,
in our bodies, souls and spirits: In temporal and eternal affairs,
being indeed none of our own, for so much as we are our own, we are none of the Lord`'s:
A great mystery, but a great truth, and of absolute necessity to witness,
to be of the number of the chosen nation,
the peculiar people and royal priesthood of Christ and his glorious kingdom.

Oh, my dear friends! let all below this keep on the left hand,
and wait to feel those blessed things to inherit the right hand,
and in faith and courage cry aloud to the Lord for his renewing and refreshing power,
that may revive and reform his work upon our hearts and minds, and our humility,
meekness, patience, self-denial and charity, with a blameless walking,
may plainly appear,
and manifest the work of God upon our hearts to those that are without,
which is not only the way to bring up the loiterers
and gather in the careless ones to their duty,
but fetch home and bring in the strangers, and the very enemies of the blessed truth,
to confess and acknowledge that God is in you and for you of a truth.

In the first love I leave you, committing you and yours,
and all the Lord`'s people amongst you, my own family and affairs,
to the merciful providence and orderings of our great and gracious God,
that welcomed us in poor America, with his excellent love and precious light,
and will I hope once more, and remain your loving faithful friend,

[.signed-section-signature]
William Penn.

[.postscript]
====

Herewith comes your school charter.

====

--
