== Chapter I.

[.chapter-synopsis]
* King George I. ascends the Throne of Great Britain
* Address of the People called Quakers to him
* G. Whitehead`'s speech to the Prince of Wales
* Act for our Affirmation renewed
* Rebellion in Scotland
* Quelled Quakers`' Address upon that Occasion
* Life and Character of Samuel Waldenfield

Immediately after Queen Anne`'s decease, the privy council assembled,
and the Earl of Dorset was appointed to carry to
Hanover the information of the king`'s accession;
who soon after left his German dominions, repaired to England,
and arrived in London the 20th of September.
After his arrival,
having declared in council his firm purpose to maintain
the toleration in favour of protestant dissenters,
whereby they were relieved from the apprehensions they had conceived,
by the measures pursued in the close of the late reign;
many addresses of congratulation were presented to him,
and on the 3rd of October one was sent up from the people called Quakers,
which was delivered by George Whitehead, accompanied by several friends,
who were introduced by Lord Townsend, one of the secretaries of state.
When George Whitehead presenting the address to the King,
he introduced it with this preface, "`We are come in behalf of the people called Quakers,
to present to King George our address and acknowledgment;
may it be favourably received.`" After which Joseph Wyeth read it as followeth:

[.embedded-content-document.address]
--

[.letter-heading]
To George, King of Great Britain, etc.

[.blurb]
=== The humble Address of the people commonly called Quakers.

[.salutation]
Great Prince,

It having pleased Almighty God to deprive these kingdoms of our late gracious Queen,
we do in great humility approach thy royal presence,
with hearts truly thankful to Divine Providence for
thy safe arrival with the prince thy son;
and for thy happy and uninterrupted succession to the crown of these realms, which,
to the universal joy of thy faithful subjects,
hath secured to thy people the protestant succession,
and dissipated the just apprehensions we were under of losing those religious and civil
liberties which were granted to us by law in the reign of King William III.
Whose memory we mention with great gratitude and affection.
We are also in duty obliged,
thankfully to acknowledge thy early and gracious declaration in council,
wherein thou hast, in princely and christian expressions,
manifested thy just sense of the state of thy people,
and which we hope will make all degrees of thy subjects easy.

And as it hath been our known principle to live peaceably under government,
so we hope it will always be our practice, through God`'s assistance,
to approve ourselves, with hearty affection, thy faithful and dutiful subjects.

[.small-break]
'''

May the wonderful counsellor and great preserver
of men guide the king by his divine wisdom,
protect him by his power, give him health and length of days here,
and eternal felicity hereafter.
And so bless his royal offspring,
that they may never fail to adorn the throne with
a successor endowed with piety and virtue.

--

To which the King returned the following Answer:

[quote]
____
I am well satisfied with the marks of duty you express in your address,
and you may be assured of my protection.
____

After the address was read, George Whitehead spoke to this effect:

[quote]
____
Thou art welcome to us, King George, we heartily wish thee health and happiness,
and thy son the prince also.
King William III.
was a happy instrument in putting a stop to persecution, by promoting toleration,
which being intended for the uniting of the king`'s
protestant subjects in interest and affection,
it hath so far that effect, as to make them more kind to one another,
even among the differing persuasions, than they were when persecution was on foot.
We desire the king may have further knowledge of us and our innocence;
and that to live a peaceable and quiet life in all godliness and honesty,
under the king and his government, is according to our principle and practice.
____

When George had thus spoken, his name was asked, which he told;
and having a desire to see the prince,
one of his gentlemen introduced these friends into a chamber, where the prince met them,
to whom George spoke as follows:

[quote]
____

We take it as a favour that we are thus admitted to see the Prince of Wales,
and truly are very glad to see thee;
having delivered our address to the king thy royal father,
and being desirous to give thyself a visit in true love,
we very heartily wish health and happiness to you both;
and that if it should please God thou shouldst survive thy father and come to the throne,
thou mayest enjoy tranquillity and peace.
I am persuaded,
that if the king thy father and thyself do stand for the
toleration for liberty of conscience to be kept inviolable,
God will stand by you.
May king Solomon`'s choice of wisdom be thy choice,
with holy Job`'s integrity and compassion to the oppressed,
and the state of the righteous ruler commended by king David,
viz. "`He that ruleth over men must be just, ruling in the fear of God,
and he shall be as the light of the morning when the sun riseth,
even a morning without rain,
as the tender grass springing out of the earth by clear shining after rain.
____

[.offset]
This speech was favourably received.

In the next year 1715 the term of the act for accepting the solemn
affirmation of the people called Quakers being nearly expired,
a bill was brought into the house of commons on the 7th of third month,
O.S. commonly called May, for renewal thereof,
which was passed by the said house without limitation of time,
and consequently was made perpetual.
In the house of lords an additional clause was inserted,
that the like indulgence should be extended to the northern part of Great Britain,
called Scotland,
and to the plantations belonging to the crown of Great Britain for five years,
and to the end of the next session of parliament.
This amendment was agreed to by the commons,
and received the royal assent the last day of the same month.
But the affirmation was yet continued in the original form,
which many friends still scrupled to avail themselves of,
by reason of their apprehensions that it appeared too near the nature of an oath.

Yet the favourable disposition of the present sovereign
and the present government towards this people,
made deep impressions of gratitude on their minds,
which drew from them the following exhortation in their epistle,
from the yearly meeting held in London about that time:

[.embedded-content-document.epistle]
--

The Lord our God, who for the sake of his heritage,
hath often heretofore rebuked meeting and limited the raging waves of the sea, hath,
blessed be his name, mercifully dispersed the cloud threatening a storm,
which lately seemed to hang over us;
which together with the favour God hath given us in the eyes of the king and the government,
for "` the free enjoyment of our religious and civil liberties,
call for true thankfulness to him.
And humbly to pray to almighty God for the king and those in authority,
for his and their safety and defence, is certainly our christian duty,
as well as to walk inoffensively as a grateful people.

--

The change of ministers and measures in the latter end of
the late reign had created much dissension amongst the people;
and while a cry was raised for the populace to follow, that the Church was in danger,
many began to fear that the protestant succession was in danger,
and the partisans of the late King James flattered themselves with hopes,
that way might be made for the Pretender to obtain the Crown;
but the sudden death of the Queen damped their sanguine expectations;
for the friends to the house of Hanover took their measures so wisely,
that George the First was immediately proclaimed King as already intimated.
Yet notwithstanding his justice and mildness,
the disappointed party retained and fomented discontent,
and endeavoured to disturb his government.
The clamour of the church`'s being in danger was revived; jealousies were excited,
seditious libels dispersed,
and the populace stimulated to riot and hatred of the dissenters, by which means,
when they hoped the number of malcontents was sufficiently increased,
they began to act more openly.^
footnote:[Thomas Story in the course of his travels came
to Oxford on the 28th 3mo (called May) this year,
and gives the following account of a riot in that city,
"`That in the evening a great mob of scholars and others arose,
and gutted (as they called it) the Presbyterian meeting house, that is,
they broke all the windows, doors, benches, wainscots and seats, carrying them away,
and burning and destroying them, which made a great uproar in the city.
{footnote-paragraph-split}
"`Friends having heard that they intended
to use our meeting-house as they had done that of the Presbyterians,
an advertisement thereof was drawn up in writing, directed to the mayor,
and sent by a friend; but the mayor being absent at the time,
it was left with his servant, who promised to give it him as soon as he came:
It contained also a request to the mayor, to protect us against the intended violence,
as the chief civil magistrate of the city; but we received no benefit by our application,
as the sequel proved.
{footnote-paragraph-split}
"`After the meeting we returned to our quarters;
and about nine in the evening, hearing a great noise of the mob at a distance,
we had soon an account that they were using our meeting-house,
as they had done that of the Presbyterians the night before: They broke in by violence,
and took away all the forms and seats that were loose,
and such as were fast round the house they broke;
they took away the doors also off the hinges, and burned them, with part of the wainscot,
in their bonfire: They broke the windows and stanchers,
and the room nest the meeting-house they abused, and defaced,
so that the whole was all ruined and destroyed except the walls and tiling.
Yet all this did not cool their rage for they broke into the dwelling-house
of our ancient friend Thomas Nichol`'s daughter,
who was a widow, where Thomas also was;
and under pretence of searching for a young nobleman, who, they said,
was murdered and hid there,
or somewhere thereabout (though there was no such thing at all,
only they put on this senseless cover for their wickedness).
They broke all the windows, and threw in some hundred weight of stones and dirt,
covering the beds therewith, breaking several things in the rooms,
making great destruction and shedding some blood.
From thence they went to the Baptist meeting-house, and destroyed it in like manner;
and as they came up the street from that piece of mischief,
I lodging with young Thomas Nichols, we expected the same usage as the widow, his sister,
had met with, and therefore got for safety into the stair-case, he,
his wife and little children, my companion and I,
and there sat out of the way of the stones: and as they came up to the house,
they let fly their volley, broke all the windows,
and passed on without doing any more harm: But this I observed,
that as Satan raged in them before they came,
blowing them up into a temper fit for the action,
Truth in our minds filled us with divine love and consolation,
so that we were without any fear or amazement of what they could do farther.
By the time all was over, it was about two in the morning;
and there came in some of the sober neighbours,
who gave us some of the mob`'s unreasonable reasons for their violence and outrage,
as they had collected them, in discoursing with some of them.
They said that some of the low party, on the seventh day afternoon,
being at a tavern in town, there drank healths and confusions;
and talked of burning the late Queen`'s picture and Sacheverel`'s, and in revenge of this,
they gutted the Presbyterian meeting-house,
and their pretence for using us in the fame manner was,
because we voted for the low members of the present parliament.`"
{footnote-paragraph-split}
I
have no doubt but rumours of this kind might be circulated
by the contrivers and instigators of this tumult;
but it seems to be principally intended,
as an act of celebrating the festival of the Restoration, it being on the 29th of 3mo,
O+++.+++ S. called May, and also the first day of the week, on which day,
considering the temper of the time (of which this riot is
but one specimen) and the spirit of many of the public teachers,
and the usual topics insisted on in their discourses on this day,
it is rather more than probable, their sermons had no tendency to allay this ferment,
but the contrary.
Thomas Story proceeds, "`We went the next morning to view the ruins of our meeting-house,
and our friend Nichols`'s; and as we were at the former, I stood upon a small eminence,
and looking over the ruins (many scholars and other
people being there) I said pretty loudly,
so that all might hear, can these be the effects of religion and learning!
Upon which several of the scholars hung down their heads; but none answered.
Then Thomas Nichols, the younger, made a short speech, but very close,
reminding them of Sodom and Gomorrah,
that it was the same spirit that now wrought in them,
which brought destruction on those cities: To which they replied, it was the mob,
and it was ill done; but some others said, they themselves were that mob,
and would be met with one day.`"]

This spirit of turbulence and disaffection soon broke out into open rebellion in Scotland,
and the national discontent was, by his partisans, so exaggerated to the Pretender,
as to induce him to make preparations to put himself at the head of the insurgents,
in which he was privately assisted by Lewis XIV.
King of France, who dying about this time,
the rebellion lost its support from that kingdom.
The Duke of Orleans being appointed Regent during the young king`'s minority,
had entered into engagements with king George,
and is supposed to have rather contributed to defeat than to promote it.
However, the Pretender at last The Pretender landed in Scotland and was crowned there

But previously to his arrival, one party of the rebels having entered England,
and advanced to Preston in Lancashire, were there besieged, defeated and taken prisoners;
and the same day their main body under the command of the Earl of Marr, met with a check,
where by they were dispersed.
The Pretender`'s expectation thus failing,
and finding no probability of drawing together an army sufficient
to withstand the forces advancing against him.
he sought security in a speedy retreat to France, which put an end to the rebellion.

This rebellion, thus successfully exterminated,
brought many addresses of congratulation to the king,
and among the rest the people called Quakers drew up an address from their yearly meeting,
which they presented to the king on the last day of the third month, O. S. called May,
this year; being introduced by the Earl of Manchester,
G+++.+++ Whitehead spoke in substance as followeth:

[quote]
____
That in the annual assembly held for the religious concerns of their society,
endeavouring to promote and put in practice the duties of religion professed by them,
the sense of the great deliverance had such a weight upon their minds,
that they were willing to express it in an address to King George,
whom God by his providence had brought hither and preserved, so that he could well say,
he was George by the grace of God, King of Great Britain, etc.
And that as men carried that saying stamped on the money in their pockets,
so it was to be wished it might be imprinted in the hearts of the subjects.
____

Hereupon the address was presented and read as follows:

[.embedded-content-document.address]
--

[.letter-heading]
To George, King of Great Britain, etc.

[.blurb]
=== The humble Address of the People called Quakers, from their yearly Meeting in London, the 26th day of the third month, called May 1716.

[.salutation]
May it please the King,

We thy faithful and peaceable subjects, Quakers being met in this our annual assembly,
do hold ourselves obliged, in point of principle and gratitude,
rather than by formal and frequent addresses,
humbly and openly to acknowledge the manifold blessings and kind providence of God,
which have attended these kingdoms ever since thy happy accession to the throne.

And as our religion effectually enjoins us, obedience to the supreme authority,
so it is with great satisfaction we pay it to a prince, whose justice,
clemency and moderation cannot but endear,
and firmly unite the hearts and affections of all his true protestant subjects.

We are therefore sorrowfully affected with the unhappiness of those our countrymen,
who have so little gratitude or goodness as to be uneasy under so just and mild an administration;
nor can we reflect on the late unjust and unnatural rebellion,
without concluding the promoters and actors thereof were spirit as would lay waste and
destroy both the civil and religious liberties of these protestant nations.

And as God, the Lord of Hosts,
hath most signally appeared to the confounding that black conspiracy;
so we pray his good providence may always attend the King`'s councils and undertakings,
to the establishing his throne in righteousness and peace,
and making his house a sure house.

Permit us therefore, great Prince,
to lay hold of this opportunity to approach thy royal prefence,
with our hearty thanks to the king and great council
for all the privileges and liberties we enjoy.
To behold a prince upon the throne,
solicitous for the ease and happiness of his people beyond any other views,
so heightens our satisfaction and joy,
that we want words to express our full sense thereof.
And therefore we can do no less than assure the king,
that as it is our duty to demean ourselves towards the king`'s
person and government with all faithful obedience,
so we are determined, by divine assistance,
devoutly and heartily to pray the God and Father of all our mercies,
to vouchsafe to the king a long, peaceable and prosperous reign;
and that when it shall please the Almighty to remove from us so precious a life,
by taking it to himself,
there may not want a branch of thy royal family
endowed with wisdom and virtue to fill the throne,
till time shall be no more.

--

To which address the King returned the following answer,

[quote]
____
I thank you for the assurance of duty and affection to my person and government,
contained in this address; and you may always depend upon my protection.
____

This year died Samuel Waldensield, a member and minister of this society,
highly esteemed for his virtuous conversation and his religious services,
both in the city of London and its neighbourhood,
and other parts where he was well known.
He was born about the year 1652 at Edmundsbury in Suffolk;
was religiously inclined from his youth, and for some time a hearer of the independents.

He was convinced of the principles of the people called Quakers,
by the powerful ministry of Giles Barnadiston,
and received the truth in the love thereof;
as he became obedient to the grace of God to which he was recommended,
he was instructed and enabled thereby to lead a sober and godly life,
and to possess his earthly tabernacle in sanctification and honour.

About the year 1672 he was called to the work of the ministry,
in the discharge whereof he was zealous and indefatigable.
He travelled in this service in England, Scotland, Ireland and Germany,
by an account he kept, near 40,000 miles to the year 1703,
and considerably from that time to his death; and his lively ministry,
through the divine blessing prospering his labours,
was made effectual to the convincement of many,
and turning them from darkness unto light, who were as seals to the efficacy thereof.

In the year 1684 he married and settled in London,
and continued faithful and diligent in the work to which he was called, when at liberty;
for although by the time he became a resident in
London and eminent for service in the society,
persecution was abated, he did not escape a share in the sufferings of the season.
At the sessions held at the Old Baily in the 10th month 1683, he,
in company of sundry others, who, with him,
had been taken from a peaceable meeting in White-hart-court, was tried for a riot,
and by a jury of this age,
when juries were modelled to the temper and influence of the bench, was, with the rest,
brought in guilty, fined 5£. and committed to prison for non-payment.
A prosecution was also commenced against him on the statute 23 Eliz.
for 20£. a month for absence from the established worship in the year 1686;
but by King James`'s order to the Attorney General,
a stop was put to that prosecution and others of the kind, as before related.^
footnote:[See vol.
3, p. 167.]

After this he continued frequent in his travels abroad,
in religious visits to his friends in most of the counties of England,
and more frequently in the eastern parts.
Being clear in expression, animated with lively zeal,
and reaching the witness in the consciences of friends and others,
his ministry was very acceptable and edifying, by means whereof, and of his solid,
circumspect and exemplary conversation, adorning and confirming it,
he obtained the esteem of his friends abroad and at home.

In or about the year 1706, declining in health,
he removed his residence from the city of London to Bush-hill in Middlesex;
yet when the state of his health admitted,
he continued his travels and his assistance with friends of the city,
in their service for the relief of their suffering friends,
and when disengaged from such services,
he was exemplary in a constant attendance of the meetings adjacent to him.

He was eminently serviceable in the discipline of the society,
as well as in his public ministry,
having a zealous concern on his mind for the preservation
of friends in a consistency with their profession,
that the testimony of truth might be kept up in all the branches thereof;
that pride and libertinism in principle and practice might be discouraged and suppressed:
That those who act as rulers in the church, should be men of truth,
fearing God and hating covetousness;
and that all the members of the society might be careful to maintain
justice and truth in all their dealings amongst men.

His circumspect conduct adorned his profession of religion,
and acquired reputation to the society of which he was a member, so that many,
who through prejudice, had entertained an unfavourable and contemptuous opinion of it,
by their acquaintance and conversation with him,
were brought to change their sentiments concerning it.

He was confined about two months before his decease,
and although his pain was often great, he was supported with remarkable patience,
and was frequently very cheerful, though his end drew near;
for death was no terror to him, the sting thereof being taken away,
having the comfortable evidence,
that he had through life been mindful of his final change,
and ordered his conversation with a view to make it a transition to everlasting felicity.
So that in the retrospection of his past time he could say, as he did in much tenderness,
"`I have done the work of my day; I feel peace of conscience; I have wronged no man;
I have received a great deal of wrong and injury, but I forgive all,
and I desire the Lord to forgive them also.
I die in charity with all the world.`"
Another time he said, "`I have endeavoured to live inoffensively towards God and Man.
And now I have no occasion to repent that I have endeavoured to live well;
and as I have nothing to boast of I have no occasion to complain.
All is well.`"

Many other lively expressions and weighty exhortations he uttered,
very affecting and edifying to those to whom they were addressed.
He continued in a serene composed frame of mind to the last,
and died in great peace the 7th of the 8th month 1715, and left a good report behind him:
And being greatly beloved, and much respected by people of divers professions,
his funeral had a numerous attendance from Devonshire-house meeting place,
to the burial ground at Bunhillfields.
