== Chapter II.

[.chapter-synopsis]
* Affirmation Act renewed
* Measures of Government to moderate party beats
* Bishop Hoadly`'s two Sermons and proceedings thereupon
* Repeal of Occasional Conformity and Schism Acts
* South Sea Scheme
* Petition to Parliament for a form of Affirmation which might be easy to all Friends
* Solicitations to procure the passing of an act for that purpose
* Passed by the Commons
* Warmly debated in the House of Lords
* Petition against it
* Passed by the Lords
* Yearly Meeting`'s acknowledgment of the favour
* Epistle of Caution concerning the use thereof
* Account of George Whitehead
* Case of some Friends in New England appointed to assess Taxes
* Death of King George I

The passing of the Act of Toleration,
and the effectual establishment thereof under the
legal rule of the Princes of the Hanoverian line,
having exempted the people called Quakers of this age from most of the
grievous sufferings to which those of the preceding age were exposed;
and having thereby obtained a settlement in quietude,
their affairs furnish fewer materials for history than heretofore:
yet there still remained some subjects of suffering
from which the Toleration did not exempt them,
particularly their scruple to pay tithes and other ecclesiastical demands.
And although the legislature had in some degree endeavoured
to give them ease in respect to swearing,
yet the form of affirmation prescribed by the first affirmation-act,
and continued in the succeeding acts, as before observed,
was so uneasy to a considerable part of the society,
that they had not freedom to make use thereof,
and therefore submitted to the attendant inconveniences,
rather than wound the peace of their own minds.

In 1715 the act for accepting the solemn affirmation
was renewed without limitation of time;
although the yearly meeting directed an application to be made to parliament,
to grant the society a form of affirmation which might be easy to all friends,
the temper of the time did not yet favour such a concession:
An opportunity for further relief did not occur till the year 1721.
In the intermediate time,
the king (and the rulers under him) perceiving the disaffection of the
party distinguished by the denomination of high-church and tories,
and their propensity to stir up those riots and tumults which had,
since the beginning of his reign, been nourished and fomented to perplex his government,
disturb the public peace,
and finally terminated in the late rebellion in favour of a popish pretender:
And after it was quelled,
their endeavours being still exerted to keep alive a spirit of discontent,
it was judged necessary to clip the wings of the high-flying ecclesiastics in particular,
by imitating the party heat, the judicious conduct of the late King William,
in selecting the most temperate and dispassionate men amongst
them to fill the dignities and highest stations in the church;
who being men of moderation themselves,
might be instrumental to diffuse a spirit of greater moderation among the inferior orders,
than they had hitherto manifested;
or to discountenance and check the violence of their
disposition to revive and keep alive party heats.

One of these exerted his talents for this purpose in a particular manner.
Benjamin Hoadly bishop of Bangor, a man of liberal sentiments, a clear head,
and sound understanding, had published thereupon, two performances,
which had given great offence to his brethren the clergy;
especially those who were jealous of every prerogative
to which they advanced their groundless claims.
One was entitled, _A Preservative Against the Principles and Practices of the Nonjurors._
The other was a sermon preached before the King at the chapel royal,
under the title of _The Nature of the Kingdom of Christ,_ in which, I have understood,
the two principal points insisted upon are, that the ministers of the gospel, as such,
have no authority to busy themselves in secular government;
nor the magistrate to punish men for matters of religion, which,
although considered dispassionately, are almost self-evident propositions;
yet at this time, when the people`'s passions were more consulted than their reason,
and violently heated in favour of high-church,
these discourses roused the whole host of high-priests
to combat propositions the most reasonable,
which they imagined had a tendency to expose the illegality of their claims.
The lower house of convocation, when they met,
took up the matter with marks of great offence and resentment,
and appointed a committee of six of their members to examine the Bishop`'s publications,
who drew up a representation, in which the Preservative and Sermon were censured,
as "`tending to subvert all government and discipline in the church of Christ;
to reduce his kingdom to a state of anarchy and confusion;
to impugn and impeach the royal supremacy in causes ecclesiastical,
and the authority of the legislature,
to enforce obedience in matters of religion by civil sanctions`" How far their indignation
against this liberal prelate and his rational doctrine might have carried them,
they were deprived of the power of discovering;
for the king and his ministers seem to have conceived a
more favourable opinion of the Bishop and his performances,
and therefore rescued him out of their hands,
by an immediate prorogation of the convocation,
which hath not been permitted to sit and do business since that period.

This inflamed the controversy;
but the bishop being now upon equal terms with his antagonists, who were a numerous body,
and having truth and reason on his side,
ably defended himself and his doctrine against them all, with manifest advantage.
This controversy, wisely conducted on his part, tended to open the eyes of many people,
to see the invalidity of clerical claims to unauthorized dominion and power,
and proved a very seasonable antidote to that spirit of tumult and intemperate riot,
which, through their instigation,
had long infected the injudicious rabble and others
to public disorder and private injury.

In the succeeding year the high-churchmen met with another mortification,
by the repeal of the act against occasional conformity and the growth of schism,
which two acts they had procured during their predominance
in the latter end of Queen Anne`'s reign,
which the bishop of Bangor (in the debate) considered in effect "`persecuting laws,
because,
by admitting the principle of self-preservation and self-defence in matters of religion,
all the persecutions maintained by the heathens against the professors of Christianity,
and even the popish inquisition might be justified.
With respect to the power, of which so many clergymen appeared to be so fond and zealous,
he owned, the desire of power and riches was natural to all men; but that he had learned,
both from reason and from the gospel, that this must be kept within due bounds,
and not entrench upon the rights and liberties of their fellow creatures and countrymen.`"
This bill of repeal met with great opposition from the high party in both houses,
but at last was passed.

These transactions tended to lessen the power and
influence of the high clergy and their partisans:
And to leave the king at liberty to follow the impulse of his liberality and benevolence,
in securing to all his subjects their natural rights of civil and religious liberty,
which encouraged the people called Quakers to hope
for the favourable opportunity they waited for,
to procure a solemn affirmation in that simplicity of form,
which might afford them universal relief.

In this year died at his seat at Rushcomb near Twyford in Buckinghamshire,
William Penn, proprietor of Pennsylvania;
he had been for some years in a declining state.
So long before as the year 1712, he had three successive fits, supposed to be apoplectic,
by the last of which (although beyond all probability of expectation
he survived it) his understanding and memory were very much impaired,
so as to render him incapable of public action for the future.
And notwithstanding the intermission of his intellectual faculties,
and the progressive failure of his memory,
his love to religion and sense of religious enjoyments apparently continued with him;
for he often went in his chariot to the meeting at Reading,
and there sometimes uttered short, but very sound and savoury expressions.
One morning preparing to go to meeting, he expressed his desire to the Lord,
that they might receive some good from him:
And though he continued declining from year to year in his memory and understanding,
he still expressed himself sensibly at times.
In the year 1716 some of his friends, who came to visit him, taking their leave, he said,
"`My love is with you, the Lord preserve you,
and remember me in the everlasting covenant!`" Thus, in the absence of his mental powers,
and in his evening repose,
his piety and innocence of heart were still discernible
as the predominating qualities in him.

After a continued and gradual declension for about six years,
his body drew near to its dissolution, and on the 30th day of the fifth month 1718,
in the 74th year of his age, his soul, prepared for a more glorious habitation,
forsook the decayed tabernacle, which was interred the 5th of the sixth month following,
at Jordans in Buckinghamshire.

For if a life of pure religion exerted actively in a constant
tenour of beneficence and good will to men,
faithfully discharging his relative duties, religious, moral,
and political in every station of life;
and passively in patient acquiescence in the divine will,
and the testimony of a good conscience,
in all his trials and sufferings (of which he had his share)
a simple reliance on divine support under them,
and on divine protection and power to work his deliverance,
can recommend to the favour of God: If fighting the good fight of faith,
and therein being made conquerors and more than conquerors
over all our spiritual enemies through him that loved us,
entitle, in any wise to the crown of righteousness,
can we doubt his being made a partaker of the promise of Christ; Rev. 3:21.
"`To him that overcometh, will I grant to sit with me in my throne,
as I also overcame and am set down with my father in his throne.`"
The account of his containment and early troubles therein,
and the outlines of his principal transactions in life have been described in course.
To expatiate on the eminence of his character seems superfluous,
the excellency thereof being well known and generally admitted.
His writings (comprised in two volumes folio) are
a standing evidence of a clear head and a good heart;
the institutions of his province, of the depth of his understanding;
and the undeviating integrity of his life, of the purity of his mind:
and all his qualifications, natural and acquired,
applied to promote the interests of religion and virtue,
establish his character on a basis firmer than written panegyrics.

The parliament being taken up with various matters of public importance,
particularly in 1720,
the investigation of the fraudulent practice in the south sea scheme,^
footnote:[An historian remarks upon this era to this purport,
"`The avarice of the times had increased with the riches and the luxury of the nation.
Commerce introduced fraud, and wealth introduced prodigality; and religion,
which might in some measure put a stop to these evils, was too little regarded.
The whole nation was infected with a spirit of avaricious enterprise.`"
Goldsmith.
{footnote-paragraph-split}
{footnote-paragraph-split}
The people called
Quakers endeavoured to guard their members from the contagion,
by the following cautionary advice, in the Epistle from their Yearly Meeting, 1720.
"`As our Lord and Saviour Jesus Christ exhorted to take heed and beware of covetousness,
(which is idolatry) we are concerned,
that all professing Christianity among us may take heed of pride, covetousness,
and hastening to be rich in this world, which are pernicious, growing evils;
let them be watched against, resisted and suppressed,
in the fear and dread of Almighty God, and have no place or countenance in the church.
O! ye grave elders, both men and women, pray be careful and watchful against these evils,
and over the flock in these cases.`"
And in the Epistle of 1721,
"`Whereas friends were weightily concerned to advise and caution,
in the last yearly Epistle, all professing with us, to "` take heed of pride,
covetousness, and hastening to be rich, as pernicious and growing evils;
which advice having not been duly regarded by some,
they have been unwarily drawn into such things as
have tended not only to the dishonour of God,
but also their own loss and sorrow.
We therefore find ourselves now again concerned,
earnestly to press all friends to be diligent in the observation thereof:
and to entreat that such, who may have been so misled, may come to a due sense of it,
and sincerely repent.
{footnote-paragraph-split}
"`And whereas, in our Epistle of 1719,
we did earnestly caution against defrauding the king of his customs, duties, or excise,
or encouraging such clandestine practices,
by buying goods reasonably suspected to be run;
in which advice this meeting having in that epistle been very particular,
doth refer thereunto, and press the same again;
and that friends do honestly and cheerfully pay their tributes to the government,
under which they enjoy protection.
And as we warn against the injustice aforesaid,
so likewise against all the provoking sins of this age,
which draw down the heavy judgments of God.`"]
and relieving the sufferers thereby,
the favourable opportunity the people called Quakers were waiting for,
to procure a law for such form of affirmation,
as might be more universally easy to their members, did not occur till the next year,
when being encouraged with hopes of success,
they took such previous steps as appeared to them expedient to
facilitate the progress and passing of an act for that purpose.
The first was an application of Joseph Wyeth, in a letter to the king,
which it is supposed was of good service to the cause,
as he was well known and well respected by the king,
whose countenance to the application was doubtless greatly contributory to its success.

The next was a petition to parliament as followeth:

[.embedded-content-document.address]
--

[.blurb]
=== The humble petition of the People called Quakers, on behalf of such of their friends who scruple the present form of affirmation,

[.salutation]
Showeth,

That they humbly beg, thankfully to remember, that the first legal privileges which,
as a people they were favoured with, were granted in the reign of King William III.
of happy memory, amongst which privileges was,
that their solemn affirmation should in certain cases be accepted instead of an oath,
which being made perpetual in the first year of our present gracious sovereign,
they now most gratefully acknowledge: That they also beg leave to observe,
that many of their friends do conscientiously scruple the present form of solemn affirmation,
whereby they have fallen under great sufferings by imprisonment or loss in their property,
they being not able to answer in courts of equity, take probates of wills,
prove debts on commission of bankruptcies,
verify their entries on the leather or candle act,
take up their freedoms in corporations, be admitted to their polls on their freeholds,
give evidence on behalf of others not of their persuasion,
declare their fidelity to the present government,
or take the effect of the abjuration as by law required,
all which they humbly conceive are hardships which
by these acts were intended to be removed and prevented.

The petitioners therefore most humbly pray, that leave be given,
to bring in a bill for such form of affirmation or declaration as may remove these difficulties,
which many of them lie under, or such other relief as you in your wisdom shall see meet.
And your petitioners shall pray.

--

The above petition was signed by one hundred and thirty two friends.

Besides these applications,
others were made by particular friends to such members of both houses, I presume,
as they were acquainted with, had influence upon, or were apprehended to be friendly.
Thomas Story, in particular, applied to the Earl of Carlisle,
who readily promised his interest and influence, and desired his son,
stiled the Lord Morpeth, to do the same in the house of commons,
of which he was a member.
He advised Thomas to make his first application to the Earl of Sunderland,
secretary of state, and procured him an opportunity of speaking to him.
Thomas informed him, "`that though the king, his ministry,
and the parliament intended the people called Quakers
a great favour in perpetuating the affirmation act,
as it then stood, yet it did not answer the end proposed;
for a great part of that people could not comply with it, the terms,
in their apprehension, importing a difference from the doctrine of Christ.`"

He then produced the form of the act, and also that which the meeting had agreed to,
which, when the Earl of Sunderland had perused, he said,
"`You might have had the latter as soon as the former if you had applied for it;
for what we did was to serve you in your own way; and you yourselves soliciting for it,
we thought we had fully gratified you;
and were informed that a very few of you were dissatisfied with that form,
and those a sect among you,
misled by Mr. Penn in disloyalty to the government and in favour to the Pretender,
and who did not desire it of the present government, hoping for it by another in time;
and those who were satisfied with that form were Mr. Mead`'s friends,
and principled for the revolution and present government in the house of Hanover;
and one sort called Pennites and the other Meadites.`"^
footnote:[Remarks of the like kind were formerly made by King William upon the personal
application of some friends to him in relation to their suffering for tithes,
and preparing the way for the first Affirmation Act.
Whereby we may observe how Princes are frequently imposed upon,
and subjects misrepresented, frequently unknown to them,
where they have no opportunity to vindicate themselves.
The King in the course of their conversation, remarked,
"`You are a divided people and some of you disaffected to
the government.`" To which George Whitehead and others replied,
"`As we are a people we are not divided, but in union.
Although some have separated from us, and therefore are not of us,
most of these were some disorderly persons,
who were therefore denied by us.`" To the latter charge George Whitehead replied,
"`Tis an hard matter for us to enter into the private
affections of persons without some overt act;
whereby we do not know that any of our friends have
manifested any disaffection to the government;
for if we did certainly know, that any of these in communion with us,
should in word or deed show any disaffection to the present government,
we should certainly disown them therein, and give testimony against them.
`'Tis true we have been aspersed and misrepresented
with such nicknames as Meadites and Pennites,
as if we set up sect-masters among us, yet we own no such thing,
but Christ Jesus to be our only Master,
as we are a christian society and people.`" The King appeared serious and well satisfied,
and befriended them in their applications for relief in both cases.]

To this Thomas Story replied, "`This is only a calumny artfully invented to defame our society,
and render the more distressed suspected by the king and government,
that we might receive no relief; and it is a great cruelty and hardship.
I do not know or ever heard of any such sect, party or parties among us,
so attached to William Penn or William Mead, or any other person;
for we are not a people subject to be led by sect-masters,
but to follow God and Christ only in matters of religion; and as such,
the denying of all oaths we believe to be a part of our duty.
And as to those who are among us, who cannot comply with the present affirmation,
I know they are as loyal to king George, and as true to his government,
as any of his subjects in all his dominions;
for I have lately been amongst them in a general way.
And the Earl of Carlisle himself likewise knows, that many of our friends,
whom he hath relieved by his interest,
who had suffered much for non-compliance with the affirmation,
were as loyal as any others.`"

The result of this conference was such as gave the friends good hope of success,
as they had reason to believe the Earl of Sunderland would
be their friend in their application to parliament.

Further applications were made to the duke of Somerset, the bishops of Canterbury, York,
and Carlisle, who all behaved courteously;
but the archbishop of York signified he could not befriend them in that case.
It looks by these applications,
as if the greatest opposition was expected in the house of peers.

The aforesaid petition being delivered,
the house of commons complied with the request thereof;
but it produced a warm debate in the house of peers.
Several of the bishops, who by their opposition, exceptions and amendments,
contrived to form the affirmation into the substance of an oath in their own opinions,
as was confessed by some of themselves,
and laid the house of foundation for the present application,
exerted their endeavours to prevent the success thereof.
Atterbury, bishop of Rochester, a man of great parts and great learning, but ambitious,
factious and turbulent both in church and state; the champion of the high church party,
and a determined foe to the dissenting interest,
reflected upon the people called Quakers upon this occasion with his accustomed acrimony,
saying, "`he did not know,
why such a distinguishing mark of indulgence should
be allowed to a set of people who were hardy christians.
He was seconded by the Earl of Stafford, Lords North and Grey,
and the Archbishop of York; these were opposed by the Earl of Sunderland,
the Duke of Argyle, White Kennet Bishop of Peterborough, the Earl of Hay,
and the Earl of Macklesfield; and the question being put for committing the bill,
it was carried in the affirmative by sixty-four against fourteen.
On the 17th, 11mo O. S. commonly called January,
the lords were to go into a grand committee on the bill,
but were prevented by an unexpected petition from some of the London clergy,
which was presented by the Archbishop of York, and was as follows:

[.embedded-content-document.letter]
--

[.letter-heading]
To the right honourable the Lords Spiritual and Temporal in Parliament assembled.

[.centered.emphasized]
The humble petition^
footnote:[That this petition was looked upon in an unfavourable light,
and as procured to serve a purpose, by many of the peers,
is manifest from the conference, which Thomas Story relates,
he had with the Duke of Somerset on the day the bill was passed.
Thomas Story informed him, that as he came,
he heard both universities intended to petition against the bill,
as the clergy in and about London had already done,
which might occasion much trouble and delay.
The Duke replied, "`perhaps Oxford may attempt something that way,
being influenced by the Bishop of York, Chester, Rochester, and the rest of that sort;
but if they should, they are obnoxious.
As to Cambridge they have done nothing,
there are a set of fellows calling themselves the clergy in and about London,
who have sent in a petition,
wherein they pretend to blame both houses of parliament for encouraging a sect,
which they rank with Turks, Jews and other Infidels;
as if we were to be imposed upon by them, and receive their dictates,
or knew not what to do without their directions: Besides we do not know who they are;
for there are five hundred of the clergy in and about London,
and we find only forty-one names to their petition, and these very obscure.`"]
of the Clergy in and about London, with all submission,

[.salutation]
Showeth,

That there is a bill now depending in your Lordships house, entitled,
_An Act for Granting the People Called Quakers, Such a Form of Affirmation or Declaration,
as May Remove the Difficulties, Which Many of Them Labour Under._
Which bill, should it pass into a law,
as it may in its consequences nearly affect the property of the subject in general,
so it will in a more especial manner,
endanger the legal maintenance of the clergy by tithes;
inasmuch as the people called Quakers pretend to
deny the payment upon a principle of conscience;
and therefore as your petitioners apprehend,
may be under strong inducements to ease their consciences in that respect,
by violating them in another, when their simple affirmation in behalf of friends,
of the same persuasion shall pass in all courts of judicature for legal evidence.

However, the injuries that your petitioners in their private affairs may possibly suffer,
are, as they ought to be, of small account with them,
in comparison of the mischiefs which may redound to society from the indulgence intended,
as it seems to imply, that justice may be duly administered, and government supported,
without the intervention of a solemn appeal to God,
as a witness of the truth of what is said, by all persons, in all cases,
of great importance to the common welfare; whereas your petitioners are firmly persuaded,
that an oath was instituted by God himself, as the surest bond of fidelity among men,
and hath been esteemed, and found to be so,
by the wisdom and experience of all ages and all nations.

But that which chiefly moves your petitioners to apply to your lordships,
is their serious concern, lest the minds of good men should be grieved and wounded,
and the enemies of Christianity triumph, when they shall see such condescension made,
by a christian legislature,
to a set of men who renounce the divine institution of Christ,
particularly that by which the faithful are initiated into his religion,
and denominated christians; and who cannot, on this account,
according to the uniform judgment and practice of the catholic church,
be deemed worthy of that sacred name.

Your petitioners moreover crave leave to represent to your Lordships, that,
upon the best information they can get,
the instances wherein any Quaker hath refused the solemn affirmation,
prescribed by an act in the seventh and the eighth year of William III.
have, from the passing of that act to this day, been exceeding rare;
so that there might be ground to hope,
that the continued use of the said solemn affirmation would, by degrees,
have entirely cured that people of all those unreasonable prejudices against an oath,
which the favour designed them by this bill may tend to strengthen and confirm.

And your petitioners humbly leave it to your lordships wise deliberations,
whether such an extraordinary indulgence granted to a people already, as is conceived,
too numerous, may not contribute to multiply their sect,
and tempt persons to profess themselves Quakers,
in order to be exempted from the obligation of oaths,
and to stand upon a foot of privilege not allowed to the best christians in the kingdom.
Your petitioners therefore humbly hope,
that these and other considerations which may offer
themselves to your lordships great wisdom,
may induce your lordships not to give your consent
to the passing of this bill into a law,

[.signed-section-closing]
And your petitioners shall ever pray, etc.

--

The archbishop of York spoke in behalf of this petition, and moved that it might be read;
and he was seconded by several bishops and noblemen.
However, the petition was branded as a seditious libel, and rejected by the majority.
On the 18th 11mo. O. S. called January, the lords went into a committee on the bill,
and after reading the first clause, the archbishop of Canterbury moved,
that the Quakers affirmation might not be allowed in courts of judicature,
but among themselves; and the archbishop of York moved for a clause,
that the Quakers affirmation should not go in any suit at law for tithes;
but after some debate, the question being put thereupon,
was carried in the negative by fifty-two voices against twenty-one;
and the question being put in the house, whether the bill should pass,
it was resolved in the affirmative.

By this bill the affirmation was established in this simple form, "`I, A.B. do solemnly,
sincerely,
and truly declare and affirm,`" whereby ease and relief was extended
universally to the members of this society in respect to oaths,
and to the inconveniences and losses in their commercial engagements, to which,
on many occasions they were liable,
through their incapacity to give a legal testimony
without injuring the peace of their own consciences;
for which favour they were thankful, in the first place, to that divine Being,
who turneth the hearts of Kings and Princes; and next,
to the king and his ministers for their particular favour,
as expressed in the epistle from their next yearly meeting 1722, as follows:

[.embedded-content-document.epistle]
--

We acknowledge the goodness of God, in disposing the legislature to grant us,
the last session of parliament, such form of affirmation, as, by accounts received,
we find very satisfactory to all the brethren; for which we are truly thankful to God,
and those in authority.
And as we are well satisfied with the care of friends in London,
in their addressing the king thereupon,
and thankful for his excellent and favourable answer,
so also with their care in writing and dispersing
the late epistle of caution concerning the use thereof.
Which good advice this meeting recommends with the greatest eagerness,
that there be no other than an honest and conscientious
use made of this farther indulgence granted us.

--

Of the Epistle referred to in the foregoing paragraph, this is a copy:

[.embedded-content-document.epistle]
--

[.blurb]
=== An Epistle of caution to friends in general, Epistle of relating to the solemn affirmation, from a meeting held in London the 2nd of the first month, January, 1721-2.

[.salutation]
Dear Friends and Brethren,

This meeting, under a weighty sense of the great favour,
which it hath pleased the Lord to incline the heart of the
king and those in the government to grant us,
by passing into a law a form of solemn affirmation,
which will remove the conscientious scruples many friends lay under
(and thereby enable all to follow their lawful occupations,
trades and concerns,
without lett or hindrance on any account) doth find
a concern to recommend to all friends in their quarterly,
monthly, and particular meetings, where this law doth or may extend.

That they in an especial manner have a watchful eye and oversight of their several members,
that this great favour be not abused or misused by any professing truth with us.
Our blessed Lord and Saviour Jesus Christ told his disciples,
Ye are the light of the world, a city set on a hill cannot be hid.
And in every age, as many as do walk in obedience to his gospel, must unavoidably be so:
the daily cross and self-denial,
which he doth enjoin (those sure tokens of a christian
discipline) are public marks easily seen,
and readily observed by those with whom we have occasion of business or converse,
and our transacting hereof with uprightness, justice and moderation,
will show that we have an awful regard to our Lord Jesus Christ,
whom we acknowledge and declare to be our great lawgiver and example.

The great end and design of the new covenant, grace and truth, which is come by him,
is to draw men into obedience to his law written in the heart,
by which only the inside can be made clean, and according:
to the degrees of obedience to this divine law,
which the apostle calls the law of the spirit of life in Christ Jesus,
the proper effect thereof will appear, that is, the outside will be clean also.
Hereby truth, justice, righteousness and charity,
will shine forth in the words and actions of such,
and then may truly be applied to them the saying of Christ,
a city that is set upon a hill cannot be hid.

Beside the inward engagements of this divine law, to speak and act according to truth,
there is at this time also an outward engagement, which the government hath laid upon us,
not only by the favour of this act,
but also by the manner wherein they have confirmed it.
For in the preamble it is said-- It is evident that the said people called
Quakers have not abused the liberty and indulgence allowed them by law.

Which testimony of the legislature concerning the use of the late solemn affirmation,
upon twenty-five years experience,
ought at least to stir up all friends to great watchfulness and care,
in the use of this further ease and relief, that this testimony may be continued,
and thereby confirm the government in their favourable sentiments concerning us.

And seeing this signal indulgence may draw the eyes
and observations of many people upon us,
it may be expected among these, some will look on us with an evil eye,
watch for our halting;
and seek occasion against us upon any misuse or abuse of this legal privilege,
which any professing truth with us, or but bearing the name, should fall into,
or commit.

First, therefore, that there be no misuse of this favour,
we do earnestly desire and entreat,
that the several meetings do advise and exhort friends that they
watch against all vexatious and trifling causes of differences,
and not for any such cause implead or commence suits of
law upon the encouragement of this solemn affirmation,
for that would certainly be a perverting the good design of the government,
in granting thereof, and must be deemed a great misuse of this privilege.

Secondly, that there be no abuse thereof committed,
we do in like manner entreat and desire that friends may be exhorted and advised,
when any just and valuable occasion doth require any to make use of this affirmation,
that such friend or friends be very considerate and
sure of the truth of what they are about to affirm;
for where property or liberty are concerned,
a false or corrupt evidence is very injurious, and may prove destructive;
besides it ought on all occasions to be remembered,
that a false witness shall not be unpunished,
and he that speaketh lies shall not escape,^
footnote:[Prov. 19:5]
and that the command, thou shall not bear false witness,`"^
footnote:[ Rom. 13:9]
is as well in the gospel as in the law,
and that all liars shall have their part in the lake which burneth with fire and brimstone.^
footnote:[Rev. 21:8]
To these inward obligations on the conscience of truth speaking,
there is also added the outward guard of pains, penalties and forfeitures,
to be inflicted on such as shall lawfully be convicted of wilful,
false and corrupt affirming or declaring,
as if the same person had been convicted of wilful and corrupt perjury.

We cannot omit also to remind you, that should any under our name,
so far depart from the righteous law of God, as here become guilty,
they will thereby contract to themselves perpetual infamy,
and to the body whereof they may pretend to be members, very great scandal and reproach,
and such instances repeated might provoke the government
to deprive us of this great benefit.
How great would be the load of guilt on any, who should be the occasion thereof!

Let it therefore be considered that the ground of our petitioning and
soliciting for this further ease and relief was a consciencious scruple;
how infamous therefore would it be for any who profess a scruple to swear at all,
at the same time to be guilty of false affirming,
and while they pretend to great degrees of purity, to fall short of common honesty;
it is indeed among the highest degrees of hypocrisy, a crime abhorred by God and man.

Dear friends, under the very weighty consideration of these things,
this epistle is recommended to you,
in order to stir up all to be careful upon every occasion to prevent the many
evils and mischiefs which may ensue upon the abuse of so great a favour,
which care we think may in some measure be answered
by two or three faithful and judicious friends,
attending the assizes and quarter sessions in every county,
whereby they may be of service in several respects; as first,
if there should come to those courts any pretending to be Quakers,
and under that pretence require to be admitted to our solemn affirmation,
and thereby excuse themselves from an oath, which they may hold as a great sanction,
to the prejudice of an honest cause, which may suffer through such deceit;
while in truth they are not Quakers, nor by us reputed such;
here friends will be at hand to detect such impostors.
Secondly, they will have service in advising any friends,
who may be obliged to attend either at the assizes or sessions in any cause,
wherein they may stand in need, as also to be assisting to any friend,
that no impositions, or addition of words be put to the affirmation,
either unwarily or designedly, by any officer, with purpose to ensnare.

To all these particulars we think it necessary to add,
and very earnestly and tenderly to recommend to all friends,
that as much as may be they avoid all disputes and differences with their neighbours,
and as much as possible follow peace with all men;^
footnote:[Heb. 12:14]
and in a particular manner we do press that all disputes
and differences between friends be avoided,
or if any do happen, that earnest endeavours be used,
by accommodation or equitable and impartial reference to end them without going to law,
that so the rebuke of the apostle may not necessarily be applied to any,
now therefore there is utterly a fault among you, because ye go to law with one another.^
footnote:[1 Cor. 6:7]

Dear friends, these things in a christian concern of mind we have represented,
in order that all may be stirred up to an humble and faithful walking,
not as knowing that any will fall short in the above particulars.
But, beloved, we are persuaded better things of you; and things that accompany salvation,
though we thus speak.`"^
footnote:[Heb. 6:9]

Signed in and on behalf of the said meeting by

[.signed-section-signature]
Bemjamin Bealing.

--

By an act, 22 Geo.
II. 1749, the affirmation was made perpetual, and to operate in all cases,
wherein by any act or acts of parliament now in force, or hereafter to be made,
an oath is required,
although no particular or express mention be made for that purpose in such act or acts,
with the same force as an oath, except in criminal cases, to serve on juries,
or to bear any office or place of profit in the government.^
footnote:[In an act, entitled _An Act for Continuing Several Laws,
and for Allowing the Quakers to Make Affirmation, Etc._ is the following clause;
And whereas a doubt has arisen whether the solemn
affirmation or declaration of the people called Quakers,
prescribed by an act made in the eighth year of the
reign of his late majesty king George the first,
entitled an act for granting the people called Quakers such forms
of affirmation or declaration as may remove the difficulties,
which many of them lie under, can be allowed and taken instead of an oath,
in any case wherein by any act or acts of parliament an oath is required,
unless the said affirmation or declaration be by such act or acts of parliament
particularly and expressly directed to be allowed and taken instead of such oath,
by reason of which doubt the testimony of the said
people called Quakers is frequently refused,
whereby the said people, and others requiring their evidence,
are subject to great inconveniences; therefore, for removing the said doubt,
be it enacted and declared, by the authority aforesaid,
that in all cases wherein by any act or acts of parliament now in force,
or hereafter to be made, an oath is or shall be allowed, authorized,
directed or required,
the solemn affirmation or declaration of any of the people called Quakers,
in the form prescribed by the said act made in the
eighth year of his said late majesty`'s reign,
shall be allowed and taken instead of such oath,
although no particular or express provision be made for that purpose in such act or acts;
and all persons who are or shall be authorized or required to administer such oath,
shall be,
and are hereby authorized and required to administer the said affirmation or declaration;
and the said solemn affirmation or declaration so made, as aforesaid,
shall be adjudged and taken,
and is hereby enacted and declared to be of the same force and effect,
to all intents and purposes, in all courts of justice, and other places,
whereby law an oath is or shall be allowed, authorized, directed or required,
as if such Quaker had taken an oath in the usual form;
and if any person making such affirmation or declaration
shall be lawfully convicted of having willfully,
falsely and corruptly affirmed or declared any matter or thing, which,
if the same had been deposed upon oath in the usual
form would have amounted to wilful and corrupt perjury,
every person so offending shall incur and suffer the like pains,
penalties and forfeitures,
as by the laws and statutes of this realm are to be inflicted
on persons convicted of wilful and corrupt perjury.
Provided nevertheless, and be it enacted, that no Quaker shall, by virtue of this act,
be qualified or permitted to give evidence in any criminal cases, or to serve on juries,
or bear any office or place of profit in the government;
anything herein contained to the contrary notwithstanding.`"]

In this year that eminent minister and serviceable member of this society,
George Whitehead, of the city of London, departed this life;
whose religious labours for the convincement and edification of friends,
sufferings for his testimony, and repeated solicitations to the government,
under a sympathetic concern for the relief of his friends under suffering,
have supplied considerable materials for different parts of this history,
and thereby the present narrative of his life and actions
may be comprised in a review of his early years,
his convincement and his character,
by his friends who were personally acquainted with him.

He was born at Sun-bigg, in the parish of Orton, in the county of Westmorland,
about the year 1636, of honest and reputable parents,
who gave him a good education at the free-school of Blencoe in Cumberland,
where he made a considerable proficiency in those called the learned languages.
As to profession of religion he was brought up in the society of the Presbyterians.
But perceiving pretty early in life, about the 14th year of his age,
that those people and ministers did not in life and
conversation act up to the purity of their professions,
he could not cordially join with them,
before he had heard of the existence of such a people as those
distinguished by the reproachful denomination of Quakers;
and being influenced with a secret desire after something
more substantial than he was yet acquainted with,
was at a loss where to find what he wanted, and became even bewildered in the search.

Having about this time some religious discourse with some sober-minded young men,
by whom he heard of a few people called Quakers at Sedbergh in Yorkshire,
and in the barony of Kendal in Westmorland, he concluded to go to a meeting of theirs,
which was held at Captain Ward`'s, at Sunny-Bank near Grayrig;
and here we have an instance that a very few words spoken from a heart affected with
an inward sense of a divine impression may be more effectual under divine influence,
to fix the best impressions on the minds of others,
than the most elaborate discourses of lettered eloquence,
as a short recommendation of a little captive maid,
was conducive to the healing the Assyrian captain of his leprosy.
He was sensible as he sat in the meeting, of the work of the power of the Lord, reducing,
humbling and contriting the spirits of the people, although but few words were spoken,
affecting them with great sorrow and weeping,
which he believed to be the godly sorrow which produceth unfeigned repentance;
and seeing a young maid go mourning out of the meeting,
he felt an inclination to follow her; he saw her sitting on the ground,
with her head bowed down, and apprehending herself alone,
she gave vent to the fulness of her heart, in this short ejaculation,
"`Lord make me clean! "`O Lord, make me clean!`" which he said,
"`did more deeply and reachingly affect my heart
than what I had heard spoken in the meeting,
and more than all the preaching that ever I heard from man to man.`"

He continued, being so persuaded in apprehension of duty,
to frequent the assemblies of these people, who were as yet but few in number,
in comparison of what he lived to see them,
notwithstanding he met with much opposition and many
hard speeches from some near relations and others,
who were under the influence of the priests or preachers of the age,
by whom this people was much misrepresented.

As his mind turned to the true light which enlighteneth
every man that cometh into the world,
he was thereby illuminated to see his inward and outward state to be in the degeneration,
depraved, corrupted and alienated from the life of Christ;
that he had a spiritual warfare to engage in and accomplish,
and a body of sin to put off, though not grown to that maturity or strength,
as in many of those of riper years,
who by suffering their propensity to evil to grow habitual,
are drawn into gross enormities, by which he, being in the innocence of his youth,
was as yet untainted; nevertheless he now saw a necessity of being cleansed from sin,
and being born again, to be redeemed not only from visible evils, but from levity,
vain thoughts and imaginations, and wanderings of mind;
which were so burdensome and uneasy to him,
that he earnestly prayed for power to suppress and get the victory over them,
and stay his mind that he might obtain inward peace.

And as he was careful to wait for it in silence and stillness,
he was gradually favoured with the power he desired; the meetings he frequented,
he informs us, were much spent in silence,
yet as they came to experience victory over sin,
and the work of sanctification advancing,
they were sometimes filled with the word of life,
and then from the fulness of the heart his mouth (among some others) was opened
to utter a few words for edification and comfort to each other.

It was out of these meetings, frequently held in silence, he saith,
the Lord was pleased to raise up and send forth living witnesses of his power and faithful
ministers of the gospel in those early days in Westmorland and other northern counties;
and that he was not the least in qualification and service is abundantly
manifest in several parts of this history.

He was one whom the Lord had fitted and prepared by his
holy spirit for the work whereunto he was called,
and whereby he was one of the most able ministers of the gospel in his day.
As he was deep in the experience of the work of redemption and reconciliation to God,
through Jesus Christ our Lord, he was frequently opened in his testimony,
to unfold the mysteries of the heavenly kingdom,
in the clear demonstration of the spirit and power, dividing the word aright,
to the opening of the understandings of many unacquainted with the work of pure religion;
and to the comforting, confirming and establishing those,
who were not unacquainted therewith,
in their endeavours after a growth and advancement therein.

He was not only a zealous assertor of the true faith and
doctrine of Christ in a sound and intelligible testimony;
but was frequently engaged to take up his pen in
vindication thereof against adversaries and opposers,
as well as on many other occasions,
and was careful through a long course of life to adorn the doctrine
of the gospel by a circumspect conduct and religious conversation,
wherein the fruits of the spirit, love, joy, longsuffering, gentleness, goodness, faith,
meekness and temperance, did eminently shine forth,
to the glory of God and reputation of his religious profession.

This christian deportment,
and his affable disposition procured him respect
and esteem amongst most people of all ranks,
who were acquainted with his worth;
which was conducive to open his way to that part of his public service,
wherein he was eminently engaged, viz. in solicitation to several kings, parliaments,
bishops and other persons in authority,
for the relief and release of his friends suffering
under severe persecution and grievous imprisonments;
in exerting strenuous endeavours for liberty of conscience,
and for relief in the case of oaths,
in which benevolent interventions on behalf of his brethren,
the foregoing pages exhibit his diligence,
often through the divine blessing crowned with success.

He was a good example to the flock in all his conduct,
and particularly in his diligent attendance of meetings
for worship on first and week days,
and other meetings for the service of truth,
so long as he was favoured with ability of body;
zealous to support good order and discipline in the church;
as he was careful to lay hands suddenly on no man,
he was equally cautious not to be hasty in casting any off,
while any hopes of their recovery remained; condescending to the weak,
and reproving transgressors in the meekness of wisdom,
for their preservation in an orderly conversation,
and the unity of the spirit in the bond of peace.

He was a tender father in the church, full of compassion to the poor,
and sympathy with friends under affliction in body or mind;
a diligent visitor of the sick, and a comforter of the mourners;
active to prevent and industrious to compose differences.

Sustained by the consciousness of a well-spent life,
he passed the last infirmities of age with christian
patience and resignation to the divine will,
desiring but in submission thereto, to be dissolved and be with Christ,
saying the sting of death was taken away; and a little before his departure,
he expressed himself to this purport, that he had taken a review of his life,
his labours and travels, that he had gone through since his first convincement,
that he looked upon them with abundance of comfort and satisfaction,
and admired how the presence of the Lord had carried him through all.

By a gradual decay of the earthly tabernacle, full of years, and full of peace,
he passed out of this life to a better, in the 87th year of his age,
the 8th day of the 1st month, commonly called March,
O.S. and was buried in friends burying ground, Bunhill Fields,
amongst many of his ancient brethren, the 13th of the same:
his funeral was attended by a very large number of friends and others.

A friend in Chester, who had a right thereto,
being refused his freedom of the city upon the freedom of affirmation,
and the case being laid before sergeant Cheshire,
he gave the following opinion viz. "`It was resolved
in the case of the King against the Mayor of Lincoln,
on a mandamus, to admit one Morris to his freedom;
that a Quaker ought to be admitted to his freedom,
on his making a solemn affirmation or declaration, and, if refused,
may properly bring his mandamus on motion in the court of King`'s Bench.`" Since which,
friends who have a right, have been admitted to their freedom of corporations,
upon their solemn affirmation.

This year Richard Claridge of London departed this life.
He was a native of Warwickshire, the eldest son of William Claridge of Farmborough.
His parents were sober religious persons of good reputation and good circumstance;
and being members of the church of England, they brought up their son in that way,
and gave him what is termed a learned education;
he was continued at the grammar school till he attained
a competent knowledge both of the Latin and Greek languages,
and in the seventeenth year of his age was entered a student at Baliol college in Oxford.
He took his degree of Batchelor of Arts in 1670, and was the same year ordained deacon;
and in 1672 ordained priest in the king`'s chapel, Westminster,
by Walter Blandford bishop of Worcester.

He was soon after advanced to the rectory of Peopleton in Worcestershire,
where he taught a grammar school and kept boarders
several years with considerable reputation and success.
During his residence here, his own accounts inform us,
he was at times actuated by a sense of duty, but not uniformly so.
Sometimes he was very strict and severe in his conversation,
and at other times too remiss and unguarded.
Sometimes he seemed to have a zeal for God and a
solicitude for the well-being of his own soul;
but again this religious concern would wear away,
and a state of lukewarmness to either succeeded.
Yet, although he had not attained to a stability in righteousness,
he was very industrious in performing the customary exercises of his office.
He studied closely in composing his sermons,
and delivered his compositions with an appearance of fervency
and affection which were very taking with his auditory,
by whom he was generally well esteemed.

In this unsettled state he continued many years;
but the Lord did not suffer him to continue therein,
without the reproofs of his holy spirit.
He was often visited by the dayspring from on high, and his candle was often lighted,
though for want of due watchfulness he suffered the
light to be eclipsed through transgression.

About the year 1687, the 15th of his incumbency at Peopleton,
through the operation of divine grace upon his spirit,
he was brought to a serious consideration of his ways,
and a clearer sight of the state of his soul, what it was, and what it ought to be;
under which view sin was manifested to be exceeding sinful,
and his soul was sorely afflicted under the sense and burden of it.
Under the weight of that godly sorrow, which leads to repentance not to be repented of,
seeking rest and finding none,
he took a journey to London in the month called April 1689,
hoping to receive consolation and instruction from the ministry
of some preachers thereof great account.

He spent some weeks in London,
during which time he went to hear sundry preachers of eminence,
both episcopalians and dissenters;
but although some of their remarks made an impression on his mind, yet upon the whole,
being too much disappointed in his view of receiving some spiritual consolation,
to relieve the anxiety of his mind, he returned home again to Peopleton,
where he applied himself to the work of repentance;
and through divine assistance he was enabled to reform his conversation,
and to persevere in a sober and religious deportment
with more stability than heretofore.

And now being awakened to a feeling sense of his own state,
and to a diligent inquiry after the safe and sure way to salvation,
he was much exercised in reading the scriptures, in order to trace it out thereby;
and his understanding being illuminated by that true light
which enlighteneth every man that cometh into the world,
was opened to discover that many things in the doctrine, practice,
worship and ceremonies of the church of England,
were not derived from this pure fountain,
but were the appointments and contrivances of men, and therefore not lawful for him,
not being of faith, to continue in the practice of.

The following texts often occurring to his remembrance,
and being applicable to his present case, he esteemed them as spoken to himself,
viz. Mat. 15: 8-9, "`This people draweth nigh me with the mouth,
and honoureth me with their lips, but their hearts are far from me;
but in vain do they worship me,
teaching for doctrines the commandments of men.`" And 2 Cor. 6:17,
"`Come out from among them, and be ye separate, saith the Lord;
touch not the unclean thing, and I will receive you.`"

Yet he found it no easy matter to yield full obedience to his convictions,
so far as to leave the communion of the national church:
both honour and interest lay at strike.
It was a severe trial of his faith, and hard to flesh and blood,
to relinquish a good living and a certain revenue,
and to depend on Providence for a future support.
He felt all the force of the natural reluctance in
the prospect of the certain consequence of his change,
that he who had been a minister of that church,
well approved for wisdom and judgment near twenty years,
should expose himself to contempt and reproach,
and be counted as a fool by those who formerly held him in honour.
These considerations retarded his resolution for some time;
but his supplication to the Almighty for strength,
to act faithfully to the convictions of his grace, was mercifully granted,
so that in the 10mo December 1691, he voluntarily resigned his parochial charge,
and the income annexed thereto, into the hands of the bishop of Worcester,
by a legal instrument, as he could now keep neither with a good conscience.

He had a considerable time before contracted an acquaintance
with some leading men amongst the baptists in his neighbourhood,
and by the conferences he had held with them,
judging them to approach nearer the primitive pattern,
he joined himself to their society.
And, as he had foreseen, his change brought upon him many reproaches,
slanders and false insinuations and accusations,
so that he was even amazed at the sudden change in those men, with whom,
whilst of their communion, he was in reputation for wisdom and integrity,
who now represented him as scarcely entitled to the character of common honesty;
but he was strengthened by divine grace to bear reproach and calumny with patience,
not to return reviling for reviling, but to pray for his enemies,
and to commit his cause to him who judgeth righteously.

He had not been long a member before he became a preacher amongst the baptists,
not as pastor of any particular congregation, but in sundry neighbouring meetings,
as his freedom or inclination drew him; sometimes at Bredon,
the place of his present residence, at other times at Tewksbury, Broomsgrove, Pershore,
and other places adjacent.

After he had continued in this itinerant line of preaching several months,
in the 5mo 1692,
he received an invitation from the baptist meeting at the Bagnio in Newgate street,
London, to come and settle among them, as their minister, to which he consented,
and removed to London the latter end of that year,
and was a very constant and diligent preacher amongst them for upwards of two years;
whether he received any salary I know not,
but find that at this time he took a house in George`'s court, Clerkenwell,
and kept a grammar school there for several years.

In the year 1695 he resigned his pastoral charge,
yet still preached frequently in one or other of
the baptist meetings in or about the city,
refusing to be any more limited to a particular assembly,
though requested thereunto by the call or invitation
of the baptist church meeting in Virginia-street;
but he could not comply therewith,
being now convinced that a church`'s call was not
a sufficient authority for preaching the gospel;
that bargain and contract, and preaching by notes,
are not authorized by the holy scriptures.
He continued, notwithstanding, to preach at times in their meetings some months longer,
and then from an apprehension of the weighty nature
of the work and his own unfitness for it,
he entirely declined the function of preaching amongst them,
and soon after began by degrees to withdraw from their communion.
For although he found among them a serious remnant, sounder in doctrine, holier in life,
and to have less of human invention in their worship than those of the national way;
yet they appeared far short of that purity in faith, worship and discipline,
by which the primitive christians of the apostolic age were distinguished.
Their dispensation, he perceived, was that of John, a lower dispensation,
which was to vanish, and to give way to a higher, the dispensation of the spirit,
which was to abide forever.
Here God teaches his people himself.

Being thus far illuminated into the nature of pure and spiritual religion,
he felt his mind affected with anxious solicitude to become
more nearly acquainted with this higher dispensation;
which induced him frequently in solitude and silence to
pour out secret and sincere supplications to the Almighty,
for greater degrees of the illumination of his spirit,
to direct him aright in his search after this desirable attainment,
who was pleased by the gradual manifestations and discoveries
of his divine light to make him acquainted with Christ Jesus
in his inward and spiritual appearance in his heart.
And now upon a serious inquiry into the principles
and practices of the people called Quakers,
and comparing them with the scriptures of truth, and the impressions upon his own mind,
he found that agreement therewith, which induced him to attend some of their meetings.

Here meeting with the satisfaction which his soul had long been in search of,
finding their ministry affecting and edifying,
and their meetings frequently attended with the divine presence,
ministering consolation and refreshment to weary and waiting souls;
as he was favoured amongst them to taste of the good word of life,
and a participation of the powers of the world to come,
those meetings became more and more desirable,
and he quickly became a constant attender of them.

He did not upon his entering into this society appear as a minister amongst them;
but being illuminated with a clear discerning of
the insufficiency of external forms and shadowy administrations,
he applied himself to seek after the attainment of the real substance of pure religion,
waiting in humility and silence to hear the voice of Christ internally revealed.

In this state of humble silence and patient waiting upon God,
he remained a considerable time, passing through the dispensation of condemnation,
under which he was humbled and judged,
not only in the view of past deficiencies and present
shortness of purity as in the sight of God,
but even for his former preaching in his own will, wisdom and time;
so that he dared not again to open his mouth in a public assembly,
until he felt himself relieved from this proving and humbling dispensation,
and so far refined thereby as to witness the ministration of life and peace,
and the immediate operation of the holy spirit moving him to pray
or preach as he might be pleased to afford both matter and utterance.
His first appearance as a minister amongst this people
was in a meeting at Sarah Sawyer`'s in Aldersgate-street,
London, the 24th of the 8th month, 1697,
and above nineteen months after he had desisted from preaching among the baptists.
His testimony tended to recommend a broken and contrite spirit for the debasing of self,
and magnifying the grace of God, by which he had been turned from darkness to light,
and enabled by living experience to testify of his goodness.

From this time to the day of his death he steadfastly continued
in christian fellowship with this society as an approved minister,
and an honourable and useful member, not only in his ministerial labours,
but in his writings of various kinds for their edification
and in vindication of their doctrines and principles.

And as he had now conscientiously declined making a gain of the gospel,
or preaching for lucre`'s sake,
he followed his occupation of instructing youth for a livelihood.
In the summer of the year 1700 he removed from London to Barking in Essex,
where he fixed his residence, and kept a boarding-school for some years.
He removed to Edmonton in 1706, and lastly to Tottenham in 1707,
where he had a considerable number of boarders,
and of the children of the inhabitants attending his school.
In the latter end of the year 1713, being the 64th of his age,
feeling his natural strength and activity begin to decline,
and the fatigue of his employment inconvenient to the infirmities of advancing years;
and having attained, through the divine blessing, a competency for his subsistence,
he left off keeping school,
and removed from Tottenham to George`'s-court near Hicks`'s-hall, London,
where he dwelt the remainder of his days.

The act of Toleration for Protestant Dissenters having been
passed some years before he joined the society of the Quakers,
and the Schism Act not yet in being,
it might be expected that no occasion at this time existed
for bringing the members of this society under suffering,
except for ecclesiastical demands; but we have ground for remark in his case,
as well as many others,
that the spirit of intolerance did not terminate
with the power of exercising it to the full.
R+++.+++ Claridge, besides repeated distraints for the demands of the Vicar and Wardens,
in common with others, was subjected to much obloquy and a severe prosecution,
only for endeavouring to procure an honest and reputable livelihood in
that line of life for which his education had qualified him.

He had not resided long at Tottenham before he was threatened
with a prosecution for keeping a school there;
that lord Coleraine, and Hugh Smithson, Esq.
men of great power in that place,
were offended that a Quaker should keep a school in that parish,
and that if he did not relinquish it,
or confine himself to the reception of Quakers children only for tuition,
they would give him trouble.

This unreasonable requisition (which would not only deprive R. C. of the equal
right of profiting by his industry in a lawful and useful calling but the inhabitants
of the advantage and natural right of procuring their children an education,
wherever they might expect it would be most conducive to
the children`'s benefit and their own satisfaction) was made,
as it appeared, at the instigation of the Vicar and Curate of the parish,
and the master of the free-school there, the former from bigotry,
and the latter from self-interest,
being sanguine for the suppression of this new seminary,
by their importunities and representations to these men in power,
of the dangerous consequences of a Quakers school in Tottenham,
to the interests of the church and of the free-school,
they excited them to second their endeavours for the suppression thereof.

First of all, the Vicar and his Curate went about from house to house,
to dissuade people from sending their children to him,
giving an illiberal licence to their tongues in abuse of
R+++.+++ C. with indecent language and opprobrious nicknames,
such as the bitterness of their spirits suggested, impostor, heretic, Jesuit, apostate,
and such like were the terms whereby they characterised him.
The Vicar further indulged his passion so far as
to make him the subject of his public discourse,
and railed at and reviled him in the pulpit,
to the great offence of several of his hearers,
who held his uncharitable proceedings in abhorrence.

Next justice Smithson sent him a summons to appear before the justices
at Edmonton to take the oaths prescribed by act of parliament:
appeared accordingly,
and subscribed the declaration and profession of faith in the act of diligence,
which prevented their exertion of power to imprison as formerly,
and which they wanted to do still.

In order whereto they began to catechise him about his keeping school,
and whether he had a licence from the bishop of London?
to which replying, that he was informed he had a right so to do;
lord Coleraine said that should be tried,
and he and justice Smithson agreed in a prosecution,
and threatened they would suppress his school or expend five hundred pounds.
Through the whole, they discovered in their countenances, words and actions,
great enmity, passion and impatience,
treating him in a manner unworthy of their station or his character,
below the rules of decency and common civility;
and it was thought that his leaving the church,
and writing in defence of the Quakers had given umbrage to some of the clergy,
and that they had incited these great men to raise this storm against him.

He had been before cited to the ecclesiastical court,
but the prosecution was dropped for want of a promoter:
and soon after this he was served with a second citation to appear at Doctor`'s Commons,
to answer to certain interrogatories concerning his soul`'s health,
and the reformation of his manners, and especially for teaching and instructing boys,
etc. where although the evidence against him amounted to no positive proof,
yet it being apprehended that the court would proceed to an admonition,
and in case of his persisting to an excommunication and consequent imprisonment,
it was thought expedient to remove the cause into the temporal court (so termed).
A prohibition was accordingly applied for to stop
proceedings in the bishop`'s court and obtained,
whereby the cause was removed to the queen`'s bench,
and tried before the chief justice Holt.
The trial was pretty long, and the chief justice declared his opinion,
that if a school-master qualified himself according to the act of Toleration
he should be exempted from all the pains and penalties of all the statutes
made against popish recusants and protestant nonconformists;
took notice of the violence of the prosecution against the defendant;
was of opinion the statutes of king James I. upon
which he was prosecuted did not reach the defendant,
but would not then determine,
and therefore directed the jury to bring in a special verdict, which they did,
finding the defendant to have taught school during two days in his house at Tottenham,
High-cross, not being licensed by any archbishop or bishop,
etc. and that the defendant is a Quaker, and no Popish Recusant.
This verdict,
and the complexion of the chief justice`'s opinion upon the cause and the prosecution,
discouraged his antagonists from further procedure, to avoid paying costs,
which would have been the case if final judgment were given against them.
The issue of this cause procured R. C. exemption from any further
molestation in following his honest and useful employment.

In the year 1720, when the nation was over run with a spirit of avaricious adventure,
whereby numbers became a prey to the visionary schemes
and fraudulent designs of ill-designing men,
this friend was zealously concerned to caution his
friends against being carried away with the stream.
In his public testimonies, in private admonitions,
exerting his endeavours to guard them against the snare,
by manifesting the sin of covetousness,
and the inconsistency of such an extravagant pursuit of precarious gain as then prevailed,
with that state of self-denial, contentment and honest simplicity of manners,
which the christian religion prescribes and establishes.
And had his faithful exhortations,
and those of other truly religious and judicious friends been duly regarded,
the members of this society had been rescued from sharing in the deception,
dishonour and disappointment which ensued.

He travelled several journeys in the work of the ministry into the neighbouring counties;
but from this time the infirmities of age increasing,
he was prevented from getting far abroad (but diligently attended meetings at
home while of ability) and at last was affected with a shortness of breath,
attended with an inward fever, which increased upon him to his end.
During the time of his sickness he expressed to several friends that visited him,
his peace and satisfaction of soul, and an humble resignation to the will of God.
He departed this life on the 28th day of 2mo, 1723, in the 74th year of his age,
and was buried on the 3d day of 3mo following, in the burying ground near Bunhill-fields,
his corpse was attended from the Peel meetinghouse by a
numerous company of his friends and acquaintance.

The friends of said meeting, amongst whom he spent the last years of his life,
have given testimony concerning him, that

[.embedded-content-document.testimony]
--

His ministry was sound and edifying, pressing all to purity and holiness of life.
His care and concern For the church was great,
that it might be kept clean from the spots of the world.
Vice and immorality met with a reprover in him, and that without respect of persons.
His christian gravity and judicious solidity,
tempered with a natural affability and sweetness of disposition,
rendered his conversation among his intimate friends and
acquaintance very profitable and delightful.

His piety towards God, his love to his neighbour,
the truth and justice of his words and actions, made him as a light in the world,
and gave forth a testimony to the truth,
in the hearts of those who came not to hear his preaching.

In his own private family he was a living example of virtue; an affectionate husband,
a loving father, a kind and gentle master,
and frequent and fervent in supplication to the Lord
for the preservation of himself and his household,
in the way of truth and righteousness.

His charity to the poor was very extensive, not only to friends, but others,
being a practical observer of the pure and undefiled religion,
recommended by the apostle James, to visit the fatherless and widows in their affliction,
and to keep himself unspotted from the world.

--

Some friends of New England having been appointed
to assess the taxes on their respective townships,
and being conscientiously scrupulous of assessing those
laid on for the support of the presbyterian ministry,
and applications for their relief having been ineffectually
made to the government of that province,
gave occasion to the following petition to the government at home.

[.embedded-content-document.letter]
--

[.blurb]
=== A petition to the King in the cause of some friends under sufferings in New England.

[.letter-heading]
To George, king of Great Britain, etc.

[.blurb]
=== The humble petition of Thomas Richardson and Richard Partridge, on behalf of Joseph Anthony, John Sisson, John Akin and Philip Tabor, prisoners in the common jail at New Bristol in the King`'s Province of Massachusetts Bay in New England, as also of their friends (called Quakers) in general, who are frequently under great sufferings for conscience-sake in that government.

[.salutation]
Showeth,

That William and Mary, late king and queen of England,
by their royal charter bearing date the 7th day of
October in the third year of their reign,
did for the greater ease and encouragement of their
loving subjects inhabiting said province,
and of such as should come to inhabit there, grant,
establish and ordain that forever thereafter there should be a liberty of conscience
allowed in the worship of God to all christians (except papists) inhabiting,
or which should inhabit or be resident within the said province,
with power also to make laws for the government of the said province,
and support of the same,
and to impose taxes for the king`'s service in the defence and support of the said government,
and protection and preservation of the inhabitants,
and to dispose of matters and things whereby the king`'s subjects there might be religiously,
peaceably and civilly governed, protected and defended.`"

And for the better securing and maintaining the liberty of conscience thereby granted,
commanded that all such laws made and published by virtue of said charter,
should be made and published under the seal of said province,
and should be carefully and duly observed, kept, performed and put in execution,
according to the true intent and meaning of the said charter.

That those sects of protestants called presbyterians and independents being more
numerous in the said country than others (to whom the said charter gives equal
rights) they became makers of the laws by their superior numbers and votes,
and ministers of the privileges of the said charter,
so as in great measure to elude the same,
and disappoint all others of the king`'s protestant subjects of the good and just
ends of their transporting themselves and families at so great hazard and charge;
one great encouragement and inducement thereto being liberty of conscience,
and ease from priestly impositions and burdens.

That in the year 1692 they made a law in the said province,
entitled an act for the settlement and support of ministers and school-masters,
wherein it is ordained,
that the inhabitants of each town within the said province shall take
due care from time to time to be constantly provided of an able,
learned and orthodox minister or ministers of good conversation,
to dispense the word of God to them,
which minister or ministers shall be suitably encouraged and sufficiently
supported and maintained by the inhabitants of such towns.

That the said law was farther enforced by another made in the year 1695,
reciting the like aforesaid, as also by another made in the year 1715, entitled an act:
for maintaining and propagating religion,
in which said last act the prevention of the growth of atheism irreligion
and profaneness is suggested as one great reason of its being enacted,
and the power of determining who shall be ministers under the aforesaid,
qualifications is by the said law assumed by the general court or assembly,
with the recommendation of any three of the ministers of the same sect,
already in orders, and settled and supported by virtue the said laws,
though it was not determined (as the said petitioners
humbly presume) either by the said charter,
or by any act of parliament in Great Britain, or by any express law of the said province,
who are orthodox or who are not,
or who shall judge of such qualifications in such ministers.

And in all which said several laws no care is had or taken of religion (even
in their own sense) than only to appoint ministers of their own way,
and impose their maintenance upon the king`'s subjects,
conscientiously dissenting from them, by force of which said laws, or some of them,
several of the townships within the said province have had presbyterian and independent
preachers obtruded and imposed upon them for maintenance without their consent,
and which they have not deemed able, learned and orthodox,
and which as such they could not hear or receive.

That by other laws made in the year 1722 and 1723,
it is ordained that the town of Dartmouth and the town of Tiverton in the said
province shall be assessed for the said years the respective sums of 100. and
72. 11s. over and besides the common taxes for support of the government,
which sums are for maintenance of such ministers.

That the said Joseph Anthony and John Sisson were appointed
assessors of the taxes for the said town of Tiverton,
and the said John Akin and said Philip Tabor for the town of Dartmouth,
but some of the said assessors being of the people called Quakers,
and others of them also dissenting from the presbyterians and independents,
and greatest part of the inhabitants of the said towns being also Quakers or anabaptists,
or of different sentiment in religion from independents and presbyterians,
the said assessors duly assessed the other taxes upon the people there,
relating to the support of government, to the best of their knowledge,
yet they could not in conscience assess any of the inhabitants of the
said towns anything for or towards the maintenance of any ministers.

That the said Joseph Anthony, John Sisson, John Akin and Philip Tabor,
(on pretence of their non-compliance with the said
law) were on the 25th of the month called May,
1723, committed to the jail aforesaid,
where they still continue prisoners under great sufferings
and hardships both to themselves and families,
and where they must remain and die,
if not relieved by the king`'s royal clemency and favour.

That the said people called Quakers in the said province are, and generally have been,
great sufferers by the said laws, in their cattle, horses, sheep,
corn and household goods,
which from time to time have been taken from them by violence
of the said laws for maintenance of the said ministers,
who call themselves able, learned and orthodox; which said laws,
and the execution and consequences thereof,
are not only (as the petitioners humbly conceive) contrary
to the liberty of conscience and security of religion,
civil liberty, property;
and the rights and privileges granted in the said
charter to all the king`'s protestant subjects there,
eluded and made null and precarious;
but opposite to the king`'s royal and gracious declaration,
at thy happy accession to the throne,
promising protection and liberty of conscience to all thy dissenting subjects,
without exception to those of the said plantations.

That after repeated applications made to the government there,
for redress in the premises,
and no relief hitherto obtained (the assembly always opposing whatever the governor
and council were at any time disposed to do on that behalf) the king`'s loyal suffering
and distressed subjects do now throw themselves prostrate at the steps of the throne,
humbly imploring thy royal commiseration,
that it may please the king to denounce his negative upon the said laws,
or such part or parts of them, or any of them,
as directly or consequentially affect the lives, liberties, properties,
religion or consciences of the protestant subjects in the said province,
and their families, and the privileges granted and intended in the said charter,
or such other, relief as thy royal wisdom and goodness may please to provide;
and in the meantime that directions may be given that the said Joseph Anthony,
John Siffon, John Akin and Philip Tabor be immediately released from their imprisonment,
on their giving such security in such sums as shall be thought proper,
for their being at any time or times hereafter forthcoming when required,
until their case be brought to an issue.

And the petitioners shall pray.

[.signed-section-context-close]
At a Court at St. James`'s, the 2nd day of June 1724,

[.no-indent.emphasized]
Present:

The King`'s Most Excellent Majesty,

His Royal Highness the Prince of Wales,

Archbishop of Canterbury,

Lord Chancellor,

Lord President,

Lord Privy Seal,

Lord Carteret,

Mr. Vice Chamberlain,

William Pultney, Esq.,

Lord Chamberlain,

Duke of Roxburgh,

Duke of Newcastle,

Earl of Westmoreland,

Lord Viscount Townsend,

Lord Viscount Torrington,

Mr. Speaker of the House of Commons

[.small-break]
'''

Upon reading this day at the board,
a report from the Right Honorable the Lords of the committee of council,
upon the petition of Thomas Richardson and Richard Partridge,
on behalf of Joseph Anthony, John Sisson: John Akin and Philip Tabor,
prisoners in the common jail at New Bristol,
in his majesty`'s province of Massachusetts Bay in New England,
for not assessing the inhabitants of the towns of Dartmouth
and Tiverton the additional taxes of 100. and 72. us.
imposed upon them by an act passed there in the year 1722,
by which they appear to be for the maintenance of Presbyterian ministers,
who are not of their persuasion,
and also in behalf of their friends called Quakers in general,
who are frequently under sufferings for conscience sake in that government.
By which report it appears, their Lordships are of opinion,
that it may be advisable for his majesty to remit the said additional taxes,
so imposed on the said two towns, and to discharge the said persons from jail.

His majesty in council taking the said report into consideration,
is graciously pleased to approve thereof,
and hereby to remit the said additions taxes of 100. and 72. 11S. which were
by the said act to have been assessed on the said towns of Dartmouth and Tiverton.
And his majesty is hereby further pleased to order, that the said Joseph Anthony,
John Sisson, John Akin and Philip Tabor be immediately released from their imprisonment,
on account thereof, which the governor, lieutenant governor,
or commander in chief for the time being of his majesty`'s
said province of Massachusetts Bay,
and all others whom it may concern, are to take notice of,
and yield obedience thereunto.

[.signed-section-signature]
Temple Stanyan

[.postscript]
====

_Vera Copia._

====

--

In the year 1720 Christopher Story departed this life.
He was a native of Cumberland, being born at Righead,
in the parish of Kirklington in that county.
His father, Thomas Story, having been in the service of Sir Philip Musgrave,
by his advice and encouragement gave this son an education to fit him for the university,
the said Sir Philip proposing to send him thither
at his expense as a companion to his own son:
But when the time arrived for their removal from school,
Christopher`'s mother was unwilling to consent to his going thither,
in consideration that an education there might be the means
of alienating him from the love of a country life,
and make him disregard his paternal inheritance,
being like to possess an estate sufficient to afford him a competency
on these and other considerations she preferred his staying in the country,
and following the safe and useful employment of a husbandman.

Through divine mercy and preservation he appears from his early
years to have been favoured with a religious disposition,
being of a careful and sober demeanor amongst men,
and frequent in reading the scriptures:
To gross evils and open profanity he had a fixed aversion;
but in vain amusements and pastimes, by the world termed innocent, he took a delight,
especially in playing at cards, wherein being generally successful,
his delight therein increased, and his thoughts were much taken up therewith;
but he found his pleasure often succeeded by painful remorse,
the convictions of the light in his own conscience frequently
gave him much trouble and uneasiness for many days together,
which brought him to some close considerations concerning the lawfulness of the practice;
and not knowing then of any man that judged it in general unlawful,
he was tempted to conclude,
he might safely play at any time except on first days at night, which he, with others,
had been in the practice of.
Under this persuasion, he set himself at ease for a time;
but as he became further illuminated,
he saw clearly that he must lead a more circumspect and religious life than he had done,
and not join with young people in their pastimes;
yet under this impression he felt a reasoner within himself, persuading him,
that as he was young, such amusements and such company suited his age and time of life,
that he yet might live long,
and that it would be time enough for him to grow religious when he was married.
To this flesh-pleasing doctrine he lent a willing ear for some time longer;
but in the cool hour of consideration his trouble
of mind returned upon him with additional weight,
as he was now sinning against conviction.

Being the only child of his parents, they were very desirous he should marry when young,
and for that purpose proposed a young woman of a
reputable family in the country for his choice.
This proposal appearing to him a matter of great
consequence to his future peace and welfare,
filled him with an anxious thoughtfulness, and prayer to the Almighty,
to prosper the design, so far only, as it might be for their good.
About the same time his religious thoughtfulness increased,
so that if at any time he joined with profane airy company, and partook in their mirth,
it would be succeeded by an additional weight of sorrow.
In this state, an epidemical fever raging in the country, he was visited therewith:
The prospect of probable death filled him with horror and great trouble of mind, fearing,
as he had sinned against conviction, he had no just ground to hope for mercy,
if he should be taken off by this distemper in the state of disobedience,
he apprehended himself to be in,
his only ray of hope was in the probability of divine mercy
being so far extended as to restore him to health,
and to grant him space to repent,
which favour in both respects was mercifully granted to
his earnest prayers in this time of accumulated distress;
and a portion of divine grace enabled him to keep his resolution,
to order his conversation still more religiously and circumspectly,
than he had hitherto done:
seeking retirement for mental prayer to the Lord in secret places,
to show him the sure way to salvation, being sensible he had not yet discovered it.
He applied himself much to reading the scriptures,
and became a very exemplary and devout attender of the public worship,
and diligently attentive to the doctrine he heard preached there;
but durst not join in the singing as unsuitable to the state of his soul,
under sorrow for his past defects,
and want of strength and understanding by what means effectually to remedy them in future;
for he observed the priests would describe the reward of the righteous,
and the punishment of the wicked; but how to overcome sin and learn righteousness,
he found himself left by them at a loss,
which lessened the esteem of those teachers in his eye.

In this time of his uncertainty and agitation of mind,
some of the ministers of the people called Quakers
came into the neighbourhood of his residence,
a desire of information, which naturally drew him to turn his inquiry on every side,
led him to hear what their doctrine was on this and other religious subjects.
The first of them whom he heard was John Wilkinson,
(formerly an independent preacher) but coming late,
and being discomposed through hurry in getting thither, being stinted in time,
and his observation more outward to others than himself, he writes,
he was little reached.
The next opportunity he had was at a meeting appointed about a mile from his habitation,
to which Robert Barclay, being on his way home, and hearing of the meeting, came,
and appearing there in a clear and convincing testimony,
his understanding was much opened into the nature of that
spiritual religion he wanted to be acquainted with,
and his convincement of the truth of his doctrine in a great measure effected.
Soon after Thomas Carleton and Thomas Langhorn were
at a meeting appointed near his house,
to which he went.
These men, by their ministry and conversation,
were instrumental to his more clear and effectual convincement,
as well as that of sundry others.
And the report of this convincement on the borders
of Scotland reaching the ears of friends,
John Wilkinson aforesaid paid them another visit,
and appointed another meeting amongst them; in which,
through a divine power attending his ministry and overshadowing the meeting,
many more were convinced.

After some more meetings amongst them,
they were encouraged to keep up a meeting among themselves for solemn worship,
though in silence, which they did; and their number increased,
notwithstanding they had no outward ministry; many also were convinced in judgment,
who had not fortitude to join the society,
it being a time of hot persecution under the last act against conventicles,
but for a while waited to see how it would fare with those,
who had openly professed themselves Quakers.
These newly convinced friends were soon made partakers with
their elder brethren in the sufferings of this season,
through the rapacity of informers.
One Gilbert Atkinson, who had formerly been a man of repute,
falling into frequent intoxication and other vicious courses,
lost his reputation and his property, and in order to repair the latter turned informer;
made great spoil of friend`'s goods,
and was instrumental to the imprisonment of many of them.
But, like many others of this infamous class, his ill-gotten gains did him little good.
Attending the sessions at Carlisle, in order to appear against friends in prison there,
and prevent them from getting their liberty, he was arrested for debt,
and cast into prison, where he fell into great poverty and want,
in which state he was often relieved by some of this people,
who he had grievously persecuted, and at last finished his days in prison.

It was now that king Charles`'s declaration for liberty of conscience was published,
whereby this people enjoyed a respite from suffering,
and their number in this corner of the nation was considerably increased,
many of those who had stood off,
seeing the divine preservation attending their innocence and steadfastness,
joined them in society, and diligently attended their meetings,
which were still held in silence,
except when friends in the ministry from abroad came to visit them.
Yet in those silent meetings they were often favoured with divine consolation,
and grew in grace and the inward experience of the work of simplification,
whereby they were fitted for the reception of spiritual gifts.
Among these Christopher Story was one who received a share in the ministry,
to which he was very backward to give up,
though often exercised under the burden of the word, for fear of missing his way,
or bringing forth unripe fruit, but at last gave up to the divine requirings,
in uttering a few words to his great peace and rejoicing in spirit;
and through diligent attention to the opening of counsel,
and instruction of the spirit of truth, he grew in his gift,
and became an eminent minister of the word of reconciliation and salvation.
This was several years after his convincement;
but it was not long after his appearance in the ministry,
till he thought it his duty to travel in the work thereof to Scotland.
His succeeding journey to the yearly meeting of London,
and thence westward in company with John Banks, hath been before noticed.
He continued in frequent journeys to exercise his ministerial labours,
for the edification of his brethren, and the convincement of many others,
through most parts of England, Scotland and Ireland, often more than once.
He was also concerned, particularly in his native county,
to appoint meetings amongst those of other societies.
His service was great, and his ministry well approved, at home and abroad; being plain,
powerful and affecting in his testimony,
reaching the hearts and consciences of his hearers.

In conducting the affairs of discipline in the church,
his abilities were equally conspicuous.
In much wisdom and prudence he exerted his endeavours
to preserve his friends in a blameless conversation,
and in faithfulness in every branch of their christian testimony.
Against undue liberty, excess and superfluity of every kind, he was remarkably zealous;
yet his zeal being tempered with meekness,
and his own example marked with circumspection, abstinence, simplicity and gravity,
they produced an awful respect, and frequently gave efficacy to his zealous labours.

He was diligent also in his endeavours to preserve the peace of the church uninterrupted,
and to keep out every incentive to strife and debate;
he had also an excellent talent for accommodating differences or misunderstandings,
when anything of that kind happened.

Although this friend was not convinced till the season of
persecution was pretty far advanced towards its period,
yet he had a share of the sufferings to which this society was still exposed.
From the time Atkinson the informer had been cast into prison,
the friends in these parts had been pretty much unmolested,
except some distresses taken for Sunday shillings (as they termed them)
and an attempt to prosecute them as popish recusants for 20. a month;
but for want of an informer these prosecutions do not appear to have been carried through.
At last, in 1682, one James Appleby from Yorkshire undertook the office,
and procuring one Story to join him, they came to Christopher Story`'s,
the meeting being there, and made information before Henry Forster, a justice,
against several being met together, and among others, that Christopher Story was there,
although at that time he was in Lancashire, above forty miles off.
A warrant was issued for making distress,
but the officers were backward to execute the warrant in his absence; and the informer,
sensible that his perjury was generally known,
thought it safest to abscond for the present, whereby, for this time,
he was disappointed of his prey.

But as soon as he thought the danger over,
this informer returned to his infamous occupation,
made information of another meeting at Christopher Story`'s,
procured a warrant from justice Aglionby to distrain for the fines;
but the constables being still backward to distress their neighbours,
were very moderate in their distraints,
which not suiting the views of the insolent informer,
he brought one of them before the justice, and had him bound to his good behaviour;
and had afterwards a general seizure made of Christopher Story`'s goods,
of which they proclaimed a public sale; but such was the detestation,
the plunder of informers was now held in, that nobody would come to buy.
He took the horses and sheep to distant fairs; sold the horses at half price,
and the sheep were scattered and dispersed about
the country by the people and their dogs,
when they knew who the man was, and how he came by them;
he also had Christopher`'s corn seized, but could get nobody to thresh it.
He again informed of another meeting to Henry Dacres, justice,
against Christopher Story for preaching there,
who was accordingly fined 20. for which the officers took several cows and young cattle;
but these officers acting against their will, when they took them to market to sell,
took care to have the people informed, what kind of goods they were.
The informer upon this complained to the justice,
who accordingly bound one of these officers also to his good behaviour.
While the distresses remained indisposed of, king Charles died,
which much weakened the informer`'s power;
for then the justices would listen to none of his complaints,
so the goods seized were not sold.
Yet Christopher, with others of his friends, were bound to appear at the assizes,
and for refusing to give bond to traverse the indictment were committed to prison,
where they continued until king James granted them a general release,
and then the persecution generally ceased.

For his eminent qualifications for service in the church;
for his diligent discharge of duty in a long and constant
course of ministerial labour at home and abroad,
and for his faithfulness as a shining example of
consistency in a circumspect and religious conversation,
he was greatly beloved and respected amongst his brethren.
And as he was also endowed with a good understanding
and a sound judgment in temporal affairs,
in moral and civil rights, and in great repute for integrity,
he was often employed in the good work of ending differences,
and composing litigations among his neighbours of other communities,
and with remarkable success, with that equity, skill and address,
as to give satisfaction to both parties, a point not generally attained.

As old age overtook him, and his body declined in strength,
his mental faculties discovered no symptom of decay; his memory and understanding,
his zeal and fervency continued unimpaired.
He was seized with a consumptive distemper,
which increased upon him about the space of nine months,
during which time he continued his attendance of religious meetings at home,
wherein he was frequently favoured,
so as to manifest that he retained his inward strength,
by the lively and affecting testimonies he bore during his bodily weakness.
And much excellent counsel,
and edifying advice he imparted to his friends who came to visit him in his sickness,
and also to his children he gave much tender and fatherly admonition.

And having lived a life of righteousness,
devoted to the service of his maker and mankind, he had hope in his death,
which happened at his own house at Righead the 6th of the 11th month 1720,
and he was interred in friends burying ground at Hetherside;
his funeral was attended by a multitude of friends and others, remarkably numerous,
evidencing the general estimation of his character amongst his neighbours.

The king this year, going to visit his electoral dominions,
was suddenly seized with an indisposition on the road, which proved mortal;
he expired at Osnaburg the next day, being the 11th day of the month called June,
in the 68th year of his age,
having reigned near thirteen years with wisdom and moderation.
