== Chapter III. Ireland.

[.chapter-synopsis]
* Visit of Benjamin Holme and John Burton
* John Burton returns home
* Benjamin visits Londonderry and several other Places, where there are no Meetings of Friends
* Is imprisoned at Longford
* Address to Government on Occasion of the Rebellion
* Thomas Story visits Ireland
* At Kilkenny is persecuted by the Bishop of Ossory

Benjamin Holme, a friend of Yorkshire, a man of ancient simplicity,
who resigning all worldly concerns and cares,
having an estate or income sufficient for his few wants,
gave up most or all his time to travel about for the edification of his friends,
generally visiting them in their families, as well as their meetings;
came over to Ireland this year, accompanied by John Burton,
from the northern part of the same county,
for the spreading the true knowledge of the principles
of this society amongst other people;
he was an able and powerful minister of the gospel,
a man of good sense and strong natural parts, refined by religion,
more than by education, in whom a peculiar wisdom in conduct,
in his ministry and in his judgment was concealed
under the rustic appearance of the simple husbandman.

After visiting the meetings of his friends to returns, their edification,
John Burton returned home; but Benjamin having a further prospect in view,
with stayed longer, and then took his journey to Londonderry,
accompanied by Patrick Henderson, with a view to get a meeting in that city;
but the magistrates would not permit it, dispersing all the people who were assembled;
whereupon Benjamin wrote to the mayor, showing how disagreeable it was to Christianity,
thus to treat men,
who under a religions concern came only to call the inhabitants to repentance.
They also wrote to the inhabitants of the city,
reminding them of the late calamities they had suffered,
and the merciful deliverance they had providentially received,
and their sudden forgetfulness of this great mercy,
warning them of divine judgments for their ingratitude and provoking sins,
if they did not timely repent.

After this the said friends had several meetings in the said county,
and in the county of Donegall, amongst a people to whom the Quakers, so called,
and their principles, were little known.
Benjamin had several meetings of the same kind in the provinces of Munster and Connaught;
at Sligo, a few had lately been convinced, whom he felt a particular concern to visit,
in order to strengthen and encourage them in the way to peace.

In the second month, 1713,
Benjamin and three friends came to Longford with the like purpose,
and having obtained a room at their inn for a meeting,
they went to invite the people and acquaint the sovereign of the town,
who told them he had no objection against their holding a meeting,
but desired them to acquaint Benjamin Spann of it,
who was both a justice of the peace and priest of the parish.
In consideration of his office as a civil magistrate
they thought it proper to wait upon him also,
to apprize him of their purpose;
but he quickly discovered in what light he held the toleration,
abruptly telling them with great indignation they should have no meeting in that town.
Benjamin Holme replied, they did not come to ask his leave,
but as a magistrate to inform him thereof and pleaded
the Queen`'s toleration for liberty of conscience,
and so they parted.
But the landlord hearing of Spann`'s prohibition, told them,
that in this circumstance he durst not by any means suffer a meeting in his house,
for that Mr. Spann would ruin him.
Whereupon Benjamin Holme and Benjamin Parvin, going to seek another place,
met the said priest in the street, who accosted them afresh upon the occasion.
Benjamin Holme renewed his plea of the Queen`'s toleration.
The priest in wrath denied,
that either man or woman in England or Ireland could grant a toleration.
Benjamin Holme desired him "`to do as he would be done by.`"
The priest replied, "`that is no rule to me.`" His passion being greatly raised,
he called for a constable; but none appearing,
he seized him, and seeing the jailer near, commanded him to take him into custody;
and so leading him by one arm, and the jailer by the other,
they put him into the dungeon, and after some abusive language,
laid hold of Benjamin Parvin, and delivered him to the jailer,
who by his orders confined him in the same place,
where they sat together in great peace and contentment for about six hours,
and then the jailer removed them to an upper room,
where several friendly persons came to see them,
and among them one who brought them a discharge from the priest,
upon condition they should promise not to come again,
nor hold any meeting in or near Longford: They told him they could make no such promise,
for that no true minister of Christ was his own master,
but must answer the requirings of him, who called them into his work and service.
They were locked up that night in the room,
where they lay on the boards in their great coats and boots.
The jailer understanding they would demand their
liberty at the expiration of twenty-four hours,
as they were arbitrarily committed without a mittimus showing any cause,
waited upon Spann, who then granted a mittimus,
charging them with coming in contempt of the Queen`'s authority,
by force and arms in a hostile manner,
to hold a Quaker`'s meeting in the borough of Longford.

This charge they denied as false in every part of it,
and particularly that it was not they who contemned the Queen`'s authority,
but the priest, who had publicly declared,
that neither man or woman in England or Ireland could grant a toleration for liberty
of conscience,`" and who had violated the toleration granted by the legislature,
in imprisoning them; which being reported to the priest, he said,
he wished he had never seen them,
and in the evening sent an order under his hand to the jailer to set them at liberty.
By reason of the rebellion which broke out in Scotland,
the friends in Ireland thought it requisite at this
time to testify their affection to the government,
which was done by the following address to the Lords justices.

[.embedded-content-document.letter]
--

[.letter-heading]
To Charles Duke of Grafton, and Henry Earl of Galway, lords justices,
and chief governors of Ireland.

[.blurb]
=== The humble address of the people called Quakers, from their national half-year`'s meeting held in Dublin the 10th of the ninth month, 1715:

[.salutation]
May it please the Lords Justices,

The many and great privileges continued unto us under
the king`'s mild and favourable government,
and those in authority under him,
more especially that we have liberty peaceably to worship
Almighty God according as he hath persuaded our consciences,
we esteem great blessings,
and lay us under great obligations of humility and thankfulness, first to God,
and then to the king, for the same.

The king having been pleased to place you chief governors of this kingdom, we take leave,
in our plain way, to congratulate you upon your safe arrival here,
and to assure you that we are well affected to king George and the present government,
and have a just detestation and abhorrence of all conspiracies,
in plots and rebellion against the king and government
and that it hath been our declared principle,
as well as practice, ever since the Lord called us to be a people,
to live peaceably and behave dutifully toward those,
whom he hath placed in authority over us, so, by divine assistance, we are resolved,
according to our duty,
to demean and behave ourselves towards the king and those in authority under him.

And as we are a people liable to sufferings for our tender consciences towards God,
we entreat, that if any such thing should attend us under your administration,
you will be pleased favourably to admit us to lay our suffering case before you,
in order to seek for redress.

We sincerely pray to Almighty God, that he may endue your hearts with,
divine wisdom so to govern, that virtue and piety may be encouraged,
and the contrary restrained, that so his blessing may attend you here in this life,
and eternal happiness in that to come.

--

Thomas Wilson and several others by appointment of the national
meeting came over to the yearly meeting of London as usual,
and at this time with a particular view to join with their brethren in England,
in soliciting further ease with respect to the affirmation,
which was uneasy to friends in Ireland In a general way,
some of whom had been great sufferers,
because their consciences would not allow them to make use
of the affirmation in its original form.

Thomas Story, who was now returned from America, went over this year to Ireland,
and had meetings not only with his friends, but among strangers,
in places where no friends resided, and where the society was little known,
amongst whom his service was generally well accepted,
and he met with little interruption until he came to Kilkenny,
the inhabitants of which city are generally of the Romish communion,
or Protestants of the high church class,
being the ancient residence of the Dukes of Ormond,
and at that time under the influence of a lordly high priest, Vesey, bishop of Ossory,
whose palace is there.
Here are few dissenters of any class except papists;
and this bishop seemed much disposed, as far as he had power, to suffer no other.

Thomas coming to the city, in company with sundry other friends, with a view to procure,
a meeting amongst the inhabitants,
a proper place being procured and fitted up with seats,
and the meeting gathered according to appointment, Some time after Thomas had stood up,
and was proceeding in his testimony, there came in two men,
Arthur Webb and Robert Shervington, and commanding him to be silent,
and the people to disperse, he took no notice of them for some time,
but proceeded in his testimony,
until they disturbed the meeting to that degree that
the people were not in a capacity to hear;
then he stopped and asked them who they were, and by what authority they acted thus?
They answered, they were the church-wardens: He replied,
the church-wardens had no authority by the virtue
of their office to meddle with their meeting,
nor power to hinder it; so desired them to desist, and sit down peaceably as others did.
Seeing Thomas and his friends no wise alarmed or terrified by their intrusion,
as they expected, they ordered the people to disperse,
threatening them with the Bishop`'s court, and began to take some names,
which some observing went out, but the greatest part stayed,
being displeased at the spoiling of the meeting which had begun well.
Soon after came one Joseph Wortey, sergeant at mace, and a constable along with him,
while Thomas was still standing and exhorting the people as he could get opportunity;
they desired him to come down,
for they had a warrant from a justice of peace to apprehend him,
and disperse the meeting.
Thomas told them the Quakers were well known to be a peaceable people,
and subject to government, and desired them to have a little patience,
till he had cleared himself to the people, to which they discovered no aversion,
till some of the superior persecutors cried out, "`How well you execute your warrant?`"
They then took him, Edward Cooper, Henry Ridgeway and John Harris away,
in custody to the justice`'s house, but he would not be seen,
being troubled that he had been drawn in to sign the warrant,
which was brought to him ready drawn up by Robert Connell the bishop`'s register,
and sent to him by the bishop, desiring him to sign it;
it was with reluctance he complied; they took them to other justices,
who evaded interfering; till at last they were taken before the mayor, and this Connell,
who being an alderman, was a justice of the city by his office;
they charged them with holding a riotous and unlawful assembly, which being denied,
Connell acknowledged they were not making any disturbance,
but still it was an unlawful assembly,
the act of toleration in England not extending to Ireland.
This position Thomas Story endeavoured to disprove;
these magistrates then required security for their appearance at the assizes,
and for their good behaviour in the meantime; this was refused;
the justices wrote a mittimus,
but at last dismissed them with menaces of the consequences,
if they should attempt to hold any more meetings there.

As these menaces proceeded from a very different disposition to that which the king
(to whom the bishop and his adherents were suspected to bear no true allegiance) and
superior order of magistrates discovered to this people at this time,
they were no way discouraged by them,
but concluded to appoint another meeting next morning;
Thomas had stood up to proceed in his discourse about half an hour,
when the same church-wardens disturbed the meeting as before;
but little notice was taken of them,
till the mayor`'s sergeants and constables came and
took Thomas Story singly a second time into custody,
and carried him before the mayor, Connell and some others, who behaved imperiously,
and gave him threatening language.
He told them they were not to insult the king`'s subjects,
nor vent their own passions upon them; that if he had broken the law,
he was subject to the law; and if they acted without law,
they also were punishable by the law.
They again required sureties for his appearance at the assizes,
and for his good behaviour,
and upon his refusal committed him to jail with the following mittimus.

[.embedded-content-document.legal]
--

[.blurb]
=== City of Kilkenny, ss. By John Birch, Esq; Mayor of the said City, and Robert Connell, Esq; one of his Majesty`'s justices of the Peace for the said City.

We herewith send you the body of Thomas Story,
he unlawfully assembling himself with several other persons,
and refusing to find sufficient security for his appearance next assizes,
and for his good behaviour, and him to keep, till thence discharged by the course of law;
and for so doing this shall be your Warrant.
Given under our hands and seals this 28th day of February, 1716.

[.signed-section-signature]
John Birch, Mayor,

[.signed-section-signature]
Robert Connell.

[.signed-section-context-close]
To the Keeper of his Majesty`'s Jail of the said City, These.

--

By this mittimus he was sent to the town jail,
and put into the common ward among thieves, in irons;
but was not suffered to stay there very long for Anthony Blunt, the sheriff of the city,
a very civil young man, well affected to the king,
in resentment to the malicious and arbitrary proceedings of the opposite party,
took him out of the common prison to his own house,
where he was provided with a very good room and agreeable accommodations,
to the disappointment of the bishop.

The account of his imprisonment brought friends from several parts to visit him,
and many stayed in town till the first day;
they where he had a meeting in the sheriff`'s house,
his wife and family and many persons of the neighbourhood being present,
wherein Thomas Story bore his testimony against Antichrist and his ministers,
to the ease of his own mind and the satisfaction of his audience.

The next day,
going in company with some friends to take the air in the duke of Ormond`'s gardens,
he was accosted by several persons,
whom curiosity drew to enter into conversation with this prisoner at large;
among the rest justice Warren, who granted the warrant for apprehending him,
and acknowledged his sorrow for it; and Alderman Haddock and others,
who entering into conference with him, began to discourse about his confinement,
at which they freely expressed their indignation.

In the meantime the mayor and alderman Connell also came in a great chase,
which was heightened when they saw these persons in friendly conversation with him.
As they advanced towards them, Thomas began to speak to his company,
concerning the grounds upon which they founded their proceedings,
viz. a supposition that the toleration act did not reach Ireland,
which Thomas proceeded to refute,
showing that the act extended to all the king`'s dominions;
that this had been the intention of the king and his predecessors,
since the law was made, and that upon several addresses presented to him by friends,
the king had assured them of his protection,
particularly on one from the last yearly meeting of London,
when Thomas was present with many others,
he was pleased to answer their address in these words,
"`I thank you for your assurance of duty and affection to my person and government,
and you may always depend upon my protection.
"`But it seems,`" continued he,
"`the mayor and the magistrates here insist in an opinion quite opposite to this,
at the hazard of what may follow;
for you may assure yourselves we are as jealous and
tenacious of our gospel and natural liberties,
as anybody here can be bent to deprive us of them.`"

The Mayor and his party discovered great rancour.
They immediately applied to Justice Warren to join them in sending him out of the county,
for their own jurisdiction extended out of the no farther than the precincts of the city.
But the justice refused,
telling them he had done too much of this drudgery for them already,
and would have no further concern with them, but leave them to their own measures.
This vexed them greatly, and occasioned more words, which grew pretty hot on both sides,
till the justices and their party, who were for the king and indulgence, asked them,
how they came to connive at so many masses in open view,
and be so furious upon the king`'s friends and peaceable subjects?
"`And pray Mr. Mayor,`" said he,
"`what notice have you taken of the seditious sermon
you heard yesterday in the little church?
you can hear such with pleasure,
whilst you treat these loyal subjects with so much severe usage; did you, Sir,
demand that person`'s notes, and bring him to account for it?`" The mayor replied,
"`that was my lord bishop`'s business, not mine.`" "`If that was not your business,
being a matter of religion,
pray how comes it to be so much your business to meddle with these people,
who have given you no other occasion but about their religious opinions,
to which they have equal right and liberty with other
his majesty`'s protestant subjects.`"

This discourse plainly discovers the temper of both parties,
and of what class the persecutors were; and it had that effect upon the mayor,
that when he grew cool the next day, he took up the mittimus,
and sent Thomas Story word that he was at liberty,
and might go when and whither he pleased; and made an apology for his conduct,
that he would not have done what he did,
but that the Clergy as one man strongly urged him to it,
by telling him they had thought him a man for the church, but to find him so remiss,
looked quite otherwise;
that for his own part it gave him no concern what meetings they had,
and was glad he was now like to be out of the way,
being obliged to attend the judges at the assizes
at Wexford as deputy clerk of the crown,
hoping all would be over in his absence.
Yet he was again drawn in by the bishop to repeat the like treatment.

Many friends from divers places being come to visit Thomas Story,
they concluded upon another meeting next first day in the same place,
in which was interrupted in like manner as the former had been,
and Thomas again taken prisoner, and after him William Brookfield of Dublin,
who stood up to speak after Thomas was taken away; they stayed but a short time,
till the sheriff again took them to his own house.

Connell, the bishop`'s register,
held the office of deputy-mayor during the mayor`'s absence,
and apprehending him still a prisoner under the Mayor`'s mittimus, not knowing,
or not owning the knowledge of its being taken up,
he had caused him to be taken and confined as a prisoner at large,
but finding his mistake dismissed them for that time.

They met again about three o`'clock in the afternoon of the same day,
and the bishop hearing of it, told one of the sergeants, if they met again,
he would have him put them in the stocks, till he came from Church;
but many people gathering, after a time of comfortable silence,
under a sense of the divine presence, Thomas stood up to speak,
and had gone on for some time, the people being very still,
very well satisfied with what they heard, and very desirous to hear him out,
when the constables and sergeants came again,
but being grown weary of the invidious office, with great reluctance and with apologies,
and so faintly, that they could hardly touch him;
and one of them naming the bishop to be concerned,
furnished Thomas with an occasion to remark,
they were not ignorant all this time,
who was at the bottom of these persecuting measures,
but now they heard plainly it was the bishop.

The officers taking him away, it gave great offence to the people,
many of whom followed them,
calling out "`shame.`" Thomas advised them to avoid disturbance,
that no advantage might be taken.
The officers, abashed and troubled, expressed their concern,
that their offices should subject them to actions so contrary to their inclinations,
entreated him to walk up to his lodgings till church was done;
he told them he was in their custody, and must go whither they should take him;
whereupon they accompanied him to the sheriff`'s house.
In the meantime the meeting continued; William Brookfield appeared in the ministry;
some constables were there, who stood without,
as if they had no mind to understand or hear anything; the meeting ended in order,
and friends were greatly comforted.

Next morning Thomas left Kilkenny to take some meetings in the country,
with an intention to return thither at the assizes, the latter end of the week,
for he thought it necessary to be there at that time,
as his adversaries had required sureties for his appearance there, which,
though not free to give, yet, conscious of his own innocence,
he esteemed his reputation and that of his profession
called upon him to show himself there,
and thereby demonstrate he feared no legal inquiry into his conduct.

He returned accordingly, accompanied by many friends from different parts,
which made his return soon known,
and raised the people`'s curiosity to see how the affair would terminate.
Some friends went to the judges,
and apprized them of Thomas`'s case and his treatment by the high-church persecutors,
at the instigation of the bishop of Ossory;
and Amos Strettell and some friends of Dublin had procured a letter
from one of the intended Lord`'s Justices to one of the Judges;
for the government favoured friends,
and inclined to do all they could for them in honor and safety.

The judges sent for the sheriff to examine the calendar,
and not finding the mittimus therein,
it appeared that his adversaries had little hopes of gaining anything by a prosecution,
and therefore having exercised their power as far as they durst,
were willing to drop further proceedings,
which must here redound to their discredit and disappointment.
And the judges advised Thomas and his friends to
overlook their proceedings for that time,
which they readily complied with.
That evening the judge in his charge declared it was treason in
any to pull down or deface any public religious meetinghouse,
which having been a practice with the populace,
intoxicated by the cry of Sacheverel and High Church,
was construed by the public as a stroke at the partisans of that faction,
who were in power at Kilkenny.

Thus Thomas being released from the power of his opponents,
and the next day being the first of the week,
he and his friends concluded to appoint another meeting, which was very full,
comfortable and quiet.
Just as Patrick Henderson had kneeled down to prayer,
the mayor`'s sergeants came in very quietly, stayed till he had done,
and till Thomas Story stood up and spake awhile; then one of the sergeants stood up,
and with great reluctance, (as was apprehended) and low voice, said,
he was sent by the mayor to command them in the king`'s name to disperse;
but quickly added, but if you will not, I cannot compel you, and so went civilly away.
Thomas had an opportunity now, for the first time,
to go through with the subject before him, and after a time of supplication,
the meeting concluded.

They had another meeting in the afternoon,
in which they met with no interruption or disturbance.
Yet the bishop finding the former measures ineffectual to accomplish his desire,
was meditating further means of gaining his ends.
He had conceived a notion that the Act of Uniformity passed
in the reign of Charles II. would reach Thomas Story`'s case,
and he was so precipitate as to issue a warrant in his own name,
directed to the sheriff to arrest and commit him to the
common jail for three months without bail or mainprize;
intending to wreak his malice by confining him in
an incommodious common prison the whole time;
for he had sent for the sheriff and reprimanded him sharply,
and threatened to call him before the house of lords,
for giving him the liberty of the town upon his first commitment.

Upon a consultation between the bishop, the mayor and alderman Connell,
the bishop`'s mistake was discovered in giving the warrant himself; for,
by the act upon which he proceeded,
he was only to certify the offence to two justices or mayor,
and then the civil magistrate was to issue his warrant and mittimus.
This error being detected,
it was concluded that the mayor should issue his warrant and mittimus,
which he did accordingly as followeth:

[.embedded-content-document.legal]
--

[.blurb]
=== City of Kilkenny, ss. By John Birch, Esq; Mayor of the said City.

Whereas I received a Certificate,
under the hand and seal of the Right Reverend Father in God Thomas Lord Bishop of Ossory,
in which he certifies, that Thomas Story, a Quaker,
did this day preach in the said City of Kilkenny,
contrary to the Act of Uniformity made in the seventeenth
year of the reign of King Charles the Second.

These are therefore in pursuance of the said Act and Certificate,
to will and require you, on sight hereof, to apprehend the body of the said Thomas Story,
and him so apprehended to convey to the common jail of the said City,
there to remain for the space of three months, without bail or mainprize;
whereof fail not at your peril, and for your so doing this shall be your Warrant.
Given under my hand and seal this 17th day of March 1716.

[.signed-section-signature]
John Birch, Mayor.

[.signed-section-context-close]
To the several Constables, and Officers of the said City.

--

This warrant was served upon him in the evening of the same day at the sheriff`'s;
but the sheriff declared he should not leave his house that night,
whatever the consequence might be.
Thomas soon after procured the act, and read it over carefully,
whereby he was clearly convinced, they had exceeded the limits of law,
the act having no relation to the people called Quakers, their meetings or preaching;
but only to their own parish priests, to reduce them to one scantling,
and uniformity of prayer and Worship;
and to prevent the ministers of Oliver`'s days from
retaining the benefices of which they were in possession,
without an unreserved Conformity to the episcopal church in every respect;
but had no respect to those who preached without pay.

Upon this discovery he told the sheriff it was false imprisonment,
and desired him and others to take down in writing at what time he was arrested,
because there might be occasion for their evidence.
The sheriff seemed surprised that the great bishop
and his counsellors should commit such a blunder;
however he took account of the time.

But it seems probable, that upon further consultation and consideration,
they had themselves discovered their mistake, for next morning, pretty early,
the sergeant who arrested him, instead of conveying him to the common jail,
to which he was committed, brought him a message from the mayor,
that he had taken up the warrant and mittimus,
and that he was at liberty to go where he pleased.
Thomas observed upon this,
that the mayor ought to send him a liberate under his hand and seal,
and not imagine him entirely at his disposal, to toss in and out of jail at his pleasure,
but that he had his remedy at law against him and them who had used him thus.

The sergeant retired,
and a little after the mayor came himself to inform him he was at liberty,
for he taken up the mittimus and destroyed it.
Thomas said,
"`Since that violence by which my just liberty hath been obstructed is taken away,
it is now returned to its natural course,
and if I could find it consist with what I profess,
I might consider of ways and means to do myself justice
against such violent and illegal proceedings;
but as it is a wrong done me for the sake of my religion,
I may probably bear it with patience for that reason,
being sensible of the advantage I have of my enemies.`" The mayor made very little reply,
but civilly departed.

The result of these proceedings was honorable to Thomas and his friends,
and their profession gained ground in the estimation of the public.
Many eyes were opened to see the bishop and his spirit and party,
and what might be expected, if he and they were reinstated in that power,
which they still grasped after and longed for,
at the same time looking with an invidious eye at the toleration,
which deprived them of it.
