== Chapter IV. Ireland continued.

[.chapter-synopsis]
* Friends allowed to answer Bills in Chancery upon their Affirmation
* Act of Exemption from the Penalties of second Eliz
* A Provincial Visit
* First Affirmation Act in Ireland
* Account of John Barcroft
* Alexander Season
* Thomas Wight, and Thomas Wilson

Although the dissenters in general in this kingdom,
and the people called Quakers in particular,
do not appear to have been subject to persecution for their religion to that
degree that they were in England during the reign of King Charles and after,
as, I apprehend, several of the penal laws of that reign did not extend to Ireland;
so as yet they had not received the legal privileges which
their brethren in England had done by the Act of Toleration,
or that for accepting their solemn Affirmation instead of an Oath.
But in the year 1719 they received a partial relief in both cases.
Great sufferings having attended them lately as well as formerly,
through the litigious and fraudulent practices of ill-designing men,
in filing bills in Chancery against them,
where their answers would not be received without an oath,
frequently in order to defraud them of their just dues.
Friends being encouraged by the moderate and indulgent disposition of the present government,
concluded if an act for a plain and easy affirmation could not be yet obtained,
to endeavour to procure a clause in some suitable bill to empower
the Chancellor and the Barons of the Exchequer to receive friends
answers without an oath in such cases as they might think convenient;
and their application was so far attended with success.
For friends in an act of parliament,
entitled "`An Act for the Amendment of the Law,`" a clause was obtained,
allowing friends answers to bills in Affirmation chancery upon their affirmation,
and producing a certificate signed by six creditable friends;
but they did not obtain a general affirmation act till the year 1722,
and then only for three years.

The same year a clause was obtained in an act passed for exempting protestant
dissenters penalties of from certain penalties to which they were liable
allowing friends the privilege (in common with the others) of worshipping
God according to their consciences without molestation.
It was hereby enacted,
that the statute of the second of Queen Elizabeth for the uniformity of common prayer,
whereby all persons are required to resort to their parish church or chapel,
etc. shall not extend to any protestant dissenters, who shall take the oaths of fidelity,
etc. under the like restrictions with the act of
exemption and toleration passed in England in 1688.
And every Quaker, who shall make or subscribe the declaration of fidelity to King George,
of renouncing the pope and pretender,
etc. shall be exempted from all penalties in the aforesaid act,
and shall enjoy all the privileges and advantages as other Protestant dissenters.

The society being, through the favour of divine providence,
and the clemency of the rulers of the land,
exempted from the severe trials and grievous sufferings
to which they had formerly been exposed,
were now exposed to trials of a different kind, viz. a season of peace and prosperity,
which some amongst them, both in this and the neighbouring nation,
were observed not to sustain with that fortitude, wisdom and in flexible virtue,
which their predecessors had maintained, through the severities inflicted upon them.
Complaints were made to the national meeting, in the third month,
of the disregard to the rules and good order of the society,
discoverable in libertinism in conduct amongst many of the youth,
and a negligence and lukewarmness of spirit in the discharge
of religious duties in some of more advanced age;
that an aspiring mind had incited some individuals to extend
in commercial engagements beyond the bounds of moderation,
or beyond the extent of their own capital,
or capacity to manage with reputation and justice,
whereby the property of other men was invaded;
debts contracted above their ability to pay, to the injury of their creditors,
and the reproach of their religious profession.
In order to obviate these and other evils,
a provincial visit was made to the several monthly
meetings in the provinces of Leinster and Ulster;
and Ambrose Rigge`'s warning^
footnote:[See page 12.]
ordered to be reprinted and distributed amongst friends for general caution.

This year several friends, according to usual practice,
were deputed to attend the yearly meeting of London,
to endeavour with their friends there to promote a joint application
for a form of affirmation that might be easy to all friends.
Thomas Wilson, who was one of them,
spent some time in visiting the meetings of friends in sundry parts of England,
and afterwards in the city of London,
in joining his assistance with friends there in their
supplications to parliament for the relief desired,
which, we have seen,
was attended with success in obtaining such a form
of affirmation as made it easy to all friends,
to their general comfort and satisfaction.

And friends in Ireland, who generally disapproved the form of the first affirmation,
and did not expect to obtain a more easy form from the parliament
of that kingdom than they had a precedent for from England,
had made no application on that account till now;
but having Application now a precedent to their mind,
they solicited the legislature of Ireland to grant them the like favour,
as the parliament of England had granted to their brethren there,
and succeeded so far as to obtain an act to accept their solemn affirmation in the same
terms and under the same restrictions as their brethren in England had done,
to continue in force for three years,
and to the end of the then next sessions of parliament.^
footnote:[This affirmation,
which was afterwards made perpetual in 1746 (the 19th year of Geo.
II.) is in these words: "`I, A. B. do solemnly, sincerely,
and truly declare and affirm:`" And no person is entitled to it,
unless he shall affirm in the form aforesaid,
that he is of the profession of the people called Quakers,
and has been so for one year last past.`"
The affirmation will not qualify a person to hold any place under the government,
or to serve on juries, or to give evidence in criminal causes.]

In this year died John Barcroft, of Arkill, near Edenderry.
He was the son of William and Margaret Barcroft, born at Shralegh,
near Rosenallis in the Queen`'s county, in the year 1664.
He was the first friend who came to settle near Edenderry after the wars,
and was principally helpful to settle a meeting in that town,
encouraging a few families of friends to meet together to worship God,
and was very serviceable in that meeting, which since became very large.

His example gave efficacy to his endeavours,
being himself a zealous attender of these meetings, and that not in a formal way,
but under a lively sense of the solemnity of the duty,
he was diligently exercised to wait for power to worship God in spirit and in truth,
according to his requiring, whereby he experienced a growth in the knowledge of God,
and the mysteries of his kingdom; and his heart being thus prepared,
he received a gift in the ministry about the 33rd year of his age.
But being a modest and humble man, he was possessed of great fears,
in the prospect of being called to this service;
the various remarks and censures to which he might be exposed;
his observing some in that line,
who hurt themselves and the people by exceeding the bounds of their gifts,
multiplying words without life, were discouragements in his way, to that degree,
that he lost his hold of the true faith, which gets the victory over fleshly reasonings,
and was left for a season in the dark;
but afterwards it pleased the Lord to cause the true light to re-illuminate
his mind with a clear sight of the duty he required of him,
and then he was strengthened to give up in obedience to the heavenly call,
and in great fear uttered a few words in the meeting,
and in process of time became a diligent and successful
labourer for the promotion of righteousness,
both in his native country and in England;
having visited the meetings in the provinces of Ulster and Munster, severally,
eleven times, in the service of the gospel,
to his own peace and the edification of the churches,
and been ten times at the yearly meeting of London.

His ministry was plain and lively,
in which he was not forward to make a public appearance, without real necessity.
In the management of his outward affairs he was diligent and discreet,
yet fervent in spirit, he kept them so in their proper place,
as not to suffer them to be any impediment to his religious duties,
being freely given up to serve the Lord, his church and people,
preferring the prosperity of truth and righteousness as his chief joy.
His conversation among men eminently adorned his profession; being affable and cheerful,
yet grave, meek and humble, preferring others before himself.
A peace-maker, singularly serviceable in composing differences.
A useful helper in the government of the church, being well qualified for that service,
and his hands strengthened therein, by ruling well his own house.
A sympathizing visitor of the sick and the afflicted; charitable to the poor,
and given to hospitality.

In the first month 1723-4, died Alexander Seaton of Hillsborough,
about the 71st year of his age, and 47th of his ministry.
He was born in Aberdeen county in Scotland,
and at the age of seventeen was put to the college of old Aberdeen,
where he continued about two years.
He afterwards stayed some time at the house of Alexander Forbes of Acorthies,
whose wife was his kinswoman; and they being friends exemplary in conduct,
it pleased the Lord to open his understanding,
so that he was convinced of the truth of our principles in the year 1675,
and afterwards confirmed by being present at a dispute
between Robert Barclay and George Keith,
and some students of the university.
In the year 1676,
he with many other friends was committed a prisoner to the Tolbooth of Aberdeen,
where he was detained nineteen months,
in which time his mouth was opened in a living testimony to the truth,
which he continued after wards to bear when at liberty,
labouring in the gospel of our Lord and Saviour Jesus Christ,
being instrumental to turn people from darkness to light,
and from the power of Satan to God, in Scotland, Ireland and England.

Some time after his marriage he took up his abode in Glasgow, where he resided some years.
The few friends who resided in that city suffered much persecution,
both from the magistrates and the rude multitude, who haling them out of their meetings,
beat and abused them in the streets, frequently to the danger of their lives,
and committed them to prison.
On this account our friend A. Seaton found himself engaged in mind to dwell there,
not only to bear a part of the burden in the heat of that time of persecution,
but also for the strengthening,
comforting and encouraging his brethren to faithfulness
and constancy through their various tribulations,
which had so good an effect, that he was instrumental, by the Lord`'s assistance,
to overcome the persecutions,
so that friends enjoyed their meetings more peaceably than before.
Now finding himself free to leave Glasgow, he took his family over to Ireland,
and settled at Hillsborough, in the county of Down.
He there duly attended meetings at home, as also the monthly and provincial meetings,
in which he was of good service both in doctrine and discipline, having a large,
sound and clear gift in the ministry; and although a scholar,
was not much known as such in his services for the Lord,
not esteeming that learning in comparison of the
gift of God and the operation of his holy spirit,
under which he was a faithful, humble and meek labourer in the work of the ministry,
to the informing the understandings of the ignorant,
and to the comfort and encouragement of Zion`'s travellers; prudent,
considerate and seasonable in offering his gift; powerful in prayer;
in Discipline of a deep and solid judgment, often helpful in difficult cases.
He was a man of a good understanding; of clear and sound reasoning;
of few words in conversation, and little acquainted with the things of the world.
He used daily to devote some part of his time to religious retirement,
and adorned the doctrine of our Lord Jesus Christ,
by a solid deportment and exemplary conversation.
In the latter part of his time he was much afflicted with bodily weakness,
which he bore with patience and resignation, and died in great peace and quietness,
having, among many other sweet expressions on his deathbed, declared,
that he had partaken of the earnest of that joy which should never have an end.

This year died Thomas Wight of Cork, in the 84th year of his age.
He was the son of Rice Wight, priest of Bandon,
a man zealous in the discharge of his office,
and more devoted and tender in that respect than the generality of that class of men,
and very strict in the education of his children in the established church.
Thomas served a hard apprenticeship with a clothier in Bandon, and whilst in his service,
hearing of a Quakers meeting to be held in that neighbourhood,
he went to it out of curiosity; but finding that the people sat for a long time silent,
he began to be very uneasy, and to think within himself,
that as he had heard the Quakers were witches,
he might be bewitched if he stayed any longer.
However, he waited a little while, when Francis Howgill stood up and uttered these words:
"`Before the eye can see, it must be opened; before the ear can hear,
it must be unstopped; and before the heart can understand,
it must be illuminated.`" These three sentences,
as Francis opened them to the congregation with great clearness and energy,
made a deep impression on his mind,
and he became in a great measure convinced of the truth of the doctrine preached;
but the prejudice of education,
and the shame and reproach he underwent from his
relations for going to the Quakers meeting,
for a while effaced that impression, until Edward Burrough came into those parts,
whose preaching was so powerful and reaching to the state of his soul,
and accompanied with such an evidence of truth,
that he was no longer able to withstand it.
He now resolved, through divine assistance,
to be faithful according to the light received,
through all difficulties that might attend;
and indeed he became a proverb and a by-word among his relations and acquaintance,
but he bore it with exemplary patience.
Being rejected by his relations, he lived some time with his master,
who had a great respect for him,
on account of his singular faithfulness and trustfulness in his service.

In the year 1670 he married, and in process of time had a numerous family,
whereupon he engaged in a considerable degree of business,
and in all probability might soon have acquired a large share of worldly riches;
but he was stopped in the pursuit hereof by an illumination, as he thought,
deeply affecting his mind with a sense to this purpose,
that he could not be heir to two kingdoms.
Hereupon he grew more retired from the world and the concerns thereof,
and devoted his mind to the service and promotion of truth,
preferring this before transitory riches.
He became an able scribe and clerk for the meeting of Cork, and province of Munster,
from the year 1680 till his death,
discharging this office from a religious impression
on his mind and zeal for the good cause.
He was the person principally concerned in compiling an historical
account of the rise and progress of friends in Ireland,
which he finished to the year 1700.
He was a man of an exemplary life and conversation,
and good conduct in the education of his children; a pattern of plainness,
and a diligent attender of meetings both at home and abroad,
being zealous for the promotion of truth.
He was seized with an indisposition which proved mortal in the 9th month 1724,
under which he showed great composure of mind and resignation to the Lord`'s will,
and on his death bed testified his great satisfaction,
that he had not put off the great affair of the salvation of his soul to the last,
signifying that God had sealed his salvation to him,
to the great comfort of those present.

In this year Thomas Wilson of Thornwell, near Edenderry, in the king`'s county,
departed this life.
A man, who under an unpolished exterior covered great mental abilities,
natural and spiritual.
He was born at Soulby, in the parish of Daker, in Cumberland.
His education was in the way of the church of England, as to religious profession;
but he had little advantage thereby,
in the improvement of his understanding by literary knowledge,
being plainly an illiterate man.
Yet by faithfulness to the discovery of the divine light,
he became well instructed to the kingdom of heaven,
and well qualified to instruct others in the way of life and salvation.
In his early youth, from a religious turn of mind,
he gave a diligent attendance to the public assemblies for worship, to hear sermons,
and repeat them as acts of religious duty, and so zealous,
as that sometimes after sermon in the forenoon he would travel
several miles on foot to hear another in the afternoon.
But he found the ear was not satisfied with hearing,
as not being productive of the clear discovery of the way to salvation,
the knowledge of which was the earnest desire of his soul.
And as the singing of psalms was one part of their
devotional exercise in the public worship,
he found a stop in his own mind from joining in that part of their worship,
from a secret intelligence that men should be made holy,
before they could sing to the praise and glory of God; an attainment which he found,
by an inspection into the state of his own mind, he was too destitute of;
he also found himself disqualified to sing under the present affection of his mind,
which was that of a Godly sorrow, from the heavy load of sin.

About this time he went to a meeting of the people called Quakers,
where a friend exhorted to an inward waiting upon the Lord in faith,
to receive power from him over every unclean thought, by which heavenly power,
men might glorify and praise the name of the Lord,
through the ability of his own free gift.
This affected him greatly, being sensible that this was what he much wanted,
and he was seized with fear and trembling to that degree,
that the table whereon he leaned was shaken, and the cry of his soul was, Lord,
create in me a clean heart! and being made sensible,
that what was to be known of God is manifest in man,
he was drawn off from a dependence on the doctrines of men,
and hearing the priests and repeating their sermons,
to turn his attention to the reproof of instruction in his own heart,
whereby he found sin discovered to be exceeding sinful,
and all the evil that he had done was detected,
condemned and judged down by the measure of light with which he was favoured,
producing that godly sorrow which leads to unfeigned repentance.
In this frame of mind he sat down among friends in their silent meetings,
patiently enduring the dispensation of condemnation for sin,
till by the assistance of divine grace (for which he was fervent in prayer and diligent
in waiting) he gradually experienced judgment brought forth unto victory.

Through a reverent attention to the inward teaching
of the teacher which cannot be removed into a corner,
in their silent assemblies friends becoming heavenly-minded,
and nearly united in love one to another, divine power was much felt,
and inwardly revealed amongst them, when no words were spoken;
and they experienced the washing of regeneration gradually cleansing their hearts,
and the renewings of the holy ghost so filling their souls,
that they were concerned of their fullness to minister to others.
Amongst the rest,
this friend felt it his duty to minister at first in a few words in great fear,
but through fidelity improving the talent, and being enlarged in his gift,
the word of the Lord, through him, was as a flame of fire against all sin and iniquity.
And he soon felt an engagement on his mind,
through the prevalence of the love shed abroad in his heart, to travel abroad,
to edify his brethren with his gift,
and to call sinners to repentance and amendment of life.

His first visit to Ireland was in the year 1682.
He landed in Dublin, and from thence travelled to some other meetings,
particularly in Leinster province,
visiting friends in the counties of Wicklow and Wexford,
and had several satisfactory meetings with them,
after which he gives us this account in his journal.
"`The motion of life in me for travelling ceased, and I durst not then go further,
but returned back to the county of Wexford, and wrought harvest work for some time.
After which James Dickenson from Cumberland came to visit friends,
with an intention to go into Munster,
and the Lord was pleased to open my way to go with him,
and we travelled together in true brotherly love, and had a prosperous journey;
and I saw it was good to wait the Lord`'s time in all things.`"
And when they had travelled through Leinster and Munster, James Dickenson went northward.
"`But,`" continueth Thomas, "`I was afraid of running before my true guide,
(because they who run and are not sent of God can neither profit the people nor
themselves) and so I stayed at work in the city of Waterford about sixteen weeks,
and went from thence to Dublin, and stayed the half year`'s meeting,
which was large and edifying, and from thence took shipping for Liverpool,
and landed there with my former companion James Dickenson.

In the year 1691 he and James Dickenson,
having both had a great exercise on their minds to visit friends in America,
went to London,
and laid their intentions before their brethren there for their concurrence,
which they readily received: But the circumstances of the time were very discouraging,
and the prospect of the probable dangers which might attend them
on their passage thither proved a close trial of their faith;
for the French had a great fleet at sea,
and the general rumour at London represented them to lie in their course,
about thirty or forty leagues from the land`'s end.
This occasioned in them much serious thoughtfulness and anxiety of heart,
with fervent supplications for preservation in submission to the divine will;
under which exercise of mind they received encouragement,
by what they believed a heavenly vision,
to hope for deliverance or preservation from surrounding danger.
James had a clear foresight even of the very manner of their deliverance, and told,
his companion, even while they were both yet in London,
that the Lord had shown him that the French fleet would encompass them,
but that the Lord would send a great mist and darkness between them,
in which they should sail away, and see them no more.

They communicated their sensations to each other with openness,
as companions united in one faith and one lively engagement for promoting pure religion,
before they departed from London; and finding the impressions on their minds to agree,
they were confirmed in their belief of the divine original thereof,
and in faith that it was easy for the Lord to deliver them.
Under this persuasion, in confidence in divine protection,
they embarked the 9th day of 5mo 1691, and after some time fell in with the French fleet,
which chased and came up within musket shot, and fired at them,
when on a sudden a great mist and thick darkness arose between the French and them,
so that they could not see one another.
Then James arose from his seat, and taking his companion by the hand, said,
"`Now I hope the Lord will deliver us.`" Thomas had spent three days in fasting and supplication,
that he who in time past smote his enemies with blindness,
might condescend to interpose in like manner for their deliverance, which, they thought,
was graciously answered by the event, for the French took every ship in their company,
except that in which they sailed and two others,
and all on board looked upon their deliverance as miraculous.
The other two ships coming up,
the captain of their vessel called to those in the other two to come aboard his,
in order to hold a religious meeting with them, which they readily did,
and had a large and good meeting,
in which they were engaged to return their grateful acknowledgments and
thanksgivings to the author of all their mercies for their great deliverance.
They pursued their voyage and landed in Barbados in the 6th month.
Here, in conjunction with his companion, the services of our friend were great,
as also in New England, Rhode-island, Long Island, Jerseys, Pennsylvania,
etc. where many were convinced by his ministry.
His visit was particularly serviceable to friends in Pennsylvania,
happening at that juncture when many were wavering in their principles,
through the opposition and separation of George Keith,
of which an ample account hath been already given.^
footnote:[See vol. 3. page 346.]

He visited Ireland in the service of the gospel several
times before he went to settle there.
In the year 1695 he was married to Mary Bewley, of Woodhall, in the county of Cumberland,
and soon after removed into Ireland, and settled near Edenderry, in the king`'s county.
In the year 1696 he visited friends in England in the work of the ministry,
and again in Ireland after his return home,
still approving himself diligent in the discharge of duty.
He had meetings amongst those of other societies,
in places where there were no settled meetings of friends,
and several were affected by his powerful preaching, that they were thereby convinced,
received the truth in the love thereof,
and continued steadfast in faithfulness thereunto.
From the year 1697 to 1713,
he repeatedly visited friends in the nation of his then residence and in England,
within which space of time he attended the yearly meeting of London seven times.

In 1713 he undertook his second voyage to America,
in conjunction with his former companion James Dickenson,
in which visit he had also great service and great consolation
in be holding the fruits of his former labours there.

His outward occupation was that of an husbandman,
and during the time of his remaining single,
he spent many years in the prime of his days in travels in the work of the ministry,
in Great Britain, Ireland and America, and to keep himself unencumbered,
he employed himself in the humble station of a day labourer.
About the 40th year of his age, entering into the married state, and removing to Ireland,
as aforesaid, he took a farm, in which,
through the divine blessing upon his care and industry, he was greatly prospered,
having an abundant sufficiency of all things needful.
Yet when his outward substance increased,
he was remarkable for preserving his primitive humility and simplicity in his apparel,
his table, his house and furniture; abstaining from all superfluity,
he confined his desires to things which were plain, useful and needful, to the last,
confirming the testimony he had to bear to the simplicity of truth,
by an example of true self-denial in these respects.
And, although he managed his outward affairs with care, attention and skill,
when at liberty to follow them, yet he kept them in their proper places,
not suffering them to prevent him from a faithful discharge of his duty,
as a member and minister of religious society,
when he apprehended a divine call to leave them behind.
He continued a zealous and diligent labourer in the gospel, even in advanced years,
visiting friends in England in the year 1721, and at home until the year 1724,
when his natural strength failed.
And now near the conclusion of his life,
the review of the manner wherein he had spent his time, in the best service,
that of his Maker, and of mankind,
in sincere endeavours to promote religion and righteousness in his generation,
was now his consolation and crown of rejoicing.
Yet as he was always an humble-minded man, so with respect to himself,
near the finishing of his christian course, he said,
"`Notwithstanding the Lord hath made use of me at times to be serviceable in his hand,
I have nothing to trust to,
but the mercy of God in Christ Jesus.`" But was not without an evidence
of his everlasting peace in the kingdom of heaven.

As a minister he was very careful to wait for fresh ability to minister to edification,
under the renewing of the Holy Ghost, under which sacred influence,
he was often deeply opened into the mysteries of the kingdom of heaven,
and his ministry attended with a reaching power and gospel authority,
had a very prevalent effect upon his audience, where by many were convinced,
many were converted to righteousness and confirmed in the truth.
The excellency of his gift hath often affected strangers with surprise,
to find such depth of matter, pertinence of expression and affecting energy,
under an appearance of rustic simplicity.

He was also zealously engaged to give his assistance with his brethren in.
keeping the hedge of discipline and good order in the church,
under the like lively frame of spirit and authority of the gospel;
his sentiments on the proper qualification for this service,
are contained in the following remarks,
which were found amongst his papers after his decease.

[.embedded-content-document]
--

As I was deeply exercised in my, mind about the things of the living God,
and the holy order of the blessed gospel of the Lord Jesus, it was opened to me,
that all concerned friends that speak in men`'s meetings;
ought to wait for a due inward feeling of the heavenly gift;
and as that gave an understanding, then speak in, and minister in the order of Jesus,
which is holy, and all that then speak will be for promoting the way of truth,
and keeping all the professors thereof in faithfulness and true obedience to the Lord.
I being thus in a travail of spirit,
the state of men`'s meetings as they now are was set before me;
and I saw three sorts of men speaking, and they were in three paths,
one sort was on the right hand, where they ran on in their own wills,
and were very fierce for order but not in a right spirit,
they were the cause of long discourses,
and greatly displeased the Lord and his faithful people.
I saw another path to the left hand, and there was a great darkness,
and a stiff-necked people that was for breaking down the orders
and good rules that the Lord has established in his church,
then my soul was filled with sorrow and cries to the Lord,
seeing the great danger both these were in.
Then the Lord was pleased to show me, a middle path, and the Lord`'s people were in it,
and had the strong line of justice and true judgment,
the Lord`'s holy Spirit and heavenly power is their guide.
I am moved to warn all you that are stiff and sturdy in your own wills,
to stand still and turn in your minds to the heavenly gift,
in it is the true wisdom and heavenly knowledge;
and you will learn to know what the good and acceptable will of the Lord is,
and if you speak in the meeting it will be to please God and for his honour,
not your own, for you strive for honour in a carnal mind,
and seek not the honour of the Lord, but are in great presumption.

--
