== Chapter V.

[.chapter-synopsis]
* George II. Accession to the Throne
* Friends address the King on the Occasion
* This Society still exposed to heavy Sufferings for Ecclesiastical Demands
* List of enormous Sufferings of the People called Quakers presented to the House of Commons
* Strongly opposed by the Clergy
* Remarks upon two Pamphlets written against it
* Extracts from the Country Parson`'s Plea and the Answer thereto
* Petitions sent up against the Bill
* Is passed in the House of Commons and sent up to the Lords
* After a long Debate is lost in the House of Lords
* Address of Thanks to the Bishops of London and Salisbury
* Remark thereupon
* Defence of the Opposition thereto
* Remarks thereupon

When the account of the late king`'s death was received,
his son George the second succeeded to the government of the British dominions.
Addresses of condolence and congratulation being
presented to him by both houses of parliament,
were followed by many others.
And the people called Quakers, who were real friends to the Hanoverian succession,
esteemed themselves engaged, in point of gratitude,
for the extension of their religious and civil liberties in the late reign,
and the particular indulgence they had been favoured with therein,
to wait upon the new king with an address upon the occasion.

It hath been before remarked,
that since the revolution and the benevolence of king William`'s parliament
had granted dissenters the act of exemption from the penal statutes,
under which they had so deeply suffered in the preceding reigns,
and the legal rule of the house of Hanover,
had maintained them in the full fruition of the benefits thereof,
that materials for the continuation of this history are less abundant,
than they were previous to that period: of the two subjects of suffering,
to which they were left exposed,
from one they were effectually relieved in the late reign,
viz. that arising from their testimony in regard to oaths; but in respect to the other,
of tithes and ecclesiastical demands, they have been frequently exposed,
since that period, to heavy sufferings both in person and estate.
For although the legislature, which in the 7th and 8th years of king William`'s reign,
granted them the first act for accepting their solemn affirmation,
instead of an oath in the usual form,^
footnote:[See Vol 3. p. 408]
added a clause pointing out an easier and less expensive
method of recovering tithes and church rates (so called)
extending that called the 40s. act to 10£. for Quakers tithe,
to be determined in a summary manner by two justices of peace,
and levied by their warrant: yet as the said act contained no restraining clause,
to prevent the clergy from applying to the more grievous and oppressive
prosecutions in the Exchequer and Ecclesiastical Courts,
many of them manifested a disposition to persecution still,
as far as their hands were not tied up by the letter of the law,
by applying to these more ruinous methods; and when an easy,
ready and expensiveness mode of recovery is in their power,
what is it but persecution to attempt the ruin of a man,
or prosecute him to perpetual imprisonment on account of a conscientious scruple?

About this time a catalogue of such grievous sufferings
was drawn up by the meeting for sufferings,
in order in due time to be laid before the public and the legislature:
but a more perfect one in 1736, which is here subjoined.

An account of many prosecutions carried on against
the people called Quakers for tithes and church rates,
Easter-offerings, etc. under the respective heads, and in the several courts following,
for sums demanded not exceeding ten pounds value,
since the act of the 7th and 8th of king William the third,
which provided for recovering of tithe and church
rates under the value of 10£. in a summary way,
with an account of the prisoners committed by process out of the several courts,
some of whom continued prisoners to the time of their death, some ten years, others less,
whereby several families have been reduced to the necessity
of being supported by the charity of their friends.

[.old-style]
=== Sums demanded and value taken From 1704 to 1722:

James Haviland: demanded: 8£. -- taken: 61£.

Thomas Strong: demanded 1£. 10s. 6d. -- taken: 15£. 11s. 6d.

Richard Case ---- demanded: 13s. -- taken: 37£. 11s. 6d. By sequestration

Thomas Drape ---- demanded: 4£. 10s. 1d. -- taken: 50£.

Robert Holiday ---- demanded: 11s. 6d. -- taken: 60£. By sequestration

Richard Allen ---- demanded: 1£. 15s. 6d. -- taken: 80£. By Do.

Henry Wake ---- demanded: 1£. 4s. 6d. -- taken: 30£. By Do.

Joseph J. Williams ---- demanded: 2£. -- taken: 30£. By Do.

John Taylor ---- demanded: 1£. 5s. 8d. -- taken: 44£. 18s.

Alexander Moore ---- demanded: 6£. 15s. 11d. -- taken: 87£. 16s. 11d. Imprisoned

Jeremiah Ellis: demanded 1£. -- taken: 44£.

George Bewley ---- demanded: 3£. 10s. -- taken: 93£. 10s.

Samuel Tulley & Thomas Warner ---- demanded: 3£. 2s. 8d. -- taken: 75£. 16s.

Willaim Pearson ---- demanded: 13s. -- taken: 19£. 16s.

Jonathan Peasley ---- demanded: 7£. -- taken 236£. 5s. And twice imprisoned

Daniel Williams ---- demanded: 1s. 6d. -- taken:
20£. In goods & estate worth 80£. and 15 months imprisonment

Abram Butterfield ---- demanded: 8£. -- taken: 90£.

Roger Jenkins ---- demanded 14s. 6d. -- taken: 84£. 10s.6d.

Thomas Jenkins ---- demanded: 1£. 5s. -- taken: 67£. 10s.

Thomas Ellwodd ---- demanded: 12s. -- taken: 24£. 7s. 6d.

The above sums are exclusive of their own expense in those suits,
and suffering many imprisonments in the course of the proceedings,
and these are only a few among the many we could produce.

N+++.+++ B. These accounts appear to be drawn up about the year 1728.

In the year 1736,
they also presented a petition and the annexed case to the parliament then sitting.

[.embedded-content-document.address]
--

=== Case of the The Case of the People called Quakers.

In the seventh and eighth years of the reign of king William the third,
an act was passed for the more easy recovery of small tithes, offerings, oblations,
obventions or compositions,
not exceeding the yearly value of 40s. from any one person in a summary way,
by justices warrant;
which was continued by an act of the eleventh and twelfth of the said king,
and was made perpetual by an act of the third and fourth of queen Anne.

In the seventh and eighth years of the reign of king William the third,
in an act for accepting the solemn affirmation of the people called Quakers,
like remedy is provided for the recovery of tithes and church rates from Quakers,
who shall refuse to pay the same,
the sum not exceeding 10£. which act being temporary was continued by a subsequent act,
and was by an act of the first of king George the first,
extended to all rates customary or other rights, dues or payments,
belonging to any church or chapel;
to be paid for the maintenance of any minister or curate in any church or chapel.

These acts, it is humbly conceived,
were intended not only for the ease of the prosecutor,
but also to prevent oppression and ruinous prosecutions.

Notwithstanding which, there have been prosecuted in the exchequer,
ecclesiastical and other courts, in England and Wales,
for demands recoverable by the said act,
above eleven hundred of the people called Quakers,
of whom near three hundred were committed to prison, and several of them died prisoners.

Those prosecutions, though frequently commenced for trivial sums,
from 4d. to 5s. and great part of them,
for sums not exceeding 40s. have been attended with such heavy costs and rigorous executions,
that above 800£. has been taken from ten persons,
where the original demands upon all of them collectively, did not amount to 15£.

By such prosecutions, the favourable intent of the aforesaid acts,
is in a great measure frustrated;
and many of the said people suffer as if no such laws were in being:
though christian charity must admit,
that their refusal of such demands is purely conscientious, since no reasonable man,
considering his circumstances and family would incur
such severe sufferings on any other account.

Tis therefore, humbly submitted, whether such prosecutions,
frequently attended with excommunications and imprisonments,
be not grievances which call for redress,
and whether it be not reasonable to restrain the prosecutors
from proceedings so ruinous and destructive.

--

In pursuance of this petition and case, a bill for their relief,
was brought into the house of commons, and printed;
when the clergy mustered all their strength against it,
whereby they manifested themselves no less eager to hold fast the power of oppression,
which the law had left them, in the recovery of the tithe than the tithe itself.
Three anonymous pamphlets soon made their appearance,
reported to be all the productions of bishops.
Two of them appear so little to the purpose, as to bring little credit their authors,
or little strength to the cause; but the third,
supposed to be written _Codex juris Ecclesiastici Anglicani_ ably answered
by judge Foster) handled the subject more fully and more artfully
in a pamphlet under the title of the _Country Parson`'s Plea,
Against the Quaker`'s Bill for Tithes, etc._
This piece received a copious and spirited answer, in a letter to the author,
by +++[+++one who styles himself]
a member of the house of commons, but was afterward found to be lord Hervey.
But even men of parts and penetration engaged in varnishing a doubtful cause,
will sometimes forget themselves, and yielding to the impulse of reason and truth,
at one stroke overturn all they have been labouring to establish:
thus the country parson, after racking his invention,
endeavouring to show the hardships to which this bill would expose him,
seems in the conclusion fairly to own,
that no wise or good clergyman would apply to any
other than the method prescribed by the bill.
And of consequence he had been laboriously advocating the cause of those parsons only,
who are neither wise nor good.
His antagonist who hath overlooked no part of his plea, upon this paragraph, argues thus,
"`If the wisest and best use it of choice,
this will be an argument that the unreasonable and unjust should be restrained to it;
for are the subjects of England to have no better security
against oppression than the wisdom and goodness of the clergy?
or ought the clergy to be trusted with a power,
which according to the parson`'s confession,
neither a wise clergyman nor a good clergyman can
use without mischief either to himself or his neighbour.
Where the power of oppression is, acts of oppression will undoubtedly be.`"

But the bishops did not trust their cause only to these pamphlets.
Circular letters were written to the clergy, in all or most parts of the kingdom,
in consequence of which, petitions were presented against the bill,
by the clergy of Middlesex, and most other parts of England and Wales.^
footnote:[The country parson`'s respondent remarks, that,
the bill ought to pass were it only for an example,
that it is not in the power of a mitred doctor, by his letter missive,
stirring up petitions from every diocese, to intimidate an house of commons,
in a matter of this high concern to the justice of the kingdom "`I hope,`" says he,
"`a body of English gentlemen will never weigh petitions
in quantity against any bill whatever;
especially bills for the reformation of the church,
against which they are certain of having as many remonstrances, as there are deaneries,
archdeaconries, chapters, colleges or ecclesiastical precincts in England and Wales.`"]
Counsel was heard in behalf of the petitioners,
and several alterations passeth in proposed in the bill,
which after long repeated debates surmounted all opposition,
and was sent up to the lords.

In the house of lords the bill was read a first time;
many petitions were here also presented against it.
The petitioners were ordered to be heard by their counsel upon the second reading,
and it was ordered, that counsel in favour of the bill should be heard at the same time.
Upon the second reading of the bill, they were heard for and against it,
and after they had finished and were withdrawn, a motion was made for commuting the bill,
whereupon a very long debate ensued.

The motion was made by lord H+++_______+++n
(supposed Hinton) supported by lords Hervey and Carteret,
the duke of Argyle and earl of Hay, and opposed by the bishop of Salisbury,
the lord Chancellor, lords Hardwick and Lovell.
But after the merits of the case were debated at large,
the reality of the grievances and the unreasonableness of the sufferings
of the petitioners being too manifest to be evaded,
a new argument was taken up against the scheme of the bill, as it came from the commons;
that it was very imperfect, and so incorrect as to render it unfit in its present form,
to be passed into a law; and that the session was so far advanced,
as did not allow time for altering and amending it.
This being urged as a reason against committing the bill at this time,
and the question being put, upon a division,
it was carried in the negative by 54 not-contents to 35 contents.
The strenuous and united exertions of the clergy,
and the weight of their interest preponderated, and the bill was lost.

In the majority we find fifteen bishops,^
footnote:[The third, the bishop of Litchfield and Coventry,]
three of whom were commonly reported to have early taken up their
pens in opposition to the petition of the people called Quakers,
and the bill in tended for their relief; two of these,
the bishop of London and the bishop of Salisbury seem to
have distinguished themselves by an extraordinary zeal,
not only for preserving the claims of the clergy unimpaired,
but the power of continuing to be vexatious and oppressive in the recovery thereof,
when either their disgust or interest might influence them thereto.
As they are particularly distinguished by an address of
thanks voted by the clergy of their respective dioceses;
the former from the clergy of London to their bishop,
for the many and great "`instances of his care and vigilance
in maintaining the constitution of the church of England,
in its present happy establishment, and the legal rights of the clergy;
and in particular for the steady and vigorous opposition,
which he had lately given to the attempt that hail been lately made upon
them`" The latter from the clergy in the neighbourhood of Devizes,
Wiltshire,
to manifest the grateful sense they "`retain of their preservation
from that strange and unheard of infringement of their rights,
which was lately attempted by the Quakers in their tithe bill,
to return him their humble and hearty thanks, for the indefatigable pains he had taken,
and the firm stand he made, agreeable to the trust and duty of his high station,
in defence of their just and indisputable privileges.`"

From these clerical representations of the proceeding of the people called Quakers,
it seems they think it a criminal design against the constitution of the church of England,
in its present establishment, a strange and unheard of infringement of their rights,
to apply to the.
legislature for a redress of real grievances,
when these grievances arise from the undue exercise of power,
in the hands of the ecclesiastics; and that to oppress, imprison for life,
and ruin a neighbour in his estate or circumstances,
is the just and indisputable privilege of the priesthood.
Whereas, candidly I think it would be more for the honour,
the service and real interest of any church,
to have all such things rectified or removed,
as administer just occasion of offence and reproach,
and are in their own natures indisputably wrong.

In an anonymous piece published about this time, under the title of,
[.book-title]#A Modest Defence of the Opposition Lately Given to the Quaker`'s Bill,#
I find a gross misrepresentation of fact,
either for want of being acquainted with the true state of the fact; or knowingly,
in which latter case the writer is inexcusable, he saith,

[quote]
____
If people suffered themselves to be imposed upon by false representations
of the clergy`'s having abused the liberty out of malice or ill-will,
they know whom to blame.

The Quakers were early challenged with out doors,
to make good a charge so injurious to the character of the clergy,
by assigning particular instances of such abuse.
The same motion is said to have been made, but in vain, in one house of parliament;
and when it succeeded in another house,
the few instances they alleged (not above four or five,
if I am rightly informed) and those so little to the purpose, when inquired into,
as shown how great reason they and their friends
had to guard against the specification of particulars.
And it was astonishing to hear them plead unpreparedness,
after they had represented those abuses in the gross,
(to the number of one thousand) as the only foundation of their bill.
____

Now by the real state of the case it will appear that,

[.numbered-group]
====

[.numbered]
1+++.+++ The people called Quakers made no false representation
of the clergy`'s having abused the liberty,
etc. in publishing a list of the grievous sufferings of their friends,
in cases wherein Reflections they might have recovered their claims in a more easy way.

[.numbered]
2+++.+++ That when they were early challenged to make good their
charge by assigning particular instances of such abuse;
they answered the challenge by producing a specification of the grievances complained
of with as much expedition as the nature of the case would admit.

[.numbered]
3+++.+++ That his information was very wrong, if he was informed,
that the instances alleged "`were not above four or five,`"
whereas they were more than twice as many hundred,
and the greatest part so much to the purpose,
as clearly shown (not how great reason they, and their friends,
had to guard against the specification of particulars,`" but) how great reason
they had to petition for redress of grievances so severe and oppressive.

====

The following cases extracted from which, may, with many others,
clearly evince that the application of this people, for the redress of grievances,
so severe and distressing was very reasonable and requisite, and the opposition thereto,
no instance of a tender regard to the maxims of Christianity or humanity.

=== 1. Grievous Prosecutions for trivial Demands.

+++[+++Bedfordshire, 1707.] William Francis, of Luton, a poor shoe-maker,
was prosecuted in the ecclesiastical court, at the suit of Christopher Eaton, vicar;
for a demand of one groat, for Easter-offerings so warmly,
that the charges of the prosecution came to eighty pounds.
The poor man was excommunicated, and lay close confined in Bedford jail above 19 months,
till an act of grace came out, and set him at liberty.

+++[+++1702.]
Adam Laurence and Eliz.
Vokins, prosecuted in the ecclesiastical court,
at the suit of John Piggott and Thomas Price, wardens of the parish of West-Charlow;
were committed to Reading jail, on a writ _de Excommunicate capiendo,_
on the 18th of the month called January, 1702,
and continued prisoners between fix and seven years,
till discharged by an act of grace in 1709:
a long imprisonment for a demand of about nine shillings from both of them!

+++[+++1703.]
John Tydd of Chatteris, was prosecuted in the Exchequer,
at the suit of William Turkington, parson of Chatteris;
for a demand of thirty-four millings, for two years small tithes,
and was committed to Cambridge castle, on the 14th of the month called August, 1703,
and continued prisoner, above six years and two months,
till discharged by an act of grace, on the 28th of October, 1709.

+++[+++Cornwal, 1704.]
Richard Hitchins, was prosecuted in the Exchequer for tithes,
at the suit of Stephen Hugoe, vicar of the parish called St. Austell.
The parson was advised by several persons of distinction,
to take his tithe by justice`'s warrant;
but he turned the deaf ear to all their persuasions, and would proceed in the Exchequer.
The tithe adjudged him by the barons was but one pound nineteen shillings and six pence,
for which the costs of suit were taxed at thirty-eight pounds; for non-payment whereof,
the poor man was committed prisoner to the sheriff`'s ward, at Bodmin,
on the 13th of the month called May, 1707,
and continued close prisoner there three years one month and two days,
and then removed himself to the King`'s Bench prison at London,
where he remained a prisoner till the 7th of the month called May, 1714:
so that the whole time of his imprisonment was seven years,
for an original demand of one pound nineteen shillings and six pence.

+++[+++Cumberland, 1701.]
Ann Henderson, Widow, and her son Robert Henderson, prosecuted in the Common Pleas,
at the suit of Thomas Story, parson of Banton;
were arrested on the 12th of the Month called June, 1701, (though the writ,
upon search made afterward,
bore date on the 17th.) Upon trial the Jury gave a verdict for one penny damages,
it being for tithe-wool.
They were imprisoned 11 months, and released by an act of grace.

+++[+++Lancashire, 1719.]
Israel Fell, prosecuted for tithes, at the suit of William Turton, parson of Standish;
was a prisoner four years for tithe, but of one shilling value;
and then discharged upon the death of the prosecutor.
298

+++[+++Middlesex.]
William Jackson, Robert Chalkley, Arnold Frowd, John Beale, Jonathan Wood,
John Constantine and John Marshall, were prosecuted in the Exchequer,
for Easter-offerings and small tithes, at the suit of John Wright vicar of Stepney.
The rates set upon Easter-offerings, and tithes claimed by the said John Wright,
in his bill of complaint against them preferred in the Exchequer, were as followeth,

[.small-break]
'''

For Easter-Offerings upon every person: 3d.

A Cock -- 2d.

A Hen -- 1d.

A Goose -- 4d.

A Duck -- 4d.

A Sow -- 1s. 8d.

A Cow -- 6d.

Turnips for every acre sowed in the field -- 4s.

[.small-break]
'''

The said vicar also made claim upon gardens, orchards, calves, lambs, wool and milk,
in his said bill of complaint.
Whereas `'tis known, that the persons aforesaid,
being most of them inhabitants in and near Spittlefields (and John Constantine
in Ratcliff) their places of habitation allow not the keeping such things,
they not using lands; some of them being mean shopkeepers,
and others such as laboured honestly for their own and families subsistence, therefore,
not capable of being stocked or possessed of such goods, as were mentioned in the bill.

The aforesaid prosecution was carried on to the imprisonment of four of the said persons,
viz. Robert Chalkley, John Constantine, William Jackson and John Beale,
who were committed to Newgate on the 8th day of November, 1703, upon attachments,
at the suit of John Wright, vicar of the said parish of Stepney.
The said John Constantine, was discharged from his imprisonment in the year 1708,
being about five years after.

+++[+++Warwickshire, 1705.]
Jane Robinson of Austrey, widow, was prosecuted in the Exchequer for tithes,
at the suit of Charles Wainwright, parson of Austrey.
The parson`'s demand was for tithes of apples, etc.
2s. 8d. and of bees, 8d. the poor widow was committed to Warwick jail,
and lay there about nine months.

+++[+++Westmorland, 1701.]
Thomas Savage of Clifton, prosecuted for tithes, at the suit of Rowland Burrough,
clerk of Browham and Clifton, was arrested and committed to prison,
in the month called January, 1701, and continued prisoner till November, 1702,
for a demand of 3s. 4d. for tithes.
Upon application to the judge who went that circuit,
he was directed to move the court of King`'s Bench, which motion being after ward made,
he was discharged.

+++[+++Yorkshire, 1699.]
Edward Walker of Thornton le Moor, in the parish of little Otterton,
was prosecuted in the Exchequer, at the suit of John Walker, parson of little Otterton;
for one year`'s composition for tithes,
amounting to about 3s. 4d. and was committed to York castle, on the 21st of October,
1699, and remained prisoner about nine years and three quarters,
till discharged by supersedeas upon an act of grace on the 20th of the month called July,
1709.

=== 2. Exorbitant Distraints.

+++[+++Buckinghamshire, 1719.]
Abraham Barber, Thomas Olliffe and Nicholas Larcum, were prosecuted in the Exchequer,
at the suit of John Higgs the elder, and John Higgs the younger, tithe-farmers.
The demand on Barber, Olliffe and Larcum,
was but eight shillings for tithe on all three of them,
and the decree of the court but for four shillings.
They were all taken up by an attachment in November, 1721, and carried to Ailsbury jail.
On the 20th and 22nd of October, 1722,
the goods of the said Abraham Barber were seized for the whole demand and charges, viz.

[.small-break]
'''

7 Quarters and 4 bushels of Wheat, 11£. 0s. 0d.

16 Quarters of Malt London measure, 12£. 16s. 0d.

For a demand of 8s. Taken 23£. 16s. 0d.

[.small-break]
'''

+++[+++1707.]
Thomas Ellwood, Abraham Butterfield and William Catch, were prosecuted in the Exchequer,
at the suit of Joshua Leaper, tithe-farmer under Humphrey Drake, rector of Amersham.

The original demand for tithes on Thomas Ellwood was about
12s. For which he had taken from him household goods,
and an horse, worth 24£. 7s. 5d.

On A. Butterfield 7 or 8£. for which he had taken from him corn, hay, and cattle,
worth 90£. 0s. 8d.

On W. Catch between 7 and 8£. for which he had taken grass worth 8£. 14s
8d and five years rent of a tenant 12£. 5s. 0d. Worth 20£. 19s. 8d.

+++[+++Gloucestershire, 1716.]
Jonathan Peasley, late of Just in the parish of Olveston,
was prosecuted in the Exchequer, at the suit of Benjamin Bayly, vicar of Olveston.
The vicar`'s demand on Jonathan Peasley was for three and a half, or four years,
small tithes of about seven pounds value.
He was committed to Gloucester jail, and the next term,
brought up by _Habeas Corpus_ to the Exchequer, and set at liberty:
But the vicar soon after renewing his suit,
Peasly was brought to the Exchequer again in 1717, and committed to the Fleet;
and proceeded against to a Sequestration,
by which was seized and taken from him in December, 1717:

[.small-break]
'''

14 Cows, 6 heifers and 3 yearlings, valued at 77£. 0s. 0d.

A wheat mow, a bean mow, and about 20 bushels of beans, 19£. 0s. 0d.

2 Beds, 2 Bedsteads and Bedding, 6£. 0s. 0d.

2 Sides of bacon, 10 hundred of cheese, 13£. 5s 0d

All the rest of the goods in and about the house, 40£. 0s. 0d.

Three ricks of hay, 12£. 0s. 0d.

7£. per Annum free land during his life, 70£. 0s. 0d.

For about 7£. value Taken 237£. 5s. 0d.

[.small-break]
'''

N+++.+++ B. The said vicar did threaten to ruin the said
Jonathan Peasley of his stock and estate,
and all that he had: and executed it in a great measure;
for by his seizure the poor man was left not worth ten pounds,
yet had a wife and three small children.

+++[+++Somersetshire, 1712.]
Charles Bewsey and his wife, were prosecuted in the Exchequer,
at the suit of Hugh Lambert, parson of Mudford, for a demand of 7£. 10s. for tithes.
Charles was first taken up, on an attachment in November, 1712.
In September, 1713, he and his wife were committed to prison,
and kept close prisoners from their family of seven children;
and in the month called January following, were brought up to London,
and then had liberty given them till the next term.
On the 15th of the month called June, 1714,
they were again brought up to the Exchequer bar, and committed to the Fleet prison.
In the month called April, 1717,
his goods were seized to the value of 9£. 15s. also
his freehold estate worth about 30£. per Annum,
which with the fruit the first year was worth thirty six pounds:
Also another estate of upwards of twenty pounds per Annum, kept two years, forty pounds.
So that he had taken from him in all,
to the value of 85£. 15s. (beside his suffering imprisonment
above five years) for an original demand of 7£. 10s.

+++[+++Wales, 1721.]
Daniel Williams of Langhorne, in South Wales,
was prosecuted in the Chancery court of the grand Sessions of Carmarthen for tithes,
at the suit of Thomas Philips, vicar.
His demand on Daniel Williams was about 1s. 6d. and his son, not a Quaker,
tendered the vicar 5s. before any prosecution began,
bidding him take his due for his father`'s tithe; but the vicar refused it, and replied,
Daniel must suffer.
He was committed to Carmarthen jail on the 16th of the month called August, 1721.
On the 22nd of the same month he was brought into court, and recommitted to prison,
where he continued about fifteen months.
On the 25th of the same month,
an order of court was issued for entering upon and
sequestering all his estate real and personal;
which was afterward executed: his goods,
worth about 20£. were seized and disposed of without appraisal.
His freehold estate, worth about 80£. was also seized: the persons who made the seizure,
would not permit the said Daniel`'s daughter, then in the house,
to take her own wearing apparel, till persuaded to it, with much ado,
by one of their own company: they turned her out of doors, locked up the house,
and took the key with them.
On the 12th of September, 1724, the said Daniel by his council, moved the court,
that the said sequestration might be discharged;
whereupon it was referred to the register to examine,
and certify whether the same did regularly issue out, or not:
upon his report in the affirmative, the sequestration was confirmed;
and an order of court was made,
requiring the said Daniel to pay the plaintiff his costs of the said reference,
which were taxed at 3£. 9s. 3d.

=== 3. Repeated Prosecutions of the same Persons.

+++[+++Buckinghamshire, 1704.]
John Babington was prosecuted for tithes, four years successively,
at the suit of Ignatius Fuller, parson of Sherington: in 1704,
in the Common Pleas for treble damages: in 1705, in the Exchequer: in 1706,
in the Ecclesiastical Court: in 1707, in the Common Pleas.
The first of which issued in the seizure of his cattle,
to the value of above 40£. for 7£. 16s. demanded.
The second, in his imprisonment in Ailsbury jail, on an attachment.
The third, in his imprisonment there, on a writ _de Excommunicate capiendo._
And the fourth,
in a seizure of his goods to the value of above 100£.
for a demand of 25£. for two years tithe;
one of which appears to be the same,
for which he had been excommunicated and imprisoned before.

+++[+++Cumberland.]
Robert Atkinson, of Laurence Holme, was prosecuted in the Exchequer for tithes,
at the suit of Sir George Fletcher, impropriator.
He was first imprisoned at Carlisle: in the month called May, 1698,
he was removed by _Habeas Corpus_ to London, and committed to the Fleet prison,
about 230 miles from his wife and family.
While he continued prisoner in the Fleet, the suit was carried on to a sequestration,
and in the year 1700, his corn and cattle were seized to the value of 58£. besides which,
in 1701, they made two other seizures,
and detained from him an horse and cow worth 6£. 16s. 6d. in all,
64£. 16s. 6d. for a demand of 26£. An Order was also is
sued for seizing the real estate of the said Robert Atkinson,
but before the attorney had time to execute it; the plaintiff, Sir George Fletcher,
died.

+++[+++1708.]
Robert Atkinson, aforesaid, was again prosecuted in the Exchequer, for tithes,
at the suit of Henry Fletcher, impropriator.
He was committed to Carlisle jail, in the month called May, 1708;
and discharged in the month called July, 1709, by an act of general pardon.
In 1710, the said Henry Fletcher subpoenaed him again into the Exchequer;
but that suit ended soon after by the death of the prosecutor.
He had during the process against him,
his corn and cattle seized at one time to the value of 58£. 1s. 9d. at another
time goods worth 15£. and at a third time to the value of 3£.

+++[+++Derbyshire, 1711.]
William Hancock of Cutthorpe, was prosecuted in the Exchequer,
at the suit of Richard Milner and John Woodward, tithe-farmers,
and again in the next year, 1712, in the Common Pleas.
He was taken up by an attachment out of the Exchequer,
and committed to the common jail at Chesterfield, on the 13th of October, 1711,
and continued prisoner till the 25th of the month called March 1712,
and was then set at liberty by the prosecutor`'s order,
who dropped his suit in the Exchequer;
and soon after proceeded against him in the Common Pleas for treble damages,
got an execution, and for an original demand of 16s. 9d. for six years,
made a seizure of his household goods, and a cow,
to the value of 20£. leaving him nothing of value for the use of his wife and children.

+++[+++Warcestershire 1700.]
Isaac Averill, of Broadway, was prosecuted for tithes, on the statute for treble damages,
at the suit of the Lady Coventry.
The jury found the value of the tithe for three years,
13£. and an execution was awarded for 39£. treble damages:
his goods were taken by distress, to the value of 59£. 10s. 6d.

Isaac Averill, aforesaid, was prosecuted for tithes, on the statute for treble damages,
at the suit of Anthony Stevens, renter, of one fourth part of his tithes.
The tithes claimed by Stevens amounted to at most but 2£. 10s. for which the
goods of the said Averill were seized by William Geatly and William Westwood,
bailiffs, to the value of 31£. 5s.

+++[+++1703.]
Isaac Averill of Broadway, was prosecuted for tithes, on the statute for treble damages,
at the suit of John Phillips, John Davies and William Lampitt,
tithe-farmers under the Lady Coventry, for three fourth parts of his tithes.
The tithe due from Averill for one year, to the renters of the three fourth parts,
on trial appeared to be but 4£. 6. 8d. for which were taken from him grain, hay, straw,
etc. worth 38£. 4s. 4d.

+++[+++1709.]
Isaac Averill, aforesaid, was prosecuted for tithes, on the statute for treble damages,
at the suit of Anthony Stevens, renter, of one fourth part of his tithes.
The said Isaac Averill, for 5£. 5s. demanded by Stevens,
had taken from him in the year 1709, corn, bedding, and other goods, worth 4l/. 4s.

+++[+++1710.]
Isaac Averill was again prosecuted on the same statute for tithes,
by the aforesaid Anthony Stevens.
In 1710, he had taken from him for a demand of 5£. 5s. goods worth 52£. 10s 6d.

+++[+++1711.]
Isaac Averill, aforesaid, was prosecuted on same statute,
at the suit of the aforesaid John Philips, John Davies and William Lampits.
In 1711, for tithes of 13£. single value, he had taken away, his horses, wagon, plough,
cart, and corn, to the value of 65£. 11s.

N+++.+++ B. The said Isaac Averill, at six several times,
for tithes amounting in the whole but to 43£. 6s. 8d. had
taken from him goods worth 291£. 5s. 4d.

=== 4. The following Persons with others laid down their Lives in Prison.

+++[+++Cumberland, 1702.]
Mable Henderson, of Kirkbanton in Cumberland, was prosecuted for small tithes,
at the suit of Thomas Story, priest of Banton, and committed prisoner to Carlisle jail,
on the 7th of September, 1702, and died a prisoner.

+++[+++1715]. Thomas Wilkinson, William Caddy, Anthony Skelton, Richard Kirkbride, John Drape,
senior and John Drape, junior of Holm-Cultrum, were prosecuted for tithes,
at the suit of Joseph Johnson and John Barnes, tithe-farmers.
They were committed prisoners to Carlisle jail, Caddy and Skelton died prisoners,
and the others continued four years.

+++[+++Leicestershire, 1705.]
John Richards of Norton, was prosecuted in the Exchequer, for small tithes,
at the suit of Theophilus Burditt and William Fenwick, priests of Hallaton:
who had first obtained a warrant from Sir George Beaumont, a justice of the peace:
But afterwards declined proceeding in that way,
and determined to take a more severe course, which they did effectually;
for he was committed to jail, and continued prisoner five years, until he died.

+++[+++Somersetshire, 1696.]
William Lyddon of the parish of Withil, was prosecuted in the Exchequer for tithes,
at the suit of William Pratt in the behalf of some children of an impropriator.
Lyddon was committed to Taunton jail, in the month called April, 1697,
and was continued prisoner many years, till he died.

+++[+++Yorkshire, 1699.]
Richard Parrott and Samuel Spanton of Nafterton,
were prosecuted in the Ecclesiastical court, for tithes and Easter-offerings,
at the suit of Robert Jaggon of Nafterton, impropriator or tithe-farmer.
Parrot and Spanton,
were both committed to York castle on a writ _de Excommunicato capiendo,_
on the 13th of the month called March, 1699: The prosecutor`'s demand on Spanton,
was about 30£. for half a year`'s tithes.
After some months close confinement he was taken sick, and not like to live;
his mother entreated the prosecutor to permit him to end his days at home;
but was answered, That if he would not pay, his body must suffer:
So he died there in prison, on the 26th of October 1700,
and the prosecutor died very suddenly about two weeks after.
Parrott, for a trivial sum for oblations, was continued a prisoner above seven years,
being released on the 5th of the month called April, 1707.

+++[+++Yorkshire, 1700.]
Richard Kendall of Hill-house-bank, in the parish of Leeds,
was prosecuted in the Ecclesiastical court for tithes, at the suit of William Hewan,
tithe-farmer.
He was committed to Rothwell jail, by a writ _de Excommunicato capiendo,_
in the month called June, 1700, and died in the same prison,
on the 24th of the month called January, 1702,
after about two years and seven months imprisonment, for 2£. 15s. adjudged by the court.

These specimens, extracted from a great number of others of like kind,
are sufficient proof,
that the people called Quakers did not apply to parliament for redress,
without real and urgent reason;
and every unprejudiced reader will be ready to reflect with the Country Parson`'s respondent,
that, "`The number of suits herein specified, the prisoners, the distresses,
and the vast disparity between the demand and sum exacted in suits for tithe,
must raise abhorrence in any compassionate mind.
The single article of one hundred pounds, taken for eighteen pence,
would be a just reason for abolishing tithes,
if suits for them could not be carried on in more humane methods.`"

The clergy by their exertions prevented the bill for the relief of this society,
from ruinous prosecutions, being passed into an act;
but could not prevent free remarks being made upon the many hard cases,
contained in the specification published at the instance of their advocate,
expressive of censure and dislike of such proceedings.
To prevent or alleviate the disrepute to publish their character,
naturally resulting there from,
the clergy of several dioceses published examinations of these cases,
as far as those of their respective dioceses were concerned.
The drift of these examinations seemed to be to palliate,
and put a deceptive gloss upon facts, which they could not disprove;
and at the same time,
by unfair reflections and uncandid insinuations to
bring the Quakers under suspicion of artifice,
of which they were innocent.
This put them under the necessity of publishing vindications
of their brief account of facts,
and of themselves from the invidious suggestions of their enemies.
In reply to what had been insinuated in one of these examinations,
they allege that they have proved,

[.numbered-group]
====

[.numbered]
1+++.+++ That 1180 persons have been prosecuted.

[.numbered]
2+++.+++ That 302 of them were committed to prison.

[.numbered]
3+++.+++ That 9 of them died prisoners.

[.numbered]
4+++.+++ That the sums sued for were frequently from 4d.
to 5s. that in one case a poor widow and her son,
were imprisoned eleven months on a verdict for one penny for tithe-wool.
And that in another case two persons were excommunicated, and sent to jail;
for a demand of but one farthing each, for a church-rate.^
footnote:[John Walton of Shildon, Thomas Lackenby of Bishop Aukland,
Ralph Dixon of Woodhouse, Love God Murwaite of Bishop Aukland, widow,
and John Dalton of the same, were prosecuted in the Ecclesiastical court,
at the suit of Thomas Sayer and William Slater, wardens, for a church-rate so called.
{footnote-paragraph-split}
The demands were on Walton, two shillings and six pence,
Lackenby, two pence halfpenny, Dixon one farthing; on the widow Murwaite, four pence,
and on Dalton, one farthing; they were all committed to Durham jail,
on a writ _de excommunicado capiendo;_ but several of their neighbours,
troubled at their imprisonment for such trifles, paid the demands of the court,
and got them discharged.
{footnote-paragraph-split}
Such trivial causes of excommunication,
are a degrading of that office,
which ought to be chiefly reserved for a testimony against gross enormities or immoralities.
In these latter cases to allow a pecuniary compensation to buy off the censure,
is priest-craft imported from Rome,
to issue them on frivolous occasions destroys their force, as matters of discipline;
to enforce them in such cases by the civil sanctions of Romish canons,
is an oppressive grievance; and to excommunicate those who were never of their communion,
is exceedingly ridiculous and absurd.
In any civil concern how would that man expose himself to censure and reproach,
who would go to law for one groat or one farthing;
suits for such sums seem peculiar to ecclesiastical demands.]

[.numbered]
5+++.+++ That a great part of those prosecutions V- were for sums not exceeding 40s.

[.numbered]
6+++.+++ That heavy costs and rigorous executions have attended those prosecutions,
of which there are a great many instances;
in some of which the proportion of the sums levied to the original demand,
is greater than that of 800£. for demands of fifteen.

====

The specifications in the account published by friends, therefore,
are so far from being defective, that they demonstrate,
the grievances complained of to be really greater than '`twas represented.

After the perusal of this summary review, can anything be more clearly manifest,
than that the Quakers did not apply for redress of imaginary or pretended,
but of real and very severe grievances;
and the reason why their petition was at last rejected, may,
perhaps be gathered from the following passage in
a defence of reasons for not paying tithes,
viz.

[quote]
____
I think it is more than probable,
that the discernment and moderation of the latter ages having rejected
the principles which were the original foundation of tithes,
would naturally have rejected the tithes also; or if they did not think proper to repeal,
would have modified these tithe-laws with more equal regulations ere now,
were it not that the clergy, still forming a body distinct from the body of the people,
with separate views and interests,
have constantly watched over the interest of the church, improperly so called,
that is their own interests, with a jealousy ready to take the alarm at every attempt,
however reasonable,
which they apprehended had ever so remote a tendency to affect their revenues,
or even their power of inflicting penalties on those who questioned their claims,
and to exert the weight of their united influence,
which from their character and connections is a very powerful one,
to frustrate any such attempt.
____

By the different examinations on the part of the clergy,
and the vindications of their brief accounts the people called
Quakers had a controversy on their hands till the year 1740,
by which time they received the following account of a similar prosecution,
whereby three friends were committed to York castle.

[.embedded-content-document]
--

[.blurb]
=== The suffering cases of Richard Ward, Benjamin Burn, and William Boocock, on the account of refusing to pay tithes.

We the said Richard Ward and Benjamin Burn of Hillam,
in the parish of Monk-Fryston in the county of York, and William Boocock of Mithley,
in the same county, who had dwelt at Hillam;
were all subpoenaed to appear at the Exchequer bar in Trinity term, 1735,
at the suit of Robert Robinson of Monk-Fryston, tithe-farmer, under Dr. Thomas Sharp,
prebendary of Wistow,^
footnote:[A prebend belonging to the cathedral of York.]
to answer a bill which he filed against us,
in which he complained against us for keeping and
detaining from him the tithes of our corn,
hay, and other small tithes, though he or his servants,
had taken our corn from us in kind every year; if he happened to miss taking it,
he took more for it the next year;
and he might have taken from us the value of our small tithes,
at any time by justices warrant,
without putting himself or us to such great trouble and expense.
In Michaelmas term following we put in our answers,
and gave an account of the value of our tithes, according to the best of our knowledge.
After several terms he amended his bill; after which he replied,
and refused to accept of our answers: Some time after he amended his replication,
and left out the tithes of our corn;
then called for a commission of inquiry to examine witnesses,
etc. which was held at Pontefract, in the 11th month called January, 1737,
the charge of which costs us on our part above 16£.
though he proved scarce anything more in value,
than what we had confessed in our answers.
In Michaelmas term following, 1738, he obtained a decree against us; Ward,
for nine years small tithes, 4£. 19s. 9d. Burn, for nine years small tithes,
2£. 17s. 6d. Boocock, for five years small tithes,
1£. 11s. 1d. and also a decree for costs,
57£. 3s. 4d. and for our conscientiously refusing to pay the abovesaid sums,
we were taken up by attachments issuing out of the Exchequer court in Easter term, 1740,
and committed prisoners to York castle, the 30th of 3rd month called May following,
and have great loss and detriment of our families.

[.signed-section-signature]
Richard Ward

[.signed-section-signature]
Benjamin Burn

[.signed-section-signature]
William Boocock

[.signed-section-context-close]
York castle the 7th of 3rd month, 1741.

[.postscript]
N.B.A. little time before we were brought hither prisoners in the 3rd mouth, 1740,
the said Robert Robinson, by virtue of a warrant from Robert Mitford and Robert Pockley,
justices, distrained one cow of Richard Ward`'s,
appraised at 3£. 10s. for five years small tithes, since the aforesaid suit commenced;
and from Benjamin Burn he distrained a cow and a calf valued at 2£. 15s. for tithes,
since the said suit commenced.

--

Had this tithe-farmer,
who appears to have known the method of recovering by justices warrant,
taken that method for the recovery of the tithes which he sued in the Exchequer for,
would it not have been much better for himself, as well as his neighbours?
for he might then have got the tithes he now lost,
and have saved himself the expense of 57£. 3s. 4d. and perhaps
much more which the Exchequer prosecution might cost him:
had the restriction the Quakers desired taken place,
this tithe-farmer would have received a very considerable advantage thereby,
in being withheld from hurting himself to imprison his neighbours.

Each had a separate warrant for the costs,
which was 57£. 3s. 4d. they were discharged the 13th of 6th month, 1743,
by virtue of a clause in the act for insolvents,
pasted in the last session of parliament, without paying the usual fees to the jailer:
by the following justices of the peace, who met at the castle of York,
pursuant to an adjournment of quarter sessions from Bradford,
the 21st of the 5th month last, and before whom the prisoners appeared, viz.

[.small-break]
'''

Francis Barlow,

Richard Dawson,

Mark Braithwate, L. D. an advocate,

Richard Gilpin Sowry.

[.small-break]
'''

It was pleaded by council on behalf of the prosecutor, that the whole costs of suit,
viz. 57£. 3s. 4d. was chargeable on any one or two of the prisoners,
if the third was insufficient; it being given in by the prosecutor`'s evidence,
that William Boocock had no effects, real or personal.

The justices laid before the prosecutor his cruelty,
and took off his demand upon William Boocock, and one third part of the costs,
and discharged William Boocock.

Nor would the justices lay William Boocock`'s part upon the other two friends;
and taking off twenty pounds,
which Dr. Sharpe allowed the prosecutor upon renewing the lease,
granted a warrant for distress, as follows:

[.small-break]
'''

On Richard Ward:

for tithes: 4£. 19s. 9 1/4d.

For one third costs: 2£. 7s. 9d.

In all: 17£. 7s. 6 1/4d.

[.small-break]
'''

On Benjamin Burn:

for tithes: 2£. 17s. 6d.

For one third costs: 12£. 7s. 9d.

In all: 15£. 5s. 3d.

[.small-break]
'''

On the prosecutor`'s return from the levy, they were all three released;
William Boocock freely.
During these transactions, some members of this society,
of eminent usefulness among their brethren, had been removed by death,
accounts of whom I have deferred in course,
with a view not to interrupt the narrative of the
proceedings in reference to their petition,
for the redress of their grievances in these prosecutions for tithes.
