== Chapter VI.

[.chapter-synopsis]
* Account of Alexander Arscott
* Samuel Overton
* John Gurney
* Benjamin Bangs
* James Dickenson
* Thomas Story
* John Fothergill

In the year 1737, Alexander Arscott of Bristol,
an useful and respectable member of civil and religious society,
was removed from works to rewards.
His father was a clergyman of the Account of church of England,
incumbent of Southmoulton in Devonshire, and designing this son for the fame function,
he gave him an education suitable thereto; after the preparatory tuition at school,
he was removed to the university at Oxford to complete his studies.
But now when he had acquired the attainments esteemed suitable
qualifications for undertaking the sacerdotal office,
and might have had a reasonable prospect of preferment,
(his father being well respected and beloved among the great men in that
country,) religious considerations preponderating in his mind,
turned his views from worldly prospects to those of an everlasting duration,
and by the convincement of his judgment,
being induced to adopt the profession of the people called Quakers,
he declined the thoughts of pursuing the line of life intended for him.
This gave his parents great anxiety, both as appearing to them a mistaken choice,
and disappointing their hopes of his preferment,
insomuch that they frequently gave vent to their sorrow with tears,
whereby the feelings of filial affection were awakened in him to join in their sorrows;
and to call in question the rectitude of his choice,
as he had been and desired to be a dutiful son to tender and affectionate parents;
his understanding became clouded for a season,
by doubts respecting the propriety of his conduct.

Being hereby brought low in his mind,
and still desirous above all things to please his maker
by doing his will to the best of his understanding;
to keep a conscience void of offence to God and to man,
(especially to his parents) as far as might be consistent with
what might appear to him required as duty to the Almighty.
During this season of spiritual conflict,
he was much exercised in inward supplication to be rightly directed,
and therein received a fresh sight, that,
if he would be Christ`'s disciple he must forsake father and mother for him,
and be faithful to the manifestation of his will in all things.

He then found there was no other way to attain that solid peace of mind,
of which he was in pursuit,
but by yielding unreserved obedience to the discovery of duty;
this appears the moving cause of his joining in society with the people called Quakers,
as being experimentally convinced of the reality
of the inward appearance of the grace of God,
and the necessity thereof to enable men to overcome their evil propensities,
and lead them into a life of virtue and holiness.
From that time till his decease, being about thirty-five years,
and when he was settled here in good business,
and in estimation with his fellow citizens,
he had the satisfaction to find his parents better reconciled to his change;
and that his interest with his friends and others,
put him in a capacity of being serviceable to the rest of his father`'s family,
by procuring them good places for getting a livelihood.

Upon his entering into this society, his worldly prospects vanished of course.
But his good qualities engaging the esteem and cordial regard of his new friends,
it was not long '`till he found encouragement amongst them in that line of life,
which by his education he was well qualified to undertake.
He removed to the city of Bristol, about the year 1702,
and kept school there for the education of his friend`'s children and others with reputation.
He received a gift in the ministry,
his labours wherein were very acceptable and edifying to his friends,
amongst whom he chiefly exercised it, of which they gave this testimony, that,
"`his ministry gave evidence of its purity, being accompanied with divine wisdom,
power and life`". Although he did not travel much from home,
yet he occasionally visited sundry meetings in the counties adjacent,
to the edification of his friends.
He also generally attended the yearly meeting in London.

The abilities and purity of his mind manifested in a circumspect life and conversation,
increased the esteem in which he was held not only by his intimate friends,
but also with the good and judicious part of his neighbours,
and his acquaintance in a general way.

His love to God was manifested by an unaffected and fervent piety;
his love to his neighbours by his readiness to do good to all men,
as far as in his power.
In the society of which he was a member, his service was very beneficial and extensive,
not only publicly in the exercise of a lively and affecting ministry,
and skilful exertions for introducing and preserving good order in general;
but in a more private way, in preventing differences,
and promoting love and unity amongst them,
under the impression of love and tender sympathetic concern,
visiting the widow and fatherless; the afflicted in body and mind, the sick,
the disconsolate and the poor; to each of whom he would freely extend a hand of help,
administering assistance, consolation, and generous contributions himself,
and using his influence with others to contribute to the
want of such as stood in need of food and raiment.
"`Blessed are the merciful, for they shall obtain mercy.`"

The instances of his benevolence and the respectability of his character,
were not confined with the pale of the society;
conspicuous amongst his fellow citizens for judgment, understanding and integrity,
he was very much employed in deciding differences between them,
either as arbitrator or umpire: so that to the blessing of the peace maker,
he might seem to have a title above most.

He wrote sundry tracts, which were well received, particularly those entitled,
_Some Considerations Relative to the Present State of the Christian Religion._

His last indisposition was a diabetes, which gradually weakened him,
till at last in a peaceful frame of mind, he departed this life, the 30th of 1st month,
1737, in the 61st year of his age.

Samuel Overton of Grovefield, in the county Account of Warwick,
was born in the parish of Tach-brook in that county, in the year 1668,
of parents in religious society with the people called Quakers,
by whom he was educated in the same profession.

The circumstances of his father (a husbandman engaged in hard labour
on his farm for his subsistence) seem not to have been such as
afforded him the advantage of obtaining much learning.
Being in his youth inured to bodily labour,
he was very helpful to his father in the management of his business.
He was favoured with good sense and a comprehensive natural capacity,
so far compensating for the defect of his education,
that he wanted neither understanding nor skill in the prudent
and successful management of his temporal affairs,
or his spiritual calling.

For, through the divine blessing prospering his honest
and judicious exertions in his occupation as a farmer,
he procured not only a comfortable subsistence on a farm,
where his honest parents laboured under very great difficulties,
but in process of time attained to plentiful circumstances.

And in the laborious season of his youth, being humbled in mind,
he was favoured with a merciful visitation from on high,
whereby he received a religious turn,
inducing him to pursue after the attainment of the durable riches of righteousness,
after which his search was not in vain.
For as he was faithful to manifested duty,
he received a dispensation of the gospel to preach,
and laboured diligently therein to the edification of his friends and others.
He travelled frequently abroad in religious visits to his
friends in different parts of England and Wales,
particularly in the western counties of the former,
and for many years attended the yearly meeting of London;
in all which his labours in the ministry were very acceptable and serviceable.
Being a man of universal benevolence, and well qualified to propagate righteousness,
and the doctrines of pure Christianity,
he was concerned to appoint meetings for the information
and benefit of people of other persuasions.
The same principle excited him to be frequent in attending marriages,
and burials amongst friends in the county wherein he resided, and those adjacent,
as affording opportunities of spreading the doctrine
of truth among the people in a general way.

He was no less distinguished for his service in meetings of discipline,
being one of the first who was remarkably zealous
to establish and keep them up in those parts.
He was a man of sound judgment, and steady deportment therein,
often advising friends to a dispassionate temper of mind,
and to speak from a sense of truth, which he was careful to exemplify in his own conduct,
being a pattern of meekness and brotherly condescension.

His private character, as described by his friends, who were well acquainted with him,
appears to be truly respectable, viz. that he was an affectionate husband,
a tender father, a kind and liberal master, a true and faithful friend,
a generous and good neighbour; charitable to the poor,
and sympathizing with the afflicted; open-hearted and hospitable to his friends;
a lover and promoter of peace,
he was often chosen an arbitrator to compose differences amongst his friends and others;
in which capacity his coolness, sagacity and impartiality,
enabled him to bring them generally to an agreeable issue.

He not only in doctrine zealously and repeatedly
recommended a holy and circumspect life and deportment,
but was a lively pattern and example thereof, in his own conversation and conduct.

He had a lingering illness for several months, which he bore with christian patience;
and as often as the intermission of his distemper would admit,
he was very diligent in attending meetings, wherein he very devoutly exercised his gift,
and was supported and carried through in the discharge thereof,
beyond what could in the eye of reason be expected,
being freely given up to spend and be spent for the service of truth;
and even at the last meeting he had amongst friends at Warwick, in the week he died,
notwithstanding the infirmities of his body,
he was deeply and excellently concerned in testimony; and,
as if sensible of his approaching death,
and the loss which the church was likely to sustain by his removal,
he fervently besought the Lord in prayer, that out of his abundant goodness,
he would be pleased to raise up and send more labourers into his harvest;
which was very affecting and heart-tendering to several then present.

He departed this life the 23rd of the seventh month, 1737,
and was interred in friends burial ground in Warwick, the 27th of the same,
being attended by a great number of friends and neighbours,
and generally lamented by all sorts of people, aged 69,
a minister about forty-eight years.

John Gurney, of Norwich, was descended of worthy and respectable parents,
who received the truth in the love of it,
soon after the appearance of friends in that city.
His Father had no small share in suffering for his religious testimony in the
most severe persecutions to which friends were exposed in those early times,
and remained unshaken in his faithfulness to the end of his days.
His parents took particular care in giving their children a religious education,
and had the consolation to behold the beneficial effects thereof, in most of them.

This their son John Gurney, in particular,
being early illuminated with wisdom to discern the
folly and vanity of youthful delights and pursuits,
turned his attention to religious and virtuous considerations in his young years;
and by submitting to the guidance of the holy Spirit, he grew in experience,
in sanctification, and in an understanding of the mysteries of the gospel;
and about the 22nd year of his age,
his mouth was opened in ministry in the religious assemblies of his friends,
much to their edification and comfort; and as he advanced in years and experience,
his excellent gift was enlarged, he being an eloquent man, and mighty in the scriptures.
His ministry was often attended with the demonstration of the spirit and of power;
his expression plain and intelligible to the meanest capacity,
and his doctrines suitably adapted to the states of the
auditory reached the witness of God in many of their hearts:
he approved himself a workman that needed not to be ashamed,
rightly dividing the word of truth.
Though his eminent qualifications made many delight to sit under his ministry,
and seek opportunities for that purpose, yet he affected not popularity;
but frequently gave way to others, perhaps less desired,
choosing rather to remain unnoticed, than to appear to gratify or please the itching ear;
being careful deeply to attend to the motion of truth in his own mind,
before he entered upon his labours in the ministry.

He had a high esteem for the good order established
in the religious society of which he was a member,
often expressing his sentiment,
"`That he believed their constitution respecting discipline,
was preferable to any other now subsisting in the world,`"
and was diligent not only in attending meetings of worship,
but those for discipline also,
wherein he discovered himself to be a member well qualified for service,
and skilful in managing matters of discipline; being a man of clear conception,
understandings penetration and expression;
his sentiments generally carried conviction with them,
whereby great regard was paid to his judgment,
not only in the monthly and quarterly meetings to which he belonged;
but the general assembly of his brethren in the yearly meeting at London.
He was no less conspicuous for his capacity and judgment in civil affairs,
wherein he was capable and ready to serve both those of his own society,
and other members of the commonwealth, many of whom received benefits from his services,
which procured him the general love and esteem of people of all ranks,
even the great men of this world; yet he was preserved from exaltation in prosperity,
and cautiously avoided opportunities of applause, which frequently offered.

His life and conversation adorned the doctrine of the gospel,
which he was concerned to publish to the world; being a pattern of sobriety, chastity,
moderation, temperance and other christian virtues.
In his family, an affectionate husband, an indulgent and tender father, and a kind master.
In religious society, a faithful overseer, a wise counsellor and a steady friend.
Among his neighbours and countrymen of all denominations,
an useful assistant on many occasions, by free and candid advice,
which as application was made to him, he generously communicated.

In the latter part of his time, he was afflicted with great pain,
being for some years grievously affected with the stone and gravel,
which very much weakened his constitution;
yet his soul seemed supported with christian fortitude,
in patience and resignation to the divine will.
And although his long indisposition prevented his travelling much abroad,
to visit the churches in the different parts of his native country,
as he had formerly done, to the edification of his friends,
yet he frequently attended the religious assemblies of his brethren at home,
amongst whom in his state of bodily weakness,
he was often engaged in a living and efficacious ministry,
whereby many were powerfully reached,
and affected with lasting impressions of religious thoughtfulness in their minds.

These painful distempers grew upon him, '`till they terminated his existence in this life,
the 19th of 11th month, 1740;
and as he had engaged the general esteem of his friends and fellow-citizens,
they manifested their respect to his memory by a very numerous attendance
of his body to the grave a solemn meeting was held to edification,
wherein the solidity of the large assembly testified
the universal regret for his removal.

Benjamin Bangs, of Stockport, in Cheshire, was a minister of eminence in his day,
of whom, however, for want of information and materials,
cannot be so particular in my relation,
as his services at home and abroad for more than sixty years, might seem to demand;
and therefore must restrict myself to the following
testimony to his qualifications and services,
by his friends of the quarterly meeting to which he belonged.

He was born in the parish of Longham, in the county of Norfolk, the 1st of 10th month,
1652, and was religiously educated in the principles of the church of England.
The Lord was pleased in his young and tender years
to extend a merciful visitation of love to him,
with which he was at times deeply affected; and about the 19th year of his age,
being then settled in London, was convinced of the blessed truth;
and shortly after he came forth in a public testimony,
and became an able minister of the gospel of Christ:
in which he laboured faithfully and fervently,
in divers parts of this nation and the kingdom of Ireland,
and was instrumental in the convincement of many.^
footnote:[See vol. 3. page 39, etc.]

In the year 1683, he married Mary Lowe, of the county of Cheshire,
and settled in that county.
After which he visited many parts of the nation and the Principality of Wales;
and till age and infirmities prevailed,
continued to visit his friends in the adjacent counties,
where his services were always acceptable.

He was an elder worthy of double honour, having obtained a good report;
not of men seeking glory, or as a lord over God`'s heritage, but an example to the flock.
In doctrine, sound, clear and instructive; his openings were fresh and lively,
and his manner of expression truly amiable.
He delighted much to wait in silence for the discoveries of the word of life,
whereby he became strong in the Lord and in the power of his might,
sounding forth the word of reconciliation by Christ our Lord,
and salvation through his eternal spirit.

He was often fervent in supplication, and drawn forth in a sweet and heavenly manner,
to the great joy and gladness of the sincere in heart.
He was signally qualified in meetings of discipline,
to speak a word in season for the promotion of peace and good order in the church.

He was remarkably compassionate to the poor,
in whom he observed a degree of sincerity and worthiness,
such were sure to meet with an advocate in him.

His countenance was awful, his deportment grave,
but intermixed with a pleasant and familiar manner of expression,
that rendered his company truly pleasing to those he conversed with,
and when old age and infirmities attended, his understanding was clear,
and many sweet and heavenly expressions dropped from him.
He often said, "`That his work was finished, and he was freely resigned;
feeling nothing on his spirit but peace from the Lord.`" When near his end,
be could not forbear rejoicing in the blessed experience of that peace, saying,
"`Now I know and witness the saying of our blessed Lord fulfilled,
'`He that believeth on me,
out of his belly shall flow rivers of living water.`'`" He died the 6th of 12 month, 1741,
in the 90th year of his age; a minister about 65 years.

In this year also, James Dickenson, of Greentrees, in Cumberland, a very serviceable,
valuable and faithful minister of the society of the people called Quakers,
(sundry of whose travels and services have been noticed in this work) departed this life.
He was born at Lowmoor, in the county of Cumberland, in the year 1659, of honest parents,
professing the truth, as held by this people.
The Lord was pleased tenderly to visit him, when very young;
but for want of keeping a steady eye to his guidance,
he was led forth into those vanities and follies of the world incident to youth;
but such was the love of the heavenly Father that he was met with again and again,
and brought back, as a sheep strayed from the Father`'s fold;
and after much affliction and solitary exercise, fitted for future service,
and engaged in a public testimony to that truth, the efficacy whereof he had experienced,
about the 1741 eighteenth year of his age.

He was shortly after concerned to go to several meetings of the Dissenters,
in the county where he lived, amongst whom he met with much ill treatment;
yet truth crowned his labours with the convincement of several.

After which he travelled through divers counties in England, in the work of the ministry,
in which he zealously laboured for the promotion of piety and virtue,
so that it often proved effectual to reach the witness
of God in the conscience of those to whom he ministered;
for it may be truly said of him,
that he went not about to publish the gospel of life
and salvation with the enticing words of man`'s wisdom,
but in the power and demonstration of the spirit of truth.
Many sufferings did he undergo in his early travels, in the times of persecution,
which he bore with christian fortitude and resignation;
looking not unto man for his reward,
but to that great and good master who had sent him to work in his vineyard.

He visited Ireland twelve times;
once he paid a visit to his friends in Holland and Germany;
and three times went over to America,
in all which places he diligently laboured for the promotion of truth and righteousness,
and in many places was instrumental to the convincement of several.
And although he travelled much and often hard, yet as soon as his service was over,
and his spirit eased of the concern which was upon him,
he was diligent to return to his outward habitation and business,
that he might not only be a good example to others herein,
but might also mind his service among friends at home.

He was a man much esteemed in his own country;
friends there highly valued him for his faithfulness
in the performance of the Lord`'s work;
and his humble deportment, circumspect life and godly conversation,
gained him a good report among his neighbours and those with whom he conversed.

He frequently attended the yearly meeting in London,
where he sometimes spoke concerning the affairs of the society,
much to the satisfaction of friends;
yet he was not so peculiarly gifted for the management of the discipline of the church,
as some others in his time, who were not so eminent in the ministry;
whereby the great wisdom of the Almighty is plainly seen;
for he fits and qualifies his faithful servants by his own power and holy spirit for
that work and service in the church to which he sees meet to appoint them.

He was a diligent labourer at home, a constant attender of meetings,
a sincere travailer therein, very tender over the youth, a nursing father to the weak,
and full of charity to all; yet not hasty to join with forward spirits.
He was very careful to keep clear of party causes,
and anxiously concerned to promote peace in the church;
and often expressed his steadfast faith that the
testimony of truth would be exalted in the nations,
and the antichristian oppression of tithes brought down;
and with concern declared his sorrow for such as weakly complied therewith.

When his natural abilities failed,
he would speak with strength apparently beyond his age and constitution.
He was seized with a palsy a year before he died, which kept him from meetings,
and by it his speech was much affected; yet he would often say he was well,
and had nothing but peace on every hand.

He died at Moorside in Cumberland, on the 6th of 3rd month, 1741, aged 83 years,
a minister 65 years.

Thomas Story died in the course of this year, whose birth, education and convincement,
a full account hath been already given,
in which it is remarked that he devoted much of his time to travelling in the
exercise of his ministerial labours for the edification of his brethren,
and convincement of others.
It was in the year 1693, he first appeared in the ministry,
and in the succeeding year he travelled into the southern
and western counties in company with Aaron Atkinson:
from the west they returned to London and there parted.
Aaron returned home to Cumberland,
and Thomas fixed his residence for the present in London,
as the place most suiting for procuring a comfortable subsistence in that line of employment,
which presented to him, as least confining and embarrassing,
and which his education had qualified him to undertake,
viz. to employ himself in drawing conveyances,
settlements and all other kinds of legal instruments,
and in a short time he had more business than he could execute with his own hands,
which frequently made it necessary to engage clerks to assist him, as occasion required;
for although he had the offers of resident clerks with competent fees;
yet considering these offers,
as having a tendency to bind him to them '`till they might be properly instructed,
and his desire being to be so circumstanced,
as that he might be at liberty fulfill his ministry at home or abroad,
as he might apprehend the call of duty to require,
he determined to decline every proposal of this kind.
And the sequel proved he did not come to this determination
without a weighty consideration of the matter.

For after spending the year 1695, and part of that succeeding in London,
in his employment aforesaid, he look a journey to the north of England and to Scotland,
and after finishing his service therein, he returned to London,
where he divided his time between his employment and attending
meetings in the city and its neighbourhood till the year 1698,
when receiving a letter from William Penn,
desiring him to meet him and John Everot at Holyhead, in order to go to Ireland,
he went accordingly, and accompanied them in a visit to friends in that nation,
of which an account hath been related in its proper place.

Shortly after his return from Ireland,
having for some time believed it his duty to pay
a religious visit to his friends in America also,
he began to prepare for his voyage thither.
He embarked in company with Roger Gill in the 9th month, 1698, for Virginia,
and arrived there in the 12th month following: his companion, as we have seen,
died at Philadelphia in the course of their travels,
and Thomas by close and almost daily labour and travel,
finished his service in the compass of the year 1699,
and early in the succeeding year seemed ready to return to England.

But William Penn being now returned to Pennsylvania, with a view of settling there,
and finding the affairs of his province,
which he had left in a peaceful and prosperous state, during his long absence,
fallen into embarrassment and disorder; and having a particular regard for Thomas Story,
as an intimate friend, and a favourable opinion of his abilities,
he importuned him to take up his residence in Philadelphia for a season,
to afford his assistance in settling the affairs
of the province and reducing them into order.

Upon due deliberation Thomas consented to stay so long as he might see it his place.
Whereupon he was appointed one of the governor`'s council, keeper of the seal,
master of the rolls, and one of his commissioners of property,
for inquiring into and confirming old rights, and granting lauds upon new purchases.
Moreover when a new charter was afterward granted to Philadelphia,
erecting it into a city and corporation, he was appointed to the office of recorder;
but he held this office only till the corporation
was regularly settled and habituated to business,
when he resigned.

But in these different secular functions, in which he was engaged,
both his honourable friend and himself had a due regard to calls of an higher nature.
For by his patent he was allowed deputies in each office,
whenever his apprehension of duty might engage him
to travel abroad in the work of the ministry;
he thereby was enabled to fill up his respective duties with fidelity,
and to divide his time here between his secular and
spiritual calling for the space of 14 years,
viz. from the year 1699 to 1714, whence he returned to England.

During his residence in America,
he paid frequent religious visits to his friends in different parts of the continent,
and in 1709, to the West Indian Islands,
when in his passage from Jamaica to Philadelphia,
the vessel he was in was taken by a French privateer and carried into Martinico,
where he and the ship`'s company (except in losing their
goods and clothes) were kindly and hospitably treated.
After some stay there, they got a passage to Guadaloupe,
and from thence in a flag of truce to Antigua.
In 1714, he passed again to Barbados, and from thence returned to England,
where he continued his gospel labours,
in a successive course of travelling in the various quarters of the British islands,
and being a man of eminent qualifications, and those sanctified,
his ministry was very convincing and edifying, so that he was acknowledged,
not only by the society of which he was a member, but by other people,
as a truly evangelical minister.

His last journey was in 1740, from his own residence at Justice-town to London,
where he continued several months,
and during his stay there he was seized with a paralytic disorder,
which affected him to such a degree, as deprived him very much of his speech,
and confined him within doors till the return of the spring;
when he regained a little strength, and got out to meetings;
but was still not so far recovered as to be able to hold a discourse long,
his memory being also much impaired by the said disorder.
Nevertheless he continued sweet in spirit, and pleasant and cheerful among his friends,
whom he was always glad to see, and be in company with.
He likewise diligently attended the yearly meeting at London, 1741,
though he spoke not much in it.
Before the end of summer he grew so much better, that he travelled down to Carlisle,
to look after his affairs in the north, which required his attendance;
for having a design to build an house at Justice-town, he provided materials,
and frequently overlooked the workmen;
and indeed his health and faculties were so well restored,
as that he many times appeared in public in the meetings,
greatly to the satisfaction of friends.
Thus he continued without much alteration, till the 23rd of 4th month, 1742,
being the first day of the week; when in the evening,
he suffered a new attack of his distemper, which seized him with great violence;
and the next morning between two and three o`'clock, he departed this life,
in perfect peace (we have reason to believe) with God and mankind.
His funeral at Carlisle was attended by a great number
of friends from several parts of the country,
and also by divers people in the neighbourhood,
who seemed deeply affected with the loss of a man,
so valuable and useful to his country in several stations of life.

John Fothergill, of Carrend in Wensleydale, but formerly of Knaresborough in Yorkshire,
was the son of religious parents, who carefully educated him in sobriety,
simplicity and virtue, according to the principles of the people called Quakers.
But in the early part of life,
being illuminated by the grace and truth that comes by Jesus Christ,
he perceived that neither tradition, outward regularity of life,
nor anything short of real internal purification of soul
would render him acceptable in the sight of the Lord,
or secure his everlasting well-being; he was incited therefore,
with an entire dedication of heart steadily to pursue this arduous attainment,
and through the repeated baptisms of the Holy Ghost, and the washing of regeneration,
he gradually experienced, what he was in pursuit of, a being made clean thereby;
and under this preparing operation of divine grace,
a sense attending his mind that he would be called to the work of the ministry,
he was very careful to wait the appointed time.
For although he was favoured with the opening of the scriptures to his understanding,
in sundry parts, and at sundry times, in the religious meetings of his friends,
he cautiously abstained from the publication thereof, till the time came,
when it was indeed required of him to make a public
declaration of what was spoken in his spiritual ear,
and when the word appeared with such clearness, as to leave no shadow of doubt,
that it was a divine requiring, like the apostle, he reasoned not with flesh and blood,
but gave up to the heavenly vision.

He was called to the ministry about the 20th year of his age,
and by a daily deep and inward dwelling with the word of divine life in his own heart,
he soon became a strong man in Christ, and a skilful and able minister of the gospel;
well instructed in the mystery of godliness,
and in the light to discover the mysterious workings of antichrist in opposition thereto,
he was well qualified,
out of the treasures of his own experience to administer consolation, counsel or caution,
suitably adapted to the different states of his auditory.

Being strongly impressed with an awful humbling sense
of the majesty and omnipresence of the divine being,
in the exercise of his ministry he was very awful and weighty,
not endeavouring to please the itching ears,
or gratify the high notions of airy speculation by the wisdom of words,
but actuated by higher and purer motives,
as considering himself under the notice of that eye,
which penetrates unto the innermost recesses of the heart,
and observes the most secret motions thereof, he durst not handle the word deceitfully;
but patiently waited, renewedly to receive power from on high,
and under the influence and divine authority thereof, to divide the word aright,
reaching the divine witness in the hearts of those he ministered unto,
to the convincement, confirmation and edification of many at home and abroad.

For the support of the discipline established in the society,
his talents were equally conspicuous, being replenished with the wisdom,
which is from above, which is without partiality, he was steadfast,
upright and discreet in the administration thereof; quick of apprehension,
and of a capacious reach of thought,
he expressed his sense and judgment on cases under deliberation with pertinence,
convincing clearness and impartiality.
No family connection (not even his own) biased him in applying righteousness to the line,
and judgment to the plumb-line, for removing offences out of the church,
or recovering backsliders in the way of truth.
The stability of his own conduct, and his inflexible integrity gave him authority,
and that authority he invariably applied to the discouragement of evil doing,
and the praise and encouragement of those that did well.

He was brought up in the occupation of an husbandman,
and I suppose his education as to school learning
was confined to what appeared necessary in that department;
but his deficiency in literature was amply compensated by the soundness
of his understanding improved and refined by pure religion,
which replenisheth the man with a dignity and consistency of conduct,
a wisdom to act well in every station of life, surpassing the wisdom of this world.
At home he was skillfully,
laboriously and successfully employed in his occupation of agriculture
for the necessary support of himself and his family,
yet not entangled therewith;
for when the sense of duty called him to leave his outward habitation and secular affairs,
to devote his time and talents to the exercise of his ministerial labours,
for the edification of the churches abroad,
he with all readiness yielded obedience to the superior calling;
and in this case manifested that wisdom,
for which he was distinguished in every circumstance of this life,
always to leave his outward affairs in reputable order,
and his children (after he was a widower) in safe hands, during his absence;
and he was very diligent in travelling with as much
expedition as a clear sense of duty would allow,
that he might not make the gospel chargeable; and when his service was finished,
to return to his family and outward occupation with as little delay as possible.

He took frequent journeys into sundry parts of England, Scotland and Wales,
in religious visits to his friends.
He visited Ireland several times,
and thrice he crossed the sea to America in the same service,
to the comfort and edification of the churches,
leaving seals to the efficacy of his ministry in many places,
being instrumental to the convincing,
strengthening and establishing of many in religious experience,
and furtherance in the way of righteousness and peace.
He also wrote sundry edifying epistles to his friends,
amongst whom he had laboured in various parts as truth opened his way,
and excited his sympathetic concern for their prosperity
and preservation in sincerity and godly simplicity,
replete with important and pertinent counsel and admonition,
for the like beneficial purposes.

As advancing age brought on painful indisposition and infirmities
symptomatic of his body`'s tending to its decline;
the natural and spiritual abilities of his better part, his zeal for God,
and love to the brethren were still graciously preserved to him unimpaired.
Under great bodily afflictions he continued his religious
visits to several places in England,
as well as his last visit to Ireland, which he performed in the year 1742,
about two years before his death;
a part of his service which I had the benefit to partake
of (as well as formerly in my native country) and can join
my suffrage to the justice of the preceding account of him,
extracted from the testimonies of his friends, to whom he was more intimately known,
as I have had frequently during my pilgrimage through life, as well as at this time,
profitably brought to my remembrance, how;
not only in the efficacious reach of his public ministry,
but particularly in his private conversation among his friends,
at some opportunities at which I had the advantage of being present,
the weightiness of his spirit, the unaffected gravity of his demeanour,
the wisdom of his reflections, his words few and savory, seasoned with grace,
made good and deep impressions with lasting effect upon my youthful mind.

Under the increasing infirmities of age in the year 1744, the last year of his life,
he attended the yearly meeting at London, and,
although under difficulty through weakness of body,
yet his spirit was still so actuated by lively zeal for the propagating
of righteousness and good order in the society at large,
and strengthened by divine support,
that he was enabled to attend the sittings of that large meeting,
where his reverent and watchful frame of mind rendered
his company truly acceptable and serviceable.
On his return he attended the midsummer quarterly meeting at York,
and soon after in a letter to a friend mentioning his bodily weakness, he adds, "`Yet,
I think, my better part is uncommonly supplied in divers respects,
much to my comfort and the reviving of my faith in the heavenly influence,
which is strength in weakness, and will be so,
where his only worthy name hath the praise.`"

After this in the latter part of the said year,
he attended the circular yearly meeting at Worcester, where through divine influence,
still eminently attending him, and reviving the recollection of past experiences,
he was strengthened to bear a noble and affecting
testimony to the all-sufficiency of that power,
which had preserved,
supported and guided him in the way that was right and well pleasing,
all his life long to that day,
and is equally able to do the same for all the children of men,
who are faithful and obedient to the inward manifestations thereof.
After the termination of this meeting he visited Bristol, Bath and some other places,
and then returned home by easy journeys, having meetings as opportunities offered.
After his return he got to meetings for some weeks,
when his testimony was as lively and powerful as ever;
several times expressing his satisfaction and inward
peace in having performed this last journey,
saying, "`His shoulders were considerably lightened by it,
and he was reconciled to his grave, if he should now be taken away.`"

By an exemplary and circumspect conduct in a private and public capacity,
he confirmed and adorned his ministry, being a lively example of primitive purity,
moderation and simplicity of manners,
and uniform virtue in every relation and station of life, as became a minister of Christ.
This consistency of conduct procured him not only
a place in the respectful affection of his friends,
but amongst people of every class; several of superior rank,
who were acquainted with his virtues, regarded him with honourable esteem.

Delighting in the law of the Lord, to meditate therein, day and night,
he was often favoured with access to the fountain of wisdom and light,
and his spirit sustained to worship in secret, when his hand was upon his labour.
Out of the good treasure of his heart at all suitable opportunities,
he was influenced to bring forth good things, whereby the minds of those,
with whom he conversed, were many times edified.
More especially for the instruction of his own family in the right way of the Lord,
he was engaged frequently to talk of his law and his statutes, as he sat in his house,
or walked with them by the way;
and his religious care form their tender minds to piety and virtue,
through the divine blessing, was not ineffectual with several of them,
to manifest the good fruits thereof,
in a stayed sober and religious disposition in the early and succeeding part of life;
and where through temptation and the instability of youth,
any of them caused him painful sensations by a temporary
deviation from the path of purity and rectitude,
he had the consolation in time, to see their return and reformation,
and the greatest joy in beholding his children walking in the truth.
And though we have observed, be himself had not the advantage of an extensive education,
yet his good sense convincing him of the benefit thereof in its proper place,
induced him to give his sons a more liberal institution in learning, by which,
added to his own religious tuition, through the grace of God,
to which he recommended them, cooperating therewith,
they became men in reputation for wisdom and honour in their respective allotments;
eminent for their abilities and service in religious and civil society.

After his return from his last journey to the yearly meeting at Worcester,
etc. his increasing infirmities gradually brought on the dissolution of his body.
Preceding which he had an evening of repose from bodily or mental labour,
sleeping the two last weeks of his life almost continually,
his memory and natural capacity apparently impaired,
seemed to have left him little recollection or sensation,
but that of divine favour and comfort; for when almost all other expressions failed,
he was observed to repeat the following in a very fervent and emphatic manner,
"`Heavenly goodness is near:
heavenly goodness is near.`" So that under the feeling sense of that heavenly goodness,
which he had ever prized as his chiefest joy,
remaining as a seal upon his spirit of his acceptance with God,
he finished his coarse in this life at Knaresborough,
(where he had fixed his residence the last eight years) the 13th of 11th month, 1744,
in the 70th year of his age.
