== Chapter VII.

[.chapter-synopsis]
* The young Pretender lands in Scotland
* The Rebellion quelled
* The People called Quakers address the King upon the Extinction thereof
* Who receives their Address favourably
* Case of Thomas Richardson and Benjamin Cox
* Case of Hannah Risdale
* Account of Evan Bevan
* Samuel Crisp

England having been engaged in a war with Spain since the year 1739,
and France having also taken part with Spain, and declared war against England; in 1743,
the eldest son of lands in the Pretender, encouraged by the enemies, and Scotland.
flattered with hopes of being powerfully assisted by the adherents of his family,
and of a favourable opportunity of asserting his father`'s claim to the British throne,
while the government was embarrassed with a heavy and expensive war,
and the people (as he was made to believe) generally discontented
at the load of taxes with which they were burdened,
landed in Scotland; when being joined by several clans of Highlanders,
and having defeated a body of the king`'s forces at Preston-pans near Edinburgh,
he made an inroad into the heart of England, whereby the rebellion became formidable.
But the The young Pretender found himself greatly disappointed
in the expectation with which he had been flattered,
both of foreign aid and the addition of strength expected from the malcontents in England;
and the king`'s forces under the duke of Cumberland approaching to give him battle,
he thought it safest to make a speedy retreat back to Scotland,
where in the month called April of the succeeding
year he was totally defeated by the duke,
and an end put to the rebellion.

Which having succeeded so far as to occasion a general alarm in England,
the event productive of great and general joy,
brought many addresses of congratulation to the king.
The people called Quakers from their yearly meeting called in the third month,
O+++.+++ S. called May,
also drew up an address on this occasion and to present king upon
at such time as the king might appoint to receive it.

And in pursuance of this appointment the friends deputed,
on the 28th of 3rd month at tended the court at Kensington,
and were introduced to the king by the duke of St. Albans,
when Daniel Vandewali read the address, as follows.

[.embedded-content-document.address]
--

[.letter-heading]
To George II. King of Great Britain, etc.

[.blurb]
=== The humble Address of the People called Quakers from their general annual Assembly in London.

[.salutation]
May it please the King,

We humbly beg leave to approach thy royal presence with united
hearts to congratulate thee upon the deliverance of these kingdoms,
from the late impending dangers, with a joy as sincere as the occasion is signal.

We beheld with grief and detestation and ungrateful and
deluded people combined against their own happiness,
and desperately engaged in open rebellion against thy person and government,
wickedly attempting to subject a free people to the
miseries of a popish and arbitrary power.

As none among all thy Protestant subjects exceed us in an aversion to the tyranny,
idolatry and superstition of the church of Rome,
so none lie under more just apprehensions of immediate
danger from their destructive consequences,
or have greater cause to be thankful to the Almighty for
the interposition of his providence in our preservation.

A preservation so remarkable makes it our indispensable duty also
to acknowledge the king`'s paternal care for the safety of his people,
of which he hath given the most assured pledge,
in permitting one of his royal offspring to expose
himself to the greatest of dangers for their security.

May we and all thy faithful subjects demonstrate our gratitude
for this signal instance of divine favour,
by the deepest humiliation, and by turning every one from the evil of our ways:
and may those, who are placed in authority over us,
by the influence of their own example,
add vigour to the laws enacted for the general suppression of vice and immorality;
so may we have an assured ground of hope and confidence in God,
that he who hath hitherto helped, will never withdraw his mercies from us.

We earnestly beseech him by whom kings reign and princes decree justice,
that his providence may ever attend thy royal person and family,
and make even the efforts of thine enemies conducive
to the establishment of thy throne in perfect peace;
give success to thy endeavours for settling the general
tranquility of Europe on a lasting foundation,
and grant, that an uninterrupted race of kings of thy royal progeny,
may perpetuate the blessings of thy reign to our posterity.

[.signed-section-context-close]
Dated in London, the 22nd of the 3rd month called May, 1746, and signed by 286 friends.

--

Which address the king was pleased to receive very graciously,
and to which the following answer was returned.

[quote]
____
I thank you for this address of congratulation,
the just concern you have shown there in for me and my family is very agreeable to me;
and you may always depend on my protection.
____

After withdrawing from the king`'s presence, the duke of Grafton came out,
and told one of the committee,
that the king expressed himself very kindly respecting the address, and laid,
that he had not received any one which had given him so much real satisfaction;
and the duke said, they might acquaint their friends thereof.

Some few of the clergy and other claimants of tithes
and ecclesiastical demands continued to be vexatious,
in needlessly applying to expensive methods of prosecution;
of which we find two instances this year,
in the cases of Thomas Richardson and Benjamin Cox,
in which the prosecutors put themselves to needless expense,
without gaining any advantage.

The former, an inhabitant Of Spittle-fields,
Was prosecuted for non-payment of 6s. for six years small tithes,
at the suit of Robert Leybourn and John Brookband,
stiled rectors and portionists of the united rectory of Stepney;
but the defendant being admitted to answer _in forma pauperis,_
heard nothing further of the prosecution.

The latter, who resided at Mumby in Lincolnshire,
was served with a writ from the court of Common Pleas, at the suit of Thomas Williamson,
tithe-farmer, for six or seven years tithe, demanded at about 20s. per annum.
He had formerly taken the tithes in kind, but having taken some offence at B. Cox,
though in no wise intended by him, he commenced this prosecution.

Application was early made to the bishop of Lincoln,
who generously expressed his dislike of anything that looked like persecution,
and readily promised to write to the prosecutor, which had the desired effect.
Williamson dropped the prosecution, and gave the said B. Cox no further trouble that way.

We meet an occurrence which happened in the last year,
of which we have few or no other instances in the present century,
although very common in the beginning of this society.
A case of young woman named Hannah Risdale, servant to John Langley,
of Waltham near Grimsby, in Lincolnshire,
having for a considerable time been under an apprehension
of duty to go to the Steeple-house there,
and speak to the people what might be required of her,
went accordingly on the 25th of the 10th month, 1745,
accompanied by her mistress and some other friends,
and waited till the priest (Christopher Jackson) had finished his sermon:
when the congregation was beginning to separate, she stood up,
and (according to her own relation) said, "`Neighbours,
I am sent with a message from the high priest of our profession to desire
you to turn the eyes of your mind inward and examine yourselves,
and to come to true repentance and amendment of life.`" She also spoke to the priest,
"`That he must come down from his high and exalted place,
and bow at the footstool of Christ,
before he could teach any people the way to the kingdom
of heaven;`" or to the like effect.

The priest exasperated at this declaration,
called to the church-warden to put her out of the place,
which he not being forward to do,
the priest in great anger violently thrust her out of the door himself.
But this rude treatment was not sufficient to gratify his resentment;
for having (what is termed) the sacrament to administer, he alleged,
that the worship was not over,
and soon after caused her to appear before a justice of peace,
who took her mailer`'s word for her appearance at the next Quarter Sessions,
where she accordingly appeared,
the Sessions being held at Caister for the county aforesaid in the 2nd month, 1746,
and was there indicted for a misdemeanor, in disturbing the priest during divine service,
and convicted on the Toleration Act, fined 20£. for the king`'s use,
and committed to prison in the castle of Lincoln, till the fine should be paid.

_Summum jus, summa injuria._
Upon perusing the clause of the Toleration Act, upon which she was convicted,
it appears to me stretched to the utmost to comprise any offence she was guilty of.
The words of the act are, "`If any person or persons, shall willingly and of purpose,
_maliciously_ or _contemptuously_ come into any cathedral or parish-church,
chapel or other congregation permitted by this act, and disquiet and disturb the same,
or misuse any preacher or teacher, such persons or persons,
upon conviction at the general or Quarter Sessions,
shall suffer the pain or penalty of 20£. to the use of the king or queen;
their heirs and successors.`"

If the priest had not been more actuated by a spirit of blamable resentment and persecution
(as far as in his power) than the poor woman was by any design of disturbance,
this prosecution had never been commenced,
much less carried on to the utmost stretch of the law, of which it is still questionable,
whether her action was a breach.
She did not disquiet the congregation, nor disturb the priest,
till the congregation broke up, and the service as far as she knew, was ended:
and though advantage was taken of a circumstance, most probably, unknown to her,
her ignorance thereof exempts her from the charge of ailing maliciously or contemptuously,
which by the act appears to constitute such intervention criminal;
so that all circumstances considered,
there wanted only a little christian charity and
moderation to exempt her from the penalty.

Her friends, sympathizing with her sufferings, and commiserating her severe treatment,
exerted their endeavours with the justices,
and other persons of influence in that county for some months after
her commitment to get the fine remitted or at least mitigated,
that being yet in their power, as it was not entreated or returned into the Exchequer.
But, although most of them seemed inclined to favour her,
and gave expectations of joining their good offices for that purpose,
at the two next succeeding Quarter Sessions;
yet the priest so far prevailed upon some then on the bench,
as to render the friendly interposition for her relief ineffectual.

The fine was in course entreated into the Exchequer.
The only remedy therefore remaining was to apply by petition
to the lords of the Treasury for her liberty.
A petition was accordingly drawn up in the name of the prisoner,
setting forth the matter of fact, and consequent proceedings thereupon,
and further alleged,

[.embedded-content-document.letter]
--

&hellip;that she had no intention of disturbing the public worship;
but acted on a motive purely conscientious,
being ignorant of the breach of any law therein--that
she had always behaved herself peaceably and honestly,
(in confirmation whereof,
she referred to an affidavit of two of her neighbours annexed) and that by a long confinement,
she who was only a poor servant-maid,
had almost expended her substance in her necessary support.

She therefore hopes they will commiserate her case, and remit the said fine,
and that she may be discharged from her confinement,
that she may be enabled to provide for her subsistence, by her labour as formerly.

--

This petition produced the desired effect:
for by an order of the board of the Treasury to the attorney-general,
after going through the usual forms of law,
a writ was issued by the barons of the Exchequer in the king`'s name,
directed to the sheriffs and jailer of Lincoln,
whereby she obtained her liberty after an imprisonment of more than thirteen months.

In this year, Evan Bevan of Pontimoyle in Bevan.
Monmouthshire, departed this life.
He was the son of Charles Bevan, of Lantwit Vardre in Glamorganshire,
who gave him a liberal education at school, and at the university of Oxford,
where he made a considerable progress in various parts of literature.

After his return from thence he applied himself to the study
and practice of the law for a season in Glamorganshire,
and served the office of deputy sheriff of that county with reputation;
but after some time, through the convictions of divine grace,
he fell under an anxious concern about his future well-being,
and that godly sorrow which worketh repentance not to be repented of;
of which exercise and the motives of his joining in society with the people called Quakers,
having himself, who could do it best, given a description in a letter to a friend,
a transcript thereof, will convey the most genuine and authentic account to the reader,
as follows.

[.embedded-content-document.letter]
--

Since it hath pleased the divine goodness to endue me with reason,
I heartily thank his most excellent Majesty:
that it has been the further product of his good will,
to give me life and being in that part of the world,
where I have had the freedom to use it; especially in the choice of my persuasion,
and way of returning my acknowledgments to him.
I wish that all, who make any pretensions to religion,
would make use of this noble faculty with subjection to the divine will,
to determine their choice in this grand affair;
and not let the religion of their education be that of their judgment.
If people were thus truly wise unto their own salvation,
and did not too lazily resign themselves to the conduct of their guides,
thereby regarding more their ease than safety,
they would not only be the better able to give a reason of the hope that is in them,
but they would show more warmth in their devotion, more charity in their religion,
and more piety in their conversation than at present they do.

When I was visited some time ago by the chastising hand of the Lord for sin,
and my disobedience to his holy will,
I laboured under great affliction of mind and anguish of spirit;
and though I was constant above many in my attendance on the public prayers of the church,
strict in my observance of its ceremonies,
and exceeding frequent in the use of private devotion, yet my burden increased,
and I waxed worse.

In this wretched and doleful condition I was, when at a relation`'s house,
who had providentially returned from Pennsylvania to his native country,
I lighted upon Robert Barclay`'s apology for the Quakers;
by the reading whereof I was so well persuaded of their principles,
and by turning my mind inward to the divine gift,
(according to their doctrine) it gave me victory, in a great measure,
over our common enemy, banished away my disorderly imaginations,
and restored me to my former regularity:
I received such satisfaction and comfort to my distressed soul,
that thereupon I left the church of England, and joined myself in society with them;
and I am the more confirmed in my change,
especially where it respects the worship of our Creator;
because it is not only the most agreeable to the Scriptures of truth,
but heaven has given us assurance of its approbation thereof, it having been at times,
to my own experience, most powerfully attended with the presence of the Most High.

I hope none will grudge me this mercy, because I received it not by their ministry;
if they do, I have cause to suspect their charity is not of a christian latitude,
since our blessed Redeemer approved not of that narrowness
in his disciples in somewhat a like case.

But here to obviate the objection some may make to my change,
because of the distress I lay under, and the discomposure I was subject to at times,
I would have it remarked, that I read the said apology beyond my expectation,
with more sedateness than usual, and a more quiet composure of mind:
so that with the influence of the almighty, or providence, or both,
I had also the benefit of that distinguishing faculty of man in the change of my opinion.
O that I may never forget the Lord`'s mercy to my soul,
who had compassion on me when I wallowed in my blood, and who said to the dry bones,
live.
O that all such as are visited by the chastising hand of their Maker,
would seriously lay it to heart, and consider their own welfare and salvation;
I could wish with all my heart, that such who labour under this anxiety of mind,
would take encouragement to hope in the Lord`'s mercy through their blessed Redeemer,
by his kindness and long forbearance with me.
I am a living monument of it now; and I hope I shall be so,
while he affords me a being here.
If these lines should come to the hands of any that
are afflicted and distressed as I was,
I have an effectual remedy, through mercy, to prescribe unto them;
turn your mind inward to the grace of God in your own hearts,
refrain from your own imaginations, be still,
and quietly resign yourselves to his holy will, so you shall find health to your souls,
refreshment to your spirits, and the sweet consolation of the Lord in your own bosoms;
you shall find your mourning turned to gladness, and your heaviness to joy;
this has been my experience of the goodness of the holy one of Israel,
who abhors sin and iniquity; therefore I recommend it to you,
and I think this is no mistrusting of the cause,
for they are the sick and wounded in spirit, not the whole, that need the Physician.

As for renouncing the covenant, which I and every christian ought to be under,
of forsaking the devil and all his works,
I am so far from entertaining one thought of neglecting that duty,
that I think myself wholly obliged to observe it: and if I should affirm,
that through the grace of God, and his assistance,
(for otherwise I am satisfied I cannot do it,) the observation of it is possible,
I can find no reason why it should be false doctrine in a Quaker,
more than in a Churchman.

As for deserting that church and ministry which the
Son of God came down from heaven to establish,
I am not conscious to myself thereof; for I say,
Christ himself is the head of our Church,
and by his spirit and grace the ordainer of our ministry.

And as to the last query my ingenious acquaintance is pleased to propose,
I do let him know, that my former despair and forlorn condition has been,
since my adhering to that reproached people,
changed into a sweet enjoyment of the goodness of God.
I could not conceal the Lord`'s goodness, least he should withdraw his mercies from me.

I had no secular interest to corrupt me in this change, it is apparent to many,
I declined it; but as it was peace with God my maker, and mercy to my soul I wanted;
so having found the pearl of great price among them, I parted with all to purchase it;
or rather, I was restored to all, I mean, the enjoyment of the divine goodness,
and of myself, by setting a due value upon it.

--

This letter presents a lively picture of humility, sincerity, disinterestedness,
meekness and modesty in the writer,
which qualities seem the distinguishing traits in his character;
for although qualified by his good sense and literary
accomplishments to make a figure in life,
and particularly in the society with which he thus associated himself;
yet he declined rather than courted popularity, seeking in a retired life,
to attain the favour of heaven, by growing in grace, in the saving knowledge of God,
and in the acquisition of pure virtue and solid peace of mind,
more than to win human applause by a display of his abilities natural or acquired.
He appeared at times as a minister, mostly, I apprehend,
among his friends in the place of his residence, or the neighbourhood thereof,
as he found his mind opened and enlarged in love to his brethren,
for the last twenty years of his life,
whereby they were often edified and profitably affected,
and that not only by his lively ministry, but by the awful,
weighty frame of his spirit manifest in the solid gravity of his countenance,
as he sat in religious meetings, feeding on the bread of life.
And when from the fulness of his heart, his mouth was opened to minister,
his words were few and savoury, seasoned with grace,
to the affecting the hearts of the well-minded, but to the disappointment of such,
as knowing him, expected to hear the eloquent orator in lengthened discourses,
delivered in elegance of expression; for abiding under the power of the cross of Christ;
as in his general conduct, so particularly in the exercise of his ministry,
his aim was still of a higher nature, than to catch the admiration of men;
the unity of the brethren in the bond of peace, the edifying them in love,
and the approbation of his Maker for the discharge
of his duty in sincerity and godly simplicity,
were the important ends he had in view;
imitating the self-denying example of the apostle, which he thus describes.
1 Cor.
2: 1-5: "`I came not with excellency of speech, or of wisdom,
declaring unto you the testimony of God;
for I determined not to know any thing among you, save Jesus Christ, and him crucified.
And my speech and my preaching was not with the enticing words of man`'s wisdom,
but in the demonstration of the spirit and of power.
That your faith should not stand in the wisdom of men, but in the power of God.`"

After his joining this society he employed himself in the education of youth,
having kept a school for about thirty-five years in their meeting-house at Pontimoyle,
where he instructed his pupils in the useful parts of literature, as Latin,
Greek and geography, with various branches of the mathematics;
yet their institution in virtue, by endeavouring to preserve them in innocence,
and fixing religious impressions upon their minds,
appears to have been the principal object in his view;
for which purpose he conscientiously declined instructing them in the heathen authors,
for fear of depraving their taste for the pure principles of Christianity;
and mostly in the evening of the day he held a religious opportunity
with his family and the scholars who boarded with him,
to wait in silence upon the Lord,
to initiate them into serious meditation in retiredness of mind,
and (as he felt his way open) to influence them to their moral and religious duties,
particularly this of waiting in silence; laying before them the benefit thence arising,
for seasoning their tender minds with profitable considerations,
and strengthening them to draw near their heavenly Father, not with the mouth or the lip,
but with the prevailing language of the heart,
awakened to a feeling sense of what it stands in need of.

Thus he seems to have confined his service and his
acquaintance pretty much to the place of his residence,
and however little known in other parts, yet here, where he was known,
he was esteemed and affectionately regarded for his private virtues, and public services;
the meeting to which he belonged having borne testimony thereto, that,
"`His memory is dear to us,
and being dead he yet speaketh.`" He officiated as clerk to the
monthly meeting for the greatest part of the time he lived there,
and of consequence was much concerned in managing the discipline of the society;
in which engagement his meekness and patience were conspicuous,
in his forbearance towards such as by their unguarded conduct,
had justly deserved the censure of the church;
and his mild manner of treating with them has reached some,
and reclaimed them to a sense of their deviations;
his humility in seeking no preeminence by the superiority
of his talents spiritual or natural,
but condescending to the weakest in charity and pure love;
plainly demonstrating whose disciple he was.
Regarded by his friends as an elder and pillar in the church, worthy of double honour,
exercising the oversight thereof, not as a lord over the heritage;
but as an example to the flock.

His circumspect conduct was truly exemplary, corresponding with his doctrine,
and the principles which he professed.
In his conversation he was affable and engaging, instructive and edifying.
So having passed his life here in pure self-denial,
in prospect of the recompense of reward in the life to come,
he finished his course in this world in peace, the 17th of 2nd month, 1746,
about the 68th year of his age,
and was interred in friend`'s burying ground at Pontimoyle, aforesaid,
and his funeral was attended by a numerous body of most persuasions and ranks in life.

Similar to the convincement of Evan Bevan, was that of Samuel Crisp,
a clergyman of the church of England,
who gives the following account of his convincement, in a letter to a friend.

[.embedded-content-document.letter]
--

[.salutation]
My dear Friend,

I received a letter from thee, the week before last, which was sent by thy uncle Bolton:
there was a great many kind expressions in it, and in thy sister Clopton`'s likewise.
I acknowledge myself much obliged to you both, and to the whole family,
for many repeated kindnesses, and if my school had not engrossed so much of my time,
I would have taken opportunity to answer my dear friend`'s letter now,
and upon that account my delay will be the more excusable.

The news thou hast heard of my late change is really true, I cannot conceal it,
for it is what I glory in;
neither was it any prospect of temporal advantage that induced me to it,
but a sincere love to the truth, and pure regard to my own soul:
neither can I be sufficiently thankful to God,
that he hath let me live to this glorious day,
and not cut me off in the midst of my sins and provocations against him;
he is long-suffering to us-ward, not willing that any should perish,
but that all should come to repentance:
he hath brought me off from the forms and shadows of religion,
and let me see in a more illustrious manner what is the life and substance of it,
as he found me in some degree faithful to that measure
of light and knowledge he had bestowed on me,
whilst I was in the communion of the church of England; therefore he was pleased of late,
as I humbly waited upon him,
to make known to me greater and deeper mysteries of his kingdom; and I can truly say,
that I find by daily experience,
as I keep low and retired into that pure gift which he hath planted within me,
things are every day more and more cleared up to me, and the truth shines,
and prevails greatly over the kingdom of darkness;
and if I should now turn my back upon such manifestations as these,
and entangle myself again with the yoke of bondage,
surely I should grieve the holy spirit,
so that he might justly withdraw his kind operations,
and never return more to assist and comfort me; for God is not mocked;
religion is a very serious and weighty thing;
repentance and salvation are not to be trifled with, nor is turning to God,
to be put off till our own time, leisure, or convenience,
but we must love and cherish the least appearance of Christ,
not slighting or despising the day of small things,
but embrace the first opportunity of following Christ in any of his commands:
When he speaks, there is such force and authority in it, that we cannot stand to cavil,
dispute, or ask questions;
for unless we will be so obstinate as to shut our eyes against the sun,
we must needs confess to the truth of his doctrine, and presently strike in with it;
and therefore when for several weeks I had lived more privately and retiredly in London,
than was usual, fasting twice or thrice in a week, or sometimes more,
spending my time in reading the Scriptures, and in prayer to God,
this was a good preparation of my mind,
to receive the truth which he was then about to make known to me:
I lamented the errors of my past life,
and was desirous to attain a more excellent degree of holiness
than I had discovered in the church of England.
In this religious retirement, God knew the breathings of my soul, how sincere I was,
and resigned to him when alone; I wanted him to set me free,
and to speak peace and comfort to my soul,
which was grieved and wearied with the burden of my sin;
for though I had strictly conformed myself to the
orders and ceremonies of the church of England,
and had kept myself from running into any great or scandalous enormities,
the fear of the Almighty preserving me,
yet still I had not that rest and satisfaction in my self which I desired,
and greatly longed for; I found when I had examined my state and condition to God-ward,
that things were not right with me.

As for a sober and plausible conversation in the eye of the world,
I knew that was a very easy attainment, a good natural temper,
with the advantage of a literal education,
will quickly furnish a man with abilities for that,
so that he shall be looked upon as a saint, and very spiritual,
when perhaps in chains of darkness, in the gall of bitterness,
and in the very bond of iniquity: if this sort of righteousness would have done,
perhaps I might make as fair pretensions that way as some others; but alas,
I quickly saw the emptiness and unsatisfactoriness of those things:
this is a covering that will not protect or hide us from
the wrath of the Almighty when he comes to judgment:
`'tis not a man`'s natural temper, nor his education that makes him a good christian;
this is not the righteousness which the gospel calls for,
nor is this the truth in the inward parts which God requires;
the heart and affections must be cleansed and purified
before we can be acceptable to God;
therefore it was death to me to think of taking up my rest in a formal pretence of holiness,
wherein yet I saw to my grief abundance of people wrapped themselves,
slept securely and quietly, dreaming of the felicity of paradise,
as if heaven were now their own,
and they needed not trouble themselves any more about religion;
I could not entertain so dangerous an opinion as this,
for then I should be tempted to take up my rest by the way,
whilst I was travelling towards the promised land.
I think I made a little progress in a holy life,
and through God`'s assistance I weakened some of my spiritual enemies,
whilst I lived in the communion of the national church.
I thank my God, I can truly say, whilst I used those prayers,
I did it with zeal and sincerity, in his fear and dread,
but still I ceased not my earnest supplication to him in private,
that he would show me something more excellent,
that I might get a more complete victory over all my lusts and passions,
and might perfect righteousness before him;
for I found a great many sins and weaknesses daily attending me:
and though I made frequent resolutions to forsake those sins, yet;
still the temptation was too strong for me,
so I that often I had cause to complain with the apostle in the bitterness of my soul,
0 wretched man that I am, who shall deliver me from the body of this death!
Who shall set me free, and give me strength to triumph over sin, the world and the devil,
that I may in everything please God, and there may not be the least thought, word,
or motion, gesture, or action, but what is exactly agreeable to his most holy will,
as if I saw him standing before me,
and as if I were to be judged by him for the thought of my heart next moment.
O divine life!
Q seraphic soul!
O that I could always stand here! for here is no reflection, no sorrow, no repentance!
But at God`'s right hand there is perfect peace, and a river of unspeakable joy.
O that we might imitate the life of JESUS,
and be thoroughly furnished unto every good word and work!
This was the frequent breathing of my soul to God when I was in the country,
but more especially after I had left my new preferment of a chaplain,
and took private lodgings in London.
In this retirement I hope I may say, without boasting,
that I was very devout and religious,
and I found great comfort and refreshment in it from the Lord,
who let me see the beauty of holiness;
and the sweetness that arises from an humbled mortified life,
was then very pleasant to my taste,
and I rejoiced in it more than in all the delights and pleasures of the world.

And now it pleased God to show me,
that if I would indeed live strictly and holy as be comes the gospel,
then I must leave the communion of the church of England,
but knew not yet which way to determine myself, nor to what body of men I should join,
who were more orthodox, and more regular in their lives.
As for the Quakers so called, I was so great a stranger to them,
that I had never read any of their books, nor do I remember,
that ever I conversed with any one man of that communion in my whole life:
I think there was one in Foxly while I was curate there, but I never saw the man,
though I went several times to his house on purpose to talk with him,
and to bring him off from his mad and wild enthusiasm,
as I then ignorantly thought it to be: as for that way,
I knew it was everywhere spoken against;
he that had a mind to appear more witty and ingenious than the rest,
would choose this for the subject of his profane jests and drollery;
with this he makes sport, and diverts the company;
for a Quaker is but another name for a fool or a madman,
and was scarce ever mentioned but with scorn and contempt.
As for drollery I confess I was never any great friend to it;
but indeed if all was true that was laid to the Quakers charge,
I thought that they were some of the worst people that ever appeared in the world,
and wondered with what face they could call themselves christians,
since I was told they denied the fundamental articles of the holy faith,
to which I ever bore the highest veneration and esteem;
and notwithstanding I had always lived at the greatest distance from that people,
and was very zealous in the worship of the church of England,
and upon all occasions would speak very honourably of it,
moreover was content to suffer some few inconveniences upon that account,
(as thou very well knowest) yet my father still looked upon me as inclining to the Quakers;
and some years ago signified to a friend, he was afraid I would become an enthusiast;
and whilst I was at Bungan school,
he sent me two books to read that were written against the Quakers,
one of which was John Faldo`'s,
who hath been sufficiently exposed for it by William Penn.

Whilst I lived in London in that private retired manner (I was
just now speaking of) walking very humble in the sight of God,
and having opportunity to reflect upon my past life,
as I had occasion to be one day at a bookseller`'s shop,
I happened to cast my eye on Barclay`'s works;
and having heard in the country that he was a man of great account among the Quakers,
I had a mind to see what their principles were,
and what defence they could make for themselves; for sure thought I,
these people are not so silly and ridiculous, nor maintainers of such horrid opinions,
as the author of the Snake and some others would make us believe.
I took Barclay home with me, and I read him through in a weeks time,
save a little treatise at the end, which finding to be very philosophical, I omitted;
but however I soon read enough to convince me of my own blindness and ignorance,
in the things of God; there I found a light to break in upon my mind,
which did mightily refresh and comfort me in that poor low, and humbled state,
in which I then was; for l was then, and indeed had been for a considerable time before,
very hungry and thirsty after righteousness,
and there fore I received the truth with all readiness of mind;
'`twas like balm to my soul, and as showers of rain to the thirsty earth,
which is parched with heat and drought.
This author laid things down so plainly,
and proved them with such ingenuity and dexterity of learning,
and opened the scriptures so clearly to me, that without standing to cavil, dispute,
raise argument or objection, or consulting with flesh and blood,
I presently resigned myself to God,
and weeping for joy that I had found so great a treasure,
I often thanked him with tears in my eyes, for so kind a visitation of his love,
that he was graciously pleased to look toward me when my soul cried after him; so,
though before I was in great doubt and trouble of mind,
not knowing which way to determine myself,
yet now the sun breaking out so powerfully upon me, the clouds were scattered.
I was now fully satisfied in my own mind which way I ought to go,
and to what body of people I should join myself.
So I immediately left the communion of the church of England,
and went to Gracious-street meeting.
After I had read Barclay, I read some other books of that kind,
among which was an excellent piece, though in a small volume, called, [.book-title]#No Cross, No Crown:#
thus I continued weeks together, but did not let any one soul know what I was about:
the first man I conversed with was George Whitehead,
and this was several weeks after I began to read Barclay, and frequent their meetings:
by him I was introduced into more acquaintance, and still the farther I went,
the more I liked their plainness, and the decency and simplicity of their conversation:
They do not use the ceremonies and salutations of the church of England,
but shake hands freely, and converse together as brothers and sisters,
that are sprung of the same royal seed, and made kings and priests unto God.
O, the love, the sweetness and tenderness of affection I have seen among this people!
By this, says Christ, shall all men know that ye are my disciples,
if you have love one to another: Put on therefore, says the apostle,
(as elect of God holy and beloved) bowels of mercy, kindness, humbleness of mind,
meekness, long-suffering.

Thus, my dear friend, I have given thee an account of my proceeding on this affair.
As to my bodily state, if thou desirest to know what it is,
I may acquaint thee that I have my health, as well as ever,
and I bless God I have food and raiment sufficient for me,
so that I want no outward thing;
and I have the necessities and conveniences of life liberally;
let us not burden ourselves with taking care for the vanities and superfluities of it;
let us posses our vessels in sanctification and honour;
and as we bring our minds into perfect subjection to the whole will of God,
so let us bring our body to the most simple and natural way of living,
being content with the fewest things, never studying to gratify our wanton appetites,
nor to follow the customs and humours of men,
but how we may so contract our earthly cares and pleasures,
that we may bring most glory to God, most health and peace to our own souls,
and do most service to the truth; and if this be our aim,
certainly a very small portion of the things of this world will suffice us:
seeing we are christians,
we should therefore earnestly pursue those things which bring us nearest to God,
and which are most perfective of human nature; for what is more than a competency,
seems to be a burden to a generous philosophical soul,
which would breathe in a pure vehicle,
that so it may have a quick sense and relish of all blessings,
both of the superior and inferior Worlds.

Thou knowest, my dear friend, that religion is a very serious thing,
and repentance is a great work, and one precious immortal soul,
is of more worth than ten thousand perishing Worlds, with all their pomp and glory:
therefore let us take courage, and be valiant for the truth upon the earth,
let us not content ourselves with a name and profession of godliness,
let us come to the life and power of it, let us not despond of getting the victory;
we have a little strength for God; let us be faithful to him,
and he will give us more strength,
so that we shall see the enemy of our peace fall before us,
and nothing shall be impossible unto us: I say, my friend,
let us be faithful to that measure of light and knowledge which God has given us,
to be profited and edified by it in a spiritual life,
and as God sees we are diligent and faithful to work with the strength we have,
he will more and more enlighten us,
so that we shall see to the end of those forms and
shadows of religion wherein we have formerly lived;
but if he sees we are about to take up our rest in those shadows,
that we grow cold and indifferent in the pursuit of holiness,
running out into notions and speculations, and have more mind to dispute,
and to make a show of learning and subtility, than to lead a holy and devout life,
then `'tis just with God to leave us in a carnal and polluted state,
to continue yet but in the outward court,
where we may please ourselves with beholding the beauty and ornaments of a worldly sanctuary,
and never witness the veil being taken away,
and that we are brought by the blood of Jesus, into the holiest of all,
where alone there is true peace with God, and rest to the weary soul.
I could say much upon this head, if time or leisure would give leave.

As for a particular answer to thy letter, I have not time now to give it;
and for the present let this general answer suffice:
and if thou wilt consider things in their pure abstracted nature,
and not suffer the prejudice of education to sway thee,
but in fear and humility wilt search out the truth for thyself,
thou wilt find that there needs no other answer to
thy letter than what I have already given;
for by waiting upon God, and diligently seeking him,
thou wilt find an answer to it in thy own bosom, and this will be much more full,
clear and satisfactory than I, or any other man living can pretend to give thee,
or any other friend who hath lovingly wrote to me, for whom I desire,
with all the sincere-hearted in the church of England,
that they may come to witness the almighty power of God,
to save and redeem them from every yoke;
and that they may see clearly to the end of those things which are abolished,
and come to the enjoyment of spiritual and heavenly things themselves,
is the daily prayer and deep travel of my soul, God knoweth.
'`Till I can be more particular, if thou please thou mayest communicate this to them,
and let them know that I am well, and thank them for their kind letters.
Let us remember to pray for one another with all fervency,
that we may stand perfect in the whole will of God, Amen, saith my soul.
I am thy most affectionate friend and servant in Jesus,

[.signed-section-signature]
Samuel Crisp.

--

This epistle and the former of Evan Bevan are introduced by William Sewel as instances,
among many others, that those from other societies,
who have joined the people called Quakers, have been induced thereto, not by interested,
but by pure conscientious motives;
while those few who have left them to attach themselves to the established church,
or other professions, have been generally actuated by pique, self-interest,
libertinism or ambition, to indulge themselves in a latitude of conduct,
which the rules of this society do not allow of,
or to attain those honours or profitable employments,
which are restricted to a conformity to the established religion.
