== Chapter VIII.

Treaty of Aix-Ia-Chapelle.--The Quakers (so called) send R. Barclay`'s Apology
to each of the Plenipotentiaries.--Letter to the Ambassadors.--- Account of Benjamin
Kidd.--Alteration of the Style.--Paper of Advice thereupon.--Account of John
Richardson and Samuel Bownas.---Cafe of Daniel Hollis,
who died a Prisoner.--Account of Peter Andrews and
Abraham Farrington.-- Death of King George II.

The war which had begun between England and Spain in 1739, still continued;
and in the intermediate time,
the flame had spread over several pans of the continent of Europe, but by this time,
the several warring powers were heartily tired of contests
which had consumed profusion of blood and treasure,
and had been productive of abundance of mischief, and in the events of which, all,
in their turns had found themselves disappointed,
as generally happens in warlike contentions.
A negotiation was therefore resolved upon,
and the contending powers agreed to hold a congress at Aix-la-Chapelle,
for the purpose of concluding a peace,
to which all the powers at war sent their Plenipotentiaries.

The people called Quakers in London (as had been done before at the treaty of Nimeguen)
at the instance Simeon Warner resolved to send some of Barclay`'s apologies to Aix-la-Chapelle,
to be presented to the plenipotentiaries of the several
states assembled there for this purpose;
and Jan Vander Werf of Amsterdam,
being reputed to be the properest person to deliver the same,
being writ to for that purpose, he consented.

In the mean time it was thought expedient to prepare an epistle by way of introduction,
as to reasons for presenting the apology, which being drawn up and approved,
was printed in English and Latin, and is as followeth.

To the Ambassadors of the Christian Princes and States,
met to conclude a general Peace at Aix-la-Chapelle,
the People called Quakers wish Health and Happiness.

Near a century ago it pleased the Almighty to raise up a people in this kingdom,
to publish among other gospel truths,
the glad tidings proclaimed at the birth of our blessed Saviour,
Glory to God in the highest, and on earth peace, good will to men;
and also declare to the world, the inconsistency of wars and fighting,
with the example and precepts of Christ, and the doctrine of his followers.

The almighty hath been graciously pleased to continue
us a people to bear witness to the same divine truths,
and to engage us in love to the whole race of mankind;
to promote the knowledge and practice of the blessed doctrines,
as they tend so manifestly to extirpate violence, injustice,
and all the dreadful calamities of war; to establish peace and harmony in the world,
and to exalt the happiness of mankind both here and hereafter.

To contribute as much as in us lies to these important purposes,
we are induced to request your acceptance and candid
perusal of the apology herewith presented to you,
written by our friend Robert Barclay, for the spreading of truth,
and the information of mankind,
which at the same time that it exhibits the meek and humble pattern of holy Jesus,
the doctrine of his apostles, the sentiments of the early christians,
and our belief in relation to wars;
contains a compendious view of the christian religion,
divested of all those inventions with which it has been corrupted by the spirit of error,
the pride, the wickedness, or the ignorance of men.

This apology was addressed and delivered by the author
to Charles II. king of Great Britain,
and accepted by him and his royal successors, to whom it has been since presented,
with marks of regard: we fervently wish it may contribute to your solid advantage,
and by your means, to the promotion of peace, righteousness and true piety amongst those,
over whom your influence in your respective stations may extend.

May the God of peace and love make you the happy instruments of
settling the tranquillity of Europe on a lasting foundation,
and perpetuate the blessings of peace to the states you represent,
and through them to the whole world.

Signed in London on behalf of the aforesaid people, the 13th of 6th month called August,
1748.

Joseph Ollive, Jacob Hagen, Simeon Warner, John Hayward, David Barclay, Thomas Hyam.

A suitable number of the apologies, in different languages,
being sent over to Jan Vander Werf, and duly received by him,
he took a journey to Aix-la-Chapelle to execute his commission,
and by the account received from him,
he was pretty well satisfied with the success he had,
having waited upon the several ambassadors and presented them with apologies as directed,
from most of whom he met with a friendly and courteous reception,
and the letter and apologies were gratefully accepted, except by the French ambassadors,
who being informed that they were upon religious affairs,
signified they had no occasion for them, and refused accepting them.

Benjamin Kidd, who was born at or near Settle in Yorkshire,
of parents in profession with the people called Quakers, was educated in that profession,
and proved a very acceptable and serviceable member and minister of the society,
and although his place in the estimation of his friends and others,
might seem to require a more particular account of
the transactions of his life and of his services,
yet for want of other authentic materials, I must confine myself to the testimony,
given of him by his Friends.

While he was very young he was favoured with the
lively and powerful influences of divine grace,
inclining him to religious thoughtfulness; and being faithful to the discoveries thereof,
he was in or about the 21st year of his age, called to the work of the ministry;
wherein through the operation of the same divine principle, he grew in his gift,
and soon became remarkable for the excellency thereof,
even while he appeared young in years; and through the advancing stages of his life,
faithful in the discharge of manifested duty,
and humbly relying upon and fervently seeking divine aid and preservation,
he grew in grace, and I think it may be said, in favour with God and man.

He is described by his contemporary fellow members,
partakers of the benefit of his labours, and witnesses of his virtue,
as a man endued by the supreme dispenser of all good,
with eminent qualifications for singular usefulness and service in the church.
In the conducting of the discipline of the society manifesting peculiar abilities,
and exerting them for the good of the body in great wisdom,
being deep in religious experience, found in judgment, discreet and able in counsel,
and zealous for the promotion of truth and righteousness in the earth.
In the exercise of his ministry well qualified to divide the word of truth,
and to unfold the mysteries of the gospel,
to the informing and convincing many who before were unacquainted therewith,
and to the comfort and encouragement of such as were under affliction
and distress of mind in their religious progress.

He was a man of great sincerity and integrity;
in his common conversation becomingly cheerful, but weighty and instructive;
in his life and conduct an example of those virtues, which his doctrine recommended;
peculiarly kind and fatherly towards his friends, he was greatly respected by them;
compassionate to the poor and distressed; generous in his disposition;
of good communicative; he was very serviceable and respectable amongst his neighbours;
and generally beloved by persons of all ranks and denominations to whom he was known.

Being a man of universal benevolence, and zealous to do good to all,
he did not confine his service and usefulness to the place
of his residence and the neighbourhood thereof;
but followed the call of duty in paying religious visits to sundry parts of England,
for the propagation of righteousness and truth.
And about the 30th year of his age, he took a voyage to America on the like occasion,
where many were convinced, and others confirmed through his powerful ministry.
His service there was very great, and to the edification,
comfort and satisfaction of friends, as appears by sundry accounts from thence.

He afterwards married and settled at Banbury, in Oxfordshire,
and visited the meetings of his friends in Ireland,
and continued his visits to various parts of England: the city of London in particular,
frequently partook of the benefit of his pious and fervent labours in the ministry,
to the great help and consolation of many;
and in all his journeys moving under the influence of divine power and authority,
he was enabled to turn many from darkness to light,
and from the paths of disobedience to the wisdom of the just.

A few months before his death he was greatly afflicted with the stone;
yet at times he went a little out;
particularly he attended the quarterly meeting at Oxford, in the 10th month, 1750,
through great affliction of body.
About a month before his decease, he attended the meeting at Banbury,
at the burial of a young man of his acquaintance.
In the course of the meeting he was raised,
beyond all expectation to preach the gospel powerfully for about an hour,
to the tendering the hearts of almost all present; many of his neighbours being there,
confessed with admiration, to the power by which be was raised that day; remarking,
that he had been a good man all his time,
and that the Almighty had crowned him in the conclusion.
After this he was mostly confined within doors,
and continued in great submission to the divine will, without murmuring or repining.

A friend from London visiting him, found him under great bodily affliction,
but freely resigned to the divine will;
expressing his firm hope in that power which had all along supported him,
and that though the greatest kindness to him was to solicit a release from his pains,
yet he desired to be content and wait the Lord`'s time;
and when the said friend took his leave of him,
he expressed himself to him in an affectionate manner
to his great comfort and encouragement.

At another time, having delivered some excelent exhortations to those present with him;
he added for their encouragement to persevere in their christian progress,
"`I am under no fear, nor doubtful apprehensions;
for I know that for me to live is Christ, and to die is gain.`"

When he was seized with the cough, he seemed full of joy, saying,
"`This is a welcome messenger, it is one step nearer;`" his wife standing by, asking why,
he answered, "`It will be a glorious change, I am not afraid to die,
and to put on immortality; that will be desirable, yet I leave it,
though of choice I had rather be dissolved; but the Lord`'s time will be the best time.`"

He died the 21st of 3rd month, 1751, aged about 59 years, a minister 38 years.

In 1751, an act of parliament was passed in England,
for adopting the new style instead of the old,
which had hitherto been used in the British`' dominions.
The latter has been termed the Julian, from Julius Caesar,
who to reduce the civil year nearly to an equality with the tropical,
considered the year to consist of 365 days, and six hours, and therefore.
ordered that to every fourth year one day should be added,
and so make it consist of 366 days by adding one day to the month called February.
But the true length of the year is computed to be 365 days 5 hours, 49 minutes nearly,
i.e. 11 minutes yearly, less than the Julian computation, which in 131 years,
makes the difference of one whole day.
In 1572, pope Gregory XIII.
reformed the Julian calendar by putting the year ten days forward,
and this reformed calendar was thenceforward used by all those states,
which owned the pope`'s supremacy, and termed the new style;
while most of the protestant states continued the use of the former form of date,
frequently for distinction adding O. S. signifying old style,
and for the same reason such as used the Gregorian form would annex N. S. to the.
date.
From 1572 to 1752, one day more had been anticipated,
from which reason it was enacted that eleven day should be taken out of the calendar,
and the day after the 2nd of September, be called the 14th.

In conformity to this alteration the meeting for sufferings in London drew up,
and circulated to friends the following directions and advice.

An Epistle to the Quarterly and Monthly Meetings of Friends, in Great Britain,
Ireland and America.

Dear Friends,

Pursuant to the directions of the last yearly meeting, and the report of a committee,
appointed by the said meeting to consider what information
or advice might be necessary to be given to friends,
in relation to an act made the last session of parliament,
for regulating the commencement of the year, and correcting the calendar now in use,
this meeting hath thought convenient to communicate unto you the following advices, viz.

By the said act it is ordered and enacted, that, The "`supputation,
according to which the year of our Lord beginneth on the 25th day of March,
shall not be made use of from and after the last day of December, 1751,
and that the first day of January next following the said last day of December,
shall be reckoned, taken, deemed and accounted to be,
the first day of the year of our Lord, 1752, and soon from time to time,
the first day of January in every year which shall happen in time to come,
shall be reckoned, taken, deemed and accounted to be the first day of the year,
and that each new year, shall accordingly commence and begin to be reckoned,
from the first day of every such month of January.`"

2+++.+++ The opinion of the said committee, agreed to by the yearly meeting, was,
that in all the records and writings of friends,
from and after the last day of the 10th month, called December, next,
the computation of time, established by the said act, should be observed;
and that accordingly the first day of the 11th month, commonly called January, next,
shall be reckoned and deemed, by friends,
the first day of the first month of the year 1752, and

Eleventh Twelfth First Second Third The Fourth Month Fifth called
Sixth Seventh Eighth Ninth Tenth January First February Second
March Third April Fourth May shall be rec Fifth June koned,
and Sixth July ttiled the Seventh August Eighth September Ninth October
Tenth November Eleventh December 7vjelfth Month of the neit,
and trerj succeed ing Year.

3+++.+++ And whereas for the more regular computation of time,
the same act of parliament doth direct, that,
"`The natural day next immediately following the second day of September,
in the year 1752, shall be called,
reckoned and accounted to be the fourteenth day of September,
omitting for that time only,
the eleven intermediate days of the common calendar.`" The opinion of the said committee,
approved by the yearly meeting, was,
that friends should be sound in the observance of this direction,
and omit the said eleven nominal days accordingly.

And we think it may be useful and expedient, on the present occasion,
to revive in your remembrance some of the motives which induced our ancient friends,
to forbear the vulgar appellations of the months and days,
and to observe in their conversations and writings,
such names as were agreeable to scripture:
and the practice of good men therein recorded.

The children of Israel, the people whom God chose out of all the families of the earth,
to place his name among, and to make himself known unto, were strictly commanded,
not only to abstain from the idolatrous practices of the nations,
in the midst of whom they dwelt,
but were enjoined to be "`circumspect in all things that the Lord commanded,`"
and even to "`make no mention of the names of other gods,
neither to let it be heard out of their mouths,`" Ex. 23:13.
This injunction was not relative to any legal or typical rites,
external ceremonies, or institutions of the law peculiar to the Jewish nation,
but was a perpetual command and standing ordinance,
respecting the honour of the one Almighty Being, the same yesterday, today,
and forever, and as such, ought to be regarded by us,
and by all the generations of those, who with the heart believe,
as well as with the tongue confess, that the Lord he is God,
and that there is none else besides him, Duet. 4:35. who hath declared,
"`I am the Lord, that is my name, and my glory will I not give to another,
neither my praise to graven images,`" Isaiah 42:8.

Convinced of this great and everlasting truth,
both by the testimony of the holy scripture,
and the manifestation of that divine principle,
which leads those who are faithful to its teachings,
from all that would dishonour the name of God, either in word or deed;
our ancient friends were conscientiously concerned to refrain
from the use of those names of months and days,
which had been ascribed by way of honour to the idols of the heathen,
and in conformity to their false worships:
this concern rested upon them from a firm persuasion,
that the glorious gospel day and time was come,
wherein the Lord was fulfilling his covenant with Israel,
viz. "`I will take away the names of Baalim^
footnote:[This word Baalim, being the plural number of Baal, signifying Lord,
has relation to the names of divers idols of the heathen worshipped in several places.]
out of his mouth, and they no more be remembered by their name,`" Hosea 2:17.

And that you may the more clearly discern the importance of that christian testimony,
borne by our predecessors in this case,
we recommend what follows to your serious consideration, viz.

A brief Account of the Origin of the Names of some Months of the Year,
and of all the Days of the week, now customarily and commonly used.

I+++.+++ January was so called from Janus, an ancient king of Italy,
whom heathenish superstition had deified, to whom a temple was built,
and this month dedicated.

II. February was so called from Februa, a word denoting purgation by sacrifices;
it being usual in this month, for the priests of the heathen god Pan,
to offer sacrifices and perform certain rites, conducing, as was supposed,
to the cleansing or purgation of the people.

III.
March was so denominated from Mars, feigned to be the god of war, whom Romulus,
founder of the Roman empire, pretended to be his father.

IV. April is generally supposed to derive its name from the Greek appellation of Venus,
an imaginary goddess worshipped by the Romans.

V+++.+++ May is said to have been so called from Maia, the mother of Mercury,
another of their pretended Ethnic deities,
to whom in this month they paid their devotions.

VI. June is said to take its name from Juno, one of the supposed goddesses of the heathen.

VII.
July so called from Julius Caesar, one of the Roman emperors,
who gave his own name to this month, which before was called Quintilis, or the fifth.

VIII.
August so named in honour of Augustus Caesar, another of the Roman emperors.
This month was before called Sextilis or the Sixth.

The other four months, namely, September, October, November and December,
still retain their numerical Latin names, which,
according to the late regulation of the calendar,
will for the future be improperly applied.
However from the continued use of them hitherto,
as well as from the practice of the Jews before the Babylonish captivity,
it seemeth highly probable,
that the method of distinguishing the months by their numerical order only,
was the most ancient, as it is the most plain, simple and rational.

As the idolatrous Romans thus gave names to several
of the mouths in honour of their pretended deities:
so the like idolatry prevailing among our Saxon ancestors,
induced them to call the days of the week by the name of the idol,
which on that day they peculiarly worshipped.
Hence

The first day of the week was by them called Sunday,
from their customary adoration of the sun upon that day.

The second day of the week they called Monday,
from their usual custom of worshipping the moon on that day.

The third day of the week they named Tuesday,
in honour of one of their idols called Tuisco.

The fourth day of the week was called Wednesday, from the appellation of Woden,
another of their idols.

The fifth day of the week was called Thursday, from the name of an idol called Thor,
to whom they paid their devotions upon that day.

The sixth day of the week was termed Friday, from the name of Friga,
an imaginary goddess by them worshipped.

The seventh day they styled Saturday, as is supposed from Saturn, or Seater,
by them then worshipped.^
footnote:[See Verstegan and Sheringham.]

The continued use of these names of days,
derived from such gross idolatry of the heathen, is a demonstration,
how little the purity of the christian religion was understood by the
generality of those who came into the public profession of it.

The following ages of Popish superstition,
not only indulged their proselytes in the use of such heathenish names and customs,
but also invented and introduced other unsound and unscriptural practices in religion.
For when the profession of the christian religion became national,
multitudes of the heathen priests, whose interest lay in the performance of rites,
ceremonies and sacrifices, embraced prevailing Christianity with selfish views,
and laboured early, with too much success, to find employment for themselves,
by imposing on the people a new set of ceremonies and sacrifices,
bearing some resemblance to those which in their former
state of heathenism they had been accustomed to.
From this corrupt source sprang the Popish sacrifice of the mass,
the celebration of which, at particular times, and on particular occasions,
gave rise to the vulgar names of Michaelmas, Martinmas, Christmas, and the like.

Seeing therefore that these appellations and names of days, months and times,
are of an idolatrous or superstitious original, contrary to the divine command,
the practice of good and holy men in former ages,
and repugnant to the christian testimony borne by
our faithful friends and predecessors in the truth,
for the sake of which they patiently endured many revilings:
let neither the reproach of singularity nor the specious
reasonings of such as would evade the cross of Christ,
turn you aside from the simplicity of the gospel,
nor discourage you from keeping to the language of truth,
in denominating the months and days according to the plain and scriptural way of expression;
and so shall we follow the example of our worthy elders,
and come up in a noble and honourable testimony against these,
and all other remains of idolatry and superstition.

From the meeting for sufferings in London, the 6th day of the 7th month, 1751.

It is to be especially noted,
that the dates hitherto used have been conformed to the old style,
and sometimes so distinguished;
and here after the months are numbered according to the new style,
as regulated in the foregoing directions.

This year John Richardson, formerly of Bridlington,
and afterwards of Hutton in the county of York,
a minister of deep experience and primitive simplicity and self denial,
died in an advanced age, very much devoted to the service of God,
and promotion of pure religion.
He was the son of William Richardson, of North Cave in the same county,
who was early convinced by the ministry of William Dewsbury,
and joined himself in society with the people called Quakers,
amongst whom he was a serviceable member and minister;
but John was early deprived of the religious care,
oversight and instruction of his well concerned father, who was removed out of this life,
when this son was about 13 years of age.

Peculiarly severe were the trials of this friend, both inward and outward.
From the time of his father`'s death much bodily hardship,
circumstances singularly distressing from various outward occurrences fell to his lot,
besides a succession of internal conflicts and deep
exercise of mind in his religious researches.
For in this early part of his youth,
he felt the convictions of divine grace disquieting his mind,
when he was tempted to commit evil in any degree, in word or in deed.
Yet reluctant (as is the nature of man)t to take
up the cross to his corrupt will and propensities,
he strove to attain ease and peace, by silencing these disquieting convictions,
and indulging his natural inclinations, which were not to gross evils,
but to youthful liberties.

And notwithstanding he received his early education
in the society of the people called Quakers,
yet after the decease of his father, his surviving parent,
though well esteemed in her neighbourhood, for industry and honesty,
seemeth to have been not over solicitous about the religious institution of her offspring,
leaving them in this respect pretty much to their own direction,
so that her son John was at liberty to use his own
discretion to associate with any religious society;
and he appears to have used the liberty granted him, resorting sometime to one,
and sometime to another, as his inclination led him,
'`till about the sixteenth year of his age.

Yet even in this unsettled state as to religious profession,
he was favoured with religious desires,
which engaged him to converse with professors of different denominations,
inquiring of them for information,
if they could direct him wherein he might find a safe rest to his soul;
but after much searching and inquiring of those (as
he expresseth it) who were but in the letter,
and in the outward court, where the veil is over the understanding,
he found his search ineffectual;
and therefore instead of going from one set of professors to another for information,
he declined to join any visible society, and betook him self to a retired life,
seeking solitary and private places to pour out his supplications to the Almighty,
that he would bring him to the saving knowledge of his truth.
This petition he thought was graciously answered,
being favoured with the illumination of the true light,
discovering the wants of his soul in its unregenerated estate;
and the necessity of being born again,
to be prepared for an entrance into the kingdom of heaven.
Through many painful conflicts under the cross, crucifying him to the will of the flesh,
and the spirit of the world, and great distress and tribulation of mind,
under the ministration of condemnation,
he gradually experienced the washing of regeneration,
and the renewings of the Holy Ghost, to effect that change,
whereby the condemnation was removed,
and justification in righteousness measurably attained.

In his time of unfixedness in religious profession and of seeking peace, if possible,
without taking up the cross to his own corrupt will and inclinations;
to that of the people called Quakers, their name of contempt,
their strict way of life and demeanour,
plainness of habit and language (none of which he saith
he learned of them) he had a particular aversion,
but when his eyes were illuminated to see the teacher,
that was not removed into a corner, and learn of him, who is meek and lowly,
taking his yoke upon him,
he found himself circumscribed and restricted to the like self-denying practice,
which had been the object of his aversion, and that not by imitation but conviction,
in like manner as the faithful members of this society
from their beginning had been restricted.
Being thus by the same internal monitor brought into the same faith and practice,
he reclaimed his birth-right in this society,
and attended their meetings as diligently as his circumstances would well admit,
about the 16th year of his age; and about the 18th,
he appeared in the ministry and in process of time became an excellent minister,
not of the letter only that killeth, but of the spirit that giveth life.

Now when he had attained to some stability in religion,
and peace of mind succeeded the in ward conflicts
and trouble through which he had hitherto passed,
his faith and patience were put to close and severe trials from various outward contingencies,
of a nature particularly distressing.
His father left a widow with five children,
and but little substance beside his farm to subsist upon.
John was the eldest, but one sister, who died soon after,
whereby he found himself under a necessity to apply to hard labour for his own support,
the help of his mother, and education of his younger brothers.
By his labour and care, through the divine blessing, the family were decently supported,
and were prospering in their circumstances, when an occurrence happened,
which was attended with grievous consequences to this young man.
His mother was solicited to a second marriage by a person rigidly zealous for Presbyterianism.
John, apprehending he foresaw unhappy consequences from the unequal match,
took the liberty to remonstrate against it, and told his mother that he feared,
she had too much an eye to the man`'s circumstances (for he was reputed to be rich) but
if she thought to improve her children`'s portions by a connection with him,
she would meet with a disappointment of her hope; and not only so,
but a blasting and mildew would come upon their own substance,
the fruit of much labour and care, and which he believed would be blessed to them,
if they kept faithful to the truth,
and would content themselves with their present condition.
His mother, although she seemed affected with his discourse,
and gave some expectation that she would not marry any person with whom he was dissatisfied;
was notwithstanding prevailed upon to join herself
in the marriage against which he had remonstrated,
which turned out much as he had foreseen.

For with her the family being young, removed to the step-father`'s house,
and their substance was intermixed with his; his mother dying before her husband,
and he afterwards marrying again, by his last will left John Richardson five shillings,
and some small token to his only surviving brother,
in bar of any demand for their share of their parent`'s substance,
yet this was at the time a light affliction to what
he had in the intermediate time to experience.

He had not been long in his step-father`'s house '`till he found his situation very uneasy.
His father-in-law treated him with symptoms of great displeasure, harshness and severity,
on account of his going to meeting.
John who seems to have been kept by him more in the station of a servant than a son,
endeavoured to appease his displeasure by unremitted diligence in his business,
working very hard, beyond his ability, even to that degree,
that it seemed wonderful how his young weak body
sustained the hardships which he at this time endured.
But his most earnest endeavours to gain his father`'s countenance proved ineffectual;
for his faithfulness and diligence in his business availed little.
His father seemed callous to all reconciliation,
while he continued to frequent the meetings of the people called Quakers,
and declined the accompanying him to those of the Presbyterians.
To render his attendance of the former as uneasy and distressing as possible,
his father would send him on first day mornings,
some miles into the fields and over the common to look after his cattle,
horses and sheep,
both to fatigue him and straiten him for time to reach the meetings of his friends,
to which he had two, three, four, sometimes six miles to ago, mostly on foot,
and often in limited in time, that he was obliged to walk very fast,
and frequently to run, to reach the meeting timely;
which severity he bore with remarkable patience.
His mother was affected with great anxiety and grief,
under the mortifying reflection upon the hard circumstances,
in which she had been instrumental to involve a dutiful son, who, she acknowledged,
had never disobliged her,
but had obeyed all her lawful directions and desires with alacrity;
and that in contradiction to the gentle caution,
wherein he had previously communicated his opinion of the consequences of her marriage.
Several friends also could hardly forbear shedding tears,
when they saw him come into the meeting in a violent heat and perspiration,
sympathizing with him in the hard task he had to undergo.
On his return from meetings he was generally received by his father
with a countenance of displeasure and harsh rebuke as for delay,
although he returned as seasonably as his strength
and the distance of place would admit.

At some times his father, on the other hand, would treat him with apparent kindness,
to induce him to go with him to the place of worship he frequented,
offering him in that case a horse to ride.
Again he took him in his arms, and fawningly told him to this effect, that,
'`if John would behave as a son to him, he should find a father in him,
hinting that he had no near kindred.
As John was conscious that he had behaved to him as a son in doing
everything in the way of business that he required of him,
and by his diligence had frequently anticipated his commands,
he was at no loss to interpret his father`'s meaning in this proposal,
and therefore replied, "`If in thus making me thy son,
thou intends to hinder me from going to meetings,
or to oblige me to go to the Presbyterians meetings,
or any thing that is against my conscience, I cannot on this condition be thy son.`"
And for the same reason he refused to become his hired servant,
which he offered to make him and give him wages.

When his father found that neither his frowns, his imposition of hardships, his menaces,
nor his promises of kindness could shake his step-son`'s
steadfastness in his religious principles,
he suffered his passion and bigotry so far to erase all tenderness and humanity,
that in much wrath he abruptly told him that, he should stay no longer in his house.
John pleaded against this hard sentence his constant endeavour to serve
him faithfully to the best of his power by night or by day,
and his purpose to do so still,
as far as he could without hurting his conscience or wounding the peace of his mind,
which he valued above all the mutable things of this world.
But his father was too much determined, to be moved by any considerations of this kind.
John even solicited his father to permit him to stay till he might hear of a place of
service (though so weakened and emaciated by hard labour that he hardly seemed fit for
one;) but the obdurate man would not comply with this last reasonable request.
His mother was an afflicted witness of her son`'s solicitations,
and her husband`'s obstinacy, which so overwhelmed her in sorrow,
that John found it requisite to leave his father,
in order to endeavour to alleviate his mother`'s grief, telling her,
That if he was but faithful,
he trusted in the Lord that he would take care of him that he should not want.`'
Withal reminding her, that as she had entered into marriage covenants with her husband,
she should endeavour to perform them, and to make her life as easy as she could,
and never to send him anything, which her husband knew not of,
for he was not free to c receive it, although all their substance was sunk in his hands.

Thus determined his father turned him out, weak in body, dejected in mind,
with very little money in his pocket, and very ordinary clothes upon his back.
Upon his taking leave of the family many tears were shed, especially by his mother.
The father stood as one amazed to see the marks of
so general affection manifested toward him,
and general a sorrow at his departure.
Yet as destitute of common justice as of every tender feeling,
he hesitated not to turn him out into the wide world, to make his way through life,
stripped of every accommodation,
and in as destitute a condition as almost any one could be,
notwithstanding this father was reckoned rich,
and certainly owed him some recompense for his service,
and for his share of his own father`'s property,
which appears to have been considerably improved by his care and labour,
and of which this father had possessed himself.

He went out on the common, where he had taken many solitary walks before,
yet none so severely trying as this, because he knew not whither to go,
nor where to lay his head,
not but many of his friends would have given him a kind reception,
but he was unwilling to be burden some to any,
unless he knew they had business to employ him in, and looking to one side and another,
he thought it appeared, as if his way was hedged in on every side,
and that scarce any man on earth was in so desolate a condition.
Under great distress and dejection of spirit,
he gave vent to the anguish of his heart in cries and tears
and supplications to the Judge of all the earth,
who, he thought, heard and answered his cries with this intelligence,
"`First seek the kingdom of heaven and the righteousness thereof,
and all these things that thou standeth in need of shall be given unto thee.`"
He believed and therefore found his mind reduced into quietude
and saw then the place to resort to and abide for a season,
viz. to the house of William Allen in South Cliff,
to whom he bound him self to learn his trade, which was that of a weaver.

Although he might seem here in a very low sphere of life,
yet he found himself settled to his full content and his situation changed for the better.
Beloved by his master, and loving him sincerely, they lived together in great harmony.
When his master understood, he had any concern or desire to visit any meetings,
he would not suffer his business to be any impediment,
but would desire him to take his mare and go,
without any uneasiness either about the mare or business.
Here he spent some time in short excursions to visit his friends in their meetings,
as he apprehended the call of duty thereto,
and in a diligent and close attention to his outward employment at home;
both out of conscientious regard to his duty,
not as an eye servant but in singleness of heart, as toward God;
and also out of gratitude to so kind a master,
he thought himself obliged to exert himself to the utmost,
to make him a recompense as far as in his power.

It may perhaps to some readers appear beside the point,
to descend to such particulars in the early stages of this friend`'s life,
but it seems directly coincident with my design,
which the reader hath been apprised is to exemplify the excellent
effects produced in the hearts and actions of men,
by a steady adherence to that inward principle of light and grace,
which the people called Quakers most surely believe in, and bore testimony to.

His first journey of consequence was into Lincolnshire, Nottinghamshire and Warwickshire;
and he was careful to return home as soon as by a
diligent discharge of his duty and service,
he could with ease and peace of mind,
to apply himself with industry to his outward occupation, for his support,
and procuring a little surplus to supply his necessary expenses in his future travels:
and thus from the 20th to the 28th year of his age,
he divided his time between an industrious application to his secular employment,
to provide things honest in the sight of all men,
and the discharge of his duty in fulfilling his ministry,
for the edification of his friends and others; during which time,
he travelled through most parts of England four times,
and twice through most parts of Wales.

About this time he entered into a married state, and settled in Bridlington,
where he was made instrumental to the help and strengthening
of many in their religious progress,
especially amongst the youth,
several of whom were called to the work of the ministry and grew therein,
to be serviceable men in their time.
He was likewise very helpful in the promoting a settlement of a salutary discipline,
in the monthly meeting, where it had not been so zealously supported,
as in some other places.

In about five years after his marriage, his wife was taken from him,
and he was left a widower with three small children,
and at the same time having had many years a prospect
of duty to visit his friends in the American colonies,
and the appointed time appearing to draw near,
he laboured under much discouragement in consideration of his circumstances in the world,
which were far from opulent,^
footnote:[Upon mentioning his outward circumstances,
as being possessed of little substance, he explains his meaning by some reflections,
expressive of that honest simplicity and integrity,
conspicuous in the primitive professors of the principle of a divine light,
in the following terms, "`I would not have any to misunderstand me,
for as to my outward circumstances, I left no debt,
neither was I in a way of going backward in the world;
forever after I received the knowledge of the truth,
I could not see what pretence I could have to religion, if any should lose by me:
I have often said, and been hearty in my intentions,
That rather than truth should suffer on that score, I would live upon bread and water,
and wear very mean clothes, and work very hard, if I were able, and upon any mean,
if but lawful calling.
It hath been matter of wonder to me,
how any that appear to carry any pretensions to religion, dare run such great ventures,
sometimes beyond their own bottom or abilities;
which to me hath always appeared an unwarrantable risk; and, as I apprehend,
pride and ostentation is much the occasion of it, which are much against truth,
and men are no better for their greatness, for the more plain and the more humble we are,
the more we resemble humble Jesus, and the religion, which he laboured to inculcate.
If any are lifted up, or aspire above their place,
let them consider well the foregoing paragraph.`"]
and the charge of his helpless children; but providence so ordered it,
that his youngest child was removed by death in less than a year,
and his two other children were placed to his own satisfaction and that of his friends.
Whereby seeing his little family and his affairs reputably settled,
that the truth which he professed,
and for the promotion whereof he thought it his duty to
leave all his near connections and his native country,
might receive no dishonour by any contingency in his private affairs in his absence,
he took leave of his friends at home,
not without the natural emotions of sorrow and regret,
and set forward on his journey to London, whence he proposed to embark in the 8th month,
1700, and sailing from thence in company with Thomas Thompson,
Josiah Langdale and John Estaugh, the 17th of the following month,
after a tedious passage of sixteen weeks arrived in the river Patuxent in Maryland.

He spent about two years and a half in this journey,
in which time he visited the colonies generally where friends were settled,
viz. Virginia, Maryland, Pennsylvania, etc. to New England, and sundry parts twice over;
after which he visited the islands of Bermudas and Barbados;
from the latter he took shipping for Bristol,
where he arrived in the 6th month called June, 1703.

In this journey his ministerial labours were eminently serviceable,
acceptable and edifying, to the convincement of many, and confirmation of many more,
particularly in the island of Nantucket, where,
the whole meeting or greatest part were wonderfully affected by the power attending
his ministry--sundry remarkable occurrences he met with in the course of his travels,
which are related at large in his journal, to which I refer the reader,
as a work profitable from his wise and instructive reflections,
and agreeable from the variety of incidents and his
plain yet pleasing manner of relating them.
The narrative of his controversy with George Keith,
hath already filled some pages of this volume;
and in the course of his travels he met with other occasions of debate,
especially in New England,
from the opposition of some professors of the religion of that country, to his doctrine,
which he managed with so much wisdom, temper and modesty,
as carried with them evident conviction of the truths he defended.
In passing some of the great rivers and other waters in open boats,
he and the company appeared oftener than once in great danger of losing their lives,
through accidents, the badness, inconvenience or mismanagement of the boats,
in most of which perils, he seems, under providence,
to have been principally instrumental to the escape of himself and companions,
by his exertions and presence of mind.
An instance whereof, accompanied with sensible and edifying reflections,
I think not impertinent to introduce here from his journal,
in hopes it may engage the attention of some readers to profit thereby.

In our imminent danger (saith he) I looked over my tender friends,
and thought in my heart, what a pity it would be,
if all these were drowned! yet the thought of my own drowning never entered my mind,
until I was got over the river, which was a mercy to me,
and a great means to keep out the disorder and confusion,
which commonly attend sudden surprises and frights, which also make many fainthearted,
and almost senseless.

On this occasion, as well as many others,
I reflected that it is an excellent thing to be, as much as we can, always ready,
and by frequent ruminating upon death, to live so as to be fit to die,
that it may not cause so much surprise and consternation when it doth come:
this is a great point of true wisdom, so to number our days,
as to consider our latter end.`"

Whilst he remained at home,
he was exemplary in the diligent attendance of the meeting to which he belonged,
as also the monthly and quarterly meetings; and visited many meetings abroad.
After living in the state of a widower near seven years, he married again;
but in a few years, he was deprived of his second wife.
Both his wives were sober, religious women, fit help-mates in the best sense,
ready to give him up,
and to forward rather than obstruct him in the faithful
performance of every religious service.
During the time of his last marriage, he paid two religious visits, one to the northern,
and the other to the southern counties of England.
And afterwards repeated his visits to the same parts: in the year 1717,
he visited the western counties as far as Cornwall: Ireland in 1722;
and in the 3rd month, 1731, he a second time embarked for America,
and visited the meetings of his friends generally through the colonies on the Continent,
which took him near two years to accomplish, returning home the 1st of 3rd month, 1733.

He lived to a good old age,
and when he was confined by the infirmities attendant this stage of life,
and his natural faculties somewhat impaired,
he appeared more heavenly-minded to the last, and finished his course in this world,
in a well grounded hope of the fruition of that happiness,
which is prepared in the next for those who persevere to the end in well-doing.
He died the 2nd of the 4th month, 1753, in the 87th year of his age,
and was buried in friends burying ground, at Kirby-moorside.

Samuel Bownas of Bridport, in Dorsetshire,
who was also a very serviceable and well-approved minister of this society,
died in the course of this year,
and upon the very same day with the afore-mentioned friend.
He was born in Westmorland, within the compass of great Strickland monthly meeting,
about the year 1676.
His father was taken away before he attained the capacity of knowing him,
being only about a month old; but he was informed by those who knew him,
that he was an honest zealous friend,
and a considerable sufferer upon account of religion,
both in the loss of his substance and liberty, the meeting being kept in his house,
in some of the hottest time of persecution in the reign of king Charles II.

His mother, who was a religious woman, was very careful to train him up in sobriety,
and to advise him to the fear of the Lord in his youth, but being in low circumstances,
she put him apprentice to a blacksmith, when he was but about 13 years of age.
He was first put out with his uncle, and afterwards to Samuel Parrat of Brigflats,
an honest well-minded friend, who treated him with affectionate kindness;
yet notwithstanding his mother`'s tender care, and his master`'s example,
he was as yet very indifferent about religion, and had very little sense thereof.
On first days he frequented meetings, but received little other benefit there by,
than being prevented from falling into hurtful company,
which indeed is a very great service to youth.
In this time of inadvertency, he indulged himself in a latitude in conversation,
for which he often met with remorse and inward reproof;
not that he was tainted with any gross vice,
but was much given to jesting and witty turns to provoke mirth;
whereby he gained the reputation of a witty, sensible young man;
but the airiness of his discourse,
in the hour of cool reflection was generally succeeded by
a heavy heart under the conviction of divine grace.

About the middle time of his apprenticeship, he met with an awakening reach.
One first day morning a young woman preaching in their meeting,
and Samuel fixing his eye upon her, she seemed to point at him,
and uttered the following expressions with great energy,
"`A traditional Quaker! thou comest to meeting as thou went from it the last time,
and goest from it, as thou earnest to it; but art no better for thy coming:
what wilt thou do in the end?`" These words were so
exactly adapted to his state at that time,
that he conceived them to have been spoken to himself and was, as it were,
smitten to the ground; and in the awakened language of his soul,
poured out this secret ejaculation "`Lord, what shall I do to help it?`" when he heard,
as if a voice spoke in his heart, "`Look unto me,
and I will help thee,`" which administered comfort to his soul.

Yet in his return home he was affected with anxiety and serious thoughtfulness
to that degree that he could neither eat nor sleep as usual.
The solidity of his conduct and the gravity of his countenance
evidenced a great and sudden change in his mind and manners,
his mirth was turned into mourning under that godly sorrow which produceth sincere repentance,
so that several who observed him were apprehensive of his danger of falling into a melancholy.
But in this state of inward thoughtfulness and exercise
of spirit on the most important of all subjects,
the religion whereby he might please his Maker, and secure the happiness of his own soul,
he found a solemnity over his mind, such as he had not known before.
And now when he came to meeting he was neither drowsy as had been too customary with him,
nor distracted by wandering cogitations; but inward stillness,
and true devotion of heart before God, was strengthened to worship him,
according to his own requirings "`in spirit and in
truth.`" His soul was quickened by the word,
which is quick and powerful,
and his understanding experimentally opened into
the meaning and application of the Scriptures,
and the nature of true gospel ministry,
which '`till then he appears to have been wholly ignorant of;
so that he seeemed to himself another man.

It was not long after his reformation, that he was called to the work of the ministry;
but he began to reason within himself,
that "`so sudden a change would hardly be borne;`" and several
of his companions being present in the meeting,
who had been witnesses of the levity of his late conversation,
and his faculty of creating and circulating mirth amongst them,
they proved another cause of discouragement in his way: so that more than once,
while he sat under the increasing burden of the word,
by the like reasoning he put it off.
In consequence he fell under great distress of mind,
fearing that he had by disobedience offended to that degree,
that he should be cast off forever; he sought solitude,
to give vent to his sorrows in secret, remote from observation of men;
but the effects of his troubled mind, and of his tears,
became visible on his countenance, which his master observing and sympathizing with him,
kindly inquired the reason of his trouble, which he candidly discovered.
Hereupon his master consoled him with the hope,
that he would come under the like concern again, and advised him to give way thereto,
which he accordingly did, to his great consolation and peace of mind.

He had at this time about three years of his apprenticeship to serve,
during which he continued at times to appear in the ministry in a few words at home,
but did not travel much abroad till the term of his servitude was expired.
Having served his full time with fidelity and diligence,
and in the last year conceiving a draught of duty
to pay a religious visit to friends in Scotland,
he set out in company with Isaac Alexander,
beginning their journey on foot at Kendal and the adjacent meetings,
they proceeded through part of Lancashire and Yorkshire;
then visiting some parts of Cumberland, they went forward to Scotland,
and accomplished their visit in about two months.
In this journey Samuel thought his companion had very good service,
but he himself was deeply proved with poverty of spirit,
which appeared at the time hard to bear,
being filled with anguish under the power of death and darkness,
and all comfort hid from him; but when the cloud which coveed his mind was blown over,
he clearly saw the benefit of trials in different dispensations,
for improvement in experience and for establishment
in the root of a divine and spiritual ministry.

Many of these bright ministers of the northern counties
were but in narrow circumstances as to earthly possessions,
being raised up from the lower class of people,
of which number this worthy friend was one.
His late journey having well nigh consumed what little money he was master of,
he returned home almost penniless; therefore the time of hay-harvest coming on,
he applied himself to mowing and other harvest work, as a day labourer,
for his present support;
and to lay up a part of his earnings to put himself
in proper condition for another journey,
and for his expenses and accommodation therein;
at the same time he attended such neighbouring meetings,
as he felt an engagement to visit,
going to one or another to the distance of 10 or 12 miles on foot,
and returned back the same way to follow his labour.
It was thus these disinterested men, after the apostolic practice, divided their time,
disengaging themselves from the world, and all worldly engagements,
when they apprehended the call of duty to go forth with the message of the gospel,
and when discharged from the concern,
to labour with their hands to supply their necessities,
that they might not make the gospel chargeable or
burdensome to those they ministered unto.
In the succeeding autumn and winter of the year 1699,
he visited several of the southern and western counties of England, and part of Wales,
and in the succeeding year visited many meetings on the eastern side of England.
In 1701, he visited Scotland a second time in company with Isaac Thompson,
and after visiting the meetings of his friends in a general way,
they came to Kelso in their return to England, and from thence to Jedburgh,
a town where none of the people called Quakers resided, and where '`till this time,
they were very little known, except as abusively represented by the preachers.
When they came thither, they went to an inn,
but the bigotted landlord refused them entertainment,
their minister having endeavoured to paint out this people to his hearers,
in the must hideous colours.
They went to another inn, where they obtained admission,
and after they had taken some refreshment, they went out into the street,
and sat down at the market cross;
but had not sat long '`till they were taken into custody, and committed to prison.
Soon after a messenger came from the provost to offer them their
liberty on condition that they would depart the town without preaching,
Samuel signified that they could make no such agreement,
and wrote to the provost their reasons;
but the people were so deterred from holding any communication with them,
that it was very difficult to procure any messenger to carry the letter.

Next day +++[+++through the intervention of a country gentleman]
they obtained their liberty, and it being market-day,
and the town full of country people; after refreshing themselves at the inn,
they went up to the market-cross, but finding no convenient room there,
they removed to another eminency, near the highest part of the principal street;
Samuel Bownas there preached to a crowded body of several hundreds of people;
and being afterwards fervently concerned in prayer,
while he was praying two men took him by the arms, and led him down the street,
he in the mean time continuing his prayer as they led him along, till it was finished.
They conveyed him again to the prison door;
but he pleaded against a second illegal imprisonment,
that he should not willingly go thither again,
without being first examined by a magistrate, and if it appeared he had broken any law,
or committed any offence worthy of imprisonment,
and they had a mittimus setting forth his crime,
he would not refuse submission to legal authority; but without it, he would not go,
except he was forced by violence, which he hoped they would not attempt.
A soldier, who stood sentinel at the prison and overheard this plea,
insisted that his countryman had spoken right, according to law and justice;
and therefore (said he) "`if you will take him before the provost for examination you may;
but if not, touch him, who dare.`" This laconic speech uttered with a determined air,
had its effect, the officers went off, and left Samuel again at full liberty.

Samuel being elevated several steps above the attendant crowd,
it burnished him with a favourable opportunity to give them a second exhortation,
the people were very quiet and attentive, appeared respectful and well satisfied; and he,
having discharged himself of what he conceived his duty,
retired to the inn full of peace and consolation.
In the evening some of the better sort of the inhabitants paid them a friendly visit,
which was pretty long;
for as they were very much strangers to the people and their principles,
they were desirous to be informed, and spent some hours in religious conference,
where in Samuel was enabled to answer their objections,
and satisfy their inquiries pretty fully.
So they took their leave in a friendly and affectionate manner, at a late hour,
seemingly pleased with the information which they had received.

In the third month 1702 he embarked for America,
and arrived in river Patuxent in Maryland, the latter end of 5th month following,
and here almost immediately after, he received the challenge from George Keith,
which with his consequent imprisonment hath been related in course.^
footnote:[See page 134, etc.]
He visited the meetings of friends pretty generally
through the sundry British colonies in North America,
from Carolina to New England, which with the time he spent in confinement,
took him upwards of four years, it being 10th month, 1706, when he landed at Portsmouth.
His service was very considerable,
and very acceptable to his friends there in a general way,
and instrumental to bring over several to the society by convincement.

Having thus diligently employed his time from the expiration
of his apprenticeship '`till the 30th year of his age,
between his temporal and spiritual engagements,
soon after his return from America he married a young woman in Somersetshire,
and removed to reside with her there.
His engagements in marriage and in business for the support of his family,
did not divert his attention from that which he esteemed his principal engagement,
a life of devotedness to the will of God,
and promoting a religious life and religious dispositions among his friends and others.

ln the summer 1708, he went over to Ireland,
on a religious visit to friends of that nation,
and in the intervening time between his landing at Cork,
and the ensuing half-year`'s meeting in Dublin,
he visited the meetings gene rally through the nation, and after the half-year`'s meeting,
took shipping at Cork, and landed at Minehead, after an absence of more than 18 weeks.

After his return from this journey,
he seems to have been for some time released from distant travels,
but was diligent in his outward occupation, and in visiting the neighbouring meetings,
which were pretty numerous.
In 1715, he visited Cornwall.
In 1719, sundry counties of England, and Scotland a third time.
In 1726, he embarked for America again,
and after a tedious voyage of eleven weeks landed at Hampton in Virginia,
whence he proceeded through the colonies to New England and back again,
having visited most of the meetings of his friends through all the provinces,
and sundry of them several times over, and finished his service where he began it,
at Hampton; from which place he reembarked for England, in company with Robert Jordan,
thankful that he had been preserved in health,
and supported with strength both of body and mind,
to accomplish this long and tedious journey,
through the very severe extremes of heat and cold, in about eighteen months.

In the latter part of the voyage, they met with a violent storm,
such as the sailors said they had not known before, and it came upon them so suddenly,
that they were not prepared for it; the water came in upon them and so increased,
that it was seven or eight feet deep in the hold.
It stayed the water casks fastened on the decks,
whereby they lost above a tun and a half of water; washed some hogs over board,
and destroyed a great number of their fowl.
These losses were irreparable; the sails were torn like paper;
the fore-top-mast and several of the yards, and the tiller of the rudder were broken,
so that having no command of the ship, they seemed to be in the utmost danger,
till the storm abated; and then it took them a full week to repair the damage,
so as to be in a condition to make sail again; and the wind being unfavourable, the men,
by reason of the losses sustained, were put to an allowance of bread and water.

But in the midst of dangers nothing supports men
in a calm presence of mind like true religion,
and a consciousness of acting uprightly, in singleness of heart towards God.
This friend amidst surrounding danger,
confiding in that divine providence which is everywhere present, ruling by sea and land,
who can command the winds to be still, and the heaving waves to subside,
found comfort in meditating on his promises,
to care for those who put their trust in him;
and after some further trials of his faith and patience,
he was preserved to land safely at Plymouth, and from thence reached his own house,
the 2nd of 8th month, 1728, having been absent about a year and ten months.
Upon entering his own house he felt abundant consolation and peace of mind,
in reward of his fidelity in the discharge of duty,
through all attendant discouragements and difficulties.

He stayed pretty much at and about home till the year 1740,
when he visited his friends in various counties in England,
and paid a second visit to those in Ireland.
The years 1746-1749, he spent mostly in travelling in different quarters of the nation.
And after this it doth not appear that he travelled any long journeys,
the infirmities of age incapacitating him;
but was very diligent in attending meetings both at home
and in the neighbourhood for twenty or thirty miles round,
as long as his health and strength continued,
his ministry continuing lively and powerful to the last,
to the edification and comfort of those who heard it.

Travel Fuller, of Swasham in Norfolk,
being prosecuted for Easter offerings in the Ecclesiastical court,
at the suit of Robert Say, priest of that parish;
a prohibition was obtained and the cause being removed into the Temporal court,
an hearing was had thereon at the Lent assizes at Thetford in Norfolk, in the 1st month,
1747, when the following state of the case was agreed to by the counsel on both sides,
and submitted to the judgment of the court, viz.

That within the parish of Swasham there is,
and for all the time whereof the memory of man is not to the contrary,
there hath been a certain custom,
that every married man inhabiting and residing within the said parish of Swasham,
with his wife being respectively of the age of sixteen years or older, hath paid,
and hath used and been accustomed to pay for himself and
his wife to the vicar of the parish of Swasham aforesaid,
for the time being, yearly at the feast of Easter,
or so soon after as the same hath been demanded,
four pence as for or in the name of Easter offerings.
That at Easter, 1745, and long before,
the plaintiff and his then and now wife were and now are Quakers.
That neither the plaintiff or his said wife ever went to the church of Swasham,
or ever received the sacrament or communion with or from the defendant,
nor did the plaintiff or his said wife ever participate of or personally
attend upon any of the offices of the church.

Upon the whole it is submitted to the court,
whether the defendant is entitled to a writ of consultation or not?

=== The Case of Travel Fuller, sued in the Bishop`'s Court for Easter Offerings.

The said Fuller, coming to live in the parish of Swasham in the county of Norfolk,
about three months since, before the time called Easier, in the year 1745, Robert Say,
vicar of the said parish, did soon after the said time demand of Fuller four pence,
as an Easter offering due from him and his wife at Easter, which Fuller refusing to pay,
Say libelled him in the court of the bishop of Norwich.
Whereupon Fuller in the term called Trinity term, 1746,
applied to the court of Common Pleas for a prohibition,
upon a suggestion that Easter offerings are not due,
but where there are particular customs warranting the payment of them,
and whether there was such a custom in the parish of Swasham,
the Sipritual courts had no right to try.
And on this foundation the court granted a prohibition; but at the fame time,
at the in stance of Say`'s counsel the court obliged Fuller
to declare in prohibition within a limited time,
which he accordingly did.^
footnote:[This was a step never before taken by any parson in the case of Easter offerings.]
And to such declaration Say pleaded that within the parish of Swasham,
there was a certain custom used,
that every married man inhabiting and residing in
the said parish of Swasham with his wife,
they being both sixteen years and older, hath used,
been accustomed and ought to pay for himself and
his wife to the vicar yearly at the feast of Easter,
four pence as for and in the name of Easter offering.
That Fuller at Easter, 1745, and for a long space of time then last past,
was and still is an inhabitant in the said parish with his then and now wife,
and that they were at the feast of Easter of the age of sixteen and older,
and that Say having been vicar of the said parish for more than a year past,
there was due to him four pence from the said Fuller.

Fuller disputed the custom, and thereupon issue was joined,
which issue was tried before Sir Thomas Abney,
the 26th of the 1st month (called March) 1747,
at the assizes held at Thetford for the county of Norfolk.

Fuller had for his counsel, counsellors Pont, Mason and Potter, and sergeant Leeds,
all which except counsellor Pont,
had been several times attended by one or more of
the friends appointed by the meeting on this affair;
and once on a general consultation of the said counsel;
and at Thetford before the trial came on they were again
all applied to by Edmund Peckover and Richard How,
who then also waited on counsellor Pont.

It was then agreed, that in case the custom should be proved,
endeavours should be used to obtain a special verdict,
that so the judgment of all the judges might be had; but that could not be,
though the custom was so fully proved that Fuller`'s counsel did
not think fit to examine any of the witnesses that were provided;
as the judge desired they would not, but save the time of the court.

The reason the judge assigned against a special verdict was that
it would be attended with an hundred pounds extraordinary expense;
but said he was willing it should be made a case,
and referred for the judgment of the court of Common Pleas.
As a question had arisen whether the custom was good or not,
and whether Fuller was liable to pay the demand,
as his counsel insisted that Easter offerings were due and
pay able to the vicar for officiating at the sacrament,
and, that Fuller never partook or attended at any of the offices of the Church.

It was hereupon agreed by the counsel on both sides
that a verdict should be given for the plaintiff,
and the matter objected on behalf of the defendant should be reserved
for the determination of the court of Common Pleas.
Whereupon a verdict was given and the following order and case agreed upon.

It is ordered by the consent of the parties their counsel and attorneys
that the verdict now given in this cause for the defendant,
shall stand as a security to him,
and that the matter in law in this cause be referred
for the opinion of the court of Common Pleas,
whom the said parties their counsel and attorneys shall attend
and if the opinion of the said court shall be for the plaintiff,
then the defendant shall not proceed on the said verdict,
but shall pay the plaintiff or his attorney his costs of this suit,
to be taxed by the prothonotary;
and if the opinion of the said court of Common Pleas shall be for the defendant,
then the said defendant may proceed on the verdict notwithstanding this order:
and it is further agreed by the like consent that
the postea shall remain in the hands of the associate,
and not be returned without the order of the said court of Common Pleas,
and that order shall be made a rule of his majesty`'s court of Common Pleas.

By the court,

Rash, Associate.

In pursuance of this order the following cafe was
stated and agreed by counsel on both sides.

That within the parish of Swasham, there is and for all the time whereof,
the memory of man is not to the contrary,
there hath been a certain custom that every married man inhabiting
and residing within the said parish of Swasham with his wife,
such married man and his wife, being respectively of the age of sixteen years or older,
hath paid and hath used and been accustomed to pay for himself and his wife,
to the vicar of Swasham, yearly at Easter four pence,
for and in the name of Easter offerings.
That at Easter, 1745, and long before,
the plaintiff and his wife were and now are Quakers, residing in the parish of Swasham,
and respectively sixteen years of age.
That neither the plaintiff nor his said wife ever went to the church of Swasham,
and never received the sacrament or communion with or from the defendant,
nor did the plaintiff or his said wife any of the offices of the church.

On the whole whereof it was submitted to the court whether the defendant
is entitled to a writ of consultation on this case or not.

Signed, Edward Leeds for the plaintiff, H. Partridge for the defendant.

N.B. Sergeant Prime refused to sign the cause on behalf of the defendant,
because he disapproved it, thinking it much to his client`'s prejudice.

After this, sergeant Leeds, sergeant Skinner, sergeant Willis, sergeant Bootle,
sergeant Draper, were attended by Fuller`'s attorney,
and one or more of the friends appointed, to advise on the affair,
and it was agreed that sergeant Leeds should have the first argument,
sergeant Skinner the second, and either Willis or Bootle the third,
provided there should be so many; but as the case was new and of great consequence,
the court of Common Pleas,
gave the counsel time to prepare until the term called Michaelmas term:
and then it was several times adjourned,
occasioned by the indisposition or absence of one or other of the judges,
but on the sixteenth of the 9th month, 1747,
at the court of Common Pleas all the four judges being present, viz.

Sir John Willis

Sir Thomas Abney

Sir Thomas Burnett

Sir Thomas Burch,

This affair came on with sergeant Leeds argument on behalf of the plaintiff Fuller;
began with a recital of the previous proceedings,
then very pertinently took notice of the provision the legislature had made for
the easy recovery of these small demands from Quakers by justices warrant,
of which provision he concluded the defendant could not be ignorant,
no more than of the Quakers conscientious scruple to pay them,
and yet the defendant had chosen the expensive and vexatious
method of proceeding in the Ecclesiastical court.

He cited many authorities to prove that offerings in general were for many of the earliest
ages of Christianity the only provision for the maintenance of the ministers,
and all other the necessities of the church,
and that Easter offerings in particular were given
some hundred years before the establishment of tithes,
which was not till about the eighth century.

That Easter offerings were a gratification, compensation or fee given the minister for,
or on account of his labour in administering the communion,
or for or on account of the holy loaf to be used at the communion.

That it was impossible Easter offerings should be a composition for,
or any ways relate to personal tithes,
as those offerings were used to be given many hundred
years before the establishment of any tithes,
of which personal tithes were the last and least general.

That the offerings which have remained since the reformation, have been for marriages,
churching of women, christenings, burials and for the sacrament.

He cited divers authorities in tried cases, wherein when the office not being performed,
the offering had been adjudged not to be payable.
And urged,
that Easter offerings were of the same nature with those several other offerings,
and that with regard to the plaintiff and his wife,
it appeared in the case that the defendant had done nothing
for them whereby to entitle him to an Easter offering.

As by the act of Toleration,
Quakers were exempted from any obligation of conformity to the church or its ceremonies.

He copiously expatiated on the several heads before mentioned,
having taken much pains himself,
as well as that he had been greatly assisted by the many quotations
and observations communicated by our friends Alexander Fothergill,
William Hird, Josiah Forster, etc.

Sergeant Belfield on behalf of the defendant answered pretty briefly,
endeavouring to narrow the whole affair into the single question,
whether the Quakers were exempted or not?
though he made some attempts and quoted some authorities
to prove Easter offerings not to be sacramental,
but a composition for personal tithes.
He insisted strenuously that though by the act of the first of William and Mary,
Quakers were exempted from the penalties of certain laws to which they were before liable,
for their nonconformity to the church of England,
yet they were by no means excused from the payment of tithes,
or any other ecclesiastical dues.

Sergeant Leeds replied in support of what he had before advanced,
adding some further reasons to prove that Easter offerings were not a composition for,
nor had no relation to personal tithes,
and particularly that those offerings were payable at the
age of sixteen by persons of all ranks and degrees;
whereas personal tithes were payable by none before the age of twenty-one,
and then not by the nobility, gentry, day-labourers and others.

He observed,
that in the rubrick confirmed by parliament of the second of Edward
VI. the curate was to provide bread and wine at his own cost,
and the parishioners to contribute money.
That in the next common prayer book the parson was discharged,
and the church-wardens and ministers were directed to provide
the bread and wine at the parish expense.

The judges then proceeded to deliver their opinions,
lord chief justice Willis began with fine encomiums
on the large body of people called Quakers,
for their loyalty and usefulness;
then took notice of sergeant Leeds learned dissertation on the original of Easter offerings;
but said be should not meddle with things he did not well understand,
but confine himself to deliver his opinion according to law,
yet should defer his full determination to a further hearing,
as he supposed there were more counsel to speak in the cause:
but hitherto it appeared to him that Easter offerings had
for a long time been customarily paid as due to the clergy,
and had been confirmed by several laws,
and that by the act commonly called the act of Toleration,
the payment of tithes and other ecclesiastical dues,
was expressly continued and preserved by a special clause for that purpose,
and that he could not find in any statute that any people whosoever were exempted:
that the jury at Nisiprius had found that it had been customary
for the inhabitants of Swasham to pay Easter offerings;
that he did not apprehend that these offerings were due
to the vicar for actually administering the sacrament,
but for his being ready to perform that office,
and that a man`'s alleging that he never did participate,
was not sufficient to excuse him from payment,
for by the same rule he might plead an exemption from the
tithes because he never went to hear the parson.
That on the whole his present opinion was to grant a consultation,
but he should attend to what might be advanced in the future arguments,
intimating however to the counsel that they should
confine themselves to matters of law only.

The other judges all declared their concurrence with the lord chief justice.

Judge Burnett observed,
that when the legislature exempted Dissenters from penalties by the act of Toleration,
they took care to preserve the established church and the rights of its clergy.

Judge Burch said he should be glad to hear the case further argued,
but it would then be necessary for the counsel to show that the Quakers were
exempted by statute law from the payment of Easter offerings to the clergy.

After this sergeant Skinner having been applied to,
he declared it was his opinion that further arguments would
be fruitless considering how far the court had declared
itself and how much they had narrowed up the counsel.

The meeting for sufferings on deliberate consideration agreed that the
friends appointed to attend the affair might let the court know,
that we would give the court no further trouble but rely on what had been already advanced,
which was done accordingly.

And on the 28th of 9th month,
being the last day of term the court proceeded to final judgment,
which the lord chief justice Willis introduced with a speech
wherein he intimated that he had before given his opinion,
though in regard to a worthy set of men called Quakers,
he had consented to a further hearing, which however they did not desire,
but did as they do in all other instances, act as a people of a pacific temper,
always submitting to the laws of their country.

He then recited the previous proceedings, particularly at the assizes of Norfolk,
where the jury had found the custom, but could not determine the law;
and that it was therefore referred to the court of Common Pleas for their opinion,
whether the custom was reasonable and legal as to the Quakers.

He then repeated great part of what he had said at the hearing, and added,

That he thought the instance of marriage no parallel,
for that a man was at liberty whether he would take the benefit of marriage,
but that all were obliged to communicate until dispensed with,
and still were obliged to pay, that never having been dispensed with,
particular care having been taken in the act of Toleration,
that the Dissenter should not be pro sited, nor the minister prejudiced,
he then added that the verdict must stand,
and the plaintiff have leave to enter judgment thereon and avoid a consultation.

Peter Andrews from New Jersey, in the course of a religious visit,
died in the city of Norwich this year;
of whom friends in said place testified that his memory was very precious to them;
and that few friends who travelled this nation (England) had been more approved,
or had more general service in so short a space of time.

In the testimonies given forth concerning him,
we find little or no account of the forepart of his life.
It having pleased the Lord to bestow on him a gift in the ministry,
he was faithful there to, and made helpful to many.
His engagements in the exercise hereof, occasioned him to be much from home,
yet his regard to his family was becoming, both as an husband and father;
it was his frequent practice to sit down with them to wait upon the Lord,
and we believe his faithfulness therein was of considerable service.

In the year 1755 he obtained a certificate from the monthly meeting of Burlington,
in New Jersey, to visit friends in England, and having settled his temporal affairs,
he embarked the 29th of 4th month, same year, and landed in the south of England,
in the 6th month following.
He proceeded immediately to London, where he had very good service.
From thence he went directly to York,
being desirous to be at the Quarterly Meeting for that county;
at the opening of which in the meeting of ministers and
elders he had a very weighty opportunity in ministry;
but in the succeeding meetings for worship was mostly silent.
In the meetings for discipline he was divinely led to set forth the nature,
good end and tendency of the same,
and very zealously pressed the keeping them up in the same wisdom and power,
in which they were first established, evidently setting forth,
that they proceeded from that which gathered our
forefathers to be as a peculiar people unto God.

From York he travelled through many parts of the north of England,
and had meetings in divers places, several of which were very large;
yet he was often led to famish the too eager desire after words,
being often in these great meetings totally silent,
which though a great disappointment to many for the present,
yet there after wards appeared a signal service in it.
He arrived at Norwich in the 11th month,
where he was made instrumental in a very particular
manner to the help and furtherance of some,
whom it hath pleased the Lord to visit with a fresh visitation of his love.
From Norwich he returned to London, visiting many meetings in his way thither.
He remained in this latter city a few weeks, being exceeding ill,
yet was at most of the meetings there,
and was very serviceable in affairs particularly relating to the society in Pennsylvania,
at that time.
From London he went back to Essex, and through several other counties to Bristol;
his indisposition still continuing,
but it did not hinder him from travelling or attending meetings.
From Bristol he passed through some parts of Gloucestershire, Wiltshire and Oxfordshire,
and got to the yearly meeting in London, in 6th month, 1756,
and although his illness continued upon him,
he was enabled to bear several living testimonies,
in the demonstration of the spirit and of power.
From London he came down to the yearly meetings at Colchester and Woodbridge,
at the latter of which, at the last public opportunity which he had,
he was strengthened to bear a large, powerful and affecting testimony,
to the tendering of many hearts whose states were so effectually spoken to,
as that it may be fitly compared to the excellency
and glorious situation which the psalmist described,
when he says,
"`How good and how pleasant a thing is it for brethren to dwell
together in unity! it is like the precious ointment upon the head,
that ran down upon the beard, even Aaron`'s beard,
that went down to the skirts of his garments.
As the dew of Hermon, and as the dew that descended upon the mountains of Zion;
for there the Lord commanded the blessing,
even life forevermore,`" Psalm 133 1-3. It was indeed a remarkable season,
in which he was wonderfully led to set forth the progressive
steps the Almighty was pleased to make use of,
in appearing to Gideon, confirming him in the certainty of his requirings,
condescending to grant his requests in a very peculiar manner,
and sealing them with his presence, and giving him victory over his enemies,
as he was faithful to follow the blessed author,
that pointed out the beginning as well as finishing
that great work to which he was called.
This memorable service, there is reason to believe, was of great use,
and long remembered by many present.

He continued very weak in body all the time of his stay at Woodbridge,
being about five days, and no persuasions could prevail upon him to continue there,
being very desirous to see friends of Norwich again,
having said he thought he could willingly die with them.
Soon after he got thither, he took to his bed; and to several friends who visited him,
he expressed, that he was satisfied he was in his place,
in giving up to follow the requirings of the Lord, in leaving his outward habitation,
and those near blessings of a most tender affectionate wife, and dutiful children.
The severity of his illness kept him mostly delirious,
yet he was favoured with some clear intervals; in one of which,
being in a sweet heavenly frame of mind,
he broke out in the following fervent supplications, "`Oh,
this poor soul hath been for many days on the brink of the pit of distress; but thou,
dear father, dost not afflict thy children willingly, but for some great and good cause,
known only to thyself.
Dear Father! suffer not thy children ever to despair of thy mercies,
but that we may be helpful, as much as may be in our power, to one another,
in all such times of trouble.
Dearest Father, thou hast been pleased to open, and to favour with thy goodness:
my soul is thankful, and can say,
thou art worthy of glory and praise forevermore.`" He continued to the 13th of 7th month,
1756, and then departed this life,
and no doubt rests with the spirits of the just made perfect,
in those glorious mansions prepared for all who faithfully persevere to the end.
He died at the age of 49 years, having been about fourteen years a minister.

On the 26th of 1st month, 1758, died in London, in the course of a religious visit,
Abraham Farrington of New Jersey, in America.
He was born in Buck`'s county, in the province of Pennsylvania,
of parents professing the truth, as held by this people.
His father died when he was an infant,
soon after which his mother married out of the society,
which exposed him to a very irregular education.
At ten years old he was put apprentice, where he suffered much bodily hardship,
and very great danger to his better part, during a servitude of eleven years;
yet the good hand of the Almighty was with him for his protection and preservation.
He for some time took great delight in reading the bible;
and though fond of youthful vanities,
yet he was careful every night to repeat those forms of prayer which he had learned,
'`till he grew afraid to say them any more,
and seemed like one abandoned by God for several years.
When he served out his time, he became a resident in the house of one of this society.
The family were very exemplary in their conduct, and treated him with great kindness.
He thought them the best people he was ever acquainted with,
careful of their words and actions, yet cheerful and pleasant in their demeanour,
so that he thought he must become a Quaker.
Here we have a striking instance of the efficacy of the silent preaching of a good example.
Soon after his forming this resolution, at a meeting of this people,
a friend preached with much divine power, reaching the witness in his conscience,
and speaking intelligibly to the state of his mind; but,
too much after the manner of the world, he gave that praise to the creature,
which was due only to the Creator, thinking within himself, "`This is a brave man,
he preaches well; I wish I lived near him,
that I might go to hear him every first day.`" But he was
little attentive what this preaching direct ed him to,
Christ in himself, the true teacher.
Afterwards he frequently attended the meetings of friends,
and became very conversant in their writings.
One of these meetings was attended by Thomas Wilson and James Dickenson,
by whose ministry, his state was so plainly spoken to,
as effectually to show him how the account stood between God and his soul,
and abiding under the divine power,
in the Lord`'s time he came to witness the work of sanctification to be carried on;
and when fully fitted thereto,
was called to bear a public testimony to others of what God had done for his soul.

He often travelled abroad on the American continent in the service of truth,
much to the satisfaction of those whom he visited.
At times his outward circumstances were difficult,
where by an opportunity was afforded him to show an example of christian resignation;
and to see its effects in divers providential assistance.

In the year 1756 he obtained a certificate from the monthly meeting of Burlington,
in New Jersey, of which he was a member, to visit friends in Great Britain,
for which he felt a concern on his mind for upwards of ten years.
After a voyage of four weeks, he landed in Dublin,
and visited the meetings of friends through out the kingdom of Ireland,
faithfully labouring to strengthen the brethren,
and assist in building up the waste places in Zion.
His service there was weighty and truly acceptable.
From thence he came over to England, visited many of the northern parts,
and thence came up; to the yearly meeting in London.
He afterwards visited many other parts of the nation
to the comfort and edification of friends,
and returned to London, about the close of the year 1757.
Having travelled with great diligence, and laboured with fervency,
his health was impaired,
yet he attended meetings '`till his disorder so increased
as to render him incapable of further public service.

His conversation was innocently cheerful, 1758.
yet grave and instructive; he was a man of a weighty spirit,
and valiant for the cause of truth; a sharp reprover of libertine professors,
but tender to the humble and contrite ones; strong in judgment, found in doctrine,
deep in divine things; often in a clear and lively manner,
explaining the hidden mysteries wrapped up in the sayings of Christ,
the prophets and apostles; and it may be truly said,
he was a scribe well instructed unto the kingdom,
bringing forth out of his treasure things new and old.

His ministry was in plainness of speech, and attended with divine authority,
reaching the witness of God in man, and to the habitation of the mourners in Zion;
frequently pointing out, in a lively manner, the paths of the exercised travellers,
and the steps of heavenly pilgrims,
by which he was made helpful to such as were seeking the true rest,
which the Lord has prepared for those who love him.

His distemper increasing, he was confined to his bed, at the house of Thomas Jackson,
in Devonshire Square, where all necessary care was taken of him.
During his illness he was very tender in his spirit, and remarkably patient.
He uttered many heavenly expressions and several times said,
he apprehended his time in this world would be but short;
and seemed fully resigned to quit this mortal state, having an evidence,
that he should be clothed with immortality and be united to the heavenly host.

He had been frequently heard to, in time of health,
that he thought he should lay down his body in this nation,
and see his friends in America no more.

He departed this life like a lamb, without sigh or groan,
as one falling into a deep sleep, at the age of sixty six years.
His body was carried to Devonshire house, where a large and solemn meeting was held;
from thence to friends burying ground at Bunhill-fields,
accompanied by a large concourse of people,
and there interred among the remains of many of our primitive worthies.

Daniel Hollis, an ancient friend of Whipingham parish in the Isle of Wight,
died in this Hollis.
year a prisoner in Winchester jail.
In the year 1708, he was prosecuted in the ecclesiastical court,
by the church wardens so called, for a few shillings charged on him in their rate,
for non-payment whereof, he was, in the year 1709, committed to Winchester jail,
where he remained a prisoner until discharged by a general act of grace.
In about 50 years there had been taken from him on
account of tithes and offerings by warrants of distress;
corn, hay, cattle,
etc. to above the value of 700. whereof about 140 was more
than the total amount of all the original demands.
It had been customary for constables before the year 1757,
to distrain considerably more than the sum claimed for tithe,
and the charges allowed by law amounted to,
which additional money the parson used to take for his pretended extra expenses;
but William James, constable of the East Medine in the said island,
who distrained for tithes in the year 1756, refusing to distrain any more for the parson,
than what the justices had adjudged to be due to him, and the charges allowed by law,
with which John Gilbert, the old rector of the parish of Whipingham, not being satisfied,
he brought an action against the said constable for
what he demanded beyond the tithes and legal charges,
in which suit the parish being cast, was obliged to pay the constables cost.

In the year 1758, the said John Gilbert preferred a bill in the court of Exchequer,
against Daniel Hollis, for tithes for one year to Michaelmas, so called, 1757,
and obtaining an attachment, the son of the priest, being an attorney,
together with a sheriff`'s officer, went to the house of the said Daniel Hollis: Daniel,
by reason of his great age, was become so feeble as to be scarce able to help himself.
They violently pulled him from his bed, and dragged him down stairs,
whereby he was bruised; they then left him in the house.
But afterwards, viz. on or about the 1st of 11th month, in the same year,
he was taken out of his house and conveyed to Winchester jail,
where he was at first confined in a public thoroughfare-room,
very incommodious to him and his daughter, who attended him;
but by the favourable influence of a justice of the peace, who had been his landlord,
he was in a few days removed into a more commodious room,
in which he was daily fed from the said justice`'s table.
After he had been a prisoner about a month,
a supersedeas was obtained from the court for his discharge;
but when it came to the prison,
he was so ill with the bruise he received when dragged down stairs,
and by increase of his weakness, that he was not fit to be removed,
and desired those about him not to attempt it.
And to one, who offered him the use of a chariot, to carry him to Southampton,
he said he had a shorter passage, and should be soon at his journey`'s end,
requesting he might not be disturbed, he said he was very easy,
and having forgiven his prosecutor, he in a tender resigned frame of mind,
departed this life in prison the 11th of 12th month, 1758 aged about 97 years.
His corps was as he desired, interred in friends burial ground at New port,
in the Isle of Wight.

On the 15th of 5th month, this year, died William Pitts of Southwark.
In his young William years he was visited with a call of divine grace,
and by adhering thereto and submitting to its operations,
he became convinced of the essential doctrines of Christianity,
as professed by this people.
In his minority he was educated by a priest,
under whose tuition he attained a considerable knowledge in several of the learned languages;
yet the tender scruples which were raised in his mind,
under the clear conviction of the impropriety of the needless
ceremonies and salutations in which he had been educated,
exposed him to many sufferings from his father,
whose unkind treatment he endured with much patience and fortitude.
This tended much to his growth and advancement in religious
experience and preparation for further service.

We find no particular account of the time of his joining this religious society;
but that after much conflict of mind for three years,
from the importance of the weighty service,
he came forth in the work of the ministry in the year 1738.
His service herein through the remaining part of his life was very great,
his heart being fully given up to do whatever his hands might find to do,
as was evident from his own expressions to some friends who visited him in his illness,
whom he encouraged to faithfulness, saying, that for the last twenty years,
he had never omitted one service which had appeared to be his duty,
and he had now the comfort and satisfaction thereof, or words to that effect;
and his talents and qualifications were employed to the glory of the Giver.

In the fourth month, 1760,
he set out to visit friends in Buckinghamshire and some parts adjacent,
but being much indisposed, he returned homewards,
and was suddenly taken very ill at a friend`'s house at Uxbridge,
during which he uttered the following expressions, "`O my Father,
my Father! be pleased to be with me in my affliction,`" and said he believed,
that his time in this world would be short,
and that he should die of his present illness,
but that he was resigned to the will of providence, for he coveted not length of days,
and was easy in body and mind.
Being asked how he did, he said, "`I am very weak in body,
but I have a great Physician in heaven,
who is merciful to me in this illness.`" At another time he said, "`if it pleased God,
he had rather die than live,
unless he had any further service for him to do,`" and he could rejoice saying, "`O death,
where is thy sting?
O grave where is thy victory?
--the sting of death is sin and the strength of sin is the law;
but thanks be to God who giveth us the victory.`" Many friends
from London and elsewhere went to visit him,
which he took very kindly,
and to one of them he expressed him self in the following manner,

I never coveted riches nor power; and indeed if I had obtained them, what could they,
or all the friendships of the world do for me now?
Nothing but the testimony of a pure conscience and the inward sense of divine favour,
can comfort my soul in these moments; and thanks be to my heavenly Father,
I feel his supporting arm underneath, and it is a rest indeed, a joy that overcomes all;
it makes this bed easy, and enables me to bear calmly and without complaint,
the dispensations of his gracious providence;
I wish for nothing to myself otherwise than it is.
I accept with satisfaction and thanks the kindness of my friends;
in compliance with their request, and thinking it my duty to do what may be in my power,
I take the medicines prescribed, which,
though it may not seem meet to providence in his wisdom,
to render instrumental in the restoration of health; yet through his blessing,
they have so far succeeded, as to remove the sense of acute pain.
To be thoughtful of and prepare for this trying time,
have I frequently and earnestly exhorted others;
not without considering and knowing the many and strong temptations of this world,
which however, as we are obedient to the spirit of Christ,
we shall be enabled to overcome;
that in the conclusion they might have this answer of peace,
this divine consolation of mind; and it always appeared best to me,
to do this in great love and gentleness,
so that I might persuade not force them to Christ!
When this time comes, it will be found hard work, without any additional weight,
to struggle on a dying bed with the pangs of the body.
But how much more to be lamented is the condition of those,
whose conscience accuse them with having enriched
themselves by oppressing the poor and helpless;
and when in an unprepared state, after a life of rebellion and hardened in iniquity,
such must feel the terrors of a guilty mind, added to the agonies of a perishing body.

A friend who went to visit him, the day before his death, asked him how he did;
after a short pause he said, "`I am waiting for my great change; O my Father,
be pleased to be with me,
and comfort me in my last moments.`" The last words he was heard to speak, were these,
"`There is a great God in heaven, who is Zion`'s king, O Zion, O Zion,
O thou great King of kings!`" Soon after which he
departed in great tranquillity and composure,
aged about 51 years, having been a minister 22 years.

The treaty of Aix-la-Chapelle produced rather a temporary
suspension of arms than a solid peace;
for though peace appeared for a season to be secured in Europe,
hostilities between France and England were still
carried on both in America and the East-Indies,
which in a few years involved England in another long and troublesome war,
which carried but a gloomy appearance at the beginning,
the English receiving sundry defeats and disappointments;
but afterward they were more successful and terminated
the war with great advantage over their enemies.
During the continuance thereof, and amidst a train of successes by sea and land,
the king king died suddenly in the 77th year of his age and 33d of his reign,
October 25th 1760, much lamented by his subjects.
