== Chapter IX. Ireland.

[.chapter-synopsis]
* Account of John Dobbs
* John Ashton
* George Rooke
* Affirmation act made perpetual
* Address to the King
* Account of Mungo Bewly
* Mary Peisley

In the year 1739, and the 80th of his age, died John Dobbs of Youghall,
in the county of Cork, who although not engaged in the work of the ministry;
yet his sincerity and self-denial, his peculiar sufferings, his steadfastness,
and contempt of worldly possessions in comparison of peace of mind,
appear to be too remarkable to be passed over unnoticed.

He was of a family of some account in the world,
being the eldest son of Richard Dobbs near Carrickfergus, a counsellor at law,
and a justice of peace of the county of Antrim,
from whom as heir he was entitled to a considerable estate,
of which he suffered himself to be deprived purely for the sake of religion.
He possessed from an early age, a thoughtful and virtuous turn of mind.
When he was about eleven years of age, his father in answer to an occasional inquiry,
signifying that he intended to educate him "`for the clerical order and he did
not know but Jonny might obtain a bishopric.`" The child hearing this,
says within himself,
"`It is a weighty matter to take the care of other men`'s souls upon me, it is well,
if I can look well after my own.`"

He received an education in literature suitable to his rank in life,
and the station he was designed for.
After he had made a considerable proficiency in the Latin and Greek languages at school,
he was removed to the university at Oxford, and applied himself to the study of physic.
But being all along of a religious disposition,
the loose conversation of his companions both at
school and the university was irksome to him.
When he was on his road to Oxford, he met with a discouraging observation from a person,
with whom he casually fell into company at York,
who remarked that there were many gentlemen,
who were afraid of sending their sons thither, lest they should be corrupted;
and he found there was too much ground for the observation; for when he came to Oxford,
the profaneness of many of the students there, was quite disgusting to him.
At first he put himself in the way of conversing with them,
with a design to use his best endeavours to reform them,
but soon found this to be labour lost; and being uneasy at his company here,
he obtained liberty of his father to return home.
Here also lying open to the company of the country gentry,
their conduct and conversation became disagreeable to him,
particularly as they were accustomed to indulge themselves in drinking too freely;
wherefore lie withdrew from their company,
as thinking their practice inconsistent with the
moderation and temperance prescribed by the gospel.

Thus actuated by religious motives in circumspection and
self-denial so to order his conversation in this life,
as to obtain everlasting felicity in that which is to come,
he conceived an aversion to an inordinate latitude in conduct,
while innocence and integrity of life, was what he edeavoured after himself,
and observed with satisfaction in others.
This disposition drew him to look upon the people called Quakers in a favourable light,
observing their chaste conversation coupled with fear.
And his mother Dorothy Dobbs, having joined with those people,
gave him an opportunity both to remark their circumspect walking,
and to peruse several of their writings on religious subjects.
But '`till the 19th year of his age,
although he had an esteem for many of those he had knowledge of,
yet he declined the thoughts of entering into their community,
his father having threatened to turn any of his children out of doors,
that should go to their meetings.
John, at length, from the perusal of their writings,
being impressed with a desire to hear their ministry; and Thomas Dockwra,
a friend from England, having about this time appointed a meeting at Carrickfergus,
John went thither, and was so effectually reached by his ministry,
and convinced of the truth of his doctrine, that from this time he joined this society,
and continued steadfast in community with them, through many severe trials.

For he, who had been a favourite of the family till now,
upon his attaching himself to this despised people,
found great alteration in their conduct toward him, especially in that of his father,
who first endeavoured by persuasion and flattering promises to bring him off from them;
but he who had chosen the profession of truth, as it appeared to him,
upon the best motives and clearest conviction,
durst not act contrary to the conviction of his conscience, on any worldly consideration.
His father exasperated by his declining to comply with his desire,
had recourse to rougher means, and treated him with great severity,
keeping him a prisoner in his house, above half a year, in the years 1683 and 1684,
during which confinement, at a certain time meeting him with his hat on,
he beat him grievously on the head with his cane, to that degree,
that he fell into a fever upon it;
nor did he ever entirely get the better of the injury received thereby.
His mother, who had been his constant friend and protectress under all his hardships,
died while he was yet young.
His father would not admit him into his presence,
and now having none in the family to compassionate his case,
or give him the least countenance, and seeing no likelihood of a reconciliation,
he thought it best to leave his father`'s house, where his presence was disagreeable,
and went to London, where he learned chemistry with Charles Marshall,
and made a further progress in the study of physic, after which he returned to Ireland,
and practised it with reputation, good success and great christian charity to the poor.

His father remained unreconciled to him to the last, and by his will disinherited him,
leaving his estate of several hundreds per annum, to his younger son,
and cut him off with 10£. Per annum, during life,
to keep him (as he expressed it) from starving, or relying on these seducing people.
This pittance was but indifferently paid by his brother,
to whose prodigality the income of the whole was inadequate,
whereby he involved the estate; but his son, being a better economist,
voluntarily doubled his uncles annuity, and paid it punctually.

His integrity,
his consistent and circumspect conversation gained
him much respect and affection amongst his friends,
by some of whom he was urged to have recourse to
the law for the recovery of the family estate,
as his birthright, and assistance offered him for that purpose.
Whereupon be commenced proceedings at law; but not feeling that inward peace with Christ,
which he preferred to all worldly possessions, in this first step of litigation,
he put a stop to all further proceedings, and rather chose to confide in God without it.

He retained his integrity to the last period of a long life, in faithfulness toward God,
and a blameless conversation among men.
Having given up all that the world reckons valuable,
to yield obedience to the discoveries of Christ in his own conscience;
he was favoured in return with what all the world cannot purchase, solid peace of mind,
and the internal testimony of an approving conscience, under the possession whereof,
he little regarded how little noise the world made about him,
being a man who declined popularity, and was more in substance than appearance.
_Bonus esse maluit quam haberi._
He aimed not so much to appear a good man, as to be one.
At the age of 80 he terminated a well spent life,
and his last moments exhibited an affecting instance of that serenity,
thankfulness and joy, wherewith the true christian takes his final leave of this world,
in full assurance of going to live forever in a better.

[.small-break]
'''

This year, John Ashton of Killconinmore, in the county of Tipperary,
died in the 80th year of his age; a man, who,
though not eminent for great and shining parts,
was a bright and shining light in the country where he resided;
of great humility and fervour of spirit, for the promotion of piety;
much beloved and esteemed by his neighbours and friends.

He was born in Cheshire, and brought to Ireland when a child by his parents,
who educated him according to the way of the church of England,
of which he continued a member '`till near the 40th year of his age.
Being desirous of farther discoveries of the knowledge of God and way of salvation,
he with his wife went to a meeting of friends at Birr,
when both of them were convinced by the powerful
and efficacious ministry of Thomas Wilson;
and were obedient to the manifestation of truth in their hearts.
Coming out of the meeting they said to each other,
"`The way of everlasting happiness has been clearly laid down before us,
and we are resolved to walk in it, come life or come death.`"

Not long after he was thrown into prison, for his christian testimony against tithes,
where he was kept six months, which he bore with exemplary patience and resignation;
and being always used to industry and an enemy to idleness,
he learned to make gartering and laces, for his support during his imprisonment.

When at liberty he and his wife constantly attended the meeting at Birr twice a week,
generally walking thither on foot, about seven miles of a very bad road,
having a river to wade through both going and returning.
In winter in crossing this river, they sometimes had the ice to break,
and John frequently wept to see the blood on his wife`'s legs in coming through it.

This good man took great pains to get travelling
friends to appoint meetings at his house;
and then would ride several miles, often in the night in winter weather,
to acquaint people of it; which labour of his was blessed, many coming to the meetings,
and several being convinced thereat.
In a little time a meeting was settled there, which soon grew larger than that of Birr,
out of which it sprung.

At the time of his joining this society, he was but low in his worldly circumstances;
but through industry and the blessing of heaven he grew rich, and did abundance of good,
being singularly hospitable and charitable, ready to distribute, willing to communicate.

About the 62nd year of his age, his mouth was opened in a public testimony for truth,
which he faithfully laboured for the stirring up the pure mind,
and encouraging that which was good in all;
and was zealously concerned against vanity and pride.

In the year 1733, he went to the yearly meeting at London,
and from thence paid a religious visit to several
meetings in different counties in England,
as also to the meetings of friends in Scotland.

He was helpful and serviceable in visiting the families,
throughout the extensive monthly meeting of which he was a member;
his heart and house were always open to receive friends;
he was a mourner with the afflicted, and full of compassion to the poor,
by whom his death was greatly lamented.

[.small-break]
'''

This year, died George Rooke of Dublin.
He was the son of Thomas Rooke of Boulton, in Cumberland.
He had been educated in the church England, but about the 20th year of his age,
being convinced of the truth of the doctrine preached by John Greaves,
a minister among the people called Quakers, he joined himself in society with them.
About the 25th year of his age, his mouth was opened in public testimony;
and he became engaged to travel abroad in the work of the ministry,
zealousty and cheerfully devoting his strength and youthful days,
to the propagation of the gospel, and promotion of truth and righteousness in the earth.
In the year 1679, he travelled on foot to Scotland on this account,
accompanied by Peter Fearon.
In the year 1681, he visited friends in all their meetings in Scotland a second time,
and the same year came to Ireland,
and visited most of the meetings of friends through the nation,
as he did also in the year 1684.
Some time after his return, visiting friends in Westmorland and Durham,
he had a meeting at Stockton,
where the mayor of the town sent one of his officers to bring George before him,
and when he came tendered him the oaths of allegiance and supremacy:
but because George for conscience-sake refused to swear,
the mayor would have had him enter in to bonds for his good behaviour,
and to appear at the next Quarter Sessions.
George told him, he was already bound to good behaviour.
The mayor asking him whether he had been before a justice of peace, he answered, "` No,
but I am bound by my principle to behave myself towards the king and all his subjects,
as becomes a christian.`" But as George persisted to refuse to enter into bonds,
the mayor committed him to Durham jail, where he continued till the Sessions,
when he was again committed and kept prisoner about a month longer,
because for conscience-sake he could not swear.

In the year 1685, he visited friends of Ireland a third time, and again in 1686,
when he married and settled in Limerick.
He continued to travel abroad in the exercise of his gift;
and indeed his ministry appears to have been clear and convincing, even among strangers,
of which an instance occurred in his travels through Wales,
at a meeting at Haverfordwest, one of his hearers,
who had a right of the presentation of a parish,
was so far affected by his preaching as to make him an offer of it:
but he was not one of those ministers, who seek for reward or support from men.

He continued to reside in Limerick, in the years 1689 and 1690,
in the troublesome times of the wars between king William and king James,
and during the first siege; but before the second siege,
while James`'s army had possession of the city, he removed with his family to Cumberland,
but notwithstanding these troubles, he still continued laborious and fervent in spirit,
in visiting the meetings of friends, and in the year 1692,
again visited the brethren in Scotland.

In the year 1693, he returned to Ireland, and settled in Dublin,
where he continued to reside the remaining part of his life, during which time,
he frequently visited friends of the three provinces;
and sometimes those in England and Wales,
and was frequently at the yearly meeting of London.

He was a very diligent attender of meetings of worship and discipline,
until disabled by infirmity of body.
He was a man of good understanding, though but little school learning; of a sweet temper;
in conversation pleasant and affable; an affectionate husband and father;
a tender and sympathizing visitor of the sick: he was a diligent and faithful minister,
and his labours were often crowned with success, to the convincement of several,
and the edification and establishment of others.
In the exercise of his gift he was clear, solid and lively, even to extreme old age;
in prayer living, reverent, weighty and concise: in his deportment meek and humble,
not elevated by his gifts and good services;
far from being desirous of exercising lordship over God`'s heritage, frequently declaring,
that he did not judge ministers to be of an order above other men,
and that he and all others in the ministry ought willingly to refer their
doctrine to the divine witness in the consciences of the hearers.
He was a diligent reader of the holy scriptures,
and in his preaching a faithful quoter of them: he retained his integrity,
as well as understanding and memory to his end,
and departed this life in the 91st year of his age, and about the 67th of his ministry.

[.small-break]
'''

This year, there being apprehension of an intended invasion of England from France,
friends drew up an address to the king signifying their
fidelity and good affection to his person and government,
which was as follows.

[.embedded-content-document.address]
--

[.letter-heading]
To George II. King of Great Britain and the Dominions thereunto belonging.

[.blurb]
=== The humble Address of his Protestant subjects, the People called Quakers, in the kingdom of Ireland.

We thy dutiful and peaceable subjects,
with hearts truly sensible of the many blessings and privileges
we enjoy under thy paternal care and protection,
beg leave at this critical conjuncture (when thy dominions are threatened with
an invasion in favour of a popish pretender) to express our sincere and hearty
abhorrence of all plots and conspiracies against thy person and government.

Duty, gratitude and interest unite to engage us in a firm attachment to thy royal person,
and the protestant succession in thy illustrious house; and we are determined,
by divine assistance, to continue unshaken in these sentiments,
and conformable to our known principles to do the utmost in our
power for promoting the peace and welfare of this nation.

The kind indulgence granted us by the legislature in our religious scruples,
the free access we have had to the several chief governors
of this kingdom since thy accession to the throne,
and the readiness shown for our relief,
whereof we retain the most grateful and lively sense,
lay us under additional obligations of duty and fidelity.

May the same divine providence,
that defeated the attempts of the enemies of our
constitution in the rebellion against thy royal father,
and which had lately protected thee in imminent danger,
preserve thee and thy royal family from the wicked designs of all your enemies,
whether foreign or domestic.
May the Almighty guide thy councils by his wisdom and render them
effectual for the reestablishment of peace and tranquillity,
and grant thee a long and prosperous reign over us.
May the British throne be always filled with one of thy royal offspring,
to transmit the blessings we enjoy to future ages.

[.signed-section-context-close]
Signed in Dublin, in behalf of the said people, the 31st of the first month,
called March, 1744.

--

The act of parliament for granting friends an affirmation in all, except criminal cases,
and for qualifying for places under the government, and serving on juries,
which was passed in the year 1736, was only temporary,
and to expire at the end of the ensuing session of parliament,
the present time was thought convenient to make early
application for a renewal of the said act,
without limitation of time, in the same manner as friends elsewhere enjoy it.
Wherefore the friends who attended the last yearly meeting
at London did there wait on the earl of Chesterfield,
the lord lieutenant, requesting his advice and friendship in our intended solicitations,
which he with great cheerfulness granted them,
and on his arrival here encouraged friends to petition the House of Commons,
this session, for such an act as aforesaid, which they accordingly did with good success,
for it passed both houses, _nemine contradicente,_ and obtained the royal assent.^
footnote:[For the words of the Affirmation, see page 260 this vol.]

[.small-break]
'''

This year died Mungo Bewley, son of Thomas and Margaret Bewley,
of Woodhall in Cumberland, from whence he came over to this kingdom,
and settled at Edenderry in the King`'s County.
He was favoured in his youth with a tender visitation of the love of God,
and manifested early a fervent zeal for divine worship in the following instance:
among his papers was found one which he wrote during the time of his apprenticeship,
requesting of his master either to have his work previously allotted to him,
in order that he might make preparation against the time of the week-day meeting,
or that he might be allowed when his apprenticeship expired
to pay for so much time as he should have spent at meetings:
and he grew and prospered in the saving knowledge of the truth accordingly,
and not long after his coming over to Ireland,
a dispensation of the gospel was committed unto him,
whereof he became an eminent minister,
freely devoting himself to spend and be spent for the promotion of piety in the earth,
being diligent in the exercise of his gift both at home and abroad,
having visited friends in the service of the gospel in England, Scotland, Wales,
Holland and America.

He adorned his ministry by a grave and solid behaviour;-he was also a man of good understanding,
zealous in christian discipline, and serviceable in visiting the families of friends;
a man of integrity and firmness, industrious in business, upright in his dealings,
and careful in the religious education of his children;
cheerful and edifying in conversation, compassionate and liberal to the afflicted;
a nursing father to young travellers in the way to Zion,
yet not hasty to lay hands suddenly on such as were more in show than substance,
being of a discerning spirit; and notwithstanding these good qualifications,
he was very humble-minded with respect to himself.

He continued lively in the exercise of his gift to the last,
finishing his christian course in the 70th year of his age,
and about the 40th of his ministry.

[.small-break]
'''

In the year 1757,
the society in general and friends of Ireland in particular met with a considerable
loss in the sudden removal of a very eminent minister of the female sex,
Mary the wife of Samuel Neale, formerly Mary Peisley.

She was born the 19th of 9th month, 1717, near Mountrath in the Queen`'s County,
of parents who were members of this religious society.

In her early days she was a lover of gaiety and vanity;
but being favoured with the visitation of divine love,
she gave up to the heavenly vision,
and was enabled to take up the cross to her natural propensities,
and finally to obtain the victory over the temptations
under which youth are too apt to fall,
the vanity and pride of life.

From the time of this effectual visitation of Christ to her soul,
few adhered with more steadiness to his guidance,
nor endured a variety of probations with more patient resignation.
Having received a gift in the ministry,
she became a vessel of honour in the master`'s house; and being reverently,
watchfully and lively exercised therein, she became a shining ornament in the church,
and an useful member of the society where her lot was cast.
Yet through religious fear, she was particularly careful of appearing too forward;
in that her offerings were like fruit in its season,
to the honour of the Lord and to the edification of his church.
She was a diligent labourer in spirit for the subjection of self,
and the prevalence of divine life; and as she was very careful to rise up in that life,
so was she likewise to sit down in it.
Her reverent solidity and patient waiting upon the Lord in meetings were very exemplary,
striking the be holders with awful solemnity.

The equable tenor of her spirit and uniformity of her conduct in the common occurrences
of life were truly edifying to those who were acquainted with her;
her deportment being weighty, and her words few but fitly spoken,
evidencing that her conversation was in heaven,
and tending to draw the minds of others thitherward.
She was often drawn forth in the pure love of God,
to administer a word in due season in the families of friends, particularly to the youth.
In the discipline of the church, her services were great; so that,
though young in the ministry, she stood in the authority of truth as an elder,
and as a pillar in the Lord`'s house,
bearing the weight of opposition from perverse spirits, without giving way;
the divine power being her shield, and the munition of rocks the habitation of her soul.

Under a lively concern for the welfare and honour of every part of the society,
she was at times qualified to impart suitable counsel to
her brethren and sisters engaged in the ministry and discipline,
"`That they might have a single eye to the glory of God,
to prefer his service before their own,
and to get their days work well done in the daytime.`"
She freely gave herself up to spend and be spent,
and to pass through various perils by sea and land.
She twice visited the meetings of friends throughout the kingdom of Ireland;
once those through England; and once visited friends on the continent of America;
much to the satisfaction of the visited in those parts,
as appears from the accounts received concerning her services.

Soon after her return from America,
our dear friend Samuel Neale and she laid their intentions
of marriage before the monthly meeting of Mountmellick,
to which she belonged;
after which she found a concern on her mind to join in a visit to the
families of friends throughout that extensive monthly meeting.
After she had performed this service, she returned home;
and on the 17th day of 3rd month 1757, on a fifth day of the week,
she was married to our aforesaid friend in the meeting of Mountrath.
Samuel appeared in a very lively testimony at the beginning of the meeting,
and at the conclusion in fervent supplication.
The evening before the day of their marriage,
in a religious sitting at her mother`'s house,
Samuel was concerned to speak of the benefit of laying
hold of every opportunity of renewing our strength,
as the only way to lay up treasure against the day of trouble
and disappointments incident to this uncertain stage.
On the evening of the marriage-day, in a like opportunity,
Mary was led to describe how the Almighty formed the great works of creation in six days,
which having finished, he appointed a sabbath day of rest; and that there were present,
who would in a short time cease from their labours, and enjoy the sabbath of rest.
Thus remarkably did they speak to their own particular states.

On the night, of seventh day the 19th of the month,
she was seized with a violent pain in her stomach;
notwithstanding which she lay quiet and still in a retired awful frame of mind,
which clearly manifested her triumph over death hell and the grave.
About half an hour before her departure, her pain being taken away, she said,
"`I praise thy name, O my God,
for this favour;`" after which she breathed shorter and shorter,
and quietly departed without sigh or groan, like one falling into a sweet sleep,
doubtless to enjoy that sabbath of rest, for which she so ardently longed.

On fifth day, the 24th of the month,
her corpse was taken to the meetinghouse in Mountrath, where a large concourse attended,
many of whom had been present at her marriage on that day week.
A solemn meeting was held on the occasion;
many testimonies were borne in a lively manner, to the circumspect life, holy zeal,
undaunted courage and faithful services of this eminent- instrument in the Lord`'s hand,
to publish his truth amongst the nations.
At the conclusion,
her late dear companion kneeled down by the coffin that
contained the remains of his most beloved earthly treasure,
and prayed to God the Father in the demonstration
of the spirit and baptizing power of the Son.
At the grave he likewise bore a lively testimony to the people,
another friend concluded the opportunity in prayer,
when the body was committed to its original dust;
the spirit having returned to God who gave it,
to enjoy the reward of her well-spent life in the regions of eternal glory.

She died at the age of 39 years, having been a minister about 14 years.^
footnote:[The account of this valuable woman would
doubtless have been much more fully given,
had not my father been suddenly called from works to rewards.
From the knowledge I had of my father`'s very great respect for her memory,
I wished it to have been given very fully;
I therefore applied to our dear friend Samuel Neale,
for materials to supply the defects in the printed testimony,
which he intendeds sending to me,
when he likewise received a summons to enter into the joy of his Lord;
whom he had for a long course of years served with fidelity;
he died the 27th of 2nd month, 1792.
-John Gough, junior.]
