== Chapter X. West Indies.

[.chapter-synopsis]
* Some Convincement in the Island of Tortola
* Thomas Chalkley visits the Island and dies there
* The next year John Cadwallader and John Estaugh visit it and die there
* Account of Thomas Chalkley
* Account of John Estaugh and John Cadwallader

In the early times of this society,
the islands in the West Indies were visited by some of their first ministers,
whose love to mankind, and desire to promote their greatest interests,
even those of immortality, and everlasting life,
were strong enough to draw them through perils by sea, and perils by land,
to publish the gospel of Jesus Christ,
as the true light that enlighteneth every man that cometh into the world,
whereby several were convinced of the truth of their doctrine,
and converted to righteousness, in Barbados, Jamaica, Antigua,
etc. many of these continued steadfast in their principles, and in an humble,
self-denying life, '`till their death.
But profanity and dissipation of manners,
having too much the ascendency over the generality of the inhabitants of the islands,
the discipline of the cross of Christ preached up and walked in by the
faithful ministers and members amongst the people called Quakers,
was too rigid or too contemptible for the people in general,
and some of the descendants of friends in particular to submit to;
and some families of this society having removed to England,
their number is so greatly decreased, that few, if any of this profession,
are now resident in these islands,
and the visits thereto have become less frequent of later years than formerly.

Yet about the year 1740,
account was received of a convincement in some of the Virgin islands,
particularly the island of Tortola,
which by the following paragraph of the yearly epistle of that year,
appears to have been the effect rather of internal conviction,
than of instrumental or ministerial labour,
viz. "`It hath pleased the Lord by the inshinings of the divine light,
to visit the inhabitants of some islands,
where no settled meetings of friends have formerly been,
to the bowing and tendering of some of their hearts, as in the first breaking forth,
and morning of our day; "` and to incline them to assemble together,
and "`silently wait in spirit and in truth upon the Lord, their Redeemer,
the unerring teacher, who teacheth his people to profit,
and leadeth them by the way that they should go.`"

Amongst others, who were here convinced of the inward principle of light and grace,
and submitted to profess themselves of,
and to pass under the contemptible denomination of Quakers, was John Pickering,
governor of the island, who continued a faithful member of this community to his death;
and after his decease his family removed to England.

The report of this convincement reaching the ears of friends on the continent of America,
and in Great Britain, the minds of some were engaged in gospel love to visit them,
confirm and strengthen them in their pursuit after true religion and righteousness.
Thomas Chalkley from Philadelphia was the first who went on this gospel errand,
in the year 1741; and was the next year followed by John Cadwallader from Abingdon,
and John Estaugh from Haddonfield, Pennsylvania.
These friends were received with gladness,
and treated with affectionate kindness by those they went to visit,
amongst whom their ministerial labours were very consolatory, strengthening and edifying;
but this island seemed unfavourable to their constitutions;
they all three laid down their lives there in peace, and in the best service,
in which a man can be engaged.

Thomas Chalkley was born in the borough of Southwark, of honest and religious parents,
who being of the people called Quakers, brought him up in the same society,
and were very careful both by example and precept
to train him up in the sobriety becoming his profession.
This religious care in his education, through the divine blessing and assistance,
had a good effect,
as he was very early tinctured with a serious turn of thought and of behaviour,
an abhorrence of profane and wicked expressions, insomuch that while he was yet a child,
he could not forbear to reprove such boys as used ill language,
and took the sacred name in vain, by putting them in mind of the third commandment,
some of whom would receive his reproof in good part,
and some with contempt and derision.

Yet he did not escape the temptation of indulging himself at times
in playful diversions and levities incident to youth,
by the world reckoned harmless;
but (by the convictions of divine grace manifested to his understanding,)
tending to divert and alienate the minds of youth from the due
remembrance and awful regard of their Creator.
Awakened by these convictions, he was reclaimed from such practices and pleasures,
as he found were afterwards productive of painful sensations to his soul,
and was enabled to bear the cross in christian patience
and self denial in his youthful days.
As he grew up to a state of maturity, and engaged in business,
the cares of this world seemed like to embarrass his mind too much,
and interrupt his progress in religious experience,
whereby he lost that inward evidence of peace and divine approbation,
which through obedience to conviction he had before enjoyed.
This occasioned him great anxiety and a resolution to deny himself
of the inordinate pursuit of the riches and honour of this world,
rather than lose the favour of the Almighty.
Being sensible that the pursuit of terrestrial acquisitions,
which are lawful in themselves, and in some measure necessary,
may be extended to an unlawful degree, and through want of watchfulness,
may divert the mind from the steady following after
the things that conduce to our future well-being;
he was favoured with light to see the danger,
and strengthened by divine grace to avoid it, to keep under the power of the cross,
which mortified his affections to the world; and in a state of humility,
and in obedience to the precept of Christ, to seek first the kingdom of God,
and his righteousness, having faith in his promise, that all things, necessary for him,
should be added.

Being thus weaned from the love of the world,
the love of the Father influenced his mind with greater degrees of strength,
opened his understanding with clearer perceptions of his will,
advanced his progress in the work of sanctification,
and favoured him with abundant consolation of spirit, in reward of his fidelity;
under the feeling whereof,
a lively concern was raised in his mind for the good of mankind in general; that they,
through repentance and circumspection of life,
might be made partakers of the like precious favour;
and for this purpose he apprehended it his duty to exhort his friends
and others in a public manner to repentance and faithful obedience
to the internal convictions of divine grace.
He appeared as a minister among his brethren before he attained the age of 21 years,
and his labours were acceptable to them and others,
through the successive stages of his life.

He soon after travelled in the public exercise of his gift,
through many parts of England, and into Scotland in the year 1697.
In the course of the same year he felt an engagement on his mind to pay
a like religious visit to his friends on the American continent;
and having proposed his prospect to the consideration of
friends of the monthly meeting of which he was a member,
and obtained their approbation,
and certificate of their concurrence and unity with his concern,
he embarked at Gravesend the 26th of 10th month, 1697,
and after a tempestuous voyage landed at Patuxent in Maryland the 1st of 2nd month following.
He spent near twelve months in America,
in which time he visited the meetings of his friends generally
in the several provinces from Virginia northward to New England;
where his ministry and conversation were acknowledged to
administer comfort and edification to his faithful brethren,
of whom he took his leave in near fellowship and mutual affection,
and landed at Plymouth in time to reach the yearly meeting in London in 1699.

Shortly after this, he entered into the married state,
which did not relax his diligence in fulfilling his ministry,
for the edification of the churches at home and abroad;
for in the course of the same year, he visited the counties of Surry, Sussex and Kent,
and afterwards passed over to Ireland in company with William Townsend,
and visited the meetings of his friends of that nation in a general way,
amongst whom their service was acceptable and satisfactory.

Soon after his return from Ireland,
he removed with his wife to America and settled in Philadelphia,
in which city and the vicinity thereof, he fixed his domestic residence for life.
And here also he divided his time between an industrious application
to his outward employment for the support of himself and his family,
and the faithful discharge of his service in the ministry,
for the propagation of piety and virtue;
for which purpose he took many long journeys and voyages
through the several English colonies on the American continent,
and most of the islands in the West Indies; and in Europe through Great Britain, Ireland,
Holland, and several parts of Germany and the adjacent northern kingdoms.
In many of these places his ministry and religious labours were blessed with success,
of which several witnesses survived him,
who were convinced of the truth of the principles which he preached,
became serviceable members of this society,
and continued therein to the end of their lives.

But the proper reward of virtue is not abundance of goods of this world,
but the prize in prospect of the righteous man,
peace here and everlasting happiness hereafter.
It pleaseth divine wisdom,
whose ways are beyond the investigation of human understanding,
to perfect the faith and exercise the patience of the best men,
by suffering them to feel adversity in common with other classes of mankind:
as to the contingencies of this life (in the words of Solomon,)
one event cometh to the righteous and the wicked.
This good man in his temporal affairs met with various trying casualties,
losses and disappointments, not in consequence of any extravagance or indolence of his,
being frugal without covetousness,
and industrious in business without suffering an
anxious care for temporals so to engross his mind,
as to unfit it for,
or prove an obstruction to his religious progress or his religious duties.
Through various unfavourable and unforeseen events, heavy losses by sea and land,
by fire and water, he was much reduced in his outward circumstances;
yet being supported by conscious integrity, he did not sink under misfortune,
but as the most likely means that offered for retrieving the state of his affairs,
he betook himself to a sea-faring life, and made several voyages to Barbados,
in quality of factor, and afterwards as master of a vessel,
wherein he encountered many difficulties and dangers in order to provide for his family,
and discharge his pecuniary engagements.
From the year 1727 to 1735, he frequently crossed the seas in the way of trade,
mostly to Barbados and other West-Indian islands; once to Dublin,
and last of all to London,
where he sold his vessel and settled his affairs to satisfaction;
joyful that divine providence (who seeing the integrity of his heart,
and the honesty of his intention, had supported him through all his difficulties,
and in the midst of outward troubles had often replenished
his mind with inward consolation) had favoured him so far,
as to grant him to see the end of his labour accomplished;
he then purposed to decline trading any longer by sea,
in which he had engaged not from choice, but expediency;
not to accumulate wealth for himself,
but to provide things honest in the sight of all men.

A heart influenced by pure religion, duty to God and love to mankind,
steadfastly pursues the same important object in every vicissitude of life.
This friend in his sea-voyages generally held religious meetings
with the passengers and mariners on the first days of the week,
and at convenient seasons on other days;
he frequently exercised himself in reading the scriptures and other religious trails,
or in meditating and writing upon religious subjects
for the edification of himself or others.
Many pieces which he wrote at sea are convincing proofs that religious
considerations were predominant above all others in his mind.

On shore his engagements in business did not abate his zeal to make use
of all opportunities of visiting the meetings of friends as formerly,
both in the neighbourhood of his residence, when at home;
and in those parts whither his business drew him.

After he had settled his affairs and was discharged of the heavy load of care,
which had long oppressed him,
he spent several months in England exercising his ministerial labours for the last time,
amongst his friends about London and Northward.
Which service being finished, and a favourable opportunity occurring for returning home,
he took his departure from England and landed at Philadelphia in the year 1736.

Although he had now passed his 60th year, and was at times afflicted with the asthma,
he continued his religious visits to his friends in various parts of the
American continent more or less every succeeding year of his life;
and last of all in the year 1741 he embarked for
Tortola under a concern to preach the free gospel,
as way might be opened, to the newly convinced inhabitants of that island,
for their confirmation and establishment in spiritual religion, as the way to salvation.

In this island he was joyfully received and hospitably
entertained by John Pickering and his wife,
where he diligently exercised himself in the faithful
performance of the service which he came upon,
being day by day employed therein,
either in public meetings or in private visits to the families of the inhabitants;
and these visits generally ended in a religious meeting,
the people being so awakened and so desirous of being instructed
in solid religion and the way of peace and salvation,
that he could seldom pay a friendly visit but the rooms would be filled,
or seldom depart without a season of worship,
in which he was often engaged in ministry amongst them,
to his own refreshment and the benefit of the audience.

Having thus profitably employed his time for about seventeen days,
on the 29th of 8th month, he found himself indisposed,
yet attended the weekday meeting that day, and also the meeting on first day following,
wherein he concluded his last labour in the words of the apostle Paul,
"`I have fought a good fight, I have finished my course; I have kept the faith;
henceforth there is laid up for me a crown of righteousness.`"
His disorder proving a fever, in three days terminated his labours with his life,
the 4th of 9th month, 1741, in the 66th year of his age,
to the great regret of his friends and others,
whose affectionate esteem and respect he had in a peculiar manner engaged,
during his short stay amongst them, by his edifying ministry,
his instructive and exemplary deportment,
and his universal benevolence and tenderness to the inhabitants of the island,
of every rank and profession.

The character given of him by his friends, amongst whom he lived,
and who were witnesses of his general demeanour, is this,
that in disappointments and afflictions, of which he had a large share,
his patience was remarkable: his meekness,
humility and circumspection in the general course of his
life and conversation were conspicuous and exemplary;
gentle, courteous and loving in his deportment, not only to friends but to all others,
with whom he had conversation or dealing;
few have lived so universally beloved and respected amongst us.
He was a lover of unity amongst brethren, and careful to promote and maintain it;
yet his love and regard to peace,
did not divert him from the discharge of his duty in a faithful
testimony to those that professed the truth,
that they ought to be careful to maintain good works.
And he was often concerned zealously to incite and
press friends to the exercise of the good order,
and discipline established in the wisdom of truth.

John Estaugh, was born in Keldevon, in Essex in Great Britain, anno 1676,
of religious parents.
As he advanced towards maturity,
he grew uneasy with the religious professions or both his parents,
they being of different persuasions,
and being religiously engaged to seek after the truth, he fell in with the Baptists,
whom he liked so well, as to incline to join with them.
But being at the burial of a neighbour, who had been one of the people called Quakers,
a friend was led to speak with such life and power directly to his state,
as to make a deep and lasting impression on his mind.
This put him upon an inquiry into the principles of friends,
of the truth of which he was so fully convinced,
as to join the society about the seventeenth year of his age.

He came forth in the work of the ministry when about eighteen years old,
and being faithful to the manifestations of duty, he grew in his gift,
and soon after travelled to visit friends in the north of England and in Scotland,
and in the year 1700, he came over on a religious visit to friends in America.
After he had performed this visit to the great satisfaction of friends,
he settled at Haddonfield in the county of Gloucester, New Jersey,
where he soon after married.

After he settled in America, he visited friends in England and Ireland;
and many parts of the continent of America;
and several times paid visits to some of the West-Indian Islands;^
footnote:[See page 149 of this vol.]
but in the latter part of his life,
he was prevented by indisposition from much travelling.
His good master, who requires no impossibilities, favoured him with ease of mind,
and the comforts of domestic peace at home, during this his time of bodily infirmity.
His wife who survived him testifies that she believes few
if any ever lived in a more perfect harmony than they did.
He was a pattern of moderation,
not lifted up with any enjoyments nor cast down at disappointments.
He was a man humble-minded, and exemplary, solid and grave in his deportment,
well becoming a minister of Christ, zealous for preserving good order in the church,
and maintaining love and unity, that badge of true discipleship,
remarkably careful in his conversation among men, his words being few and savoury.

After some years of indisposition,
it pleased the Lord to restore him to a state of health;
and soon after he had a concern to visit friends at Tortola.
This brought on him a deep exercise,
but when he was confirmed it was really required of him, he gave up to it;
and was then weaned from home, and the company there,
which used to be so pleasant to him.

He first wrote to friends on that island; but finding that would not excuse him,
he durst no longer delay; so on the 13th of 8th month, 1742,
he left his home to proceed on his visit to that Island.
On the 8th of 9th month,
he arrived at the house of John Pickering with his companion John Cadwallader,
where they were received with much love and great joy,
being made to rejoice together in the tender mercies and love of God,
which were greatly manifested that day, to the honour and praise of his name,
and to the comfort of his people.
The testimonies of these ministers were with life and power,
and as clouds of rain upon a thirsty land.

The godly life and conversation of this friend,
of whom we are now giving a particular account, spoke him a true follower of the Lamb,
and minister of Christ.
He had his health very well, '`till the death of his dear companion;
but going to his funeral he caught his illness from a shower of rain.
However he was favoured with the divine presence,
so as to be able to answer the service of that day;
and the next being first day he was at meeting, and though near his end,
his candle shone as bright as ever, and many that beheld it,
were led to glorify God on his behalf.
This was the last opportunity he had on the island, except his farewell on his dying bed,
where he both preached and prayed, a short time before his departure.

On the next day he went to a little island called Jos.
Vandick`'s, accompanied by several friends; on the third day in the morning,
he complained very much, but was enabled to go to meeting,
where he bore a lively testimony, but from weakness of body, and extending his voice,
he was so inwardly spent, that he was ready to faint.
However he went on board the sloop that night on his return to Tortola,
where he landed next morning.
He had not been long at his lodging before he was seized with a shivering fit,
and a fever soon followed.
The two last days he suffered much pain,
yet he was preserved under it in patience and resignation,
and had his perfect senses to the last--On the 6th of 10th month,
he went away like a lamb,
with praises and thanksgivings on his lips in the 67th year of his age.

John Cadwallader, was convinced of the truth when young;
and by a diligent attention to its manifestations,
became in some time a minister thereof to others.
He travelled much in the exercise of his gift on the continent of America;
twice crossed the seas to Europe, and once to Barbados on the same account.
His last visit was to the island of Tortola, in company with John Estaugh.
He was taken ill on his passage thither, yet when he landed, proceeded in the service,
upon which went, much to the satisfaction of friends there,
as appears from accounts from thence.
But his disorder increasing upon him, he departed this life in peace on said island,
the 26th of 9th month, 1742, aged near 66 years.
