== Chapter XII. Pennsylvania continued.

[.chapter-synopsis]
* Endeavours used to deprive Friends of their Places in the Assembly
* They are misrepresented to the British Nation and Government
* General Meeting at Philadelphia
* Dead Bodies of some who had been murdered brought into the City
* Vindication of Friends
* Remarks upon the Indians, and the Methods of treating them
* Subscription for the suffering Inhabitants
* Meeting for Sufferings established at Philadelphia

By the misapprehensions and prejudices raised in
the minds of the proprietaries concerning them,
or by their voluntary resignation,
few of the people called Quakers now enjoyed any share in the executive part of government;
and to elude the force of that spirit of envy and rancour,
which had been artfully excited against them,
and for the peace and quiet of their own minds,
several of them had avoided taking part in the legislature.
On the approach of the annual election of this year,
their adversaries exerted their utmost efforts to prevent the same members being re-elected,
the press being set at work,
to pour forth acrimonious and unjust invectives against them,
in order to prevail with the electors to set them aside, and choose their own partisans,
or members who might be brought to act in a manner more conformable to their views;
but notwithstanding much the greater number of the inhabitants were not of their society,
yet such was the confidence reposed in those Quakers,
(so called) that the former representatives who had not declined the service were re-chosen,
by the greatest majority ever known,
and this was done not only without the solicitations,
but in some instances without the privity or approbation of some that were chosen,
four of whom, being of those called Quakers,
at the first meeting of the house resigned their seats, and a new election took place.

Their antagonists, filled with vexation at their disappointment,
both in missing their aim in the election,
and finding all their disingenuous efforts had made
so little impression on the judgment of the electors,
whole dependence on the tried integrity of their representatives,
where their views and characters, and those of their adversaries were best known,
was too firm to be easily shaken; next exerted their endeavours to carry their point,
by misrepresenting them on this side of the Atlantic,
where both the Quakers (so called) of America, and their accusers; their different views,
principles and general conduct were less thoroughly known;
for this purpose they drew up the most pointed invectives,
and procured them to be printed in pamphlets and the English newspapers.
In order as much as possible to prepossess the minds of
the people with strong prejudices against them.

The general or half year`'s meeting was held in the
third month of this year at Philadelphia in course,
and notwithstanding the deeply exercising trials
which affected this society at this time,
they had a strengthening and edifying meeting, and,
beside a great number of friends from different parts of the country,
it was attended by Samuel Fothergill and Catharine Peyton from England,
and Mary Peisley from Ireland;
these being well qualified ministers and deeply experienced in the work of religion,
their service was very helpful and instrumental to the consolation of their friends,
and to the confirmation of their faith,
patience and stability in their religious principles.

During the time of this meeting an incident occurred which
affected friends with still more gloomy apprehensions.
The Indians who had before ravaged some of the frontier settlements,
about this time renewed their incursions on the back settlements of Pennsylvania,
where they burned several houses and killed and scalped some of the inhabitants:
this furnished an opportunity pleasing to the parties, who were clamorous for war,
to promote their purpose, in order whereto,
two or three of the dead bodies of those who had been murdered,
were at this time brought in a wagon to Philadelphia,
with a design to exasperate the citizens, and rouse them to tumult and vengeance.
For they were taken before the State House door and from
thence conveyed through several streets of the city,
attended by a crowd of people cursing the Indians and the Quakers also,
because they were backward to promote warlike measures for their destruction.
The sight of the dead bodies and the outcry of the
people were both very afflicting and alarming.

The incursions and ravages of the Indians,
and the dangers to which the frontier settlers were exposed, were much magnified,
and furnished a plausible subject for more violent
exclamations against the people called Quakers,
and the absurdity of adhering to pacific principles, when the enemy was at the door:
allegations of an alarming nature were now spread through the colonies,
and through England, that the province would be ruined or absolutely lost,
if speedy measures were not taken,
to deprive the Quakers entirely of any share in the government;
these representations of the state of this province
met a ready reception and belief on this side;
and the blame of the whole was laid upon this people,
who in fact were the least culpable of any,
and the least answerable for the present disturbed state of the colony,
as having least contributed thereto.

For from their first settlement,
and while the direction of public affairs was in their hands,
the Indians were so far from making hostile incursions into any part of the province,
that,
being treated by them with a scrupulous regard to justice and with cordial hospitality,
in return for the kindness they had received from them,
they (the native inhabitants) lived with the Pennsylvanians on the most friendly footing,
and regarded them with affectionate esteem.
And had the succeeding governors and the people in general observed
the like equitable and friendly conduct towards them,
I believe these hostile incursions (into the frontiers
of Pennsylvania at least) had never been heard of.

For notwithstanding some writers have represented the Indians as naturally stupid,
ferocious, treacherous and ungrateful:
yet several of those who had the opportunity of conversing amongst them,
and observing them more attentively, represent them in a different character,
as sensible, friendly, hospitable, faithful to their engagements,
kind to the neighbouring Europeans,
and very affectionate and peaceable in general in their own tribes and allies:
but of quick sensibility to feel injuries, and of savage cruelty in revenging them.^
footnote:[The first settlers of Pennsylvania who had full opportunity
of being acquainted with the nature and disposition of the natives,
and who made it a principal point to observe strict
justice in all their transactions with them,
have left us very favourable memo rials of the long
continued kindness they experienced from those people.
The disposition of the Indians has generally been,
to show kindness to the Europeans in their early settlements;
and their mental powers are equally with our own capable of improvement.
The apparent difference between them and us arises principally
from the advantages of our education and manner of life.
The early settlers of New Jersey have always confirmed
the testimony of the Pennsylvanians concerning them,
with respect to the good usage they met with from the Indians.
The writer of the history of that province informs us "`That for almost a century,
the natives had all along maintained an intercourse of great cordiality and friendship
with the inhabitants.`" (A. Benezet)
{footnote-paragraph-split}
They manifest much
stability in the engagements they have solemnly entered into;
patient in affliction,
as well as in their submission to what they apprehend to be the appointment of providence;
in which they manifest a nobleness of soul and constancy of mind,
at which we rarely arrive with all our philosophy and religion.
They are slaves neither to ambition nor interest,
the two passions which have so much weakened in us those sentiments of
humanity which the kind Author of nature hath fixed in the human heart,
and kindled those of covetousness, which are as yet generally unknown amongst them.
_Charlevoix apud umdem._]

Therefore if the like prudence, justice,
and friendly intercourse bad been maintained in their
conduct and commerce with the Indians,
by their successors of this age, which had been done by William Penn,
and the early settlers, I am persuaded these natives,
instead of hostilities would have continued to cultivate
the like amicable disposition towards them,
as they had done to their predecessors;
and that it would not have been in the power of the French in that case,
by all their artifice,
to have incited them to hostile measures against the English plantations,
if the English themselves had not by their neglect and unfair dealing,
furnished their enemies with a handle of which they well knew how
to avail themselves.--One of our historians remarks upon this period,
that "` It had been long the method of the English to cultivate
the friendship of this fierce and hardy race in time of danger,
but to slight it in circumstances of safety.`" This served to alienate
the affections of the Indians from the English government,
and the avarice of our merchants particularly those called the Ohio company,
as well as the Indian traders who sold them bad commodities,
and treated them with perfidy and insolence, served to confirm their aversion.^
footnote:[ Duprat observes,
"`That there needs but prudence and good sense to persuade the Indians to what is reasonable,
and to preserve their friendship without interruption.`" He adds, "`We may safely affirm,
that the differences we have had with them have been more owing to us than to them.
When they are treated insolently or oppressively,
they have no less sensibility of injuries than others.
If those who have occasion to live among them, will have sentiments of humanity,
they will meet in them with men.`"]

These moving causes of their discontent and present inimical disposition,
the people called Quakers were not instrumental to promote.
We have seen their early care to prevent any of their members
from supplying the Indians with spirituous liquors,
of which they were very fond, and which were very pernicious to them in various respects^
footnote:[See vol.
3 page 307.]
--they were studious to do them good;
to endeavour to draw them by winning persuasions and acts of benevolence,
and instruction from the inconveniences to which
their ignorance and roving temper subjected them:
this the Indians knew, and for this they venerated the memory of the deceased,
and placed an especial confidence in the surviving body of this people.

From hence this inference may be drawn, that beside those conscientious motives,
which have the greatest weight with religious and good men, to do justly to all men,
even as we would have them to do unto us;
human prudence and sound policy point out the superior wisdom
of endeavouring to conciliate the friendship of the natives,
which is easily purchased by affability, honesty and integrity,
rather than to subdue them by force,
which is not easily effected even at the expense of much blood and treasure,
often expended in vain.
And of consequence that after all the severe censure, calumny,
and clamour raised against the people called Quakers in Pennsylvania,
their measures of treating the Indians, both formerly and even at this time,
were more christian-like, more rational,
and more effectual for rescuing the frontiers from their devastation,
than the sanguinary and violent measures their adversaries were desirous to promote.^
footnote:["`The perpetual increasing generations of Europeans in America,
may supply numbers that must in the end wear out
these poor Indian inhabitants from their country;
but we shall pay dear, both in blood and treasure, in the mean while, for our injustice.
{footnote-paragraph-split}
"`Our frontiers,
from the nature of advancing settlements dispersed
along the branchings of the upper parts of our rivers,
and scattered in the disunited valleys, amidst the mountains,
must be always unguarded and defenceless against the incursions of Indians.
The farmer driven from his little cultured lot, in the woods, is lost:
the Indian in the woods, is everywhere at home; every bush, every thicket, is a camp,
to the Indian; from whence, at the very moment when he is sure of his blow,
he can rush upon his prey.
In short, our frontier settlements must ever lie at the mercy of the savages;
and a settler is the natural prey to an Indian, whose sole occupation is war and hunting.
{footnote-paragraph-split}
"`To countries circumstanced as our colonies are,
an Indian is the most dreadful of enemies.
For in a war with Indians, no force whatever,
can defend our frontiers from being a constant wretched scene of conflagrations,
and of the most shocking murders.
Whereas on the contrary, our temporary expeditions against the Indians,
even if successful can do them little harm.
Every article of their property is portable, which they always carry with them;
and it is no great matter of distress to an Indian,
to be driven from his dwelling ground,
who finds a home in the first place he sits down upon.`"]

It also appears that the people called Quakers were sensibly impressed
with a degree of compassion and sympathy for the sufferers in this calamity,
equal or superior to any thing of that nature manifested by the adverse party,
who taking advantage of the prevailing distresses,
to promote their own political schemes were indefatigable
in their clamours to vilify the Quaker government;
but did little that I find for the help or relief of the afflicted;
while the Quakers actuated by motives of commiseration,
as soon as they heard of the devastation committed by the enemy Indians on Gnadeuhutten,
a settlement of the society called Moravians,
on the frontier part of the county of Northampton,
voluntarily raised a sum of money among themselves,
which was expended in provision and clothing,
and committed to the care of suitable persons for distribution among the sufferers.

And about the same time a subscription was on set on foot and a
considerable sum of money contributed by the Quakers in the city,
and some parts of the country,
for the succour of the distressed inhabitants who had abandoned
their habitations on the western frontiers of the province,
and taken refuge in the interior parts,
which was in like manner distributed among them without distinction of sect or party,
and proved a seasonable relief against the winter.

As I am furnished with the originals or copies of several letters of correspondence,
which passed between them, I am enabled to trace the transactions of this period,
so far as this society is concerned, with a greater degree of precision.^
footnote:[ I apprehend it will be more satisfactory to the reader,
and more apposite to the uniformity of historical
narration to recite the matters of fact as they arise,
than to interrupt the narrative by the insertion of the letter, and papers at length:
yet as some of the said letters and paper appears worthy of a place in this work,
and may give considerable satisfaction,
I think they may be conveniently introduced in an appendix
to this book and referred to as occasion requires.]

The annual meeting for Pennsylvania and New Jersey,
(held in course in the 9th month of this year at Burlington) taking under consideration
the distressed state of the frontier settlements of these provinces,
and having grounds to apprehend that many of their brethren in religious profession,
situated in parts immediately exposed to danger,
might soon stand in need of relief and assistance,
who for want of timely attention and care might be
liable to suffer greatly in the approaching winter:
agreed to raise the sum of one thousand pounds for this purpose:
and as the exigencies of the society by the continuance of the calamities of the war
and the malevolent misrepresentations of their adversaries required vigilant attention;
this meeting after approving the transactions of
the committee appointed in the preceding year,
found it expedient to adopt a proposal of constituting a meeting for sufferings,
and after considering and defining the services and
trust to be committed to the said meeting,
nominated twelve friends as representatives of the yearly meeting,
and directed the respective Quarterly meetings to
appoint four members each to represent them.

[.embedded-content-document.letter]
--

[.letter-heading]
The Services to be performed by the Meeting for Sufferings, viz.

To hear and consider the cases of any friends under sufferings
and to administer relief as necessity is found to require,
or to apply to the government or persons in power on their behalf.

To correspond with the meeting for sufferings or the yearly meeting in London,
and to represent the state of friends here,
and in general to represent this (the yearly) meeting,
and appear in all cases where the reputation and interest
of truth and our religious society are concerned,
but not to interfere in matters of faith or discipline
which are not already determined by the yearly meeting.

To consider the uses and manner of application of charitable legacies and donations,
and to advise respecting the titles of any land,
or other estate belonging to the several meetings, etc.

To receive an account from the several particular meetings,
of any sufferings to which friends may be subjected for the testimony of truth.

And that fair minutes of all their proceedings should be kept,
and laid before the yearly meeting from time to time.

--

And some years after the establishment of the said meeting,
the revisal of all manuscripts intended for publication by any member of the society,
was committed to the care thereof,
as also any proposal for the reprinting of books for general service.
