== Chapter XI. Pennsylvania

[.chapter-synopsis]
* Original State of Pennsylvania
* Its long Enjoyment of Peace
* A due Regard to Religion the surest Foundation of a good Government
* The Prosperity of Pennsylvania under the Administration of the People called Quakers
* New Settlers excite Discontents
* The proprietary Governors endeavour to shake Encroachments, which are opposed by the Assembly
* Whereby they conceive a Dislike to Friends
* The French instigate the Indians to war against the English Plantations
* Declaration of War
* Causes a popular Cry for warlike Preparations
* Militia-law for the lower Counties
* Address to the Proprietaries there upon

Pennsylvania from the excellent institution of its founder William Penn,
in concert with original planters, and the punctual adherence thereto,
in the letter and spirit of it,
by the succeeding assemblies and magistrates of the province,
in the enacting and executing of useful laws,
had enjoyed tranquility and security in the possession
of religious and civil rights and immunities,
exceeding any other government or nation whose history we are possessed of.
The legislative and executive authority being in the hands of religious
men (the greater number of whom were of the people called Quakers,
although the universal toleration granted by William Penn,
admitted all denominations of christians to offices of magistracy
and to the highest posts in the state) their laws and institutions
were directed to cultivate and maintain a lively sense of religion:
and being themselves examples of that sobriety, decorum,
and submission to salutary institutions and legal rule,
not for wrath but for conscience sake,
which they wished to disseminate amongst the different orders of the people,
a general harmony subsisted between the inhabitants; and regularity,
order and due subordination resulted from this lively sense, of religion,
to a degree far beyond that merely effected by human policy or penal laws.

That the welfare and happiness of the people is the end of government,
is a proposition maintained in theory in other states;
but in Pennsylvania it was reduced to practice.
A government established on so equitable, liberal and useful a plan,
induced great numbers of people of different persuasions,
to emigrate from various countries,
to participate in the privileges and felicity of this equal government,
the basis of which was religious and civil liberty: and for a length of time,
under the pleasing sensation of the ease, security and change for the better,
they felt from their removal hither, people of different nations,
complexions and ways of thinking,
lived together in a state of society beautiful in prospect, and happy enjoyment,
in mutually giving and receiving the benefit of an equality of privileges in peace,
amity, and benevolence, although not belonging to the same visible church,
yet as belonging to the same fraternity of mankind.
Universal liberty of conscience, and universal good-will to men,
being in the estimation of the people called Quakers
essential characteristics of the christian religion,
have been adopted by them in their fullest extent,
they hold none excluded from the favour of God on account of their religious persuasion,
provided it be founded in his fear, and the love of mankind.

By means of these excellent principles of its long government,
and the just and equal administration thereof, through the favour of divine providence,
Pennsylvania had enjoyed an almost uninterrupted peace from
within and without for more than sixty years.

Amidst the variety and fluctuation of opinions upon the subject of government,
it appears evident to me that it is virtue, simplicity of manners,
and a reverent regard to religion, more than the particular form,
which stamps it with the character of good and excellent;
not but I admit some forms and some constitutions are better in themselves than others,
and better adapted to promote the general good, yet we shall find, that wherever virtue,
justice, and real religion are departed from and disregarded,
the very best will go to decay.
Those ancient republics which many so much admire, and extol,
as perfect models of good government, were only so,
while the people by the example of their superiors, were taught to be virtuous,
frugal and temperate; but when opulence and vice had banished those good qualities,
and introduced dissipation, luxury and a general corruption of manners,
what scenes of human misery can exceed these produced
by the collision of inflamed and hostile parties,
by the cruelty and vengeance of their leaders,
or the violent outrage of a licentious and ungovernable populace?
So that most ages, states and nations, have verified the scriptural position,
Righteousness exalts a nation but sin is a shame
(and very often a downfall) to any people.

The industry, frugality and security of the Pennsylvanians,
made this colony as prosperous and flourishing during this period as it was peaceful.
This flourishing state of the province, occasioned a great accession,
of people of different dispositions and views from the first settlers,
who had resorted thither to share in its prosperity,
which they had contributed nothing to.
And many of these soon discovered,
that they grudged the body of friends the rank and
influence which they possessed in the stable,
and the place they had in the estimation of the people,
although so justly entitled thereto;
both on account of their being principally instrumental, through much expense,
labour and difficulty, to reduce the wilderness into a fruitful land,
and bring the province to its present state of prosperity;
as also on account of the equity and economy of their government,
which had proved them faithful guardians of the public weal:
parsimonious in granting and rigid in requiring an
account of the expenditure of the public treasure;
limiting the salaries of public offices to a moderate and
reasonable compensation for the labour and trouble thereof;
peculation was a stranger here, and public taxation very light:
under their government the people had been long contented and happy;
so that it is no wonder that in general they regarded them with cordial esteem.

But those who envied them their power and influence,
those who had in a great measure among got possession or wanted
to get possession of the posts of government they had enjoyed,
and to reap the fruit of their labours,
began to interrupt the peace of this peaceful state,
and sow the seeds of discord and discontent by decrying the public measures of friends.
As a self interested policy prevailed, that brotherly intercourse and mutual benevolence,
which had so honourably distinguished the original colonists decayed:
private interest and private views were more regarded by many than the public good,
and gradually introduced jealousies, mistrusts and party animosities,
whereby the system of happiness, so long and so well maintained,
fostered a lamentable reverse;
and the manners of the people discovered an alteration for the worse.

A principal cause of uneasiness to the people called Quakers
and the ancient inhabitants of endeavour the province,
seems to have arisen from the proprietary governors and their adherents,
who did merits not pay that strict regard to equity and the constitutional
rights of the people in all the departments of government,
which during the life of the first proprietor and long after, had with little exception,
harmonized the different orders of the state within itself,
and gained it the reputation of wisdom and honour
from those who attentively considered its excellency.
The descendants of William Penn, who inherited his possessions and his power,
do not appear to have inherited all his virtues, his disinterestedness, his faith,
or his benevolence: they,
and the governors under them on sundry occasions adopted self-interested maxims of government,
and partial schemes of policy.
Not contented with the power and emoluments the constitution allowed them,
they had extended and wanted still to extend their prerogatives further;
and such of the people called Quakers as were members of the assembly,
in conjunction with others,
conceived it to be their civil as well as religious
duty in faithfulness to their constituents and in,
the conscientious discharge of their delegated trust,
to adhere firmly to the salutary regulations and concessions
agreed upon between the early settlers and William Penn,
which stood as a guard and defence of the subjects rights,
and as a bar against the encroachments and sinister designs
of men lusting after the unequal emoluments they hoped for,
from the attainment and exercise of an undue power and influence:
Under these impressions the assembly opposed and withstood all further innovations
and invasions of the constitutional rights of the people.

From this opposition to their selfish purposes,
Whereby the governor and his partisans manifested
a great dislike and enmity to the body of this society;
and having the ear of the proprietaries,
they exerted themselves by most unfair and unjust representations to impress
them with very unfavourable sentiments of the society in general,
and to create jealousies and distrusts between them and the colonists,
to separate their interests and set them at variance,
having perhaps more regard to their own views and power,
which they sought to establish by these means,
than either to the real interests of the province or the proprietaries,
which in the opinion of judicious men were united,
and that they were no friends to either who endeavoured to separate them.

The enemies of this society also sought occasion to accomplish their selfish designs,
and about this time an opportunity presented.
The hostilities of the French had been but little suspended
by the treaty of Aix-la-Chapelle in these remote parts;
for while peace was ostensibly preserved in Europe,
both in Asia and America hostile measures were carried on in a covert way,
which discovered themselves in America by the incursions of the
Indians into the back settlements of the English plantations,
being instigated thereto by the French as was generally understood;
who killed and scalped many of the inhabitants, and carried others into captivity.
The French at the same time were busily employed in erecting a
line of forts on the back of the English settlements and in places
to the prior possession of which England laid claim.
These infractions of a treaty so lately made,
produced repeated complaints from the government of Great Britain without redress;
they were principally answered by recriminations,
so that at length the result was a declaration of war on both sides.

This circumstance furnished a plausible occasion
to raise a popular cry for warlike preparations,
which the people called Quakers were known to principled against,
and for their declining to enter into such measures they
were treated with all the virulence of party rage:
both the pulpit and the press were employed calumniate and vilify them;
they were represented as unfit to take any share in government,
and much violence and artifice of party were put in practice,
with little regard to truth or justice,
to deprive them of their reputation and their influence.

About this time means were used to get a law passed
by the legislature of the lower counties on Delaware,
for establishing a militia, and it seems to have been enacted in a temper,
that paid no regard to the conscientious scruples of friends and others;
but rather pointed to bring them under difficulties and sufferings.
Upon this it was thought necessary to address the proprietaries with the following remonstrance,
viz.

[.embedded-content-document.address]
--

[.letter-heading]
To Thomas Penn and Richard Penn, proprietaries of Pennsylvania,
and the three lower counties of New Castle, Kent and Sussex upon Delaware.

[.blurb]
=== The Address of the People called Quakers, on behalf of their Brethren inhabiting the said lower Counties, respectively showeth,

That for above one hundred years past,
we as a religious society have declared to the world,
that we could not for conscience sake bear arms or be concerned in military preparations;
that for many years after our becoming a distinct society,
we suffered many grievous and oppressive persecutions on account of our principles;
that the prospect of being entirely relieved from such oppression,
and of enjoying perfect liberty of serving God in
the way they believed most agreeable to him,
engaged many of our ancestors to leave their native lands, and come over to settle this,
then a wilderness country,
and though your honourable father`'s principles were
well known to be for entire liberty of conscience,
yet he and the first settlers mutually thought it
necessary to fix this as a law before they came over,
and accordingly did, as appears by the 35th section of laws agreed upon in England,
May the 5th, 1682, in these words.

That all persons living in this province,
who confess and acknowledge the one almighty and eternal God to be the Creator,
Upholder and Ruler of the world,
and that hold themselves obliged in conscience to live peaceably and justly in society,
shall in no ways be molested or prejudiced for their religious
persuasion or practice in matters of faith and worship,
nor shall they be compelled at any time, to frequent or maintain any religious worship,
place or ministry whatsoever.

That this was understood as the first and most fundamental
part of the constitution appears undoubtedly plain,
from the solemn manner in which it is introduced,
and the general expressions contained in the first clause of the charter of privileges,
viz.

Because no people can be truly happy though under the greatest enjoyment of civil liberties,
if abridged of the freedom of their consciences as
to their religious profession and worship,
and almighty God being the only Lord of conscience, Father of lights and spirits,
and the author as well as object of all divine knowledge, faith and worship,
who only doth enlighten the minds and persuade and convince the understandings of people,
I do hereby grant and declare,
that no person or persons inhabiting in this province or territories,
who shall confess and acknowledge one almighty God, the Creator,
Upholder and Ruler of the world,
and profess him or themselves obliged to live quietly under the civil government,
shall be in any case molested or prejudiced in his or their person or estate,
because of his or their conscientious persuasion or practice,
nor be compelled to frequent or maintain any religious worship, place,
or ministry contrary to his or their minds,
or to do or to suffer any other act or thing contrary to their religious persuasion.

May it please the Proprietaries,

Notwithstanding these plain and explicit words,
an act of assembly hath been lately passed in the lower counties, entitled,
an act for establishing a militia in this government,
whereby the inhabitants are required to enlist,
provide themselves with arms and ammunition, to attend with them at certain stated times,
"`in order to be taught and instructed in the military exercise;`" with other
injunctions of the like kind and nature under certain fines and penalties,
without any exemption of those of tender consciences,
which in our judgment is in direct repugnance to the clauses above recited,
because it enjoins certain acts and things contrary to the
religious persuasion of many of the inhabitants.

Our ancestors who did foresee the probable inconveniencies likely to attend,
had the greatest reason to esteem this interesting and important
point inviolably secured to them and their posterity,
both by the foregoing,
and (if possible firmer still) by the following paragraphs of the same character,
viz. --"`But because the happiness of mankind depends so
much upon the enjoying of liberty of their consciences,
as aforesaid.
I do hereby solemnly declare, promise and grant, for me,
my heirs and assigns that the first article of this charter,
relating to liberty of conscience and every part and clause therein,
according to the true intent and meaning thereof,
shall be kept and remain without any alteration inviolably forever,
and if anything shall be procured or done by any person or persons,
contrary to these presents, it shall be held of no force.`"

We presume we need not say much more to you on this head,
because we are informed that you have always given express instructions
to your deputies that in case of making any militia law,
they should take especial care that the charter be not infringed in this respect,
it is therefore we have the greater cause to hope
for your disapprobation of the act before mentioned,
as far as concerns tender consciences,
and we earnestly request it may be speedily declared,
as the heavy fines laid on the officers for not putting it in execution,
is without doubt,
intended to oblige them to a strict observance of the several parts of it,
and as it is possible this may come to your hands
before you receive from your officers here,
a copy of the said act,
we have sent one certified under the seal of the office at New Castle,
to our friends Richard Partridge, Thomas Jackson, John Hunt and John Fothergill,
whom we have requested to communicate it to you,
and though our principal objection to the act arises
to its enjoining things upon some of the inhabitants,
which they are religiously persuaded they neither can nor ought to do,
yet we believe in your perusal of it you will see other reasonable objections,
in particular that the fines for noncompliance,
are so many and so much in the power of rapacious officers,
that they may under the colour of it,
take more (from such as cannot for conscience sake
comply) than the produce of their labour,
after necessary allowance for clothes, diet, etc. would amount to,
as goods taken in consequence of such oppressive measures,
are generally sold much under their real value, which if the law be so put in execution,
must tend to the ruin of the worldly substance of many inhabitants,
and the consequence of that to your interest, we need not point out.

We sincerely desire that divine wisdom may be plentifully afforded to
conduct you through the various difficulties attending your station,
to your own true peace, the prosperity of your province and the glory of God.

[.signed-section-context-close]
Signed at Philadelphia, 5th month 21st, 1756,
by a committee appointed by the yearly meeting, for Pennsylvania and New Jersey.

--
