== Chapter XIII. Pennsylvania continued.

Proprietaries`' Answer to the Address.
--Calumnies against the People called Quakers in Pennsylvania,
gain credit in England.--The fleeting for Sufferings in London
interpose on behalf of their Brethren.--A Deputation from them
apply to a Nobleman in high Station.--His Advice to them.
--Meeting for Sufferings in London write to Friends in Philadelphia.--But one
third of the present Assembly are Quakers.-- Rigorous Exactions under the Militia-law.--
Proprietaries refusing to let their own estates be taxed,
occasions Discontent.

The meeting for sufferings in London,
in compliance with the request of friends of Philadelphia,
in a letter accompanying their address to the proprietaries,
appointed a committee to deliver it and confer with them thereupon,
who received for answer,
"`That the proprietaries had no desire or intention to abridge
the people of the province of Pennsylvania in general,
or friends in particular,
of any rights or privileges to which they are by charter entitled;
and that if either friends or others, inhabitants of the province,
apprehend they have any just cause of complaint,
and will point out the particular grievance, it shall be duly considered and redressed.
--This answer appears plausible, but I think evasive;
the address specified the particular grievance and cause of complaint,
and that their chartered privileges were abridged; yet it doth not appear,
that the complainants received any redress, but the cause of complaint still continued.

On the other hand,
their calumniators by their strenuous efforts had well nigh compassed their main design
of excluding all the Quakers (so called) from any share in the government or legislature,
and subjecting them entirely to their mercy.
Their exaggerated mis-statement of facts,
and unjust reflections upon a body of men who had deserved better of Pennsylvania,
than any other, had met with easy credit by many people of various ranks in England,
and filled them with violent prepossessions against
the Quakers and their principles and conduct:
not only the injudicious part of the people;
but men of abilities and men in power had been carried
away with the stream of popular prejudice,
and suffered themselves to be influenced by the prevailing notion,
that the Quakers must be removed from all Offices of government,
or the province be absolutely lost.

In this circumstance of affairs the meeting for sufferings
in London understanding that measures were in agitation,
tending to deprive their friends in Pennsylvania of their religious rights and privileges,
and to make some material alterations in the present frame of government in that province;
from that fraternal affection and sympathy which connects
the members of this society as brethren all the world over,
and in discharge of the trust of their appointment, which is,
to advise and interfere in every good office for the help
and relief of their friends under suffering in general,
thought it their duty to use their endeavours to prevent the design taking effect.

A deputation of several friends was accordingly appointed
to wait upon a nobleman in a high station,
in order to request his advice and favourable interposition,
who received and treated them with remarkable kindness,
and candidly gave them his advice,
and promised his endeavours to prevent matters being carried to extremity;
the purport of his advice the said deputed friends
delivered to the meeting in their report,
as follows.

He acquainted friends who waited on him,
that he discovered a general and strong prepossion
nobleman excited against us as a people,
both here and in America, chiefly he believed from the station,
repeated accounts transmitted hither,
of the distressing situation of affairs in that province,
which were too readily credited by all ranks,
and ascribed to the principles and conduct of the society.

That even those in considerable stations,
who had been our firm friends on various occasions, now seemed to be so far influenced,
as to be either wavering in their opinion or disposed
to join in the popular cry against us;
and that from the present appearance of things, such seemed to be the temper of many,
that no measures however disadvantageous to us, could be offered to either house,
which would not at least meet with a strenuous support.

Nevertheless that he and a few more from a thorough knowledge and
approbation of our principles and conduct in divers particulars;
and from a consideration of the injustice it would be,
to exclude those from any share in the legislature of a province,
who had so highly contributed to its present value and reputation,
were desirous that we ourselves if possible, should apply a remedy,
rather than leave it to be done by the public, who from the disposition they were in,
seemed inclined to the severest;
a clause for totally excluding our friends in Pennsylvania and other parts of America,
from having seats in any provincial assembly, by imposing an oath,
having actually been part of a bill now before parliament,
that as the majority of the present assembly were of our profession,
who from their known principles could not contribute to the defence of the country,
now grievously harassed by the Indians under French influence,
in a manner that most people here, and even many in Pennsylvania, thought necessary;
it seemed but common justice in our friends to decline accepting a trust,
which under the present circumstances they could not discharge;
and therefore advised that we should use our utmost endeavours to prevail upon them,
neither to offer themselves as candidates, nor accept of seats in the assembly,
during the present commotions in America.

That if we could give any reasonable hopes this advice would be complied with,
he for one would endeavour to prevent any violent
measures from being taken at the present.

But, that as much depended on this compliance,
he earnestly recommended we should not trust to letters only,
or the most pressing advice,
but that even some proper persons should be deputed to go over on this occasion.

For should any disaster befall the province,
and our friends continue to fill the assembly,
it would redound to the prejudice of the society in general, and be the means, perhaps,
of subverting a constitution under which the province had so happily flourished.

He farther recommended it to us,
to wait upon some other principal persons in high stations,
and endeavour to prevail upon them to join in suspending the resolutions which
might have been formed either for a present or total exclusion.

In consequence of these conferences and the foregoing report,
a letter was drawn up by the meeting for sufferings in London,
addressed to friends of the quarterly meeting of Philadelphia,
and other quarterly meetings in Pennsylvania; as the subject was of great consequence,
not only to the ease and safety of friends there,
but to rescue the society at large from the impressions,
which malignant abuse had exerted itself to fix unjustly on its reputation,
and as the yearly meeting of London was at hand,
it was thought expedient to communicate the said letter and the occasion thereof,
and the minutes of their meeting to the said yearly meeting,
that they might be strengthened by the concurrence
and approbation of the body in their collective capacity.
The minutes and proceedings of the meeting for sufferings
on American affairs were fully approved;
with a recommendation to them,
to continue their care and assistance therein as occasion might require;
and likewise to use their endeavours to procure two suitable friends to go over,
in pursuance of the advice given them.
The draught of the letter was also read in the yearly meeting, and approved.

Two friends being found,
who from a persuasion of duty were willing to cross the seas on this occasion,
and in the estimation of their brethren were well qualified for the service,
each of them having travelled through the province on religious visits
and were generally well known and esteemed by their brethren there,
viz. John Hunt of London, and Christopher Wilson of Cumberland;
they accordingly embarked and arrived at Philadelphia,
in the early part of the tenth month this year,
meeting with a cordial reception from friends of that city,
and had conferences with such of them as were nominated by their late yearly
meeting to compose a part of the meeting for sufferings agreed to be established,
to whom they imparted the nature of the interesting
business upon which they had come over,
when they soon perceived it so uniformly coincided with
the sense and judgment of the friends in those provinces,
that several months previous to their arrival,
six representatives in the assembly of Pennsylvania
who were members of the society called Quakers,
desirous to preserve a conduct consistent with their peaceable principles,
and from a conviction of judgment against complying with
the military requisitions warmly urged on the legislature,
had of their own accord applied to the house for liberty, to vacate their seats;
and after consideration of the reasons they offered for such a measure,
their request was granted, a new election ordered,
and other persons not of their religious profession were chosen to supply their places;
others also of the same society at the close of the session of this year,
refused to be continued in that station.
See page 511, Appendix, No. I.

William Denny, being commissioned to succeed Robert Hunter Morris,
as lieutenant governor of Pennsylvania and us territories, arrived in Philadelphia,
in the 8th month,^
footnote:[Previous to his leaving London,
a committee of the meeting for sufferings there was deputed to wait on him (as had been
usual on the like occasion) and request his favourable regard to friends in that province,
and he gave assurance of his amicable disposition towards them.]
which raised the hopes of the people,
that the proprietaries seeing the ill effects of the controversies which had
subsisted were become disposed to remove the cause of their continuance;
but it was soon found they had changed their deputy only, and not their measures;
in which the assembly was so confirmed by the governor`'s first speech on public business,
that they requested him to lay before the house full copies of such instructions
given him by the proprietaries as related to money bills of any kind,
with the preambles or other parts that contained the reasons of such instructions,
with which request he complied,
and they evinced rather an increase than a relaxation
of the restrictions heretofore given;
and the governor having made a demand of money for the defence of the province,
the house framed a bill for granting for the king`'s use, sixty thousand pounds,
to be raised by an excise on spirituous liquors,
which was presented to the governor for his assent who after making
many objections which occasioned some altercations between them,
he at length absolutely refused to enact,
whereupon the house appointed a committee to prepare a reply to his objections,
on consideration of whose report it was-- Resolved--that
the said proprietary instructions are arbitrary,
and unjust; an infraction of the charter; a total subversion of the constitution,
and a manifest violation of their rights as freeborn subjects of England.^
footnote:[Votes of Assembly, vol. 4. page 360.]

The annual election of representatives through out the province for the present year,
having lately past,
and the day appointed by charter for their convening being near at hand,
conferences were obtained with those members called Quakers who had been re-elected,
in consequence of which four of them,
convinced of the propriety of the proceedings of our brethren in Great Britain,
agreed to decline taking their seats and the qualifications usually subscribed;
their reasons for which were set forth in a writing
directed to the speaker and house of assembly,
where their request was considered, and allowed,
a new election immediately ordered and four others of different
religious denominations legally chosen in their stead;
so that now of thirty six members of which the whole house consisted,
there were not more than twelve under the character of Quakers,
and divers of them were not acknowledged members of that society.

The several quarterly meetings in the provinces, appointed their representatives,
pursuant to the directions of the late yearly meeting,
and the first meeting for sufferings for Pennsylvania, and New-Jersey,
was held in Philadelphia, the 11th of the 12th month of this year;
at which the before mentioned deputies from friends in England,
attending laid before the meeting several papers
and two letters they had brought with them,
relating to the business of their deputation.

The inimical disposition which had been so earnestly and
undeservedly raised against friends in Pennsylvanian,
manifested itself not only in endeavours to deprive
them of their power and influence there,
but extended itself into the government of the three lower counties on Delaware,
where the militia-law had been enacted,
and was executed with great rigour and-oppression on the members of this society,
by such exorbitant exactions that in some instances
they amounted to tenfold the sum imposed by law,
which rendered it necessary to represent the grievance
to the governor by an address on the occasion.

The proprietaries and their adherents had gained little or nothing by
their exertions to remove the Quakers (so called) out the provincial assembly,
for their successors opposed them and their measures, even more vehemently,
so that by this time dissensions between them had risen to a very serious height;
the assembly having come to a resolution to send an agent to London,
to remonstrate to the government there against the
proprietaries instructions to their governors,
which were apprehended to be subversive of the essential rights of the people.
In this circumstance the people called Quakers,
though much misrepresented by aspersions and groundless surmises to the proprietors,
who were too easily prejudiced thereby, in conformity to their pacific principles,
thought it their duty to caution their friends against mixing with the contending parties,
so as to suffer their minds to be agitated with the prevailing heats and animosities.
The meeting for sufferings also appointed a committee to
labour to promote an amicable adjustment of their differences.
A conduct highly becoming their christian profession in endeavouring to do good for evil,
and very different from the malevolent party spirit of their adversaries.

Notwithstanding which,
friends thought they had still reason to complain of the
averseness of the proprietaries to attend to their remonstrance;
and in their opinion to their own true interests, as well as those of the people,
in not using seasonable endeavours to check the encroachments
on the fundamental principles of their constitution;
and that they declined to return a satisfactory answer to their address,
and were quite silent as to their resolution of preserving to the
provincials their fundamental privilege of liberty of conscience:
the answer they returned appeared merely evasive,
and designed to avoid a plain and candid reply to their request.
These proprietaries instead of imitating the example of their honourable father,
in studying the welfare of the people,
and cultivating a good understanding with and amongst them,
by just and generous measures, seem rather after the example of too many in power,
to use the power they were invested with to grasp at more,
without a due consideration of the obligation they were under to those men, who,
by the equity of their administration, their industry,
and their virtue had principally contributed to the late prosperous state of the province,
whereby the value of their estate was greatly increased.

The principal subject of misunderstanding between
the present assembly and the proprietary governors,
was concerning the public taxation.
The latter in their speeches were continually urging
the assembly to raise money for military preparations,
and building forts for the defence of the province,
which the present assembly or the majority of them,
having no conscientious scruple against, were not averse to grant;
and in order to raise an adequate sum, had recourse to a land tax,
and in drawing up the bills they taxed the proprietary estate,
as thinking it reasonable that they who had the greatest property to be defended,
should bear their share of the charge.
The governor therefore in pursuance of his instructions,
whereby the proprietaries claimed an exemption from the tax,
and also a controlling power in the disposing of the money raised,
refused his assent to the money bills.
Both sides persevered in supporting their contradictory sentiment, without yielding;
mutual accusations, and remonstrances widened the breach;
the frontier settlements still remained exposed to the incursions of the Indians,
and the people were divided in attachment to one side or the other,
hence arose those party beats and animosities,
which this society were concerned to caution their members against intermeddling in.

The assembly of Pennsylvania at the same time having under
consideration a law for establishing a militia in that province,
the meeting for sufferings at Philadelphia interposed in behalf of friends,
by an address to the assembly, in which they again recite the 35th section of laws,
and the first clause of the charter of privileges,
whereby it appears that laws requiring under pains and penalties,
services of friends incompatible with their well-known christian principles,
are direct infractions of that religious liberty
which was the most essential condition of settlement;
and therefore they request that the assembly would make such provision
therein that the liberty of conscience heretofore enjoyed,
and so solemnly and repeatedly granted by the charter
may not in any respect be infringed or violated.
