== Chapter XIV. Pennsylvania continued.

[.chapter-synopsis]
* A Proclamation published for a public Fast
* Reasons for not observing it
* Necessity for a Reconciliation with the Indians not early enough attended to
* Subscription and Association for preserving Peace with them
* Government of Pennsylvania treat with the Indians, at Easton
* Some Friends think it best to attend though discouraged by the Governor
* Trustees of the Friendly Association address the Governor in defence of their Conduct
* The Governor transmits to England a Report of a Committee, which casts the Blame on Friends.
* An intended Theatre prohibited by the Assembly

In the sixth month, this year, a proclamation was published,
appointing a day to be observed a public fast,
a manifest evidence that the people called Quakers had little influence in the government;
yet being still disposed both to avoid occasions of just offence,
or decline complying with the ordinances of the present rulers without rendering a reason,
and to inform the public in general concerning their
principle respecting ordinances of this nature,
a committee by appointment of the meeting for sufferings had a
conference with the governor and the mayor of the city,
to whom they gave their reasons for not complying with observations enjoined human authority.
That meeting also published an apology in justification of the practice of friends,
and in support of their christian testimony against complying with
human injunctions in matters relative to the worship of God,
viz.

[.embedded-content-document]
--

[.blurb]
=== An Apology for the People called Quakers, containing some Reasons, for their not complying with human Injunctions and Institutions in Matters relative to the Worship of God.

It is well known that the province of Pennsylvania
was first settled by a number of pious,
sober and substantial people (mostly) members of the religious society called Quakers,
who had many years suffered grievous persecutions in their native country,
for their faithful conscientious testimony against complying with human
institutions and injunctions in matters of faith and worship.

That by their patience and meekness in sufferings, and their integrity,
sobriety and honesty in the course of their conduct,
they clearly approved themselves to be the sincere followers and disciples of Christ,
and were by royal authority entrusted with many valuable and extensive rights and privileges,
to be enjoyed with the property they had purchased in the soil of the province,
which induced them, without any expense to the government, to cross the seas,
and settle and improve it, though at that time a wilderness;
and by the 35th section of the first laws made under the royal charter,
the most clear and determinate assurance was made to them and their successors,
that "`as long as they lived peaceably and justly under the civil government,
they should in no ways be molested or prejudiced for their religious persuasion or practice,
nor be compelled at any time to frequent or maintain any religious worship,
place or ministry contrary to their religious persuasion.`"
These privileges were confirmed by our worthy first proprietor William Penn,
by the 8th article of the present charter of privileges granted by him in these words.
"`But because the happiness of mankind depends so
much upon the enjoyment of liberty of their consciences,
as aforesaid, I do hereby solemnly declare, promise and grant for me,
my heirs and assigns,
that the first article of this charter relating to liberty of conscience,
and every part and clause therein, according to the true intent and meaning therfeof,
shall be kept and remain without any alteration inviolably forever.`"

From the first settlement of this province, till within a few years past,
the administration of the laws was committed chiefly
to men of the same principles with the first settlers,
and by the divine blessing on their religious concern for
the present and future prosperity and happiness of the people,
virtue and true religion were promoted and encouraged,
vice and irreligion were discouraged, peace,
tranquillity and plenty remained in the land;
and the enjoyment of religious and civil liberty was inviolably preserved.

We profess,
and acknowledge the same religious principles our predecessors published to the world,
and since by the permission of infinite wisdom,
the peace of this province hath been interrupted,
and the desolating calamities of war experienced by our
distressed fellow subjects on the frontier settlements,
we have been affectionately concerned in true sympathy,
freely contributed towards their relief and often been engaged both in public and private,
to put up our supplications to Almighty God on their behalf;
and by the constant tenor of our conduct, manifested that to fear God, honour the king,
and promote peace and piety among men are acknowledged by us indispensable duties;
yet ever since we were a people we have had a testimony against mere formality
and human injunctions in matters of religion and the worship of God;
and being taught by the precepts of our Lord Jesus Christ,
the testimonies of his Apostles, and our own experience,
that the worship and prayer which God will accept,
can only be performed and offered by the immediate assistance of the Holy Spirit;
we are conscientiously concerned to maintain our religious
dissent from formal and ceremonious injunctions;
by which set forms or times are appointed in man`'s will for divine worship,
"`For though the Jews in the first covenant had many fasts and feasts, and holy days,
as the feasts of the new moon, and passover, and feasts of unleavened bread, Pentecost,
the feasts of tabernacles, and the feasts of dedication,
which are largely showed in the books of Moses,`" yet even in that time
when the observation of fasts and appointed days was thus enjoined,
the Lord by the prophet declared, he was weary to bear their appointed feasts,
that their solemn meeting was iniquity,
because for want of a proper disposition of heart to seek and serve him,
their hearts remained polluted.
"`Ye shall not fast as ye do this day, to make your voice to be heard on high.
Is it such a fast that I have chosen, a day for a man to afflict his soul?
Is it to bow down his head as a bulrush, and to spread sackcloth and ashes under him?
Wilt thou call this a fast and an acceptable day to the Lord?
Is not this the fast that I have chosen, to loose the bands of wickedness,
to undo the heavy burdens, and to let the oppressed go free,
and that ye break every yoke?
Is it not to deal thy bread to the hungry,
and that thou bring the poor that are cast out, to thy house; when thou seest the naked,
that thou cover him, and that thou hide not thyself from thine own flesh,
then shalt thou call, and the Lord shall answer; thou shalt cry, and he shall say,
here I am.`"
From which it appears that even when public fasts were observed by divine appointment,
yet the Lord declared his disapprobation of them,
when the observers thereof did not manifest their sincerity
by suitable fruits of repentance and amendment of life.
But we dare not comply with injunctions of that kind,
as the dispensation in which those outward observations were enjoined, is now ceased.
Christ our holy head and high priest,
who is the substance of that which was pointed to and hoped for,
enjoins his followers the observance of a daily universal fast.
A fast from everything which has not a tendency to purify and perfect the soul,
and render it more and more fit to become the tabernacle of the Holy Ghost.
He positively requires of his disciples and followers, _that they deny themselves,
take up their cross and follow him, and that they watch and pray always,
that they may be accounted worthy to stand before him._
That in the primitive churches they saw an end of these shadows of things to come,
and were brought to him, the substance, in whom all figures and shadows do end,
is manifest from the repeated expressions of the apostle Paul,
"`For Christ is the end of the law for righteousness to everyone that believeth,`" Rom. 10:4.
"`But now hath he obtained a more excellent ministry,
by how much also he is the mediator of a better covenant,
which was established upon better promises.`" Heb. 8:6.
"`But now after that ye have known God, or rather are known of God,
how turn ye again to the weak and beggarly elements,
whereunto ye desire again to be in bondage.
Ye observe days and months and times and years, I am afraid of you,
lest I have bestowed upon you labour in vain.`" Gal. 4:9-11.
"`One man esteemeth one day above another;
another esteemeth every day alike.
He that regardeth the day, regardeth it unto the Lord, and he that regardeth not the day,
to the Lord he doth not regard it.
Let us not therefore judge one another any more, but judge this rather,
that no man put stumbling block, or an occasion to fall, in his brother`'s way.`" Rom. 14:5-6,13.
"`Let no man therefore judge you in meat or drink,
or in respect of an holy-day, or of the new moon, or of the sabbath days,
which are a shadow of things to come, but the body is of Christ.`" Col. 2:16-17.
And we apprehend that the practice and
testimony of our forefathers is truly consistent therewith,
as will appear on a perusal of their writings,
and particularly those of our worthy friends William Penn and Robert Barclay.

We cannot, in conscience to God,
observe holy days (so called) the public fasts and feasts,
because of their human institution and ordination, and that they have no divine warrant,
but are appointed in the will of man.`"
Even as we have suffered much in our native country,
because we neither could ourselves bear arms nor send others in our place,
nor give our money for the buying of drums, standards, and other military attire;
and lastly, because we could not hold our doors, windows, and shops,
close for conscience sake, upon such days as fasts and prayers were appointed,
for to desire a blessing upon, and success for the arms of the kingdom or commonwealth,
under which we live,
neither give thanks for the victories acquired by the effusion of much blood,
by which forcing of the conscience, they would have constrained our brethren,
living in divers kingdoms, at war together,
to have implored our God for contrary and contradictory things,
and consequently impossible; for it is impossible, that two parties fighting together,
should both obtain the victory; and because we cannot concur with them in this confusion,
therefore we are subject to persecution.
Yea and others, who with us do witness, that the use of arms is unlawful to christians,
do look asquint upon us:
but which of us two do most faithfully observe this testimony against arms?
either they, who at certain times at the magistrates order,
do close up their shops and houses, and meet in their assemblies,
praying for the prosperity of their arms, or giving thanks for some victory or other,
whereby they make themselves like to those that approve wars and fighting: or we,
which cannot do these things for the same cause of conscience,
lest we should destroy by our works, what we establish in words?
we shall leave to the judgment of all prudent men.

And as we can appeal to the searcher of hearts that our testimony
herein proceeds from inward conviction and a principle of conscience,
and not from perverseness, obstinacy or disrespect to our superiors,
we hope the most charitable and christian construction will be put upon our conduct,
in thus dissenting from the practice of other professors of Christianity:
for though we think ourselves well warranted in adhering to the
precepts of our Lord Jesus Christ who enjoined his followers,
that _when they fasted they should not appear unto men to fast,
but unto their Father who seeth in secret;_
nevertheless it is far from us to censure or condemn such who sincerely
esteem it their duty to observe in humility of soul,
days and times of fasting and prayer.
Our intention and desire is to preserve our privileges both religious and civil,
and to maintain that liberty of conscience we are entitled to by the laws of this province.
Conscience is God`'s prerogative, he is the supreme Lord, Judge,
and William Penn`'s Guide thereof.
"`Nor are we so ignorant as to think it is within the reach of human power
to fetter conscience or to restrain its liberty strictly taken;
but the plain English of liberty of conscience we would be understood to mean is this,
namely, the free and uninterrupted exercise of our consciences in that way of worship,
we are most clearly persuaded God requires us to serve him in (without endangering
our undoubted birthright of English freedom) which being matter of faith,
we sin if we omit, and they cannot do less, that shall endeavour it.`"

We have ever believed that it is by the light or gift of God that
all true knowledge in things spiritual is received and revealed,
and as the same is manifested and received in the heart,
by the strength and power thereof, all true believers, in Christ,
come to the clear and distinct knowledge of their duty;
and will be taught thereby when to fast, and what to pray for as they ought:
and as prayer is the most awful and solemn part of religious worship,
we esteem it our duty to wait for divine light and understanding,
that we may know the will of God, otherwise we may ask amiss and not receive,
and by offering the sacrifice of fools, do evil.

The most eminent and experienced christians declared, they,
_knew not how to pray or what to pray for as they ought,
but as the spirit itself helped their infirmities with sighs and groanings, etc.
And they were to pray with the spirit and with the understanding,_
surely then not in the will of man, nor because he appoints?
Everything we pray for should be in the name or power of Jesus,
and according to the will of God,
who knows best what is most proper and convenient for us,
and will tend most to his glory and the good of his creatures.
And who can say that adversity and afflictions may not be productive of real good,
and a means of bringing many to seek the Lord,
who in a time of ease and prosperity forgot and departed from him.
For we have great reason to acknowledge that the
just judgments of the Lord are now in the land,
and that there is cause for deep penitential humility and mourning before him,
that these judgments may be removed from us;
and if the people will make a right improvement of them,
and every particular person reform one,
as it is in the power of everyone under the operation
and influence of divine grace to do;
this will be an acceptable fast to the Lord: to fast from pride, strife, contention,
unnatural heats, broils, animosities, blood; from luxury, wantonness, revellings,
drunkenness, profaneness, impiety, covetousness, deceit, fraud, infidelity,
and all manner of evil;
then might we have some well grounded reason to hope that the scourge
which hangs over us will in due time be removed and we again be
favoured with days of peace and tranquillity.

There are some yet living in this country,
who are witnesses that so long as the people lived in the fear of God,
walked in humility before him, and kept his holy law and commandments,
it went well with them and with their children; the land rejoiced,
the blessing of the Most High was known,
and his powerful and protecting providence remarkably conspicuous;
for though we had no outward barrier,
the sword was not permitted to enter within our border,
but the salvation of the Lord was a defence round about:
but now blood has been spilled and the land is polluted therewith,
and the sound of war is heard.
Oh! that the inhabitants may consider these things and lay them to heart,
before it be too late, and cry mightily to the Lord our God,
turning to him with all our hearts and imploring his assistance, who,
if our ways please him,
can arise for our deliverance and cause our enemies to be at peace with us.

[.signed-section-context-close]
Signed on behalf and by appointment of our said meeting for sufferings,
held at Philadelphia, the 29th of the 6th month, 1757, by

[.signed-section-signature]
James Pemberton, Clerk.

--

But although the members of this society could not
consistently join in observing such a fast,
they were sensibly affected on account of the calamitous state of the province,
and the general disregard to religion and rectitude
of conduct prevailing amongst the inhabitants,
which they considered as the principal cause thereof;
and notwithstanding they were now mostly excluded
from places of trust or power in the government,
and by their christian principles averse to the shedding of blood;
yet they exerted themselves from the first, not without some degree of success,
to bring about a reconciliation with the natives,
in a manner consistent with their principles.
Soon after the first invasion of the frontiers of
Virginia by the Indians in the French interest,
divers of this religious society were led to turn their thoughts
to those Indians who had been their old friends and neighbours,
and to consider whether they and the government had fully
demeaned themselves towards them with fidelity and justice.
A little reflection convinced them there had been a deficiency.
Some in their private capacity were willing to promote a good understanding with them,
by giving them a testimony of their friendly regard:
others of them used endeavours to prevail with the government (as
more effectual) to enter into conciliating measures with them;
but the proposal was not duly regarded,
till the distressed state of the province brought many to more serious considerations,
and convinced them that such measures were expedient and even necessary.

The friends who were principally active in promoting these measures,
informed the ensuing yearly meeting of their proceedings, which were approved,
and friends in general recommended to assist in promoting so good and necessary an undertaking:
but this being business of a civil nature,
the meeting did not think it properly belonged to them, as a religious body,
to interfere further therein.
Many friends and others promoted a friendly association for raising and applying
a sum of money for forwarding and preserving a peace with the Indians,
a liberal subscription being made by them the application whereof,
produced a salutary effect.^
footnote:[ The friendly association was first promoted in the 11th month, 1756,
and continued to the 19th of 4th month, 1763;
during which time committees were annually elected by the subscribers,
who met on the 19th of 4th month, in each year,
to receive from the said committee an account of their transactions,
and expenditure of the money raised,
which amounted to 4004£. 1s. 6d. which was chiefly laid out in presents to the Indians
and delivered to them at the public treaties either by the governors of the province,
Morris and Denny, on behalf of the subscribers,
or by the permission or knowledge of the said governors,
as well to conciliate the minds of the Indians as to encourage
them to seek out and release the captives remaining among them.
430£. part of the above sum was contributed by the Menonists,
who entrusted it to the care of the said association,
and besides the above contributions the sum of 236£.
14s. was raised by a number of other religious Germans,
called Swingfielders which they directed to be applied
for the particular purpose of the redemption of captives.
{footnote-paragraph-split}
In 1764,
another subscription was set on foot by the people called Quakers,
and 266£. 10s. raised and applied for the relief of the frontier
inhabitants distressed by the incursions of the Indians.
{footnote-paragraph-split}
Note, these sums are supposed to be in Pennsylvania currency.]

In the 7th month (commonly called July) this year a treaty was opened between
the government of Pennsylvania and the neighbouring Indians at Easton,
in Northampton county.^
footnote:[At this place two treaties had been held in the preceding year 1756.
One of them in the 7th month by governor Morris,
preparatory to the other in the 11th month by governor Denny:
when some captives were brought in and restored to their connections:
which treaties appear to have been promoted by a conference
had between some of the people called Quakers in Philadelphia,
and a few Indians who were occasionally in that city, in the 4th month preceding;
and also through the mediation of Sir William Johnson,
the king`'s agent in Indian affairs.
The subsequent treaties in the year 1758 were also held at Easton, at the last of which,
a general peace was settled on the 23d of October, 1758,
for Pennsylvania and all the other provinces.
Francis Bernard, governor of New Jersey, acting on behalf of that colony.
The disputes respecting their claims unsatisfied
for lands having been at the preceding treaty,
in the month called May, by mutual consent referred to the king of England.]
And several friends proposing to attend the treaty
to forward the desirable work of peace,
the governor declared his disapprobation of their attendance at the treaty,
or distinguishing themselves by giving the Indians any presents.
Whereupon friends held several conferences as to the measures they should pursue;
the result whereof was,
that as mutual tokens of the revival of ancient friendship had passed
between them and the Indians with a view to promote a general peace,
it might now be of bad consequence to decline,
or neglect attending on this important occasion.
In consequence of this determination,
several friends from Philadelphia proceeded on their
journey to Easton and attended the treaty.

In the afternoon of the same day that they arrived there,
the Indians with Teedyuscung their king or chief waited on the governor,
and signified the sincerity of their intentions to promote the good work of peace;
when he desired that as things had heretofore been misunderstood or forgotten,
he might have the liberty to choose a clerk to take
minutes of the transactions of the treaty,
which request being twice evaded, it gave the Indians considerable uneasiness,
as apprehending treacherous dealing; but by the interposition of friends in,
conferring with them, and making them a small present they were pacified.
At the next meeting the governor consented to allow them a clerk,
and they proceeded to the business of the treaty.
The first demand Teedyuscung made was that of satisfaction
for the injury a messenger of theirs had received,
who, being sent on a message to the remote Indians,
in his return was shot by one of the provincials,
and at this time lay dangerously ill of the wound.
The satisfaction he demanded was, that if the wounded man should die,
the aggressor should be tried by the laws of the colony and suffer death in like manner.^
footnote:[Offering also to renew the annual compact,
that if any of their people should commit the like crime the criminal should
be delivered up to be tried by the laws of the colony and suffer death.]
This demand and proposal seemed not well relished by some persons,
who wished rather to retard peace than to forward it:
the next day there was no public treaty; all things seemed to be in confusion;
during which time friends kept quiet,
waiting for opportunities wherein they might hope
to be more successful in their well meant endeavours,
being very earnest to procure peace for the province,
and to pursue the most effectual means for obtaining security to the frontier settlements.

But deep rooted prejudice possessed the minds of many,
who manifested such bitterness and envy to the whole society, that,
their measures were thwarted, their laudable undertakings misrepresented,
and their characters aspersed;
very unjust charges and insinuations were propagated
against friends for their conduct in Indian affairs,
as treacherously taking their part in a manner hostile to the interest of the province.

Upon this occasion the friends concerned Trustees thought it necessary in their own
justification to explain and vindicate their conduct in an address to their governor,
William Denny, Esq.
which is placed in the appendix, No. 2.

What impression this address made on the governor I am not informed,
but if a favourable one,
he and his coadjutors suffered their minds afterwards
to be biased by popular rumours and party;
for in the beginning of the year 1759,
the said governor and his council transmitted to
England a report of a committee by them appointed,
to inquire into the dissatisfaction and claims upon the Indians,
containing insinuations and charges calculated to
asperse the society of the people called Quakers,
and committee injure their reputation with the British government.
The meeting for sufferings there coming to the knowledge hereof,
applied to the governor and council by two successive addresses,
for a copy of said report, and received an evasive answer to the first,
and to the second a positive refusal, which carries the appearance of a secret design,
not only to stigmatize them, but to procure credit to the report as undeniable,
by depriving them of the means of vindicating their conduct or of refuting most probably,
a partial and misstated representation of fact.
See Appendix, No. III.

I find in a letter from the meeting for sufferings at Philadelphia to that in London,
bearing date the 25th of 3rd month, 1760,
a reference to a future treaty to be held the ensuing summer as followeth,
"`It will be a great advantage to the public, and afford real satisfaction to us,
to find at the general treaty, which is expected to be held with the Indians next summer,
that the governor hath full power to terminate the controversies,
which are subsisting respecting their lands in the northern parts of Pennsylvania.
Until this is done the release of some hundreds of
our fellow-subjects who remain in captivity,
can hardly be expected to be obtained.
The pacific measures, which, through much difficulty have been pursued;
being blessed with happy effects,
the friends immediately concerned therein are encouraged to continue their endeavours.
And it appearing to them necessary at this time to
address the proprietaries of that province,
we hope,
the account they are able to give of their first
motives to engage in that important business,
and their proceedings therein to the present time,
will tend to remove some of those prejudices, which have heretofore prevailed,
and engage a favourable attention to the important subjects of reestablishing
peace on the principles of justice and equity.`" It being their opinion and,
they think must be that of all men, who are open to conviction,
that peace with the natives which the circumstances of the colonies indispensably
required was to be restored and preserved only by pacific measures.

The foregoing quotation seems to elucidate the before mentioned report, of the committee,
as to their reasons for reflecting on the proceedings of friends in Indian affairs;
it may be presumed from thence that the Indians conceived
they had been injured by the proprietaries or their agents,
by encroachments on their lands without their consent,
or without an equivalent (contrary to the practice of the first settlers) and
probably the members of the friendly association thought they had reason to complain,
and might give their opinion in favour of a compensation
to the natives for the injuries done them,
as most consistent with the principles of Christianity and justice,
and most eligible in the present disposition of the Indians to
enter into an amicable discussion of the grounds of their discontent,
which might be interpreted by this committee a strengthening
of the Indian cause against the proprietary interest.
And from political motives might be represented to the English government in terms to
carry the appearance of being contrary to the interests of the mother country also.

Thus Pennsylvania which for a series of years from its first settlement,
had been remarkably distinguished for the public and private virtues;
the mutual benevolence; sobriety and industry of its inhabitants;
was now disturbed and its peace destroyed by party dissensions and mutual distrusts.
And now also the simplicity of manners, which had been the ornament of the state,
the safe-guard of its virtue, and the foundation of its prosperity,
was in danger of being subverted;
for an attempt was made in imitation of the states and populous cities of Europe,
to introduce into Philadelphia the refinements of voluptuousness,
and a taste for sensual gratifications, by erecting a theatre for exhibiting stageplays;
entertainments which the people called Quakers (as well as the
most sober and considerate part of other religious societies) have
ever deemed incompatible with the principles of Christianity,
the tenour of the doctrines of the gospel and the practice
of the best men in the earliest ages of the christian church.
The address the members of this society in Philadelphia thought
it their duty to bear their testimony against this pernicious attempt,
by an address to the general tended assembly,
requesting the interposition of their authority to prevent the introduction of them;
in which they were at this time so successful that a law
was passed prohibiting such corrupting entertainments.
