== Appendix to Chapter XII. XIII. XIV.

[.blurb]
=== No. I. Extract of a Letter from the Meeting for Sufferings in Philadelphia.

[.blurb]
=== No. II. A summary Account of the Occurrences with Governor Denny, on the Approach of the Treaty at Easton, in the seventh Month, 1757.

[.blurb]
=== No. III. Abstract from the Report of the Committee of Council, appointed to inquire into the Complaints of the Indians at the Treaty at Easton, 8th of November, 1756.

=== No. I. Extract of a Letter to the Meeting for Sufferings in London, from the Meeting for Sufferings in Philadelphia--Twelfth Month, 1756.

Our friends John Hunt and C. Wilson by their long passage being
prevented of seeing friends together at our yearly meeting,
and the anniversary of the election of the members of assembly for the province of Pennsylvania,
being also over,
on their arrival they communicated your epistles and minutes
to those of us who were nominated at the yearly meeting,
and though our meeting was not then fully constituted,
the manner in which you had proceeded in the consideration of our affairs,
and the engagements you had entered into on behalf of friends here,
so evidently appeared to be conducted with a real regard to our true interest,
and so perfectly consistent with our sentiments,
that they were encouraged and assisted by those members of this meeting
in doing everything in their power to render the service proposed effectual,
in order to which,
those of our society who were chosen representatives in the several counties,
were requested to give them an opportunity of a conference
before the usual time of meeting in the assembly,
which was readily complied with by all whom there
was at that time any prospect of prevailing with,
to regard the advice and concern of their brethren, and in consequence of it,
four of them declined taking their seats in the house,
and others not of our profession were soon after chosen in their stead,
so that there are now but twelve of the members of the assembly
who make any pretensions of being called by our name,
and several of these are not acknowledged by us as members of the society;
it would have been matter of real satisfaction to us,
to have been able to prevail with every one of them to decline serving in the legislature,
during the present circumstances of our affairs, but this could not be obtained,
as they do not appear to be convinced it would be for the public interest,
for as six of the friends who were chosen into the
assembly last year had resigned their feats,
and some others since refused to be re-elected,
those who now remain say they should not think themselves excusable to their constituents,
if they should decline the service, but we think it may be truly said,
they were most of them so clear of intermeddling in the elections,
and so many friends declined attending or voting in several of the counties,
that they appear to be chosen by a majority of people not of our profession,
many of whom are very apprehensive of danger from permitting those,
who have been endeavouring to subvert the constitution,
to have any considerable share in the legislature.

Some of us were witnesses of the circumspection and prudence,
with which our dear friends John and Christopher performed this weighty service;
and this meeting having now received from them your epistle and minutes,
with some account of their proceedings then and since
at several quarterly meetings in Pennsylvania,
it is our duty to inform you, that we have full unity with them, being assured,
they have steadily proceeded with a single eye to the exaltation of truth,
and the promoting the peace and prosperity of the church.
