[short="Appendices"]
== Appendices to Chapters XII, XIII, and XIV.

[.chapter-synopsis]
* No. I. Extract of a Letter from the Meeting for Sufferings in Philadelphia.
* No. II. A summary Account of the Occurrences with Governor Denny, on the Approach of the Treaty at Easton, in the seventh Month, 1757.
* No. III. Abstract from the Report of the Committee of Council, appointed to inquire into the Complaints of the Indians at the Treaty at Easton, 8th of November, 1756.

[.old-style]
=== Appendix No. I. / Extract of a Letter to the Meeting for Sufferings in London, from the Meeting for Sufferings in Philadelphia, Twelfth Month, 1756.

Our friends John Hunt and C. Wilson by their long passage being
prevented of seeing friends together at our yearly meeting,
and the anniversary of the election of the members of assembly for the province of Pennsylvania,
being also over,
on their arrival they communicated your epistles and minutes
to those of us who were nominated at the yearly meeting,
and though our meeting was not then fully constituted,
the manner in which you had proceeded in the consideration of our affairs,
and the engagements you had entered into on behalf of friends here,
so evidently appeared to be conducted with a real regard to our true interest,
and so perfectly consistent with our sentiments,
that they were encouraged and assisted by those members of this meeting
in doing everything in their power to render the service proposed effectual,
in order to which,
those of our society who were chosen representatives in the several counties,
were requested to give them an opportunity of a conference
before the usual time of meeting in the assembly,
which was readily complied with by all whom there
was at that time any prospect of prevailing with,
to regard the advice and concern of their brethren, and in consequence of it,
four of them declined taking their seats in the house,
and others not of our profession were soon after chosen in their stead,
so that there are now but twelve of the members of the assembly
who make any pretensions of being called by our name,
and several of these are not acknowledged by us as members of the society;
it would have been matter of real satisfaction to us,
to have been able to prevail with everyone of them to decline serving in the legislature,
during the present circumstances of our affairs, but this could not be obtained,
as they do not appear to be convinced it would be for the public interest,
for as six of the friends who were chosen into the
assembly last year had resigned their seats,
and some others since refused to be re-elected,
those who now remain say they should not think themselves excusable to their constituents,
if they should decline the service, but we think it may be truly said,
they were most of them so clear of intermeddling in the elections,
and so many friends declined attending or voting in several of the counties,
that they appear to be chosen by a majority of people not of our profession,
many of whom are very apprehensive of danger from permitting those,
who have been endeavouring to subvert the constitution,
to have any considerable share in the legislature.

Some of us were witnesses of the circumspection and prudence,
with which our dear friends John and Christopher performed this weighty service;
and this meeting having now received from them your epistle and minutes,
with some account of their proceedings then and since
at several quarterly meetings in Pennsylvania,
it is our duty to inform you, that we have full unity with them, being assured,
they have steadily proceeded with a single eye to the exaltation of truth,
and the promoting the peace and prosperity of the church.

[.old-style]
=== Appendix No. II. / A summary Account of the Occurrences with Governor Denny on the Approach of the Treaty at Easton, in the 7th Month, 1757.

Although the governor at the preceding treaty held at Easton,
had delivered to the Indians the presents provided for them by the people called
Quakers (as his predecessor had done on their behalf and in their name) and expressed
his satisfaction with the conduct and company of those who attended that treaty,
he now pleaded "`That the proprietaries had directed him not to suffer them,
or any other body,
or particular society in Pennsylvania, to concern themselves in any treaty with the Indians,
or on any pretence to suffer presents from such persons to be given to the Indians,
or to be joined with the public present in any such treaty.`" And he further says;
"`These directions I shall conform to,
and my regard for you as well as Mr. Penn`'s instructions lead me to observe,
it would be prudent in you to decline going in a body;
your attendance at treaties as a distinct society
having given great offence to the ministry.`"

Which answer occasioned the address of the trustees and treasurer of the friendly association,
as follows.

[.embedded-content-document.address]
--

[.letter-heading]
To William Denny, Esq.
Lieutenant Governor and Commander in Chief of the Province of Pennsylvania, etc.

[.blurb]
==== The Address of the Trustees and Treasurer of the Friendly Association, for regaining and preserving Peace with the Indians by Pacific Measures.

[.salutation]
Respectfully showeth,

That on consideration of the answer given by the governor to our offer
of contributing towards the expense of the ensuing treaty with the Indians,
we apprehend it to be necessary to lay before him a true state of the motives,
which induced us to use our endeavours to promote a reconciliation with them,
of the manner in which we proceeded before and since the governors arrival in this province,
and of some reasons we have for desiring to see that the grounds of their
complaints are carefully and impartially inquired into and considered,
and such measures pursued for satisfying them,
as the present melancholy circumstances of this province immediately require;
and we doubt not if the governor will be pleased to attend
to and impartially consider what we shall offer,
he will be fully convinced,
that our conduct hath been consistent with the profession
we make of acting on those principles,
of fearing God, honouring the king and promoting peace among men.
We therefore beg leave to inform the governor,
that soon after the first accounts were brought of the mischief done by the Indians,
on the frontiers of Virginia, some of the people called Quakers residing in Philadelphia,
seriously considering the fatal consequences of losing that
interest and friendship our predecessors had obtained by
their upright dealing and hospitable treatment of the Indians,
in the first settlement of this province; and apprehending the general neglect of them,
which had for some time been obvious, would terminate to the public disadvantage,
determined to improve every future opportunity of manifesting some regard to them;
and several companies of Indians,
of different tribes coming to this city on divers occasions,
they were visited by some of us, invited to our houses,
and on their going away presented with some small matters,
necessary for them in their way of living;
and the grateful manner in which they received these instances of regard,
and the lively remembrance they appeared to retain of the friendship which
subsisted between their ancestors and the first settlers of this province,
afforded us real satisfaction,
and some grounds to hope our good intentions would not be disappointed.

During the following winter the frequent melancholy accounts of the barbarous murders
committed by the Indians on the western and northern frontiers of this province,
filled the minds of people in general with a spirit
of indignation and resentment against them,
and no opportunity presented of publicly manifesting the earnest concern we had,
to use our utmost endeavours, a manner consistent with our peaceable principles,
to prevent the impending desolation;
the calamity became general and everyone was deeply interested
in the measures taken for inquiring into the causes which
induced our ancient steady friends to become our enemies:
yet this being the proper business of those then
concerned in the administration of the government,
we waited the event of their proceedings,
having just grounds to hope that the knowledge some of them had of several
matters which might probably have contributed to this unhappy rupture,^
footnote:[These were printed both in the gazettes and in their minutes.]
together with the repeated applications of the assembly of the province,
would have excited them to pursue every rational method of making such an inquiry,
and obtaining an amicable adjustment of all differences with these Indians,
and of thereby averting the melancholy consequences of continuing
to expose them immediately to the artifices of the French,
who would not fail to take advantage of our misunderstanding with them:
but the spring of another year returned,
and the public remained unacquainted with such measures being pursued:
great military preparations were indeed made and
forts erected in many parts of the frontiers,
but the desolation and distress of the province increased,
and the sanguine expectations of the people,
who had at first hoped by these means to defend themselves, were remarkably disappointed.
Governor Morris nevertheless,
determining to issue a declaration of war against the Delawares and Shawnese,
many of the people called Quakers residing in Philadelphia,
met together and presented an address to him,
earnestly beseeching "`that every measure which had been
pursued and whatever remained possible to be done,
to prevent so lamentable an extremity,
might be strictly and impartially reviewed and considered;
that full inquiry might be made,
whether some apprehensions these Indians had conceived of
a deviation from the integrity of conduct towards them,
conspicuous in the first establishment,
might not unhappily have contributed in some degree
to the alteration of their conduct towards us;
that full time might be allowed for those Indians, who remained well affected towards us,
to use and report the effect of their endeavours to reconcile our enemies to us,
and that by the governor`'s care, to guard against involving the innocent with the guilty,
such clear demonstrations of christian tenderness might be given,
as might tend to the engaging other neighbouring Indians
in the desirable work of restoring peace and tranquillity;
and at the same time offering,
though a much larger part of their estates should be necessary
than the heaviest taxes of a war could be expected to require,
by voluntarily grants cheerfully to contribute towards the obtaining peace in the same
manner as the unhappy experience of several of the most martial neighbouring colonies,
had after long and bloody wars, testified it must at last, if ever, be obtained.

Governor Morris was pleased to give a civil answer to this address;
but thought it necessary to proceed immediately to a declaration of war:
a few days after which,
some of us having the opportunity of a free conference with Conrad Weiser, who had,
as a provincial interpreter, been long concerned in public transactions with the Indians,
we were thereby confirmed in our apprehensions,
that some dissatisfaction respecting their lands,
had tended to the alienating their friendship from us;
and that he thought the only method, to save the province from ruin,
was to endeavour for a peace with them by pacific measures; and the next day,
a Delaware Indian from the Jerseys was sent to one of us,
with a letter from Conrad Weiser, recommending him as a person,
worthy of some notice from us and fit to be employed on a message to the Delawares,
when an opportunity of sending one could be obtained;
and there being at that time a number of the chiefs of the Six Nation Indians in town,
some of us thought it necessary to take some friendly notice of them;
but being determined to avoid giving any occasion of offence,
before we had any conversation with them, two of us waited on governor Morris,
and informed him, "`that as he had issued his declaration of war,
we thought it our duty to acquiesce therein, but,
as there were some friendly Indians in town,
we were disposed to take some notice of them,
and to endeavour by a friendly conversation to manifest
our good disposition towards them,
and engage their good offices on any occasion,
which might be improved for the public welfare; and we at the same time,
assured`" the governor if anything should occur which
had a prospect of tending to the public interest,
or might be worthy of his notice,
he should be fully acquainted therewith.`" The governor
expressed his approbation of our design,
and gave us full liberty to prosecute our intentions,
and the next day some of these Indian chiefs, with Conrad Weiser,
and Andrew Montour the provincial interpreters, and D. Claus,
general Johnson`'s secretary, dined at one of our houses; and after dinner,
had some conversation on the happy state of the first settlers of this province,
and the unhappy rupture which had lately happened.

The free and hearty acknowledgments of pleasure and gratitude from these Indians,
fully evidenced their good disposition towards us, and induced Conrad Weiser to declare,
he had not lately heard them express themselves with so much openness,
and he earnestly urged our improving this opportunity;
and in order to it he advised the calling together,
as many of our ancient men of the survivors of the first settlers as we could collect,
and to give the Indians another meeting,
in which the substance of that conversation might
be repeated and enforced on their minds,
by presenting them with a belt of wampum.
Governor Morris was immediately informed of what had passed,
and as there appeared some prospect of improving
this disposition of the Indians to the public benefit,
he was assured, that if he would advise and direct the manner of proceeding,
nothing more was desired by us,
than under his direction to proceed therein in such
a manner as would be most agreeable to him,
most effectually answer the purpose intended,
and demonstrate that we did not act from views of private advantage thereby:
and lest the differences then subsisting between him and the assembly,
about the raising money for the public services,
should discourage or retard his engaging therein, he was told,
that whatever sum of money should be wanting even to the
amount of 5000£. he should be immediately supplied with,
and by every part of our conduct, should find our hearty concern for the public welfare,
to be our principal motive.
Our purposes appearing acceptable to the governor,
about twenty of us with the same interpreters, had two conferences with the Indians,
and the most material parts of what they said,
were immediately communicated to the governor,
and the proposal of sending three messengers to the Delawares and Shawnese,^
footnote:[This was made by the Indian chief,
and the message to be from them to the Delawares, etc.]
being approved of by him, the necessary provision was made for their setting out,
and proper company provided for their safe conduct
through the improved part of the province;
and when they were ready to proceed on their journey,
the governor being waited on for the passes,
and requested to direct what signal they should give
on their return to distinguish them from enemies;
while the passes lay before him ready to be signed,
he suddenly appeared to change his intentions,
and signified his resolution to consult his council on the occasion.
The minutes of our conversation with these Indians being examined,
and signed by the three interpreters,
were immediately after this delivered to the governor; and his council being summoned,
we were informed they soon agreed, that as he had so lately declared war,
any offers of peace from him would be unreasonable,
and that the method first proposed of the messengers going with
such instructions as they had received from their own chiefs,
was most fit to be pursued.
The next day the Indian chiefs setting out in the stage-boat for New York,
after they were gone, the messengers refused to perform the service they had undertaken,
and the day following, the governor,
in consequence of some intelligence received from the governor of New York,
concluded to send the messengers in his own name.

To prevent any misrepresentations of our conduct,
as well as to engage the friendship of gentlemen from whom we hoped to receive
more hearty assistance than we had from those on whom we had hitherto depended,
copies of the minutes of our conversations with the Indians, and of their answers,
were immediately sent to the governor of New York and to general Johnson,
and an earnest application for their assistance,
in engaging the Indians of the Six Nations to promote the restoration of peace,
with an offer of cheerfully defraying the expense thereof.
Governor Hardy was so kind as to send such an answer,
as evidenced his hearty concern for the public welfare,
and laid us under sensible obligations;
and we never received the least hint from general Johnson,
of his disapprobation of any part of our conduct: therein: Under these circumstances,
we had reason to apprehend that our intention was approved of,
and the speedy return of the messengers with an agreeable answer,
confirmed us in a resolution to continue our endeavours
to engage as many of our fellow subjects as possible,
to concur with us therein.

The messengers being sent the second time,
on their return brought with them the Indian king Teedyuscung,
and some of his people to Easton;
and repeatedly informed us of the necessity of our personal attendance there,
and manifesting thereby, and by contributing towards the expenses of a suitable present,
the sincerity of our professions of regard to them,
and they were not willing to go back to the Indians without us.

We therefore being informed that governor Morris had resolved to meet them at Easton,^
footnote:[The votes of the assembly prove it.]
that the provincial treasury was exhausted,
and that the proprietaries agents refused to contribute towards the necessary expenses,
and appeared averse to the promotion of these pacific measures;
a considerable number of us thought it necessary to enter into a subscription,
towards raising a fund to supply the deficiency of what ought
in justice to be contributed by the proprietaries on this occasion,
and a considerable sum was immediately subscribed,
and governor Morris informed of our inclination to attend at the treaty,
and to make some addition to the present provided at the public expense.
From the time of the first messengers arriving at Teaogon,
the hostilities on our northern frontiers ceased,
and a stop being put to the cruel devastation that had been committed,
an acceptable respite was obtained for our distressed fellow subjects,
which afforded us real pleasure and satisfaction;
so that all the malicious calumnies and aspersions,
(which then were uttered) were not sufficient to
divert us from the steady prosecution of our purpose.
Governor Morris being at Easton sometime before us, immediately after our arrival there,
some of us waited on him, to repeat our desires of promoting the public interest,
and contributing any assistance in our power,
in such manner as might be most agreeable to him; he received us civilly,
and expressed his approbation of our design.
At the governor`'s lodgings we first saw Teedyuscung the Delaware chief,
to whom we were before utterly strangers; on our coming in,
he immediately expressed his regard for and confidence in the Quakers, and declared,
he would not proceed to any business, unless we were present;^
footnote:[This was in the hearing of governor Morris.]
and confirmed it so evidently by his subsequent conduct at that and the ensuing treaty,
that we could not without an unjustifiable neglect of our duty,
decline contributing our utmost endeavours to improve this disposition,
to the interest of our country, so far as we might be able to do it,
consistent with our respective stations in life.

Governor Morris was afterwards pleased to accept of the present provided by us,
and to deliver it in our name to the Indians.

After the conclusion of this treaty, governor Morris thought it necessary,
to send captain Newcastle on a message to the Indians at or near fort Johnson:
but before he was set out, governor Denny arrived,
and succeeded in the government of this province, and we always apprehended,
that in his name, and by his authority, captain Newcastle went on that message,
as we never interfered therein in any manner whatever,
and were not informed the particular business he was charged with.
On captain Newcastle`'s return, we found by conversing with him,
he had given some offence to general Johnson,
and we have since had cause to apprehend that some gentlemen in higher stations,
have been informed, that we had sent Newcastle on this message,
and given him matters in charge, to be privately transacted with the Indians,
after it was known to us,
that the king had by a special commission authorized sir William Johnson,
to negotiate all matters of a public concern with them;^
footnote:[From the account given by general Johnson
to the earl of Loudoun of this journey of Newcastle`'s,
it is thought the earl was induced to express himself in the manner
governor Denny has published in his late messages to the assembly.]
but as we had not given any occasion for such a charge,
nor were any way concerned in sending that message, it affords us a particular pleasure,
that the governor has given us so favourable an opportunity
of clearing ourselves from this unjust censure,
and we hope that this ingenuous account of our conduct,
in the course of this business before the governor`'s arrival,
will fully evince that we proceeded therein on just motives,
and with the regard due from us to the governor of this province.

It is well known to the governor that on his arrival here, some of us waited on him,
and one of us assured him,
of our sincere desire to proceed in contributing
our assistance towards the restoration of peace,
in a manner most agreeable to him, and consistent with our characters and stations.
He was then pleased to declare his approbation of our purpose;
and when we waited on him with our address before the second treaty at Easton,
the governor by his answer, declared his approbation of our proceedings,
and his being willing to receive the present we prepared, and us to attend the treaty:^
footnote:[This answer was in writing.]
we had reason to conclude,
that our conduct there had given the governor no occasion of offence,
as after the business was finished,
on our acknowledging his integrity and candour in the public transactions there,
he gave us such an answer, as fully expressed his being well pleased with us:^
footnote:[He thanked us for our company, and said he was glad we were there,
and that his conduct was satisfactory to us,
and should endeavour to act so upon all occasions, as to deserve our esteem, etc.,]
and the secretary and provincial interpreter very liberally
declared their satisfaction and approbation of our conduct;
and the latter fully testified that we had thereby evidently promoted the public interest,
and been instrumental in bringing the business so far towards the desired issue.

From that time till the late treaty at Lancaster,
we know of no part of our proceedings which could displease the governor,
unless our application to the secretary for an inspection
of the records in his office had that unexpected effect.
Lest that should be the case,
and the intention and manner of that application
be misrepresented by any of the proprietaries agents,
and others engaged with them in the measures which have contributed
to the present unhappy circumstances of this province,
we think it necessary to inform the governor,
that this province was settled on terms very different from most of the other colonies;
the first adventurers were men of substance and reputation,
who purchased the lands of the proprietor,
and as he obliged himself and his heirs by an express covenant contained
in their original deeds "`to clear the land from all titles,
claims or demands of the Indian natives,
or any other persons whatsoever;`" they agreed to pay an annual quit-rent,
more than sufficient to enable him to satisfy the Indians,
and obtain a peaceable possession of the land;
and during the lives of our first proprietor and the first settlers,
we believe this was faithfully performed,
and so large a balance remained towards making further purchases,
as the settlement of the country increased,
that any attempt to elude the original intention and agreement
of honestly purchasing the land of the people,
who had a native right in it, will be ever condemned by all impartial and honest men.

At the second treaty at Easton,
the governor by his candid and ingenuous treatment of the Indians (as the Mohawks
since aptly expressed it) "`put his hand into Teedyuscung`'s bosom,
and was so successful as to draw out the secret (which neither sir William Johnson
nor the Six Nations could do.`") From that time it was generally known,
that one cause of the alienation of their friendship,
was some injustice they had received or supposed to be done
them in the purchases and running out of their lands.
They complained of divers kinds of frauds, which had been committed,
repeatedly urged that an impartial inquiry should
be made into the grounds of their complaints,
by searching all our records,
and by the strong motives of a regard to our temporal and eternal interest,
urged the governor to give liberty to all persons and friends,
to search into those matters.
Thus we thought ourselves under the strongest obligations,
to make all the inquiry in our power, into the true state of the Indian claims,
whether or not such care had been taken to purchase and pay them for the lands,
as the proprietaries agents had constantly asserted.
The right of many of us who hold large tracts of land under the first settlers,
the governor`'s repeated declarations, both in public and private,
that those matters should be honestly and fully inquired into,
and the Indians injunctions,
that this should be done not only by the persons thus complained of, or their agents,
but by others likewise interested therein, united in engaging our particular attention,
and gave us a reasonable prospect of meeting with the governor`'s approbation;
and though the secretary refused to permit us to proceed therein,
by inspecting the records in his office,
we still had cause to think our farther application,
to the necessary and important concern of regaining peace,
was not contrary to the governor`'s inclination,
as on our informing him of our intention to attend the treaty at Lancaster,
and our willingness to contribute towards the expenses
of the present to be given to the Indians there,
the governor with the utmost readiness expressed his approbation of our proposal;
and we are not conscious of having at that treaty or since,
given the least occasion for the alteration of his conduct towards us;
which from the answer now received, and the conversation consequent thereon,
we have occasion to observe.

We have no views inconsistent with the honour of our gracious king,
and the interest of our country, both which we sincerely endeavour to promote;
we have heartily desired that people of every denomination in the province,
would unite in the same good purpose, and particularly in this business,
that the same harmony and good understanding,
which subsisted between the first settlers of the province and the natives,
might be revived and maintained,
and we have happily succeeded with several religious societies, who have raised funds,
and are ready to apply them towards restoring peace:
and if the complaints of the Indians appear to be just,
and the proprietaries and their agents should refuse to
make them such satisfaction as injustice they ought to have,
rather than the lives of our fellow subjects should be sacrificed,
their properties destroyed, and so large a part of the king`'s dominions laid waste,
they will freely join with us,
in contributing towards the satisfying such just claims of the Indians,
or at least to pacify them, till the immediate authority of the king,
of whose justice and paternal care we have not the least doubt, can be interposed,
and justice, equity, and mercy be again restored and maintained amongst us.

And if we are now so happy,
as to convince the governor of the integrity of our intentions and conduct,
we shall have reason to hope, he will concur with us,
in taking the first opportunity of convincing the nobleman he has named,
that it must be from some unjust representations, that he was induced to think,
"`we had presumed to treat with foreign princes, or by acting as mediators,
between the government and an independent people,
invaded the king`'s prerogative royal.`" We apprehend our duty to God and the king,
have engaged us in this business and some of the good effects thereof have already appeared;
we therefore now again offer the governor,
to contribute something considerable towards the present,
necessary to be made to the Indians at the ensuing treaty,
and by our personal attendance to improve the confidence
and good opinion these people have of us,
to the public benefit.

Should the governor persist in refusing to accept our present; we assure him,
we shall not by any part of our conduct,
give any just occasion to charge us with a disrespectful conduct towards him,
and we desire our attendance at the treaty may not be considered as such.
The business to be transacted there, is of so much consequence to the lives, liberties,
and properties of the people of this province, that should we omit to attend there,
and depend on the governor and the king`'s agent,
receiving all their information on this important occasion,
from the proprietaries agents and others,
who have for some years past been concerned in the transacting Indian affairs,
we should be deficient of our duty as christians and Englishmen,
denominations we hold more dear to us, than any other titles or appellations whatsoever.

Signed on behalf and by appointment of the said trustees and treasurer, by

[.signed-section-signature]
Abel James, Clerk.

[.signed-section-context-close]
Philadelphia, 14th of seventh month, 1757

--

The next day after the delivery of the foregoing address to the governor,
the same committee who presented it,
waited on him by direction to inform him of their intention to print it,
and requested the governor to acquaint them,
whether he had any objections to their also printing
his answer to their first verbal application to him;
about three hours after, he sent them the two following answers.

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Philadelphia, 15th July, 1757, 12 o`'clock.

[.salutation]
Gentlemen,

As you know I am desired and most strictly enjoined not to suffer any
particular body or society to concern themselves in treaties with Indians,
or on any pretence to give presents to them,
it is out of my power to permit your presents to be given.
I shall once more repeat my advice;
you would do well to decline appearing at the ensuing treaty in a body;
your attendance at treaties as a distinct society,
having given great offence to the ministry.

[.signed-section-signature]
William Denny.

[.signed-section-context-close]
Philadelphia, 15th July, 1757, 2 o`'Clock

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Mr. Israel Pemberton, and the other Gentlemen.

[.salutation]
Gentlemen,

Your address, in some parts of it,
which relate to transactions that have passed since my administration,
misrepresents several important facts,
and contains some reflection on the conduct of the proprietaries, and their agents here,
in managing the affairs of the Indians,
which I hope will be found to be without the least foundation.
I cannot therefore conceive it seasonable, or proper at this time, for you to print it;
especially when it is considered,
that the publishing may tend to inflame the minds of the Indians,
and obstruct the business of the ensuing treaty at Easton,
where the complaints made by them will be fully and impartially heard,
and I hope finally accommodated.

[.signed-section-signature]
William Denny.

[.signed-section-context-close]
To Mr. Israel Pemberton, and the other Gentlemen.

--

On consideration of which they sent him the following address.

[.embedded-content-document.address]
--

[.salutation]
May it please the governor,

Nothing less than a regard to the public interest would engage
us to decline fully complying with the governor`'s advice,
not to attend the ensuing Indian treaty;
though we have reason to believe the proprietaries instructions to the governor on this
occasion are grounded on some false and unjust information sent from hence.

Our application this day was to desire the governor would be so kind as to inform us,
whether he had any objections to our printing his answer,
in which the earl of Halifax is said to have called the Indians "`foreign
princes and an independent people,`" but the answer the governor has now
been pleased to send us relates solely to our address;
as it is contrary to our intention--to misrepresent any
transaction before or since the governor`'s administration;
we shall esteem it a favour to have those parts pointed out;
which the governor thinks in any respect exceptionable.

What we have said concerning the proprietaries and their agents is grounded on
the public records-- The governor`'s refusing to consent to accept of our contribution,
or our offer of attending the treaty has given much encouragement
to the adversaries of the peace of the province,
to repeat their malevolent assertions and calumnies against us;
but to manifest our regard to the public interest,
to be greater than to our private characters;
we shall for a few days suspend the printing of our address,
that there may be no possibility of charging us by
the publication "`inflaming the minds of the Indians.`"

Signed by appointment,
and on behalf of the trustees and treasurer of the friendly association--for
regaining and preserving peace with the Indians by pacific measures.

[.signed-section-signature]
Abel James, Clerk.

[.signed-section-context-close]
15th of 7th month, 1757

--

[.old-style]
=== Appendix No. III. / Abstract from the Report of the Committee of Council, appointed to inquire into the Complaints of the Indians at the Treaty at Easton, the 8th of November, 1756.

[.blurb]
==== To William Denny, Esq. Lieutenant Governor, etc. of the Province of Pennsylvania, and Counties of New-Castle, Kent and Sussex on Delaware.

Upon the whole it is very evident to us;
and so we presume it must appear to all unprejudiced persons,
that there is not the least shadow of foundation
for any part of the complaint made by Teedyuscung,
on behalf of the Indians against the proprietaries,
we must therefore attribute his exhibiting that groundless
and false charge against them to some undue influence,
or to the difficulty he was under to invent any other plausible pretext for the
cruel murders and horrid devastation committed by them on our back inhabitants,
and for their base ungrateful breach of faith, and the many treaties made,
and so solemnly and frequently renewed with us,
even so lately as the spring before they committed
those shocking murders and cruelties on our borders:
and we cannot but think that,
instead of this false cause which Teedyuscung has thought fit to
assign for their taking part with the enemy against us,
he might with greater truth have mentioned that, of our refusing,
or neglecting (though so frequently and earnestly requested) to offer them protection,
and give them the hatchet, and to join, and go out with them against the French,
as we have before observed;
but the people who have since that time appeared so indefatigably
industrious to engross all the management of the Indians to themselves
(in which your honour must be sensible as well as we,
they have but too well succeeded) were chiefly the
same who made up a great majority of the assembly,
at the time when the house from their avowed religious principles,
or from what other motives they best know, refused,
or declined to concur with the governor in giving the hatchet to,
and joining with those Indians against the enemy: and as they cannot but be conscious,
that they justly deserve, and must have incurred great blame on that account,
if the Indians should have given that for the reason
of their joining with the French against us:
we are better able to account for these people being
so numerous at all the late Indian treaties,
and upon all occasions so very forward and anxious
to ingratiate themselves with the Indians,
and for Teedyuscung`'s choosing to offer these imaginary reasons for his quarrel with us,
rather than the true one.

[.signed-section-closing]
We are, Sir, your most humble Servants,

[.signed-section-signature]
Lynford Lardner, etc.
