== Chapter II. Pennsylvania.

[.chapter-synopsis]
* A Spirit of Enmity remains in Pennsylvania
* Account of the Indians at Conestogoe
* These Indians address the Governor
* Six of them are murdered in their Huts
* Proclamation is sued for taking the Murderers
* Fourteen Indians are murdered in the Work-house at Lancaster
* A second Proclamation
* Other friendly Indians are removed to Philadelphia for Protection.
* Further Mischief is intended
* Governor consults the Inhabitants of the City
* Rioters come within six Miles of Philadelphia
* Governor sends some to speak with them
* They deliver a Remonstrance and return Home
* Address of the People called Quakers to the Governor

[.old-style]
=== Ireland.

[.chapter-synopsis]
* Death of the Author of this History
* Testimony concerning the Author.

The affairs of this society in England furnish few or no
remarkable materials for history at this period of time;
but in Pennsylvania a spirit of bitter enmity against this people
was still retained and disseminated by a restless party,
who, as hath been before remarked,
had for some time past been endeavouring to raise tumults in this state.
The honest endeavours of friends to promote a reconciliation
with the Indians and the success attending them,
gave a new edge to the acrimony of their opposers,
because these measures thwarted the views of these men, who,
without regard to the public good or the principles of Christianity,
wished the continuance of public disturbances to advance their private ends.
A mutinous and lawless spirit was by them industriously fomented
amongst the most ignorant and ferocious inhabitants of the frontiers,
whereby they were instigated to the commission of
a crime of the utmost turpitude in itself,
and utterly detestable by all moderate and humane persons,
as a heinous violation of the laws of Christianity, morality and hospitality.

A small body of Indians, the remains of a tribe of the six nations,
were settled at a place called Conestogoe.^
footnote:[Narrative of the late massacres in Lancaster of a number of Indians,
friends of this province, printed in 1764.]
On the first arrival of the English in Pennsylvania,
messengers from this tribe came to welcome them, and brought them presents of venison,
corn and skins;
and the whole tribe entered into a treaty of friendship with the
first proprietor William Penn (as hath been noticed in its place.)
This treaty was to last as long as the sun should shine,
or the waters run in the rivers.
The treaty had been frequently renewed, and the chain brightened, as they express it,
from time to time.
As their lands by degrees came mostly into the hands
of the white people by successive purchases,
the proprietor assigned them lands on the manor of Conestogoe,
to be retained for their own use and habitation.
There they lived many years in friendship with their European neighbours and their descendants,
by whom they were regarded with affection for their peaceful and inoffensive behaviour.

This tribe was greatly diminished in number from the time when
the European planters first arrived in their neighbourhood.
There remained in their town no more than twenty persons, viz. seven men, five women,
and eight children.
This little society continued the custom,
which they had begun when they were a more numerous body,
of addressing every new governor, and every descendant of the first proprietor,
welcoming him to the province, assuring him of their fidelity,
and requesting a continuance of that favour and protection,
they had hitherto experienced.
They had sent up an address of the same kind to the present governor, John Penn,
as he had lately succeeded William Denny in the government, who, I presume,
might have resigned the office, which must have become very uneasy to him,
pressed on one hand by the apprehended exigences of the state; on the other,
cramped by proprietary instructions,
and involved thereby in disagreeable altercations with the assembly,
who entertained a confirmed jealousy of these instructions and
of the political views of the proprietors to take advantage of
the present difficult and distressed circumstances of the province,
to wrest from them and their constituents some of their chartered privileges,
and to invade their constitutional rights.

The last address was but just delivered,
and the new governor scarce settled in his government, when on the 14th of 12th month,
1763, fifty-seven men from some of the frontier settlements,
who had projected the destruction of this little community, came all well mounted,
and armed with muskets, hangers and hatchets to Conestogoe manor,
having travelled through the country in the night.
There they surrounded the small village of Indian huts,
and just at the dawn of day broke into them all at once.
Six of the only two men three women and a young boy Indians were found at home,
the rest being absent about their lawful occasions.
These poor defenceless their huts, creatures were immediately fired upon,
stabbed and hatchetted to death.
The good Shaeshaes among the rest they cut to pieces in his bed:^
footnote:[Shaehaes (as described in the narrative) was a very old man,
having assisted at the second treaty, held with the Indians by William Penn, in 1701,
and ever since continued a faithful and affectionate friend to the English,
he is said to have been an exceeding good man, considering his education,
being of a most kind and benevolent temper.
It is said that he being be fore told, that it was to be feared,
that some English might come from the frontiers into the country,
and murder him and his people, he replied, "`It is impossible:
there are Indians indeed in the woods, who would kill me and mine,
if they could get at us, for my friendship to the English;
but the English will wrap me up in their match-coats,
and secure me from all danger.`" How lamentably was he mistaken!]
all of them were scalped and otherwise horribly mangled;
their huts were set on fire and most of them burned down.
The assassins then rode off, and in small parties, by different roads went home.

The tidings of this barbarous transaction filled the neighbouring white people,
who were not abettors, with dismay and abhorrence.
And the lamentations of the younger Indians, when they returned,
and beheld the desolation and the butchered half burned
bodies of their murdered parents and other relations,
were excessive and affecting to the last degree.

The magistrates of Lancaster sent out to collect the remaining Indians,
brought them into the town for their greater security against any further attempts;
took them by the hand, and promised them protection.
They were all put into the work-house, a strong building,
as the place of greatest safety.

The astonishing news of this dismal and disgraceful catastrophe soon reached Philadelphia;
whereupon a proclamation was issued by the governor, charging all judges, magistrates,
officers civil and military,
and all other liege subjects to make diligent search and
inquiry after the authors and perpetrators of the said crime,
their abettors and accomplices,
and to use all possible means to apprehend and secure
them in some of the public jails of the province,
that they might be brought to their trials, and be proceeded against according to law.

Too many of the inhabitants of the town and county of Lancaster seeming
rather to approve than discourage their sanguinary achievement,
added audacious insolence to the wanton ferocity of these cruel men.
So that neither the precaution of placing the Indians in a place of security,
nor the proclamation issued by the governor intimidated them from
prosecuting their wicked purpose in defiance of all justice,
rule and government.
Having got intelligence that the remaining fourteen
Indians were in the work-house of Lancaster,
on the 27th of the same mouth, they entered that town (which is large and populous,
containing several thousand inhabitants) fifty of them armed as before,
went directly to the work-house, by force broke open the door,
and barbarously murdered all the Indians confined there,
on their bended knees protesting their innocence and attachment to the English,
and with uplifted hands imploring their lives; unarmed men; helpless women,
and innocent infants-- all murdered--in cold blood.

The rioters who committed this atrocious deed, in violation of all laws,
human and divine, then mounted their horses, in triumph,
as if they had accomplished a laudable exploit, and rode off--unmolested.
Although a number of the king`'s soldiers were then in the barracks there,
whose officers declared they were ready to assist the magistrates,
if they had been called upon, and,
by their conduct after wards manifested their willingness and ability to do it.

Upon this second massacre,
a second proclamation was issued by the governor in the following terms.

[.embedded-content-document.legal]
--

Whereas on the twenty-second day of December last,
I issued a proclamation for the apprehending and bringing to justice,
a number of persons, who in violation of the public faith, and in defiance of all law,
had inhumanly killed six of the Indians who had lived in Conestogoe manor,
for the course of many years, peaceably and inoffensively,
under the protection of this government, on lands assigned to them for their habitation;
notwithstanding which,
I have received information that on the twenty-seventh of the same month,
a large party of armed men again assembled and met
together in a riotous and tumultuous manner,
in the county of Lancaster, proceeded to the town of Lancaster,
where they violently broke open the work- house,
and butchered and put to death four-teen of the said Conestogoe Indians, men,
women and children,
who had been taken under the immediate care and protection
of the magistrates of the said county,
and lodged for their better security in the said work-house,
till they should be more effectually provided for by order of the government.
And whereas common justice loudly demands,
and the laws of the land (upon the preservation of which
not only the liberty and security of every individual,
but the being of the government itself depend) require that
the above offenders should be brought to condign punishment;
I have therefore, by and with the advice of the council, published this proclamation,
and do hereby strictly charge and command all judges, justices, sheriffs, constables,
officers civil and military,
and all other his majesty`'s faithful and liege subjects within this province,
to make diligent search and inquiry after the authors
and perpetrators of the said last mentioned offence,
their abettors and accomplices,
and that they use all possible means to apprehend and secure
them in some of the public jails of this province,
to be dealt with according to law.

And I do hereby further promise and engage that any person or persons,
who shall apprehend and secure,
or cause to be apprehended and secured any three of the ring-leaders of the said party,
and prosecute them to conviction, shall have and receive for each,
the public reward of two hundred pounds; and any accomplice,
not concerned in the immediate shedding the blood of the said Indians,
who shall make discovery of any or either of the said ring-leaders,
and apprehend and prosecute them to conviction, shall, over and above the said reward,
have all the weight and influence of the government,
for obtaining his majesty`'s pardon for his offence.`"

Given under my hand and the great seal of the said province, at Philadelphia,
the second day of January, in the fourth year of his majesty`'s reign,
and in the year of our Lord, one thousand seven hundred and sixty-four.

[.signed-section-signature]
John Penn.

[.signed-section-context-close]
By his honour`'s command Joseph Shippen, junior, sec.

[.signed-section-context-close]
God save the King.

--

These proclamations produced no discovery;
the murderers and their partisans having given out such
threatenings against those who disapproved their proceedings,
that the whole country seemed to be terrified, and not one durst discover what he knew;
even letters from thence were unsigned,
in which any dislike to these shocking enormities was expressed.

Neither doth it appear that proper measures were taken by the magistrates
in that county for the purpose of discovering the criminals.
Indeed whether it proceeded from fear or favour,
the conduit of these magistrates seems highly reprehensible;
to confine the poor creatures under promise of protection,
and suffer them to be butchered, as before their faces, in violation of their good faith;
and make no effort either to give them the protection which they had promised,
or to apprehend and bring to justice the perpetrators;
either of which one might presume they might have effected.

Having proceeded so far with impunity, it increased their insolence;
filled with rage against all Indians,
they seemed determined to destroy them in like manner,
in defiance of the government itself, they prevailed with others to join them,
with a view to increase the number of offenders,
so much as to render it dangerous or difficult to bring them to justice.
There yet remained a number of friendly Indians,
who had put themselves under the immediate protection of government,
by whose orders they were remove to the city of Philadelphia, from the plantations,
on which most of them had lived many years under the care of the Moravians,
by whose missionaries they had been brought to the
profession of the christian religion with them,
and lived soberly and peaceably on the fruit of their own labour and industry.

From the intelligence received from time to time of the design
of the rioters to destroy these Indians in the barracks,
it was resolved by government to remove them, first to the Province-island,
as a place of greater safety; and afterwards to convey them out of the province,
and commit them to the immediate care of Sir William Johnson,
the king`'s agent for Indian affairs; and the general at New York.
They were accordingly sent through the province of New Jersey as far as Amboy;
but the governor of New York refusing them admittance into his province,
they were soon after ordered to return to Philadelphia,
and general Gage sending a number of soldiers for their protection on their return,
they were lodged in the barracks under a guard.

The rioters enraged at their disappointment,
as soon as they heard of the return of the Indians,
of which they received early intelligence from their accomplices in the city,
assembled again in numbers.
Accounts were received of their proceedings,
and breathing out threatenings of executing their barbarous intentions,
not only against the Indians, but all that defended them,
and particularly against some concerned in government,
as well as sundry private persons.

On the 4th of the month, called February, 1764,
the governor receiving information that the rioters were on their march towards the city,
called the inhabitants together to consult them upon such measures
as he thought advisable for preventing the intended mischief;
numbers showed more readiness than was expected to support his authority,
and to oppose such a daring insult offered to the government.
About midnight succeeding the following day,
fresh advice was received of their near approach,
and precautions being taken to prevent their pasting the ferries over the river,
and a very heavy rain having raised the fords, retarded their march.
They came down to Germantown, about six miles from Philadelphia,
from whence they sent their spies into the city,
to observe the conduct and preparations of the government against them;
and by their intelligence finding they were likely to meet with a very
different reception from that which they had experienced at Lancaster,
they though it safest to halt there, and return home without effecting their purpose.
Possibly this account of these murders and riots may appear foreign to our subject,
and thus far it is so; but the people called Quakers,
although they were of a very contrary disposition,
and could have no concern in such actions,
yet they were very causelessly involved in the consequences.
When the rioters came to Germantown, and found themselves frustrated in their designs,
they dropped their menaces of destroying the Indians,
and began to complain of grievances.
A paper unsigned had been delivered to the governor, as from the rioters on their march,
though it was doubted whether many of them were acquainted with the contents,
and whether it was not rather the composition of some of their abettors.

On the 7th of the month some persons by the governor`'s authority, went to meet them,
and inquire into the reason of their tumultuous appearance.
It appeared in the conference held with them,
that these people were much deluded through invidious misrepresentations,
which had raised their prejudice against the conduct of the government.
In fine, their, leaders engaged they should return home,
two of them being agreed upon to represent the rest,
in order to lay the grievances they pretended they and were under before the governor,
and the assembly then sitting.

A declaration of their intentions, I suppose,
and a remonstrance of their grievances were presented to the legislature;
and the meeting for sufferings at Philadelphia receiving information that the said declaration
and remonstrance contained groundless reflections on the Quakers as a society,
they applied to the governor, requesting a copy of each, which he readily granted;
whereupon they agreed upon an address in answer thereto,
which they presented to the governor as follows.

[.embedded-content-document.address]
--

[.letter-heading]
To John Penn, Esq.
Lieutenant Governor of the Province of Pennsylvania.

[.blurb]
=== The Address of the People called Quakers in the said Province.

[.salutation]
May it please the Governor,

We acknowledge thy kind reception of our Address of application for copies of the two
papers presented to thee by some of the frontier inhabitants of this province,
on the 6th and 13th instant, which we have perused and considered,
and find several parts thereof are evidently intended to render us odious to our superiors,
and to keep up a tumultuous spirit among the inconsiderate part of the people.
We therefore request thy favourable attention to some observations
which we apprehend necessary to offer,
to assert our innocence of the false charges, and unjust insinuations,
thus invidiously propagated against us.

Our religious society hath been well known through
the British dominions above an hundred years,
and was never concerned in promoting or countenancing
any plots or insurrections against the government;
but on the contrary, when ambitious men, thirsting for power,
have embroiled the state in intestine commotions and bloodshed,
subverting the order of government; our forefathers, by their public declarations,
and peaceable conduct, manifested their abhorrence of such traiterous proceedings;
and notwithstanding they were often subjected to
gross abuses in their characters and persons,
and cruel imprisonments, persecutions, and some of them to the loss of their lives,
through the instigation of wicked and unreasonable men,
they steadily maintained their profession,
and acted agreeable to the principles of the true disciples of Christ;
and by their innocent peaceable conduct,
having approved themselves faithful and loyal subjects,
they obtained the favour of the government,
and were by royal authority entrusted with many valuable rights and privileges,
to be enjoyed by them and their successors,
with the property they purchased in the soil of this province
which induced them to remove from their native land,
with some of their neighbours of other religious societies, and at their own expense,
without any charge to the public,
to encounter the difficulties of improving a wilderness,
in which the blessings of divine providence attended
their endeavours beyond all human expectation;
and from the first settling of the province, till within a few years past,
both the framing and administration of the laws were
committed chiefly to men of our religious principles,
under whom tranquillity and peace were preserved among the inhabitants,
and with the natives.
The land rejoiced, and every man was protected in his person and property,
and in the full enjoyment of religious and civil liberty; but with grief and sorrow,
for some years past,
we have observed the circumstances of the province to be much changed,
and that intestine animosities, and the desolating calamities of war,
have taken place of tranquillity and peace.

We have, as a religious society,
ever carefully avoided admitting matters immediately
relating to civil government into our deliberations,
farther than to excite and engage each other to demean
ourselves as dutiful subjects to the king,
with due respect to those in authority under him,
and to live agreeable to the religious principles we profess,
and to the uniform example of our ancestors, and to this end meetings were instituted,
and are still maintained,
in which our care and concern are manifested to preserve
that discipline and good order among us,
which tend only to the promotion of piety and virtue; yet as members of civil society,
services some times occur which we do not judge expedient to become
the subject of the consideration of our religious meetings,
and of this nature is the association formed by a
number of persons in religious profession with us,
of which on this occasion it seems incumbent on us to give some account to the governor,
as their conduct is misrepresented,
in order to calumniate and reproach us as a religious society,
by the insinuations and slanders in the papers sent to the governor,
and particularly in the unsigned declaration, on behalf of a number of armed men,
on the sixth instant, then approaching the city, from distant parts of the province,
to the disturbance of the public peace.

In the spring of the year 1756, the distress of the province being very great,
and the desolating calamities of a general Indian war apprehended,
at the instance of the provincial interpreter Conrad Weiser,
and with the approbation of governor Morris,
some of us essayed to promote a reconciliation with the
Indians and their endeavours being blessed with success,
the happy effects thereof were soon manifest,
and a real concern for the then deplorable situation
of our fellow subjects on the frontiers prevailing,
in order that they might be capable of rendering some effectual service;
they freely contributed considerable sums of money,
and engaged others in like manner to contribute, so that about 5000£. was raised,
in order to be employed for the service of the public,
and chief part thereof hath been since expended in presents given at the public
treaties (where they were sometimes delivered by the governors of this province,
and at other times with their privity and permission) for promoting the
salutary measures of regaining and confirming peace with the Indians,
and procuring the release of our countrymen in captivity;
and thereby a considerable number have been restored to their friends;
and we find that the measures thus pursued being made known to the king`'s generals,
who from time to time were here,
and having been communicated by an address sent to
the proprietaries of this province in England,
appear, by their written answers, and other testimonials,
to have received their countenance and approbation.
This being the case, and the conduct of those concerned in these affairs,
evidently contrary to the intent and tendency of
the assertion contained in the said unsigned declaration,
pretended to be founded on the records of the county of Berks,
we do not apprehend it necessary to say any more thereon,
than that we are (after proper inquiry) assured,
that nothing of that kind is to be found on those records,
and that the private minute made by Conrad Weiser,
of a report he had received from two Indians,
of a story they had heard from another Indian,
pretending to be a messenger from the Ohio, does not mention any person whatever,
nor contain the charges expressed in the declaration, and from the inquiry we have made,
we find them groundless and unjust,
uttered with a view to amuse and inflame the credulous, and to vilify and calumniate us.

The invidious reflection against a sect that have got the political reins in their hands,
and tamely tyrannize over the good people of this province;
though evidently levelled against us,
manifests the authors of of these papers are egregiously ignorant of our conduct,
or willfully bent on misrepresenting us; it being known that as a religious body,
we have by public advice, and private admonitions, laboured with, and earnestly desired,
our brethren,
who have been elected or appointed to public offices
in the government for some years past,
to decline taking upon them a task become so arduous,
under our late and present circumstances;
and that many have concurred with us in this resolution is evident,
by divers having voluntarily resigned their seats in the house of assembly,
and by others having, by public advertisements signified their declining the service,
and requesting their countrymen to choose others in their places,
and that many have refused to accept of places in the executive part of the government.
We are not conscious that as Englishmen and dutiful subjects,
we have ever forfeited our right of electing or being elected;
but because we could serve no longer in those stations with satisfaction to ourselves,
many of us have chosen to forbear the exercise of these rights,
and wish a disposition of a contrary nature was not so manifest in our adversaries.

The accusation of our having been profuse to savages,
and carefully avoiding to contribute to the relief
and support of the distressed families of the frontiers,
who have abandoned their possessions, and fled for their lives,
is equally invidious and mistaken;
we very early and expeditiously promoted a subscription,
and contributed to the relief of the distresses of those who were plundered,
and fled from their habitations in the beginning of the Indian war,
which was distributed among them, in provisions and clothing,
and afforded a seasonable relief.
Divers among us, in the city of Philadelphia,
also contributed with others the last summer,
and we are well assured that money was raised,
and sent up by the members of our society in different parts of the country;
and as soon as we were informed,
that the greatest part of what had been voluntarily raised
by the citizens of Philadelphia was nearly expended,
a subscription was set on foot, to which several very generously contributed,
and a large sum might soon have been raised,
and was stopped only on account of the tumult which hath lately happened;
and it hath been from our regard to our fellow subjects on the frontiers,
and sympathy with their afflicting distresses,
and a concern for the general welfare of the province,
that engaged our brethren to raise the money they
applied to promote a pacification with the natives,
and no separate views of interest to ourselves;
but thus unhappily our most upright and disinterested
intentions are misconstrued and perverted,
to impose on the weak, and answer the pernicious schemes of the enemies of peace.

The eighth paragraph of the second paper, called the remonstrance,
being chiefly answered by the foregoing observations,
it may be necessary only to observe,
on the malicious charge of abetting the Indian enemies,
and keeping up a private intelligence with them,
which we can assure the governor is altogether false and groundless,
and we do not know of any member of our society chargeable therewith;
the transaction relating to the string (which they have called
a belt of wampum) we find by letters from general Forbes,
and other papers produced to us,
was in consequence of a message sent by the king`'s
deputy agent to the Indians on the Ohio,
in the name of Sir William Johnson, their brother Onas,
and the descendants of the first settlers who came
over with their ancient brother William Penn;
as also of Frederick Post`'s being engaged by some members
of our community to go on another message to these Indians,
by the express orders of that general, who then commanded the king`'s army,
and with the concurrence of the governor of this province;
but we do not approve or think it allowable for any private subject to carry on a correspondence,
or treat with the enemies of the king and government,
nor to engage in the transaction of any affairs of the government,
without the privity and consent of those in authority over us.

We desire the governor to excuse our taking this opportunity
of exculpating ourselves from another false accusation,
industriously propagated, with a design to reproach us as a society;
it having been reported, during the late commotion in this city,
that some persons of our community had in the evening of the 6th instant, removed,
from or near the barracks, six Indians, to an island in the river,
nearly opposite the city, with a design to conceal them,
and evade their being seen and examined by some of the people from the frontiers,
and that an _ex parte_ deposition of an apprentice boy was taken to that purpose;
upon hearing which,
some of us immediately requested to have the said boy and
his master carefully examined before the mayor;
in consequence thereof, both of them were enjoined and required by the recorder,
and one of the aldermen, to appear before the mayor, in the morning of the 11th instant,
at 11 o`'clock, but it appeared from the testimony of his master,
that before the time appointed the boy absconded,
and after diligent search is not since found.
Wherefore the mayor,
after the examination of the military officers (to whose care the Indians
had been committed) and of other witnesses relating to the matter,
upon consideration thereof, and the circumstances attending the relation;
first the alderman, before whom the deposition had been made,
and afterwards the mayor publicly declared,
they were convinced the accusation was utterly false and groundless.

It would be a tedious task for us to undertake to answer
all the slanderous reports and misrepresentations,
which have been spread, with a design to prejudice our characters,
through the malice of some, and the ignorance of others;
but having the testimony of our consciences to recur to for our innocence,
we hope through divine assistance, we shall be enabled to bear reproaches; and,
by the uprightness of our conduct, show forth to the world,
that we live in the fear of God,
and pay the just returns of dutiful submission to the king,
for the continuance of his paternal tenderness towards us; and that we are,
as we have ever been, real friends to the government,
and steadily desirous of acting agreeable to our stations, as members of civil society.

[.signed-section-context-close]
Signed on behalf,
and by order of a committee appointed to represent
our religious society in Pennsylvania and New Jersey,
at a meeting held in Philadelphia, the 25th of second month, 1764.

[.signed-section-signature]
Samuel Emlen, junior, Clerk.

--

The frontiers were mostly inhabited by emigrants
from the north of Ireland and their descendants,
and Germans; the latter, though solicited, to their reputation, refused to join with,
or have any concern in these iniquitous and tumultuous proceedings.

And, as the disposition and behaviour of the people called Quakers towards the Indians had
been as to all others (and contrary to theirs) regulated by a strict regard to equity,
morality and that religion that dictates peace on earth, and good will to men;
the rioters looking upon it in an invidious light,
and as reproaching their own too general vindictive temper and conduct,
they went beyond all bounds of justice and truth
in most abusive representations of that people,
to whom and their predecessors and principles,
Pennsylvania was principally indebted for its prosperity and population:
all their conduct, public and private,
was misconstrued with the usual injustice of party rage.^
footnote:[Nothing has been added to the copy left written by my father,
except a few of the biographical accounts of deceased friends,
which he had proposed to be inserted.
He intended to have concluded the work in this fourth volume,
but from the number of original papers yet remaining, it seems impracticable.
Those papers are now in my possession, and shall be carefully preserved,
till some friend may see it his business to finish it in a fifth volume.
Lisburn in Ireland, 5th of sixth mo. 1792. John Gough, Junior]

[.asterism]
'''

Soon after writing the foregoing, the author was seized with a fit of apoplexy,
which in a few hours ended in his decease.--He attained to 70 years,
and had been engaged during the work,
last eight years of his life in writing this history.

[.embedded-content-document.testimony]
--

[.blurb]
=== A Testimony from Lisburn Men`'s Meeting, concerning our deceased friend John Gough, read and approved in the Quarterly-Meeting for Ulster, held at Moyallon the 18th of 2nd Month, and in the National Half-year`'s Meeting in Dublin, 5th Month, 1792.

He was born at Kendal in Westmoreland, in the beginning of the year 1721,
of parents professing the truth, as held by us, the people called Quakers,
and by the information we have received concerning him,
we find that from his youth he was much inclined to seriousness and thoughtfulness,
being early made acquainted with the teachings of divine grace in his heart,
and measurably attending thereto, he became an example of plainness,
frugality and sobriety, in his apparel and conduct,
and was thereby preserved from the evils and condemnable practices,
into which too many of our youth by pursuing a contrary conduct, have unhappily fallen.

Having received an education suitable to qualify him for a schoolmaster,
and being endowed with good natural parts,
he was employed about the sixteenth year of his age as usher in a friend`'s school,
at Pickwich in Wiltshire, in which station he continued four years,
and then resigning his place, he removed into this kingdom.

In the year 1750, he settled in Dublin, where he remained about twenty four years,
following the occupation of a schoolmaster.
During his residence in that city, he approved himself a valuable member of society,
having experienced through the sanctifying operation of the spirit of truth,
a gradual advancement in the work of righteousness, as he grew in years,
growing in grace and in the knowledge of our Lord and Saviour Jesus Christ,
he was thereby fitted for service,
and being appointed to the office of an elder in the church,
pretty shortly after his settlement there,
he was found truly serviceable in his station amongst his brethren.

In the year 1774,
he was induced by an apprehension of duty to remove into this neighbourhood,
and undertook the care of a boarding school,
about which period he was called forth into the more public work of the ministry,
and approved himself in the exercise of his gift as an able minister,
speaking the things that be, came sound doctrine,
labouring abundantly in the fresh flowings forth of gospel love,
for the exaltation of truth and the edification of the body.
In the course of his ministerial labours,
he visited the province of Munster and sundry parts of Leinster, and once,
viz. in the year 1785, several counties in England,
he also sundry times attended the yearly meeting in London,
and on all these occasions we have reason to believe his
company and services were truly acceptable to friends.

In transacting the affairs of the church,
he was eminently skilful and of extensive use in the society,
particularly by his assistance therein at the time of our national assemblies,
being favoured with a sound judgment,
quick conception and a right understanding of the letter and spirit of our discipline,
with the capacity of expressing his thoughts in a clear, concise and convincing manner.
He was often instrumental by his judicious and seasonable remarks,
in cases of difficulty, where friends were divided in judgment,
in reconciling their different sentiments, to the preservation of harmony and concord;
yet was he careful not to press his opinion above measure,
thereby manifesting his regard to the promotion of good order in the church of Christ,
in observance of the apostle`'s injunction to his son Timothy,
that the servant of the Lord must not strive, but be gentle unto all men, apt to teach,
patient, in meekness instructing those that oppose themselves.
He also showed a good example of brotherly condescension in giving
up to the necessary service and appointments of the meeting,
at the request of his brethren.

He was of a sober, circumspect life and conversation, as becometh the gospel of Christ;
plain and humble in his appearance, and grave in deportment,
showing himself a pattern of good works, in doctrine showing uncorruptness, gravity,
sincerity.
And although it may be said, that in public testimony,
he was for the most part drawn forth in a close line of doctrine,
from a weighty sense of the deep revolting and departure
in heart of many of the professors of the blessed truth,
in the present day, from the holy law and government of the Prince of peace,
yet at other seasons, particularly in more select opportunities,
he was experienced to be as a nursing father to the children of the family,
a tender instructor in the way to the kingdom,
and an encourager of the honest-hearted therein.

And if we consider him in the more contracted circle of private life,
he was a kind and affectionate neighbour, full of tenderness and compaction,
feeling in much sympathy for the trials and sufferings of his friends,
whom he neglected not to visit,
and to commiserate in their distress as opportunity offered,
to cheer the drooping heart and to administer consolation to the afflicted.

He was a diligent attender of meetings for worship and discipline at home and abroad,
being scarcely ever absent from our general province quarterly and national meetings,
he likewise frequently visited the smaller meetings,
and the adjacent meetings of discipline;
as also the families of friends in different parts of this province,
to good satisfaction,
being often therein much favoured to speak applicably to the several states of the visited.
And when released from services of this nature abroad,
he was careful not to be slothful in business at home,
being closely employed for several years during the latter stage of his life,
in the weighty and arduous under taking of compiling a general history of our society,
three volumes of which have been lately published,
and the remaining one brought very nearly to a conclusion;
of this work as it is already well known and pretty generally in friends hands,
it does not appear needful for us to fay much,
further than to express our hope that it may be as a memorial to many,
of those useful talents where with he was gifted, and of his application of them,
under the influence of divine aid, with diligence and devotedness of heart,
to the cause and service of truth in his generation.

About a year before his death,
he was attacked with a sudden stroke of the paralytic kind,
which gave much cause of apprehension to his family and friends,
that the time of his departure was at hand;
from which however he so far recovered as to undertake the performance
of a religious visit to some meetings in the province of Leinster,
and to join with sundry friends, nominated by our national meeting,
in visiting the meetings of discipline in Munster,
and he was furnished with strength and ability to accomplish
the service and to return to his family in peace.

He was at times concerned in public supplication in our assemblies,
on which occasions he appeared weighty and fervent in spirit,
as one deeply impressed with a reverent sense of the solemnity pf the engagement,
and a few weeks previous to his death, being engaged on this wise,
after interceding for the general state of the church,
be was led by a remarkable transition,
as if favoured with a sense of his approaching dissolution,
to supplicate on his own behalf,
that he might be more and more purified and fitted for his final change,
that when the angel of the divine presence should be sent to his habitation,
with the solemn message that time should be to him no longer,
he might be admitted to join the hundred and forty four thousand who were redeemed from,
the earth, in singing praises to the lamb.
And as our dear friend continued a zealous and diligent
labourer in the vineyard until the conclusion of his days,
being willing to spend and to be spent, that so he might finish the work;
allotted to him therein, as a good and faithful servant;
we doubt not but be is now a partaker of the blessed
recompense of reward in the joy of his Lord.

On the 25th day of the tenth month, 1791, being suddenly seized with another fit,
which in a few hours put a period to his existence in this state of mutability,
he quietly departed as one falling asleep and on the 28th he was decently interred
in friends burying ground at Lisburn after a solemn meeting.

--

[.the-end]
End of the Fourth Volume.
