== Appendix, No. III.

=== Abstract from the Report of the Committee of Council, appointed to inquire into the Complaints of the Indians at the Treaty at Easton, the 8th of November, 1756.

To William Denny, Esq.
Lieutenant Governor, etc. of the Province of Pennsylvania, and Counties of New-Castle,
Kent and Sussex on Delaware.

Upon the whole it is very evident to us;
and so we presume it must appear to all unprejudiced persons,
that there is not the least shadow of foundation
for any part of the complaint made by Teedyuscung,
on behalf of the Indians against the proprietaries,
we must therefore attribute his exhibiting that groundless
and false charge against them to some undue influence,
or to the difficulty he was under to invent any other plausible pretext for the
cruel murders and horrid devastation committed by them on our back inhabitants,
and for their base ungrateful breach of faith, and the many treaties made,
and so solemnly and frequently renewed with us,
even so lately as the spring before they committed
those shocking murders and cruelties on our borders:
and we cannot but think that,
instead of this false cause which Teedyuscung has thought fit to
assign for their taking part with the enemy against us,
he might with greater truth have mentioned that, of our refusing,
or neglecting (though so frequently and earnestly requested) to offer them protection,
and give them the hatchet, and to join, and go out with them against the French,
as we have before observed;
but the people who have since that time appeared so indefatigably
industrious to engross all the management of the Indians to themselves
(in which your honour must be sensible as well as we,
they have but too well succeeded) were chiefly the
same who made up a great majority of the assembly,
at the time when the house from their avowed religious principles,
or from what other motives they best know, refused,
or declined to concur with the governor in giving the hatchet to,
and joining with those Indians against the enemy: and as they cannot but be conscious,
that they justly deserve, and must have incurred great blame on that account,
if the Indians should have given that for the reason
of their joining with the French against us:
we are better able to account for these people being
so numerous at all the late Indian treaties,
and upon all occasions so very forward and anxious
to ingratiate themselves with the Indians,
and for Teedyuscung`'s choosing to offer these imaginary reasons for his quarrel with us,
rather than the true one.

[.signed-section-closing]
We are, Sir, your most humble Servants,

[.signed-section-signature]
Lynford Lardner, etc.
