== Chapter I.

[.chapter-synopsis]
* George III. succeeds to the Throne
* Address to him
* Address to the Princess Dowager of Wales
* Francis Hart is prosecuted by Mary Jerom for reading a Testimony of Denial
* Address on the Peace
* Account of John Goodwin

George II was succeeded by his grandson George III.
our present sovereign, son to Frederick, late prince of Wales, who died in the year 1751,
greatly and generally lamented, as he was generally beloved.
Addresses to the young king, being sent up from all quarters,
the people called Quakers in London, also drew up,
and appointed a deputation to wait upon the king with the following address.

[.embedded-content-document.address]
--

[.letter-heading]
To George III.
King of Great Britain and the Dominions thereunto belonging.

[.blurb]
=== The humble Address of his Protestant Subjects the People called Quakers.

[.salutation]
May it please the King,

Deeply affected with the sudden and sorrowful event,
that leads our fellow-subjects with condolence to the throne,
we beg leave to express the sympathy we feel on this occasion.

Justly sensible of the favour and protection we have
enjoyed during the late mild and happy reign,
and impressed with the warmest sentiments of duty and gratitude to our deceased sovereign,
we pay this tribute of unaffected grief to the memory
of the father and friend of his people.

We have abundant reason to acknowledge the goodness of Almighty God,
for continuing to this period a life of such importance to the welfare of these kingdoms;
a period when we behold a prince endowed with qualities that add lustre to a crown,
formed by tuition and example to protect the liberties of his people,
ascending the British throne; and in the earliest acts of power,
giving the most ample demonstration of his royal regard for piety and virtue.

Ever faithful and zealously affected to thy illustrious house,
though differing in sentiments and conduct from others of our fellow-subjects,
we embrace this opportunity to crave thy indulgence and protection,
and beg leave to assure the king that our dissent
proceeds not from a contumacious disregard to laws,
to custom or authority, but from motives to us purely conscientious.

The same religious principles that produce this dissent, we trust,
through divine assistance,
will continue to engage us as it always hath done since we were a people,
to exert whatever influence we may be possessed of in promoting the fear of God,
the honour of the king, and the prosperity of his subjects.

May the Almighty bless thy endeavours to put a stop to the effusion of blood,
and render thee the happy instrument of restoring peace and tranquillity.

May sacred and unerring wisdom be thy guide, adorn thee with every virtue,
and crown thee with every blessing;
that future ages may commemorate the happiness of thy reign with grateful admiration.

[.signed-section-context-close]
Signed on behalf of the said people in London, the 1st of 12th month, 1760, by.
220 friends.

--

[.old-style]
=== The Answer.

[quote]
____
This dutiful and loyal address is very acceptable to me,
and you may depend on my protection.
____

They also presented an address to his mother, the princess of Wales, viz.

[.embedded-content-document.address]
--

[.salutation]
May it please the Princess Dowager of Wales,

We the people called Quakers,
beg leave to testify our grief for the loss we have
sustained by the decease of our late gracious sovereign;
duty as well as gratitude for the favours we enjoyed during his long and happy reign,
claim our unfeigned regard to his memory,
and to every part of the royal family our most grateful attachment.

As the afflictions that befall them very deeply affect us,
so we share in the blessings they enjoy,
and we sincerely rejoice at the happy accession of thy son, our sovereign,
to the throne of these kingdoms.

The noble proofs he has already given of great and illustrious qualities,
sufficiently point out how much we are indebted to a mother`'s early care in his education.

It will we trust,
be our constant endeavour to manifest our dutiful affection to the princess,
and our cheerful obedience and fidelity to the king,
by a conduct becoming our religious profession.
May the Almighty pour down his choicest blessings on every branch of the royal family;
may they be regarded as the ornaments of the present age,
and as examples of virtue in succeeding generations.

--

To which she returned an answer, as nearly as can be recollected, as follows.

[quote]
____
I am much obliged to you for your kind attention to me and my family.
____

A case occurs in this year,
whereby the validity of the discipline of this society was brought to a legal trial,
an occurrence of which I know no other instance.
Mary Jerom, a young woman of Nottingham,
who had been educated by her parents in this society,
and by them left in possession of a considerable property,
having been in various parts of her conduct,
very inconsistent with a life of self-denial,
and the religious principles of this people,
and for some time mostly neglected the attendance of the meetings of divine worship;
and as wrong conduct is frequently attended with or productive of erroneous sentiment,
she had also imbibed erroneous notions, contrary to scripture doctrine;
wherefore her conduct came under the cognizance of friends of Nottingham monthly meeting.
According to the salutary discipline of the society,
they appointed friends to pay her religious visit,
to use endeavours in gospel love to inform and reclaim her;
but she seems to have been lifted up in her mind above the reception of advice.
The labour of love extended to her proved ineffectual, she rejected their admonition,
and persisted in the same line of conduct, and justified herself therein.
The meeting therefore,
after a deliberate consideration of the case in all its circumstances,
thought it necessary to bear a testimony of their
disunity with her said sentiments and conduct;
which being drawn up, approved and authenticated,
was ordered to be published in the customary way.
It was accordingly read after the time of worship in the meetinghouse of Nottingham,
by Francis Hart, clerk of the monthly meeting,
and a copy thereof handed to her a few days after.

The high spirit of this female was so mortified and provoked by this act of discipline,
that instead of reflecting on her own conduct,
which had made it necessary to preserve consistency,
and prevent confusion in the society; depending upon her abundance,
she formed a resolution to obtain satisfaction, as far as money could effect it.
First, upon an affidavit of the publication thereof by Francis Hart, by reading the same,
etc. she moved the court of King`'s Bench for an information against him for a libel,
but the court, looking upon it as a case by no means proper for such a prosecution,
asked the counsellor who moved it, if he was really in earnest,
and upon his affirmative reply, rejected the motion,
and refused to grant a rule even to show cause.

Although disappointed in this first application the said
Mary Jerom desisted not from prosecuting her purpose.
For on the 12th of 3rd month, 1762,
she preferred an indictment for a libel against Francis Hart,
at the assizes at Nottingham,
grounded on the publication of the said paper in the manner above stated,
and having prevailed with the grand jury to find the bill,
to which Hart pleaded not guilty,
the cause was tried at Nottingham the 30th of 3rd month, 1762, before judge Clive,
when it was insisted by Francis Hart`'s council,
that the paper in question was not a libel,
(according to the legal definition of a libel laid down in Hawke)
being only an ordinary and usual act of church discipline,
according to the rules of the religious society to
which the said Mary Jerom the prosecutrix had belonged,
and that what was called a publication of it,
was nothing more than a compliance with the said rules,
without any malice in Francis Hart towards the prosecutrix,
or intent to blacken her reputation or expose her to public hatred, contempt or ridicule.
And the judge in his charge to the jury declared as his opinion,
that the paper in question (notwithstanding the endeavours used
in framing the indictment to extract scandal out of it,
by means of forced constructions,
with a view to make it a libel) did not really contain such scandal, nor did it,
under the circumstances in which it appeared to the court, amount to a libel.

Notwithstanding which, the jury after going out of court,
and deliberating about three hours upon the matter, brought in their verdict,
finding the defendant guilty,
contrary to the general expectation of those who were present at the trial,
who from the judge`'s charge to the jury were persuaded
that he would have been acquitted.

Neither could the judge forbear expressing his surprise when the
jury returned him their verdict (which was at his lodgings,
the court being adjourned) and to show them that he differed in sentiment with them,
he told them he would take care the fine should be very small.
Francis Hart finding himself greatly aggrieved by this verdict, did,
by advice of his counsel on the 10th of 11th month, 1762,
move the court of King`'s Bench for a new trial.
On hearing the nature of the cause opened by his
counsel which was confirmed by the judge,
who tried the cause, who added his dissatisfaction at the verdict found by the jury,
the court ordered the prosecutrix`'s counsel, sergeant Hewit,
if he had any cause to show against the motion he should urge it then,
for that they would not give so much countenance to the prosecution,
as to make a rule to show cause;
and accordingly the court made an absolute rule for a new trial.
Immediately upon which sergeant Hewit came out of the court,
and told two friends then present, that if the plaintiff would be advised by him,
he would take care the defendant or his friends should have no further trouble; and,
as far as appears, there was no further procedure in the matter.

The injudicious and illegal verdict of the Nottingham jury in this case
might have been productive of very troublesome consequences to the society,
if Francis Hart and his friends had quietly submitted under it.
But the judgment of the King`'s Bench both before and after the trial,
exhibiting a clear evidence that in the concurring opinion of the justices of that court,
the writing in question, under its circumstances, was not a libel;
but as this society was legally tolerated,
and as every orderly society civil or religious must
have some common principles and rules of conduct,
as external marks of discrimination between those who are members and those who are not,
the simple declaration that any person for the causes specified
had forfeited his or her membership therein was not only no libel,
but requisite to the well ordering of any society.
This judgment of the principals of the law prevented this high spirited
woman from carrying her resentment to the length she designed,
to oblige the monthly meeting of Nottingham to erase all their proceedings in her case.
Her counsellor, most probably,
had informed her that in case of a new trial it would be likely to go against her,
and if she did not give up the cause, it must go on.

The final termination of this affair did not only release this
innocent and worthy man from further trouble and perplexity;
but had a beneficial tendency to discourage some others from similar proceedings.

The nation had been for several years engaged in a war with France,
which was not yet terminated, when the present king ascended the throne,
but was carried on for a year or two longer against France and Spain in conjunction.
It was at last terminated by a treaty of peace concluded at Paris, the 10th of 2nd month,
1763.
In consequence whereof friends at their ensuing yearly meeting
thought it expedient to present an address to the king,
and appointed a committee to draw one up, which being done,
was presented to the king by a deputation of said meeting, and read by John Fothergill,
who introduced it with the following preface.
"`I think myself happy in being appointed once more to convey
the sentiments of the people called Quakers to the king,
and at the same time to have it in my power to acquaint him,
that the address which I beg leave to offer to the king,
was proposed and solemnly and unanimously agreed
to in a very large assembly of the aforesaid people;
the only difficulty attending it being the choice of terms sufficiently strong,
in which to express our duty and affection.`"

[.embedded-content-document.address]
--

[.letter-heading]
To George III.
King of Great Britain and the Dominions thereunto belonging.

[.blurb]
=== The humble Address of his Protestant Subjects the People called Quakers.

[.salutation]
May it please the King,

Being met in this our annual assembly from various parts of Great Britain and Ireland,
for the worship of Almighty God, and the promotion of piety and virtue,
we embrace the opportunity which the restoration of peace affords us,
to testify our affection to thy royal person and family,
and our dutiful submission to thy government.

To a people professing that the use of arms is to them unlawful;
a people who reverence the glorious gospel declaration of good will to men,
and fervently wish for the universal establishment of peace,
its return must be highly acceptable.

To stop the effusion of blood, to ease the burden of thy people,
and terminate the calamities that affect so large a part of the globe,
we are persuaded were thy motives to effect the present pacification;
motives so just in themselves, so full of benevolence and humility,
demand our united and cordial approbation.

May the sovereign of the universe, who created all nations of one blood,
dispose the minds of princes by such examples,
to learn other means of reconciling their jarring interests and contentions,
than by the ruin of countries and destruction of mankind.

The proofs we have received of thy royal condescension and indulgence,
the lasting impressions of gratitude to the memory of the kings of thy illustrious house,
fill our hearts at this time with the warmest sentiments of affection and duty.

Strongly impressed by such sentiments we return to our respective habitations,
with full purpose to cultivate as much as in us lies, a spirit of harmony and concord,
so essentially necessary to the dignity of the crown and happiness of the subject.
May God, the source of every blessing, the fountain of every excellence,
ever graciously direct thy steps and preserve thee long to rule over thy extensive dominions,
with that wisdom, moderation and equity,
which effectually secure to princes the cheerful obedience of their people,
and transmit their names with deserved honour to posterity.

--

To which the king was pleased to return the following answer.

[quote]
____
These repeated assurances of your affection to my person and family,
and of your duty to my government,
are agreeable to me and cannot fail to insure to you the continuance of my protection.
____

In the year 1763, died John Goodwin of Eskyrgoch in Montgomeryshire, North Wales,
a man of a low station in the world, yet an eminent minister of the gospel,
being instrumental to turn many from darkness to light,
and from the power of Satan to the power of God;
so that he might well be numbered among the valiants of Israel,
and has justly been esteemed one of the principal worthies of our age.

His father and mother were both convinced of truth about the same time,
and received it in the love of it.
At that time his father was clerk to the parish and master of the free-school thereof;
but upon his joining with friends, and giving up faithfully to divine conviction,
he was turned out of both these places, and obliged to have recourse to hard labour,
wherein his mother heartily joined; but John, their eldest child,
then well grown toward the state of a youth, not understanding their case,
thought them fools to turn Quakers, and resolved he would not be like them in that;
nor did they offer any compulsion to him therein.
But their prayers, put up to the Lord for him, were manifestly answered,
and they had in their son the comfort they desired.
At this time friends were grown numerous in Wales; but soon after,
by the encouragement given by William Penn,
most of the friends in some parts of that principality removed and settled in Pennsylvania,
and amongst the rest John`'s father and mother, with most of their children.
From inclination, he would have removed with them;
but a higher power directed his stay in his native land;
and to that he gave up father and mother and everything.
This account of John Goodwin is principally taken
from the writings of a friend lately deceased,
who received it from his own mouth.^
footnote:[See the life of James Gough.]
The great favours of the Lord to him, he recounted to the following purport,

[.embedded-content-document.testimony]
--

When the Lord pointed out poor Wales as a field of labour for me,
he promised that if I was faithful to him in it,
he would be with me and favour me therein;
and now I have in my heart a testimony for him in my old age,
that he hath abundantly made good his promise to me, both outwardly and inwardly,
far beyond what at that day I could have ever expected.

--

In his early days he lived and maintained his wife and family by the labour of his hands,
on a farm of four pounds a year; but at length was enabled to purchase it,
and so improved it, as that it became worth six pounds a year.
The first journey he travelled in the ministry,
he had then got of clear money about forty shillings;
and he was free to spend it (if there was occasion) in the Lord`'s service,
knowing that he could enable him to get more.

When he first began to entertain travelling friends, he had but one bed,
which he left to them, he and his wife taking up their lodging in the stable.

He filled up the several duties of life with good repute, being an affectionate husband,
a tender father and a good neighbour.
He was of an upright life and conversation, a fervent lover of the cause of truth,
and zealous for the support of its testimony in all its branches.

He continued fresh and lively to old age, and about three weeks before his decease,
at the last public meeting which he attended,
he was enabled to bear a testimony in the life and power of truth,
in a very remarkable manner, and after meeting said, he was fully clear of the people,
and released from that service; signifying, his time here was near a conclusion,
and that now after a painful affliction, he should soon be at rest with the righteous,
for which he longed, yet said, "`Let patience have its perfect work.`"

During his illness he appeared to be in an heavenly frame of mind,
abounding with praises to God for his continued mercies,
often expressing "`How valuable is the enjoyment of the love of God on a dying bed.`"
He desired his love might be remembered to his brethren and sisters in Christ,
being sensible and clear in his understanding to the last hour,
he quietly departed this life, as one falling into a deep sleep, the 7th of 12th month,
1763, aged 82 years.

[.embedded-content-document.testimony]
--

The foregoing narrative of the life of this worthy elder may convey profitable
instruction to every class of readers whether of high or low degree.^
footnote:[Life of James Gough.]
To the former a lesson of instruction how humbly thankful they ought to be to
the gracious Giver of all good things for his extensive bounty to them,
when they consider this truly good man, in circumstances,
which we should reckon mean indeed, and a manner of living suitable to his circumstances,
bearing a lively and grateful testimony to the goodness,
mercy and truth of the Lord in his gracious dealings with him.
Also when he dedicates his little all (in faith) to his Lord`'s service,
doth he not in the silent and reaching language of example,
convey this intelligence to thy soul, who art blessed with abundance?
Go thou and do likewise; honour the Lord with thy substance,
and the first fruits of thine increase; love mercy, and walk humbly with thy God;
deeply pondering in thy heart, how much owest thou to the Lord?

And those of low circumstances from hence may learn,
that happiness is not confined to any particular station of life;
but is the result of observing the law of God in the inward parts,
being (as it prescribes) content with the things which we have, not minding high things,
but reducing our desires to the level of our station in life,
that so we may fill it with propriety.
If we thus walk by the unerring rule of truth, though we be esteemed poor in this world,
we shall be rich in faith, and, with this good man, enjoy,
in the obscurity of the humble cottage what palaces too seldom afford, solid content,
the consolation of a conscience void of offence, and in reward of well doing,
the peace of God that passeth the understandings of men.
The most splendid and extensive earthly possessions,
when laid in the balance against durable possessions like these,
are indeed as nothing and lighter than vanity.

--
