== Book IV. Chapter XV.

[.chapter-synopsis]
* Public Affairs
* Rise of the Separation of John Wilkinson and John Story
* Causes thereof
* They endeavour to form a Party and cause a Division in Westmoreland
* Friends of that County refer the Matter to some Friends of the neighbouring Counties
* Who give Judgment against the Authors of the Separation
* Which is confirmed by a general Meeting at Drawell
* The Subject of this Separation brought before the yearly Meeting
* William Penn writes upon this Subject
* Robert Barclay publishes his "`Anarchy of the Ranters`"
* Which draws upon him the Calumny of the Party
* William Rogers an advocate of their Cause
* Publishes a Book under the Title of "`The Christian Quaker`"
* Thomas Elwood and George Whitehead reply thereto
* William Rogers`'s Challenge to the yearly Meeting accepted
* He quits London suddenly

Ever since the king dissolved the Oxford parliament,
the court triumphing in the depression of the country party,
went beyond all bounds of moderation;
for besides the violent invasion of religious liberty
in the oppressive persecution of dissenters,
the whole power of the nation being wrested by the
executive part of the government without control,
the civil liberties and peculiar privileges of the subjects
were not left uninfringed by the hand of arbitrary sway.
After the violence committed on the citizens of London,
by extorting their charter into the king`'s hands,
the other corporations were prevailed upon to deliver up theirs,
and accept such others as the court would grant;
for after the city of London had been obliged to submit,
it seemed in vain for any other to withstand a power too absolute to be controlled.
But although the ardor of opposition was damped, it was not extinguished,
but lay as embers smothered in the ashes, ready to burst into a flame,
whenever it should find vent.

Many of the country party, and particularly their leaders,
viewing with extreme uneasiness the arbitrary proceedings of government,
and considering the liberty and property of the subject as lying at the king`'s mercy,
thought it requisite that some measures should be taken for the preservation thereof,
to which (it`'s like) they still thought the exclusion of the Duke of York necessary,
and for this purpose they held several consultations,
of which information being given to government, several persons were taken up, tried,
and executed for a plot against the King and the Duke of York,
the principal of whom was Lord Russel, son of the Earl of Bedford,
who having shown a determined zeal for the exclusion of the duke from the crown,
is thought by many to have fallen a sacrifice to the resentment of the court,
and that the charge of high treason was not legally proved against him;
much less against Algernon Sidney, Esq; who also lost his life on a scaffold,
on account of the same plot.

The discovery of this plot, whatever it was, and the executions consequent thereto,
gave new occasion of exultation to the court party,
and strengthened the hands of the government and persecuting magistrates,
both by weakening the opposite party,
and by furnishing a plausible pretext for rigorous measures
under the mask of vigilance for the public security,
and guarding against plots.
Through the rancour of party-prejudice the dissenters in general were,
by the reigning party, represented as rebels and plotters,
and renewed occasion taken from thence to proceed against them with fresh vigour;
and the Quakers amongst the rest suffering under the weight of additional oppression,
and thinking themselves called upon to take away the occasion sought against them,
by exculpating their society from any concern in plotting or acting against government,
presented the following address:

[.embedded-content-document.address]
--

[.letter-heading]
To the King.

[.signed-section-context-open]
The humble address of the People commonly called Quakers:

[.salutation]
Oh King,

The king of kings and lord of the whole earth incline thy
heart to do that which is just and merciful in his sight,
and to make such clear and equal distinctions,
as that the innocent may not suffer in any case for the guilty,
that it may ever redound to thy honour and safety, and thy peaceable subjects comfort.

Our innocence, love and good-will to thy person and the government,
that God has committed to thee, encourage us in this our humble address and application.

Whereas the late plot against the king, and his brother the Duke of York,
etc. is made an occasion to persecute many of us
for our religious meetings more severely than formerly,

We do solemnly declare, that `'tis known to the Divine Majesty,
and the all-seeing wisdom whereby king`'s reign and princes decree justice,
that our manifold, extreme and continued sufferings, being only on a religious account,
have not been the least motive or provocation to us to desire, much less to contrive,
the least hurt either to thy person or government,
or to the person of thy brother the Duke of York, etc.
We are clear in the sight of God, angels and men,
from all hellish plots and traiterous conspiracies,
and from all murderous designs and undertakings against the king, his brother,
or any person on earth whatsoever, being works of the devil and darkness;
having contrarywise learned of Christ Jesus our Lord,
by his light and grace in our hearts, not so much as by force to defend,
much less avenge ourselves for injuries done us,
but to commit our cause to him that judgeth righteously,
as peaceable followers of our Saviour and Redeemer,
in his patient example and sufferings, who is the prince of peace.
O king, we do further declare,
that God Almighty hath taught and engaged us to acknowledge and actually to obey magistracy
(as his ordinance) in all things not repugnant to his law and light in our consciences,
which is certainly agreeable to the holy scriptures,
and admits not of any immoral or injurious action.
And that even, where through tenderness of conscience we cannot conform,
`'tis our duty patiently to suffer, and not to rebel nor seek revenge.
And we hope, by his divine grace,
ever to demean ourselves as peaceable-minded Christians,
in our conversations under the civil government.
And as we do sincerely and with reverence confess
to divine power and providence in thy restoration,
and the preservation of thy person hitherto,
so our prayers and supplications are to the Almighty for thy future safety and peace;
and that in a thankful remembrance of God`'s great mercies towards thee,
thou mayest be thereby obliged to show mercy,
and to relieve the oppressed from these unmerited afflictions and persecutions,
which a great number of us, thy peaceable subjects, do even at this day suffer under,
in our persons and estates, not only by laws made against,
but also by laws never intended against us; and which is more extreme,
divers severities of late have been, and still are inflicted,
for which no colour or pretence of law have been or can be alledged,
several jails being so filled as that they want air,
and many innocent persons are held under extreme distress, without regard to age,
sex or condition, to the loss of some lives already, and apparent hazard of many more,
if not to the endangering infection in divers cities and places in this nation;
and many houses, shops, barns and fields are ransacked, and swept of goods,
corn and cattle, tending also to the great discouragement of trade and husbandry,
and to the impoverishing of a great number of quiet and industrious people,
and for no other cause but for their religious worship,
and the exercise of their tender consciences towards Almighty God that made them,
who is the sovereign lord of all, and king in men`'s consciences.

Therefore we humbly entreat thee, O king, in princely justice,
christian charity and compassion, to open our prison doors, and take off our bonds,
relieve the innocent and oppressed in thy land that fear God,
and (in conversation) truly honour the king;
and suffer not the ruin of such as are quiet in the land,
nor of the widow and the fatherless, for their peaceable consciences,
to lie at the door of a prince professing the tender and compassionate religion of Christ.

--

Although the king (who did not naturally delight in cruelty) seemed
affected with this exhibition of unreasonable and unmerited sufferings,
and after George Whitehead, A. Parker, G, Latey and F. Camfield, who presented it,
were withdrawn,
expressed himself (as they were in formed) to one of his courtiers standing by;
What shall we do for this people,
the prisons are full of them?`" The party to whom he addressed this query,
to divert his attention therefrom, drew him into conversation upon some other topic,
so that little or no relaxation of the oppressive measures resulted from this address,
nor during the remainder of this monarch`'s reign.

While the people called Quakers were thus harassed by persecution from others,
there had arisen a dissent among themselves, which was Wilkinson,
now of some years standing.
It took its rise from a difference of sentiment in relation to church discipline,
a matter not easily settled,
so as to guard against the subjecting of conscience
to an undue ecclesiastical authority on one hand,
or an unlimited liberty introducing anarchy and confusion on the other.
And although the discipline established among this
people appears calculated to avoid each extreme,
as it relates to moral conduct more than to nice speculative points of religion;
yet almost from its first establishment, jealousies were entertained thereof,
and the establishment opposed by several of the members from different motives:
By some from disgust,
because they could not obtain that preeminence among
their brethren which they wished for,
without merit to procure it, nor obtain such weight of influence over their meetings,
as to carry things always as they desired;
by others from a want to take a greater latitude of conduct
than the self-denying principles of the society allowed;
to refrain the attendance of religious meetings for fear of human penalties,
and pay tithes and such-like demands to evade suffering.
These were averse to a discipline circumscribing their conduct
within limits they were inclined to transgress,
and for which they did not wish to come under censure or control.
Others mistook a regulation solely designed to guard
the practice of the members from enormity,
and in a regularity of life and manners, consistent with the purity of their profession,
for an attempt to force upon conscience an uniformity of worship,
and speculative notions, and to subject them to ecclesiastical power.
These apprehensions secretly spreading in the hearts,
and private conversations of the dissatisfied,
at length broke out in a public opposition to the body of the society,
and chiefly to the most distinguished members thereof.

The leaders of this opposition were two north-countrymen, John Wilkinson and John Story;
who having appeared as ministers,
and not keeping in the humility becoming their stations,
but thinking of themselves more highly than they ought to think,
began to consider themselves as elders worthy of preeminence,
and to look for greater deference,
than the most sensible part of their brethren thought it right to pay them;
who rather warned them of the danger they appeared to be in, of losing themselves,
by indulging an aspiring mind.
Such admonitions were very ungrateful and mortifying to their pride,
and perceiving thereby that they were not in the honourable
estimation with their friends of sound judgment,
which they affected, they let in a disgust and grudging against them;
and to strengthen themselves,
endeavoured to gain adherents from amongst the looser and weaker members of the society,
by soothing doctrines to the favourers of libertinism,
vilifying the religious care of friends to preserve them
in an orderly and christian conversation and practice,
as an imposition on their gospel liberty;
and by wily insinuations to the more simple and honest,
as if the body of friends were apostatized from their original principles,
and instead of referring them for direction to the light in themselves,
were now drawing them off therefrom to the doctrines of men.
By such means drawing a party into their own sentiments and views,
they caused a rent and division in the quarterly meeting of Westmoreland,
to which they belonged.
The judicious members of this meeting with pain observing
the dangerous tendency of these proceedings,
to destroy the peace of society, and to introduce contention into their meetings,
established for edification;
to prevent the hurt and wounding the peace of mind
naturally resulting from unedifying disputes,
used christian endeavours to reclaim them,
by calm reasoning to convince them of the prejudicial consequence
of their litigious proceedings to themselves and to the society,
by earnest entreaties to return to a state of greater humility and nearer
unity with the body of which they professed themselves members;
but all their endeavours were frustrated,
by means of the unreasonable prejudice which they had imbibed
against the most considerable members of their own meetings,
and of the society at large; looking upon it, it`'s like,
in the prevailing vanity of their minds, as a more splendid situation,
to be leaders of a party in the wrong,
than to lose their distinction by ranking again with a society,
amongst whom the superior qualifications of many members in capacity
and virtue might involve them amongst the common mass,
and with whom their credits, they imagined, was impaired;
so that they treated all the well-meant endeavours of their best friends,
for their own and the general good, with contempt,
and persisted in their opposition with a spirit which threatened an open breach;
to prevent which, if possible,
the quarterly meeting of Westmoreland thought it expedient to refer the
case to the judgment of unprejudiced friends of the neighbouring counties,
who had no concern in the differences amongst them,
and accordingly at their request six of the most eminent and judicious friends of Cumberland,
(amongst whom was John Burnyeat,
from whose narrative this extract is made) and several of Yorkshire,
went over to a meeting appointed by the said quarterly meeting,
on purpose to hear and determine the matter of difference;
but their opponents would not appear, though duly apprized of time and place,
but by letter refused to come, and disowned the meeting.

These friends of the adjacent counties being unwilling to come
to a judgment without hearing both parties concerned face to face,
desired another meeting, to which friends of Westmoreland readily assenting,
it was appointed at Milthrop next day,
and the said mediators themselves went as messengers to Wilkinson, Story and others,
to desire their attendance at the meeting; but they were so elevated in their minds,
and so confident in their own opinion, that they treated them,
their message and cordial advice, with slight and contempt;
and by their reflections and conduct manifesting their spirits to be wrong,
and that they were not by any means to be reconciled to their friends,
or to be prevailed upon to come to a candid and sober
discussion of the subjects of their discontent,
or to meet the complainants face to face.
The friends called in as mediators having heard them in such manner as they could,
proceeded to give a second hearing to those of the meeting aggrieved, which having done,
they withdrew to consider the whole matter among themselves;
and having taken down the heads in writing, after a solid conference thereupon,
they came unanimously to the judgment,
That seeing these men had set themselves against every approach to a reconciliation,
and slighted the tenderest advice,
entreaties and persuasions that could be extended to them,
they had dissolved the bonds of unity with the society,
by a public opposition to the good order established therein;
and appearing determined to continue in their opposition,
and they having cleared themselves by tender admonition to them,
that they were now authorized to testify against them and their spirit;
and accordingly drew up a testimony,
and left it with friends of the quarterly meeting of Westmoreland.
These meetings were held the latter-end of the year 1675.

This judgment increasing the discontent and clamour of this restless party,
who seem to have had a life in contention and railing; the society, out of condescension,
to make another trial if they could at all be won upon, appointed a meeting at Drawell,
near Sedbergh in Yorkshire, on the border of Westmoreland,
to give them a fair opportunity of being heard upon the subjects of their discontent.
The friends who had before drawn up the testimony against them attended,
with many other ancient friends from other parts,
and gave these dissatisfied persons a full hearing.
They spent four days successively in the patient and full
inquiry into the disagreeable subject of this difference,
and plainly perceiving that it proceeded from a spirit of contention and
opposition to the introduction of regularity and good order into the society,
they besought them, with an affectionate tenderness,
to return to that love and pacific disposition,
which cements the community in union and mutual benevolence; but still,
all endeavours paving ineffectual to reclaim them,
and they obstinately persisting in their opposition, this meeting also,
enlarged by the attendance of elders and unprejudiced members from several parts,
confirmed the judgment of the former, which disturbed the opponents so far,
that they soon after detached themselves entirely from the society,
and set up a separate meeting.

The yearly meeting soon after coming on, this division in Westmoreland,
with other important matters, engaged the attention and consideration thereof.
In result the said meeting wrote two epistles,
one of caution and advice to Wilkinson and Story, as leaders of the opposition,
to dissolve their separate meeting, and to be reconciled to their brethren,
before they went abroad to offer their gift;
the other epistle was directed to their meeting, advising them to withdraw therefrom,
and return to their former fellowship with the society.
Yet still the well-meant advice of their friends
had no prevalent effect with the greater number,
as the arrogance,
obstinacy and bitterness of their spirits seemed the more
confirmed by all the endeavours used to allay them.

This difference about church discipline drew from William Penn a small treatise,
entitled [.book-title]#A Brief Examination of Liberty Spiritual,#
designed to inform the judgments of the dissatisfied.
Robert Barclay also took up his pen upon the same occasion,
and handled the subject more copiously,
in a piece under the title of [.book-title]#The Anarchy of the Ranters and Other Libertines,
the Hierarchy of the Romanists and Other Pretended Churches, Equally Refused and Refuted.#
In which, with his usual clearness and strength of reasoning,
he vindicated the discipline established amongst this people against those,
who accuse them of confusion and disorder on one hand,
and such as calumniate them with tyranny and imposition on the other:
He drew upon himself much reproach which and invective from these separatists,
who imagined his work was pointed at their dissent,
and found his arguments too conclusive to answer.
They called his sincerity in his profession in question,
insinuating he might be popishly affected, if not a papist,
being educated in France under an uncle that was a papist, if not a priest,
and maintained church authority upon the same principles, which the Romanists have done:
But what will not prejudice misrepresent?
He all along maintains it on different principles,
and much of the work is employed in showing the difference.

Of these leaders of separation, Story was the more considerable among their partizans,
and more active in propagating the dissent in other parts of the nation.
For this purpose he travelled in sundry parts,
but it was in Bristol and some of the western counties that he gained most adherents;
amongst these, William Rogers, a merchant of Bristol, a bold and active man,
entertaining a high opinion of his own capacity and abilities,
stood forth as champion of their cause:
He first discovered himself as such in advancing
sundry objections to Robert Barclay`'s book,
which he handed about in manuscript about the year 1677; upon which,
at Robert Barclay`'s request, he met him in London,
in order that by a cool and moderate conference before
divers friends from different parts of the nation,
Robert Barclay might have an opportunity of explaining the passages objected to,
which he apprehended William Rogers had misunderstood,
in order that by satisfying and convincing him of his mistakes,
an unedifying controversy might be prevented.
In consequence of this conference, William Rogers wrote a letter to his friends,
in which is the following passage: "`The meeting was this day had,
and in it a christian and very fair debate, to the satisfaction of both of us,
as far as I can understand;
and the matters chiefly objected by me were fairly and brother like, and in much love,
discoursed; and upon the whole matter I am satisfied,
that Robert Barclay is not principled so as I and others have taken his book to import.`"

Yet notwithstanding this fair concession,
apparent candour often wants a bottom of sincerity with those who have
suffered their tempers to be embittered with the spirit of party.
Some months after this the said William Rogers and his adherents wrote
sundry other papers against Robert Barclay`'s book and principles,
not devoid of uncharitable reflections upon the author,
and spread them abroad unknown to him, while he was confined in prison at Aberdeen.
This ungenerous treatment occasioned Robert Barclay to write a
vindication and explanatory postscript to his [.book-title]#Anarchy of the Ranters,#
in order to give satisfaction to all of the society,
but those who through prejudice seemed resolved not to be satisfied.

In the year 1682 William Rogers appeared in print in a quarto volume,
to which he gave the pompous title of [.book-title]#The Christian Quaker,
Distinguished from the Apostate and Innovator,#
under the former description comprehending himself and his own party,
and representing the main body of the society as apostates and innovators.
This book, which soon sunk into oblivion,
was more remarkable for passionate intemperance of language than soundness of reasoning,
abounding in personal invectives against many of the most eminent members of this society,
but the chief force of the envy of him and his party was pointed at George Fox,
as being the instrument of establishing that good order
which they wanted to have considered as a grievance.
Both their discourses and writings manifested the deep prejudice,
they had imbibed against this irreproachable character,
which answered not their design of lessening him, or exalting themselves,
or their cause in the eyes of the society, or the world;
but afforded him an opportunity of manifesting his
steady adherence to the inward principle of truth,
and the firmness of his mind in a new light,
being preserved by conscious innocence in rectitude and dignity of conduct,
as superior to wrath from the shafts of envy, as to fear from the oppression of power;
he bore all their weakness and malice with invincible patience,
forgave all their bitter speeches, praying for them,
that they might recover a sound mind, not returning reflection for reflection,
but charitably endeavouring to convince them of the
danger of the error into which they were fallen,
and the hurt they had sustained thereby;
and by verbal admonitions and various epistles to preserve
the society at large from being entangled in the like snare,
laying open the subtlety of that spirit by which they were actuated,
in entertaining and spreading groundless jealousies of the religious
care of friends over each other for their good.

The aforementioned performance of William Rogers
meeting with great applause from his own party,
increased his vanity to that degree,
that he came up to the yearly meeting at London in 1682;
and at the conclusion thereof he gave William notice in writing to this effect,
viz. "`that if any were dissatisfied with his book,
he was there ready to maintain and defend,
both it and himself against all opposers.`" This vaunting
challenge was neither dreaded nor slighted,
but an answer immediately returned him in writing,
that "`as many were dissatisfied with his book and him,
he should not fail (God willing) to be met by the sixth hour next
morning at the meeting place at Devonshire house.`"

The meeting was held accordingly and continued till noon,
when it appeared that notwithstanding his vaunt he
was not equal to the task he had undertaken;
for although he was attended by many of his party to abet and assist him,
he was so fairly foiled, and his errors and petulance so fully exposed,
that he quitted both the meeting and the city abruptly, refusing a second meeting,
which was offered for the further discussion of the subject of difference,
leaving this frivolous excuse for his precipitate retreat,
that he had before given earnest for his passage in the stage coach home,
and was not willing to lose it.

This book of his did not pass unanswered, Thomas Elwood published a reply,
under the title [.book-title]#An Antidote Against the Infection of William Roger`'s Book,#
miscalled the [.book-title]#Christian Quaker,# answering it paragraphically.
To which it doth not appear that any rejoinder was ever given.
George Whitehead also published remarks upon it, in a piece,
entitled [.book-title]#The Accuser of the Brethren Cast Down.#

It hath been remarked, that the establishing of discipline,
and instituting of men`'s and women`'s meetings for the supporting thereof,
was the original cause of this dissent and temporary separation.
The separatists urging against them,
that every man having received a measure of the spirit of God,
ought to follow that as his leader, without regarding the prescriptions of men;
that those meetings of discipline were therefore needless,
as being employed in prescribing rules to the members of the society,
and requiring their observance thereof,
drawing an invidious parallel between them and the Romish councils and their decrees;
that such meetings and rules were an imposition upon conscience,
and in them some men were set up to usurp authority in the church over their brethren;
that nothing ought to be given forth in the church
of Christ but by way of advice or recommendation;
and that every man ought to be left at his liberty to act
according to the light of his own conscience without censure,
or being accountable to any man, but only to God, the sole proper judge of conscience.

Against women`'s meetings they more particularly objected,
as usurping authority in the church, contrary to the apostle Paul`'s prohibition.

In support of the discipline introduced into the society it was advanced,
in opposition to such arguments; that the Spirit of God is one and the same in all,
and leads all who are faithful to its dictates into all truth and righteousness,
into unity and brotherly kindness; that God, who, according to the apostle`'s testimony,
is a God of order and not of confusion,
doth not by his Spirit lead any into confusion and disorder;
but that they who walk in the light, as he is in the light,
have fellowship one with another; that therefore the only rational ground of dissent,
as following the leadings of the Spirit, without regarding the prescriptions of men,
must be, because these prescriptions are opposite to, or in consistent with,
the dictates of the Spirit of God;
that the scriptures of truth are allowed to be written by holy men of old,
as they were inspired by the Holy Ghost, and this Spirit is not inconsistent with itself;
if therefore these prescriptions of men are consonant to and confirmed by the scriptures,
he who follows the leadings of the Spirit can have no reason to reject
prescriptions dictated by the same spirit or regulated by that rule which
is universally acknowledged by Christians to have been dictated thereby,
that therefore this argument, plausible as it may appear, proves nothing,
'`till the prescriptions be first proved inconsistent
with the scriptures of truth or right reason,
which they apprehended,
had not been done in the case between the society and the discontented party.
That the parallel attempted to be drawn between the church government adopted by friends,
and that of the church of Rome, was ill founded,
their principles and spirit in the administration of this government,
and the ends to which it was directed, being quite different both in nature and object:
In nature, as not being coercive or penal upon the persons or estates of such as dissent,
and that not only for want of power,
but because such penalties are unauthorized by the
Gospel and primitive practice of the church;
in object, because the former regards matters of faith and worship,
but the latter only orderly conduct, agreeable to the principles of the society.

Hence the plea of liberty of conscience,
which hath been reasonably advanced by protestants
against the hierarchy of the church of Rome,
as establishing articles of faith, institutions of worship, and ceremonious observations,
for which they have no authority from scripture, or the primitive practice of the church,
is groundlessly or absurdly advanced in opposition to the discipline of this society:
For although we may reasonably plead a scruple of conscience
against acknowledging such an article of faith,
or practising such an institution of worship as hath not God for the object;
yet we cannot reasonably plead the like scruple against supporting the poor,
visiting the sick, ending differences, reproving the licentious, reclaiming backsliders;
neither against punctuality to our engagements; doing justly and living temperately;
nor against obtaining the consent of parents and relations concerned in cases of marriage;
or to give them, or the society satisfaction as to clearness from all others;
and to wait previous to marriage for due inquiry to be made thereinto.
That in society, meetings of discipline are so far from being needless;
that they are both necessary and useful for attaining
the best ends of uniting together in society.
All societies, for instance, have poor, sick and aged members, widows and orphans,
who demand the care of the body;
this care cannot be taken effectually without some method;
nor that method universally settled but by the deliberation and concurrence of the community:
And further, all societies marry, trade and converse,
and have one time or other some who are unjust, litigious, licentious, and others,
who may not fall under the censure of those without,
yet violate the testimony and principles upon which they joined themselves in fellowship.
Has then the society no power to establish such regulations
as may prevent disorder and scandal?
And is not the body at large the properest judge to deliberate and determine,
what is the fittest method to be pursued in such cases?
That although God be the only proper judge of conscience,
and man be accountable to him alone for the inward persuasion and frame of his mind,
yet for his visible conduct and conversation, which are cognizable to men,
he is accountable not only to civil but also to religious society,
while he continueth a member thereof,
because the reputation of the society is virtually interested therein,
and may be materially injured by a deviation from
the rectitude of conduct professed by them,
as a consequence of their principles;
and that to preserve a consistency of conduct with virtuous,
just and benevolent principles, a christian community or church, properly so called,
hath a power not only to issue advice and recommendations,
but to establish rules of discipline for regulating this external conduct,
having the precedent of the christian church in its purest state;
for we are clearly informed in the Acts of the Apostles,
that they made rules for the conduct of the members of the church,
and dispersed them to the believers for their observation.
"`As they went through the cities they delivered them the decrees for to keep,
which were ordained of the Apostles and Elders which were at Jerusalem.
And the churches were established in the faith, and increased in numbers daily.`"
Acts 16: 4-5.

And as to their objections to the women`'s meetings which were established
in suffering times for the purposes of assisting in the care of the poor,
the sick and the imprisoned, the apostle`'s prohibition affects them not;
it being absurd to imagine that he ever meant to discourage religious
women from cultivating the natural tenderness of their hearts,
and following the impulse thereof, inclining them to acts of charity,
in extending a tender care towards their friends in prison, the poor or the afflicted;
and although, since that time, a motherly, watchful care over their own sex,
to preserve them in an orderly conversation hath been devolved upon them,
as the properest to advise and counsel in many cases;
yet their meetings have no aspect of usurping authority over the man,
as they have neither any oversight of the men`'s meeting,
nor were their own meetings and services established but
in compliance with the desire and directions of the men,
from the consideration of the usefulness thereof.

In fine,
the independency claimed by the discontented party
is incompatible with the existence of society;
absolute independency in society being a contradiction in terms.
Walking by the same rule, holding the same principles, and pursuing the same end,
being the outward bond of communion betwixt the members of every visible society.
Take all these away, and the society is dissolved,
and reverts again to unconnected individuals.

The justness of this reasoning was proved by the event, for these separatists,
like the ranters, seekers and other independent societies,
found themselves too loosely compacted to adhere long together;
their connection was so slight that it was soon dissolved,
the more sincere coming in time to perceive the causelessness of their separation,
re-united themselves to the body of the society,
and the rest soon fell to pieces and dwindled away.

The principal part of the public history this year consists of prosecutions,
many of them conducted in a manner in nowise to the
credit of the promoters or conductors thereof,
and of penalties and punishments enormously disproportioned
to the charges brought against the defendants.
The courts of justice, so termed,
seem in many cases to have been influenced in their judgment
merely by the vindictive temper of party hatred;
and the juries, influenced by them, and chosen from men of like temper,
seem in their verdicts to have paid more regard to
the accommodating of the wish of the bench,
than the depositions of the evidence, or the obligation of their oaths.^
footnote:[Of this we meet with a remarkable instance in the course of this year,
in the trial of Thomas Rosewell, dissenting minister of Rotherhithe,
who was accused by three women of having uttered treasonable expressions in a sermon.
They swore to two or three periods, and agreed exactly in their depositions.
Yet Rosewell, in his defence,
proved these women to be of abandoned and infamous characters;
and as to the sermon of which he was accused, several witnesses who heard it,
and some who wrote it in short hand, deposed that he had used no such expressions,
as were sworn against him:
The expressions were so gross that no man in his senses
could be supposed to use them before a mixed audience:
It was also urged that it was next to impossible that three
women could remember so long a period on one single hearing,
who had for got the text of his sermon,
and could not remember one single passage but the words they had deposed.
In short, he defended himself so ably, that the Solicitor-General made no reply.
Yet judge Jeffries, who presided at the trial,
railing in his usual manner against conventicles and non-conformists,
that all preaching at conventicles was treasonable,
so inflamed the party prejudice of the jury,
that they made no difficulty to bring him in guilty.
But the palpable injustice of his sentence being almost universally condemned,
as no better than legal murder, the king,
abashed at the exorbitant lengths to which the pliant
judges and juries now carried their partial resentments,
prevented the execution of the sentence, by granting him a pardon.]
In these circumstances of affairs the dissenters,
who were ranked in the vanquished party, had little room to hope for ease.
The Quakers renewed their application for relief from their grievous sufferings,
but with no better success than before;
the informers and persecuting magistrates assuming
new spirit from Suffering`'s the late executions,
and pretending fresh occasion from the discovery of the late plot,
continued to persecute them by all the variety of penal laws.

The informers harrassed them with insolence, perjury and rapine,
upon the conventicle act, '`till they left some of them neither a bed,
nor even a stool to sit upon,
so that whole families who had supported themselves in decency were reduced to the necessity
of relying upon the humanity of their neighbours for a night`'s lodging;^
footnote:[William Bond, of Bridport in Dorsetshire, at this time an active informer,
was a bailiff, and kept an alehouse; this Bond, and one Bryan,
a lad he had trained to his hand, would make information at all adventures.
He came to a silent meeting, and went away and swore that a preacher was there.
He would sometimes carry prisoners to his house, and keep them there a month together.
He had impudence enough to command and insult the constables and other officers,
and even the justices.
He seized the goods of John Newberry to the value of 30£.
for a fine of 5£. He in concert with William Darby,
constable, pulled the friends out of the meetinghouse one by one,
and carried two of them to his house, where he kept them prisoners.
Darby at another time turned the friends out,
and nailed up the doors of the meetinghouse, sending eight of them to Bond`'s house,
where they were put in a narrow stinking chamber for four days, men and women together,
and not suffered to go out upon any necessary occasion: A bed being sent to one of them,
Bond and his wife took it away, he telling them, they should have no law.
{footnote-paragraph-split}
William Kenway, of Bridport,
being fined 5£. for himself and others meeting there,
Bond and Darby broke open his doors,
kept possession of his house two days and two nights, drank up his beer,
and burned up his wood.
They carried off all they could find within or without
doors to the value of 13£. threatening withal,
that if he brought any more goods into the house they would take them,
insomuch that the man with his family were constrained, in the depth of winter,
to remove his habitation out of the town.
This Bond is represented to have been a man of a seared conscience,
infamous character and debauched morals,
and supported in extravagant living by the plunder of honest men`'s substance.
{footnote-paragraph-split}
Neither age nor sex, nor infirmity,
moved the merciless informers or magistrates to compassion or humanity.
Five women were taken by an informer and constable from a meeting at Ipswich,
and carried before the bailiff of the town, who committed them to prison;
three of them were near eighty years of age, and one of these also blind,
so that she was led between two men to the bailiff`'s house.
This magistrate`'s zeal exceeded his charity or his judgment:
Could he apprehend any danger to government from an assembly of a few infirm old women?
{footnote-paragraph-split}
One John Smith, and one Warner in Leicestershire,
made themselves remarkably conspicuous in all the infamous qualifications of informers;
they would sometimes make their information upon mere conjecture,
whereby two of this society suffered severe distress
for a fine for a meeting they had not been at,
the justice being as forward to convict as they to inform.
Smith, meeting another on the highway,
positively swore before the same justice Lyster what he only imagined,
and obtained a warrant to distrain,
by which he took from the man four cows worth 14£. One Mary
Wood being fined on the information of these men,
they stripped her of all her effects, leaving her nothing to lie on or scarce to sit on.
But amongst the numbers prosecuted by these two men,
and plundered by their extravagant distraints,
the case of John Fox was peculiarly pitiable.
A meeting was sometime kept at his house,
upon which account these men persecuted him with information after information,
and distraint upon distraint for fines of 20£. a
time '`till they stripped him almost entirely,
taking away even the meat in the house, and his casks of beer,
ripping up the matting from the floor,
and digging up a copper furnace and carrying it away,
at the same time rudely abusing him, and calling him ill names,
because upon viewing the warrant,
reading a clause mentioning more than five persons beside the family,
he said it was not true.
About two weeks after this,
hearing that the poor man (made such by their rapine) had got some bedding and
other necessaries into his house for his family (some of whom for want of beds
had been obliged to lodge elsewhere) they came again with officers,
and Smith, in the assumed importance of his office, menaced the legal officers,
If they left any thing in the house to the value
of a penny he would make it cost them 5£. a man;
upon which they swept away all they could find.
The sufferer, his wife, children, and servants were constrained to lodge at other houses,
having neither bed nor bed clothes left,
by which they and their children contracted great colds, it being in the depth winter.
The goods were taken to Warner, informer,
for 2£. 2s. 6d. At last this society was relieved from Smith`'s
persecution by an order of king James to the justices of Leicestershire
to give no sort of countenance to him or his prosecutions.
[.book-title]#Besse# _passim._
{footnote-paragraph-split}
Henry Gates in Sussex was fined 40£. for preaching,
for which he had goods seized to the value of 160£. One Calvert Bristow, a neighbour,
observing the spoil, treated with the officers, who assigned him all the goods,
on condition of his paying 40£. He took away as much
as he thought sufficient to answer that sum,
leaving the rest with Henry Gates, the owner:
he then offered to pay the 40£. to the justices,
upon their making him a valid sale of the goods: this they refused to do,
and directed him to keep the money till the sessions.
Upon this the informers, Henry and Matthew Marrian,
conceived a grudge against Bristow for concerning himself in this affair,
and hindering them from the spoil they aimed at.
Wherefore they endeavoured to suborn one Bennet to swear treason against him.
Bennet, though a very bad man,
was not so hardened in wickedness as to undertake so black a business,
but discovered their design to Bristow,
and also made oath of their attempt before a magistrate:
Upon which the Marrians were sent to jail.
There one of them confessed the whole affair,
and afterwards they were bailed out in order to answer it at the assizes.
However in the conclusion Calvert Bristow was obliged to pay in to the
justices about 64£. 5s. and to repay himself out of Henry Gates`'s goods,
as aforesaid, sold to him.]
and, as if the penalty of the conventicle act, unreasonably severe as it was,
was yet inadequate to the rapacity and avarice of these informers and persecuting magistrates,
in numerous instances they resorted to the more ruinous one of 23 Eliz.^
footnote:[From several persons in Bucks goods were seized under this act,
amounting to 295£. in value,
which were disposed of by public sale for 90£. 2S.
6d. less than one-third of the real value.
From one friend, exclusive of the above,
were taken three geldings worth 23£. and when he appealed to the quarter sessions,
his appeal not being in Latin, was rejected and treble costs given against him,
for which his horses and other goods were taken to the value of 40£.
{footnote-paragraph-split}
Several
friends in Cheshire were distrained under the same act to the amount of
146£. 11s. 2d.
{footnote-paragraph-split}
In Hertfordshire from a few friends
were taken goods to the amount of 190£. and upwards.
{footnote-paragraph-split}
In Norfolk John and William Roe, farmers,
having been prosecuted on the statute for 20£. a month for
twelve months absence from the national worship,
the sheriffs officers came to their house to make a seizure
for 240£. and accordingly seized all their cattle,
corn and household goods,
to the value of 183£. 4s. The behaviour of the officers and assistants was very rude:
They broke open the doors, drawers and chests,
and threatened the servants with sword and pistol.
To make them selves merry they roasted a pig,
and laid so much wood on the hearth that they set the chimney on fire, which,
with their revelling, cursing and swearing,
affrighted W. Roe`'s wife to the endangering of her life,
causing her to miscarry a short time after.]
for 20£. a month for absence from the national worship,
whereby numbers suffered repeated and exorbitant seizures of their effects,
to the great damage or ruin of their outward circumstances.
They continued to be prosecuted in the Exchequer for their tithes;
in the ecclesiastical courts to excommunication, and to premunire for not swearing.
The trials for riots, of which we have given some examples in former years,
were still in use, and the defendants generally brought in guilty,
imprisoned and fined by the partial judges and juries of this corrupt and licentious age,
and the prisons to be crowded with fresh prisoners of this society,
in addition to those already confined.
To detain the reader with a detail of all the particular instances of
oppression they underwent appearing a needless repetition of similar cases,
after a recital of so many preceding, I shalt content myself with a few notes, as before,
in confirmation of this general account thereof.

This year died William Bennet of Woodbridge in Suffolk,
a man of a religious turn of mind from his infancy.
This religious inclination increasing with his years,
incited him to seek out and associate with the strictest sort of professors,
and with this view he frequented the meetings of the independents for some time,
as appearing to him the nearest to purity in profession;
but upon his more intimate acquaintance with them he became dissatisfied with his choice.
When hearing the public testimony of some of the people called Quakers,
he was so affected therewith that he joined their society,
and continued therein a steady, serviceable and honourable member till his death.
He received a gift in the ministry,
and travelled in many parts of England in the exercise thereof,
to the edification of his friends, and convincement of others;
adorning his profession and doctrine by the innocence and integrity of his life,
in so eminent a manner as to gain universal esteem,
and to extort even from the adversaries of his profession
a confession of his personal merit.
Yet his sufferings were remarkable, he appears to have spent,
at least in the latter part of his life, nearly as much, if not more time in prison,
than in the enjoyment of his liberty, not for any real offence,
but for preserving the testimony of a good conscience.
At Bliborough, in 1661,
I apprehend in the general imprisonment in consequence of the rising of the fifth-monarchy-men.
In 1662, he, with several men and women, was taken out of a meeting at Yarmouth,
and sent to prison, where they were confined all together in a noisome unhealthy dungeon,
without convenient food, lodging, or other necessaries;
at the succeeding sessions the women were set at liberty;
and not long after the Recorder released the men also,
no cause of their imprisonment appearing, nor any legal process against them.
The bailiffs, displeased at their release,
presently committed them again by a new mittimus,
of which desiring a copy they received a positive refusal.
How long this imprisonment continued I meet with no account.
In or about 1664 he was again imprisoned in Norwich castle with fifteen others,
who were taken from their religious meetings, and committed for refusing to swear:
He was again confined in the jail of Edmundsbury in 1665, and suffered a very severe,
distressing and tedious imprisonment there; being kept (much of the time) among felons,
for the greatest part of eight years, so closely,
as scarce to go over the threshold for five years together.
At last the king`'s declaration in 1672 delivered him from the hands of his cruel persecutors.
Lastly, in the year 1683, the parochial officers of Woodbridge,
excited thereto by Edward Brume, priest of that place, came to the meeting there,
when a church-warden and constable seized William
Bennet with violence whilst on his knees at prayer,
and haled him and several others before Edward Jenny, justice,
who committed them to Melton jail,
where William Bennet was closely confined until the sessions,
when he was indicted for being at a riotous assembly;
he used many arguments to prove the religious meetings he frequented were peaceable,
and purely to worship God, and pleaded Not guilty to the indictment:
Being then required to give bail for his appearance at another sessions,
and for his good behaviour, for his refusal he was committed,
and brought with others upon his trial be fore Christopher Melton, chairman:
He pleaded his cause with so much force of reason,
that the jury brought in their verdict not guilty.
At the jury which the chairman being displeased,
persuaded them to return and alter their verdict,
upon which they brought him in guilty of being present at an unlawful assembly:
The chairman ordered William to be carried to Ipswich the same day in order to be fined,
it being the sharpest time of that winter, so remarkable for extremity of cold;
in going thither he received much wet, coming it snowing hard all the way;
and coming thither late, and many other prisoners with him,
for want of a bed he was obliged to sit up all night in that wet cold condition,
which so weakened him, who was naturally of a tender constitution,
that he never got the better of it.
At the sessions there he was fined 20£. and sent back to prison.
At the succeeding sessions he was called again, when no mention was made of the fine;
but the court pretending they had a particular order from the king to deal with him,
tendered him the oath of allegiance,
and upon his refusal took an additional occasion of continuing him in prison.
These different modes of persecuting this innocent man show
the unrelenting malice of the ruling party at this time,
and the determined resolution of his persecutors
to prolong his imprisonment to the utmost.
By his close and continued confinement he grew weaker and weaker,
till as many others had done,
he fell a sacrifice to the vindictive temper of partial magistrates,
and the forced construction of unequal laws;
for the hardship of his unmerited imprisonment,
put a period to his existence in the body the 23rd or the 4th month, 1684.

Equally remarkable were the repeated and severe sufferings of Thomas Stordy,
of Moorehouse in Cumberland, who also laid down his life in this year in Carlisle jail,
under a cruel persecution for the testimony of a good conscience.
He was descended from a family of repute in that country,
and born to the inheritance of a handsome estate;
and had his religious sentiments fallen in with the passion for conformity,
now predominant, he might have bid fair for making some figure in his country,
and holding a rank of eminence therein.

But about the term of middle age he became seriously thoughtful about his better part,
where by he was circumscribed in his views and desires
after the vanities and carnal gratifications,
the pomp and the power of this world, and in cited to the pursuit of pure religion,
as the foundation of peace here, and everlasting happiness hereafter:
With this view he joined in society with the independents,
amongst whom he was in particular estimation for his talent in exhortations, expositions,
and such like religious exercises in use amongst them.
After some, time he left them, and joined the people called Quakers,
which in the circumstances of the times was an indubitable proof
of the sincerity of his heart in his religious researches;
when having it in his power to live in ease and affluence, by a temporizing conduct,
what but a conscientious persuasion of acting right
could induce him to embrace a profession hated,
vilified, persecuted and exposed to the loss of all that mankind reckons valuable?
In this society he spent the remainder of his life in near unity with his friends,
and truly respectable in his neighbourhood as a man of a circumspect,
sober and temperate demeanour amongst them, upright in his dealings,
obliging in his disposition, hospitable in his house,
and liberally charitable to the poor around him.
But in this age, at once bigotted and licentious,
virtues the most conspicuous were insufficient to
secure the possessor from the iron hand of persecution,
from priests and priest-ridden magistrates,
who would see no virtue beyond the pale of conformity, nor hardly vice within it,
seeming to place the sum of religion therein.
Thomas Stordy was first imprisoned in the general imprisonment in 1660,
for declining to take the oath of allegiance, and detained in prison nine weeks.
We have already seen his illegal imprisonment at Carlisle in 1662,
and his condemnation in a premunire,
under which he was detained a close prisoner ten years from Carlisle,
his wife and family, until he was released by the king`'s aforesaid declaration in 1672:
His real estate was recovered through the intercession of Charles Howard earl of Carlisle;
but his personal estate entirely lost; and as if his imprisonment,
and the loss of his substance was not a sufficient
gratification of the enmity of the persecutors,
in the year 1670, whilst lying under this confinement, now of eight years duration,
a warrant was granted against his goods and chattles
for a fine of 20£. 10s. upon the conventicle act,
for a meeting at Moorhouse.
Thus was an honest respectable citizen harassed by prosecution upon prosecution,
and penalty upon penalty, by the variety of penal laws now brought into force;
though innocent of any crime against the state:
first arbitrarily imprisoned as seditious, although guiltless of any seditious practice;
again still more arbitrarily imprisoned without apparent cause; and to detain him there,
occasion was sought against him to deprive him at once of his liberty and property,
by a snare laid for the purpose, because he durst not violate the command of Christ,
as he understood it;
fined for a meeting when he was under restraint several miles from it,
and last of all prosecuted by one Launcelot Simpson,^
footnote:[The character of this Launcelot Simpson may be gathered from
a more particular account we have of his treatment of Richard Banks.
This man, one of the same society, being a farmer,
rented some land which Simpson purchased: who, not content with the rent of his purchase,
seemed to adopt a plan for possessing himself of the best part of the tenant`'s property,
and impoverishing him at once.
He prosecuted him in the ecclesiastical court to excommunication,
and under pretence that all he had was too little to defray the expense of the prosecution,
he came one day in the owner`'s absence with an assistant,
and nailed up his granary and barn door, turning out all his thrashers:
He came again in the night when the family was in bed,
and took possession of his stable and cow-house and turned out his cattle,
and the snow lying thick on the ground, some of the young calves perished with the cold,
and others were with difficulty recovered:
He caused the hedge to be torn away from the hay stack, and put his own cattle to eat it.
The poor man had about nine score sheep,
to these Simpson pretended a title and by those means
deterred others from purchasing any of them;
so that after contesting his claim, and the death of near a third part,
the owner was obliged to let Simpson take them at his own price,
which was about one third of the value.
Richard Banks, perceiving he was like to obtain neither quiet nor property,
while exposed to the chicanery and oppression of this man,
took another farm twenty miles distant.
Even thither Simpson pursued him,
and shortly after had him arrested on a writ of excommunication
but this upon examination proving out of date,
his purpose was prevented at that time.
He afterwards caused both the said Richard and his wife to be apprehended together,
and taken away from their children and servants,
by such rude unfeeling persons as are generally employed in such offices,
who would not give them time to leave the necessary directions be hind them,
nor scarce speak to their workmen, having at that time ten men at work.
On their way to prison they met Simpson, of whom Richard demanded before witnesses,
"`If he owed him any thing:`" But the other could not make any demand appear,
only reckoning his imprisonment was for contempt of the law:
Richard then desiring the forbearance of only two days to put his affairs in some order,
Simpson replied, "`He would not give him two hours.`"]
a proctor, on the revived obsolete statute of 23 Eliz.
for 20£. a month for absence from the public worship,
cast into prison and detained there several years, until his death,
which happened the 22nd of December, 1684.
As he sought for solid peace of mind through many tribulations,
he was favoured therewith at his conclusion, for not long before his decease,
being visited by some of his friends,
he encouraged them to faithfulness by this testimony to the advantage thereof,
"`if you continue faithful to the Lord whilst ye live in this world, he will reward you,
as he now rewardeth me,
with his sweet peace.`" His testimony against tithes under
the gospel dispensation was proved to be truly conscientious,
for after he was convinced of the impropriety of the demand,
he not only refused to pay them, but to receive them;
for he inherited from his predecessors an impropriation of 10£. per annum,
which he released to the owners of the lands from whence they accrued (to whom
he thought they belonged of right) by a legal instrument quitting claim thereto,
for himself, his heirs and assigns forever.

Thus the revived persecution was carried on to the
death of King Charles II. without relaxation,
who about this time was taken off in a sudden fit of convulsion or apoplexy,
leaving little less than one thousand five hundred of the
people called Quakers in prison on various prosecutions.
Having now finished the account of this persecuting reign in England,
before I proceed to the transactions of the succeeding reign it seems a proper period
to take another review of the state of this society in other parts of the world,
and first in Ireland.
