== Chapter XVI. Ireland.

[.chapter-synopsis]
* Account of William Morris
* Benjamin Bangs visits Ireland
* At Antrim rudely treated, but has afterwards a solid Meeting
* His Prediction
* He meets with a Company of Men, whose Teacher is fled
* Which affords him Occasion to recommend them a Teacher in their own Hearts
* William Edmundson and Robert Jackson prosecuted for Tithe
* William Edmundson`'s Conference with the Bishop
* Procures their Liberty
* Dissenters ordered to discontinue their Meetings
* Friends continue to meet as usual
* John Burnyeat committed to Prison

This year died William Morris, of Castle-Salem in the county of Cork,
who at the time William Edmundfon was put in the stocks
at Belturbet was an elder of repute amongst the baptists,
and a man in authority, being a captain in the army, a justice of peace,
and commissioner of the revenue;
and upon the occasion remonstrated against the magistracy there,
in favour of William and his brethren, telling these persecuting independents,
the time would come when they would be glad to shelter under their +++[+++the Quakers]
wings: Although he was a man of great abilities,
he had been convinced by a weak instrument,
and it being now known that he had joined this people,
his commissions were taken from him.
But being a person of considerable consequence, both from his station in the world,
and his abilities as a man, he was a serviceable member of this society,
particularly in applications to the government on be half of his suffering friends,
with whom he also shared in suffering.
He wrote an excellent little tract, entitled [.book-title]#Tithes No Gospel Ordinance.#

Benjamin Bangs, from Cheshire, landed in Benjamin Dublin,
and travelled through several parts of this nation,
exercising his ministry to the edification of his brethren,
and their number was increased by the convincement of many,
who before had not professed with them.

In the course of his travels he came to Antrim the inhabitants
of which town were mostly of the presbyterian profession,
sundry emigrants from Scotland having at different
times removed to settle in these parts.
He had a meeting here in the evening, which was greatly crowded by these high professors,
some of whom are said to meeting, have come with a design to oppose him.
The meeting-house being too small to contain the number resorting thereto,
the people without grew very tumultuous and noisy,
and at length while Benjamin was preaching, began to throw pieces of dirt and turf;
upon observing such rudeness, he made a full stop, which occasioned a general silence,
and after a short pause he made this remark,
"`I understand this is a place of great profession of religion.
I am sorry to see so much irreligion as appears amongst you at this time,
through your rude behaviour.
It is not long since I came out of my native country,
and I think it will not be long ere I return again,
and then what shall I say of you to your poor suffering brethren in England?`" This remonstrance,
expressed in great awfulness,
affected the more considerate part of the audience with a sense of the scandal,
which such abusive behaviour brought on their profession of religion,
and therefore exerting themselves to quell the disorder, and putting a stop thereto,
the meeting afterwards was held in great solemnity,
whereby many present were reached to the heart,
and a young man of the popish persuasion convinced,
as were many others in this part of the nation.

Benjamin, to the aforesaid remonstrance, was concerned to add this prediction,
_the time draws nigh that ye will be blown away like chaff before the summer
thrashing floor and the place of your meetings shall not be found;_
which before he left the nation he found to be brought to pass:
After attending the half-year`'s meeting in Dublin, and travelling southward to Cork,
and from thence to Tralee in the county of Kerry,
a place where none of the people called Quakers resided,
and where they were little known; amongst these strangers, to whom,
from a particular impulse on his mind, he paid this religious visit,
he had a comfortable meeting,
under the sense of divine assistance attending him in his service,
and affecting the minds of the people with religious consideration,
with solid impressions whereof they withdrew from the meeting;
and he returned again to the North,
where on the way from Antrim to Grange he observed ten or
twelve men walking along in a very solitary manner,
and it arose in his heart, _These are sheep having no shepherd:_ When he came up to them,
he entered into discourse with them, and inquiring of them,
if they were going to a meeting.
They answered, "`our minister is silenced, for orders are come down,
prohibiting all dissenters from assembling,
now we have no teacher,`" which appeared to him in effect to verify his prediction,
_that their meeting could not be found._
For the inimical disposition entertained at this
time by the ruling party in England against dissenters,
having spread to Ireland,
exerted itself in similar measures of persecution to suppress their meetings,
which produced the effect designed here as well as there,
with the several other classes of dissenters: The people generally, except the Quakers,
declined their public meetings, and their teachers absconded, to escape persecution.

Benjamin Bangs from the previous discourse,
which took occasion to bring them off from a dependence upon hireling teachers,
as "`the hireling fleeth because he is a hireling
and careth not for the flock,`" (John 10:
11-13.) and to turn them to the teacher that cannot be removed into a corner,
"`the inward principle of the grace of God, that bringeth salvation,
and hath appeared unto all men, teaching them what to deny, and how to live,`" Titus 2:
11-12. The manifestation of the spirit given "`to every one to profit withal,`" 1 Cor.
7: 7. advising them to turn their minds inward, and mind the secret operations of it,
whereby they would find by a lively experience,
that it checks for bad words and bad actions; and as they minded its teachings,
they would find it would lead them into all truth.
The men were well pleased, and affected with his discourse, declaring at parting,
they had never heard things so opened to them in their lives.

Here we have a remarkable instance of the spirit of universal charity and benevolence,
of the zeal and diligence,
which actuated these ancient laborious ministers
among the people called Quakers of this age,
to watch every opportunity to answer the end of their calling, to promote truth,
and explain to mankind the way of life and salvation, without fee or reward from man.
Benjamin Bangs having travelled upwards of one thousand seven hundred miles,
held one hundred and eighty meetings, exclusive of Dublin,
and spent near twelve months in laborious and profitable
service amongst his friends and others,
returned home.

William Edmundson and Robert Jackson having been prosecuted in
the bishop`'s court to excommunication for non-payment of tithes,
were taken upon a writ, committed to prison, and detained prisoners about twenty weeks,
when the Earl of Ely (their landlord) interesting himself to procure their liberty,
the bishop ordered them to appear personally in his court at Kildare,
where they appeared accordingly before the bishop, in company with several priests,
the aforesaid earl, and sundry other persons of note.
The bishop desired to know William Edmund`'s reasons why he did not pay tithes;
but Edmundson William was not forward to enter upon the
subject being diffident of his capacity to manage it,
so as`' not to hurt a good cause through a weak defence.
Notwithstanding, as the bishop was urgent, a conference commenced,
which held for three hours, wherein William was enabled, with wisdom and understanding,
as he thought superior to his own, and a ready recollection of arguments from scripture,
to prove tithes abolished,
and that it was antichristian to pay or receive them in the gospel dispensation,
to the full satisfaction of the audience:
So that their suffering and this conference thereupon had a good effect,
and some other religious subjects were handled,
which afforded William Edmundson an opportunity to
explain the principles of himself and friends,
in relation to a gospel ministry, faith, and the true worship of God.
The bishop, who appears to have been a man of moderation,
soon after caused them to be released,
and afterwards both himself and the officers of his court behaved
with kindness towards the members of the society.

About the middle of this summer a fresh order was issued
by government to the several sects of dissenters in Dublin,
to forbear meeting publicly in their worship houses as formerly:
And the archbishop of Dublin sending for Anthony Sharp, informed him,
that it was the desire of government that his friends
also should forbear their public assemblies,
but friends returned answer,
that they believed it was their indispensable duty to meet together to worship God,
from whom they received all their mercies,
and not to neglect this reasonable service for fear of human penalties;
the end of their assemblies being purely for divine worship, and for no other purpose.
In consequence of these orders, other dissenters generally deserted their meetings;
but the people called Quakers, under persuasion of duty, assembled together as formerly,
and thereby became obnoxious to censure and punishment from the secular power,
but in a degree very short of the sufferings of their brethren in England.
Upon a first day the marshal and several of the mayor`'s
officers came to the meeting at Wormwood-gate,
where finding John Burnyeat preaching, the marshal commanded him to go along with him,
which, after some discourse, he did.
He commanded the meeting to disperse, but the members kept their places quietly.
John Burnyeat being taken before the mayor, was asked,
why they acted contrary to the orders of government?
To which John replied, we do nothing in contempt of government.
But, said the mayor, why do you not obey then?

[.discourse-part]
_John._
Because it is matter of conscience to us,
and that which we believe to be our indispensable duty, to meet together to worship God.

[.discourse-part]
_Mayor._
You may be misled.

[.discourse-part]
_John._
If we be misled we are willing to be informed.

[.small-break]
'''

Then it being urged that other dissenters had submitted and why would not they?
To which John Burnyeat returned answer,
"`What they do will be no plea for us before the judgment
seat of God.`" After some further discourse,
the mayor committed him to prison, to which, soon after,
Anthony Sharp and Alexander Seaton were committed.
After a month`'s imprisonment, application was made to the mayor for their release,
who refused; but in consequence of an application to the Earl of Arran, lord deputy,
it was obtained, after an imprisonment of about two months.
