== Chapter XVII. West Indies

[.chapter-synopsis]
* The West Indian Islands the first Part of America visited by the People called Quakers
* General Imprisonment there
* Greatest Sufferings for refusing to bear Arms
* Several Friends from England embark for Barbados
* George Fox convenes the Men`'s and Women`'s Meetings at his Lodgings, being weak at his Arrival
* Pays a Visit to the Governor, and is kindly received, which occasions a large Meeting at Bridge-town
* Ralph Fretwell, a judge, being convinced, is turned out of his Office.
* Thomas Briggs and William Edmundson proceed to Antigua, thence to Nevis, where they are not suffered to land
* George Fox continues in Barbados, where he hath good Service
* Priests endeavour to stir up Persecution, and to render Friends suspected, whereupon they publish a Confession of their Faith
* Friends accused of a Design to stir up the Negroes to Rebellion
* Their Vindication
* George Fox and others pass to Jamaica
* Elizabeth Hooton dies there
* Her Life

It hath been already remarked the two first of these people who
went to New England arrived there in a ship from Barbados in 1656.
Whence it appears this island of Barbados,
and the adjacent islands of Nevis and Antigua,
were the first of the American Plantations which were visited
by any of the people called Quakers from England,
whose labours in the work of the ministry seem to have been attended with success,
to the convincement of several of the inhabitants
of the validity of the doctrines they published;
but it is remarkable, that in every quarter of the world wherever these doctrines spread,
although calculated to promote virtue, peace,
and due subordination in religious and civil society; persecution still followed.

In the island of Nevis, Humphrey Highwood,
the first inhabitant who entertained the people called Quakers,
having given a friendly reception to three of them, Peter Head,
John Rouse and Mary Fisher, he was cited to appear before the governor,
and charged with the breach of a law enjoining notice to be given to the
governor of the arrival of all strangers within a limited time,
which the said Humphrey, through inadvertency, had suffered to elapse,
for undesigned omission he was committed to prison.

He had not as yet embraced the principles of the said people,
but after some time being convinced thereof, he suffered imprisonment: First,
for declining his usual appearance in arms and service in the militia,
and a second time for appearing before the governor with his hat on,
and was detained in prison till the next court, at which,
as there was no law extant making such appearance criminal, he was set at liberty;
but at that time they made a law,
That whosoever for the future should come into any court with his hat on,
should pay a fine of five hundred pounds of sugar, or suffer a month`'s imprisonment.

Upon the arrival at Barbados of the king`'s proclamation
in consequence of the insurrection of the fifth monarchy-men,
there seems to have been a very general imprisonment
of the members of this society in that island,
for declining oath of allegiance, which the magistrates here were zealous to enforce,
in order to ingratiate themselves with the government.

They also suffered by frequent distresses for refusing to
contribute to the maintenance of the priests by law established,
and toward the charges of repairing the public worship houses,
which were enforced by penal laws, frequently executed with more than legal severity.

But they were exposed to the severest of sufferings in person and
property for refusing to bear arms or work at the fortifications.
The laws of the country requiring the personal service of the inhabitants,
their servants and horses, and enacting severe penalties in case of default,
therefore for their conscientious testimony in these respects,
they were not only liable to severe fines and exorbitant distraints,
frequently to double the value of the estimated fine,
but to frequent imprisonments and corporal punishment,
at the arbitrary pleasure of officers and military commanders.

Feeling their sufferings heavy and multiplied,
they made repeated remonstrances to the successive governors and
council for redress of their grievances and ease from their sufferings;
but here, as in England, instead of relief, heavier penal laws were often the result.

Soon after the yearly meeting in London several friends
took shipping from England in order to visit the West Indies,
and other parts of the British dominions in America,
and after a passage of near two months arrived safely in Barbados.
In this voyage they were closely pursued by a Sallee, man of war,
and apparently in danger of being taken, but were providentially delivered;
for when this ship was come up with them, it being by moon-light,
a thick cloud intercepted the view; the moon set, and a fresh gale arising,
carried them rapidly on their course, and they saw them no more.

The friends who went over at this time in company were George Fox, Thomas Briggs,
William Edmundson, John Rouse, John Stubbs, Solomon Eccles, James Lancaster,
John Cartwright, Robert Widders, George Pattison, John Hull,
Elizabeth Hooton and Elizabeth Miers, and John Burnyeat the year before.
George Fox, through indisposition,
was so weak at his landing that he was not of ability for some time to go much abroad,
but his fellow-labourers and the companions of his
voyage entered diligently upon the business,
which had induced them to encounter the difficulties of a passage to these remote islands,
viz. to promote true religion and righteousness in places
where they were too little considered or practised.
Here their gospel labours were attended with such success,
that many of the inhabitants of this island were
remarkably awakened from their spiritual lethargy.
The meetings crowded by people of all degrees,
even some of the principal rank amongst them,
and many were convinced of the truth of the doctrines they published.

George Fox`'s concern pointing particularly to the promotion of
that discipline and good order amongst his friends in this island,
which he had been employed in establishing in other parts,
and not being able yet to travel,
the men and women assembled in their respective meetings for the
affairs of the society at his lodging at Thomas Rous`'s,
which furnished him with the opportunity of being present,
where he found his assistance and directions much wanted,
sundry disorders having crept in for want of vigilance and care.
Besides the subjects of discipline usual in other places,
he recommended to their especial care the case of their negro slaves,
advising to instruct them in Christianity,
and endeavour to instil into them the fear of their creator,
as well those they might purchase as those who were born in their families;
also that they should cause their overseers to treat them with humanity and gentleness,
and not to follow the custom too prevalent of using them with cruelty;
and that after certain years of servitude they should set them free.
This advice being well accepted and observed by the members of this society,
caused a general alarm to the inhabitants;
gave a handle to their adversaries to misrepresent their good intentions,
and some time after occasioned them trouble and damage.

After George Fox was able to go abroad, he, in company with his host Thomas Rous,
paid a visit to the governor, who received them with remarkable kindness;
and a few days after, a general meeting being held at Bridge-town,
the rumour of this visit to the governor, and the kind reception he met with,
drew many of the officers, both civil and military, and others not of the lowest ranks,
from most parts of the island to the meeting.
Lewis Morris, who had been a colonel and a member of the council,
having been before convinced, brought in company with him Ralph Fretwell,
a judge in the island.
The meeting, which was very large,
was conducted to the great satisfaction of the general part of the audience,
and Ralph Fretwell aforesaid, through the powerful and effectual ministry of George Fox,
was thoroughly convinced;
and not discouraged by the general contempt which this people lay under,
openly professed himself of the society of the people called Quakers.
He was one of the chief judges of the court of Common Pleas in this island,
had been regularly sworn into office, and executed it with integrity and honour;
but after this his profession, his adversaries insisted upon his being sworn again,
on purpose place of that they might take advantage of his religious scruple,
and procured it to be put to the vote in council.
Many of the council disapproved of the motion, and upon putting the question,
they were equally divided, but the governor having the casting vote gave it against him,
being actuated more by the narrowness of party spirit, prevalent in this age,
than a regard to justice or the public good.

After this meeting Thomas Briggs and William Edmundson took leave of George Fox,
and proceeded to the islands of Antigua and Nevis.
In the former they had large meetings, attended by many of the principal inhabitants,
as well as numbers of other ranks.
Many were convinced by their ministry, and amongst the rest Colonel Winthrop,
who had been governor,
at whose house they had afterwards several large and satisfactory meetings.

When they had finished their service in Antigua they set sail for Nevis,
where soon after they came to anchor.
A marshal was sent aboard by the governor, a man of a persecuting spirit, with orders,
that none should come ashore until he knew whence the vessel came, and who were in it;
in consequence whereof they were detained on board;
and the governor receiving intelligence who the passengers in the vessel were,
immediately sent an officer and a guard of soldiers,
with strict command to suffer none of them to go on shore,
nor any of the islanders to go on board to see or converse with them,
upon the penalty of a large fine; but the officer and soldiers being of a better temper,
carried themselves kindly to them,
and suffered several of their friends to come to visit them,
and by consent of the owner of the vessel, Colonel Winthrop,
they held a meeting on board, to their mutual edification.

The governor sent for the master of the ship, who was no Quaker,
and obliged him to enter into a bond of 1000£. sterling to carry them back to Antigua;
but in the mean time, while they lay there, Colonel Stapleton, governor of Montserrat,
paid them a visit,
to whom William Edmundson complained of the inhospitable
treatment of this governor of Nevis:
That it was very hard usage, that they, being Englishmen,
and coming so far as they had done to visit their countrymen,
should be prohibited from coming on shore,
to refresh themselves within King Charles`'s dominions, after such a long voyage.
Colonel Stapleton replied, "`It is true;
but we hear that since your coming into the Carribee
islands seven hundred of our militia are turned Quakers,
and Quakers will not fight, and we have need of men to fight,
being surrounded by enemies,
and that is the reason why governor Wheeler will not suffer you to come on shore.`" Accordingly,
by the governor`'s orders, they were carried back to Antigua,
where they were received with gladness by their friends,
met with no molestation from the government,
their meetings were resorted to by many of all ranks,
and their testimony well received by them.

George Fox continued still exercised in his ministerial gift in Barbados,
where he had many large and satisfactory meetings, both for good worship and discipline,
free from any interruption from the government,
the former of which many of other societies attended.
At one of them Colonel Lyne, a sober man,
was so well satisfied with George Fox`'s testimony,
that he expressed his satisfaction in these terms:
"`Now I can gainsay such as I have heard speak evil of you, who say you do not own Christ,
nor that he died; whereas I perceive you

exalt Christ in all his offices, beyond what I have ever heard before.`"

But as his labour in the Gospel was effectual to the convincement
of several in most parts of the island,
the priests and their partisans being much disturbed and alarmed,
had recourse to persecution, their customary means of redress,
in endeavours to instigate the magistrates to severity against him and his fellow-labourers;
but finding them selves frustrated in these endeavours,
they next exerted themselves to render them odious or suspected,
by strenuously dispersing amongst the people the vulgar calumnies of the time,
which had been repeatedly objected to them, and as often refuted by them,
"`That they denied God, Christ Jesus, the Holy Scriptures,
etc.`" whereupon they thought it requisite to draw
whereupon up and publish a confession of their,
faith, wherein they assert their belief in one only wise, omnipotent and eternal God,
the creator of all things in heaven and earth,
and the preserver of all that he hath made, who is God over all, blessed forever.
That they own and believe in Jesus Christ, his only begotten son,
who was conceived by the Holy Ghost, and born of the Virgin Mary,
in whom we have redemption through his blood, even the forgiveness of sins.
That he was crucified for us in the flesh, without the gates of Jerusalem; was buried,
and rose again the third day by the power of his father for our justification:
That he ascended up into heaven, and now sitteth on the right hand of God.

Concerning the holy scriptures,
they believe they were given forth by the Holy Spirit of God,
through the holy men of God, who "`spoke as they were moved by the Holy Ghost;`"^
footnote:[2 Peter 1:21]
that they are to be read and believed, and are "`profitable for reproof, for correction,
and for instruction in righteousness, that the man of God may be perfect,
thoroughly furnished unto all good works.`"^
footnote:[2 Timothy 3:19]
George`' Fox`'s Journal, folio, page 435-436, much more at large.

But the malignity of his accusers did not stop here,
the universality of the benevolence of these faithful ministers,
and disposition to be serviceable in the cause of righteousness to every class of mankind,
furnished their adversaries with occasion to invent another calumny,
which applied home to the passions of the people, as affecting them in a tender part,
their secular interests and safety;
persecution still endeavouring to pervert religious
dissent into a crime against the state.
We have seen the care and concern that George Fox had upon
him respecting the negro slaves in the families of friends.
The principle of universal charity incited him and his fellow-labourers,
both to promote a religious care over them from their masters of the society,
as a part of their respective families,
and also to hold meetings among them in different plantations,
wherein they exhorted them to justice, sobriety, temperance, chastity, piety,
and to due subjection to their masters and governors.
From these charitable endeavours to instil religious sentiments
into this poor neglected and oppressed part of the species,
their opponents took occasion to add this to the before recited calumnies,
"`That they taught the Negroes to rebel.`"

In their vindication against this charge they appeal to the Searcher of all Hearts,
that this was an abominable untruth,
their principles and which practice being utterly abhorrent of such an intention:
That their addresses to these poor people themselves,
had been directed to exhort them to be sober, to fear God,
to love their masters and mistresses,
to be faithful and diligent in their service and business;
that they cautioned them against a plurality of wives, against theft, drunkenness,
adultery, fornication, cursing, swearing, lying,
and such vices as people of their station are too prone to;
referring them to something within them, that tells them, they should not practise these,
nor other evils.
That if notwithstanding they should commit them, they informed them,
that there were but two ways, one which leads to Heaven,
whither the righteous go into inconceivable happiness; and the other that leads to Hell,
whither the wicked and debauched, whoremongers, adulterers, murderers and liars,
go into everlasting misery.
They wish it to be considered,
that it is no transgression for a master of a family to instruct his family himself,
or for others to do it for him,
but an important and incumbent duty upon them to pray with and for their families,
to advise, instruct and admonish every member thereof for their good;
this being a command of the Lord; disobedience thereunto will provoke his displeasure.

This apology, weighty in itself,
it is presumed had some weight with those to whom it was addressed;
as notwithstanding these invidious misrepresentations by the priests and their adherents,
no severe measures on this account seem to have been adopted '`till some years after.
George Fox having spent three months in his gospel labours in this island,
visiting and confirming his friends,
whose number was now increased by the convincement of others,
and having settled the meetings to his satisfaction,
apprehending himself clear of his service there, prepared for his departure;
having first: communicated his prospects to his friends,
he thought it expedient to acquaint the governor
and divers of the council with his intention,
that, as his entrance into the island had been open and public,
his departure might be so too.

From Barbados he passed over to Jamaica, in company with Robert Widders,
William Edmundson, Solomon Eccles and Elizabeth Hooton,
where they met with a kind reception, being treated with civility both by the governor,
magistrates, and the people in general.
Their meetings here were large and very quiet,
their ministerial labour conducive to the convincement of many,
and amongst them some people of account in the world.

About a week after their arrival, Elizabeth Hooton, being far advanced in years,
departed this life.

She was a woman religiously inclined in an early stage of life,
and one of the first who joined in religious fellowship with George Fox,
before the name of Quaker was applied to him and his friends.
In his early journeys to seek out, and converse with, sober and well-minded people,
before he appeared as a public preacher, in the year 1647 he came into Nottinghamshire,
where he met with a number of-such as he desired to visit,
and had some serious conferences with them upon religious subjects;
amongst them was Elizabeth Hooton, who was then convinced by his doctrine,
of the sufficiency of the light, which enlighteneth every man that cometh into the world;
and by an inward attention to this monitor in her own breast (by Divine aid) she experienced
the work of conversion and sanctification begun and advanced in her heart,
whereby she was prepared for the reception of spiritual gifts.
In the year 1650 she received a gift in the ministry,
being reputed to be the first minister of her sex in this
society but not the first in the Christian church:
For beside those in the primitive age of christianity,
mentioned by the apostle Paul as his fellow helpers and labourers in the Lord,
according to William Sewel, there are more modern accounts,
"`that among other persuasions in London there were also women who did preach,
and were heard with great satisfaction.`"^
footnote:[W. Sewel]
As Elizabeth Hooton was one of the earliest believers in,
and one of the earliest preachers up of, the light of Christ in man,
while those about this time denominated Quakers were but few, and not, properly speaking,
an embodied society, it was not unusual for their preachers, at this time,
to attend the public places of worship, and generally, at the close,
to seek an opportunity to publish their doctrine there,
not having yet established meetings of their own in many places,
a custom not peculiar to them, as hath been already shown;^
footnote:[See Vol 1 p. 86]
yet for this many of them met with much abuse, and amongst the rest Elizabeth Hooton.
She travelled into many parts of the nation to call people to repentance,
and to take heed to the convictions of the Divine
Light and Grace of God in their own hearts,
for which she was one of the earliest sufferers among the members of this rising society.
As early as 1651 she was imprisoned in Darby upon the complaint of a priest,
to whom she had spoken by way of reproof,
who in resentment applied to a justice and procured her imprisonment.
In the next year, 1652,
she was again imprisoned at York for delivering an
exhortation to the congregation at Rotheram,
at the close of their public worship.
In 1654 she was on the like account imprisoned five months in Lincoln,
and in 1665 twelve weeks in the same place.
In 1660, passing quietly along the road, she was met by one Jackson,
priest of Selston in Nottinghamshire, who abused her, struck her repeatedly,
knocked her down, and afterward put her into the water;
thus manifesting his malice in the abusive treatment of an inoffensive female,
in a manner disgraceful to his character as a teacher, a christian, and a man.
The barbarous usage she received in New England hath been already related.
In all her afflictions, through Divine support,
she appears to have been preserved in patience, and in a meek and quiet spirit;
but steadfast and immoveable in the truth in which she most surely believed.
And at last, in an advanced age, finished her life in peace in a foreign land.
