== Chapter XVIII.

[.chapter-synopsis]
* William Edmundson visits these islands a second time
* At Bridgetown a Priest disturbs the Meeting and challenges William Edmundson to a Dispute
* In which being foiled the Priest complains to the Governor
* William Edmundson waits upon the Governor, and by his Discourse brings him to moderation
* William Edmundson appears before the Council, where the Priest failing in proof of his Charges meets with merited Reproof
* William Edmundson writes an Epistle to the Governor, etc. against the prevailing Vices of the island
* And their Treatment of the Negro Slaves
* Act passed to prevent the People called Quakers from bringing Negroes to their Meetings, and against their Schoolmasters and Preachers
* Reflections on this Act, and on the Slave Trade.

In the year 1675,
William Edmundson aforesaid went a second time from Ireland to Barbados,
under a renewed religious concern to visit, the meetings of his friends in that island,
and in other parts of the American plantations, where he was gladly received by them,
and had many favourable opportunities in the exercise of his ministry amongst others,
the meetings through most parts of the island being very large,
many were convinced of the truth,
and the hearts of friends enlarged in love to receive his
testimony and instructions both in doctrine and discipline.

He had a meeting at the house of Tobias Fryer, a man of great substance,
repute and authority, in commission of the peace,
whose wife was one of the society of Quakers, so called; the meeting was crowded,
and amongst the rest the priest of the parish, whose name was Ramsey, attended at it.
After meeting many of the auditors expressed their satisfaction,
only the priest seemed disturbed, yet made no public opposition there;
but afterwards at a meeting at Bridgetown,
to which he came attended by a company of rude people in order to make a disturbance,
he reviled friends with abusive language, calling priest them heretics,
blasphemers and traitors, and challenged William Edmundson to a public disputation,
in which he threatened to prove the charge.
This challenge being accepted,
the rumour thereof drew together abundance of people of all ranks,
by computation 3000 or upwards; the assembly was accommodated under shades without doors:
But the priest, instead of making good his former charges,
broke out in railing accusations, sometimes against particular friends,
sometimes against the society in general, advancing many invidious charges,
but proving none, whereby he disgusted the judicious part of the auditory,
manifested his own folly,
and furnished William Edmundson and his friends (who kept cool in their minds)
with an opportunity of explaining their principles to the general information
and satisfaction of the large number of people assembled upon the occasion.

Disappointed of his aim, but persevering in his enmity,
this priest next applied to the governor, Sir Jonathan Atkins,
with a complaint against William Edmundson,
that he was a Jesuit from Ireland under the appearance of a Quaker,
and pretending to make the Negroes Christians, would make them rebels,
and rise and cut their throats.
The governor, upon this false information,
was determined to issue his warrant to apprehend William Edmundson, who,
coming to the knowledge thereof,
anticipated the execution by a voluntary visit to the governor.

The governor, when he found who his visitant was, fell into a passion,
menaced him greatly, that he would take a course with him,
and sent his man for the marshal;
but before the marshal came they entered into a conversation,
in the course of which the governor acquainted William
Edmundson with the information he had received,
that under pretence of making the Negroes Christians,
he was teaching them to rebel and cut their throats.
To which William replied,
that it was a good work to bring them to the knowledge of God and Christ Jesus,
and to believe in him that died for them and for all men,
which would keep them from rebelling or cutting any man`'s throat;
but if they should rebel and cut their throats, as was said,
it would not be in consequence of his doctrine, but of their treatment,
keeping them in ignorance and under oppression,
giving them liberty to be common with women, like brutes; and on the other hand,
starving them for want of food and raiment convenient for them:
Thus allowing them liberty in that which God restrained,
and restraining them in that which God allowed and afforded to men, meat and clothes.
After some time the governor grew very moderate.

The marshal coming, desired to know his pleasure.
The governor told him he had thought to have committed William Edmundson to prison,
but his mind was altered; so ordering him to appear before the council next day,
he dismissed him for that time.
Next day he appeared before the council, and his accuser, Ramsey, appeared also,
and renewed his accusations against William Edmundson and his friends, of heresy,
blasphemy and treason,
alleging that he would prove his charge out of Edward Burrough`'s book.
The book was brought, the where the priest toiled and turned it over and over again,
but could find nothing there to answer his purpose;
whereupon he met with merited rebuke from the governor,
and general displeasure from the council,
for advancing such gross charges against a body of people without foundation.
The priest, as abject as he was envious, fell on his knees to ask their forgiveness,
and from that time the governor behaved with kindness during William`'s stay there.

William Edmundson spent five months in his religious labours in this island, in which,
being a man of fortitude, by conscious integrity raised above the fear of man,
and actuated by an honest zeal for promoting the
cause of pure religion and discouraging vice,
he was a faithful reprover of the immoralities and
vicious practices abounding among the inhabitants,
and eluded his labours amongst them by an epistle addressed to the governor, council,
and all others in authority in the island of Barbados, in which,
after a recital of the various vices and
immoralities which blemished the island, as swearing, drunkenness, pride,
oppression and uncleanness;
and pointing out from scripture that general depravity frequently draws down the symptoms
of Divine displeasure in inflicting signal calamities upon guilty places and nations,
as upon the old world, Gen. 6:2,
"`for taking wives of all that they chose;`" and upon Sodom
for the pollution and unrestrained lust of its inhabitants:
He closely presses them to use the power in their hands to put a stop to the current
of wickedness and uncleanness which had over-run the island and cried for vengeance;
in particular, the promiscuous commerce of the sexes among the Negroes,
connived at or rather encouraged from motives of interest,
appears to him a sin of complicated enormity,
shocking to every sentiment of chastity and decency, disgraceful to humanity,
and a violation of every law, moral and divine.

He therefore strenuously urges them to exert their authority for restraining
and suppressing this licentiousness and offensive liberty among their negro slaves,
and not only to break the bonds of iniquity,
but to remove the yoke of oppression from off their necks; to moderate their labour,
treat them with humanity, and allow them a comfortable sufficiency of food and rainment.
That as the beneficent creator of the world hath filled the earth with plenty,
and provided a sufficiency for food and raiment for all the inhabitants thereof,
for a part of the human race to be deprived of necessaries,
which they fully earn by their labour,
in order that their superiors may more freely riot in all the superfluities of luxury,
can never be vindicated or answered for to the Lord, to whom the earth belongs,
and the fulness thereof.

He concludes his said epistle in these plain and honest terms:

[.embedded-content-document.epistle]
--

You have power, if you make the right use of it, to rectify these abuses,
if the inclination of your hearts be to the Lord;
or otherwise he will find a way to purge the land of her wickedness and her filthy abominations;
and in that day remember you are warned by one, that wishes well to the island,
and stability to her government.

[.signed-section-signature]
William Edmundson.

[.signed-section-context-close]
21, 12th mo, 1675.

--

Although the rulers to whom this epistle was addressed, convicted, doubtless,
in their consciences that the state of their island gave just occasion
for the close and poignant reprehensions contained therein,
appear not to have expressed any immediate resentment against the author,
who soon after took his departure for New England unmolested;
yet in a short time after that,
instead of using their authority to suppress the vices remonstrated against,
listening more to the calumnies and suggestions of the adversaries,
and to the dictates of their own self-interest,
prompting them to increase the number of their slaves even by wicked means,
they resolved to keep such troublesome monitors at a distance,
to prevent the preaching up of doctrines they disliked,
and to render themselves secure in the continued practice of immoralities,
they knew to be indefensible; for these purposes,
about two months after the date of the aforesaid letter,
they passed an act to prevent the people called Quakers
from bringing negroes to their meetings,
etc.

The preamble recites,

[.embedded-content-document.legal]
--

that many negroes have been suffered to remain in the meetings of the Quakers,
as hearers of their doctrine, and taught in their principles,
whereby the safety of this island may be much hazarded.`" They therefore enact,
that if after the publication of the act any negro or negroes shall
be found with the said Quakers at any of their said meetings,
and as hearers of their preaching, such negro or negroes shall be forfeited,
one half to the party who shall seize and sue for them,
and the other moiety to the public use of the island.
And if any such negro or negroes do not belong to
any of the persons present at the same meeting,
any person may bring an action, grounded upon this statute, against any person present,
at the election of the informer, for the sum of 10£. sterling for every such negro.
That no person shall keep a school,
unless in one month after publication such person shall take the
oath of allegiance and supremacy before some justice of peace,
or obtain a special license from the governor for the time being,
under the penalty of three months imprisonment,
and a forfeiture of three thousand pounds of Muscovado sugar.
That no person or persons whatsoever,
that is not an inhabitant and resident in this island,
and hath been so for twelve months together,
shall hereafter publicly discourse or preach at the meetings of the Quakers,
upon the penalty of six months imprisonment,
and shall forfeit ten thousand pounds of Muscovado sugar,
to be recovered and divided in manner aforesaid.

--

By this act several of the said people were great sufferers;
but the attempt made on Ralph Fretwell aforesaid, and Richard Sutton,
exceeded all reasonable bounds,
the former being in formed against and prosecuted by one
Thomas Cobham for the sum of 800£. for eighty negroes,
and the latter for thirty negroes being present at a meeting;
but the defendants in this cause made their defence so well,
that notwithstanding the act, the jury weighing all the circumstances of the matter,
acquitted them, to the disappointment of their enemies.

Three years afterward, in the year 1678,
this act was extended to include the inhabitants of the island,
under the penalty before enacted,
for preaching at any of the meetings of the people called Quakers,
whereby all preaching in the public assemblies of the said people was
prohibited under the severe penalties of fines and imprisonment.

Now it will be no difficult matter for unprejudiced reason to determine,
whether these ministers of the people called Quakers,
objects of contempt and aversion with many of those,
who pride themselves upon their refined reason, and their superiority of understanding;
or the legislature of this island,
who from their rank in life were probably in estimation for wisdom and honour,
acted most consistently with the principles of religion, humanity and moral justice.

After the foregoing narrative of the tendency of the labours
of these ministers with the negro slaves in this island,
the preamble of this act, insinuating apprehension of danger to the safety of the island,
must appear nothing more than a mere pretence.
The priests, as we have seen, alarmed at the success of the ministry of these friends,
spread jealousies of them upon groundless suggestions,
and after their customary manner in that age,
endeavoured to excite the secular power against them,
and at length seem to have succeeded.
This act therefore appears to me the result of clerical jealousy,
joined to national prejudice, under the bias of an irrational and unjust policy,
which made them averse to every measure,
which might conduce to let in any degree of light into the darkened minds of their slaves,
absurdly imagining, that the nearer they were kept to the state of brutes,
the more safely they might treat them as such.

But what shall we think of the christianity of these islanders,
who yet laid claim to the name of christians and protestants,
to make it penal for honest men, sincerely employed in the discharge of religious duties,
to instruct these poor heathens, members of their own families or others,
in the nature of religion and morality, to give them some notions of a supreme Being,
and exhort them to live in his fear,
and bring them into the belief of a future state of rewards and punishments.
To make such laudable endeavours penal by a public
act of state argues a general depravity of sentiment,
disgraceful to any people, and as irreconcilable to sound policy,
as to the nature and doctrines of the gospel.

The discovery of America engaged several nations of Europe to send out colonies
to possess and cultivate many of the parts to which they respectively laid claim,
not only to the continent, but to the West Indian islands.
This island of Barbados was early resorted to by several adventurers,
from England who upon their landing found it a desert waste,
without the least sign of having ever been inhabited; and being,
as well as the other colonies and islands, over-run with wood,
consisting of trees very large, hard and stubborn,
put the emigrants to great labour and difficulty to clear
as much ground as was necessary for their subsistence.
This laborious clearing and cultivating of their lands being requisite, in a good degree,
for their support, and in a greater degree for acquiring property and raising estates,
occasioned a great call from the planters for assistants of ability to labour,
and afterwards gave rise to a very iniquitous traffic, a traffic in the human species,
wherein the laws of nature and humanity, much more,
the more sacred laws of religion and christianity, were most enormously violated,
both by the Europeans and Americans.

The former sent their ships to the coast of Africa
to take away such of the natives as they could purchase,
captives taken in war, whereby they fomented wars and bloodshed amongst the natives,
or frequently such as they could trepan, take by surprise or steal,
inhumanly regardless of the pain they suffered in
being violently torn away from their parents,
their wives, their families, their natural connections,
and all that they held dear in life;^
footnote:[A negro residing near Philadelphia,
from his first arrival appearing thoughtful and dejected,
frequently dropping tears when fondling his master`'s children,
it incited a curiosity in those who observed him to know the cause, which,
when he had got English enough to make himself understood,
he let them know in the following moving relation:
--That he had a wife and children in his own country; that some of these being sick,
he went in the night-time to fetch water from a spring,
where he was violently seized and carried off by per sons,
who were lying in wait to surprise and seize such of the inhabitants,
as might fall in their way, and thence was transported to America;
that in remembrance of his family and friends, whom he never expected to see any more,
he could not help giving vent to the anguish of his heart,
by dropping a tear to their memory.
Now can any man, whose mind is not rendered quite obdurate by the practice of oppression,
or love of gain,
hear this relation without commiserating sympathy and a participation of his sorrow?
And doubtless the cases of many of these oppressed people will be found
to be attended with circumstances equally cruel and aggravating.]
who, though termed savages,
yet many of them appear more susceptible of the feelings
of men than their more savage captors,
who must be dead to all the tender feelings of the human heart,
before they could be concerned in a traffic so disgraceful to civilization,
and rendering the name of christian odious to infidels.

[verse]
____
_Quid non mortalia pectora cogis
Auri sacra fames._

O cursed hunger of pernicious gold,
What bands of faith can impious lucre hold.
____

As they were thus purchased or kidnapped,
they were hurried on board the ships in waiting to carry off their human cargo,
until they procured their complement.
On shipboard, with out regard to health or decency,
hundreds being confined together within the narrow limits of the hold,
were liable to contract distempers,
which put a period to the sorrows of many of them by a premature death;
many others found a release from the accumulated
sufferings which awaited the less happy survivors,
by the seasoning in the islands, as it is termed.

When landed they were exposed naked to sale like beasts of burden,
and being sold to the highest bidder, branded with an hot iron,
as the property of the purchaser, a property which God or nature never gave the seller,
which therefore he had no right to transfer,
and of consequence could convey to the purchaser no right over them,
but what himself had, that is, none at all.

But arbitrary custom and unequal laws gave a power over them to the purchaser,
who generally considered this as a right of property, and often used his power over them,
or his overseer for him, with unfeeling barbarity,
keeping them to excessive labour with the lash over their backs,
which was exercised without mercy,
allowing them at the same time neither proper food nor clothing;
while these slave owners, many of them,
supported the state and luxury of princes by the labour of those miserable men;
and by them their children being waited upon with the most abject homage,
were corrupted in their early years with intolerable pride and cruelty,
and inured to look upon, their slaves as beings of a different species,
and by these means prepared to perpetuate their bondage and their afflictions.

From this view of the slave trade, of the treatment of those slaves,
and the use those islanders found them of to support themselves in ease and grandeur,
it is not difficult to discover from what principle
the aforesaid act against the Quakers originated;
a mean and selfish jealousy,
lest their minds being in any degree or by any means enlightened,
might attain a clearer knowledge of their rights as men,
which they were very desirous to prevent,
as thinking it more conducive to their interested views,
that they should continue in their native ignorance of moral and religious truth.
Tyranny to pagans and savages loseth much of that abhorrence,
through the prejudice of custom, which it might be productive of,
if exercised upon any under the christian name, and therefore they chose rather,
they should continue pagans to be treated as brutes,
than to be converted to Christianity, and be treated like men.

I esteem it no inconsiderable credit to these pious and worthy men, that,
from a lively sympathy with their grievous sufferings,
they exerted their religious labours in favour of
this grossly abused part of the human species,
at a time when the rights of human nature were not so clearly understood;
when habitual tyranny and general usage had given
a kind of sanction to the commerce in slaves,
when few pleaded their cause, but most, in palliation of their treatment,
looked upon and represented them as beings of an inferior order.
