== Chapter XIX. New Jersey, etc.

[.chapter-synopsis]
* The Discovery of the Continent of North America
* The Dutch and Swedes the first Settlers
* King Charles II. dispossesses the Dutch, and gives the Country to his Brother the Duke of York, from whom it is named New York.
* Some of the People called Quakers migrate to America
* John Burnyeat pays a religious Visit to his Friends on that Continent
* Thomas Thurston, a Ranter, gives Friends in Maryland much Trouble
* John Burnyeat`'s Care and Endeavours to manifest his Unsoundness
* In Virginia several drawn aside by John Perrot`'s Notions, forsake meeting together for Worship
* John Burnyeat with much Solicitation gets a Meeting among them
* Which proves of Service.

The success of Columbus and Americus Vesputius in discovering the Caribbee Islands,
and the continent of South America,
diffused a spirit of adventure in search of further discoveries of the Western Continent.
Sebastian Cabot, an Englishman of Venetian extraction, an expert navigator,
was the next adventurer, who under the patronage of Henry VII.
sailed in quest of a north-west passage to the East Indies,
and fell in with the continent of North America, to which country the English,
as the first discoverers, laid claim; but they made no at tempts to settle in it,
'`till Sir Walter Raleigh, a man of extraordinary genius,
planted a colony in the southern part, which he called Virginia,
in honour of his mistress queen Elizabeth.

But the first attempts to settle colonies in this country proving unsuccessful,
damped the spirit of emigration for some time.
In 1606, king James I. granted a new patent of Virginia, under which denomination,
beside the country now distinguished by that name, the Provinces of New England,
New York, New Jersey, Pennsylvania and Maryland, were included.

In the interval between the discovery of the middle part of this continent,
and the actual possession thereof by any colony from England, Henry Hudson,
an Englishman by birth, but in the service or employ of the Dutch East India Company,
sailing also in quest of a northern passage to China,
and being disappointed in the principal purpose of his voyage;
coasted along the northern shore of America in search of some discovery,
whereby his employers might in some measure be indemnified for
the expenses of his fruitless attempt to find out the passage desired:
After sailing up the river to which he gave his own name, and reconnoitering the coast;
and its inhabitants, he returned to Amsterdam from whence he sailed.

The Dutch nation, in consequence of this discovery,
laid claim to this part of the continent,
and the court of England maintained their claim to the same,
upon the plea that Cabot first discovered it for them.
However, the Dutch sent a colony hither, who gave to the country the name of New Belgia.
The succeeding disturbances and civil wars in England,
between Charles I. and his parliament, furnished them time to settle without molestation,
and to build forts for their defence, and a town on the island of Mahattos,
to which they gave the name of New Amsterdam.
Sometime after them another colony emigrated from Sweden,
and settled in a part of this country.
So the Dutch and Swedes appear to be the first Europeans
who formed settlements in this part of America,
and remained there unmolested, until kine;
Charles II. in 1665 Charles sending out a squadron
with a considerable body of land forces,
dispossessed them, and gave this country country to his brother the Duke of York,
from whom both the town of New Amsterdam and the province
of Nova Belgia received the name of New York.
The Duke of York also, in 1669,
granted a part of this territory to Lord Berkeley and Sir George Carteret,
ordering it to be called Nova Caesaria or New Jersey.

This country as well as Virginia being thus settled,
many years previous to the grant made to William Penn,
some of the people called Quakers had migrated to both these colonies,
some time before Pennsylvania was inhabited by any Europeans.
Previous to the year 1665, when it first fell under the government of England,
some of this people had removed to settle at Middletown and other places in East Jersey.
And in that year the first ship arrived,
which brought any of them to the western division; the passengers were landed at Salem,
where many of them took up their residence.
In the year 1677 others followed, and settled at Burlington and Gloucester.
After these a succession of new settlers increased the number of this people considerably;
so that in the Jerseys, as well as in Virginia, Maryland and New England,
there were many settlements of them before William
Penn obtained his grant of Pennsylvania.

In the year 1665 John Burnyeat, after his service in Barbados was finished,
took shipping for these parts of America, and landed in Maryland in the second month,
and spent the summer travelling, in the exercise of his gift in the ministry,
amongst his friends and others in this province.
The meetings were large and much favoured; friends were greatly comforted,
and several others convinced.
But in this place, friends met with great trouble from one Thomas Thurston,
and a party which he drew for a while after him.
This man seems to have been tainted with a spirit of ranterism,
although professing himself of this society; in his conversation loose and disorderly,
his conduct scandalized his profession; in his disposition perverse and self-willed,
he gave great disturbance to their meetings by public opposition and bitter contention;
and yet disqualified as he was, he wanted to be the leader of a people,
and some were so weak as to be betrayed by him to their hurt.
John Burnyeat,
from a zealous concern to remove occasion of offence through his evil conduct,
to rescue the simple from the snare of his deceptive insinuations,
and to restore peace and order to the public assemblies of his friends, took much pains,
in concert with faithful friends of the province, to detect the man`'s conduct,
by searching out matters of fact,
and to convince the understandings of his followers of the error of his principles,
and unsoundness of his heart;
and through to manifest divine assistance they were so successful, that by the man,
their endeavours most of the people came to see the man, to forsake him,
and to return into unity with their friends.
But Thurston lost himself as to religion, and declined in his outward circumstances.

John Burnyeat having spent the summer in settling his friends in peace,
and in a good degree restoring order amongst them, departed from Maryland to Virginia,
and found sufficient employment there for a considerable part of the in succeeding winter.
For here, as well as in Barbados, he found many of the professors of truth,
even the greater part of them, led away by the fanciful opinions of John Perrot,
who carried his erroneous and extravagant notion of being got above forms,
much farther than he had done in England;
for here civil government and religious order being more unsettled,
gave him an opportunity of carrying his whimsies to a greater extreme,
and propagating them with less restraint or discouragement,
leading his bewildered followers into undue liberties,
inconsistent with the strictness of their profession,
or of good report with any religious or sober people;
for they had almost entirely forsaken their meeting for divine worship,
scarcely assembling together once a year, looking upon it as a form; much less,
it is to be presumed, would they assemble with any other people,
who were still more in the form.
Of consequence the reasonable and profitable duty of public united worship being neglected,
they lost ground in religion, and the effects of backsliding manifested their loss,
for they had laid aside the form,
appearance and plainness of their profession in dress and language;
and were become loose and irreligious in their conduct,
equally with those who made little profession of religion;
shunning the cross to evade suffering;
and preferring outward ease to the testimony of a
conscience void of offence towards God and man;
which they had been zealously concerned to preserve
by a diligence in keeping up their meetings,
through great sufferings,`'till this man came amongst them,
and beguiled them from the simplicity of truth into a fleshly liberty,
whereby the offence of the cross ceased,
and the power of godliness (with the form) was lost.
So that when John Burnyeat came thither he found
it difficult to get a meeting amongst them.
But in him we have a fresh instance of the lively zeal,
diligence and earnestness of engagement with which these primitive promulgators
of religious truth were actuated in the discharge of duty.
For when he saw their reluctance to give him a public meeting,
he did not leave them under their delusion,
but sought private opportunities of treating with them,
to convince them of their mistakes, to vindicate the principles of the society,
the consistency of their testimony, and rectitude of practice proceeding therefrom,
both in their diligent meeting to worship God, walking in all orderly conversation,
sobriety and temperance, as in his sight,
and fulfilling their social and moral duties to mankind.
By patient continuance in repeated visits and conferences
of this kind he at length obtained a meeting with them,
which, being favoured with the overshadowing of divine power,
seems to have been very conducive to open the understandings
of several to see their error more clearly,
and to the revival of more regard to their religious duties;
and by the continuance of his gospel labours,
and the renewed convictions of the spirit of truth in their own hearts,
many came in time to see through the wiles of the enemy,
and to be again serviceable members of religious society.

He afterwards travelled a while longer in these provinces,
and from thence into New England, Long Island and Rhode Island;
and about the latter end of 1st month, 1667, took shipping for Barbados,
where he spent some time, had many large meetings to edification,
wherein several were convinced; and when his service was finished there,
he returned to England.
