== Chapter XX.

[.chapter-synopsis]
* John Burnyeat pays a second Visit to America in company with William Simpson, who dies soon after their arrival
* Half year`'s Meeting at Oyster-bay
* Disturbed by the Opposition of some disorderly Persons, who read a Manuscript they had drawn up
* John Burnyeat opposes their Cavils, and vindicates his Friends
* John Burnyeat embarks for Maryland, and thence to Virginia, where he proposeth the establishing a Men`'s Meeting of Discipline
* General Meeting at West River, to which came George Fox and others
* They are in danger passing through the Gulf of Florida
* George Fox explains the Benefit of Meetings of Discipline
* General Meeting at Cliffs

Soon after the yearly meeting in London in 1670, John Burnyeat,
in company with William Simpson,
took shipping a second time for the American plantations;
and after a passage of twelve weeks landed at Barbados, where William Simpson,
an innocent humble man, who like the rest of his brethren had suffered much persecution,
was soon taken off by a fever, in, company which was a near trial to his companion,
(they having walked together in near unity and brotherly
affection) to be left alone in a foreign land,
under the discouraging prospect of many difficulties
and disagreeable occurrences to encounter,
considering the state of the church in that island; but he writes, the Lord was with him,
and by his power and good spirit assisted him to discharge his duty fully,
so that he left that island in peace, under the sense thereof.

From Barbados he took shipping for New York, where he arrived in about four weeks;
from thence he travelled through Long Island, Rhode Island,
and sundry other parts of New England,
and in his return came to Middletown in East Jersey,
where he had some meetings among friends settled there;
and from thence he returned to Oyster-bay in Long Island, to the half-year`'s meeting,
which began about the 8th day of the 8th month.
It appears to have been held to general edification and comfort,
through the meetings for worship.
After them the meeting for discipline,
which was gathered in much quietness and agreeable harmony,
was disturbed by some disorderly professors,
who had imbibed a prejudice against discipline,
and enmity against those friends who were zealous for the establishment thereof,
for the purpose of preserving good order,
and keeping the reputation of the society unblemished.
For it seems the spirit of opposition, which had given friends in England much trouble,
had spread to these remote regions;
and notwithstanding the plausible pretexts with which the dissent was covered over,
it appears to me to have originated in unstable minds,
from a desire of taking liberties not allowed by, but inconsistent with,
the profession of godliness in some,
and of evading the heavy sufferings to which the society was at this time exposed;
and as the prosecutions at home had driven many of other societies
of dissenters to seek an asylum in this quarter of the globe,
so it is not improbable but some of those who had
been infected with John Perrott`'s notions,
had from the like motive removed beyond the reach of persecution,
and disseminated their principles of dissent and opposition to good order here.
They directed the efforts of their envy and bitterness as they had done in England,
principally against George Fox and his epistles of salutary advice,
against which they had drawn up a book in manuscript,
which they demanded to have read in the meeting.
They were told the epistles and papers were there, and they might make their objections,
which friends would endeavour to answer; but this proposal not satisfying them,
and persisting in their purpose of reading their book, the meeting gave way,
and sat in silent attention till they had gone through it,
and then John Burnyeat recapitulating the principal parts thereof,
vindicated George Fox and his friends and the purity of their intentions,
and religious care for the welfare of the society
in promoting men`'s and women`'s meetings for discipline,
by explaining the benefit and advantage thereof to the society at large,
and to the individual members thereof;
refuting and reproving their slanders and falsehoods,
whereby they had hurt the minds of several young and newly-convinced friends;
and placing facts that had been misrepresented in a true light,
he gave great satisfaction to friends in general,
and brought them to a perception of the mistaken notions they had let into their minds,
through the insinuations of one George Dennis and two others,
who were chiefly concerned in writing the book, and in the opposition.
And after this seasonable interposition for the information and reconciliation of friends,
the meeting settled down in harmony,
and was conducted and concluded to mutual satisfaction and edification.
After all the meetings were over, friends comforted, the opposers refuted,
the simple-hearted who had been beguiled by them, rescued from their snares,
and peace and order restored,
John Burnyeat proceeded in his travels by Flushing and Gravesend to New York,
from whence he embarked for Maryland,
being accompanied by Daniel Gould from Rhode Island.
From Maryland they proceeded to Virginia,
where John had the consolation to observe the good effects
of his former labour and service in that province,
finding friends in general revived into a good degree
of religious care in their conduct and conversation,
a lively zeal for keeping up their meetings for worship,
and a disposition to receive him and his ministry with ready attention,
whereby his meetings with them were to mutual satisfaction and edification.

Finding them in this agreeable disposition,
in order to confirm and strengthen them in it,
and for the help of those who were not yet recovered
from the effect of John Perrot`'s infection,
proposed to them the establishing a men`'s meetings of discipline,
to promote good order amongst them,
that might be instrumental to the bringing back those, who were yet scattered,
to the unity of the body,
to exhort the careless and lukewarm professors to religious thoughtfulness,
and to exert their zealous endeavours to preserve
the reputation of the society unblemished.

Then recommending them to God and the word of his Grace, he took boat again for Maryland,
where arriving after a troublesome and tedious passage,
after some time spent amongst them,
he appointed a general meeting at West River for the friends in the province,
that he might see them together before he departed, proposing to take his leave of them,
and proceed on his way to return for England.
To this meeting came George Fox, William Edmundson, and sundry other friends,
whom he had left behind in the West Indies.

These friends sailed from Jamaica for Maryland,
and after a tedious and difficult passage,
especially in passing through the Gulf of Florida,
meeting with contrary winds and tempestuous weather, they were in great danger;
but being mercifully preserved, and the weather growing more temperate,
in something more than six weeks they reached the
mouth of Potuxan river in the Bay of Chesapeak,
where another great storm arising, a boat near them, with several passengers on board,
being in great distress, the ship, which they were in,
took in the passengers before the boat was lost.
These faithful ministers,
ever diligent in propagating the gospel and spreading the truth,
not discouraged by perils by sea or perils by land,
from a zealous exertion of their ministerial labours on all occasions,
confiding in Divine Providence for protection through all proving seasons,
and strengthened and supported by the consciousness of integrity in discharge of duty,
took the present opportunity to hold a religious meeting
with these new passengers to mutual satisfaction.
But their provisions growing short, through the tediousness of their passage,
and their having thus got an additional number to feed, without any addition of food,
their scanty store was soon consumed.
In this exigency George Pattison, at the hazard of his life, took boat,
and providentially got safe ashore;
and soon after some friends residing in that part of Maryland came aboard,
and brought the rest safe to land also, very opportunely,
their provisions being quite spent.

Soon after their landing they went directly to the general meeting at West River,
appointed by John Burnyeat, which afforded them, as well as him,
a seasonable opportunity of seeing the friends of the Province together.
The meeting was very large, and held four days, being attended generally by friends,
and numbers of other societies, and several of the principal rank among them.
After the public meetings were over,
the men`'s and women`'s meetings for discipline succeeded, in which George Fox,
with admirable ability and clearness, explained the benefit,
the end and the manner of holding these meetings, discipline.
His friends here received his directions with becoming condescension and cordial satisfaction,
and the meeting being ended, friends separated, under a sense of divine favour.
After this the travellers went together to another
general meeting appointed at the Cliffs,
which was also large,
and the people attended reverently to the doctrines delivered there.
They had also a general meeting for discipline,
at which the several particular meetings of discipline were established;
and most of those who had apostatized with Thurston, and remained unreconciled,
returned into unity with their friends.
