== Chapter XXI.

[.chapter-synopsis]
* Friends part company
* William Edmundson goes to Virginia
* Thence through the Wilderness to Carolina
* Returns to Virginia to a Men`'s Meeting appointed there
* Friends here agree to the Establishment of Discipline
* William Edmundson passeth on to New York, and hath a Meeting there at an Inn

After these two general meetings the friends from Europe parted company,
dividing themselves upon their respective services.
James Lancaster and John Cartwright went by sea to New England; George Fox,
John Burnyeat, Robert Widders and George Pattison toward Jersey,
and William Edmundson for Virginia.
Here William, as John Burnyeat had done before him, found sundry disorders yet unremoved.
He had several edifying meetings amongst them,
whereby having brought them to a better temper,
and cultivated a friendly disposition in their minds, he appointed a men`'s meeting,
for the settling of an orderly discipline amongst them,
after the model of that established in England and Ireland.
From hence he travelled to Carolina, through an uninhabited wilderness;
he and his guides through the passed two nights in the woods,
in the latter of which he could not lie down, it rained so violently, the ground wet,
and himself wet to the skin, so that he passed the night partly under a tree for shelter,
and partly walking between the trees; added to this uncommodious circumstance,
his guide was uncertain about the way, but William,
having the day before advanced farther in the woods than his guides,
who were tired and faint, had discovered a path, to which he leading the way,
it took them to Henry Philips`'s house by Albemarle river, the place of their designation.

His host and hostess, who had been convinced in New England,
and removed their residence hither,
received him and his company with remarkable gladness,
not having seen the face of a friend for many years.
It was first-day morning, but William being weary and faint with fasting and travelling,
found it requisite to take some rest,
he therefore appointed a meeting about the middle of the day, to which many people came,
but, as is too much the case in these desert countries,
they seemed to have little sense of religion amongst them,
for they sat down in the meeting smoking tobacco; notwithstanding which,
William`'s testimony, in the authority of the gospel, had that reach upon them,
that they were affected with great seriousness,
desired him to stay with them with more meetings.

At this meeting, one Tems, a justice of peace, and his wife, being convinced,
desired to have the next meeting at their house, which was accordingly held,
and being favoured with divine regard,
was conducive to the convincement and edification of several of the auditory.

Having appointed a men`'s meeting in Virginia,
he was under a necessity of returning thither from this second meeting in Carolina.
After a journey of great pain,
through sickness contracted by hardships in the wilderness, he reached the men`'s meeting,
where friends readily consented to the establishment of discipline,
and desired to have another meeting of the same kind appointed before he left the country,
to which agreeing,
and in the intermediate time visiting sundry places and meetings to satisfaction,
he attended the said men`'s meeting; previous to which a meeting for worship being held,
it was attended by several persons of condition, as Justice Taverner and his wife,
who was one of the society, Major-general Bennet, Colonel Teve and others.
This meeting proved to general edification,
the doctrines of the gospel being delivered with powerful energy,
and the hearts of the people affected with religious thoughtfulness.
When this meeting was ended,
the members of the society withdrew into a large upper room to the men`'s meeting,
to confer upon and settle the affairs of the church.
Justice Taverner`'s wife, who was of the society,
informing William that the major-general and Colonel Teve, and others below,
were desirous to speak with him, he went down;
they told him they only wanted to take leave of him,
and acknowledge the truth of his doctrine; whereupon apologizing for friends withdrawing,
he told them the reason was,
to lay down a method for providing for their poor widows and fatherless children;
to take care that no disorders were committed in the society, and that all lived orderly,
according to what they professed.
That in England and in other places friends had such
meetings appointed for the like purposes.
This account gained the major-general`'s approbation,
he saying he was glad there was such care and order amongst friends,
and wished it had been so amongst others.

Having thus been instrumental to settle good order in some
measure amongst the members of the society in Virginia,
he returned through Maryland to New York.
He was very desirous of a religious meeting with the inhabitants of this town,
where no meeting of friends had ever been held;
and the owner of the inn where he lodged being willing
to accommodate him with a large room,
the meeting was accordingly held, largely attended,
and amongst others by some of the chief officers, magistrates and principal inhabitants.
They were very solid and attentive to the doctrine he delivered, and affected thereby,
which appeared in their affectionate demeanour to him after the meeting was over.
From thence he went to Long Island and Shelter Island,
where he met with George Fox and his companions on
their way from New England to Virginia.
