== Chapter XXII.

[.chapter-synopsis]
* George Fox, etc. go to the Eastern Shore
* Thence by Land through the Wilderness to New England.
* Lodged in the House of an Indian King
* Half Year`'s Meeting in Long Island
* Opposition being expected from a dissatisfied Party
* A Day is set apart for hearing them
* Yearly Meeting in Rhode Island held for six Days
* Discipline established
* J. Burnyeat and others go to New England
* Meeting disturbed at Scituate
* Thatcher, Priest at Boston, endeavours to stir up Persecution
* James Lancaster and John Stubbs imprisoned at Boston and banished
* Bellingham, Governor of Massachusetts, dies
* Meet with little Success among some who are drawn aside by J. Perrot
* Dispute with Roger Williams
* William Edmundson embarks for Ireland

After their separating in Maryland to their respective services,
the last-mentioned friends, viz. George Fox and his companions,
went by boat to the Eastern shore, and had a large meeting there, to which,
besides many persons of quality of the country, came one of the Indian kings,
Eastern and some other Indians coming thither,
George Fox had two meetings with them in the evening of the same day;
they seemed very attentive to his doctrine, and owned it to be truth.
Then he desired that what he had spoken to them, that they would speak to their people,
and make them acquainted that God by his witness in their hearts
was willing to make himself known in their wilderness country,
and set up his glorious ensign of righteousness amongst them.

From hence they took their journey by land through for New England,
which at that time was an undertaking of great peril and difficulty,
most of the intermediate country being a dreary uninhabited wilderness,
intersected by large and deep rivers, some of which they headed,
others they passed in canoes, swimming their horses by the sides;
sometimes they were under a difficulty to procure Indian guides,
and the Dutchman whom they had hired was not willing
to undertake the guidance without an Indian;
they lodged some nights in the woods, some in the Indian wigwams.
In some whole day`'s journeys they saw no human creature besides their own company,
not an house or dwelling-place in the way.
One night reaching an Indian town, they lodged at the king`'s house or wigwam,
who entertained them with affectionate kindness,
and his attendants were assiduously respectful to them;
they fared and lodged as well as himself, but provisions were scantily afforded them,
not for want of hospitality,
but because he had been unsuccessful in the chase and caught little or nothing that day.
They lay on mats on the ground, with blocks of wood or such like for their pillows.
In nine days they reached Middletown in East Jersey, where was a plantation of English,
and amongst them some of the people called Quakers.
After a short stay at the house of Richard Hartshorn, a man of an hospitable,
benevolent and honourable character, who had lately removed from London,
they were by him carried over in his boat to Long Island,
whither they were hastening to the half year`'s meeting to be held
at Oyster Bay for that island and the province of New York.
The said half year`'s meeting began the fourth day after their arrival,
and lasted four days.
The two first days were employed in holding public meetings for worship;
the third day was allotted for holding the men`'s and women`'s meetings
for the needful care of the affairs of the church.

As opposition was expected from these prejudiced and contentious spirits,
who had disturbed the last half year`'s meeting there,
George Fox did not think it proper that the service of the men`'s
and women`'s meetings should be interrupted by their cavils;
but let them know,
that if they had any objection to make to the discipline of the society,
a meeting should be appointed for the purpose;
the fourth day was therefore set apart for this business,
open to as many of the opponents as chose to attend it, and to friends likewise;
but those of the prejudiced party,
who had been so free in their reflections upon George Fox when remote from them,
began now to fawn upon him, and cast the blame upon others,
particularly George Dennis endeavoured to exculpate himself; but John Burnyeat,
who had been witness to his conduct at the last half year`'s meeting as well as this,
proved evidently that he was the principal actor and instigator
in the opposition to the good order of the society,
and in reading their book of reflections thereupon,
and upon George Fox as the founder thereof,
whereby his deceitfulness being made manifest,
he and his party were confounded and foiled to that degree,
that their attempts to disturb the peace of the society were entirely frustrated.

After some little time spent in Long Island in the work of the ministry,
these European friends took shipping for Rhode Island to attend
the Yearly meeting to be held there for the province of New England,
where they met with John Stubbs, just arrived from Barbados,
and James Lancaster and John Cartwright from New England,
with a number of friends from different parts of the province.
This yearly meeting was continued by adjournments for six days successively;
the first four were employed in public meetings of worship,
to which the governor and several justices giving daily attendance, their countenance,
drew abundance of people from all parts of the island,
amongst whom these friends found an open reception for their ministry:
For this large auditory behaved in a manner remarkably solid,
becoming the solemnity of the occasion,
hearing the doctrines of truth with diligent attention,
and regarding the promulgators thereof with cordial affection during these four days;
the fifth was appointed for holding the men`'s meeting,
and the sixth for the women`'s meeting, which were both large, solemn, instructive,
and beneficially conducive to the end of the appointment.
Many important remarks being made upon the use and
intent of meetings of discipline in general,
the several particular men`'s and women`'s meetings,
to be held in the different parts of the province constituting this yearly meeting,
were agreed upon and fixed,
to take care of the poor and other general concerns of the church,
that the members of the church might not blemish the truth they professed
by a life and conversation inconsistent with the principles thereof,
by the purity of their manners and integrity of their lives,
might be of a good favour among their neighbours, blameness and harmless,
without rebuke.

During their stay on the island,
a marriage was solemnized between two of the people called Quakers
at the house of a friend who had formerly been governor thereof.
Some justices and many others, as well as friends, attended,
who all confessed they never saw such solemnity on such an occasion,
so solemn a marriage, and such decency of order.

George Fox and Robert Widders stayed yet longer in the island; but John Burnyeat,
John Cartwright and George Pattison went to the eastern parts of New England,
in company with the friends from thence.
Their first meetings were at Marshfield, Sandwich and Scituate,
to advantage and consolation.
As John Burnyeat was in the exercise of his ministry at Scituate,
some of the elders of the independent church came to the meeting,
which was held in an orchard, and was very large, and made opposition to him;
but the people being much displeased at the interruption,
desired them to be still '`till they had done,
upon which they went away to their own worship,
and after it was over returned to hold a disputation with these friends,
in which directing their endeavours to make the Quakers appear
in the eyes of the auditory as a people under delusion and error,
John Burnyeat proposed to them,
that since they represented him and his friends as
heretics and their own church as a true church,
that they should try both by the criterion laid down by Christ himself, that is,
by fruits; and although they were averse to close in with the proposal,
he proceeded to recount the fruits of their church,
viz. fining and distraining for not attending their worship, imprisonings,
cruel whippings, cutting off ears, burning in the hand, banishing and putting to death,
only upon account of religion;
if they could prove these to be the fruits of a true Christian church,
they were to be owned as such; but if not, they were to be denied:
These elders could not relish this kind of argument, having some of them,
as he was informed, been themselves active in persecution,
and therefore put an end to this discourse upon a disagreeable subject by withdrawing.

The violence of persecution was by this time abated in this province,
(the persecuting magistrates being mostly dead) yet not wholly abolished;
some of their preachers and others of the old stamp still remaining,
used their endeavours to keep the spirit thereof alive.
The next day these friends went to Boston, where many people came into the meeting,
and while John Burnyeat was speaking to them, the marshal and a constable came in.
The marshal bidding the constable, who was a moderate man, to execute his office,
he replied, So he did, he was to see the king`'s peace kept.
He stood a while to hear, went away,
and told the deputy governor he had been at the meeting,
and heard nothing like blasphemy, but solid and important truths, or to that effect.
The people stayed and furnished him with a fair opportunity
to preach the gospel to their edification,
and to vindicate the society from the calumnies of the priests and others.
The people departed greatly satisfied, and applauded the doctrine they had heard,
which when Thatcher, one of the Boston preachers, understood,
actuated by the old spirit of persecution still alive in him, the succeeding first-day,
in his sermon, he excited the magistrates present against the Quakers,
who immediately sent to take friends from their meeting,
and committed several of them to prison.
Also James Lancaster and John Stubbs, who came after these the following week,
were imprisoned and banished out of the colony by R. Bellingham, governor,
who had been deputy under J. Endicott, and a party with him,
in all the inhuman severity of his government;
but his power of punishing was near its termination,
for soon after this he went distracted,
and in that state departed this life the 7th of December in this year.

These friends from Europe continued their travels and religious
labours for some time longer on this continent,
edifying their friends by their ministry,
settling meetings of discipline for preserving and promoting a circumspect conversation,
Christian charity and tenderness, brotherly affection and cordial unity amongst them,
whose numbers were now increased by convincement.
To avoid the tediousness of repeating similar circumstances I forbear
tracing their respective movements in their further services,
restricting myself to the more notable passages to be met with in their progress.

John Burnyeat and his companions continued their journey to Salem,
and here met with some more of those who had been perverted by John Perrot`'s
notions in keeping on their hats at the time of public prayer,
amongst whom John Burnyeat and his friends exercised much labour in Christian
patience and solicitude to convince them of their error;
they appointed a second meeting with them,
in order to prevail with them to establish meetings of discipline,
the service of which being clearly explained to them,
whom they they could not help assenting to the expediency to introduce thereof,
and yet when pressed to come into the practice of holding these meetings regularly,
they discovered a manifest reluctance.
John Burnyeat observing their disinclination to comply with the advice of their friends,
represented to them, with sorrow, that while they continued in the spirit they were in,
they could not act in the church in the unity of the body,
to the honour of the holy head, or the edification of the members thereof,
'`till they saw their error and condemned it.
So saying he left them.
However this remonstrance had that effect, that, in several,
their consciences were so awakened, as to let them see their mistake, condemn it,
and return into unity with the body.

From hence they journeyed on to Providence and Rhode Island;
at the former place they met with a company of Ranters,
who went generally under the name of Gortonians,^
footnote:[This name was given them from their leader, Samuel Gorton,
who is represented by Neale, in his [.book-title]#History of New England,#
as a most impudent enthusiast, who had no settled notions of religion,
having disowned the principles of the Puritans,
and embraced no other that he knew off that he was not only unprincipled in religion,
but of turbulent behaviour in every state where he resided.
He was banished from Boston and Plymouth, and went to Rhode Island;
that he behaved with such insolence there,
that he was whipped and banished from that island,
and then went over to Roger Williams at Providence,
where entering the lands of some Indians,
he had like to have involved the English in an Indian war, for which he was condemned,
with six of his disciples,
by the Massachusetts`'s government to the work-house for six months,
and afterwards to depart the country.
Neale.]
but called themselves Generalists.
These people gave them some trouble, and a greater degree of disgust;
by their wicked and immoral principles,
maintaining that no creaturely actions could be sin, neither fornication nor drunkenness,
nor such like immoralities; only spiritual uncleanness;
the outward action was but creaturely; thus, like the Ranters in England,
making an unintelligible discrimination between the action,
and the temper of the mind it was done in.

At Rhode Island they met with George Fox and his companions going westward,
in whose company George Pattison joined.
They also here received a challenge from Roger Williams
of Providence with fourteen propositions,
which he engaged to maintain against any of the Quakers from Old England,
proposing a discussion of the first seven in Rhode Island.
The challenge was accepted, the meetings held for three days,
and terminated in a clear conviction of the envy and prejudice of the old man,
whose propositions (as he called them) were a collection of general charges and accusations,
which he could not make good,
but which were plainly disproved to the satisfaction of the auditory,
whereby at length he was silenced.

The friends, whom William Edmundson had joined,
had afterwards a religious meeting with the people, who, at the conclusion thereof,
departed well satisfied and kindly affectioned to them.
Soon after William Edmundson proceeded to Boston,
from whence he embarked for Ireland and returned home.
