== Chapter XXIII.

John Burnyeat and John Stubbs continue their Travels.--Rigidness prevalent in the Government
of Massachusetts.--At Greenwich a Priest raises an Expectation of a Dispute,
but procures a Warrant to apprehend them.--The Magistrate being moderate
advises them to a Conference.-- Remarkable Incident.--George Fox,
Robert Widders, life,
travel through the Woods to Maryland.--General Meeting there.--They go
to Virginia by Water.--Thence through the Wilderness to Carolina.--Where
they visit the Indians as well as the Colonists--Return to Europe.

After William Edmundson had taken his passage to Ireland,
John Burnyeat and John Stubbs continued their journey through New England.
When they came into the government of Massachusetts they
found the root of bitterness still fruitful in that quarter.
When they appointed meetings, the officers would come and prohibit them,
and so terrify the people with menaces of bringing them
under the penalties of their ecclesiastical laws,
that few or none durst come near them;
when they remonstrated to the officers and elders they would not stay to hear them,
but would only exclaim against their religion and them as heretics,
although at the same time confessing they knew not what their principles were,
speaking evil of the things they understood not,
and tacitly manifesting that they had proceeded in persecuting this society,
even to banishment and death, without ever giving them a fair opportunity of being heard,
or well knowing for what reason they inflicted these severities upon them.
At other times the elders would come to dispute with them, on purpose by their presence,
to awe the younger people from coming to hear their doctrine,
which excited the desire of the young people so far,
that since they could get no public opportunity of hearing them,
several of these resorted to their chamber at the inn,
to whom these friends explained their principles, proving them by the scriptures,
whereby these young people were well satisfied and edified;
but when the elders and dry formal professors discovered this private opportunity,
and understood they were much affected thereby,
they sent a constable to command all to depart, which they declining, the inn keeper,
who was an elder, took away the candle, upon which they went away much displeased.

When they came to Greenwich they met with some friends and appointed a meeting there.
The priest of this town had frequently made the supposed errors
of this society the topic of his invectives in the pulpit,
and boasted how he would dispute with the Quakers if any should come thither,
which occasioned a great concourse to the meeting,
in expectation of the priest`'s making good his vaunt;
but he thought best to cut disputation short,
by mounting his horse early in the morning and riding to Stamford about two miles,
to complain to a magistrate,
who sent a constable with a warrant to apprehend the said two friends;
they coming at the beginning of the meeting, took them,
and carried them before the magistrate; many of the people followed, and friends also,
to see the result.
They were called into an inner room to the magistrate, he being indisposed, two priests,
the constable, and one other present.
This magistrate, a very moderate man, asked them several questions,
to which they returned suitable answers; they had much discourse,
with which he appeared well satisfied; but upon one of the priests putting a question,
John Burnyeat remarked, that if they were disposed to discourse on religious subjects,
a more public place would be best adapted to that purpose,
as the people were without and desirous to hear; which proposal the magistrate seconded,
saying, "`Mr. Jones and Mr. Bishop, I desire you to go into the public meeting-house,
and discourse with these men before the people,
for they are sober rational men.`" Upon which the friends retired,
and went to the meeting-house, whither the priests followed,
not without symptoms of being mortified at the disappointment of
their desire through the moderate disposition of the magistrate.
They spent several hours in conference upon the wages and call of Gospel ministers,
election and reprobation, also of free grace; wherein the priests,
in contradiction to plain scripture testimony,
alleged that the Grace of God had not appeared to all men.
The discourse John Burnyeat writes was drawn up in manuscript,
but was too copious to be inserted in his journal.
The next day they had another meeting at Greenwich,
to which the priest came and entered into fresh debate, but failed of his principal aim,
for the magistrate would not imprison them,
but suffered them to proceed on their travels without further molestation.

In the mean time George Fox, Robert Widders, etc. passed to Providence and Narraganset,
and thence to Long Island, Shelter Island, and thence to Shrewsbury in East Jersey.
Here they met with an incident which it may not be improper to recite,
for the sake of the service it may be of in the like case.
They had in their company one John Jay, a planter, in Barbados,
who intended to accompany them, through the woods to Maryland,
and mounting an horse to try him, being ill broken, it immediately ran away,
and threw him on his head, and they believed his neck was broken.
Those who were near him took him up as dead, and carried him and laid him on a tree.
George Fox got up to him as soon as possible, and feeling him, concluded he was dead.
As he stood commiserating him and his family, he took hold of his hair,
and found that his head turned any way.
He then took his head in both hands, and putting one under his chin,
and the other behind his head, he raised it two or three times with all his strength,
and brought it into its place, whereby his neck recovered its usual stiffness.
He began first to rattle in the throat, and then to breathe,
to the amazement of all present.
Being taken into the house, getting some warm drink, and being put into a warm bed,
he recovered so well (though he had no recollection of what had befallen
him) that he continued his journey with them next day to Middletown,
and several hundred miles afterwards.

From hence they took their journey to Maryland through the woods,
having hired Indian guides.
In this journey they met with equal difficulties with those they had before experienced,
in the like wilderness journey from Virginia to New England.
They lodged some times in the woods, sometimes in the Indian wigwams.
They had many large rivers to cross, some of which they crossed near the head,
others in canoes, swimming their horses by the sides thereof.
Through numerous difficulties they reached Newcastle in five days,
where George Fox was hospitably entertained by the governor,
and had a meeting at his house the next day, pretty large, most of the town attending it,
as there had never been any meeting of that kind in this town or its vicinity before.
It was refreshing to the travellers, and satisfactory to the people,
who in tenderness confessed to the truth of the doctrines published amongst them.

From hence, by very hard travelling through the like inconvenient ways,
they got to Robert Harwood`'s at Myles River in Maryland in three days more.
In this province they had several meetings to profit, both amongst the inhabitants,
attended by many of the first rank, and also amongst the Indians,
to whom George Fox spoke by an interpreter.
They were seriously attentive to his doctrine,
and discovered a very affectionate respect to himself.

Soon after the general meeting for friends of General the province came on,
which lasted five days; the three first for public worship,
which meetings were very large, comfortably edifying to friends,
generally acceptable to the people, and conducive to the convincement of many;
the remaining two days were applied to holding the men`'s and women`'s meetings.
When the meetings were over, they took their leave of friends in these parts,
leaving them well established in the truth.

They continued their religious labours some time longer in Maryland,
passing from place to place by water in open boats,
whereby they were much exposed to wet and cold, and frequent storms;
but their zeal and diligence in the discharge of duty,
and filling up their days work in honest endeavours
to bring mankind to the knowledge of the truth,
that they might be saved,
through confidence in divine protection surmounted
all the difficulties and dangers of the way.

When they had finished their service in Maryland they went to Virginia by water,
and from thence by land to Carolina, through a wilderness abounding with bogs and swamps,
whereby they were frequently, wet to the knees,
and at night were obliged to lodge by a fire in the woods.
They had meetings in most habitable places, as they passed along,
in all which they expressed their satisfaction in the peace
they felt as the reward of their labours and travels,
and in observing the beneficial effects thereof on the auditory,
by bringing them to religious thoughtfulness in these desolate countries,
where few or none of this society had travelled before,
and where they had little advantage of religious fellowship.

Nor did they confine their labours within the precincts of the English government;
the principle of universal love, which they professed and cultivated,
incited them to travel and labour among the Indians
in the back parts of Carolina done in other provinces,
endeavouring, by the help of interpreters,
to suit their doctrine to the comprehensions of these people,
by whom also their christian labours were well received, and they would own,
they understood what was spoken, and that it was very good.

From Carolina they returned back through Virginia to Maryland,
and after spending some time in that province, till the general provincial meeting,
which held four days, they took their leave of friends in those parts,
and embarked at Potuxant for Bristol,
as John Burnyeat had done some time before for Galway in Ireland, on their way home.
