== Chapter XXIV.

[.chapter-synopsis]
* In the Time of the Indian War in New England
* William Edmundson under impulse of Duty travels a dangerous Journey to the Eastward
* Had Meetings where none of this People had been held before, at which several were convinced
* He visits a religious People at Reading, at the House of one Gould
* Where William Edmundson`'s Preaching had a good Effect
* After the Indian War an epidemic Sickness ensues, which proves very mortal
* William Edmundson seized with it, but recovers
* He embarketh for New York
* At New London endeavours to get a Meeting, but is prevented
* William Edmundson and James Fletcher pay a Visit to a Meeting of Baptists
* William Edmundson questions them concerning the Sabbath, as introductory to the Exercise of his Ministry amongst them
* Some Professors of this Age fond of the Old Testament
* Meeting near New London broken up by Officers and armed Men

It hath already been observed that William Edmundson
after visiting Barbados a second time in 1675,
sailed from thence for New England and landed in Rhode Island.
This was in l675 the height of the New England war with
the Indians under the command of Philip king of the Wampanoags,
which made travelling very dangerous.
He stayed some meetings with friends in Rhode Island,
which was not molested by the Indians,
for the governor being one of the society of the people called Quakers,
the inhabitants had taken no part in the war:
But on the Continent the Indians carried on the war with considerable success;
after their savage manner burning several towns and houses,
and daily murdering some or other of the inhabitants,
such as they could surprise or overpower.
It was an usual custom with them to conceal themselves
behind the trees or among the bushes in the woods,
and moot down the passengers before they were aware,
and numbers were murdered in that manner.

William Edmundson thought it his duty to travel Eastward to Piscataway,
to visit his friends in their distress, on account of the war:
This was by all esteemed a very perilous undertaking, yet under persuasion of duty,
and trust in divine protection, he had the courage to undertake the journey;
one friend ventured to go with him as a guide through the woods to Sandwich, where,
through gracious mercy, they arrived in safety.
Friends were greatly rejoiced at his brotherly visit in this discouraging season,
and he also was favoured with the consolation of inward peace in the discharge of duty,
in faith, through difficulty and danger; he had two meetings with them,
to their mutual refreshment and comfort.

From thence he travelled to Sessenase, Boston.
and Salem, and so to Piscataway river and Great Island, visiting his friends,
and appointing meetings with them, as he passed along, to mutual satisfaction.
He proceeded by boat to Nicholas Shapley`'s, a friend of note in the country,
and from thence over the river to visit his friends on that side,
had a meeting with them on the first day of the week, which was very large and edifying,
many came far to it, and expressed their thankfulness for that comfortable opportunity.
Then he returned to Nicholas Shapley`'s and stayed some days,
where he had a satisfactory public meeting, and also one for discipline.

At this time there was a cessation of arms on that river;
and one evening while William Edmundson rested at Nicholas Shapley`'s,
fourteen able Indians came into his house;
their heads being trimmed and faces painted for war
gave them a fierce and terrible appearance.
As some of them could speak broken English,
William Edmundson endeavoured to enter into familiar conversation with them,
but from the moroseness of their carriage, and the fierceness of their countenances,
he conceived they were meditating hostile measures;
however they went off in the night without offering any injury.
In the morning his host acquainted him that he had intelligence
that the Indians were designing to make a new incursion,
which proved true,
for soon after accounts came of their having murdered seventy white people,
but William did not hear of any friend being of the number.

William Edmundson returned to Salem, and thence to Marblehead,
and had several meetings in those parts, both amongst friends,
and in places where none had been held before; many people resorted to them,
and several were convinced:
For by reason of the wars which spread into most quarters of those colonies,
the people`'s minds were greatly humbled by the apprehensions
of danger to which they were exposed,
not only of losing their substance, but their lives also.

Thus travelling in many places, as with his life in his hand,
and hearing of a religious body of people at Reading,
he felt a draft of duty to pay him a visit,
and in company with five or six friends more went thither, to an ancient man`'s house,
whose name was Gould, and his house a garrison; for at that time most people,
except those called Quakers, were in garrison, for fear of the incursions of the Indians.
When they came to the house, the gates were locked,
but upon their calling they were presently opened,
and when they entered they found several assembled for the exercise of religious worship,
to which their coming in seeming to give some interruption,
William Edmundson informed them, that they came not to disturb them,
for he loved religion, and was seeking religious people;
upon which the master of the house desired him to sit down,
and took the next seat for himself.

As William sat amongst them,
he felt his heart warmed towards them in the love of the gospel,
and told them he had something in his heart to declare amongst them,
if they would give him leave: The master of the house bade him speak:
His heart being filled with the word of life,
he spoke in the demonstration of the spirit and of power,
to the awakening of their consciences, and reaching the witness of God in them,
to own the truth of his testimony: And after he had finished his testimony,
he concluded the meeting in prayer.

At the conclusion the old man, the master of the house, was so affected, that he rose up,
took William in his arms, owned what he had spoken to be sound doctrine,
and thanked God that he could understand it; adding,
that he had heard that the people called Quakers denied
the scriptures and denied Christ that died for them,
which he understood to be the cause of the difference
between their ministers and the said people;
but that this day had convinced him of the falsity of the charge,
as he had witnessed that they owned both Christ and the scriptures.
Although the depredation of war had made provisions scarce in these parts,
he would not part with them, until they had dined with him.
Then the friends leaving these people impressed with religious
desires for themselves and affectionate regard to their visitors,
the old man embraced William again, signifying, he doubted his ever seeing him any more.

He had several meetings at Boston and parts Boston, adjacent,
where he met with considerable exercise and trouble, by means of some persons, who,
professing themselves of the people called Quakers,
did not live up to the principles of their profession, which did much hurt,
as administering occasion of offence to those who sought it,
and counteracting the religious labours of such worthy ministers,
as in apprehension of duty, were concerned to leave every domestic comfort,
and travel to remote lands, through many hardships and perils,
to propagate righteousness, and spread the knowledge of truth, which good work,
he regretted, was obstructed by such unfaithful professors.

Being at length clear of those parts he passed over to Rhode-island
in a bark belonging inhabitants to Edward Wharton of Salem.
Here he found friends attended with difficulties by reason of the wars,
which raged in many places in that quarter, out of the island: The Indians plundering,
burning and killing as they went along; which made the inhabitants of the island,
who were not of the society, eager to arm; but the governor Walter Clark,
being a member thereof, could not in conscience issue commissions to kill and destroy.
Under their present trouble friends were strengthened
and encouraged by William Edmundson`'s company,
he stayed some time amongst them,
and had many edifying and comfortable meetings with
them both for worship and discipline.

During his stay at Rhode-island, the heat of the Indian war abated,
King Philip being killed, and his party subdued; but almost immediately after,
this island was visited by an epidemically mortal distemper, which proved so mortal,
that few families therein escaped the loss of some
of their number in two or three days sickness.
William Edmundson was diligently employed at this
time in visiting the families of his friends,
(of whom many died) although the smell of the sickness was loathsome,
and but few escaped the infection; he expected himself to take it,
frequently feeling himself as loaded therewith;
and after some time he was actually seized with it,
and obliged to take to his bed at Walter Newberry`'s at Newport; but,
through the favour of divine providence, he was brought safely through,
and restored to health,
so that in about ten days time he was able to appear at public meetings,
and although he was weak, not only by his sickness, but the trouble he met with,
by disorderly walkers, who took undue liberties in their conversation here,
as well as in New England, yet he felt divine support bearing him up over all.

From hence he took shipping for New York, having James Fletcher for his companion;
but by contrary winds was driven back to New London, and being detained some days,
they endeavoured to get a meeting there;
but the inhabitants being rigid independents or presbyterians, and filled with prejudice,
would not suffer one to be prevented, held amongst them.

About five miles from hence dwelt a company of baptists, called seventh day baptists,
because they kept the seventh day of the week for their sabbath;
and bearing the character of a sober conscientious people,
William Edmundson felt his mind drawn to pay them a visit, and accordingly went thither,
accompanied by his companion James Fletcher,
and a friendly old Englishman who resided near New London.
On the seventh day of the week, when they came thither,
they found them assembled in silence; when they went in,
these people seemed to be disturbed; William gently informed them,
that he and his companions had not come to disturb their meeting,
but hearing that their sentiments in religion were different
from those of the generality of the people in that country,
they were come to visit them, and if they had a religion that was good,
to share with them.
The master of the house then invited them to sit down; they sat some time in silence,
when William feeling a divine authority to speak,
and that these people had honest desires in their hearts after the knowledge of God,
he began his service by way of question,
"`Why they kept that day as a sabbath?`" to which they answered,
"`because it was strictly commanded in the old testament.
He next queried, "`if we were obliged to keep all the law of Moses?`" They replied, "`No;
but the keeping of the sabbath seemed to be required
more than the rest of the law.`" From this introduction,
William took occasion to inform them,
that to keep the sabbath after the Jewish law under
the christian dispensation was not necessary,
as Christ himself did many things which the Jews esteemed a breach of the sabbath;
that Christ had ended the law of the old covenant,
and now was himself the rest of his people; and that all must know rest,
quietness and peace in him.
These people sitting in stillness and quietude furnished
him with a favourable opportunity to continue his declaration,
in the authority of the gospel, opening to them the way of life and salvation,
and when he had done, concluded in fervent prayer;
and then took leave of them under the mutual impressions of good will and affection.

There seems to have been amongst many of the professors of this age too
fond an attachment to the Old Testament and the ceremonial law,
not only in the preachers,
who are said to be fond of taking texts and examples from thence,
but also in many well disposed people, like those above-mentioned,
who have been thereby prevented from making advances in real religion,
so far as they might probably have done,
if they had more generally considered the ceremonial parts
of the law only as types and shadows of good things to come;
and the prophecies chiefly to point forward to the benefits
of the spiritual dispensation of the gospel of Christ;
and instead of resting in the shadow and type,
had pressed forward after the possession of the substance typified thereby,
and the good things prophesied of.
I do not mean hereby to lessen in the least degree a due regard to the Old Testament,
as being written by holy men of old; as they were inspired by the Holy Ghost:
As such I value and esteem it;
but the doctrines of the gospel delivered in the New Testament
more immediately concern us under the gospel dispensation,
and confirm, and are confirmed by, many parts of the old;
and both together are an excellent treasure of divine wisdom and religious instruction.

The next day, being first day,
they appointed a meeting near New London at the house of the person,
who had accompanied them in their last visit,
to which several of the baptists and other sober people came;
the meeting was very solidly gathered,
and like to be a favoured and profitable opportunity;
but the old prejudiced and persecuting spirit,
still prevailing amongst the bigoted self-righteous professors in this quarter,
interrupted their solemnity;
for a constable and other officers came with a body of armed men,
and broke up the meeting, haling and greatly abusing the friends,
which much offended the sober people present.
