== Chapter XXV.

[.chapter-synopsis]
* William Edmundson constrained to go to New Hertford, in resignation to divine Disposal
* Goes to one of their Meetinghouses, where he is heard with Attention
* Goes to the other Meetinghouse in the Afternoon, whence he is taken Prisoner
* Being taken to an Inn, he discourses with several Professors
* John Rogers, a Baptist Teacher, entering into Argument with him is confuted
* William Edmundson discharged
* At Long Island they meet with Ranters, who disturb their Meetings
* Edward Tarff, a Ranter, opposeth William Edmundson

Soon after William Edmundson first went aboard the ship,
in order to pass over to New York,
he felt a weighty concern on his mind to go to New Hertford, in Connecticut colony,
which lay about fifty miles up the country, through a great wilderness,
and very dangerous to travel: The Indians, yet in arms, haunting those parts,
and killing many of the English; so that it seemed very discouraging for him,
a stranger in the country, to encounter a journey attended with so much danger.
He therefore kept his concern thus far to himself,
in hopes that he might be excused in this time of jeopardy.
That evening he went on board again, and the vessel set sail, the wind being pretty fair;
but soon turned right against them and blew a storm,
which obliged them to put into harbour, where they lay some days.
William Edmundson being unable to get from under his concern towards Hertford,
apprehended himself, by his backwardness to obey the pointings of duty,
to be the cause of the crosses and detention of the vessel;
and therefore acquainting the company with his concern, he took his leave of them,
signifying he must go in submission to the divine will, whether he should live or die.

Then preparing himself for his journey, and his companion resolving not to desert him,
they went ashore, purchased horses, and next morning set out without a guide,
and travelled hard through the wilderness, for the greatest part of the day,
and reached an inn about four miles from the town:
Here he left his companion and the horses,
and walked early next morning (being the first day of the week) to the town;
he went in the morning to one meetinghouse, and when the priest had finished,
he spoke to the people what was on his mind; they were moderate and quiet,
heard with attention; and when he had done they parted.
In the afternoon he went to the other meetinghouse,
for there were two large ones in the town; when he came thither,
the priest and people were gathered, having a guard of soldiers,
for fear of the Indians coming upon them, while they were at their worship.
William went in, and declared the in the way of salvation amongst them;
but after some time, at the instance of the priest, the officers haled him out rudely,
and hurt his arm, so that he bled, and took him to the guard, upon a hill.

It was a very piercing cold day; the officer who had him in charge, complaining thereof,
asked him "`how he could bear the cold?`" for that he was very cold.
William replied, "`that it was the entertainment,
which their great professors in New England afforded to a stranger,
and yet they professed the scriptures to be their rule,
which command to entertain strangers:`" The officer seemed to be troubled,
and endeavoured to excuse the magistrates.
Then he took him to an inn, and immediately the room was filled with professors,
with whom he had much discourse: As one company went away another came.
William being well qualified to discourse or dispute
with them and well versed in the scriptures,
was furnished with matter to inform the enquirers, and silence the disputers.
When the company in general had given up,
a preacher among the baptists took up the argument,
imputing it to the people called Quakers, as a great error to maintain,
that every man had a measure of the spirit of Christ;
he wanted to know if William held the same error.
William told him, it was no error, for the scriptures testified it in many parts.
The baptist denied that the world had received a measure of the spirit;
but that believers had received it.
And as William brought one scripture after another in confirmation
of the universality of the manifestation of the spirit,
he still restricted it to every one of the believers,
alleging that was the ground of their error, in applying that to every man,
which properly belonged to believers.
William then recollected the promise of our Saviour, "`That he would send the comforter,
the spirit of truth, that should convince the world of sin,
and should guide his disciples into all truth.`" On which he argued thus;
therefore thou must grant that all have received it;
or else prove from scripture that there is a select number of believers,
and besides them a world of believers that have the spirit;
and also another world of unbelievers that have no
measure of the spirit to convince them of sin.
This put him to a non-plus, and many sober persons, who stayed to see the issue,
gave it against him, saying, "`Indeed, Mr. Rogers, the man is in the right,
for you must bring the proof, which he hath demanded,
or grant his argument,`" Then the people departed well satisfied.

As they lodged that night at the same inn,
William took the opportunity of a friendly conference with this man;
and finding by his dis course,
that he also had suffered some persecution from the
rigid presbyterians or independents of that quarter,
he remonstrated to him, how ungenerous it was in him to join with them in opposing him,
who was a stranger and single, engaged against a multitude;
to which he made no reply directly; but gave him an account of himself,
whereby it appears,
this John Rogers had been a member of one of the independent congregations,
but was now a pastor, of those seventh-day people,
to whom William had lately paid a religious visit.

In the morning William Edmundson`' sent to the officer
who had him in charge the day before,
to know whether he had any further business with him,
who sent him back word that he might go when and whither he pleased;
upon which he returned to the place, where he had left his horse and his companion.
In the mean time his companion, uneasy at his stay,
had gone to Hertford by a different way to look for him,
whereby they missed of one another.
At Hertford James Fletcher hearing of his return followed him,
and upon their meeting told him he had set all the town talking of religion.

From hence they went to Long Island, where they were gladly received by friends;
but were much disturbed by a set of ranters, who had arisen in these parts,
and made it a practice to come into friends meetings,
singing and dancing in a frantic manner,
to the great annoyance of their religious assemblies.
Notwithstanding which they had several large and comfortable meetings;
many of these ranters, present in some of them,
appeared to be chained down by the divine power covering these awful solemnities,
and attending the testimonies delivered therein;
whereby some of them were brought to a sense of their errors,
and under the perception thereof to condemn themselves
for their licentious and indecent conduct.

Proceeding to East Jersey, they had meetings at Shrewsbury, and at Richard Hartshorn`'s,
full and large and edifying.
In this last they were disturbed again with those deluded people,
particularly by one Edward Tarff, who came into the meeting with his face blackened,
saying, it was his justification and sanctification;
he sung and danced after their wild manner, and coming up to William Edmundson,
called him old rotten priest.
William told him he was mad, and that made him fret,
and looking at him in the authority with which he was vested,
dared him to look him in the face for half an hour,
where with being smitten and daunted he went away.
William stood up, in the power of the gospel, and appealed to the meeting,
whether this was not the same power of God, in which he came among them at first,
unto which they were directed, and whereby they were convinced of truth.
Shewing them that the ranters, by departing from this divine power,
were deceived by a transformed spirit, and given up to strong delusions.
It proved an edifying meeting; the people were affected with tenderness,
and friends strengthened and edified together.
