== Chapter XXVI.

[.chapter-synopsis]
* An Indian Guide loseth his way in the Woods, and guided them wrong
* Richard Hartshorn adviseth their turning back to Rariton, and they discover the Path to Delaware
* At Delaware Town under difficulty to get Entertainment
* William Edmundson loseth the Use of his Limbs by the Cold in Virginia and the Bay of Chesapeake
* An Indian War and a Civil War in Virginia at the same Time
* William Edmundson hath Carolina in prospect
* His Friends dissuade him from the Journey, as being very dangerous
* But being confirmed in the Apprehension of Duty calling him, he undertakes the Journey
* Arrives there in safety
* And returns to Virginia in like Manner
* And from thence embarks for England

From East Jersey William Edmundson and his companion took
their journey through the wilderness towards Maryland,
with an Indian for their guide, who lost his way and left them in the woods,
where they were obliged to take up their lodging that night.
And next morning being entirely at a loss to find their way in the wilderness,
to which they were strangers, Richard Hartshorn,
who with Eliakim Wardel had accompanied them thus far,
proposed their turning back to Rariton river,
which they had left about ten miles behind them,
to find out a landing place from New York, from which a small path led to Delaware Falls.
This plan succeeded; by travelling all that day,
and taking up another night`'s lodging in the woods,
they reached the falls pretty timely next morning,
where providentially they found an Indian man and woman with a canoe,
whom they hired to set them over the river.
They passed over, after the customary manner of that time,
by swimming their horses by the side of the canoe, and got safely to shore.
They proceeded to Uplands (since called Chester) and to Delaware town,
which at that time was under New York government;
for Pennsylvania was a name as yet unknown.
At Delaware town they were under difficulty to get
entertainment amongst the Dutch and Swedes,
who inhabited it, until William Edmundson applied to the deputy governor,
informing him that they were travellers, and had money to pay for what they called for,
but could not get lodgings for their money.
The governor received them with much courteousness, went with them to an ordinary,
and ordered the landlord to provide them lodging, which was both mean and dear;
but the governor was so kind as to desire them to send to him for anything they wanted.

William Edmundson continued his travels and ministerial
labours (as in his former visit) to Maryland,
Virginia and Carolina, appointing meetings in all convenient places,
and attending the meetings of his friends, wherever they were settled,
which were often very satisfactory and profitable, both the public meetings for worship,
and those for managing the discipline of the church.

While in Virginia, and passing the bay of Chesapeake,
the weather was so cold and stormy that,
for want or fire or covering (being in an open boat) he
in a great measure lost the use of his limbs for a season;
so that when he came ashore he could neither stand
nor walk without the support of two men on each side;
and in the use of like manner was he taken again to the boat.

It was also a time of trouble and danger in this province,
they being at once engaged in a war with the Indians,
and in a civil war amongst themselves.
A young man, named Bacon, availing himself of some discontents among the people,
on account of restraints on trade, by his popular declamations,
gained that ascendence amongst them,
that they chose him for their general against Sir William Berkley,
governor of the province.

In this contest the country was generally involved,
except those of the society of the people called Quakers,
who in conformity to their principles took no active part in the quarrel.
And William Edmundson`'s presence at such a season amongst them, contributed, no doubt,
to strengthen them in a steady adherence to their pacific principles.
He travelled for a considerable time from place to place,
until some frigates came from England with troops to quell the disturbances,
which with the death of their leader, terminated the civil commotions;
but the Indians continued their incursions some time longer.

When he apprehended his service finished in Virginia he had Carolina
in prospect before his return to his native land;
but this prospect was attended with great discouragement,
the Indians being still out in arms, and committing frequent murders,
and particularly frequenting that wilderness, through which his road to Carolina lay,
where very few durst travel unarmed.
His friends used their endeavours to dissuade
him from undertaking so hazardous a journey,
from where (by their accounts) several people had been murdered.
He was naturally a man not easily intimidated,
yet having a tenderness for the reputation of truth more than his own life,
he began to consider, that if he should fall by the hands of the savages,
it might furnish occasion to such as sought occasion,
to depreciate the principle of truth which he professed, and his friends also,
as being under the guidance of a principle of action delusive in its nature,
and leading them presumptuously into error and danger, to the loss of their lives:
For this reason he endeavoured to protract his setting out,
in hopes the concern might be taken from him.
In the meantime he appointed a meeting on the north side of James River,
to which many friends came a great way,
and amongst others the eldest son of the widow Houtland,
at whose house William had lodged,
with whom he took a walk the evening before the meeting,
to give him some friendly advice:
They parted to their respective lodgings in usual health,
and a messenger came before morning to tell William, the young man was dead.

This news was an affecting surprise to his friends,
but particularly to William Edmundson, who with it seemed to hear a language in his soul,
which he took to be a divine warning, expressing itself to this purport:
All lives are in my hand, and if thou go not to Carolina,
thy life is as this young man`'s; but if thou go, I will give thee thy life for a prey.
Thus powerfully impressed with the inward sense of
duty calling him to the performance of the journey,
the next day he began to prepare for it, but none durst venture to accompany him,
except one ancient friend.
In his company he traversed the wilderness,
and through the merciful protection of that divine hand in which he trusted,
in two days reached Carolina in safety; here he had several consolatory meetings.
The people at this time being widely scattered in this colony,
having little or no benefit of ministry amongst them,
received William with gladness and affection; and several were convinced by his labours.
Friends being settled in the discipline and good order of their profession,
he left them edified by his religious service amongst them,
and departed under the comfortable sense of their prosperity in the best things,
and of peace in his own bosom,
resulting from his pursuing the line of duty without being deterred by impending danger,
trusting his life to the hands of him who gave it,
and who he knew had power to preserve it.
In the like religious confidence in divine preservation he returned safe to Virginia.
and from thence to England,
with the view of attending the ensuing yearly meeting at London,
which he reached in due time.

From these accounts it appears that sundry members of this society had
removed to or been convinced in several of the West Indian islands,
also in New England, Rhode Island, Long Island and New York,
and that the number in these parts were sufficiently numerous to
constitute a regular yearly or half yearly meeting in Rhode Island,
for the said island and the province of New England; and in Long Island for New York;
also in Maryland, Virginia and Carolina we find sundry meetings were settled;
and in the two former men`'s and women`'s meetings were established
for preserving good order in the society.
