== Chapter XXVII.

[.chapter-synopsis]
* Settlement in West Jersey
* Friends hold their Meetings at first in a Tent
* Afterwards at the House of John Woolston
* They establish a Monthly Meeting at Burlington
* Commence a Correspondence with the yearly Meeting of London
* Several Friends from Dublin and its Neighbourhood remove thither
* George Fox writes an Epistle of Advice to the new Settlers
* Yearly Meeting established at Burlington

Before and about this time several friends had arrived in West Jersey,
and the Indians were very kind and hospitable,
both by supplying them with provisions on moderate terms, and otherwise assisting them,
so that they were friends not very long there till
they found their new settlement tolerably easy.

One of their first cares was to accommodate themselves with a place for religious worship.
At first they built a tent at Burlington, where they assembled regularly at stated times,
until their meet.
John Woolston had got his house (the first framed house in Burlington) completed;
then they met there, both for worship and discipline, for near three years,
when they removed their meeting to Thomas Gardiner`'s,
where it continued to be held during his life and that of his widow,
till a meeting-house was built there.
Soon after they established a regular monthly meeting for business,
after the manner of the country from whence they had removed,
the first care of which was to make provision for their poor; the next,
to discourage all friends from being concerned in
selling spirituous liquors to the Indians.
In the year 1680 friends of the said monthly meeting of Burlington
commenced a correspondence with the yearly meeting of London.
The purport of their first epistle was to request friends of the
yearly meeting to recommend it to the several counties and meetings,
out of which any of their members might incline to remove to these parts,
to take care to supply them with certificates of their orderly conversation,
right of membership, and clearness from marriage engagements, if single and marriageable,
that friends here might not be at a loss in what light to receive them,
coming strangers amongst them;
which request being agreeable to the discipline established in like cases,
procured a minute of said meeting, recommending to friends a compliance therewith.

A considerable number of friends of Dublin and its vicinity being inclined
in 1681 to remove from thence into the province of West Jersey,
wherein several of them had before purchased an interest,
sent to London and chartered a vessel, whereof Thomas Lurting,
noted for his deliverance from the Turks^
footnote:[This man being brought up to the sea,
was convinced of the principles of the people called
Quakers by means of one of the said people,
who was likewise a mariner on board a man of war.
After which he was repeatedly pressed into ships of war,
and in danger of suffering for refusing to fight, but he kept steady to his principles.
Afterwards being mate to George Pattison, a friend,
as they were passing through the Mediterranean, in their return from Venice,
they were chased and taken by an Algerine Pirate,
and thirteen Turks put on board to take the ship and prisoners to Algiers;
but by the management of this Thomas Lurting the ship was re-taken,
without violating his peaceable principles, in the following manner:
The weather growing stormy, separated them from the man of war, and a night or two after,
it raining hard, he persuaded all the Turks, one after another,
to go down into the cabins and sleep; and while they were all asleep,
he got possession of their arms, which when he had done, he told the sailors,
"`Now we have the Turks at our command, no man shall hurt any of them,
for if you do I will be against you.`" Then they put before the wind for Majorca,
and next morning they were near it, which when the Algerines understood,
they were in great affliction and terror,
and begged that they might not be sold to the Spaniards,
which it was promised they should not, and the promise was made good;
for it being reported on shore,
by an English Captain who wanted to have two or three of them in his possession,
that there were several Turks prisoners aboard their Vessel, the Spaniards, they heard,
threatened to take them away; to prevent which, calling the Turks to their assistance,
they quickly got out to sea.
Afterwards they sailed to the coast of Barbary,
where the mate undertook to put them ashore in their own country;
and after some time of consideration how it might be done in safety, he took them,
with the help of some of the men, in the boat,
so near the more that they might wade to it, which at his desire they readily did;
and because they said they were four miles from any town,
he gave them some bread and other necessaries.
Then putting the boat closer in, they threw them their arms on shore,
and put off to return to their ship.
Thus manifesting in deeds their obedience to the
precepts of our Saviour--Love your enemies,
and do good to them that hate you.]

, was master,
who accordingly sailed to Dublin to take them in, but being taken sick there,
he could not proceed: His mate therefore taking his place,
in about eight weeks after their departure from Dublin
landed them at Elsingburgh near Salem,
where some of them settled amongst their former acquaintance,
who had removed before them,
and whose industry had provided an ample supply of provisions for their accommodation.
There was then a considerable number of friends at Salem, and a meeting-house built;
and several of the houses in that town being unoccupied,
by means of the owners having removed further into the country,
those who had families were readily accommodated with habitations for the present.
After some time several of them took up their land,
and fixed at a place called Newton Creek,
where they raised temporary habitations adjacent to each other, for fear of the Indians,
of whom their fears and jealousies subsided, as they be came better acquainted with them:
Then finding it inconvenient to be seated so near together, they divided their lands,
and removed to their respective plantations;
and notwithstanding the land had been purchased by the Commissioners of the Indians,
they gave them a compensation to remove off.
The Indians were very friendly and serviceable to them in several respects,
often supplying them with venison and corn,
till they could reap the fruits of their own labours, which,
with the supply they received from Salem,
prevented them from suffering much hardship in their new settlement.
In the spring they settled a meeting at the house of Mark Newby,
and in two years afterwards they built a meeting-house at Newtown.
Sundry friends having settled, some by the river`'s side, some beyond Cooper`'s Creek,
and some at Woodberry Creek,
with the concurrence of Burlington friends they established a monthly meeting for discipline,
to preserve their members orderly in conversation,
and for the other good purposes of such meetings; and some time after,
they and friends at Salem increasing in number, composed together one quarterly meeting.

In the latter end of this year George Fox wrote an
epistle of salutary advice to the new settlers,
and those who were proposing to move to the plantations in America; in particular,
to cultivate a good understanding with the Indians,
and by all means in their power to bring them to the knowledge of true religion,
to invite them to their meetings, and hold meetings amongst them,
that truth and righteousness might spread; and that friends, by an upright,
peaceable and honest conversation, might be a light to the nations around them,
wherever their lots might be cast.

The monthly meeting of friends in Burlington was still held at the house of John Woolston,
and consisted of friends residing about the Falls of Delaware,
and those of the meetings of Rankokas and Schackamaxon, who were now grown numerous.
In consideration whereof friends at the said monthly meeting,
held the 2nd of the 3rd month this year,
concluding that a yearly meeting might be of general service,
unanimously agreed to establish one in Burlington,
the first of which was to begin the 28th of 6th month following,
which accordingly met at the house of Thomas Gardiner.
On the 31st they proceeded to business,
and particularly to regulate the holding of the different meetings of worship and discipline,
by appointing the times and places when and where each particular
meeting through the country should be held;
among which a general meeting for worship was agreed to be held yearly at Salem,
on the first day of the 2nd month.

Having now traced the settlement of friends in the various inhabited parts of
this continent from such authentic records as I have had the opportunity of consulting,
the time calls our attention to the planting of a new colony,
wherein this society have become more numerous, and more conspicuous than in any other,
or perhaps in all the rest together.
