== Chapter XXVIII. Pennsylvania

[.chapter-synopsis]
* Pennsylvania granted by the Crown to William Penn
* Of which he is made Governor and absolute Proprieto
* William Penn publishes a Description of the Country, and encouraging Terms of Settlement
* He takes Shipping for his Province
* And at his Arrival is received with joy and Affection
* His Treaty with the Indians
* Kindness of the Indians to the new Settlers
* Liberty of Conscience the leading Article of the Constitution
* First general Assembly

Sir William Penn, who had been long employed in the station of admiral,
both under Oliver Cromwell and King Charles the Second,
at his death had a considerable debt due to him from the crown,
either for arrears or for advances via made to government
in the sundry expeditions in which he was engaged.
The King in lieu of pecuniary satisfaction, by letters patent,
bearing date the 4th of the month called March, 1680-1, granted to William Penn,
son of the admiral, and his heirs, that province lying on the west of the river Delaware,
North America, formerly possessed by the Dutch,
being a part of that tract denominated by them The New Netherlands;
but now the name was changed by the King to that of Pennsylvania,
in honour of William Penn,
whom and his heirs he made governors and absolute proprietors thereof.
This peculiar favour of the king is supposed to be principally
owing to the influence of the Duke of York,
with whom, as high admiral of England, admiral Penn had been a peculiar favourite,
who considering his son exposed to the danger of suffering for his religious principles,
had demonstrated his paternal affection by soliciting the duke`'s protection of him,
which he promised, and in general afforded.

William Penn soon after published an account of Pennsylvania, with the king`'s patent,
and other papers relating thereto, describing the country and its produce,
and offering an easy purchase of lands,
and encouraging terms of settlement to such as might incline to remove thither.
Many single persons and some families from England and Wales accepted the invitation,
especially from North Wales an hardy race of men went over,
well adapted to encounter the difficulties of cultivating a new colony,
having been inured to hard labour for a scanty subsistence
from the barren mountains of their native country.
With singular application and industry they surmounted the
inconveniences generally attendant upon settling in a wilderness,
soon cleared their purchased lands,
and improved their respective plantations to advantage.
And to secure the friendship of the natives to the new colony (who in some other provinces
having been injuriously treated had revenged themselves to the loss of many lives) the
governor gave order to use them with the utmost candour and humanity,
appointed commissioners to treat with them about land, and to confirm a league of peace,
by whom he also addressed the following letter:

[.embedded-content-document.letter]
--

[.signed-section-context-open]
London, the 18th of the 8th month, 1681.

[.salutation]
My Friends,

There is a Great God and Power, that hath made the world and all things therein,
to whom you and I and all people owe their being and well-being;
and to whom you and I must one day give an account for all that we do in the world:
this Great God hath written his Law in our hearts,
by which we are taught and commanded to love and help, and do good to one another,
and not to do harm and mischief unto one another:
now this Great God hath been pleased to make me concerned in your part of the world,
and the king of the country where I live hath given me a great province therein;
but I desire to enjoy it with your love and consent,
that we may always live together as neighbours and friends;
else what would the Great God do to us?
who hath made us not to devour and destroy one another,
but to live soberly and kindly together in the world.
Now I would have you well observe,
that I am very sensible of the unkindness and injustice that hath been
too much exercised towards you by the people of these parts of the world,
who have sought themselves, and to make great advantages by you,
rather than to be examples of justice and goodness unto you,
which I hear hath been matter of trouble unto you,
and caused great grudgings and animosities, sometimes to the shedding of blood,
which hath made the Great God angry.
But I am not such a man, as is well known in my own country:
I have great love and regard towards you,
and I desire to win and gain your love and friendship by a kind, just,
and peaceable life, and the people I send are of the same mind,
and shall in all things behave themselves accordingly;
and if in any thing any shall offend you, or your people,
you shall have a full and speedy satisfaction for the same,
by an equal number of just men on both sides,
that by no means you may have just occasion of being offended against them.
I shall shortly come to you myself,
at what time we may more largely and freely confer and discourse of these matters;
in the mean time I have sent my commissioners to treat with you about land,
and a firm league of peace: let me desire you to be kind to them and the people,
and receive these presents and tokens which I have sent you,
as a testimony of my good-will to you, and my resolution to live justly, peaceably,
and friendly with you.

[.signed-section-closing]
I am your loving friend,

[.signed-section-signature]
W+++.+++ Penn.

--

In the summer of 1682, William Penn himself took shipping for this province,
in order to take possession and establish the constitution and government thereof,
being accompanied by many of his friends, who,
from the prospect of enjoying their civil and religious liberties,
without the molestation they were exposed to in England,
were induced to remove themselves,
to settle under the government of a man with whose humanity, liberality of sentiment,
and religious regard to justice and equity they were well acquainted.

In about two months they finished their voyage,
during which William Penn manifested a- fatherly concern
for his people`'s welfare and accommodation in every respect,
edifying them by his good conversation,
holding religious meetings with them regularly during their pas sage,
and therein labouring to establish them in virtue and righteousness,
as the sure foundation of success and prosperity in their undertakings in this life,
as well as felicity in that which is to come:
And the small pox breaking out amongst them,
his tender care was further evidenced by his compassionate attention to the sick,
in contributing every necessary relief and assistance in his power.
Out of the company about thirty died.

When they had entered the Delaware, and were sailing up that river, the inhabitants,
as well Dutch and Swedes as English, met and congratulated William Penn on his arrival,
and received him with demonstrations of much joy and affection.
He landed at Newcastle,
and next day summoned the people to the courthouse and made a speech,
declaring the purpose of his coming and the ends of his government,
assuring them of the free enjoyment of liberty of conscience and civil freedom,
recommending them to live in sobriety and peace one with another;
previous whereto possession of the country was legally given him.
But William Penn`'s religious principles leading to the practice
of the most scrupulous morality in point of justice and equity,
did not permit him to look upon the king`'s patent,
or the legal possession according to the laws of England,
sufficient to establish his right to this country,
without purchasing it from the natives,
to whom by right of possession it properly belonged.
He entered into and confirmed Indians.
a treaty with them for this purpose, whereby they,
for a valuable consideration in purchase,
freely ceded to him and his heirs the lands in question,
which gave a security to the planters in this colony,
beyond that which those of the other provinces had obtained by much blood shed.
And the testimony of a late author^
footnote:[Voltaire.]
concerning this treaty is very honourable to both the contracting parties,
that "`it is the only treaty between those people
and the Christians that was not ratified by an oath,
and was never infringed.`"

This friendly and pacific manner of treating the Indians begat
in them an extraordinary affection and regard to him and his people,
such, that they maintained a perfect amity with the English of Pennsylvania,
and revered the memory of William Penn long after his decease,
and still continue to hold it in great esteem.

This amicable disposition of the natives was of very great service to the new planters,
who at their arrival found the country a mere wilderness, chiefly inhabited by Indians,
with a few Swedes thinly scattered,
who received and treated them with particular kindness and hospitality,
so that notwithstanding the number of these new colonists was considerable,
they were by the goodness of Providence furnished with the necessary supply of provisions,
partly by the Swedes and Indians,
who brought them abundance of venison and corn at very reasonable rates,
and partly by importation from the neighbouring provinces which were settled before.

William Penn having thus conciliated the affections of the Indians to his colony,
his paternal care and humanity was next applied to lay a lasting
foundation for the peace and happiness of his people among themselves,
by establishing a constitution of government and a body of laws,
calculated to secure their religious and civil liberties,
and the free and full enjoyment of their property on the firmest basis:
Ever an advocate for a full toleration of religion,
he established it in the first place on the broadest bottom,
the leading article of the new constitution being this:

[quote]
____
That all persons living in this province,
who confess and acknowledge the one Almighty and Eternal God to be the Creator,
Upholder and Ruler of the world, and that hold themselves obliged in conscience
to live peaceably and justly in civil society,
shall in no wise be molested or prejudiced for their religious
persuasion or practice in matters of faith and worship;
nor shall they be compelled at any time to frequent or maintain any religious worship,
place, or ministry whatsoever.
____

In the tenth month following a general assembly of the freeholders was held at Chester,
by which Newcastle was annexed to Pennsylvania;
the foreigners there inhabiting were naturalized; and William Penn having agreed,
in concert with the adventurers, previous to their departure from England,
upon the frame of government, and the laws to be established in the province,
(drawn up by himself) the same, with some amendments and alterations, were now confirmed,
ratified and passed into acts of assembly,
of the at as the established laws of the colony.
The proceedings of this assembly were conducted with
mutual affection and remarkable unanimity;
nor is it wonderful that they should,
as no occasion of jealousy could possibly arise between a governor,
whose extraordinary disinterestedness centered his
views chiefly in the ease and prosperity of his people,
and an assembly who placed an implicit confidence
in the approved veracity and equity of their ruler.
William Penn`'s own account,
in a letter to the committee in London of traders
to this province in the fall of the succeeding year,
gives an amiable picture of the harmony subsisting between him and the assembly,
and in the assembly among themselves, viz. "`Two general assemblies have been held,
and with such concord and dispatch, that they sat but three weeks,
and at least seventy laws were passed without one dissent in any material thing.
I cannot forget their singular respect to me in this infancy of the state,
who at their own private expense so early considered mine for the public,
as to present me with an impost on certain goods imported and exported,
which after my acknowledgment of their affection I did as
freely remit to the province and the traders to it.`"^
footnote:[The following is Abbe Raynal`'s reflection
upon the state of Pennsylvania at this time:
"`Here it is that the mind rests with pleasure upon modern history,
and feels some kind of compensation for the disgust,
horror or melancholy which the whole of it,
but particularly the European settlements in America, inspires.`"]

The constitution and laws being fixed and established by the unanimous
suffrage of the people`'s representatives in an unbiased assembly;
in order to preserve the future assemblies equally free and uncorrupt;
it was ordained that elections should be annual, and the votes given by ballot;
that the voices of the electors might be given of free choice,
without the possibility of being detected,
in order to remove every opportunity of undue influence.
William Penn`'s next care was to establish magistrates
and tribunals in every county with proper officers,
etc. where the courts were held every two months for the executing of the laws,
the administration of justice, and preservation of property.
But in order to prevent the expense and vexation of lawsuits as much as possible,
which in other states, through the management of the practitioners,
are generally a gulf that swallows up the property they should defend,
and are a grievance instead of protection;
he ordained that three arbitrators should be appointed by every county
court to hear and end differences between their neighbours in an amicable,
impartial and inexpensive way.
And judging it more eligible to prevent crimes than to punish them,
his laws were directed to put a stop to them in their very sources, poverty and idleness:
It was enacted,
that every child of twelve years old should be obliged to learn some trade or profession,
what ever his condition might be.
No class of his people escaped the attention of his spirit of universal benevolence,
which incited him to patronize and assist them all,
and especially those who stood most in need of assistance.
He instituted a particular and distinct court in each county, called the orphan`'s court,
to meet twice a year,
for the purpose of inspecting and regulating the affairs of orphans and widows,
and affording them its patronage and protection.

Such institutions, evidently calculated for the happiness and prosperity of mankind,
quickly drew numbers of fresh adventurers from different parts
to participate in the advantages of this just and equal government,
so that its progress in cultivation and population was rapid, almost beyond example.
"`Pennsylvania,`" says Raynal, "`without either wars, or conquests, or struggles,
or any of those revolutions which attract the eyes of the vulgar,
soon became an object fit to excite the admiration of the whole universe.
Its neighbours, notwithstanding their savage state,
were softened by the sweetness of its manners; and distant nations,
notwithstanding their corruption, paid homage to its virtues.`"

Perhaps it may be thought I have digressed too far,
and am making a transition to a political history by dwelling too long on this subject:
The humane mind must delight to dwell with satisfaction on a subject
which is both honourable and beneficial to humanity;
nor is it foreign to my purpose to delineate examples
of virtue in public or private life;
in the latter it promotes the happiness of the individual,
but in the former that of the community at large; and it is to be regretted,
the state of mankind, even of the professors of christianity, is such,
that history in general presents us with too few such worthy public-spirited characters.

William Penn`'s legislation is generally admired,
while the religion which he professed is too generally treated with contempt;
and yet it appears to me,
that this despised religion chiefly contributed to the formation of the excellent legislator.
His natural and acquired abilities were very considerable,
his understanding clear and his judgment sound; yet in these qualifications,
it is not to be doubted, many politicians have equaled or surpassed him;
but having been induced, in pursuit of truth, and peace of mind,
to disregard the opinion of the world,
and attach himself to a body of people despised and ridiculed by it,
because he thought he found the essence of pure religion
in doctrine and practice maintained amongst them,
he gradually experienced his heart regulated,
and all the irregularity of the passions and affections,
which produce disorder and discord, subdued by the power of this inward principle,
which convinceth of evil; and being illuminated thereby to keep in view an higher object:
than the praise of men or worldly splendor,
I believe his principal aim was in all his actions
and proceedings to stand approved of his Maker,
and to act in all respects as in his sight.
In this refined state of mind, avarice, ambition, arrogance and wrath,
(those corrupt sources of human action) have no influence or dominion over the man;
but considering himself as the minister of God for good, his integrity,
justice and benevolence are only bounded by the extent of his power to do good;
and the superior advantages in the constitution of the government
of William Penn seem to result from this,
that whilst most others establish a religion conformable
to human prudence or to the maxims of their policy,
he made religion the rule and basis of his political regulations.

Furthermore,
from the analogy between several of the institutions of
his government and those of the discipline of his friends,
it appears that his religious profession influenced him in his legislative capacity;
their first concern being to take care of the poor, of widows and orphans,
to discourage vice, and immorality, to prohibit lawsuits amongst themselves,
and to discountenance their members in going to law unnecessarily with others,
to promote peace and prevent differences as far as in their power;
and if any arise amongst them relating to matters of property, they are not to go to law,
but refer the differences to arbitrators indifferently
chosen or appointed from amongst themselves.

The purity of his religion is further manifested herein,
that in the greatest honour of his public station he retained
the meekness and humility of the private Christian,
and that he looked upon his acquisition of this province chiefly
as a gift of Divine Providence placing him in a capacity to promote
the present and future happiness of many people,
and that he directed his power to these beneficial purposes more than
to the advancement of himself or his family in wealth or grandeur,
as is apparent from the following lines addressed by him about this time to a
person who had made some invidious and unmerited reflections upon him:

[.embedded-content-document.letter]
--

[.salutation]
My Old Friend,

I could speak largely of God`'s dealings with me in getting this thing:
what an inward exercise of faith and patience it cost me in passing.
The travail was mine, as well as the debt and cost, through the envy of many,
both professors, false friends, and profane:
My God hath given it me in the face of the world, and it is to hold it in true judgment,
as a reward of my sufferings; and that is seen here,
whatever some despisers may fay or think: the place God hath given me,
and I never felt judgment for the power I kept, but trouble for what I parted with.
It is more than a worldly title or patent that hath clothed me in this place.
--Keep thy place: I am in mine,
and have served the God of the whole earth since I have been in it:
nor am I sitting down in a greatness that I have denied.
--I am day and night spending my life, my time, my money,
and am not six-pence enriched by this greatness: costs in getting, settling,
transportation, and maintenance, now in a public manner at my own charge duly considered;
to say nothing of my hazard, and the distance I am at from a considerable estate, and,
which is more, my dear wife and poor children.

Well! --the Lord is a God of righteous judgment.
Had I sought greatness I had stayed at home, where the difference between what I am here,
and was offered and could have been there, in power and wealth,
is as wide as the places are: No, I came for the Lord`'s sake,
and therefore have I stood to this day, well and diligent and successful,
blessed be his power.--Nor shall I trouble myself
to tell thee what I am to the people of this place,
in travails, watchings, spendings, and my servants every way, freely,
(not like a selfish man) I have many witnesses.
To conclude, it is now in friends hands; through my travail, faith and patience it came.
If friends here keep to God, and in the justice, mercy, equity and fear of the Lord,
their enemies will be their footstool; if not,
their heirs and my heirs too will lose all, and desolation will follow;^
footnote:[This remarkable prediction hath been fully verified.]
but blessed be the Lord we are well, and live in the dear love of God,
and the fellowship of his tender heavenly spirit; and our faith is,
for ourselves and one another,
that the Lord will be with us a king and a counsellor forever.

[.signed-section-closing]
Thy ancient, though grieved friend,

[.signed-section-signature]
William Penn.

[.signed-section-context-close]
Chester, 5th of the 12th mo, 1682

--
