== Chapter XXIX.

[.chapter-synopsis]
* A temporary Meeting-house erected
* Philadelphia laid out and begun to be built
* Men`'s and Women`'s Meetings established
* Their care for the Poor
* George Fox`'s Epistle to Friends of Pennsylvania
* John Burnyeat`'s Epistle to the same
* Account and Character of John Thomas, Francis Whitewell, Thomas Langhorn and William Gibson
* William Penn returns to England

The first settlers of this province were particularly careful
to keep up their meetings in the houses of the inhabitants,
till they got a temporary meeting-house erected of boards,
near the banks of the Delaware, where their capital city was designed to be built;
and as they were nearly united in brotherly affection to each other,
their meetings were held and conducted to their mutual consolation and edification.
In their intervals they were assistant to each other
in building small houses for their present residence,
mostly by the side of the Delaware,
till their ability and leisure might enable them to build
more comfortable and substantial habitations.

This was the beginning of the city of Philadelphia city,
which for convenience of situation (between the navigable
rivers Delaware and Schuylkill) uniformity of design,
and the regularity of its plan,
remains a lasting monument of the abilities of the founder,
and his unremitted attention to the convenience, satisfaction and interest of the colony.
The very name seems to have been adopted from the generous view of reminding
the inhabitants of the satisfaction and advantage of cultivating amity,
and a mutual good understanding between themselves, which they continued long to cherish,
to a degree sufficient to obtain the honourable testimony
of sundry authors in their commendation.

Some little time after their establishing a women`'s meeting of worship,
William Penn and his friends,
from experience of the service and benefit thereof
in those parts from which they had removed,
determined to set about the establishment of men`'s and women`'s meetings,
after the model of those in England.
The first monthly meeting of this kind fixed in and about Philadelphia
(to which the meeting at Schackamaxon was now joined,
and Pinepoint to Newton) was held there the 9th day of the 11th month this year.
They agreed that the first third day in every month should be the day
for holding the monthly meeting in future for the city and county,
and that every third meeting should be the quarterly meeting for the same.

They proceeded next to the consideration of a suitable place to build a meeting-house,
and the plan upon which it should be built;
the expense whereof it was agreed should be defrayed by friends of the city:
And whereas it was not improbable but some individuals
might be reduced to want through sickness,
the loss their of their parents or relations,
or the expenses attendant on so distant a removal and new settlement.
Their next care was to provide for the present supply of the exigencies of such,
if such should be found, at the expense of the monthly meeting.

This year George Fox,
whose care was anxiously exercised over his friends for their good
in every quarter of the world where they had fixed their residence,
wrote an epistle to friends in this province and the adjacent provinces,
advising them to liberality, justice,
and open honesty in all affairs of commerce which they might be engaged in.
Not to let avarice tempt them to take advantage of the circumstances of the times,
or the necessity of those with whom they dealt,
by enhancing their gain in exorbitant profits when provisions were scarce,
but rather serve their neighbours by selling on moderate terms.
On the other hand,
when the prices were too low to give a profit equal
to the necessary occasions of the proprietors,
that they should purchase at an advanced rate, letting their moderation appear,
and joining charity with justice;
and having an eye more to the public good than private interest,
might be the means to procure themselves the divine blessing upon their endeavours,
and be of a good report among their neighbours.
That as justice and open fair dealing procured them reputation,
and caused them an increase of trade, when riches thereby increased,
to beware of setting their hearts upon them, lest they should lose the image of God,
wherein the dominion over the creatures is retained.
He cautions them against extending in trade beyond their capitals and abilities to manage,
with reputation and justice to all men.
To circumscribe themselves within such limits,
as that they might be punctual to all their engagements,
and pay every one his due in due time.
He further cautions them not to let out their desires after
extensive possessions and greatness in the world,
lest they should be absorbed in the encumbrance thereof;
like the fool who had gotten much, and his barns being too little, would build bigger,
and then his heart should be at rest, but did not live to see the end of his hope,
and was soon deprived of all his possessions.

And as friends were, several of them, advanced,
and like to be advanced into places of trust in government,
and into the office of magistrates, he exhorts them earnestly to the practice of justice,
righteousness, fidelity and mercy in the discharge of their trust,
quoting abundance of exhortations from scripture,
descriptive of the various duties of magistrates,
and recommending them to their perusal and observation.

At the same time John Burnyeat wrote also to these provinces,
by desire of the yearly meeting of London,
giving them a satisfactory account of the state of said meeting,
and of their receiving epistles from friends in several foreign parts,
desiring them also, on behalf of the meeting,
to write to the said meeting an account of their state,
the prosperity of religion amongst them,
and the circumstances of the affairs of the society in their several provinces,
from their respective yearly or half-year`'s meetings, the latter end of the year,
to be transmitted to the ensuing yearly meeting in London,
which desire was complied with,
and an annual correspondence between these colonies and
the yearly meeting hath been continued thence forward,
and is continued still.

In this year died John Thomas of Gwynedd in Pennsylvania,
who had removed thither with several others of his countrymen,
from Larthguin in Merionethshire, whose character Hugh Roberts, his friend,
acquaintance and country man, hath drawn, to the following purport:
He was a man distinguished above the generality of his neighbours in his native
country for the solidity of his understanding and excellency of his natural parts.
In the year 1672 he was convinced of the principles of the people called Quakers,
and this being a time of hot persecution,
proved the sincerity of his motives for joining them in society;
for immediately upon his first convincement he had
his share of the sufferings to which the people,
whose profession he had adopted were exposed.
The two first meetings he was at he was informed against and fined,
and for these two fines,
which could not legally exceed 15s. the informers took from him two oxen and an horse,
and returned nothing back.
But he seemed to feel less for his own sufferings than for those of his poor friends,
insomuch that he hazarded the loss of his own estate to save them and theirs;
for the principal informer, a subtle man, and intent upon his prey,
perceiving a reluctance in the high and petty constables to execute
the warrants to the injury or ruin of their peaceable neighbours,
had formed a project to get himself appointed high constable,
in order to make his gains sure,
and expedite the impoverishing or ruining of friends in their estates;
and most of the magistrates of this age being too
propense to give encouragement to the vilest characters,
and invest them with power to do mischief to dissenters,
which virtuous persons would not, gave this man hopes of success in his application.
John Thomas, hearing of his design,
and foreseeing the great loss and distress likely to accrue to friends thereby,
applied himself to one of the more moderate justices,
and requested he might be accepted for that office, which was granted.
The informer upon this continued his information against friends,
and procured warrant after warrant for distraints,
which he brought to the high constable to execute, but he being principled against it,
told the informer he was responsible,
and kept the warrants by him till they had got nine,
expecting at the same time to be prosecuted by the informer,
to his great loss or ruin in his outward circumstances; but Divine Providence,
who directs the actions of men to his own wise purposes,
rescued him from the impending suffering,
for now the king`'s declaration for liberty of conscience
put a stop to the power and office those informers.

Being faithful, after some time he received a gift in the ministry,
in the exercise whereof he became very serviceable
amongst his friends in his native country,
by whom he was greatly respected and beloved during his residence amongst them.
At what time he removed to America doth not appear,
but it is most probable in the emigration of last year,
and that he did not long survive his removal.
His sickness was tedious,
but the weakness of his body did not diminish the strength of his love to pure religion,
or to the prosperity of his friends and family therein,
to whom he imparted many lively exhortations, during his indisposition,
to religious care of their conduct in fidelity to God and man.
A little before his departure he said to some friends present, "`Friends,
wait upon the Lord, for he is near;
and then expressed his resignation in this ejaculation: "`Blessed be thy name,
Lord God everlasting, thy will be done in earth as it is done,
in heaven.`" In this resigned temper he calmly took his leave of his friends present,
giving his hand to them one by one,
and in an heavenly frame of mind departed this life the 3rd day of the 3rd month, 1683.

In the beginning of the next year Francis Whitewell departed this life,
who besides his services in the government, being one or the proprietor`'s council,
was also very serviceable in a religious capacity,
being an approved minister amongst his brethren,
and a useful member of society in other respects.
William Darvel was chosen to supply his place as counsellor for Kent County.

Bucks County began now to increase in settlements, and to extend back into the country,
the earlier settlers having generally chosen to fix
their residence along the side of the Delaware,
both for the convenience of the river, and the neighbourhood of friends in West Jersey.
They were already settled about as far back as Middletown,
at which place a monthly meeting had been lately established.
The first of that kind there was held at the house of Nicholas Waln,
the 1st day of the 11th month last year;
and several friends from Europe continuing to remove to this province,
and settle in these parts, this neighbourhood soon became well improved.
Amongst the rest Thomas Langhorn from Westmoreland,
with several other friends from that county, landing in this colony,
retired up hither to settle,
and proved a valuable acquisition to this part of the province,
being men inured to industry, and accustomed to agriculture:
And some of them being men experienced in the work
of religion and the discipline of the church,
were well qualified for serviceable members of religious society,
especially Thomas Langhorn,
a man high in the esteem of his friends in his native country,
for his religious labours and services amongst them,
to which they bore ample testimony in the certificate
they gave him upon his removal to America,
from which it appears,
that the motive to his change of residence was of a more refined
nature than a desire to move in a conspicuous sphere of life,
or to acquire property, "`for,`" they say, "`God hath made him an instrument in his hand,
for the help and comfort of many, and for the service of truth in the church of Christ.
An elder that hath ruled well, and is worthy of honour,
who in his own country hath a large share,
that he need not covet the enlargement thereof elsewhere; and for outward possessions,
God hath given that plenty,
and dominion over them in the divine life wherein the blessing is obtained,
to true content,
so that the glory or riches of this world he hath no occasion
to covet after.`" It was a religious concern of mind,
and an inward persuasion of its being now his proper place to settle in,
that induced him to remove with his family hither,
as the place assigned for his future ministerial labour,
to promote amongst the new settlers (besides a spirit of industry in cultivating
their plantations) an inward exercise in the cultivation of religious dispositions,
by the help of that measure of grace of which they were respectively partakers,
which produceth a life and conversation adorned with
the uniform practice of piety and moral virtue.
He did not survive his arrival very long.
Having purchased a plantation, and made some improvement on it,
in a few years after he was removed from works to rewards,
yet lived long enough amongst them to make his loss sensibly felt,
being here also greatly beloved and esteemed by his friends and neighbours.

And now William Penn having spent about two years in his province of Pennsylvania,
and having settled this infant colony in a thriving prosperous condition,
returned to England some months before the death of King Charles the second,
the period at which I dropped the history of this people in England,
and which I now resume.

1684, William Gibson of London, an eminent minister, and member of this society,
finished an useful and profitable life in the course of this year,
in whose conversion there was something peculiarly remarkable.
He was born at Caton in Lancashire about the year 1629,
and during the civil wars enlisted as a soldier.
Being in garrison at Carlisle,
and hearing that a Quaker preacher had appointed a meeting in that city, he,
in concert with three of his comrades, made an agreement to go to the meeting,
with a design to insult and abuse the preacher;
but William Gibson coming thither before his confederates, and the friend,
who was Thomas Holmes, being in the course of his ministry,
it was attended with such demonstration of power,
as almost immediately wrought an effectual change in William`'s disposition,
for he was so affected therewith, that instead of executing his intended purpose,
he stepped up near to the friend to protect him from insult or abuse,
if offered by any other.
From that time he frequented the meetings of this society,
and soon after quitted his military engagements,
and employed himself in the occupation of a shoe maker; waiting upon God in silence,
under the refining operation of his saving grace for about the space of three years:
He afterwards received a dispensation of the gospel to preach to others.
In the year 1662 he married, and settled in the precincts of Sankey meeting,
near Warrington.
He was a very serviceable man in that country while resident there,
his doctrine being effectual to the convincement of some,
and to the confirmation of many others in the truth,
which he recommended in the authority of the gospel;
so that when he removed from thence he left a good report
and impressions of affectionate respect to his memory.

It fell to his lot with his brethren to suffer persecution for his testimony,
in divers imprisonments, in personal abuses,
and in loss of substance by various distraints.
In the year 1660, at a meeting at Hinton in Herefordshire,
many rude people and soldiers rushing in, pulled out those that were met,
and meeting William Gibson in the street, just come to town on horse back,
thronged about him.
He told them that be came in love to their souls,
and as he rode along exhorted them to repentance,
when a rude fellow beat him and his horse unmercifully,
after which they dragged him about in the dirt,
and kept him with the rest under a guard all night,
and next day sent two men to conduct them to Justice Blagny,
charging them with holding an unlawful assembly, and breaking the king`'s peace:
But the justice being of a different disposition
from the generality of those of that age,
judicious, reasonable and dispassionate, remarked,
That it was not probable they could be dangerous persons or peace breakers, who,
being twenty-three in number, were brought to him with only two men to guard them,
and so civilly dismissed them.

In the 4th month, 1661, being on the road near Stanton in Shropshire,
he was taken by a party of soldiers, and with twenty-three of his friends,
whom they had taken at several places, sent to prison,
whence in a short time they were escorted eight miles to the assizes,
and there discharged, all but William Gibson, whom the judge re-committed,
and he remained in prison a considerable time,
where he was treated with great cruelty by the keeper,
who would not permit his food to be taken to him,
but he was obliged to draw it up by a rope.
The keeper also threw him down a pair of stone stairs,
whereby his body was greatly bruised,
and beat him to that degree that he was sick near six months.

Afterwards he travelled southward on a religious visit to
his friends and others in the work of the ministry,
and was again imprisoned at Maidstone in Kent, where he was long confined.
After he was released he went to London and settled there,
removing his wife and family to that city, where his service was conspicuous,
in a fervent zeal against hypocrisy, formality and libertinism,
but in a strain of pathetic encouragement to the virtuous and religious mind,
being instructed by the spirit of wisdom and a sound
understanding to divide the word aright.
His circumspect conversation was a seal to his ministry, and the example he set,
a confirmation to the doctrine which he taught.

He employed a part of his time in his imprisonments in writing
epistles to his friends for their edification in righteousness,
when he could not edify them by his ministry, as well as occasionally at other times;
and was engaged in some controversies, particularly on the subject of tithes,
in a treatise, entitled, Tithes ended in Christ;
for his testimony against which he frequently suffered the loss of property.
He wrote several other treatises serviceable at the time.

In the fore-part of the year 1684, notwithstanding he was in a declining state of health,
feeling an affectionate draft and engagement of mind
to pay a religious visit to his native country,
Lancashire, he travelled thither, and having performed this service, he was,
in his return, seized with an ague and fever at Coventry,
yet he reached his own habitation in London,
and his indisposition continued upon him about three months,
and terminated his life in this world.
On his sick bed he exhorted friends who came to see
him to "`faithfulness and confidence in the Lord,
and to the love of the brethren;`" and testified against "`that spirit which leads
out of the unity into a selfish separation.`" He left two sons and a daughter,
for whose well-doing he discovered an anxious concern,
by the frequent admonitions and important councils
he inculcated upon them in the time of his sickness,
like Abraham,
commanding his children and household after him to keep the way of the Lord.
He died the 20th of the 9th month, 1684, at the age of fifty-five years,
and his funeral was attended by many hundreds of friends and others,
from their respect to his memory,
to the burial ground be longing to the society in Bunhill Fields.
