== Chapter II.

The Complaint of Friends against the Informers.--- They move for Commissioners
to be appointed to examine the Truth of their Allegations,--Which is granted.
--The Informers endeavour to get George Whitehead and others imprisoned.--The
Commissioners draw up their Report.--To which George Whitehead
objects,--And gets it amended.--Informers discouraged.

After the people called Quakers were released from imprisonment,
they were still exposed to the ravages of the unprincipled informers.
The king having condescended to admit and petition them sundry times to his presence,
and to attend patiently to the relation of their grievances;
and having complied with their petition to release their imprisoned friends,
they were encouraged to present the following complaint and petition
against the informers and their iniquitous practices.

To King James the Second.

The Complaint and Petition of his peaceable and suffering
Subjects called Quakers in and about the City of London,

Humbly presenting,

That only for religious concerns,
a great number of them continue fore oppressed in their estates
on numerous convictions made against them in their absence,
often on false depositions sworn by concealed informers, divers of them confident women,
who swear for a part of the fines and seizures to maintain themselves and husbands,
some of them being prisoners for debt through their own extravagance:
And by warrants frequently issued out by Thomas Jenner, recorder of London,
to break open and enter houses, to seize for the king,
(as is pretended) which is done with rigour and great spoil,
and without compassion to widows, fatherless,
or poor families who are sustained by their daily industry,
not leaving them a bed to lie on, etc.
The fines only upon his warrants amounting to many hundred pounds,
besides what has "`been suffered by others.
And that when appeal is made from the said recorder, as the person convicting,
(as the law directs) he being judge also upon the trial, altering the record,
and urging juries to find against the appellant, divers appeals have proved ineffectual,
and to their great damage, considering their charges and treble costs, etc.
And that also upon old convictions under king Charles the second,
then remaining unexecuted,
he now by new warrants entitles the now king James the second to these grievances;
besides the great numbers imprisoned and crowded
in jail by him and others for the same cause,
to the greatly impairing their health and loss of some lives;
witness Newgate at this present.

Wherefore the said subjects humbly entreat the King,
in his princely compassion and wisdom,
to put a speedy stop to these destructive proceedings.

Signed in behalf of the rest of the said sufferers,

William Crouch, Samuel Boston, James Goodwin, Timothy Emerson, Thomas Lacy,
John Skelton.`"

This petition was followed up by a request to the king to appoint
commissioners to examine into the truth of the allegations,
by giving the petitioners an opportunity of proving them to the informers faces.
Their request was granted,
and a commission was issued to Richard Graham and Philip Burton, Esqrs.
who sent their summons to the informers,
sufferers and witnesses to appear before them at Clifford`'s Inn the 4th of June,
(so called) 1686.

On the day appointed the complainants and their witnesses appeared,
and the informers also.
As the people called Quakers had selected fifty-four cases; and the friends,
whose cases had been so selected, being summoned to appear with their witnesses;
when they came to Clifford`'s Inn, the informers being without door,
at seeing so numerous a company appearing against them,
expressed their malice in this ribaldry, suitable to their vulgar manners:
Here come all the Devils in Hell; and observing George Whitehead,
who had been instrumental to bring them to this disgraceful investigation,
they cried out, And there comes the old Devil of all.

The first charge advanced against the informers was that they had sworn falsely in fact,
which was clearly proved to their shame and confusion in no less than thirty-four cases;
in divers of which they had given their information on oath against
friends for being at meetings which they were not at;
for holding meetings at certain places where there were none;
swearing upon trust from one another`'s information on mere presumption.
Several women informers took as much latitude in swearing as the men,
and were equally unrestrained by conscience, law, or matter of fact as they.
Their frequent perjuries being established by substantial evidence,
to the full satisfaction of the commissioners and others,
friends next proceeded to lay before them sundry cases,
wherein the doors of houses and shops were broken
open with violence by constables and informers,
to make distraints severe and exorbitant,
by which house hold and shop goods were carried away by cart loads.
So many flagrant instances of perjury, devastation and spoil plainly appeared upon proof,
that the commissioners grew weary of hearing them,
and adjourned the further proceeding for ten days,
when they had got through scarce one fourth of the
cases prepared to be laid before them.

At the second meeting of the commissioners,
the informers fee`'d a lawyer to plead for them and manage their cause;
but the instances of their perjury and oppression,
transgressing the bounds and severity of the conventicle act, severe as it was,
were so numerous, and so well supported by evidence, that he was quickly silenced.
At this second meeting,
although they had not examined half the cases prepared for their cognizance,
the commissioners thought the allegation of the petition fully proved,
and that they had sufficient grounds to make their report to the king.

It seems proper to remark here the contrivance of the informers
to prevent some of the most active promoters of this inquiry from
appearing against them at the second meeting of the commissioners.
Having procured a warrant George whitehead, John Daw, William Ingram and John Vaughton,
bearing date the 12th of June 1686, they were apprehended the 13th,
(being the day before that appointed for the second
meeting aforesaid) and taken to the Lord Mayor`'s,
where they were kept several hours waiting for his coming from his worship,
and afterwards detained several more,
until the informers should come in to give evidence against them, but none appearing,
about ten o`'clock at night the mayor required them to be bound
by recognizance to appear at the next sessions for the peace,
and in the mean time to be of good behaviour.
With this requisition they were not willing to comply, as implying misbehaviour,
which was not proved against any of them.
Upon their refusal, the mayor called them a company of coxcombs;
and ordered mittimus to be drawn to send them to prison;
but on further consideration and consultation,
took their words to appear at next sessions, and dismissed them for that time,
whereby they were at liberty to attend the commissioners at their second meeting.
And when they appeared at the sessions, no evidence appearing against: them,
they were discharged by proclamation.

The commissioners having drawn up their report, George Whitehead got a view of it,
and objected to it, as very deficient and improper,
being rather a proposal for limiting prosecutions to the less ruinous penal laws,
than a plain state of matter of fact, according to the evidence before them,
of the various perjuries, and illegal and injurious acts of the informers,
one of the commissioners informed him,
that they found themselves engaged in a critical business,
having received a message from a great person or persons in the church,
soliciting them to do or report nothing that might invalidate the power of the informers,
as they were of great service to the church.
George Whitehead notwithstanding pleaded for justice to be done,
in regard to matters of fact, in their report to the king,
and prevailed upon them to amend it, and frame it more to the purpose.

The king, in cabinet the 11th of 5th month 1686,
referred the report and case of the petitioners to the Lord Chancellor,
in order to correct the irregular proceedings of some justices and the informers.
Besides which he signified his pleasure to the subordinate magistrates and justices,
that they should put a stop to the predations of these men.^
footnote:[The following letter from the Earl of Sunderland to the Earl of Huntington,
I suppose, must have been written upon this occasion.
{footnote-paragraph-split}
"` Whitehall, Dec.
7,
1686
{footnote-paragraph-split}
"`My Lord,
{footnote-paragraph-split}
"`The
king being informed that one John Smith,
a common informer,
doth very vexatiously prosecute the Quakers in the county of Leicester,
and in the town and county of Nottingham;
and his majesty being pleased to extend his favour
to
{footnote-paragraph-split}
those of that persuasion,
his majesty would have your grace direct the justices of
peace to give no sort of countenance to the said John Smith,
and his prosecution against the Quakers.
{footnote-paragraph-split}
"`Your grace`'s most faithful and humble servant,
{footnote-paragraph-split}
"`Sunderland.
P.`"
{footnote-paragraph-split}
"`To the Right Hon.
the Earl of Huntington, one of his majesty`'s most honourable privy council,
chief recorder of Leicester, custos rotulorum of the county of Leicester:`''`]
Instead therefore of being encouraged and protected in their oppressive persecutions,
they were now discountenanced by the justices,
and by the quarter sessions of London and Middlesex.
And when it was now discovered that the protection and favour
of the court was withdrawn from these vile persons,
several of them being prosecuted by other dissenters,
such a scene of iniquity and injustice was laid open,
as caused several of them to fly the country; and the rest, when their trade was gone,
were mostly reduced to beggary;
a blast remarkably attending their dishonest gains and infamy blasting their reputation.^
footnote:[George Whitehead informs us that some time
after the trade of informing was put a stop to,
George Hilton, who had been a very vexatious informer to several friends in London,
and to himself amongst the rest, came to his house, and complained,
that he could get a place of service with a great person; but he wanted clothes,
or money to buy some; and that he gave him some money, thus rendering good for evil.]

These informers had gradually risen to that height of insolence and audacity,
as well as rapine,
by the joint encouragement of the court and church
(so called) i. e. the high church ecclesiastics,
as hath been already remarked; but now when their secular support was taken away,
the ecclesiastics, loath as they were to lose their service,
were not able to support them singly, with the weight of the court against them;
so they were obliged, though reluctantly to give them up.
