== Chapter I.

[.chapter-synopsis]
* The Duke of York ascends the Throne
* Fictitious Address of the People called Quakers
* Remark thereupon
* First Application of the People called Quakers to King James
* Their suffering Case
* Friends of London draw up a more copious State of their Case to lay before Parliament
* The Duke of Monmouth lands in the West Defeated, taken and executed
* Rigorous Severity against his Adherents
* The King addreseth the Parliament in a magisterial Strain
* Which excepts against his dispensing Power
* Friends of London renew their Solicitations in favour of those in Prison
* King`'s Order for their Release

Notwithstanding the opposition which, during the late reign,
had been made to the succession of the Duke of York,
and the dreadful apprehensions conceived by many Protestants of that event,
yet immediately after the decease of his brother he was proclaimed king,
without the least tumult or shadow of opposition.
On the first day of his reign he assembled a council at Whitehall,
in his speech to which he disclaimed arbitrary principles,
promised his protection to the Church of England and the liberties of the people.
His speech was printed and read with applause.
He received congratulatory addresses from most parts of the kingdom, many of them,
as usual, couched in servile terms of adulation: Amongst the rest a fictitious address,
remarked for its brevity, uncouthness and blunt familiarity of expression,
hath been by Eachard, and after him by Hume and others,
published to the world for the ad dress of the people
called Quakers to King James upon his accession,
conceived in the following terms:
"`We are come to testify our sorrow for the death of our good friend Charles,
and our joy for thy being made our governor.
We are told thou art not of the persuasion of the church of England no more than we,
wherefore we hope thou wilt grant us the same liberty thou allowest thyself.
Which doing we wish thee all manner of happiness.`"

It is allowed that the members of this society ranked adulation
and insincerity in the list vices not allowable to them to practise;
that they were not in the custom of paying complimentary addresses to any man;
but that when their sympathetic regard to the sufferings of their friends,
or the distressing feelings of their own, impelled them to apply for relief,
on which occasions chiefly they addressed their superiors, their addresses,
though expressed in their plain manner, were comprised in respectful terms;
void of flattery, but not indecent; unceremonious, but not uncivil.

Immediately on King James`'s accession I find no account
of their being in the number of the congratulatory addressers.
The first address they presented, as far as appears, was in a very different style,
on the like occasion with those which had influenced them
to address the successive rulers from their first rise.
King Charles at his death left near one thousand five hundred of them in prison,
on various severe prosecutions;
and notwithstanding we have seen petition upon petition presented to him for relief,
few of them were attended with beneficial effect; so that a people,
paying a strict regard to speaking truth from the heart,
could hardly term him their good friend.
But the grievous sufferings they had long endured with patience,
and were still subjected to, induced them, particularly on every change of government,
to apply to the new rulers, in hopes at last to excite them to commiserate their case,
and to yield them redress.

Accordingly, about a month after this king`'s accession to the throne, George Whitehead,
Gilbert Latey and Alexander Parker waited upon him with the following address,
and case of their friends:

[.embedded-content-document.address]
--

[.letter-heading]
To King James the Second.

[.signed-section-context-open]
The humble application of the people called Quakers.

Whereas it has pleased Almighty God (by whom kings
reign) to take hence the late king Charles the second,
and to preserve thee peaceably to succeed, we, thy subjects,
heartily desire that the giver of all good and perfect
gifts may please to endue thee with wisdom and mercy,
in the use of thy great power, to his glory, the king`'s honour and the kingdom`'s good.
And it being our sincere resolution,
according to our peaceable principles and conversation,
(by the assistance of Almighty God) to live peaceably and honestly,
as becomes true and faithful subjects, under the king`'s government,
and a conscientious people that truly fear and serve God,
we do humbly hope that the king`'s tenderness will appear,
and extend with his power to express the same,
recommending to his princely clemency the case of our present
suffering friends hereunto annexed.

[.letter-heading]
To the King.

[.signed-section-context-open]
The distressed case and request of the suffering people commonly called Quakers,
humbly presented.

[.salutation]
Showing,

That according to accounts lately given, above fourteen hundred of the said people,
both men and women, are continued prisoners in England and Wales,
only for tender conscience toward Almighty God that made them.
Many under sentence of premunire, and many near it,
not for refusing the duty or substance of allegiance itself,
but only because they dare not swear.
Others under fines on the act of banishment.
Many on writs of excommunication.
Besides some hundreds have died prisoners,
many by means of this long imprisonment since the year 1680,
(as `'tis judged) thereby making widows and fatherless,
and leaving poor innocent families desolate, in distress and sorrow.
These two hard winters,
their confinement tending also to the destruction of many in cold holes and jails,
their health being greatly impaired thereby.
Besides the violence and woeful spoil made by merciless informers on the conventicle act,
upon many convicted, unsummoned and unheard in their own defence,
both in city and country; as also on _Qui tam_ writs and other processes for 20£. a month,
and two-thirds of estates seized for the king; all tending to the ruin of trade,
husbandry and industrious families.
To some not a bed left, to others no cattle to till their ground or give them milk,
nor corn for bread or feed, nor tools to work withal;
and all these and other severities done under pretence of serving the king and the church,
thereby to force us to violate our consciences, and consequently to destroy our souls,
which we are very tender of, as we are of our peace with God and our own consciences,
though accounted as sheep for the slaughter.
And notwithstanding all these long sustained extremities,
we the said people do solemnly profess and declare, in the sight of the heart-searcher,
that we have nothing but good will and true affection to the king,
praying for his safety and the kingdom`'s peace.
We have never been found in any seditious or treasonable designs,
as being wholly contrary to our christian principles and holy profession.

And knowing that where the word of a king is, there is power, we in christian humility,
and for Christ`'s sake,
entreat that the king will please to find out some
expedient for our relief in these cases,
from prisons, spoil and ruin.

And we shall, as in christian duty bound, pray God for the king`'s welfare in this world,
and his eternal happiness in that which is to come.

[.signed-section-context-close]
London, the 2nd of the 1st month called March, 1684-5.

--

Soon after the friends of London drew up a more copious state of their case and sufferings,
addressed to the king and both houses of parliament,
wherein they recapitulate their grievous sufferings
in person and estate by no less than ten penal laws,
which for a long series of years had been rigorously
put in force against them by adverse magistrates,
frequently picking out of them, to gratify a causeless enmity,
that law to prosecute them by, which they apprehended the most oppressive,
clearly demonstrating the iniquity and multiplied hardships to which they were exposed,
(which need not be recited,
being such as have already been repeatedly recited in this work) and praying relief.^
footnote:[The statutes whereby this people suffered
imprisonment and spoil were the following,
viz.
{footnote-paragraph-split}
The 1st Eliz.
ch. 2, for twelve pence a Sunday (so called)
{footnote-paragraph-split}
The 5th Eliz.
ch. 23, _de excommunicato capiendo._
{footnote-paragraph-split}
The 23d Eliz.
ch. 1, for 20£. a month.
{footnote-paragraph-split}
The 29th Eliz.
ch. 6, for continuation.
{footnote-paragraph-split}
The 35th Eliz.
ch. 1, for abjuring the realm on pain of death.
{footnote-paragraph-split}
The 3d James I. ch.
4, Premunire.
{footnote-paragraph-split}
The 13th and 14th King Charles II. against Quakers.
Transportation.
{footnote-paragraph-split}
The 17th Charles II. ch.
2, against non-conformists.
{footnote-paragraph-split}
The 22d Charles II. ch.
1, against seditious conventicles.
{footnote-paragraph-split}
The 27th Henry VIII.
ch. 20, for the recovery of tithes.]

How far the parliament might be impressed by this affecting
state of the sufferings of this oppressed people,
with sentiments of compassion and equity, they had not the opportunity of discovering,
nor, I imagine,
had even the members of the society an opportunity of presenting it to them;
for soon after their meeting their proceedings were interrupted by the news of
the Duke of Monmouth`'s arrival on the western coast with three ships from Holland:
The parliament, upon this intelligence,
passed a vote that they would adhere to the king with their lives and fortunes,
passed a bill of attainder against the duke,
granted the king 400,000£. for suppressing the rebellion,
and then the parliament adjourned.

This adjournment was in the fourth month,
(June) and the parliament did not meet again till November.
The summer was spent in quelling the rebellion,
and taking vengeance rather than executing justice upon the unhappy insurgents,
and with them upon many who had been guilty of no treason,
and more who could not be legally convicted of any.
The Duke of Argyle landed in Scotland,
and endeavoured to raise a rebellion there something sooner
than the Duke of Monmouth`'s landing in the west.
Both of them were defeated, taken and soon executed;
and great numbers of the followers of the latter
were executed without the form of a trial,
by the Earl of Feversham, and with savage wantonness by Colonel Kirk.
Many others were tried, but very unfairly, by the forms of law, before a judge,
who wantoned in cruelty,
and triumphed in the misery of the unhappy victims who fell under his hands;
and the king, by advancing Jeffries immediately after to the office of chancellor,
participated in his infamy, and lost the affection of his subjects to a great degree,
particularly of those in the western counties.

Upon the second meeting of the parliament, the king,
elated with the "`defeat of the insurgents,
apprehended his power so firmly established as to bear down all opposition,
and seemed determined to brook none.
His speech the and demands were delivered in a strain
which showed them that he was determined to be master.
He demanded a supply to maintain an additional number of forces.
He informed them he had employed several catholic officers, and that he had,
in their favour, dispensed with the law requiring the test to be taken,
and signified his resolution neither to expose them to disgrace,
nor himself to the want of their assistance, in case of another rebellion.

The commons, having been elected under the influence of the court,
were awed into compliance with his demand in part,
and voted 700,000£. toward the augmentation of the army;
but both lords and commons excepting against the king`'s dispensing power,
as they had formerly to his brother`'s,
he was so piqued that an immediate prorogation followed, whereby, I apprehend,
the people called Quakers were prevented of their
intention of laying their case before the parliament;
at least the parliament had no time to attend thereto.
But being earnestly desirous to obtain the liberty of their imprisoned friends,
the friends of London renewed their solicitations to the king for their liberation,
and at length obtained the following warrant to Sir Robert Sawyer, attorney-general:

[.embedded-content-document.legal]
--

[.letter-heading]
James R.

Whereas we are given to understand that several of our subjects, commonly called Quakers,
in the schedules hereunto annexed, are either convicted, or upon process,
in order to their conviction of premunire, for not swearing,
or indicted or presented for not coming to church, or convicted for the same,
and several of them have been returned into our Exchequer,
and in charge for twenty pounds _per mensem,_
according to the statutes in that case provided,
and some of them lie in prison upon writs _de excommunicatio capiendo,_
and other processes, for the causes aforesaid;
and we being willing that our said subjects,
and other our subjects commonly called Quakers, who are or have been prosecuted,
indicted, convicted, or imprisoned for any of the causes aforesaid,
should receive the full benefit of our general pardon,
which we have been pleased to grant to our loving subjects by our royal proclamation,
with all possible ease to them, our will and pleasure is;, and we do hereby authorize,
will and require you to cause such of our subjects, commonly called Quakers,
who are in prison for any of the causes aforesaid,
to be forthwith discharged out of prison, and forthwith to stop and discharge,
or cause to be discharged, by giving your consent on our behalf, all fines, forfeitures,
or sums of money, charged upon any of our subjects commonly called Quakers,
for not coming to church, or set upon them upon any process for the same;
as also all processes, indictments, presentments and convictions,
for any of the said causes, by entering _noli prosequi,_ or otherwise,
as you shall judge necessary for rendering that our pardon
most effectual and beneficial for our said subjects;
and for your so doing this shall be your warrant.

Given at our Court at Whitehall the 15th Day of March, 1685-6,
in the second year of our reign.

[.signed-section-closing]
By his Majesty`'s Command,

[.signed-section-signature]
Sunderland, P.

[.signed-section-context-close]
To our trusty and well beloved our Attorney-general

--

Sir Robert being at this time at his country house in Hampshire,
about forty miles from London,
and friends of that city being earnest to expedite the release of their fellow-professors,
requested George Whitehead and John Edge, accompanied by Rowland Vaughan, attorney,
to undertake a journey thither, which they did accordingly,
and were received and entertained by the attorney-general with great civility,
'`till liberates could be made out by the attorney,
under the attorney-general`'s directions for the prisoners in the city,
which took up a good part of the day; by means whereof, after their return,
their friends in the sundry prisons in the city obtained
their liberty within the description of the warrant.
Soon after the attorney-general returned to London,
and then the said friends of the city exerted themselves
to procure the like liberates with all possible expedition,
whereby the discharge of the rest of the prisoners in the different parts of the nation,
under the circumstances comprised in the king`'s warrant, was obtained.
