== Chapter IV.

[.chapter-synopsis]
* Informers and their Abettors in danger, through an Inquiry into their Application of the Fines they had recovered
* Revocation of the Edict of Nantz
* Declaration for Liberty of Conscience
* For which the Dissenters present Addresses of Thanks to the King
* Address of the People called Quakers of the City of London
* Second Address from the yearly Meeting on behalf of the Body at large
* Both the King and the Dissenters desire the Repeal of the Penal Laws, but with different Views
* Application to the Prince of Orange in favour of the Repeal of the Penal Laws and Test
* He is willing the former should be repealed, but not the latter
* Second Declaration for Liberty of Conscience
* Ordered to be distributed by the Bishops, to be read in all Churches and Chapels
* Seven of them show the Reasons why they cannot comply
* For which they are imprisoned in the Tower
* Robert Barclay hath a Conference with the Bishops in the Tower
* Persecution subsides
* The People called Quakers petition the King for relief in respect to their Sufferings for Tithes.

The people called Quakers and other dissenters being thus
providentially rescued from the tyranny of persecuting justices,
high-churchmen and informers,
these persecutors were now made to feel a little of the uneasiness they had,
in the wantonness of power,
abundantly occasioned to others without pity and without mercy.
The king,
probably from the aforesaid discovery of the practices of the informers and their confederates,
appointed commissioners to inquire what money had been raised,
or what goods had been seized by distress on dissenters on prosecutions for recusancy,
and not brought to account in the Exchequer,
and what money or goods had been received for any
matters relating to religion since September 1677,
in any of the counties fro which they were named.
They were to return the names of all persons, who had seized goods or received money.
This struck a terror into the whole tribe of informers,
the justices and others connected with them,
who were ill provided to make up their accounts, being generally poor or extravagant,
they are said to have mostly shared the booty amongst themselves,
without either giving to the king or to the poor the share appointed by law;
so that if prosecuted they were threatened with ruin from this inquiry;
but it doth not appear the protestant dissenters were forward to appear against them,
it being reported that assurances were given by leading persons, both clergy and laity,
that if they would not appear no such methods should be pursued in future.

The dread and aversion which the people of England entertained of the Romish religion
received additional strength and influence by an occurrence which happened this year.
Louis the Fourteenth revoked the edict of Nantz,
which had been published by Henry the Fourth, for the security of the protestants,
and which had been declared irrevocable.
They were immediately distressed by all the rigours of persecution,
whereby multitudes of them were driven to seek in foreign nations
an asylum from the severities inflicted upon them at home.
Near fifty thousand took refuge in England,
and brought such dismal accounts of the cruel treatment they had undergone,
as produced in all the protestants the utmost abhorrence of the sanguinary,
cruel and perfidious spirit of popery.
The king`'s friendly reception and protection of the fugitives,
and his affecting highly to blame the king of France,
were ineffectual to cure his subjects of their jealousy of him,
or their antipathy to his religion.

The forepart of the succeeding year king James published
a declaration for liberty of conscience to all his subjects,
ordering that hence forth the execution of all penal
laws concerning ecclesiastical affairs,
for not coming to church, for not receiving the sacraments,
or for any other non-conformity with the established religion,
or for performing religious worship in any other way, should be suspended.

Although this liberty was only granted by the king himself,
and the parliament when assembled might call his power in question,
as they had done his brother`'s in the like case, yet the dissenters of every class,
wearied out with the length and severity of their sufferings
under the tyranny of the church (so called) being less attentive,
perhaps, at this time to any sinister view which might give rise to it,
or to the legality of it, than rejoicing at the state of ease they found themselves in,
presented addresses of thanks to the king for his said gracious declaration;
and the people called Quakers of the city of London,
seeing that those of other persuasions had gone up to court with such addresses,
that they might not seem less sensible of the relief which they,
who had suffered more severely than any others, received,
thought it expedient also to wait upon the king with the following address;

[.embedded-content-document.address]
--

[.letter-heading]
To King James II. over England, etc.

[.blurb]
=== The humble and thankful address of several of the king`'s subjects, commonly called Quakers, in and about the city of London, on behalf of themselves and those of their communion.

[.salutation]
May it please the King,

Though we are not the first in this way,
yet we hope we are not the least sensible of the great favours,
we are come to present the king our humble, open and hearty thanks for,
since no people have received greater benefits, as well by opening our prison-doors,
as by his late excellent and christian declaration for liberty of conscience,
none having more severely suffered,
nor stood more generally exposed to the malice of ill men upon the account of religion;
and though we entertain this act of mercy with all the acknowledgments
of a persecuted and grateful people,
yet we must needs say it doth the less surprise us,
since it is what some of us have known to have been the declared principle of the king,
as well long before as since he came to the throne of his ancestors.

And as we rejoice to see the day that a king of England should, from his royal seat,
so universally assert this glorious principle,
that conscience ought not to be constrained,
nor people forced for matters of mere religion (the want of which happy conduct in government
has been the desolation of countries and reproach of religion) so we do,
with humble and sincere hearts, render to God first, and the king next,
our sensible acknowledgments;
and because they cannot be better expressed than in a godly, peaceable and dutiful life,
it shall be our endeavour (with God`'s help) always to approve
ourselves the king`'s faithful and loving subjects;
and we hope that after this gracious step the king hath made towards the union
of his people and security of their common interest has had a due consideration,
there will be no room left for those fears and jealousies
that might render the king`'s reign uneasy,
or any of them unhappy.

That which remains, great prince, for us to do,
is to beseech Almighty God (by whom kings reign and princes decree justice)
to inspire thee more and more with his excellent wisdom and understanding,
to pursue this christian design of ease to all religious
dissenters with the most agreeable and lasting methods;
and we pray God to bless the king, his royal family and people with grace and peace,
and that after a long and prosperous reign here,
he may receive a better crown amongst the blessed.

Which is the prayer of, etc.

--

This address met with a favourable reception;
but being presented by friends of London only,
at the ensuing yearly meeting held in that city,
constituted of representatives from the several parts of the nation,
a second address was drawn up in the name and on behalf of the community at large,
deputing amongst others William Penn to deliver it,
who introduced the delivery with the following speech:

[.embedded-content-document]
--

[.salutation]
May it please the King,

It was the saying of our blessed Lord to the captious Jews in the case of tribute,
render to Caesar the things that are Caesar`'s,
and to God the things that are God`'s. As this distinction ought
to be observed by all men in the body at the conduct of their lives,
so the king has given us an illustrious example in his own person that excites us to it:
for while he was a subject, he gave Caesar his tribute, and now he is a Caesar,
he gives God his due, viz. the sovereignty over consciences.
It were a great shame, then,
for any Englishman (that professes christianity) not to give God his due.
By this grace he has relieved his distressed subjects from their cruel sufferings,
and raised to himself a new and lasting empire, by adding their affections to their duty:
and we pray God to continue the king in this noble resolution;
for he is now upon a principle that has good-nature, Christianity,
and the good of civil society on its side;
a security to him beyond the little arts of government.
I would not that any should think that we came hither
with design to fill the Gazette with our thanks;
but as our sufferings would have moved stones to compassion, so we should be harder,
if we were not moved to gratitude.
Now since the king`'s mercy and goodness have reached
to us throughout the kingdom of England,
and principality of Wales, our general assembly from all those parts,
met at London about our church affairs,
has appointed us to wait upon the king with our humble thanks, and me to deliver them;
which I do by this address, with all the affection and respect of a dutiful subject.

--

[.embedded-content-document.address]
--

[.old-style]
=== The Address.

[.letter-heading]
To King James the Second, over England, etc.

[.blurb]
=== The humble and grateful acknowledgment of his peaceable subjects called Quakers, in this kingdom.

[.blurb]
=== From their usual yearly meeting in London, the 19th day of the 3rd month, vulgarly called May, 1687.

We cannot but bless and praise the name of Almighty God,
who hath the hearts of princes in his hand,
that he hath inclined the king to hear the cries
of his suffering subjects for conscience sake:
And we rejoice, that instead of troubling him with complaints of our sufferings,
he hath given us so eminent an occasion to present him with our thanks:
And since it hath pleased the king, out of his great compassion,
thus to commiserate our afflicted condition,
which hath so particularly appeared by his gracious proclamation, and warrants last year,
whereby twelve hundred prisoners were released from their severe imprisonments,
and many others from spoil and ruin in their estates and properties;
and his princely speech in council, and christian declaration for liberty of conscience,
in which he doth not only express his aversion to all force upon conscience,
and grant all his dissenting subjects an ample liberty to worship God,
in the way they are persuaded is most agreeable to his will,
but gives them his kingly word the same shall continue during his reign;
we do (as our friends of this city have already done) render the king our humble,
christian, and thankful acknowledgements, not only in behalf of ourselves,
but with respect to our friends throughout England and Wales: And pray God,
with all our hearts, to bless and preserve thee, O king, and those under thee,
in so good a work:
And as we can assure the king it is well accepted
in the several counties from whence we came,
so we hope the good effects thereof, for the peace, trade, and prosperity of the kingdom,
will produce such a concurrence from the parliament,
as may secure it to our posterity in after-times: And while we live,
it shall be our endeavour (through God`'s grace) to demean ourselves, as,
in conscience to God, and duty to the king, we are obliged,

[.signed-section-signature]
His peaceable, loving and faithful subjects.

--

[.embedded-content-document]
--

[.old-style]
=== The Kings`'s Answer.

Gentlemen, I thank you heartily for your address: Some of you know (I am sure you do,
Mr. Penn) that it was always my principle, that conscience ought not to be forced;
and that all men ought to have the liberty of their conscience;
And what I have promised in my declaration, I will continue to perform as long as I live:
and I hope, before I die, to settle it so,
that after-ages shall have no reason to alter it.

--

Some have objected against our friends and other dissenters, for addressing king James,
upon the aforesaid declaration of indulgence,
as though they had thereby countenanced the king`'s dispensing with the laws in general:
Let such observe their imputation, as to the people called Quakers,
sufficiently guarded against in that part of their address, where they say,
"`We hope the good effects thereof, for the peace, trade and prosperity of the kingdom,
may produce such a concurrence from the parliament, as will secure it to our posterity.`"

Many of this people, being themselves men of sincerity and simplicity of heart,
might apprehend the king to be in earnest in his
professions in favour of liberty of conscience.

Yet from their experience in the former reign,
of the precarious duration of such indulgence,
without the sanction of an act of the whole legislature,
they looked upon the liberty granted them uncertain and insecure,
until it should be ratified by the two houses of parliament,
whose concurrence they esteemed requisite to give stability
and permanency to the privileges they now enjoyed;
accordingly they properly express their gratitude
to the king for what he had done in their favour,
and modestly hinted their sentiments of what they apprehended
yet wanting to be done to complete the favour.

But although the dissenters, as well as the king,
Although were desirous that the repeal of the penal
laws might receive a parliamentary sanction,
yet the ends they had respectively in view were such as laws to prevent a cordial coalition.
James`'s design became every day more and more clearly apparent,
to center entirely in the promoting and establishing of popery in the nation,
to which the dissenters were no less averse than the established church;
and notwithstanding the ease and even favours which they enjoyed,
under the present disposition of the king towards them, yet they began clearly to,
perceive all these flattering measures were ultimately designed in favour of the Romanists;
and therefore they placed but little confidence in the king`'s favours,
and cautiously abstained from lending their assistance to measures,
the design of which they did not inwardly approve.

Notwithstanding the king had prohibited the protestant
preachers to meddle with controverted points,
several of them continued their exertions in the protestant cause; the king,
provoked at this opposition, broke all measures with the church, so called;
he erected a new ecclesiastical commission, to enforce obedience to his mandates.
He sent an ambassador to Rome, to acknowledge his spiritual obedience to the Pope,
and reconcile his kingdoms to him.
A popish nuncio was sent to London, who made his public entry at Windsor,
with all the usual formalities.
He attempted to force papists into the Universities, and succeeded at Oxford.
By all these arbitrary acts he shocked the sentiments of his subjects,
confirmed their abhorrence of his measures, and precipitated his own downfall.

As the dissenters in general were well affected prince to the Prince of Orange,
and the nation regarded the princess as heir apparent to the crown,
the repeal the king next directed, that their sentiments procured upon the subject,
in hopes that if the prince should declare in their favour,
it might have a beneficial influence on the deliberations of a parliament.
The prince, naturally of a reserved temper, was not forward to intermeddle in the matter;
but at last, lest his silence might be imagined an acquiescence,
the pensionary Fagel was authorized to convey the sentiments of himself and the princess,
through the hands of Stuart, who had corresponded with him on the subject,
which were afterwards published to the nation, the purport of which was,
that they were willing to assent to the repeal of the penal laws,
as far as they laid any restraint on free liberty
of the conscientious exercise of religious worship,
which they were willing should be enjoyed in the fullest extent; but as for the test,
and those laws which debarred the papists from sitting in parliament,
or getting into places of trust and profit in government,
they could by no means agree to the repeal of these, as they were not like the others,
laws of punishment or persecution,
but merely a necessary security of the protestant religion.
When this was published it gave the protestants fresh spirits and encouragement;
but very much disgusted the king.

When these attempts failed, the king, determinately bent on carrying his point,
and mortifying the church of England, from whom the weight of opposition arose,
on the 27th of the 2nd month April 1688,
published a second declaration for liberty of conscience, fuller than the former,
exciting his subjects to accede to it,
and to choose such members of parliament as might
do their parts to finish what he had begun,
signifying his resolution to convene a parliament to meet in November next;
with an order of council annexed for reading his declaration in all churches and chapels,
and directions to the bishops to distribute the same
through all churches their dioceses to be read accordingly;
but the bishops, unwilling to be the instruments of undermining their own interests,
and those of their church,
mostly declined compliance with this humiliating and disagreeable mandate.
Seven of them being in London,
and consulting together what expedients to use on this critical occasion,
came to a resolution, to present an humble presentation to the king,
of the reasons why they desired to be excused from complying with this order of council,
alledging that the aversion they found in themselves against it
proceeded neither from want of duty and obedience to their sovereign,
nor of due tenderness to dissenters;
but because it was founded upon such a dispensing power as had
been repeatedly declared by the Parliament to be illegal.

Although they waited personally upon the king with their petition,
without communicating the contents to any person whatsoever,
and presented it to the king`'s own hand, he resented it to such a degree,
that they were committed committed prisoners to the tower or London,
this extraordinary proceeding occasioned a great alarm among the people.
The petition, on the other hand, was published by authority, with satirical remarks,
setting forth,
that though the bishops had without tenderness or mercy
exercised many inhuman cruelties upon the dissenters,
they promise now to come to a temper but it is only such
an one as they themselves should settle in convocation;
and though they had all along vigorously endeavoured
to advance the regal power above all law,
when it was strained to the oppression of dissenters,
yet now (as in 1672) they want to limit it by law, when exerted for their ease,
that the laws for persecution may retain the wonted force.

And notwithstanding the public temper was warm in favour of the bishops,
yet the late severities of some of their order against the dissenters,
particularly the Quakers (so called) occasioning
some reflections which came to their ears,
they alleged, That the Quakers belied them,
and reported that they (the bishops) had been the cause
of the death of some- Robert Barclay hearing of this,
paid a visit to the bishops in the tower, and in a conference with them upon the subject,
gave them undeniable proofs of some persons,
who by order of bishops had been detained in prison until death,
though they had been apprized of their danger by physicians who were no Quakers.
This was so manifestly evidenced that the bishops were not able to contradict it;
yet Robert Barclay told them, that since, through change of circumstances,
they themselves were now under oppression,
it was by no means the intention of the people called Quakers to publish such incidents,
or to give the king or their adversaries any advantage against them thereby.
And they were accordingly very careful to refrain from every measure in word
and deed that might in any respect aggravate the case of the prisoners,
as esteeming it no time to revive old animosities,
when the common enemy was seeking an advantage.

In the present state of the nation,
both the king and the members of the established church
endeavouring to gain the dissenters to their side,
persecution subsided, and they enjoyed liberty of conscience without molestation.
In these circumstances the people called Quakers thought it convenient at their
yearly meeting in London this summer to draw up another address to the king,
upon a subject which still rendered them exposed to trouble and considerable detriment.
This address they presented to him, which was as followeth:

[.embedded-content-document.address]
--

[.letter-heading]
To King James the Second, over England, etc.

[.blurb]
=== The humble address of the people called Quakers, from their yearly meeting in London, the 6th day of the month called June, 1688:

We, the king`'s loving and peaceable subjects, from divers parts of his dominions,
being met together in this city, after our usual manner,
to inspect the affairs of our christian society throughout the world,
think it our duty humbly to represent to him the blessed effects the liberty he has
graciously granted his people to worship God according to their consciences,
hath had, both on persons and estates;
for whereas formerly we have ever had long and sorrowful
list brought to us from all parts almost of his territories,
of prisoners, and the spoils of goods, by violent and ill men,
upon account of conscience,
we bless God and thank the king the jails are everywhere clear
except in cases of tithes and the repairs of parish churches,
and some few about oaths;
and we do in all humility lay it before the king to consider the hardships
our friends are yet under for conscience-sake in those respects,
being in the one chiefly exposed to the present anger of the offended clergy,
who have therefore lately imprisoned some of them '`till death; and in the other,
they are rendered very unprofitable to the public and themselves,
for both in reference to freedoms in corporations, probates of wills and testaments,
and administrations, answers in Chancery and Exchequer,
trials of their just titles and debts, proceeding in their trade at the custom-house,
serving the office of constable, etc. they are disabled,
and great advantages taken against them, unless the king`'s favour do interpose;
and as we humbly hope he may relieve us,
so we confidently assure ourselves he will ease us what he can.

Now since it has pleased thee, O king, to renew to all thy subjects,
by thy last declaration,
thy gracious assurances to pursue the establishment of this
christian liberty and property upon an unalterable foundation,
and in order to it to hold a parliament in November next at farthest,

We think ourselves deeply engaged to renew our assurances of fidelity and affection,
and with God`'s help intend to do our parts for the
perfecting so blessed and glorious a work,
that so it may be out of the power of any one party
to hurt another upon the account of conscience.
And as we firmly believe that God will never desert
this just and righteous cause of liberty,
nor the king in maintaining of it,
so we hope by God`'s grace to let the world see we
can honestly and heartily appear for liberty of conscience,
and be inviolably true to our own religion,
whatever the folly or malice of some men on that account may suggest to the contrary.

--

This address being presented to the king was well received;
but before the time proposed for holding a parliament arrived
he found it out of his power to redress their grievances,
if he were so inclined, or support himself on his throne.
The legal confirmation of their present liberty,
and their effectual deliverance from the hardships and inconveniences,
which they experienced from their conscientious scruple against taking oaths,
were reserved for the reign of his successor.
