== Chapter III.

[.chapter-synopsis]
* Another Grievance to which this Society was exposed, suffering as Popish Recusants
* Gives occasion to a fresh Application to the King for a Noli Prosequi, which is granted
* William Penn supposed a serviceable Assistant in procuring the King`'s Favour
* His Intimacy at Court subjects him to much Censure and Suspicion
* George Fox writes an Epistle to Friends on account of regaining their Liberty
* Account of David Barclay
* And Anne Whitehead

There still remained another grievance, and a very severe and iniquitous one,
unredressed, which hath been repeatedly noticed, i.e. the sufferings of friends,
as popish recusants, particularly the act of 23 Eliz.
for 20£. a month, for absence from their parish churches (so called);
this people and that for two-thirds of their estates, were still carried into execution,
whereby many friends were greatly impoverished in their substance and estates;
being charged or entreated in the Exchequer,
and writs annually issued out front thence against them, to the several sheriffs,
to make seizure of their goods and estates to satisfy the confiscations;
by virtue whereof, rude, unprincipled bailiffs,
when they made their seizures would remain in the houses
eating and drinking until all the goods were removed.
These penal laws were as unjustly applied to the people called Quakers,
as they were severe in the extreme, being made against popish recusants,
which they were not.

They therefore made their third application to the king for a _Noli prosequi,_
or stay of process in the Exchequer, which he was pleased to grant;
and gave direction to the lord treasurer and attorney-general,
that no writs should be issued out of the Exchequer against friends on these accounts.
The lord treasurer accordingly sent his warrant to the clerk of the pipe to forbear
making out any process against any of the persons in the annexed list (being
a list of friends under persecution) and if any process were made out,
to supersede the same.
They met with some difficulty from the clerks in the office,
in relation to the fees demanded, which appeared to them exorbitant;
but at length bringing them to more reasonable terms, they got the business effected,
whereby the great damage or ruin of some hundreds of friends was prevented,
and many thousand pounds saved in their estates.

Although I do not find William Penn`'s name amongst the applicants to the king,
in these assistant in exertions for the relief of his friends
from the grievous sufferings to which they were exposed,
I presume he might be very instrumental in cultivating a friendly
disposition towards the society of which he was a member.
For he having had an intimacy with the King, when Duke of York, for whom,
excepting their difference in matters of religion,
the duke had always discovered a personal respect and esteem,
was induced by the repeated protestations he had heard him make,
to believe he was really principled for granting liberty of conscience,
and accordingly embraced the present opportunity of soliciting
for the relief of his innocent and suffering friends;
and that he might be the nearer on all occasions for serving them and others,
took lodgings this year near Kensington.

And here his acquaintance and frequency at court,
where it was generally thought those of the king`'s religion were most favourably received,
subjected him to the undeserved censure and such as least knew him,
as being a papist or jesuit,
or at least of holding a correspondence with the jesuits at Rome;
and this mistaken notion was not entertained by the common people only,
but began to get admission into the minds of some persons of better judgment;
and amongst others his acquaintance John Tillotson (afterward
Archbishop of Canterbury) having let in a suspicion of this nature,
dropped some expressions, which were improved to his disadvantage.
William Penn wrote a letter to him on the subject, which introduced a correspondence,
terminating in Tillotson`'s full conviction that his suspicion was groundless.

The condescension and ready compliance of the king with
these successive applications for relief enjoyed thereby,
however they may be viewed by others,
were by this body of people attributed neither to political projects,
nor the king`'s compassion merely, but to proceed from an hand higher than the king`'s,
which turns the actions,
consultations and designs of men to his own wise and gracious purposes,
who having in unsearchable wisdom permitted their faith and patience to be tried,
was now, in his own time, pleased to work their deliverance:
They were therefore thankful to the supreme being as the original cause,
and to the king as the mediate administrator of the favour.

It was a great consolation to the members of this society,
at their ensuing annual meeting in London, to have the company of many valuable friends,
whose faces had not been seen there for many years, having been immured in prison,
some of them twelve or fifteen years and upwards, for no crime,
but endeavouring to keep a good conscience towards God.
George Fox, who resided now mostly in and about London,
being on every occasion watchful over his friends for good,
wrote an epistle of caution to them, to beware of carelessness and lukewarmness,
creeping in through the liberty with which they were now favoured,
signifying "`that the Lord by his power had influenced
the king`'s heart to open the prison doors,
whereby about one thousand five hundred are set at liberty;
and to give a check to the informers, so that in many places meetings are pretty quiet.
My desires are that both liberty and sufferings may all be sanctified to his people;
and friends may prize the mercies of the Lord in all things, and to him be thankful,
who stilleth the raging waves of the seas, allayeth the storms and tempests,
and maketh a calm.`"

In this year David Barclay departed this life at his house at Ury in Scotland,
and by his expressions on his deathbed clearly manifested the great blessing
and benefit of having through life an eye to this awful closing scene;
in consideration whereof he was endued with fortitude to deny himself of the vanity,
the splendour and honour of this world,
to a considerable share of which his rank in life might have entitled him,
in search of true piety and peace of mind, amongst a people despised,
and everywhere spoken against.
In the latter end of September this year, being the seventy-sixth year of his age,
he was taken ill of a fever, and was also afflicted with the gravel,
which continued upon him for two weeks;
during which time he discovered a quiet and contented mind,
in no wise disturbed with the prospect of the future;
for which he had been mindful to prepare through the course of his life.
He was preserved in resignation and patience under great pain,
being supported under the feeling of a lively hope of shortly
attaining admission into the mansions of felicity,
unallayed with sorrow or pain.
Two days before his death he said to his son Robert, I shall go to the Lord,
and be gathered to many of my brethren, who are gone before me.
The next morning early, his son watching by him, and expressing his desire,
that he who loved him might be near him to his end, he answered, the Lord is nigh me.
And, as comforted in the prospect of his son`'s succeeding him, in a life of piety,
virtue and religious conversation, he said,
the perfect discovery of the day-spring from on high,
how great a blessing hath it been to me and my family!
The apothecary who attended him, visiting him in the course of his employment,
he took him by the hand and said, thou wilt bear me witness,
that in all this exercise I have not been curious to pamper the flesh.
To which the apothecary replied, Sir, I can bear witness,
that you have always minded the better and more substantial part;
and I rejoice to see the blessed end the Lord is bringing you to.
In the afternoon several of his friends came to see him; he said,
they came in a seasonable time, and after some words were spoken,
and Patrick Levingstone had prayed, the sick man lift up his hands and said, Amen,
Amen forever!
Adding, how precious is the love of God among his children,
and their love one to another! thereby shall all men know that ye are Christ`'s disciples,
if ye love one another.
My love is with you, and I leave it among you.
Several of his friends standing round his bed, perceiving some of them shedding tears,
he said, "`dear friends, all mind the inward man, heed not the outward.
There is one that doth reward,
the Lord of Hosts is his name.`" His last expressions were uttered in prayer.
"`Praises to the Lord.
Let now thy servant depart in peace.
Into thy hands, O father, I commit my soul, spirit and body.
Thy will O Lord, be done, in earth,
as it is done in heaven.`" And soon after he breathed his last.

And notwithstanding he had desired, that he might be interred without much parade,
and that not many should be invited to his funeral,
his remains were attended to the grave by a numerous train,
particularly of the higher rank, who, from the regard they bore to his memory,
came uninvited, to pay this last office of respect thereto.

This year also Anne Whitehead, wife of George Whitehead,
mentioned in this work oftener than once, by the name of Anne Downer, departed this life;
a woman religiously inclined from her early youth,
who followed the most approved preachers, and used the best means,
as far as she could discover them, to insure her present and future peace and happiness;
and when the ministers, bearing the reproachful name of Quakers,
came to the city of London, where she dwelt,
she was one of the first who received their ministry,
and was distinguished thereby that name of reproach.
Being convinced of the inward principle of the grace of God,
she yielded obedience to the convictions thereof;
and by laying aside not only manifest evils, but everything, which,
by the light she was favoured with, was discovered to be an idol of her affections,
or an obstacle to her progress in religion;
through many trials and sufferings she experienced a growth therein,
and in due time was called and qualified to preach to others
from her own experience of the work of sanctification.
Being sent for to attend George Fox and his fellow-prisoners at Launceston in 1656,
as before remarked, she travelled thither on foot, two hundred miles,
and in that journey was instrumental to convince
many of the truth of the doctrine she published,
some of whom were of account in the world.
And in her return she confirmed and established several who were newly convinced;
and in the year 1658, she travelled in the southern counties, and the isle of Wight.
She was married first to Benjamin Greenwell, a grocer in Bishop`'s-gate-street,
and afterwards to George Whitehead.
She was a woman remarkably conspicuous in her day for her singular piety,
benevolence and charity, adorned with the wisdom which is from above, pure, peaceable,
gentle and easy to be entreated, full of mercy and full of good fruits;
spending much of her time in visiting the poor, the imprisoned, the sick,
the fatherless and the widows, in their afflictions,
and taking care that nothing might be lacking for their relief.
In tender sympathy with the afflicted, willingness to distribute,
readiness to communicate, and zealous exertions to do good to others, she had few equals;
so that it might be said of her, though many daughters have done virtuously,
she (in some respects) exceeded them all.
She was justly esteemed an ornament to her profession,
for which she undauntedly suffered, when it fell to her lot.
She held her integrity to the last.
When she was visited with her last sickness, she was removed out of London,
about six miles, and her disorder increasing upon her,
she perceived it was like to prove mortal;
but the apprehension of her approaching end occasioned
no terror or perturbation in her well-prepared mind,
having filled up her place in the creation,
she seemed in a good measure prepared to receive the sentence of, "`Well done,
good and faithful servant--enter into the joy of
thy Lord`" under the animating prospect whereof,
she signified her resignation and lively hope in sundry
savory and affecting expressions to her friends,
who came to visit her on her deathbed.
To her ancient friend Mary Stout, who asking, if she knew her, she replied,
"`Yes, very well, `'tis Mary Stout.
I have my memory very well, and my understanding is clear, though I am very weak;
but I am given up to the will of the Lord, whether to live or to die;
for I have been faithful to him in what I knew, both in life and death.`"
Perceiving some in trouble concerning her, she said,
"`There is no cause for you to be troubled or concerned, for I am well and in peace.`"
To another visitor, "`If I never see thy face more,
it is well with me-- God knoweth my integrity, and how I have been,
and walked before him.`"
At another time, nearer her dissolution,
"`I have done with all things in this life, and have nothing that troubles me;
but am in true peace and ease every way.`"
She thus departed in peace the 27th of the 5th month 1686,
about sixty-three years of age,
leaving impressions of affectionate regard to her memory in the hearts of many,
to whom she had been helpful by her ministerial, or by her charitable services.
