== Chapter V.

[.chapter-synopsis]
* The Bishops in the Tower tried and acquitted
* The Queen reported to be delivered
* Prince of Orange invades England
* King James flies to France
* The Prince and Princess of Orange declared King and Queen of England
* William Penn falls under the groundless Suspicion of being a Papist or Jesuit
* William Popple`'s Letter to him thereupon
* His Answer
* William Penn summoned before the Lords of Council.

The bishops, who had been imprisoned in the tower,
were brought to their trial at the king`'s bench bar, for publishing a seditious libel,
and acquitted.
The rejoicings of the people upon this occasion were so loud and so general,
that they reached the camp on Hounflow-heath,
where the soldiers joined in the general joy (although the king was there) conveying
to him a disgusting token of the little place he had in the affections of his people,
which indeed he had taken little pains to cultivate.

It was now clearly perceived,
that the king aimed at more than a toleration of his religion,
and that his design was to give it the predominance over every other,
which gave a very discouraging prospect to his protestant subjects,
as they feared the loss of both their civil and religious
rights by the intolerant spirit thereof:
Their hopes were chiefly centered in the king`'s advanced age,
and the succession of the princess of Orange, the presumptive heiress, to the crown,
who had been educated in the protestant religion.
But these hopes were greatly damped by a report of the queen`'s pregnancy,
and afterward of her being delivered of a son,
which being a circumstance peculiarly favourable to the views and designs of the Romanists,
and depriving the protestants of their expected resource,
occasioned in the latter a strong suspicion of a deception:
Many circumstances attendant on this birth corroborated these suspicions.
But the king solemnly asserted the reality and legitimacy of the birth of his son.

The dissatisfaction of the people was so general,
as to induce them to unite in an invitation to the prince of Orange,
who brought over twelve thousand men to their assistance.
James at the same time being deserted by many of his former adherents,
was so terrified that he fled to France, and leaving the throne vacant,
a convention was summoned by the Prince,
which conferred the crown upon him and his consort, by the title of William and Mary,
king and queen of England.

When king James was declining in power,
the odium resulting from his measures reached most or all
who were supposed of his party or well-affected to his person.
William Penn continued to be exposed to much undeserved obloquy on this account,
as appears by a letter from a particular friend of his, William Popple,
secretary to the plantation office, and his answer thereto,
where we may view afresh the exaggerating spirit of party,
which forms characters from vague conjectures.

The following lines are extracts from the said letter, and William Penn`'s answer thereto.

[.embedded-content-document.letter]
--

[.letter-heading]
To the Honourable William Penn,
Proprietor and Governor of Pennsylvania.

[.salutation]
Honoured Sir,

Though the friendship with which you are pleased to honour me doth afford
me sufficient opportunities of discoursing with you upon any subject,
yet I choose rather at this time to offer unto you in writing
some reflections which have occurred to my thoughts,
in a matter of no common importance.
The importance of it doth, primarily and directly, respect yourself,
and your own private concerns; but it also, consequentially and effectually,
regards the king, his government, and even the peace and settlement of this whole nation.
I entreat you, therefore, to bear with me,
if I endeavour in this manner to give somewhat more weight
unto my words than would be in a transient discourse,
and leave them with you, as a subject that requires your retired consideration.

You are not ignorant that the part you have been
supposed to have had of late years in public affairs,
though without either the title, or honour, or profit of any public office,
and that especially your avowed endeavours to introduce amongst us a general
and inviolable liberty of conscience in matters of mere religion,
have occasioned the mistakes of some men, provoked the malice of others, and, in the end,
have raised against you a multitude of enemies,
who have unworthily defamed you with such imputations, as, I am sure, you abhor.
This I know you have been sufficiently informed of,
though I doubt you have not made sufficient reflection upon it:
the consciousness of your own innocence seems to me to have given
you too great a contempt of such unjust and ill-grounded slanders:
for however glorious it is, and reasonable, for a truly virtuous mind,
whose inward peace is founded upon that rock of innocence,
to despise the empty noise of popular reproach,
yet even that sublimity of spirit may sometimes swell to a reproveable excess.

But I must not entertain you with a declamation upon this general theme.
My business is to represent to you, more particularly,
those very imputations which are cast upon yourself,
together with some of their evident consequences; that, if possible,
I may thereby move you to labour after a remedy.
The source of all arises from the ordinary access you have unto the king,
the credit you are supposed to have with him,
and the deep jealousy that some people have conceived
of his intentions in reference to religion.
Their jealousy is, that his aim has been to settle Popery in this nation,
not only in a fair and secure liberty,
but even in a predominating superiority over all other professions:
and from hence the inference follows,
that whosoever has any part in the councils of this reign,
must needs be popishly affected: but that to have so great a part in them,
as you are said to have had, can happen to none but an absolute papist.
That is the direct charge; but that is not enough,
your post is too considerable for a Papist of an ordinary form,
and therefore you must be a Jesuit: nay, to confirm that suggestion,
it must be accompanied with all the circumstances that may best give it an air of probability;
as that you have been bred at St. Omer`'s, in the Jesuit`'s college;
that you have taken orders at Rome, and there obtained a dispensation to marry;
and that you have since that frequently officiated a priest,
in the celebration of the mass at Whitehall, St. James`'s, and other places.
And this being admitted, nothing can be too black to be cast upon you.

Now that I may the more effectually persuade you to apply some remedy to this disease,
I beseech you, Sir, suffer me to lay before you some of its pernicious consequences.
It is not a trifling matter for a person, raised, as you are, above the common level,
to lie under the prejudice of so general a mistake, in so important a matter.
The general and the long prevalence of any opinion gives it a strength,
especially among the vulgar, that is not easily shaken.
And as it happens that you have also enemies of an higher rank,
who will be ready to improve such popular mistakes, by all sorts of malicious artifices,
it must be taken for granted that those errors will be thereby still more confirmed,
and the inconvenience that may arise from thence no less increased.
This, Sir, I assure you, is a melancholy prospect to your friend;
for we know you have such enemies.

Pardon, I entreat you, Sir, the earnestness of these expressions; nay, suffer me,
without offence, to expostulate with you yet a little farther.
I am fearful lest these personal considerations should
not have their due weight with you,
and therefore I cannot omit to reflect also upon some more
general consequences of your particular reproach.
I have said it already, that the king, his honour, his government,
and even the peace and settlement of this whole nation, either are, or have been,
concerned in this matter: your reputation,
as you are said to have meddled in public affairs, has been of public concern.
The promoting a general liberty of conscience having been your particular province,
the aspersion of popery and jesuitism, that has been cast upon you,
has reflected upon his majesty, for having made use, in that affair,
of so disguised a personage as you are supposed to have been.
It has weakened the force of all your endeavours, obstructed their effect,
and contributed greatly to disappoint this poor nation of that inestimable happiness,
and secure establishment, which I am persuaded you designed,
and which all good and wise men agree,
that a just and inviolable liberty of conscience would infallibly produce.
I heartily with this consideration had been sooner laid to heart,
and that some demonstrative evidence of your sincerity in the profession you make,
had accompanied all your endeavours for liberty.

But what do I say, or what do I wish for?
I confess that I am now struck with astonishment at that
abundant evidence which I know you have constantly given,
of the opposition of your principles to those of the Romish church,
and at the little regard there has been had to it.
If an open profession of the direct opposition against popery,
that has ever appeared in the world,
since popery was first distinguished from common Christianity, would serve the turn,
this cannot be denied to all those of that society,
with which you are joined in the duties of religious worship.
If to have maintained the principles of that society, by frequent and fervent discourses,
by many elaborate writings, by suffering ignominy, imprisonment,
and other manifold disadvantages in defence thereof,
can be admitted as any proof of your sincere adherence thereunto; this,
it is evident to the world, you have done already: nay farther,
if to have inquired as far as was possible for you,
into the particular stories that have been framed against you,
and to have sought all means of rectifying the mistakes upon which they were grounded,
could in any measure avail to the settling a true character of you in men`'s judgments;
this also I know you have done.

Nay I have seen also your justification from another calumny of common fame,
about your having kidnapped one who had formerly been a monk,
out of your American province, to deliver him here into the hands of his enemies; I say,
I have seen your justification from that story under that person`'s own hand:
and his return to Pennsylvania, where he now resides,
may be an irrefragable confutation of it,
to any that will take the pains to inquire thereinto.

Really it afflicts me very much to consider that all this does not suffice.
If I had not that particular respect for you, which I sincerely profess;
yet I could not but be much affected,
that any man who had so deservedly acquired so fair
a reputation as you have formerly had,
whose integrity and veracity had always been reputed spotless,
and whose charity had been continually exercised in serving others,
at the dear expense of his time, his strength, and his estate,
without any other recompense than what results from the consciousness of doing good;
I say, I could not but be much affected,
to see any such person fall innocently and undeservedly
under such unjust reproaches as you have done.
It is a hard case; and I think no man, that has any bowels of humanity,
can reflect upon it, without great relenting.

Since therefore it is so, and that something remains yet to be done,
something more express, and especially more public,
than has yet been done for your vindication, I beg of you, dear Sir,
by all the tender efficacy, that friendship, either mine,
or that of your friends and relations together, can have upon you;
by the due regard which humanity, and even christianity,
obliges you to have to your reputation; by the duty you owe unto the king;
by your love to the land of your nativity;
and by the cause of universal religion and eternal truth;
let not the scandal of insincerity, that I have hinted at, lie any longer upon you;
but let the sense of all these obligations persuade
you to gratify your friends and relations,
and to serve your king, your country, and your religion,
by such a public vindication of your honour, as your own prudence,
upon these suggestions, will now show you to be most necessary, and most expedient.
I am, with unfeigned and most respectful affection, Honoured Sir,

[.signed-section-signature]
Your most humble and most obedient servant.

[.signed-section-context-close]
London, October the 20th, 1688.

--

[.offset]
W+++.+++ Penn`'s Answer to the foregoing Letter.

[.embedded-content-document.letter]
--

[.salutation]
Worthy Friend,

It is now above twenty years, I thank God,
that I have not been very solicitous what the world thought of me.
For since I had the knowledge of religion from a principle, in myself,
the first and main point with me has been, to approve myself in the sight of God,
through patience and well doing: so that the world has not had weight enough with me,
to suffer its good opinion to raise me, or its ill opinion to deject me.
And if that had been the only motive of consideration,
and not the desire of a good friend, in the name of many others,
I had been as silent to thy letter,
as I used to be to the idle and malicious shams of the times:
but as the laws of friendship are sacred, with those that value that relation,
so I confess this to be a principal one with me,
not to deny a friend the satisfaction he desires,
when it may be done without offence to a good conscience.

The business chiefly insisted upon, is my popery, and endeavours to promote it.
I do say then, and that with all sincerity, that I am not only no Jesuit, but no Papist.
And which is more, I never-had any temptation upon me to be it,
either from doubts in my own mind about the way I profess,
or from the discourses or writings of any of that religion.
And in the presence of Almighty God,
I do declare that the king did never once directly or indirectly attack me, or tempt me,
upon that subject, the many years that I have had the advantage of a free access to him;
so unjust, as well as sordidly false, are all those stories of the town.

The only reason that I can apprehend they have to repute me a Roman Catholic, is,
my frequent going to Whitehall,
a place no more forbid to me than to the rest of the world, who, it seems,
find much quarter.
I have almost continually had one business or other there for our friends,
whom I ever served with a steady solicitation, through all times,
since I was or their communion.
I had also a great many personal good offices to do, upon a principle of charity,
for people of all persuasions, thinking it a duty to improve the little interest I had,
for the good of those that needed it, especially the poor.
I might add something of my own affairs too;
though I must own (if I may without vanity) that they have
ever had the least share of my thoughts or pains,
or else they would not have still depended as they yet do.

But because some people are so unjust, as to render instances for my popery,
(or rather hypocrisy,
for so it would be in me) it is fit I contradict them as particularly as they accuse me.
I say then, solemnly, that I am so far from having been bred at St. Omer`'s,
and having received orders at Rome, that I never was at either place,
nor do I know any body there;
nor had I ever a correspondence with any body in those places;
which is another story invented against me.
And as for my officiating in the king`'s chapel, or any other, it is so ridiculous,
as well as untrue, that besides that no body can do it but a priest,
and that I have been married to a woman of some condition above sixteen years,
which no priest can be, by any dispensation whatever;
I have not so much as looked into any chapel of the Roman religion,
and consequently not the king`'s,
though a common curiosity warrants it daily to people of all persuasions.

And once for all, I do say, that I am a protestant dissenter, and to that degree such,
that I challenge the most celebrated protestant of the English church, or any other,
on that head, be he layman or clergyman, in public or in private.
For I would have such people know,
it is not impossible for a true protestant dissenter to be dutiful, thankful,
and serviceable to the king, though he be of the Roman catholic communion.
We hold not our property or protection from him by our persuasion;
and therefore his persuasion should not be the measure of our allegiance.
I am sorry to see so many, that seem fond of the reformed religion,
by their disaffection to him, recommend it so ill.
Whatever practices of Roman catholics we might reasonably object against,
(and no doubt but such there are) yet he has disclaimed and reprehended
those ill things by his declared opinion against persecution,
by the ease in which he actually indulges all dissenters,
and by the confirmation he offers in parliament,
for the security of the protestant religion and liberty of conscience.
And in his honour, as well as in my own defence, I am obliged in conscience to say,
that he has ever declared to me, it was his opinion; and on all occasions, when duke,
he never refused me the repeated proofs of it,
as often as I had any poor sufferers for conscience-sake to solicit his help for.

But some may be apt to say,
why not any body else as well as I? Why must I have the preferable access to other dissenters,
if not a papist?
I answer, I know not that it is so.
But this I know, that I have made it my province and business;
I have followed and pressed it; I took it for my calling, and station,
and have kept it above these sixteen years; and, which is more,
(if I may say it without vanity or reproach) wholly at my own charges too.
To this let me add the relation my father had to this king`'s service,
his particular favour in getting me released out of the Tower of London in 1669,
my father`'s humble request to him, upon his deathbed,
to protect me from the inconvenience and troubles my persuasion might expose me to,
and his friendly promise to do it, and exact performance of it,
from the moment I addressed myself to him: I say, when all this is considered, any body,
that has the least pretence to good-nature, gratitude, or generosity,
must needs know how to interpret my access to the king.

But, alas, I am not without my apprehensions of the cause of this behaviour towards me,
and in this I perceive we agree;
I mean my constant zeal for an impartial liberty of conscience.
But if that be it, the cause is too good to be in pain about.
I ever understood that to be the natural right of all men;
and that he that had a religion without it, his religion was none of his own;
for what is not the religion of a man`'s choice, is the religion of him that imposes it:
so that liberty of conscience is the first step to have a religion.
This is no new opinion with me.
I have writ many apologies within the last twenty years to defend it,
and that impartially.
Yet I have as constantly declared, that bounds ought to be set to this freedom,
and that morality was the best; and that as often as that was violated,
under a pretence of conscience, it was fit the civil power should take place.
Nor did I ever once think of promoting any sort of liberty of conscience for any body,
which did not preserve the common protestancy of the kingdom,
and the ancient rights of the government.
For, to say truth, the one cannot be maintained without the other.

Upon the whole matter, I must say, I love England; I ever did so;
and that I am not in her debt.
I never valued time, money, or kindred, to serve her and do her good.
No party could ever bias me to her prejudice,
nor any personal interest oblige me in her wrong.
For I always abhorred discounting private favours at the public cost.

Would I have made my market of the fears and jealousies of the people,
when this king came to the crown, I had put twenty thousand pounds into my pocket,
and an hundred thousand into my province;
for mighty numbers of people were then upon the wing: but I waved it all;
hoped for better times ;
expected the effects of the king`'s word for liberty of conscience, and happiness by it;
and till I saw my friends, with the kingdom, delivered from the legal bondage,
which penal laws for religion had subjected them to,
I could with no satisfaction think of leaving England;
though much to my prejudice beyond sea, and at my great expense here; having,
in all this time, never had either office or pension,
and always refusing the rewards or gratuities of those I have been able to oblige.

If therefore an universal charity, if the asserting an impartial liberty of conscience,
if doing to others as one would be done by,
and an open avowing and steady practising of these things, in all times,
and to all parties, will justly lay a man under the reflection of being a jesuit,
or a papist of any rank, I must not only submit to the character, but embrace it too;
and I care not who knows that I can wear it with more pleasure,
than it is possible for them with any justice to give it me.
For these are corner-stones and principles with me;
and I am scandalized at all buildings, that have them not for their foundations.
For religion itself is an empty name without them, a whited wall, a painted sepulchre,
no life or virtue to the soul; no good, or example, to one`'s neighbour.
Let us not flatter ourselves.
We can never be the better for our religion, if our neighbour be the worse for it.

He that suffers his difference with his neighbour about the other
world to carry him beyond the line of moderation in this,
is the worse for his opinion, even though it be true.
It is too little considered by christians,
that men may hold the truth in unrighteousness, that they may be orthodox,
and not know what spirit they are of: so were the apostles of our Lord;
they believed in him, yet let a false zeal do violence to their judgment,
and their unwarrantable heat contradict the great end of their Saviour`'s coming, love.

Men may be angry for God`'s sake, and kill people too.
Christ said it, and too many have practised it.
But what sort of christians must they be, I pray, that can hate in his name,
who bids us love; and kill for his sake, that forbids killing, and commands love,
even to enemies?

Whatsoever divides man`'s heart from God, separates it from his neighbour;
and he that loves self more than God, can never love his neighbour as himself.
For as the apostle said, If we do not love him, whom we have seen; how can we love God,
whom we have not seen?

Since all of all parties profess to believe in God, Christ, the Spirit, and scripture,
that the soul is immortal, that there are eternal rewards and punishments,
and that the virtuous shall receive the one, and the wicked suffer the other; I say,
since this is the common faith of christendom, let us all resolve,
in the strength of God, to live up to what we agree in,
before we fall out so miserably about the rest, in which we differ.
I am persuaded, the change and comfort which that pious course would bring us to,
would go very far to dispose our natures to compound easily for all the rest,
and we might hope yet to see happy days in poor England;
for there I would have so good a work begun.
And how it is possible for the eminent men of every religious persuasion
(especially the present ministers also my own soul with it,
God requires moderation and humility from us; for he is at hand,
who will not spare to judge our impatience, if We have no patience for one another.
The eternal God rebuke (I beseech him) the wrath of man,
and humble all under the sense of the evil of this day;
and yet (unworthy as we are) give us peace, for his holy name`'s sake!

It is now time to end this letter, and I will do it without saying any more than this;
thou seest my defence against popular calumny;
thou seest what my thoughts are of our condition, and the way to better it;
and thou seest my hearty and humble prayer to Almighty God, to incline us to be wise,
if it were but for our own sakes.
I shall only add,
that I am extremely sensible of the kindness and
justice intended me by my friends on this occasion,
and that I am, for that and many more reasons,

[.signed-section-closing]
Thy obliged and affectionate friend,

[.signed-section-signature]
William Penn.

[.signed-section-context-close]
Teddington, October the 24th, 1688.

--

Notwithstanding the foregoing explanation of his conduct;
his clear refutation of sundry calumnies charged upon him;
his open profession of his faith as a protestant,
and the unequivocal proofs he had continually given thereof,
and of his sincerity in adopting and maintaining
the principles of the people called Quakers,
whereby he was restrained from the least intermeddling in any plot in favour of,
or against any person whatever;
yet William Penn`'s intimacy with the late king had so firmly
fixed jealousies of him in many minds of all ranks,
as upon this revolution of government,
occasioned him considerable embarrassment and inconvenience for some time after.

On the 10th of December 1688, walking in Whitehall,
he was sent for by the lords of the council, then sitting;
and though nothing appeared against him, and he assured them that he had done nothing,
but what he could answer before God, and all the princes in the world;
that he loved his country and the protestant religion above his life,
and never acted against either; that all he ever aimed at in his public endeavours,
was no other than what the prince himself had declared for;
that king James was always his friend, and his father`'s friend,
and in gratitude he was the king`'s, and did ever, as much as in him lay,
influence him to his true interest;
yet they obliged him to give sureties for his appearance the first day of the next term;
which he did, and then was continued on the same security to Easter term following,
on the last day of which no cause of crimination appearing,
he was cleared in open court.

This year Rebecca Travers of London died.
She was born about the year 1609, received a religious education,
and was a zealous professor among the baptists.
In the year 1654 James Nayler came up to London,
and being engaged to dispute with the baptists, Rebecca`'s curiosity drew her,
with many others, to hear the disputation:
And coming under the impression of the prevailing prejudices,
which public rumour circulated to the disadvantage of the Quakers,
she pleased herself with hopes of enjoying the satisfaction,
of beholding the conquest and triumph of her party
over their simple and illiterate antagonist.
For she had heard of a people in the North called Quakers,
who were principally remarkable for their simplicity and rustic behaviour;
for a manner of worship strangely different from all others;
and a strenuous opposition to all the public teachers;
whereby they gave offence not only to the vain,
but even the religious part of the people were ready to condemn them.
Thus prepossessed, she came to hear the dispute,
which turned out very differently from her expectation;
for the plain peasant proved an over-match for the champions of the baptists,
making his replies and remarks so closely and so powerfully,
that she thought she felt his words smite them.
When one and another of them gave out, a third attacked him with confidence,
as if he would have borne down all opposition; but producing scriptures,
which turned against him, he also, being confuted, was obliged to give up.

Rebecca was ashamed and confounded to find a man so simple in appearance
should get the advantage of their learned men;
which affected her with serious considerations,
and abated her preconceived prejudice so far, as to beget in her a desire,
to hear him in the exercise of his ministry,
who had managed the controversy so much beyond her expectation;
she had soon after the opportunity of gratifying her desire,
at a meeting at Bull and Mouth, and was at that time so fully convinced,
that when she came home, she expressed her apprehension,
"`that since the apostles days truth could not be more plainly laid down,
nor in greater power and demonstration of the spirit, than she had heard it that day;
and from that time forward she attended the meetings of this people.`"

Soon after she was invited by a friend to dinner with James Nayler, where one present,
being high in notions, put many curious questions to James Nayler,
to which he returned pertinent answers; to which Rebecca Travers giving close attention,
James Nayler, perceiving her desirous to comprehend truth in her understanding,
rather than apply it to rectify her heart and affections, taking her by the hand, said,
"`feed not on knowledge; it is as certainly forbidden to thee as ever it was to Eve:
It is good to look upon, but not to feed upon; for whosoever feeds upon knowledge,
dies to the innocent life.`" This admonition she received as truth,
and found it so in her deepest, trials; of which she had her share.
The benefit she received from his ministry,
and the profitable impressions made upon her mind,
by the observation of his circumspect and self-denying conversation in those days,
engaged her affectionate esteem for James Nayler;
and although she was a woman of too much discretion and stability
in religion to carry her regard beyond its proper limits,
to such extravagant lengths as those weak people who contributed to his downfall;
yet being a woman of tender sympathizing disposition,
she attended him carefully in his grievous sufferings, washed his wounds,
and administered every charitable service for his relief in her power.

After some time she received a gift in the ministry,
in which she seems to have laboured mostly in the city of London and its neighbourhood.
She was a partaker in the sufferings of these times.
In the year 1659 she thought it her duty to go to the public worship house,
called John the Evangelist`'s, to which she formerly belonged;
and after their worship was ended, she put a question to the priest, as she said,
not to give disturbance, but for edification: The priest hurrying away without replying,
his hearers assaulted her with violence, railing at, and pushing her down several times,
whilst she had none to protect her, or take her part,
though several of her relations were spectators of the abuse she received.
She was committed to Newgate three times in one year, viz. 1664,
this being the year wherein the conventicle act for banishment came in force;
when the mode of short and repeated imprisonments was adopted,
in order that the third offence for transportation might be expedited.
She wrote sundry small tracts, in one of which,
directed to the parishioners of the aforesaid parish,
she gives the following account of her religious experience,
that though she had "`been a reader of the scriptures
from a child of six years old as constantly as most,
yet when, by the power of the gospel, she was turned from darkness to light,
they appeared another thing in her view,
being clearly explained to her state and her understandings,
as she came to learn of that spirit, which gave them forth.`"

She was a virtuous woman, discreet in her conduct,
and much employed in acts of charity and beneficence;
of sympathetic tenderness toward the afflicted;
and therefore one of the first of these faithful women to whom
the care of the poor and the imprisoned members of the society,
was assigned, which care, in conjunction with others, she religiously discharged.
And after a long life of virtuous and charitable deeds,
she died in much peace the 15th of the 4th month, 1688, in the 80th year of her age.

William Dewsbury a native of the East Riding in Yorkshire,
was early distinguished amongst the foremost members of this society;
both for depth of religious experience, the eminence of his labours in the ministry, and.
for the severity of his sufferings for the testimony of a good conscience.
He was first bred to the keeping of sheep, and afterwards put apprentice to a clothier.
He was religiously inclined early in life; he went amongst the independents and baptists,
but could not join in close communion with either;
and when the civil wars broke out he entered into the parliament`'s army,
with those who pretended they fought for the gospel, but appeared too ignorant,
of what he conceived the gospel to be.
As he grew more seriously attentive to religious considerations,
the recollection of the expression or our Saviour, "`Put thy sword into the scabbard,
if my kingdom were of this world,
then would my servants fight,`" affected his mind with a lively impression
of the inconsistency of war with the peaceable gospel of Christ:
Under this conviction he left the army and returned to his outward habitation and calling;
and while his hands were diligently employed in his outward vocation,
his mind was often exercised under the convictions of that
light which had convinced him of the evil of outward wars,
in a spiritual conflict with his inward enemies,
the propensities of nature and the body of sin;
and by patient and faithful attention to the grace of God which bringeth salvation,
he received strength to over come his evil propensities.
About this time George Fox coming to Balby, William Dewsbury,
as hath been related in course, assented to his doctrine,
as agreeing with his experience, joined him in fellowship,
and soon after in the work of the ministry.

He travelled much in different parts of England for the propagation of truth and righteousness,
for which, like his brethren, he met with much personal abuse from the misled multitude:
his imprisonments were many, and some of them long.
In the year 1654, on the information of Edward Bowles, a priest of York,
as a ring leader of the Quakers, judge Windham granted a warrant to apprehend him;
and being soon after apprehended at a meeting at Crake,
the constable consented to his continuing there until next day,
but in the night a rude multitude of the inhabitants beset the house where he lodged,
and seized him by violence, shouting loudly as they were hauling him from place to place.
Thus they kept him until the next day, and then took him before a magistrate; who,
although upon examination he could find no legal cause,
committed him prisoner to York Castle, where he lay until the assizes;
but was brought to no trial,
and at the termination of the assizes he was cleared by proclamation.
He then pursued the line of his duty,
travelling through Yorkshire and Nottinghamshire to Darby and Leicester,
at which places he was taken up, carried before magistrates,
and ordered to be turned out of both these towns;
but returned and fulfilled his ministry, until he apprehended himself clear.
His next imprisonment was at Northampton, in company with Joseph Storr and others,
of which a pretty full account hath been given in the course of this work.^
footnote:[See vol. I. page 190.]
In the year 1657, he went up to London, and from thence he travelled into Kent,
and along the South coast westward to the Land`'s end.
In his return through Devonshire he was stopped at Torrington, put under a guard,
and brought before the mayor and other magistrates:
At this time many being raised to offices of magistracy from inferior stations,
were very jealous of the honour of their office;
enraged at his appearing before them with his hat on, some of them, in wrath,
threw his hat on the ground, charged him with being a jesuit from abroad,
read him several new laws against him (as they said) as a vagabond,
and sent him to prison: They brought him again to examination,
to try if they could ensnare him in his words;
but he was mercifully preserved in that wisdom,
that they could gain no advantage over him that way.
They then made a mittimus to send him to the common jail at Exeter;
they returned him to his prison, where he had only the cold floor for his bed;
and made a mittimus to send him to the county jail,
in order to stand his trial at the ensuing assizes.
At last, as doubtful of their power of showing cause, they tore the mittimus,
and set him at liberty: Being released, he prosecuted his journey through Somersetshire,
Wiltshire, Gloucestershire and so on to Warwick, the place of his residence.
He visited Scotland in the year 1658, and London again in 1659.
In the years 1661-63,
his travels were much interrupted by successive imprisonments for his testimony;
first at York, for part of the two former years; next in Newgate, London; and again,
at York castle.
And in 1663 he was imprisoned at Warwick,
premunired for refusing to take the oath of allegiance,
and detained a prisoner there about nineteen years in all,
four of them under a close imprisonment.
Being released for a season by king Charles`'s declaration of indulgence,
he spent a considerable part of his time of liberty,
in repeating his travels for propagating religion and righteousness in
several parts of the nation (as he expressed it) while the doors was open.
But after a few years he was again taken up in his
travels at or about Leicester for a jesuit,
and recommitted to his former prison at Warwick.
The vindictive disposition of the persecutors of this time,
leading them to add any invidious character to the iniquity and hardship of their imprisonments,
which might render this people,
and particularly the most useful and considerable members, obnoxious to public odium;
the jesuits being in a peculiar manner obnoxious at this time;
for it was about the time of the popish plot.
In this imprisonment he was detained by the best accounts, I have,
until the general release of friends by king James.
After his last release he was disabled from travelling much,
his health and strength being so greatly impaired by the
many violent abuses and long imprisonments he had endured,
that he was obliged to rest frequently in walking
from his house to the meeting place in the same town.
In the 3rd month, 1688, he travelled to London, mostly visited the meetings in that city,
intending to stay the yearly meeting, which was approaching,
and here preached his last sermon in a lively animated
testimony to the necessity of regeneration,
in order to ensure an entrance into the kingdom of Heaven.
But being seized with a sharp fit of a distemper which he had contracted in prison,
he thought it expedient to endeavour to return home,
and left behind him a short epistle to the yearly meeting,
signifying his reason for leaving London at that time,
and wishing his friends there divine assistance and heavenly wisdom,
in their endeavours and consultations for the good of the body.

He got home by short journeys,
but survived his departure from the city only seventeen days.
He was a man of deep penetration, great experience in the work of religion;
courageous in bearing his testimony for the truth, both in his ministry and conversation,
and undaunted in suffering for it;
as appears by his following expressions on his death bed,
to some friends who came to visit him, "`Friends, be faithful,
and trust in the Lord your God; for this, I can say, I never played the coward;
but as joyfully entered prisons as palaces.--And in the prison house,
I sang praises to my God; and esteemed the bolts and locks put upon me as jewels,
and in the name of the eternal God, I always got the victory;
for they could not keep me any longer than the time determined of him.`"

His fidelity in duty, his sincerity in religion, and his patience in tribulation,
were abundantly rewarded by the serenity of his conscience,
and the peaceful tenor of his mind at this awful period,
whereby he could look death in the face, not only without terror,
but with a holy triumph over its power: For, continuing his discourse he said,
"`my departure draws nigh; blessed be God, I have nothing to do but to die,
and put off this corruptible and mortal tabernacle, this body of flesh,
that hath so many infirmities;
but the life that dwells in it ascends out of the reach of death, hell and the grave;
and immortality and eternal life is my crown forever and ever.`"

He concluded in prayer and supplication to the Lord, for all his people everywhere;
but more especially for his dearly beloved friends
assembled at the yearly meeting in London,
where he intended to have been, if his health had enabled him.
He departed this life at his house in Warwick, in a good age, the 17th of the 4th month,
1688.
