== BOOK VI. From the Revolution to the Accession of George I. Chapter I.

The Prince and Princess of Orange elected King and Queen of England.--Convention changed
into a Parliament.--An Attempt to abolish the Test.--Rejected by the Lords.--Act of
Toleration brought in and passed.--Some Members reluctant to the Ease intended the Dissenters,
and proposed a Confession of Faith as a Test.--Friends
propose a Confession of their own drawing up,
which is accepted.--Declaration of Fidelity allowed to the Quakers,
instead of the Oath prescribed by the Act.--Clause
for Payment of Tithes.--Account of Alexander Parker.
--Further Troubles of William Penn.--Account of Robert Lodge.--Robert
Barclay.--George Fox.--Thomas Salthouse.

William and Mary, prince and princess of Orange, being elected king and queen of England,
by a convention of the two estates of lords and commons,
were crowned at Westminster the 11th of 2mo. O. S. called April, 1689.^
footnote:[The coronation oath according to the new form was this:
Will you solemnly promise and swear to govern the people of this kingdom of England,
and the dominions thereunto belonging according to the statute in parliament agreed to,
and the laws and customs of the same?
Answer.
I solemnly promise so to do.
Will you to your power cause law and justice in mercy to be executed in all your judgments?
Answer.
I will.
{footnote-paragraph-split}
The next question,
will you to the utmost of your power maintain the law of God,
the true profession of the gospel,
and the protestant reformed religion established by law?
And will you preserve unto the bishops and clergy of this realm,
and to the churches committed to their charge, all such rights, and privileges,
as shall belong to them?
Answer.
All this I promise to do.]
The ceremony was performed by the bishop of London, as Sancroft,
archbishop of Canterbury, declined the office.

The king having appointed his privy council,
they judged it expedient to convert the present convention into a parliament,
in order that the new settlement might be established by a legal sanction:
and it was thought hazardous to the peace of the nation to proceed to a new election,
until the revolution was more firmly settled.
For although the common danger had united different
parties in a joint application to the prince of Orange,
yet they were no sooner rescued therefrom, than their former prejudices,
and jealousies of him, and each other, began to revive.
As he had been bred a Calvinist, and was a warm advocate for liberty of conscience,
the presbyterians and other dissenters were zealously attached to him,
and considered him as their protector;
but for the same reason the high-churchmen began to regard him with a jealous eye,
first endeavoured to exclude him from the throne, and afterwards to thwart his measures,
and perplex his government.
The old party heats were rekindling,
and virulent disputations like to blow them up to a flame.
In this state of the nation it was deemed inexpedient to proceed to a new election.
Wherefore the king went in the usual form and state,
and opened the session with a speech from the throne.
After the usual form cf returning the king thanks for his speech,
a bill was brought in and pasted, whereby the lords and commons,
now sitting at Westminster,
were declared to be a parliament to all intents and purposes.

The parliament now conceiving themselves invested
with full power to discharge their functions,
proceeded to the enacting such laws as appeared requisite
to attain the ends of the revolution.
As the fears and aversion of the protestant subjects to popery had given rise to a coalition,
which brought about this revolution,
the first attempt of the parliament was to an attempt strengthen this coalition,
in uniting the protestants of the different denominations in stronger bands of alliance
against their common adversaries and attaching them closely to the present government,
by taking away the sacramental test (so called ) and making
room for all protestants to be admitted to offices,
who might be found qualified; but this bill was rejected by the lords.
This attempt in favour, of the dissenters being supposed to be promoted by the king,
augmented the prejudices of the high-church men against him.

The next measure in favour of dissenters was attended with better success,
i.e. the bringing in and passing an act, commonly called, The Act of toleration,
entitled An act for exempting protestant subjects, dissenting from the church of England,
from the penalties of certain laws, which passed without much opposition.
For after their late promises to the dissenters, when they wanted their assistance;
after losing the pretext for opposition,
on account of the incompetency of the power granting it;
after the declaration of the bishops in their address to king James,
"`That in relation to the dissenters they were willing to come to such a temper,
as shall be thought fit,
when the matter comes to be considered and settled in parliament:`" The high-churchmen
could not with any degree of plausibility oppose so reasonable a provision for the quiet
and security of this body of the subjects in the possession of their liberty and property.
Yet still some of them could not refrain discovering their
reluctance to the relief intended to the dissenters,
and more especially to the people called Quakers by this act:
for some friends of London attending the parliament to use their
endeavours that the bill might pass in such terms as might yield
an effectual relief to the society from persecution,
and secure their religious liberties without interruption,
they found the bill clogged with a confession of faith, as a test upon the dissenters,
to qualify them for admission to the benefit of the act which seemed
to them designed to exclude the people called Quakers,
in consequence of a declaration made in the house, by some adverse member or members,
That the Quakers were no christians--An old refuted calumny of notorious adversaries,
or malicious apostates.

The article proposed to be inserted in the bill by way of test was this,
"`That all such who profess faith in God the father, and in Jesus Christ his eternal Son,
the true God, and in the Holy Spirit, co-equal with the Father and the Son,
one God blessed forever:
And do acknowledge the holy scriptures of the old and new
testament to be the revealed will and word of God.`"

Because the people called Quakers dissented from the unscriptural terms,
wherein divers professors had endeavoured to explain their notions of the three,
that bear record in heaven; and objected to the term, the word of God,
being applicable to the scriptures, in the sense the scriptures themselves apply it,
viz. The word that was from the beginning, that was with God, and was God,
their adversaries calumniated them with disbelieving the Trinity,
and denying the scriptures;
whereas they were always ready to testify their faith
in both according to scripture testimony,
but did not esteem themselves obliged to receive for doctrine, the invented terms,
or commandments of men, without it.
They believed in Christ, in his divinity, as the Son of God,
and as he is the eternal word.
And that the three which bear record in heaven, the Father, the Word, and the Holy Ghost,
are One; one God blessed forever.

Now it is apprehended,
that the above clause for a test was inserted in the bill on the
presumption that this people would scruple acceding thereto,
by some who had adopted the persuasion, received by too many at that time,
that they disbelieved the Trinity, and denied the scriptures.

Upon viewing this clause in the bill, the friends who were attending the parliament,
to solicit the passing thereof in such terms,
as might give effectual relief to them and their brethren,
as well as to other dissenters, objected to some expression in the aforesaid profession,
as appearing unscriptural; and therefore, at the desire of Sir Thomas Clarges,
and some others, who were friendly,
that they might not lie under the imputation of being no christians,
nor be deprived of the benefit of the intended act,
they proposed the following profession instead thereof,
viz. "`I profess faith in God the Father, and in Jesus Christ his eternal Son,
the true God, and in the Holy Spirit, one God blessed forever:
And do acknowledge the holy scriptures of the old and new
testament to be given by divine inspiration.`"

Which Sir Thomas Clarges took into the house,
and moved in the committee of the whole house,
that this last proposed confession of faith be inserted in the place of the former;
where upon the friends in waiting, George Whitehead, John Vaughton,
William Mead and John Osgood were called in and examined, and gave them,
or the moderate part, full satisfaction as to their belief in these points,
which was conducive to gain the end of their attendance,
obtaining the same relief for their friends, as other dissenters were favoured with.

This act gives liberty to dissenters to hold their meetings without molestation,
provided the doors were not locked, barred or bolted during the time of such meeting.
Provided also they take the oaths prescribed in the act.
And inasmuch as the people called Quakers entertain
a conscientious scruple against taking any oath,
they were entitled, upon their subscribing the following declaration,
to the benefit of the act, viz.

"` I, A.B. do sincerely promise and solemnly declare, before God and the world,
that I will be true and faithful to king William and queen Mary.
And I solemnly profess and declare, that I do from my heart abhor, detest and renounce,
as impious and heretical, that damnable doctrine and position,
that princes excommunicated, or deprived by the pope,
or any authority of the Fee of Rome,
may be deposed or murdered by their subjects or any other whatsoever.
And I do declare that no foreign prince, person, prelate, state or potentate hath,
or ought to have, any power, jurisdiction, superiority, preeminence or authority,
ecclesiastical or spiritual, within this realm.`"

And provided they shall subscribe a profession of their christian belief in these words:

+++[+++The same which the friends drew up.]

As a profession of faith is required of this society only,
it evinces the truth of the conjecture, that this profession of faith was started,
with a view to exclude the people called Quakers from a
participation in the benefits of this act.

It was also enacted, that no congregation or assembly be allowed by this act,
until the place of such meeting should be certified to the bishop of the diocese,
or to the arch-deacon of the arch-deaconry,
or to the justices of peace at the general or quarter
sessions of the peace for the county,
city or place, in which such meeting should be held,
and registered in the said bishop`'s or arch-deacon`'s court respectively,
or recorded at the said quarter sessions,
for which the register or clerk should not take a greater fee or reward than six-pence.

The people called Quakers by this act were at last legally tolerated in their religion,
and exempted from the persecution they had been long subjected to,
for keeping up their religious meetings, and declining to take the oath of allegiance.
But they were and are still subjected to the power of those
called spiritual courts in prosecutions for tithes,
the 5th clause of the act being,

Provided always,
that nothing herein contained should be construed to exempt
any of the persons aforesaid from paying of tithes,
and other parochial duties to the church or minister,
nor from any prosecution in any ecclesiastical court or elsewhere for the same.

So that they were not exempted from sufferings for their
religious dissent to the legality of tithes under the gospel.
For although the king was principled against persecution,
yet this exemption was out of his power to grant, being prevented by the coronation oath.
Many of the prosecutions for these demands evidence that
the spirit of persecution survived the act of toleration,
by the severe and oppressive methods adopted by many
claimants of tithes for the recovery of their demands,
of which an account may appear in the sequel.

They were as yet also liable to many inconveniences and losses,
by reason of their conscientious scruple to take an oath; but the legislature,
sometime after upon their petition, was pleased to yield them relief in that matter.

This year died Alexander Parker.
He was born on the borders of Yorkshire, near Bolton in Lancashire; was well educated,
and early convinced of the truth of the principles of the people called Quakers,
and became an eminent minister in that society.
He accompanied George Fox in his journey to London,
when he was sent up by Colonel Hacker to Oliver Cromwell;
tarried with him in and about London, and travelled with him through sundry counties;
as he did afterwards from time to time in divers journeys in different parts of England,
in Scotland, and into Holland in 1684.
He travelled also many journeys by himself in the exercise of his gospel labours,
being one in the number of the worthies of this age,
who were given up to the service of their maker,
and the promoting of pure religion and the practice of piety in the nation,
as the principal purpose of their lives.
In the year 1664, soon after the act for banishment was put in force,
on the 17th of 5mo. O. S. commonly called July, two justices with constables,
and armed soldiers,
came to the meeting at Mile-end-green and placed a guard at each gate:
After some time Alexander Parker stood up to speak, beginning with these words,
"`In the name of the Lord, upon which one of the justices rushed into the meeting,
profanely crying out,
"`In the name of the devil pluck that fellow down,`" which was presently done.^
footnote:[Besse, vol. 1. p. 393.]
Then the justices took the names of all the men, being thirty-two,
and sent them to Newgate for three months for the first offence upon the act for banishment.
Alexander Parker was imprisoned a second time in the tenth month the same year.
In the 3rd called May, 1670, as he was preaching in Grace-church-street,
he was violently pulled down, and carried before the mayor,
who fined him 20£. In 1669 he married Prudence Wager, of Stepney, widow,
and settled in London,
but still continued frequent travels into different parts to edify his friends.
After he fixed his residence in London he was very serviceable
in company with other friends in solicitations to government,
for the relief of their friends under sufferings, being a man very fit for such service,
comely in his person and deportment.
He wrote several treatises and epistles to his friends for their edification:
And concluded a life spent in honest endeavours to do good, in much peace,
the 8th of the 1st month 1688-9.

William Penn, notwithstanding his public disclaiming of disloyal principles;
notwithstanding the defence he had made before the council;
and notwithstanding nothing criminal had been laid to his charge;
yet his late supposed intimacy at the court of king James brought him
under strong suspicions of being disaffected to the present government,
and involved him in a series of troublesome prosecutions during the course of this year:
The intelligence of William Popple in his letter, that he had many powerful enemies,
seems confirmed by the sequel, for he was again brought before the privy council,
upon an accusation.
of holding a correspondence with the late king:
Upon their requiring sureties for his appearance, he appealed to king William himself,
who, after a conference of near two hours, inclined to acquit him; but,
to please some of the council he was held upon bail,
and in Trinity term the same year discharged.

As the campaign in Ireland had not been at tended with much success the last year,
king William determined to command the army there in person,
which suggested to some of the discontented party a favourable opportunity,
during his absence to form a conspiracy in favour of the abdicated monarch:
This conspiracy, originally formed in Scotland,
was discovered about the time of the king`'s departure for Ireland,
upon which a proclamation was.
issued out by the queen, foreseeing, not only those immediately engaged therein,
but such also as lay under suspicion of being zealous partisans of the late king,
and amongst others William Penn; who,
with divers lords and others to the number of eighteen,
was charged with adhering to the kingdom`'s enemies; but proof failing respecting him,
he was again cleared by the court of king`'s bench on the
last day of that called Michaelmas term this year.

Being now at liberty, he had purposed to make another voyage to Pennsylvania,
and had published proposals in print for a second settlement there,
but was prevented by a fresh accusation of being concerned in another plot.
King William going over to the congress at the Hague,
as soon as his intentions were known,
some of the disaffected party resolved to take advantage of the opportunity,
which his absence would afford them, to form a new conspiracy against the government;
and in order to accomplish their design,
Lord Preston and one Ashton were fixed upon to go over to France,
to concert with king James the measures and conditions, upon which they were to proceed:
But by intelligence given to the Marquis of Carmarthen
they were both taken in the hold of the vessel,
which they had engaged to take them to France,
together with the packet of letters and papers they were carrying over.
Ashton was executed: But Preston, to save his own life,
informed against several of the nobility,
who had been most active in forwarding the revolution,
as well as against many of the partisans of the late king,
and amongst others against William Penn;
and this accusation being backed by the oath of one William Fuller,
who was afterward branded by the parliament with infamy as an impostor,^
footnote:[In the year 1702 this Fuller was prosecuted
in the king`'s bench and convicted as an impostor:
And for publishing certain libels, one entitled, Original letters of the late king James, etc.
Another, Twenty-six depositions of persons of quality and worth,
was sentenced to stand three times in the pillory, to be sent to the house of correction,
and to pay a fine of one thousand marks.
--Salmon`'s Geography, p. 241.]
a warrant was thereupon granted for the apprehension of William Penn,
which he narrowly escaped at his return from George Fox`'s burial,
the 16th 11mo O. S. called January 1690-1.

He had hitherto defended himself before the king and council:
But perceiving his safety to be greatly endangered, having, undeservedly,
many powerful enemies, the tide of public rumour

making against the accused, and witnesses now procured against him in particular,
he thought it more advisable to retire for the present,
'`till more favourable circumstances might give him an opportunity
of being heard without prejudice in vindication of his innocence,
than in the present circumstances hazard the sacrificing
thereof to the oaths of a profligate miscreant;
he accordingly appeared little in public for two or three years.
During this recess he employed himself in writing; and first,
lest his friends might be induced by public report to entertain
any suspicious sentiments concerning him,
he sent the following epistle to their yearly meeting in London, viz.

The 30th of the third month, 1691.

My beloved, dear, and honoured brethren,

"`My unchangeable love salutes you; and though I am absent from you,
yet I feel the sweet and lowly life of your heavenly fellowship, by which I am with you,
and a partaker amongst you, whom I have loved above my chiefest joy:
receive no evil surmisings, neither suffer hard thoughts,
through the insinuations of any, to enter your minds against me, your afflicted,
but not forsaken, friend and brother.
My enemies are yours, and, in the ground, mine for your sakes;
and that God seeth in secret, and will one day reward openly.
My privacy is not because men have sworn truly,
but falsely against me for wicked men have laid in wait for me,
and false witnesses have laid to my charge things that I knew not,
who have never sought myself, but the good of all, through great exercises,
and have done some good, and would have done more, and hurt to no man;
but always desired that truth and righteousness, mercy and peace,
might take place amongst us.
Feel me near you, and lay me near you, my dear and beloved brethren; and leave me not;
neither forsake,
but wrestle with him that is able to prevail against the cruel desires of some,
that we may yet meet in the congregations of his people, as in days past,
to our mutual comfort.
The everlasting God of his chosen in all generations, be in the midst of you,
and crown your most solemn assemblies with his blessed presence! that his tender, meek,
lowly, and heavenly love and life may flow among you,
and that he would please to make it a seasoning and fruitful opportunity
to you! that edified and comforted you may return home,
to his glorious high praise, who is worthy forever!
To whom I commit you, desiring to be remembered of you before him,
in the nearest and freshest accesses, who cannot forget you in the nearest relation,

Your faithful friend and brother,

W.P.

His excellent preface to Robert Barclay`'s works, and another to those of John Burnyeat,
both printed this year, were farther fruits of his retirement; as were also,

1+++.+++ A small treatise, entitled, "`Just Measures, in an epistle of peace and love,
to such professors as are under any dissatisfaction about
the present order practised in the church of Christ.`"

2+++.+++ "`A key opening the way to every common understanding,
how to discern the difference between the religion professed by the people called Quakers,
and the perversions, misrepresentations, and calumnies of their adversaries,
both upon their principles and practices;
wherein several doctrines of that people are set
in a clear light:`" a book so generally accepted,
that it has been re-printed even to the fifteenth edition.

Having thus improved the time of his retirement,
it pleased divine providence in the year 1693,
to dissipate this cloud and to open his way again to public service:
for through the mediation of his friends, Lord Ranelagh, Lord Somers, Sir John Trenchard,
or some of them, he was admitted to appear before the privy council,
where he pleaded his innocence, so as to obtain his release,
and met with no further trouble on the like account.

In this year the society were deprived of the following eminent and serviceable members,
some of whose labours have appeared considerable enough to be particularly
noticed in course in various parts of this history,
viz. John Burnyeat, Robert Lodge, Robert Barclay, George Fox and Thomas Salthouse.

1+++.+++ John Burnyeat married, and spent his latter years in Ireland,
where will be the proper place to give account of him.

2+++.+++ Robert Lodge,
his early and frequent companion and fellow traveller in
his religious visits to his friends in various parts,
had his domestic residence at Masham in Yorkshire, where he was born about the year 1636.
He was religiously inclined from his youth, and his understanding was opened to behold,
in true religion,
a purity and refinement beyond the instructions and general
doctrine of the priests or teachers of that age;
with several of whom he would discourse on serious subjects,
in which he generally proved his apprehensions and notions superior to theirs,
before he had heard of any of the people called Quakers,
or joined himself to their religious society: But when they came into those parts,
he (with many others) was convinced about the year 1654,
and the eighteenth year of his age.
A meeting was gathered here to sit together in silence, waiting for divine instruction,
to feel the state of their own minds,
and to receive power over their natural infirmities and propensities,
and through faith being strengthened to obtain the victory,
were in due time prepared to receive spiritual gifts.
Amongst them Robert Lodge was favoured with an eminent gift in the ministry,
in the exercise whereof he travelled in this nation, and in Ireland;
his labours were attended with a convincing evidence,
whereby he was made instrumental to gather many from the
evils that are in the world and the entanglements thereof,
to serious consideration of their ways,
and religious desires after the attainment of peace and future happiness.

His labours and travels in Ireland, in company with John Burnyeat,
have been related in course.
Soon after his return in 1660, he was imprisoned,
with one hundred and twenty-five more in the county of York,
in the general imprisonment succeeding the insurrection of the fifth monarchy men,
and detained in prison till king Charles II. issued
his proclamation for their release in the next year.
He was again imprisoned at Wakefield in the said county in 1665.
He went to Ireland a second time in company with George Fox in 1669,
where their service was conducive to the strengthening of many,
their meetings being held and their ministry exercised under
the sense of`' the divine power and presence.

After his return he continued his ministerial labours
for some time about his native county:
And attended the yearly meeting in London,
accompanied by his old companion John Burnyeat, in the years 1674 and 1676,
and in the latter year visited Bristol and parts adjacent.
John Burnyeat and he had been frequent companions in travelling,
and closely united in their services, and they finished their course nearly together,
the former being removed by death the 11th and the latter the 15th of the same month,
viz. the 7th month O. S. commonly called July, 1690.

Robert Lodge (with many other of his faithful brethren,) having kept his first love,
and holden his integrity to the last,
in his concluding scene felt that serenity of mind
which supported him above the fear of death;
of which his expressions to his friends, who visited him in his last sickness,
appear a convincing evidence;
to one of whom he expressed his feeling of an approving conscience in these terms,
"`The Lord knows my heart that I have served him; and it hath been of more account to me,
the gaining of one soul, than all my labours and travels.`" To another,
"` It is well with me, I have no disturbance in my mind.`"
And to a third, "`The Lord knows I was never commissioned to go any way,
or to do any thing, but I have willingly answered him;
and the Lord who hath been my rock and refuge, my shield and buckler, and my sanctuary,
hath been with me all along to this day.`" His last expression was "`Blessed be God,
I have heavenly peace.`" In this peaceful temper of mind he breathed his last,
like one falling into an easy sleep.

He was a man of an amiable disposition; a fine natural temper,
cultivated by pure religion: A preacher of righteousness,
no less in the whole tenor of his life, and circumspect conversation,
than in word and doctrine;
whereby he acquired the general esteem of his friends and neighbours,
and left an honourable and spotless reputation behind him.

The particular account of Robert Barclay`'s birth, family, education and convincement,
laid before the reader at his first introduction into this history,
and of his services in the course thereof,
while it points him out as a man conspicuous for usefulness in the society,
anticipates a considerable portion of the memoirs of his life and labours:
So that it remains principally to relate the manner of his conclusion;
transcribe his character, as drawn up by his intimate friend William Penn, and others,
who were well acquainted with him;
and to give account of the writings he hath left behind him,
in vindication of his religious profession.

This excellent man was taken away in the prime of life,
having attained only the 42nd year of his age: But in a life devoted, as his was,
to the love and service of his creator,
and the employment of those remarkable talents with which his mind was enriched,
to the propagation of pure religion among mankind, I esteem every period of our age,
in the ordering of divine wisdom, a life long enough to answer the end of our existence,
and to ensure our well-being in a state of eternal duration.
His sickness was short; but having through life had his eye to a future state,
he wanted not a long time of preparation for death.
James Dickenson of Cumberland,
being in the course of his religious travels in these parts, paid him a visit,
when on his deathbed, and as he sat by him,
they were favoured with the feeling of the divine power
and presence humbling and solacing their spirits;
under the tendering affection whereof Robert Barclay
expressed his love to all faithful friends in England,
who kept their integrity in the truth;
and desired James to remember it to friends in Cumberland and at Swarthmore,
and the faithful everywhere, adding, "`God is good still,
and though I am under a great weight of weakness and sickness, yet my peace flows;
and this I know, whatever exercises may be permitted to come upon me,
they shall tend to God`'s glory, and my salvation,
and in that I rest.`" He died at his house at Ury
in Scotland the 3rd day of the 8th month,
1690.

His character as an author is given already: As a man and a christian,
three of his intimate friends, who were well acquainted with his merit, William Penn,
Patrick Livingstone and Andrew Jaffray,
have in substance described his character as followeth:

He loved the truth and way of God, as revealed among us, above all the world,
and was not ashamed of it before men; but bold and able in maintaining it.
Sound in judgment; strong in argument; cheerful in sufferings; of a pleasant disposition;
yet solid, plain and exemplary in conversation.
He was a learned man, a good christian; an able minister; a dutiful son,
a loving husband, a tender and careful father, an easy master,
and a good kind neighbour and friend.
These eminent qualities in one, who employed them so serviceably,
and who had not lived much above half the life of a man, aggravated the loss of him,
especially in that nation where he lived.
William Penn

He was a lover of peace, and on all occasions exerted his endeavours to promote it.
The quickness of his penetration and discernment furnished him with ability;
his love of peace, with a disposition to promote reconciliation;
and his uncorrupted integrity,
with understanding to give sound judgment in matters of difference,
and compose and determine them with impartiality, Patrick Livingstone.

He ruled his own house well; so that beauty, good-order, holiness,
gravity and humility were conspicuous therein.
He was a man of great meekness, evenness of temper, and lowliness of spirit,
not in the least degree lifted up with the superiority of his attainments,
natural or spiritual:
But through the assistance of divine grace was so
preserved in dominion over pride and passion,
that he was rarely ever seen in a peevish, angry, fretful, or disordered temper.
Andrew Jaffray.

His writings were mostly of the polemical kind.
As he lived at a time when great pains were taken to vilify
and defame the society of which he was a member,
he found it his concern to vindicate his profession
from the misrepresentations of its antagonists,
which he is generally allowed to have done in a masterly manner in the following tracts.

1+++.+++ Truth cleared of Calumnies, published in 1670, about the 23rd year of his age,
occasioned by a book, entitled A Dialogue between a Quaker and a stable Christian,
the invention supposed of one W. Mitchell, a preacher near Aberdeen.

2+++.+++ Queries proposed to the serious consideration of the inhabitants of Aberdeen,
by way of appendix to Truth cleared of Calumnies, 1670.

3+++.+++ William Mitchell unmasked;
being an answer to his Animadversions upon Truth cleared of Calumnies 1671.

4+++.+++ A seasonable warning,
and exhortation to and expostulation with the inhabitants of Aberdeen,
concerning this present dispensation, and day of God`'s merciful visitation towards them,
1672.

5+++.+++ A catechism and confession of faith, etc. l673.

6+++.+++ The Anarchy of the Ranters, and other libertines; the Hierarchy of the Romanists,
and other pretended churches, equally refused and refuted, 1674

7+++.+++ A Vindication of the preceding tract, serving as an explanatory postscript, 1679.

8+++.+++ An Apology for the true Christian Divinity,
as it is held forth and preached by the people called in scorn Quakers.
Dedicated to king Charles II, 1675, the 28th year of his age.

9+++.+++ A dispute between John Lestey, Alexander Sheriff P. Gelly,
called students of divinity, at Aberdeen, and Robert Barclay and George Keith, 1679,

10+++.+++ Quakerism confirmed.
A vindication of the chief doctrines and principles of the Quakers,
from the objections of the students of divinity 1690.
(so called) of Aberdeen, in their book, entitled Quakerism canvassed, 1676.

11+++.+++ Universal Love, 1677.

12+++.+++ An Epistle of Love and friendly Advice,
to the Ambassadors of the several Princes of Europe met
at Nimeguen to consult of the Peace of Christendom,
showing the true cause of War, and proposing the best means of Peace.
To each of whom, with the epistle, were delivered one of his Apologies,
which were received with respect, 1677.

13+++.+++ A Vindication of his Apology;
in reply to the objections made against it by one John Brown, in his book,
entitled Quakerism the path-way to paganism, 1679.

14+++.+++ The Possibility and Necessity of the inward and immediate Revelation
of the Spirit of God towards the Foundation and Ground of true Faith,
proved: In a letter written in Latin to a person of quality in Holland;
and now also put into English, 1676.

George Fox grown too infirm to bear travelling,
in consequence of the multiplied hardships,
he had endured in long and afflicting imprisonments, and by other means,
spent his latter years in the city of London and its neighbourhood,
as the place where he could be most essentially and universally serviceable to his friends,
particularly those under persecution and suffering for their religious testimony,
his sympathy with them producing an anxious solicitude for their relief.
Be sides his public service in the meetings of his friends in the city,
and places adjacent; and writing several epistles of advice on various occasions;
he spent much time in perusing the records of the affairs of the society,
especially those of the meeting for sufferings, and the letters addressed thereto,
which when communicated to the meeting,
he was sure to press the speedy answering thereof, according to the exigency,
in suffering cases; and to promote applications to government,
both in behalf of particular sufferers, and for the ease of the body in general,
by proper persons, who were more fit for active services than himself,
in the decline of his health and strength.

The last epistle he wrote, was a consolatory epistle to friends in Ireland,
with whom he deeply sympathized under the great hardships, dangers,
and distressing sufferings,
they were afflicted with by the war at that time carried on in that kingdom.
And the next day after he had written this epistle,
he went to the meeting at Grace-church-street,
which was large (it being on the first day of the week) where he
was enabled to preach the gospel fully and effectually,
opening many deep and weighty truths with great power and clearness;
after which he prayed.
And after the meeting he went to Henry Goldney`'s in White-hart-court,
adjoining to the meeting house, and some friends accompanying him,
he told them he thought he felt the cold strike to his heart as he came out of the meeting,
adding, "`I am glad I was there; now I am clear,
"`I am fully clear.`" As soon as the company retired,
he lay down upon a bed (as he sometime used to do,
through weariness after a meeting) but soon rose again; and feeling his strength decay,
he was obliged to take his bed, where he lay in much contentment and peace.
William Penn, who was present with him in the time of his confinement,
hath reported "`that as he lived so he died, feeling the same eternal power,
that raised him to be greatly serviceable in his generation,
and preserved him steadfast in a life of righteousness,
to raise him above the fear of death in his last moments.
In full assurance he triumphed over death; and was so calm in his spirit to the last,
as if death were hardly worth notice: Recommending to some of us, who were with him,
the dispersion of an epistle he had lately written, and some of his books;
but above all the care of friends, and of all friends those in Ireland and America,
twice over repeating '`mind poor friends in Ireland and America.`'
And to some, who came in and inquired how he felt himself?
he answered, "`never heed; the Lord`'s presence is over all weakness and death,
the seed reigns, blessed be the Lord.`" He had the comfort of a short illness,
and his senses clear to the last.
He survived his last ministerial labour only two days,
being removed from works to rewards on the succeeding third day of the week,
in perfect love and unity with his brethren, and in peace and good-will to all mankind,
the 13th of the 11th month, 1690, in the 67th year of his age.

His funeral from the meeting at White-hart-court on the 16th of
the same month was at tended by a great concourse of friends,
and other people of divers sorts (for though he had many enemies,
yet many others had a high esteem of his signal virtues)
to friends burying ground near Bunhill fields,
where (as well as in the meeting) several affecting testimonies were borne,
under the lively sense and remembrance of his extraordinary services, during his life,
after which his body was decently interred: but his memory,
and the fruits of his religious labours, still survive.

He was a man of tall stature and large body, but remarkably temperate in eating,
drinking and sleeping.
His deficiency in literature, and want of a liberal education,
have furnished a topic of ridicule and contempt to the generality
of writers who have taken notice of him.
But William Penn, who had the opportunity of knowing him better,
and of discovering under the unpolished surface, the intrinsic value of his character,
describes him to be "`a man whom God endowed with a clear and wonderful depth;
a discerner of other men`'s spirits, and very much a master of his own.
And though the side of his understanding, which lay next to the world,
and especially the expression of it, might sound uncouth and unfashionable to nice ears,
his matter was nevertheless very profound,
and would not only bear to be often considered, but the more it was so,
the more weighty and instructive it appeared.
And as abruptly and brokenly as sometimes his sentences
would fall from him about divine things,
it is well known they were often as texts to many fairer declarations.
And indeed it showed beyond contradiction, that God sent him,
in that no art or parts had any share in the matter or manner of his ministry;
and that so many great, excellent and necessary truths,
as he came forth to preach to mankind,
had therefore nothing of man`'s wit or wisdom to recommend them.
So that as to man he was an original, being no man`'s copy.`"

He ever confirmed the doctrines he promulgated, by the example he set,
showing forth the fruits of the spirit out of a good conversation: Upright, steadfast,
pacific, sincere, innocent, disinterested, charitable,
sympathizing and universally benevolent,
he not only maintained the ancient christian doctrine in words,
but manifested in a practice uniformly regulated thereby, "`that the grace of God,
which bringeth salvation, and hath appeared to all men,
teacheth to deny ungodliness and worldly lusts; and to live soberly,
righteously and godly in this present world.`"
And although esteemed a fool as to the wisdom that is from beneath,
he was richly replenished with that wisdom which is from above, which is sure, peaceable,
gentle and easy to be entreated, without partiality and without hypocrisy; full of mercy,
and full of good fruits;
and I am persuaded many have indulged their pride in ridiculing and censuring him,
who fall far short of him in solid wisdom and pure virtue.

I have in my hands in manuscript the testimony of a person generally
allowed to be a very competent judge of men and things,
who after remarking that he dared to assert the freedom
of man against the tyranny of customs,
sprung up in the times of gothic barbarism and monkish ignorance,
concludes "`I revere that wisdom, and that goodness,
who condescended to afford us such an example of prirmitive christianity in life,
doctrine and conversation, so near our own times.`"

Thomas Salthouse was living in Judge Fell`'s family
at the time when George Fox came to Swarthmore,
and was convinced by his ministry with the greatest part of that family.
And being faithful to conviction,
he sometime afterward received a dispensation of the gospel,
and was commissioned to preach it to others.
In the year 1654 he travelled to London,
from whence in company with Miles Halhead he went to Bristol;
and thence westward towards Exeter:
But numbers being discontented at the time with Oliver
Cromwell`'s usurpation of the government,
encouraged the party called cavaliers to attempt an insurrection in the west,
which was soon quashed;
and guards being placed in these parts to take up
such as were suspected to be assistant therein,
when these friends reached Honiton,
they were taken up and brought before Colonel Copleston, high sheriff of the county,
on suspicion of being cavaliers, and of being concerned in the insurrection:
And though upon examining them, he owned he believed them clear, he imprisoned them,
and sent them away with a pass as vagrants,^
footnote:[See vol 1 p. 207-209.]
which is already related,
together with their succeeding imprisonment by the procurement of George Brooks.
After their release, they went to their habitations in the north; but Thomas Salthouse,
in 1656, travelling again in the work of the ministry returned into the western counties,
and continued some time in that quarter, in the exercise of his gift,
in the course whereof he was taken from a meeting at d Thomas Budd`'s at Martock in Somersetshire,
and committed by Robert Hunt and John Cary to Ivelchester jail, as a dangerous,
wandering and idle person, till the quarter sessions,
where the justices tendered him the oath of abjuration,
for his refusal whereof they fined him 5£. and remanded
him to prison till he should pay it,
where he continued a prisoner about a year.

After his release he prosecuted his travels for promoting
religion and righteousness in different parts of the nation;
and in 1660 returned again into the west,
and was again imprisoned at Ivelchester in the 11th month that year,
together with his companion John Scaife, and many others;
at the ensuing assizes at Chard,
the greatest part of their fellow prisoners were released,
but these two and a few more were detained till the ensuing sessions;
at which the rest were discharged;
but the court required sureties of Thomas Salthouse and John Scaife for their going home,
the former into Lancashire, and the latter into Westmoreland,
and for their coming no more into Somersetshire for three years;
terms which they could not comply with:
Wherefore Thomas Salthouse was sent back to prison,
and John Scaife to the house of correction as a vagabond.
They were detained till the latter end of the third month,
and then enlarged upon the king`'s proclamation for setting the Quakers at liberty.
He was again taken up with Thomas Lower,
on account of an insurrection in the month of October the same year;
but after a long examination and a detention of three days, being found innocent,
they were discharged.

After a considerable portion of his life spent between
travelling and labouring for the promotion of truth,
and suffering for his testimony thereto, he married in Cornwall,
and settled his habitation at the town called St. Austel in that county.
Yet continued in frequent visits to different parts of the nation,
in the exercise of his ministry;
and although he escaped imprisonment for some time after this,
he did not escape out of the reach of the informers, when they were set to work;
for in the 12th month 1681 was the funeral of Benjamin Growden,
a man well be loved of his neighbours, many of whom attending his funeral,
Thomas Salthouse addressed them in a brief exhortation suitable to the occasion,
i.e. to seriousness and sobriety, reminding them of the certainty of death and judgment,
and a retribution according to their works, etc.
This exhortation he delivered in the open burying place at Tregangreves,
to an audience of many good christians, loyal subjects,
and professors of the protestant religion as by law established.
On such an occasion, and to such an assembly, one would scarce expect,
that reminding men of their mortality, and inciting them to prepare for death,
could have been liable to the penalties of any law: Yet upon the oath of two informers,
who were there watching for their prey, several of those present were convicted unheard,
and fined for a conventicle by three justices, Sir Joseph Tredenham, Joseph Sawle,
and William Mohun, amongst whom Thomas Salthouse was fined 20£. for preaching:
For which shortly after goods were taken out of his shop to the
value of 29£. 9s. 9d. He was again committed to Launceston jail,
and with several others l690 or declining to take an oath
was brought to the assizes in the 6th month 1683,
where the oath was again tendered them in open court, and upon conviction of refusing it,
sentence of premunire was passed upon them,
under which they were detained in prison near three years,
till they were discharged by king James`'s general pardon.

After his release from this his last imprisonment he continued his visits to his friends,
as he felt the draft of duty and brotherly affection exciting him thereto;
till a period was put to all his labours and sufferings by his removal out of this life,
which happened in the 12th month 1690, at his house in Cornwall,
about the 60th year of his age.

He was a man of a good natural capacity,
and adorned with an excellent gift in the ministry;
remarkably affable and pleasant in his conversation,
which procured him the respectful regard of many others as well as friends.
He wrote some notable tracts and divers excellent epistles to friends,
and is no doubt at rest from his labours, and his works follow him.
