== Chapter II. Ireland.

[.chapter-synopsis]
* Friends in Ireland recommended a Collection for their suffering Brethren in England
* Account of Thomas Carleton
* James Barry calumniates the People called Quakers, and being desired to give them a Meeting evades it
* W. Edmundson warns his Friends of an approaching Day of trial
* The Earl of Tyrconnel disarms the Protestants
* Many of whom flee to England
* The Natives spirited to Insolence
* W. Edmundson and others abused by Troopers
* A Massacre apprehended
* W. Edmundson and two of his Neighbours go to Dublin to complain of these Abuses
* Tyrconnel reluctant to hear them
* They apply to Colonel Russel Lord Granard and Lord Mountjoy

Friends in Ireland still appear less liable to sufferings than their brethren in England,
their principal sufferings being for the non-payment of tithes,
and the unreasonable costs of recovery in Friends in the bishop`'s courts;
on which occasion they petitioned the lord lieutenant and council:
But this collection people being as yet much exposed to great sufferings
in England by the rapacity of the informers and otherwise,
furnished a fresh instance of the sympathetic concern and mutual benevolence,
which prevailed amongst them, as members of one family all the world over;
their brethren in Ireland understanding that many had been by the ravages of these informers,
and penalties severely inflicted upon them for their religious testimonies,
reduced to necessitous and distressed circumstances,
took their suffering case into consideration at their national meeting this year,
and recommended a collection towards their relief,
to be made by friends in the several provinces.

This year died at Ballinacarrick, county Wicklow, Thomas Carleton,
a native of Cumberland,
where he was convinced of the principles of the people called Quakers,
and joined them in society, after passing through many spiritual conflicts,
of which the reader may find a clear account, written by himself,
in Rutty`'s history of the rise and progress of this people in Ireland, to which,
to avoid unnecessary prolixity, I refer.

He removed to reside in Ireland about the year 1673,
was a man of greater abilities than many others,
of a good understanding and clear discernment, yet of an humble spirit,
ready to prefer others before himself.
As a member of religious community, he was circumspect and exemplary in his conversation,
zealous and diligent for keeping good order therein; he was an able minister,
being endowed with a divine gift to minister from;
whereby he was instrumental both to convince strangers, and to confirm,
edify and provoke to diligence those who were already convinced:
He was also well qualified to exercise his pen in asserting and
defending the principles of his profession against its opponents;
and patient in suffering for them,
as appears from a tract he published while a prisoner in Carlisle jail for tithe,
entitled [.book-title]#The Captives Complaint,
or the Prisoners Plea Against the Burdensome and Contentious Title
of Tithes,# wherein are laid down the several reasons against the
propriety of paying tithes in this evangelical day and dispensation.
He published some other small tracts,
particularly an excellent general epistle of admonition
and advice to friends in Ireland and elsewhere.

In consequence of the prohibition issued by the government of Ireland last year but one,
the other bodies of dissenters deserted their meeting houses, and met more privately:
But the people called Quakers in this nation, like their brethren in England,
continued their public meetings, both for the worship of God, and those for discipline,
wherein being strengthened and comforted,
they were favoured with the increase of peace in themselves,
and near unity one with another.
Their public meetings were crowded by the resort of numbers of other societies,
with many of whom their innocent fortitude,
in openly bearing their testimony to the propriety of meeting to worship the Almighty,
according to the persuasion of their consciences, had gained them a good report.
While some of the other societies of dissenters, who absconded, or met in private,
suffered their minds to be filled with envy and prejudice against them,
principally because they would not desert their public assemblies,
as themselves had done.

Among the rest, one James Barry, an independent preacher in Dublin,
published many accusations and groundless calumnies against this people,
friends and upon hearing thereof, some of them applied to him,
to give them a public meeting, in order to make good his charges,
or furnish them with a fair opportunity of clearing themselves; but he made many excuses,
would not give them an hearing, and notwithstanding continued his railings against them;
by which conduct, instead of gaining his ends,
in depriving them of any part of that estimation
which they had obtained in the opinion of the public,
he preached away many of his own hearers, who, like the noble Bereans,
came to friends meetings to satisfy themselves whether these reflections were true or no;
and by the ministry of John Burnyeat and others, their prejudices were removed;
they were convinced, joined themselves to,
and became afterwards very serviceable members of, the society.

At this time the government having made choice of
some friends to serve in offices in corporations,
and to act as magistrates, and some few having accepted thereof,
though it was not of their own seeking,
a paper of tender advice was drawn up by order of a general meeting,
to those friends who had engaged in these offices,
to act conscientiously in every station; to shine as lights in the world,
and be punctual in distributing justice with impartiality.

William Edmundson, after his return from America, and some stay at home,
renewed his travels in various parts of this nation, in the exercise of his ministry.
In his progress in which service,
his spirit was deeply affected with an humbling sense
of great afflictions and trials approaching,
which would try the inhabitants of the land;
when the carcasses of men would be spread on the earth as dung;
under the impression whereof he plainly warned friends and others,
in many public meetings,
and advised his friends particularly to contract their concerns in the world,
that they might be prepared to receive the Lord in his judgments that were at hand,
and to flee to him for succour, that they might find refuge in his protection.

And the times soon after began to look gloomy and
threatening to the protestants of this nation,
in a much greater degree than in England.
The Earl of Clarendon, although the king`'s brother-in-law,
had been removed from the station of lord lieutenant to make way for the Earl of Tyrconnel,
who, from his first advancement to this office, seemed determined,
by the most arbitrary and undisguised measures, to humble the protestant subjects;
destroy their interest, power and property in the nation;
and transfer them into the hands of the popish inhabitants;
and to establish his despotic government over the heads protestants, of the former,
he disarmed them, and modelled and composed an army chiefly of the latter;
so that the leading men among the protestants, and many others of all ranks,
recollecting the cruelties of the Irish in the massacre of 1641,
which many still living could remember,
and others had heard dismal accounts of from their parents,
being terrified at the prospect of the insecurity of their persons and properties,
and dreading the repetition of the former barbarities, fled to England for safety,
leaving their possessions open to the invasion of their enemies.

Every succeeding season presented a succession of terrors and injuries to the protestants,
and increased the number of refugees.
Tyrconnel proceeded with precipitancy and violence in establishing the civil government,
as well as the military power in the hands of the Romanists;
they were put in possession of the council table,
the courts of Judicature and bench of justice-- the charters of Dublin
and all the corporations were recalled--protestant freemen expelled,
Roman catholics introduced, and the latter sect, who were the majority in number,
were now invested with the whole power of the kingdom.

By this partiality of the government in their insolence favour,
the natives of the lower classes, assumed a spirit of insolence and abuse,
to the increasing the terror of the disarmed protestants,
who saw no safety but in exile or the shelter of fortresses.

William Edmundson among others was a great sufferer at this time, who,
although an inoffensive man, and principled against taking up arms;
yet being much respected by, and looked upon as an eminent man among the protestants,
in the neighbourhood of his residence, a man of fortitude, and one, who,
having frequently made applications to government in favour of his friends,
was known and respected by several of the leading men on both sides,
and was now very serviceable in like applications on behalf of his protestant neighbours,
was marked out as an object of abuse in this unsettled time.
A party of Sir Maurice Eustace`'s troopers came into their parts
and committed many violent abuses upon several protestants in,
and about, Mountmellick.
Some of them came to William`'s house, and made him a sharer in their injurious treatment,
taking him by the hair of the head,
and dragging him about the yard amongst their horses feet, without the least provocation;
some with clubs, and others with pistols cocked, swore they would kill him;
upon hearing which, his wife was so terrified, that she desired them,
to take all they had so that they would spare her husband`'s life.
Report went to Mountmellick that William Edmundson was killed,
which made the inhabitants of that town conclude that a general
massacre of the protestants was determined upon,
being persuaded William Edmundson would give them no occasion.
Many of the protestants fled in consternation to
the bogs and woods to conceal themselves.

After these troopers were gone off,
William went next morning to Mountmellick to confer with the principal inhabitants,
who had not fled, who were glad to see him alive, but seemed of the opinion,
that this violent treatment of protestants was a forerunner of a massacre.
William was of a different sentiment,
apprehending it was rather with design to alarm and terrify all the English settlers,
to induce them to flee to England,
that they might get the country and all their substance to themselves,
than any intention of a massacre.
He advised them to take full examinations of the abuses, and petition the government;
and there by they might probably make some discovery of their intentions.
His proposal being approved, he was desired to undertake the journey, as none else durst.
Although he was sensible of the jeopardy attendant upon the undertaking,
as at the hazard of his life;
yet perceiving it might be conducive to the general security of that neighbourhood,
he assumed his usual courage, to risk his life for the good of his countrymen.
He pitched upon two of the townsmen to accompany him, who assented,
and next day taking their journey by an unusual road, for fear of being way-laid,
they arrived safely in Dublin.

W+++.+++ E. having an interest with Lord Chief Justice Nugent,
by his interference procured an audience of Tyrconnel,
who appeared to hear his complaint with reluctance,
and gave him little encouragement to expect redress from him.
Not discouraged by his cool reception here,
he resolved to prosecute the matter to the utmost;
and with his companions (whose complaints Tyrconnel would not even hear) waited upon
Colonel Russel who was colonel of the regiment to which these troopers belonged,
and gave him a relation of the abuses they had committed,
and the general consternation of the English inhabitants.
He, who was a protestant, seemed alarmed at the report, and expressed his apprehensions,
that, "`If such proceedings met not with exemplary punishment,
it was time for every man to look to himself;`" but he would go to the Duke,
and remonstrate against the iniquity of such proceedings.^
footnote:[Colonel Russel soon after went over to England]
They applied next to Lord Granard, the lieutenant general,
who upon hearing their account, in great dissatisfaction remarked,
that he was general and no general;
and determined also to remonstrate to the Lord Lieutenant Tyrconnel upon the subject.
They applied also to Lord Mountjoy, and others of the principal men among the protestants.
By these successive applications, the rumour of these proceedings spread;
and Tyrconnel sending for William,

William, seemed displeased, and said, They had made as great noise in the city,
and wanted to know, If they had witnesses ready,
to which William replied in the affirmative.
They were then referred to Lord Chief Justice Nugent,
before whom they appeared next morning,
as did also chief justice Sir M. Eustace and the troopers, who being examined,
all denied the fact.
William then being asked, if he knew any of them that had abused him, challenged one,
who confessed; and then the officer, who headed the party,
was ordered to discover the rest, which he did; upon this they were disarmed,
and sent to Maryborough jail.
William and his companions, apprehending they had discovered their real intention,
returned home.
Afterwards, at their request, William forgave the troopers,
and procured their horses and arms to be returned to them.
