== Chapter V. America.

Meeting-house built in Philadelphia.--Death and Character of Robert and Jane
Owen.--Ditto of John Skein.--Yearly Meeting to be held alternately at Burlington
and Philadelphia.--Care to prevent strong Liquors being sold to the Indians,
and Means used for their Instruction.-- Emigration from Holland
and Germany.--Life and Character of Christopher Taylor.
--Two Letters from William Penn to the Colony.

In this year friends of the quarterly meeting of Philadelphia put in execution the design,
which they had a considerable time in contemplation,
of building a meeting-house in the city.
At a quarterly meeting held in the sixth month it
was concluded to have one built in the center,
between the two rivers bounding the city, of brick,
fifty feet by thirty-six in dimension, which being in due time completed,
the meetings were held there, till the bank meeting-house was built:
The next year friends of Burlington also built a large commodious meeting-house

The quarterly meeting of Philadelphia was now composed of
the following particular meetings and bodies of friends,
viz. Tacony (or Oxford) Poetquesing, the Welsh friends,
and those contiguous to the city on the other side of Schuylkill,
with the meeting of Philadelphia; and in a few years the friends of Plymouth, Byberry,
and Dublin or Abington, joined them.

This year James Martyn from East Acton in Middlesex,
crossed the seas on a religious visit to the continent of America,
where he spent a considerable part of two years;
passing through the meetings of his friends in Pennsylvania
and other parts of that continent:
And being a man of worth and innocency, whose conversation adorned the gospel,
which he preached faithfully,
his zealous and diligent labours amongst them were edifying, serviceable and acceptable,
to his friends in those parts.

In the year 1685,
an honourable ancient couple of distinction amongst the Welch colonists
were removed by death shortly after their arrival in America,
viz, Robert Owen, late of Doleysevre near Dolgelly in Merionethshire, and Jane his wife,
whose character, two of their countrymen, John Humphrey and Rowland Ellis,
who knew them well both before and after they removed to America,
have left us upon record, in testimony of their worth,
from whence the following abstract is drawn.

They were both well descended from families of the
rank of gentry (as they are usually termed).
The said Robert inherited from his father a competent estate,
and received a liberal education, suitable to his rank in life.
Being blessed with a good genius and quick apprehension, his presidency in literature,
and his intellectual abilities,
placed him in eminence amongst his neighbours of the same rank.
After the expiration of the protectorate,
he received a commission of captain of militia and governor of Beaumorris,
under the committee of safety,
which he held to the time of the restoration of King
Charles II. and discharged his functions with fidelity.
But the solidity of his understanding, illuminated by divine grace,
made him clearly perceive that real and durable happiness
was not founded in the estimation of men,
or worldly honour Or preferments, but in something more substantial;
from which consideration he had long devoted the
attention of his mind to religious researches,
and by the sincerity of his heart and the influence of the light he was favoured with,
was endued with penetration to distinguish between the precious and the vile,
between pure religion and the appearance thereof;
and being disposed to part with all (like the wise merchant-man
in the gospel) to possess himself of the precious pearl,
pure religion, and the peace of mind resulting therefrom,
his researches terminated in joining in society with the people called Quakers,
from which he was not deterred by the prospect of
sharing with them in persecution and reproach.
It appears to have been about the time of the restoration
that he fully joined this body of people,
although I apprehend, as far as I can gather from the above cited testimonies,
that he was partly convinced before.
But now the change of government, and of the national worship,
introducing party altercations and struggles for power and preeminence,
and amongst many of the ecclesiastics an offensive versatility of profession,
to secure the revenues of the livings they possessed, in some; and in the rest,
on one side an avaricious engrossing of the emoluments of the church so called to themselves;
on the other the regret at losing them,
seemed to manifest more of a spirit of covetousness than of christianity
prevailing amongst them in too general a way.
This offensive conduct was an occasion of stumbling to many of their hearers,
who were sincere in religious inquiries, and of looking forward to a people,
who were more disinterested and exempt from such struggles,
and was the means of increasing the numbers of this society,
by the addition of many valuable members.
Amongst them, I apprehend, was Robert Owen, who upon this revolution in the state,
was with many others committed to prison, not indeed as a Quaker,
but for accepting a commission under the former government;
and although he cleared himself of acting under the same,
only in compliance with the orders of his superiors, yet the opposite party,
in the exultation and intemperate warmth of party zeal,
exerted themselves to effect his ruin in body and estate.
Others imprisoned on the like account obtained their liberty by the act of oblivion,
passed some time after, upon their taking the oaths of allegiance and supremacy,
which our said friend at this time could not do,
being in conscience persuaded of the unlawfulness of an oath;
and chose rather to suffer adversity, than wound the peace of his own mind.
He therefore suffered five years close imprisonment in the town of Dolgelly,
about a mile from his own house, whither he was not permitted to go during that time.
At last his principal prosecutor was visited with a fit of sickness,
under which the remorse of his conscience was such that he could enjoy neither
rest nor ease until he sent a special messenger to release him.

His wife, Jane Owen, was also honourably defended,
her father being in the office of a justice of peace,
and a man for integrity conspicuous above most of his rank.
His said daughter was a woman whose natural good understanding
was improved by a religious turn of mind;
she was of a grave and solid deportment; adorned with a meek and quiet spirit;
in her prosperity humble-minded; in adversity patient;
a sympathizing help-meet and encourager to her husband in all his trials;
he being a repeated sufferer for his religion, by imprisonment and loss of substance.
They freely opened their house for the reception of the meetings of their friends,
through the hot test times of persecution,
whereby they were frequently exposed to sufferings and spoil.
As they had a large family, she being the mother of nine sons, her relations,
persons of eminence and influence in that country, but not walking by faith, as they did,
were often solicitously engaged to plead with her husband to pity his children,
and save his estate; but she, on the contrary,
found it her place to encourage him to fidelity to his duty,
and not to violate his conscience for fear of suffering, in which,
when it fell to his share, she tenderly sympathized,
and with firmness and courage bore her part therein.

They were remarkable for their hospitality,
their house and hearts being open to all honest friends and other sober people.
Being very serviceable members of religious and civil society,
they were greatly loved and respected in their native country.
From whence after they had borne their share of suffering in the heat of the persecution,
and had spent a length of years together in near affection,
they removed in their old age to Pennsylvania in the year 1684,
and there laid down the body in peace,
and were buried within a few days of each other in the fifth month 1685.

About this time died John Skein, formerly of Aberdeen in Scotland, his native country,
where he was marked out as a principal member of this society, by the excess of injury,
depredation and persecution to which he was exposed there.^
footnote:[See vol. 2. p. 464, 468.]
About 1678 he removed to America, and settled in West Jersey,
of which (being a man of good abilities,
natural and acquired) he was advanced to the station of governor,
which he filled with reputation and integrity near two years.
And it is a remarkable instance of the solidity of
the religion of these early professors of the truth,
that neither the frowns of power, nor the possession thereof,
were able to make their constancy and steadfast adherence
to rectitude and religious considerations,
which in their prosperity as well as adversity were the ruling principles in them,
whereby they were supported to bear sufferings with patience and fortitude,
and prosperous circumstances with humility and fear.

By these principles John Skein, in the enjoyment of power,
was instructed to use it for the service of the people,
over whom he was placed in government,
not in mere profession (as too customary) but in truth and reality, as a religious duty.
And while he was employing his talents in the service of government,
and discharging his trust with fidelity in his station, as a member of civil society,
he did not look upon it as beneath him, but esteemed it his indispensable duty,
to fill up his place also in religious society among friends,
both by his exemplary conduct, and his edifying ministry.

The general yearly meeting which for the past four
years successively had been held at Burlington;
at a meeting in 1683,
had been agreed upon to be held alternately at Burlington and Philadelphia.^
footnote:[This yearly meeting was first intended to consist of friends northward,
as far as New England, and southward as far as Carolina:
Maryland sent representatives for some time.
But the distance of their habitations rendering it inconvenient
for friends of the remoter colonies to give their attendance,
the yearly meeting was constituted of the friends of New Jersey and Pennsylvania only,
and so continued several years;
but now a considerable number of friends residing in the western
parts of Virginia and Maryland belong to this yearly meeting,
which since the year 1760 hath been held annually at Philadelphia.]
In consequence of this agreement,
the first yearly meeting in the latter place began
on the fifteenth of the seventh month this year.
Many friends from East and West Jersey expressed their unity and satisfaction
in the present establishment of one yearly meeting for the three provinces.
Amongst other subjects of deliberation,
the concerting of some additional measures for preventing all persons,
who went under the name of Quakers,
from being in any manner concerned in selling rum to the Indians,
particularly engaged their attention.
This subject attracted the very early and earnest care of
the first settlers of this society in both provinces,
from the clear sense they had of the iniquity and bad consequences of this traffic.^
footnote:[The bad consequence and iniquity of this traffic,
is clearly set forth in a pamphlet published in Philadelphia,
entitled Some Observation on the Indian Natives of this Continent.
Much of their blamable conduct, now complained of,
is certainly imputable to a long continued train of fraudulent
and corrupt practices in our intercourse with them,
especially the fatal introduction of strong drink, of which they have often complained,
and desired it might not be brought amongst them,* by which
instead of allaying the ferment of corrupt nature,
by a good example, and the good instruction,
which our superior knowledge would enable us to give them,
too many have been instrumental in working them up to a state of distraction,
which when it has burst forth in vengeance upon ourselves,
is made a pretence for destroying them, as though they were wholly the aggressors.
That Indians may be tempted or provoked to the perpetration of great evils,
by the intemperate love and use of strong liquors, is easily conceived; but whether they,
who, to gratify the cravings of sordid avarice,
furnish them with the intoxicating potion, and then take advantage of their situation,
to impose upon them, and tempt them to evil, are not principally accountable,
for the crimes they commit, and their consequences,
is a query worthy of their most serious consideration.
{footnote-paragraph-split}
From Maija:
Here`'s the footnote within a footnote
{footnote-paragraph-split}
*At the treaty at Carlisle,
in 1753 the Indians say, "`The Rum ruins us.
We beg you would prevent its coming in such quantities.
We desire it may he forbidden, and none sold in the Indian country;
but that if the Indians will have any, they may go amongst the inhabitants,
and deal with them.
When these Whiskey traders come, they bring 30 or 40 Kegs, and put them before us,
and make us drink,
and get all the skins that should go to pay the debts
we have contracted for goods bought of the fair trader;
and by this means, we not only ruin ourselves,
but them too.`"
{footnote-paragraph-split}
"`The wicked Whiskey sellers,
when they have once got the Indians in liquor,
made them sell their very clothes from their backs.
In short, if this practice be continued, we must be inevitably ruined.
We most earnestly, therefore,
beseech you to remedy it.`"
{footnote-paragraph-split}
We find an early record,
in the history of New Jersey, to the credit of the people of that day.
That at a conference they held with the Indians, where 8 Kings or Chiefs were present,
the speaker expressed himself to the following effect:
"`Strong liquors were sold to us by the Swedes and by the Dutch; these people had no eyes,
they did not see it was hurtful to us; that it made us mad.
We know it is hurtful to us.
Nevertheless, if people will sell it to us, we are so in love with it,
that we cannot forbear; but now there is a people come to live amongst us,
that have eyes; they see it to be for our hurt;
they are willing to deny themselves the profit, for our good.
These people have eyes, we are glad such a people are come,
we must put it down by mutual consent.
We give these four belts of wampum ---to be a witness of this agreement we make with you;
and would have you tell it to your children.`" ]

Instead of endeavours to take advantage of the weakness of the natives by making
ungodly gain in a commerce so injurious to their temper and their morals;
these friends and their European brethren who visited them,
exerted endeavours to cultivate amity and a friendly
correspondence with the native Indians,
in order by kind treatment, fair dealing, and good conduct,
to gain their esteem and good opinion,
thereby to open themselves a way to be more essentially serviceable to them,
in bringing them to an acquaintance with the principles of christianity.
For this purpose religious-minded friends friends to would
frequently enter into conversation with them,
visit them in their villages, and hold meetings amongst them;
their discourses being explained by an interpreter
to such of them that did not understand English.
John Hayton and James Martin from Europe,
who came early in a religious visit to friends in these provinces; William Penn,
Samuel Jennings, Thomas Olive, and others of the new settlers, had meetings amongst them,
as well as many since from time to time,
wherein they used endeavours to inculcate the benefit of a christian life.
And in this year a committee of friends was appointed by the quarterly
meeting of Burlington to pay the neighbouring Indians a religious visit,
and hold a meeting among them, to which many of the Indians gathered,
and quietly attended to what was delivered.
At this and many other meetings of this kind they seemed to be affected,
and particular persons amongst them would profess
some convincement and reformation for a season;
and in a general way they would be serious on these occasions,
and confess to the truth and goodness of what they heard and understood;
but the thorough mortification of their passions and natural appetites,
which is the essence of christianity, seemed a discipline too severe for them,
habituated to little restraint, to submit to.
Yet the religious conversation and virtuous examples
of these first settlers in these provinces,
and their free and friendly correspondence and intercourse with them,
were conducive to bring the bordering Indians to a degree of civilization
and good neighbourhood unknown to those of the remoter tribes.

About the year 1686 many friends and others from Holland and Germany arrived in Pennsylvania,
who, fixing their residence among their land and friends,
contributed to the extension of the town Germany, called Germantown,
situated six miles north of Philadelphia, which had been begun in 1682.
Several of them, I apprehend, emigrated from the Palatinate,
in which province many of the inhabitants had adopted the name and profession of Quakers,
whereby they escaped sharing in the succeeding calamities
of their country in the year 1689,
when Louis the Fourteenth, in the cruel wantonness of power,
caused the fine towns in that principality to be destroyed by fire.

In this year Christopher Taylor of Pennsylvania departed this life.
He was brother to Thomas Taylor, of whom an account hath been given before in 1681.
He is supposed to have been born near Skipton in Yorkshire,
and as well as his brother received a learned education,
to qualify him for the office of the ministry:
and he officiated as preacher among the puritans '`till he was convinced about
the same time with his brother by the ministry of George Fox in 1652,
and after some time he became an approved minister amongst the people called Quakers,
and travelled in many parts of the nation to propagate religion and righteousness,
but was imprisoned at Appleby in Westmorland in 1654, by warrant from Thomas Burton,
a justice, for speaking, what he esteemed his duty,
to a priest in the steeple-house yard,
where he remained under severe sufferings and inhuman usage about two years.
During his imprisonment he wrote a warning to the rulers in England,
especially to the persecuting rulers, priests and people in the county of Westmoreland,
and some other pieces.
After his release from this imprisonment, I have no certain account of his future travels.
At some distance of time I find he kept a boarding-school
of repute at Waltham Abbey in Essex,
for children of both sexes,
during which time he employed his leisure hours in
exercising his pen in the service of truth.
From Waltham he removed about to Edmonton in Middlesex, and continued his school there.
In the discharge of his duty he was remarkably zealous and diligent,
not only in instructing the children under his care in literature,
but in successful endeavours to instill into their
tender minds early impressions of religion,
virtue, and the fear of their maker.
In these laudable endeavours he was effectually seconded
by the joined exertions of his wife,
a faithful woman and a minister, and of his principal assistant, John Materft,
a German by birth, who had received a learned education in his native country,
being also designed for the sacerdotal office;
but being convinced of the principles of the people called Quakers about 1674 there,
he removed to reside amongst his friends in England,
and engaged with Christopher Taylor as assistant in his school,
for which station he was well qualified, not only as a man of literature,
but in the more valuable qualification of the truly religious and faithful man.
The conjoined labours of these worthy men had a remarkable effect
on the minds and manners of the children under their tuition,
of which they published an account this year,
under the title of A Testimony to the Lord`'s Power
and blessed Appearance in and among the Children.
John Matern did not long continue,
but finished his course in this life at Edmonton the 1st of the 7th mo, 1680,
under the consolation of a good conscience,
and a well-grounded hope of entering into eternal rest.
His concern for the lasting good of the children
under his care only left him with his parting breath;
for about four hours before his departure he desired them to be called up into his bed-chamber,
and there he prayed for them, and gave them his final exhortation,
to be faithful to the little they knew of the fear and will of their maker,
and that greater degrees would be added.
After his death Christopher Taylor continued his
school at Edmonton between two and three years,
during which time he wrote a cautionary epistle to
friends in relation to William Rogers`'s writings,
and an answer to two of his libels.
About the year 1682, resigning his school to George Keith,
he removed with his wife to Pennsylvania, where she died in the year 1685,
and himself the next year.
And although the residence of this valuable man was of no long duration in this colony,
he lived long enough to impress his friends there with a lively sense of his worth,
and of their loss in his so speedy removal, as appears by their testimony,
that he was a diligent and faithful minister among them; in the exercise of his gift,
pertinent, clear and affecting; in prayer, solemn, reverent and weighty;
in his general deportment, circumspect, meek and humble.
He was also, in a civil capacity,
a very respectable and serviceable member of the colony of Pennsylvania,
and for his services the few years he lived there,
seems to have been regarded by them as one of the best men of the age in which he lived.

William Penn, at different times in the year 1689,
sent the following letters to his friends in Pennsylvania;

My dear Friends and Brethren,

If it be with you, as I can say it is with me in the presence of God,
then are we one in him; for neither length of days, nor distance of place,
nor all the many waters between us, can separate my heart and affections from you;
but my love, yea the love of God my father, and your father, abounds towards you,
with endeared salutations to you all; and for you, and the blessing of you and yours,
with grace, peace and prosperity,
are my knees bowed to the God of all our mercies and preservations; that a holy,
blameless people, without guile and wrath, brawling and selfishness,
you may be made and kept in all things.
That God may spread his great name over you, and make a wall of defence about you,
and create a glory upon the same, to your unspeakable joy,
and the renown of his own great power; for this mine eyes have beheld under the sun,
that all is vanity in comparison of him,
and that happy and blessed is that people whose God is the Lord.
For the nation or province upon the earth that will not reverence him,
and call in righteousness upon him,
and in all their undertakings have his glory first in their eyes, shall be cut off.
He will vex, visit and trouble that people,
that they may know that he ruleth in the kingdoms of men.
Therefore the Lord guide you by his own spirit, and preserve you a lively,
green and savoury people to his praise.
Amen.

Great revolutions have been of late in this land of your nativity,
and where they may period the Lord knows;
it can be no new thing for us to meet with exercises.
Europe looks like a sea of trouble; wars all over it, like to be this summer;
I strongly desire to see you before it be spent, if the Lord will;
and I can say in his sight,
that to improve my interest with King James for tender consciences,
and that a christian liberty might be legally settled, though against my own interest,
was that which has separated me from you chiefly.
I desire your remembrance before the Lord,
as you are not and cannot be forgotten in my addresses and approaches to him,
who rest in his unchangeable love, Dear friends and brethren,
your`'s unalterably in the communion of the precious truth,

2nd 1st mo 1689

William Penn

My love to friends in Jersey, etc.
Let this be read among friends,

Hammersmith, 30th 10th mo, 1689,

Dear Friends,

I cannot slip this opportunity, but send you the endeared salutations of my love,
that in the truth gives me frequent occasions to remember you,
and earnestly desire your preservation to God,
as well as your comfort and prosperity about outward things about which have a care,
that they grow not too fast upon you, nor too many for you,
I mean as to the cares and concerns that attend them in the exercise of your spirits;
for it is a blessed state to enjoy and use the world
in the dominion of his life and power,
that has quickened by his light and spirit a people to himself;
for in this stands all our peace and blessedness, that God be eyed in the first place,
that we set him on our right hand, that we set him continually before our eyes,
and that our eye be directed towards him in all things,
as the eye of the handmaid to her mistress,
that we may be able to say in truth and righteousness, We have none in Heaven but him,
nor any on earth besides him- This it is that keeps God`'s people everywhere,
for hereby they put on Christ in all his blessed teachings and leadings,
and make no provision for the flesh, to fulfill the lusts thereof.
Friends, they are deep words, and deeper things; I know you understand me,
and I hope you feel me, who have your eyes to the mark, and look to the joy before you,
that is above all joys in this momentary, troublesome, busy world.
And now, friends, I have a word more to you, and that is this, that faith,
hope and charity are the great helps and marks of true christians, but above all,
charity is the love of God, or divine love.
Blessed are they that come to it, and hold the truth in it, and work and act in it,
for they are poor indeed in spirit of their own, but rich in God`'s; they are meek,
they inherit; all other states are a brangle in comparison, but this enjoys,
this possesses, this reigns.
O come into this love, more and more,
for to this shall all gifts and operations give place,
and they do so in the hearts of those that are come to know charity greatest in them.
It will preserve peace in the church, peace in the state, peace in families,
aye and peace in particular bosoms.
God Almighty draw, I beseech him, all your hearts into this heavenly love more and more,
that the work of it may shine out to God`'s glory and your comfort.

For matters here, as to myself, I am well and free, and for the church of God,
liberty continues; but in the nations of Europe, great wars, and rumours of wars,
such as have not been almost from the beginning; suns are turned into darkness,
and moons into blood, for the notable day is at the door.
It could not be borne from some of you, when you went for America,
that such a day would come, but come and coming it is, for almost every eye sees it,
and tongue says it, and some thousands, alas! have already felt it.
Sanctify, therefore, the Lord in your hearts; be satisfied in him and in your lot,
and walk worthily of his daily mercy, and attendance upon you, and care over you;
and the Lord keep you to the end.
I am, in the truth that makes us near to God, and one to another,

Your faithful friend and brother,

W+++.+++ Penn.
