== Chapter III.

[.chapter-synopsis]
* Act of Settlement repealed
* King James lands in Ireland, which becomes the Seat of War
* The People called Quakers keep their Habitations and Meetings in the Midst of Danger
* National Meeting 3mo; O+++.+++ S. now 5mo
* Ditto 9mo, now 11mo
* The Citizens of Londonderry shut their Gates against King James`'s Army
* The War breaking out, Friends (with others) exposed to great Injury and Hardship
* An Army arrives from England
* Battle of the Boyne
* King James leaves the Kingdom
* Parties of the Irish Army cruelly plunder the Protestants
* William Edmundson proproseth to his Irish Neighbours an Interchange of good Offices
* Which he maketh good on his part, notwithstanding their Insincerity
* King William publisheth a general Proclamation of Pardon

That William Edmundson`'s conjecture was well-grounded
appeared manifest by the proceedings of the parliament,
which was afterwards summoned by King James to meet in Dublin.
One of their first measures was to repeal the act of settlement,
by which the protestants of the kingdom had been
secured in the possession of their estates;
and the bill was so severely framed, that no regard was paid to such protestant owners,
as had purchased estates for valuable considerations;
no allowance was made for improvements, nor any provision for protestant widows;
the possessor or tenants were not even allowed to remove their stock and corn.
They also passed an act of attainder against all the protestants,
who were absent from the kingdom,
and against all those who should retire to any part of the three kingdoms,
which did not own the authority of King James.
By these two acts they had gained the point in view,
by stripping the protestants present and absent of all their property,
and taking it into their own possession, if they could have retained power to secure it.

The late King James upon his desertion of England retired to France,
where he was very cordially and hospitably received by Lewis XIV.
who also assisted him with some forces and a considerable number of officers;
arms for the use of his numerous adherents in Ireland; a large sum of money;
a fleet and transport ships to land them there,
which was effected in the first month of this year; and in consequence thereof,
this nation becoming the theatre of a war,
threatening the utter ruin of all the English protestants,
increased the number of refugees into England or into garrisons.
But through all, the people called Quakers generally kept their habitations,
and kept up their religious meetings, placing their confidence in divine protection,
surrounded as they were with perils on every hand.
For they were not only exposed to the depredations meetings in of soldiers,
permitted to live upon free quarter,
and countenanced by their officers to be very abusive;
but to the more savage devastation and cruelties of armed bodies of banditti,
under no restraint or discipline, termed tories and rapparees,
who infested every quarter of the nation, plundering and burning all before them.

Notwithstanding the imminent danger of travelling in a nation thus circumstanced,
yet such was the zeal of friends at this time for the discharge of their religious duties,
and for their own edification, and growth in religious experience,
and such their faith and confidence in the protection of divine providence,
that all the terrifying prospects and impending dangers could not prevent them,
from resorting from the different parts of the kingdom to
the national meeting in Dublin in the third month this year,
even at the hazard of their lives.

The principal business,
which engaged the deliberations of the present and succeeding national meeting,
was the distressed condition of their brethren through the nation,
and the ordering of convenient supplies proportioned to their necessities.
They received accounts of the sufferings of friends in several
parts of the nation by robberies and spoils by soldiers and others,
and the losses sustained by friends of the province of Leinster appeared
to be above 900£. Hereupon friends made application to King James,
who received them kindly, and promised that they should be protected.^
footnote:[Dublin the 13th of 3d month, 1689.
Our half year`'s meeting is over,
where were assembled many friends and brethren from divers parts of the nation,
according to our usual manner.
We enjoy our meetings peaceably and quiet generally over the nation,
and in most places our meetings are large, and many people come in;
and all people have their liberty in the free exercise
of their consciences in matters of religion;
and as for friends and truth, they are in good esteem both with high and low.
The Lord`'s care and mercy over us hath been largely manifest,
and friends do learn great experience of the preservation
of the mighty arm of the Lord in this great day of trial,
which is upon this nation;
yet to our joy and comfort friends are carried over it in the faith of the Son of God,
and have been preserved miraculously, even beyond our expectation in several places,
where their trials have been very great, and the dangers, as to appearances, dreadful;
yet friends have kept to their habitations, trusting in the Lord,
and following their lawful concerns and business.
At this half-year`'s meeting our hearts were made more than ordinarily
glad to see one another`'s faces in such a time as this,
and the Lord`'s power and presence was with us, that crowns our meetings;
and in the sense and sweetness of the same are the most of our friends and brethren
this day gone towards their outward beings in the peace of God,
and in great love and unity,
which did preciously abound amongst us in this our
meeting throughout all our concerns and affairs.
Extract of a letter from John Burnyeat.]

At the succeeding half year`'s meeting in the ninth month, it appeared,
that the losses of friends being still continued and increased,
those of the friends of Leinster and Munster amounted to
above 7000£. No account appears in my author from Ulster,
which I apprehend, being now seat of war, must have been the most considerable,
but that friends, as well as other inhabitants,
were too much alarmed and distressed to find leisure to
keep and return regular accounts of their sufferings,
though many of them were spoiled of all their substance.^
footnote:[At Cavan (a place that lay open to both armies and to
the cruelty of the rapparees) several friends kept their habitations,
and held their usual meetings;
and though sometimes in skirmishes between the two armies many were slain,
their lives were wonderfully preserved;
but of their substance they were spoiled and entirely stripped,
and at last commanded by the chief officer of the Irish army to quit their habitations,
and their houses were set on fire.]

After King James`'s arrival in Dublin, and establishing a more orderly government,
than had subsisted there for some time before,
the protestants became better settled in their minds,
and their fears of a massacre began to die away;
but they were still exposed to great devastation,
their stock and cattle being mostly taken away from them or killed;
friends were obnoxious to these depredations in common with other protestants.

James was in Ireland at the head of a considerable army,
and he and his partisans possessed of the whole power
and command of the nation for several months,
before any forces arrived from England to give them opposition:
But on the first alarm of an intended massacre,
the protestants of Londonderry had shut their gates,
and resolved to defend themselves against the Lord Lieutenant,
being at their request supplied with some arms and ammunition from England;
and the protestants in other parts of the province of Ulster,
which had suffered most severely in the massacre of 1641,
who retained the deepest impressions of terror and resentment,
seemed resolved to prepare for their own defence
against the repetition of such inhuman barbarities,
as they recollected, or had heard,
were then exercised by the merciless natives on their contemporaries or predecessors.
In order to quash this insurrection, the army was put in motion to march to the North,
which now being likely to become a scene of war and devastation; William Edmundson,
in company with some friends of Dublin (from the
impulse of that universal fraternal regard,
which subsisted amongst the members of this society at this time)
was zealously concerned to use all his and their interest and influence
with the chief officers to spare and protect their friends,
who were not in arms, and many of them promised they would,
and performed their promises.

As the storm of war gathered, the calamities of the peaceable inhabitants,
in which number are comprised the people called Quakers, increased.
The rapparees on one hand plundered many of the English without mercy,
and on the other hand, the army marching, and being quartered upon them,
took from them what they pleased;
the protestant families were but as servants to wait upon them,
and dress them what provisions their houses afforded, so that,
between the one and the other,
the melancholy prospect of famine for themselves seemed most they had to look for.

At length an army from England arrived, An army under the command of Duke Schomberg;
but the ill success of the campaign,
and the miserable situation of the Irish protestants,
determined King William to take the command upon himself, and attempt their relief.
He landed at Carrickfergus in the summer 1690, marched forward without much delay,
and came in view of King James`'s army,
which had taken an advantageous post on the banks
of the Boyne to dispute the passage of that river;
but the English army having made good their passage, attacked the Irish,
and put them to flight.

King James immediately after this battle made a precipitate retreat by Dublin to Waterford,
and from thence embarked for France.
He had no sooner quitted Dublin,
than it was abandoned by the papists in authority under him,
whereby the civil government was deserted;
and although measures were taken by the bishops of
Meath and Limerick to secure the peace of the city,
and King William`'s speedy arrival there secured it, yet anarchy overspread the country,
and left the defenceless inhabitants exposed to greater
danger and damage in many parts than ever.

The people called Quakers having generally kept their habitations, as before observed,
while they had any to dwell in,
were deep sharers in the calamities attendant upon this war.
Those suffered by William Edmundson are perhaps as severe as most,
at least of them we have the most particular account in the journal of his life,
written by himself, from whom, as a man of indisputable veracity and an eye-witness,
I have principally deduced my relation of the state
of this nation in this distressing season;
and the relation of his particular sufferings exhibits
a lively description of the violence of injury,
abuse and cruelty,
which afflicted the protestants and English settlers
during these times of tumult and civil war.

Inflexible virtue generally procures respect and confidence.
William Edmundson`'s protestant neighbours being mostly
driven by violence from their dwellings,
took shelter under his roof, until every room was full,
and brought their cattle which had escaped rapine
to his land as to a place of greatest safety;
but after the battle of the Boyne,
parties of the Irish army dispersing through the country with their
hostile disposition and riveted aversion to the English,
aggravated by their late disappointment and defeat,
set no bounds to their plundering and cruelty; so that the protestants in those parts,
after losing most if not all or their property,
were forced to take sanctuary in the neighbouring parish church (so called) at Rosenallis,
and other places more secure than private dwellings, to save their lives.
For it was now out of William Edmundson`'s power to
protect them or himself from rapacity or violence.
He saith, "`They plundered my house several times over,
and we were in jeopardy of our lives,
for they were wicked and blood-thirsty.`" In this extremity
of danger his family were forced to go out of the way,
and his wife was earnest in her solicitations for him to go aside also,
lest he should fall a sacrifice to their insatiable vengeance,
being willing to venture her own life to save his;
but he had not freedom to leave his habitation,
although now staying there at the risk of his life.
Yet through the protection of providence their lives were preserved,
but they lost all their household furniture, which the pillagers could find,
and thought worth carrying away, and all their horses that were left.

Now violence was let loose without restraint; no power to control,
no government they could apply to for redress.
The straggling parties of the Irish army, the bands of robbers,
and persons disaffected to King William,
gave the full swing to their vindictive tempers and avaricious rapine;
whilst the remaining protestants, defenceless and unprotected,
had only to submit in silent sorrow;
for it was a considerable time before any of the
English army came into this quarter to protect them,
and when they came were not very active in their protection.

In this emergency William Edmundson applied to the principal persons
amongst the Irish in their neighbourhood who stayed at home,
desiring them to recollect that they +++[+++and the protestants]
had lived together as peaceable neighbours, and wished they might do so still:
Though at present the English in this neighbourhood
lay exposed to the spoil of their countrymen,
yet they might easily foresee it would soon be like to come
to their turn to be obnoxious to similar sufferings;
for the English army being masters in the field would soon advance,
and probably revenge the wrongs of their countrymen upon them.
He therefore proposed to them a mutual interchange of good
offices towards each other with their respective parties;
that they should exert their endeavours to prevail upon their countrymen
to desist from robbing the English of the little they had left;
and that when the English army advanced,
the English protestants should use their influence and interest with them in their favour.
This proposal they seemed gladly to accept,
and promised with many oaths firmly to adhere to it on their parts.
But their promises and oaths appear to have been only a cloak of deceit;
no check was given to the nocturnal depredations of the rapparees,
scarce a night pasting but some of the English neighbours were robbed and wounded;
and when William Edmundson remonstrated to them,
and reminded them of the obligation of their sacred promise,
a deceitful plea of ignorance was all the satisfaction he got.

William Edmundson, actuated by the benevolent principles of true christianity,
which instruct us to love them that hate us,
and do good to them that despitefully use and persecute us,
did not look upon the violation of good faith in the Irish
as any plea to justify him in the like practice.
The most considerable family of the Irish in that
neighbourhood was those of the name of Dunn,
who being a powerful family among the natives, had they acted sincerely, might,
it is thought, have prevented much of the mischief perpetrated in that quarter;
but there seemed reason to suspect they encouraged it underhand, and shared in the spoil.
King William, soon after his entrance into Dublin,
published a proclamation of pardon to all the common people, who had served against him,
and declared that the Irish and others, who would live peaceably at home,
should not be molested; notwithstanding which,
as parties of the Scots and English advanced, they did retaliate upon them.
Two captains with a body of near three hundred soldiers
came into the neighbourhood of Mountmellick,
drove off abundance of cattle, and took some prisoners,
amongst whom was William Dunn and two of his sons,
one of whom they had stripped in order to hang him,
under suspicion of his being a rapparee.
In this reverse of their circumstances the Dunn`'s
sent with all expedition to William Edmundson,
to request his interposition, who immediately mounted his horse, rode after,
and overtook the party.
He reasoned closely with the officers,
as the persons that must answer for the violation of the king`'s late proclamation,
and for the reflection, which the permitting the army to plunder,
would bring upon his honour, and that of the English nation.
By his reasoning he prevailed upon the captains to relinquish the prey,
if the soldiers could be brought to consent.
These were greatly enraged, and ready to put all the Irish to the sword;
yet William at the hazard of his own life,
by venturing amongst them while exasperated at the thoughts of losing their booty,
so patiently reasoned the matter as, with the captains assistance,
to prevail upon them to give up the greatest part of their prey.
He also obtained the release of Dunn and his sons, with all their cattle.

It was not on this occasion only, but as often as exigency required,
that he was ready to interpose his good offices in favour of his Irish neighbours.
He often interceded with the English soldiers to give back the cattle they had taken,
and persuaded them to return part at least,
or bought them with his own money at a low price, and returned them to the owners.
He let their horses graze on his land, to screen them from plunder.
One might naturally imagine,
that such acts of extraordinary kindness would produce sensations
of respect and gratitude in the most savage tempers,
but it had not that effect upon those bigots;
they were as ungrateful for the good offices done them,
as they were faithless in the performance of those,
which they had solemnly promised to do;
and the only advantage William Edmundson reaped by his well-meant exertions
to serve them lay in the consciousness of acting from the purest motives.
