== Chapter IV.

[.chapter-synopsis]
* The Irish Army left under no strict Discipline plunder the Country
* The Half year`'s Meeting held in course, notwithstanding the perilous Season
* Friends in England contribute to the Relief of their suffering Friends in Ireland
* William Edmundson plundered
* The Times look more threatening, yet he is not free to leave his Habitation
* Colonel Bierly solicited for Protection, but treats the Solicitation with Neglect
* William Edmundson`'s House burned, and him self and his Sons taken Prisoners
* Sentenced to be put to death
* William Dunn takes them from the Rapparees to carry them to Athlone, where they are in danger from the Populace
* Brought before Colonel Grace, who releases them upon parole
* Shortly after which they are set at liberty
* William Edmundson`'s Wife stripped by Rapparees, contracts a Cold, from which she never recovered
* William Edmundson still in danger
* Account of George Gregson
* Ditto of John Burnyeat
* Termination of the War

When the campaign was over, the English army was dispersed into winter quarters,
and the number of rapparees increased greatly.
Lauzun, the French general, went back to France with the auxiliaries of that nation,
and Tyrconnel along with him, to solicit fresh aid.
So that their king,
their general and their governor having left the Irish army with arms in their hands,
under little or no strict government,
they also formed themselves into separate parties of free-booters or rapparees,
and burnt and plundered the country without mercy.
The English army in the mean time enjoying their ease in their quarters,
and not entirely desisting from imitating the rapine of the enemy,
gave little protection to the defenceless protestants,
who were now more dreadfully harrassed, terrified and abused than before.
This winter proved the accumulation of their sorrows.

The half-year`'s national meeting of the people called Quakers at Dublin approached,
and was held as usual in the ninth month (November) of this year,
to which friends from the sundry quarters of the
nation resorted with their usual zeal and diligence,
amidst surrounding perils, and were uncommonly refreshed together,
under an humbling sense of thankfulness to that divine power which
had graciously preserved their lives through so many dangers,
and given them this renewed opportunity of rejoicing
in seeing one another`'s faces again in safety,
of strengthening the bonds of gospel fellowship,
of inquiring into and receiving intelligence of the state and necessities
of their brethren in the different quarters of the nation,
and raising supplies to the utmost of their ability;
but through the repeated losses they had sustained by continual depredations,
numbers who before were affluent or comfortable circumstances
were reduced to penury themselves.
Yet those who resided in Dublin and other places
garrisoned with the English escaped better;
and it appears probable,
they were in a capacity to spare some of their substance for the relief of the sufferers,
and with this people the extension of relief to their friends
and others generally accompanied the capacity to do it.

As early as the half-year`'s meeting in 9mo last year,
the meeting for sufferings in London,
feeling for the distresses of their friends in Ireland,
had commenced a correspondence to inquire into their state,
and offer them their brotherly assistance, as far as occasion might require.
The said half-year`'s meeting, in reply, acknowledged their tender care,
but at that time declined the acceptance of their friendly offer;
the several provinces being as yet, notwithstanding their losses,
in a condition to administer the necessary relief;
but through the continued loss Friends in of their substance,
and general impoverishment of the members of this society,
by the to the relief violence of rapine,
they found themselves under the necessity of accepting
the benevolence of their brethren in England;
they drew first for 600£. and afterwards friends of England
remitted 150£. for the relief of friends of Ulster;
and 1060£. more was sent from London,
which in 1692 was distributed proportionally to each province.
A letter was then sent to friends of London, acknowledging their brotherly kindness,
and desiring them to stop any further remittances,
hoping upon the resettlement of the nation in peace,
to be able amongst themselves to contribute sufficiently
to the future necessities of friends in their nation.
So great and so universal was the near and sympathizing
affection subsisting between the members of this society,
that even from friends of Barbados 100£. was remitted
for the relief of their brethren in Ireland,
under their distressing sufferings.

By means of these aids, and by the protection of divine providence,
the friends in Ireland were mostly enabled to weather out the storm,
which seemed now at the height.
William Edmundson, during his attendance on the half-year`'s meeting,
received intelligence that the rapparees had carried off about twenty of his cows,
but that none of his family had received any hurt.
As soon as the meeting was over, returning home,
he had the satisfaction to find his wife and family well;
but the times looked still more gloomy and threatening; spoil and cruelty increased;
but although imminent dangers surrounded these parts,
he durst not yet move to a place of greater safety.
He was apprehensive that his removal might discourage his friends and protestant neighbours,
and perhaps induce them to flee from their habitations,
and thereby be in danger of perishing through want.
But although he had the faith to believe that one hair of his head
would not fall without the permission of divine providence,
his stay with them was to be but short.

Of this he seemed to have a foresight; for on the 23rd day of the same month,
about ten days after his return, he applied to Colonel Bierly, governor of Mountmelick,
and told him,
if he did not use some means to succour their quarter it would be to his own great damage,
for he expected every night that his house would be burnt down;
that if he gave way all the protestants thereabout would flee;
that then the rapparees might burn and destroy all the forage in the country,
and thereby distress himself and his garrison.
Bierly took little notice of his application, although the occasion was urgent;
for that same night William Edmundson`'s house was
beset by several hundreds of these banditti,
while the family were asleep, who fired vollies of shot through the windows,
which were heard in Mountmelick, two miles off.
Upon this several of the inhabitants, by whom William was greatly respected,
waited upon Bierly, desiring him to order out a party of men to his relief,
which he refused to grant.
Then (as William was informed) a lieutenant applied to him for a party of men,
saying that William was an honest man, and he would relieve him or lose his life;
but Bierly,
who would neither take any step to protect a respectable inhabitant from danger,
nor to relieve him when actually assaulted, answered the lieutenant,
that he would hang that man, that should stir out of the garrison.

The rapparees having set fire to the house, William capitulated upon terms,
to which they agreed.
But he surrendered to men, insensible to every obligation or religion,
conscience or honour.
They first fell to pillaging whatever the fire had spared or had not reached.
They left his wife without subsistence, having taken every head of cattle they had.
They took William and his two sons prisoners, bare-footed, bare-headed, and almost naked.
In this condition they took them in the night some miles through rough thickets, bushes,
mire and water, up to their knees, although in the winter season.
Their legs and feet were hereby much hurt and bruised.
When they came into a neighbouring wood, they held a council upon them,
and sentenced William to be shot, because he was a stout man;
and his two sons to be hanged.
William, who was naturally of an undaunted spirit, was not afraid to plead his cause,
even with these barbarians.
He told them, that many of them knew him and his two sons also,
and challenged them to prove that they had wronged
any of their countryfolk to the value of one farthing,
through all this time of civil disorder; but on the contrary,
that he had exerted himself to serve and save them to the utmost of his power;
sometimes with the hazard of his life amongst the English soldiers.
They acknowledged, they knew him to be an honest man:
Notwithstanding which they hoodwinked his two sons
to put their barbarous design in execution,
and having two fire-locks prepared to shoot them, they went about hoodwinking him also;
but he told them, they needed not, for he could look them in the face,
and was not afraid to die.

But just as they were about executing their cruel purpose, William Dunn,
a lieutenant in rappartes, the Irish army, and son to Captain Dunn beforementioned,
came up and took them from these rapparees, to bring them prisoners to Athlone,
the next Irish garrison, about twenty miles distant.
He expected to make a merit hereof with his superiors, and obtain some preferment.
After he had detained them three days in a poor cottage in cold and hunger,
he marched them to Athlone.
On the way they were met by Richard Dunn and his brother-in-law, who,
though so much obliged to William for his friendly services,
treated him with railing language;
could not repress the symptoms of their malignant joy at his present circumstances,
and in exultation told him they were going to burn Mountmelick,
and the rest of the country that had hitherto, escaped the flames.
William commiserated his neighbours, but could not help them;
but if this was their purpose, they were prevented from executing it.

When they arrived at Athlone, they appeared again in imminent danger of their lives;
a great number of the populace and soldiers gathered about them,
and at their head the high sheriff of the county, who stimulated them to mischief,
by loading these inoffensive persons with opprobrious epithets,
calling them rebels and traitors; so that it was admirable,
that they were not stabbed with the bayonets and skeins by the soldiers and rabble;
but that just then a person of genteel appearance made his way through the crowd,
and coming up to William, saluted him with respect,
and vindicated him from the sheriff`'s reflections, calling to him aloud,
"`I have known him above twenty years, and know him to be an honest man,
say what you will of him.`" This intervention of a stranger to William,
was the means of quieting the evil disposition of the sheriff and of the crowd,
which William esteemed as help raised in their great danger
from among themselves by the direction of divine providence.
He understood afterwards this man`'s name was Valentine Toole, a lieutenant in the army,
who also acquainted William that Dunn had informed against him.

After some little time they were brought up to the castle before Colonel Grace,
governor of the town, and his council of officers, to be examined,
before whom William appearing wrapped up in an old
blanket (almost his only clothing) the colonel,
not knowing him in this disguise, inquired of him his name and place of residence;
to which answering, I am old William Edmundson, the colonel, who knew him well,
and had been hospitably entertained by him, stood up,
and with tears signified his sorrow to see him there in that condition.
He then inquired of Dunn what he had against him, who advanced sundry false accusations,
which William refuted clearly to the satisfaction of the colonel and council.
At this the colonel grew angry with Dunn,
and expressed his resentment at his treatment of so respectable a person.
Dunn now, to excuse himself, said the rapparees were going to hang them,
and that he brought them thither to save their lives, upon which the governor declared,
that if he had them there he would hang them.

At Moate, a few miles from Athlone, lived John Clibborn,
who was not as yet driven from his habitation,^
footnote:[A meeting was settled at John Clibborn`'s,
who kept his habitation long in much danger;
and the meeting was kept up at this time with great difficulty,
lying only fix miles from Athlone, a chief Irish garrison,
and place of refuge for that party,
whence scouting parties often sallied to ravage the country,
and whither the rapparees usually carried those captives,
whom they were not permitted to murder, as they had done many.
Whilst the said J. Clibborn could keep his house, it was an asylum to friends and others.
Amongst these Anthony Robinson and John Millar, two of this society,
who resided about three miles from Athlone, after they had their houses plundered,
were threatened to be murdered with their families; but were rescued by a near neighbour,
wife to an Irish justice of peace, who took them into her house,
and kept them there till the band of robbers grew so insolent and
outrageous as to force their way into the house after them,
insomuch that despairing of their longer safety there,
she desired them to escape with their lives if they could.
She then conveyed them into her garden,
whence with much difficulty they escaped into a neighbouring wood,
where they lay concealed several days and nights in great terror and distress.]
and hearing of William`'s captivity in that town,
came to see him in his destitute condition, and supply him with provisions;
and afterwards, upon becoming surety for his appearance, if called for,
obtained the governor`'s consent to remove William and his sons to his house upon parole;
and shortly after they were set at liberty.

One of William`'s sons had a tanyard well stocked;
and about a week after the burning of their house, while they were in confinement,
William`'s wife thought it necessary to remove the
hides and leather to a place of greater safety;
and accordingly went, accompanied by several of their neighbours,
with horses and cars to assist in removing them.
While they were loading the prized by leather, etc.
Colonel R. Dunn and his brother-in-law aforesaid,
came upon them with a multitude of rapparees;
whereupon the neighbours fled for their lives, and left the horses, cars and loading,
which the rapparees seized and carried off.
But the old woman, not being able to escape, they stripped her naked,
and left her in that condition to walk home two miles in the month of December,
whereby she caught a cold of which she never recovered,
but died about seven months alter.
Dunn`'s egregious perfidy immediately met with exemplary vengeance.
For the next morning a party of twenty-five troopers
being sent from Mountmelick in pursuit of the plunderers,
to whom (I have heard) about eighty of the inhabitants joined themselves,
they came up with the said Dunn and several hundreds of the rapparees, whom they engaged.
Dunn and his brother-in-law, with many others,
were killed at the commencement of the engagement,
upon which the rest sought their safety in flight,
of whom a great number were taken prisoners, and safely brought off to Mountmelick.

After William had obtained his liberty,
and was returned back into the neighbourhood of his former residence,
he was not released from danger,
being still the object of the cruel machinations of his popish neighbours,
to whom he had been a peaceable neighbour and kind friend.
For so multiplied had the enormities of the bands of rapparees been through the winter,
that as soon as the English army could be drawn out of their winter quarters,
it was resolved to put a stop to their depredation by driving them over the Shannon.
And Major General Kirk, with part of the army,
marched to Mountmelick with intention to settle garrisons
in convenient places to protect the country.
Rosenallis was pointed out to him as a convenient place,
and information given him of William`'s sufferings and usage from the papists there.
Whereupon he sent for William and ordered him to attend him to Rosenallis,
which at the general`'s command he did.

In consequence of this, the popish neighbours,
who kept their dwellings thereabout under the protection of king William`'s proclamation;
and who, though they kept at home under this protection,
favoured and harboured the rapparees,
conceived a deep but concealed resentment against William Edmundson,
whom they causelessly suspected as the author of fixing a garrison there,
to overawe them from harbouring those plunderers,
and prevent their sharing in their plunder as heretofore.
Therefore fully to satiate their vengeance,
they procured eight or nine of the most determined of the rapparees,
to lie in ambush between Mountmelick, where he dwelt after his house was burned,
and Rosenallis, his former residence, where his land lay,
with a full determination to murder him.
To draw him into the snare, two of his neighbours came to him,
disguising their villainy under the mask of friendship,
and endeavouring to make his christian disposition
to serve them the instrument of his own destruction;
fawningly requesting him to go to Rosenallis to speak to the officers
of the garrison to be favourable to the inhabitants there,
as they centered their hopes of being well-treated in his friendly interposition.
But it was providentially ordered that he did not go that day.
Two days after they came again with the same pretence;
and now added that the soldiers were pulling down his out-houses,
which had escaped the flames, when his house was burned.
They used many arguments, under the treacherous veil of kindness and friendship,
to persuade him to go, but he writes, "`I was restrained by a secret hand,
that knew their evil design,
and would not suffer me to sail into their snare.`" The very next morning,
one James Dobson with his son and cousin passing that way,
these rapparees shot the son dead in the place, and took the other two into the woods,
and there barbarously murdered them.
Upon which they fled; and that night the popish inhabitants of this quarter,
conscious of the part they had acted, and fearing the punishment due to their crimes,
fled also to the rapparees for protection.

Many other friends, in common with every denomination of protestants,
were exposed to the like losses, perils and perfidy, in this calamitous time.
Others, who had stayed,
generally took refuge in the garrisoned places for their security;
but friends kept their places and habitations,
till they were driven therefrom by violence,
placing their faith and confidence in divine protection, which,
although permitting many of them to be tried with the loss of their substance,
miraculously preserved their lives;
so that we have no account of more than four that fell by the hands of violence,
and two of these forwardly exposed themselves to danger.

Besides the other trying calamities attendant upon
war at the return of the army to winter quarters,
a mortal distemper overspread the country,
which took off many of the inhabitants of every class and denomination.
Many also who had been driven from their houses, and lost most or all of their substance,
repining at this reverse of their circumstances, languished in sorrow till they died:
which friends were greatly supported over, in resignation to the divine will,
and quiet submission to the government of the sovereign ruler of the universe,
who not only giveth, but also taketh away.

This year George Gregson of Lisnegarvy (now Lisburn) in the county of Antrim,
departed this life.
He was born in Lancashire, and educated in the popish persuasion;
but was converted to the profession of the principles of the people called Quakers,
and was faithful to the principle he professed.
His conversion raised him many enemies,
and much aversion and envy amongst those whose communion he had deserted,
who propagated many false and malicious reports concerning him,
which he bore with patience;
and persevered with unshaken fortitude in the steady pursuit of peace of mind,
whereby growing in religious experience, he received a gift in the ministry.
His ministerial labours were effectually conducive to the
converting of many from the evil of their ways,
and opening their under standings to discover the way of life and salvation,
being favoured with good natural parts,
and a clear and agreeable manner of delivery in the
expression of his sentiments on religious subjects.
Great was his concern for the offspring of friends, and those newly convinced,
that they might not rest contented in a profession of truth,
received by education or tradition;
or in the comprehension thereof in their understandings;
but that they might be excited to press after the experience of the washing of regeneration,
and be renewed in their minds thereby.
He travelled in the exercise of his gift in Ireland and divers parts of England,
and was a sufferer for his religious persuasion, both by imprisonment and spoil of goods.
He retained his love to God and his brethren to the last period of his life;
and at his death left a considerable part of his substance to several meetings in Ireland,
and to friends in Lancashire.

In this year also the community at large, and friends of Ireland more particularly,
sustained a loss in the removal of John Burnyeat of Dublin;
whose travels and religious labours amongst his friends
and others have been recited in various parts of this work.
He was born in Cumberland, of parents of good repute, who gave him a good education,
suited to his circumstances and line of life.
He was religiously inclined from his youth, delighted in reading the scriptures,
and endeavoured from them to imbibe those virtues
and practices that conduce to solid peace of mind.
His solicitude to attain this important acquisition also led him to inquire after,
and apply to those teachers, who bore the character of men of religious experience,
for direction and instruction in the way to true peace;
but met not with that satisfactory intelligence,
whereby he could attain the desire of his soul,
being more built up in the fashionable speculations of the age about religion,
than instructed in the internal work, whereby the heart is purified and changed.
When George Fox came into the parts where he resided,
he with many others were recommended to an instructor near at hand,
the true light that enlighteneth every man that cometh into the world.
John Burnyeat was convinced by his doctrine in the year 1653.
And by turning the attention of his mind to the instruction of this internal monitor,
and the discovery of this true light,
he clearly perceived the emptiness of his former high profession,
and the danger and hazard of depending upon the imputed righteousness of Christ,
whilst he lived in sin (a notion greatly prevailing amongst many high
professors in those days) for he was now convinced that the guilt remained,
while the body of death, leading by its power into actual sin, remained.
Seeing the necessity of regeneration and holiness,
he endured many deeply exercising conflicts with
the corruption and infirmities of his heart,
till in the due time, by the assistance of divine grace, victory over them was obtained;
and sanctification in a good measure perfected in him.

Being thus properly prepared for the reception of the gifts of the spirit,
he was soon called to the work of the ministry;
in the discharge whereof he was not slothful in business; but fervent in spirit,
serving the Lord, both in his native country, and in many foreign regions,
where his friends were settled, to the convincing of many,
of the truth which he published,
and the confirmation and establishment of many in the way of righteousness and peace,
as hath been variously related in the course of this work.

Amongst his contemporaries he was greatly beloved,
and highly esteemed for his many excellent qualities and services amongst them,
from whom we have received the following character of him as a minister,
a christian and a man.
His depth in religious experience, through the effectual work of sanctification,
and discovery of the mystery of the kingdom of heaven,
through the illumination of the spirit of truth, qualified him,
like the good householder in the gospel, to bring out of his treasury things new and old,
for the edification of those to whom he ministered.
He was far from being rash with his mouth, or hasty to utter any thing before God;
frequently waiting a considerable time in awful silence and diligent attention of mind,
for the renewed feeling of the word, which is quick and powerful,
to animate his doctrine with the fresh savour of life before he stood up to minister,
in order that his ministry (delivered with a natural unaffected eloquence,
in the demonstration of the spirit,
and not in the oldness of the letter) might be effectual to reach
the divine witness in the consciences of his auditory.

Through this reverent attention, he was endowed with skill to divide the word aright,
and administer consolation to the sincere and disconsolate believers;
encouragement to the diffident; instruction to the young and inexperienced;
and reproof to the insincere members,
who disturbed the peace of the church by a spirit of contention,
or dishonoured its character by licentious manners,
inconsistent with the purity of its principles.

He confirmed his ministry by his example, his conversation,
being adorned with the christian virtues of humility, charity, meekness, patience,
gravity and temperance, in a conspicuous degree;
his natural temper was kind and benevolent; his constitution hardy,
his resolution undaunted and persevering, in the discharge of manifest duty,
which was put repeatedly to the trial,
by his sharing in persecution in common with his brethren of that age.

His first imprisonment was in Carlisle in 1655, at the instigation of one Denton,
priest of Brigham in Cumberland, who promulgating in his sermon many false charges,
bitter invectives and groundless calumnies against
the people called Quakers in John`'s hearing,
after he had finished it, John spake to him what was in his mind;
to which the priest made little answer;
but after his hearers had rudely assaulted him with their bibles and staves,
till he was sore with bruises to a degree, which affected him for some time,
the priest commanded the constable to secure him, and a friend, who accompanied him,
and next day had them before Launcelot Fletcher, who committed them to the county jail,
where John was detained twenty-three weeks.
He was next imprisoned at Rippon in Yorkshire in 1662.
Coming in the course of his religious travels to this town,
and understanding that many of his friends of that place
were in prison for meeting together to worship God,
he thought it his duty to pay them a brotherly visit;
and for uttering some words of exhortation and encouragement to them,
the jailer took him before the, mayor,
who had in company with him the chancellor of the diocese and several aldermen.
The chancellor took upon him the office of chief magistrate in examining him,
and sought to ensnare him in his words,
that he might extort an occasion to commit him to prison;
but when he could not get the advantage, at which he aimed by these means, he grew angry,
and, in order to attain his ends, was forced to resort to the usual snare,
by causing the oaths to be tendered to him,
and upon his declining to swear he was committed to prison with his friends,
who were twenty-four in number.
Some time after the magistrates assembling in a bowling green, contiguous to the prison,
for the diversion of bowls, during the time of the meeting for worship,
which the prisoners kept up daily,
they overheard John Burnyeat concerned in exhortation or prayer,
and being provoked thereat, they commanded him to be put down into the dungeon,
a place without light or air, where he was detained at this time two days and two nights:
But still, when released from his dismal cell,
feeling the impulse of duty at times to exercise his ministry
for the edification of his friends in prison,
to release themselves from the mortification of hearing his preaching, they released him,
and sent him away, after fourteen weeks causeless imprisonment.
In 1670, upon the new conventicle act coming in force,
he was fined 20£. for preaching at Devonshire house, London, by Sir Samuel Starling,
mayor,
and about two weeks after committed to Newgate by the same magistrate for the same cause.
Again being informed against for preaching at Machynlleth in Montgomeryshire, his mare,
saddle and bridle, value 8£. was taken from him, and he left to travel on foot.
But the informers were disappointed of the best part of their spoil,
for the mare died in the possession of those who took her about an hour after.

We have seen that he devoted the prime of his life to the service of his Maker,
and promoting righteousness in divers parts of the earth,
being engaged very much in travelling in the exercise
of his gift till past the state of middle age,
when (in 1683) he married and settled in Dublin, in which city,
as well as other parts of Ire land, by his steady, circumspect and exemplary conduct,
and his powerful ministry, he was a very serviceable member of religious society,
and obtained a great place in the affection and esteem
of his friends and neighbours here,
as he had done before in his native country.

After his settling in Dublin his travels and service
were mostly confined to the different parts of Ireland,
only in the year after his marriage (1684) he visited
Scotland and the northern counties of England.
In the year 1688 his wife died, and after her death he had an inclination to return,
and spend the remainder of his days in his native country;
but the prospect of approaching war, and its concomitant evils,
which terrified numbers of the protestant inhabitants to flee to England,
had the contrary effect upon him;
for when the face of affairs began to look dismal and menacing,
he felt no liberty to pursue his intention;
but found it his place to stay and take a share in the sufferings
which might be permitted to befal his friends,
amongst whom he was very serviceable in strengthening and comforting them
under their severe afflictions in these perilous and calamitous times.
Twice, for this purpose, during the time of the war,
he visited the meetings of friends in the provinces of Leinster and Munster,
where he had large meetings;
for in many places the teachers of other denominations had fled and left their flocks.
As soon as the way was open, he paid a like visit to friends in the province of Ulster,
amongst whom he had acceptable service,
and was greatly comforted in finding them in a state
of patient acquiescence under their sufferings.

Soon after his return from this northern journey
he went to the province meeting at Rosenallis,
and whether it was at this or some other in this year,
that he delivered the following prophetic warning, is not clear,
but it is recorded of him, that at a province meeting in 1690,
he declared to his friends,
"`It is now a time of great trial upon you in losing all your substance;
but the time will come when you will be as greatly tried
with getting wealth,`" which was soon accomplished.
From Rosenallis he proceeded to Mountrath,
Ballinakill and the monthly meeting at New Garden,
and from thence went home with John Watson, where he fell ill of a fever,
which in twelve days put a period to his life.
During his illness he was preserved clear in his understanding,
and in a fine frame of spirit,
being borne up over the fear of death by the testimony of a good conscience,
in the solacing review of the integrity and virtue of his past life.
Expressing his lively hope, "`That he ever loved the Lord,
and the Lord loved him from his youth,
and that he now felt his love.`" He was sensible to the last,
and so laid down his head in peace with God,
in love to his brethren and good will to all mankind, in the fifty-ninth year of his age,
and was buried at New Garden; his funeral was attended by many friends and others,
upon which occasion William Edmundson bore a lively and affecting testimony
in commemoration of his eminent and faithful services.

The campaign of 1691 put the finishing stroke to the wars and the troubles in Ireland.
King William at the close of the last campaign returned to England,
and General Ginkle being appointed to the command of the army, took Athlone,
gave the Irish army a total defeat at Aughrim and took the city of Limerick,
which capitulated upon articles, whereby the war was brought to a termination,
and the peace of the nation restored.

The people called Quakers, upon the restoration of peace,
through the recollection of the precarious tenure they had of their secular possessions,
during the continuance of the war, were, as yet, so loosened in their attachment thereto,
and the sympathetic benevolence of their hearts to each other so increased, that those,
who had something left, "`were ready to communicate to their indigent friends.

Those who had been driven from their habitations generally returned to repossess them;
and the succeeding national meeting took care, that in every quarter,
friends should be supplied for the present with such necessaries
as the time and their abilities could afford;
and that in resettling a competent number might settle near together,
so as conveniently to constitute a meeting for divine worship,
for their mutual edification,
and the reciprocal benefit of themselves and their families.

And it is remarkable, that through the whole of this season of danger and tumult,
they kept up their meetings for worship and discipline in their accustomed
manner without much interruption or disturbance from either party;
although, as before remarked, they often went to distant meetings through great perils,
by reason of the rapparees,
who in many places beset the roads in ambush to rob
and murder the passengers on their way;
but they resorting to their meetings in faith, and under persuasion of duty,
were mercifully preserved, and their fidelity rewarded with inward consolation,
peace of mind, and an increase of spiritual strength:
And they gained ground in religious experience,
in the number of their members and in the public esteem, through their innocent,
steadfast and sober deportment in the fear of God.
