== Chapter VIII.

[.chapter-synopsis]
* The Case of George Keith brought before the Yearly Meeting
* The judgment and Advice of the Yearly Meeting thereupon
* George Keith`'s Endeavours to make a Party in England frustrated
* Thomas Elwood writes an Epistle of Caution to Friends, against which George Keith complains
* The Yearly Meeting of London disowns him
* He sets up a separate Meeting at Turner`'s-hall
* Summons Friends to a Meeting there
* Which they think Improper to comply with
* Their Reasons
* He publisheth his Account of the Meeting
* Which is answered by Thomas Elwood
* An anonymous Publication, entitled "`The Snake in the Grass.`"
* Answered by George Whitehead and Joseph Wyeth.

George Keith having arrived in England in the spring of 1694, attended the ensuing 1694.
yearly meeting of London;
and a full account of the trouble he had given friends in America
being sent over in an epistle from the yearly meeting of Philadelphia,
specifying very particularly all his contentious proceedings
therefore the grounds of their disowning him,
after repeated meeting,
labours to bring him to a better way of thinking and acting proved ineffectual,
and his and his partisans setting up a separate meeting,
whereby this difference coming regularly before the meeting,
the epistle being in course read therein, George Keith desired to be heard,
and it was agreed to enter upon hearing and inquiring into the
cause of difference between him and friends of Pennsylvania,
after the other business of the meeting was over.
Then they patiently spent near ten days in reading books and papers relating thereto,
and hearing George Keith and his party on one side,
and Samuel Jennings and Thomas Ducket on the other,
with Thomas Wilson and James Dickenson, just returned from their travels in America.
They used earnest endeavours to reconcile the difference,
and prevail upon George Keith with his party to return
into unity and amity with their friends;
but Keith seeming predetermined either for carrying everything his own way,
or for a separation, eluded all endeavours for reconciliation and peace.
The more tender reasoning and earnest entreaty was extended towards him,
the more perverseness he discovered in turning it to a wrong end,
and strengthening himself in contention and opposition.

The yearly meeting having fully heard and considered the circumstances of the difference,
at last came to this judgment.
That the separation lay at George Keith`'s door,
and that he had done ill in printing and publishing those differences as he had done;
and therefore the advice of the thereupon, meeting to him thereupon was,
to call in those books of his,
or publish something innocently and effectually to
clear the body of the people called Quakers,
and their ministers, from those gross errors charged on some few in America,
and retract the bitter language in them, so far as he was concerned,
and sincerely to use his utmost endeavours with his friends to remove the separation.
Which judgment and advice being drawn up in writing, was in the meeting delivered to him,
and soon after printed by one of his party, with very invidious reflections upon it,
in a small pamphlet, entitled A true Accounts, etc.
Thus, instead of taking the advice of the yearly meeting, he persisted in his opposition,
and his endeavours to cause a rent in the society, and form a party to himself;
but his behaviour was so exceeding rude and passionate,
that the weakest could not but discern, he was actuated by an intemperate spirit,
which frustrated his views of forming a party in opposition to the body of friends here,
as he had done in America; so he could gain few adherents,
except some of the former separatists about London,
who yet soon grew dissatisfied with him, and left him.

In Pennsylvania having (as we have seen) secured the principal printing-press
under his own direction and control he could publish his calumnies,
and justify his own cause without fear of reply or reproof;
but in England the case was altered; for here were sundry members of the community,
who wanted neither the capacity nor opportunity of following him from the press,
clearly to answer all his cavils, and confute his calumnies; George Whitehead,
Thomas Elwood and Benjamin Coole exercised their pens for these purposes.

Thomas Elwood in particular, observing the pernicious tendency of his procedure,
in the epistle of first place wrote an excellent epistle to friends,
briefly commemorating the mercies of the Almighty,
and warning them to beware of that spirit of contention
and division which had appeared of late in George Keith.
Which epistle when finished he submitted to the second day`'s morning meeting,
by which it was fully approved in a full meeting, and he left at liberty to publish it.
And yet George Keith pretended it was printed in great disunity,
and against the mind of many friends, insinuating that it was promoted only by a pasty;
an evidence of his disposition to divide the society into parties,
and to hesitate at nothing that might forward his views.

Against this piece of Thomas Ellwood`'s,
against George Keith made a heavy complaint to friends, and wanted it to be called in,
as highly injurious to him.
That it might be injurious to his cause admits of no doubt; but himself,
by his late conduct, had made his cause distinct from,
and opposite to the cause of the society,
and could have no reasonable grounds to expect they should so far counteract their own,
which appeared to them a good one, to strengthen his,
which they saw in a very different light.
Therefore his complaint and clamour were disregarded, by friends,
who saw no reason to stifle a piece coinciding with their own sentiments,
and which on that account they had approved; to gratify the unreasonable demand of a man,
who was at the same time contemning their advice to him.
He would call in none of his petulant productions,
nor retract his unjust representations, at their desire;
but went on printing and publishing his own partial
accounts of all transactions between them,
insinuating that the advice he had received was not the advice of the yearly meeting,
not that the yearly meeting which gave it,
still aiming to represent them divided into parties.
The succeeding yearly meeting observing this,
treated further with him upon this disingenuous representation,
renewed their endeavours to make him sensible of the wrong he had done them and himself,
in order to bring him to a temper of mind to perceive and acknowledge it;
but the more cordial endeavours they used,
the more obstinate and positive he grew in his opposition,
and in his justification of his own cause.
After hearing him patiently '`till he withdrew of his own accord,
the yearly meeting at large,
to take away all grounds of again representing it as the work of a party,
drew up the following testimony:

[.embedded-content-document.testimony]
--

That the said George Keith hath of late been, and yet is,
actuated by an unchristian spirit,
which hath moved and led him to stir up contention and strife in the church of Christ,
and to cause divisions, separations and breaches among them that profess the truth;
and that the tendency of divers of his late writings and actings hath been to
expose the truth and the friends thereof to the reproach of the world,
did unanimously agree, and declare it to be the sense and judgment of this meeting;
and it is the sense and judgment of this meeting,
that the said George Keith is gone from the blessed
unity of the peaceable spirit of our Lord Jesus Christ,
and hath thereby separated himself from the holy fellowship of the church of Christ;
and that whilst he is in an unreconciled and uncharitable state,
he ought not to preach or pray in any of friends meetings,
nor to be owned or received as one of us,
until by a public and hearty acknowledgment of the great offence he has given,
and hurt he hath done, and condemnation of himself therefore,
he gives proof of his unfeigned repentance,
and does his endeavour to remove and take off the reproach,
he hath brought upon truth and friends,
which in the love of God we heartily desire for his soul`'s sake.

--

He now set up a separate meeting at a place called Turner`'s-hall.
The novelty excited the curiosity of the people,
and at first attracted a meeting at crowded audience,
mostly of such as were of unfriendly dispositions to the people called Quakers.
At the same time he proceeded to write against them,
but was so closely answered and pinched by quotations from his former writings,
being unable to reply to purpose, or with any degree of consistency,
that under pretence of inability to bear the expense of printing, he shifted his ground,
and set up a kind of judicial court by his own authority, on a day of his own appointing,
at Turner`'s-hall aforesaid; giving notice by public advertisement,
that he intended in the 4th month to hold a meeting at Turner`'s- Summons hall,
for the purpose of pointing out the errors of the Quakers,
and summoned sundry of them by name, and others in general,
to attend and answer for themselves:
But the friends looking which they upon his assumed authority as an imposition,
did not think proper to take notice of his challenge: Yet lest any,
who might attend upon the occasion with might mistake the cause of their not appearing,
as proceeding from consciousness of inability to make a proper defence,
they drew up the following reasons for absenting themselves,
and sent them to be read there.

[.embedded-content-document]
--

Whereas George Keith hath, after his wonted irregular and unruly manner,
challenged diverse of us to defend ourselves against such
charges as he has to exhibit against us at Turner`'s-hall:
These are to certify to all whom it may concern,
that the reasons why we decline any such meeting are as follow:

[.numbered]
_First._
Because the said George Keith has given us such frequent
proofs of his very passionate and abusive behaviour,
at the many more select meetings we have had with him, in all manner of sweetness,
long-suffering and patience on our side, to satisfy and preserve him from these extremes:
That we cannot assure ourselves now of any better entertainment,
or that the meeting can have any desirable success; for a thorough information.

[.numbered]
_Secondly._
We decline to meet because it is not an agreed meeting on both sides,
which it ought to have been, and where that is not, or cannot be adjusted,
the press is the next fair way and expedient,
which he has begun with and now seems to decline;
nor hath he sent us a copy of his charge of indictment against us,
which also he ought to have done.

[.numbered]
_Thirdly._
That he has two of bur books which lie hard at his door,
in vindication of us and doctrines from his exceptions,
and which he has not yet answered; so that he is not on equal terms with us;
and therefore we think his challenge, appointment and summons unfair;
and that all that are not partial will be of the same mind with us.

[.numbered]
_Fourthly._
Such public and unlimited meetings, are too often attended with heats,
levity and confusion, and answer not the end desired by sober and inquiring men.
Besides, that it sets up a practice,
that authority may judge to be an abuse of our liberty,
and so draw that under reflection, as no friend to the civil peace.

[.numbered]
_Fifthly._
We know not what religion or persuasion this wavering man is of,
or what church or people he adheres to, or will receive him, with his vain speculations,
that have led him to desert us; nor who are accountable to us for him,
and his irregularities and abuses;
the generality of such assemblies usually making ill auditors, worse judges,
and no good security for our satisfaction.
And we must therefore take leave to say,
it seems to us an indirect way of disquieting and invading our present liberty,
that so irreligious a meeting should be held,
whose end is abuse other men for their religion,
if this should be imitated by all the several sorts
of different persuasions in this city,
what heats and confusions must necessarily ensue!

[.numbered]
_Sixthly and lastly._
Wherefore be it known unto all, that for the sake of religion, the liberty granted us,
and the civil peace, we decline to meet him;
and not from any apprehensions we haye of his abilities,
or our own consciousness of error, or injustice, to the said George Keith,
whose weak and unbridled temper we know is such, that what learning and parts he hath,
have not been able to balance and support him on less occasions,
so that we may say they are in ill hands; and if he proceeds as he begins,
they will be employed to an ill end, which his (poor man!) cannot but be,
unless he change his course; which we heartily pray for,
that a place of repentance he may find; and through a true contrition,
the remission of his great sin of envy, and evilly entreating the Lord`'s people and way,
which we profess,
and which he the said George Keith hath long and lately
both professed and zealously vindicated as such.

--

George Keith soon afterwards published his narrative of
the proceedings at this meeting of his own appointment,
with the usual prejudice of party animosity,
which was answered by Thomas Ellwood in a piece,
entitled An Answer to George Keith`'s Narrative of his Proceedings at Turner`'s-hall,
wherein his Charges against divers of the People called Quakers are fairly considered,
examined and refuted.
In which he made his title good in a clear and entire
refutation of his cavils against friends`' books,
manifesting his disingenuous perversions of their sense to answer his own partial purposes,
by unfair or false quotations, by partial selection of passages curtailed and mutilated;
and by putting his own constructions upon them,
to wrest from them a meaning never thought of by the writer,
in order to render them unsound or contemptible;
against which Thomas Ellwood defended the soundness of their doctrine,
showing George Keith`'s inconsistency and self-contradiction in condemning opinions,
which he had publicly vindicated as orthodox on various
occasions for a series of near thirty years;
and pretending to hold the same doctrines and principles still,
and detecting his deceit and prevarication so plainly and effectually,
that George Keith never replied to it.

He seems to have at last grown tired of a controversy, in which,
while he made loud clamours of the vile errors held by the Quakers,
he found his own unretracted doctrines compared with
theirs were the same or of the same import,
and that no palliatives could screen him from the detection of his palpable inconsistency,
he therefore declined any further appearing in print
against Thomas Ellwood in his own name:
But either by his procuration,
or from the spontaneous effusion of a similar disposition in himself,
he met with a confederate equal in malice,
against whom the advantage of quoting his own writings would not lie.
This author, in an anonymous book, under the title of The Snake in the Grass,
proceeded in the line, George Keith had chalked out,
but not being under the like titled restraint, outwent him, or most that went before him,
in virulent reflections,
raking every kennel for dirt to throw at the people called Quakers.
This piece was published without a name,
but was afterwards found to be the work of one Lesly, an highflying nonjuring parson,
to whom of course the name of a dissenter was odious,
and his spleen not satiated with hating them himself,
he exerted the talents he was master of to render them odious to the world;
but this most bitter, illiberal and unjust production must,
with all impartial and judicious readers,
have fixed a deeper stain on the authors reputation, than on the people he vilified.

As he listed himself a volunteer in George Keith`'s cause,
it afforded ground for a suspicion that George Keith
was not unconcerned in promoting the work,
if not a co-adjutor therein,
for being now rejected and disowned by the people called Quakers,
and frustrated in his endeavours to draw a party to himself from among them here,
or attach any considerable number of others to himself as a leader,
he began now to ingratiate himself with some of the ecclesiastics of the church of England,
who were inclined to countenance him for his opposition to the Quakers (so called).
The author of the Snake,
in his preface plainly implying that it was in George Keith`'s cause he took up his pen,
and in reply to Thomas Ellwood`'s examination of his narrative,
by saying it was not meant as a defence of George Keith,
any further than he defended the truth of the christian faith, for which reason, says he,
"`I have wholly omitted all the reflections cast upon him,
and the contradictions which Thomas Elwood pretends to find in
his former books (while he was a Quaker in their communion) to
the doctrine he now sets up in opposition to them.`"
Thomas Ellwood, not without probability,
conjectured that this book was published by the procurement of George Keith,
who had himself for a long series of years maintained for truth those doctrines
and practices which he would now represent as errors in the Quakers,
and was pinched in the controversy by quotations of Keith against Keith;
that this anonymous publication was a contrivance to get clear of this dilemma,
in which he found himself entangled.

As to this envenomed performance it was remarked,

[.embedded-content-document]
--

[.numbered]
1+++.+++ That the matters therein charged upon us,
are generally the same that have been charged on us heretofore, by Faldo, Hicks,
and other adversaries; and always refuted over and over, both formerly and of late.

[.numbered]
2+++.+++ That the things they charge on us as errors and heresy,
are not pretended to be proved by any plain express positions or assertions of ours;
but from our adversaries own perverse meanings, and wrested constructions of our words,
always denied and rejected by us.

[.numbered]
3+++.+++ That the words and passages brought by our adversaries
for proof of their charges against us,
are not taken out of our doctrinal treatises, or declarations of faith and principles;
but (for the most part) out of controversial books; wherein, ofttimes,
the scope and aim of the author is,
not so much to assert or express his own principles or doctrines,
as to impugn and expose his adversaries, by showing the contradictions, absurdities,
and ill consequences of his adversaries opinions; from whence,
positively to conclude the author`'s own judgment, is neither safe nor fair.

[.numbered]
4+++.+++ That however any of our former adversaries might
have been misled in their judgments concerning us,
George Keith, who hath now moved this controversy against us, knows full well,
that we do not hold those things either generally as a people, or as particular persons,
which he has charged on us as errors.

--

Besides this,
as George Keith had done before in his quotations and references to their writings,
he stuck at no unhandsome nor unfair means to represent this people in the most ridiculous,
absurd and disadvantageous light.
He mutilated their expressions by omitting the leading or concluding parts of a sentence,
or passing over some in the middle,
whereby in most cases they made sense quite different from the author`'s intention.
To this he added many stories of occurrences, which, he said,
had happened among the Quakers;
some of which were plainly proved to be fictitious and without foundation in fact;
others greatly exaggerated, and the actions of several,
who were disowned and disclaimed by them,
were raked up and imputed to this body of people.

Among this author`'s untruths this was one,
that the Quakers in their schools did not suffer the children to read the holy scriptures;
which was evidently returned upon him as a palpable falsehood,
by a certificate of the French usher at Wandsworth, who was no Quaker;
and another signed by several neighbours, persons of character and consideration,
who testified that the bible was daily read in this school (which
was a very large boarding school kept by Richard Scoryer,
a friend) in a regular course of succession from the beginning to the end.
This book, entitled the [.book-title]#Snake in the Grass,# did not pass unnoticed.
The author`'s misrepresentations were laid open, his fabulous tales disproved,
and his crafty imposture clearly manifested in suitable
replies by whitehead George Whitehead,
and by Joseph Wyeth, in a book under the title of [.book-title]#A Switch for the Snake.#
