== Chapter VI.

[.chapter-synopsis]
* George Keith removes to Pennsylvania
* Is appointed Master of a free School established there, which he soon quits
* Account of George Keith before his Removal to America
* Further Remarks concerning him
* He lets in an aspiring Mind
* Friends concerned to caution him
* He discovers an open Dissent
* Begins to quarrel, first with Thomas Fitzwalter and William Stockdale
* Complains against them to the Monthly Meeting
* Friends in England, hearing of the Difference, write a Letter of Advice
* Their Counsel slighted by George Keith
* He treats Thomas Lloyd and other Magistrates with illiberal Language
* He reflects upon the Meeting of Ministers
* Testimony of the Monthly Meeting against him
* Presented by the Grand jury and fined
* Magistrates`' Vindication
* Thomas Wilson and James Dickenson arrive in Pennsylvania
* Extract from Thomas Wilson`'s journal
* George Keith`'s Departure for England

George Keith, to whom Christopher Taylor aforesaid had resigned his school at Edmonton,
did not keep it up long, but had also in the intermediate time removed to Pennsylvania.
And about this time friends of Philadelphia,
considering the advantages of a good education,
had it in contemplation to establish a free-school in Philadelphia;
and looking upon George Keith, now a resident there,
as a person well qualified to conduct such an undertaking,
they pitched upon him for master of this school, and engaged him on the following terms:
That he should have a salary of 50£. for the first year, a house for himself and family,
and a school-house provided, and the profits of the school beside;
for two years more his school was to be made worth 120L per annum,
if he should choose to stay so long;
in consideration of which advantages he which he was to teach the poor children gratis.
He continued in this station only about a year, and was succeeded by his usher,
whose name was Thomas Makin.

George Keith`'s conduct seems, at this time,
to betray symptoms of a very unstable and wavering temper of mind;
he soon grew weary of every circumstance of life,
especially such as was attended with labour and confinement.
Christopher Taylor, we see,
resigned into his hands a well-established and profitable school,
which after no long time he quitted; removed first to London, and soon after to America.
Here the strenuous exertions of his friends to make so handsome a provision
for him as their school-master in the infant state of their colony,
evince the cordiality of their regard, and generosity of their disposition toward him,
and that they were desirous to make his residence amongst
them easy and comfortable to the utmost of their power.
Under these circumstances, one might imagine,
he might have enjoyed ease and satisfaction to his full content,
if free from uneasiness in his own mind;
but he who carries the source of unhappiness within himself,
is not like to find happiness in any circumstance of life.
He seems to have given a loose rein to an unsettled and dissatisfied temper,
which occasioned himself much hurt and friends much trouble, first in America,
and afterwards in England.
In order to convey a more satisfactory intelligence of the misunderstandings
and separation which soon broke out between him and friends in America,
it may not be impertinent to recapitulate the successive
passages of his life previous thereto,
as far as my materials enable me.

George Keith was a native of Scotland,
where he received a liberal education in the national profession or kirk of Scotland,
not only at school, but also at the university of Aberdeen.
By whom he was convinced,
or by what means he joined in society with the people called Quakers, I am not informed,
but I find that in the year 1664,
he came as a minister from the south of Scotland
on a religious visit to his friends at Aberdeen,
and was detained in prison there ten months,
and Patrick Livingstone with him seven months,
where they were violently beaten and abused by one Peter Strachan,
son to Andrew Strachan, priest in Kintore, who was confined in the same prison;
for which he fell under great trouble of mind,
under the sense of his wicked and abusive behaviour to them,
fearfully crying out that the judgments of God were upon him,
and repeatedly begging their forgiveness before many witnesses.

In the next year,
being under a religious concern to bear his testimony
to the truth in the great steeple-house at Aberdeen,
in attempting that service he was violently assaulted,
and knocked down to the ground by James Home, the bell-ringer.
Shortly after which it was remarked that the said
Home going up the steeple to ring the bell,
suddenly fell through a hole above four stories high,
and was instantly killed by the fall,
upon the same spot of the pavement where he had beaten George Keith.
We find him afterwards amongst the number of this persecuted people at Aberdeen,
involved in confiscations and long imprisonment.

He was not only a sufferer in common with his brethren
in testimony to the truth of his profession;
but exerted his talents in defence thereof both in verbal disputations,
and in print on many occasions.
He first joined Alexander Jaffray in confuting a virulent invective
of George Meldrum in his sermon against the Quakers in 1666.
He was coadjutor to Robert Barclay in the dispute he had with the
students of Aberdeen in defence of his Theses in 1675.
He was likewise engaged, together with Stephen Crisp, George Whitehead and William Penn,
in a dispute with the baptists in London the preceding year.
He also wrote and published several treatises in vindication
and explanation of the principles of the people called Quakers,
viz. One upon revelation;
another under the title of [.book-title]#The Universal Free Grace of the Gospel Asserted.
The Way to the City of God.
The Benefit, Glory and Advantage of Silent Meetings, 3tc.#

In 1682 he was informed against for preaching,
and teaching school at Edmonton without license, the quarter sessions for Hertfordshire,
upon which the justices tendered him the oath,
and upon refusal to take it committed him to jail.
In the year 1684 he was again imprisoned in Newgate, London, for refusing to swear,
and continued a prisoner above five months.

Thus for the greatest part of thirty years had he retained full unity with the society,
and not the lowest degree of estimation for his service amongst them,
during which time he never pretended to discover
any errors or false doctrines maintained by them,
though he had the fullest opportunity; but on the contrary publicly vindicated them.
Yet not duly attending to the apostle`'s caution to the Colossians,
"`beware lest any man spoil you through philosophy and vain deceit,
after the traditions of men, after the rudiments of the world, and not after Christ,`"
affecting to be wise beyond what is written or revealed, he became wavering in mind,
and was shaken from his steadfastness in the faith.
Having indulged him self too much in curious, uncertain and unprofitable speculation,
that inward watchfulness which is necessary to keep the heart clean and pure,
the passions in subjection, and the life and manners upright and pacific, was suspended.
He is said to have imbibed some fanciful notions of Van Helmont about the year 1682,
concerning the transmigration of souls, the resurrection,
etc. which the people called Quakers have never though
it necessary to be curiously inquisitive about,
as not believing subjects, above the investigation of human reason and knowledge,
to be necessary to salvation, further than they are clearly revealed in the scripture:
And looking upon the things which are clearly revealed, to belong to us,
and to be sufficient for salvation,
have avoided to pry into the secret things which belong to divine omniscience.
Finding no room for the propagation of such notions amongst them,
he is supposed to have let in some secret jealousy and contempt,
which afterwards broke out in open opposition and contention; first with individuals,
and afterwards with the body at large.

The first symptom of loss of spiritual strength was
discovered in his impatience under suffering.

After he had taken up Christopher Taylor`'s school at Edmonton,
and was imprisoned at Hertford, he removed to London,
and sought a privileged place to reside in:
but finding this not sufficient to protect him,
being taken and imprisoned in Newgate as above,
seeing himself so closely pursued and molested in
his lawful occupation by the spirit of persecution,
as yet retaining power to be vexatious to the non-conforming subjects;
and his steadfastness of faith in divine protection being weakened by airy speculation,
and reasoning with flesh and blood, he complained now,
that as nothing but persecution was to be met with here,
he would seek an asylum in a land of liberty;
under which disposition he removed to America.

The apostle hath left this cautionary reflection on record as a
warning to christians of all denominations and generations,
"`Knowledge puffeth up; but charity edifieth.`" And in this man we have an instance,
that as we suffer ourselves to be puffed up with our knowledge,
we are in danger of losing that charity, which excelleth all gifts and attainments.
George Keith was a man of good natural abilities, improved by a liberal education,
clear in comprehension and fluent in expression,
which gave him in these respects a superiority over many,
or the greater part of his brethren,
and would have been the means of continuing his estimation as an useful member,
if he had not been himself too conscious of this superiority,
and thereby let in an aspiring mind, aiming at preeminence amongst them,
which when he could not attain, he transgressed the bounds not only of christian charity,
but of common decency.

It is remarkable that it was soon after the removal of George Fox,
that symptoms of self-importance began to discover themselves in George Keith`'s conduct,
which suggests a conjecture,
that he might not be without a secret apprehension of his own fitness
to succeed to that esteem and influence in the society,
at least in America, which George Fox had held, not of his own seeking, nor for himself,
but from the conviction of his friends,
of the many excellent virtues he was endowed with,
and the spiritual advantages they had received from
his faithful example and pastoral care,
they regarded him as the principal of their elder brethren, worthy of double honour;
and the influence he thereby acquired, he steadily directed to the honour of God,
and their edification and establishment in pure religion to the last.

Several friends had been concerned to caution several
George Keith in great christian tenderness,
of the dangerous consequences of busying himself in useless speculations,
and questions of words which gender to strife, previous to his removal to America,
as I apprehend; where, when he arrived, keeping his latent notions to himself,
or partly disclosing them only to such as he could
venture to entrust therewith as a secret,
he continued openly to profess and vindicate the doctrines
of the people called Quakers in sundry notable tracts,
as,
[.book-title]#The Presbyterian and Independent Visible Churches in New England
and Elsewhere Brought to Doctrines of the Test and Examined;#
[.book-title]#A Refutation of Three Opposers of Truth; the Pretended Antidote Proved Poison,
or The True Principles of the Christian and Protestant
Religion Defended Against Cotton Mather and Others;#
and [.book-title]#A Serious Appeal to all the More Sober,
Impartial and Judicious People in New England, in Vindication of Friends.#
Yet in the same year that he published this last treatise,
his secret disgust at his friends broke out into open dissent and contention, chiefly,
as appears, because he could not obtain that preeminence he aspired after,
nor carry things in all cafes according to his own prescriptions or dictates:
for instead thereof, several of his friends, less versed in speculative points,
but better established in practical religion,
fearing his falling into danger and error through unwatchfulness,
were not wanting in brotherly affection gently to communicate their apprehensions;
but he, who, in the present exaltedness of his mind,
locked upon himself as their superior in wisdom and knowledge,
and now began to regard his friends with an eye of contempt,
seems to have thought it beneath him to regard the advice of those,
whom he imagined himself better qualified to instruct;
and to have formed a design to govern, or to divide.

He began with objecting to the manner in which the discipline of the society was conducted,
complaining there was too great a slackness in the application thereof,
and proposed new regulations for the amendment of the deficiencies,
which having drawn up in writing,
he presented to the meeting of ministers at the yearly meeting;
but as they did not fully approve thereof,
they proposed to refer the matter to the consideration of the yearly meeting of London,
which he declined, signifying, he would rather let it drop.
Notwithstanding this,
he conceived aggravated disgust at the disappointment to such a degree,
that from this time the secret envy and dislike, which had been rankling in his breast,
began to break out in captious remarks,
and bitter sarcasms upon the general conduct of friends, their manner of preaching,
and such like matters; not that they were more liable to objection at that time,
nor in that place, than, I imagine,
they had been all along from the time of his first entering into their community;
for I cannot discover, that any remarkable change appeared in the body of friends,
either in Europe or America, in their principles, their manners,
or their manner of preaching, which were much the same as at their first rise,
and as they were all the time while George Keith continued in close fellowship with them;
but it appears too evident that he was now become
a man given to change in all these respects.

Passion and prejudice corrupt the heart, and give it a perverse bias.
George Keith, now invidiously watching for occasion against friends,
took exceptions at some words uttered by Thomas Fitzwalter
and William Stockdale in their public testimonies,
first began to quarrel with them, and charged them with preaching false doctrine,
in setting forth the light of Christ to be sufficient for salvation,
and declared to Thomas Fitzwalter, that he himself did not believe,
the light was sufficient without something else.
Which expression Thomas reported to some other person,
for which George brought a complaint against him to the monthty meeting.
This appears to me a very frivolous cause of complaint
to bring before any body of men in a judicial capacity,
and carries the appearance of a spirit lusting to contention,
and a mean duplicity in George Keith;
for that he so expressed himself was proved by the evidence of several witnesses,
who were present, and yet he denied it to the meeting.
The meeting entering into the examination of his complaint,
in order to take away all occasion of cavilling from him,
who was now studiously seeking it, as Thomas had reported nothing but matter of fact,
and had the evidence of many witnesses,
they saw no cause to charge him with asserting an untruth;
but his manner of procedure in George Keith`'s absence,
and without first endeavouring a reconciliation between themselves,
they judged a wrong proceeding, as being a breach of gospel order.
Thomas very readily acknowledged, that though the charge itself was true,
the mentioning it, in the manner he had done, was wrong.

He next complained to the meeting of ministers against William Stockdale,
for having said,
that his preaching Christ without and Christ within was preaching two Christs.
William Stockdale denied his uttering the expressions in the terms complained of;
and on the other hand alledged against Keith,
that he had treated him in a very contemptuous and abusive manner,
calling him an ignorant heathen, and several other opprobrious appellations.
The meeting delivered their opinion, that Stockdale was culpable, and deserving reproof,
for uttering the words he did,
they being an offence to sundry sound and well-minded friends,
and that he should condemn the same.
And as to George Keith`'s manner of proceeding against him,
they could not admit it to be agreeable to gospel order,
he not having dealt with him alone in a private manner,
before he proceeded further in his complaint;
neither could they hold him excusable for his indecent expressions to William Stockdale,
he being older in experience and in years.

By this time friends in England got intelligence of these differences,
whereupon several of hearing of them in London wrote
an epistle to their brethren in Pennsylvania,
earnestly pressing them to their advice keep the
unity of the spirit in the bond of peace,
and guard against disputations upon subjects not tending to edification,
whereby that charity and brotherly kindness,
which had hitherto connected them in gospel-fellowship,
might be in danger of being weakened or dissolved.
That obedience to the precepts of the gospel was a better proof of our honouring Christ,
as a teacher come from God,
than airy speculations and controversies leading
to contention about his glorified body in heaven;
wishing them rather, after the custom of friends from the beginning,
to be emulous in the practice of all christian virtues,
and show forth the fruits of the spirit out of a good conversation,
than to be over curious in questions of words, ministering to strife and contention;
reminding them of the ancient and constant principle and experience of friends,
that the dispensation of the gospel committed to them, was a

[.embedded-content-document.epistle]
--

&hellip;spiritual dispensation; in nowise to oppose,
reject or invalidate Jesus Christ`'s outward coming, suffering, death, resurrection,
ascension and glorified estate in the heavens;
but to bring men to partake of the remission of sins,
reconciliation and eternal redemption, which he hath obtained for us, and for all men,
for whom he died, and gave himself a ransom, both for Jews and Gentiles, Indians,
Turks and Pagans, without respect of persons or people.
And Christ is fully to be preached unto them, according to the holy scriptures,
by them whom he may send unto them for that end;
that as the benefit of his sufferings extends to all,
even to them that have not the scriptures, or outward history thereof, they may be told,
who was and is their chief friend, that gave himself a ransom for them,
and hath enlightened them;
yet not excluded those from God`'s mercy or salvation by Christ,
who never had nor may have the outward knowledge or history of him,
if they sincerely obey, and live up to his light;
for his light and salvation reach to the ends of the earth;
yet still we that have the holy scriptures,
and those plain outward confirmed testimonies concerning
our blessed Lord and Saviour Jesus Christ,
both as to his coming in the flesh and in the spirit,
have cause to be thankful to God for the peculiar favour,
and that these scriptures are so well preserved to posterity; and we beseech you,
let us keep to the plainness and simplicity of scripture
language in all discourses about matters of faith,
divinity and doctrine; and sincerely believe,
own and confess our blessed Lord and Saviour Jesus Christ, the Son of the living God,
in all his comings, appearances, properties, offices and works, both for us and in us.

--

This epistle, which is very long, concludes with the excellent counsel of the apostle,

[.embedded-content-document.epistle]
--

If there be therefore any consolation in Christ; if any comfort of love;
if any fellowship of the spirit; if any bowels and mercies, fulfill ye my joy,
that ye be like-minded, having the same love, being of one accord and one mind;
let nothing be done through strife or vain glory, but in lowliness of mind,
let every man esteem others better than himself.

[.signed-section-signature]
Signed by George Whitehead, Samuel Waldenfield, John Field, Benjamin Antrobus,
William Bingley, John Vaughton, Alexander Seaton, Daniel Monro, Patrick Livingston.

--

The brotherly counsel and concern of friends in England,
although marked throughout with of clear reasoning,
and christian tenderness and moderation,
and earnest zeal to heal the breach or prevent the widening thereof,
had no better effect than the honest endeavours of friends in America had before.
Ambition and bitterness of spirit had so thoroughly possessed George Keith,
that their suggestions had greater power over him than the best admonitions.
Being baffled in his principal aim, that of taking the lead -- in the society,
he set no bounds to his malicious invectives,
suffering his passion to hurry him on to vent his resentment in illiberal reproaches,
in violation of decency and common sense.

At another meeting with him he openly avowed the doctrines,
which before he had endeavoured to conceal,
by denying his having said what was proved he did say,
as in the case of Thomas Fitzwalter,
and roundly charged several friends with unsoundness of faith.
Thomas Lloyd told him, in behalf of himself and others, whom he had accused,
that they believed all things written in the scriptures concerning our Saviour`'s birth,
death and resurrection, etc. in the outward; to which he smartly replied,
but is it absolutely and indispensably necessary
to all and every one of mankind to believe it?
adding, that unless he did so believe, he would not own him as a christian; but said,
he might be a devout heathen.

Thomas Lloyd was appointed by William Penn to the station
of deputy governor of Pennsylvania during his absence,
and filled the station with integrity and repute.
His consequence, of course, must be considerable both in religious and civil society.
His particular patronage of George Keith, and unremitted endeavours to serve him,
previous to his violating of the unity of society,
deserved his grateful respect yet because he gave
his tongue within the bounds of common decency,
even to him, but at a succeeding meeting,
gave the loose rein to his petulance so far as to call him impudent man,
and pitiful governor; asking him why he did not send him to jail;
telling him his back had long itched for a whipping; menacing him and his friends,
that he would, expose them in print all over America, if not over Europe.
One of the magistrates, remarkable for his moderation and pacific disposition,
he called an impudent rascal.

This conduct betrayed the passion and malignity of a violent party spirit,
and could mean nothing but an essay,
whether he could provoke them to some act of authority as magistrates,
whereby he might take an occasion to raise a cry of persecution against them;
and men of less temper, and less regard to religion, might very probably,
in the like circumstances, have complied with his desire, and cured his itch,
and have vindicated themselves also against the charge of persecution,
by alledging that reviling is not religion,
nor reproachful appellations a conscientious scruple:
But the men with whom he had to deal were of a very different cast,
being of those who were restrained by their religious principles,
conformable to primitive christianity, from returning railing for railing;
being defamed they entreated; they bore his reproaches with patience,
exerted their endeavours to pacify him, and recover him to a better mind,
and to prevent an open breach, in a spirit of meekness;
but all their endeavours were in vain.

At length, after many vilifying expressions to particular persons,
as occasion raised his wrath,
he went so far as to bring a most reproachful charge
against a reputable part of the body at large,
charging a meeting of ministers with coming together _to cloak heresies and deceit,
and that there were more damnable heresies and doctrines of devils
among the Quakers than among any profession of protestants._

This reflection, which is mere assertion with out shadow of proof,
evidences the bitterness of his spirit, urging him to expressions pointed in malice,
to provoke, without regard to candour or to truth: Against the validity whereof,
and in defence of the people called Quakers,
we can perhaps bring no authority more opposite to the point than his own,
in his serious appeal printed in Philadelphia in this very same year 1692,
wherein he fully condemned in others those measures, he was now so fondly pursuing.

[.offset]
Serious appeal, page 6.--

[.embedded-content-document]
--

Notwithstanding Cotton Mather`'s strong asseverations against us,
as if we denied all or most of the fundamental articles
of the christian and protestant faith,
yet he shall never be able to prove it,
that we are guilty of this his so extremely rash and uncharitable charge,
either as in respect of the body of that people,
or in respect of any particular writers or publishers of our doctrines and principles,
and preachers among us, generally owned and approved by us,
as men of a sound judgment and understanding.
And for his citations out of the Quakers`' printed books and treatises,
I would have you to consider, that most of them are all borrowed and taken,
not from our own books, but from our professed adversaries,
men known well enough to be possessed with prejudice against us;
such as Thomas Hicks and John Faldo and others, whom our friends in Old England,
and particularly George Whitehead and William Penn, have largely answered.

--

Hitherto friends had treated with him in a private way in much meekness and patience;
but it was properly judged that this public insult demanded public reparation,
which he contemptuously refusing to make,
the monthly meeting of Philadelphia proceeded to disown him,
and as the testimony they published on this occasion exhibits a
plain narration of the case and the reasons of their procedure,
and his offensive conduct, it justly claims a place in this work,

[.embedded-content-document.testimony]
--

[.blurb]
=== To the several monthly and quarterly meetings in Pennsylvania, East and West Jersey, and elsewhere, as there may be occasion.

[.salutation]
Beloved Friends,

In tender love, and with spirits bowed down before the Lord,
is this our salutation unto you; earnestly desiring your growth,
and daily preservation in the ancient truth,
and in the simplicity of the gospel of our Lord Jesus Christ,
and our hope and breathings are that no insinuations or wiles of
the enemy shall prevail to turn you aside from your steadfastness,
or to cause you to esteem lightly of the rock, and way of God`'s salvation unto you;
but that you be kept in the sight and life, which was and is the just man`'s path,
to the end of our days.
Amen!

Now dear friends it is with sorrow of spirits, and grief of souls,
that we signify unto you the tedious exercise, and vexatious perplexity,
we have met with in our late friend George Keith, for several months past:
So it hath happened, friends, lest any flesh should glory,
but become silent before the Lord,
that this once eminent man and instrument of renown in the hand of the Lord,
whilst he kept his first habitation,
and knew the government of truth over his own spirit,
and witnessed the same to be a bridle to his tongue, was then serviceable,
both in pen and speech, to the churches of Christ:
But now and of late it is too obvious and apparent, that being degenerated from the low,
meek and peaceable spirit of Christ Jesus,
and grown cool in charity and love towards his brethren,
he is gone into a spirit of enmity, wrath and self-exaltation, contention and janglings,
and as a person without the fear of God before his eyes,
and without regard to his christian brethren,
and letting loose the reins of an extravagant tongue,
he hath broken out into many ungodly speeches,
railing accusations and passionate threatenings towards many of his brethren, and elders,
and that upon slender occasions:
and when some in christian duty have laid before
him his unsavoury words and unchristian frame,
he hath treated them with vile words, and abusive language,
such as a person of common civility would loath: It hath been too frequent with him,
and that in a transport of heat and passion,
to call some of his brethren in the ministry, and other elders,
and that upon small provocations (if any) fools, ignorant heathens, infidels,
filly souls, liars, heretics, rotten ranters, Muggletonians,
and other names of that infamous strain, thereby to our grief, foaming out his shame:
And further, his anger and envy, being cruel against us,
and not contenting himself with his harshness against persons,
he proceeded in bitterness of spirit to charge our meetings
with being come together to cloak heresy and deceit;
and publishing openly several times, that there were more doctrine of devils,
and damnable heresies, among the Quakers,
than among any profession among the protestants.
He hath long objected against our discipline, even soon after his coming among us;
and having prepared a draught of his own,
and the same not finding the expected reception, he seemed disgusted.
Since which he hath often quarrelled with us about confessions,
declaring that he knew none given forth by the body of friends to his satisfaction,
and often charged most of us with being unsound in the faith.
We have offered in several meetings for his satisfaction,
and to prevent strife amongst us, and for preserving the peace of the church,
to deliver a confession of our christian faith,
in the words of our Lord and Saviour Jesus Christ, the author of the christian faith,
and in the words of the apostles, and disciples, his faithful followers;
or we would declare our belief in testimonies of our ancient friends and faithful brethren,
who were generally received by us; or we would concur and agree upon a confession,
and have it transmitted for the approbation of the yearly meeting here,
or the yearly meeting at London; yea, it was offered unto him at the same time,
that a confession concerning the main matters of controversy
should be given out of a book of his own;
but all was slighted as insufficient.
The Lord knows the trouble which we have had with this unruly member;
and the openess of our hearts, and well-wishes towards him,
notwithstanding his rage and violence against us,
and of the endeavours of many in this place,
to have gained upon him by a friendly converse, and by other means,
not inconsiderable to a brotherly freedom:
But our labour hitherto seems to be as water spilt upon a rock.
And this meeting having orderly and tenderly dealt with
him for his abusive language and disorderly behaviour,
he hath not only slighted all applications of gaining
him to a sense of his ill treatment and miscarriages,
but in an insulting manner said to the friends appointed by the meeting to admonish him,
that he trampled the judgment of the meeting under his feet as dirt:
And hath of late set up a separate meeting here, where he hath, like an open opposer,
not only reviled several friends by exposing their religious
reputations in mixed auditories of some hundreds,
endeavouring to render them, and friends here, by the press, and otherwise,
a scorn to the profane, and the song of the drunkards;
but he hath traduced and vilified our worthy travelling
friends James Dickenson and Thomas Wilson,
in their powerful and savoury ministry, whose services not only here,
but in most meetings in England, Scotland and Ireland,
are well known to have a seal in the hearts of many thousands.
He hath also within a few weeks appeared in opposition, as it were,
to the body of friends, by putting on his hat,
when our well received and recommended friend James Dickenson was at prayer,
and that in a meeting of near a thousand friends, and others,
and so going out of the meeting to the great disquiet thereof,
and to the drawing some scores into the same opposition with him, by his ill example.
And by thus persisting in his repeated oppositions, hard speeches,
and continued separation, and labouring like an unwearied adversary,
to widen the breach made by him, and so abusing some of the neighbouring meetings,
by being as yet under that cover of being owned by us;
we are hereby brought under a religious constraint and to
prevent other meetings of being further injured by him,
to give forth this testimony,
strained as it were from us by his many and violent provocations,
viz. That we cannot own him in such ungodly speeches and disorderly behaviour,
or in his separate meetings;
and that we disown the same as proceeding from a wrong spirit,
which brings into disorder inwardly, and leads into distraction and confusion outwardly;
and until he condemn and decline the same, we cannot receive him in his public ministry,
and would have him cease to offer his gift as such amongst us,
or elsewhere amongst friends, until he be reconciled to his offended brethren.
And as to those few of our brethren in the gift of the ministry,
who are gone out with George Keith,
into his uncharitable and dividing spirit (the miserable effects whereof many
of us have sufficiently known in Old England and other parts) our judgment is,
that while they continue such, they become unqualified to the work of the gospel,
as degenerating from the guidance of God`'s blessed and peaceable spirit
in their hearts (from whence proceeds the effectual New Testament ministry):
and being turned from the peaceable fruits thereof,
are gone into uncharitableness and contention.

And now all you who have walked in fellowship and communion with us,
and are drawn aside through inconsideration or otherwise into this
spirit of separation and prejudice against our meetings,
orderly established, and wherein we have been often mutually refreshed together,
we cannot but in the fear of God, and in love to your souls,
admonish you also of the insecurity of your present state,
and that therein we cannot have unity with you,
and unless you return from under that spirit,
dryness and barrenness from the Lord will be your reward.
And so dear friends we exhort you all to behave yourselves in the spirit of meekness,
and peaceable truth, upon all occasions,
but more especially upon any discourse or conference
with any of them who are discontented among you,
or have started aside from you; and avoid all heats and contentions,
in matters of faith and worship;
and let not the salt of the covenant be wanting in your words and actions,
for thereby the savour of your conversation will reach the witness of God in them.
The grace of our Lord Jesus Christ be with you all.
Amen!

Given forth by the meeting of public friends in Philadelphia the 20th of the 4th month,
1692.

[.signed-section-signature]
Thomas Lloyd, John Willsford, Nicholas Wain, William Watson, George Maris,
Thomas Duckett, Joshua Fearne, Even Morris, Richard Walter, John Symcock, Griffith Owen,
John Bown, Henry Willis, Paul Sanders, John Blunston, William Cooper, Thomas Thackory,
William Byles, Samuel Jennings, John Delaval, William Yeardly, Joseph Kirkbride,
Walter Fawcit, Hugh Roberts, Robert Owen, William Walker, John Lynam, George Gray.

--

George Keith having drawn a considerable party to join him in his opposition,
now set up a separate meeting.
This party adopted the name of Quakers,
but by way or distinction assumed to themselves the ostentatious
appellation of _Christian Quakers and Friends._
This separate meeting soon published a counter testimony signed by twenty-eight of them,
disowning all those concerned in denying George Keith; and soon after that another paper,
which they entitled, __An Expostulation with Samuel Jennings,
Thomas Lloyd and the Rest of the Twenty-eight Unjust Judges and Signers
of the Paper of Condemnation Against George Keith and His Friends.__^
footnote:[Vide, Appeal from the twenty-eight Judges, etc. after the postscript,
pages 6-9.]
Both these papers were drawn up with artfulness,
and calculated to catch the humours of the unwary and unsteady; and being circulated,
and puffed with all the industry of party zeal, a wide schism ensued;
much passion and rancour on one side, occasioned much painful exercise, vigilance,
circumspection and patience on the other.
They went on venting their malevolence in one defamatory libel, after another;
injuriously mutilating and culling such passages out of friends writings,
public testimonies and private conversations,
as might best serve their own partial purposes, making their own comments,
and putting their own meaning upon these passages,
in order by such unfair procedure to make their opponents
appear unsound in principle and ridiculous in practice;
sacrificing truth and equity to the gratification of their envy.

The government of this province at this time being
placed in hands which William Penn had selected,
I presume, from the most suitable in rank, character and abilities amongst those,
who had accompanied him to his new colony,
of whom the greater number being of the people called Quakers, many of this people,
and several of their ministers, were put into offices of magistracy and of government.
This expanded the field for party prejudice to range more widely.
George Keith had early brought over to his party one William Bradford, the printer there,
whereby he had a ready means of publishing all his defamatory writings;
and his present disposition of mind instigating him to lay
hold upon every occasion to depreciate the Quakers,
and deprive them of that place of estimation with the people which
their public and private conduct had justly procured them,
took occasion from some late public transactions,^
footnote:[In the beginning of the year 1691,
one Babit and his crew stole a small sloop from a wharf in Philadelphia,
and going down the river committed divers robberies,
of which information being given to the magistrates,
three of them issued a warrant to take them in order to bring them to legal trial,
by virtue whereof they were taken, and brought to justice.
The magistrates, who granted the warrant,
being some or all of them of those called Quakers,
George Keith and his adherents made their comments upon this as a proceeding
inconsistent with their principles against bearing arms,
and dressed it in the most aggravating colours, which party prejudice could invent,
although the most he could make of it was, that a Peter Boss with a few more took them,
without gun, sword or spear.
--Smith.]
to reflect upon and calumniate the principal magistrates for their judicial
proceedings in restraining robbers and bringing murderers to justice.
In this reflects attack of the magistrates,
George Keith seemed to have two objects in view:
to gratify his malevolence against the Quakers, and increase the number of his adherents;
a point of great consequence with him;
for several of the Menonists from the county of Meurs (being of that class of baptists
who hold magistracy unlawful for a christian to exercise) had removed into Pensylvania,
and by these means he brought several of these to side with him, or favour his cause.
But this liberty (or more properly the abuse thereof) taken by Keith and his partisans,
put the magistrates under the necessity to vindicate
the laws and excellent constitution of their country,
under which they acted, and which,
by the united testimony of the judicious and impartial part of mankind,
they supported with honour and justice, for the benefit and peace of the state,
to proceed against them.
First William Bradford the printer, and John Mc. Comb the publisher,
of a reflecting paper, were by a warrant from five magistrates taken up,
examined and committed to prison, but discharged without being brought to trial;
and the latter was afterwards so just as to give a true state of the case.
George Keith and Thomas Budd were also presented by the grand jury of Philadelphia,
as authors of another tract of like tendency; this presentment, being prosecuted,
the matter was brought to trial, and the parties fined 5£. each;
hut the fines were not levied.

These proceedings without doubt added fuel to the flame, and exasperated these men,
and their adherents, to represent them with the usual partiality of the spirit of party,
to raise a clamour of persecution against the magistrates,
who considering the mischievous design and tendency of these publications,
to introduce disorder and faction into this state in its infancy,
thought it necessary to prevent the fatal consequence of such licentious measures
by publishing the following vindication of their aforesaid proceedings.

[.embedded-content-document]
--

[.blurb]
=== At a private sessions, held for the county of Philadelphia the 25th of the 6th month, 1692, before Arthur Cooke, Samuel Jennings, Samuel Richardson, Humphrey Murray, Anthony Morris, Robert Ewer, Justices of the county

Whereas the government of this province being by the late king of England`'s
peculiar favour vested and since continued in governor Penn,
who thought fit to make his and our worthy friend Thomas Lloyd his deputy governor, by,
and under whom the magistrates do act in the government,--and
whereas it hath been proved before us,
that George Keith being a resident here,
did contrary to his duty publicly revile the said deputy governor,
by calling him an impudent man, telling him he was not fit to be a governor,
and that his name would stink, with many other flighting and abusive expressions,
both to him and the magistrates (and he that useth
such exorbitancy of speech towards our said governor,
may be supposed will easily dare to call the members of council, and magistrates,
impudent rascals, as he hath lately called one in an open assembly,
that was constituted by the proprietary to be a magistrate)
and he also charges the magistrates,
who are ministers here, with engrossing the ministerial power into their hands,
that they might usurp authority over him, saying also,
he hoped in God he should shortly see their power taken from them:
all which he acted in an indecent manner.

And further, the said George Keith with several of his adherents,
having some few days since, with unusual insolence, by a printed sheet called _An Appeal,
etc._ traduced, and vilely misrepresented the industry, care,
readiness and vigilance of some magistrates, and others here, in their late proceedings,
against the privateers Babbit and his crew in order to bring them to consign punishment,
whereby to discourage such attempts for the future;
and have thereby also defamed and arraigned the determinations
of the principal judicature against murderers,
and not only so, but also by wrong insinuations,
hath laboured to possess the readers of their pamphlet,
that it is inconsistent for those who are ministers of the gospel, to act as magistrates,
which if granted,
will render our said proprietary incapable of the
powers given him by the said king`'s letters patents,
and so prostitute the validity of every act of government,
more especially in the executive part thereof,
to the courtesy and censure of all factious spirits and malcontents under the same.

Now forasmuch as we, as well as others have borne,
and still do patiently endure the said George Keith and his adherents,
in their many personal reflections against us,
and their gross revilings of our religious society,
yet we cannot (without the violation of our trust to the king and governor,
as also to the inhabitants of this government) pass by, or connive at,
such part of the said pamphlet and speeches, that have a tendency to sedition,
and disturbance of the peace, as also to the subversion of the present government,
or to the aspersing of the magistrates thereof.

Therefore for the undeceiving of all people, we have thought fit by this public writing,
not only to signify that our procedure against the persons, now in the sheriffs custody,
as well as what we intend against others concerned (in its proper
place) respects only that part of the said printed meet,
which appears to have the tendency aforesaid,
and not any part relating to differences in religion, but also these are to caution such,
who are well affected to the security,
peace and legal administration of justice in this place,
that they give no countenance to any revilers, and contemners of authority,
magistrates or magistracy,
as also to warn all other persons that they forbear the
further publishing and spreading of the said pamphlets,
as they will answer the contrary at their peril.

Given under our hands and seal of the county, the day, year and place aforesaid.

--

As George Keith persevered after all in the same line of conduct,
the general meetings thought it their duty to confirm the
judgment and testimony of the monthly meeting of Philadelphia,
whereby they had disowned him.
First the quarterly meeting of ministers held at Philadelphia the 20th of the 4th month,
1692: And afterwards the yearly meeting for Pennsylvania and New Jersey,
held in Burlington the 7th of the 7th month following,
published their respective testimonies of approbation, of,
and unity with the proceedings of the monthly meeting of Philadelphia in his case.
So that being now publicly disowned by the meetings representative of
the whole body of friends in those parts of America where he dwelt,
and the meetings of which he was a member;
we are now to consider him no longer as a member of this society,
but as an open and professed adversary, and leader of a sect in opposition to them:
yet he would still lay claim to the name, although he had separated from them,
and made a dangerous schism,
alleging his dissatisfaction was only with some unsound Quakers in America;
but he was in unity with all faithful friends in England.

So when strangers from Europe or other parts came on religious visits into those countries,
he would affect unity with them,
and endeavour to ingratiate himself into their favourable opinion;
but as soon as they discovered any dislike of his proceedings,
he would give them little better treatment, than he did the colonists.
Two of these, Thomas Everdon and Richard Hoskins,
travelling at this time in Pennsylvania in the exercise of their ministry,
being well qualified ministers, and men of meek and humble spirits, with whom,
particularly the former, he said, he had good unity:
Yet two days after being at at meeting, where they were concerned in their ministry,
to the edification of their brethren, he rudely and openly opposed them,
calling out several times as they were proceeding in their testimonies,
hypocrites! hypocrites!
And Thomas Everdon, with whom he had so lately professed his unity,
he called in the face of the assembly, consisting of several hundreds,
_the greatest hypocrite that ever stood upon two legs._

Thomas Wilson also and James Dickenson from Cumberland, Great Britain,
arrived about this time on a christian visit to their friends in North America;
and being ministers eminently qualified with experience
and abilities to minister to the edification of their brethren,
their arrival at this season was of great service in these provinces;
both to recover and confirm the wavering, and to admonish George Keith,
and those that joined him, of the hurt to themselves and reproach to religion,
which must necessarily follow their giving way to such intemperance of spirit and conduct.
Thomas Wilson hereby incurred George Keith`'s greatest resentment at first;
but afterwards James Dickenson, to whom he professed a great amity and regard,
became equally obnoxious thereto,
the occasion whereof will appear by the following extract from Thomas Wilson`'s journal.

[quote]
____
We went to Philadelphia,
where we found the difference between George Keith
and friends broke out to an open separation,
he having gathered a company to himself, and set up a separate meeting,
which was cause of great exercise to faithful friends;
and he seeing we did not go to his meeting, sent us a challenge to dispute,
which we readily complied with, and had a meeting with him and his party,
a great many faithful friends accompanying us:
We sat a while in silence to hear his charges against friends,
viz. that some of them were not found in faith, doctrine and principle,
but did not prove it, nor suffer friends to answer him, but went on in railing:
We made remarks, though said nothing,
which raised a great desire in him and his abettors
to have another meeting with me and my companion,
which we readily agreed to.

Sometime after having divers friends along with us,
we met again with the said George Keith, and the chief of his abettors;
and being quietly set to hear what he had to say,
he advanced his former charge against friends, as being unsound in faith,
doctrine and principle, unto which I answered, saying, no error in faith,
doctrine or principle of particular men (or persons) was
a sufficient reason for him set up a separate meeting.
He opposed me; then I asked liberty to be heard, and told him to this effect:
If he and his company were sound in faith and doctrine, and men of God,
they should have kept up their testimony for the Lord in the meeting;
and if there must have been a separation,
such unsound men (or persons) would have gone away from friends, as those did formerly,
of whom John said, "`they went out from us, but they were not of us,
for if they had been of us, they would no doubt have continued with us,
but they went out that they might be made manifest, that they were not all of us.`"
I also asked them,
whether ever they knew faithful friends in England leave their meeting,
and set up a separate meeting?
Thus we left the dispute at that time,
and went to visit the meetings of friends in the Welch tract or plantation,
and to and fro in the country; so returned again to Philadelphia,
and had a third meeting (very large) with Keith and his party.--I told them,
they were gone from the Lord in an airy sourish, and the wit of man,
and had set up a separate meeting,
but in a little time the sun of righteousness would shine amongst them,
and drive away the misty doctrines of men,
and that they (meaning the separatists) should dwindle, die away, and come to nothing,
except such who were most honest (towards God) who should return to truth and friends;
which in a little time was fulfilled in both respects.

Now leaving friends at Philadelphia, we went into the country to a meeting,
to which George Keith came, and asked me where we would be on the first day?
saying also, that he had appointed a meeting to be the next first day at Crosswix;
and finding freedom, I went thither,
but my companion James Dickinson found drawings from the Lord to go to Philadelphia,
and be at the meeting there that first day,
to which George Keith came contrary to his appointment, and leaving his separate meeting,
met with friends in their large meetinghouse, and preached fawningly,
as though he and James Dickenfon were in unity, but after he had done,
James stood up in great authority in the Lord`'s power;
and confuted George`'s doctrine and practice, setting truth over him and his party,
and opened the mystery of salvation to the people, to their great satisfaction;
after which George Keith went away in great wrath, and the people who were not friends,
being many, cried aloud, Give way and let the devil come out,
for the little black man from England has got the day;
after which George called his party together to their meetinghouse,
and told them that James Dickenson had never appeared against him till that day,
but had then made himself equal with Thomas Wilson (meaning in opposition to him, etc.)
____

In short George Keith had suffered his passion and
prejudice to embitter his mind to such a degree,
that few or none under the name of a Quaker,
whose virtues and services placed them in a rank of estimation,
and were too steadfast in the faith to countenance his proceedings,
escaped his revilings and calumnies: Since his being disowned,
he spent his time about Burlington, Philadelphia, and other places adjacent,
amongst his disciples, writing in his own and their defence,
and establishing them as well as he could in his novel doctrines:
But the matter of his being disowned by so many meetings sitting very uneasy upon him,
after causing so much trouble and dissension amongst a people,^
footnote:[Beside the monthly and quarterly meetings of Philadelphia,
and the yearly meeting of Burlington, already mentioned, friends of Bucks county,
of Maryland, Long- Island and others,
had testified their disunity with the proceedings of George Keith and his adherents.]
reputable for the peace and good order in general maintained by them, in America,
he set sail for England in the beginning of the year 1694,
accompanied by his intimate friend and associate Thomas Budd,
in order to lay his complaint before the yearly meeting in London,
and as the sequel proved,
to endeavour to foment contention and disorder among friends in England,
as he had done in America: Where leaving him to pursue his journey,
it seems proper to break off this disagreeable narrative,
to bring forward the affairs and transactions of friends in England during this period,
and thenceforward.
