== Chapter VII

[.chapter-synopsis]
* Account of Thomas Story`'s Convincement
* His Birth and Education
* Brought up to the Study of the Law
* He conceives Offence at some Ceremonies in the public Worship
* And declines attending it
* He goes to a Meeting of the People called Quakers
* In which feeling a divine Power attending his Mind, he soon after enters into their Society
* Receives a Gift in the Ministry, and travels much in the Exercise thereof
* Life and Character of Stephen Crisp
* Applications for an Affirmation Act
* Death of Queen Mary
* Declaration of the People called Quakers, etc.

In this year Thomas Story joined himself in society with the people called Quakers,
whose convincement was not owing to the ministry of any instrument;
but to the immediate operation of the grace of God in his own heart,
of which himself hath given a remarkable narrative in the journal of his own life.
He was born at Justice-town, near Carlisle, in the county of Cumberland,
where he had the advantage of a liberal education,
being designed by his father for the study of the law.
He had an early inclination to solitude,
which he sometimes spent in religious thoughtfulness,
and frequently in reading the holy scriptures,
which he prized and delighted in above all books, especially the New Testament,
not only at this time, but in the succeeding stages of his life,
when in refute for the excellency of his understanding and his extensive learning.

But his solitude was interrupted by a plan of education accounted genteel, but,
in his opinion, not well calculated to promote religious inquiries or experience;
being put to learn fencing and music,
by which he not only found his mind drawn away from serious considerations,
but he contracted society, which was not favourable to religion.

He was next placed with a counsellor in the country to commence his studies in the law;
preparatory to his entering one of the inns of court for the completion thereof,
where being much in the country,
in a sober and religious family of the most moderate sort of Presbyterians,
he had again the advantage of solitude and little company, and that innocent,
so that he recovered his former seriousness in a good degree.
And though he indulged himself at times in some youthful airs,
yet through secret grace he was preserved from gross evils,
and his agreeable manners gained him respect with all the family.

He received his education as to religion in the church of England, but as his mind,
intent up on investigating truth,
was illuminated with a discovery of some practices which appeared to him relics of superstition,
and in no wise conducive to advance pure religion,
it occasioned him some offence and some doubts of the propriety offence at thereof.
For the family removing from the country to Carlisle,
he was diligent in attending the public worship, especially at the cathedral,
the repetition of the apostle`'s creed;
and at the mention of the word Jesus bowing and kneeling toward
the altar-table (on which were two common prayer books in folio,
and over them painted on the wall I.H.S.) were ceremonies which,
he not comprehending the use or benefit of, gave him uneasiness,
as esteeming them relics of Popery;
and although he continued to go thither a little longer,
yet he could not comply with several of the ceremonies used there.

Afterwards being invited to a christening (so termed) of a relation`'s child,
he conceived additional offence at the ceremony of baptizing the infant, as apprehending,
we have neither example nor precept in scripture
for the manner then practised in that ceremony.

Being still attentive to the reproofs of instruction, which are the way to life,
he felt them a law condemning those thoughts, expressions, passions and affections,
which are fixed in the first nature, and rooted in the carnal, mind;
and experienced that spiritual warfare begun,
wherein he felt the law in his members warring against the law in his mind,
and saw and felt many things in himself, unnoticed by any man,
but clearly discovered by the measure of light he was favoured with,
to be obstructions to his growth in religion,
and which were to be subdued and consumed by the spirit of judgment and of burning;
the lust of the flesh, and of the eye, and the pride of life, the produce of every soil,
and which in him had much to feed upon; the elegant airs of a youth well bred, strength,
activity and comeliness of person; mental endowments,
and competent acquisition of literature; the glory,
advancements and preferment of the world spreading their nets before him,
and the friendship of the world beginning to court him with flattering address.

But through the illumination of divine light, and the assistance of the grace of God,
he was enabled to deny all these worldly lusts, and to attain moral righteousness,
and sequester himself from all his former acquaintances, whose manners and conversation,
though not vicious (for such he never affected) yet as they had not the knowledge of God,
became burdensome and irksome to him,
in the present serious and inquiring state of his mind.

As he followed on to know the Lord,
he was favoured with deeper and clearer manifestations of the purity of true religion,
and to the spiritual eye it was discovered,
that the Son of God was not yet effectually revealed in him,
nor the old man by the power of the holy cross sufficiently mortified and slain;
which increased his internal inquiry after essential truth,
and his attention to the monitor in his own breast for information;
as he did not know of any in all the world to teach him,
or that the Lord had any people then on earth, owned by his presence with them,
as his flock and family.

After a season of deep humiliation under the sense of his being short of that purity,
which was discovered to his mind as an object to aspire after,
being strengthened to resign his soul to the divine will in this state of resignation,
the sun of righteousness arose in him with healing and restoring virtue,
whereby his old self, and the whole carnal mind, with all that dwelt there in, self-love,
pride, evil thoughts and evil desires,
with the whole corruption of the first state and natural life, were wounded and slain,
his mind became serene and free from anxiety, in a state like that of a little child.

These secret operations were confined to his own breast,
so that no man knew any thing of them; only an alteration was perceived in him,
but the cause unseen; He put off his usual airs, his jovial conduct and address;
laid aside his sword; burnt his instruments of music;
divested himself of the superfluous part of his apparel,
confining himself to that which was decent, plain and useful.
He declined the public worship; but not with a design to join himself to any other sect.
For he was apt to conclude, from what he had observed,
that these inward manifestations were peculiar to himself,
and that there was not any people, with whom he might properly associate.

Continuing in silence and solitude he advanced in religious experience,
and with this experience his inward peace and consolation increased.
In this state of his mind he was led into a consideration
of the states of many persons in the national way of worship,
as also among the dissenters of divers denominations;
for although he received his education in the way of the church of England,
he had no aversion to any class professing the christian name;
but occasionally heard several sorts, but did not fully approve any sect in all things,
as he came to consider them closely; yet observing many, who seemed men of sincerity,
and to have good intentions in their respective modes of worship,
he began to question whether it might not be through his own fault,
for want of the true knowledge of God heretofore,
that he did not enjoy his presence among them, as he had done in his retirement;
and therefore determined to go and see,
and accordingly he went to the public worship at
the place called St. Cuthbert`'s in Carlisle,
and although he retired in his mind, to feel after the divine presence,
as he was wont to do in his solitary waiting, he found himself veiled in darkness,
and encompassed in trouble, to that degree,
that it was only in regard to decency he could prevail
upon himself to tarry till their worship was ended,
which being over he returned to his chamber in trouble, and went not among them any more.
But though he declined all outward worship, determining to follow the Lord,
wheresoever he might see good to lead him;
yet he found his mind clothed with universal charity and benevolence,
to all man kind of every denomination.

In his solitude at a certain time the people called Quakers were suddenly,
and with some surprise, brought to his mind, with an impression sufficiently deep,
to induce a secret inclination to inquire after them,
their principles and manner of worship.

An opportunity presented in the 5th month the Quakers
1691 when meeting with a member of that society,
and inquiring of him concerning some points of their religion,
he perceived no material difference between their sentiments and his own,
and being invited by the friend to accompany him next day (being
the first day of the week) to their meeting at Broughton,
he readily complied.

The meeting at their arrival being fully gathered,
he sat down among the throng of the people in inward retirement.
And though one of their ministers began to speak,
yet his attention was more turned to what passed in his own mind,
with a desire to gain an intelligence,
whether the Lord owned them with his presence in their religious assemblies,
than to the doctrine at that time delivered,
and he soon received a convincing evidence of what he desired to know.

For not long after he sat down amongst them, the like divine power,
which he had of late been favoured with in his private retirements,
overshadowed his mind with abundant consolation; and whereas from general observation,
he had perceived the prevailing formality in religious
profession amongst the various sects and denominations,
contenting themselves in that religion,
which was merely the effect of education or tradition, he was ready to apprehend himself,
like the prophet, alone,
in this inward experience of the refining work of the washing of regeneration,
and the mental consolation in consequence thereof,
he now perceived that herein he was mistaken; for he was convinced, beyond a doubt,
that the same divine presence and holy influence attended the greatest part of the meeting,
and that under the shadow of the wing of divine power they sat with great delight:
Under this edifying sensation they felt themselves mutually of the comforted and united,
and made one another`'s joy in the Lord.
For the friends there being generally sensible,
he was affected and tendered with them by the influence of the truth,
they made profession of and concluded he had at that time, and not before,
been convinced thereof, their joy was as at the return of a penitent.
And his joy was in the view of reformation so far advanced in the earth;
when not long before he had thought,
there had been scarce any true and living faith or knowledge of God in the world.

From this time, he continued to attend their meetings, as he had opportunity,
and as he be came more intimately acquainted with them,
he felt the bands of near unity with them daily strengthened,
and was not ashamed on the following occasion openly
to acknowledge himself a member of their society,
although so generally despised by the world.

At the time of the assizes at Carlisle, an acquaintance of his applied to him,
in regard to a suit he had to come on the next day for the greatest part of his property;
and Thomas being the only witness to the deeds of conveyance he could at present procure,
he desired him not to fail giving his attendance at the court early the next morning.
Thomas, in answer to his request, said,
"`I am concerned it should fall out so (for he had a friendly regard for the man,
and saw his case was very hard) but I will appear, if it please God,
and testify what I know in the matter, and do what I can for you in that way;
but I cannot swear.`" This answer got the better of the man`'s patience,
so far as to make him in a passion reply with an oath,
"`What! you are not a Quaker sure!`" As he had neither hitherto received from others,
nor assumed himself this appellation,
nor as yet saw whether he had so much unity with all their tenets,
as might justify him in adopting the name,
he continued silent and attentive to the truth in his own mind,
till clear in his understanding what answer to make, and then he said,
"`I must confess the truth, I am a Quaker.`"

This plain confession increased his peace,
and his acquaintance`'s perplexity and vexation,
whose case appeared to him hereby rendered desperate;
so that in the height of his passion he threatened to have Thomas
fined and proceeded against with the utmost rigour of the law,
exclaiming, "`What! must I lose my estate for your groundless notions and whims?`"
Thomas Story was not free from anxiety in consequence of this menace,
under the probable prospect of fining and imprisonment,
and of little help from his father or friends,
but rather of their displeasure at such an unaccountable scruple, as,
it would appear to them.
After some time of silent meditation he felt strength to,
resign himself to the divine disposal, under the consciousness of a good intention,
and therein found his anxiety vanish, and his mind center in serenity.
And next morning, as he was going up, to the courthouse,
in expectation of being called as a witness in the case aforementioned,
he met his acquaintance in a very different disposition from that,
in which he had left him the night before, for with a cheerful countenance,
denoting friendship and affection, he said, "`I can tell you good news;
my adversary hath yielded the cause, we are agreed, to my satisfaction.`"

He continued diligently to attend the meetings of this people, where,
in a state of silence, his heart was frequently tendered and broken,
as well as under a powerful living ministry;
and some years after his joining this society,
he received a gift in the ministry himself;
and devoted much of his time to travelling in the exercise thereof,
for the edification of his brethren, and the convincement of others,
in most parts of the British dominions, on both sides of the Atlantic.
There were few of his contemporaries more diligent,
or more esteemed for their gospel labours, than he was, not only within the society,
but also without, the meetings which he visited,
being frequently attended with a numerous concourse of people of other societies.

His conversion gave considerable uneasiness to his relations, particularly his father,
chiefly because it crossed his views as to his son`'s rising
to eminence in that line for which he designed him;
for Thomas clearly perceived that the practice of the law,
and being conversant in frequent suits and contests of the world,
would disturb the peace and serenity of his mind, expose him to many temptations,
and be the probable means of preventing his advancement in religious experience,
and an obstruction to the fulfilling of his duty,
he therefore finally resolved to decline the practice of the law,
though the only thing designed as the means to procure him a living;
accordingly the next persons who came to employ him in business of that kind, he refused,
telling them he should not under take business of that kind any more.

In this year Stephen Crisp terminated a life of righteousness and repute, very much,
and very successfully employed in propagating the doctrines of truth,
as held by the people called Quakers, amongst,
whom he was distinguished for his labours in the ministry,
and for his eminent qualifications for service.
He was born at Colchester in Essex in the year 1628, where he received his education,
at a time when religion lay much in seeking after truth and purity,
rather than settling in any established form.
This friend appears to have been one of those,
who were seriously engaged in seeking a religion, wherein he might find rest to his soul;
but was seeking many years before he could find it.
For from an early age he had a religious turn of mind,
and therein was favoured with light to distinguish between good and evil,
and with earnest desires to obtain power over the evil and corruptions of nature;
that he might pursue after that goodness, he had a discerning of, without obstruction:
In order whereto,
he became a very attentive hearer and regarder of those reputed the best ministers,
and even at this tender age gave himself up to reading,
and resorted to hear sermons with as much cheerfulness,
as other children resorted to their play and diversions;
and yet could not meet with what he was seeking after; power over his infirmities,
nor a foundation to rest upon with security.
He went from preacher to preacher, and from one society to another,
till wearied out with his fruitless search he detached himself
from close connection with every visible society;
but wandered up and down, sometimes to one sect of people, sometimes to another,
taking a sharp inspection into their lives and doctrines, though he confesses,
he left his own garden undressed, until many noisome weeds overgrew.
He began to take delight in airy and mirthful company,
and indulging himself in a participation of their pleasures;
but in the midst of his mirth,
the reproofs of the monitor in his own breast followed him with strong convictions,
and finally put a stop to his deviation.
He then renewed his inquiries of one kind of professors and another,
and how peace and assurance might be attained.
Amongst the rest, falling in with the baptists,
they told him the only way was to be obedient to the commands and ordinances,
of Jesus Christ; to imitate the primitive saints; to walk in church order and communion,
where every one had the strength of many;
and all the church are bound to watch over every member.
To these sentiments he yielded assent, joined them in communion,
and submitted to their mode of baptism,
expecting to attain thereby greater power over sin than before;
but found it not to be the baptism which now saveth,
being only a washing away of the filth of the flesh;
which conveyed not the ability he was looking for, to attain the essential part,
the answer of a good conscience toward God;
and though he strove much in the his strength of his own will and wisdom,
to subdue his inclination to levity and jocularity,
and by a more stayed and sober conduct to contribute
to the reputation of the religion he had chosen,
that he might not appear to have run and changed all in vain,
he felt that he continued to want what he what he wanted before,
power to gain the victory over his corruptions;
he therefore was induced to look for something more substantial than signs and shadows,
being impressed with a belief, that a way would be revealed,
superior to all he had been acquainted with, though he knew not what it might be.

This was about the time that the people distinguished by
the contemptuous denomination of Quakers became the subject,
of much conversation, generally in the line of censure and contumely;
he could hear no good report of them,
only they were universally the objects of scorn and aversion,
evil treatment and persecution,
and that they were remarkable for bearing all the injuries,
to which they were exposed with patience.
This seemed to have a different effect upon him from
what it had upon many of those he conversed with;
for he was in expectation that when this way, which he looked for as more perfect,
than what he had hitherto found, should be discovered, it would be hated and persecuted;
whereby he was influenced with a strong desire,
that some of the ministers of that denomination might visit their parts,
as he heard they had done sundry other parts of the nation;
and it was not long '`till James Parnel came to Colchester, in the year 1655,
by whose ministry and conversation Stephen Crisp was effectually convinced,
as hath been already related in its place.^
footnote:[See Vol. I. page 182.]
After his convincement he had many conflicts to endure,
before he attained the desire of his soul;
he found he must put off the old man with his deeds, his words,
his imaginations and his wisdom; take up the cross of Christ, and bear it upon him;
which as he willingly submitted to, he found it be to him,
that which he had been seeking from his childhood, even the power of God,
whereby he was crucified to the world, and the world unto him.
By these means attaining experience in the re deeming work of true religion,
he became in, due time qualified for service in the church, first in the discipline,
in the care and oversight of the poor, which care he discharged with fidelity,
both in administering advice and relief, as exigency required;
and afterwards in the work of the ministry,
in the exercise whereof he was zealous and diligent,
travelling much abroad for the edifying of his friends, and increasing their number,
being made instrumental to convince many others in various places and nations.
His first prospect: as to going abroad to exercise and travels his gift was to Scotland,
but many difficulties presented themselves in his way; his own inability,
the care of his family, his service in his own meeting,
were pleas which he would willingly have advanced
to have gotten himself excused from this service,
but found he could not keep that peace of mind,
which he had through faithfulness measurably obtained,
and which was now of more value with him than all the comforts and conveniences of life,
without being faithful to manifested duty in this prospect; wherefore,
after visiting his friends in some neighbouring meetings in Essex and Suffolk,
he gave up all in obedience to the divine requirings,
and arrived in Scotland in the ninth month, 1659,
where travelling through various parts of that nation that winter on foot,
his labour was not in vain in the Lord, several being convinced thereby.
About mid-winter he returned to England by the western road,
through Westmoreland and Lancashire,
etc. as he had made his way from home through Lincolnshire and Yorkshire,
and arrived safe at his own habitation in much thankfulness to that divine power,
whose presence had attended him,
and whose providential arm had preserved and restored him
in peace and safety to his beloved wife and children,
after an absence of five or six months.

He divided his future time between his outward occupation
and the requisite care of his family,
and the filling up his service in the cause of religion, as he felt the impulse of duty.
His succeeding travels for propagating gospel truths
were frequent through the greatest part of his life.
He visited the northern and western counties, and other parts of England,
several times over;
but the care of the churches which had been gathered principally by the
ministry of William Caton and William Ames in Holland and Germany (now
these labourers who had lived amongst them for some time,
were removed by death) fell most weightily upon him.
He crossed the German ocean no less than thirteen times,
on religious visits to these countries,
which the friends of these parts esteemed a favour of divine providence,
that just about the juncture of time in which they were
deprived of the services of the aforesaid ministers,
Stephen Crisp, under the impulse of love and duty, should be drawn to visit them,
to exercise his religious care over and his ministry amongst them.
In the discharge hereof his diligence and his attention
to all their concerns were remarkably conspicuous,
not only in his public ministry,
but in his visits to private families and particular persons he
was very zealously engaged to impart counsel and instruction,
as occasion required.
And not only in word and doctrine were his labours exerted,
but he frequently employed his pen for the spreading of the principles of truth,
in the defence thereof against opposers,
and for the refuting of the misrepresentations and calumnies raised against it.
His doctrine at first was expounded by an interpreter,
but afterwards he attained a knowledge of the Low Dutch language,
whereby he was qualified to preach to them in their own tongue.
In fine, amongst them he exercised the office of a bishop without the title,
according to the apostle`'s instruction to Timothy, 2 Epist.
4:2. "`Preach the word, be instant in season; out of season; reprove, rebuke,
exhort with all long suffering and doctrine.`"

And as he was so eminent for his usefulness in this society,
it is not to be expected he could escape the persecution,
to which all his friends were exposed in the age wherein he lived.
After his return from Scotland he stayed but a short time at home
'`till his apprehension of duty drew him to visit the city of London,
and from thence to proceed to the north of England,
where his labours were conducive to the converting
of several people from darkness to light;
and while he was prosperously engaged in his service
the fifth monarchy men made their insurrection,
in consequence whereof a general imprisonment of the members of this society ensued.
Stephen Crisp at this time was travelling in the county of Durham,
and being at a meeting at Simon Townsend in Norton,
was taken thence by Captain Bellasise with a party of soldiers, with six other friends,
and cast into prison (nigh two hundred miles from home) as were many others,
to the number of an hundred; some taken from their work in the fields,
others from inns on their travels.
Here he was detained in prison '`till released by the king`'s proclamation the next year,
1661.
In the same year he was apprehended at a meeting at Harwich,
and by a justice of peace there,
who had ordered his mittimus to be written before his examination, committed to prison.
In the year 1663 a grievous persecution of this people
broke out at Colchester where William Moore,
mayor, exerted the utmost of his authority to oppress them,
and on the 25th of October forcibly broke up the meeting,
and committed Stephen Crisp and John Pike to prison;
but how long he was detained in these two last imprisonments I have no account.
In the beginning of the year 1670 he was again imprisoned at Ipswich in Suffolk,
at the instigation of a priest,
who had contrived to get him imprisoned about two years before;
he was now committed on the act of the 14th of Charles II. which enacts
for the first offence a fine not exceeding 5£. or else imprisonment,
not exceeding three months.
Upon his trial at the assizes, the judge, R. Rainsford,
suffered his passion to get the better of his recollection so far as to condemn
him in the penalty of 5£. and imprisonment '`till he should pay the same;
but afterwards recognizing his error,
he sent an order for his release at the expiration of three months.
In the latter part of the same year a new act against conventicles coming in force,
Stephen Crisp was again taken by soldiers from the meeting at Horslydown, Southwark,
and fined 20l for preaching there.

In the latter years of his life, being much afflicted by the stone,
he was disabled from travelling as heretofore; but still devoted to the service of truth,
and the cause thereof, and promoting the prosperity of friends therein,
he divided his time pretty much between his native place and the city of London,
as the place where he could be most extensively serviceable.
He was very diligent and exemplary in attending meetings, in preaching the gospel,
in provoking to love and good works, in joining friends in the city,
in their solicitations to government; circumspect in conversation,
and in every practice and every virtue,
whereby he might promote the peace and prosperity of his brethren,
and edify them in love to God and one unto another.
In the exercise of his ministry be was ready and clear in expression,
agreeable in his manner of delivery,
and preaching the heartfelt truths of his own experience,
he reached and affected the hearts of his auditory with
convincing evidence of the weight and truth of his doctrine.
The meetings which he attended were frequently crowded
by a resort of people of other professions,
both at home and in his, foreign travels, being esteemed by others, as well as friends,
an eminent minister of the gospel.

He was also a very useful member,
and well qualified for service in the discipline of the society,
being a man of a good natural understanding, of acute discernment and penetration,
whereby he was enabled to give sound judgment in
matters under deliberation in meetings of discipline.
He was not only charitably engaged in a religious care over the members of the
society for their preservation from evil and encouragement in well-doing,
but actively assistant to his friends and others, especially widows and orphans,
by advice and otherwise, in the management of their outward affairs,
for which he had a capacity beyond many.

Having thus sent a life here of devotion to the service of God and man,
he was well prepared for his translation to a better.
His disorder gathering strength, he suffered great bodily pain,
which he bore with exemplary patience to the last.
George Whitehead visiting him about four days before his decease, he said,
"`I see an end of mortality, but cannot come at it.
I desire the Lord to deliver me out of this troublesome and painful body;
yet there is no cloud in my way;
I have full assurance of my peace with God in Christ Jesus,
my integrity and uprightness of heart is known to the Lord,
and I have peace and justification in Christ Jesus,
who made me upright in the sight of God.`"
To another he said, "`I have fought the good fight of faith, and have run my course,
and am waiting for the crown if life that is laid up for me.`"
And to another, "`Serve the truth for the simple truth`'s sake,
and it will preserve thee as it hath done me.`"
He desired his dear love in Christ Jesus to be remembered to all his friends,
and on the 28th day of the 9th month, 1692,
he departed this life at Wandsworth in Surry near London, in the 64th year of his age.
His body was removed to the meeting-house in Grace-Churchstreet, London,
and from thence accompanied by many friends and others
to friends`' burying ground at Bunhill fields.
Several lively testimonies were borne to the power of that truth,
whereby he had been made honourable through life, and rendered happy at his close.

The people called Quakers,
who were still subject to many great injuries and inconveniences
by reason of their conscientious scruple to take an oath,
were encouraged by the apparently more liberal and moderate temper or the times,
in consequence of the late revolution,
to apply by petition to the parliament for relief in this solemn case,
praying that a bill might be enacted,
by which their solemn affirmation or negation might be admitted instead of a formal oath.
The petition was read and referred to a committee, who reported, "`Upon the whole,
it is the opinion of this committee;
that the Quakers ought to be relieved according to the prayer of their petition.`"

But inveterate prejudices were yet too strong,
and the accustomed propensity to persecution,
too prevalent with many of the members of the parliament,
to yield them the desired relief.
The opponents of the bill found means to retard its progress,
and to prevent it from passing this session.
Friends renewed their application the succeeding year,
and having drawn up a state of their case in respect to oaths,
signed in their behalf by Theodore Ecclestone,
they presented it to the members of parliaments being as followeth:

[.embedded-content-document.address]
--

[.blurb]
=== A brief representation of the Quakers case of not swearing; and why they might have been, and yet may be relieved therein, by parliament.

`'Tis a certain truth, that among Christians, and Protestants especially,
there are divers particular things about religion,
conscientiously scrupled by some as unlawful, that others esteem orthodox:
and therefore it is not to be wondered,
that the Quakers differ from many others (though not from all) in this case of oaths;
they believing they are absolutely forbid to swear in any case,
by that positive command of Christ,
Matt. 5:34 and the earnest exhortation of his apostle, James 5:12.
And that this is undeniably their Christian persuasion
is evidenced by their sufferings these many years for not swearing.

And therefore their case may be worth the charitable notice of the government,
by law to relieve them therein; and not for their religious persuasion,
to continue them and their families exposed to ruin,
who among their neighbours cheerfully pay to the support of the government,
and by their trades and industry (according to their
capacities) advance the national stock.

It may therefore be humbly offered,
that it is not the interest of the government to refuse them relief.

Their industry in trade, both at sea and land, bringing profit to the government,
as well as others; the station they stand in, as merchants, farmers, manufacturers,
improvers of lands and stocks, is advantageous to their neighbours as truly as others.
And as it seems not the interest of the government in general,
that they should be any ways discouraged in honest industry,
so neither is it the interest of an eminent part of the government,
that they should not be relieved viz. the judges.

For the frequent suits that are brought against the Quakers before the
Chancery and Exchequer judges are no doubt very troublesome and burdensome,
by the difficulty of getting at a just issue, for want of swearing;
whereby justice is delayed,
and their causes often held very long and no doubt when just judges see the Quakers
wronged and abused and cannot relieve them* it is irksome to them:
so that it is humbly conceived, it would be a great ease to those courts,
to have the Quakers relieved in this case of oaths.

Neither is it without advantage to the king`'s other courts,
to be able to use the evidence of one who is now a Quaker,
that perhaps was not so some years ago; when he was witness to a bill bond, book-debt,
or deed of indenture; or when he was steward or trustee, or servant,
either to persons of quality, or to others of trade, or estate.

Nor may their testimony be useless to coroners, in case of unnatural deaths;
nor inconvenient in cases of trespass or felony, etc.

And it is farther proposed,
that it is not the interest of the subject to continue them unrelieved:
for it is not the interest of those the Quakers are indebted to; because,
though such may sue and harrass the Quakers in person and estate,
yet they may long want a decision of their debt or claim, as to the right of it,
for want of an answer upon oath.

It is not the interest of those they are concerned with, in any doubtful case,
because of the difficulty to come to trial.

And for those that owe money to the Quakers,
to be allowed to fly into Chancery for a refuge, to obstruct paying just debts,
is such an injury, as it is hoped no one that is rational will countenance,
or desire should be continued upon them.
And may it not then be asserted, that it is no honest man`'s true and just interest,
(to have the Quakers denied relief) no not the gown-men of Westminster-hall,
whose few fees from the Quakers, as plaintiffs,
might suggest (though unduly) that they have no long-tailed debts to sue for,
nor titles to recover; but if they so suppose, it is a mistake,
for it is rather their despair of relief,
and their well-known inability to pursue a cause,
that is their common determent to begin.

So that of all causes that crowd those courts, few are brought by the Quakers,
though they may need it much as others, to the great loss of the learned in the law,
as well as the poor injured Quaker.

And one might think,
it were great pity an industrious people should be kept liable to all injurious suits,
and so much barred from suing for their rights, be their cause never so reasonable, just,
or necessary.

Seeing their relief is to them so needful, so harmless to all,
and so useful to the government, and their neighbours;
let us a little consider the common objections, which may be summed up in short thus:

[.numbered-group]
====

[.numbered]
_First objection,_ How shall we then be at a certainty?

[.numbered]
_Secondly,_ Why should the laws be altered for them? For,

[.numbered]
_Thirdly,_ It would be to rase old foundations:

[.numbered]
_Fourthly,_ And let them into the government,

====

Which it is hoped will not be difficult to answer one by one,
and that to reasonable satisfaction.

And to the first, viz. The doubt of certainty.
It may be rationally affirmed, that whosoever is bound to tell the truth,
(especially against men`'s own interest, where the temptation, if any,
mainly lies) such are either so bound by the law of God, or the laws of men, or both.

Now the obligations by the law of God are binding on good men,
whether they give answers on oath, or on their solemn affirmation in the fear of God;
and knaves are only bound by the penal laws of men; which if made equally severe,
to those that give fallacious answers, as well without oath as by oath,
would be equally effectual and binding, both to them that give answers without swearing,
and to them that swear.

The second objection, that it would be an alteration of the law;
not of the substance of the law, but of a circumstance;
and if that hath no detriment in it, but that the alteration be really an amendment,
and a convenience to an honest, industrious people, pray why should it not be done?
what sessions of parliament is there, that passes,
but some law or other is made for the ease, security, or relief of the subject?

If foreigners are too hard for our sea-faring people,
out goes an act of navigation to prevent it.

If our poor at home want silk to work with, how soon is it granted,
(notwithstanding the same act) to come over land,
and not directly in shipping from the places of its produce,
as the said act before did enjoin:
and shall the ease of trade be so soon granted against a positive statute;
and the ease of conscience be so long denied in this, as positive a command of Christ,
at least really so believed and accepted?

And for the third objection, that it is to rase old foundations.
Answer, No, as it was said, it is rather to mend them; a proper work for parliaments.

Did not parliaments abrogate Popery, with all its claim of antiquity?
did not a parliament make the act of Habeas Corpus against the claim of prerogative?
and was it more reasonable to secure the subject
from perpetual imprisonment by a king without trial,
than it is to secure one subject from imprisoning another '`till death,
for not giving an answer in Chancery or Exchequer upon oath?
does it belong to parliaments to secure other subjects in their estates, liberties,
and properties?
and is it unparliamentary to secure the Quakers from
sequestrations against their whole estates?
because they dare not comply to a circumstance of the law;
when (as they understand it) it is against an express command of Christ?
surely no:
and therefore their relief in parliament is a fitting
case to be there tenderly taken notice of,
and provided for.

May it not then be well worth the while for this
present parliament to relieve these distressed people,
and afford their suffering case redress?
that thereby their causes may the sooner come to an issue;
whether they sue for just debts, or are sued; whereby many unjust and vexatious suits,
by injurious and litigious persons, may be prevented,
which have often tended rather to the Quakers`' ruin and others damage,
than recovery of their right.

As to the fourth objection, That it will tend to let them into the government:
For answer thereto, bar that as hard as you please; only do not let the supposal of that,
from which so easily and so willingly they may be excluded,
be a hindrance to that ease and benefit the government may so easily afford them.

But now while you have opportunity by the station Providence hath placed you in,
pray be you of such noble, generous spirits, as to relieve them,
though they differ from you in the construction of
a text they esteem plain and positive on their side,
and from which they dare not swerve,
having therein the concurrence of many ancient fathers, and martyrs,
and since them the Menists, and of late Francis Osbourne, Esq;
in his Political Reflections, 7th edition, p. 319, who treating of judicial cases,
calls not swearing,
a yielding a sincere and faithful obedience to the precept of our Saviour,
swear not at all, which (says he) the corrupt glosses of expositors labour much,
though all in vain, to elude.

And Swinderby in his appeal to the king, complaining of the errors of the Papists,
says thus, As Christ forbids swearing, so (says he) the Pope justifieth swearing,
and compels men to swear.

Which no man can rationally say, is only spoken of swearing in communication,
for his complaint is against justifying swearing, and compelling men to swear,
which cannot be pretended to mean other than solemn swearing; for no age that we read of,
did ever authorize profane swearing, much less compel to it.
"`

Since therefore not only profane swearing, but also solemn swearing,
was early complained of by Protestants, let it not seem strange to any,
that the Quakers now scruple swearing,
and for ease therein have often sought relief in parliament, the proper place.

Seeing then they believe, they have the authority of Christ`'s command,
and the apostle`'s exhortation, and the martyrs doctrine on their side;
though divers of you are not so persuaded.

Yet let the world behold your justice and willingness (according
to your power) to do good to all the honest and industrious people,
you both represent and govern: by enacting,
that their solemn affirmation shall be accepted in lieu of an oath; and all,
that falsely therein, shall be punished equally with perjured persons.

It having been made appear to a committee of this parliament, +++[+++Dec.
2, 1692]
that they are exposed to great hardships, as aforesaid, and not themselves only,
but others also; (which was the case of a member or two of this present parliament.)

So that upon the whole matter, the said committee were of opinion,
and did report it to the house,
THAT THE QUAKERS OUGHT TO BE RELIEVED ACCORDING TO THE PRAYER OF THEIR PETITION,
(then newly presented to the house.)

Wherefore,
as liberty hath been given them to declare their
allegiance to the government without swearing,
for which ease they are sincerely thankful;
so be pleased to add to that kindness their relief in the matter of oaths,
between them and other subjects, as well as between the government and them.

[.signed-section-closing]
Signed in behalf of the said people,

[.signed-section-signature]
Theodore Ecclestone.

[.signed-section-context-close]
London, Dec.
22, 1694.

--

After the perusal of this case,
several of the members of parliament discovered a
more friendly regard to the people and their petition;
yet the house came to no resolution in favour of their request.
In the following year, 1695, they renewed their application with better success..

This year Queen Mary was taken off by the small pox;
she was a woman not more eminent for her elevated rank in life,
than for her personal embellishments, intellectual endowments and virtuous dispositions.
In her sickness undaunted,
she awaited her change with a perfect resignation to the Divine Will,
and continued in that Christian resigned temper to the last.
As she had merited the general respect,
her death was generally lamented by all ranks of the people, but most of all by the King,
who was most intimately acquainted with her worth,
and so sensibly affected with his loss, that he could neither see company,
nor attend to the affairs of state for some weeks after.

Upon the death of Queen Mary, the zealous partisans of the late King James,
on the supposition that the interest of William was considerably weakened by her removal,
renewed their efforts for his restoration, both by an application to the French King,
to enable James to make a descent upon England,
and also by a plot at home to assassinate King William, which designs,
being timely discovered, were defeated.

First,
the two houses of parliament entered into an association
to defend King William`'s life and government;
and in case he should come to a violent death,
to revenge it upon his adversaries and their adherents.
And as this association was subscribed by people of all ranks, the people called Quakers,
whose conscientious principle against taking up arms prevented their subscribing,
thought it expedient to manifest their loyalty and fidelity to the King,
by drawing up and publishing the following declaration:

[.embedded-content-document.address]
--

[.blurb]
=== The ancient testimony and principle of the people called Quakers, renewed with respect to the King and government, and touching the present association.

We the said people do solemnly and sincerely declare,
that it hath been our judgment and principle from the first
day we were called to profess the light of Christ Jesus,
manifested in our consciences unto this day,
that the setting up and putting down kings and governments is God`'s peculiar prerogative,
for causes best known to himself;
and that it is not our work or business to have any hand or contrivance therein,
nor to be busybodies in matters above our station,
much less to plot or contrive the ruin or overturn of any of them;
but to pray for the king, and for the safety of our nation, and good of all men,
that we may live a peaceable and quiet life, in all godliness and honesty,
under the government which God is pleased to set over us.

And according to this our ancient and innocent principle,
we often have given forth our testimony, and now do, against all plotting,
conspiracies and contriving insurrections against the king or the government,
and against all treacherous, barbarous and murderous designs whatsoever,
as works of the Devil and darkness; and we sincerely bless God,
and are heartily thankful to the king and government for
the liberty and privileges we enjoy under them by law,
esteeming it our duty to be true and faithful to them.

And whereas we the said people are required to sign the said association,
we sincerely declare, that our refusing so to do,
is not out of any dissatisfaction to the king nor government,
nor in opposition to his being declared rightful and lawful king of these realms,
but purely because we cannot for conscience sake fight, kill or revenge,
either for ourselves or any man else.

And we believe that the timely discovery and prevention of the late barbarous
design and mischievous plot against the king and government,
and the sad effects it might have had, is an eminent mercy from Almighty God,
for which we and the whole nation have great cause to be humbly thankful to him,
and to pray for the continuance of his mercies to them and us.

[.signed-section-context-close]
From a meeting of the said people in London the 23rd of the first month called March,
1695-6.

--
