== Chapter X.

Treaty of Ryswick.--Address of the People called Quakers thereupon.--A Spirit of Persecution
revived.--Some Priests of Norfolk challenge to a Dispute.--They publish two abusive
Tracts.-- Answered by George Whitehead.--Remonstrance by William Penn.
--They procure a Petition against she Quakers to Parliament.--The Petition suppressed.
--Second Petition from the Magistrates of Edmundsbury, Suffolk, also suppressed.
--Account of Charles Marshall.--Account of John Crook.

A treaty of peace was concluded at Ryswick this year between England, France and Holland,
whereby the nation was relieved from a long and expensive war,
and king William acknowledged by Lewis XIV.
as king of Great Britain,
who also engaged not to disturb king William in the possession of his realms and government,
nor assist his enemies, nor favour conspiracies against his person.
Addresses of congratulation hereupon being made or sent up to the king from many quarters,
and from most or all other societies of protestants;
this society also in point of gratitude for the religious liberty they now enjoyed,
and to testify their satisfaction in the restoration of peace,
presented the following address:

To king William the third, over England, etc.

To grateful acknowledgment of the People commonly called Quakers, humbly presented.

May it please the king,

Seeing the most high God, who ruleth in the kingdoms of men,
and appointeth over them whomsoever he will,
hath by his over-ruling power and providence placed
thee in dominion and dignity over these realms,
and by his divine favour has signally preserved and
delivered thee from many great and imminent dangers,
and graciously turned the calamity of war into the desired mercy of peace;
we heartily wish that we and all others concerned may be truly
sensible and humbly thankful to Almighty God for the same,
that the peace may be a lasting and perpetual blessing.

And now, O king, the God of peace having returned thee in safety, it is,
cause of joy to them that fear him,
to hear thy good and seasonable resolution effectually
to discourage profaneness and immorality,
righteousness being that which exalteth a nation,
And as the king has been tenderly inclined to give ease and liberty of conscience to
his subjects of different persuasions (of whose favours we have largely partaken) so
we esteem it our duty gratefully to commemorate and acknowledge the same,
earnestly beseeching Almighty God to assist the king
to prosecute all these his just and good inclinations,
that his days here may be happy and peaceable,
and hereafter he may partake of a lasting crown that will never fade away.

London, 7th of 11mo called January, 1697.

The society of people, called Quakers,
although they now enjoyed the exemptions of the act of toleration,
did not enjoy them unmolested, revived.
There still survived a spirit of persecution and
intolerance in sundry ecclesiastics and others,
who envied them the liberty with which they were favoured,
and united their exertions to deprive them thereof.
The first effort about this time was made by some priests of Norfolk,
at the instigation of one Francis Bugg,
who formerly made profession with the people called Quakers,
and had apostatized from them some years before,
whether with William Rogers and the separatists of that day, or before,
I find no certain account;
he seems to have been of too little consequence to be particularly noticed,
only in a cursory manner, in any records or memoirs of this people I have met with.

These Norfolk priests commenced hostilities by a challenge to a
public meeting in their parish church (so called) at West Deerham,
where some friends of London and of the country met them;
the priests had got many books written by some of the society,
and endeavoured from thence to draw injurious conclusions,
which they could not make good,
nor gain the advantage they expected and aimed at in this dispute.

Being disappointed in their hopes in this verbal controversy, they then took up the pen,
and published two tracts, entitled, 1st [.book-title]#A Brief Discovery, Etc.#
2nd, [.book-title]#Some of the Quakers Many Horrid Blasphemies;#
and now discovering their real intention,
they presented these calumniating tracts to the parliament or members thereof,
to prepare the way for their further attempts.

These books, written with design to represent the principles of the Quakers blasphemous,
and the people seditious, met with suitable answers by George Whitehead,
wherein their ungenerous aims were detected,
and their acrimonious and injurious assertions refuted;
and copies of this answer were also delivered to the members of parliament,
to obviate any ill impressions from their misrepresentations.

But as these answers could not be finished and printed off so expeditiously
as the exigency required the following brief remonstrance,
drawn up by William Penn, was in the mean time printed,
and handed to the members of parliament.

It does not surprise us to be evilly entreated,
and especially by those that have an interest in doing it.
But if conscience prevailed more than contention, and charity over prejudice,
we might hope for fairer quarter from our adversaries.

But such is our unhappiness,
that nothing less will satisfy them than breaking in upon the indulgence that we enjoy,
if they could persuade the government to second their attempts to a new persecution,
in order to which we perceive they have been hard at work to pervert our books,
violate our sense, abuse our practice, and ridicule our persons;
knowing very well with whom they have to do,
and that the patience of our profession is their security for abusing of it.

However,
if it has weight enough with our superiors to expect
a fresh defence of our principles and practices,
we shall, with God`'s assistance, be ready, for their satisfaction,
once more to justify both, against the insults of our restless adversaries;
who otherwise, we take leave to say, would not deserve our notice,
since we have already repeatedly answered their objections in print,
and think it our duty, as well as wisdom,
to use the liberty the government has favoured us with,
in as peaceable and inoffensive a manner as may be.

Notwithstanding which, these priests and their assistant Francis Bugg,
and other abettors,
not contented with vilifying the people called Quakers
with their gross aspersions in print,
proceeded in their design,
and procured an invidious petition to the house of commons
replete with general invectives against this people,
accusations without grounds, and calumnies which they could not prove;
a copy whereof will evince the extent of their evil disposition,
and their reluctance to the toleration granted by the late act.

To the House of Commons.

Norfolk petition of justices and grand jurors.

We cannot without resentment take notice of the great
growth and daily increase of the Quakers,
and the mischiefs and dangers from thence threatening this nation.

It is observable with what restless zeal their deluding teachers,
and (as we suspect) many Romish emissaries under
their disguise ramble into all parts of these kingdoms,
and boldly spread their venomous doctrines everywhere;
attempting to infect and shake the minds of weak protestants;
and assuming rules of discipline, powers in matters of religion and forms of government,
repugnant to the established laws of this kingdom,
contrary to the very act of toleration, and not allowed to any other dissenters;
vouching all their actions by divine inspiration for their warrant,
and the indulgence of the government for their indemnity.

How apparently their blasphemous books and pernicious principles tend to subvert the
fundamentals of christianity and undermine the government is sufficiently demonstrable;
the publishing whereof, by pretended permission of the government,
is of a most dangerous consequence.`"

The prayer is to take these things into consideration,
that (with whatsoever tenderness to the persons and estates of these people)
their said principles and practices may be strictly examined,
and censured or suppressed as they shall appear to deserve,
and as in your great wisdom shall seem expedient;
and that the true christian religion may be preserved from popish
superstition and unpolluted with enthusiastic innovations.`"

It is unnecessary to make any comment on this extraordinary petition,
it speaks for itself,
that the spirit of persecution survived the act of
toleration in the breasts of all concerned in it.
Two priests,
John Meriton and L---- Topcliff attended the parliament
to solicit the introducing of their petition into the house;
but the times were now changed,
and more liberal sentiments in respect to religious liberty
generally adopted by all men of sense and candour,
than had prevailed in the preceding reigns.
Friends having obtained a copy of the petition showed
it to several of the leading members of parliament,
and how the direct tendency thereof was to make void the act of toleration,
and the liberty of conscience legally granted by the government.
This consequence was too obvious, not to be perceived by the members at the first view,
and they resolved accordingly to set their faces against the petition;
the petitioners put it into the hands of the members for the county,
who were brought into a disagreeable dilemma,
under the prospect of either disobliging the clergy of their own county and their partisans,
or taking a part contrary to their own judgment and the general sentiments of the house:
But on due deliberation they prudently withheld the petition,
thinking it in vain to make a motion in favour of a measure which
they were sensible would be immediately rejected.

A petition of the like tenour and tendency was also
drawn up by the magistrates of Edmundsbury in Suffolk,
who had signalized their promptitude to persecution, while the penal laws were in force,
and hereby evidenced their regret at being deprived of the power
of domineering and harassing their inoffensive fellow subjects,
and their eagerness to regain it.
Their petition was drawn up in the following terms:

To the honourable the commons of England, in parliament assembled.

The humble petition of the aldermen, assistant justice,
and chief burgess and burgesses of the common-council,
in behalf of themselves and the other inhabitants
of the borough of Bury St. Edmund`'s in Suffolk.

Humbly showeth,

That we considering all ancient heresies which have vexed both church and state,
were never so formidable in their rise and progress, as are the Quakers;
we have too just a cause of dreading the subversion of our
government by them if not carefully prevented and suppressed,
being in their clandestine constitutions opposite
to the condition of our established policy,
and in their principles of faith anti-christian; of government anti-monarchical;
in points of doctrine anti-scriptural; and in practices illegal, having their monthly,
quarterly and yearly meetings,
which we cannot but reasonably believe tend not only to
the subversion of our laws but of our religion also,
to us of greater concern than our lives.

We therefore, obliged in duty to God and our country,
do humbly pray your timely consideration of our jealousies, and remove our fears,
if not by totally suppressing,
yet at least by preventing their after-growth and increase amongst us;
that our posterity may untroubled live by this early care of our laws and liberties,
and we enjoy the wished-for happiness of a peaceful life.

The tendency of this petition was so plain and evident,
that after the care of friends respecting the Norfolk
petition they had little trouble about this,
for the Suffolk members had with others also declared their
aversion to the principles and drift of the former petition,
and therefore would not violate their own judgments and
convictions so far as to introduce it into the house;
but prudently suppressed it.

In this year this society in the city of London in particular,
was deprived of the company and services of a very valuable
and respectable member in the decease of Charles Marshall,
who had fixed his residence for several years past in that city.
He was born in the city of Bristol, in the 4th month,
and his parents being persons of religious and virtuous
dispositions gave him a good education,
directed to cultivate a similar virtuous disposition in him,
as well as to furnish him with a sufficient attainment of literature,
to fill his station in future life with reputation.
Faithful guardians of his tender youth,
they endeavoured to preserve his innocency by a cautious
restriction from the company of such children,
as being less carefully educated,
by their conversation and example might prove injurious to him.
Whilst yet a child he took delight in reading the scriptures,
and conceived an abhorrence of swearing, lying and other immoralities;
at this tender age his mother was careful to take
him along with her to the meetings of the independents,
which she frequented, who were at that time an enlightened,
sincere and conscientious people; sometimes he went to the baptist meetings,
and after the custom of that seeking age, to hear those teachers of every denomination,
who were in greatest repute for their zeal, experience and piety.

As he grew in years and experience,
he perceived that many of these people departed from
the pure principle of light and grace,
into lifeless and empty profession, wherefore he became dissatisfied with them,
and left them, spending;
much time in solitary retirement in the fields and
woods to pour forth his supplications to the Almighty,
and meditate in his law, out of the sight or observation of men;
being in great conflict of spirit under the weight
of death and darkness prevailing over him,
he cried for deliverance, and being now much detached from gathered societies,
he consorted with some other seeking people,
who spent one day in the week in fasting and prayer.

This was about the year 1654, when John Camm and John Audland,
having under a religious engagement of mind travelled to Bristol,
visited this select society in their meeting,
when by the powerful ministry of John Audland, Charles Marshall was effectually reached,
convinced and turned to an attention to the manifestations
of the light in his own heart.

Through a long series of inward exercises,
spiritual conflicts and assaults of the prince of the power of the air,
which were made manifest by the light in his conscience,
he grew in experience till the work of sanctification was measurably perfected,
and after many years, viz. in the year 1670,
he received a dispensation of the gospel to minister to others,
in the like demonstration of a divine influence by which he him self had been convinced;
and by his labours and travels was instrumental to convince many others,
and convert them to righteousness, continuing a faithful minister to the last.

In the same year 1670 he commenced his travels in the work
of the ministry under the impression of a divine requisition,
first through the neighbouring counties of Wiltshire and Gloucestershire,
and thence northward as far as Kendal in Westmorland, and back again through Cheshire,
Worcestershire and Gloucestershire home;
and so continued his travels pretty constantly to the year 1672,
during which time he visited most parts of England,
and what at this time was very remarkable,
met with no interruption by imprisonment or from informers,
no man being suffered to lay hands on him or stop his journey;
neither did any man (as far as he knew or heard) lose five
pounds on his account by means of the conventicle act.
But he was twice sick, nigh unto death, and passed through many trials,
difficulties and jeopardies, from which he experienced deliverance many ways.
One particular instance was this, having the sands to cross near Ulverston in Lancashire,
he came in company with four others to the river side,
where they were informed by two persons who lived on the other side,
that they might get over in safety; but he found a stop in his own mind,
and standing still he received this intelligence,
which he understood to be a divine warning,
_that if any attempted to go at that time they would perish;_
and in about an hour the sea overflowed the sands, which were several miles over,
whence they concluded, if they had gone at that time they had lost their lives.

Although he seems to have escaped imprisonment and personal
injury beyond most of his friends contemporary with him,
yet he did not escape entirely.
Being at a meeting at Claverham in Somersetshire, in the 10th month 1674,
some justices came to break up the meeting, one of whom, Francis Pawlet of Wells,
as he was concerned in prayer,
laid violent hands on him to pull him through the rail of the gallery,
and gripped him by the side so rudely and so hard as caused him to spit blood,
and haled him out of the meeting, whereby he received a contusion,
of which he complained long after.

He was a considerable sufferer for his testimony against tithes,
in the loss and spoil of his goods.
In the year 1682, whilst resident at Tetherington in Wiltshire,
he was prosecuted for tithes by John Townshend, priest of that parish,
in consequence whereof he was arrested, and brought before the barons of the Exchequer,
and committed to the Fleet prison, where he was confined for the space of two years.
The priest growing uneasy in his mind about this time, came in person to the prison,
released him, and soon after died.
Upon his release Charles Marshall stayed in London,
and fixed his domestic residence there,
but was frequent in his visits to his native city, Bristol, and places adjacent,
as well as several other parts of England.

Previous to his said imprisonment, while he was a resident in Wiltshire,
the separation which had its rise in Westmorland,
by the opposition of John Wilkinson and John Story
to the establishment of an orderly discipline,
had spread to the city of Bristol and the adjacent counties, particularly Wiltshire,
which was a new source of exercise to our said friend with others of his brethren,
men of discernment and integrity,
who clearly perceived the fallacious origin and pernicious tendency thereof,
and exerted their joint endeavours in much sincerity, meekness and patience,
to prevent its progress,
by zealous and charitable endeavours to convince the opponents of their error,
to recover them to a better temper,
and to rescue the more unexperienced or unstable members of the
society from being drawn aside by plausible and deceptive reasonings.
For this purpose George Fox in the year 1677 came to Bristol,
and being joined by William Penn and Charles Marshall they obtained
a meeting with William Rogers and others of the separatists,
in order to convince them of their error and the causelesness of their separation,
and the hurt which the temper of their own minds
sustained by entertaining sensations of rancour,
passion and hostility to their former friends, upon groundless surmises and suspicions;
but their well meant endeavours were ineffectual,
these separatists of Bristol being elevated in self-sufficiency
and obstinate in their opposition,
like their associates of Westmorland,
eluded all advances to reconciliation and mutual concord.

Being thus determined to persist in their opposition
to the establishment of good order in the society,
and Charles Marshall from clear conviction of the utility thereof,
finding it his duty to exert himself to procure its establishment in those counties
and places where the opposition thereto was kept up with the greatest violence of enmity,
he met with many trials of his faith and patience amongst them:
But being on a good foundation, engaged in a good cause,
and finding all endeavours to recover the opponents to a better temper fruitless,
he opposed their machinations with wisdom and fortitude,
and bore his testimony against the spirit they were in with faithfulness,
and without giving way to their insinuations or reproaches in the least.
In the authority of the gospel,
he with his fellow-labourers maintained a superiority over the antagonists,
and laboured with a good degree of success to lay open the fallacy of their pretensions,
and to establish the churches in the city of Bristol and
the adjacent counties in peace and good order.

Through many trying exercises of body and mind he continued his labours and travels
in the work of the ministry for the greatest part of twenty years,
freely given up to spend his substance,
time and strength therein for the gaining of souls,
and converting many to the way of life and salvation.
His last journey was to Bristol and the western counties,
after his return from which he was visited with a
lingering indisposition which proved mortal,
contrary to the opinion of his physicians, but not to his own,
for he seemed fixed in the opinion that it would terminate his existence in this chap.
world.

And even before his illness he seemed to have a presage of his approaching end,
for some little time before he pressingly requested
an intimate friend to take a ride with him,
having something of moment to impart, and when they were gone a few miles out of London,
he told him, he was satisfied the time of his departure drew near,
and therefore he was desirous of an opportunity to discourse with
him between themselves about some particulars before he died.

And when, soon after this, he was seized with indisposition,
though he remained settled in opinion that he should not recover;
yet this fixed persuasion of his mind was attended with
no fearful apprehensions of his future well-being;
having passed a life of faithfulness,
integrity and extensive benevolence in the service of God and man, he felt,
in the assured prospect of his approaching change,
that the work of righteousness was peace,
and the effect thereof quietness and assurance forever.

Being advised to go into the country for the benefit of the air,
he rather chose to be removed to John Padley`'s, near the river side,
a friend for whom he had an affectionate esteem;
he lay ill about four months in great weakness, frequently attended with great pain;
but borne up superior to his affliction, by the serenity of his conscience,
he was strengthened to bear his painful sensations with
much patience and calm resignation to divine disposal;
and his senses and understanding were preserved to him clear and sound to the last,
under the pure influence of heavenly support and
the consolatory enjoyments of divine life.

His love to his brethren, his universal benevolence and his spiritual abilities,
appeared to feel no decay from his bodily weakness,
as his expressions and his counsel to those, who came to visit him in his sickness,
clearly evidenced;
particularly to some of his brethren in the ministry
he addressed himself to the following purport,
as related by one then present,
who committed the substance of his expressions to writing presently after;

I have loved the brethren,
I have sought the unity and peace of the church for these forty years,
and to my great comfort never did anything tending to the breach thereof.

Two things are weightily impressed upon my mind warmly to recommend to friends,
which I desire may be communicated to them; the first is,
that they gather down unto the immortal seed and word of life in themselves,
and be exercised in it before the Lord; and duly prize,
and set a right value upon the many outward and inward blessings that the Lord
has eminently bestowed upon them since the morning of the day of his visitation;
then shall they grow and be preserved in a living freshness to him,
and the Lord will continue his mercies to them,
and they shall not want his divine refreshing presence
in their meetings together before him.
The second thing is this,
that those friends to whom the Lord hath given great
estates ought to cast their bread upon the waters,
and do good therewith in their life-time;
for those that are enjoyers of such things should see that they be good stewards thereof.
Oh, the many poor families such persons might be an help to!
How easily might they with a little assist many a family to live in the world! and what
a comfort would it be for such to see the fruits of their charity in their lifetime?
Some of his last words were these,
That he had not handled the word of the Lord deceitfully, nor done the work negligently;
earnestly desiring friends might live in love, and keep in the unity of the spirit,
which is the bond of peace.`"

As his last moments approached he closed his eyes with his own hand,
with composure of mind, as one from whom the sting of death was taken away,
and resigned his soul to God who gave it, the 15th of the 9th month 1698,
in the sixty-second year of his age.

Although by his profession, which was in the medical line, as an apothecary and chemist,
it must be presumed he had acquired a greater share of literature than many of his brethren;
yet in his ministering he affected no show of learning in the use of high sounding words,
nor laboured for elegance of expression, nor leaned upon memory or former openings,
but waited to feel the fresh opening of heavenly power,
and the animating influence of divine virtue to carry him forth in his ministerial exercises,
in which his demeanour was grave and reverent,
ministry in simplicity and godly sincerity, not with fleshly wisdom,
but by the grace of God,
his ministry was truly edifying and effectual to the refreshment of his friends,
and to the converting of many to,
and confirmation of many in pure religion and righteousness.

He was skilful to divide the word aright in plain dealing and close reproof
to such as in life and conversation were inconsistent with their profession,
and dishonoured it by a practice contrary thereto; but very tender,
sympathizing and encouraging to the well-minded in all their religious exercises.

His zeal for the establishing and keeping up a salutary
discipline against much opposition hath been already related;
and as he was a man of great meekness and great charity,
a lover of the brethren and a promoter of peace in the church,
so he was exceedingly zealous against the at tempts to rend and divide the body,
prevalent in his time, never sparing to reprove their obstinacy,
detect their deceitfulness,
and bear a faithful testimony against their contentious spirit.
His life and conversation gave efficacy to his ministry and to his religious labours,
his practice was agreeable to his doctrine,
and he was himself a living example of that virtuous and moral
conduct to which he was concerned to admonish his friends,
feeling for, sympathizing with, and full of compassion to the poor,
he failed net to be their advocate with the opulent
as well in the different parts of his life,
as in his latter end, reminding them at their plentiful tables of the necessitous,
and recommending self-denial, hospitality and liberality rather than high living;
and also was remarkably exemplary in the practice of that
charity which he recommended in the line of his business,
freely supplying the sick of this class with advice and with medicine,
the hungry with food, and the naked with raiment, according to his ability.

His natural temper was lively and cheerful,
but his religion tempered it with innocence and meekness;
he kept his passions in such subjection that he bore
ill-treatment and injuries without resentment,
or ruffling the serenity of his mind; he loved, practised and promoted peace,
and exerted his endeavours to reconcile such of his
friends or others as were in any respect at variance;
unity and concord amongst brethren being his delight.

He was an affectionate husband, a tender and vigilant guardian to his children,
by counsel and by example training them up in the way they should go, a kind master,
a faithful friend and a respectable and serviceable member of religious and civil society;
being accounted worthy of double honour amongst his friends,
and obtaining a good report among his acquaintance and in his neighbourhood for innocence,
honesty and integrity of life.

In this year John Crook departed this life; he was a man of literature,
of a good estate and rank in life, and in the commission of the peace for Bedfordshire,
where he lived: He was early convinced by the ministry of William Dewsbury in 1654,
about the 37th year of his age, soon after which his commission was taken away.
Through faithfulness to the truth, of which be was convinced,
he became deeply experienced in the work of sanctification,
and in the mysteries of the kingdom of Heaven;
where by he was made an able minister of the gospel,
being reputed by his contemporaries like Apollos,
eloquent man and mighty in the scriptures, which he highly esteemed,
and had an excellent gift in opening the mysteries thereof;
and was careful to adorn his ministry by a circumspect conversation,
coupled with the fear of the Lord.

While the state of his health admitted,
he travelled for the edifying his friends in different parts of the nation,
but mostly in Bedfordshire and counties adjacent,
and was instrumental to the convincement of many of the truth which he had to deliver,
but in his latter years being disabled from travelling
far by a complication of painful maladies,
he resided at Hertford, and spent much of his time in that town and county.

We have already seen by the account of his trial at the Old Bailey in 1662, that he,
as well as many others of his friends,
was a deep sufferer for the testimony of a good conscience,
and it was not upon that occasion only that he felt the severity of unmerited persecution.
On the 12th or 13th of the 111th month, commonly called January, 1660,
O.S. being on his travels in Huntingdonshire, where two friends,
Robert Ingram and John Parnel,
having been taken from their own houses by a party of horse,
and by the commissioners at Huntingdon committed to prison,
were visited by some of their friends, when a party of Horse surrounded the jail,
crying out, a meeting,
a meeting! and those who came to visit the prisoners were imprisoned with them;
but the day following they were discharged by the magistrates,
who released them only in hopes of finding a more legal pretence for imprisoning them,
saying, we shall soon have them again;
for they had heard of a meeting appointed at Sotho the next day.
Accordingly some armed men on horseback were sent thither,
who apprehended several friends, and amongst them John Crook,
who being carried before the justices, and refusing to take the oaths,
were sent prisoners to Huntingdon.
At the assizes in the 1st month called March,
most of the prisoners were set at liberty by judge Hale,
but John Crook and Robert Ingram, with Benjamin Thornby,
were detained until the ensuing assizes,
they being causelesly represented as ringleaders, and more dangerous than the rest.
John Parnel was discharged as to the oath;
but by an action laid against him for small tithes,
was detained five years longer in prison, at the suit of John Heath,
priest of Hemmington-abbott.

John Crook had enjoyed his liberation from this imprisonment
but a short time '`till he was imprisoned again at Aylesbury.
On the 1st of September having appointed a meeting at Culverton near Stony-stratford,
six or seven soldiers entered with pistols, and being accompanied with two constables,
they ordered them to take out the principal men; but the constables refused,
alleging they knew them not, at which the soldiers expressed their resentment,
and took away eight persons, amongst whom was John Crook,
and carried them before the deputy lieutenant of the county, who requiring sureties,
which they refused to give, he with much difficulty and perplexity,
after some hours puzzling, framed a mittimus, and sent them to Aylesbury jail,
where John Crook was detained up wards of three months,
as appears by an epistle to his friends dated from thence,
and how much longer I find no certain account.

His indisposition growing upon him with his advancing years, especially the stone,
proved a severe trial of his patience;
and although he had long suffered much pain under this and his other disorders,
so that he might say with Israel, Psalm 129, I have been afflicted from my youth;
yet his patience through divine support was remarkable
under all his afflictions to the last;
under the feeling sense whereof he frequently acknowledged,
_that if he did not feel and witness an inward power from the Lord,
he could not subsist under his violent pain.
And, that the furnace of affliction was of goad use,
to purge away the dross and earthly part in us._
In all the severity of his pain he was never known to utter
an unsavoury expression or impatiently to cry out.
And when the extremity of his fits was over,
he would thankfully express the inward joy and peace of mind which he enjoyed:
Beside the bodily affliction with which he was tried,
he was not exempt from trials of another kind,
in observing the deviation of some of his offspring from the ways of righteousness,
under his sorrow on which account,
he would some times solace himself with the words of David;
although my house be not so with God,
yet he hath made with me an everlasting covenant ordered in all things and sure.
In his old age he could remark that many of the ancients are gone to their long home,
and we are making haste after them; they step away before me, and I, that would go,
cannot; well! it will soon be my turn also.

Yet in the intermissions of his distemper he appeared frequently
so strong and lively in the spiritual warfare,
in his advanced age, that many were, ready to think,
he might properly adopt the language of Caleb, "`As yet I am as strong; this day,
as I was in the day that Moses.`" sent me; as my strength was then, even so is,
my strength now for war,
both to go out and come in.`" He continued in a solid and
christian frame of mind to the last period of his life,
which was terminated the 26th of 2nd month O.S. commonly called April,
in the 82nd year his age, at his house at Hertford.
He left behind in writing,
an epistle of weighty counsel to his children and grandchildren,
written scarce two months before his death, as followeth:

Dear Children,

I must leave you in a wicked age,
but commend you to the measure of the grace of God in your inward parts,
which you have received by Jesus Christ; and as you love it,
and mind the teachings of it, you,
will find it a counsellor to instruct you in the way everlasting,
and preserve you out of the ways of the ungodly.

I have seen much in my days, and I always observed,
that the fear of the Lord God proved the best portion,
and those that walked in it were the only happy people,
both in this life (while they continued faithful) and when they come to die,
though they meet, with many hardships in their passage.
By experience I can speak it,
that the ways of holiness afford more true comfort and peace to the upright soul,
than the greatest pleasures this world can afford; the former reaches the heart and soul,
while the delights of this world are but a show, and appearance only,
vanishing like a dream; and whoever believes otherwise of them,
will certainly find them to be but lying vanities; therefore the apostle,
might boldly put the question to the converted Romans,
viz. What fruit had you then in those things whereof you are now ashamed?
for the end of those things is death.

Therefore, dear children, be in love with holiness; make it your companion,
and those that walk in it; you may find buddings of it, from an holy seed in your hearts;
as you mind the inner man, the light will manifest the stirrings of it after God,
which I felt from my tender years; although I understood them not so plainly,
till I heard the truth declared.

I advise you to keep a pure conscience, both towards God and man; for if that be defiled,
hypocrisy and formality will deprive you of all comfortable feeling of God`'s presence;
and then deadness and dryness will be your miserable portion.

Be careful how you spend your precious time,
for an account must be given of every idle word, though but few regard it;
but foolish jesting, and vain talking, are said to grieve the spirit of God; read Eph.
4: 29-30. But improve your time in prayer, and religious exercises,
etc. and be diligent in your lawful callings;
for the desire of the slothful man killeth him, Prov.
21: 25. Be careful what company you frequent;
for a man is commonly known by the company he keeps, as much as by any one outward thing;
and of your behaviour in company;
for I have found that a wise and sober deportment adds much
to a man`'s reputation and credit in the world.

Watch to the light, and its discoveries of good and evil,
that you may not be ignorant of Satan`'s devices;
so the net will be spread in vain in the sight of the bird;
for watchfulness will make you in love with a retired estate;
and the more truly and perfectly any man knows and understands himself,
the better discerning will such have of other men; as in the beginning,
when deep silence of all flesh was more in use,
the spirit of discerning was more common and quicker than since it hath been neglected;
therefore be sure you spend some time (at convenient
seasons) in waiting upon God in silence,
though it be displeasing to flesh;
for I have had more comfort and confirmation in the truth,
in my inward retiring in silence, than from all words I have heard from others,
though I have often been refreshed by them also.

Love the holy scriptures, preferring them to all other books whatsoever;
and be careful to read them with an holy awe upon your spirits,
lest your imaginations put constructions upon them to your hurt;
but exercise faith in the promise of Christ, who hath said, my spirit shall take of mine,
and show them unto you.

Keep constantly to religious meetings amongst friends; but look to your affections,
that you respect not persons, but the power and life of truth, from whomsoever it comes;
not minding the tickling of your affections,
but the demonstration of the truth to your understandings and consciences;
for that will abide, when flashes of affections will fade and come to nothing,
after the words are ended.

Love one another truly, manifesting your love by good counsel,
and being helpful to each other upon all occasions;
being good examples to all you converse with, especially to your children,
and those of your own families, that pride and vanity may not be countenanced by you,
but rather reproved; remembering, while they are under your government,
you must give an account of the discharge of your duty to God towards them.

Lastly, be always mindful of your latter end, and live as you would die,
not knowing how soon your days may be finished in this world:
and while you do live in it, despise not the chastenings of the Lord, whatever they be,
he is pleased to visit you withal.
I have been afflicted from my youth up, both inwardly and outwardly,
but the God whom I served provided for me, when all my outward relations forsook me,
none of them giving me any portion to begin the world withal.
This I speak, to let you know, I shall leave more outwardly, even to the least of you,
than was left me by all my relations, etc.
I need not mention this sharp affliction (beyond expression) in my old age, because,
in some measure, you know it; but I could not have been without it,
as the Lord hath showed me, for I have seen his wonders in the deeps:
therefore I say again, despise not afflictions,
but embrace them as messengers of peace to your souls (though displeasing to the flesh.)

These things I commend unto you, out of true love to your fouls,
knowing how the vain mind of man little regards such advice as this I leave behind me:
but by this advice I show my true love to you all, desiring God`'s blessing upon it,
to whom I commit you all, my dear children, and end my days,

Your loving father and grandfather.

JOHN CROOK.

Hertford, the first of the 1st month, 1698-99.
