== Chapter IX.

[.chapter-synopsis]
* Friends still liable to exorbitant Sufferings for Tithes
* Present a Petition to the King
* Conference with the King
* William Penn visits the Western Counties
* He appoints a Meeting at Wells, which is broken up by the Mayor`'s Order
* Application for an Affirmation Act
* A Committee appointed to solicit Members, and promote passing the Act
* In the House of Lords the Bishops endeavour to frustrate the Application
* Form of the first Affirmation
* Bill for recovering small Tithes and Church Rates
* Exceptions against it

Notwithstanding the people called Quakers were now exempted from
suffering for attending their religious meetings by the toleration-act;
yet the jealousy of the clergy, and their watchful eye over their own interests,
prevented friends from obtaining any relief from
their sufferings for the non-payment of tithes,
and other ecclesiastical demands, by procuring an exception in the forementioned act,
whereby friends still not only the original demand,
but the exorbitant and oppressive methods of recovery were still retained:
reserving not only their alledged dues, but the power to be vexatious in reclaiming them,
a power which many of the clerical order exerted with rigour.
For at this time many friends were prisoners,
and others under severe prosecutions for non-payment of these demands,
and some long detained in prison upon contempts (as they term them) because they could
not from a conscientious scruple answer priests bills and complaints upon oath.
Friends of the meeting for sufferings in London taking this matter into consideration,
thought it expedient to draw up a state of the case, and present it to the king,
which was drawn up accordingly in the following terms:

[.embedded-content-document.address]
--

[.letter-heading]
To the King.

[.blurb]
=== The case and request of the peaceable people commonly called Quakers, in behalf of many of them, who are present sufferers for conscience-sake, humbly presented,

[.salutation]
Showing,

That as the God of all our mercies hath preserved
us a peaceable and quiet people in u the land,
according to our christian principle and profession,
under the various revolutions of government:
So we hope and resolve (by his divine assistance) ever so to continue;
being heartily thankful for the several kindnesses
and compassions received from the government,
especially for the present liberty we now by law enjoy in point of religious worship.
Yet forasmuch as many of said people are continued
under deep sufferings in their persons and estates,
by tedious imprisonments, seizures and sequestration;
divers also of late having died in prisons, and many more under prosecution,
and liable so to suffer in England and Wales,
tending to the ruin of many families for these causes of conscience,
chiefly on contempt (as adjudged) for not answering upon oath in cases of tithe,
when sued in the Exchequer;
and also for not answering upon oath when prosecuted
in the ecclesiastical courts for tithes,
church-rates, etc. whereupon they proceeded to excommunication,
and by significavits procure writs _de excom.
cap._ and sometimes justices warrants to imprisonments.

We therefore humbly remind the king that the great severities and persecutions
formerly inflicted on us were sometimes abated and respited,
when it pleased God to move the hearts of kings and governments
to show some compassion and favour to us,

[.numbered-group]
====

[.numbered]
_1st,_ By king Charles the second`'s proclamation of grace in 1661,
whereby many of our friends were released and freed out of prison.

[.numbered]
_2nd,_ By his letters patent (or pardon) in 1672,
pursuant to his declaration of indulgence to tender consciences in the same year.

[.numbered]
_3rd,_ By an act of parliament 25 Car. 2, ch. 5. entitled,
_An act for the king`'s majesty`'s most gracious and general pardon,_
pardoning contempts against the king,
whereby many also of the said people were discharged, and released out of prisons.

[.numbered]
__4th,__ Also by king James the second many were released out of prisons,
and relieved by divers commissions; and two general proclamation pardons,
the one in 1685 and the other in 1688.

[.numbered]
_5th,_ And also by an act of gracious general and free pardon
in the second year of king William and queen Mary,
several were discharged for contempt and imprisonments.

[.numbered]
_6th,_ And by thy late consort the queen (on application
made to her in thy absence) a poor innocent woman,
who had been long prisoner at Lancaster upon a fine, was released;
which as an intimation of the queen`'s tender and
merciful disposition we very thankfully acknowledge,
as we do also very kindly acknowledge the king`'s late favourable
inclination to discharge two of our friends,
prisoners in Westmorland, upon a petition presented by our friend Daniel Quare.

====

These precedents of royal favour and compassion to the oppressed,
and the present confinements and hardships of many innocent persons tenderly considered,

We the said people humbly request that the king would be pleased
to extend his favour and compassion towards the said sufferers
for their lawful ease and relief from their present confinements,
prisons and hardships, either by proclamation or otherwise,
as in his wisdom and clemency shall seem most meet and convenient.

--

This case and petition was presented to the king by George Whitehead, Gilbert Latey,
Thomas Lower, John Taylor and Daniel Quare;
which last named person being known to the king, had ready access to him,
and obtained admission to his presence for the rest;
he previously inquiring who they were, and in what stations in the society;
Daniel told him, they are ministers and elders amongst us.

The king then sent for them into a private apartment, where he was alone;
he inquired of them what places they belonged to?
Of what with the congregations they were ministers?
This furnished George Whitehead with a favourable opportunity to inform him that
they were not settled as ministers or pastors over any particular congregations,
but visited their friends meetings, as the Lord inclined them:
that they did not make a gain of their ministry,
nor receive stipends or hire for preaching; but preached the gospel freely,
according to Christ`'s command to his ministers, freely ye have received, freely give.
The king made no reply, but appeared very serious, and satisfied with the answer.

With the king`'s approbation a copy of the petition was also delivered
by George Whitehead and Gilbert Latey to the lord keeper Somers,
who received it courteously, and signified his readiness to comply with their request,
as far as the law would admit,
assuring them that the king was really principled in favour of liberty of conscience,
as he was also.
And in a short time after, an act of grace was passed,
whereby about forty friends in prison on the forementioned
accounts were restored to liberty.

William Penn in the course of last year paid a religious
visit to several of the western counties,
and had meetings almost daily in counties, the most considerable towns and other places,
which were greatly crowded, and in many places were held in the town-hall,
as the only place capable of containing the numbers who flocked to hear him.
And in this year repeating his visit to the same quarter,
some of the inhabitants of the city of Wells,
from the accounts they had of his public meetings last year in most of the great towns
(this excepted) expressed a desire that he might appoint a meeting there also.
He went thither accordingly,
and John Whiting and Robert Holder went to seek a suitable place to hold it in,
and also to give information there of to the bishop,
according to the prescription of the act of toleration,
which appeared afterwards to be a measure of expediency;
after they had got a grant of the market-house,
the clerk of the market being dissuaded by some persons who were unfriendly,
retracted his promise, and when they came at the time appointed refused them admittance;
whereupon they concluded to hold the meeting at their inn,
and took care previously to certify it also to the bishop.
The meeting was held in a large room with a balcony to the street;
the room was quickly filled, and there was also a great concourse in the street;
so that for the convenience of the double auditory,
William Penn placed himself in the balcony, and thence preached to the people;
but in the midst of his declaration he was interrupted
by officers from the mayor with the following warrant:

[.embedded-content-document.legal]
--

[.signed-section-context-open]
Wells City and Borough.

[.letter-heading]
To all constables, verderors, sergeants at mace of the said city.

Whereas William Penn and several others called Quakers,
are now riotously and unlawfully assembled and gathered together in this city,
and the said William Penn is now preaching or teaching in
a house not licensed according to the late act of parliament;
these are therefore to require you to take the said William Penn,
and him immediately to bring before us to answer the premises;
Given under our hands and seals this 15th day of November 1695.

[.signed-section-signature]
Matthew Baron, Mayor.

[.signed-section-signature]
William Salmon.

--

The officers, rudely officious, could not be prevailed upon to wait till he had done,
although desired, but forced him away instantly before the magistrates,
who upon examination finding the house was certified,
and that by disturbing a lawful assembly for an unlawful one,
they had exceeded their commission, they excused the matter as well as they could,
and presently dismissed him.
In this transaction we have an evidence that the
spirit of persecution survived the act of toleration,
and that the disposition to injure still remained in many minds,
although the power to gratify it was taken away.

These magistrates afterwards threatened the innkeeper
to fine him for a conventicle held in his house,
so earnest were they to revive the former severities;
but the bishop`'s certificate of the due notice being produced,
secured the man from their mischievous designs.

Friends after all this hired a house in this city for a meeting-place, and William Penn,
came thither again, and had a meeting to good satisfaction.
Several other meetings, and the quarterly meeting for the county,
were afterwards held there.

This year friends of the meeting for sufferings in
London renewed their application to parliament,
for accepting the solemn affirmation of the members of their society instead of an oath,
by the following case and petition.

[.embedded-content-document.address]
--

[.blurb]
=== The suffering case of the People commonly called Quakers, relating to oaths and swearing, humbly offered.

It is not unknown to this nation, that ever since we were a people,
it hath been our principle not to swear, make, or take oaths, which he,
who is the searcher of all hearts, knows is no other than a case of pure conscience,
in tender obedience to the mind of our blessed Lord and Saviour Jesus Christ,
as we are fully persuaded (according as many eminent
martyrs and men of wisdom and renown were,
who testified against oaths and swearing in the gospel day) and not obstinacy,
disaffection or worldly interests whatsoever on our parts;
we being really witting and desirous to answer the just and good ends of law and government,
as a peaceable people, fearing God;
and for this case of not swearing we have been exposed to
great sufferings and inconvenience in our persons and estates,
by tedious imprisonments, and disabled from receiving our due debts,
or defending our just titles and properties;
not suffered to give evidence in courts of judicature, at common or civil law,
nor to answer in Chancery or Exchequer, prove wills and testaments,
or take administrations, or to proceed in our trades at the custom-house,
or be admitted to our lands,
or trusted in our duties and services in courts leet or courts baron,
but great advantage is taken against us, because we so fear an oath,
as that we dare not swear;
for which cause also our children and young men are not
allowed their freedoms in cities or corporations,
when they have faithfully served out their apprenticeships;
nor admitted to give our voices in elections of magistrates
and parliament members in divers places,
though known to have right thereunto, as freeholders, etc.

Wherefore our request is, that in all cases where oaths are imposed,
and swearing required, our word, that is our solemn affirmation or denial,
as the fear and presence of God, may be accepted instead of an oath,
for which we humbly offer, and freely submit,
that if any under the same profession among us, break their word,
or be found false in such affirmation or denial,
or guilty of falsehood in any unsworn testimony, evidence or answers,
that then such penalty be inflicted on the person so offending as law
and justice require in case of false swearing or perjury.

To the respective members of the house of commons,
the humble application of the people commonly called Quakers.

We the said people, being members of that body which you represent,
and concerned in trade and industry,
and employing many poor in the manufactories of this nation,
as also in contributing to the charge of the government according to our abilities,
do desire and humbly crave that our liberties,
rights and properties may be secured to us and ours that
we may no longer be exposed to unjust and vexatious suits,
nor be a prey to ill disposed persons, who take advantage against us,
to prosecute and ruin us, merely because in point of tender conscience dare not swear,
in any case,
which is in obedience to the command of our blessed Lord and Saviour Jesus Christ,
as we verily believe is our duty in this gospel day;
but hold ourselves obliged to declare and testify the truth without oath,
in cases wherein our answers and testimonies may be required.

Wherefore we humbly entreat your christian compassion
in your favourable acceptance of our petition,
which is for leave to bring in a bill for our relief,
and so to consider our suffering case as if it were your own, and you in our stead;
that we and our posterity may have cause to bless the Lord on your behalf?

--

[.embedded-content-document.address]
--

[.letter-heading]
To the commons of England in parliament assembled.
Petition.

[.blurb]
=== The humble petition of the People called Quakers.

[.salutation]
Showeth,

Our many long and renewed sufferings for not swearing
we hope may give satisfaction to this nation,
that it is purely our conscientious and religious principle not to swear in any case,
in tender obedience to the command of our blessed Lord and Saviour Jesus Christ,
as we are fully persuaded,
and according to the example of many eminent martyrs and men of holiness,
wisdom and renown, who testified against oaths and swearing in the gospel day;
nevertheless we have been, and yet are exposed in our persons to tedious imprisonments,
in our estates to sequestrations and seizures,
disabled from defending our just titles and properties, recovering our just debts,
or helping others in like cases, and to many unjust and vexatious suits.

Wherefore the power of relieving us by law from these our grievances and hardships,
resting in the king and parliaments our humble request is,
that you will favourably please to give leave to bring in a bill,
that our solemn affirmation or denial may be accepted instead of an oath,
freely submitting, that whoever in this case shall falsify the truth,
and be thereof duly convicted,
shall undergo like pains and penalties as in law and justice are due unto perjured persons.

--

A committee of the aforesaid meeting was moreover appointed
to solicit the members in favour of the petition,
and to procure the passing of a bill for the relief of friends.
They showed copies of the petition to many of the committee members,
to furnish them previously with a clear understanding of the nature of the case,
as having a conscientious scruple against violating the command of Christ,
swear not at all, which they understood to be a positive prohibition;
also to show them the great necessity of affording them relief in this case,
by reason of the hardships and disappointments to themselves and others,
for want of their power to give legal evidence without injuring their consciences.

They spent some weeks in solicitation previous to their introduction of the petition,
being desirous that it might not be presented too hastily or abruptly,
before the members of the house were properly apprized of the tenour and tendency thereof,
and prepared for its reception.
They then applied to Edmund Waller, Esq; to take in the petition,
which he cheerfully undertook, moved the reading thereof,
and for leave to bring in a bill, that the solemn affirmation,
etc. which motion was carried by a great majority, and leave accordingly given.

The friends of the committee would have been glad to have procured the acceptance
of their simple affirmation or negation without any appeal to the divine Being;
but their friends in the house, who were rejoiced at their success so far,
and who were active in promoting the bill, giving their opinion,
that to make the attestation so solemn in courts of justice,
as to be adequate to the idea of the parliament,
there must be some solemn or sacred expressions respecting the omniscience of God, as,
solemnly to declare the truth in his presence,
in which form they thought it more eligible to acquiesce,
than to risque the losing of the bill.
In this form it passed the house of commons.

In order to procure it an easy passage through the house of lords,
the case of friends was re printed and enlarged;
particularly with reference to the Menonists in Holland,
who had since 1577 the indulgence granted them,
that their Yea and Nay should be accepted instead of an oath,
they being subject in case of falsifying the truth to the penalty of perjury,
and no public or private damage had been found to result therefrom.

But although king William had made it his study to fill
up the vacant fees with men of distinguished moderation,
yet there seemed to remain still some bishops of the old cast,
who retained an aversion to the ease intended by bill,
and excepting against the form of affirmation, aimed at defeating the benefit thereof,
by substituting an oath in effect, in a different form,
in place of an oath in the common form.
Instead of the affirmation, as it came from the commons,
they wanted to introduce more solemn asseverations, such as,
I call God to witness and judge, etc.
I call God to record upon my soul,
and appeal to God as a judge of solemn oath the truth of what I say,
etc. which the committee of the meeting for sufferings
being in formed of by some of the temporal peers,
who were friendly, and wished to redress the grievances of the society in this respect,
justly remarked that the end of their solicitation
and petitioning to be freed from all oaths,
as contrary to their conscientious persuasion,
would be manifestly defeated by the imposition of a new oath,
in which light they understood all these proposed forms of expression,
whereinto the invocation of the sacred name as judge or avenger was introduced.
Upon this representation the peers returned into the house,
and entered into a fresh debate, and returning back to the friends in waiting,
informed them that they had brought the bishops to agree to this amendment,
to add after the word +++[+++God]
these words +++[+++the witness of the truth of what I say]
and earnestly persuaded them to agree to the addition of these words,
rather than lose the bill, whereupon the said friends, finding they could do no better,
consented to leave the matter to their discretion; so the bill was finally passed,
with an affirmation in this form, _"`I, A. B. do declare in the presence of Almighty God,
the witness of the truth of what I say.`"_

The act as passed, besides the foregoing, contained the following article.

[.embedded-content-document.legal]
--

Fourthly, And whereas, by reason of a pretended scruple of conscience,
Quakers do refuse to pay tithes and church-rates, be it enacted,
by the authority aforesaid,
that where any Quaker shall refuse to pay or compound for his great or small tithes,
or to pay any church-rates,
it shall and may be lawful to and for the two next justices of peace of
the same county (other than such justice of the peace as is patron of
the church or chapel whence the said tithes do or shall arise,
or any ways interested in the said tithes) upon the complaint of any parson, vicar,
farmer or proprietor of tithes, church-warden or church-wardens, who ought to have,
receive or collect the same, by warrant under their hands and seals,
to convene before them such Quaker or Quakers neglecting
or refusing to pay or compound for the same,
and to examine upon oath,
which oath the said justices are hereby empowered to administer,
or in such manner as by this act is provided,
the truth and justice of the said complaint,
and to ascertain and state what is due and payable by such
Quaker or Quakers to the party or parties complaining;
and by order under their hands and seals to direct and appoint the payment thereof,
so as the sum ordered as aforesaid do not exceed ten pounds;
and upon refusal by such Quaker or Quakers to pay, according to such order,
it shall and may be lawful to and for any one of the said justices,
by warrant under his hand and seal to levy the money thereby ordered to be paid,
by distress and sale of goods of such offender, his executors or administrators,
rendering only the overplus to him, her or them,
necessary charges of distraining being thereout first
deducted and allowed by the said justice;
and any person finding him,
her or themselves aggrieved by any judgment given by such two justices of the peace,
shall and may appeal to the next general quarter sessions to be held for the county,
riding, city or town corporate; and the justices of the peace there present,
or the major part of them, shall proceed finally to hear and determine the matter,
and to reverse the said judgment, if they shall see cause;
and if the justices then present, or the major part of them,
shall find cause to continue the judgment given by the first two justices of the peace,
they shall then decree the same by order of sessions,
and shall also proceed to give such costs against the appellant,
to be levied by distress and sale of goods and chattels of the said appellant,
as to them shall seem just and reasonable;
and no proceedings or judgment had or to be had by virtue of this
act shall be removed or superseded by any writ of _certiorari_ or
other writ out of his majesty`'s courts at Westminster,
or any other court whatsoever, unless the title of such tithes shall be in question.

--

This act for seven years, was at the expiration continued for eleven years longer,
and afterwards in the year 1715 made perpetual;
but the terms of this affirmation being still uneasy to many friends,
who conscientiously scrupling the use thereof,
as in their opinion approaching too near the nature of an oath,
by reason of an implied appeal to God for the truth,
applied for an amendment thereof in the year 1721, and obtained their request.

Whilst king William was studiously endeavouring to relieve the people called
Quakers from their sufferings and hardships to which they were exposed,
the high-church ecclesiastics were contriving to
bring them under the lash of a fresh penal law.
A bill was brought into the house of lords about this time, by the bishop of London,
and warmly promoted by him, for the better payment of church-rates,
small tithes and other church dues, whereby the penalties of the act of 32 Henry VIII.
for the recovery of predial tithes were extended to small tithes,
repairing the public places of worship, clerk`'s wages,
and even the demands of the sexton;
so that for a trifling demand of perhaps less than a shilling any person might
be subjected to the enormous expense of a suit in the ecclesiastical courts,
and if he did not obey the monition of the judge to pay the demands and costs,
he was to be attached, and committed to prison without bail or mainprize,
as specified in the aforesaid act of Henry VIII.
for predial tithes, with this addition,
that the justices may grant warrants to distrain the goods of defendants in such causes,
or imprison if no distress could be found.

A bill of this tendency to bring very severe injury to the people called Quakers
must necessarily awaken the attention of the meeting for sufferings in London.
Having previously procured a copy of the bill, and prepared some exceptions to it,
showing how injurious it would be to the rights and properties of the subject,
and how repugnant to common law and justice, if passed into an act,
and having notice of the day appointed for a committee of the lords to sit upon it,
some of the friends of London were admitted to an audience of the said committee.
The bishop of London being chairman interrogated
them what reason they had to except against the bill?
To which George Whitehead replied,
the same reason that is given in the act of parliament 17 Charles I. for
abolishing the star-chamber and high commission courts,
it being conceived with submission,
that the same reasons may be objected to the present bill,
as giving absolute power to the ecclesiastical courts, their judges and ordinaries,
to pass definitive sentence without appeal,
and conveying to them the power of becoming arbitrary and oppressive,
which were the reasons assigned for abolishing the aforesaid arbitrary courts.

The temporal lords were very civil and kind during the conference,
and after much discourse the bishop asking if they had any exceptions to offer in writing,
was answered in the affirmative, and the following exceptions produced;

[.embedded-content-document.legal]
--

[.blurb]
=== Exceptions against the bill, entitled An Act for the Better Payment of Church-rates, Small Tithes, and Other Church Dues; and for Better Passing Church-wardens Accounts.

[.salutation]
Humbly offered,

It is observed, That in the said bill no appeal to any other or higher court is granted,
or provision made for redress or restitution to the persons wrongfully prosecuted;
nor for the punishment of such as may maliciously or wrongfully prosecute others;
but the ecclesiastical judge is made the sole judge and determiner,
by his definitive sentence,
concerning the penalties upon the persons and personal
estates.--No trial by juries allowed,
although the penalty seems to be two-fold, or of two kinds,
imprisonment of persons and distress of goods.--No discharge
of the prisoner provided when distress is made;
doth not this amount to two punishments for one offence
(supposed) that is loss of liberty and loss of goods,
tending to starve the poor widow and children at home?--No
legal excuse admitted or provided for the party cited,
summoned or prosecuted, suppose he be gone a long journey,
or otherwise unavoidably prevented by his emergent occasions from appearing,
but he must be taken _pro confesso,_ which is to condemn him without hearing.
The penalty the same for not paying the clerks or sexton or church-rates,
as is for not paying small tithes.
Query, How can this be equal or bear proportion?
May not this increase our trouble and sufferings, by thus giving power to so many,
and such prosecutors as clerks, sextons, etc. and on such small accounts as theirs.

Any party or witnesses cited to appear in the ecclesiastical court
are liable to inprisonment upon certificate from the said court,
which is or may be very hard, especially as to our friends,
who cannot for conscience-sake swear in any case.

Whether this bill does not exceed the statute 32 Henry VIII. c. 7. in severity,
and give greater and more absolute power to the ecclesiastical
courts over men`'s persons and properties than ever they had,
excepting the power of the star-chamber and the ecclesiastical commissioners,
or high commission court, taken away, repealed and made void, 17 Car I. chap.
10, 11. An appeal seems allowed, stat.
// lint-disable invalid-characters
Hen. VIII. chap. 7. ยง 3. Here`'s none in this bill.
Imprisonments till sureties to perform the definitive
sentence and judgment of the court ecclesiastical,
but no distress of goods in the interim, by the said statute 32 Henry VIII.
// lint-disable invalid-characters
chap. 7. ยง 4. which yet is very hard and severe of itself.

It is also with submission conceived that other reasons
against this bill may be duly alledged,
and such as formerly did legally and justly induce the parliament
to repeal the statute made the eleventh year of Henry VII. chap. 3.
which was repealed in the first year of Henry VIII. chap. 6.
vide Chief Justice Coke`'s Institutes, part 4, folio 40, 41, and second part, folio 51,
where Richard Empson and Edmund Dudley`'s arbitrary
proceedings thereupon are discovered and condemned,
as well as the said court of star-chamber, and the power of the high commission court,
were taken away by king and parliament, as before quoted.

`'Tis conceived that the same reasons for removing those
courts and repeal of the branch of the said statute,
1 Eliz. (which gave them their power and jurisdiction)
stand good against the present bill,
as being contrary to the great charter and common course of justice,
by giving such absolute power to the ecclesiastical courts and their judges,
to determine and give definitive sentence and judgement
upon subjects personal estates or goods and chattels,
and for confinement of persons; which tends greatly to oppress, burden and ruin them.
Lastly,
the liberty of conscience already confirmed by law may greatly be infringed and lessened,
if the ecclesiastical judges or courts have such absolute power
and jurisdiction given them over men`'s persons and properties,
according to the import of the present bill;
which it is really believed must needs greatly dissatisfy many
thousands of the king`'s conscientious protestant subjects,
and increase the number of prisoners,
of which there are many on the account of conscience already.

--

[.offset]
The bill was laid aside.
