== Chapter XL

Further Account of George Keith.--Bishop Burnet`'s Account
of him.--Remarks thereupon.-- King James dies,
and his Son acknowledged King of England by the French King.--Address of the
People called Quakers to King William.--A forged Address published.--Detected
by the Publication of the real one--King William`'s Death.

George Keith,
who for some time past had been endeavouring to ingratiate
himself with the episcopal clergy,
as the most likely means of getting a support,
had succeeded in his views so far by his vilifying of the Quakers,
and raising expectations of the service he could be of by his influence,
in bringing over many of that people to the established church,
that about this time he was ordained a priest by the bishop of London,
and was employed for the present as a curate.
This furnished an occasion for an anonymous publication under the
title of Mr. George Keith`'s Account of a national Church and Clergy,
humbly presented to the Bishop of London, being a selection from his former works,
in which he had treated of the national church, its clergy, rites and ceremonies,
to which were added some queries he had formerly written
concerning that termed the Sacrament of the Lord`'s Supper,
concluding with these words of the apostle,
"`if I build again the things which I destroyed, I make myself a transgressor.`"

That the episcopalians, even those called dignitaries of the church,
entertained great hopes at this time of the service that this new
convert might be of in bringing many others to their community,
appears from the following extract from bishop Burnet`'s
history of his own times, vol. 2. p. 144, 1700.

The Quakers have had a great breach made among them by one George Keith a scotch-man,
with whom I had my education at Aberdeen, he had been thirty-six years among them;
he was esteemed the most learned man that ever was in that sect;
he was well versed both in the oriental tongues, in philosophy and mathematics;
after he had been above thirty years in high esteem among them,
he was sent to Pennsylvania,
(a colony set up by Penn where they are very numerous) to
have the chief direction of the education of their youth.
In those parts, he said, he first discovered that, which had been always denied to him,
or so disguised that he did not suspect it; but being far out of reach,
and in a place where they were masters, they spoke out their mind plainer,
and it appeared to him that they were Deists,
and that they turned the whole doctrine of the christian religion into allegories;
chiefly those which relate to the death and resurrection of Christ,
and the reconciliation of sinners to God by virtue of his cross;
he being a true christian, set himself with great zeal against this,
upon which they grew weary of him, and sent him back to England.
At his return he set himself to read many of their books,
and then he discovered the mystery,
which was so hid from him that he had not observed it: Upon this he opened a new meeting,
and by a printed summons he called the whole party
to come and see the proof that he had to offer,
to convince them of these errors: Few Quakers came to his meetings,
but great multitudes of other people flocked about him;
he brought the Quakers books with him,
and read such passages out of them as convinced his
hearers that he had not charged them falsely;
he continued these meetings, being still in outward appearance a Quaker for some years,
till having prevailed far as he saw any probability of success,
he laid aside their exterior, and was reconciled to the church,
and is now in holy orders among us,
and likely to do good service in undeceiving and reclaiming some of those misled enthusiasts.`"

I think this not the only instance,
wherein this prelate hath given occasion to the observation,
that he expresseth himself in a manner, very dogmatic, in cases wherein,
he is not well informed.
That George Keith was thirty-six years among the Quakers--that he was sent to
Pennsylvania---that he was sent back by them;-- are facts plainly misstated.
He was by his own.
account about twenty-eight years amongst them when
he first began his open dissent--he removed,
to Pennsylvania of his own accord,
to evade the persecution he was exposed to here-- he returned unsent, and unsent for,
to complain to the yearly meeting, etc.
These mistakes (though of no great consequence) discover the loose and
negligent manner in which Burnet took up and stated matters of fact.
The more important objections to the bishop`'s narrative of this difference
having already engaged the attention of our friend Alexander Arscott,
in an appendix to his Serious Considerations,
etc. remarks thereupon anticipate the necessity of my making many others,
being as follow:

The only foundation of this story, so far as concerns the Quakers,
was George Keith`'s bare relation of it; for it is introduced with these words,
viz. In those parts, he said, he first discovered, etc.
It does not appear that the bishop either read or heard
what the people called Quakers had to say for themselves:
and yet as if he certainly knew that George Keith was perfectly right,
and these people altogether wrong, he pronounces judgment upon an hearing only ex parte;
a method of proceeding utterly inconsistent with the duty of a fair historian;
and which he himself, no doubt, were he living, would loudly exclaim against,
if it concerned himself, or any people whom he was disposed to favour,
or even to do justice to.

It is well known,
that the difference between George Keith and his friends in Pennsylvania, was,
upon an appeal of his from thence,
solemnly heard and debated for many days by the yearly-meeting in London, 1695,
and at last determined in a moderate censure upon him;^
footnote:[Which censure was in the following words,
viz. "`That the said George Keith hath of late been, and yet is,
acted by an unchristian spirit,
which hath moved and led him to stir up contention and strife in the church of Christ,
and to cause divisions, separations and breaches among them that profess the truth:
and that the tendency of divers of his late writings and actings hath been to
expose the truth and the friends thereof to the reproach of the world,
did unanimously agree, and declare it to be the sense and judgment of this meeting:
and it is the sense and judgment of this meeting,
that the said George Keith is gone from the blessed
unity of the peaceable spirit of our Lord Jesus Christ,
and hath thereby separated himself from the holy fellowship of the church of Christ,
and that whilst he is in an unreconciled and uncharitable state,
he ought not to preach or pray in any of friends`' meetings,
nor be owned or received as one of us,
until by a public and hearty acknowledgment of the great offence he has given,
and hurt he hath done, and condemnation of himself therefore,
he gives proofs of his unfeigned repentance,
and does his endeavour to remove and take off the
reproach he hath brought upon truth and friends,
which in the love of God we heartily desire for his soul`'s sake.`"
{footnote-paragraph-split}
From which censure, it is evident,
that George Keith was not (as the defender of the
bishop of Litchfield and Coventry erroneously asserts, p. 98.)
"`excommunicated by the Quakers,
for maintaining the necessity of believing in an outward Christ in order
to salvation.`" Nor does there appear in the whole censure against,
or proceedlngs relating to him, the least footstep of any charge of that nature.
He was disowned for his unchristian and uncharitable actions,
and for the reproach he had brought upon truth and friends,
by his slanders and lying accusations, and particularly,
as it is expressed in one part of the proceedings "`His insinuating as if friends
only owned the blood of Christ in a mystical sense.`" No wonder then,
if Keith, being ejected by the Quakers for his falsehood and abuses of them, did,
as evil men and seducers used to do, wax worse and worse,
kept on the exterior of the Quakers, as a decoy to draw others after him,
so long as he saw any probability of success, or outward support;
which at length failing, he thought meet to be reconciled to a church,
qualified to gratify her new convert with present and constant pay, which yet,
in his case, was not the reward of righteousness.]
and it cannot be supposed but that the meeting had some reasons for such a proceeding.
And it is as well known, that afterwards,
though our friends did not attend his peremptory summons,(chiefly with regard
to the peace and good order of those cities and places where he was pleased to
mount the stage) yet they followed him closely from the press:
and as all these transactions were public to the world, the bishop ought either to have,
said nothing about them, or more than he has said;
either have passed the whole over in silence,
or have given an impartial summary view of the controversy on both sides.

But feeling he has been pleased to be silent on one side,
and condemn us as a company of misled enthusiasts, with his usual air of contempt,
that his readers may not think our friends had nothing
to say in defence of themselves and doctrines;
they are referred to what was written about that time by our elder friends, G. Whitehead,
T+++.+++ Ellwood, B. Coole, R. Claridge, D. Philips, and J. Wyeth.
But we are told, that it appeared to him,
(George Keith) that they (the Quakers) were Deists,
and that they turned the whole doctrines of the Christian religion into allegories.

To the first, that they were Deists: he is inconsistent with himself,
for he calls them afterwards enthusiasts.
Deism and enthusiasm are as opposite as the two poles.
The one denies all revelation; and the other believes and contends for it to an excess.
But to come more closely to the point, Deism, in the modern use of that word,
is the belief and profession of natural religion,
in opposition to revelation of all kinds.
Christianity, in the sense of the people called Quakers,
is the belief and profession of revealed religion,
revealed externally in the holy scriptures,
and internally by the spirit of Christ in the secret of our hearts:
by the first we come to the knowledge of the facts,
doctrines and precepts of the christian religion;
by the last we are enlightened and assisted to understand, apply and practice them,
for the great ends for which they were delivered to the world: so that religion,
in the sense of the Deists, hath nothing to do with revelation; in the Quaker`'s sense,
it is all revelation, either external or internal:
a plain contradiction then between the one and the other,
and consequently they cannot be the same, nor be predicated of the same person or people.
The Quakers therefore cannot be esteemed Deists, which charge is so far from being true,
that upon their principles only, the very root of Deism is destroyed,
as I have already observed.

Again we are told, that it appeared to him, George Keith,
that the Quakers turned the whole doctrines of the christian religion into allegories.

Answer.
I can name many of the doctrines of the christian
religion which they never turned into allegories,
but have been great sufferers for adhering to them in a literal sense, as is well known;
so that this charge, in the extent of it, is false.
But it is not denied,
that the Quakers writ of some of the doctrines of
the christian religion in an allegorical style,
and so did the apostles, even those very doctrines he there mentions,
which relate to the death and resurrection of Christ,
and the reconciliation of sinners to God by virtue of his cross,
as may easily be made appear by many instances.
And the best christians in all ages have done the same,
as is acknowledged by the bishop of London in his Pastoral Letter before cited.
But neither those nor the Quakers did so turn these doctrines into allegories,
as to destroy their proper meanings, or the reality of those facts,
which are always supposed, and taken as a real foundation for the allegory,
and so professed and believed by that people.

Those who have read the writings of our friends with an honest
disposition to be truly informed of their real sentiments,
and who have conversed with them candidly with the same design,
have found the truth of this.
Among whom the learned and pious Dr. Henry More was an eminent instance; who,
though at first he thought the Quakers carried their allegorical way of writing too far,
yet upon better information from reading and conversation with some of them,
became very much changed into another mind, as hath been fully shown in a late pamphlet,
entitled, A vindication of the Quakers,
or an Answer to the Bishop of L----'`s charge against them,
and a late defence of that charge; to which is added,
a more full and perfect account of the Quakers and their doctrines,
occasioned by Dr. Henry More`'s opinion of them;
containing extracts of several letters of the doctor to William Penn and others,
to which the reader is referred; and more largely to the letters themselves,
and other passages, in his life and works.

There is also good reason to suppose that Dr,
Burnet had changed his sentiments of the Quakers, when it is well known,
that he long since published to the world an excellent system of spiritual religion,
altogether agreeable to their principles, entitled, The Life of God in the Soul of Man,
or the nature and excellency of the Christian Religion,
with the method of obtaining the happiness which it proposes:
also an account of the beginning and advances of a spiritual life:
with a preface by Gilbert Burnet.
Wherein he very strongly and pathetically recommends that performance,
the design of which is to explain the nature and properties of true religion,
which the author calls, An union of the soul with God,
a real participation of the divine nature, the very image of God drawn upon the soul, or,
in the apostle`'s phrase, it is Christ formed in us.
Briefly, I know not how the nature of religion can be better expressed,
than by calling it a divine life.
The very terms in which the Quakers often express themselves on the same subject.
And therefore as the bishop has so fully recommended that work to the public,
however he might be misled by wrong representations of their doctrines,
he could not be an enemy to the principles of the Quakers rightly understood.
The whole of that piece is penned with that true spirit of religion and piety,
that I gladly take this opportunity to recommend the perusal
of it to all serious Christians of all denominations.

But to return to George Keith.
The bishop has told us, after a long detail of his performances, that he is now,
in the year 1700, in holy orders among us,
and likely to do good service in undeceiving and reclaiming some of those misled enthusiasts.
But what if it should appear after all, that he deeply repented of what he had done?
I shall relate what has come to my knowledge,
and leave the reader to judge of the truth of it.
The fact as related is this:
That one Richard Hayler of Sussex made a visit to George Keith on his deathbed,
which visit was kindly taken by him; and among other things that passed,
George Keith expressed himself in these words,
viz. I wish I had died when I was a Quaker,
for then I am sure it would have been well with my soul.
This I have from a person now living, of unquestioned reputation,
who had it from the widow of the said Richard Hayler, and her sister,
both since deceased, but persons of unblemished characters.
I shall make no comment upon the expression, but only remark,
that it stands on as good ground of credibility as many thousand
matters of fact that are readily believed without any hesitation,
and is altogether as well, what if I say,
better attested than the bishop`'s partial relation of this whole affair,
and some other facts in his history, wherein the characters of all ranks of people,
living and dead, are treated with an uncommon freedom.
I hope, therefore, I may be excused in this one instance,
at a time when George Keith`'s performances against the Quakers
are so much magnified by the bishop of L----'`s defender,
as well as Dr. Burnet, in letting the world know, that there is reason to believe,
that this conduct of George Keith, at last became his burden,
and that he himself did not approve of it: the consideration of it, I confess,
gives me some secret pleasure, in hopes, that he that gave him this sight,
might give him also the grace of repentance.

To which I may add,
that it appears to me an instance of great weakness or great prejudice
for any man to suffer himself to be imposed upon so far,
as to receive, and record so great an improbability,
as that a man could be for the space of twenty-eight years
in intimate society with so large a body of people,
and never during that time discover their real principles;
or that all the members of that society either would or could artfully
conceal or disguise their real sentiments from a member who was no novice,
but one esteemed by them as a faithful and serviceable member of the same society,
and of the same sentiments with themselves.
But that he first discovered in America any pretended errors of this people,
which he had hot the like opportunity of discovering,
or which he did not discover long before his removal, and approve and maintain too,
is not only improbable, but really untrue.

The matter of controversy between George Keith and
friends in America appears clearly to be this,
whether the knowledge and belief of the history of Christ`'s life, death, sufferings,
resurrection and ascension be necessary to salvation,
to those who have no opportunity or possibility of coming to the knowledge thereof.
Now he could not be ignorant that the people called Quakers
had always taken the negative side of the question,
as esteeming it incompatible with divine justice to condemn
a great part of mankind for the mere ignorance of that,
which they had no means of attaining the knowledge of.
We have seen George Keith join Robert Barclay in his dispute with the students of Aberdeen,
in defence of his Theses, the sixth of which is particular upon the subject;
neither was he unacquainted with his more explicit arguments thereupon in his apology.
But further George Keith himself in his former writings maintained the same doctrine,
having declared it as his sentiment,
that those men who had not the matter of Christ`'s outward birth, death,
resurrection and ascension revealed or made known to them;
yet living faithful to what by his light and holy spirit was manifested to them,
should be saved, though they died in that state,
and that the contrary doctrine was uncharitable, and argued thus upon it;
"`Why may not the benefit of Christ`'s taking upon him the form of
man redound unto many who do not expressly know it,
even as a diseased person may receive benefit of a cure applied to him,
though he have not an express knowledge of all the means and ways, how,
from first to last, it hath been prepared.`"^
footnote:[See his book, entitled The Rector Corrected.]

This being the original subject of George Keith`'s open dissent, it is evident,
it was not in America he first discovered it to be the doctrine of the Quakers,
he being well acquainted with it, and having adopted it in England long before,
where it was openly professed and vindicated, and never, as far as I have heard or known,
denied or disguised, in the least, by any under that name, till he denied it,
in contradiction of his former avowed sentiments,
both in his public preaching and private discourses;
and when it was urged against him how hard it would be upon honest Gentiles, who,
though they steered ever so exactly by the law written in the heart,
must notwithstanding for want of that knowledge they had no means of attaining, perish,
without remedy; he would recur to his capricious notion of transmigration, and answer,
they could not perish, though they should die in that state;
but would have an opportunity to hear the gospel preached,
and of being saved thereby in some future revolution.^
footnote:[Samuel Smith,
from whose manuscript principally I have extracted
the narrative of George Keith`'s proceedings in America,
informs us that the substance of the whole is taken from the memorials of Caleb Pusey,
a man of undisputed veracity, an intimate friend of George Keith,
before he left the society, and concerned in opposing him afterwards;
who wrote these memoirs of transactions, in which he was personally engaged.]
I wonder what tenet of the Quakers he could tax with
heterodoxy or absurdity equal to this.

This year put a period to the life of king James,
who died at the palace of Germains in France the 17th September,
and upon his death his son, by order of the French king,
was proclaimed king of the British dominions.

As the parliament had just settled the succession to the crown, in Sophia,
electress of Hanover, and her heirs,
in case of the death of king William and the princess of Denmark with out issue,
this interference of a foreign prince,
to assign another king to England than they chose for themselves,
roused the general indignation of the people.
Addresses were sent up from all quarters expressive of gratitude for the revolution,
and loyalty to the king and the

house of Hanover.
Upon this occasion the people called Quakers also,
who had heretofore chiefly complaints of grievances to lay before their rulers,
from most of which they were effectually delivered by the present sovereign,
thought themselves called upon in point of duty and gratitude to wait
upon him soon after his return from Holland with the following address,
which was presented by George Whitehead, '`William Mead and Francis Camfield, viz.

To King WILLIAM III.
over England, etc.

An Address from the People commonly called Quakers, humbly presented.

May it please the King,

We thy dutiful subjects sincerely express our joy for thy safe return to thy people,
having great cause to love, honour and pray for thee,
as a prince whom we believe God hath promoted and principled for the good ends of government,
under whose reign we enjoy great mercies and favours,
and particularly that of liberty to tender consciences in religious worship,
as a proper expedient to unite thy protestant subjects in interest and affection.

For which great mercy we cannot but be humbly thankful to God,
and renew our grateful acknowledgment to the king,
whom God by his almighty power hath eminently preserved,
and made exemplary in prudence as well as goodness to other kings and princes,
whereby thy memorial will be renowned to posterity.

We are also engaged to bless the Lord,
for that he hath manifestly frustrated the mischievous and
treacherous designs of thine and the nation`'s adversaries,
both against the lawful establishment of thy throne,
and the true interest of thy protestant subjects.

And we beseech almighty God to bless the good designs
and just undertakings of the king and his great council,
for the good of his people, and for obtaining to Europe a firm and lasting peace;
and continue thee, O king, a blessing to these nations,
establish thy throne in mercy and truth,
give to thee a long and prosperous reign over us, and hereafter a glorious immortality,
is, and shall be the fervent prayer of us, thy true and faithful subjects.

Signed in behalf and by appointment of the aforesaid People, at a meeting in London,
the 8th month, 1701.`"

This address was favourably received by the king, who, in answer, replied,
"`I have protected you, and shall protect you.`"
and repairing to his closet he perused the said address over again,
and it was understood that he expressed his particular approbation thereof.
But it being some days before it made its appearance in the Gazette,
some news-writers in the intermediate time (as had been done in the beginning
of king James`'s reign) fabricated a very ridiculous piece,
purporting to be the address of the people called Quakers to the king,
in which the expressions are represented to be so blunt and unmannerly,
as bespoke audacity and insolence, rather than the honest simplicity of the Quaker;
and in which the fabricator might probably gratify his spleen
against the Quakers and his sovereign together;
but the real address being soon after published detected the forgery.

King William`'s health had been some time on the decline,
and a fall from his horse hastened his dissolution.
He departed this life at Kensington the 8th day of the month called March 1702,
in the 52nd year of his age;
leaving deep impressions of gratitude to his memory in the minds of many of his subjects,
who were sensible of his important services and the benefits thereof,
in rescuing them from the impending danger of a popish government,
and securing to them the free and full enjoyment of civil and religious liberty:
the dissenters especially,
who considered him as their friend and protector for the
early and effectual immunities his reign secured to them,
in exempting them from the penalties of sundry laws, which,
in the reigns of his predecessors, had exposed them to a variety of damage and distress.
