== Chapter XII. Ireland.

Care of Friends to preserve their Members from too anxious a pursuit of
Riches.--Sentiments of Friends in Ireland in respect to the Affirmation.
--Their Zeal and Care in supporting Discipline.
--William Penn,
Thomas Story and John Everot visit Ireland.--Meetings largely attended.--John Plympton
publishes an abusive Paper.--Complaint against
him.--Meeting at Cashell ordered to disperse.--William
Penn`'s Conference with the Bishop thereupon.--The Bishop writes to the Lords Justices.
--A Province Visit performed.-- Epistle from the Province-meeting at Castledermot.

Peace being restored to this nation, plenty and prosperity quickly followed.
This fruitful island, thinned of its inhabitants by the late war,
both by the number who fled for refuge to other countries, and the number who perished,
afforded those who kept their habitations and survived,
who had been despoiled of all their property,
and had felt all the distress of penury and scarcity during that calamitous time,
an opportunity of soon emerging from a state of want to plenty,
and from poverty to competency and to affluence,
even beyond what could be expected in the usual course of things.
Both agriculture and commerce being in few hands,
and the former applied to fertile land which returned great increase with little labour,
more than sufficient for the support of the remaining inhabitants,
especially in the fine grazing lands;
and the latter employed in the exportation of the superfluity to advantage,
soon presented a tempting bait to pursue the accumulation of property with ardour.
And now a second generation being risen and arising amongst this society,
who held the profession as the religion of their education,
and not by the purchase of giving up all for its sake, as their predecessors had done,
too many pf these appeared in danger of being carried away with the stream,
and of being drawn aside by the tempting prospect into an inordinate pursuit of wealth,
beyond the limits of a truly religious disposition,
and to the obstruction of their growth in religious experience.

Yet the main body of the society consisted pf some of the old stock who still survived,
and several of the present generation,
who actuated by a serious concern for their eternal well-being,
sought it in the way of self denial and the daily cross,
as their elder brethren and fathers had done;
and made the religion of their education that of their judgment,
and the rule of their conduct in life.
These clearly perceiving the injurious consequences likely to arise to
the present and future generation by indulging this worldly disposition,
and the danger of friends and their posterity resuming
the spirit and customs of this world,
from which their fathers had a pursuit of been redeemed,
by which means they might be led into forgetfulness of the eminent care of providence,
who had in great mercy preserved them safe through all the late seasons of calamities,
on these considerations were incited in point of duty as
faithful watchmen to give timely warning of the danger.
Many admonitions and exhortations from their meetings of discipline
were sent forth for exciting their friends to vigilance,
and to keep within the limits of pure religion in their temporal engagements,
and under the guidance of divine grace, which would teach them to deny all ungodliness,
and worldly lusts.
In this pious concern they were encouraged by the
consolation with which they were favoured therein,
and endued with wisdom in directing their measures for preventing the progress of this
worldly spirit so that their zealous endeavours were attended with a good effect.

It was in the year 1693 that an application to the parliament of England,
to request their indulgence to the people called Quakers,
in accepting their solemn affirmation instead of an oath,
was first undertaken to be made by friends of that nation,
which when their brethren in Ireland understood,
they took the brotherly freedom of writing an epistle on the subject,
to the meeting of sufferings in London, desiring that Christ`'s own words,
yea and nay might be adhered to, if possible, recommending rather to exercise patience,
and wait God`'s time, to open a clear and free way for their assertion of the truth,
than to accept such a form of affirmation,
as might bring a snare or burden upon any tender consciences,
by appearing in any degree similar to an oath.

And in the year 1695,
when the government of England was pleased to favour them with an act of parliament,
prescribing a form of an affirmation instead of an oath;
although it was rather dissatisfactory to many friends in Ireland,
by reason of the sacred name being comprised there in,
which they considering as an appeal to the divine Being,
thought it bordered too near upon an oath, and were not free to use it.
Others less scrupulous, gratefully accepted the favour,
conceiving it only in the light of a very solemn affirmation.
This difference of judgment how ever was productive of no schism;
but the spirit of christian charity and mutual forbearance appeared
conspicuously amongst the members of this society at this time.
Those who scrupled the use thereof, not harshly judging those who were free to use it,
and these latter sympathising in the difficulty under which the
tenderness of their consciences brought others of their brethren,
were earnestly disposed to cooperate with them in
procuring an universal ease to all the members.
When they met at the next yearly meeting of London,
an edifying harmony appeared amongst the friends of both nations,
and it was resolved unanimously to solicit government,
as soon as providence should open the way, for granting a form of affirmation,
which might be easy to all.

As this society became numerous in that nation,
the advantage and necessity of a salutary discipline had become obvious,
and was immediately adopted by friends there,
upon the notice of its being established by their brethren in England,
and without any of that opposition,
which occasioned so much trouble to their said brethren ;
the benefits of the religious and brotherly care for each other, during the late war,
having been evidently manifested,
had confirmed the judgment of friends generally in favour of a
zealous exertion of care and endeavours for the preservation of
friends in the uniform practice of piety and virtue,
and the cultivation of a pure and religious disposition in their minds,
as well as to relieve and help them in their outward circumstances,
which at this time were so remarkable, as to gain the commendation of most friends,
who were engaged in the love of the gospel to visit them.

John Gratton, of Moneyash, in Derbyshire, in particular, an able minister,
visiting Ireland this year,
hath in his journal left the following testimony concerning them.

That, "`there was great love, peace, and concord amongst them,
and good order and government in a careful oversight of the flock,
that friends be careful in all respects, to keep their profession without blame,
and particularly that none run inordinately after the world,
or break in other men`'s debts.`"

And friends of Bristol, in an epistle from their men`'s meeting,
express their approbation in the following terms:

Your love to the holy cross of our Lord Jesus,
and your zeal for promoting the way thereof, by a strict and close discipline,
is that which is much wanted in many places;
and though ignorant and malicious spirits may (as they have done) carp at it,
and cry out against it as an imposition on conscience,
God Almighty hath blocked up their way, and spoiled the spoiler,
and manifested their folly to all, the necessity of a holy care in the church,
more and more daily appearing.

But the amplest testimony of approbation, is that of William Penn, who,
in company with John Everot and Thomas Story, set out from Bristol,
at that time the place of his residence, in the 2nd month 1698,
to visit friends in Ireland.
They landed in Dublin the 6th of 3rd Month O. S.
and the half year`'s meeting began on the 8th,
wherein Thomas Story writes, they were greatly comforted,
not only in the enjoyment of the divine presence; but also in observing the unity,
mildness, and order, which appeared among Friends,
in the management of the affairs of the church in that meeting.

The resort of people of all ranks, qualities, and professions to the meetings,
was very great, chiefly to hear William Penn,
who was furnished with matter to answer their expectations,
and his preaching gained the assent and commendation of the audience in a general way.
Many of the clergy attended amongst others, and amongst them the dean of Derry,
who being at several meetings, was asked by his bishop,
whether he heard anything but blasphemy and nonsense,
and whether he took off his hat in time of prayer; to which he replied,
that he heard no blasphemy nor nonsense, but substantial truth;
and did not only take off his hat at prayer, but his heart said amen thereto.

Here they met with John Plympton, a tenacious baptist teacher,
whose pertinacity in opposition and envy,
William Penn had experienced before in a dispute at Melksham, in Wiltshire.
This person had published a very invidious and abusive paper against friends in general,
and William Penn in particular, in intemperance of language outraging common civility.

Upon this several persons applied to the chiefc elders and the meeting of that people,
to inform themselves whether this work was with their consent or approbation; and they,
with becoming candour and concern, disclaimed having any hand in it,
but that it was altogether Plympton`'s own work, and disowned him there in.
So looking upon him as a wrangler, they thought him not worthy of notice at that time:
But afterwards William Penn publishing a paper,
entitled _Gospel Truths Held by the People Quakers,_
subscribed by himself and three others of his friends,
Plympton`'s enmity was roused again to appear in print in a piece
to which he prefixed the invidious title of _The Quaker No Christian._
William Penn also reprinted the 8th and 9th chapters of his [.book-title]#Primitive Christianity Revived,#
which clearly exposed to the public the falsity of Plympton`'s charges and reflections.

In the course of his visit, coming to the city of Cork,
William Penn paid a visit to the bishop, and presented him with the above said paper,
called _Gospel Truths,_ which he seemed to receive favourably, but afterwards,
unexpectedly, published some exceptions against it; to which William Penn,
after his coming back to England, replied in,
a defence of a paper entitled _Gospel Truths Against
the Exceptions of the Bishop of Cork.

I look upon it as unnecessary to attend them through the whole course of their visit;
but only to take notice of one or two remarkable occurrences.

At Ross, in the county of Wexford, they met with an interruption in their journey:
There was a law at that time in Ireland,
that no Papist should possess a horse of the value of 5£. 5s. or upward;
that any horse being in possession of one of that denomination,
any protestant making information thereof,
and tendering the owner 5£. 5s. before a magistrate, might possess himself of such horse:
And all to be deemed papists, who should refuse to take the oaths,
and subscribe the declaration, upon tender thereof.

Two officers, quartered in Ross, thought to avail themselves of this law,
by seizing these friends`' horses, and obtained a warrant from the sovereign of Ross,
for that purpose, denominating the friends papists, within the construction of the act,
because they held it unlawful to take an oath.

By this warrant the horses of four of the friends were seized, but two returned,
being worth little more than 5£. 5s. but the horses
of William Penn and his son they detained,
being of much greater value; whereupon two friends, Joseph Pike, of Cork,
and Thomas Cuppage, of Lambstown, went to the magistrate, and took out a replevin;
Thomas Cuppage giving bond to stand the trial,
by which they regained possession of the horses.
The disappointed officers, enraged hereat, threatened what they would expend at law;
but were prevented of giving the friends any further trouble.

For William Penn wrote to the Lords Justices an account of this transaction,
who immediately let these officers know their displeasure at their disingenuous proceedings,
by ordering them to be confined to their chambers:
And being apprehensive of the consequence,
they procured application to be made to William Penn,
to entreat him to write again for their release, and to prevent their being broke,
who finding them brought to a sense of their error, readily complied with their request;
upon which they were released and forgiven, for which they appeared very thankful.
Thus terminated this business, without much inconvenience to the friends concerned,
further than preventing some of them from reaching Waterford in time,
to the meeting they had appointed there.

Proceeding in their journey to Cashel, the county of Tipperary,
they met John Vaughton and Samuel Waldenfield, from London:
And being the first day of the week,
the meeting was crowded by a multitude of people
of various notions and ranks in that place.
The meeting being gathered, the mayor of the town, with constables, etc. came,
by direction of the bishop of the place, and commanded them, in the King`'s name,
to disperse, though he could not get into the house for the throng.
John Vaughton, upon this, remarked "`that he, with some other friends, had,
upon a late occasion, been admitted into the King`'s presence;
and the King was pleased to ask,
if we had full liberty in all his dominions to exercise our religion without molestation,
and we, not knowing any thing to the contrary, answered in the affirmative.
To which the King was pleased to reply, that if any did disturb us therein,
to make it known to him, and he would protect us.
And here thou disturbest our meeting, and commandest us, in the King`'s name, to disperse;
but I appeal to this audience, whether we should obey thee without law,
or gratefully accept the King`'s protection according to law.`"

To this Thomas Story added, "`that the high priests, scribes, and pharisees, of old,
were the greatest enemies of Christ and his apostles;
and that generally where mischief appeared in any nation, that set of men, in every form,
were at the bottom of it, and so it is still to this day.`"

William Penn, being detained in writing some letters of importance,
while the meeting was gathering, had not yet come in;
but taking an opportunity to speak with the mayor,
(whom he treated with the respect due to his office) he requested him to go,
and let the bishop know, he would wait upon him at his own house, after meeting,
and desired his patience until then.
The mayor assented and withdrew: And then William Penn went into the meeting.
The meeting was much favoured, and every instrument fitted for his share of the labour;
and the people generally satisfied with what they heard and felt.

The meeting being ended, William Penn, taking two or three friends along with him,
went to the bishop, with whom he expostulated concerning that transaction,
telling him "`it looked a little extraordinary, as the case then stood,
when a general liberty was granted by law,
to the King`'s subjects in all his dominions.`" The
bishop treated William Penn in a friendly manner,
and, in his excuse, said, "`that he went that morning to church, as usual; and,
when there, had no body to preach to but the mayor, church-wardens,
some constables and the walls, the people being all gone to your meeting; which,
I confess,`" said he, "`made me a little angry;
and I sent the mayor and constables with that message,
in hopes by that means to procure a greater auditory; though I have no ill will to you,
or those of your profession.`" And they parted in seeming friendship.

But afterwards,
recollecting that his proceeding could not be justified under the present laws,
except the meeting had been attended with some extraordinary and unlawful circumstances;
the bishop to apologize for his conduct, wrote to the lords justices, to inform them,
though causelessly,
"`that Mr. Penn and the Quakers had gathered that day such a multitude of people,
and so many armed papists, that it struck a terror into him and the town;
and not knowing what might be the consequence,
he had sent the mayor and other magistrates to disperse them;
but seeing they had taken no notice of him, or the civil powers there,
he thought it his duty to lay the matter before their lordships,
that such remedy might be applied, as in their wisdom they might think proper,
to obviate the danger and ill consequences of such assemblies.`"

When William Penn and his companions arrived at Cork,
finding the lords justices arrived there before them, William Penn,
for whom they had entertained a great regard, went to pay them a visit:
After mutual salutations,
the earl of Galway gave him the bishop of Camel`'s letter to read, which having done,
he related to them the real circumstances of the case, telling them,
"`that he did not see any armed persons there,
unless here and there a gentleman might have a sword, as usual;
but that he knew nothing of what religion they were.
Then the earl, calling the bishop "`old dotard!`" said,
"`why should he make all this ado upon so common an occasion.`" And that
was all the forward man got by busying himself beyond his sphere.

From Lambstown, in the county of Wexford,
they wrote the following epistle to the yearly meeting in London,
conveying an account of their service,
and the state of their religious society in that nation.

To the Yearly Meeting at London.

Dear Friends and Brethren,

It is not the least of our exercises, that we are thus far outwardly separated from you,
at this time of your holy and blessed solemnity:
But because we have good reason to believe it is in the will of God,
we humbly submit to his ordering hand, and with open arms of deep and tender love,
embrace you our living and loving brethren,
who are given up to serve the lord in your generation,
and that have long preferred Jerusalem, and the peace and prosperity of her borders,
above your chiefest joy.
The salutation of our endeared brotherly love in Christ Jesus is unto you,
desiring that he may richly appear among you in power, wisdom, and love,
to guide your judgments and influence your spirits,
in this weighty and anniversary assembly,
that so nothing may appear or have place among you,
but what singly seeks the honour of the Lord, the exaltation of his truth,
and the peace and establishment of his heritage.
For this, brethren, you and we know, has been the aim,
end and practice of those whom the Lord hath made willing
to forsake and give up all for his name`'s sake,
and through various exercises and tribulations, yea in the way of the daily cross,
and through the fight and baptism of many afflictions,
to have their conversation and sojourning here below upon the earth, in fear and love,
looking for their reward in the heavens that shall never pass away,
who have not been lifted up by good report, nor cast down by evil report,
from their love to the Lord and his precious truth, but hold on their way,
whose hands being clean of evil things towards all men,
have waxed stronger and stronger in the Lord.
Wherefore, dear brethren, let us all be found in the same steps,
and walking in the same way, not being high-minded, but fearing the Lord,
that we may serve him through our generation in diligence and faithfulness,
and former into the rest that God has reserved for his true
travellers and labourers in his vineyard.

And now, dear brethren,
know that the Lord hath brought us well into this kingdom of Ireland,
and given us many large and blessed opportunities in several parts,
meetings being crowded by people of all ranks and persuasions, especially at Dublin, who,
for ought we have heard, have given the truth a good report;
and indeed the Lord has mightily appeared for his own name,
and owned us with a more than ordinary presence, suitable to the occasions,
and made very heavy and hard things easy to us, because of the glory of his power,
with which he assisted us in our needful times, for which our souls bow before him,
and bless, reverence and praise his holy and worthy name.
So that, dear brethren, we have good tidings to give you of truth`'s prosperity at large,
and more especially in the churches,
having had the comfort of the general meeting of this nation,
consisting of many weighty brethren and sisters, from all parts thereof,
which was held in the city of Dublin in much love, peace and unity for several days,
wherein we had occasion to observe their commendable
"` care for the prosperity of the blessed truth,
in all the branches of its holy testimony, both in the general and in the particular,
improving the good order practised among the churches of Christ in our nation.

Indeed their simplicity, gravity, and coolness in managing their church affairs;
their diligence in meetings, both for worship and business;
their dispatch in ending differences and expedients to prevent them;
but especially their zeal against covetousness and indifference in truth`'s service,
and exemplary care to discourage,
an immoderate concern in pursuit of the things of this life,
and to excite friends to do good with what they have, very greatly comforted us,
and in the sweet and blessed power of Christ Jesus the meeting ended and friends departed.
The Lord grant that you may also make the same purpose the travail of your souls,
and end of your labour and service of love, who seek not your own things,
but the things of Jesus Christ, in this your solemn general meeting.

And dear bretheren,
we must tell you here is room enough for true labourers in God`'s vineyard,
and cannot well forbear to recommend the service of truth, in this nation,
to your serious consideration,
if haply the Lord may put into the hearts of any faithful and weighty brethren,
to visit it in the word of eternal life; for we cannot but say,
the harvest appears to us to be great, and the labourers in comparison but a few.
So in that love which many waters cannot quench,
nor distance wear out of our remembrances,
and in which we desire to be remembered of you to the Lord of our household,
we dearly and tenderly salute you, and remain

Your loving and faithful brethren,

William Penn

John Everott

Thomas Story

Lambstowne, 2nd of the 4th Month, 1698.

This epistle confirms the truth of the preceding
remarks concerning the care of friends in Ireland,
to guard the members of their society against an immoderate engagement in temporal pursuits,
which seems to have been an earnest and growing concern:
For about this time a general provincial visit was appointed and performed,
i.e. a visit to every particular men`'s meeting through each province,
in order to inquire into the state of each meeting;
and how the wholesome exhortations and admonitions,
imparted from the half year`'s meetings,

had been put into practice;
and an account was returned to the succeeding national meeting,
of the great satisfaction and comfort,
which the friends concerned were favoured with in their service,
under the feeling of divine assistance with them;
and finding a condescending temper of mind in those that were visited,
so as to receive their advice with cordiality, and readily to comply therewith;
some of whom had been prevailed with to lessen their outward concerns,
that their moderation might appear,
and they be more at liberty in body and mind to attend to the important work of salvation,
and to fill up their places in society with greater fidelity; others,
who were possessed of large holdings of lands, to accommodate their poorer brethren,
who wanted smaller tracts at reasonable rates.

They also published and dispersed an epistle from the province meeting of Leinster,
held at Castledermot, the 9th, 10th, and 11th days of 7 month this year,
on the same subject,
which affords us a specimen of the spirit and sentiments
of the faithful elders of this time,
and of the just conceptions they had of christian simplicity and self denial,
taking it in its proper latitude and extent; not confining it,
as too many are ready to surmise, to superfluousness of apparel,
or a peculiar mode of speech and address; but extending it to every object of pursuit,
so far as it is intemperately followed, to the obstruction of our progress in religion,
and the carrying away the mind from the steady pursuit
of those things that conduce to our peace.
The cares of this life,
and the deceitfulness of riches they considered to be as dangerous
snares to the men of great business as airiness of deportment,
and fondness for pleasure and vanity are to the youthful and inconsiderate;
that the good seed was as effectually hindered from bringing forth fruit in the thorny,
as in the highway or stony ground, in the parable.
And we must admit it to be a standing evidence of the spiritual wisdom,
and foresight of these men,
that the pernicious effects of the unbounded love and pursuit of temporal
treasures upon the spiritual prosperity of our christian society,
have been too manifestly confirmed by the event in succeeding times.
This epistle is recorded at length in Dr. Rutty`'s [.book-title]#History,# to which I refer;
but the preface, written by Thomas Trafford, and the postscript, by William Edmundson,
the former explaining the motives and authority of the friends in their concern,
and the latter briefly recapitulating the subject,
I think not unworthy of introducing in this place,
as a specimen of the sense and judgment of Our friends of this age and place.
"`Love not the world, neither the things that are in the world:
If any man love the world, the love of the Father is not in him.`" 1 John 2:15.

=== PREFACE.

Dear Friends,

The following epistle is recommended to be read in the fear of the Lord, in which,
I doubt not, you will have a sense of the religious care and concern,
which the Lord hath raised in the minds of some of his faithful elders,
for the good and preservation of his heritage.
But if there be any amongst ourselves or others,
not acquainted with our christian discipline, who,
for want of truly seeing the great danger and hurt
that hath attended the professors of Christianity,
by unbounded desires, and pursuit after the things of this world,
shall censure our christian care,
as if we went about to exercise lordship over one another,
or would hinder or limit such industrious and capable persons, who in the fear of God,
and in moderation, do improve the creation in general,
or their own worldly talents in particular, which God hath been pleased to give them;
I say, if any shall thus judge of our godly care and endeavours,
let all such know they are mistaken, and that no such thing is intended.
But as a people whom the Lord hath made sensible of the many, snares that do attend,
and the loss some have sustained by the insatiable desire,
and too eager pursuit after the lawful things of this world,
we felt a concern to attend our minds, that if possible,
we might be limited within the bounds of truth, which leads to moderation and content;
and to depend upon the providential hand of the Lord,
that will afford us what we stand in need of,
rather than indulge an inordinate desire after accumulating a superfluity of wealth,
or pursuing after the gain of this world`'s goods.

And now, dear friends and brethren, this brotherly caution arises in my heart to you,
who were eye witnesses and partakers of that wonderful and eminent,
bowing power and presence of the Lord God, that appeared amongst us at that meeting,
that none who were witnesses thereof,
and thereby brought chap into a lively sense of the great danger attending that mind,
that would be going after covetousness, may give the least way thereto,
or enter into reasoning with flesh and blood,
by which you will lose the sense you then had of that spirit,
and be in danger of becoming monuments of God`'s displeasure.
But, on the contrary, keep to the guidance of God`'s spirit in yourselves,
which will limit your desires after the lawful things
of this world within the bounds of moderation,
which is the earnest desire of one, who desires the good and preservation of all,
in that, which will tend to the glory of God, and bring everlasting comfort in the end.

THOMAS TRAFFORD.

POSTSCRIPT

At the first, when the Lord called and gathered us to be a people,
and opened the eyes of our understandings, then we saw the exceeding sinfulness of sin,
and the wickedness that was in the world;
and a perfect abhorrence was fixed in our hearts against all the wicked, unjust, vain,
ungodly, unlawful part of the world in all respects;
and we saw the goodly and most glorious lawful things of the world to be abused:
And that many snares and temptations lay in them,
and many troubles and dangers of divers kinds; and we felt the load of them,
and that we could not carry them and run the race the Lord had
set before us so cheerfully as to win the prize of our salvation;
so that our care was to cast off this great load and burden
of our great and gainful ways of getting riches,
and to lessen our concerns therein,
to the compass that we might not be chargeable to
any in our stations and services required of us,
and be ready to answer Christ Jesus our captain that
called us to follow him in a spiritual warfare,
under the discipline of his daily cross and self-denial;
and then the things of this world were of small value with us,
so that we might win Christ, and the goodliest things of the world were not near us,
so that we might be near the Lord, and the Lord`'s truth outbalanced all the world,
even the most glorious part of it.
Then great trading was a burden, and great concerns a great trouble; all needless things,
fine houses, rich furniture, and gaudy apparel, was an eye-sore;
our eye being single to the Lord, and the in shining of his light in our hearts,
which gave us the light of the knowledge of the glory of God,
which so affected our minds, that it stained the glory of all earthly things,
and they bore no mastery with us, either in dwelling, eating, drinking, buying, selling,
marrying, or giving in marriage; the Lord was the object of our eye,
and we all humble and low before him, and self of small repute;
ministers and elders in all such cases walking as good examples,
that the flock might follow their footsteps as they followed Christ in the daily cross;
and self-denial in their dwellings, callings, eating, drinking, buying, selling,
marrying, and giving in marriage;
And this answered the Lord`'s witness in all consciences,
and gave us great credit amongst men.

And as our number increased, it happened that such a spirit came in amongst us,
as was amongst the Jews when they came out of Egypt,
and this began to look back into the world,
and traded with the credit which was not of its own purchasing,
and striving to be great in the riches and possessions of this world; and then, great,
fair buildings in city and country, fine and fashionable furniture,
and apparel equivalent, with dainty and voluptuous provision,
with rich matches in marriage,
far wide from the footsteps of the ministers and elders the Lord
raised and sent forth into his work and service at the beginning;
and far short of the example our Lord and master Jesus Christ left us,
when he was tempted in the wilderness with the offer of all the kingdoms of the world,
and the glory of them, and despised them: And Moses,
that refused to be called the son of Pharoah`'s daughter,
and rather chose affliction with the Lord`'s people,
having a regard to the recompense of reward.
And the holy apostle writes to the church of Christ, both fathers,
young men and children, and advises against the love of the world,
and the fashions thereof: And it is working as the old leaven at this very time,
to corrupt the heritage of God, and to fill it with briars, thorns, thistles and tares,
and the grapes of the earth, to make the Lord reject it, and lay it waste.
But the Lord of all our mercies,
whose eye hath been over us for good since he gathered us to be a people,
and entered into covenant with us, according to his ancient promise,
is lifting up his spirit as a standard against the invasion of this enemy,
and is raising up his living word and testimony in the hearts of many,
to stand in the gap which this floating, high, worldly, libertine spirit hath made,
and that is gone from the footsteps of them that follow Christ as at first, and know him,
to bound them, and to keep in his bounds;
and not in their own will and time lay hold on presentations
and opportunities that may offer to get riches,
which many have had and refused for truth`'s sake,
and the Lord hath accepted as an offering, and rewarded to their great comfort,
and to the praise of his great name.

WILLIAM EDMUNDSON.

This year died James Greenwood, and Ann his wife, of Grange, in the county of Antrim,
a faithful couple,
being of one spirit (as well as joined together in the covenant
of marriage) wherein they were true help-meets to one another,
being endowed with many spiritual gifts and graces, which they, as good stewards,
faithfully improved to the honour of the great Giver,
and the benefit and comfort of his people.
They were of such a just and upright conversation, fearing the Lord and eschewing evil,
that the truth they professed was honoured by them;
their hearts being seasoned by the heavenly grace, so that they were as the savoury salt,
among those with whom they were conversant, being of a grave and weighty deportment,
aiming at the glory of God and the good of souls in their concerns.
They were strict observers of the apostle`'s exhortation,
not to forget to entertain strangers,
their house and hearts being open to receive the travelling servants of the Lord;
for which service they were well qualified,
administering to them spiritual help and assistance, as well as outward entertainment.
James being for many years infirm in body, was unable to travel much abroad;
but Ann being healthy, both in body and mind,
was frequently serviceable at the general meetings of friends,
where she appeared in such sweetness and evenness of temper, so savoury, grave,
deliberate and reaching in her expressions,
that such as were in the service with her were much strengthened and encouraged,
by the excellent fruits of the divine spirit that appeared through her, both in doctrine,
discipline, and conversation.
Her words in her testimony were but few and not forwardly expressed,
she being careful not to run before her guide, but to observe divine conduct,
under which her example was a check to forward and rash appearances;
yet she was a nursing mother to the young and tender, a refresher of the weary,
an encourager of the distressed, and was endued with heavenly wisdom,
and a taking way of expression and gesture in conference,
that even disorderly and obstinate persons were oftentimes won upon by her.
They both died in the same year, in great resignation and assurance of peace with God.
