== Chapter XIII. America.

[.chapter-synopsis]
* Account of John Delaval
* Ditto of Thomas Lloyd
* Robert Wardel and Robert Barrow visit America
* Robert Wardel dies in Jamaica
* Account of Robert Barrow
* His Imprisonments and Sufferings in England
* His Visits to Ireland
* His Shipwreck in the Gulf of Florida
* The Succession of grievous Calamities which he and the Company endured among the Indians, and on the Way to Augustine
* He arrives at Philadelphia in a very weak State,
* Three Days after dies there
* Some of the Partisans of George Keith continue to be troublesome
* Several others of them return to the Society
* Caleb Wheatley`'s Acknowledgment
* Epistle to the yearly Meeting
* Account of Welsh Settlers
* Visit of Thomas Story and Roger Gill
* Epidemical Distemper in Philadelphia
* Roger Gill dies of it
* William Penn`'s second Voyage to Pennsylvania

In the latter end of 1693, died John Delaval, who,
in the early settlement of these provinces, was a captain of militia at New-York,
and being Account of convinced there,
about the time that Thomas Musgrave and Jonathan Tyler visited those parts,
after some time he appeared in the ministry, and removed to Philadelphia,
where he continued his residence, except when he travelled in the work of the ministry.
He is said to have been partly concerned with George Keith, in answering Cotton Mather,
and in his latter time in controversy with the said George Keith also.
His benevolence and universal spirit procured the public esteem;
he maintained an amiable character, and kept his integrity to the day of his death.

In this year Thomas Lloyd, deputy governor of Pennsylvania,
finished his course in this life.
He was younger brother to Charles Lloyd, of Dolobran, in Montgomeryshire;
descended from a family of repute and good estate,
of the rank of gentry in their native country.
His father, a man of great esteem, gave him art education suitable to his rank in life,
at the best schools his country afforded,
and afterwards sent him to the university of Oxford, to complete his studies;
in which his proficiency procured him a degree of distinction above many of his fellows.
His natural abilities thus improved by the acquisition of useful knowledge,
recommended him to the regard of many persons of superior rank,
by whom he was proffered posts of preferment;
but being favoured with a religious turn of mind,
he was enlightened to discern the vanity and the danger of worldly honours and dignities;
and being about the fame time convinced of the truth
of the doctrines of the people called Quakers,
he, like Moses, chose rather to suffer affliction in the way of peace,
than barter it for eminence, preferment, and riches in this world.
Being endued with strength and resolution to take up the daily cross and deny himself,
whereby his natural will and affections were crucified,
the wisdom that is from beneath was made of no reputation with him,
in comparison of the favour of his creator, and the attaining of peace of mind,
which he perceived was only to be attained by a life or virtue
and religious dedication of heart to the service of God,
and the doing of his will, as far as he should be favoured with light to discover it.
Under these impressions he attained fortitude to become a fool for Christ`'s sake,
and to endure the contempt attendant on the profession he had adopted,
to become the object of the censure and wonder of his former acquaintances.

Thus leaving the vanities, the pleasure and honour of the world behind him,
and following the guidance of the spirit of truth,
he experienced the gradual work of sanctification,
and the unfolding the mysteries of the kingdom of heaven,
where by he received qualification to become an able minister of the gospel;
and his distinguished abilities natural and acquired were sanctified,
and applied to the best purpose, the promoting of religion and righteousness,
wherever his influence extended; both in the land of his nativity,
and the American plantations.
Before his removal to America he was frequently and successively
engaged in controversy in defence of those doctrines,
which he received as truth.
In the year 1664 he was taken up on the highway, as he was on a journey,
and for declining an oath, was committed to prison, where he was detained several years;
I apprehend, until the general release in 1672.
Through all, his prevailing and effectual ministry,
his circumspect and exemplary conversation, his pacific spirit,
the meekness and evenness of his temper, his humility, patience, temperance,
love to his brethren, and his religious care in the church,
to preserve good order therein, and the reputation thereof unsullied,
raised him high in the estimation of his friends and neighbours in his native country.
Such was the man chosen by William Penn from amongst the companions
of his voyage to entrust with the government of his province,
in his absence.
In his temper not easily provoked to anger, in his judgment cool,
deliberate and penetrating;
he was well accomplished for the administration of the government of the province,
and for the execution of the beneficial laws of Pennsylvania.
In peace and prosperity, seconded by magistrates like-minded,
the affairs of government were managed under his direction,
to the mutual satisfaction of himself and the people at large;
'`till the disturbances raised by George Keith,
for a season interrupted the remarkable harmony subsisting
between the different orders of the state.
To him Thomas Lloyd was a kind and beneficent patron,
whilst he acted in the unity of the body, of which he was a member;
and he might here have been in happy and honourable circumstances, under his protection,
if he could have been contented with the station
and allotment for which he was chosen and qualified,
but aspiring above it, he became uneasy to himself and to many others, and in the end,
in a great measure,
lost his estimation amongst the discerning and dispassionate part of mankind.
For when he exerted his endeavours to promote schism in the church,
and faction in the state, it became the duty of the governor,
in regard to the public good,
to use all his influence to discountenance and check his proceedings.
For which,
we have seen he met with unmerited obloquy and bitter revilings from him and his partisans,
which he bore with christian patience, neither returning their revilings,
nor abusing the power with which he was invested, to avenge himself;
but endeavouring by sound reasoning in the meekness
of wisdom to bring them to a better temper,
to return to the cultivation of amity and peace with their neighbours;
and when his united labours with his brethren failed of the desired success,
he joined his authority with them in issuing a public testimony
against their contentious and disorderly conduct.

Thus devoting his labour, his time and his talents to the service of God,
and of the public, promoting the good of civil and religious society,
he fell ill of a malignant fever,
which in about six days put a period to his life in about the 54th year of his age.

The violence of his distemper he bore with exemplary patience,
the pain of his body being alleviated by the serenity of his mind,
the prospect of death being no terror to him as the sting thereof was taken away;
which appeared by the following expressions,
addressed to some or his friends a short time before his decease, viz. "`friends,
I love you all, and I am going from you;
I die in unity and in love with faithful friends.
I have fought a good fight, and have kept the faith,
which stands not in the wisdom of words, but in the power of God.
I have not sought for strife and contention, but for the grace of our Lord Jesus Christ,
and the simplicity of the gospel I lay down my head in peace,
and I desire you may all do so.`" Afterwards to Griffith Owen,
"`I desire thee to mind my love to friends, in Old England,
if thou live to go over to see them; I have lived in unity with them,
and do desire the Lord to keep them all faithful
to the end in the simplicity of the gospel.`"

In the course of this year Robert Barrow, from Westmorland, and Robert Wardel,
from Sunderland, county Durham, both far advanced in years,
but men eminently qualified for service,
the latter being more remarkable for an extraordinary talent in the discipline,
the former for an excellent gift in the ministry, notwithstanding their advanced age,
and the probability of a final separation from their
nearest connections and their native land,
under persuasion of duty and the impulse of gospel love,
paid a religious visit to their friends in this remote quarter of the globe.
They commenced their service in the province of Pennsylvania and Jersey,
to the comfort and edification of those they ministered unto,
and afterwards visited New England and other parts of the continent,
in which service they spent the remaining part of the present,
and greatest part of the succeeding year,
and in the latter end thereof embarked for the West Indian islands ;
and after passing through Bermudas and Antigua,
where they had considerable service among friends and other inhabitants,
they arrived at Jamaica in the second month 1696,
intending after their service there was finished, to return to the continent of America.
Continuing in diligent labour for the promotion of truth and righteousness
among their friends and others in that island,
for the space of two weeks,
the climate seemed unfavourable to their declining constitutions at their time of life,
making a visible alteration in both; but more immediately on Rohert Wardel,
whom it threw into an indisposition, which soon terminated his labours with his life.
During his confinement to his bed, a friend coming to visit him,
and inquiring of him how he found himself?
he answered, "`I have been sick many times, but I never felt myself as I am now,
therefore I know not how it may be with me, the will of the Lord be done, I am given up,
and am content with God`'s will.`" At another time he said to the woman friend,
at whose house he was, "`the Lord reward thee for thy tender care,
it makes me think of my dear wife; I know not whether I may ever see her more;
but however the will of God be done; I am,
and was willing to be contented with the will of God, whether life or death,
before I came hither; and I bless God,
I am not afraid to die.`" And continuing to the end in a resigned frame of mind,
gave pertinent exhortations to several of those who came to visit him,
concerning the education of their children, their care of discipline in the church,
and that things might be kept in good order,
and expressed his desire that friends might walk answerable to God`'s love to them;
and after four days sickness, he peaceably expired on the 22nd of the second month,
leaving his companion and fellow-labourer on the island.
And as this friend was not the least distinguished among his brethren for his services,
and his peculiar sufferings,
a more particular account of him may not be unacceptable to some readers.

Robert Barrow was a native of Lancashire,
but removed and brought up from his infancy in Westmorland.
He was convinced of the truth as held by the people called Quakers, in the piety pro,
early times of their being distinguished by that denomination,
and after some time received a gift in the ministry;
in the exercise whereof he travelled much in England, twice through Scotland, Ireland,
and Wales.
His testimony and service was, I understand, everywhere very edifying,
and very acceptable to his friends, and reaching to others.

He appears to have been a man of great meekness, innocence, and patience,
which was repeatedly put to the trial by the successive
sufferings he endured for the testimony of a good conscience,
in his native country; as well as those distressing hardships he endured in Florida,
hereafter to be described.

In the year 1663 he was taken from a meeting at Birkhagge, in company with other friends,
indicted at the sessions; from which he, with John Ayrey and Bryan Lancaster,
were committed to prison, and confined there upwards of eleven months.

In the year 1665 he was committed to prison on an old indictment,
but after eight days confinement, again discharged, upon being fined 13s. 4d,
for which his goods were afterwards distrained.

His next suffering was by distraint of his property for a demand not properly his own.
In the year 1664 Christopher Bisbrown, of Arnside, was sued for tithes to an outlawry,
and arrested by Robert Wilkinson, a bailiff of Kendal, at the suit of James Bucket,
lord of the manor of Grayrigg: The plaintiff,
instead of obeying the requisition of the writ, by causing him to be conveyed to London,
to appear personally in the court of exchequer,
found means to keep him close prisoner in the bailiff`'s house above sixteen months,
in order to force him to a compliance with his demands: But the old man,
who was then seventy-seven years of age, bore his confinement with christian patience,
and at length died in the bailiffs house, the place of his long confinement.
And in a year or two after the prosecutor was also removed by death.

For in the year 1668 the two daughters and executrices of the said
Christopher Bisbrown were prosecuted by Elizabeth Ducket,
widow and executrix of James Ducket aforesaid, in the manor court of Beethom,
for the same tithe for which their father suffered imprisonment until death.
Mary Bisbrown, one of the said executrices, was summoned to appear,
and upon her non-appearance a verdict of 6£. 10s. was obtained against her,
and a warrant granted for distress on her goods;
but she being in the station of a servant, they could find no effects of hers;
and her sister was out of their jurisdiction.
The prosecutrix, vexed at these disappointments, manifested clearly,
that her aim in these prosecutions was not so much to obtain justice,
as to gratify a tyrannical and vindictive disposition;
declaring that she would spend 100£. upon the representatives of Christopher Bisbrown,
rather than suffer them to get off with impunity.
Therefore, soon after her aforesaid disappointment, this our friend Robert Barrow,
who had married Margaret Bisbrown, the other executrix,
was summoned into the court at Kendal by the said Elizabeth Ducket,
upon the aforesaid verdict obtained at Beethom,
where he demurred to the jurisdiction of that court, which appears to have been allowed,
Sometime after, he was again summoned to the said court at Kendal,
where four actions were brought against him at the suit of the said Elizabeth Ducket;
and on the second day of the month called March, 1668, those actions were tried,
and a verdict obtained against him for 4£. for which the bailiffs
took from him a horse which cost 4£. 5s. hay worth 15s,
and sundry articles of household furniture beside.

In the same year Robert Barrow, with Miles Bateman, and John Fell,
was prosecuted in the ecclesiastical court at Richmond,
for small tithes and Easter offerings, at the suit of William Brownswood,
priest of Kendal, and was committed to prison and detained there nine weeks:
After which these friends,
being informed of some illegality in the proceedings against them,
appealed to the ecclesiastical court at York,
upon which they were set at liberty during the appeal,
and were likely to recover costs against the priest:
But by the advice of one Dr. Burwell,
the priest took an oath of the legality of his prosecution,
and thereupon they were cited to answer upon oath, otherwise they would incur a contempt,
which must have been the consequence,
only that both the priest and this Dr. Burwell died in the intermediate time,
whereby the suit was terminated after an expense of 7£. to our said friend,
besides his false imprisonment,
which was attended with a circumstance evidencing the unfeeling temper of his prosecutor:
When the bailiffs came to his house to arrest him, he was sick, and had taken medicine,
wherefore he requested them to forbear taking him from home until the next day.
Although these are a class of men by no means remarkable for tenderness, yet,
in this case, they evidenced more of that disposition than the priest;
to whom when they applied in favour of the prisoner,
informing him it might endanger the man`'s health to take him away at that time;
the priest churlishly answered, that unless he would pay,
he should go immediately to jail.
So they were obliged to hurry him away, to the apparent danger of his health.

He was again imprisoned in 1677.
The mayor of Kendal sent three constables to the meeting,
who found Robert Barrow preaching: At the next sessions he, and two other friends,
who were at the meeting, were (after the custom of this time) indicted for a riot,
fined by the court, and imprisoned: But some little time after,
their fines were levied by distress of their goods, and themselves set at liberty.

His last imprisonment was in London in the year 1685, after the death of king Charles,
and the accession of his brother James to the throne,
while the persecution of this people, for their religious dissent,
though carried on with less vehemence, still was continued,
he was taken from Devonshire house meeting,
and with several others indicted again for a riot,
brought in guilty and fined 2£. 13s. 4d. and of course remanded to prison for non-payment;
but how Jong he was detained there I find no certain account.

But it was not long until the persecution was chap.
much moderated, and in fine terminated by the king`'s declaration of indulgence.
Robert Barrow had, when at liberty,
travelled into sundry parts of Great-Britain in the exercise
of his ministerial labours in sundry periods of his life;
but did not cross the seas in that service until his declining years.
In 1691 his sympathy with his friends in Ireland,
just relieved from a season of great distress, drew him to pay them a religious visit,
being the first friend from abroad who visited that nation after the wars.
And in the next year 1692, he repeated his visit to that nation,
in company with Alexander Seaton.

In the year 1604 he left his outward habitation under a full persuasion or duty,
to pay a religious visit to his friends on the American continent,
and some of the West-Indian islands;
for so discouraging was the prospect of this undertaking at his time of life,
that nothing short of a firm belief of a divine impulse inciting
thereto could have prevailed over his reluctance to the voyage;
but in obedience to the divine will, though in a cross to his own,
he submitted to prosecute that way, which only seemed to open,
to the maintaining that peace of mind, which with him was of more consideration,
than bodily ease, or even domestic satisfaction, without it.
Such was his apprehension of the attendant difficulties and dangers,
that he expressed himself to this effect before he left England,
"`that he had rather have immediately laid down his natural life there,
if by so doing he could have kept his peace with Cod,
than to cross the seas to America.`"

We left him in the island of Jamaica,
where he spent about four months after the decease of his companion,
and being clear of his service in those parts was purposing to return to Pennsylvania;
and with that view he embarked in company with Jonathan Dickenson and his family,
on board the Barkentine Reformation, Joseph Kirle master,
on the 23rd day of the 6th month called August, 1696;
they proceeded pretty successfully on their voyage till the 22nd of next month,
when being in the Gulf of Florida,
a great storm arose and drove them shipwreck ashore in the night,
when it was so dark they could see no land, the seas broke over them,
and set all things in the cabin afloat; the vessel was soon mattered,
several of the timbers broken and planks started.
They concluded to keep in the vessel as long as it would hold together,
and at day light found themselves on shore upon a
beach which was dry when the surges retreated.

They seemed to conceive the joy naturally resulting
from this preservation from the raging waves,
but allayed by fears from their ignorance of the land on which they were thrown,
they got on shore, and brought off some of their pro visions,
with spats and fails to make a tent.
Jonathan Dickenson with a negro servant went to view the land,
which appeared a dreary waste without trees or herbage;
they chose the most convenient place they could find for their tent,
to which they brought the sick and the weak,
particularly Jonathan Dickenson`'s wife and young child, and Robert Barrow,
who besides the infirmity of age, had been for some time under an infirm state of health;
the storm and rain still continued, from which they had no proper shelter,
their clothes also were all very wet and cold,
but these were scarcely to be reckoned hardships
in comparison of what they had to experience.

For in a short time two of the natives made their appearance, who went quite naked,
except a small piece of plaited straw-work, about their waists, fastened behind,
and depending down a little before; these savages looked very fierce,
their countenances very furious, their hair was tied behind in a roll,
in which stuck two bones, one shaped like a broad arrow,
the other like the point of a spear,
and their weapons were long knives with which they were furnished by the Spaniards.
These two natives running furiously,
seized the two first of the ship`'s crew they met with,
who were fetching corn from the vessel;
the rest of the crew coming up seemed disposed to fetch their guns to kill them,
but were dissuaded by Jonathan Dickenson,
who observed to them their inability to defend themselves
and company from the consequences of such an action,
advising them to put their trust in the Lord,
who was able to defend them to the uttermost.
After looking upon these strangers awhile, the Indians turned their backs and ran away.

These Indians of Florida appear to have been of a much more savage
and vicious temper than any of those tribes bordering upon the
middle and northern provinces inhabited by the English planters,
so much so that these latter might be esteemed civilized people compared to them,
being of that barbarous kind in those days termed canibals or men-eaters.
The sudden retreat of these two filled the ship-wrecked
crew and passengers with gloomy apprehensions,
imagining they were gone to alarm the rest of the natives in these parts,
which seemeth to have been really the case.

Conferring amongst themselves about the best expedients in this extremity,
one of the company proposed to assume the denomination of Spaniards,
as these Indians stood in awe of them; and one of the mariners, named Solomon Creson,
speaking the Spanish language well,
the motion was agreed to by most of the company as the most
probable means of escaping with their lives.

Soon after word was brought by some of their people who had been near the beach,
that the Indians were coming in a very great number, all running and shouting;
the greatest part went to plunder the vessel,
but the Cassakey (their king or chief) with about thirty more,
came upon the shipwrecked people in a furious manner, with a terrible aspect,
their large Spanish knives in their hands, and foaming at the mouth,
cried out "`Nicaleer, Nicaleer`", which though not understood at that time,
they came after to understand was the term they used to signify Englishmen,
to whom they bore a particular malevolence,
whether from any misrepresentations of the Spaniards,
or because the English having no power here to call them to account,
they might think themselves at liberty to give full
scope to their natural propensity to cruelty;
or whether it might proceed from any injury they conceived themselves
to have received from any individuals of this nation,
it is not possible to determine; however it be,
it would be well for those who may not be in their power,
to offer them no injury or offence, lest their countrymen suffer for their misconduct.

When these persons endeavoured according to their
agreement so pass themselves upon them for Spaniards,
they repeated their cry, "`no Espania, Nickaleer, Nickaleer,`" and surrounding them,
placed themselves each behind one, and some taking hold of them by the head,
with their knees set against their shoulders,
with their arms extended and their knives in their hands,
in this posture they seemed to wait for the Cassekey to begin the butchery.
But the hearts of all men are in the hands of a superior power,
and he can turn them as he pleases.

The friends sitting quite still, and apparently unmoved, resigned to the divine will,
and placing their confidence in divine providence, quietly waited the event;
when all on a sudden the Indians,
who had been very clamorous in their unintelligible jargon,
and dreadfully fierce in their countenances, were struck dumb, their countenances fell,
and they looked like men amazed for a quarter of an hour.
Then they withdrew their hands, and left them, to rifle their trunks and chests,
which they had brought on shore, and divided the spoil,
the Cassekey reserving the money to himself.
They stripped most of them of their clothes, leaving them as naked as themselves,
(except Jonathan Dickenson`'s wife and child, Robert Barrow and Joseph Kirle).
Being now in the hands of these Indians,
it pleased divine providence to affect the Cassekey`'s heart with tenderness,
who thence forward became their protector against
the further rapine or abuse of his people.

But the next day the Cassekey came into the tent, which by his direction by a signal,
the ship`'s company had erected to shelter themselves from the storm and rain,
and sitting down amongst them, repeated the question Nickaleer, Nickaleer?
and addressed himself directly to Robert Barrow.
Now although the rest for the safety of their lives had assumed the name of Spaniards,
some on that account making a wrong assertion, others evading a direct answer,
yet this honest man, who had learned of the God of truth,
to speak the truth from his heart on all occasions, even at the hazard of his life,
durst do neither the one or the other, but in simplicity answered yes;^
footnote:[As neither party understood the language of the other,
a difficulty may present itself to the reader;
how this Cassekey could know that yes was an affirmative answer.
It hath been observed that one of the company could speak Spanish, whom, when present,
they employed as their spokesman, and, in his absence,
had answered Espania or Pennsylvania:
This Casekey had got a smattering of Spanish from his intercourse with the Spaniards,
and finding by Robert Barrow`'s answer that it was neither in the Spanish language,
nor the expression the others had made use of,
being all along suspicious they were Englishmen, or Nickaleer,
this new answer might confirm his suspicions,
and make him take it for granted that this answer was an owning of it.]
whereupon the Cassakey asked him, if another person, to whom he pointed was Nickaleer?
to which he returned the same answer.
Then he said totus (all) Nickaleer, and went out,
but returned in a short time with some of his men with him,
and then they stripped Robert Barrow and the rest, who had hitherto been spared,
of their clothes, and left them likewise almost naked;
yet God suffered not these savages to take their lives.

The Indians having collected their plunder,
provided a guard armed with bows and arrows to conduct their prisoners to their town,
who were each of them, if any ways able,
obliged to carry a burden provided for them out of the plunder.
Thus loaded, and threatened to shot if any of them offered to lay down their burden,
they were marched about five miles barefooted through a deep sand,
and the sun extremely hot; when they reached an inlet of the sea,
on the other side whereof their town stood, composed of a few wigwams,
constructed of small poles stuck in the ground, bent one to another to form an arch,
and covered with a thatch of palmetto leaves;
to this town they were taken over the inlet in canoes.

Here they had an opportunity of observing The Indian their manner of worship,
which was performed by night, and which is thus described: The moon being up,
an Indian who performs their ceremonies, looking steadfastly at the moon,
made a hideous noise, and acted like a mad man for the space of half an hour,
all the Indians being silent till he had done; after which they made a great noise,
some like the barking of a dog, and other strange sounds; after this, one got a log,
and set himself down, holding the stick or log upright resting on the ground,
several others gathered about him, making a hideous noise,
and singing after their fashion; at length their women joined the chorus,
and added greatly to the vociferation, which continued till midnight.

The next day the 26th of the month,
they had amongst themselves worship of a very different kind.
Robert Barrow under a deep exercise of mind,
in consideration of their present distressing trials,
toward the evening of the day felt a concern to address an exhortation
to his fellow sufferers to patience under their present afflictions,
preaching from the text of scripture, Rev. 3:10.
Because thou hast kept the word of my patience,
therefore I will keep thee.
After which he ended with a most fervent prayer, desiring of the Lord,
that whereas he had suffered them to be cast amongst a barbarous and heathenish people,
that if it was his blessed will he would preserve and deliver them from amongst them,
that their names might not be buried in oblivion,
and that he might lay his body among his faithful friends.
At the close of his prayer he seemed to have an assurance
that his petition would be granted.

They spent five days amongst this savage people, and then,
being stripped of all they had, were permitted to depart,
and obtained from the Indians at their departure
some things they seemed to set no value upon,
being articles of provision these savages knew not the use of,
but which might be of service to them in their journey.
They had hitherto eaten very little, if any thing, from the time of their shipwreck;
at first their affliction and terror took away their appetite,
that they had little inclination to eat;
then the Indians food here was mostly distasteful to them,
and when they were provided with fish pretty plentifully,
some of them hungry as they were,
having conceived a dreadful notion of them as cannibals or men-eaters,
durst eat but sparingly, as imagining they only fed them to feed themselves upon them.

They divided their company, the ablest taking their journey by land,
and the sick and weak by water, in their own boat,
which they had obtained of the Cassekey,
and directed their course to a place called Lucia, on their way to Augustine;
but particularly to describe all the hardships,
distresses and dangers they passed through in a wilderness journey,
or voyaging little less trying and dangerous for the space of six or seven weeks,
till they reached that town, would be too tedious a recital:
A summary relation thereof may suffice in this place.

When they came to the place of their first destination where they expected greater safety,
and more friendly treatment amongst Indians nearer to the body of the Spanish settlements,
they found themselves greatly disappointed,
meeting here with inhabitants not a whit more civilized than those they had left behind,
equally savage, equally suspicious of their being Englishmen,
and equally ill-disposed towards them as such;
yet they were here also providentially preserved from personal injury,
any farther than stripping them of those poor rags which the others had left them,
for these stripped and left them quite naked.
Here the Cassekey`'s wife was made an instrument for their preservation,
she and some others possessing some tenderness, though amongst such an inhuman crew.

They were daily conversant in perils by sea and perils by land;
once an arrow shot at them narrowly missed them; another time,
when some were going to shoot,
certain of their own company caught hold of their bows and arms to prevent them;
some did shoot, and their arrows missed oftener than once;
one time as they were rowing along shore in their boat,
the sea swelled to that degree that it was dangerous continuing there all night,
and as dangerous to endeavour to gain the shore,
yet that divine providence in which they trusted made way for them here,
and conducted them safe to shore,
it appearing as if a lane were made through the breakers, so that they landed safely.
Another time, by reason of a great flood,
they were obliged to remove their lodgings several times,
and for divers days were in continual apprehension of being drowned;
at length they were preserved on an oyster-hill.

Their food amongst these latter Indians as well as the former was both very scanty,
and very loathsome, even gills and guts of fish picked off a dunghill;
sometimes the nauseous scraps the Indians threw away,
and the water they boiled their fish in however filthily handled:
At first we have seen their sorrows and alarms deprived them of appetite,
then the Indian food was distasteful,
but at length extreme hunger prevailed over all disgust,
they could eat the palmetto berries with an appetite,
which at first had a most disagreeable taste, and were like to take away their breath.

Their lodging was equally uncomfortable:
it is easily imagined how great a hardship it must be to people well educated,
and inured to comfortable accommodations,
to lie on a floor swarming with vermin of many sorts,
and in the midst of all the filth that bred these vermin;
more severely trying still was their lodging on the cold ground afterwards,
unclothed and unsheltered, exposed to the chilling blasts of the rigid North-west wind.

For before they reached Augustine,
this wind introducing the severest cold and frost in this continent set in;
they were then in an uninhabited country,
where they were obliged to take up their lodging on the ground in the open air,
they provided the best shelter they could against the freezing wind,
and having wood here made a large fire, but when they lay down could not and rest,
for when on one side they were even scorched by the fire,
the other side was ready to freeze,
insomuch that they were obliged to stand or keep running most of the night;
the next day proved the accumulation of their sorrows,
faint and weary for want of rest and want of food,
they walked in pain through weakness and fatigue,
if they stood still they were benumb ed with the frost and lost themselves,
and if this were the case with any of them, the rest were too weak to assist them;
they were obliged to leave them to perish, or perish with them;
three or four of their negroes actually perished, and were seen by them no more,
and one of the passengers fainting they were forced to leave be hind half dead,
and I find not that he came to them again.
Upon this catastrophe I find the following remark,^
footnote:[Preface to J. Dickenson`'s narrative.]
"`God can both administer strength in the midst of weakness,
and also take away strength and cause weakness to succeed whenever he pleases.
Here was an old man,^
footnote:[Robert Barrow.]
a woman with a sucking child,^
footnote:[Jonathan Dickenson`'s wife.]
and a woman with child,
persons very unlikely to encounter such hardships, all persevered through,
and yet divers negroes inure to more hardships perished.`"
The next day they reached a Spanish settlement,
and in two days more they arrived at Augustine; on the 5th of 9th month November,
after a very distressing journey from the 28th of 7th month September,
the day they left the first Indian town,
wherein they experienced calamities the most distressing to human nature,
literally those the apostle recounts as such, "`In perils of waters, in perils of robbers,
in perils by the heathen, in perils in the wilderness, in perils in the sea;
in weariness and painfulness, in watchings often, in hunger and thirst, in fasting often,
in cold and nakedness. 2 Cor. 10:26-27.

At Augustine they were entertained, clothed and fed with great humanity by the governor,
who having providentially heard of their captivity among the Indians,
sent out a body of Spaniards into the Indian settlements
to find them out and conduct them thither;
and when they were sufficiently refreshed to undertake the journey,
provided them with necessary accommodations and proper
guides to conduct them safely to Carolina.
The governor of Carolina,
with equal generosity and humanity completed that relief the other had begun,
supporting them liberally,
and providing them with better clothing than Augustine afforded;
here they stayed a month wanting four day; when Robert Barrow Jonathan Dickenson,
his wife and child, embarked for Pennsylvania,
and in fourteen days arrived at Philadelphia,
on the 1st day of the 2nd month O. S. called April, 1697,
about six months and seven days from the time of their ship wreck.

Robert Barrow from the decay of nature and the unwholesomeness
of the food he had subsisted on among the Indians,
had contracted a violent flux, added to his preceding sickness,
which had held him ever since he left Augustine, and was aggravated by the cold weather,
so that when he arrived at Philadelphia,
he was reduced to such extremity of weakness as to
be incapable of moving or helping himself.

It was about eight o`'clock in the evening when the vessel he was in arrived,
and divers friends went on board to help him on shore,
but found him too weak to remove that night; he was rejoiced to see them,
and expressed his great satisfaction that the Lord had granted
his request that he might lay down his bones in that place;
that his heart was strong, and he hoped to see friends again at the meeting.
He gratefully acknowledged the goodness of God to him,
the consolation of whose presence had attended him in all his exercises.

The next morning several friends went aboard to assist
in bringing the vessel up to a wharf,
in order to get him on shore, which they effected,
and wrapping him up in a blanket conveyed him in a hammock to the house of Samuel Carpenter,
where being shifted, he slept a consider able time:
the same day some friends came to visit him,
at the sight of whom he seemed greatly rejoiced.
The friends expressed their gladness to see him,
but said they were sorry to see him so weak; to which he replied,
"`although my body be weak, my mind is sound and my memory good.
The Lord hath been very good to me all along to this very day,
and this very morning hath sweetly refreshed me.`" And further added,
"`the Lord hath answered my desire, for I desired content,
and that I might come to this place to lay my bones amongst you.`" And afterwards,
"`it is a good thing to have a conscience void of offence, both towards God,
and towards men.`"

On the 4th day of the 2nd month, about the 5th hour in the morning,
he desired a friend to write for him to his dear wife, to remember his dear love to her,
and let her know of his travels and his arrival at Philadelphia;
that the Lord was with him, that his outward affairs were settled,
and that she had wherewithal to live on.
Several friends coming to visit him this day, he said, "`that the Lord was with him,
and all things were well,
and that he had nothing to do but die.`" And the same day departed this life,
being the 3rd day after his arrival,
and on the 6th day of the same month was decently
interred in friends burying ground in Philadelphia.

Although George Keith had left America,
and was now busying himself in vain endeavours to scatter
the seeds of discord amongst his former friends in England,
yet in America, where he had been more successful in causing an open separation,
the seeds of dissension and enmity he had sown amongst his partisans had grown to strength,
and many of them having thoroughly imbibed the bitterness of his spirit,
continued to be very troublesome to their quondam friends.
At the yearly meeting at Burlington this year, George Hutchinson,
with some others of the party, attempted to disturb the meeting of worship,
coming in under a very ill-timed pretence of demanding
justice against the ministers and strangers,
against whom he alledged he had divers things to object,
both in respect to doctrine and practice;
but it being evident by his manner of expression,
that he was actuated by a spirit of envy and malignity,
and that his intention was only to disorder the meeting by cavilling and contention,
friends took no notice of him,
but continued their meeting unmoved by his railing accusations,
and as they felt their minds properly influenced, bore their testimonies to the truth,
and continued them over all his opposition:
Nothing perhaps aggravates passion more than the observation that it makes no impression;
exasperated at the neglect of his calumnies he continued
his railing even while some of the friends were preaching;
and when he found he could not attain his end to
put the meeting in disorder or confuse the preachers,
he departed in wrath, with a menace that he would publish or expose them to the world.
A menace which could make little impression on them,
as they had already experienced what his strenuous
efforts in this line of conduct could effect,
particularly the preceding evening, when the town being full of people,
he had gathered a tumultuous company in the streets,
whom he entertained with an harangue, conceived in those invective and injurious terms,
which were now be come too customary with him and his party inventing their causeless
enmity against that body of people of which they had professed themselves members,
and who having administered no just occasion for their reproaches,
they rebounded in the estimation of the impartial upon themselves.

Hutchinson had no sooner withdrawn than a fresh disturbance was attempted
by a number of Germans with one Henry Bernard Castor at their head,
who was one of those called Pietists, whom his brethren,
friends in London were reported to have assisted on their way to Pennsylvania,
for which they seem to have made very some ungrateful returns;
for divers of them gave friends there much trouble in matters wherein
no reasonable plea of conscience or duty could be advanced,
and in a manner inconsistent with the spirit of christianity,
appearing very fierce and violent, especially at this meeting:
for with turbulent vociferation they produced several books of Edward Burrough`'s,
William Penn`'s and other friends,
clamouring against them that they denied the Lord Jesus Christ,
and that they were there ready to prove it out of these books.
It was certainly a great hardship, imposed by these unruly spirits,
upon a people religiously assembled for mutual edification,
to have their solemnities thus interrupted and disturbed,
and endeavours used to convert them into scenes of confusion and altercation;
but friends feeling their minds stayed under an awful inward sense
of the great duty of worship which they were engaged in,
they were preserved so steadfast and immovable,
as not to gratify their lust to contention by an opposition at that time unseasonable,
but such as felt their minds influenced to speak in public were
strengthened to continue their testimonies over all their clamour,
disorder and raising of their voices, and speaking, two,
three and some times more at a time,
so that at length they gave out and left the meeting.

But although many of those who had withdrawn themselves with George
Keith retained their inveterate enmity against friends,
yet many others perceiving the causelessness of their separation,
and feeling want of peace in themselves therein, had returned back to the society,
and acknowledged their errors to the monthly meetings to which they had belonged,
by a writing under their hands, of which the following is a specimen:

[.embedded-content-document.letter]
--

Long before George Keith set up his separate meeting,
my mind was at times gone out of the pure fear of God,
into my own reason and conceivings,
and in that I took in hand to judge of friends`' testimonies,
and therein speak evil of that which through God`'s goodness I now see I understood not,
and particularly against John Willsford,
who often gave us warning of what is now come to pass, telling us,
in the power and demonstration of God`'s pure spirit,
that if we went from the guidance of God`'s spirit in our own imaginations,
and hunting to study God`'s secrets, it would gender to strife and contention,
and we should be like heads and hands pushing and rustling one at another,
which is too apparent at this day;
and notwithstanding George Keith went beyond all
bounds of moderation in reflecting upon friends,
perverting their words, and mangling their testimonies,
and unto such great heats and passions, the fond,
foolish affection I had to him blinded my eyes, or at least,
made me willing to overlook them, and not only so,
but the guidance of God`'s spirit in my own heart,
which would have kept me out of those evils if I had well-minded it,
and often followed me, and reproved me, and broke my rest,
while I joined with the separate party.
I am not able to express in words the sorrow and trouble I had night and day,
whilst I frequented their meetings and heard them speak evil of friends,
for that was most of their practice when their meetings were over,
as well as at many other times.
But now I praise the Lord for his mercies,
who hath let me see the out-goings of my own mind, and the evil of their ways,
and hath in measure given me strength to come but from amongst them,
and to bear my testimony against that spirit, both in myself and others,
which leadeth into such evil, as is too frequent among them;
and I am very sorry and sore grieved that I should
be so foolish as to join with them against friends,
in setting my hand to their pretended yearly meeting paper.
I was troubled for it often before I left them.
They often desired me to give them a reason why I left them.
I might give them many, but in short I had no true peace with them.
I often tried for life.
I could not feel it amongst them, but instead thereof sorrow and anguish of soul,
and if I had kept to the pure guidance of God`'s pure spirit,
and the light of Christ in my own heart,
which some of them in my hearing have undervalued,
saying they thought I had known better things,
when I said I ought to believe in the light within, which reproveth for sin.
I say, if I had kept to this, I had never joined with them in the beforementioned things,
which I am satisfied by my own experience Christ never led them into.
To conclude,
my desire to the Lord is that he will keep me close to the guidance of his pure spirit,
out of that restless spirit which I have sometimes been in, and I hope he will,
if I diligently wait upon him; but if for want of watchfulness the enemy should prevail,
as I hope he never will, I have full satisfaction in what I have have here written,
and in joining with my real friends again, amongst whom I feel life,
and more quiet and steadiness of mind than I have done for a long time before.
Praise to the Lord forevermore. Amen.

[.signed-section-signature]
Caleb Wheatley.

[.signed-section-context-close]
Written the 31st of the 11th month, 1692.

--

Those of the Separatists who did not return to their
brethren were now under various fluctuations,
some turned to the episcopalians, some to the baptists, and others to nothing;
but many of them though shattered among themselves continued violent against friends,
and as irreconcilable as ever;
it was however plainly enough to be seen that the
whole was breaking and coming to nothing fast;
the yearly meeting epistle of this year from hence to friends in London,
gives some account of the present state of things,
as well among them as otherwise in these provinces;
some paragraphs of it are therefore here inserted:

[.embedded-content-document.epistle]
--

[.salutation]
Dear Friends,

In that which abides forever we salute and tenderly embrace you,
and in the joy of God`'s salvation rejoice with you,
admiring and reverencing that arm that has thus far brought
us out of darkness into the marvellous light of the Lord,
in which the nations of them that are saved must walk,
in which light and life our unity and heavenly fellowship
stands sure against all the attempts of Satan,
to break it either immediately by his own suggestions, or instrumentally by those,
who either never knew it, or having known it, through an evil heart of unbelief,
have departed from it.

Dear friends, our yearly meeting at this time hath been much larger than ever,
notwithstanding the backsliding and apostasy of divers with George Keith,
and the vain endeavours used by them, in their restless state to trouble and divide us,
which the more they attempt the more the Lord unites us to his glory and our comfort,
and their vexation and torment,
and in this blessed unity have we had a sweet time together at this season,
which may be truly called a feast of charity;
and besides the public friends belonging to this meeting,
we had with us our friends Jonathan Tyler, Henry Payton and Sarah Clark, who,
we are sensible, came in the love of truth to visit us,
in which we receive and bid them God speed;
they have laboured painfully and industriously in the service of truth,
with good acceptance, and are now near leaving us, in order to return to England,
whom we pray God to protect, and give them their sheaves in their bosoms,
and provoke others to the like services, of which we shall be at all times glad.

Our exercise with the Separatists is much over here,
only our lamentation over some of the most simple of them, for whose return we wait,
since they have ceased to give us disturbance as formerly;
they are at great variance amongst themselves, biting and devouring one another,
and surely the Lord is letting fall showers of confusion upon them,
they continue still going back, divers of them to water baptism, about which,
and the supper, and the lawfulness of oaths, a great part of their contention is.

We are sensible, dear friends,
of your exercise with that malicious unruly instrument George Keith,
the weight of which we bore here for some time,
and therefore can the more sensibly sympathize with you,
and you by your present exercise with us.
But glory to God, though the rage of him and his adherents be great,
yet their time is short and they are falling apace,
and that power before which they have begun to fall
shall accomplish what is yet behind concerning them,
and so, dear friends,
we conclude letting you know that through the Lord`'s great mercy we enjoy our
health generally here and in the blessed fellowship of the gospel of peace,
rest your friends and brethren.
Signed in behalf and by appointment of the meeting by

[.signed-section-signature]
Phineas Pemberton.

--

Thomas Janney, from Bucks county, Pennsylvania,
in the year 1698 visited friends in New England in the work of the ministry,
as did also at different times in the same year John Simcock, James Dilworth,
William Biles, John Willsford and Nicholas Wain, all from Pennsylvania;
Richard Gove also this year went with Thomas Chalkley on
a religious visit to friends in Maryland and Virginia.

Several settlers as we have seen had already arrived from Wales to Pennsylvania;
Hugh Roberts who was on a visit there from hence, stayed till this year,
when being about to return,
a number of the inhabitants of North Wales who had resolved to return with him,
having settled their affairs for that purpose,
they together in the spring sailed from Liverpool in a vessel belonging to Robert Haydock,
Ralph Williams commander, and touching at Dublin,
failed from thence the first of the third month;
shortly after they got to sea the bloody flux began among the passengers,
and proved very mortal,
forty-five of them and three sailors having died before their arrival at Philadelphia,
which was not till the 7th of the 5th month following.
When arrived they met with a kind reception,
not only from their relations and acquaintance, that were in the country before,
but from others who were mere strangers to them,
in that they understood not their language, so that; it then appeared to them,
that christian love presided even amongst those of a different speech and profession,
for they were not now many of them of those called Quakers;
in the latter end of this year William Jones, Thomas Evans, Robert Evans, Owen Evans,
Cadwallader Evans, Hugh Griffith, John Hugh, Edward Foulke, John Humphrey,
Robert Jones and others, having purchased of Robert ten thousand acres of land,
in the following year began to improve and settle it, and called the township Gwynedd,
which is in English North Wales.
There were for some time after their settlement,
but a few of the passengers in the ship before mentioned
that had made open profession with friends,
but several of them had inclinations after it,
which probably was not unknown to Evan Evans,
the then officiating missionary to the episcopalians in Philadelphia,
who made them several visits with offers of service,
but discovering no encouragement in the way he seemed to aim at, left them.
After some time they were generally convinced,
and more thoroughly established in the principles they had espoused,
and with their families met often together to wait upon the Lord in silence,
at the houses of John Hugh and John Humphrey,
and for their encouragement in this way many of their country-folk,
and others of their brethren in profession, some of which were ministers,
came often to visit them, particularly Ellis Pugh,
whom they mentioned as greatly instrumental in those early
times to the convincement and establishment of many,
and adding to the number of those who afterwards professed with friends;
frequent were his visits and labours in the ministry,
though he then lived at a considerable distance,
but in time removing within the verge of their meeting,
he continued a fervent labourer among them to the end of his days,
and many of them with good reason thought they had cause
to be humbly thankful for such a blessing.

Elizabeth Webb from Gloucestershire in England,
about this time travelled through all the English colonies on the continent of America,
where friends were settled,
and was eminently serviceable amongst them in the exercise of a large public testimony.

Mary Rogers from England, was also here now travelling on the same account,
and Elizabeth Gamble from Barbados,
both of whom visited the meetings in these provinces to good satisfaction.

In the beginning of the year 1699, Roger Gill and Thomas Story from England,
arrived in Virginia, and from thence went to.
North Carolina, thence travelled by land to Philadelphia,
taking friends meetings in their way.
They made a small stay in the city, and then set out for the provinces to the Eastward,
which having visited, on their return they heard of the great sickness in Philadelphia,
what is since commonly called the yellow fever,
which had for a considerable time before been very
mortal in several of the West India islands;
toward the latter end of the summer this year it raged there also with unusual terror,
and so great was the visitation, that a person of note in Pennsylvania,
and an eye witness, speaks of it in the following terms,^
footnote:[Thomas Story, a lawyer,
and afterwards some time one of the provincial council and recorder of the city of Philadelphia.
Vid. Journal of his life, page 224.]

[quote]
____
Great was the majesty and hand of the Lord, great was the fear that fell upon all flesh;
I saw no lofty airy countenance, nor heard any vain jesting to move men to laughter,
nor witty repartee to raise mirth,
nor extravagant feasting to excite the lusts and desires of the flesh above measure,
but every face gathered paleness, and many hearts were humbled,
and countenances fallen and sunk,
as such that waited every moment to be summoned to the bar and numbered to the grave.

But the just appeared with open face, and walked upright in the streets,
and rejoiced in secret, in that perfect, love that casteth out all fear;
and sang praises to him who liveth and reigneth, and is worthy forever,
being resigned unto his holy will in all things; saying, Let it be as thou wilt, in time,
and in eternity, new and forever more: nor love of the world, nor fear of death,
could hinder their resignation, abridge their confidence,
or cloud their enjoyments in the Lord.
____

The said friends being arrived at Philadelphia from their journey to the Eastward,
found things in this languishing situation,
they remained there some time with their friend and brother in the ministry Aaron Atkinson,
visiting and encouraging the sick and afflicted,
the latter after some time was taken with the distemper, but recovered.

At the yearly meeting of friends held in the seventh month, Roger Gill,
who from divers instances appears to have been very
deeply affected with the present heavy calamity,
in one of his public addresses to the Almighty,
with great zeal and earnestness solemnly prayed,
that the Lord would be pleased to accept of his life as a sacrifice for his people,
that a stop might be put to the contagion. When he first heard of this mortality,
he said he felt "`a great weight and exercise to come upon him`"
so that he had no ease in his spirit until he came in amongst them,
and when he came, he not only visited the sick,
but such was the part he took in their affliction,
that he declared in his public preaching that when he was one hundred miles off,
his love in the Lord was such to them,
that had he had wings he would have flown to them. After the yearly
meeting was over he often expressed the state of his mind,
and that he had not much to do but visit friends of Burlington,
and having accomplished that journey,
at his return to Philadelphia was taken sick with the common distemper,
which filled him with great pain and affliction of body,
and he remembered in his sickness "`the free-will offering of himself up unto the Lord,
saying to those about him,
it is not in my heart to repent of the offer I have made,`" and
continued notwithstanding his pains exhorting friends to faithfulness,
and at a certain time said, "`the Lord hath sanctified my afflictions to me,
and hath made my sickness as a bed of down;`" and when some
of his friends spoke as though they had hopes of his recovery,
he said to them, "`truly I have neither thoughts or hopes about being raised in this life,
but I know I shall rise sooner than many imagine,
and receive a reward according to my works.`" This sickness continued seven days upon him,
and a few hours before his death he took his leave of his friends about him,
by saying farewell, farewell, farewell,
and calmly passed from time to eternity on the second of the eighth month.

The death of this good man by the common distemper,
so soon following the public offer he had made,
and the sickness ceasing in a little time afterwards,
made it an occurrence much taken notice of; and was the more extraordinary,
that he does not appear to have been a man apt to be carried away by undue transports,
but on the contrary was much favoured in his public services.

[.embedded-content-document.testimony]
--

At the ferry, says Thomas Story,
I had the afflicting news of the death of my companion Roger Gill at Philadelphia,
at which my soul was greatly bowed, and my heart tendered,
and the ground whereon I sat was watered with my tears,
in the conclusion whereof I was fully satisfied he had obtained
a crown of everlasting peace with the Lord,
and that his memory should not rot,
nor his living testimony fall in those American parts,
wherein we had laboured together from New England,
where many hearts had been tendered by him and souls comforted, and several convinced,
and all through that divine power by which he is now raised to glory,
to sing praises to him who sitteth on the throne, and ruleth and reigneth,
and is alone worthy, forever and ever, Amen.

--

James Dickenson, whose first and second visits have been mentioned already,
did this year send the following epistle to friends in these provinces.

[.embedded-content-document.epistle]
--

[.signed-section-context-open]
Rogerskail, 27th of 1st month, 1699.

[.salutation]
Dear Friends,

In the love of God, my soul dearly salutes you all in the seed of life,
in which we are united the whole world over,
and are bound up in that one eternal power and spirit by which we have been gathered
to be a people to appear in the world to make mention of his name,
and that in truth and righteousness.
All wait low in the depth of humility,
daily to feel the operation and opening of his eternal power upon your spirits,
that by it you may be all guided in true fear and wisdom in all
your exercises and services for God in your several gifts,
and places that God has committed to your trust and charge,
that you all be showing forth the glory and power and wisdom
of him that hath called you out of the dark world,
and its ways, customs and fashions, into his marvellous light, to walk therein,
and to be faithful witnesses for him, and that your lights may so shine before men,
that they may see your good works, that may glorify your father which is in heaven.
My spirit and life is often with you in my secret retirement
unto the Lord in those remote parts of the world.

Oh! my bowels yearn towards you, night and day,
for your growth and prosperity in the truth,
that you may be kept under the government of Christ
where his peace will daily rise up in your souls,
which will far transcend all earthly enjoyments,
and redeem your affections out of the earth,
and the snares and corruptions that are in it, and will draw the affections heavenwards,
and to seek those things that are above, so will the Lord bless you every way,
both inwardly and outwardly, and your table will never become a trap and a snare to you.

Treasure the advice given of old, trust not in uncertain riches, but in the living God,
and then he will abundantly bless those parts of the world where it is your lot to dwell,
he will be as a wall of fire round about you,
and make your enemies to be at peace with you; keep low, there is your safety,
and look not out but to the Lord, whose eye is watching over you for good,
and his hand is full of blessings to be poured down upon you,
if you give him not occasion to withhold them from you,
by letting your minds wander from him;
therefore let an holy care and zeal be kept in by all,
to keep their minds close to the Lord,
so will he bring up a godly concern upon your minds, for the honour of God,
and a holy strict discipline amongst you, that all that profess the holy truth,
walk as becomes truth in their life and conversation, and that those that do not,
be dealt with, and if possible be reclaimed, and if not, to clear the holy truth of them,
and to wipe off the scandal,
that may be cast upon your holy profession by their disorderly walkings.
I do not write those things because you know them not,
but to stir up your minds to put them in practice, and in order thereto,
we are in the practice of appointing two or more faithful friends in every
particular meeting to take inspection into the conversation of friends,
how they walk as becomes truth, and these friends of every meeting,
which we call a preparative meeting, because it fits those that are appointed,
to give a true account to the monthly meeting, that often consists of several,
and takes a great deal of work from the monthly meeting,
things being done without going thither.
We find great benefit in a strict; discipline, and there is a great need of it,
I desire you to keep in the unity of the spirit, which is the bond of peace,
and stir up one another to love and good works,
and that those whom God hath trusted with heavenly
gifts may all improve them to his glory,
and stir up one another to visit remote parts that want help, as Virginia, Carolina,
New England, Barbados, Jamaica, Antigua, Nevis, and let all be done in the love of God,
so will he bless you with spiritual blessings in his son Christ Jesus,
in whom I dearly salute you all, letting you know I am well every way,
and to God`'s eternal arm of power I commit you all,
and remain your friend and brother in the holy truth,

[.signed-section-signature]
James Dickenson

--

The second of the 8th month died Arthur Cooke of Philadelphia.
He came over amongst some of the first settlers,
since his arrival had borne many of the most considerable posts in the government,
which he seems to have discharged with a good character.

In the sixth month this year,
William Penn with his wife and family took shipping
a second time for his province of Pennsylvania;
and on the ninth of the seventh month (September) they set sail,
and were near three months out at sea.
Providence, by the tediousness of their voyage, protracting the time of their arrival,
until the danger pf the contagious distemper then reigning in that country was over.
Upon their coming thither, they were received with the universal joy of the inhabitants.

Being now determined to settle in his province,
he applied himself to the offices of government,
always preferring the good of the country and its inhabitants to his own private interest;
rather remitting, than rigorously exacting his lawful revenues:
so that under the influence of his paternal administration
the province was in an easy and flourishing condition:
when some persons here in England, taking advantage of his absence,
were endeavouring to undermine both his and other proprietary governments,
under the specious pretence of advancing the prerogative of the crown;
and a bill for that purpose was brought into the house of lords.
His friends, the proprietors and adventurers here,
presently represented the hardship of their case to the parliament,
soliciting time for his return to answer for himself;
and accordingly giving him a speedy account how matters stood,
they pressed his coming over forthwith; with which he seeing it necessary to comply,
summoned an assembly to meet at Philadelphia, to whom, on the 15th of September, 1701,
he made the following speech, viz.

[.embedded-content-document]
--

[.salutation]
Friends,

You cannot be more concerned than I am at the frequency of your service in assembly,
since I am very sensible of the trouble and charge it contracts upon the country,
but the motives being considered, and that you must have met of course in the next month,
I hope you will not think it a hardship now.

The reason that hastens your sessions, is the necessity I am under,
through the endeavours of the enemies of the prosperity of this country,
to go for England; where, taking advantage of my absence, some have attempted,
by false or unreasonable charges, to undermine our government,
and thereby the true value of our labour and property.
Government having been our first encouragement,
I confess I cannot think of such a voyage without great reluctance of mind,
having promised myself the quietness of a wilderness,
and that I might stay so long at least with you,
as to render everybody entirely easy and safe.
For my heart is among you as well as my body, whatever some people may please to think;
and no unkindness or disappointment shall (with submission to God`'s
providence) ever be able to alter my love to the country,
and resolution to return and settle my family and posterity in it:
but having reason to believe I can at this time best
serve you and myself on that side of the water,
neither the rudeness of the season, nor tender circumstances of my family,
can over-rule my inclinations to undertake it.

Think, therefore,
(since all men are mortal) of some suitable expedient and provision for your safety,
as well in your privileges as property,
and you will find me ready to comply with whatsoever may
render us happy by a nearer union of our interests.

Review again your laws; propose new ones that may better your circumstances;
and what you do, do quickly,
remembering that the parliament sits the end of the next month,
and that the sooner I am there, the safer I hope we shall be here.

I must recommend to your serious thoughts and care,
the king`'s letter to me for the assistance of New-York with 350£. sterling,
as a frontier government,
and therefore exposed to a much greater expense in proportion to other colonies;
which I called the last assembly to take into their consideration, and they were pleased,
for the reasons then given, to refer to this.

I am also to tell you the good news of the governor of New-York,
his happy issue of his conferences with the five nations of Indians,
that he hath not only made peace with them, for the king`'s subjects of that colony,
but (as I had by some letters before desired him) for those of all other
governments under the crown of England on the continent of America,
as also the nations of Indians within those respective colonies:
which certainly merits our acknowledgments.

I have done, when I have told you, that unanimity and dispatch are the life of business,
and that I desire and expect from you, for your own sakes,
since it may so much contribute to the disappointment of those
that too long have fought the ruin of our young country.

--

[.embedded-content-document.address]
--

[.letter-heading]
The Assembly`'s Address.

[.salutation]
May it please the Proprietary and Governor,

We have this day in our assembly read thy speech, delivered yesterday in council;
and having duly considered the same,
cannot but be under a deep sense of sorrow for thy purpose of so speedily leaving us,
and at the same time taking notice of thy paternal regard to us and our posterity,
the freeholders of this province, and territories annexed,
in thy loving and kind expressions of being ready to comply with
whatsoever expedient and provisions we shall offer for our safety,
as well in privileges as property,
and what else may render us happy in a nearer union of our interests;
not doubting the performance of what thou hast been so lovingly pleased to promise,
we do in much humility, and as a token of our gratitude,
return unto thee the unfeigned thanks of this house.

[.signed-section-closing]
Subscribed by order of the house,

[.signed-section-signature]
Joseph Crowdon, speaker.

--

The next month he took shipping for England,
and safely at Portsmouth about the middle of December;
and the same month came up to London; after his return, the bill, which,
through his friends solicitations, had been postponed the last session of parliament,
was wholly dropped, and no farther progress made in that affair.
It doth not appear that after this he returned any more to Pennsylvania.

[.the-end]
End of the Third Volume
