== Preface.

The people who are the subjects of the ensuing history,
beside the great sufferings in person and property they endured at their first appearance,
from the spirit of persecution, prevalent in that age,
were exposed to another species of persecution in ungenerous attacks upon their reputation,
through the misrepresentations of prejudice; the malignity or ignorance of those,
who did not love, or those who did not know them;
particularly the public preachers of that era, too many of whom,
provoked at their testimony against formality, priestcraft and preaching for hire;
from the pulpit, and from the press,
published them to the world under very obnoxious descriptions.
To these, their regard to the reputation of the truth they professed,
induced one or other of them to reply, in defence of themselves and their principles,
and it was no difficult task for them to disprove assertions,
which had no foundation in fact.
They proved themselves to impartial judges guiltless
of the charges exhibited against them,
and refuted the fabulous invectives of their antagonists,
so that few or none of these early calumnies passed unanswered; added to which,
the tried innocency and integrity of their lives giving a more convincing refutation,
and religious controversy at length going out of fashion,
this species of abuse seemed in process of time to die away,
and the world in general to look upon them in a more favourable light, not as deceivers,
but as men of sincerity, probity and virtue.

Yet some modern authors of reputation in the learned world have
thought it worth their while to revive long refuted calumnies,
and debase the page of history with a delineation of this people,
copied from the distorted caricatures of their bitterest antagonists;
the consideration whereof pointed out the propriety of a new review of their real history,
drawn from authentic memoirs, and genuine records, preserved in their own archives;
that by comparing their own accounts of themselves, with those of their adversaries,
a more impartial judgment may be formed of their real character: That as these authors,
particularly Mosheim, and Formey after him,
have not thought it beneath them to draw from oblivion,
long refuted and long forgotten misrepresentations of men of worth (if solid virtue,
and real religion are considered as constituent parts
of worth) an attempt to rescue deserving characters,
worthy of imitation in the general tenour of their lives,
from the contempt and censure endeavoured to be thrown upon them,
seems an act of justice, not only to them, but to the world at large.

Incited by these considerations,
the compiler of the ensuing sheets hath not been
discouraged by the prospect of the laborious undertaking,
the scantiness of his leisure, nor his advanced stage in life,
from engaging in the business of collecting and digesting
the materials preserved by them,
in the following history;
and although the like laborious talk hath before employed the pen of William Sewel,
yet fresh occasion being offered,
seemed to demand a fresh revisal of the real history of this people:
In the prosecution whereof,
I propose to lay before the reader my objections to those passages,
which we consider as misrepresentations, partly in notes,
as occasion arises from my subject, and partly in an appendix to the history,
if my life and health shall be prolonged to bring it to a conclusion,
towards which it is already considerably advanced.

The reader is not to expect,
in the history of this pacific body to meet with a recital of those splendid actions,
or schemes of policy, which are apt to dazzle the eyes of mankind,
while they generally contribute very little to the felicity of the greater part,
are often productive of great damage and destruction to many;
and the happiness they convey to individuals, in the splendour of a name,
is but a poor recompense for the mischief they occasion, and but of short duration:
But what is of much more importance to the generality of the human race,
he will meet with many examples (worthy of imitation) of steadfast resolution and inflexible
perseverance in prosecuting through life the great end of our being,
happiness in a future state.
But few men have the ability,
the power or opportunity of conquering nations or governing kingdoms;
but all men have immortal souls to be saved or lost,
in consequence of the manner of passing the time of their sojourning here.

For this reason I have been more particular in the biography,
in the accounts I have collected of the lives and deaths
of several of the most serviceable members of this society,
with design to point out the beneficial effects of a life
of pure religion and virtue at that solemn period,
which mocks the splendour of triumphs, and lays human honours in the dust;
more with a view to inspire their survivors with a desire of copying their virtues,
than to build the tombs of the prophets, or garnish the sepulchres of the righteous.

I foresee an objection may possibly be made to the partiality of this history,
as being taken from the memoirs and records of the people whose history it is.
In many cases, and this in particular, no other authentic records can be met with,
but what are preserved amongst the people themselves; notwithstanding which,
histories founded on such records, have obtained a reception;
whilst those founded on public rumour or uncertain
and obscure tradition obtain but little credit.
Who that hath read Moses`'s plain account of the descendants of Israel,
regards the fabulous narrative of Justin?
If we had no accounts of the primitive Christians but in the works of the Gentiles,
would not Christianity itself be contemptible, as well as Quakerism so called?
But with us who are favoured with the writings of the evangelists,
the acts of the apostles, and other records of the primitive Christians themselves,
the Gentile descriptions of them are thought worthy of little regard.
Societies whose virtues have been more active in private
life than in the bustles and notoriety of public affairs,
escape the public attention, so far,
as to leave few genuine records of transactions in which they are engaged,
except such as are preserved amongst themselves.

The authorities I have chiefly followed are William Sewel`'s history of
this people compared with Joseph Belle`'s collection of their sufferings,
in the compilation whereof he informs us he "`had recourse to their own manuscript records,
wherein is preserved a genuine account of such of the sufferings
of their friends as were transmitted to them;
and also consulted several printed accounts,
which were published at or near the time of the transactions related.`"
I have been further assisted by the perusal of the
journals of several members of this society,
who have left us memoirs of their lives and travels,
and of the transactions in which they were engaged:
For the account of the settlement of this people
in Pennsylvania and some other parts of America,
I am much indebted to the assistance of my esteemed friend James Pemberton,
and some other friends of Philadelphia, who with singular industry,
have procured and furnished me with a transcript of their history in manuscript,
drawn up by Samuel Smith, but never published; and other authentic manuscripts.

In fine, if I have succeeded in my endeavours,
to avail myself of the materials in my hands,
so judiciously as to answer the expectations of my friends in a tolerable degree,
and to convey some satisfaction and profitable reflection to the readers in general,
my design in under taking this work will not be entirely frustrated: If otherwise,
I hope I shall rest satisfied in the conscious reflection
of endeavouring to be of some usefulness in life,
to dedicate a portion of my time to the service of society,
and to promote religious consideration in an age too much relaxed by dissipation,
by levity of conduct, by spiritual indolence,
and great forgetfulness of the concerns of their immortal part.
