== Introduction.

[.old-style]
=== Section I. / Of the different Dispensations, or Means whereby God hath condescended to reveal the Knowledge of himself and his Will to Mankind.

The universal consent of all nations hath been advanced as a proof of the Being of a God:
That in almost all ages and places of the world,
the inhabitants had some notions of a Supreme Being; some way of worship;
and some sense of religion amongst them: But the various erroneous notions,
imperfect conceptions and absurd fictions, concerning the supreme Being,
that religion which recommended man to his favour,
and that worship which he required at his hand,
which have been adopted by all nations whether civilized or not,
the Greeks no less than the Barbarians,
amount to a presumptive proof of the advantage and necessity of a divine revelation,
to rescue men from error, to illuminate their dark understandings,
and to convey more just notions of God, of true religion, and acceptable worship.
Proving the truth of the apostle`'s reasoning, 1 Cor. 2:14.
"`What man knoweth the things of a man, save the Spirit of man,
that is in him?
Even so the things of God knoweth no man, but the Spirit of God.
The natural man knoweth not the things of the Spirit of God;
for they are foolishness unto him; neither can he know them;
because they are spiritually discerned.`"

The Creator of man, in his unsearchable wisdom,
hath chosen different means by which to reveal this knowledge of himself to
different ages of the world:
First (according to scripture testimony) to the Patriarchs by Angels;
next to the Jews by the Law of Moses.
"`This dispensation,`" saith William Penn, "`was much outward,
and suited to a low and servile state,
called therefore by the apostle Paul that of a School-master,
which was to prepare the people to look and long for the Messiah to deliver
them from the servitude of a ceremonious and imperfect dispensation,
being only the shadow of good things to come,
by discovering to them the knowledge of the reality and substance of pure religion,
typified by the shadowy ceremonies of the law.`"

The ministration of the prophets was the summit of the legal dispensation,
and more immediately preparatory to the introduction of the Gospel of Jesus Christ,
as more clearly pointing out its nature and advantages above the dispensation of the law;
and preparing that people for the reception thereof,
by representing the legal ceremonies ineffectual to please God,
without ceasing to do evil and learning to do well.
This dispensation ended in the ministration of John the Baptist,
the forerunner of the Messiah, as John`'s was finished in him, the fulness of all.

Now God,
who at sundry times and in divers manners spake to
their fathers by his servants the Prophets,
spake to men by his son, whom he made heir of all things.
And the religion, which this teacher come from heaven introduced, excelled every other,
as far as the divine author excelled the sons of men.
I should think it bordering on blasphemy to bring into any comparison with it,
the vanities of the Gentiles, who knew not God: But a short view thereof,
compared with the Mosaic dispensation,
may conduce to the elucidation of its superior excellency.
The law of Moses was an outward and partial law, written on tables of stone;
the grace and truth which came by Jesus Christ was an inward and universal law,
written on the living tables of the hearts of men.
The dispensation of the Gospel being the new covenant prophesied of by Jeremiah:
"`And it shall come to pass in the last days, saith the Lord,
that I will make a new Covenant with the house of Israel and with
the house of Judah--I will write my law in their hearts,
and put my spirit in their inward parts,`" etc.

Under the legal dispensation the worship of God was more particularly
restricted to the temple at Jerusalem built of stone;
but this restricted worship was abolished under the universal Gospel of Jesus Christ,
being to be no longer confined to time or place; neither to Jerusalem,
nor to the mountain of Samaria;
but the true worship of God was to be performed in spirit and in truth,
God was now declared not to dwell in temples made with hands,
but in the living temples of the purified hearts of true believers.
The law of Moses as an outward law reached the outward action;
the Gospel of Christ as a spiritual dispensation
laid the axe to the root of the corrupt tree,
to manifest and destroy sin in its first conception in the heart,
in the root and ground thereof: "`His fan is in his hand,`" said John,
"`and he will thoroughly purge his floor.`"
The law of Moses made not the comers thereunto perfect as pertaining to the conscience;
but the bringing in of a better hope did.
The inside of the cup and platter was to be cleansed,
that the outside might be clean also.
Thus the Gospel appears in its direct tendency designed to rectify the heart,
and purify the conscience from the corruptions of human nature,
that the efficient cause of sin and evil being destroyed, the effect may cease;
and the tree being made good, the fruit thereof may be good also,
that is if the heart be made right in the sight of God,
the whole conversation of consequence will be unspotted,
and productive of every religious, social and moral virtue.

Thus the Christian religion in its original purity,
as it was delivered to the world by its divine author and his apostles,
carrieth in it the plain marks of its divine origin;
as being calculated to answer the important ends of true religion,
according to the prophetic anthem of the heavenly host,
in the prospect of the great benefits it would confer on the human race,
_Glory to God in the highest; in earth peace, good-will to men._
It is plain, practical and spiritual; not a system of nice speculations,
accommodated only to the understandings of the narrow
circle of the wise and the learned of this world;
but of important and practical truths adapted to the comprehension of common capacities,
as being designed for the common benefit of mankind; not amuse the heads,
but to amend the hearts of men:
To instruct all who are sincere in their inquiry after salvation,
in the most excellent wisdom, and most solid virtue, for the attainment thereof.
It abolished the ceremonial part of the law, which was to continue but for a season,
refineth and establisheth the moral part, as being in its nature of perpetual obligation,
resolving it into two very comprehensive, but very intelligible precepts,
viz. "`Thou shalt love the Lord thy God with all thy heart, with all thy soul,
with all thy mind, and with all thy strength, and thy neighbour as thyself.`"
"`Whatsoever ye would that men should do to you, do ye even so unto them.`"

Notwithstanding the evident importance and advantages of the doctrines of the Gospel,
the propensities of human nature inclining men to sensual gratifications,
and selfish indulgencies, in a direct opposition to the tenour of these doctrines, He,
who knoweth all things, knowing this,
lays it down as a radical principle requisite in a Christian, to take up his cross daily,
deny himself, and follow him.
And for his direction and assistance in reducing this doctrine to practice, hath,
by his mediation and intercession, procured for;
him the Gift of the Holy Spirit and Grace of God,
both to illuminate his darkened understanding with the clear discovery of sin and evil,
in its conception in the heart;
and to assist him to subdue his natural propensity thereto.
"`The Law was given by Moses; but Grace and Truth came by Jesus Christ.`"^
footnote:[John 1:17]
"`If I go not away, the Comforter will not come; but if I go away,
I will pray the Father, and he will send you another Comforter, even the Spirit of Truth,
whom the world cannot receive, because it seeth him not, neither knoweth him;
but ye know him, for he is with you and shall be in you.`"^
footnote:[John 14:17]
"`When the Spirit of Truth is come he will guide you into all truth.`"

To these great and beneficial ends of the dispensation
of the Son of God did the Apostles bear testimony,
whom he had chosen, and qualified by his spirit,
to turn the Jews from their prejudice and superstition,
and the Gentiles from their vanity and idolatry, to the light and spirit of Christ,
that they might be quickened from the sins and transgressions in which they were dead,
to serve the Lord in the newness of the spirit of life.
It was up on this inward principle,
which cleanses the inside by the washing of regeneration,
and the renewing of the Holy Ghost,
that they endeavoured to build up and establish the
primitive believers as the surest foundation,
of real piety and moral rectitude.
The primitive Christians were of consequence eminently
distinguished for a purity and integrity of life,
representing the essence of Christianity not to consist
in refined speculation or elegant expression,
but in living well,
exemplifying their faith in Christ by an uniform observance of his divine precepts;
and approving themselves (by walking in the light) children of the light,
born not of the will of the flesh, nor of the will of man, but of the will of God,
by doing his will, and denying their own.

Through the successful and effectual labours of the Apostles
the Church maintained her brightness during their age,
being dignified with all the beauty of holiness,
as a city set upon a hill her light shed a lustre,
attracting both Jews and Gentiles to the sense and love of truth;
the multitude of Christians increased greatly.
Yet even during that age some symptoms of declension were discovered,
of which these faithful pastors,
were not wanting to give timely warning to the believers,
as well as of a greater degeneracy,
which they foresaw would overspread the Church to eclipse the brightness thereof.
As the Apostle Paul, in his first epistle to Timothy,
"`Now the spirit speaketh expressly,
that in the latter times some shall depart from the faith,
giving heed to seducing spirits and doctrines of devils; speaking lies in hypocrisy,
having their consciences seared, forbidding to marry,
and commanding to abstain from meats.`"^
footnote:[1 Timothy 4:1-3]
And in his epistle to the Thessalonians, cautioning them not to be troubled,
as if the day of the Lord was at hand, he adds, "`That day shall not come,
except there come a falling away first, and the man of sin be revealed,
the son of perdition.`"^
footnote:[2 Thessalonians 2:3]
The apostle Peter also expresseth a clear foresight of a future apostacy:
"`There were false prophets among the people,
even as there shall be false teachers among you,
who privily shall bring in damnable heresies, even denying the Lord that bought them,
and bring upon themselves swift destruction;
and through covetousness shall they with feigned words make merchandize of you.`"^
footnote:[2 Peter 2:1,3]

[.old-style]
=== Section II. / Of the gradual Declension and Apostacy of the professed and visible Church.

These predictions were soon verified by the consequential
degeneracy of the Christian Church,
from the internal life of godliness into external observations of days and meats;
into useless ceremonies and unimportant debates.
As early as the second century we find the churches of the East and West involved
in a warm dispute upon a point of no greater consequence than whether Easter
should be celebrated on the day whereon the Jew celebrated the passover,
according to the law of Moses, or on the first day of the succeeding week.
Frivolous as the subject of this controversy was,
it was carried on with as much zeal and earnestness as if
the present and future happiness of mankind depended thereupon;
and so great was the animosity it occasioned, that Victor, bishop of Rome,
excommunicated, or threatened to excommunicate, the Asiatic churches,
because they dissented from his decision.

The fourth century produced a revolution in the Christian Church which,
in its consequences, brought on an almost total reverie to the Gospel of Jesus Christ,
and the doctrines of his apostles.
Constantine, emperor of Rome, embraced the profession of Christianity,
whereby that profession, from an object of persecution, aversion and contempt,
became the religion in vogue.
The Gentile priests, and people of course, adopted this profession,
not so much from a conscientious conviction of the truth and purity thereof,
as from the frivolous motive of complying with the fashion,
or the more unchristian motives of securing and advancing their secular interests,
or gratifying their lust of power.
These pagan priests, accustomed to a ceremonious and pompous religion,
introduced the impure mixture into the Christian Church, before too much declined:
But from this period corruption overspread to an extensive degree.
"`An attachment to heathenish and Jewish ceremonies,
the introduction of images into the public places of worship,
the canonizing and invoking of saints,`"^
footnote:[Formey]
and reversing Christianity into idolatry,
from which it is most abhorrent, are flagrant instances that Christianity,
thus metamorphosed, had no title to the character of the Church of Christ,
being in its spirit and tendency the very reverse thereof.

Yet though the visible church had lost the nature,
she endeavoured to keep up her good name of _The True Church_
and mother of the faithful Her bishops and priests having,
many of them adopted the profession of Christianity from worldly motives,
manifested their conversion to be only in name, their minds remained worldly still.
They were more intent upon recommending worship by ostentatious pomp and splendour,
to catch the eyes of men, than the humility, and sincerity, of heart,
which in the church`'s original state, of purity had made it acceptable to God.
What now continued to be professed for the Christian religion degenerated into form,
and even that form became exceedingly marred by the introduction
of unedifying ceremonies and insignificant observations.
Then human invention took the seat of divine wisdom,
human policy was substituted for divine
Grace, the ordination of men in the stead of the call of the Holy Ghost,
and temporal revenues, powers and honours became more sought after than divine favour.

Not very long after another incident succeeded,
which increased the degeneracy and distractions of the visible church,
viz. the irruption of the northern nations of Europe into the Roman empire,
marking their progress with desolation and destruction
by fire and sword wherever they came;
perfect strangers to decorum and civilization,
what religion they had was idolatry of the grossest kind,
on a profession of Christianity little better: idolatry,
paganism and gross ignorance again overspread all Europe,
and for a season overran the nations thereof,
so that even the name and profession of Christianity became greatly obscured.
After the Goths and Vandals, and the other northern invaders, had subdued all opposition,
they settled down quietly in their conquests,
having left no enemy able to withstand or oppose them;
and by this means the states returning to a settlement, though an imperfect one,
the monks and other ecclesiastics, about the seventh century,
employed themselves zealously to convert these pagan nations to the profession of Christianity,
and met with considerable success; but the doctrines which they taught,
and the ends which they had in view,
were very different from the purity of the apostolic age,
the heavenly doctrines of Christianity being vastly
corrupted by the impure mixture of superstition;
and the end in view being the advancement of clerical interest and power,
they chiefly influenced their converts to submission to the power of the Pope,
and liberality to the priesthood.

The effect of their labours, and the temper of their converts,
as they are described by an eminent historian, evince the nature of their doctrines:

"`The barbarous nations, when converted to Christianity, changed the object,
not the spirit of their religious worship.
They endeavoured to conciliate the favour of the true God by means
not unlike to those they had employed to appease their false deities.
Instead of aspiring to sanctity and virtue,
which alone can render men acceptable to the great author of order and excellence,
they imagined they satisfied every obligation of
duty by a scrupulous observance of external ceremonies.
Religion, according to their conception of it, comprehended nothing else;
and the rites by which they persuaded themselves they could gain the favour of heaven,
were of such a nature as might have been expected from the
rude ideas of the ages which devised and introduced them.
They were either so unmeaning as to be altogether unworthy
of the Divine Being to whose honour they were consecrated,
or so absurd as to be a disgrace to reason and humanity.`"^
footnote:[William Robertson]

This was another revolution in the visible church, which increased her degeneracy,
eclipsed her beauty, and established a kingdom of priests.
These barbarians, grossly ignorant themselves,
destroyed the monuments of literature and science in their way,
as objects of little value with them,
and introduced a general barbarity wherever they settled: "`The human mind,
uncultivated and depressed, sunk into profound ignorance.`"
In this age of intellectual darkness,
the brightness of the christian religion suffered an additional eclipse,
for although its precepts are "`delivered in scripture with a precision which
should prevent their being wrested or corrupted,`" yet a body of men,
who from the highest to the lowest could few of them write or read,
could draw no intelligence of duty from that fountain,
but simply rested upon the word of the priest for instruction.
And notwithstanding the priests were, for the most part,
involved in the general gloom and ignorance,
insomuch that many of them did not understand the
breviary they were obliged daily to recite,
and several of them could not read it,
they had nevertheless the craft to avail themselves
of the ignorance and prejudices of the people,
to procure the guidance of their consciences, emoluments and power to their own order,
and a superstitious veneration to their persons.

From this time ecclesiastical history (too much sullied
before) becomes deformed with instances of ambition,
avarice, political intrigues, persecution, cruelty and revenge,
(qualities diametrically opposite to the purity and nature of Christianity) in
an equal or superior degree to the annals of most secular kingdoms.

[quote]
____
The bishops in general, who had the chief authority in church affairs, had,
for a succession of ages,
lost daily more and more the proper qualifications of overseers in the Church of Christ,
true piety and ancient simplicity of manners;
and were so taken up with the desire of enlarging their pretensions and prerogatives,
that the promotion of pure religion,
or the salvation of those souls committed to their charge,
seems to have been the least of their concern.
Nor were they content with grasping most or all the power and possessions
of their respective fees into their own hands,
but by the impulse of their unbounded ambition they entered into shameful
and unchristian contentions with each other for preeminence in dignity,
and supremacy in power.

The fees of Alexandria, Rome and Constantinople became,
in a short time after Constantine`'s public profession of the Christian faith,
possessed of so much power and wealth,
that to gain possession of them engaged the emulous efforts of the principal ecclesiastics;
and the means employed to attain their desire were as irreconcilable
to the pure principles of Christianity as the object thereof,
being frequently pursued by indirect means, frequently by violence and force of arms.
And in a like manner they possessed them in too general a way,
living on the spoil of the churches in splendor and luxury,
inconsistent with the humility and temperance prescribed by the Gospel of Jesus Christ.^
footnote:[Formey]
____

The bishops of Rome, through the favour and assistance of the western potentates,
succeeded at length in the struggle for supremacy,
in claiming and procuring to themselves the titles
of _Universal Bishop Vicar of Jesus Christ,_
and _Infallible Head of the Church._
These claims, chimerical in themselves,
and quite opposite to the genius of the Christian religion,
could hardly have been advanced with any reasonable prospect of establishing them,
but in such an age of gross ignorance and credulity as this:
Yet on these visionary foundations the ecclesiastics found
means to raise a superstructure of priestly dominion,
which not only gave to the papal decrees a sanction
and obedience from all degrees of people,
as divine and infallible oracles,
but made even kings and emperors feel the effects of the plenitude of that power,
which they had artfully established over the consciences and understandings of mankind.

Splendour and magnificence, the attendants of ambition,
are generally the parents of avarice, as they create many unnecessary wants,
and much superfluity of expence; the clergy, therefore,
were not wanting to turn the influence they had acquired to their own secular advantage,
by a continual augmentation of their property as well as their power.
In the primitive church, as in all visible societies,
it was necessary to raise some contributions for the public uses of the church,
of which the support of the poor, and the public edifices, seem to be the principal part:
These contributions were purely voluntary,
and the distribution thereof entrusted to the deacons,
the apostles having assigned this charge to them.
And as they were content with food and raiment,
their demands upon the public stock were proportionately moderate, if any.
Their principal concern was to gain souls to Christ,
not to extort or secure property to themselves.
They sought not theirs, but them.

The church continued for some ages to defray the necessary expences,
by the voluntary contributions or its members,
and while she was under a state of suffering and persecution it is natural
to suppose she was preserved in humility and heavenly mindedness for what
could nourish pride in men treated with universal contempt and hatred,
as the scum and off-scouring of all things?
what temptation could they have to enlarge their worldly prospects,
who lived every hour in jeopardy?
or what could support them under the cruel persecutions they were exposed to,
or enable them, in testimony to the truth in which they most surely believed,
to meet a violent death in all its terrors and tortures
with calm fortitude and religious joy,
but a mind redeemed from the earth,
and panting for the full fruition of happiness in a future state?
This temper of mind reduced their wants within narrow limits,
which were easily satisfied:
And being connected in gospel fellowship by the strong
bonds of mutual benevolence and brotherly kindness,
they who had to spare communicated to the wants of the church and of their brethren,
according to their abilities with liberality.

But when Christianity,
from a state of persecution became the reigning religion of the empire,
and the church was enriched with secular possessions;
when princes and nobles had adopted the Christian profession,
and a notion was artfully propagated, that munificence to the church would atone for sin,
and purchase future felicity,
and the great found it easier to give freely than live well,
her possessions vastly increased by donations of lands, and pecuniary oblations:
But as her portion increased, her beauty decayed.
They whose office should have been exercised, after the original pattern,
in diligent labour and vigilance to prevent the introduction,
and overspreading of corruption in the church,
became no less conspicuous for their avarice than their ambition.
The bishops, as it might seem,
in order to get the revenues of the church into their possession;
relieved the deacons from the charge of the administration, and took it upon themselves.
When the bishops of Rome, assuming the title of Universal Bishop,
affected the state of secular princes,
they soon found means to appropriate the lands of the church of Rome to the fee.
Other bishops soon followed their example,
and engrossed to themselves the patrimony of the churches under their care,
of consequence, the poor and other necessary charges of the church,
were but scantily provided for.

Amongst the rest the inferior orders of the clergy, who were dependent on the bishops,
had been destitute of support by other means,
than their portion of the income of the church lands.
It seemed necessary to devise means for their support, independent of this income,
and with that view they cast their eyes upon the tithe of the produce of lands,
after the Jewish model; these were accordingly preached up with remarkable zeal:
"`So that during some centuries (saith a modern historian)^
footnote:[David Hume]
the whole scope of homilies and sermons was directed to
influence the people to punctuality in paying them;
and one would have imagined, from the general tenor of these discourses,
that all the practical parts of Christianity were comprehended
in the exact and faithful payment of tithes to the clergy.`"
In addition to this extensive revenue,
various other pretexts were contrived to increase it still more: Purgatory, penance,
dispensations, indulgences,
were crafty impositions upon the credulity of these
dark ages to extort gain to the priesthood:
The living were deceived in to liberality; and the dying,
in their weakest moments of despondency and approaching dissolution,
were beset by designing ecclesiastics,
to obtain bequests under the notion of purchasing
a communion of the good works of the church,
in order to increase the estate and revenue thereof.

About the end of the thirteenth century the apostacy was come to the height.
There appeared little in the professing Christian church which
bare any resemblance to the religion of Christ and his apostles.
The holy scriptures being locked up in an unknown tongue,
beyond the comprehension of the ignorant people of this illiterate age,
they were deprived of these means of discovering the traces of pure Christianity,
and the corruptions which had crept into the church.
They had no means of knowing what Christianity was but through
the corrupt representations of their teachers.
The rules of their conduct were not the sacred precepts of the Gospel,
but the decrees of Popes; and innovations, and unmeaning fancies of visionary Monks;
which, instead of promoting the true spirit of religion,
appear studiously calculated to draw off the human mind from researches of this nature,
as such enquiries must have a tendency to detect
the deceptions of these (apparently pious) impostors.

Yet as in the purest ages of the church there were some
members who were not sincere and steadfast in the faith,
or fell away therefrom, so in the most corrupted state thereof, I believe,
there were several who, through all the mist of ignorance and superstition,
were faithful according to their knowledge, and sincerely disposed to do the will of God,
as far as they could discover it; but being few were hidden and obscure.
"`For it was now,`" saith William Penn, "`the true church fled into the wilderness,
that is from superstition and violence, to a retired, solitary and lonely state, hidden,
and out of the sight of men.
In this state many attempts she made to return,
but the waters yet too high blocked up her way,
and many of her excellent children in several nations fell by the cruelty of superstition,
because they would not fall from their faithfulness to the truth.`"^
footnote:[From The Rise and Progress of the People Called Quakers]

[.old-style]
=== Section III. / Of the gradual Advancement of the Reformation.

Even during these ages of gross darkness there arose a few individuals
endued with light and sense to discern the enormities abounding
in the church fortitude to bear their testimony against them,
and fidelity to seal their testimony with their blood.
For the general darkness was too gross as yet to admit a full display of light,
and the dominion of priestcraft over the consciences of the people so riveted,
and its power so firmly fixed, that every attempt to remonstrate against corruption,
and to let light into the minds of the people,
whereby the sources of the wealth and power of the
priesthood might be in danger of being exhausted,
was frustrate,
and generally terminated in the punishment of those who made such attempts with death.
For the visible church of those ages,
that she might manifest her variance with the true church of Christ in all her fruits,
in her treatment of those who opposed her doctrines,
or exposed the futility of her claims,
gave a scope to her vindictive resentments in the exercise of unparalleled cruelty,
not only opposite to the meekness and forbearance
prescribed by the doctrines of the gospel,
but disgustful to the feelings of common humanity.

In the 12th century Peter Waldo, a citizen of Lyons, about the year 1140,
applying himself to the study of the scriptures,
and finding therein no grounds for several of the popish doctrines and practices,
publicly opposed them.
He translated the scriptures into the vulgar language,
and from them taught and inculcated a doctrine much more conformable
to the gospel of Christ than that professed in the Roman church.
His followers were denominated Vaudois or Waldenses.
In the same century arose another body of men of like sentiments,
who also perceiving the palpable errors and shameful vices of the Romanists,
thought it their duty to separate from their communion,
and to exert their endeavours for a reformation.
These were the Albigenses, who were so named from Albi, a considerable town of Languedoc,
near which Peter and Henry Bruys, the first preachers of this sect,
formed their assemblies.

The popes and the clergy,
having long enjoyed an uninterrupted dominion over the consciences of mankind,
as far as their power extended, and stopped up the avenues of free inquiry,
by implanting in the human mind an implicit trust in their doctrines and decrees,
were very much alarmed and exasperated at these efforts to cast off the yoke,
and unveil the mystery of iniquity.
And accordingly made these Vaudois and Albiegenses feel the weight
of their resentment in all its strength and violence.
Most of their teachers were dragged to the stake;
and it was only the increasing number and power of their adherents,
rendering them formidable, which for the present rescued them from sharing the same fate.

But in the succeeding century, under the despotic papacy of Innocent III.
whose haughtiness made kings and emperors submit to his imperious sway,
a cruel and bloody war, to which the blasphemous appellation of the _Holy War_ was affixed,
in order to enflame and deceive the people,
was raised and carried on by the instigation of the pope and his dependant ecclesiastics,
who called in the force of arms against these Vaudois
and Albigenses to gratify their implacable aversion:
They invited the princes to assist them, particularly Philip Augustus, King of France.
They raised numerous troops, who set up the cross,^
footnote:[The Cross was the badge worn by those who engaged in the Crusades,
or wars undertaken against the infidels to dispossess them of the Holy Land (so called).
These wars were termed holy,
and those who engaged in them (besides many other privileges)
were persuaded that they were engaged in the cause of heaven,
and under its immediate protection:
They received a plenary indulgence for the remission of all their sins, etc.
In imitation of these appendages of the Crusades, those of this war were assumed;
to fix an impression on the minds of the men employed therein,
that they were embarqued in a sacred cause;
that their exertions therein would atone for their sins,
and that the gates of heaven were open to such as should fall in the holy warfare.
By such artifices the Pope and his Clergy raised armies in their cause,
regardless of the guilt of sanctifying the most flagitious crimes,
under colour of means to obtain eternal happiness.
Formey writes, "`Amongst the most zealous promoters of this war, called holy,
but that in reality was most execrable, we find Dominick Guzman, a Spaniard,
who founded the order of Preachers called Dominicans,
and contrived the dreadful tribunal of the inquisition: And Francis of Asisses, who,
about the same time, gave rise to the order of Minorites or Franciscans.
These two men were afterwards ranked by the Catholics in the number of their Saints,
and not undeservedly, if the most bloody fury, and the most extravagant notions,
could give them a right to sanctity.`"]
indulgences were freely given, and the war was carried on with cruelty almost unequalled,
in order to effect the entire extirpation of these sects:
But they failed of accomplishing this design;
for their barbarous treatment of such of the Vaudois as
fell into their hands struck the rest with such horror,
that when they were reduced by war, so as to be unequal to further resistance,
they avoided the tortures designed for them, by dispersing,
and spreading themselves and their tenets in different parts of Europe,
Divine Providence so ordering it,
that by these means the seeds of the reformation were widely scattered.

The next essay towards a reformation, which claims our attention,
took its rise in England,
through divine goodness one of the first states of Europe
favoured with the dawn of the light of reformation.
John Wickliffe, rector of Lutterworth in Leicestershire,
lived in the latter end of the reign of Edward III.
and the beginning of that of Richard II about 130 years before Luther,
a man of good understanding, great courage, and solid piety.
The doctrine he publicly preached was directly opposite to the received notions.
He particularly insisted on the vices of the priests, the tyranny of the court of Rome,
and the insatiable avarice of the monks, who invaded everything;
and persevered with great zeal and intrepidity to oppose superstition and unmask hypocrisy.
Being appointed by Edward III,
one of the members of an embassy sent in 1373 to Pope Gregory at Avignon,
to remonstrate against the heavy taxes with which England was burdened by the popes,
he was furnished with an opportunity of seeing the papal court,
observing the nature of its policy, and the licentiousness of its morals,
at which he conceived much disgust, persuading himself it was the fee of Antichrist.

He applied himself with diligence to the study of the sacred writings,
and was the first who translated them into English.
From this source drawing,
purer instruction concerning the nature and spirit of the Christian
religion than that which was conveyed through the vitiated channel
of the clerical doctrines and expositions of those times,
he clearly perceived the nullity of various papal pretensions;
that the Pope had no valid claim to infallibility;
that the power he had assumed over all the church, and over the princes of Christendom,
was a mere groundless imposition, without authority from reason or revelation.
He opposed the worshiping of saints and images, indulgences, the celibacy of the clergy,
the doctrines of transubstantiation and auricular confession.
He maintained that the New Testament was a perfect rule of faith and manners,
and therefore ought not to be kept from the people,
but divulged amongst them that they might read it; and that tithes were pure alms,
which should not be extorted by compulsion,
but accepted as the voluntary oblations of the donor.
His doctrines thus derived from the same original, viz. the scriptures,
and the practice of the primitive church,
are represented to be nearly the same with those propagated
by the reformers in the sixteenth century.

Notwithstanding this bold and open opposition to doctrines and practices,
which had passed for certain and reasonable,
and received the sanction of the assent and approbation of several ages,
this reformer was favoured beyond the preceding reformers,
to escape the punishment of his heresy, as it was termed,
and died of a stroke of the palsy in the year 1385, at his rectory of Lutterworth.
This was not owing to any relenting temper or tenderness in the ecclesiastics:
They wanted power more than inclination to punish the man
who had the audacity to undermine their credit and authority.
It was a great mortification to them that he had escaped their vengeance while living,
which they wreaked upon his memory and reputation after his death,
blasphemously and maliciously asserting that he was gone into eternal damnation,
and that his last distemper was a judgment upon him for his manifold heresies and impieties.^
footnote:[What these impieties were, we may easily apprehend;
when we consider that what passed for religion at
this era was devotion to the interests of the Clergy,
and veneration to their order.
For as to his moral conduct we are informed that "`Wickliffe himself,
as well as his disciples,
was distinguished by a remarkable austerity of life and manners.`"
Hume Vol.
2 p. 56]
Besides this, ecclesiastical malice, unlimited in cruelty, and unabated by time,
vented itself in a ridiculous and senseless persecution of his remains,
his body being dug up and burned by a decree of the
council of Constance forty years after his decease.
The same council condemned to the flames two Bohemian disciples of his,
John Hus and Jerome of Prague, in violation of good faith,
they having attended the said council under promise
of protection by the emperor`'s safe conduct.

Edward the III.
a prince of great wisdom and fortitude,
had penetration to perceive the pernicious tendency of the papal encroachments,
and the nullity of their pretensions to revenues and dominion in England;
and the spirit to withhold the one and withstand the other.
And this spirit in the prince seems to have spread amongst the people,
which opened the way for the reception of Wickliffe`'s doctrines,
amidst a general discontent at the usurpations both of the pope and their own priests.
Above the rest John of Ghent, Duke of Lancaster, brother to the King,
and during the minority of Richard regent of the kingdom, encouraged his principles,
and protected his person against the vindictive measures of the clergy,
to bring him to punishment, which they repeatedly attempted,
but were disappointed of effecting their purpose.
Such was the disposition of the nation at this time,
that the proselytes to his doctrines,
who received the appellations of Wickliffites and Lollards, became very numerous;
and although the priests in the succeeding reigns
regained power to persecute them with violence,
they could not thoroughly eradicate the principles he had
propagated from the minds of many of the people of England;
who were thereby prepared more readily to fall in with the
more extensive reformation of the following age.

When the professors of Christianity in the papacy of Urban II. in the eleventh century,
were almost universally seized with the extravagant passion
of recovering Palestine out of the hands of the infidels,
and resolved upon those expeditions,
which were distinguished by the denomination of Crusades,
from the standard of the cross erected by the pope,
and the signs thereof worn by the soldiers employed therein, the pope and the clergy,
actuated by an extraordinary zeal to forward this pious undertaking
(as they would have it esteemed) amongst other immunities and privileges
granted those who should engage therein a plenary indulgence,
and remission of all their sins.
The gates of heaven (they were made to believe) were set open to them,
without any other proof of their penitence than engaging in these expeditions.
The prevalent effect of these indulgences upon the
superstitious imaginations of the people,
in bringing vast numbers to enlist under the banner of the cross,
encouraged the ecclesiastics to continue them after the Crusades were laid aside,
on every future occasion of suppressing all who became obnoxious to ecclesiastical power,
under the notion of heretics,
a term of reproach and odium applied to all such as exposed the futility
of their usurpation of power over the consciences and rights of mankind.
Their wars against the Vaudois, it hath been remarked, they termed holy,
in imitation of the Crusades,
and like indulgences were promised to the adventurers therein.

But these indulgences were not confined merely to
the purpose of encouraging religious wars:
When the priests and monks had wrought upon the superstitious minds of their followers,
to bring them into the delusive persuasion of the efficacy of them,
they converted them into a very lucrative and scandalous traffic,
which obtained and gained ground till the popedom of Leo X.
a man more celebrated for a taste in literature and elegance,
and the encouragement thereof, than for experience in religion,
or promoting it in purity: The liberality of his disposition,
and his affectation of great splendour and magnificence,
ran him into a profusion of expence,
to which even the revenues of the papal fee were inadequate.
So that in order to provide a more ample supply, he resorted, amongst other means,
to a sale of indulgences; the dispersing of which in Saxony was committed to one Tetzel,
a Dominican friar.
This man and his associates scandalized the more serious and thinking part of the people,
both by the extravagance of their assertions in favour of their merchandize,
and by the licentiousness of their morals.
Martin Luther, an Augustine monk,
offended at Tetzel`'s absurd and wicked assertions in recommendation of his wares,
stood forth in open opposition thereto,
and in his sermons and writings zealously endeavoured to open the
peoples eyes to discern the fraudulence and impiety of this imposition.
The gross darkness of the night of apostacy was drawing to an end,
wherein mankind had been artfully kept in ignorance of their rights and real interest;
and the dawning of clearer light was fast advancing,
and opening the understandings and minds of many for the
more ready reception of the purer doctrines of the gospel.
Luther`'s doctrines gained ground in Germany,
in spite of the united efforts of the secular and ecclesiastical powers.
Even the Pope`'s Bull, which had been so formidable to the greatest potentates,
made little impression on Luther and his followers;
he disregarded all their menaces and attempts to stop his progress;
and being supported by sundry princes of the empire, particularly the Electors of Saxony,
he proceeded strenuously and undauntedly in the work of reformation,
in which he was effectually seconded by Philip Melancthon;
and soon after Zuinglius embarking in the same cause in Switzerland,
the principles of these reformers spread widely through Germany,
and from thence through other parts of Europe.

In England the sparks of light kindled in many hearts by the preceding
labours of John Wickliffe in the cause of reformation,
which had been smothered rather than extinguished
by the persecutions to which the Lollards were exposed,
revived by means of several works of the German reformers translated into English.
William Tindal and some others, who were inclined to the reformation,
dreading the effects of King Henry`'s arbitrary temper, had fled to Antwerp:
During their abode there,
besides other books against the corruptions of the Church of Rome,
Tindal employed himself in translating the scriptures into the English language;
these books they sent into England privately, and by that means made many converts:
But the pertinacious jealousy,
which the Romish ecclesiastics entertained of divulging the Bible in the vulgar tongue,
betrays a consciousness that the dominion they had established upon the superstitions,
and the credulity of ignorance,
would not bear the test of reason enlightened by revelation:
And that while they were pretending to instruct the people in religion,
and artfully making it the supporter of their usurped prerogatives,
they dreaded nothing more than that the people should be supplied with
the means of becoming acquainted with the pure source of religious truth,
exhibited in these sacred records.

The Bishops strenuously decried Tindal`'s translation,
as abounding in errors to that degree that it was not fit to be corrected,
but utterly suppressed.
Tonstal, Bishop of London +++[+++afterwards of Durham]
procured all the copies at Antwerp to be bought up, and burned publicly in Cheapside:
But this did no service to the clerical cause; for a considerable body of the people,
who were now brought over to feel more reverence for these inspired writings,
than for the priesthood,
took occasion of much offence and reproach at committing to the flames those volumes,
which they considered as the word of God.
Neither did it answer the Bishops intention,
for Tindal soon after published a more correct translation of the New Testament,
copies of which were sent over to merchants in London,
who dispersed them privately amongst their friends and acquaintances;
and after some time his translation, being revised and corrected by Archbishop Cranmer,
was established by authority, and in the year 1538, by command of King Henry VIII.
was set up in every parish church, (so called) in order that the people might read it.
This was a great step in favour of the reformation,
and greatly increased the adherents there to.
But this was the utmost of the reformation in this reign;
King Henry continually wavering between the old religion and the new,
kept and left the reformation in an imperfect state.
It was considerably advanced in the minor reign of King Edward VI.

But the succeeding reign of Queen Mary, an arbitrary, weak and cruel princess,
educated in the Romish superstition, to which she was a bigot in the extreme,
overturned the reformation, diverted the national religion into the old channel,
and reintroduced popery, with all its train of superstition, bitterness of enmity,
and severity of persecution.
This revolution proved literally a fiery trial upon the sincerity of the reformers,
many of whom were brought to the stake,
and suffered martyrdom with remarkable fortitude and piety,
bearing a noble testimony to the truth they believed in, and against the errors,
corruptions and cruelty of the church of Rome, to the last.
Unshaken from their faith by flattery or menaces,
they supported their testimony in the midst of tortures,
and undauntedly sealed it with their blood.
It was computed that no less than two hundred and seventy-seven suffered by fire,
besides those punished by imprisonment, fines and confiscations,
and the numbers who sought safety in flight.
Divine Providence was pleased to deliver his people
by cutting short this barbarous reign,
the Queen being removed by death, after a reign of about five years and four months.

She was succeeded by her sister Elizabeth, who from her education,
temper and intellectual abilities,
formed a contrast greatly to her advantage over her predecessor.
She is said to have resolved upon furthering the reformation while she was held in the
constraints of a prison and upon her coming to the crown immediately set about it.
The parliament completed what she had begun,
and in the course of a single session the reformation was established
in that form which constitutes the present system of the church of England;
to the ready accomplishment whereof, it is apprehended,
the disgust conceived by the people at the frequency and
barbarity of the late executions greatly contributed.

It is justly to be esteemed a signal favour,
demanding the grateful acknowledgments of the inhabitants of these nations,
that divine Providence, in abundant mercy to Great Britain and its dependencies,
was pleased to rend the veil of superstition, disperse the cloud of papal darkness,
and cause the morning of Gospel light to dawn upon them; and those pious worthies,
who by the purity of their manners and doctrines, by the tenor of their lives,
and their faithfulness to death in testimony to the truth,
were the principal instruments of bringing about and forwarding the reformation,
are justly entitled to honorable esteem, and doubtless enjoy the reward of well-done.
But as the apostacy from primitive purity was gradual,
and did not arrive at the height in one day or age,
so it is not to be expected in the nature of things,
that a complete reformation should be effected at once;
multitudes attached to opinions long received as unquestionable truths,
were prepossessed against the reformed doctrines; and the majority of the ecclesiastics,
repugnant to a reformation which threatened the diminution of their gain and authority,
violently opposed the attempts of the reformers as dangerous innovations,
insomuch that these were forced to win their way step by step; and at last,
when by the successive revolutions of two reigns the ardour of that zeal
which gave rise to and promoted the reformation began to wear away,
and the protestants, harassed and driven into exile by the persecutions under Mary,
naturally wished for a quiet settlement in their native country on any tolerating terms,
the protestant religion was established in England under Elizabeth;
but in this establishment the maxims of human policy seem to have had too much influence,
whereby those of the scripture were so qualified and restricted as to leave too many
vestiges of the declension from the original purity of the Gospel dispensation remaining,
divers things being reserved in use,
for which we find no precedent in the precepts or practice of our Lord Jesus Christ,
or his apostles after his ascension.

Priestcraft, which ever sullied and obscured the brightness of Gospel light,
had too much scope, and retained too much influence in the established system.
In imitation of the Romish hierarchy,
the clergy of the church of England assumed to themselves
the title and property of the Church,
which originally belonged to the whole body or congregation of the believers.
The first ministers of the Gospel claimed neither to themselves,
as they aimed at no power or dominion over their flocks,
no reverence to their persons or their order,
but what naturally resulted from the superiority of their spiritual gifts,
the excellency of their ministry, and their exemplary lives.
They claimed no share of the church`'s stock, but what necessity required;
they had no idea of engrossing the whole to themselves, and leaving the poor,
and the building or repairing the places of worship,
an additional burden upon their hearers.
And although the reformation in some degree diminished
both the power and the property of the priesthood,
yet it left the more than enough of both to answer the end of a perfect reform,
or to redress all the grievances complained of under the former hierarchy.
It left them titles of distinction unheard and unthought of in the primitive church,
such as archbishops, deans, archdeacons.
It left in possession of the superior orders not only the title of lords of the realm,
but the power and honours appendant to that high rank,
and allotments of lands sufficient to support the state and dignity of that station,
which, however consistent with human policy,
appear to be irreconcilable to these precepts of Christ and his apostles.
"`The princes of the Gentiles exercise dominion over them, and they that are great,
exercise authority upon them: but it shall not be so among you.`"
Matt.
20:25-26. "`A bishop must be blameless, as the steward of God; not self-willed,
not soon angry, not given to wine, no striker; not given to filthy lucre,
but a lover of hospitality; a lover of good men, sober, just, holy, temperate,`" etc.
Titus 1:7-8. "`Feed the flock of God, which is among you, taking the oversight thereof,
not by constraint, but willingly; not for filthy lucre, but of a ready mind:
Neither as being Lords over God`'s heritage, but being examples to the flock.`"
1 Peter 5:2-3.

The vesting in the Bishops such a portion of honour, power and property,
had no tendency to advance reformation;
bearing too near a resemblance to those badges of
distinction borne by those of the Church of Rome,
it was thought by many a resuming of the spirit, and principles of the former hierarchy,
and defeating the ends of separating from that church,
and protesting against the impositions and domineering spirit thereof.

For although we admit that many respectable characters have
adorned the bench of Bishops at and since the reformation,
yet it is too manifest that these honours and emoluments of the
office have proved a tempting bait to ambition to too many others,
probably the greater part,
whereby they have been drawn into negligence of their pastoral charge,
to frequent the courts and palaces of princes, to hunt after greater preferments;
and to pay more attention to their secular, than their spiritual calling.

The power also left in their hands proved a temptation
to revive the spirit of persecution amongst them;
soon forgetting all the ill usage and hardships their predecessors had undergone,
during the bitter intolerancy of the last reign, from the Romish Bishops;
the Protestant Bishops were hardly firmly seated in their stalls,
till they exerted their endeavours to force an uniformity,
which comprehended an universal assent to the propriety of their prerogatives,
and a submission to their power and decrees in matters ecclesiastical,
by the penalties of imprisonments, confiscations, banishment,
and (in some instances) of death.
In their legislative capacity they were too generally
zealous promoters of penal laws against non-conformists,
and in their official and executive capacity strenuous aiders and
abettors in carrying them rigorously into execution.

The reservation of tithes for the maintenance of the priests
is another of the reliques of the apostatized church,
an imposition which even ecclesiastical avarice did not
extort till the ages of gross darkness and ignorance;
and the grounds on which they were claimed,
the return of Gospel light clearly manifested to be merely nugatory,
and that they could not be retained in any reformation reverting to primitive purity,
as no vestige of such a demand could be derived from the new testament,
or the original practice of the Christian church.

Sundry other articles of the former superstition were reformed but partially:
Ostentatious splendor and human contrivance in worship, and in the decoration of temples;
the clerical vestments, pluralities and non-residence of the clergy,
appear plain instances of a deviation from the simplicity, disinterestedness,
and conscientious concern for the propagation of pure religion,
conspicuous in the primitive age of Christianity; and the latter,
of a spirit of avarice approaching to injustice.

William Penn, who lived nearer those times,
and whose introduction to his account of the rise and progress of the people
called Quakers I have had my eye upon in the progress of this part of my work,
having described the successive steps of the reformation in general terms,
I quote his description, with some explanatory notes,
as the readiest method to bring this introduction to a conclusion.

[quote]
____
The last age did set some steps towards reformation, both as to doctrine,
worship and practice; but practice quickly failed,
for wickedness flowed in a little time,
as well among the professors of the reformation as those they reformed from;
so that by the fruits of conversation they were not to be distinguished.
And the children of the reformers, if not the reformers themselves,
betook themselves very early to earthly policy and power,
to uphold and carry on their reformation that had been begun with spiritual weapons;
which I have often thought has been one of the greatest reasons the reformation
made no better progress as to the life and soul of religion.
For whilst the reformers were lowly and spiritually minded, and trusted in God,
and looked to him, and lived in his fear, and consulted not with flesh and blood,
nor sought deliverance in their own way,
there were daily added to the church such as one might reasonably say should be saved;
for they were not so careful to be safe from persecution
as to be faithful and inoffensive under it;
being more concerned to spread the truth by their faith and patience in tribulation,
than to get the worldly power out of their hands
that inflicted those sufferings upon them:
And it will be well if the Lord suffer them not to
fall by the very same way they took to stand.

In doctrine they were in some things short; in other things,
to avoid one extreme they ran into another; and for worship,
there was for the generality, more of man in it than of God.
They owned the spirit, inspiration and revelation indeed,
and grounded their separation and reformation upon
the sense and understanding they received from it,
in the reading of the scriptures of truth.
And this was their plea; the scripture is the text, the spirit the interpreter,
and that to everyone for himself.
But yet there was too much of human invention,
tradition and art that remained both in praying and preaching;
and of worldly authority and worldly greatness in their ministers,
especially in this kingdom, Sweden, Denmark, and some parts of Germany.
God was therefore pleased in England to shift us from vessel to vessel,^
footnote:[These were first distinguished by the appellation of Puritans,
and afterwards by that of Presbyterians.
During the persecution under Mary`'s cruel and bigotted reign many of the reformed
Church had sought an asylum from the fury of the persecution in those foreign
countries where the Protestant religion had obtained an establishment,
particularly at Frankfort and Geneva.
Here a disagreement arose between them respecting ceremonies,
discipline and modes of worship.
Those who had taken up their residence at Frankfort adhering
to the regulations established in England under King Edward,
and those at Geneva adopting the doctrine and discipline established there by Calvin.
When the persecution in England terminated with the life of Mary,
the exiles returned and brought their difference along with them.
The Puritans, so called from their singular purity of life and manners,
in which I have no doubt many of them were very sincere,
being represented of exemplary lives, diligent in preaching, and moral in their conduct,
desirous of a greater reformation,
and wanting the useless ceremonies and clerical habits to be laid aside,
or at least not to be imposed upon them against their consciences;
they also wished the Common-prayer Book to be left indifferent, i.e. to be used or not,
as every minister or congregation might be fully persuaded in their own minds:
Although these demands appear reasonable,
both the civil and ecclesiastical rulers thought otherwise,
and insisted upon an absolute and entire conformity to that model of religion
which they had agreed to establish for the observation of the whole kingdom.
{footnote-paragraph-split}
The Puritans appear not at first to
have entertained any design of separating from the established Church:
their teachers had no aversion to a participation in her revenues,
or to have officiated as parish ministers,
if they might have been indulged to officiate in consistency with their religious scruples;
and many efforts they made in this and the succeeding reigns
to procure for themselves a comprehension in the church.
But the Bishops,
averse to every concession whereby any part of the ecclesiastical revenues
might be possessed without an unreserved conformity to their prescriptions,
and submission to the decrees of their convocations,
in conjunction with the ecclesiastical commissioners appointed by the Queen,
proceeded first to silence the puritan preachers, and deprive them of their benefices;
and afterwards to persecute and imprison them.
The Puritans, hereby despairing of a coalition with the established Church,
withdrew from it, and formed themselves into a separate society;
but with as much privacy as possible, to escape the edge of the penal laws.
{footnote-paragraph-split}
It doth not appear,
that during their endeavours to keep their places in the church,
they made much objection or opposition to the order of Bishops;
but seemed content to act under them,
if they might be allowed the liberty of disusing the vestments,
which they looked upon as reliques of popery,
and of using such parts of the liturgy only as they might judge for edification.
But for their non-conformity in these frivolous and unnecessary matters,
being prosecuted with rigour by the Bishops,
they were confirmed in a dislike to episcopal government;
and when they separated into a select society,
in the place of Bishops they chose ruling Elders, or Presbyters, from among themselves,
from whence they received the appellation of Presbyterians.
{footnote-paragraph-split}
Although in their first separation from the church of Rome,
and afterwards in their dissent from the church of England, the Puritans were,
many of them, actuated by pure conscientious motives, and were men of circumspect lives,
and a pious, religious turn of mind; yet in process of time, historians remark,
the sincerity of their successors, and their zeal for religion,
degenerated into formal preciseness, and outward shew of purity,
while their actions manifested,
that their real views were more turned to the acquisition of secular power than holiness.
To wrest the sword out of the hands of their persecutors,
they formed a party in the state,
and when they had carried their point to get the power into their own hands,
they proved themselves equally intolerant,
and as great sticklers for conformity to their directory, confession of faith,
and solemn league and covenant,
as the Bishops had been for conformity to the use of the surplice, the liturgy,
and the cross in baptism.]
and the next remove humbled the ministry, so that they were more strict in preaching,
devout in praying, and zealous for keeping the Lord`'s Day,
and catechizing of children and servants,
and repeating at home in their families what they had heard in public.
But even as these grew into power, they were not only for whipping some out,
but others into, the temple;
and they appeared rigid in their spirits rather than severe in their lives,
and more for a party than for piety,
which brought forth another people that were yet more retired and select.^
footnote:[This sect at first received the appellation of Brownists,
from Robert Brown their pastor, a puritan preacher of Norfolk,
and afterwards that of Independents:
His followers were so prejudiced against the established church,
by reason of the severities she exercised upon the Puritans,
that they went farther in their separation than the Presbyterians had done;
for the latter were very willing to own her as a true church, and even to unite with her,
if she would but abate them certain ceremonious usages;
but the Independents would not allow her to be a true church,
nor her ministers true ministers, and renounced all communion with her.
They apprehended every church ought to be limited within the bounds of a single congregation,
and that it had full power, exclusive of secular penalties,
over its own pastor and members,
independent of the superintendency or control of
any other congregation or general assembly,
or of the civil magistrate,
as far as conscientious scruples gave no disturbance to civil order;
(for although they found it afterwards expedient to convene Synods,
they allowed them only the privilege of advising,
but not of any control or governing power) and thence they were stiled Independents;
but this independence connected them so slightly,
and their particular sentiments seem to have been of different,
that it was difficult for them to adhere closely together,
or for others to know precisely what the system of their doctrines was.
Their political sentiments coincided with their religious tenets,
being favourable to civil liberty, but to a degree which proved, by experience,
too refined for the present slate of civil society.
In ecclesiastical government they were for independency;
in civil government for republicanism.
To them our modern historians ascribe the origin of the doctrine of toleration,
but go too far in asserting that they uniformly maintained
it in their practice when invested with power:
the succeeding history will exhibit some melancholy
instances in contradiction to such assertion.
In fine the pursuit and acquisition of secular power proved
highly detrimental to their reputation and their innocence;
introducing a polluting transition from religious thoughtfulness,
and a circumspection of life and manners,
regulated in some measure by the doctrines of the gospel; to political considerations,
and maxims of human prudence in the administration of civil government,
wherein their leaders and teachers betrayed symptoms of ambition, avarice,
and a vindictive disposition irreconcilable to the purity of Christianity;
at the same time continuing to make a high profession of, and pretensions to,
religious purity,
which gave occasion to Historians of the opposite party to represent them,
and other dissenters, as a body of Pharisaical hypocrites:
But it appears to me both ungenerous and unsafe to
comprehend any body of men under one general character,
which is most frequently the result of the narrow spirit of party zeal,
and secret antipathy,
rather than that generosity of sentiment and dispassionate temper of mind,
which can calmly investigate truth and applaud virtue, wherever it may be sound.
I believe the Independents, in common with other societies,
in their first separation from the established church,
were generally actuated by conscientious motives;
that many of them retained their integrity;
that several of more tender consciences among them,
offended at the latitude taken in their measures by some
of their ruling members in their political capacity,
left them in search of a purer and more undefiled religion elsewhere.
For it is too notorious to be controverted,
that the conduct of too many of their principal men and pastors,
whose particular conduct commonly fixeth the character of the whole body,
was unjustifiable in various instances: Their policy in acquiring,
and their jealousy of losing their power,
which many looked upon as a violent and unjust usurpation,
pushed them upon some measures, which cannot be defended upon the principles of religion,
morality or humanity.
Their reputation, not withstanding,
was very considerable for wisdom and political capacity
in the administration of public affairs,
during which they made a conspicuous figure;
but with the termination of their power their religious
character seemeth to have been irrecoverably lost,
they soon sunk into obscurity, and dwindled in their numbers,
till they became so inconsiderable a body of themselves, that they applied for,
and obtained their desire, to be incorporated amongst the Presbyterians.]

They would not communicate at large or in common with others,
but formed churches among themselves of such as could give some account of their conversion,
at least of very promising experiences of the work of God`'s Grace upon their hearts;
and under mutual agreements and covenants of fellowship they kept together.
These people were somewhat of a softer temper,
and seemed to recommend religion by the charms of its love, mercy and goodness,
rather than by the terrors of its judgments and punishments,
by which the former party would have awed people into religion.
They also allowed greater liberty to prophecy than those before them,
for they admitted any member to speak or pray as well as their pastor,
whom they always chose, and not the civil magistrate.
If such found anything pressing upon them to either duty,
even without the distinction of clergy or laity, persons of any trade had the liberty,
be it never so low and mechanical.
But alas! even these people suffered great loss, for tasting of worldly empire,
and the favour of princes, and the gain that ensued, they degenerated but too much.
For though they had cried down national churches and ministry, and maintenance too,
some of them, when it was their own turn to be tried,
fell under the weight of worldly honour and advantage,
got into profitable parsonages too much,
and outlived and contradicted their own principles; and, which was yet worse, turned,
some of them, absolute persecutors of other men for God`'s sake,
that but so lately came themselves out of the furnace, which drove many, a step farther,
and that was into the water: Another baptism,
as believing they were not scripturally baptized,
and hoping to find that presence and power of God in submitting to this watery ordinance,
which they desired and wanted.
These people^
footnote:[The third society mentioned by William Penn,
as aiming to carry the reformation still farther, are the Baptists,
(or Anabaptists) who received that denomination from their
objecting to the validity of infant baptism by sprinkling,
and their practise of baptizing by the immersion of adults,
whom they considered as believers,
thinking these the only proper subjects of this ceremony.
Upon this account they claim an immediate descent
from the apostles and the primitive church,
whose practice in this respect, they maintain, was the same.
But their origin is generally deduced from later ages,
they being considered as having sprung up in Germany,
by separating themselves from the Lutherans, because their reformation was imperfect,
and not brought up to the primitive standard;
as the proper mode and subject of baptism was not allowed
by them to be necessary in the performance of that rite.
Therefore they re-baptized their followers, condemning infant baptism as unscriptural,
and of no effect, whence they acquired the name of Anabaptists.
In their first separation they also seem to have
been actuated by sincere and purely religious motives;
and exemplified the sincerity of their religious profession,
by the strictness of their lives and doctrines, being conspicuous for their morality,
mortification, and simplicity of dress.
They exclaimed not only against the authority and tyranny of the church of Rome,
but against every authority which opposed the rights of conscience.
{footnote-paragraph-split}
This society was much exposed to persecution,
and therefore it was natural for them to exclaim against it.
Yet in their early appearance in Germany some under the denomination of
Anabaptists gave occasion for the extension of the magistrate`'s sword.
Upon their first separation from the Lutherans they seem to have been
more quick-sighted in discovering what to reject than what to pursue;
it appears as if they were not agreed in any system
of religious principles except the doctrine of baptism;
in other respects their principles were lax and indeterminate,
which gave a latitude to some unsettled spirits under their name
to adopt opinions destructive to the peace and order of civil society.
"`That amongst Christians,
who had the precepts of the gospel and the spirit of God to guide them,
the office of magistracy was not only unnecessary,
but an unlawful encroachment on their spiritual liberty; that all Christians,
throwing their possessions into one common stock,
should live together in that state of equality,
which becomes the members of the same family.`"
Nay, it is said they went so far as to maintain,
"`that as neither the laws of the New Testament had placed any restraints upon men,
with regard to the number of wives they might marry,
they should use that liberty which God himself had granted to the Patriarchs.`"
(Robertson)
{footnote-paragraph-split}
The actions of these men were such as might be expected to flow from such extravagant notions:
they made an insurrection in Westphalia, seized the city of Munster,
and in their attempts to establish a commonwealth conformable to their wild ideas,
ran into the most exorbitant and criminal excesses;
which induced a confederacy of the secular powers to quell them by force of arms,
and bring the ringleaders to condign punishment.
This being effected, these commotions, which were principally raised by two obscure men,
John Matthias, a baker, of Haarlem, and John Bocold, a journeyman tailor, of Leyden,
subsided entirely; but the brand of infamy, which they stamped upon the denomination,
was too deep to be readily effaced;
and involved the innocent with the guilty in the fatal consequences of these disorders:
Being persecuted in one city they fled into another,
dispersing themselves and their opinions into divers countries,
where although they led a quiet and peaceable life,
and disavowed the criminal extravagancies of those of Munster,
yet riveted prejudice, detestation and persecution were long attendant upon anabaptism,
wherever it was adopted or professed.
Numbers were martyred in different countries for their adherence thereto.
And although in England persecution hath not in latter ages proceeded to that extremity;
yet in every storm of persecution here,
they had generally their full share.
Next to the body of people, who are the subject of the following history,
they were perhaps the most hated and persecuted sect,
they having adopted many opinions of the same tenor with those
which exposed the people called Quakers to the severity of their sufferings;
they maintained the liberty of prophesying,
as any individual was authorized and qualified by the gift or
influence of the holy Spirit; some of them held war to be
inconsistent with Christianity,
and scrupled to take an oath they insisted that the gospel ought to be free,
and denied the right of tithes, or other compulsory maintenance of ministers.]
also made profession of neglecting, if not renouncing and censuring,
not only the necessity, but use of all human learning, as to the ministry,
and all other qualifications to it, besides the helps and gifts of the Spirit of God,
and those natural and common to men.
And for a time they seemed like of _John_ of old,
_a burning and a shining light to other societies_.

They were very diligent, plain and serious, strong in scripture and bold in profession,
bearing much reproach and contradiction.
But that which others fell by proved their snare, for worldly power spoiled them too;
who had enough of it to try them what they would do if they had more:
And they rested also too much upon their watery dispensation,
instead of passing on more fully to that of the _fire_ and _Holy Ghost_
which was _his baptism, who came with a fan in his hand, that he might thoroughly,_
and not in part only, _purge his floor,
and take away the dross and the tin of his people,
and make a man finer than Gold._
Withal they grew high, rough and self-righteous,
opposing farther attainment; too much forgetting the day of their infancy and littleness,
which gave them something of a real beauty, insomuch that many left them,
and all visible churches and societies, and wandered up and down,
as _sheep_ without a _shepherd_, and as _doves_ without their _mates_;
seeking their _beloved_,
but could not find him, as their souls desired to know him,
whom their souls loved above their _chiefest joy_.

These people were called _Seekers_ by some, and the _Family of Love_ by others; because,
as they came to the knowledge of one another, they sometimes met together,
not formally to pray or preach at appointed times or places, in their own wills,
as in times past they were accustomed to do, but waited together in _silence_,
and as anything rose in any one of their minds that
they thought savoured of a _divine spring_,
they sometimes spoke.
But so it was, that some of them not keeping in _humility_ and in the _fear_ of God,
after the abundance of revelation, were exalted _above measure_;
and for want of staying their minds in an humble dependence upon him that
opened their understandings to see _great things_ in his _law_,
they ran out in their own imaginations, and mixing them with those divine openings,
brought forth a monstrous birth, to the scandal of those that feared God,
and waited daily in the temple, not made with hands, for the consolation of _Israel_;
the _Jew_ inward, and circumcision in spirit.

This people obtained the name of _Ranters_,
from their extravagant discourses and practices;
for they interpreted Christ`'s fulfilling of the law for us to be a discharging
of us from any obligation and duty the law required of us,
instead of the condemnation of the law for sins past, upon faith and repentance;
and that now it was no sin to do that which before it was a sin to commit,
the slavish fear of the law being taken off by Christ; and all things good that man did,
if he did but do them with the mind and persuasion that it was so,
insomuch that divers fell into gross and enormous practices,
pretending in excuse thereof, that they could, _without evil_,
commit the same act which was sin in another to do.
____

Their extravagancies and immoralities shocking the
sincere seekers of pure religion amongst them,
they relinquished a community fallen into manifest disorder,
to search after it elsewhere; and many of other societies also,
feeling a desire after a greater degree of purity
and peace of mind than they had yet met with,
were at a loss to know where to find it, or whom to apply to for direction.

About this time Providence saw meet to raise up an instrument to gather
a people from those who were dissatisfied with these different professions,
and were looking for the revelation of the Gospel in greater purity,
as well as many who were not.
A man of strong natural parts, firm health, undaunted courage,
remarkable disinterestedness, inflexible integrity, and undisguised sincerity,
unacquainted with the doctrine of the schools, and unattached to any system,
but endued with a power and authority which schools cannot convey,
speaking the language of experience, and of a heart versed in the work of sanctification.
The tenor of his doctrine, when he found himself concerned to instruct others,
was to wean men from systems, ceremonies, and the outside of religion in every form,
and to lead them to an acquaintance with themselves,
by a most solicitous attention to what passed in their own minds;
to direct them to a principle in their own hearts, which if duly attended to,
would introduce rectitude of mind, simplicity of manners,
a life and conversation adorned with every christian virtue, and peace,
the effect of righteousness, which they were looking for.
Drawing his doctrine from the pure source of religious truth, the New Testament,
and the convictions of his own mind, abstracted from the comments of men,
he asserted the freedom of man, in the liberty of the Gospel,
against the tyranny of custom, and against the combined powers of severe persecution,
the greatest contempt and the keenest ridicule.
Unshaken and undismayed he persevered in disseminating principles and practices
conducive to the present and everlasting well-being of mankind with great honesty,
simplicity and success.
It seems proper, therefore, with an account of this extraordinary character,
who was the first preacher of the principles of the society afterwards
distinguished by the contemptuous appellation of Quakers,
and the first person who received that name, to open the history of this people.
