== Chapter 1

[.chapter-synopsis]
* Birth of George Fox
* His early turn to Religion
* Is put apprentice
* Religious Thoughtfulness predominant in his Mind, and its Effects
* He leaves his Relations
* Falls under great Trouble of mind
* Applies to several Priests, but receives no Relief
* Withdraws from the public Worship
* Passeth his Time in Retirement
* Grows in religious Experience.

George Fox was a native of Leicestershire, being born at Drayton in the Clay,
in the said county, in the year 1624,
of parents not considerable for their rank in the world,
but Birth of respectable in their neighbourhood for piety, and integrity of life,
who gave him a sober, although not a learned, education,
in the way and worship of the national church: His mother especially,
a woman of qualifications superiour to the generality of her circumstances in life,
observing the bent of his disposition to gravity and seriousness from his childhood,
treated him with particular tenderness and indulgence,
being careful not to discourage his virtuous inclinations,
feeling much satisfaction in these early indications of
a pious and religious turn of mind in her son.^
footnote:[Penn`'s Preface to George Fox`'s [.book-title]#Journal#.]

As he grew up, this seriousness and gravity grew up with him,
and his contemplative turn of mind enlarged his understanding
with just notions of religion in his early minority,
insomuch that about the eleventh year of his age,
he had clear conceptions of righteousness and purity;
whereby he was influenced to be faithful in all things; inwardly to God,
and outwardly to man.^
footnote:[George Fox`'s [.book-title]#Journal#, p. 2]
The stayedness and gravity of his demeanour suggested to some of
his relations a desire that he might be educated for the Priesthood;^
footnote:[Ibid.]
but whether the circumstances or the inclinations of his parents prevented,
he was put apprentice to a shoe-maker,
by whom he was chiefly employed in keeping of sheep,
an employment well suited to the temper of his mind,
both for its innocence and solitude.^
footnote:[William Penn`'s Preface.]
In his service and commerce he was truly conscientious,
discharging his trust with the most scrupulous fidelity to his master,
and honesty and integrity to all he dealt with.

At the expiration of his apprenticeship he returned home to his parents,
and religious consideration having still the ascendancy in his mind,
the clear impression fixed therein of the refined nature of true religion,
pointed out to him the necessity of great circumspection in all his words actions;
e that his words should be few and savoury, seasoned with Grace,
sincere and void of deceit;
that he must deal with all men uprightly as in the sight of God;
that he must be watchfully temperate in eating and drinking,
using the Creatures not for the gratification of a carnal appetite,
but for the preservation of health,
as Servants in their places to the Glory of him who created them.^
footnote:[George Fox`'s [.book-title]#Journal#, p. 3.]
At the same time observing in the greater number
of those who were high in profession of religion,
a latitude in their conduct and conversation; an indulgence in sensual gratifications;
or an attachment to temporal pursuits, to a degree, in his view,
irreconcilable to the purity of the Christian religion, it occasioned him discouragement,
and anxiety of heart to that degree, that he could not, sometimes, take his natural rest;
but spent his nights in watchings and in prayer:
Under his solicitude on the most important subject he received this internal
admonition "`Thou seest how the young people go together into vanity,
and old people into the earth; thou must forsake all, both young and old,
and be as a stranger unto all.`"

This, which he understood to be a divine He command,
determined him to leave his relations and acquaintance; to detach himself,
as much as possible from company and conversation,
for fear of being drawn into unwatchfulness,
and transgressing the limits of pure religion, and receiving hurt thereby.
Yet in his moving about (for he tarried not long in any place) he sought
out the most retired and religious people to converse with,
as he felt freedom, or apprehended the pointings of duty thereto,
and sojourned amongst them.^
footnote:[Penn`'s Preface.]
In these his solitary travels,
he was under great trouble and anguish of mind to
that degree that he was tempted almost to despair,
whereby he was brought to a narrow scrutiny and retrospection into his past life;
and blameless as it seems to have been,
his anxiety still increased nigh to despondency at times.
In this state a doubt arising in his mind of the rectitude of his conduct:
in leaving his relations, he returned home;
yet here feeling little mitigation of his sorrows,
he had recourse to several of the Priests in these parts,
who were in repute for religious experience, to consult them,
for their counsel and advice; but found no real benefit or help from them,
they not being able to reach his state, or administer the relief he wanted.^
footnote:[George Fox`'s [.book-title]#Journal#, p. 3, etc.]

Being disappointed in his application to these teachers,
and finding them to him Physicians of no value,
he was discouraged from a dependence upon them.^
footnote:[Ibid, p. 4, 5.]
And shortly after this his under standing being enlightened
to see beyond the prevailing popular prejudices,
"`That an education at Oxford or Cambridge was not enough to fit and qualify
men to be ministers of Christ,`" and "`That God did not dwell in temples
made He with hands,`" he declined the attendance of the public worship,
to hear sermons unavailable to the state of his soul,
and to join in prayers and singing not expressive of its feelings,
esteeming it not worship, but offensive to the divine being,
who knows the secrets of all hearts,
to address him in language not conceived in the soul,
nor formed from the inward feeling of what it stood in need of.
He therefore turned his views toward the dissenters,
as apprehending more tenderness and religious experience among them:
yet he found not that satisfaction here, which he desired:^
footnote:[George Fox`'s [.book-title]#Journal#, p. 7.]
For being convinced that to be a true believer was a more
arduous attainment than mankind in general apprehended,
and that they only were such "`Who were born again`" and "`had passed from death to life:
that a profession of truth without the possession;
a form of Godliness destitute of the power thereof,
prevailed too much amongst the different classes of the professors of Christianity.
Wherefore withdrawing from communion with all outward
societies he retired alone into solitary places,
with his bible, and employed himself in reading and meditation there.

For the space of three or four years he lived in privacy and solitude; during which time,
through a variety of probations, he grew in religious experience,
and the work of sanctification being illuminated
with the clear discovery of the mystery of iniquity;
endued with wisdom and fortitude to avoid evil;
and steadily to endeavour after righteousness and holiness; which, through divine Grace,
he was enabled to attain in a good degree.
By a strict attention, and ready obedience to the teacher nigh at hand,
the word in the heart, and in the mouth, to be heard and obeyed,
he was endued with intellectual discernment, to distinguish between the essential,
and external part of religion, between the spirit and the letter:
the latter he thought unavailable of itself to salvation; but the former he adopted,
as that without which no man can be saved.
Thus by an internal monitor, being,
(as the wise scribe in the Gospel) well instructed to the kingdom of heaven,
and qualified to bring out of the treasury of his own experience, things new and old;
he felt it his duty not to hide the light under a bed, or under a bushel,^
footnote:[Mark 4:21]
but to set it as on the candlestick to diffuse to the nation; that is,
publicly to recommend to mankind an inward attention to the same internal monitor,
the light, which enlighteneth every man that cometh into the world.^
footnote:[John 1:9]

I know that George Fox and his Friends have been exposed to much contempt and ridicule,
for assuming the province of teachers, being many of them illiterate men:
But absurd and ridiculous as it may appear in the
eyes of human policy or contemptuous science,
the sequel proves them not without qualification for the part which they undertook.
They, and the people called Quakers after them in general,
although they neither did nor do condemn nor reject useful literature,
yet were and are fully of opinion it is not an essential qualification of a Gospel minister;
but that the inward experience of the work of conversion and sanctification is:
That the latter without the former may constitute
the character of a minister of the Gospel;
that the former without the latter never can.
We admit that good natural parts, and an enlarged understanding,
are valuable accomplishments,
and gifts of the Creator of man for great and good purposes;
that being cultivated and improved by useful knowledge,
they may bring advantage to the possessor in particular, and the community in general,
for many purposes of this life; and that being sanctified by divine grace,
they may be made highly subservient to promote the welfare of mankind in the best sense,
if, in gratitude to the beneficent giver of every good and perfect gift,
they be devoted to the ends for which he gave them,
the advancement of religion and virtue:
that by such an application alone of these precious gifts,
men act as faithful Stewards of the talents their Creator hath entrusted them with,
to whom we must all give an account of the use and improvement we have made of them,
which merits the serious consideration of all who are favoured with these advantages.
Yet we esteem it the most valuable and genuine characteristic of the Gospel,
that its doctrines, whereby life and immortality are brought to light,
under the influence of divine Grace,
are intelligible to the unlearned in human literature, as well as the learned:
This we believe as the necessary consequence of the
divine attributes of Goodness and Justice.
We consider Christianity, not as a speculative science, but a practical doctrine;
and that religion most worthy of our study and pursuit, which mends the heart,
and regulates the life and manners,
not that which only fills the head with a notional apprehension of divine things.
If George Fox with experience without learning became a preacher of righteousness,
so did those,
who of all others have the most undisputed title to the character of Gospel ministers,
viz. the Apostles, on the authority of one of themselves, "`That which we have heard,
which we have seen,
and our hands have handled of the word of life--declare we unto you.`"^
footnote:[1 John 1:1,3]
