== Chapter II.

[.chapter-synopsis]
* George Fox travels abroad again
* State of the Nation
* A general Turn to Religion prevalent, and religious Opinions multiplying, open a freer Reception for George Fox`'s Ministry
* His first Appearance as a Minister
* Independents seize the Government
* George Fox`'s first Appearance in Prayer
* Attends a public Dispute at Leicester
* Endeavours on all Occasions to promote Righteousness
* Symptoms of Disgust against him begin to appear
* For disusing customary Modes of Salutation and Address
* Other Causes of Offence
* Chiefly the Doctrine of him and his Friends concerning Gospel Ministry
* George Fox`'s first Imprisonment at Nottingham
* Removed to the Sheriff`'s House, and back to Prison
* His ill Treatment in other Places
* Occasion thereof
* Apology for it

It was in the year 1647 that George Fox conceived it his
duty to leave his outward habitation a second time,
and travel abroad,
to seek out the most serious and religious people to associate and converse with.
Passing through part of his native county and Derbyshire he came into Nottinghamshire;
and in his passing along wherever he met with honest-hearted religious people,
he would enter into religious conferences with them, as freedom and opportunity invited,
for mutual improvement and edification; but he chiefly recommended silence,
and abstinence from self-performances,
in order to turn the attention of men more steadfastly
to the light of Christ within them;
and to wait in patience to feel the power of this
divine principle animate them to a heavenly temper,
and a life of righteousness;
always exemplifying the doctrine he taught in his own practice.

At this time the nation was in a very unsettled state.
After some years of civil war, commenced, (as alleged) for the redress of grievances,
and limiting or preventing arbitrary power,
(for which too much occasion had been given) and terminating in a contest for the supremacy.
The Presbyterians and their adherents, assisted by their brethren from Scotland,
had vanquished the Royalists, and were themselves overreached by the Independents,
who having now gotten the King into their hands, a prisoner in the Isle of Wight,
and the army, attached to their interest,
were proceeding rapidly to fix themselves in the feat of government.
As this civil war had been undertaken to redress
religious grievances as well as those in the state,
that class of the people who were distinguished by the denomination of Puritans and
Sectaries (having suffered much persecution under the power of the bishops) ranked generally
on that side which aimed at the abolition of their dominion and office;
and this party (who made high pretensions to sanctity
and purity of religion) succeeding in their aim,
both in the conducting of the war, and of the government after the war was concluded,
giving scope to a latitude of policy, ambition, and a vindictive temper,
irreconcilable to the honest simplicity,
the peaceable and forgiving spirit of the Christian religion,
and the purity of their former pretensions, gave occasion to their antagonists,
and sundry historians after them,
to represent the dissenters of this age in general
under one description of hypocritical enthusiasts,
who covered pernicious designs under the veil of sanctity,
and masked deep deceit under specious professions.
These party-reproaches (however well-grounded in
respect to some public characters) could not,
with candour or justice, be applied to numbers of the people of that age,
who dissented from the preceding established worship,
and nevertheless were sincere in piety,
and in their researches after pure and undefiled religion;
forever since the reformation had broken the shackles,
with which Priestcraft had fettered the understandings of mankind,
and taught them to think for themselves,
and pursue the train of their thoughts in a free inquiry after truth and pure religion,
many of the most sincere in their enquiries,
apprehending too much of the old leaven both in doctrine,
discipline and manners retained in the episcopal church;
and that they had the same right by the laws of God and nature to dissent from her,
that she had to dissent from the Church of Rome,
were engaged in honesty of heart to wish for, and endeavour after,
a more perfect reformation:
and several of them evidenced the sincerity of their
piety by circumspect and virtuous lives,
the criterion whereby only men can safely judge of each other.
_By their fruits shall ye know them._
The persecution and sufferings to which their dissent exposed
them may be considered also as a test of sincerity;
for what man would incur certain evil, but in prospect of greater good?

As I am far from attempting to vindicate all those
who at this time made pretensions to purity,
being sensible that too many of them either made
religion a cloak of covetousness and ambition,
or if they were ever sincere, became corrupt by the possession of power;
so I cannot think they do any service to the cause of religion, who,
by dwelling upon the prevailing insincerity without exception,
give an air of suspicion to all religious appearances,
of being only a cover to bad designs: Many, I believe,
who were drawn into wrong measures,
for want of discriminating religious dissent from political faction,
were sincere and acted upon principle,
though under the influence of human frailty liable to err in judgment,
and that divers of these coming to see their error relinquished it.
I believe also many others were really religious,
devoted in heart to the service of their Creator,
and so to pass the time of their sojourning here in his fear, as to obtain his favour;
that they were preserved thereby through these times
of tumult in innocence and integrity of life,
lamenting the calamities of their country,
and forbearing to take any active part in the guilty and distracting scene.
That from the reformation to this time a spirit of
free religious inquiry had been kept alive,
even by the severities practised to quash it: That the civil wars,
which spread bloodshed and devastation to almost every corner of the land,
having stripped great numbers of much of their outward substance,
and leaving the remaining part at the disposal of superior force,
had an effect to wean men`'s affections insensibly
from possessions of so precarious a tenure:
That all, who could think seriously,
were naturally led to look for something more stable; which not being found below,
they were incited to look for it above: And that the spirit of religious inquiry,
and sincere desire in many to seek after and attain solid good,
received additional strength.

It was certainly an era when religious profession
and regularity of manners were in general estimation;
and amidst this general profession,
we must presume many were truly conscientious in their dissent from established forms,
and in their inquiry after a better way.
But in these times of turbulence, and intestine commotion,
when the reins of civil and ecclesiastical authority were shifting from hand to hand,
sects and opinions multiplying, and many coming, and saying, "`Lo here is Christ,
and lo he is there,`" perplexed many of the honest and sincere enquirers,
in their search of truth: Amidst the variety and fluctuation of doctrines and opinions,
like Noah`'s dove, they found no rest for the soles of their feet,
being under uncertainty what guide to follow, or what society to associate with;
and therefore sundry others, besides George Fox, deserted these uncertain teachers,
and in retirement and solitude consulted the scriptures,
and the oracle in their own breasts, for instruction in the way of their duty;
or met in select companies for worshipping, and mutual edification.

Amongst such as there who were weary of a fruitless search without,
George Fox found an open reception for his doctrine,
directing to an unerring guide within them, viz. The light of Christ,
which he hath placed as a witness for himself in every man`'s conscience.

His ministerial labours were at first exercised in the way of religious
conference with such well disposed people as he met with upon inquiry,
as he passed along from place to place in concise
but instructive remarks upon the nature of pure religion.
He durst not stay long in any particular place,
for fear of contracting acquaintance which might not be profitable,
or of entering into much conversation,
whereby his mind drawn off from its habitual meditation and recollection
might be retarded or injured as to advancement in religious experience.
But as he went northward as far as Duckenfield and Manchester,
meeting thereaway with some religious enquirers he made some stay,
and had religious meetings, and declared truth amongst them;
whereby there were some convinced of the truth of his doctrine,
who (as he expresseth it) received the Lord`'s teaching,
were confirmed and stood in the truth.

This is the first instance we have of his public ministry, which,
in his first setting out in this line, I understand,
consisted in a few weighty expressions, attended with a reaching power,
greatly affecting the hearts of his auditory.

At no great distance from this time,
another opportunity occurred for his public ministry on the following occasion:
The Baptists had appointed a meeting at Broughton in Leicestershire,
with some persons who had separated from them:
The report thereof drew abundance of people together, even from other counties,
George Fox among others; but from whatever cause it happened,
but few of the Baptists attended.
This circumstance presenting a full audience,
and George feeling his mind divinely influenced,
made use of the opportunity to inculcate the doctrines he had received
as truth upon the minds of the assembly with success:
Several by his powerful preaching, and others, by his reasoning in conferences with them,
were convinced of the truth he published that day.

Near the close of this year O. S. the independents and Republicans
accomplished their purpose in bringing the King to the block,
abolishing regal dominion; the authority and peculiar privileges of the Nobility;
and the office of Bishops: and seating themselves at the helm of Government.
Their professed principles being in favour of civil and religious liberty,
the public places of worship seem, for a season,
till they were more firmly fixed in their seats,
to have been open to teachers of different denominations,
and not uncommonly appropriated to theological discussion,
and disputation between the teachers or members of various sects:
This furnished George Fox and others with more public and
full opportunities of divulging their respective opinions,
and accordingly we find him frequently availing himself thereof.

Private houses also were occasionally open to religious conferences,
and as the principal bent of this pious young man`'s mind, excited by persuasion of duty,
was to do good to others, or reap spiritual advantage to himself,
he was zealous to attend sundry meetings of this kind,
appointed in these parts where he mostly resided at this time,
viz. his native county of Leicestershire (to which he was now returned) and places adjacent:
Once at a meeting of sundry priests and professors at a Justice`'s house,
and twice at Mansfield,
in which he modestly offered his sentiments on the subject of disquisition,
which were generally well received, and gained the assent of several of the company.
At the first meeting at Mansfield he was moved to pray (being the first time we find
any account of his praying in public) and the power accompanying his prayer was so reaching,
that the house seemed to be shaken:
which occasioned some of the company to remark that
it was now as in the days of the Apostles,
when the house was shaken where they were.
The effect of his prayer on the audience,
encouraged another professor present to pray also;
but (not being under a similar influence) his prayer, instead of edifying,
brought deadness and a veil over the assembly, which displeasing them,
he desired George to pray again, but he could not pray in man`'s will.^
footnote:[William Penn who knew George Fox very well,
from long and intimate acquaintance, gives this character of his excellency in prayer.
"`Above all he excelled in prayer.
The inwardness and weight of his spirit;
the reverence and solemnity of his address and behaviour;
and the fewness and fulness of his words,
have often struck even strangers with admiration,
as they used to reach others with consolation.
The most awful, living, reverent frame I ever felt or beheld,
I must say was in his prayer.`"]

Soon after this hearing of a great meeting George Fox appointed at Leicester for a dispute,
wherein it was reported, that Presbyterians, Independents,
Baptists and Episcopalians were engaged, he went thither,
the meeting being held in the public worship house opened a general admission;
and liberty being granted for any to speak, after some time of conference and reasoning,
a woman present put this Question, "`What birth was that which the Apostle speaks of,
A being born again of incorruptible seed, by the word of God,
which liveth and abidith forever?`"^
footnote:[1 Peter 1:23.]
The priest replied, I suffer not a woman to speak in the _church_,
which drew from George Fox an inquiry what he understood the Church to be, for reply,
the priest returning the question George expressed
his idea thereof "`That it was neither a building of lime and stones,
nor a mixed multitude assembled together; but the pillar and ground of truth,
a spiritual building composed of living stones, a spiritual household,
which Christ was the head of.`"
This, he writes, set them all on fire, and the dispute was marred.^
footnote:[George Fox`'s [.book-title]#Journal#, p. 15.]
I own myself at a loss to discover anything in these expressions,
(which are mostly scriptural) to provoke any reasonable
person to the least degree of resentment,
were it not that being prepossessed in favour of received opinions,
our prejudices too easily rouse our passions to their aid at the advancing of
any new doctrines which have not obtained the sanction of public reception.
The pride of human nature is mortified at the supposition
of its being in ignorance or error,
and he who endeavours to inform it better, or set it right, frequently meets wit,
insult and ill treatment for his pains: This occasioned George Fox, a young man,
obscure and illiterate, coming abroad with new doctrines,
in many respects opposite to the received opinions, much enmity and persecution,
as we shall find in the sequel: but he was on a foundation not to be shaken.
At this time when the meeting was thus broken up he retired to his inn,
whither he was followed by several of the priests and professors,
with whom he disputed the subject afresh, and maintained his opinion of the true church,
and true head thereof, till they gave out and went away.
Several were convinced that day, and amongst them the woman who put the question,
and her family.

Travelling about in the central parts of the nation,
and now staying more or less in a place as he found his mind engaged,
his preaching of repentance, and endeavours to turn people from the evil of their ways,
was attended with considerable success:
the power and convincing authority attending his
ministry daily increasing the number of proselytes:
So that meetings of them begun to be settled in these parts in the course of this year.

His endeavours to propagate true religion, and righteousness,
the necessary concomitant thereof, were not confined to public or private meetings;
but exerted in other places as occasion offered: particularly in courts of judicature,
to admonish to justice, and caution against oppression: In markets to recommend truth,
candour, and fair dealing, and to bear his testimony against fraud,
and deceitful merchandise:
At public houses of entertainment to warn against indulging intemperance,
by supplying their guests with more liquor than would do them good:
At schools and in private families to exhort to the training up
of children and servants to sobriety in the fear of their maker;
to testify against vain sports, plays and shews,
as tending to draw people into vanity and libertinism,
and from that state of circumspection and attentive consideration,
wherein our salvation is to be wrought out,
forewarning all of the great day of account for all the deeds done in the body.

It is not improbable but this uncommon manner of intervention in places,
unusual might expose him to the derision of some, and resentment of others;
but we meet not as yet with any instance of ill usage in his person;
although the symptoms of that persecuting spirit,
which soon George Fox after caused him to suffer many grievous hardships and much injurious
treatment (notwithstanding the liberal sentiments of toleration now professed) began
to discover themselves in the virulent and contumelious disposition,
which actuated people of all sorts against him.

For upon his appearing abroad in his more public capacity,
the clear impression fixed in his mind of the purity of the Christian religion,
and the too general defection of the greater part of professors therefrom,
produced in him cautiousness to take no man for his copy;
but singly pursuing what the light in his own conscience discovered to be right,
he was led into a manner of conduct in many respects singular, but, properly considered,
not absurd; although contradictory to fashion, yet not contrary to reason and propriety.
Viewing the customary modes of salutation in uncovering the head, and bowing the body,
as owing their original to pride on one hand,
and folly and parasitical artifice on the other, introducing marks of homage to men,
which they had no just claim to, and which general usage only,
and neither right reason nor real religion ratified,
he esteemed it his duty to bear a public testimony against these customs,
by declining compliance therewith.^
footnote:[Inasmuch as this primitive simplicity of manners is still
retained by the stricter sort of the people called Quakers,
those who are such upon principle,
and as these practices are looked upon by many to
be frivolous objects of religious scruple,
it seems proper in this place to recapitulate the reasons
which they advance in defence of their behaviour.
The practices of uncovering the head, bowing, and bending the knee,
being marks of divine worship, they think, as such,
are marks of reference not due from man to his fellow creature,
but ought to be peculiarly reserved for the worship of their Creator, since,
according to the doctrine of the Apostle Paul,
the head is to be uncovered in worshipping him, as a mark of veneration;
and to him and his name alone every knee must bow.
Now (say they) he that kneeleth and prostrateth himself to man, what doth he more to God?
He that boweth to the creature, what hath he reserved for the Creator.
{footnote-paragraph-split}
Secondly,
the example and doctrines of the primitive Church are against such practices.
Peter`'s refusal of such external marks of reverence from Cornelius amounts to
a presumptive demonstration that such signs of veneration were neither used,
nor allowed among Christians in their state of primitive purity;
And in the Angel`'s refusing the like expression of adoration from John, saying,
"`See thou do it not: I am thy fellow servant, and of thy brethren,
worship God,`" we have the sense of superior Beings
(who have a clearer notion of the fitness of things,
and of divine perfection, and approach nearer thereunto than the short-lived,
dim-sighted inhabitants of this globe, that worship,
and the external signs thereof belong to God only.
{footnote-paragraph-split}
Thirdly,
they scruple compliance with these customs because they were received
(amongst many other gross corruptions of Christianity) through
the polluted channel of Paganism in its most corrupted state.
The eastern monarchs, enervated by luxury,
intoxicated by the flattery of pernicious parasites, and debauched by pride and by power,
were so elevated above the common state of mankind,
that they seemed to look upon themselves as something more than mortals;
and demanded and received the most humiliating signs of reverence
to their persons from those who approached their presence;
and the most extravagant titles of adulation from all who presumed to address them.
But the more virtuous and wiser Greeks refused to
comply with these abject modes of access and interview,
as unbecoming from man to man.
Yet this conduct of the Greeks seems to have met with applause and approbation,
whilst the like conduct in the Quakers is censured and condemned;
a signal instance of the partial, and inconsistent judgments of men, when fashion,
and not propriety is the rule they judge by.]
Being by the light and precepts of the Gospel early
instructed that his words should be few and savoury;
conformable to sincerity and truth; void of flattery and void of deceit,
he felt himself circumscribed from adopting the prevailing deviation from the
original propriety and simplicity of language in using you to a single person,
or giving customary compliments, or flattering titles, and accordingly,
under persuasion of duty,
addressed individuals of every rank with the singular appellation of _thou_ or _thee_,
without respect of persons.^
footnote:[Their declining the use of you to a single
person is grounded upon the like reason,
the vulgar custom being derived from the same polluted source.
In the scriptures throughout, in all the ancient languages,
and to this day in our addresses to our maker,
the proper singular _thou_ and _thee_ are used in speaking to one.
The first instance of a deviation from this grammatical propriety, that I have met with,
occurs in the last stages of the decline of the Roman empire,
in the reign of Valentinian and Valens,
between three and four hundred years after the commencement of the Christian era.
Eutropius addresseth to Valens,
__vestra tranquillitas__ +++[+++your tranquillity+++]+++. And the
same author dedicated his work to the same Emperor,
with the following extravagant epithets: _Domino Valenti Gothito maximo, perpetun,
augusto.
To Lord Valens Gothic, the most mighty, everlasting,
and august._ R. Barclay quotes from the Epistles
of Symmachus to the Emperors Theodosius and Valentinian,
these forms of address: _Vestra eternitds; your eternity, Vistrum numen, your Godhead._
So this mode of addressing one as many, oweth its origin to the Gentiles,
who knew not God; to sycophants,
who racked their invention for absurd and extravagant terms of adulation to their Emperors,
whom, in this age of gross degeneracy from the manly spirit of their ancestors,
they were servile and stupid enough to flatter with divine attributes while living,
and enroll them among their imaginary Deities when dead.
To an extravagance of Idolatry,
as irreconcilable to the whole tenor of Christianity as light is to darkness,
or Christ to Belial.
For these reasons, this people,
endeavouring to regulate their conduct and their
consciences by the light they were savoured with,
one might reasonably expect should have met with indulgence,
rather than persecution and insult from the present rulers and teachers,
whose professed principle was that every man ought to direct his
conscience and interpret the scriptures according to his own convictions,
light and apprehensions.
What was the ground of the first reformation from Popery,
but a well-founded apprehension,
that in that system the beauty of Christianity was marred,
and the spirit thereof lost by the introduction of foreign ceremonies,
and the heterogeneous mixture of Gentile customs?
And what was the ground of dissent from this first reformation,
but an apprehension that it retained too much of this foreign mixture?
If these reformers justify themselves in their respective
separations from churches appearing to them not pure,
why censure and condemn the Quakers for endeavouring to
clear their system still further of heathenish vanities,
introduced in the darkness of apostacy;
to revert as nearly as possible to apostolical purity,
and to reject every practice which hath not the stamp of divine authority upon it;
much more that which in their apprehension may be offensive to the Almighty,
by robbing him of his honour in a communication thereof to fallible man?
{footnote-paragraph-split}
Lastly, as seekers after,
and promoters of pure religion and primitive Christianity,
they felt themselves restrained from practices,
not only contrary to the nature and spirit of Christianity in their original;
but tending to defeat the end thereof in their effect,
as supplying strength and nourishment to pride and vanity in man,
which the Gospel is plainly designed to weaken and destroy;
and instead thereof to introduce humility and meekness into the soul.]
This uncourtlike manner of salutation and address begat general disgust,
filled the magistrates, ecclesiastics, and laics with indignation,
and exposed George Fox and his fellow-believers to much grievous abuse in their persons,
being often beaten, buffeted, stoned,
imprisoned and fined for no other reason but declining to take off their hats,
and to give the customary titles of adulation to men;
customs which they believed to be unlawful for them to comply with:
But they preferred the testimony of a good conscience,
and a faithful adherence to the conviction of that which they received as truth,
to the ease and safety of their persons, or the smiles or frowns of men;
and for the sake of peace with God, patiently endured all the abuse,
and ill-treatment they met with on this account;
hereby giving an indubitable evidence of their sincerity,
that they were as the Jews inward, whose praise was not of man but of God.

Their unfashionable demeanor was not the sole cause of the severe
treatment George Fox and his fellow-labourers met with;
their doctrine, their circumspect conversation,
their plain-dealing and honest testimonies against religion without righteousness,
carrying in them strong reproof to hypocrisy and lifeless profession,
were little less offensive to many of the ostentatious and formal professors of the age.

But still the greatest rock of offence,
and which created them the greatest number of enemies,
and contributed as much as all the rest to fasten in the minds
of the people an aversion too deeply rooted to be easily eradicated,
was their opinion concerning Gospel ministry.
They taught that the Gospel was free;
that the Gospel minister ought either to minister because it was his indispensable duty,
or omit taking the charge up on him; that no person ought to teach for hire,
but that of the ability which God gave, they ought to give freely to the people,
and their practice corresponded with this doctrine.
A doctrine, which,
touching the teachers of every other denomination in a very tender part, their interest,
raised against them a combined host of foes,
such as have proved able to overturn kingdoms.
The priests and pastors of every other class, however at variance among themselves,
generally took the alarm, and united in exertions against these hated reformers;
to paint them in hideous colours;
to impress upon the magistrates and the people the most unfavourable opinion
of the doctrine and conduct of those men who in the face of the whole
world had so widely deviated from the common conduct of mankind,
and broached opinions in their view so pernicious.
Biased by prejudice, and blinded by passion,
their representations of this people transgressed the bounds of candour and of truth;
the pulpits in the solemn hour of divine worship
were converted into vehicles of calumny and fiction;
every ridiculous story was circulated to their disadvantage;
and all manner of pains taken to represent them, not what they were,
but what their adversaries would have them thought to be.
The press seconding the efforts of the pulpit, spread undeserved reproach widely,
and to ages yet unborn.
Men of letters, leisure and abilities, warped by the popular voice,
without giving themselves time to consider this people and their doctrines attentively,
joined in the common cause against them.
This confederacy of enemies could vilify their reputation; abuse their persons; plunder,
imprison and grievously persecute them:
but could neither overset their confidence in divine support,
nor prevent the increase of their numbers, till they became a very considerable body,
not more remarkable for the singularities of their profession,
than for the uniform practice of every Christian virtue,
and the severity and iniquity of their sufferings for the testimony of a good
conscience through three successive revolutions of governments.

George Fox`'s first imprisonment was in the course of the present year at Nottingham:
Coming thither on a first day of the week,
under a persuasion of duty he went to the public worship and the
priest taking for his text these words of the apostle Peter,
"`We have a more sure word of prophecy, etc.`" which he expounded to be the scriptures,
by which all doctrines, religions and opinions were to be tried.
George Fox feeling, as he apprehended,
a divine power opening his understanding into a clearer
conception of the meaning of the text,
and an authority to express his sense thereof,
signified that this _sure word_ of prophecy was not the scriptures, but the holy spirit,
by which holy men gave forth the scriptures,
whereby (as the surest interpreter of them) opinions,
religions and judgments were to be tried: For it led men into all truth.
The Jews had the Scriptures, yet resisted the Holy Ghost, and rejected Christ,
the bright morning star, persecuted him and his apostles,
while they pretended to try their doctrine by the scriptures; but erred in judgment,
because they tried them without the Holy Ghost.
Hereupon the officers seized him, and took him to prison,
putting him into a place so filthy and intolerably noisome
that the smell thereof was very grievous to be endured.
At night he was carried before the mayor, aldermen and sheriffs of the town,
and after examination was recommitted.
But one of the magistrates was more kindly disposed than the rest; John Reckless,
sheriff,
being with his wife and family much affected with
George`'s doctrine and the power attending it,
after some time removed him to his own house: During his residence here,
he had great meetings,
which some persons of considerable condition in the world attended,
and the Lord`'s power appeared eminently among them,
to his own whereby a great change was effected in the sheriff,
insomuch that he and several others being excited by a sense of
duty to exhort both the people and magistrates to repentance,
the latter were so provoked,
that they caused George Fox to be removed back from
the sheriff`'s house to the common prison,
where he lay till the assizes;
yet was not then brought to his trial for any offence committed by him,
for although he was ordered to be taken before the judge,
the officer was so dilatory in obeying the order
that the court was broken up before he got thither,
at which the judge expressed his displeasure, signifying,
_he would have admonished the youth, if he had been brought before him._
This backwardness in giving him an opportunity of being tried or discharged,
appears to me a tacit confession that the magistrates were sensible,
they had no legal cause for imprisoning him; yet they ordered him into the common jail,
and detained him there some time longer.^
footnote:[Daniel Neale, in his [.book-title]#History of the Puritans#, vol.
II. p. 399, etc. giving an account of the first rise of the Quakers,
amongst other instances of a partial bias, either by oversight or design,
gives a very palliative narration of George Fox`'s imprisonment there, not strictly true.
"`Continuing his speech,`" saith he, "`to the disturbance of the congregation,
the officers were obliged to turn him out of the church,
and carry him to the sheriff`'s house: next day he was committed to the castle,
but was quickly released without any further punishment.`"
For this assertion he quotes no authority but W. Sewel,
whose account being drawn from the same authority (George
Fox`'s own journal) in substance corresponds with mine.
Whence Daniel Neale got his information that the officers took
George Fox from the church (so called) to the sheriff`'s house,
and that he was quickly released, he saith not; George Fox himself saith the contrary.]
And as far as appears, he was imprisoned, detained in prison,
and released at the mere will and pleasure of the magistrates of Nottingham,
without any legal cause assigned.
Such arbitrary exertion of power but ill agrees with that regard for chartered privileges,
that equal liberty,
the establishment whereof these republicans pretended to have in view, in taking up arms,
and in seizing the government into their own hands.
The popular odium causelessly raised against in several an inoffensive character,
injurious to none,
but other zealously employed in endeavours to do all the good in his power,
began now to discover itself more openly;
where the magistrates did not interpose their authority to imprison,
the populace were stimulated to abuse.
In most places whither he came, bonds or afflictions abode him.
At Mansfield Woodhouse,
speaking to the priest and congregation in their public place of worship,
the people assaulted him in a furious manner, struck him down,
and beat him cruelly with their hands, bibles and sticks,
whereby he was grievously bruised.
After they had thus far vented their rage,
they haled him out and put him into the stocks, where he sat some hours;
and then they took him before a magistrate, who seeing how grossly he had been abused,
after much threatening, set him at liberty.
But still the rude multitude, insatiate in abuse, stoned him out of the town,
though hardly able to go, or well to stand, by reason of their violent ill usage,
for no other cause but exhorting them for their good.^
footnote:[Neale passeth over this treatment of George Fox in a cursory manner,
viz. "`After this he disturbed the minister of Mansfield in time of divine service,
for which he was set in the stocks, and turned out of the town.`"
ibid.
Where we may observe,
that while George Fox`'s conduct is placed in the most invidious light it would bear,
disturbing the minister,
etc. he takes not the least notice of the real disturbance
raised by the priest`'s own hearers,
in converting the place of divine worship into a scene of lawless riot,
and the time set apart for the service of God into enormous abuse of a fellow creature;
manifesting their religion to be such,
at the time when it should most affect their minds, as admitted of injury, revenge,
and violating of the peace and order of civil society;
which is another instance of the partial bias of this writer,
as he had as plain an account of this riot in W. Sewel`'s history as of the part he selected.
But perhaps he might suspect that an exhibition of such conduct
might depreciate his character of the temper of the times,
and state of religion under the instruction and through
the zealous labours of the late dissenting pastors,
now the established preachers, which he thus describes: Anno 1647,
"`The laws against vice and immorality were strictly executed,
the Lord`'s day was duly observed, the churches were crowded with attentive hearers,
family devotion was in repute,
neither servants nor children being allowed to walk in the fields,
or frequent the public houses; there was a zeal for God,
and a much greater appearance of sobriety,
virtue and true religion than before the civil war, or after the blessed restoration.`"
And anno 1649, "`There was a great appearance of sobriety both in city and country;
the indefatigable pains of the Presbyterian ministers in catechising,
instructing and visiting their parishioners, can never be sufficiently commended.
The whole nation was civilized.`"
I mean not to detract in the least from real merit,
or deny diligence in discharge of duty to be very commendable and meritorious, so far.
But without transgressing the bounds of candour or charity,
the history of this age authorizeth the opinion,
that the religion of the time had too much of the Pharisaical leaven;
in the general more specious than solid;
productive of a demure austerity rather than real internal holiness.
Strictness in outward observations and appearances,
while the sanctifying virtue of pure religion,
which cleanseth the inside and destroyeth sin in the root, was too little regarded;
under all the appearance of sobriety and virtue,
a root of bitterness remained unpurged out in many,
ready on the least opposition or provocation to break
out into acts of open violence and vindictive abuse.
The common people as prone to tumult and excess of riot as in a more licentious age;
which dispositions are scarcely less opposite to the genuine spirit of Christianity,
designed to promote peace on earth and good will to men, than profaneness or immorality.]
With much difficulty he reached the distance of about a mile from the town,
where he met with some people humane enough to administer some cordials for his ease,
being inwardly bruised.^
footnote:[George Fox`'s [.book-title]#Journal#, p. 26.]
At Market Bosworth he was also stoned out of the town:
and at Chesterfield he was detained in custody till late at night,
and then put out of the town by officers and watchmen,
and left in the dark to provide for himself as well as he could.
In the midst of his sufferings he had the consolation
of apprehending himself in the way of his duty,
and of finding that in each place some were convinced,
and others confirmed in the truth by his ministry.

The occasion of this repeated ill-treatment which
he met with from place to place was still the same:
his speaking to the priests and people in their public assemblies,
to bring them off from the teachings of men to the
teachings of the grace of God in their own hearts:
Now at the first appearance of this people several others of them as well as George Fox,
thought it their duty to go to the public places of worship, to,
declare to the priests or people the burden of the word on their minds;
mostly (though not always) waiting till their worship was ended, and then delivering,
or attempting to deliver,
their sentiments in quietness (as far as I can discover
from their accounts) and in as few words as possible,
for which they were often treated with great violence and outrage;
and to palliate such treatment, irreconcilable to the professed purity of this period,
or to the good order of civil society,
great pains have been taken to describe their conduct
in terms of aggravation to a heinous offence,
and at this day may seem to deserve censure:
Let us take a retrospective view of the manners and principles of that age,
and I think we may find some cause of excuse for their seeming intrusion.
This people were not single, at that time,
in their sentiments concerning the Gospel-liberty of prophesying:
But the Independents also as well as the Baptists adopted the opinion,
that the ordained ministers or pastors had not, by any ordination of Christ,
or the order observed amongst the primitive Christians,
an exclusive right of speaking in the church, but that all properly gifted,
might speak one by one.
It had been during the time of the civil war,
and still continued to be no unusual practice for laymen,
soldiers and others to speak or preach in the public places of worship and elsewhere,
with the connivance, if not with the approbation of the ruling powers.
Oliver Cromwell,
in his correspondence with the ministers of Scotland in the next year 1650,
after the battle of Dunbar, vindicates the practice.
Oliver having made an offer,
to the ministers who had taken sanctuary in the castle of Edinburgh, or had fled,
of free privilege to return to their respective parishes;
the Scotch ministers in reply objected his opening the pulpit doors to all intruders,
by which means a flood of errors was broken in upon the nation; to which Oliver answered,

[quote]
____
We look upon you as helpers of,
not lords over the faith of God`'s people:--where do you find in scripture,
that preaching is included within your function?
Though an approbation from men has order in it, and may be well,
yet he that hath not a better than that hath none at all.
I hope he that ascended up on high may give his gifts to whom he pleases;
and if those gifts be the seal of mission, are not you envious,
though Eldad and Medad prophesy?
You know who hath bid us covet earnestly the best gifts,
but chiefly that we may prophesy;
which the apostle explains to be a speaking to instruction, edification and comfort,
which the instructed, edified and comforted can best tell the energy and effect of.
&hellip;Indeed you err through mistake of the scriptures.
Approbation is an act of convenience in respect to order, not of necessity,
to give faculty to preach the Gospel.
Your pretended fear lest error should step in,
is like the man that would keep all the wine out of the country lest men should be drunk.
It will be found an unjust and unwise jealousy,
to deny a man the liberty he hath by nature, upon a supposition he may abuse it.
____

And in answer to the governor`'s complaint that men of secular
employments had usurped the office of the ministry,
to the scandal of the reformed churches, he queries,

[quote]
____
Are you troubled that Christ is preached?
Doth it scandalize the reformed churches, and Scotland in particular?
Is it against the covenant?
away with the covenant if it be so.
I thought the covenant and these men would have been willing
that any should speak good of the name of Christ;
if not, it is no covenant of God`'s approving,
nor the kirk you mention the spouse of Christ.
____

By this it appears evident that a participation of the laity in ministerial offices
was not only allowed but patronized by some of the leading men of that time.
If then some members of this infant society, under persuasion of duty,
at times made use of the liberty allowed to others, (and to several of themselves,
'`till they joined this society) to deliver a short exhortation,
most generally at the close of their worship, to the people assembled,
as a full opportunity to discharge their duty;
to give them contumelious and violent abuse on that account was
as contradictory to the professed principles of the Independents,
and those free notions of civil and religious liberty
which they had been so active in disseminating,
as to religion and the civilization boasted of;
and administers ground for suspicion that they propagated
these reasonable principles chiefly with sinister views,
or by liberty meant, as is too common, liberty only to themselves.
It is certain this society enjoyed a very precarious liberty under their rule.
