== Chapter IV.

[.chapter-synopsis]
* George Fox recommences his Travels and Gospel Labours
* Much abused by the Populace
* His Patience in Suffering
* Remarkable Success of his Ministerial Labours at Sedbergh and Firbank Chapel
* John Audland and Francis Howgill being convinced return Money they had received for preaching
* Edward Burrough convinced.

George Fox having regained his liberty, pursued his travels,
and had meetings in several places in Nottinghamshire and in Derbyshire,
George Fox and thence he passed into Yorkshire.
Richard Farnsworth, among several others, was convinced at Balby: at Wakefield,
James Nayler, and William Dewsbury and his wife, with many others, were also convinced.
These three men became of several,
powerful coadjutors to George Fox in the ministry of the gospel.
Of these William Dewsbury had been immediately convinced of the
internal principle of light and grace before he saw George Fox;
but when he met him he found they were in the unity of the same spirit,
and thereupon gave him the right hand of fellowship,
and joined him in society and in his ministerial labours.

Passing on to Beverly he went to the public worship house
and after the preacher had done,
he exhorted him and the people,
directing them to Christ their teacher with such an authority
as brought a great dread and awfulness over the assembly,
and his ministry in these parts was effectual to the convincement of many people,
and amongst them some persons of account:
Captain Pursloe and justice Hotham were in the number
of his friends and favourers of his doctrine,
being convinced in their understandings,
though it doth not appear they openly joined him in profession,
yet their countenance and favour were conducive to
protect him from the insults and abuse,
to which in some other places he had been exposed.

That an extraordinary power attended his ministry in this
place appears from a relation of this justice Hotham.
"`That a great woman coming to him upon business,
told him in discourse that the last sabbath-day there
was an angel or spirit came into the church at Beverly,
and spoke the wonderful things of God, to the astonishment of all that were there;
and when it had done it passed away,
and they did not know whence it came or whither it went.`"
Now, although this relation may seem the effect of a superstitious imagination,
yet her account bears the marks of an uncommon influence attending his ministry,
whereby the audience were greatly affected.

In the afternoon of the same day he went to another
worship house about two miles from Beverly,
where, after the preacher had done, he spoke very largely,
and expounded the way of life and truth, and the grounds of election and reprobation.
The people were so much affected with his doctrine,
that they requested him to favour them with another opportunity of hearings him;
but he directed them to a better instructor that would abide with them,
the spirit of Christ in their own hearts, and so passed away.
For it was not his desire to seek men`'s admiration or respect,
so much as to obtain and preserve peace with his Maker,
in consequence of the faithful discharge of his duty;
or to gather a party to himself as a leader;
as to gather the people to their internal teacher, who points out the way to walk in,
when we turn to the right hand or to the left.

Continuing in the prosecution of his travels and of his ministry,
he met with various success,
and a variety of occurrences which the limits I have prescribed
to myself do not allow me particularly to relate.
He went on northward through most parts of Yorkshire,
where he met with little or no restraint from the magistrates;
but received much abuse from the rude multitude in many places.
He also repeatedly experienced the want of hospitality in these parts,
being refused entertainment or lodging at the inns, though he offered to pay for both;
whereby he was obliged several times to take up his lodging in the open air,
or under such shelter as he could meet with in the fields;
yet being on a good foundation, and engaged in a good cause,
he was not discouraged by these hardships from a
steady perseverance in the way of his duty.

And under these sufferings he manifested on all occasions
the meek and forgiving temper of a Christian;
as at Tichhill,
where the clerk struck him so violently with a bible in the public worship house,
as to make his face run down with blood, where,
after this the people thrust him out of the steeple-house,
threw him down and dragged him along the street, and took away his hat: When he got up,
covered with blood and dirt,
he only endeavoured to convince them of of the evil of their doings,
by representing to them how inconsistent their conduct
was with the peaceable spirit of Christians,
and how they dishonoured Christianity thereby:
and some moderate justices who had heard how he was abused,
coming to examine into this riot, he would not appear as an accuser against any of them;
but freely forgave them all, evidencing in his example,
that he was not as those whom he found it his duty frequently to reprove,
who speak of Christ and the scriptures, while they do not conform their lives thereto;
but that he was especially careful to regulate his whole conversation
by that internal principle of light and grace which he preached to others,
and by the uniformity of a Christian conduct to exemplify the excellency thereof.
This, doubtless,
greatly contributed to give success to his plain but prevailing ministry,
which he continued to exert for the gathering of
the people from the uncertain teachers of the world,
to Christ the unerring teacher and sure guide to salvation.

Coming to Sedbergh on a fair day, and preaching first in the fair,
and afterwards retiring into the steeple-house yard,
abundance of people flocked after him, when he preached several hours.
Several priests were present,
yet none of them made the least objection or opposition to his doctrine;
but one Francis Howgill, an independent preacher, was so much affected therewith,
as well as the powerful manner of delivering it, as to acknowledge,
"`This man speaks with authority, and not as the scribes.`"
Many were convinced that day, and amongst them Captain Ward.

On the first day following he went to Firbank chapel in Westmoreland,
where Francis Howgill aforesaid, and John Audland, had been preaching in the morning.
About noon, after refreshing himself with a little water from a brook,
he sat down on the top of a rock contiguous to the chapel,
in order to hold a meeting there; at this the people,
who had been accustomed to look upon the church, so called, as a sacred edifice,
where only worship could be properly celebrated,
seemed surprized that he did not go into the chapel; but he,
esteeming it part of his mission to bring them off
from their superstitious veneration for these places,
which priestcraft, in the dark ages, had introduced,
informed them that there was no inherent sanctity in the
ground or building beyond that on which he stood.
To a large audience of many hundreds he preached for a considerable space of time,
directing them to the spirit of God in themselves,
that so they might be turned from darkness to light,
and from the power of Satan unto God, etc.
He was largely opened in his ministry at this time,
and was attended with a convincing power and authority,
greatly affecting the hearts of the auditory, whereby many of them,
and in particular the teachers of that congregation, became proselytes to his doctrine;
of these were John Audland and Francis Howgill,
both of whom having been zealous preachers amongst the Independents,
became in some time noted publishers of these doctrines, which,
through the ministry of George Fox, they had embraced as truth;
and as these doctrines condemned as antichristian the teachers for hire,
they gave back the money they had received from the parish
of Colton in Lancashire for preaching there.

George went from thence to Preston-Patrick and Kendal,
at each of which places he had meetings to good effect,
many being gained over to the acknowledgment of the truth published by him;
and in these places are large meetings of the people called Quakers to this day.
From Kendal he proceeded to Under-barrow, accompanied by several persons,
with whom he had much reasoning, especially with Edward Burrough,
a young man of good natural parts,
yet not able to withstand the solid expressions and
weighty truths delivered by George Fox.
This Edward Burrough became an eminent member of this community;
and during his short life, a principal promoter and supporter of its cause,
both in his discourse and writings.
