== Chapter III.

[.chapter-synopsis]
* George Fox is imprisoned in Derby
* Remarks thereupon
* Employs himself in writing sundry Epistles and Exhortations
* Justice Bennet gives him and his Friends the appellation of Quakers.
* Note thereupon
* George Fox refuseth to be released upon Bail, for which Bennett abuseth him
* The Jailer having been an Enemy to George Fox repents of his evil Treatment of him
* A Slander raised against the Quakers from a Soldier`'s Discourse with George Fox
* George Fox being solicited to go into the Army declares his Scruple against Wars
* Is imprisoned amongst Felons
* Pernicious Effects of keeping Prisoners long in Jail
* George Fox writes to Colonel Barton, etc.
* Discharged from his Imprisonment

From Chesterfield George Fox directed his course to Derby,
where he was entertained at a doctor`'s house, whose wife was convinced, where,
as he was walking in his chamber, hearing the bell ring, upon inquiring into the cause,
he was informed that there was to be a great lecture there that day,
at which many officers of the army and preachers were to be present,
particularly a colonel, who was a preacher.
George went to this lecture, and after it was finished spoke what was on his mind,
and they heard him without molestation; but when he had done, an officer came up to him,
and taking him by the hand, told him he must go before the magistrates.
Being brought before about the first hour afternoon, they spent the day till the ninth,
in examination and consultation about him,
and then committed him and another to the house of correction,
by the following mittimus:^
footnote:[George Fox`'s [.book-title]#Journal#, p. 29.]

[.embedded-content-document.legal]
--

[.letter-heading]
To the Master of the House of Correction in Derby,

[.salutation]
Greeting,

We have sent you herewithal the Bodies of George Fox,
late of Mansfield in the County of Nottingham, and John Fretwell,
late of Staniesby in the County of Derby, Husbandman, brought before us this present Day,
and charged with the avowed uttering and broaching of divers blasphemous Opinions,
contrary to a late Act of Parliament;^
footnote:[An act or ordinance had been passed near three
months before by the parliament against several atheistical,
blasphemous and execrable opinions derogatory to the honour of God,
and tending to the dissolution of human society.
(M`'auley, Appen.
to vol.
5.) Enacting, that any persons not distempered in their brains,
who shall maintain any mere creature to be God, or to be infinite, almighty,
etc. or shall deny the holiness of God;
or shall maintain that all acts of wickedness and
unrighteousness are not forbidden in holy scripture;
or that God approves of them.
Any one who shall maintain, that acts of drunkenness; adultery, swearing,
etc. are not in themselves shameful, wicked, sinful and impious;
or that there is not any real difference between moral good and evil;
all such persons shall suffer six months imprisonment for the first offence,
and for the second shall be banished;
and if they return without license shall be treated as felons.
(Neale, vol. 2. p.397)
{footnote-paragraph-split}
Several other efforts
were made to draw sundry members of this society within the terms,
and under the penalties of this act, by accusations of blasphemy,
which could never be proved against them.]
which, upon their Examination before us, they have confessed.
These are therefore to require you, forthwith upon sight hereof to receive them,
the said George Fox and John Fretwell, into your Custody,
and them therein safely to keep during the Space of Six Months, without Bail or Manprize,
or until they shall find sufficient Security to be of good Behaviour,
or be thence delivered by Order from ourselves.
Hereof you are not to fail.

Given under our Hands and Seals this 30th Day of October, 1650,

[.signed-section-signature]
Ger. Bennet

[.signed-section-signature]
Nath. Barton

--

The magistrates of Nottingham appear to have imprisoned him without law,
the magistrates of Derby would appear to commit by law;
but it was law violently strained; and under such pretext of law,
right and justice might be, and were grossly violated.
Laws may be wrested to the purposes of malice, prepossession and passion;
justice is equal, impartial and dispassionate.
I know not where we meet with any opinions of George Fox which can, with any propriety,
be termed blasphemous,
or are comprehended in the terms of the act of parliament these
magistrates pretend to regulate their proceedings by.
His principles were as remote from the terms of blasphemy mentioned in the ordinance,
as far as I find it cited, as their own or any other could be.
They have stood the test of severe examination,
and have been well defended against the objections of their opponents,
as well by several others as by Robert Barclay in his apology.

And whereas the mittimus alledgeth, that upon their examination they confessed them,
viz. their blasphemous opinions,
how far that was true will best appear from the examination it self, which,
by George Fox`'s journal, was to this purport:

The magistrates asked, why they came thither?
George Fox answered, God, who dwelleth not in temples made with hands moved us to do so.`"
He observed farther, all their preaching,
baptism and sacrifices would never sanctify them,
and bade them to look unto Christ in them, and not unto men,
for it is Christ that sanctifies.
And as they were very full of words, some time disputing, and some time deriding,
he told them, They were not to dispute of God and Christ, but obey him.
At last they asked him if he was sanctified; he replied "`yes.`"
"`If he had no sin:`" his answer was, "`Christ my Saviour hath taken away my sin,
and in him there is no sin.`"
To the next question, "`How they knew Christ was in them?`"
he replied, "`By his Spirit, which he hath given us.`"
Then they were asked if any of them were Christ:
to which insidious query he answered "`Nay, we are nothing; Christ is all.`"
They next queried, "`If a man steal, is it no sin?`'`" to which he replied,
"`All unrighteousness is sin.`"

Had these magistrates been principled against the belief of any supernatural influence;
had they been men who esteemed all pretences to inspiration as mere delusion,
it might administer less cause of admiration if they should
interpret George Fox`'s reason for coming to Derby,
and his directing them to Christ in them, as implying blasphemous opinions.
But for two independent justices, and one of them +++[+++Barton]
a preacher, being an officer, I presume, had received no regular ordination,
and therefore had no commission to preach, but a pretended or real gift,
and how are spiritual gifts received if not by inspiration?
For magistrates whose own tenets implied a supernatural influence,
and admitted no interference of the civil power in spiritual concerns,
but were pointed in favour of universal toleration;
for men professing such principles to commit to prison an inoffensive man,
only for his religious opinions,
in many respects not far different from those professed by them,
and which the sequel hath proved were neither derogatory to the honour of God,
nor prejudicial to human society but the very reverse,
is utterly irreconcileable to every idea which history gives us of independency:
and a remarkable instance of the inconsistency of men with
themselves in different stations of life.

For it appears evident to me that these magistrates,
tainted with the general aversion causelessly conceived against this people,
were desirous to find an occasion to proceed to severity,
in order as far as in their power to repress their growth,
and that not being able to prove any blasphemy from George`'s public declaration,
they spent so many hours in examining and deliberating,
to see if they could extort some unwary concession,
which might furnish a more plausible pretext to accomplish their purpose.
The two last questions appear to he put with a plain design
to make him an offender under the terms of the act,
which design being defeated by his answers, they proceed, notwithstanding,
to involve him in the punishment prescribed for blasphemy therein, although unconvicted,
in manifest contradiction to their avowed principles of toleration.
Speculative principles frequently prove too weak a check to human passions and prejudices,
to prevent these latter from becoming the spring of action,
with men possessed of power to gratify them.

George Fox was now prevented from travelling by his confinement, but his mind,
actively impelled by persuasion of duty, to advance the truth he believed in,
to promote righteousness, and to testify against iniquity,
did not suffer him to rest unemployed,
for during his confinement he was much exercised in writing,
particularly to the priests and the magistrates of Derby: To the former,
that if they had received the Gospel freely, they should minister it freely,
without money or without price.
That if they maintained the scripture to be their
rule they ought to manifest that it was so,
not by words only,
but by the conformity of their lives to the doctrines and precepts thereof.
To the magistrates,
repeatedly pointing out the injustice and inconsistency
of persecution and oppression for religion:
That the magistrate is set for the punishment of evil-doers, and for the praise of them,
that do well.

Neither was he, under his restraint, unmindful of his principal concern,
the instruction and confirmation of those who had been convinced by his ministry.
He wrote a paper to be spread abroad amongst his friends and other well disposed people,
for the opening their understandings in the way of truth,
and directing them to the true teacher in themselves.

It was during his imprisonment here, that upon occasion,
bidding Gervas Bennet (one of the justices who committed
him) and those in company with him,
tremble at the word of the Lord; Bennet, in an airy mind,
turning this expression into a subject of ridicule and banter,
in derision gave George Fox and his friends the appellation of Quakers,
by which name this people have since that time been distinguished.^
footnote:[Other authors have given a different account of the original of this denomination,
but this is taken from George Fox`'s [.book-title]#Journal#,
which I apprehend the only authentic account we have.
Neale, who is followed by Mosheim,
discovers on several occasions a very inimical bias when he speaks of this people,
as will more fully appear when we proceed to the review of their treatment in New England.
And on this occasion in particular his aversion and contempt are notoriously manifest,
in his opprobrious description approaching to scurrility.
It was (saith he) in the year 1650,
that these wandering lights first received the denomination of Quakers, upon this ground,
that their speaking to the people was usually attended
with convulsive agonies and shakings of the body.
When George Fox appeared before Gervas Bennett, Esq; one of the justices of Derby,
he had one of his agitations or fits of trembling upon him,
and with a loud voice and vehement emotion of body bid the
justice and those about him tremble at the word of the Lord,
whereupon the justice gave him and his friends the name of Quakers.
Now whence he receives his information of the attendant circumstances we are to seek;
he quotes no authority,
nor could he who dates his preface in 1737 speak his own knowledge
of transactions passed seventy or eighty years before;
and abstracting the air of ridicule and censure in which this description is exhibited,
what does it amount to?
no certain symptom of error.
We readily admit these promulgators of primitive Christianity had no university,
education, were not trained in schools of oratory;
it was plain truth and righteousness they sought
to follow and recommend in a plain and simple way,
without the studied decorations of fine language,
or the engaging attractions of a graceful motion; they spoke not to the head,
or to the eye, but to the hearts of their auditors.
Being themselves animated,
and deeply affected in spirit with the inward feeling of the power of that truth,
to the knowledge of which they aimed to bring others, that thereby they might be saved;
in unaffected warmth of zeal in recommending righteousness,
and testifying against vice and wickedness,
might produce a warmth of expression and action also,
which to an invidious eye might appear convulsive:
But their convulsions did not bereave them of understanding;
they spake with the spirit and with the understanding also, of things which they knew,
and testified of things which they had seen.
And their doctrine was often, effectual to open the understanding of their hearers,
to see clearly the states of their minds, both what they were and what they ought to be.]

His relations being uneasy at his imprisonment,
applied to the justices who committed He resuseth him for his release upon bail,
offering to be bound in one hundred pounds,
and others of Derby in fifty pounds with them;
whereupon he was brought before the justices, but he refused consent to the bail,
because he thought the conditions (which were that he should be of good behaviour
and come no more thither to cry against the priests) in one part,
a groundless impeachment of his character, who was innocent of ill-behaviour;
and in the other, a restraint from duty.
Justice Bennet, who, I conjecture, would willingly have got rid of him,
saving his honour,
being transported with passion to a degree unbecoming his office as keeper of the peace,
rose up in a rage, and as George was kneeling down to pray for him,
he fell furiously upon him, and struck him with both his hands,
commanding the jailer to take him away to his prison; he was accordingly carried back,
and there detained.

The keeper of the prison, an high professor, was in the number of George`'s enemies,
he watchfully remarked his words and actions, asked many frivolous,
many insidious questions,
in order to draw some unwary or unguarded answer
to turn to the disadvantage of his character;
but George was mercifully preserved in that treatment,
innocence and circumspection of conduct,
that the jailer could get no advantage against him this way:
and yet it seems he spoke very wickedly of him.
For which evil treatment he was one day so smitten in his own conscience,
that as George Fox was walking in his chamber, he heard a mournful voice,
upon which he stood to listen more attentively,
and heard the jailer give the following relation to his wife: "`Wife,
I have seen the day of judgment, and I saw George there, and I was afraid of him,
because I had done him so much wrong, and spoken so much against him to the ministers,
professors and justices, and in taverns and alehouses.`"
And afterwards coming to George Fox, he made the following acknowledgment,
"`I have been a lion against you,
but now I come like a lamb and like the jailer that came to Paul and Silas trembling.`"
The next day he went to the justices and complained to them
that he and his house had been plagued for George`'s sake.
To which (as the jailer reported) the aforesaid Gervas Bennet replied,
that plagues were upon them for keeping him there:
and soon after the justices gave him leave to walk a mile,
in expectation that he would make use of the opportunity given him to regain his liberty,
and escape out of their hands.
But they were mistaken in their apprehensions: this man,
as patient in suffering for his principles,
as he was zealous and undaunted in propagating them,
was too tender of the reputation of the truth he maintained,
to give advantage against it to its adversaries,
by obtaining his liberty in any clandestine manner; he therefore signified,
if they would ascertain the extent of a mile, he might make use of the liberty sometimes.
His fellow prisoner Fretwell, not being on the same foundation,
observed a different conduct,
for he soon found means to ingratiate himself with the jailer,
and by his interference obtained leave to go see his mother, and so got his liberty;
which occasioned the jailer to remark, "`that man was not right,
but that George was an honest man.`"
The jailer`'s sister also being sickly, visiting George in his chamber,
was so affected with his discourse, as to bear testimony concerning him and his friends:
"`that they were an innocent people that did harm to none, but did good to all,
even to those who hated them.`"

But notwithstanding his circumspect conversation,
and persevering caution to minister no occasion to the adversaries to speak reproachfully,
he could not long escape the obloquy of their malevolence:
For among others that came to see and discourse with him in his confinement,
there came a soldier from Nottingham, who it was understood had been a baptist,
and several along with him.
In the course of their conversation this person made use of this assertion:
"`Your faith stands in a man that died at Jerusalem,
and there was never any such thing.`"
George receiving this assertion with horror and amazement, opposed it with becoming zeal,
asserting on the contrary his firm belief of the scriptural account,
that as certainly as there were a Chief Priest, Jews and Pilate, there outwardly,
so certainly was Christ persecuted by them outwardly, and suffered death by their hands.
But from this conversation, notwithstanding this clear evidence of his faith,
a slanderous report was raised That the Quakers should deny Christ,
that suffered and died at Jerusalem,^
footnote:[This groundless calumny hath not (through the malevolence
of successive adversaries) been suffered to become obsolete,
being a charge,
brought against them (in contradiction to their positive assertion of their belief,
who certainly know best what they believe) to this day.
Mosheim hath revived this refuted reproach in a manner which does no honour to his candour,
his moderation or his veracity.
"`The European Quakers (saith he) dare not so far presume
upon the indulgence of the civil and ecclesiastical powers
as to deny openly the reality of the history of the life,
mediation and sufferings of Christ; but in America, where they have nothing to fear,
they are said to express themselves without ambiguity on this subject,
and to maintain publicly that Christ never existed,
but in the hearts of the faithful.`" What a specimen
of illiberal misrepresentation is this!
The European Quakers thought it their duty to pay obedience to
the civil power in all things relating to civil peace and order:
And where the laws of the state required compliances
contrary to the law of God in their consciences,
they were eminently remarkable for innocent boldness
in maintaining their testimonies publicly,
and making open profession of their faith,
notwithstanding the penalties they were exposed to,
for their faithfulness to the superior law, as will abundantly appear in the sequel;
no fear of civil or ecclesiastical powers ever deterred
them from asserting their doctrines and sentiments,
in the face of the world, as believing them founded in truth.
When their present persecutors were fallen from the pinnacle of power,
and by the successive changes of government became again exposed to persecution themselves,
they with other dissenters could disguise and conceal themselves and their
sentiments to avoid the penalties to which they were obnoxious,
while these Quakers, so called,
(like Daniel praying with his windows open towards Jerusalem,
contrary to the king`'s decree) steadily adhered to their principles,
and openly professed them, without shrinking at the danger,
or skulking in corners to avoid detection.
They were not ashamed to avow their principles, nor afraid of suffering for them;
so far were they from not daring to presume upon
the indulgence of the civil or ecclesiastical powers,
in preserving the testimony of a good conscience.
{footnote-paragraph-split}
How egregiously uncandid then,
uncharacteristic and ill- sounded is the insinuation,
as if the Quakers privately held one opinion,
and for fear of detection publicly avowed the contrary;
and what proof or authority doth he advance in support of this disingenuous innuendo?
truly none at all.
Is the Chancellor of the university of Gottingen a title of such
con sequence as to make his _ipse dixit_ pass for a denomination,
or is the testimony of an high Dutch D.D. to whom this people were not known,
deserving of any credit, without the clearest and most incontestible authority?
I have not the opportunity of as intimate an acquaintance
with the Americans as the Europeans;
yet I believe that the faith of the people called Quakers
is the same in this respect all the world over;
and although the discipline exercised amongst them relates chiefly to their moral conduct,
yet I am firstly persuaded that if any member or
any body of that people should maintain the doctrine,
which this author insintuates they do, the body at large, in their collective capacity,
would reject them and their doctrine together.
And really, when so heavy a charge is recorded as history with an air of confidence,
upon no better grounds than hearsay, one is apt to be a loss which to admire most,
the want of charity, modesty or integrity in the writer.
{footnote-paragraph-split}
This passage also conveys a caution how warily we
ought so receive for truth the calumnious representations of this people at this era,
when we find how readily every wild notion or action of any person,
whom chance threw amongst them, though not of their society at all,
was by public rumour affixed to them.]
which George asserted to be utterly false, "`and the least thoughts of it,
(said he) never came into our hearts.`"

Although the civil war in England was terminated by the death of the late king,
and the independent parliament was fixed in the seat of government there,
yet Ireland remained to be subdued,
and the ruling party in Scotland had come to a resolution,
after the execution of Charles I. to acknowledge
his son Charles II. as solicited to his successor,
and upon very humiliating conditions received and proclaimed him their king.
The parliament of England therefore being likely to have a double war on their hands,
thought it necessary to augment their forces,
and many new soldiers being raised at this time,
when George Fox`'s term of commitment to the house of correction was nearly expired;
the commissioners invited him to accept the office of a captain,
and the soldiers were desirous to have him for their commander;
for which purpose being by the keeper of the house
of correction brought up before the commissioners,
in the market place,
they there made him the offer of that preferment (as they called it) asking him
if he would not take up arms for the commonwealth against Charles Stuart.
He told them, he knew from whence all wars did arise, even from the lusts,
and that he lived in the virtue of that life and
power that took away the occasion of all wars.
And they pressing him more earnestly with a shew of kindness to accept of their offer,
which they said they made out of regard to his virtues,
and he still rejecting their proposals,
and persisting to testify against all wars and fightings,
their pretended regard to his virtue quickly gave way to
the impetuosity of their resentment at his peremptory refusal,
and probably at his pointed testimony against their
warring spirit under their religious pretensions.
They immediately commanded the jailer to put him into the common jail among the felons;
into a most filthy prison, without any bed,
he was accordingly thrust amongst thirty felons, and kept there near half a year,
the companion of thieves (except that he was allowed the privilege
of walking in the garden sometimes.) What power of arbitrarily
imprisoning these commissioners were invested with,
or whether by martial or civil law, or any law but that of their own wills,
we are uninformed: But this seems certain, that they were filled with rage against him,
and had power to gratify it; which they did with unjustifiable severity:
For what greater punishment could be inflicted on a tender innocent youth,
who feared God, and detested every species of wickedness,
than to be thus pent up and confined in the company
and conversation of the vilest of mankind.
It was in some degree analogous to the cruelty of the tyrant,
who is feigned to have tied the living to the dead: Their bad expressions,
and the obscenity of their conduct and conversation,
were no less grievous to him than the filthiness and inconvenience
of the prison in which they were stowed together.
However, not discouraged by the prospect of the danger he might be exposed to,
he felt himself frequently constrained to reprove them for
their wicked words and evil carriage towards each other.
Yet it doth not appear he received any ill usage from them,
and people wondered he was so preserved from harm amongst such company;
And those who watched for his halting could never catch
a word or action from him to turn to his disadvantage,
which he did not attribute to his own wisdom or strength,
but to the preserving power of that Divine Being,
to whose service he was sincerely devoted.

During his confinement he had occasion to remark the pernicious
effects of keeping prisoners long in jail,
as it furnished them opportunity, by recounting their feats of villainy,
to corrupt one another still more,
and to initiate the fresh men into all the mysteries of ingenious or daring depredation,
so that they generally came from thence more confirmed in vice and debauchery.
He therefore thought it his duty to communicate his observations hereon to the judges,
and to point out the necessity of speedy justice to prevent these bad consequences,
so prejudicial to the peace and security of society.

Although few, if any,
could be more circumspect to avoid sin and evil in their own particulars,
and few were more averse to them in others, yet he was affected with commiseration,
for those unhappy wretches who forfeited their liberty and
lives to the laws of their country by their illicit practices;
and especially that the lives of men should be taken away even for small thefts.
The compassion he felt on that account, particularly for a young woman in prison,
for robbing her master of some money,
induced him to write to the judges and magistrates to move them to mercy in such cases,
shewing them how contrary it was to the old law:
That in the Jewish state thieves were to make restitution; and if they wanted ability,
they were to be sold for their theft; putting them in mind to shew mercy,
that they might receive it from the judge of all.
Whatever effect his interposition might have,
the young woman above mentioned was reprieved at the gallows,
and was afterwards in prison convinced.

The Scots, after the unfavourable battle of Dunbar,
were obliged to admit their king to a greater participation of power than
before that event their jealousy of him suffered them to entrust him with,
and to admit him to a command in their army, which was so advantageously posted,
and so well supplied with provisions from the northern parts,
that Cromwell was unable to force them to an engagement,
and therefore passed northward in order to cut off their provisions,
but by this movement left the passes into England unguarded.
Charles, in expectation of being joined by all his friends,
and the malcontents under the present government,
seized the advantageous opportunity presented to him,
and advanced by great marches into the heart of England.
Cromwell, to repair this oversight, pursuing with equal alacrity,
overtook and defeated the Scots at Worcester, which finally decided the contest,
and left the independent parliament undisputed masters of the empire.

This sudden and unexpected invasion with out doubt created a great alarm in the nation,
and excited the adherents to the present government to zealous
exertions in procuring recruits from all quarters,
to repel the invaders;
upon this occasion Justice Bennet sent a constable to press George Fox for a soldier;
but he who would not voluntarily accept of a command,
and that from a conscientious scruple, was not like to comply with their requisition.
The constables brought him before the commissioners,
who positively insisted on his entering into the military line,
and he acting upon principle, and persisting in his refusal,
they committed him to close imprisonment, without bail or mainprize;
whereupon he again appealed to their feelings in a letter addressed to Colonel Barton,
and the rest who were concerned in his commitment, in which,
through the simplicity of his style, the christian temper which dictated it is apparent;
in substance as follows:

[.embedded-content-document.letter]
--

You who profess yourselves to be christians, and one of you a minister of Jesus Christ,
consider neither he nor his apostles did ever imprison any; but his command was,
"`Love your enemies, and do good to them that hate you.`"
The love of God persecuteth none, but loveth all: Take heed of owning Christ in words,
and denying him in life and power.
The imprisoning my body is to gratify your own wills, but beware of giving way thereto,
for that will hurt you.
If the love of God had +++[+++tendered]
your hearts ye would not have imprisoned me,
but my love is to you as to all my fellow creatures; and my intent in writing to you is,
+++[+++in order]
that you may +++[+++be incited to]
weigh yourselves, +++[+++in the balance of sincerity and equity]
and see how you stand, +++[+++approved in the sight of God].

--

It is not improbable that this letter,
together with the innocency and circumspection of his conduct,
made an impression upon them; for they now began to grow uneasy about him,
from a consciousness, I suppose,
of their exertion of an arbitrary and unjust power against an inoffensive man,
in whom they could find no crime to justify their proceedings:
For notwithstanding their former representation of him as a deceiver,
seducer and blasphemer,
his innocency and integrity of life had so far gotten the better of their prejudices,
that they now acknowledged him to be an honest and virtuous man.
Let the world say what they will,
God hath placed a witness for himself in the consciences
of all men which convinceth them of evil,
whereby they may be brought to see their errors,
but (it being too humiliating to acknowledge them) to preserve a reputation,
they often endeavour to conceal their perception thereof from the observation of others.
They wanted to rid their hands of him,
but how to preserve some appearance of consistency and palliate the severity
of their treatment seems to have been a subject of perplexity.

One while they talked of sending him up to the parliament,
another of banishing him to Ireland.
At length they set him at liberty in the beginning of the winter 1651,
after detaining him in prison near twelve months, six months in the house of correction,
and the rest of the time in the common prison.
