== Chapter V

[.chapter-synopsis]
* George Fox goes to Swarthmore
* Lecture at Ulverston, at which George Fox preaches; and in Judge Fell`'s Family, who are most of them convinced
* The Judge informed, and alarmed thereat
* His Wife in a distressing Dilemma
* George Fox vindicateth himself and his Doctrines to the Judge`'s Satisfaction
* Priest Lampit endeavours to incense Judge Fell against George Fox in vain
* Justice Sawrey stirs up the Rabble, from whom George Fox and others receive violent Abuse
* Instances of more violent Abuse
* Judge Fell issues Warrants to apprehend the Rioters
* George Fox accused of Blasphemy, acquitted, and encouraged to preach whereby several are convinced

He next passed over to Lancashire by Cartmel and Ulverstone to Swarthmore,
the seat of Thomas Fell, a Welch judge,
who was upon his circuit when George Fox came to his house,
being an house of hospitality, open for the reception of ministers and religious people.
Next day there being a lecture at Ulverston, George Fox went to it;
when he came in they were singing,
and after they had finished this part of their service, he stood upon a seat,
and desired liberty to speak, which was granted:
He there so plainly distinguished the essential from the professional part of religion,
that Judge Fell`'s wife Margaret was effectually reached,
so that she sat down in her pew and wept bitterly, crying in her spirit,
"`We are all thieves! we are all thieves!
We have taken the scripture in words, and know nothing of them in ourselves.`"
George proceeding in his discourse, and declaring against the false prophets,
who take upon them to explain other men`'s words,
while they were out of the life and spirit of those
whose expressions they pretended to explain,
John Sawrey, a justice of peace, ordered him to be taken away;
and after some time a constable executing the order,
he continued his exhortation to the people in the graveyard.
In the evening he returned to Judge Fell`'s,
and had an opportunity to preach in the family to
that effect that most of them were convinced by him.
Being a family of note their conversion made a great noise in the country,
and raised George Fox many enemies, several of whom met the judge on his return home,
and prepossessed him with the melancholy intelligence,
"`That a great disaster had befallen his family; that the Quakers were witches,
and had turned them from their religion; and that he must send them away,
or all the country would be undone.`"
Under the affecting impression of this report he reached his house in perturbation,
displeasure, and anxiety of mind; nor was the anxiety of his wife short of his,
for being clearly convinced of the truth of the doctrines delivered by George Fox,
she thought it her duty to adhere thereto,
and yet her affectionate regard for her husband filling
her with reluctance at the thoughts of giving him uneasiness,
she felt herself in a distressing strait,
between the apprehension of displeasing her husband or offending her maker;
but James Nayler and Richard Farnsworth being then in the house,
at her desire had a conference with him,
in which they conducted themselves with so much prudence
and moderation as greatly conduced to mitigate his displeasure;
and in the evening George Fox returned,
and finding that Judge Fell was greatly prejudiced
and incensed against him and his principles,
by the misrepresentations of the priests and professors,
and George Fox in particular by those of Justice Sawrey,
he entered into a free discussion of his principles and his doctrines;
answered all the judge`'s objections so fully and clearly
from scripture that he was thoroughly satisfied,
and assented to the truth and reasonableness thereof.
This judge`'s conduct was truly candid and respectable,
highly becoming his station as a judge,
and honourable to his character as a man and a christian,
to hear the defendant before he condemned him,
and to indulge him with a fair opportunity of vindicating
himself from the misrepresentations of malice and prejudice.
Had George Fox, his adherents, and their successors,
always met with the like candid treatment, they had not been so often,
and so lately unfairly represented to the world through malice or ignorance,
by those who do not love, or those who do not know them.

The next morning after this conference, Lampit, priest of Ulverstone,
paid a visit to the judge, and walking out with him into the garden,
he had much conversation with him, no ways in favour of his new guests,
to whom he was no friend; but his attempts against them were of little effect,
for the judge was too clearly convinced by the evening conference with George Fox,
not to receive easily impressions to their prejudice.
Instead of listening to the insinuations of the priest,
he soon gave a demonstrative proof of his favourable disposition to the
Quakers by a voluntary offer of his house for a meeting place,
in consequence whereof there was a pretty large meeting the first day following,
and thenceforward a settled meeting continued in that house '`till the year 1690,
when a new meetinghouse was built there.

This impression on judge Fell`'s mind in their favour was very mortifying
to those who wished the suppression of this rising society,
as in him they found a steady friend and protector: Justice Sawrey and +++_______+++ Lampit,
priest of Ulverstone, were particularly chagrined hereat,
and let no favourable opportunity slip of gratifying their resentment,
and making them feel the effects of their aversion and ill will.
Soon after this there being a lecture day at Ulverstone, and Judge Fell being from home,
George Fox went to the worship house on that occasion, and attempting to speak there,
Sawrey came up to him and told him if he would speak
according to the scriptures he might speak;
George replied, he should speak according to the scriptures,
and prove his doctrine thereby: Then Sawrey insisted,
in plain contradiction to his own voluntary proposal, that he should not speak at all;
notwithstanding which he proceeded to make use of the liberty given him,
and the people were attentive and heard him with satisfaction,
'`till Sawrey (the first promoter of persecution in the North) incensed them against him,
and incited them to abuse him greatly.
By the instigation of this man,
the place and time of worship were converted into a scene of riot and tumult,
for there George Fox was kicked, knocked down and trampled upon in his presence.
At last Sawrey took him from the people,
and delivered him to the constables and other officers,
with orders to whip him and put him out of the town,
which orders having executed in a rough and violent manner,
they delivered him over to the rude multitude, who being provided with staves,
hedge-stakes and bushes of holly, assaulted him with such fury,
and beat him in various parts of the body, head, arms and shoulders,
to that degree that he fell down fainting and senseless on a wet common.
After lying a while he recovered,
and the return he made them was an endeavour to bring them to a
sense of the inconsistency of their conduct with Christianity,
informing them that this carriage was more like that of Heathens or Jews than true Christians,
and manifested the fruits of their priest`'s ministry.
Returning to Swarthmore,
he found his friends there humanely employed in dressing the wounds
of those who had been cut and bruised by Lampit`'s hearers.
For although the chief force of their violence had fallen on George Fox, several others,
not only of those who openly joined in profession with him,
but of such also as discovered a partiality towards them who did,
in this day of lecture perverted into riot,
felt the injurious effects of the license given to a mob,
divested of the restraints of law, religion and humanity.

At this time the current of popular odium ran very
strongly against this inoffensive people hereaway;
and it is not to be wondered at that the unthinking multitude
should give the loose rein to their propensity to evil,
when those whose proper business it was to restrain them, and to instruct them better,
so far forgot the duty of their offices as to encourage
and abet this mischievous disposition in them.
Magistrates (invested with power to preserve peace and good order in the state,
to support the laws, and to be "`a terror to evil-doers,
and a praise to them that do well`") yielding to the influence of their teachers,
or the impulse of their passions, so far as to instigate the populace to acts of riot,
in violation of law, peace and justice.
Preachers (who ought to promote righteousness,
truth and christian forbearance) prostituting the pulpits
to the unbecoming purpose of propagating calumny,
in malicious misrepresentations and fabulous tales, in order to set off the Quakers,
so called, in odious colours, and to point them out as objects of detestation,
insult and abuse.^
footnote:[One Marshall, priest of Wakefield,
was not ashamed to promulgate this ridiculous report,
that George Fox carried bottles about him,
and by making people drink thereof made them follow him.
That he rode upon a great black horse,
and was seen in one county upon his horse in one hour,
and in the same hour in another county threescore miles off;
but by these absurd fictions he missed his aim,
so far as to drive away many of his hearers.
{footnote-paragraph-split}
Camelford, priest of a chapel about Cartmel,
upon George Fox`'s beginning to speak after he had done,
incited the rude multitude to fall upon him, who haled him out, struck and kicked him,
and threw him headlong over a stone wall.
{footnote-paragraph-split}
An idle report was propagated of the Quakers being
witches (as appears by the intelligence carried to Judge Fell) than which none could
be invented more mischievous among the superstitious vulgar of those days,
who not only believed such reports,
but that no treatment could be too bad for those
who lay under the imputation of being such.]

By such unjustifiable proceedings were the populace
stimulated to rage and violence against this people,
who did injury to none.
George Fox in about two weeks after the abuse he met with at Ulverstone,
passing over to the island of Walney in company with James Nayler,
there met with equal or greater abuse.
At Cockan a man snapped a pistol at him, but it would not go off;
and he was no sooner landed on the island than he was assaulted by about forty men,
armed with staves and fishing poles, with an intent to pull him into the sea,
which when he prevented, by pressing into the midst of them,
he was knocked down and stunned: For James Lancaster, having been convinced there,
they pretended that he had bewitched him,
and promised his wife if she would let them know
when he came there they would put him to death,
and this seemed to be their intention; "`but (says he) the Lord`'s power preserved me,
that they could not take my life.`"
James Lancaster`'s wife was amongst the foremost in this assault,
for when George Fox recovered his senses he observed
her busy in throwing stones at his face,
while her husband was endeavouring to protect him from the violence of the multitude,
by covering him with his own body, to keep off the blows and stones aimed at him;
but this woman being afterwards convinced,
repented of the evil she had been hurried into in this abuse,
as did some others of those concerned therein.
When George at length recovered his feet they beat him down again into the boat,
which James Lancaster observing, came to him and set him back over the water;
and when he got off they fell on James Nayler in the like unmerciful manner.
When George Fox landed again at Cockan he met with no better treatment,
for the people there rose upon him with pitchforks, flails and staves, crying out,
"`__kill him__;`" and after giving him much abuse,
drove him some way out of the town and left him,
after which he walked three miles to a friend`'s house named Thomas Hutton,
where Thomas Lawson (who had been a priest, and was convinced by George Fox) lodged.
When arrived at this house he was hardly able to speak by
reason of the wounds and bruises he had received,
and could barely inform them of the jeopardy in which he left James Nayler,
whereupon they mounted their horses, went in search of him,
and brought him thither that night.

Next day Margaret Fell sent an horse to fetch him to Swarthmore,
but it was with great difficulty, and in much pain he got thither,
through the soreness of his bruises, being scarce able to bear the motion of the horse.

Then the justices Sawrey and Thompson issued a warrant against him,
but judge Fell coming home prevented its present effect:
He was greatly displeased with the abusive treatment which
George Fox and his friends had received in his absence,
representing to Sawrey the impropriety and illegality of
his conduct in fomenting riots and tumults in the country.
He also sent forth warrants into the isle of Walney to apprehend the rioters,
whereupon some of them absconded.
Desiring George Fox to give him a narrative of his abuse, he only told him,
"`They could do no otherwise in the spirit wherein they were;
that they manifested the fruits of their priests ministry,
and their profession of religion to be wrong;`" which made the judge remark,
he spoke as of a matter in which he had no concern.

His enemies did not rest satisfied with stirring up the rabble against him,
they next made an attempt to endanger his life by a false
accusation of speaking blasphemy in a certain meeting,
and suborned false witnesses against him to prove it.
Upon their information it was that before-mentioned
justices granted their warrant to apprehend him,
which, although it was not executed, George Fox, whose fortitude,
supported by the consciousness of his integrity and innocence,
never declined a fair trial of his doctrine or practice, hearing of it,
voluntarily appeared at the ensuing sessions at Lancaster to face his accusers,
and hear what they had to lay to his charge.
There appeared not less than forty priests to aid and abet the accusation,
who chose one Marshal, priest of Lancaster, for their orator; a young priest,
and two priests sons, for witnesses; but these witnesses failed of answering their ends;
for after the first was examined,
the second on his examination was so much at a loss to answer the questions put to him,
that he acknowledged he could not say it,
(I suppose repeat the blasphemous expressions) but the other could.

This drew the following interrogatory reproof from the justices: "`Have you sworn it,
and given it in already upon oath, and now say that he can say it?
It seems you did not hear those words spoken yourself, though you have sworn it.`"
There were in the court several persons, men of integrity and reputation in the country,
who had been at that meeting wherein the witnesses
swore he uttered those blasphemous expressions,
who declared in court,
"`That the oath which these evidences had taken was altogether false;
and that no such words as they had sworn against
him were spoken by him at that meeting.`"

The justices finding the witnesses did not agree,
and perceiving that the prosecution was malicious, discharged him.
Then Judge Fell, after speaking to the justices who granted the warrant,
and shewing them the errors thereof, in concert with Colonel West,
granted a supersedeas to stop its execution.
This confederacy of priests to inflict punishment on an innocent man,
and to stop the progress of those doctrines he propagated,
received a signal defeat in both attempts.^
footnote:[When we see the lengths these priests could go to wreak their malice,
have we not reason to suspect their descriptions
of this people of being tinctured with the same spirit,
and therefore to be credited with caution,
and some grains of allowance for the disposition in which they were written?]
For he was not only honourably acquitted in the open sessions of
the false accusations with which their malice had charged him,
to their lasting disgrace and confusion; but,
being called upon by the aforesaid Colonel West,
that if he had anything to say to the people he might freely declare it: He,
feeling a proper qualification, made use of the liberty granted him;
and though he met with opposition from some of the angry priests,
they were so clearly confuted,
and divine truths so plainly and powerfully opened by him,
that many new proselytes to his doctrine were gained that day;
and amongst them Justice Benson of Westmoreland, Major Ripan, mayor of Lancaster,
and Thomas Briggs (who had shewn much aversion and
opposition to the Quakers) was so effectually convinced,
that he became a faithful minister of the gospel amongst them,
and so continued to the end of his days.
