== Chapter VI.

[.chapter-synopsis]
* The Society increaseth under their Sufferings
* Sufferings of James Nayler
* James Nayler imprisoned for not putting off his Hat, and as a Vagabond; and Francis Howgill along with him
* James Nayler tried for Blasphemy and acquitted
* Note on Nicholson and Burn`'s Extract from Higginson`'s Memoirs
* Imprisonment of Thomas Aldam

By patient suffering, through divine support, and the testimony of a good conscience,
through jealous exertions of their ministerial labours, under persuasion of duty;
the combined efforts of a licentious populace, of malevolent priests and professors,
and of persecuting magistrates, proved ineffectual to check the progress of this society.
Meetings of this people were now settled in many central and northern parts of the nation,
and several of them had joined in the work of the ministry with
the approbation and to the edification of their fellow members,
so that the number of preachers was augmented to twenty-five,
amongst whom Francis Howgill, Edward Burrough, John Camm, John Audland,
Richard Hubberthorn, with the three before-mentioned, viz. Richard Farnsworth,
William Dewsbury and James Nayler, were eminent for their services and their sufferings;
for they had not only a share with George Fox in his ministerial labours,
but also in his mal-treatment.

For in the course of this year James Nayler and Francis
Howgill were both imprisoned at Appleby;
James being at a meeting at Orton, five priests with many people came thither;
the priests asked him many questions,
to which he gave such answers as frustrated their purposes of ensnaring him in his words.
However, against the succeeding first day,
they had prepared sermons filled with invectives against him,
representing him as a blasphemer, a denier of the resurrection and humanity of Christ,
and a contemner of authority;
and some of them indulged their spleen so far (as their hearers reported)
as to assert it would be doing God service to knock him down.
Having thus prepared the ruder sort of people,
and one of the priest`'s sons drawing a great company of them together,
beset the house where he was, and dragged him with violence into a field,
where a justice, sent for by a priest, was present,
who commanded him to answer such questions as the priest should put to him,
who after much conference, getting little advantage against him, grew angry,
and warning the people not to receive him into their houses turned away,
and the people beginning to be abusive, the justice was about doing the same,
as if they intended leaving him to the mercy of the populace.
But at James`'s remonstrance, the justice turning back rescued him for the present:
yet at the instance of the priests, who were pleased thereat,
he was again seized by the rabble, and brought before the priests and justice,
at a neighbouring alehouse, and because he did not put off his hat,
they committed him to prison for his pretended contempt,
and also as being not putting a vagabond, under pretence,
that none there knew whence he came; for they had shut out all his acquaintances:
Upon his appealing to the justice that he knew him,
they having been in the army together several years,
the justice replying it was no matter,
made his mittimus and carried him to Kirby-steven that night and placed a guard over him.
Amongst several more of his friends, Francis Howgill accompanied him thither,
who took an opportunity to preach to the people,
a considerable number being gathered in the street; upon which,
being brought before a justice, after an examination,
in which they endeavoured to wrest his expressions in order to criminate him,
he was likewise put under a guard, and next day, together with James Nayler,
sent to Appleby jail.^
footnote:[Besse`'s [.book-title]#Suffering of the Quakers#, vol. 2. p. 2]

At the sessions held in Appleby in the month blasphemy, called January, 1652,
James Nayler was tried on an indictment for blasphemy; but after a long examination,
it appearing that the priests^
footnote:[Nicholson and Burnn, authors of reputation,
have thought it worth while to draw from obscurity to public view,
as late as the year 1777, an extract from some memoirs of Higginson,
vicar of Kirby Steven, (one of the priests before-mentioned,
and the only one mentioned by name,
as a principal in promoting the abuse offered James Nayler by the populace,
and this prosecution for blasphemy) containing a recital of various extravagancies
committed by the people called Quakers at this period;--such as foaming,
bellowing out "`repent, repent; woe,
woe,`" etc. some of them running naked about the streets,
and preaching naked at the market-cross--many of them in their
assemblies falling down suddenly as in an epileptic fit,
and lying grovelling on the ground, foaming at the mouth, their lips quavering,
their flesh and joints trembling, and their bellies swelling like a blown bladder:
All which easily accounts for the name of Quakers being given them.--In
their preaching they called themselves the way,
the truth and the life.--One James Milner declared
himself to be the son of God and Christ.
{footnote-paragraph-split}
The narration from which this
abstract was taken was republished in the Monthly Review for March,
1778, which gave occasion to the following remonstrance to the reviewers,
published in the succeeding Review.
{footnote-paragraph-split}
"`To the Authors of the Monthly Review.
{footnote-paragraph-split}
"`Gentlemen,
{footnote-paragraph-split}
"`You have selected an extract from
Nicholson and Burn`'s History of Westmorland in your last Review,
respecting the first Quakers, and, by adding the epithet curious to it, you have,
in some degree, given it your sanction.
The account is said to be drawn from some (I suppose
before unpublished) memoirs of a Mr. Higginson,
formerly vicar of Kirkby Stephen.
{footnote-paragraph-split}
"`It seems somewhat extraordinary,
that a gentleman of Dr. Burn`'s great and deserved reputation in the literary
world should have thought it fair to draw from its obscurity a paper,
written at a time when the minds of most men were heated with religious prejudice,
and when the clergy, more particularly, were irritated against the Quakers,
because their tenets, opposing the venal support of the priesthood,
sapped the very foundations of its splendour and authority.
Nor perhaps did they scruple to add the epithet of hireling to those,
who making a trade of religion, brought it into disrepute amongst the people.
{footnote-paragraph-split}
"`At the quarter
sessions at Appleby in Westmoreland in January 1652,
James Nayler, a Quaker, was tried for blasphemy.
The trial is still extant, and it appears from thence that Higginson,
vicar of Kirkby Stephen, was a promoter of the prosecution.
Nayler was then honourably discharged, nothing of that kind being proved against him,
unless it be reckoned blasphemy to oppose Higginson`'s assertion, repeated in open court,
that Christ is in heaven with a carnal body.
Both the temper of the good vicar, and the complexion of his divinity,
may perhaps be inferred from this anecdote.
{footnote-paragraph-split}
"`The evidence of Higginson carries with it
all the marks of that wanton exaggeration which characterises personal animosity.
The charge is supported by no proof.
Gerard Croese, indeed, in his [.book-title]#History of the Quakers#,
mentions a petition from the ministers, and sundry other persons of Lancashire,
against George Fox, James Nayler, and their associates,
in which they are accused of foaming at the mouth in their conventicles,
and of other strange agitations; and George Fox, in particular,
of having said that he was equal to God, the only Judge of the World, Christ, the Way,
the Truth, and the Life.
One James Melver (perhaps Milner) was also charged with saying that he was God and Christ,
and with prophesying that the day of judgment was at hand
that there should be no more justices in Lancashire,
and that the parliament should be plucked up by the roots.
Higginson`'s narrative and this petition bear striking marks of affinity with each other,
and probably sprung from the same source.
Croese, however, who was no Quaker, nor is his history partial to the Quakers,
acknowledges, '`that these charges were so completely refuted,
that it was apparent they who invented them were wicked men,
and they who believed in them were fools.`'
He excepts the mad presumption of Melver (or Milner), whom he says the Quakers rebuked.
The truth is, that as the Quakers, for the reason above-mentioned,
were especially singled out as the objects of priestly indignation,
every rumour to their disadvantage was eagerly adopted
and frequently spread with circumstances of aggravation.
Thus a Vicar of Wakefield, whose name was Marshal, reported of George Fox,
that he rode upon a great black horse,
and was seen within an hour at two places sixty miles distant from each other.
If the papers of this Vicar were narrowly searched into, it might, possibly,
be found recorded as his opinion, that the first Quakers were witches.
It must, notwithstanding, be acknowledged,
that it was not unusual for some of the most zealous
to go sometimes into the public places of worship,
and after the preacher had finished his discourse,
to reprove both priest and people for practices which
they considered as superstitious or antichristian.
{footnote-paragraph-split}
"`Amidst the swarm
of sects which distinguish the last century,
there was one, of which little is now known,
but that the practices of its adherents outraged all decency and order.
They were called Ranters.
The enemies of the Quakers found it frequently suitable
to their purpose to confound them with this ephemeron sect,
whose principles were nevertheless totally incompatible with those of the Quakers.
There is a paper still extant, written by Edward Burroughs,
an active preacher amongst the Quakers,
against the licentious practices of these people.`"]
could not make out the charge exhibited against him,
he was discharged by the justices from his imprisonment,
which had continued about twenty weeks.
Whether Francis Howgill`'s confinement was of a longer or shorter continuance than this,
we have no account.

Thomas Aldam, one of those early preachers, was also imprisoned this year in York,
at the instigation of the priest of Warnsworth,
for uttering some expressions after the priest had ended his sermon.
At York assizes he was fined 40. for coming into the court with his hat on:
and was a second time imprisoned in York castle for refusing to pay tithes,
and detained in prison two years and six months.
He had also, for 11£. 10s. demanded for tithes, taken from him goods worth 58£. 10s.

In the course of the same year several others,
whose religious concern induced them to exhort the priests and their congregations
at the close of their public assemblies for worship,
met with the like severe treatment;
but to describe particularly the sufferings they underwent for their Christian testimonies,
would carry me far beyond my proposed limits.
Their suffering in the different counties of England and elsewhere,
have been digested by Joseph Besse, and make two volumes in folio.
