== Chapter I.

[.old-style]
=== From the End of the Commonwealth to the Restoration of Monarchical Government

[.chapter-synopsis]
* Oliver Cromwell dissolves the Parliament
* The Change of Government brings no Advantageto the Quakers
* George Fox goes into Cumberland
* At Carlisle he preaches at the Market-cross, and in the Steeple-house
* Summoned before the Magistrates and imprisoned
* Rumour of his being to be hanged
* The Judge and Magistrates in Consultation about bringing him in guilty of Death; being puzzled therein, resolve not to bring him to Trial
* A fair Trial demanded without Effect
* George Fox confined among Felons and cruelly treated
* James Parnell convinced
* The Parliament inquire into George Fox`'s Case
* George Fox released
* M. Halhead greatly abused

We are now entering upon the year 1653,
in the forepart whereof another revolution in government took place:
The parliament conceiving a jealousy of Oliver Cromwell`'s ambition,
power and influence in the army;
and having upon trivial grounds commenced and prosecuted
a naval war against the Dutch with signal success,
very plausibly insisted on the intolerable additional parliament,
expence to which the nation was put,
to maintain a land army (now no longer necessary)
and urged the necessity of a reduction thereof.
Cromwell wanted not penetration to see the tendency of these designs to lay him aside,
and therefore resolved to anticipate them.
Bringing the officers and body of the army, now the real masters of the nation,
into his views,
he without hesitation forcibly dissolved the remnant of the long parliament, and,
in conjunction with the principal officers,
took the reins of government into his own hands.

This change of government doth not appear to have
produced any revolution in favour of the Quakers,
so called; for although the supreme power was seized into new hands,
the subordinate magistrates were continued in office by the new council of state,
nor do I find any material change among the ecclesiastics,
so that their former persecutors retained power to be still troublesome to them:
and their sufferings continued to increase with the increase of their numbers.

George Fox, still indefatigable in his labours,
in spite of all opposition and the discouragement of his sufferings,
passed about this time into Cumberland,
and from place to place his ministry was so well received,
that many new convert were gained to his doctrines in most places which he visited.
Coming to Carlisle, he first preached to the soldiers in garrison there,
directing them as usual to Christ as their teacher,
and to the measure of his spirit in themselves, warning them to do violence to no man,
but shew forth a Christian life.

On the market-day, he went up to the Market-cross,
and cautioned the people against fraud and over-reaching in their dealings,
and to speak the truth one to another.
On the first day following he went to the Steeple-house,
and after and at the priest had done he preached to the people with a reaching power.
The rude people of the town rose and assaulted him in the Steeple-house;
but the governor sent down some musketeers to appease the tumult, who,
taking George by the hand in a friendly manner,
led him out and rescued him from further insult.
A lieutenant who had been convinced took him to his house,
and there they had a quiet and satisfactory meeting.
The next day he was summoned before the magistrates,
who falling into discourse with him upon religion, in the course of their conversation,
perceiving their emptiness as to the essence thereof,
he endeavoured with his accustomed sincerity to shew them,
that although they were high in profession (being Presbyterians and Independents)
yet they were without the possession of what they professed.
This plain dealing exasperating them, who, it`'s too probable,
affected the name of religious men,
and the appearance of purity more than the substance of pure religion;
they committed him to prison under the hard names of a blasphemer,
an heretic and a seducer, where he lay '`till the assizes.
And in the interim the general discourse was,
and from the disposition that prevailed against him at this time and in this place,
it`'s to be feared, the general wish was that he was to be hanged.
The high sheriff, whose name was Wilfry Lawson,
indulged his rancour so far as to say he would guard him to execution himself.
And the notion was so universal that curiosity drew
several ladies (so called) to see him,
as a man that was to die.
When the assizes came the judge and magistrates held a consultation
how to proceed against him in order to bring him in guilty of death;
but the judge`'s clerk starting a question that puzzled them and confounded their counsels,
and finding that the charge of blasphemy could not be made good to bring against him,
and that of consequence if brought to trial he must be acquitted,
they concluded not to bring him to a trial at all.

Anthony Pearson, a justice of peace in Westmoreland, lately convinced,
being then in Carlisle, and understanding the result of their consultation,
wrote to the judges, shewing the illegality of this resolution,
and demanding a fair trial for George Fox;
but they paid no regard to this reasonable demand of the subject`'s right,
but left him to the magistrates of the town, encouraging them to treat him with rigour.
He had hitherto been confined in the jailer`'s house so closely,
that all his friends were denied access to him;
but the day after an order was sent to the jailer to put him among the felons and murderers,
in prison noisome and filthy to the last degree, where, contrary to all decency,
men and women were kept together,
without any other convenience to ease nature than the room they were in;
amongst a crew so unclean that one woman was almost eaten up with lice.
Yet these prisoners, vile as they were, behaved affectionately to him,
received his admonitions with deference,
and some of them became converted by his doctrine.
But far different was the conduct of the jailers, being very cruel and abusive,
particularly that of the deputy,
who in brutal rage would often fall upon his friends who came to see him,
and himself also, with a great cudgel.

Whilst he was confined in the dungeon here,
among others who came to visit and discourse with him was one James Parnel,
a youth of about sixteen years of age,
who was by his conference so effectually reached that he was convinced,
received the truth in the love of it, and soon became a powerful minister himself,
and the means of convincing many others, proving himself by his pen and his tongue,
in the zealous promotion of solid religion, a workman that need not to be ashamed;
although for these zealous endeavours he underwent grievous persecution,
as will hereafter appear.

The report that had been raised previous to the assizes,
that George Fox should be put to death, had by this time spread abroad;
and it came to the ears of the parliament then sitting,^
footnote:[This was the parliament that is distinguished by the denomination of Barebones,
and by some by that of the short parliament,
being a number of one hundred and twenty summoned by Oliver Cromwell,
in order to amuse the people with some resemblance of a common-wealth,
to take upon them the executive part of government.
Many of them being selected from the middle rank of the people have given occasion
to sundry historians to characterize them in terms remarkably contemptuous,
as men of the lowest birth and meanest intellects, chosen by Cromwell,
particularly for their want of knowledge and experience in affairs,
in prospect that the reins of government might revert into his own hands:
But others speak of them with more respect,
as a convention in which were several persons of worth, fortune and abilities;
and as the principal objection to their conduct seems to
be a project they were designing to put in execution,
which the people had been flattered with the hopes of before but disappointed,
viz. the abridging of the delay and expense of law-suits, and abolishing tithes.
I am ready to join in with the latter opinion,
that there were amongst them men of worth and integrity,
disposed to apply the power they were invested with to the public good,
which I think would have been essentially promoted
by the execution of such a scheme as this.]
that a young man at Carlisle was to die for religion,
whereupon they ordered a letter of inquiry to the
sheriffs and magistrates concerning him.

The justices Benson and Pearson having more than once demanded
liberty of the magistrates to visit George Fox in prison,
and being refused, wrote to them,
emphatically describing the turpitude of persecution in general,
and their own exorbitant severity in particular,
as exceeding in inhumanity that of the heathens, who having the apostle Paul in custody,
refused him not the consolation of the visits of his friends and acquaintance.
At length, however, Anthony Pearson got an opportunity, in company with the governor,
to visit him in his dungeon and found his situation so disagreeable,
George Fox and the place of his confinement of a smell so exceedingly offensive,
that the governor exclaimed at the barbarity of the magistrates,
and calling the jailers required securities for their good behaviour;
and the under-jailer, who had treated George Fox with great cruelty,
he imprisoned in the dungeon with him.
In the mean time, these persecuting magistrates,
probably afraid of the parliament`'s further cognizance of their proceedings,
and ashamed at the governor`'s remonstrance,
soon after thought it expedient to release him,
as the surest measure to bury their unjustifiable conduct in oblivion.

This year Miles Halhead, of Underbarrow in Westmoreland,
one of the first zealous preachers,
feeling a concern to travel into Yorkshire in the work of the ministry,
in obedience to what he believed his duty, proceeded on his journey, in which,
for publishing those doctrines which he held as truth, he met with much grievous abuse.
At Skipton and at Doncaster he was so sorely beaten and bruised
by the rude multitude that they left him to appearance dead;
but being supported by an invisible hand he recovered,
even to the astonishment of those who abused him,
and to the convincement of many who had heard his doctrine,
and observed his patience in suffering nigh unto death,
and the unchristian and unprovoked malice of his assailants and their abettors.
Thomas Briggs in Lancaster, Robert Widders and William Dewsbury in Cumberland,
were also severally abused in like manner.

But still through all opposition, patient and undismayed,
through divine assistance and support,
George Fox and his fellow-labourers persevered in their
ministry with unremitted zeal and remarkable success,
the number of their adherents increasing in proportion
to the cruel efforts exerted by magistrates,
priests and mobs, to prevent their increase.
Even these measures, employed to stop their progress, proved,
in the over-ruling hand of divine providence, the means of advancing it.
The innocence and integrity of their lives,
the fortitude and christian temper with which they suffered persecution,
buffeting and grievous abuse, pleaded powerfully in their behalf,
and procured them the compassion and esteem of many.
Others who heard them everywhere spoken against, and particularly from the pulpits,
which should have been better employed, on a nearer acquaintance with them,
found them and their principles so grossly misrepresented
as induced them to forsake such teachers,
who under the profession of purity in religion fell so far short of moral rectitude,
and to associate with this people, whom they found honest in heart, upright in conduct,
and truly sincere in their profession of godliness.
