== Chapter II.

[.chapter-synopsis]
* Oliver Cromwell declared Protector
* Which is of no Advantage to the People called Quakers
* Pretext for Persecution
* Remark upon the Benevolence and mutual Affection of the Quakers, so called
* Their Prosperity in Commerce by Means of fair Dealing

The short parliament, commonly called Barebone`'s,
having resigned their power back into the hands of Oliver Cromwell,
from whom they received it, the council of officers, by the advice of Lambert,
adopted a new scheme of government,
tempering the liberty of a republic with the authority of a single person,
under the Cromwell denomination of protector.
Cromwell was accordingly declared protector, and a model of a protector,
new legislature was drawn up, which they termed the instrument of government,
and which he was sworn to observe in his administration thereof; in which,
as there were a several articles in favour of liberty of conscience,
some relaxation of the vindictive measures hitherto pursued
against the Quakers was natural for this people to expect.

But notwithstanding these plausible appearances of
liberality of sentiment in favour of religious liberty,
this people reaped no advantage therefrom,
but continued to be exposed to all the hardships they had before experienced,
not only from ordinances being turned against them, but their meetings for worship,
though seemingly allowed, were in fact prohibited,
since they were punished as sabbath-breakers,
for travelling to them no further than their distant dwellings made necessary.

But the authority of government, and power of executing the laws,
being in the hands of those whose principles had formerly
subjected themselves to the severity of the bishops;
and who had, when under suffering,
loudly exclaimed against the tyranny and iniquity of persecution,
for a conscientious dissent from established forms of worship or modes of faith,
and had taken up arms to deliver themselves therefrom, having now gotten the upper-hand,
they could not, with any degree of consistency or modesty,
openly reverse their former professions, and maintain persecution lawful in them,
which they had so violently opposed in others;
they continued to condemn it speculatively, but to keep it up practically in use;
for this purpose they endeavoured to comprehend actions merely
religious under a description within the reach of the laws.
A christian exhortation to an assembly after the priest had done,
and their worship was over, was denominated, interrupting public worship,
and disturbing the priest in his office:
An honest testimony against sin in the streets or
markets was styled a breach of the peace;
and their appearing before the magistrates covered a contempt of authority:
Hence proceeded fines, imprisonments and spoiling of goods.
Nay, so hot for persecution were some magistrates,
that by an unparalleled misconstruction of the laws against vagrants,
they tortured with cruel whippings the bodies of
both men and women of good estate and reputation,
merely because they went under the denomination of Quakers.

While they were exposed to hatred, contempt and abuse from without,
brotherly kindness and unfeigned charity increased,
and connected them in cordial affection amongst themselves;
so that the priests and professors,
who had vainly prophesied their downfall by other means,
observing Remark their mutual charity and hospitality, began now to say,
they would eat one another out: Because many of them after meetings,
having a great section of way to go,
took a night`'s lodging at some of the people their friends houses,
sometimes in large numbers: Others who walked not by faith as they did,
actuated by political considerations, expressed their fears,
that by their expenses in entertaining one another, they would be reduced to beggary,
and fall a charge upon the parishes.
But many of these lived to see the vanity of their fears and forebodings;
for it pleased divine providence remarkably to bless them and prosper their undertakings.
At the first, indeed, people were shy of dealing with them, by reason of their plain,
and, as it was generally esteemed, uncouth demeanour and address;
and by reason of the general aversion produced by malignity and misrepresentation,
so that many of this people were reduced to difficulty
in procuring a living by their callings for a season;
but afterwards, when they became better known for what they were,
and not for what they were falsely reported to be;
manifesting the excellency of that internal religion they
professed by the regularity of their moral conduct,^
footnote:[It is a remarkable instance of the charity and
mutual benevolence that prevails amongst this people,
that they have never suffered their poor to fall an incumbrance on their parishes;
but they have ever afforded them a comfortable support amongst themselves:
and at the same time evidence the universality of their benevolence,
by a readiness with the foremost to contribute to the support of the common poor,
both in their quota of the poor tax,
and in extending private charity to deserving objects within their notice.]
and their conscientious regard to fidelity in their commerce,
void of all deceit and circumvention;
careful in manufacturing or choosing such goods as might be substantial,
and answer the expectations of the a purchasers, moderate in their profits,
sparing in their commendations, and punctual in their payments,^
footnote:[Hume,
notwithstanding the contemptible and ridiculous light
in which he has endeavoured to place this people,
owns this (and this only) to be a laudable maxim.
If he had viewed them with dispassionate and discerning eyes,
I think he might have discovered many other maxims
of this people deserving approbation as well as this.]
not asking more for their ware than the precise sum they were determined to accept,
taking no advantage of ignorance,
the unskilful customer being sure to be treated with as much justice as the most judicious;
their tried integrity begat general confidence,
and that confidence brought them a great resort of customers,
so that they prospered greatly in their outward affairs, and verified the proverb,
that _honesty is the best policy._
