== Chapter III.

[.chapter-synopsis]
* Sundry Friends travel abroad in the Work of the Ministry
* Francis Howgill and Edward Burroughs the first of this People who visited the City of London
* Francis Howgill intercedes with Oliver Cromwell to stop Persecution
* Meetings settled in London
* Francis Howgill and Edward Burrough travel to Bristol, and there meet with John Camm and John Audland
* Francis Howgill and Edward Burrough examined by the Council and ordered to depart out of the City
* The Mob instigated to abuse those Friends, which they do in a very gross Manner
* Sufferings of Elizabeth Heavens and Elizabeth Fletcher at Oxford
* Convincement and Sufferings of Barbara Blaugdon
* She is imprisoned at Alarlborough, committed to Exeter Jail and cruelly whipped
* At Basing-Stoke procures the Liberty of Thomas Robertson and Ambrose Rigge

Meetings being settled in many parts of the northern counties,
and with the number of professors the number of ministers proportionately increasing,
several of these conceived it their duty to go forth
into other parts of the nation to propagate the gospel,
and to turn people to righteousness.
Of these Francis Howgill and Edward Burrough travelled to London;
John Camm and John Audland to Bristol;
Richard Hubberthorn and George Whitehead to Norwich, and others to other parts.
George Fox from experience,
impressed with a lively sense of the importance of the work in which they were engaging,
solicitous for the advancement of the truth,
and that no part of the conduct of those who were concerned to
promote it might in the least degree sully the brightness thereof,
wrote an epistle, admonishing them to prudence; to abide under the cross of Christ;
to receive wisdom from God by the light; and not to be hasty to run in their own wills,
but to continue in patience.
Francis Howgill and Edward Burrough arrived in London in company with Anthony Pearson,
being the first of the people called Quakers that had a meeting in London,
Francis Howgill and Anthony Pearson at the house of Robert who visited Dring in Watling-street,
and Edward Burrough the same day in the assembly of a separate society:
Their ministerial labours were blessed with signal success,
being attended with a convincing power, impressing awful considerations,
and awakening the consciences of the audience to a sense
of their conditions and earnest desires after salvation.
They were eminently qualified for the service in which they were engaged,
not only with sound understanding and a sufficient share of literature,
but the superior qualification of the experience
of the quickening power of that inward religion;
which they endeavoured to recommend and propagate;
a religion not amusing the head in curious speculations,
but purifying the heart and cleansing the conscience
from dead works to serve the Lord in newness of life;
prepared for the work of the ministry by the previous work of inward sanctification,
and bettering themselves to that arduous undertaking called of God as was Aaron.

Having a feeling sympathy with his brethren under persecution,
with whom he had been a fellow-sufferer,
Francis Howgill went to court to intercede with Oliver Cromwell to put a stop thereto;
but his visit seems to have had a more beneficial
effect upon Oliver`'s servants than upon himself;
for some of these,
and particularly Theophilus Green and Mary Sanders were so far affected by his discourse,
that after some time they joined themselves to the people called Quakers.

Francis Howgill afterwards wrote to Oliver very boldly and plainly on the same subject;
but the sequel doth not manifest any good effects resulting therefrom;
his friends continued still subject to a variety of hardships
for their conscientious adherence to their religious principles,
during the remainder of his protectorate, and through the succeeding revolutions.

Through the zealous and effectual preaching of Edward Burrough and Francis Howgill,
many of the citizens of London were brought over to their profession,
so that meetings were settled in sundry places in that city,
first in the house of Sarah Sawyer in Aldersgate-street,
then in that of +++_______+++ Bates in Tower-street,
and another at Gerard Roberts`'s in Thomas Apostles,
'`till the body growing too large for private houses to accommodate,
a house known by the name of Bull and Mouth in Martins-le-grand, near Aldersgate,
was hired for a meetinghouse.

Now the press as well as the pulpits was set to work for the purpose of defamation:
Abundance of books and publications by the priests and teachers of several sects
were spread abroad representing the Quakers as seducers and false prophets.
For being chagrined at the loss of their hearers,
many of whom had gone over to this rising society,
they were roused to employ every engine to stop its progress:
But the event did not answer their hope,
for Burrough and Howgill did not suffer these writings to pass unnoticed;
but clearly manifested the malice and the absurdities of the writers.

It doth not appear that they met with any molestation in their persons in the metropolis;
but after they had gathered and settled meetings there, they travelled thence to Bristol,
where John Camm and John Audland had arrived before,
and where their ministry had been effectual to gather a
number to their community and particularly Josiah Coale,
George Bishop, Charles Marshal and Barbara Blaugden.
Their preaching was like that of the apostles, in the demonstration of the spirit,
and with power; multitudes flocked to hear them, and many embraced their doctrine.
Their public assemblies, for want of room in their usual meetinghouses,
were held in the fields, even in winter, increasing in number to two, three,
and sometimes near four thousand of all degrees, professions, ages and sexes.
This alarmed the priests, and they the magistrates,
who on the 30th October held a council, the mayor presiding,
and sent for Burrough and Howgill.
The issue of their examination,
at which none of their friends were suffered to be present,
though their opposers were readily admitted,
was an order for their departing the city forthwith at their peril.
To this they answered: "`We came not in the will of man, nor stand in the will of man,
but when he shall move us to depart who moved us to come hither we by whom shall obey:
We are free-born Englishmen, and have served the commonwealth faithfully,
being free in the fight of God from the transgression of any law:
To your commands we cannot be obedient; but if by violence you put us out of the city,
and have power to do it, we cannot resist.`"
Having said this, they went out of the court,
but tarried in the city preaching as before;
for though the magistrates bare them no good will,
yet they could not either by law or justice execute the order they had made.
The opposers of the truth, enraged at this disappointment,
excited the mob to do what the magistrates could not.
On the 19th of December John Camm and John Audland,
passing over the bridge toward Brislington, where they had appointed a meeting,
were assaulted by some hundreds of the rabble,
whose ignorant zeal had been blown up to the highest pitch of fury by one Farmer,
a persecuting priest, and some others.
They violently drove back the innocent strangers, some crying out, "`hang them presently,`"
others, "`knock them down;`" and would have dragged them out of the city,
in order to execute their wicked purpose,
but were dissuaded by some who advised first to carry them before the mayor.
Then they dragged them to the Tolzey, where the courts of justice are held.
There again the enraged mob would probably have torn them to pieces,
had not a friend with much danger and difficulty
got them into his house and shut the doors.
The rabble with hideous noise threatened to pull down the house,
while the innocent men remained as lambs dumb before their shearers,
in quietness and patience, yet undaunted, putting their trust in God.
After some time the officers of the garrison approaching, the mob,
fearing military execution, dispersed.
Next morning, the two strangers passed over the bridge to their meeting at Brislington.
Three of the rioters were apprehended,
on the report of which they gathered again to the number of fifteen hundred,
and forced the discharge of their companions.
Towards evening it was rumoured that the Quakers were returning,
whereupon multitudes drew together on the bridge,
and on the other side of the river Avon, uttering terrible menaces,
so that the magistrates, fearing bloodshed,
sent their sword-bearer to prevent the men from returning that way,
for that they could not undertake to secure them.
Thus Providence preserved the innocent from the enraged rabble,
whose fury spread a terror over the whole city.
These disorders were too much countenanced by men in office.
It was credibly reported that George Helliar, an Alderman, said at the Tolzey,
to some of the rioters, that he would spend his blood, and lose his life,
rather than that any of his fellow apprentices should go to prison:
Such familiarity increased their insolence.
Nevertheless the magistrates soon after, in representing these tumults to the Protector,
charged the innocent men, against whom they were raised as, the authors of them.^
footnote:[Sewel]

Amidst so many instances of arbitrary rule and lawless riot,
I am pleased to meet with one of a more humane and Christian
disposition in the mayor of Oxford of this year.
Elizabeth Heavens and Elizabeth Fletcher, two North-country women,
came under a religious concern to the said city,
to exhort the inhabitants and students to repentance and amendment of life.
Their labours of love met with inhuman returns from the scholars,
who drove these innocent women by force to the pump in John`'s College,
where they pumped water on their necks and into their mouths till they were almost suffocated;
after which they tied them arm to arm,
and with great barbarity dragged them up and down
the college and through a pool of water:
They threw Elizabeth Fletcher, a young woman, over a grave,
whereby she received a contusion on her side, from which she never recovered,
but soon after died.
A few days after this rude and unchristian treatment,
the same women went to one of their places of public worship,
and after the priest had done,
one of them began to exhort the people to the practice of godliness:
Two justices of peace, who were present, ordered them immediately to be sent to Bocardo,
a prison usually appropriated to the reception of felons and murderers.
Next day those justices sent a message to the mayor,
to meet them and others to examine these Quakers,
who expressed his disapprobation of their proceedings, "`Let them,`" said he,
"`who committed them, deal with them according to law,
for my part I have nothing against them: If they wanted food, money or clothes,
I would willingly supply them.`"
However, when the justices met he met with them, and the Vice-chancellor^
footnote:[Dr. Owen.]
of the university being sent for, readily came, and was the principal in examining them.
After a short examination,
the women were ordered to withdraw while the magistrates consulted together,
and although nothing appeared to criminate them,
these magistrates drew up their sentence against them in writing,
That they should be whipped out of the city.
Now, according to the legal constitution of the city,
it was requisite for the mayor to sign a sentence of corporal punishment,
and affix his seal of office to make it valid, which in this case he refused to do,
because he could not in conscience consent to a sentence,
which he thought unmerited and unjust.
But as a scrupulous adherence to legal forms was too often made to give
way to the gratification of a vindictive temper in magistrates,
actuated more by causeless hatred to this people, than regard to justice or humanity,
the Vice-chancellor and his coadjutors resolved,
since the mayor would not legalize the sentence by the sanction
of his signature they would have it executed without him,
and accordingly gave orders that the poor women should
be severely whipped the next morning,
and had their order effectually executed;
though the conviction of their innocence affected
the heart even of the executioner to that degree,
that he performed his office with manifest reluctance.
The women bearing their grievous sufferings with Christian patience,
without murmuring or complaining in the least,
their meek and patient behaviour impressed many of the sober
inhabitants with compassionate sympathy towards them,
and induced them to acknowledge them as the servants of God,
supported by his divine power to bear their testimony with innocence,
and their sufferings with the patience of saints.
With sensations of tender regard to them,
and of disgust and aversion to the severity of their persecutors,
they in much love and tenderness accompanied them out of the city.

In this year Barbara Blaugdon of Bristol met with usage equally severe.
She was a woman of good parts and education, religiously inclined from her youth,
of good repute, and esteemed in her profession or employment,
which was the instruction of children.
But being amongst the number of those who had been converted to Quakerism
(so called) by the efficacious ministry of John Camm and John Audland;
and believing it her duty to take up the cross,
she conscientiously adopted not only the simplicity of manners peculiar
to this society in dress and address (whereby she lost her employment)
but was so abstemious as to deny herself the use of flesh,
wine or beer, drinking only water for the space of a year.
In the meantime she grew in piety and religious experience,
This woman was repeatedly concerned to intercede on behalf of her persecuted friends,
and not without success,
and was remarkably exposed to a variety of afflictions and persecutions herself.
At Marlborough, for exhorting the people to fear God,
in the rough steeple-house and other places,
she was imprisoned for the space of six weeks; and after her release,
visiting Isaac Burgess, the magistrate who committed her,
by her discourse his understanding was so opened, that he assented to the truth;
and although he had not resolution to take up the cross,
so far as to make public profession thereof,
yet he was ever afterwards a man of moderation, averse to persecution,
and a friendly protector of the members of this community.
Soon after passing into Devonshire, at Great-Torrington,
for expressing a few words of exhortation to the people in the steeple-house,
whe was summoned before the mayor,
who upon her appearing before him conducted himself with moderation,
and seemed reluctant to send her to prison.
But the priest being present, discovered a very different temper,
and was very urgent with him to do it, expressing the bitterness of his spirit,
in saying, she ought to be whipped for a vagabond.
Upon which she desired him to prove wherever she asked any one for a bit of bread.
At length the priest`'s urgency prevailed over the magistrate`'s moderation,
by whom she was sent to Exeter prison twenty miles distant,
where she was detained till the assizes, but brought to no trial;
and after the assizes she was lodged one night among
a great number of gipsies who were there in prison.
Next day the sheriff coming and cruelly with the beadle, brought her into a room,
where she was very cruelly whipped till the blood ran down her back;
and such was her magnanimity, supported by an invisible power,
that she never started at a blow, but sang aloud,
rejoicing that she was counted worthy to suffer in a noble cause,
the testimony of a good conscience.
The unfeeling beadle, provoked at her constancy, laid his stripes with redoubled fury,
till the sheriff seeing that the utmost exertion of their malice made no impression
upon her (for she was strengthened by an extraordinary and more than human power,
so that she declared afterwards that in the state in which she was at that time,
if she had been whipped to death she should not be
terrified or dismayed) ordered the fellow to desist.
The next day she was turned out of the city along with the gipsies,
the beadle following them two miles out of town.
Upon his leaving them, she returned to visit her friends she had left behind in prison,
which having done she went home to Bristol.

She had not been long at home before she felt an impulse
on her mind to go abroad on the following occasion:
Two of her friends, Thomas Robertson and Ambrose Rigge,^
footnote:[These men coming to Basingstoke were informed that the priest
of that parish had uttered several invective speeches against them:
They, in order to clear themselves, desired an interview with him, which he refused;
but said they might expect to be shortly in prison;
And holding a meeting in a friend`'s yard, to which many of the town resorted,
during the meeting this priest with a justice of
peace came thither in a rude and angry manner;
and in order to get occasion against them the justice tendered them the oath of abjuration,
which refusing, from a conscientious scruple against swearing,
they were committed to prison, kept and examined apart; their money, bibles, ink-horns,
knives and papers taken from them,
(but the money returned) and none of their friends suffered to come near them.]
being at a meeting at Basingstoke in Hampshire (the first their
friends had there) were taken up and committed to prison,
where they had lain for some time;
and Barbara apprehending it her Christian duty to visit them in prison,
and use her endeavours to obtain their release, went to Basingstoke;
and upon her arrival there, going to the prison, was refused admittance.
She then went to the mayor, and requested their liberty; which he promised her to grant,
provided he might see the letter she had brought them,
(viz. a letter from J. Camm) which she readily producing, after he had read it,
he told her she should have her friends out,
but that he could not let them out presently:
Yet it was not long till they were set at liberty.
