== Chapter IV.

[.chapter-synopsis]
* George Fox in Lincolnshire convinceth the Sheriff
* Also Sir Richard Wrey and others
* A general Meeting at Swanington
* At Drayton disputes with Priest Stephens and other Priests
* Is taken up at Whetstone and brought before Col. Hacker
* Who sends him to the Protector at London
* By whom he is discharged
* Has great Meetings in London
* A Meeting at John Crook`'s, who is convinced

George Fox, after his release from Carlisle jail,
travelled through sundry parts of the north of England,
and through Yorkshire into Lincolnshire:
and the Sheriff of Lincoln coming to a meeting which
he was at made great contention for a time,
but at length was so reached by the power attending George`'s testimony that he was convinced,
as were several others also who came to oppose.

During his stay in this country the church of his friends increased,
and many received his doctrine; amongst others Sir Richard Wrey, his brother,
and his brother`'s wife, who both retained their integrity.
But Sir Richard finding the way too narrow left their community after some time:
for persecution gathering strength became as a touchstone
to try the sincerity of the professors,
being a trial of faith too severe for the hypocritical
or superficial professors to endure.

Travelling through Derbyshire into Leicestershire, he came to Swanington,
to a general meeting, where he met John Audland, Francis Howgill and Edward Pyot,
from Bristol, and Edward Burrough, from London;
and several were convinced in those parts.
To this meeting came many Ranters, Baptists, and other professors;
and the Ranters were very rude;
but that power which attended George and his friends
brought them down and confounded them,
so that many of them became convinced.

From hence he went to Twycross, and thence Drayton, the place of his nativity,
to visit his relations.
While he was here Nathaniel Stephens, priest of Drayton,
having first got another priest to dispute, and after that seven others to join him,
had given public notice, unknown to George,
that on such a day there would be a meeting and dispute with him.
Upon this occasion several hundreds of people were
gathered to witness the triumph of the priests.
This formidable combination was formed with a view to get
an advantage by their numbers over George and his friends,
in order to bring them and their principles into disgrace with the people;
but the event did not answer their hopes;
for in the course of their conference George drawing a striking parallel
between their practices and those of the false prophets and pharisees,
who were the subjects of rebuke in both the Old and New Testament,
the priests in disappointment quitted the field,
and many of the people were convinced that day: and George`'s father,
who was still in communion with Stephens, as one of his parishioners,
was so well satisfied, that, striking his cane upon the ground, he said,
"`Truly I see he that will stand to the truth, it will carry him through.`"

The priests failing of their purpose to vanquish George Fox by their disputing and argumentation,
had recourse to the secular power to gratify their envious designs against him,
and to bring him into trouble, or to put a stop to his travelling abroad.
He went from Drayton to Leicester, and from thence to Whetstone,
where a meeting was to be held; but before it began,
and to about seventeen troopers of Colonel Hacker`'s regiment took him up,
and brought him before the Colonel and his company of officers,
by the procurement of the priests as he thought.
And Hacker, after much discourse and reasoning with them,
the Colonel gave him liberty to go home,
provided he would stay there and not go abroad to meetings.
But George being unwilling to agree to the conditions, his son Nedham said, "`Father,
this man hath reigned too long, it is time to have him cut off.`"
So malicious a speech drew from George this pertinent query.
"`For what?
what have I done?
or whom have I wronged from a child?
In this country I had my birth and education,
and who can accuse me of any evil from my infancy
to this day?`"--Then the Colonel asked him,
if he would go home and stay at home?
George looking upon this requisition as unreasonable,
having administered no cause for such restriction of his liberty, replied,
if he should agree thereto it would imply that he was guilty of something,
for which his home was made his prison: And if he went to meeting,
they would consider that as a breach of their order;
therefore he plainly told them he should go to meeting,
and could not answer their requirings.
"`Well then,`" said Hacker,
"`I will send you tomorrow morning by six o`'clock to my Lord Protector, by Captain Drury,
one of his "`life guard.`"
That night he was kept in the marshalsea,
and next morning about the hour appointed delivered to Captain Drury.
But before they set off, requesting to speak with Colonel protector Hacker,
he was taken to his bedside,
when the Colonel repeated his order to him to go home and stay there:
And George being still unwilling to comply,
the Colonel insisted on his going to the protector.
Whereupon George kneeled down at his bedside, and prayed the Lord to forgive him:
looking upon him to be like Pilate,
willing to wash his hands while he complied with
the instigations of the persecuting priests;
and therefore desired him, when the day of his misery and trial came upon him,
then to re member what he had said to him.

So parting from him, he was carried prisoner by Captain Drury to London,
where being lodged at the Mermaid, Charing-Cross, Drury went to inform the Protector,
who sent him back with this message, That the Protector required of George Fox,
that he should promise not to take up the sword, or any other weapon,
against him or the government, as it then was;
that he should write it in what words he saw proper, and set his hand to it.
George, on consideration thereof,
wrote to the Protector the next morning by the name of Oliver Cromwell,
declaring in the presence of the Lord,
"`That he did deny the wearing or drawing of a sword, or any outward weapon,
against him or any man.
That he was sent of God to stand a witness against all violence,
and against the works of darkness;
and to bring people from the occasion of wars and fightings to the peaceable gospel;
and from being evil doers,
to whom the magistrates sword should be a terror;`" to which he subscribed his name,
and gave it to Captain Drury to deliver to Cromwell.
Some time after Drury returned, and brought George Fox before the Protector at Whitehall.
Upon his coming in he said, peace be in this house,
and exhorted the Protector to keep in the fear of God,
that be might receive wisdom from him; that by it he might be ordered,
and with it might order all things under his hand to God`'s glory.
They had much discourse about religion,
in which the Protector carried himself with much moderation:
But remarking that George Fox and his friends quarrelled with the ministers,
George told him he did not quarrel with them, but they quarrelled with him; but,
added he, if we own the prophets, Christ and the apostles,
we cannot up hold such teachers as they testified against, that is,
such as violate Christ`'s command, in not giving freely;
such as take the oversight of the flock for filthy lucre, and divine for money.
When George made a motion to retire, upon other people coming in,
Cromwell took him by the hand, and with tears in his eyes said, "`Come again to my house,
for if thou and I were but an hour of a day together
we should be nearer one to another,`" adding,
that he wished him no more ill than he did his own soul.
Then George bade him hearken to the voice of God, stand in his counsel and obey it,
if he did so it would preserve him from hardness of heart;
but if not his heart would be hardened.
The Protector seemed affected, and said, it was true.
George then taking his leave retired, and Captain Drury following him out,
informed him that the Lord Protector said he was at liberty,
and might go whither he would.

Being restored to liberty he stayed during the remaining part of the year in London,
where he had meetings so greatly crowded that he could hardly get to or from them,
because of the crowd.
The number of his friends greatly increased,
and he could reckon some belonging to Cromwell`'s court in the number of those convinced.

When he was clear of London he went into Bedfordshire,
where he had a great meeting at the house of John Crook, a justice of peace,
and many were convinced of the truth he declared,
of which number John Crook himself was one,
on which account he was soon deprived of his commission;
but after some time he became an able minister,
and a very serviceable member of this religious community.
