== Chapter V.

[.chapter-synopsis]
* Account of William Caton, Companion to Judge Fell`'s Son
* Convinced by George Fox
* He receives a Gift in the Ministry
* Account of John Stubbs, a Soldier
* Being convinced he refuses the Oath of Fidelity to Oliver Cromwell, for which he is disbanded
* Meets William Caton at London, and travels with him into Kent
* Being prohibited Entertainment at Dover, Luke Howard entertains them Samuel Fisher convinced
* Account of him
* At Maidstone John Stubbs and William Caton sent to the House of Correction, set in the Stocks and severely whipped
* Turned out of the Town different Ways
* Return to Maidstone, and discharge their service without Molestation
* William Caton goes over to Calais
* William Caton and John Stubbs go to Scotland

This people still increasing in number,
and the number of their ministers increasing also,
few counties in England remained unvisited by one or other of them.
About this time William Caton and John Stubbs went into Kent,
where they were made partakers with their brethren in bearing their
testimony to the sufficiency of the divine light with success,
and charitable endeavours to turn the people thereto,
and in suffering in their persons for their testimony:
But before I proceed to the particular description qf their labours and sufferings,
it seems proper, as they have not been noticed before,
to make the reader a little acquainted with them.

William Caton, about the fourteenth year of his age, by his father`'s procurement,
was introduced into the family of Judge Fell,
where agreeable disposition so ingratiated him with that family,
that he was made companion to the companion Judge`'s
son in his amusements and in his studies;
they learned Latin together for some time under a private tutor,
and were afterwards removed to a public school at
Hawkshead for their further improvement in the languages,
in which he made a good proficiency;
for which advantages he had reason to be humbly thankful
to divine providence for allotting him so favourable a situation;
but these were not the only advantages he reaped thereby.

Judge Fell, his wife and daughters, being in general persons of good sense,
liberal education, virtuous demeanour, and religious inclinations,
his conversation in such improving company, gave him an early turn to piety and virtue;
he was very punctual in his private devotions, and diligent, after hearing a lecture,
to transcribe the chief heads thereof,
in order to improve the favourable sentiments the family entertained of him,
it being a point with them at that time to hold in highest
estimation those who could repeat the sermons they had heard,
and paraphrase thereupon: But whatever praise he might attain thereby from others,
he did not feel that inward approbation therein which could satisfy his own soul.

In the year 1652 (as before recited) George Fox came
to Swarthmore and preached in the family,
recommending them to give heed to the light which Christ hath enlightened us withal,
to convince us of sin and evil:
This so affected William Caton that he became subject to this internal convincement,
whereby he felt much restriction in his conduct,
and could no longer take the liberties he had done before;
for although he had not been addicted to vice or profanity,
yet by the light he saw that he must be also weaned
from vanity and the common diversions of youth,
which tend to bring the mind into a state of dissipation,
inconsiderateness and unwatchfulness,
whereby it is in danger to fall into the enemy`'s snares,
and to be seduced from the paths of virtue and righteousness.
The divine witness was awakened in his conscience,
and reproved him for everything that was contrary to Christian gravity,
convincing him that it was a serious matter indeed,
to use all diligence to make our calling and election sure.
The change of company he met with at the school at Hawkshead,
on comparison with that he had left at Swarthmore, did not sit easy on his mind before,
but under these solid impressions both his companions
and exercises there became quite burdensome.
The making of Latin verses caused him particular uneasiness,
as he could not now give that scope to his invention which others did,
and as he had used to do.
Margaret Fell, perceiving his uneasiness in his present situation,
caused him to stay at home where she employed him in writing and teaching her children.
Being arrived at his eighteenth year,
he was increased in experience and strengthened in the spiritual warfare:
And in a while esteeming it his duty to labour in the ministry of the gospel,
he desired to be discharged from his engagements in that family,
which was granted in consideration of the service for which it was asked;
and so about the end of the year 1654 he took his leave,
not without tears on both sides.

John Stubbs was a soldier in Oliver Cromwell`'s army,
and being in garrison at Carlisle when George Fox was in prison there,
he was convinced by him, and became a convert to the doctrine he delivered;
and proving faithful to conviction he grew in experience;
he was now become a minister amongst this people,
and proved a man of eminence and ability for service.
Having received a liberal education, he was well skilled in the Latin,
Greek and Oriental languages.
When Oliver Cromwell took the reins of government into his own hands,
he required the soldiers and others to take an oath of fidelity to him and his government;
but several of them being convinced of the truth of the doctrine of the Quakers,
(so called) when the oath was tendered to them, declared,
that in obedience to Christ`'s command, they durst not for which swear,
whereupon they were disbanded; amongst these refusers was John Stubbs,
who the latter end of this year, or the beginning of the succeeding one,
travelled to London, where he met William Caton,
and in company with him travelled into Kent, and coming to Dover, altogether strangers,
they took up their lodgings at an inn.
They sought opportunities of publishing their doctrines
in the sundry congregations of professors in that town;
but the most remarkable opportunity was at a meeting of baptists,
to which abundance of people resorted, and many were affected with their doctrine,
and adhered to it, which occasioned such a stir,
that they were haled before the magistrates, who examined them,
though they had transgressed no law,
and prohibited the inhabitants from entertaining them under a penalty,
whereupon they were turned out of their lodgings,
but Luke Howard received them into his house, and heard them gladly.
The mayor sent four constables, with an order, to take them from thence,
and turn them out of the town; but Luke asserting his right,
as a freeman of the corporation, refused to comply with the order, insisting,
that the mayor had no legal authority to violate the laws of hospitality in his house,
by forcing out his guests, who were no malefactors, nor accused of any crime.
They tarried with him some days, and so confirmed him in the belief of their principles,
that he publicly declared himself to be of their persuasion,
and had meetings afterwards frequently at his house.

Soon after they came to Lidd, where by their Samuel ministry,
in conjunction with that of Thomas Robertson and Ambrose Rigge,
Samuel Fisher being convinced joined their society; he was a man of good abilities,
having received a liberal education in his minority,
and afterwards prosecuted his studies at the university--while there he
was a young man remarkable for his circumspect and pious conversation.
When he had finished his studies there he was ordained a priest,
and was first a chaplain to some man of quality,
and afterwards presented to the living at Lidd, worth two hundred pounds a year.
Before he became acquainted with any of the people called Quakers,
being conscientiously engaged in seeking after truth,
he discovered that infant baptism was an human institution,
and to preach for a stipend contrary- to the command of Christ: And Luke Howard,
before mentioned, also, before he had any acquaintance with any of those called Quakers,
being dissatisfied in his mind with the singing of David`'s psalms in the public worship,
gave his master, to whom he was apprentice, so much uneasiness,
that he applied to Samuel Fisher, as a learned minister,
to take an opportunity of a religious conference with him,
in order to remove his scruples, with whose request complying,
Luke was very open in declaring the reasons of his scruple, to the following purport:
That God was a spirit, and to be worshipped, not in other men`'s words,
but in spirit and in truth.
That it was a falsehood for a proud man to sing, that "`he was not puffed up in his mind;
he had no scornful eye, and he did not exercise himself in things that were too high.`"
That it was absurd for any man to sing, "`Rivers of tears run down mine eyes,
because other men keep not thy laws,`" whilst he never knew a true sorrow
and repentance for "`his own sins.`" The result of this conference was,
that instead of removing Howard`'s scruples,
these reasons of his had such a convincing effect on Samuel Fisher`'s mind,
that he found himself restrained from giving out
David`'s conditions to the people to sing any more.
And at length his continuing to preach for wages,
contrary to the inward conviction of his conscience
becoming a burden too grievous for him to bear,
he gave a rare instance of the honesty of his heart,
and the value be put upon the testimony of a good conscience, by resigning his living,
and divesting himself of the sacerdotal character,
placing his confidence in Divine Providence for the
future support of himself and his family.
He rented a farm, and commenced grazier, by which he procured a decent competency,
enhanced by the consolation of solid content, and the testimony of an approving heart.

Having discovered too great a mixture of human invention
and tradition retained in the episcopal church,
he withdrew from its communion, and joined the baptists,
amongst whom he be came an eminent teacher.

It was about this time that William Caton and John Stubbs came to Lydd,
whom Samuel Fisher received into his house, remembering that scripture exhortation,
Be not forgetful to entertain strangers.
John Stubbs going to the baptists meeting where Fisher preached,
and having gotten an opportunity to preach the gospel,
according to the principles of his friends, he delivered;
his doctrine with a clearness and authority, whereby Samuel Fisher was so affected,
that he soon after openly professed himself of this despised society,
particularly on the following occasion: Hammond, his colleague in office,
in a sermon uttering many bitter invectives against the Quakers, Samuel Fisher,
incited by a more Christian temper, and a dispassionate regard to truth,
thought his duty called upon him, in justice to his misinformed flock,
and the injured Quakers,
to bear his testimony in opposition to the calumnies of his colleague,
but with the moderation and charity of a Christian, expressing himself in these terms,
"`Dear brother, you are very dear and near to me, but the truth is dearer and nearer:
It is the everlasting truth and gospel which they hold forth.`"
Which candid expressions drew one from Hammond,
stamped with the mark of a very different spirit:
"`Our brother Fisher is also bewitched.`"
But Samuel`'s faith was not of that cast, which returned reviling for reviling;
but in the sincerity of his heart having borne testimony to the truth,
as held by the people called Quakers,
he corroborated it by joining with them in religious fellowship,
and proved a very serviceable member,
both by his gospel labours and his judicious writings.

William Caton and John Stubbs continued their journey through Kent,
where they met with many people religiously inclined,
who readily embraced their doctrine;
and some of them which they being desirous to make them
a pecuniary acknowledgment for their gospel labours,
and being urgent with them to accept thereof, they acknowledging their good-will,
but refusing their money, let them know it was not theirs but them which they sought.

Travelling on to Maidstone,
John Stubbs went to the public place of worship then possessed by the Presbyterians,
and William Caton to the meeting of the Independents.
John Stubbs was taken from the worship house and put into the stocks,
and afterwards examined by the Recorder,
to whom he rendered a good account of himself and of his estate,
being sufficient to support himself and his family.
Caton was next day taken from the inn, and also examined by the Recorder;
and they were both sent to the house of correction where they were searched,
and their money, ink-horns and bibles, etc. taken from them.
Afterwards they were stripped, and their necks and arms put in the stocks,
and were so cruelly whipped with cords as to draw tears from the spectators.
After all this, endeavours were used to compel them to work, but in vain;
for as they were guilty, of the breach of no law,
they justly refused to comply with the unreasonable demand; as their submitting thereto,
being an agency in their own punishment, might imply guilt, from which they were free.
Their persecutors therefore, under the pretence that "`he that would not,
work should not eat,`" kept them some days without victuals,
allowing them only a little water once a day.
Some of the malefactors imprisoned there,
more compassionate than these ill-principled religionists,
would have shared their bread with them, but they were not free to accept of it.
But the report of their cruel treatment being spread in the town,
and producing compassion in many of the inhabitants,
and discontent and aversion to this arbitrary severity,
an officer was sent to restore them some of their property,
which had been taken from them, and then they purchased victuals with their own money.
Not long after they were separated, and sent away with a pass by the officers,
like vagabonds, being taken out at different end of the town,
and sent off by different ways.
Afterwards they met again at London, and had not been long there,
till they apprehended it a duty required of them to return to.
Maidstone, to fulfill their ministry in that place and places adjacent.
This, after their late severe sufferings there, was a very great trial to them;
but believing it to be a without divine requiring,
they gave up in resignation to the divine will,
and through the providential ordering of that hand in which they trusted,
or the sense the magistrates retained of the disreputation
brought upon them by their former cruelty,
they were suffered to discharge their duty and pass away unmolested.
From thence they went to Canterbury,
and at the meeting of the Baptists and Independents
had liberty to publish their doctrine among them,
whereby some being convinced of the truth thereof received their testimony.

In the latter end of this year and the beginning of the
next they took their journey together to Scotland,
and at Berwick William Caton went to the public worship house,
and after the priest had concluded,
had pretty good liberty to deliver what was on his mind; but when he had done,
was laid hold of and taken before the magistrates,
who ordered him to be turned out of the town, which order was immediately executed.
John Stubbs was that day at the Baptist`'s meeting, and had some service there.
They travelled on to Edinburgh,
where they found some disorders crept into the church
through the unfaithfulness of some who had been convinced;
but, through the effectual influence of their ministry,
better order was restored amongst them.
From hence John Stubbs returned to England.
William Caton stayed some time longer in Scotland,
exercising his ministerial labours in sundry places to good purpose; whereby,
having discharged his service in this nation to the ease and clearness of his own mind,
he returned to Swarthmore where he was received with much affection.
