== Chapter VII.

[.chapter-synopsis]
* Sufferings of William Dewsbury
* Imprisonment of him and Joseph Storr
* Examination before the Judges Hale and Windham
* Imprisonment of John Whitehead and Marmaduke Storr
* Second Examination before Judge Atkins, and Recommitment
* Released by Order from Oliver Cromwell
* Thomas Stubbs imprisoned
* Committed to Bridewell and whipped
* Edward Burroughs writes to the Protector
* Reflections on Cromwell`'s Conduct in regard to the People called Quakers
* Account of John Lilburn: 1. Prosecuted in the Star Chamber, and put in the Pillory. 2. Prosecuted by the Long Parliament, and acquitted. 3. Prosecuted by Cromwell, acquitted, but detained in Prison
* In Dover Castle he is convinced of the Principles of the People called Quakers
* Anne Downer committed to the House of Correction and whipped
* Miles Halhead and Thomas Salthouse taken up and passed as Vagrants
* An angry Priest procures their Imprisonment
* Their Examination
* Committed to Exeter Jail
* Indictment at Sessions
* Cruel Usage of Margaret Kellam

So epidemic was the causeless inveteracy against this people;
so general the persecution under which they suffered,
that we scarce meet with one person, whose travels and services are preserved on record,
who escaped personal abuse or cruel imprisonment in any quarter of the nation.
William Dewsbury about this time traveling in Northamptonshire, came to Wellingborough,
where as he was passing along the street,
the priest Thomas Andrews called out to him "`Give over deceiving the people,
lest the plagues of God fall upon thee;`"^
footnote:[Sewel, p. 119]
to whom William replied, "`Dost thou say I deceive the people?
make it appear wherein I deceive them.`"^
footnote:[Besse, v. 1 p. 518.]
Andrews answered,
"`Thou tellest them there is no original sin;`" to which William Dewsbury rejoined,
"`Didst thou hear me say any such words?`"
upon which the priest went away.
William being thus in public charged by the priest as a deceiver,
thought himself called upon, in vindication of his own character,
and that of the society,
to bring the priest to the proof of his charge or public acknowledgment of the truth:
For that purpose he went soon after to the Steeple-house,
and waiting till the people were dismissed, he spake to them,
who gave attention to his exhortation.
Then addressing himself to the priest, he said,
"`Thou hast accused me of deceiving the people;
prove thy accusation before this audience, or acknowledge the falsehood of it.`"
But the priest without giving an answer went away:
And William was haled out of the worship house into the yard,
where he preached to the people again, who stood quietly to hear him,
till the high constable came, and laying hold of him led him to the market place,
saying he would bring evidence against him for blasphemy.
After a short time he was let go, and lodged at a friend`'s house that night;
but next day a constable apprehended him with a warrant, granted against the Quaker,
without mentioning his name, and took him before a justice,
who committed him to Northampton jail by a mittimus,
which was said to contain a charge of blasphemy;
wherefore William solicited for a copy of it; but his request,
though just and reasonable, was not granted.

By the same mittimus Joseph Storr, who only came to hear his friend`'s examination,
and against whom there was no accusation, was sent to prison along with him:
So arbitrary were the proceedings of those magistrates,
under a government professedly set up for dispensing universal liberty.
They were imprisoned in a dungeon, twelve steps under ground, among felons,
till the ensuing quarter sessions,
at which they were brought before the bench of justices, where their mittimus was read:
a copy of it again requested and refused.

No cognizance was taken of their cause, but they were remanded to prison,
to lie there till the next assizes.
At which they were brought before the judges Hale and Windham,
and after a long examination, in which nothing criminal was made out against them,
they were offered their liberty, on condition of giving bail for their good behaviour,
and also for their appearance at the next assizes;
which proposal they were unwilling to comply with,
as an unreasonable demand from them who had given no just occasion for it,
being neither convicted nor guilty of ill behaviour.
They were recommitted to the same filthy dungeon, amongst the felons as before,
till another assize.
In the mean time several other of their friends were sent
to bear them company in prison in the like arbitrary manner,
viz. John Whitehead, Marmaduke Storr, and Francis Ellington.

John Whitehead going into the Steeple-house at Wellingborough,
and waiting quietly till the public worship was ended,
asked the priest some questions about his doctrine and practice,
to which he made no answer, but in contempt called him madman, and went away:
But the people generally staying, were soon convinced he was not mad;
for his powerful preaching and rational discourse impressed
very different sentiments of him on their minds,
procuring their assent to the soundness of his doctrine and his understanding.
Intelligence of this being carried to the priest,
irritated him to challenge John to a dispute; but the issue mortified him still more,
because he missed his aim, which was to get some matter of complaint to the magistrates.
He next wanted John to meet him before a persecuting justice to settle the dispute;
but he avoided this open snare,
signifying to the priest that he must appoint some other place.
He then sent him notice to meet him at a public lecture, which he accordingly did;
and there being several other ministers and many people present,
he waited quietly till their service was over:
Then he proposed a question to the preachers, which they refused to answer; and Andrews,
the priest, who had challenged him to dispute,
instead of entering into the discussion of their differing religious sentiments,
launched out into personal invectives and accusations against John Whitehead,
who was not at a loss to vindicate his character by plain truth,
to the conviction of many of the people.
The priests seeing themselves not like to compass their
design by these means had recourse to their last argument.
Byfield, priest of Torrington, having laid violent hands on John,
and dragged him by force out of the Steeple-house;
a warrant was procured to apprehend him as a vagrant,
and he was carried before two justices, convened for that purpose.
In contradiction to the charge, he insisted he was no vagrant,
that he could prove his habitation and manner of living by one of his neighbours,
a substantial man, if they would admit him to come in.
Upon this Marmaduke Storr was called, who informed them of the place of John`'s residence,
and that he had a wife and family, whom he maintained reputably.

Then they asked Marmaduke his name and place of abode,
and what was his business in those parts?
He gave them full satisfaction in these points: that his residence was in Holderness,
and his occupation that of a grazier; that his business there was to visit,
and be an assistant to his brother Joseph Storr, prisoner at Northampton;
and that from thence he proposed to proceed into Staffordshire
to renew the lease of his farm near expiring.
The account he gave both of himself and his neighbour was
so unexceptionable that the justices were at a stand,
and after some consultation with the priests, dropped the pretence of vagrancy,
and determined to ensnare them both another way.
They asked Marmaduke if he would confirm his testimony upon oath,
and finding that he would not, they tendered them both the oath of abjuration.
They answered,
that they had sufficiently demonstrated their good affection to the commonwealth,
in assisting it with their persons and estates in times of its greatest straits,
that they were well known to be no papists,
but that they could not swear for conscience-sake.
They then required sureties of them for their good behaviour,
and upon their refusal they were committed to prison,
whereby M. Storr was prevented from getting his lease renewed;
so that his family were constrained to remove, and carry off his stock at a day`'s notice,
to his great detriment.
And these, as well as the former, were detained in prison till the ensuing assizes,
in the month called July, 1655, when they were all brought before Edward Atkins,
Judge of Assize, before, whom they passed under a long examination,
for it cannot be properly termed a trial,
there being nothing against them to found an indictment upon,
nor any living witness produced only an information exhibited by the Clerk,
that W. Dewsbury, came into the church of Wellingborough,
and stood there during the time of sermon and prayers with his hat on:
and after the Minister had done, he spoke these words "`the Priests preach for hire,
and my people love to have it so,
and what will you do in the end thereof,`" with other railing words,
which made disturbance among the people.
In his vindication Dewsbury related the matter of fact as specified before.

The Judge after examination of him and his fellow-prisoners,
finding the allegations against them too frivolous for his attention,
express his displeasure at being troubled therewith;
and although he conducted himself towards them with
a degree of temper and moderation beyond some others,
yet he left them where he found them, that is, recommitted them till the next assizes,
upon their refusal to put in bail for their appearance there.^
footnote:[Their trial or examinations at large,
would take up more room than I can conveniently spare,
and therefore refer those who may desire further information to Besse`'s [.book-title]#Sufferings,
Vol. 1.# p. 518, etc. from whence this account is abstracted.
The examination, however, of Francis Ellington,
discovering the measure of justice dispensed to them all,
will serve as a specimen of the rest: Judge.
Which is Ellington?
F.E. I am so called.
Judge.
What are you here for?
F.E. I was in bonds 15 weeks for my appearance at the general sessions,
and when I appeared, no accuser or evidence appeared against me;
I was convicted of the breach of no law, yet those called Justices committed me to jail,
where I have been kept in the dungeon these 13 weeks,
among those arraigned for felony and murder;
being taken from my outward habitation at Wellingborough, from my out ward calling,
and from my wife and five small children:
and here am deprived of the benefit of the law of this nation,
which no felon or murderer that is here is deprived of,
for they have liberty to speak for themselves, and to have a fair trial,
which is denied to us.
Judge, to the Clerk of the peace.
Where is your evidence against these men?
Clerk.
This Ellington is a receiver of these men,
and here is a letter he writ to a Justice of Peace,
wherein he accuseth him of injustice in committing Dewsbury and Storr to prison.
Judge.
Why do you trouble me with that which there is no matter of fact in?
I much wonder you should trouble a Judge of Assize with such small things,
and not end them in your own sessions, for we come hither to determine greater matters.
Mr. Ellington, I have a great love for you, being a man that lives in this country:
Will you enter into bond for your good behaviour, and to appear at the next assizes?
F.E. I am of no evil behaviour,
neither to this day hath any thing been proved against me,
and if it can yet be proved by any one man here, that I have been of evil behaviour,
or have broken any law of this nation, I am present to answer it,
and give bonds for my liberty.
Judge.
You have transgressed the law, in that you come to the bar with your heads covered;
because it is a contempt of authority.
F.E. There is no law in this nation requires any such thing as putting off the hat;
if there be any, I desire it may be read,
that so before the country I may be convinced by the law, before bonds may be required.
Judge.
I shall deal favourably with you,
for I shall take your own bond to appear at the next assizes.
F.E. First prove me a transgressor of the law; for the righteous law of God saith,
where there is no law, there is no transgression;
and there is no law in England that requires putting off the hat,
therefore it is not a transgression;
for which reason I desire I may have the benefit of an Englishman,
which is not denied to any felon here among us;
for I have to this day stood always faithful to the common wealth,
and have not forfeited any liberty,
but have hazarded my life and estate to procure freedom, which I am now deprived of.
Judge.
If you will not put in bond, which I think is very reasonable, take him away.
F.E. For my behaviour, if there be any here that can accuse me,
I would have you countrymen to speak, any of you;
if not let all the poor people in Wellingborough, and the towns thereabout,
and those in Northampton, whom I have employed for those 15 or 1 6 years, in carding,
spinning, dying, and weaving, declare what my behaviour has been towards them or others:
For, till I was cast into prison, I employed more poor people at work about wool,
than any one man in this country doth;
yet not withstanding what I have done and still do,
I may not have the benefit of the law, as all malefactors here have.
Judge.
Take him away.]

During their imprisonment their friends were not suffered to visit them,
but several who attempted it were taken up and sent out of town with a pass:
About six months after their last examination as above,
they were discharged by an order from O. Cromwell,
after having suffered a grievous imprisonment (the two first 15
months) without any just cause or legal process against them.

Thomas Stubbs was another who experienced the illegal severity
of the magistrates of this county about the same time;
being concerned to exhort the inhabitants of Daventry to repentance,
he was for this office of christian charity sent to prison by a Justice, of whom,
when Thomas required by what law he proceeded, he received for answer,
by the law that faith all Quakers must go to prison.
On this ill-founded committal he was detained in prison thirteen weeks,
till the sessions at which he was released, and then sent out of the county:
Returning soon after to a meeting at Ilham,
he was taken thence and by two Committed Justices committed to Bridewell as a vagrant,
where he was cruelly whipped, and endured much hardship,
being not suffered to purchase necessaries for his money.

These arbitrary proceedings and severity of the magistrates incited Edward
Burrough by letter to apply to the Protector to put a stop thereto,
wherein he reminded him of his vows in the day of his distress;
and that he suffered cruelty, oppression and tyranny to be practised in his name,
by unjust imprisonments,
and merciless persecutions of a peaceable and religious body of people;
that he was to be accountable to the great judge of all mankind
for the use he made of the power he was invested with.
It doth not appear that his plain-dealing either
drew any marks of resentment from the Protector,
or any interposition of his authority to put a stop to the persecution of his friends.

It is asserted that Cromwell`'s principles were in favour of religious liberty,
and that he allowed it in the fullest extent to all,
but the papists and prelalatists yet the Quakers (so called) may be justly
added to the number of those who were not allowed that liberty.
From what motive, in violation of his solemn professions,
confirmed by oath on his entrance upon the protectorate,
and probably in violation of the convictions of his own conscience he
suffered and connived at the severe persecution of this unoffending society,
is not easy perhaps to determine at this day.
Mosheim writes that "`He entertained uneasy apprehensions concerning them;
and in his first thoughts formed a resolution to suppress, their rising community;
but when he perceived that they treated with contempt both his promises and threatenings,
and were in effect too powerful, or too headstrong to yield to either,
he prudently abstained from force.`"

It doth not appear upon what authority this account is founded,
or from what source he drew his intelligence of Oliver`'s private thoughts;
but from any historical narratives, which have fallen in my way,
or the records of their sufferings kept amongst this people,
I recollect no instance of the Protector`'s either amusing them with promises,
or attempting to awe them by menaces;
neither that he himself openly disturbed them on
account of their religious opinions or practices:
yet those who acted under his authority did grievously persecute them,
and he gave little or no check to their persecution, although he had the power,
and was repeatedly and earnestly solicited to do it.
I do not imagine, however,
that the uneasy apprehensions he entertained of them
was the ruling motive of his conduct towards them.
They not only professed themselves to be followers of peace with all men,
but exemplified their pacific principles, by their patience under suffering,
and unresisting submission to all the trying injuries they were exposed to,
never betraying the least symptom of a disposition to revenge their wrongs,
various and aggravated as they were;
so that I imagine that Oliver`'s sagacity and intelligence would
not be long in discovering he had nothing to fear from them.

But there was another body of men, whom he might be fearful of offending,
because they have proved able to shake the foundations of established governments,
much more his recently usurped dominion;
the supporting himself in which at this time was with him the predominant consideration:
I mean the clergy or popular preachers of the age,
a set of men who had shewn themselves capable of
exciting civil tumults to a disastrous degree,
and who, the greater part of them,
seem to have imbibed a spirit of hatred and bitter animosity against the Quakers,
for their honest and undisguised testimonies against their hypocrisy,
self-interestedness and lust of power,
no less than their bringing over many of their hearers,
and maintaining it unlawful to take tithes, or preach for hire.
These men being the principal agents in promoting the persecution in which they suffered,
I am ready to conjecture, that Oliver,
who made every religious and moral consideration
subordinate to that of retaining his sovereignty,
might consider the Quakers as too contemptible,
or too pacific a body to fear any danger from, even under the greatest provocations;
and that therefore he might safely connive at the oppression
and persecution exercised by these men and their adherents,
whereby he would keep them in temper, and attach them to his interest,
to the strengthening of his authority with the them,
he might be fearful to add a powerful and dangerous party to the number of his adversaries,
who were already too many.

For not only amongst the royalists and presbyterians,
but even amongst the independents themselves, he had created himself many enemies;
and these last perhaps the most virulent as being agitated
under a keener sense of their more recent disappointment,
in the abolition of their favourite republic, and the beholding of that power,
which they expected to share amongst them, wrested out of their hands,
and usurped by one man; who was therefore odious to them as the most perfidious of men,
and the great betrayer of the public cause.

Amongst the malcontents John Lilburn was one or the foremost to oppose his usurpation.
This man, originally a book-binder in London,
ranked early with the assertors of civil and religious liberty on the broadest base.
In his efforts in this cause, the ardency of his zeal,
and the inflexibility of his temper,
rendered him obnoxious to punishment or prosecution under
the different successive governments of this age.
First, in the year 1637 he suffered under the petulant tyrants of archbishop Laud,
being accused before the Star-chamber for publishing and dispersing seditious pamphlets,
when refusing to take an oath to answer to interrogatories,
as being a violation of the privilege of Englishmen, secured by magna charta,
whereby no man was bound to accuse himself; for this contempt, as it was termed,
he was condemned to be whipped, pilloried and imprisoned.
During the execution of this sentence he harangued the populace,
and declaimed against the tyranny of the bishops.
The Star-chamber, sitting at this time, ordered him to be gagged,
and added to his former punishment, the lying in irons,
and confinement in that part of the Fleet where the basest
and meanest sort of prisoners are used to be put.
In the year 1640 he recovered his liberty, by order of the long parliament,
and was decreed damages against his judges.
On the breaking out of the war between the King and Parliament,
his principles led him to side with the latter,
and his merit with this party raised him to the rank of lieutenant-colonel,
in which capacity he defeated the Earl of Derby on his march through
Lancashire to join Charles II. in his invasion of England.
In the year 1649, after the civil war was terminated,
and the independent members of the long parliament
had fixed themselves in the seat of government,
Lilburn apprehending, that finding their ambition fully gratified,
and tasting the sweets of unlimited and undivided authority,
their sole aim was now the establishing and perpetuating
of the supreme power in their own hands,
forgetting or overlooking the more generous alleged purposes,
for which the war had been undertaken and carried on,
to the over turning of the monarchy,
viz. the redressing of the grievances of the subjects,
and establishing their liberties and immunities on a permanent foundation (and the sequel
seemed to prove his apprehensions not entirely groundless) published a pamphlet,
entitled England`'s Second Chains.
This liberty was so ill relished,
that he was thrown into prison as a promoter of sedition and discord in the commonwealth,
and illegally prosecuted; and although a petition was presented to the parliament,
signed by a vast number of subscribers,
to stop the prosecution they had commenced against him,
and seconded by a female petition of the same tendency; yet,
disregarding these solicitations, the prosecution was carried on,
and Lilburn was brought to a trial for high treason after about seven months imprisonment,
on which occasion his intrepid spirit did not desert him;
with invincible constancy he maintained his sentiments, and pleaded his cause; so that,
notwithstanding powerful exertions to prevail on the jury to bring him in guilty,
he was acquitted, and after some time regained his liberty.
Again, when Oliver Cromwell had usurped the supremacy,
this zealous Prosecuted partisan of liberty rose against his usurpation,
Oliver both by word and writing exerted himself in representing
to the public the treachery and tyranny of his proceedings,
whereby Cromwell, being both provoked and alarmed,
in the apprehension of the danger of his credit and
authority being undermined by such bold attacks,
likewise ordered him into custody, and to be impeached of high treason.
At his trial he maintained the like intrepidity as before,
asserting in answer to the charge against him,
"`That what he had done was not only no high treason,
but the government was such that no high treason could be committed against it,
and that it was the duty of all good Englishmen to oppose it, as a tyrannical usurpation;
that he might have attained great preferment if he
could have brought himself to acquiesce in it;
but believing this to be unlawful, his life was to be a sacrifice for his honesty,
but he was exempt from fear, because he was asserting a good cause.`"
After this defence the jury acquitted him,
notwithstanding the endeavours of the judges to the contrary.
Being acquitted by the jury, his immediate release was his legal right, but Cromwell,
in defence of his own safety, thought it necessary to transgress the boundaries of law,
and kept him in prison, through the remainder of his government, during which time,
being moved from one prison to another, he was at length confined in Dover Castle.
His long confinement had changed the temper of his mind,
from an active and bustling to a serious and contemplative cast,
and preventing him from conversing in the busy scenes of life,
furnished him with opportunity to be more conversant with himself in religious recollection:
In his confinement here, becoming acquainted with Luke Howard, an inhabitant of Dover,
and one of the people called Quakers, before mentioned,
and conversing with him on religious subjects,
Luke gave him such convincing reasons for his profession, as gained Lilburn`'s assent,
and brought him over to his sentiments and profession, in part at least,
as appears by the letters that passed between him and his wife at this time,
the following abstracts whereof will convey an idea of the present temper of their minds,
whereby it may be perceived that adversity had proved
a school of profitable instruction to them both.
His wife having visited him in prison,
soon after wrote him the following laconic admonition: "`My dear, retain a sober, patient spirit,
which I am confident thou shalt see shall be of more force
to recover thee than all thy keen metal hath been.
I hope God is doing a work on thee and me too,
that shall make us study ourselves more than we have done.`"
To which he returned in answer, after other passages:

[.embedded-content-document.letter]
--

I am deeply entered into my part.--The mighty power of God enable thee to get in too,
and also go through thine, and effectually to go cheerfully and willingly along,
hand in hand with me.--I am sorry thou art so straitly put to it for money;
but to live upon God in faith in the depth of straits,
is the lively condition of a christian.--I can now favourily
live on bread and cheese and small-beer alone,
for saving of money.
And as for my liberty, about which thou so weariest and spendest thyself,
I can say in my present temper of spirit--It is good being here;
for here in Dover Castle, through the lovingkindness of God, I have met with more clear,
plain and evident knowledge of him,
than ever I had in all my lifetime.--And now submissively and heartily I can say,
the will of my heavenly Father be done in me, by me, and for me.

[.signed-section-signature]
John Lilburn.

[.signed-section-context-close]
Dover Castle, 4th 10th month 1655.

--

After he had lain some time in Dover Castle, Cromwell seemed inclined to release him,
on condition of signing an engagement not to draw a sword against his Government;
but being not yet so far convinced, as to believe the use of the sword unlawful,
nor perfectly approving of that point of self-denial,
he refuted to purchase his liberty on this condition.
However, persevering in fidelity to that knowledge of duty he had already attained to,
he became in process of time,
so fully convinced of the unlawfulness of war under the Gospel dispensation,
as to make the following publication of his sentiments:

[.embedded-content-document.paper]
--

That being brought to believe in his inward teacher,
which shall never more be removed into a corner, by the teachings thereof,
he was taught to die to sin, and to the very occasion and real grounds of outward wars,
and was therefore firmly persuaded that he should
never thereafter use the temporal sword,
nor join with them that did.

[.signed-section-context-close]
This paper was dated from Dover Castle, the 4th of 3rd month 1655.

--

He was continued a prisoner here till Cromwell`'s death,
and then being liberated from his long confinement,
he continued steadfast in his profession of those doctrines he had received as truth,
and died in London, Anno 1660.

In this year, Anne Downer, of London, being one of the earliest sufferers in that city,
a maiden of about thirty years of age,
and the first person of her sex who preached publicly there,
for some expressions against the preacher who officiated in the Steeple-house at Stepney,
was committed to the house of correction, and detained there ten weeks,
and because she refused to work was beaten with a rope`'s end.
She was a woman of excellent endowments,
and became exceeding serviceable in religious society, fitly qualified to exhort others,
and remarkably exemplary in her christian care over persons in sickness and poverty.

Miles Halhead, and Thomas Salthouse,
travelling from their respective habitations in Lancashire and Westmoreland,
with intention to visit their friends imprisoned in Cornwall,
in their passage through Devonshire were apprehended,
and after 14 days close confinement at Exeter, were by warrant from Colonel Coplestone,
the high Sheriff, ordered to be passed as vagrants from thence to their own dwellings:
an illegal procedure against men of substance and reputation, who travelled on horseback,
lodged at the best inns, and paid punctually for their entertainment.
On the way between Taunton and Bridgewater,
the officer who had them in charge was suddenly seized with a kind of apoplectic fit,
which disabled him from proceeding farther.
They returned to Taunton and informed a justice of peace of the casualty.
He thereupon suspended the further execution of the warrant, and set them at liberty,
wishing the Lord might be with them.

They went to Bristol and returned to Plymouth, where they had several meetings;
one of which was in the garden of John Harris,
his house being too little to contain the numerous auditory:
their plain and powerful ministry reached the consciences of many,
and was generally well accepted.
At the close of the meeting, one George Brooks, a priest,
chaplain of the Nightingale frigate,^
footnote:[This was proved by sundry certificates from Captains of Ships, etc., etc.
See Sewel, p, 118.]
but a man of a profligate character spoke to the
people in commendation of what had been delivered,
declaring it to be the eternal truth.
Thomas Salthouse, a man of deep discerning, justly suspecting the chaplain`'s sincerity,
remarked that he had spoken many good words; but withal asked him,
Whether his life corresponded with his expressions?
For that it was he who hath the witness in himself
that can set to his seal that God is true.
The priest being irritated at this reproof, and meditating revenge,
two days after procured a warrant from the Mayor,
by which they were taken from a meeting at the house of Robert Cary,
and imprisoned in Guildhall: Next day they were brought before the mayor,
magistrates and common council,
who ordered the doors to be shut during their examination, which lasted three hours;
after which they remained in custody several days, while the magistrates,
who had determined to send them to the county jail,
were deliberating how to form a plausible pretence for their commitment.
At first they charged them with denying the Trinity,
of which they fully cleared themselves.
Then they tendered them the oath of abjuration,
but the proclamation enforcing that oath giving no
authority to imprison any for their refusal,
they omitted proceeding thereupon.
At length they made out their mittimus, grounded on reasons either false or frivolous,
or absurd.

[.numbered]
1+++.+++ As disturbers of the public peace.
+++[+++A false charge.]

[.numbered]
2+++.+++ For divers other misdemeanors.
+++[+++A general charge unsupported by any matter of fact.]

[.numbered]
3+++.+++ For acting against a,
late proclamation prohibiting the disturbing of ministers
and other Christians in their assemblies.
+++[+++It is observe able that the meeting was of their appointment,
and therefore the disturbance, if any, was made by their prosecutor, and not by them.]

[.numbered]
4+++.+++ For acting against an ordinance of the Lord Protector and his council,
lately made against duels, challenges, and provocations thereunto.
+++[+++The absurdity of this charge appears plainly at first view.]

[.numbered]
5+++.+++ For refusing to give sufficient security for their
appearance at the next general sessions.
+++[+++This appears to be a direct falsehood, for two of their friends,
Robert Cary and Arthur Cotton, had given security, and entered into recognizance,
for their appearance, but on further deliberation it was vacated,
under pretence it would not be according to law, and they were sent to prison next day.
A certificate whereof was signed by those two and nine others.
Sewel, p. 116.]

After six weeks imprisonment in Exeter jail,
they were indicted at the sessions for a breach of the ordinance against duels,
and particularly for divers disgraceful words and gestures against George Brooks, clerk,
etc.

Witnesses were provided to prove the indictment, one of whom on his way was heard to say,
"`I am going to Exeter to swear against the Quakers,
and if swearing will do it I`'ll make them suffer soundly:`" But
the court did not choose to bring the matter to a fair hearing:
For though they pleaded, and desired a trial, their plea was refused,
and no trial granted.
But the oath of abjuration was tendered them in court, which, it is well known,
they could not take, and only tendered as a pretext to prolong their imprisonment.
In fine, they were fined 5£. a piece, and committed to Bridewell till payment,
and finding sureties for their good behaviour.

Pursuant to this sentence they were removed from the county jail to Bridewell,
and a guard of soldiers placed over them, with strict orders,
signed by one Captain Joyce, to detain all that should come to visit them,
especially if they suspected them to be Quakers.
They lay on the ground in a close dark room many days,
and were continued near seven months under such cruel usage,
as had the aspect of a design to destroy them:
for their persecutors administered not anything for their support,
but exerted their endeavours to prevent others from
bringing them the common necessaries of life,
and imprisoned several of those who came to see and relieve them.
But this extreme malice of their enemies rendered
the christian charity of their friends the more distinguished,
who frequently hazarded the loss of their own lives to supply their wants.

In the same year Margaret Kellam, an innocent woman, of a tender constitution,
good education and considerable property, was treated with great cruelty and ignominy,
without any just occasion administered on her part, as is manifest from the sequel.
On the 19th of December she went to the house of Peter Ceely, mayor of Plimouth,
and told him she had a word from the Lord to him: he bid her come in, heard her,
and confessed that what she said -was very good and true;
yet was so displeased with this truth, that he sent her to prison,
detained her there about a week,
when at the intercession of her friends she had liberty to return home.
But on the 4th of the next month, about four o`'clock in the morning,
a constable and sergeant came to her chamber, broke open the door,
and refusing to shew their warrant, took her away by violence, tied a rope about her,
bound her arms behind her, threw her across a horse, and tied her feet under its belly,
and in this inhuman manner carried her ten miles.
Then loosening the cords, they told her they had a warrant to carry her to Exeter jail.
There she lay till the quarter sessions,
when endeavours were used to get an indictment drawn up against her;
but the clerk and his coadjutors, although desirous to do it,
could find nothing in her conduct whereon to ground an indictment,
and so she was released by the sheriff after an imprisonment of about two months.
