== Chapter VI.

[.chapter-synopsis]
* Richard Hubberthorn, George Whitehead and James Lancaster imprisoned
* The two latter discharged
* George Whitehead violently assaulted by the Populace, and rescued by a Trooper
* Richard Clayton for fixing a Paper on the Steeple-house Door at Bures in Suffolk, is whipped and sent away with a Pass
* George Whitehead, John Harwood and George Rose committed to Bury Jail
* Indicted at the Assizes and fined
* Hardly used in Prison
* Released by order of Oliver Cromwell
* Account of James Parnell
* He travels through Huntingdonshire and Cambridgeshire into Essex
* His Sufferings
* His Trial
* The Judge prejudiced against him
* Used with great Cruelty in Prison
* Dies by his hard Treatment there

Richard Hubberthorn coming into Norfolk, at Wymondham,
feeling a Christian concern to exhort the congregation in the steeple-house there,
after the priest had ended his sermon, was committed to Bridewell,
and from thence the next day to Norwich castle, where Norfolk,
he was lodged in a very incommodious prison, being a poor hole in a cross wall,
and there detained till the time of the sessions.
On his appearance there, the justices waving the original cause of his commitment,
took occasion from his appearing before them with
his hat on to charge him with a contempt of authority,
and under that pretence recommitted him to prison, where he lay a long time after.

George Whitehead also,
believing a duty required of him to go to that called
Peter`'s church in the city of Norwich,
to bear such testimony as the Lord might give him, in endeavouring to discharge his duty,
was haled out and much hurt, and from thence hurried to the Guildhall before the mayor,
who examined him concerning water baptism and some other things,
in hopes to get some answer from him which might furnish a more
plausible pretext for committing him to prison than the occasion
he had given by his Christian exhortation as above;
but getting no advantage against him from his answers,
he committed him to prison notwithstanding.
James Lancaster, for calling the people to repentance in the market at Norwich,
with one Christopher Atkinson, had been committed to the same prison a short time before,
where not complying with the jailer`'s extravagant demands,
they lay in their clothes on the floor for eight weeks in the cold winter,
which was a great hardship, especially on George Whitehead,
a youth of eighteen years of age, who had been tenderly educated by his parents.

At the ensuing sessions for that city,
George Whitehead and James Lancaster were discharged by the court,
but still detained by the jailer under pretence of fees several weeks longer,
till the jailer died, and his widow, of a more merciful disposition,
set them at liberty.

Atkinson being of a rougher temper,
for uttering some bitter expressions against his opposers,
was detained longer in prison by actions laid against him by a priest and an attorney,
and by giving way to heat and passion he fell from the tenderness of his first convincement,
and ministered occasion to the adversaries to speak reproachfully.

Not long after this Thomas Symonds,
for asking a priest a serious question respecting his doctrine,
was committed to Norwich castle;
and George Whitehead going to visit him and another of his friends under confinement,
was by order of the mayor detained there about three weeks,
without any cause but the arbitrary will of the magistrate.
These repeated instances of despotic rule in men
professing a sacred regard to religious liberty,
and under colour of procuring which,
they had not hesitated to plunge the nation into all the miseries of a civil war,
have furnished the opposite party, not without much plausibility,
with occasion to bring under suspicion the sincerity of their pretensions:
That under the pretext of redressing grievances,
they meant only to wrest the sceptre out of the hand that bore it,
to wield it with equal or superior severity over those,
who were not of their own sentiments in their religious as well as political creed.

Amongst numbers who were convinced in those parts by these able ministers of the gospel,
Richard Hubberthorn and George Whitehead, was Captain John Laurence,
(and most of his family) who having been a member of some meeting of consequence,
of an independent congregation at Norwich,
was summoned to their meeting in the leaving parish church, called George`'s of Tombland,
to answer their charge against him for leaving their communion;
and he being disposed to appear was accompanied by George Whitehead.
The charge against him was in effect, His forsaking their church or communion;
his entertaining strangers or persons dangerous; and holding dangerous doctrines.
To the first he answered,
That in his forsaking their communion he had followed the apostle`'s advice, Tim.
2:3. "`Having the form of godliness, but denying the power, from such turn away.`"

After John Laurence had given his reason for leaving them,
they proceeded to excommunicate him;
and a great concourse of people being gathered upon the occasion,
George Whitehead felt a lively concern animating
his mind to deliver a brief exhortation among them;
but had scarce stood up, when he was pulled down, and held down by force,
till some of their church haled and pushed him out of the steeple-house,
and exposed him to a rude multitude, prepared for violence and mischief,
from whom he received much gross abuse, being dragged along the street,
frequently thrown down on the stones, and thereby grievously hurt and bruised.
Thus dragged out of the city, he came near a great house belonging to a lady Hubbard,
her chaplain coming out to see the occasion of the
tumult entered in to discourse with George Whitehead;
and during their discourse the mob, who seemed intent upon further mischief,
stood round them in a ring to hear what passed.
In the meantime a trooper coming up, seeing how he was beset,
kindly offered him his assistance, and rescued him from their hands:
for laying his hand on his sword, and commanding the mob to give way,
he conducted him safely to his quarters at Thomas Symonds`'s house in the city.
This trooper, whose name was Robert Turner, was afterwards convinced,
and joined the society of the people called Quakers, residing at Lynn in Norfolk.

Richard Hubberthorn being still detained a prisoner in Norwich castle,
George Whitehead continued moving about, and attending meetings in Norfolk and Suffolk,
sometimes alone, sometimes accompanied by Richard Clayton and others.
After Richard Hubberthorn was set at liberty,
they joined again as companions in gospel fellowship,
and had several large and comfortable meetings together.
In several of these meetings they were interrupted by opposition
from some of the preachers of other societies;
and by moderate enquiries for the clearer understanding of their doctrine from others;
and were endued with wisdom and recollection of scriptures
to answer the objections of the former,
and satisfy the enquiries of the latter; whereby two of them, Richard Townsend,
and John Burch, a preacher among the baptists,
were so far affected by their instructive remarks in the explanation of their doctrines,
that after a season of serious consideration they were both convinced of the truth thereof,
joined in society with friends,
and in process of time became serviceable members and ministers among them.

On the 30th of the month called July 1655, George Whitehead,
John Harwood and Richard Clayton passing through Buers, a town in Suffolk,
the said Richard Clayton did fix a papers on the door of the Steeple-house there,
being as follows, viz.^
footnote:[George Whitehead`'s [.book-title]#Journal#, p. 60, 62]

[.embedded-content-document.paper]
--

If you do set up such ministers as seek for their gain from their quarter,
you set up such as the prophet Isaiah disapproves of,
Isa. 56:11 And you that do set up such as bear rule by their means,
you set up such as the prophet Jeremiah and this Lord disapprove, Jer.
4+++.+++ And you that set up such as seek for wool and make a prey upon the people,
you set up such as the prophet Ezekiel disapproves of,
Ez. 34. And you that set up hirelings, you set up such as Micah disapproves of,
Micah 3. And you that set up such as are called of men master,
stand praying in the synagogues, have the chiefest places in the assemblies,
you set up such as Christ disapproves.
Mat. 6 and 23. With sundry other quotations from scripture.

--

This paper being stuck up,^
footnote:[George Whitehead`'s [.book-title]#Journal#, p. 67, 68]
some people came together to read it,
to whom George Whitehead and John Harwood gave a Christian
exhortation to live in the fear of the Lord,
and to turn from the evil of their ways, etc.
While they were speaking a constable came and carried them before Herbert Pelham,
an Essex justice, then at Buers, who examined them, though officiously,
being out of his precinct, and then sent them, together with Clayton,
to Thomas Waldgrave, a justice at Small-bridge, who having asked them a few Questions,
left them in the custody of the constable till Pelham and he had laid their heads together.
The issue of their consultation was, that Richard Clayton, by Waldgrave`'s order,
was whipped publicly as a vagabond, and sent out of the town the same day with a pass;
a proceeding not justifiable by law, Clayton being a man of reputation,
and known to have a competent estate.
John Harwood was the next day sent to Edmundsbury jail,
and George Whitehead the day following;
and a few weeks after George Rose was sent to the same prison by justice
Gurdon with a mittimus assigning no breach of law nor any matter of fact,
nor indeed had he given any just occasion of offence,
except his asking a question of the priest of Stoke after his sermon,
at which the priest was displeased, and the justice to avenge the parson`'s quarrel,
took this extrajudicial course to send the poor man to prison.

At the next quarter sessions Whitehead, Harwood and George Rose,
were indicted as common disturbers of the magistrates and ministers.
The justices who committed them were their sole accusers, and incensed against them;
and an ignorant jury being empaneled,
by direction of the court presently found them guilty;
where upon they were fined twenty nobles each, and recommitted to prison till payment.
George Fox of Chasefield, commonly called George Fox the younger,
to distinguish him from the other of that name, being present at the trial,
and observing the prejudice expressed by justice Gurdon against the prisoners,
said to him, as he was coming out of the sessions house,
"`Repent of thy unjust actions this day,
for otherwise thou canst not escape the just judgment of God.`"
Upon this Gurdon laid hold on him, and had him before the bench,
who demanded sureties till the next sessions, which he not complying with,
they sent him to prison with the others.^
footnote:[George Whitehead`'s [.book-title]#Journal# p. 69, 70]

On the 22nd of November Henry Marshal,
for speaking a few words to a priest after his sermon was ended, was,
by order of justice Gurdon, first set in the stocks, and then sent to Edmundsbury jail.
At the next sessions he was fined twenty marks, and remanded to prison.

At the same sessions George Fox was called, but no indictment laid against him;
yet the court sent him back to prison.

The usage of these five prisoners was very hard:
Because they would not gratify the jailer`'s avarice
in paying him the price he demanded for their lodging,
but demanded a free prison, not knowing how long their imprisonment might continue,
he turned them down to the common ward among the felons,
in a low dungeon with a damp earthen floor, where they lay upon ryestraw;
because they declined advancing his gains by buying his strong liquors,
against the use of which they had a conscientious scruple;
because they bore their testimony against the drunkenness, swearing,
and other disorders in his house; and because they reproved him for his hypocrisy, who,
while he suffered, and for his gain promoted these disorders,
made high pretensions to religion;
and on the day called Sunday would summon his prisoners together,
pretend to give them instruction, and exercise a kind of devotion among them:
for which in consistency of conduct, and fruits so opposite to religion,
being charged with hypocrisy, his daughter exclaimed,
"`What! do you call my father a hypocrite, who hath been a saint these forty years!`"^
footnote:[George Whitehead`'s [.book-title]#Journal# p. 80-81]
But it was such saintship as his which brought too
much of the religion of this age into disrepute.
For these causes he was exceedingly embittered against them,
so as often to strike them on the face, and grievously abuse them various ways,
both by words and blows.
His servants also, and some of the drunken prisoners, encouraged by his example,
were often exceedingly abusive to them, by their expressions and mischievous actions;
the prisoners frequently took away their food and other necessaries,
alledging the jailer gave them leave so to do;
and one more desperately wicked than the rest frequently kicked and smote them,
and threatened in a drunken fit to kill them, saying,
if he killed them he should not be hanged for it.

It was, as hath been remarked, because they would not take rooms from him at his price,
but demanded a free prison, that they were thrust into the common ward among felons,
and grossly abused there by the jailer`'s connivance, if not instigation:
Yet even here they could not obtain a free prison;
for after they had been in prison about thirty weeks,
he demanded arrears of dues for fourteen pence a week from each of them, which they,
who were obliged to buy even the straw they lay upon,
remonstrating against as an unreasonable demand,
he ordered the turnkey to take away their bed-clothes and boxes, which was done;
and he threatened to take their coats from off their backs.
Their bed-clothes being taken away,
they were obliged to lie in part of their body-clothes
upon straw for the space of twenty-four weeks.

When a woman friend brought them some necessaries of linen,
etc. to replace what had been taken from them, the jailer caused them to be seized.
When provisions were brought them,
they were examined before they would be suffered to be delivered.
One time being enraged at their constant testimony against the drunkenness, swearing,
and other gross disorders abounding in the jail through his self-interested connivance,
the jailer caused them to be put down, into a dark dismal dungeon,
in which was a dangerous deep pit.
When their friends came to visit them, they would not be permitted;
and if they endeavoured to speak to them at the window or door of the jail,
they had frequently water thrown upon them to drive them away.

At length an account of their hard usage was sent to some of their friends in London,
upon which they made application to the Protector and his deputy Fleetwood,
representing the inhuman treatment they had received:
And an order was sent down to have the matters of
fact complained of examined into by four justices;
who hearing their complaints in the jailer`'s presence, which he could not gainsay,
some of them blamed the jailer, and charged him not to suffer his servants to abuse them,
for if they did they would send them to Ipswich jail.

After this examination they met with better treatment: the jailer,
although exasperated at their exposing of his cruelty, was restrained, through fear,
from exercising himself,
or suffering his servants or prisoners to exercise cruel abuse toward them,
as hitherto he had done; and therefore afterwards, when provoked,
contented himself with calling them ill names.
But one of the justices, named John Clark, being the jailer`'s neighbour,
and a fellow member of the same community, in favour of his reputation,
and that of his religious profession,
seemed to discover a manifest partiality to his side,
endeavouring as much as he could to palliate or extenuate the jailer`'s misconduct;
so that from his behaviour through the whole examination,
they conceived little hope of a full and impartial
account`'s being returned to the protector by them;
or that their release would follow the justice`'s representation,
which it did not for some time.
But the report of their barbarous treatment, and of the hardships which they endured,
spreading abroad, again reached their friends in London,
which caused them to be more solicitously concerned for their relief,
and to redouble their efforts to effect it by repeated applications to Oliver Cromwell;
which being seconded by the private applications of Mary Sanders,
(afterwards Mary Stout) a waiting gentlewoman in Cromwell`'s family,
and one of the people called Quakers,
whose prudent and exemplary conduct had gained her a respectful esteem in that family;
their joined solicitations at last procured the following order for their release,
after an imprisonment from twelve to fifteen months.^
footnote:[George Whitehead`'s [.book-title]#Journal#, p. 93, 94.]

[.embedded-content-document.legal]
--

[.signed-section-context-open]
Thursday the 16th of October, at the Council at Whitehall.

Ordered, by his Highness the Lord Protector, and the Council,
that the Quakers imprisoned at Golchester in the county of Essex,
and Edmundsbury and Ipswich in the county of Suffolk,
be forthwith released and set at liberty.
And it is referred to Sir Francis Russill to take care that the same be done accordingly;
as also to consider how the fines set upon them, or any of them,
(if any) may with most convenience be taken off and discharged;
and likewise to take order,
that upon their being set at liberty they be forthwith sent to their own homes.

[.signed-section-signature]
W+++.+++ Jessop, Clerk of the Council.

--

Pursuant to this order Sir Francis Russill, who was a moderate man,
and averse to persecution, caused them immediately to be set at full liberty,
without any restriction as to returning home,
leaving them at liberty to travel whithersoever the persuasion
of duty or inclination might prompt them.

George Whitehead adds that in all their hard personal sufferings they were favoured
with peace and consolation in the inward sense of divine support,
bearing up their spirits and strengthening their faith,
and preserving their bodily health; under the feeling whereof, in their afflictions,
they were frequently made to sing praises to his holy name, who thus preserved them,
to the astonishment of their fellow prisoners.

In the beginning of this year James Parnel,
who hath been already mentioned to have been convinced in a conference with George Fox,
during his imprisonment in the dungeon at Carlisle, travelled southward also,
labouring in the ministry of the gospel,
and the propagation of those doctrines he received as truth;
for which service he was eminently qualified,
although but a youth of about eighteen years of age.
He was born at Retford in Nottinghamshire, and had the advantage of a good education,
in the schools of literature.
He was convinced of the truth of the principles of the people called Quakers,
and joined them in society as early as the sixteenth year of his age,
and for that reason was despised and rejected by his relations.
Being low of stature, his bodily presence appeared contemptible,
which increased the admiration of his excellent mental qualities,
in those who could view him through the medium of cool judgment,
divested of envy and prejudice; for in the person of the apparently despicable lad,
were concealed wisdom and understanding of age and experience,
the affecting preacher and able disputant;
being always ready to give a reason of the hope that was in him,
and maintained the doctrines which he preached against their opposers.
In qualifications for the ministry he seemed behind few of his fellow-labourers;
in suffering for his testimony he experienced even greater severity and inhumanity.

He took his journey through Huntingdonshire and the Isle of Ely into Cambridgeshire,
preaching the gospel and disputing with opposers.
At Cambridge,
for publishing a declaration against corrupt ministers and corrupt magistrates,
he was imprisoned, and detained in prison over two sessions,
and afterwards turned out of the town as a vagabond.
He soon after returned, and disputed with the scholars of the university,
from whom he met with very rude and cruel treatment.
He thence prosecuted his journey into Essex (being the first called
a Quaker who preached the gospel in that county.) At Stebbing,
Felsted, Witham, Coggeshall and Halsted, and other places,
he preached with remarkable effect,
many by his ministry being convinced of the truth of his doctrine.
About the middle of summer he came to Colchester,
and on the first day of the week preached to a large number of people,
first at his lodging, then at the public place of worship;
next in a great meeting appointed on purpose.
After that he disputed with the town-lecturer and another priest in the French school,
all in one day;
in which labours the wisdom and patience of the true Christian manifestly appearing,
a considerable convincement was the fruit of his incessant labour.
Among the rest, Stephen Crisp, a man of good parts,
coming to discourse or dispute with him at his lodging,
and James appearing at first sight a mere boy, he viewed him with a contemptuous eye;
but upon entering into discourse with him, the awful frame of his spirit,
the weight and conciseness of his expressions fixed
so deep an impression on the mind of Stephen Crisp,
that he was effectually convinced,
and became himself an eminent publisher of the same doctrines.
James Parnel spent the rest of that week there in preaching,
exhorting and disputing to the convincement of many more;
while others were provoked to such a degree of rage,
as often to reward with blows his fervent zeal for their reformation.
In particular, as he was coming out of Nicholas`'s Steeple-house in that town,
he was met by a blind zealot, who struck him a violent blow with a great staff, saying,
"`Take that for Christ`'s sake;`" to whom this innocent sufferer meekly replied, "`Friend,
I do receive it for Jesus Christ`'s sake.`"
From thence he went to Coggeshall, where the independent professors had appointed a fast^
footnote:[It was no unusual thing for the professors
of those days to appoint public fasts,
and days of humiliation, frequently on no very important occasions;
but by their fruits they too often manifested their
humiliation to be but voluntary humility,
their praying will-worship, and their fasting the fast of the hypocrite.
The day of humiliation giving no interruption to the pursuit of their ambitious views;
their praying, performed in, an unforgiving spirit,
discovered in their vindictive disposition to all that opposed them, or thwarted.
their measures and their fasting to be seen of men:
on many other occasions as well as this proving them proper
objects of the severe reprehension of the prophet Isaiah,
delivered in the name of the Almighty to the Jews, "`Behold,
ye fast for strife and debate, and to smite with the fist of wickedness;
ye shall not fast as ye do this day, to make your voice to be heard on high.
Is it such a fast as I have chosen, a day for a man to afflict his soul?
Is it to bow down his head as a bulrush, and spread sackcloth and ashes under him?
Wilt thou call this a fast or an acceptable day to the Lord?
Is not this the fast that I have chosen: to loose the bands of wickedness,
to undo the heavy burdens, to let the oppressed go free, and that ye break, every yoke?`"
Isaiah 58:4-6.]
on purpose to pray against the spreading of error,
by which they meant the doctrine of the people called Quakers.
The priest who officiated on the occasion had prepared a sermon,
replete with the common-place invectives against that people,
the fruit of prejudice and prepossession.
James Parnel being present,
esteemed it his duty to vindicate himself and brethren against his opprobrious misrepresentations;
but stood still till the priest was coming out of the pulpit,
he then began with these words: "`This is the order of the true church,
that all may speak one by one; and if anything be revealed to him that stands by,
let the first hold his peace.`"
Then proceeding in his vindication of the Quakers
(so called) in reply to an assertion of the priest,
that they were on a sandy foundation, he signified,
"`I am ready to prove that the Quakers are not on a sandy foundation,
and that thou art a false prophet and a deceiver.`"
After some words had passed, a person standing by accused Parnel, that he owned no church.
He replied, that`'s false: Being asked, what church he owned, he answered,
the church in God.
Whereupon the priest said, that was nonsense:
Parnel taking a bible out of his pocket shewed it was a scriptural expression,
and charged the priest with blasphemy in calling it nonsense.
Upon his coming out of the Steeple-house he was apprehended
and brought before four justices.
After examination he was committed to Colchester Castle, where he was closely confined.
And at the time of the ensuing assizes at Chelmsford,
he was fastened to a chain with felons and murderers,
and so led above twenty miles through the country, remaining chained both day and night.

At his trial he was brought to the bar handcuffed,
but the people exclaiming against that barbarity,
at his next appearance his manacles were taken off.
The accusations brought against him were,
That in a riotous manner he did enter into the parish church of Great Coggeshall,
that he there did stand and told the minister he blasphemed and spoke falsely,
using many other reproachful words again him:
And that he could not give a good account where he was last settled,
or of his life or conversation, appearing to be an idle person.
He was also accused with contempt of the magistracy and ministry.
In his defence he alleged, That he entered the Steeple-house in no riotous manner;
but came thither perfectly quiet and alone without any disturbance:
That he had told the priest he blasphemed in saying
the church in God was nonsense he denied not;
but did not own himself a vagabond or idle person.
And he did not think it either criminal or indecent to call an unjust judge unrighteous,
a _persecutor_ persecutor, or a _deceiver_ deceiver.

The judge seemed to be predetermined against him, saying,
the Lord Protector had charged him to punish such persons
as should contemn either magistrates or ministers;
and in his charge to the jury he directed them to bring him in guilty.
After consultation, the jury found nothing to lay to his charge but a book or paper,
entitled The Fruits of a Fast, in which he had answered the justice`'s mittimus,
in purport agreeing with the accusation before recited;
and wherein he exposed the errors and inconsistency of the charge against him,
justified the peaceableness of his own demeanour,
and gave a solid account of the work of divine grace upon his soul,
and of the necessity laid upon him to testify against
the formalities and will-worship of human invention;
and this writing he had owned to be his.
But being indicted for a riot,
they found themselves under a difficulty to agree in their verdict.
The judge and the clerk strove to wrest some expressions
for their purpose from the foreman,
which the others did not consent to,
and himself as unwilling to answer their questions fully.
James Parnel was then made to withdraw, and being called in again,
the judge fined him 40£. for contempt of the magistracy and ministry,
and recommitted him to the same prison till he should pay the fine.
And the jailer was ordered not to admit any giddy-headed people,
by whom were meant his friends, to have access to him.

His persecutors,
who by their past treatment discovered a disposition of malicious cruelty,
having thus far carried their point in obtaining a sentence against him,
whereby they had him entirely in their power, lead us to open a scene,
which (when we contemplate the innocence,
meekness and patience of the sufferer on one hand,
and the persevering insatiable cruelty of his enemies on the other) is
sufficient to raise commiseration in every breast less obdurate than theirs.

The jailer, cruel in his own disposition, or inured to cruelty by his office,
punctually observed the orders he had received;
for he would suffer none to come near him but such as came to abuse him;
and the jailer`'s wife, equally cruel, not only ordered her servant to beat him,
but struck him with her own hands, swearing she would have his blood.
When his friends sent him victuals, she ordered the other prisoners to take them;
and when a bed was sent him, she refused him the use of it,
but obliged him to lodge on the hard damp stones.
After this he was put into a hole in the castle wall, not so wide as some baker`'s ovens,
which hole was a great height from the ground;
and the ladder placed for the purpose of going up to it, being several feet too short,
he was obliged to climb up and slide down by a rope to fetch his victuals and other necessaries;
for when his friends would have given him a cord and basket to draw up his food by,
the savage keeper would not suffer it.
By lying long in that damp hole his limbs grew greatly benumbed,
so that as he was once going up the ladder with his food in one hand,
attempting to catch the rope with the other,
he missed his aim and fell down on the stones,
whereby he received such contusions in his head and body that he was taken up for dead.
After this he was put into a hole underneath the other, there being two stories,
of such narrow vaulted holes in the wall.
In this, while the door was shut, was scarce any air,
there being no other aperture to admit it.
Thus bruised with his fall, and shut up where he could hardly breathe,
his life appeared in imminent danger; whereupon two of his friends,
William Talcot and Edward Grant, wealthy tradesmen of the town,
offered to be bound in sufficient bonds, and Thomas Shortland, another of his friends,
offered to lie in prison in his stead,
so that he might have liberty to go to William Talcot`'s
house till he might recover of his bruises;
but this was denied.
Nay, so great was the inhumanity and inexorable malice of his persecutors,
that when they were requested only to grant him the common privilege of the other prisoners,
liberty to walk sometimes in the yard, they would not grant it by any means.
It happened once that the door being open,
he went out of the hole into a narrow yard between two walls,
at which the brutal keeper was so enraged,
that he locked up the door and shut him out in the yard all night,
in the extremity of winter.
His tender constitution, unable to support such severe shocks,
sunk under the multiplied hardships of his unmerited imprisonment,
and after ten or eleven months he fell sick and died.
Two of his friends, Thomas Shortland and Ann Langley, were present at his departure.
When death appeared, he said, "`Here I die innocently;`" and a little after,
turning his head to Thomas, "`This death I must die, Thomas, I have seen great things,
don`'t hold me, but let me go.`"
He had repeatedly said one hours sleep would cure him of all.
His last audible words were,
"`Now I go;`" and then stretched himself out and breathed his last.
Though he finished his course in his youth, dying about the age of nineteen,
he had approved himself a strong man in Christ,
and having an eye to the eternal recompense of reward,
was preserved in faithfulness to the end, through manifold sufferings,
with remarkable innocence, patience and magnanimity.
The mere consideration of the youth of real offenders hath not uncommonly excited commiseration,
even towards such as have been guilty of flagrant enormities,
and procured a mitigation of their punishment or pardon of their crimes.
But the relentless obduracy of his persecutors seems to have been
proof against every incentive to sensations of compassion or humanity;
no regard to the tenderness of his youth, to the innocence of his demeanour;
to the solicitations of his friends, or to the danger of his dying under their hands,
could prevail upon them to relax of their rigorous treatment in the least degree.
And instead of repenting of their cruelty, the apparent cause of his death,
they seemed to continue it even beyond the grave; for they raised a slanderous report,
that he was the occasion of his own death, by willfully refraining from food, which,
whether it originated in the remains of that malicious disposition,
the effect of which he so severely felt,
or from conviction of guilt to palliate the infamy of their unmerciful usage,
was proved absolutely untrue by the testimony of credible witnesses,
who were frequently with him during his sickness;
and to whom that groundless calumny was a clear indication of the
deep rooted malice or criminal policy that invented it.
