== Chapter VIII.

[.chapter-synopsis]
* Imprisonment of G. Fox, Edward Pyott and William Salt in Launceston Jail
* Their Trial before Judge Glyn
* P. Ceely accuseth G. Fox of Treason
* Who refutes the Accusation
* They are fined and recommitted to Prison in Doomsdale
* The suffices at the Sessions at Bodmin order the Dungeon to be cleansed
* A Friend offers himself to lie in Prison in G. Fox`'s stead
* Thomas Lower convinced
* The Prisoners discharged by an Order from Major General Desborrow
* The Imprisonment of these Friends conducive to spread their Principles

A short while before the beginning of the year 1656,
G+++.+++ Fox from London travelled westward.
At Pool, William Baily, a Baptist teacher was (with others) convinced by his ministry,
and entered into society with the people called Quakers,
among whom he became afterwards an eminent minister.
G+++.+++ Fox continued his journey through Devonshire into Cornwall to Market Jew,
being accompanied by William Salt of London and Edward Pyott of Bristol,
where he wrote a paper containing an exhortation to fear God,
and learn of Christ the light.

This paper coming to the hands of Peter Ceely, a major in the army,
and a justice of the peace, when G. Fox and his companions came to Ives,
the place of Ceely`'s residence, while George was taking a walk by the seaside,
his w. salt two companions were taken into custody, and brought before the said Ceely,
to whose house George soon followed, where the abovementioned paper being produced,
he was asked whether he would own it, and he said, yes.
Then he tendered him the oath of abjuration;
upon which he drew from his pocket the answer to said oath,
which had been given to the Protector;
they were all three nevertheless sent to prison under
a guard of horse with the following mittimus:

[.embedded-content-document.legal]
--

Peter Ceely, one of the justices of the peace of this county,
to the keeper of his highness`'s jail at Launceston, or his lawful deputy in that behalf,

[.salutation]
Greeting.

I send you herewithal, by the bearer hereof, the bodies of Edward Pyott of Bristol,
and George Fox of Drayton and Clea in Leicestershire, and William Salt of London,
which they pretend to be the places of their habitations,
who go under the notion of Quakers, and acknowledge themselves, to be such,
who have spread several papers tending to the disturbance of the public peace,
and cannot render any lawful account of coming into these parts,
being persons altogether unknown,
and having no pass for their travelling up and down the country,
and refusing to give sureties for their good behaviour,
according to the law in that behalf provided, and refuse to take the oath of abjuration, etc.
These are therefore, in the name of his highness the Lord Protector,
to will and command you, that when the bodies of the said Edward Pyott,
George Fox and William Salt, shall be unto you brought, you them receive,
and in his Highness`'s prison aforesaid you safely keep them,
until by due course of law they shall be delivered.
Hereof fail not, as you will answer the contrary at your peril.

Given under my hand and seal at Saint Ives the eighteenth day of January, 1655.

[.signed-section-signature]
P+++.+++ Ceely.

--

By this mittimus it is evident on what vague pretences
the Quakers (so called) were committed to prison;
for such frivolous reasons as it is grounded upon might be urged
against any man almost travelling where he is not known,
even men of property and repute, such as G. Fox`'s present companions were.
Their guard was a company of unthinking and unfeeling mortals,
by some of whom they were but rudely treated, and particularly by their captain,
whose name was Keat.
By these men they were guarded to Launceston,
and there delivered to the custody of the keeper of the common jail,
who demanded of them seven millings a week for their horses,
and the same for their own diet each.
Being the first of this people seen in this corner of the nation,
they not only excited wonder and curiosity in the people, who were, many of them,
of a dark and insensible cast;
but by the novelty and simplicity of their manner and address,
they raised their animosity and anger to a great degree.
When they saw them address every single man of every degree as such,
with the plain appellation of thou and thee,
when they saw them decline the compliment of the hat and knee to the great,
no less than the mean,
there were some so envious or so ignorant as to expect no less
than that at the assizes they would be condemned to death,
if they declined these marks of honour to the bench;
yet there were many others of a more amicable disposition,
who from different parts of the country came to visit and discourse with them;
with many of whom their religious conferences had that good effect,
that they were convinced of the truth of the doctrine held forth by them.

After nine weeks confinement the assizes came on,
at which they were brought to their trial before judge Glyn a Welchman,
at that time chief justice of England.
They were guarded to the court by a band of soldiers and the sheriff`'s men,
and so great was the curiosity raised in the people to see this new kind of prisoners,
that it was with great difficulty they could make their way to and from the court,
through the multitude with which the streets were crowded;
all the doors and windows were also filled with spectators,
as if to see some strange sight.
Historians generally agree that the Protector in his civil
administration paid a just regard to equity and clemency;
and was careful to fill the benches with judges of integrity,
who did justice without respect of persons.
But this chief justice did not appear at this time to act up to that character.
He was so highly offended at their appearing before him with their hats on,
that when they made the reasonable demand of justice
for their imprisonment for nine weeks wrongfully,
being taken up without just cause in their journey by major Ceely,
he refused to hear them, unless they would appear before him uncovered,
which (it being to them a matter of conscience) amounted to an absolute refusal,
being only to be heard and receive justice on a condition they could not comply with.
Instead of granting their demand, an indictment was read against them,
conceived in such terms,
that at first G. Fox thought it had been against some of the thieves; for it asserted,
that they came by force and arms, and in an hostile manner, into court,
whereas they were brought thither as prisoners, which made them say, it was all false,
and there seems to have been no judicial procedure upon it.
Then major Ceely falsely and absurdly charging with making him privately a treasonable
proposal of raising forty thousand men to bring in King Charles,
George desired their mittimus might be read in the face of the country,
that the real causes of his commitment might appear.
This request, equitable as it was, the judge repeatedly refused to comply with.
At their next appearance,
the prisoners repeated their request to have their mittimus read,
and the people appearing desirous to hear it, one of his fellow prisoners, having a copy,
was permitted to read it aloud.
Which being done, G. Fox remarked upon it, that if he would have given surety,
he might still have been at full liberty to carry on the
design (if he had any) which Ceely charged him with,
at the same time appealing to the court,
whether Ceely had not made himself a party in the treason by omitting it in the mittimus,
desiring him to go out of the country, and never charging him with pretended treason,
nor making any discovery thereof till now.

The judge clearly perceiving,
that in this accusation Ceely instead of ensnaring G. Fox had ensnared himself,
let that business fall.
Ceely then finding this intended snare broken, got up again, and accused him,
that he struck him such a blow as he never had in his life;
seeming thus to sport with justice, truth and conscience,
in idle endeavours to criminate innocence with groundless absurdities;
for this blow he alleged himself to have received from G.
Fox proved to be nothing more than a merited reproof,
for an hypocritical complimenting of him,
while he was suffering under his malicious imprisonment.

In fine, either from the mittimus, the indictment, or Ceely`'s accusations,
no sufficient grounds of legal crimination appearing,
the judge instead of discharging them whom he could not condemn,
or regarding their demand of justice for their false imprisonment,
ordered them to be taken away;
and in their absence fined them twenty marks apiece
for coming into the court with their hats on,
and ordered them to be detained in prison till their fines were paid.

Being thus fixed in prison upon such a commitment,
that there was little probability of their being speedily released,
they thought it necessary to discontinue the weekly payment
of seven shillings a piece for their diet for themselves,
and as much for their horses, which the jailer had hitherto, in a manner,
extorted from them.
This defalcation of his oppressive gains stirred up the wicked
temper of this jailer to use them with great inhumanity:
He turned them down into in a dismal dungeon, called Doomsdale,
usually appropriated to the reception of atrocious criminals, after their condemnation.
This place was noisome beyond description,
it being remarked that most who were confined there lost their health thereby;
for the excrements of former prisoners were said
to have remained there unremoved for many years,
so that it was all like mire, in some places to the top of their shoes,
and the jailer would not suffer them to cleanse it, nor to have beds or straw to lie on.
They were therefore obliged to stand there all night,
the place being too filthy to allow them room to sit down.
Thus they were kept a considerable time before he would let them cleanse it,
or suffer them to have any victuals brought in, but what they got in through the grate,
and even this with difficulty.

This cruel treatment continued till the sessions at Bodmin,
when upon representing their case Bodmin to the justices,
they obtained an order for opening the door of Doomsdale,
and that they might be suffered to clean it, and buy their provisions in the town;
having obtained this liberty, they sent for Anne Downer, a young woman before mentioned,
from London, to come down to them to buy and dress their meat;
who readily complied with their request, attended them cheerfully,
and became a serviceable assistant to them during their confinement here.

While G. Fox lay here in prison,
one of his friends offered himself to O. Cromwell lie in prison body for body,
in George`'s stead; to which proposal Cromwell answered, he could not grant it,
being contrary to law, and turning to some of his council standing by him, queried,
"`which of you would do as much for me, if I were in the same condition?`"
Upon this, and other applications on their behalf,
he sent an order to the governor of Pendennis castle
to examine into the circumstances of their case:
On which occasion, Hugh Peters, one of the Protector`'s chaplains, remarked to him,
that He could not give George Fox a better opportunity
of spreading his principles in Cornwall,
than by imprisoning him there.
The truth of which observation the sequel confirmed,
for he was visited by many persons of repute, of whom several embraced his doctrine;
one of whom was Thomas Lower, a physician of London,
who asking many questions concerning religion,
received such clear answers from G. Fox that he said,
his words were like a flash of lightening, they ran so through him, adding,
that he never met with men of such wisdom and penetration in all his life.
By their means he became fully convinced of the truth of their doctrine,
and thenceforward entered into community with them.
The whole time of their imprisonment was about thirty weeks,
when they were discharged by an order from major general Desborrow.

The case of the jailer who had so barbarously used them is observable.
He before lay under the infamous character of a thief,
and was said to have been burned in the hand,
and in the next year after their release he was turned out of his place,
and for some crime was cast into jail himself, where for his unruly behaviour,
he was by the succeeding jailer put into Doomsdale, locked in irons, and beaten;
and bid to remember how he had used those good men in that nasty dungeon.
Thus the divine justice over took him, deservedly rewarding him with the same measure,
which he had unjustly meted to others.
At length he died in prison poor and miserable.

Their imprisonment was (through the ordering of divine providence) conducive to the
propagating their principles extensively through the their western counties,
and adding considerably to the number of their proselytes;
not only of those who came to visit them in prison, and were convinced by G. Fox there;
but many others by the ministry of other friends,
who being in cited by brotherly sympathy to come
from different parts of the nation to visit them,
and other friends in prison here and in the neighbouring counties,
were at the same time engaged to exercise their ministerial labours as they passed along,
and met with convenient opportunities,
in declaring their experience of the virtue of true religion to the people,
in order to excite them to the attainment thereof for themselves;
and these labours met with a cordial reception from many, who were convinced thereby.
Their success alarmed the priests and professors, and they, as usual,
instigated the magistrates to interpose their authority to check their progress.
For which purpose the justices in Devonshire made an order of sessions to apprehend,
as vagrants, all Quakers travelling without a pass.
They also appointed watches in the streets and highways,
under pretence of taking up suspicious persons,
principally with intention to take up these friends
of theirs on their journey to visit them in prison,
and to put a stop to their preaching; in consequence whereof, in the summer of this year,
above twenty persons male and female were committed to Exeter jail.
At the assizes the men were fined and confined in like manner as G. Fox had been,
for appearing with their hats on;
and the women were remanded to prison till they should
find sureties for their good behaviour.
They were lodged among the felons, and lay generally upon straw, by reason of which,
and the filth of the place, many of them fell sick, and one of them, named Jane Ingram,
died there.

In tracing the variety of arbitrary and unjust proceedings against this body of people,
one might imagine that in these unsettled times,
notwithstanding the professed high notions of civil liberty,
little regard was paid to legal rule: That men destitute of the feelings of humanity,
of virtue and good sense, suddenly starting up into offices of power,
which their original station gave them little reason to expect,
and for which by their education and prejudices they were ill qualified,
knew no bounds of moderation in the use of it; and that their politics,
no less than their religion, consisted more in specious pretensions,
than in a clear comprehension of the principles of real liberty,
and a practice regulated thereby.^
footnote:[We have a curious account in Thomas Elwood`'s
[.book-title]#Journal# of the manner of his being taken up,
and the treatment he met with: Calling at Isaac Penington`'s, in his return from London,
and designing to proceed home into Oxfordshire,
his friend kindly accommodating him with a horse as far as he might choose,
at Beconsfield he sent back the horse, intending to walk the rest of the way;
but he had not walked to the middle of the town before
he was stopped and taken up by the watch.
He asked the watchman by what authority he stopped him on the highway,
who produced an order from the constables to take up all rogues,
vagabonds and sturdy beggars.
Thomas thereupon asking for which of these he took him,
and informing him at the same time of the signification of these terms,
and that none of them belonged to him, though the fellow was too ignorant to answer him,
he was strong-headed enough to detain him: after some time the constable, being sent for,
came; who appeared something more mannerly but not much wiser than his watchman.
Being at a loss how to dispose of his prisoner,
he went to consult with the chief men of the town upon the subject,
who assembling in a poor hut, denominated the Town-house,
he was by the constable brought before the mock-senate,
some of whom eying him with a supercilious air, asked him some impertinent questions,
to which he returned suitable answers.
Then they entered upon consultation how to dispose of him
till they could take him before a justice to be examined.
At last to save charges they concluded to make him walk
about the streets with the watch till next morning;
till one of this grave assembly willed them to consider whether they could answer that,
and if the law would bear them out in it.
An old woman who lived in this town-house (who had in her youth lived
with some of his ancestors) being present at their consultation,
upon hearing the prisoner`'s name,
gave them such an account of his family as made them
suspect their prisoner as good a man as themselves.
Whereupon the council broke up,
and the constable took him home to lodge at his house that night, and the next morning,
proposing as a favour, to let him slip out at the back door and make off, he signified,
that as he came in, so he would go out at the fore door;
when he appeared determined he was suffered to depart his own way,
after being causelessly detained on his journey home.
G+++.+++ Fox.
W+++.+++ Sewel.]
For these magistrates and officers of their watches took up not only strangers,
but their own neighbours travelling about their lawful occasions,
as clothiers going to the mill, and others upon affairs of business: Of those,
some were cruelly beaten, and others taken up and whipped for vagrants,
though men of considerable property and estates,
and not above four or five miles from their habitations.
Henry Pollexfen, who had been a justice of peace for the most part of forty years,
and consequently well known for what he really was, they cast into prison for a jesuit.
