== Chapter IX.

[.chapter-synopsis]
* New Parliament
* Samuel Fisher attempts to deliver a Message to the Protector, Parliament and People
* Being prevented he publishes it in print
* The Parliament passeth an Act against Vagrants, which seems designed against the People called Quakers
* Sufferings of several Persons of that Denomination
* Account of James Nayler
* He comes to London
* Martha Simmonds`'s Complaint to J. Nayler at first rejected by him
* Afterwards her passionate Sorrow makes an Impression, darkening his Understanding
* He is reproved by G. Fox, but flights his Admonition
* He is taken up at Bristol and committed to Prison
* Sent up to the Parliament
* His Sentence
* Remarks thereupon
* Ineffectual Petition in his Favour
* First Part of his Sentence executed
* Second petition
* Rejected
* J. Nayler visited by five Preachers
* Execution of the second Part of his Sentence
* He is sent to Bristol and whipped there
* His Recantation
* Taken ill and dies
* Reflection upon his Case
* Account of John Camm

It was about this time the Protector thought it necessary
to convoke a parliament to sit on the 17th September,
better adapted to answer his purpose,
than those he had before summoned under that denomination.
He is thought to have been conscious of the weakness
of his title to the dignity he possessed,
having only received it from hands which had no right to bestow it.
The authority of a parliament, therefore, appeared to him requisite to confirm his own;
but as he had found by experience that, in the present temper of the times,
a free parliament could hardly be procured to coincide with his
main design he used every art in his power to influence the elections,
and to get a decided majority of his friends into the house;
and in order to make sure of this point, he placed guards at the door,
to permit none to enter but such as produced a warrant from his council;
and the council rejected about an hundred,
who either refused a recognition of his government,
or were on other accounts obnoxious to him.
The residue seemed implicitly resigned to act under Cromwell`'s dictates.

Samuel Fisher, beforementioned, late priest of Lydd, from an impulse on his mind,
was present at the opening of this sessions, and heard the protector`'s speech,
in which he asserted,
that he knew not one man that suffered imprisonment unjustly in all England.
After the speech was ended, Samuel Fisher, taking a convenient stand, said,
that he had a word to speak from the Lord to the Protector,
the parliament and the people; but had not proceeded far,
till he was interrupted by an exclamation, "`A Quaker, a Quaker, keep him down,
he shall not speak.`"^
footnote:[Sewel]
This prohibitory exclamation is said not to have
arisen from either the Protector or members,
who discovered no disinclination to hear him,
but from two angry justices and some others, by whom being interrupted,
the Protector arose, and the house broke up.

Fisher, by this interruption,
being deprived of the opportunity of delivering his message
(to which undertaking apprehending himself unequal,
he had desired to be excused from it, with fasting,
tears and supplications) took the only method left him to ease his mind of its burden,
by publishing in print the substance of what he intended to have spoken;
being a zealous reprehension of the hypocrisy of those, who under a shew of godliness,
made long prayers, and kept frequent fasts; yet at the same time lived in pride,
pomp and luxury,
and persecuted those who were in reality a pious and conscientious people.
With an admonitory caution to the Protector, that,
unless he took away the wicked from before him, and all flatterers and false accusers,
his throne would never be established in righteousness.

This parliament appears to have been of a complexion to which the
foregoing reprehension might not be improperly applied,
as they soon, manifested their promptitude to give a sanction to persecution.
It hath been evidently shewn what an illegal and despotic rigour was exercised
by the bigotted and passionate magistrates of this age,
who disclaiming persecution in theory, practised it in reality,
in the misapplication of the laws against vagrants,
to the punishment of men truly religious, for their religious persuasion of duty,
in travelling at their own charges to preach the gospel,
and propagate righteousness and purity of life in the nation.
This parliament, as if to give a sanction to the unreasonable severity,
and strengthen their hands in oppression and cruelty,
early passed an act against vagrants, and wandering, idle,
dissolute under which description they comprehended all who were gone from home,
and could not give a satisfactory account of their business.

If the Quakers (so called) found themselves before exposed to tyrannical punishments,
and causeless deprivation of their liberty,
this combination of the legislative with the executive power rivetted their chains,
as it deprived them of all hope of redress,
and exempted their persecutors from all fear of control.
When we consider this act so perfectly coinciding with the
mode of proceeding before adopted by inveterate magistrates,
in bringing them to punishment,
one must conclude that many of these prejudiced magistrates
had been admitted into this packed Parliament,
or had a great influence over the members;
or else that their teachers had leavened both into one sentiment
and disposition to wards this inoffensive body of men,
as the act seems plainly designed to legalize their arbitrary manner of punishing,
and the title expressed in vague and indefinite terms,
on purpose to admit a latitude of construction,
whereby it might be extended to comprehend such of them
as travel led abroad to propagate their doctrines,
which as their adversaries could not confute by argument,
they seemed determined to suppress by violence; and by an arbitrary stretch of power,
to make harmless actions illegal,
since the general tenour of their conduct administered no just cause of crimination.
For the vagrancy is applied, not only to idle, dissolute persons,
but all that go from home, who cannot give a satisfactory account of their business;
but what account should be deemed satisfactory seems to be left to the judgment,
or caprice of the civil magistrates to determine at his discretion.
Leaving the admirers of the government of the nation at this era
to reconcile such an act to any just notion of civil liberty,
I proceed to the consequential sufferings of several of this people,
wherein we shall view the same spirit of hostility and intemperate
domination actuating the magistrates in the execution,
through the remainder of the present and succeeding year;
but I mean not to swell the volume,
or exercise the reader`'s patience with a full recital
of the various cases of sufferers under this act,
preserved in the authentic records before me;
but to restrict myself to a few of the most remarkable,
as a specimen of unfeeling perseverence in inflicting,
and patient equanimity in sustaining, unmerited punishment.

Henry Clifton, only riding through Upwell in Cambridgeshire, was taken up by a constable,
and carried before a neighbouring justice; and after some reproach and derision,
sent by him to another justice four miles distant,
by whom without any reasonable cause he was sent to prison,
where he lay in the dungeon among condemned felons a considerable time.
Ann Blakely, for openly testifying against the corruption of their times,
being also imprisoned at Cambridge and detained there six months,
during her imprisonment, two of her friends, Richard Hubberthorn and Richard Weaver,
being moved in brotherly sympathy to pay her a visit, were,
for this office of christian duty, and no other cause, themselves cast into prison:
They had travelled from home,
and the account they could give of the motive of their journey,
however reasonable and laudable, if not satisfactory to a prejudiced magistrate,
he had doubtless an authority from the preceding law to commit them,
probably during pleasure.
The said Richard Hubberthorn for not departing the town at the mayor`'s
command was also sent to the house of correction for three months.

Thomas Curtis of Reading, woollen-draper, coming to Plymouth upon affairs of trade,
went from thence accompanied by John Martindale to West-Alvington:
being in bed at a friend`'s house,
a constable with attendants came with a warrant at midnight,
and next day carried them before two justices, who sent them to Exeter jail,
notwithstanding that upon their examination,
they made it appear that they were travelling upon lawful and requisite affairs of business:
They were brought before the judge at the ensuing assizes,
where nothing was laid to their charge; but the judge, taking occasion from their hats,
fined them 40£. a piece for contempt,
for nonpayment of which they were kept prisoners above a year after.
During his imprisonment Martindale having obtained leave of the
jailer to visit a friend at Ilchester went to meeting at Cullington,
where he, Humphry Sprague and Thomas Dyer lodged at a friend`'s house.
In the evening two constables came and required the strangers to go with them,
which (they having no warrant) was refused.
Next morning they came with a warrant,
and carried them before the justices at the quarter-sessions at Honiton,
to whom they gave account of their places of abode,
being one of them but two miles from home, and another not above five:
however the justices sentenced them all as vagrants, to be whipped in the market-place,
and sent with a pass, from tithing to tithing, which was accordingly done.

George Whitehead after his release from Edmundsbury jail took the opportunity
of paying a religious visit to his friends in the city of London,
a service which he had in prospect before his imprisonment, but was prevented thereby:
his visit was very acceptable to friends, and conducive to the convincement of several,
through his powerful and effectual ministry.
His stay in the city was not long,
till he thought it his duty to go back into Essex and Suffolk,
notwithstanding his late suffering and imprisonment there,
and the inimical disposition of several of the magistrates
to the society of which he was a member;
for being favoured with the conscious sense of inward peace,
in reward of the faithful discharge of apprehended duty,
and relying upon divine protection for support, while they continued in the way thereof,
the ministers of that day were neither to be deterred by the remembrance of past,
nor the prospect of future sufferings.

Having travelled through Essex and part of Suffolk,
appointed several meetings and met with a variety of occurrences,
he appointed a meeting at Nayland at a friend`'s house,
which being too small for the purpose, the meeting was held in the yard or orchard,
which many friends from Essex and Suffolk, as well as others, attended.
While George Whitehead was in the course of his testimony, a person,
under the character of a gentleman, rushed into the meeting,
with a rude company of attendants,
and with violence pulled him down while he was preaching,
and some of them with the constable took him to Arlington, before John Gurden,
an old and bitter adversary, who, as soon as he appeared before him,
began to threaten him; upon which George desired his moderation,
to hear him before he passed judgment; to which, he replied, "`you are a moderate rogue:
moderate rogue!`" said George, such language doth not become a magistrate,
especially one professing Christianity.

Gurden repeating his menaces, and unseemly language, bidding him go quake,
after some examination, ordered his clerk to take it down in writing, which being read,
George was required to sign it, which he refused to do, as being partially taken.
Afterwards Gurden bringing a law-book in his hand,
read an abstract of a statute against vagrants, sturdy beggars,
idle and dissolute persons, pedlars, tinkers, etc, with the penalty appointed for them.
And although the prisoner came no more under any of these descriptions,
properly understood and applied, than the justice himself,
yet he was informed by this justice that they had
ordered him to be whipped he is order at Nayland,
and if he came again into the country, he should be branded in the shoulder for a rogue;
and if he came a third time he should be hanged.
To which menace George replied, "`I am no such person as thou haft mentioned;
thou art an old man, and going to thy grave,
and dost not know how soon the Lord may put an end to thy days,
and disappoint thy evil designs against me: however I fear not thy threats:
If the Lord whom I serve require my return into those parts, I must obey him.`"

The warrant for his punishment being signed and sealed by John and Robert Gurden,
father and son, two justices,
was delivered to the constable with this charge from R. Gurden,
to see it executed upon him to purpose at his peril.
The copy of the warrant followeth, viz.

[.embedded-content-document.legal]
--

[.letter-heading]
To all Constables, and all whom it may concern, and every of them.

Be it remembered, that one George Whitehead, a young man of about twenty years of age,
who confesseth himself to have been born at Orton in Westmoreland,
being this present day found a vagrant, and wandering at Nayland in this county,
contrary to the laws of this nation, and being thereupon brought before us,
two justices of peace for this county,
is by us ordered to be openly whipped at Nayland aforesaid, till his body be bloody,
as the law in such case enjoineth:
and he is to pass thence from parish to parish by
the officers thereof the next way to Orton aforesaid,
before the first day of June now next ensuing.

Dated at Arlington in this county of Suffolk the first day of April 1657.

--

The warrant was the next day put in execution,
with such severity as displayed the malignancy,
and acrimony of the justices and officers in full light.
The constable procured a foolish fellow, without feeling or discretion,
to inflict the punishment, who being provided with a long sharp whip,
laid on his stripes with unmerciful violence,
where by George Whitehead`'s back and breast were grievously cut, his skin torn,
and his blood shed in abundance, and the insensible fool still went on,
unrestrained by the constable, till some of the spectators, who were numerous,
and many of whom were so affected at beholding their cruelty as to drop tears,
cried out to stop him;
whilst the victim of the justices`' vengeance was so supported in patience,
so filled with inward peace and consolation in Christ,
under the cruel torture and mangling of his body, that his spirit was raised,
and his mouth opened to sing aloud in praise to that divine being,
who had counted him worthy to suffer persecution for righteousness`' sake,
to the amazement and conviction of the by-standers.

When the hand of the executioner was stayed by the cry of the people, George Whitehead,
as he stood there, undressed with his wounds and stripes fresh upon him,
addressed the spectators,
informing them it was a proof of a minister of Christ patiently to endure affliction,
according to the Apostle`'s testimony, 2 Cor.
6+++.+++ Approving ourselves as the ministers of God in much patience, in afflictions,
in stripes, in imprisonments, in tumults:
Whereby he appeared to rise superior to the in dignity
intended him by these invidious magistrates,
to manifest himself to be no proper object of the servile
and contemptuous punishment they had adjudged him to suffer,
being neither a vagrant in the legal sense of the word,
nor in any sense a disorderly person.
And therefore the shame and ignominy designed to
him more properly reverted to these magistrates,
who abused the power they were invested with to the oppression of innocence,
and the punishment of those that did well.

After the execution he mounted his horse,
and was attended by the proper officers with the warrant and pass to Sudbury, Clare,
Haverill, and to the edge of Cambridgeshire;
the said warrant and pass all along reflecting disgrace
and disgust to the justices who signed them,
it being a common and natural reflection with the
people who saw him well-habited and well mounted,
"`This young man doth not look like a vagrant.`"
When he came to the last place the constable being employed in his necessary labour,
looking upon the young man, upon the warrant,
upon the unreasonable burden imposed upon himself
by the caprice and malice of two distant justices,
delivered him the warrant and pass to convey himself whither soever he might think best.

Being thus set at liberty he returned, notwithstanding the justices menaces,
to finish his service in those parts,
where he was interrupted by his being causelessly arrested and punished:
the curiosity of the people being awakened by his late sufferings,
caused a great resort to the meetings where he was,
to see and hear the young man who was so cruelly whipped at Nayland.

Many were tenderly affected towards him,
and many convinced of the truth of the doctrine he delivered.
Thus by the over-ruling hand of divine providence the arbitrary measures pursued to
prevent the growth of this people contributed to their increase and establishment.
Humphry Smith and Samuel Curtis riding together near Axminster, were stopped,
and carried before a justice, who, upon consultation with a priest,
ordered them to be whipped as vagrants, burnt their books and papers,
took their money from them, and sent them away with a pass.

Joan Edmunds, wife of Edward Edmunds of Totness,
was stopped on the road by a drunken fellow, who took away her horse:
she complained to a justice of peace, being then about ten miles from home;
but having no pass, the arbitrary and officious justice sent her to Exeter jail,
ordered her horse to be sold,
and part of the money applied to defray the charge of carrying her to prison.
Her habitation being in the direct road to Exeter,
they took her by another road six miles about,
to prevent their injustice being exposed amongst her neighbours,
who well knew she was no vagrant.

George Bewley, John Ellis and Humphry Sprague,
after a meeting at Bridport in Dorsetstshire,
were by the mayor and bailiffs caused to be whipped
for vagabonds and sent away with passes:
George Bewley desired liberty to go to the inn for his horse and clothes,
but was not suffered.
When he had gone some miles from the town,
the officer who conducted him gave him his liberty;
whereupon he returned for his horse and clothes,
and the bailiffs caused him to be whipped again, and sent away without them:
he returned again, went to his inn, paid his host,
and was riding out of town on his horse,
when the bailiffs ordered him to be taken and whipped the third time.
They then suffered him to depart with his horse and clothes
which they had unjustly detained without any colour of law,
and cruelly tortured the owner for claiming his own property.

It was under this parliament that James Nayler suffered
punishment by a most rigorous sentence,
most unmercifully executed.
And although that extravagant conduct, which subjected him to those sufferings,
was disclaimed and censured by the generality of those of his own persuasion;
yet as some authors (Hume in particular) instance his case, almost singly,
as a specimen of Quakerism,
it seems proper in this place to introduce a narrative
of the principal occurrences of his life,
whereby we may be enabled to form a sounder judgement,
how far his miscarriage ought to be imputed to the body of the Quakers so called,
or their principles.

James Nayler was born near Wakefield, of honest parents,
his father was an husbandman of good repute,
having a competent estate to live upon after the manner of that country;
about the age of twenty-two he married,
and continued his residence near Wakefield till the civil war broke out in 1641.
He then entered into the army, in which he continued eight or nine years,
first under Lord Fairfax, and afterwards as quarter-master under major general Lambert,
till being disabled by sickness, he returned home about 1649.
As to his religious profession,
he was in society with the Independents till the year 1651, when,
being convinced by the ministry of G. Fox, as noticed before,
he joined in community with the Quakers.
He was a man of excellent natural parts,
and had received a tolerable education in his native language, and wrote well.
And being by his convincement turned to the measure of divine grace in his own heart,
by a diligent attention thereto he grew in experience of the work of sanctification,
and received an excellent gift in the ministry;
and while he kept in obedience to the dictates of this preserving principle,
he was eminently favoured in his ministry with divine power, and a convincing influence,
reaching to the consciences of his auditory,
and awakening many to a clear sight of the internal state of their minds;
of their misery under the bondage of sin,
and to ardent desires after redemption and sanctification.
By the same divine principle he was so preserved in circumspection
of life as to confirm his doctrine by his example,
shewing forth the fruits of the spirit out of a good conversation;
exemplary in godliness, humility, and every christian virtue; and instrumental,
by divine grace, in turning many from darkness to light,
and from the power of Satan to the power of God.
During the space of three years, he continued in near unity with his friends,
and in just estimation amongst them, for his works sake.
In the latter end of 1654, or beginning of 1655, he came to London,
where he found a meeting of his friends already gathered,
through the effectual ministry of Edward Burrough and Francis Howgill.
Among them he preached in a manner so nervous and affecting,
that he thereby captivated the affections of several of
the more superficial and unexperienced part of the auditory,
so as to hold his person in admiration,
and to prefer him much above his fellow-labourers, which was injurious to him,
and tended to introduce divisions,
like those the Apostle Paul reproves in the church of Corinth,
when the carnal walkers as men were disposed to pay
that veneration to the respective Apostles,
which be longed only to Christ, and to separate into parties.
Of these were some forward females of weak intellects, strong passions,
and flighty imaginations,
who carried their impertinence so far as to oppose Francis Howgill and Edward Burrough,
men of great worth, openly in their ministry, to the great disturbance of the meetings.
For which disorderly behaviour,
meeting with merited reproof from these judicious and discerning men,
who clearly perceived the tendency of these pernicious proceedings,
they could not bear the rebuke with any patience; but one Martha Simmons,
with another woman, carried their complaints to James Nayler, flattering themselves,
that as they were endeavouring to make him the head of a party,
he would not hesitate to give his opinion in their favour,
but herein their hope deceived them; for his judgment being as yet sound and unclouded,
he thought it his duty to discourage their insinuations or complaints,
as tending to sow discord between brethren.
Her unexpected disappointment proving a trial too severe for this
Martha`'s impatient spirit to sustain with any degree of moderation,
she immediately vented her passion in doleful exclamation, lamentation and weeping;
these passionate expressions of sorrow moved Nayler`'s commiseration,
and left an impression on his mind, which resulted into a deep melancholy,
under the effect whereof he became darkened and bewildered
in his understanding and judgment;
estranged from his best and most judicious friends,
who were concerned to admonish him of his danger;
and open to the pernicious flatteries and intoxicating praise of these unsettled spirits,
which in his better days he would have heard with abhorrence and rebuke;
by which means he gradually lost the brightness, beauty and humility,
which formerly adorned his ministry and his conversation;
became exalted above his sphere, and lifted up in spiritual pride to a lamentable degree.
From London travelling westward to visit George Fox in Launceston,
he was in the summer of 1656,
one of those before related to have been committed to Exeter jail,^
footnote:[From thence we came through the countries to Exeter,
where many friends were in prison, and among the rest James Nayler.
For a little before the time that we were set at liberty James run out into imaginations,
and a company with him; and they raised up a great darkness in the nation.
And he came to Bristol, and made a disturbance there:
and from thence he came to Launceston to see me,
but was stopped by the way and imprisoned at Exeter.
That night that we came to Exeter, I spake with James Nayler; for I saw he was out,
and wrong, and so was his company.
The next day, being the first day of the week, we went to the prison,
to visit the prisoners, and had a meeting with them in the prison;
but James Nayler and some of them could not stay the meeting.
The next day I spake to James Nayler again, and he slighted what I said, and was dark,
and much out; yet he would have come and kissed me; but I said,
since he had turned against the power of God, I could not receive his shew of kindness;
so the Lord moved me to slight him, and set the power of God over him.
So after I had been warring with the world,
there was now a wicked spirit risen up amongst friends to war against.
And when he came to London, his resisting the power of God in me,
and the truth that was declared to him by me, became one of his greatest burdens.
George Fox`'s [.book.title]#Journal#, octavo, Vol.1, p. 374.]
where he was a prisoner at the time of George Fox`'s release,
who upon the night of his arrival at that city visited his friends in prison there,
and James Nayler in particular,
to admonish him of the delusion and danger he and his partisans were fallen into;
being impressed with a sorrowful sense of their error:
but James being covered with darkness, and exalted in his imagination,
slighted this admonition:
for his ranting adherents set no bounds to the madness of their enormities;
they proceeded from bad to worse; from wildness to an excess of frenzy:
in their letters to him, at this time,
they addressed him with appellations not fit to be attributed to any mortal man,
diametrically opposite to the avowed principles of the people called Quakers.
Nor did their madness stop here, for three of these silly women, in this prison,
kneeled before him, and kissed his feet: after his release, riding into Bristol,
one Thomas Woodcock went before him bareheaded, a woman led his horse;
and the three women before mentioned spread their handkerchiefs and scarfs before him,
singing in imitation of the Hosanna before our Saviour riding into Jerusalem.
Here they were taken up, and carried before the magistrates, by whom being examined,
they were committed to prison.
Upon search,
some of those foolish and extravagant letters of his followers were found in his possession,
with others of a very different strain from his former friends,
reproving him for his instability and self-exaltation;
the former were divulged to aggravate his offence,
the latter not answering any purpose of his prosecutors seem to have been suppressed.
Not long after he was transmitted to London to be examined by the parliament,
who judged these senseless enormities of a few deluded individuals,
little affecting the public good, or the nation`'s safety,
of sufficient consequence to engage their attention for ten days.
Debates ran high,
many of the members being very averse to the severity of the measures taken against him;
but the majority (to whom James Nayler`'s zeal in his writings and discourses,
reprehending self-righteousness and pretences to religion,
deformed by immorality in life and conversation) had given offence,
actuated by vindictive motives,
to gratify private hatred under the colour of public justice,
on the 17th of December passed the following dreadful sentence upon him.^
footnote:[The trial of James Nayler was published;
but the extravagancy of the sentence passed upon him, with other circumstances,
give great reason to suspect the account was partially taken,
and published to justify the cruelty thereof; some of his answers were innocent enough,
some not clear; and some wrested and aggravated by his adversaries: and it is remarkable,
that upon his appearing before the parliament,
he was ordered not only to uncover his head, but also to kneel before them,
when one of the heaviest charges against him was
that he barely suffered some to kneel to him,
for it doth not appear that he required or expected any such thing:
when the Speaker Widderington was going to pronounce the sentence,
James Nayler said he did not know his offence.
To which the Speaker replied, he should know his offence by his punishment.
After the sentence, he seemed desirous to have spoken something,
but was refused the liberty: he then just expressed himself with a composed mind,
"`I pray God, he may not lay it to your charge.`".]

[.embedded-content-document.legal]
--

That James Nayler be set on the pillory, with his head in the pillory,
in the palace-yard Westminster, during the space of two hours on Thursday next,
and be whipped by the hangman through the streets from Westminster to the Old Exchange,
London, and there likewise be set on the pillory, with his head in the pillory,
for the space of two hours, between the hours of eleven and one on Saturday next;
in each place wearing a paper containing an inscription of his crimes,
and that at the Old Exchange his tongue be bored through with an hot iron,
and that he be there also stigmatized in the forehead with the letter B,
and that he be afterwards sent to Bristol,
and be conveyed into and through the said city on horseback, with his face backward,
and there also publicly whipped the next market day after he comes thither;
and that from thence he be committed to prison, in Bridewell, London,
and there restrained from the society of all people, and there to labour hard,
till he shall be released by parliament,
and during that time be debarred the use of "`pen, ink and paper,
and shall have no relief but what he earns by his daily labour.

--

The prosecutions and punishments of the Starchamber in the last reign,
as being exorbitant and unreasonably barbarous, excited general disgust and indignation;
and the tyrannical proceedings thereof occasioned an almost universal outcry,
particularly amongst the puritans, and with very good reason; upon which account,
when they found themselves the majority in the long parliament,
they justly abolished this court, as an intolerable grievance.
But here we find a fresh occasion to remark upon the inconsistency
of these puritans of the independent class,
of whom, I imagine, the majority of this parliament was composed,
for it was this party Oliver principally trusted and employed.
The sentence passed on this unhappy man,
is for the greater part almost a copy of that by the aforesaid
in famous court passed upon Leighton for his book called,
Zion`'s Plea against Prelacy.
And the poignant censure of a late historian on the latter,
may with little impropriety be applied to the other also.^
footnote:[For a comparative view of the similarity of the two sentences,
fee that passed upon Leighton in the above quoted author,
viz. Macaulay, Vol.
II. p. 93.]

[.embedded-content-document]
--

Notwithstanding all that may be said against the conduct of this unfortunate enthusiast,
his offence was by no means adequate to his punishment;
his treatment and prosecution notoriously inhuman and illegal.
The judgment passed against him was by an illegal court,
whose jurisdiction was unconstitutional;^
footnote:[The House of Commons by the constitution is no court of judicature,
nor hath any power to inflict any other punishment than imprisonment during their
session.]
--was directly contrary to the humane spirit of the British laws;
and the single instance of such an execrable barbarity would have
disgraced the government of an absolute monarch.

--

Many people (not of the society of Quakers) esteeming
the sentence passed upon Nayler exorbitantly severe,
for a crime proceeding more from a disordered understanding than a malignant intention,
actuated by the feelings of compassion for the man,
of which his judges appeared divested,
solicited the parliament with petitions in his favour, but to no purpose:
for after the sentence was passed,
the Speaker was authorized to issue his warrants to the sheriffs of London and Middlesex,
the sheriff of Bristol, and the keeper of Bridewell,
to see the judgment put in execution.

And the very next day, viz. on the 18th of December,
the first part was severely executed; sentence, after standing two hours in the pillory,
he was stripped,
and tortured with a most cruel whipping from Palace-yard to the Old Exchange,
receiving three hundred and ten stripes;
so that according to the testimony of Rebecca Travers, a woman of indisputable veracity,
who washed his wounds, in a certificate presented to the parliament,
and afterwards printed,
"`There was not the space of a man`'s nail free from stripes
and blood from his shoulders down to near his waist,
his right arm sorely striped, and his hands so hurt with the cords,
wherewith he was tied, that they bled, and were greatly swelled.`"
This cruel torture Nayler endured with patience and
quietude to the astonishment of the spectators.
The 20th of the same month was the day appointed
for the execution of the second part of his sentence;
but he was reduced to such a state of weakness by the severe execution of the first part,
that many persons of note, compassionating his condition,
interposed in his favour by petition to the parliament,
and obtained a respite of one week,
during which interval a second petition was presented in the following terms.

[.embedded-content-document]
--

Your moderation and clemency in respiting second the punishment of James Nayler,
in consideration of his illness of body,
hath refreshed the hearts of many thousands in these cities,
altogether unconcerned in his practice: wherefore we most humbly beg your pardon,
that are constrained to appear before you in such a suit (not daring to do otherwise)
that you would remit the remaining part of your sentence against the said James Nayler,
leaving him to the Lord, and to such gospel remedies, as he hath sanctified;
and we are persuaded you will find such a course
of love and forbearance more effectual to reclaim,
and will leave a zeal of your love and tenderness upon our spirits.

And we shall pray, etc.

--

This petition, replete with good sense and humanity,
was presented to the house by about an hundred persons on behalf of the subscribers,
but the same vindictive temper, which had dictated the sentence,
resisting all solicitation for mitigating it, obliged these petitioners to endeavour,
by an address to the Protector, to obtain from him that favour,
they could not obtain from the parliament; whereupon he wrote a letter to the house,
which occasioned some debate, but no resolution in favour of the prisoner.
Finding their interposition hitherto ineffectual,
the petitioners presented a second address to the Protector; but, it is said,
the public preachers, by their influence, prevented its effect.
How ever it is probable that these reiterated petitions
of persons unconnected with the offender in religious community,
conveyed a plain indication to his adversaries,
that their severity was not generally well relished.
Wherefore five of the noted public preachers, Caryl, Nye, Manton, Griffith and Reynolds,
by order of the parliament,
(as it was said) visited James Nayior in prison to treat
with him concerning those offences for which he was detained,
and bring him to a sense there of,
as if to varnish over the deformity of their proceedings
with a colour of intending only the reformation of the man,
by an heterogeneous mixture of ghostly counsel with corporal punishment,
and inhuman severity with some semblance of christian charity;
but this amiable virtue had little place in their
public or private transactions with him:
for these men would admit no friend of his nor any other person into the room,
although requested, upon which Nayler insisted that what passed should be put in writing,
and a copy left with him or the jailer, to which,
in order to draw such answers from him as they wanted, they consented.
The reason of his making this demand, was an apprehension he had of an insidious design,
as they would suffer no impartial person to be present at the conference to testify
the truth if requisites and the result seems to manifest his fears not groundless,
for after some discourse, perceiving they were endeavouring to wrest words from him,
to pervert to his crimination,
in order to furnish some colour of justification to the public, he remarked to them,
"`They had soon forgot the work of the bishops, who were now, treading the a same steps,
seeking to ensnare the innocent.`"
Whereupon they rose up in a rage, burned what they had written,
and left him to undergo every jot and tittle of his unmerciful sentence.

At the expiration of his respite, on the 27th of December,
the second part of his sentence was executed upon him.
There was one Robert Rich, a zealous partisan of his, who mounting the pillory with him,
held him by the hand, while he was branded in the forehead, and bore through the tongue,
who being much affected with his sufferings,
licked his wounds in order to allay the pain.
The spectators, who were very numerous, behaved with decency and quietness,
without reviling or throwing anything at him,
seeming generally affected with commiseration and regret at his unchristian treatment.
He was afterwards sent to Bristol, and there whipped from the middle of Thomas-street,
over the bridge up High-street and to the middle of Broad-street,
all which he bore with astonishing patience, according to the testimony of an eyewitness;
thence he was sent the back way to Newgate, and from thence returned to Bridewell,
London, pursuant to his sentence, and was there detained a prisoner about two years:
During his confinement he was favoured with a clear sight of his lamentable fall,
and sincere repentance on account thereof,
and after his release he published his recantation,
the following extracts from which evince that he not only repented of his transgression,
but through the divine mercy was again restored to a lively feeling sense of true religion,
whereby he recovered his unity with his friends,
and continued therein to the end of his days.

[.embedded-content-document.paper]
--

Condemned forever be all those false worships,
with which any have idolized my person in the night of my temptation,
when the power of darkness was above all their casting of their clothes in the way,
their bowings and singings, and all the rest of those wild actions,
which did any ways tend to dishonour the Lord,
or draw the minds of any from the measure of Christ Jesus in themselves,
to look at flesh, which is as grass,
or to ascribe to the visible that which belongs to Christ Jesus; all that I condemn,
by which the pure name of the Lord hath been any ways blasphemed through me,
in the time of temptation; or the spirits grieved, that truly loved the Lord Jesus,
throughout the whole world, of what sort soever.
This offence I confess, which hath been sorrow of heart,
that the enemy of man`'s happiness in Christ should
get this advantage in the night of my trial,
to stir up wrath and offences in the creation of God;
a thing the simplicity of my heart did not intend, the Lord knows;
who in his endless love hath given me power over it, to condemn it;
and also that letter which was sent me to Exeter by John Stringer, when I was in prison,
with these words: Thy name shall be no more James Nayler, but Jesus.
This I judge to be written from the imaginations,
and a fear struck me when I first saw it, and so I put it in my pocket close,
not intending any should see it; which they finding on me, spread it abroad,
which the simplicity of my heart never owned.
So this I deny also, that the name of Christ Jesus was received instead of James Nayler,
for that name is to the seed to all generations, and he that hath the son, hath the name,
which is life and power, the salvation and the unction,
into which name all the children of light are baptized.

And all those ranting wild spirits,
which then gathered about me in that time of darkness;
and all their wild actions and wicked words against the honour of God,
and his pure spirit and people; I deny that bad spirit, the power and the works thereof;
and as far as I gave advantage, through want of judgement,
for that evil spirit in any to arise, I take shame to myself justly,
having formerly had power over that spirit, in judgment and discerning, wherever it was;
which darkness came over me through want of watchfulness,
and obedience to the pure eye of God, and diligently minding the reproof of life,
which condemns the adulterous spirit.
So the adversary got advantage, who ceases not to seek to devour;
and being taken captive from the true light, I was walking in the night,
where none can work, as a wandering bird fit for a prey.
And if the Lord of all mercies had not rescued me, I had perished,
for I was as one appointed to death and destruction, and there was none could deliver me.
And this I confess, that God may be justified in his judgment,
and magnified in his mercies without end, who did not forsake his captive in the night,
even when his spirit was daily provoked and grieved,
but hath brought me forth to give glory to his name forever.
And it is in my heart to confess to God, and before men, my folly and offence in that day.
Yet were there many things formed against me in that day, to take away my life,
and bring scandal on the truth, of which I am not guilty at all; as that accusation,
as if I had committed adultery with some of those women,
who came with us from Exeter prison, and also those who were with me at Bristol,
the night before I suffered there; of both which accusations I am clear before God,
who kept me in that day, both in thought and deed, as to all women, as a child,
God is my record.
And this I mention in particular (hearing of some who still cease not to reproach therewith
God`'s truth and people) that the mouth of enmity might be shut from evil speaking,
though this toucheth not my conscience.

--

Sundry other papers which he published during his imprisonment, and after,
confirm the sincerity, of his repentance;
and so deeply was the humbling sense of his fall impressed on his mind, that during,
the remainder of his life he was a man of great self-denial, and;
very diffident and jealous of himself.
At last, taking his departure from the city of London in the fall of 1660,
in order to go home to his wife and family at Wakefield,
he travelled on foot as far as Huntingdon,
and was observed by a friend as he passed through the town in such an awful,
solemn frame, as be spoke him a man redeemed from the earth,
seeking a better country and inheritance.
He went not many miles from Huntingdon before he was taken ill, taken ill,
being reported to have been robbed and left bound and being
found in a field by a countryman toward evening,
he was removed to a friend`'s house at Holm, not far from King`'s Rippon,
where he was attended by Thomas Parnell, a physician of said town, and.
not long after departed this life in peace, about the ninth month (November), 1660,
in the forty-fourth year of his age.
The following expressions, uttered by him about two hours before his departure,
evidence the peaceful and even tenor or his mind at that solemn period.

[.embedded-content-document.testimony]
--

There is a spirit which I feel, that delights to do no evil, nor to revenge any wrong,
but delights to endure all things, in hopes to enjoy its own to the end:
Its hope is to outlive all wrath and contention,
and to weary out all exaltation and cruelty,
or whatever is of a nature contrary to itself.
It sees to the end of all temptation: As it bears no evil in itself,
so it conceives none in thought to any other: If it be betrayed it bears it;
for its ground and spring is the mercies and forgiveness of God: Its crown is meekness,
its life is everlasting love unfeigned,
and takes its kingdom with entreaty and not with contention,
and keeps it by lowliness of mind.
In God alone it can rejoice, though none else regard it, or can own its life:
It is conceived in sorrow, and brought forth without any to pity it;
nor doth it murmur at grief and oppression.
It never rejoiceth but through sufferings, for with the world`'s joy it is murdered:
I found it alone being forsaken;
I have fellowship therein with them who lived in dens and desolate places in the earth,
who through death obtained this resurrection and eternal holy life.

--

There seems to be a pride and malignity in human nature while unreformed by religion,
diametrically opposite to christian charity, which,
unconscious of sublime virtue in itself,
and aiming to depress the rest of mankind below its own level,
delights to dwell on the dark side of characters, to magnify the failings of men,
and draw a suspicious shade over their virtues,
or the mitigating circumstances of their defects,
and this malevolent disposition receives new force from the spirit of party,
which peculiarly characterized this age,
and raged with unabated violence against the Quakers.
So in this poor man`'s case, and that of the society with which he had been connected,
his failings were not only greatly exaggerated,
but crimes imputed to him of which he appears entirely innocent;
his enormities are overlooked by few who have given an account of him,
his repentance by most:^
footnote:[There is a passage in a book, entitled, [.book-title]#A Complete History of England,
Vol. 3# p. 201, which asserts that James Nayler died with no fruits,
nor as much as signs of repentance:
How the author came by such information we cannot tell;
but that it is a manifest mistake we doubt not but
the impartial reader is by this time convinced.]
That he was a Quaker (so called) is carefully preserved from oblivion;
that his extravagant conduct was disapproved by the Quakers mostly passed over unnoticed.
The fall of one man in the hour of temptation, or the infirmity of another,
recorded as a picture of Quakerism,
without any regard to the far greater number of those people,
who evidenced the virtue and efficacy of the divine principle
of light and grace they bore testimony to,
by an undeviating observance of every christian and moral virtue in their lives;
and the solidity of their religion, and the purity of their consciences,
by the divine support they felt,
bearing up their spirits at the approach of the awful hour of death.

While some,
to involve the body of the Quakers at large in the reproach of James Nayler`'s extravagancies,
have passed over in silence their general disapprobation thereof; others,
on the contrary,
because Rich and a few more wrongheaded forward people took part with him throughout,
with pleasure observed, as they were willing to persuade themselves,^
footnote:[Mosheim, who omits no occasion of depreciating this people,
discovers his accustomed partiality and unfriendly bias,
in his ill-natured description of these imputed divisions.
"`Even during the life of their founder (says he) the Quakers,
notwithstanding their extraordinary pretensions to fraternal charity and union,
were frequently divided into parties, and involved in contests and debates.
These debates, indeed, which were carried on in 1656, 1661, and 1683,
with peculiar warmth, were terminated in a short time, and without much difficulty.`"
The dividing into parties, he mentions, in 1656,
was no more than what is here represented,
which how far it falls short of his exaggerated description
is referred to the judgment of the dispassionate reader.
It gave no interruption, that I can discover,
to the general subsistence of that fraternal charity and union
at this time remarkable amongst the members of this society,
not in pretension but in reality, being demonstrated by facts,
which are more indisputable evidence than uncandid insinuations
or assertions What else but true brotherly affection,
the essence of charity,
could induce them to come from the remotest parts of the
nation to visit and administer to their imprisoned friends?
What else bring them on foot from the extremity of the North to
London to solicit the protection and commiseration of government
in their favour? We have seen in more instances than one,
some of these people offering up their bodies to lie in prison,
if thereby they might release a friend,
whose life or health was endangered by the hardships of imprisonment;
we see these offices of brotherly kindness still continue,
and shall find them again hereafter.
Are these extraordinary pretensions?
Are they not rather extraordinary instances of fraternal charity and union,
to which the silly conduct of a very few misguided individuals gave no interruption.
This author, in conclusion,
seems to refute his preceding description by an inexplicable inconsistency.
"`These debates which were carried on with peculiar
warmth--were terminated in a short time,
and without much difficulty.`"]
the symptoms of dissension and divisions among the members of this society from
whence their sanguine wishes led them to prophesy the speedy dissolution thereof;
but such diviners found themselves mistaken in their
conjectures and disappointed in their wishes,
on this as well as former occasions;
for the imprudence of a very small number of the most unsteady
and insignificant members occasioned no division,
properly speaking, none of consequence or long duration.
George Fox, coming up from Exeter, after his release from Launceston jail,
by Bristol (where he had large meetings to good effect) to London about this time,
ever vigilant to guard the people he had been made
instrumental to gather into a separate society,
against every danger, whereby they might sustain harm,
writ them a short caution on this occasion,
to beware of that disposition which hath a life in strife and contention;
to forbear mutual aggravation, which breeds confusion, but to let their moderation,
temperance and patience appear to all men,
that they might enter into peace and covenant with their Creator,
and preserve their fellowship one with another: his care was exercised towards all,
the weak especially, to whom I apprehend this caution was addressed,
for except a very few weak members the body at large took no part with James Nayler.^
footnote:[Upon Robert Barclay`'s opponent saying, "`One thing I would ask, what he,
Robert Barclay, thinketh of that honour and worship that was given to James Nayler,
as he rode into Bristol, October 24th,
1656?`"
{footnote-paragraph-split}
Robert Barclay answers,
"`I think it was both wicked and abominable, and so do the people called Quakers,
who thereupon disowned him, and all those that had an hand in it,
as by the several letters found written to him and other papers, if need were,
I could at large prove; but it sufficeth to inform the reader of this,
that he was denied by that people,
and not any ways owned by them until several years afterwards,
that he testified his full repentance for that thing
in a public assembly with many tears,
signifying the same also under his hand, which was also printed.`"
{footnote-paragraph-split}
[.book-title]#Robert Barclay`'s Works#,
page 876.
{footnote-paragraph-split}
James
Nayler himself gives the following account:
"`After I was put into the hole at bridewell,
I heard of many wild actions done by a sort of people who pretended that they owned me;
and these were earnestly stirred up at that day with
much violence and many unseemly actions,
to go into the meetings of the people of the Lord, called Quakers,
on purpose to hinder their peaceable meetings,
and yet would take that holy and pure name of God and Christ frequently in their mouths,
whereby the name of the Lord was much dishonoured and his pure spirit grieved,
and much disorder they caused in many places of the nation,
to the dishonour of Christ Jesus, for which I feel wrath from God;
which when I understood that they had any strength through me,
I used all means I could to declare against that evil spirit,
which under the name of God and Christ, was against God and Christ,
his truth and People.]

This year died John Camm of Camm`'s-gill, in the barony of Kendal in Westmoreland,
a man blessed with religious inclinations from his childhood,
which gathered strength as he approached the state of maturity,
whereby he was incited in a sincere inquiry after true, religion,
and the most certain way to salvation,
to separate himself from the national worship of that time,
and associate with several others, who from a similarity of impression and pursuit,
formed a select assembly at Firbank chapel and other places,
amongst whom he sometimes officiated as minister.
Here it was that he,
with the greater part of that congregation in the
notable meeting which George Fox had there in 1653,
by his effectual ministry,
was happily prevailed with to turn the attention of his mind more
closely to the measure and manifestation of the spirit,
which he recommended, as a certain guide from darkness to light;
in obedience whereunto he was made willing to take up the
cross to the glory and friendship of this world,
in endeavours to secure an everlasting inheritance in that which is to come.
And abiding in patience the refining operation of this sanctifying grace,
he was fitly prepared for the reception of the gifts of the spirit,
and had a share in the ministry committed to him,
more formed to reach the heart than please the ear, being weighty and deep,
conveying awakening reproof to the libertine, the hypocrite,
and such as disgraced the profession of truth by a disorderly conversation.
In his moral conduct very circumspect,
exemplifying the doctrine he taught by the example he set.
In the capacity of a parent he conscientiously discharged his duty
in a religious care over his children and family.

He was amongst the first of these preachers who travelled
into different parts of the nation to propagate the Gospel,
according to the principles of the people called Quakers,
in which service he was careful not to make the gospel chargeable,
having an estate of his own.
His first journey was through the northern counties in company to the borders of Scotland;
his next, in company with Francis Howgill, to visit Oliver Cromwell, protector,
on behalf of their brethren under persecution.
Afterwards he travelled in company with Edward Burrough,
through the middle of the nation to London,
where they met with their countrymen John Audland, Francis Howgill, Richard Hubberthorn,
and others from other parts:
From thence John Audland and he became fellow travellers to Bristol,
where their united powerful ministry was effectual
to the convincement and reformation of many hundreds,
as before related in its place.
But the fatigue and exercise of his travels and labour proved too great for his
bodily ability to sustain without feeling the natural effects thereof,
for his constitution, naturally weak, was hereby reduced into a gradual decline;
and as he drew near the termination of his well spent life,
supported by the testimony of an approving heart,
he viewed the awful scene without dismay.
His indisposition being sanctified to him by that word that sanctified his soul,
he was filled with a thankful sense of divine goodness,
under the impression whereof he thus expressed his lively hope:
"`How great a benefit do I enjoy beyond many,
who have such a large time of preparation for death,
being daily dying that I may live forever with my God in
that kingdom which is unspeakably full of glory.
My outward man daily wastes and moulders down, and draws towards his place and center;
but my inward man revives,
and mounts upwards towards its place and habitation in heaven.`"

The morning he departed this life he called his wife, children and family,
to whom he imparted solid instruction, to love and serve the Lord,
and to walk circumspectly in his fear, adding, that "`his glass was run;
the time of his departure was come;
he was to enter into everlasting joy and rest charging them all "`to be
patient and content in his removal;`" presently after fainting,
he seemed to pass quietly away, as falling into an easy sleep, where upon some about him,
weeping aloud, as one awakened out of sleep, he expressed himself again in these words:
"`My dear hearts, you have wronged me and disturbed me, for I was at sweet rest:
You should not so passionately sorrow for my departure:
This house of clay must go to its place,
but this soul and spirit is to be gathered up to the Lord, to live with him forever,
where we shall meet with everlasting joy.`"
So again taking his leave of them, and repeating his charge, he lay down,
and in a little time departed this life, in the fifty-second year of his age.
