== Chapter X.

[.chapter-synopsis]
* George Fox applies to Oliver Cromwell to stop Persecution
* Edward Burrough writes to him on the same Subject
* Attempt to make Cromwell King
* Articles relating to Religion
* Remarks
* The excluded Members admitted into Parliament, which is soon after dissolved
* Fruitless Applications for Relief from Persecution
* Edward Burrough`'s Proposal to vindicate the Doctrines of the People called Quakers rejected

George Fox, near London, seeing a concourse of people,
found they were gathered to see the protector passing by;
and as the persecution of his friends continued unabated,
he rode up to the coach side to speak with him thereupon,
continuing in discourse with him on the subject till they came to James`'s park gate,
and at parting, Cromwell desired him to come to him at Whitehall:
He accordingly went thither, accompanied by Edward Pyott,
where they opened the subject more fully,
acquainting him with the sufferings of their brethren,
and remonstrating against persecution, as entirely inconsistent with Christianity,
and a manifest deviation from the example of Christ and his apostles,
who suffered persecution, but never persecuted any.

About the same time Edward Burrough also, finding his former applications ineffectual,
resumed his pen and wrote several epistles to Oliver on the same subject,
with his usual plainness.
The following extracts whereof give us a specimen of the honest simplicity and
undisguised plain dealing which these men used in their applications for redress,
not (as falsely represented) in contempt of authority,
but in conformity to the dictates of their consciences,
which taught them to decline every appearance of flattery
and refinement in their addresses to the greatest,
as apprehending these things inconsistent with the simplicity
and godly sincerity recommended in the gospel:
These extracts also exhibiting a lively description of the
sufferings which this people at that time endured,
are a confirmation of the narrative thereof, comprized in the preceding pages.

After reminding the Protector of the obligation he was under
to the supreme being for his providential favours,
both in prospering his undertakings and preserving him from
the plots and treacherous designs of his enemies,
he proceeds:

[.embedded-content-document.letter]
--

In that day when thou was raised up, when the fear of the Lord was before thy face,
and thy heart was towards him, and thou was but little in thine own eyes,
it was well with thee, and the Lord blessed thee;
and it was not once thought concerning thee,
that the hands of the ungodly would have been strengthened
against the righteous under thee,
or that such grievous and cruel burdens and oppressions
would ever have been laid upon the just,
and acted against them in thy name and under thy dominion,
as unrighteously have come to pass in these three years.
Many are unjustly and woefully sufferers, because they cannot swear,
though in all cases they speak the truth, and obey Christ`'s commands;
such are punished by unjust fines imposed upon them,
and this by the corruptness of some that bear rule under thee,
who rule not for God as they ought, but invert the sword of justice.
Some suffer long and tedious imprisonments, and others cruel stripes and abuses,
and danger of life many times from wicked men,
for reproving sin and crying against the abominations of the times
(which the scriptures testify against) in streets and other places.
Some have been taken up on the highway, sent to prison,
and no crime charged against them; and others committed,
being taken out of peaceable meetings, whipped, and sent to prison,
without transgressing any law, just or unjust,
through the rage and envy of such who have perverted judgment and justice;
and some in prison have suffered superabundantly
from the hands of the cruel jailers and their servants,
by beatings and threatenings, and putting irons on them,
and not suffering any of their friends to visit them with necessaries;
and some have died in the prisons, whose lives were not dear to them,
whose blood will be reckoned on account against thee in one day.
Some have suffered hard cruelties, because they could not respect persons,
and bow with hat or knee;
and from these cruelties thou canst not altogether be excused in the sight of God,
being inflicted in thy name and under thy power.

--

A copy of the letter from which this extract was
taken was delivered into Oliver Cromwell`'s own hands;
but not producing the desired effect, he soon after waited upon him in person,
to procure a conference with him upon the subject,
in the course of which Cromwell told him in effect that
all persecution and cruelty were against his mind,
and that he was not guilty of those persecutions
carried on unjustly against Burrough`'s friends.
The futility of this excuse, too apparent to escape Burrough`'s penetration,
drew from him the following remonstrance:

[.embedded-content-document.letter]
--

Consider what is the cause, that what thou desirest: not to be done is yet done:
Is it not that thou mayest please men?
that thou mayest do the false teachers of this nation and wicked men a pleasure:
Thou knowest of some in this city and elsewhere, whom we know to be just men,
who suffer imprisonment and the loss of their liberty,
because for conscience sake they cannot swear;
and many others in this nation suffering cruel treatment even for well-doing,
and not for evil, which oppression might be put a stop to,
and their unjust sufferings relieved by thee, by a word of thy mouth or pen,
shewing thy dislike of these cruel persecutions;
but there seems in thee rather a favouring of them,
by connivance at the actors of cruelty, to the strengthening of their hands,
than any dislike shewn by thee, in bearing witness, as thou oughtest to do, against them;
and this makes that thou canst not be clear in the sight of God in these things,
because not helped by thee, when thou hast power to help them.`"^
footnote:[Sewel p. 165]

--

These honest remonstrances met the like reception with former applications;
they were received without apparent resentment,
and persecutions carried on without redress.
Cromwell`'s attention about this period was engrossed by a subject
much nearer his heart than redressing the grievances of this society.
The supple parliament now sitting, entirely devoted to his humour and to his interest,
had complimented him with the offer of the crown and the title of king,
and although it is thought to have been in consequence of his own management,
and his ambition prompted him to accept the offer,
yet finding his nearest friends and most powerful partisans,
together with the body of the army, averse to the measure,
deterred by the prospect of the danger attending this advancement,
after some perplexity and hesitation,
he finally determined to reject the proffered crown.

The parliament upon this confirmed to him his dignity of protector,
with an addition of more power, in some instances,
than had been annexed to it by the council of officers, by a solemn act,
entitled "`The humble petition and advice,`" which
after investing him with power to name his successor,
to convoke a yearly parliament composed of two houses, and settling his revenue,
concluded with the following articles relating to religion:

[.embedded-content-document.legal]
--

That his highness would encourage a godly ministry in these nations;
and that such as do revile and disturb them in the worship of God,
may be punished according to law, and where laws are defective, new ones to be made:
That the protestant christian religion, as it is contained in the Old and New Testament,
be asserted and held forth for the public profession of these nations, and no other;
and that a confession of faith be agreed upon and
recommended to the people of these nations;
and none to be permitted by word or writing to revile
or reproach the said confession of faith.^
footnote:[Rapin]

--

These articles seem to betray little liberality of
sentiment concerning religious or civil liberty,
and whether they originated from Cromwell himself or the parliament,
give us a specimen of the change of principles effected
in men by the possession of power,
according to the concurrent accounts historians have
given us of the independents and their principles:

[quote]
____
The fanaticism of the independents abolished all ecclesiastical government,
disdained all creeds and systems, and rejected every ceremony.
Of all christian sects this was the first, which,
during its prosperity as well as its adversity,
always adopted the principle of toleration;
and it is remarkable that so reasonable a doctrine owed its origin, not to reasoning,
but to the height of extravagance and fanaticism.^
footnote:[Hume]
____

[quote]
____
The doctrine of toleration, in these enlightened ages,
adopted by the liberal of almost all persuasions, owed its origin to the independents,
whose declared aversion to persecution and church tyranny was too opposite to the bigotry
and views of the presbyterians not to be productive of high contest and animosity.
Whilst the presbyterians exclaimed that toleration was but an indulgence for soul-murder,
etc. the independents, from the authority of the gospel and the dictates of reason,
argued that every man had a right to direct his religious conscience,
and interpret the scriptures according to his own lights and apprehensions;
that the doctrine of intolerancy would equally justify all religious persecutions,
pagans against christians, papists against protestants,
with that which had been so lately endured from the power of the episcopacy;
and that the presbyterians,
by preaching up the doctrine of obedience in spiritual matters to established powers,
passed a self-condemnation on their own opposition to former tyrannies.^
footnote:[Macauly]
____

These sentiments are laudable, and the reasoning upon them just;
but I think the first quoted author hath gone too far in asserting,
that they always adopted the principle of toleration in prosperity as well as adversity,
except we understand it as a mere speculative truth,
for that they always adopted it in practice,
matters of fact will not support the assertion.
And if their former principles are justly described by the fore-cited authors,
it appears evidently, from the foregoing articles,
that their principles were changed with the times.
The first seems to be aimed directly at the Quakers,
and the proposal of making new penal laws against
them bears little marks of a tolerating spirit;
the second is expressed in terms of remarkable ambiguity,
yet from this and the next we may gather thus much,
that if formerly they disdained all creeds and systems,
they had now altered their sentiments;
since they propose the formation of a system for the profession of the nation,
exclusive of all others, and a confession of faith^
footnote:[Soon after this a confession of faith,
drawn up by several of the teachers at the Savoy, was published;
and George Fox having previously procured a copy of it,
not withstanding the parliamentary prohibition, he animadverted upon it with freedom,
and published his remarks about the same time, the Church Faith, as they termed it,
was published, which incensed some of the members to that degree,
that one of them threatened him, "`That they must have him to Smithfield.`"
To which menace he replied, he was over their fires and feared them not,
wishing him to consider whether all people had been
without a faith this one thousand hundred years,
that the priests must now make them one;
that as Christ Jesus was the author of the apostles faith,
of that of the primitive church and of the martyrs,
should not all people look unto him to be the author and finisher of their faith,
and not unto the priests?]
so sacredly inviolable,
that both the freedom of speech and the liberty of
the press were to be violated in its favour.

I would not be understood by these occasional remarks to tax the
whole body of the independents with this inconsistency of conduct;
but those only who in contradiction to their former professions,
when invested with power, perverted it to the persecution of such as dissented from them,
and those who fomented the persecution.
There were doubtless very many, more sincere in their profession,
and more uniform in their conduct, who were so far from promoting,
that they secretly condemned these unnecessary severities,
as hath been noticed in James Nayler`'s case and others.
I wish the reader to apply this distinction to my
future observations on this body of men,
as I shall be under a necessity, in the sequel,
to lay open still more exorbitant severities, practised by arbitrary magistrates,
who were instigated by vindictive teachers of this denomination,
against the people called Quakers.

After all,
we need not perhaps admire that the measures of this
parliament were not favourable to liberty:
Men who had given themselves up to act by the nod or direction of another,
having resigned their own liberty,
were not likely to have a tender regard for the liberties of other men.

In the next session of this parliament,
in pursuance of an article in the aforementioned instrument of government,
the members who had parliament been excluded by Oliver`'s
council were admitted to take their seats in the house,
which seems to have produced a majority less favourable to his views,
and less pliant to his will than that of the former sessions;
and their proceedings displeasing him, he soon put a stop thereto by dissolving them.

When we view this parliament, so much devoted to the Protector,
and acting principally under his immediate influence,
enacting laws so unfavourable to liberty, we can hardly exculpate him from encouraging,
at least by connivance, these persecuting acts and severe proceedings,
even while he declared himself against persecution,
and disavowed the guilt of those carried on against the Quakers.

After the dissolution of the parliament, different applications,
by personal interviews and by letters,
were made to the Protector by divers of this people in favour of their persecuted brethren,
laying before him a full narrative of their grievances, which,
when he not only pleaded ignorance of, but pretended not to believe, two of them,
Thomas Aldam, and Anthony Pearson, to put the matter out of dispute,
undertook the laborious task of visiting all or most of the jails in England,
to prove by authentic documents the truth of their representations; which having done,
by procuring copies of their friends commitments under the hands of the respective jailers,
they laid the same before Oliver Cromwell; but now, all subterfuge being taken away,
he declined to comply with their request in behalf of the sufferers,
which was to give order for their release.
It was upon this occasion that Thomas Aldam, taking off his cap, tore it, saying,
"`so shall thy government be rent from thee and thy house.`"^
footnote:[Sewel, 185]

The public preachers at this time,
both palliate and promote persecution and rigorous measures against the Quakers,
so called, took great pains to represent them as a people deluded,
deceived and involved in error; and particularly to Cromwell and others in authority:
For which reason Edward Burrough, in a letter to the Protector,
proposed that these teachers might be directed, abstracted from general reflections,
and vague accusations, to put their objections to the Quakers doctrines,
and their imputed errors, in plain terms and clear propositions;
and that by divine permission they should receive a suitable answer,
concluding his letter to the following purport;

[.embedded-content-document.letter]
--

We are willing to be made manifest to all men,
and that our principles may be brought to the test of true judgment; when,
if any objections against us cannot be answered to
the satisfaction of sober and unprejudiced men,
our adversaries will be more justified in their censures and their severity against us.
But if our answers shall prove our principles,
practices and doctrines agreeable to the scriptures, and vindicated thereby,
then let the truth be owned, and no longer persecuted:
Let the teachers and all our adversaries refrain their contumelious aspersions,
uncharitable railings against us, and false accusations of us to thee:
Let thy ears be shut from believing lies against the innocent;
and let none in thy dominions suffer under the cruelty of men,
upon such groundless pretences.

--

This proposal was fair and reasonable,
but we have no account that it was acceded to by Oliver or his teachers:
The latter found it easier to rail than to reason;
and their hatred of this people impelled them to
endeavour the suppressing of them by rigour,
rather than convincing them by argument.
Persecution continued unabated till Oliver Cromwell`'s death,
which happened on the 3rd of September this year.
And being by the humble petition and advice empowered to nominate his successor,
he nominated his son Richard,
who was accordingly proclaimed Protector of the Commonwealth.
