== Chapter XI.

[.chapter-synopsis]
* Applications continued to Richard Cromwell, but without Success
* Friends violently abused by the Populace
* The Nation in great Commotion
* George Fox writes a Caution
* Account of Friends Sufferings presented to the Parliament
* Remarkable Proposal of a number of Friends to the Parliament
* The Quakers so called invited to take up Arms
* George Fox cautions against it
* General Monk`'s Order to his Soldiers not to molest the Meetings of this People
* Account of their suffering in Property, especially for their Testimony against Tithes
* Specified in various Cases
* Remarks upon Tithes, etc.

The same fraternal compassion for the hardships sustained by their suffering brethren,
which had animated several of this community to make repeated applications
to the late Protector for redress of their grievances,
continued to operate, and produced similar applications to his successor.
Edward Burrough in particular,
who (as before related) made repeated applications
to the father with much plainness of speech,
was not backward, from a sense of duty, and the impulse of brotherly sympathy,
to take the like liberty with his successor.
Very soon after his advancement to the Protectorate,
he communicated by letter to Richard Cromwell,
a clear and concise relation of the sufferings and
persecutions his friends were afflicted with,
putting him in mind that the power of the magistrate, by divine ordination,
was for a terror and restraint to evil-doers,
and the protection and praise of all that do well.
But that at that time, in this nation,
it was diverted from its original purpose to the oppression of the poor, by injustice,
subverting the good laws of God and man to a wrong end, abusing authority,
by turning the sword against just men,
and inflicting punishment on the innocent for righteousness sake.

This remonstrance met with the same disregard as the former applications for redress.
The persecution of the Quakers (so called) received no check in consequence thereof,
that I can find.
But, as in this interval between Cromwell`'s death and the restoration of Charles the second,
through the ambitious struggles,
and the alternate success or failure of the contending parties for the sovereignty,
the nation was almost in a state of anarchy; gross abuses of the licentious rabble,
instigated by the inflammatory calumnies of the priests against the Quakers
(so called) were added to the severity of persecuting magistrates,
who not confining themselves to the abuse of individuals,
began to disturb and attack these devoted people
in their public assemblies for divine worship,
in a shameful and riotous manner;
of which we have many instances in this and the succeeding year.^
footnote:[At a meeting near Zanchy, where Elizabeth Leavens was preaching,
a rude company, headed by an elder of their church, pulled her down and abused her much.
As she and others were going home, the people fell upon them and grieviously beat several.
{footnote-paragraph-split}
Rebecca Barnes, Elizabeth Holme and others,
coming from a meeting near Ormskirk, met with David Ellison, a priest,
to whom Rebecca spake some words which displeased him;
the persons who accompanied the priest fell to abusing her, while he animated them,
crying out, "`down with her,
down with her,`" which his cruel comrades effectually performed, for they beat, bruised,
and struck her on the breast so cruelly, that within seven days after she died.
Besse,
Vol 1. p. 304.
{footnote-paragraph-split}
On the
7th of the month called June was a meeting at London,
the house of William Mullins of Vine-street, Holborn, when one Atkins,
bailiff to the Earl of Southampton, came to the window,
swearing desperately that he would quake them; and gathered a mob,
whom he heated with strong drink, until they threw dirt and stones in at the window,
and shamefully abused many there assembled, he pushing his sword in at the window,
and threatening to strike his dagger into the preacher`'s face,
calling him reproachful names, and belching out all manner of evil speaking,
till the meeting was ended.
{footnote-paragraph-split}
On the 7th of the month called April, this year,
was a meeting at the house of Thomas Budd, in the parish of Martock,
to which five priests came, attended by a rabble, furnished with staves, cudgels,
pitchforks, and such like rustic arms.
They rushed into the meeting with so much confusion and noise,
that the preacher could not be heard: Their coming made it indeed a riotous assembly,
which the moment before was a congregation of grave and serious christians,
of sober and virtuous conversation, and some of them of considerable estates: However,
the priests who brought the mob, and caused the riot,
complained to the magistrates that the meeting held at Thomas Budd`'s was a riotous assembly,
to the disturbance of the public peace; whereupon one Captain Raymond, with his soldiers,
was ordered to disperse the next meeting that should be held there:
Accordingly he came thither on the 23rd of the month,
when Thomas Salthouse was preaching, and took him, together with Thomas Budd,
into custody, and conducting them next day to Robert Hunt, justice of the peace,
they were by him and others examined and committed to prison,
and indicted for a riot at the quarter sessions at Ilchester:
Great endeavours were used to find them and others taken with them guilty thereof,
yet their attempts were frustrated by the concurring
testimonies of the witnesses produced against them;
whereupon the justices tendered the oath of abjuration to Thomas Salthouse,
and for refusing to take it fined him five pounds.
{footnote-paragraph-split}
On the 27th of the month called June, this year,
was a meeting in the borough of Liskeard, where a multitude of rude people came in,
hallooing, singing, railing, throwing flirt, stones, mire,
and filthy excrements on the clothes, heads and faces of those that were met,
beating some with clubs, others with their fists,
and breaking a pitcher about the head of George Bewley.
One wicked fellow sounded an hunting horn, and raised a cry of his hounds,
to drown the voice of the preacher.
They threw George Bewley and others down a steep hill on the pavement;
and while they were pulling the hair off their heads, the priest,
who sat smoking his pipe in a Chamber window, animated the rabble, crying,
"`Hold him fast, keep him in, if his brains be knocked out, he has his own seeking.`"
This violence continued till some of the persecuted
were almost strangled and ready to faint.
At length some of them being let into an house,
and secured from the inferior mob (for some of the mob were men of figure,
and one a magistrate of the town) the tumult began to cease.
Besse, v. 1. p. 115.
{footnote-paragraph-split}
With much barbarity did
the rabble insult this innocent people assembling at Sawbridgeworth,
striking them as they came thither, throwing them off their horses,
and wallowing them in the mire, daubing their faces and clothes,
filling their hats with dirt, and so putting them on their heads:
When this cruelty could not deter them from meeting,
a rude multitude surrounded the place, and assaulted them, breaking down the tiles,
boards, windows and walls of the meetinghouse, and throwing stones, dirt, rotten eggs,
human dung and urine, that few or none of the assembly escaped unhurt;
They tore their clothes in pieces, laid as dead, sorely bruised others,
and thus continued abusing them for the space of three hours,
the whole time of the meeting, and at their departure repeated the like abuses,
pursuing some of them with stones and dirt about two miles.
{footnote-paragraph-split}
It was customary with the scholars at Cambridge,
when any of this people passed the streets to or from their meetings,
to throw dirt and stones at them, to tear their clothes and spit in their faces.
In their public meetings the scholars insulted them by breaking the windows,
throwing great stones and mooting bullets in, to the hazard of their lives.
When William Allen, who was frequently concerned to preach in those meetings,
was declaring, they would run through the meetinghouse like wild horses,
throwing down all before them, hallooing, stamping and making a noise,
as if several drums had been beating, to prevent his being heard: while he was speaking,
they threw stones at him, broke his head in several places,
cut his face and bruised his body;
he nevertheless persisted in his known duty undismayed.
In like manner did they abuse others of the assembly,
pulling off the women`'s headclothes, and daubing their faces with filth and excrements.
Some of the barbarities were acted in the sight of
the senior fellows and proctor of the college,
who shewed no dislike thereat; and when Alderman Nicholson, a sober and moderate man,
grieved at such inhumanity, complained to the proctor,
desiring him to use his authority to keep the scholars quiet,
he churlishly answered that he could not, nor would not.
{footnote-paragraph-split}
On the 7th of November, this year, William Dewsberry,
preaching at a meeting at Newark upon Trent, was insulted and much abused by the people;
however, the meeting was held, though through much disturbance,
and at the close of it another meeting was appointed
at the same place on the 11th of same month,
being the first day of the week, at which while the testimony of truth was declaring,
a rude multitude broke in, thrusting down both men and women, buffeting,
punching and stoning them, so that some were knocked down,
others had their teeth beaten out and their faces bruised;
women had their head-clothes pulled off.
After this manner they continued to abuse about an
hundred persons who were there religiously assembled,
and who bore all patiently as Christian sufferers.
{footnote-paragraph-split}
On the 22nd of the month called March, this year,
was a meeting at the market-cross in Glastonbury, where Edward Burrough preached.
Samuel Winney, priest of that parish, attended by some drunken fellows with a drum,
came thither, and demanded by what authority he came there to preach?
Edward answered in the scripture phrase, he that hath received a gift,
let him minister according to the gift received.
He then returned the question upon the priest,
desiring him to prove his call to the ministry from scripture.
This pinched him, and he withdrew, leaving the rabble to plead his cause,
who fell to beating their drum, whooping,
hallooing and thrusting the friends to and fro in a wild and barbarous manner;
and it was said that one of the priest`'s agents had made many of the mob drunk on purpose
to qualify them to perform such wicked service for the church.
{footnote-paragraph-split}
On the 17th of the month called May,
a rabble raised by beat of drum came to the meeting at Broad Cerne, beset the house,
fired guns under the windows, beat those that were met with poles and with their guns,
stoned them through the streets and hurt several of them,
so that some spit blood a long time after, and others were sorely bruised,
narrowly escaping with their lives.]

Many of these abuses being committed on the first day of the week, the day they called,
their sabbath, with impunity, under a government,
and by a people who pretended to make it a point
to observe it with all the pharisaical strictness,
and in many cases beyond the strictness which the
mosaical law appointed for observing the seventh,
furnish an occasion to reflect upon the irrational
inconsistency of superstition in every shape,
by which I understand an overzealous attachment to some circumstantials of religion,
while the essential part, viz. the inwardly sanctifying power thereof,
whereby we are taught to honour God, and love and do good to mankind, is overlooked.
These men, it`'s probable,
would have thought it a heinous crime to have been
employed on that day in any honest labour,
though in itself lawful, and in some sort necessary,
and yet shewed no reluctance or compunction in committing unlawful actions,
as opposite to good government as to religion, in assaulting the persons,
and destroying the property of their inoffensive,
unresisting neighbours and fellow citizens, with violence and outrage,
whose only crime was the applying the day to the best purpose,
the assembling to worship their maker in that way they were
persuaded in their consciences was most acceptable to him.
The magistrates and teachers also could not only
let such riots pass unpunished and uncensured,
but too often abet them,
and at the same time and confine several of these people as sabbath-breakers,^
footnote:[Such was the superstition of those times,
that many of the people called Quakers,
going to religious meetings a few miles distant from their own dwellings,
were taken up by officers under pretence of breaking the Sabbath,
had their horses impounded,
and sometimes detained for a penalty of ten shillings for travelling on that day;
and at other times themselves, for refusing to pay that penalty, were set in the stocks.
{footnote-paragraph-split}
The religious zeal of
this people in frequenting their assemblies for worship,
obliged them to travel to the places where they were held,
which being sometimes at a considerable distance,
their going to or coming from them on the first day
of the week was called a breach of the Sabbath,
and punished by fines, distress of goods or imprisonment.
For this cause, Samuel Skillingham and Zachary Child,
going to a meeting at Weathersfield, were stopped by wardens in the street,
and sorely beaten and abused by a justice`'s clerk:
and for the same cause Elizabeth Court was sent to the house of correction,
where she was whipped and suffered much cruel usage,
being kept without candle or fire in the cold winter when she was sick of an ague.
John Child, for riding to a meeting,
had his horse taken away and kept from him three weeks,
and then returned home without bridle, saddle, pillion or cloth,
all which they detained for a pretended forfeiture.
Edmund Cross, John Pike, Richard Waite and William Halley,
were taken out of a meeting at Horsley and set in the stocks
six hours for coming thither on the Sabbath day,
etc. etc. George Taylor and his wife,
riding on the first day of the first week to Puddimore meeting,
had one of their horses taken away; and on the same day of the next week,
passing thither again through Ilchester, had their mare taken away, with saddle,
pillion and bridle.
In like manner Christopher Pittard`'s horse was taken
from him as he was riding to the same meeting:
at which meeting,
the justices Hunt and Cary being informed that Thomas Budd`'s wife was present,
they granted their warrant for levying ten shillings upon her husband`'s goods.
About the same time, Christopher Bacon of Sutton, going to Puddimore meeting,
by the way went to visit his friends in Ilchester jail, where he was taken by the watch;
after three days detention there he was sent to prison,
where he lay three months till the sessions,
at which he was fined five pounds for not taking off his hat, and recommitted.
{footnote-paragraph-split}
Anne Upcot, daughter to the priest of Anstell,
being convinced of the truth, separated from the public worship,
and testified against the vain conversation of the professors of those times:
this incensed her father and three brothers against her,
so that they sought occasion to prosecute her,
a peculiar instance of which is as follows, viz. on the first day of the week,
as she was putting on her clothes, she found her waist coat torn, and was mending it,
when one of her sisters came into the room; she acquainted her brother,
who also was constable, he goes to a justice and gets a warrant to bring her before him,
who ordered her to pay five shillings for Sabbath breaking,
and authorized her brother either to levy the same upon her goods,
or set her in the stocks.
The spiteful brother took the rougher course,
and put her in the stocks in a time of much rain,
himself with his father and brothers being placed in a window hard by,
and from thence jeering and scoffing at her,
and encouraging the boys and other rabble to abuse her,
insomuch that some of the neighbours wept to see their unnatural usage of her;
which cruelty of theirs affords this observation,
that men of ill morals may be extremely superstitious.]
for riding, a few miles to a meeting on that day:
Proving their ostentatious religion to be like that of the Pharisees,
who would strain at a gnat and swallow a camel.

In this year the nation was in great commotion and fluctuation.
Oliver Cromwell, notwithstanding the authority he possessed,
notwithstanding his reputed political abilities, his penetration,
his artful duplicity and address,
is said to have felt himself greatly embarrassed
and perplexed near the close of his time,
to manage the different contending parties into which the nation was divided;
but after he was removed, his successor not inheriting his father`'s capacity,
experience or dissimulation, being a man rather of a tranquil and pacific disposition,
and more adapted to fill a private station than to guide the helm of government,
in these days of turbulence and confusion,
the different factions were upon the watch for some event
or revolution favourable to their respective interests,
and the repossession of the supreme power, which Oliver had wrested from them all.
Party animosities revived with additional heat.
The officers of the army, the republicans and royalists, all caballing,
plotting and waiting the favourable season to promote
a revolution in support of their own power.
George Fox, solicitously concerned for the preservation of his friends in an honest,
quiet and peaceable life, and fearful lest any young or unexperienced people,
who might sometime come amongst them,
might be drawn into associations with one or other of these parties,
wrote an epistle of caution,
where in he admonishes his friends "`to live in love and peace with all men,
to keep clear of all the commotions of the world,
and not to intermeddle with the powers of the earth,
but to let their conversation be in heaven,
which is above all the combustions of the earth,
to let the innocence of their lives and circumspection of their
conduct manifest to all men the spirit of the gospel of Christ;
that whereas those who speak evil of them,
beholding their chaste conversation coupled with fear,
might glorify their Father which is in heaven.`"
And he thus remarks: "`All that pretend to fight for Christ are deceived,
for his kingdom is not of this world, therefore his servants do not fight.`"
All that pretend to fight for the gospel are deceived,
for the gospel is the power of God "`unto salvation,`" and the distinguishing
characteristic thereof is peace on earth and good will towards men;`"
he seems to have the Millenarians or fifth-monarchy men in view,^
footnote:[Rapin]
who by an absurd combination of wild inconsistencies had brought themselves to a belief,
that the time was come to erect a fifth monarchy,
or the reign of Jesus Christ upon earth,
and that they were obliged in conscience to use their utmost endeavours to promote it,
even by force of arms,
as if Christ wanted the assistance of weak mortals
to effect his purposes or assert his rights:
Or the Prince of Peace, who came to save men`'s lives and not destroy them,
would establish his kingdom by compulsion, violence and bloodshed.

Afterwards a printed account of their sufferings was presented
to the parliament which this Protector convened,
exhibiting a relation of above one hundred and forty then in prison,
and of one thousand nine hundred who had suffered in the last six years,
twenty-one of whom had died in prison, generally by hardship or by violent abuses.
But the unmerited prejudices of the age ran in a current so strong against that people,
as to bear down every sentiment of compassion.
Amongst the different classes into whose hands the government fell,
none could be prevailed upon to yield them effectual relief.

The principal officers in the army,
who had been the chief instruments of promoting Richard`'s succession to the Protectorate,
had exerted their influence, principally from self-interested views, in expectation,
under the umbrage of his nominal power,
to hold the reins of government in their own hands.
But Richard, dissatisfied with this shadow of power,
took measures for possessing himself of the real authority,
by an attempt to enlarge the number of the Privy Council,
so as to introduce a majority of his own creatures,
and to bring the army to a dependence on himself.
These measures roused the jealousy of the officers,
and the parliament now sitting having also discovered a purpose to weaken their influence,
they combined together to force Richard to dissolve this parliament,
and shortly after restored the supreme authority to the remnant of the long parliament,
now reduced to about forty in number.

We have had sundry occasions to remark the brotherly
affection and sympathy abounding amongst this people,
manifested by a mutual concern for each other`'s welfare;
and that while they seemed each regardless of his own liberty,
they were strenuous advocates for that of their brethren,
zealously and almost incessantly in their several turns,
representing to those successively in authority the suffering cases of their friends,
either by word of mouth, in writing or in print.
So upon this change of government,
fresh application was made to this parliament for relief in a very extraordinary proposal:
A printed paper presented to them,
subscribed by one hundred and sixty-four of this people,
wherein (referring to the account of their sufferings before presented
to the parliament) they offer themselves freely person for person to lie
in prison instead of such of their brethren as were under confinement,
and might be in danger of losing their lives from the length and extremity
of their imprisonment as several of their brethren had done,
whereby they demonstrated the perfection of christian charity amongst themselves,
and left their oppressors without excuse,
although their offer was rejected with some marks of resentment.^
footnote:[I find Macauley`'s [.book-title]#Hist. Ann 1659# the following note:
"`Even so early as the commencement of the last parliament,
when the bill for recognizing Richard was in debate,
a petition in favour of a republic was presented
to the house by a formidable body of citizens;
and after the army had declared themselves,
was seconded by another from the sectaries called Quakers.
This last petition was highly resented, and the following angry answer returned;
That the house had read the paper,
and did dislike the scandals thereby cast upon magistracy and ministry;
and did therefore order that the petitioners should
forthwith resort to their respective habitations,
and there apply themselves to their callings,
and submit to the laws of the nation and the magistracy.`"--What
I have to remark on this note is,
that I apprehend a mistake as to the purport of the
petition presented by the people called Quakers,
so far as it conveys an idea of their petitioning
for a republic or restoration of the long parliament.
It was an established principle with them to demean themselves
quietly and peaceably under that government which providence might
permit to exercise the rule over them in their temporal concerns,
reserving to the divine Being What properly belonged to him,
and in their estimation to him alone the dominion over their consciences.
But (as far as I can discover) they attached themselves to none
of the political parties which at that time distempered the state,
having been treated with severity by all in their turns;
having made successively ineffectual application for redress of their grievances,
and met with nothing but rejection, indignities and contempt,
they had no political reason for wishing well to any one
of the present contending powers above the other,
as all were their adversaries.
And it was with them a principle of religion to have no intermeddling with secular factions;
for notwithstanding the contemptuous light in which they were generally viewed and represented,
they were undoubtedly actuated by as clear notions of the
essence of Christianity and the spirit of the gospel,
as any other sect at that time existing, in authority at least,
being thereby convinced that the kingdom of Christ was not of this world,
and that of consequence the smugglers for worldly
power were not establishes of the kingdom of Christ,
which was their principal aim.
Ignorant as they are generally represented,
they had the good sense to discern the selfish views
and partial politics of all these parties,
under the disguise of plausible professions, and that all were guilty of palpable errors:
{footnote-paragraph-split}
`    Seditione, dolis, scelere atque libidine & Ira
     Iliacos intra muros peccatur; & extra.
     - - - - - -
     In factious deeds, deceit or lust or rage,
     Republicans and royalists engage. `
{footnote-paragraph-split}
Under these circumstances, I meet with no addresses of theirs to the ruling powers of this era;
but either plain and honest testimonies of individuals against their unrighteous
application of the power in their hand,
or remonstrances in a collective capacity of their grievous sufferings,
and applications for relief: Of the latter sort is the above,
which I presume is the petition mentioned in the note,
which as it contained a full account of their grievous sufferings under arbitrary magistrates,
instigated by their vindictive teachers to treat them with illicit severity,
such representation of real fact being displeasing to the parliament,
as it was disgraceful to their government, was by them termed
(though indisputable truth) a scandal cast upon the magistracy and ministry.]

Commotions still continued in the nation.
The royalists, meditated a general insurrection, and George Booth, in Cheshire,
rising in arms in favour of the exiled monarch,
the committee of safety invited the Quakers, so called, to take up arms,
offering considerable posts and commands, to some of them:
But being very sincere in their profession of religion,
and esteeming war and violence inconsistent with pure Christianity;
steady to those principles they believed true,
the prospect of human honour and worldly advancement,
had no place with them to turn them aside from the undeviating pursuit of a point,
in their view, of much higher importance,
the endeavouring to secure to themselves admission in that
kingdom which is higher than all the kingdoms of this world.
Yet some unsettled and inconsiderate persons who at times seemed to associate with them,
appearing inclined to comply with these proposals, and take up arms under Lambert,
George Fox found it his duty, by an epistle to caution them against it,
and his concern for their preservation had the desired effect.

Edward Burrough,
indefatigable in his endeavours to procure some relief for his brethren under suffering,
wrote very copiously and plainly to the successive governors of the nation;
and in sundry letters was concerned to tell them (particularly
in one to the parliament now sitting) that if they desisted not
from persecuting the innocent their power would be cut short,
which the event proved to be a true prediction.

During this time of anarchy,
the meetings of this people being frequently disturbed by the populace,
as before remarked; and when General Monk marched up to London,
some of the soldiers under his command having been guilty of such disturbance,
a complaint was made to the general,
which met with better success than similar applications
to those in authority before had generally done,
as it produced the following order.

[.embedded-content-document.legal]
--

[.signed-section-context-open]
St. James`'s, March 9th, 1659.

I do require all officers and soldiers to forbear
to disturb the peaceable meetings of the Quakers,
they doing nothing prejudicial to the parliament or commonwealth of England.

[.signed-section-signature]
George Monk.

--

Besides the personal injuries they suffered,
to which I have hitherto chiefly confined myself,
they were also exposed to great spoil and depredations in their property,
by unreasonable fines and exorbitant distraints on divers accounts,
and especially for their conscientious refusal to pay tithes,
and other ecclesiastical demands,
which the present preachers (notwithstanding their
representing them as a relict of Judaism,
when in the possession of the Episcopalians) being gotten into the possession of,
were as rigorous and severe in the exaction as their predecessors.
To record all their sufferings for their testimony against the propriety
of these demands under the christian dispensation would fill a large volume.
The few following cases will afford a sufficient specimen of patience under suffering,
extravagant damage and tyrannical malice, in exacting unreasonable demands.

In the month called August, Elizabeth Bruce, a poor widow,
was sent to prison for tithes of small value,
her house and garden being rented but at 6£. per annum,
out of which she supported herself and two fatherless children;
she was continued a long time in prison.

Leonard Cole, for refusing to pay tithes, suffered six weeks imprisonment at Reading,
and soon after his discharge, for a demand of 5s. had an horse taken from him worth 4£.

The aforesaid Leonard Cole was imprisoned twelve weeks at Reading,
and then removed by _Habeas Corpus_ to the Fleet, London; While there,
the priest his prosecutor, with bailiffs,
made a seisure of his corn and cattle to the value
of near 100£. all for one year`'s tithe,
for which the former occupier of the same farm told Cole he used to pay but 6£.

John Richmond suffered distress of his cattle the
value of 40£. for 8£. demanded for tithe.

For 50£. demanded, were taken from John Pollard of Steeple, corn,
etc. to the value of 322£.

On the 9th of the month called July, Richard Attwood was committed to prison for tithes,
where, after a year`'s imprisonment, he died.

In the same month Edward Buden and William Beaseley,
for demands of tithe less than 20s. each,
were sent to jail and detained there above seventeen months.
During their imprisonment the prosecutor took away three
cows from the former and six from the latter of them.

William Wooley was prosecuted in the Exchequer for tithes of but 6d. value.
Rachel Trueman was sued in the Hundred Court,
and for 10s. demanded for tithes had a cow taken from her worth 5£.

John Tyler of Frampton Cotterel, sued by his parish priest for tithe of about 20s. value,
was adjudged by the court to pay 10£. 10s. besides 3£. 10s. costs he had been put to.

Thomas Welsted, for a demand of 3£. for tithes,
had his goods taken away to the value of 12£. 10s. And in this year several
persons for claims of 1£. 9s. 3d. for steeple-house rates,
suffered distress of goods to the value of 11£. 12s.

In this year were taken from Henry Streater, for 4£. demanded for tithes,
three mares and two cows, worth 42£. Robert Biddle,
for a demand of 16s. two horses and two cows, worth 15£.

John Bishop of Gatcomb in the Isle of Wight, a poor labouring man,
having a large family dependent on his labour,
was imprisoned in Winchester jail for tithes twenty weeks.

In this year Elizabeth Maynard, a poor widow, for tithe of about 2s, value,
had a cow taken from her by distress; also Richard North of Yardly,
for tithe of an acre of wheat, had his house ransacked by a bailiff,
when only two little children were at home: He took away beside his household goods,
the wearing apparel of himself and children, and the covering of their beds,
for want of which they were much prejudiced in their health, the weather being cold.
The bailiff had been heard to boast, that now he had to do with Quakers,
he should grow rich, death deprived him of his expectation soon after.

On the 19th of the month called January, this Hunting-year,
Simon Sanford was prosecuted in the Exchequer for tithes under 5£. value,
and committed to Huntingdon jail where he lay seventeen months,
till discharged by order of a committee of parliament.

Edward Noakes of Word near Sandwich, after he had suffered imprisonment at Canterbury,
at the suit of Paul Pettit, an impropriator, for tithes,
was removed to the upper bench at London.
At the next assizes a judgment was obtained against him,
and in the term following an execution, by which,
for tithes valued by the jury at 20£. he suffered distress of cattle to the value of
99£. Moreover this poor man was kept prisoner in the upper bench above two years,
in which time his wife died, and his family suffered much by his absence.
He was also sued by the priest of the parish in the
Exchequer for small tithes at the same time.

Edward Muggleston, after a prosecution in the Exchequer for tithes,
was committed to prison at, Leicester.
While he lay there his son was prosecuted for the same tithe,
though known to be but a servant to his father.

Zachary Gilby of Thifleton was imprisoned in Oakham
jail by an attachment out of the Exchequer:
He was confined there about sixteen weeks amongst felons in a cold nasty place.
John Riddish was also imprisoned there, on an attachment, for tithe of ten groats value,
he being a poor labouring man, and having a wife and five small children.
The woman in her distress applied to the priest, his prosecutor,
to intercede for his liberty, and took, one of her little children with her,
judging that might be a means of moving his companion; but the priest, void of pity,
thrust them out of doors,
and churlishly told her she might get her husband out again how she could.

William Vincent, for a demand of only 4d. for tithes,
was imprisoned in Northampton low jail, at the suit of Thomas Andrews,
priest of Wellingborough, above a year, among felons, by whom he was much abused,
being a very weakly man, and having above a dozen sores about him,
by which he was rendered almost unable to help himself, and obliged to go on crutches.
His miserable case was represented to the priest, who yet shewed no lenity towards him,
but seemed to value the poor man`'s life at less than one groat.

Margaret Parker of Aino on the hill, a poor widow, having three children,
was imprisoned at Northampton seven and twenty months for
tithes of corn and hay less than 13s. 4d. in value.
This poor woman`'s sufferings were grievous, being close confined among murderers,
thieves and whores, where her friends were not admitted to see her,
otherwise than through the key-hole of the door.

Arthur Goddard was arrested for tithes at the Sussex, suit of Richard Rogers,
priest of Clopton, and after he had been six months in custody,
his prosecutor obtained a warrant from two justices to make distress for the same tithe,
and took about four times the value.
Hard was the case of John Causton, imprisoned in Ipswich jail,
in the coldest time of the winter, three months in an open room, under a cruel keeper,
where, through the extreme hardship he endured, he contracted a sickness,
of which he there died.

In this year were taken for tithes,

From William Driver of Tremlic, for 1£ 14s. demanded,
goods worth --12£ From Thomas Pinson of Ditto, for 14£ 1s. demanded,
goods worth -- 57£ From William Burroughs of Great Fenborough, for 30£ 8s. 6d. demanded,
goods worth -- 40£ From Arthur Goddard of Clapton, for 3£ 10s. demanded,
goods worth -- 14£ From Richard White of Mendlelham, for 4£ demanded,
goods worth -- 15£ For 53£ 13s. 6d. Total Taken -- 138£

Lucy Oxe, widow, her son-in-law Christopher Sharpe, and Lucy his wife,
were cast into Melton jail, at the suit of Francis Davis, priest of Clifford;
though the son and daughter had no property in the land out of which the tithe was claimed,
being only servants to their mother.

It may be proper here to remark,
that although at this day the people called Quakers are single
in their opposition against the legality of tithes under the gospel,
yet many others before them,
and many contemporary with those of the first generation as well as they,
looked upon this relic of Judaism to be abolished with the law which appointed them.
That the pure ages of the church they were neither paid nor demanded.
That they were reestablished among the numerous corruptions
introduced in the darkness of a declining age,
and wrested from the people to the sole use of the clergy, so called,
by Romish craft and policy, and were by many of that age esteemed a relic of popery,
retained by a partial reformation,
through the management of self-interested priests and rulers,
and looked upon as an intolerable grievance,
to be abolished in the progress of reformation to apostolical purity;
the redressing whereof, with other grievances, the people were amused with the hopes of,
by those preachers and leaders who had instigated them to arms against
the civil and ecclesiastical encroachments on their liberty and property:
But they were only amused;
for when their leaders attained their aim in reaching the pinnacle of power,
they were more intent on keeping by policy a fast hold of the reins of government,
which they had seized by violence, than to redress the grievances of the subject.
When the dissenting teachers, by the revolutions of the state, became the establishment,
and succeeded to the possession of the ecclesiastical revenues of the episcopalians,
they manifested the genuine spirit of the priesthood,
in securing to themselves the possessions and emoluments of the church,
(so called) and opposing in a body every attempt to lessen them,
or make any alteration therein; being as tenacious of the power, the privileges,
the incomes and the perquisites of the sacerdotal office,
and as oppressive in exacting and recovering them from those,
who from a conscientious scruple withheld them, as those that went before them;
proving that priestcraft in all denominations is the same.
And thus through all the revolutions of government,
and all pretensions of attempting a further and more perfect reformation,
this anti-christian yoke continues unremoved.

Other denominations, to evade suffering, gave up the contest;
but the Quakers still maintain their testimony in this case for primitive purity,
and against Romish corruptions and usurpations, from a conscientious motive,
and therefore rather choose to suffer some loss of property than violate their consciences
by actively upholding a practice which they esteem to be virtually forbidden by Christ,
in his command to the first and best ministers of the gospel,
from whom the following priesthood have idly laid claim,
by uninterrupted succession to power they never thought of,
and emoluments they neither possessed nor desired: "`Freely ye have received,
freely give,`" was the first and plainest ordination sermon,
which this people think amounts to a prohibition not only of tithes,
but of stated and involuntary contributions for the support of gospel ministers;
and therefore it is an established principle with them,
not to pay tithe or any other fixed stipends either to their
own ministers or those appointed by the state.

Being now advanced to a remarkable period,
wherein a thorough revolution in the government and state of the nation took place,
by the reestablishment of monarchy and episcopacy,
in consequence of the restoration of Charles the second to the throne,
which was effected in the month called May this year;
and having confined the narrative to England, as the principal scene of action,
it seems a proper time to look abroad,
and relate the steps taken by sundry members of this society to propagate their doctrines,
and the reception they met with in other parts during this period.
