== Chapter XII.

[.old-style]
=== Wales

[.chapter-synopsis]
* Morgan Floyd, Priest of Wrexham, sends two of his Congregation to make Inquiry after the People called Quakers, when one of them, John Ap John, is convinced
* He is abused by a Priest, and imprisoned
* Thomas Holmes travels in Wales
* George Fox visits Wales
* Is rudely treated at Brecknock
* Many convinced
* Sufferings of this People in this Principality

In the year 1653, while George Fox and his,
fellow-labourers were yet employing their ministerial
labours in the northern parts of England,
divers reports going abroad concerning them, Morgan Floyd,
priest of Wrexham in Denbighshire,
sent two of his congregation into the north to make inquiry concerning this new sect,
who upon meeting and conferring with them,
were so affected with the power attending their discourse and their ministry,
that they were both convinced of their principles,
abode with them some time and then returned home.
One of them, named John Ap-John, retaining his integrity,
in some time after received a gift in the ministry,
and continued a faithful and serviceable member of the society,
and a sharer with his brethren in the tribulations of that day.

For in the year 1655, being in the public worship house at Swanzey,
after the preacher had ended his sermon, he asked him,
whether he was a minister of Christ?
This question gave great offence both to the priest to whom it was addressed,
and another who was present;
this latter gave way to his passion so far as instantly to seize John by the collar,
and without suffering him to speak another word,
dragged him out and delivered him to a constable,
who confined him that night in a close dark prison.
Next day he was brought before the magistrates,
whom these priests endeavoured to incite to persecution, as too usual,
by desiring in their blind zeal, to have him whipped,
that the devil might come out of him: and as often as he attempted to speak,
one or other of the priests would strike him and stop his mouth with their hands.
At length he was sent to prison under a general charge of misbehaviour,
no particular cause of imprisonment being specified in the mittimus,
the fact being in no wise criminal, nor liable to the penalty of any law;
but the justice, to gratify the priests,
stretched his power beyond the letter of the law, to oppress an harmless man,
of which arbitrary rule our history furnishes not a few instances.

In 1654, Thomas Holmes travelled into Wales,
being reputed to be the first minister among the people
called Quakers that preached in that principality;
of his service I do not meet with very particular accounts,
yet there is reason to believe it was effectual to the convincement of several,
as in the year 1656 I find that from seven persons of this society in Glamorganshire,
for 8£. 10s. 6d. demanded for tithes,
their goods were taken by distress to the amount of 28£.
8s. And from nine in Radnorshire for 4£. 3s. 4d. demanded,
to the amount of 23£. 6s. 8d. was taken.

In the forepart of 1657, George Fox first visited some parts of Wales:
From Bristol coming to Cardiff, a justice of peace sent him a message, desiring,
"`he with half a dozen of his friends would come to his house;`" accordingly he went,
accompanied by a few of his friends,
and met with a courteous reception from the justice and his wife.
The next day he had a meeting there, which notwithstanding some attempts of disturbance,
was held to good satisfaction,
and many were convinced of the truth of the doctrines he published that day.

At Swanzey also his labour was blessed with remarkable success,
and a settled meeting of this society established there.
At Brecknock he met with rude treatment, and apprehension of danger from the populace,
raised and stimulated to riot and tumult by the magistrates.
Next morning he wrote a paper to the town, to point out their unchristian-like behaviour,
and how contrary it was to true religion and virtue.

From hence he went to a great meeting in a steeple-house yard, to which many people came,
and amongst the rest Walter Jenkin, who had been a justice,
accompanied by another justice:
his ministry here was effectual to the convincement of many: after the meeting,
he went with Walter Jenkin to the aforesaid justice`'s house,
who expressed his approbation of his service, saying,
"`you have this day given great satisfaction to the people,
and answered all the objections that were in their minds.`"

He next proceeded to Pontemoil, had a great meeting there,
which several people of account attended, and so many were there convinced,
that a large meeting was gathered and established in these parts.
From hence he returned to England.

As to the sufferings and persecutions of this people in Wales,
as their numbers were not very large during this period,
their sufferings were less multiplied, yet chiefly through the instigation of priests,
they bore a share of the afflictions of their brethren, in imprisonments,
in personal abuse, in the disturbance of their meetings, and distresses for tithes,
and those called church-rates,
and although some of them were remarkable and severe enough,
particularly the sufferings of John-ap-John and Elizabeth Holmes,
yet to avoid prolixity on a subject everywhere supplying abundant matter for reflection,
I pass on to:

[.old-style]
=== Scotland

The earliest meetings of the people called Quakers
in Scotland were held about the year 1653;
when several serious enquirers into the nature of true religion,
and the purity and spirituality of gospel-worship, burdened with the formality,
superstition and will-worship,
under which the national preachers laboured to keep their hearers in bondage,
began to separate from the public assemblies,
and to meet together by themselves to wait upon God in silence, and to worship him,
who is a spirit, in spirit and in truth.
As they were thus exercised in an holy silence, and awful humility of soul,
they came to experience the quickening virtue, power and influence,
of the holy spirit of God, enabling some of them to speak forth his praise,
and from a sense of his goodness to become instrumental
for the edification of others in the faith.
The first natives of this country,
who distinguished themselves as preachers among this people, were William Osborne,
Richard Ree, and Alexander Hamilton: This Alexander Hamilton, with his wife and sister,
had been members of a church or society of independents,
whereof one Thomas Chartres was the pastor or teacher.
Their departure from the church was regretted by the rest of the society,
they being persons esteemed for their regular life and religious deportment,
and Charles would willingly have induced them to come again and sit under his teachings,
but finding all his endeavours to that purpose ineffectual,
he at length threatened them with excommunication,
and appointed a day for passing that sentence,
giving the said Alexander Hamilton previous notice thereof.
Hamilton warned him to forbear, lest the anger of the Lord should be provoked against him.
This caution Chartres regarded not, but answered,
it is but Alexander Hamilton that says so: To which Hamilton,
in the presence of many witnesses, replied, that it was not only he,
but what he had said, was of the Lord.
But Chartres persisted in his resolution,
which yet he was prevented from putting into execution, in a remarkable manner,
whether providentially, or accidentally, we leave to our readers judgment,
and shall only relate the matter of fact, being as follows,
viz. About two days before the time he had fixed for pronouncing
the sentence of excommunication against the said persons,
as he was walking in the steeple-house yard, where his horse was grazing,
he stepped to him to stroke him,
when the horse gave him such a violent kick on the side as proved mortal,
and occasioned his death about the same time in which
he had purposed to pass the said sentence.
By this means his design was frustrated, and the curse causeless did not come. Prov. 26:2.

Some of the first of this people from England, travelled into Scotland,
were Christopher Fell, George Wilson, John Grave, Sarah Chevers, and Katharine Evans;
also Miles Halhead and James Lancaster, who in the year 1654, being at Dumfries,
and Miles,
after the priest had ended his customary performance in the steeple-house there,
testifying against the deceit and hypocrisy of the people, they were so enraged,
that they forced him and his companion out of the town to the side of a great river,
intending there to have stoned them, but they by wading through the river,
escaped their hands.
After which they were at Edinburgh about ten days,
where Miles delivered to the officers and captains of the army and garrisons his message,
which was, that the anger of the Lord was kindled against them,
because they had not performed their promises,
which they made to him in the day of their distress,
when the enemies compassed them on every side,
for then the Lord delivered them and gave them the victory,
but they had returned him evil for good,
and committed violence against those he had sent to declare his word among them.
Having performed his duty in this respect, they went to Glasgow and Sterling,
and then returned to England.

Anno 1655.
William Caton and John Stubbs visited their brethren in Scotland,
administering such counsel, as in their low condition at that time,
tended to their edification.
John Stubbs returning to England, W. Caton went to Sterling,
where he was taken and carried before the governor,
who at first accosted him in a rough and angry manner,
but William being of a meek and christian temper, by his soft answers appeased his wrath,
so that he became cool and sedate.
He was also at Glasgow, and went into the great cathedral there,
where after their worship was ended,
he had an opportunity of speaking to the people in the yard, the English soldiers,
in garrison there, not permitting any injury to be done to him.
At Douglas he published the truth without much opposition.

In October 1657, George Fox was at Edinburgh,
where he was summoned to appear before the council, who sent an officer to his inn,
with the following order, viz.

[.embedded-content-document.legal]
--

Tuesday, the 8th of October 1657, at his Highness`'s council in Scotland.

Ordered,
that George Fox do appear before Order of the council
on Tuesday the 15th of October next,
in the forenoon.

[.signed-section-signature]
E+++.+++ Downing, clerk of the council.

--

He appeared accordingly, and after examination,
they told him that he must depart the nation if Scotland by that day seven-night.
Nevertheless he continued travelling up and down through several parts of that country,
preaching among the people wheresoever he came, and afterwards returned to Edinburgh,
where he was told,
that the council had issued warrants to apprehend him for breach of their order,
in not departing the country within the limited time.
To which his answer was, what do ye tell me of their warrants?
If there were a cart-load of them I do not heed answer them.
For he, knowing his commission to be from God,
was carried above the fear of man in discharging it;
and a peculiar hand of Providence was sometimes visible
in the manner of his deliverance.

[.old-style]
=== Isle of Man

The magistrates of this island being early prepossessed with prejudice
against the Quakers (so called) and their doctrine,
by the misrepresentations of the preachers of those times,
whose interest it militated against, made laws against them at their first arrival there,
one of which was for banishing all of that persuasion, whether natives or others;
accordingly Catharine Evans was taken out of her bed by night, and sent away.
James Lancaster was also expelled the island for no other
reason than his going under the name of a Quaker.
Peter Cosnock, his son, and several others were imprisoned at Castlepeel,
by order of William Christen, a magistrate there,
from thence they were removed to Douglas, and banished.
They applied to the Lord Fairfax for leave to return, but he would not grant it,
though some of them were born there.
At length, upon application to the parliament,
such as were inhabitants of the place were permitted to return to their habitations.

William Callow was detained eight weeks in prison for reproving a priest,
whom he had heard abusing the people called Quakers in his sermon to the people.
Several persons were taken out of a meeting the first day of the week,
and set in the stocks four hours in the marketplace; others were fined,
of whom were William Callow, John Christen and Evan Kerush;
from the two former were taken ten bushels of oats by distress,
which were laid in William Christen`'s barn.^
footnote:[This William Christen was a deputy under Lord Fairfax,
but falling afterwards under his displeasure for some misdemeanour,
he was shot to death on the island.
In his last speech he mentioned with much regret his evil treatment of the Quakers.]
On the next first day after sermon the priest gave public notice
for the poor of the parish to go to the barn and take some corn,
which the governor had ordered to be distributed amongst them; some of the poor people,
his own hearers, answered,
"`That it had been more charity to have given his own goods to the poor than other men`'s,
and that they would receive none of it.`"
However, some of the poor went to the place with the priest and soldiers,
and William Callow went also.
The priest called to the poor several times to hold their bags, but none of them would;
at this the priest grew angry, and looking sternly at William Callow,
called to the people, "`Why don`'t you take the corn?
Is there any one here that hath aught to do with this corn,
or faith it may not be given to the poor;`" this
he said to provoke from William some expression,
but he held his peace.
The poor stood still a while, and then withdrew one by one,
leaving the corn with the priest and soldiers.
On the following first day the parson again published
the distribution of the corn as before,
signifying how much the governor was displeased that they had not taken it.
For fear of the governor and the priest, some poor people went again to the place,
but only one of them would take any, and he vauntingly said to the rest,
"`you are so proud you will not take it: I have got this,
and there will be more of his goods taken before this be eaten,
and then I`'ll get more;`" but it happened, that before he had eaten what he took,
he was taken away by death.
His sudden exit was interpreted by the other poor as a judgment upon him,
and they were glad that they had kept themselves clear.
The rest of the corn lay till it was spoiled, for nobody would take it.
From this instance we may justly observe,
that the innocence and patience of sufferers in the cause of religion,
carries with it a force of conviction on the consciences of the people,
which the arts of designing and interested men cannot easily eradicate.

William Callow and several others each demanded by the priest for bread and wine,
of which they had received none,
were imprisoned by a warrant from James Challoner the governor,^
footnote:[This James Challoner had been a member of the long parliament,
and after the King`'s return had been sent for to London, in order, as was thought,
to be tried among the regicides.
The day he was to go he took something under pretext of physic,
which killed him in a short time.
He had been a violent persecutor, and was heard to say, a little before his death,
that he would quickly rid the island of Quakers.]
from whom also in September this year the priest procured another
warrant for the imprisonment of William Callow and Evan Christen,
for refusing to pay tithes.
One morning early, as soon as they came on shore,
after being all night in the wet and cold at sea,
(for they were fishermen) they were hurried to prison in their wet clothes,
and detained several days in the midst of their herring fishery,
the most advantageous season for their business.
This, however designed by their adversary,
was not productive of the prejudice which might be naturally expected,
for the next night after their release they caught
as many fish as they were able to bring to shore,
so that they had reason gratefully to acknowledge a peculiar providence attending them.
