== Chapter XIV. New England.

[.chapter-synopsis]
* Discovery of North-America
* First Planters of New-England
* John Robinson`'s Farewell-Admonition
* Emigrations multiply in the Reign of Charles I
* Reflection on the Spirit of these Colonists
* Roger Williams banished for his religious Opinions
* Schism at Boston
* Synod convened to decide upon it
* John Wheelwright summoned before the Court, disfranchised and banished
* John Coggeshal disfranchised
* Ann Hutchinson adopts Antinomian Opinions
* Summoned before the Court and condemned to Banishment
* Murdered by the Indians
* Some of the People professing Anabaptism are persecuted
* Three of them committed to Prison
* Law against Anabaptists

In order more fully to elucidate this part of the history,
it seems not improper to take a retrospective view of the
first settlement of Europeans in this country of New England,
one of the most considerable states of the late British dominions in North America.

The continent of North America was discovered by Sebastian Cabot,
in the name of Henry VII.
in the year 1497. It first received the name of Newfoundland,
which is now appropriated solely to an island on its coast.
It was a long time before any attempt was made to fix a settlement in this country.
Sir Walter Raleigh first shewed the way by planting a colony in the southern part,
which he called Virginia, in compliment to his mistress Queen Elizabeth,
under which name at first the whole tract of land
from the bay of Fundy to Florida was comprehended,
and was distinguished only into South Virginia and North Virginia,
which together contained the countries which came afterwards
to be distinguished by the names of New England,
New York, New Jersey, Pennsylvania, Maryland, Virginia, Carolina and Georgia,
King James I. incorporated two companies by patent, one for South Virginia,
called the London Adventurers, and the other for North Virginia,
who were distinguished by the name of the Plymouth Adventurers.

The first colonists who went over to people this latter country were a
class of Puritans (so called) distinguished first by the name of Brownists,
from Robert Brown their leader or teacher, and afterwards by that of Independents.
A congregation of these in the eastern parts of England, viz. Nottinghamshire,
Lincolnshire and Yorkshire, who had chosen John Robinson for their pastor,
and William Brewster for their elder,
to avoid the persecution they found themselves exposed
to from the bishops in the year 1608,
fled for refuge to Holland, and fixed their residence at Leyden,
where they enjoyed the privilege of performing their
worship in their own way without molestation.

After some years residence here,
Robinson apprehending their church would naturally be brought to a dissolution,
and their religion be lost in a strange land,
and having little prospect of obtaining an establishment
or even a toleration for them in England,
encouraged his followers to transport themselves and their
families into some part of the British dominions in America,
where they might live by themselves,
and have a prospect of increasing their number by the future
resort of their friends and countrymen of like principles,
as to an asylum from the sufferings and persecutions,
which their dissent from the national worship still rendered them obnoxious to.^
footnote:[These are Neale`'s expressions,
and carry an appearance as if these emigrants had more extensive views in their
emigration than merely withdrawing from the reach of episcopal power;
and their subsequent conduct seems to afford ground for the supposition,
that even then they were not exempt from thoughts of establishing
amongst themselves an independent dominion in church and state.]

Being thus brought to a resolution to emigrate,
they sent over agents to treat with the Virginia company in England
for a large tract of land in the northern part of that country,
representing themselves as considerable for their numbers, inured to hardships,
industrious and frugal; and embarking on a religious motive,
they hoped for the blessing of the Almighty, and resolution to surmount all difficulties.
These representations induced the company to comply with their proposal;
and they agreed among themselves to divide, that one party should go before,
to prepare for the reception of the rest.
Robinson, their pastor, stayed with the residue at Leyden,
and Brewster their elder put himself at the head of the emigrants.

When the time of their separation was come, they appointed a day of fasting and prayer,
to implore a blessing on their hazardous undertaking;
upon which occasion their pastor preached to them from Ezra
8:21 concluding his discourse with the following exhortation,
which if the chiefs of his flock and their successors had,
in the administration of their government in their new colony,
paid a proper attention to, they had rescued themselves from much guilt and censure;
but as their pastor did not live to join them,
it seems as if the good man and his admonitions were too soon forgotten; although,
from the christian temper that animates them, well worthy of remembrance.

[quote]
____

Brethren, (says he) we are now quickly to part from one another,
and whether I may ever live to see your faces on earth, the God of heaven only knows;
but whether the Lord hath appointed that, or no,
I charge you before God and his blessed angels,
that you follow me no farther than you have seen me follow the Lord Jesus Christ.

If God reveal any thing to you by any other instrument of his,
be as ready to receive it, as ever you were to receive any truth by my ministry;
for I am verily persuaded, I am very confident,
the Lord has more truth yet to break forth out of his holy word.
For my part, I cannot sufficiently bewail the condition of the reformed churches,
who are come to a period in religion,
and will go at present no further than the instruments of their reformation.
The Lutherans can`'t be drawn to go beyond what Luther saw:
whatever part of his will our great God has revealed to Calvin,
they will rather die than embrace it; and the Calvinists, you see,
stick fast where they were left by that great man, who yet saw not all things.

This is a misery much to be lamented;
for though they were burning and mining lights in their times,
yet they penetrated not into the whole counsel of God;
but were they now living would be as willing to embrace further light,
as that which they first received.
I beseech you remember it, it is an article of your church covenant.
That you be ready to receive whatever truth shall
be made known to you from the written word of God.
Remember that and every other article of your sacred covenant:
But I must herewith exhort you to take heed what you receive as truth.
Examine it, consider it, and compare it with other scriptures of truth,
before you receive it;
for it is not possible the christian world should
come so lately out of such thick antichristian darkness,
and that perfection of knowledge should break forth at once.

I must also advise you to abandon, avoid and shake off the name of Brownists:
Tis a mere nickname; and a brand for the making religion, and the professors of it,
odious to the christian world.
____

These first settlers with their families made about one hundred in number,
and having taken shipping from Plymouth,
they distinguished the place of their settlement in New England by the name of New Plymouth.
Their number gradually increased by the arrival of other emigrants from England;
but it was in the succeeding reign of Charles the First that emigrations became far
more numerous and more considerable.
The King having committed the direction of ecclesiastical
affairs into the hands of the bishops,
and more particularly to William Laud, then bishop of London,
and afterwards archbishop of Canterbury;
his intemperate bigotry to useless and unmeaning ceremonies;
his aversion to the Puritans, to whom his innovations in worship were an abomination;
and his determined resolution to force them into
an uniformity after his superstitious scheme,
impelled him to prosecute them with rigorous seventy
in the high commission court and Star Chamber,
two very arbitrary and illegal courts,
that seem to have been established for the purpose of subduing
the people to an absolute subjection to the crown in temporals,
and the mitre in spirituals.

To evade the persecution of this furious prelate and his associates,
many of the Puritan teachers with their hearers resolved
to withdraw to New England for sanctuary.
About the year 1625, White, minister of Dorchester,
encouraged by the success of Plymouth colony,
projected a new settlement at Massachusetts Bay, as an asylum for the silenced ministers,
and engaging several persons of consequence in the project,
a patent was obtained from the King by the adventurers.

One Roger Conant was first sent over to establish a settlement in 1625,
and after him John Endicott with recruits and provisions in 1628.
And in the next year the grand colony sailed in six ships,
and arriving at their intended settlement founded there the towns of Salem,
Charlestown and Boston.

Religion (saith Neale) being the chief motive of coming over into these parts,
they resolved to settle that in the first place; accordingly,
with the approbation of John Endicott, their deputy governor,
they adopted the church order and discipline settled by their brethren at Plymouth,
upon the system of their former pastor, John Robinson;^
footnote:[John Robinson was the father of the independents,
being the first that beat out a middle way between Brownism and Presbytery;
he maintained the lawfulness of separating from those
reformed churches amongst which he lived,
yet did not deny them to be true churches;
he allowed the lawfulness of communicating with them in the word and prayer,
but not in the sacraments and discipline.]
however, disregarding his farewell admonition,
their present teachers and governors seem to have been a self-righteous generation,
so far from the diffidence in their present attainments,
and that openness to the reception of the further revelation of truth,
which he recommended;
that in their own opinionated apprehensions of their
own purity and ultimate refinement of orthodoxy,
they watched with a jealous eye every conscientious dissent from their establishment,
every attempt towards a further reformation.
In their new religious system, with all their regard to the written word,
they appear to have overlooked the principal moral rule of the gospel,
"`whatsoever ye would that men should do unto you, do ye even so to them.`"
For these religious dissenters from established forms of worship,
would admit of no dissent from that way or form they established in their new colony;
notwithstanding their violent exclamations against
the tyranny and oppression of the bishops,
in endeavouring to force an uniformity in worship by penal laws and coercive measures,
they were no sooner invested with the power, than they trod in the very same steps,
being equally rigorous in exacting uniformity,
as severe in enacting and executing penal laws against con-conformists.
Whilst under sufferings,
they pleaded for liberty of conscience to
themselves,
which when in a capacity to exercise authority, they refused to others.^
footnote:[Guthrie`'s remarks on this subject are a confirmation of these observations.
The inhabitants of New England, who fled from persecution,
became in a short time tainted with this illiberal vice,
and were eager to introduce an uniformity in religion among all that entered their territories.
We have also a full proof of this in a letter dated August 16, 1677,
from William Coddington, governor of Rhode Island, to R. Fretwell:
"`These forty years to my knowledge, they +++[+++the rulers of New-England]
have had many warnings From the Spirit of the Lord in his servants,
all crying out against their idolatrous practices,
confused principles and fighting spirits long before
that reproachful name of Quakers got up,
and before they were sent of God to call them to repentance and amendment of life;
but these they evilly entreated, as they have done John Wheelwright,
Anne Hutchinson and others, banishing them at a court at Boston in 1636, Henry Vane,
governor, and twelve magistrates, twelve priests, and thirty-three deputies:
Notwithstanding the governor and myself,
who was then a magistrate and treasurer of the country, being against it,
had for two days the major part of the magistrates and deputies holding with us;
till the third day the priests gained over two of the magistrates to their side,
and so got a majority, who proceeded to banish, them,
although we entered our protest against it.`"]
Of the justice of these remarks, severe as they may seem,
the sequel furnishes too many melancholy instances.

Long before those called Quakers came amongst them, and before they existed as a society,
as early as the year 1634, about four years after their settlement here,
they banished Roger Williams, pastor of their church at Salem,
for his religious opinions.^
footnote:[These opinions (according to Neale) were
"`that it was lawful for an unregenerate man to pray,
nor for good men to join in family prayer with those they judged unregenerate.
That it was not lawful to take an oath before a magistrate.
That the patent they had from King Charles for their lands was invalid,
and an instrument of injustice to the natives,
the king having no right to dispose of their lands to his subjects without their consent.
That magistrates had nothing to do with matters of the first table, but the second only;
that there should be an unlimited toleration for all religions,
and to punish men for matters of conscience was persecution.`"
I see nothing in these opinions deserving banishment or even censure.
Neale`'s [.book-title]#History of New-England, Vol 1.# p. 159.]
In the year 1637 a more extensive schism broke out,
which divided 16 the inhabitants of Boston and the adjacent country into two parties,
under the denominations Boston, of Antinomians and Legalists,
or such as were (as they termed it) for a covenant of grace;
and such as were for a covenant of works:
And as it was no unusual thing with this body to mix politics with their religion,
(the general prelude to persecution) the Antinomians exerted themselves
to keep Henry Vane,
(afterwards a distinguished character in the long
parliament) their present governor in power,
as he openly espoused their doctrines, and protected their preachers: On the other side,
the opposite party employed their efforts to eject him, and substitute John Winthrop^
footnote:[John Winthrop,
although chosen governor for the purpose either of suppressing the Antinomians,
or at least depriving them of any powerful support,
seems to have been a man of too much good sense and moderation to be a sanguine persecutor.
To keep up his party, and to accommodate the furious temper of the priests,
he was led too far into the persecuting measures adopted at this time,
but lived long enough to see and condemn his error;
for when advanced in years and infirm,
Dudley and others applied to him to sign an order for the banishment of one Mathews,
a Welch priest, he refused, saying, he had his hands too much in such things already.]
as governor in his stead, with some difficulty succeeded in the election:
Winthrop being settled in the government,
and the Antinomians having lost their chief Synod protector,
a synod was convened to consider the controverted points, and give judgment upon them.
This synod consisted not only of the ministers and delegates, but the magistrates also,
under colour of keeping the peace,
were present,
and had liberty to speak if they thought proper.
By this synod, composed chiefly of their antagonists,
the Antinomian opinions to be sure were condemned.
This point being carried,
the next step was to summon the principals of the party before the secular court,
which was removed for the purpose to Newtown,
(since called Cambridge) from fear that they had too many partisans in Boston.
And three of the Boston deputies having sided with these Antinomians,
in the first place were expelled the court; before the court thus culled for the purpose,
John Wheelwright, colleague with John Cotton as preacher at Boston, being an Antinomian,
was summoned to appear and give answer,
whether he would acknowledge his offence in preaching up these new doctrines,
styling his discourse a seditious sermon, or abide the sentence of the court,
his answer being that he had been guilty of no sedition nor contempt;
that he had delivered nothing but the truth of Christ,
and for the application of his doctrine, that it was made by others and not by himself:
And refusing, at the desire of the court, to go into voluntary banishment,
they sentenced him to be disfranchised and banished the jurisdiction.
John Coggeshall, one of the late Boston deputies of this party,
was disfranchised for a speech he made in the court,
notwithstanding his pleading his privilege as a member.
And Aspin, another of them, for signing a remonstrance in favour of Wheelwright,
was disfranchised and banished.
William Baulston and Edward Hutchinson, two of the sergeants of Boston,
for signing the said remonstrance, were turned out of their places,
disfranchised and fined,
the former in 20£. the latter in 40£. Hutchinson
acknowledging his fault had his fine remitted.
The exiles found a friendly reception with Roger
Williams beforementioned at Providence for the present,
and afterwards purchased a settlement at Rhode Island and of the natives,
and fixed themselves and their families there.^
footnote:[As Neale, from whom I take this account, follows Cotton Mather,
an apologist for these severities, there is reason to suspect his relation of partiality;
if we had accounts on the other side to balance against this,
I doubt not but these proceedings would appear in even a more unfavourable light.
Of these first settlers in Rhode-Island he copies this character from Mather.
Cotton Mather represents them as a generation of Familists, Libertines,
Antinomians and Quakers,
whose posterity for want of schools of learning and a public ministry,
are become so barbarous as not to be capable of speaking
either good English or good sense.
They have an extreme aversion to a public ministry,
and would never till of late allow any such to preach among them.
This seems the language of animosity and contempt;
but I have before me a very different description of these
Rhode Islanders drawn up by a more judicious pen in my opinion:
"`Several slips, torn from the original government of New-England,
planted themselves of Rhode-Island,
whose inhabitants were driven out from the Massachusett colony (for that is the
name by which the government first erected in New-England was distinguished)
for supporting the freedom of religious sentiment,
and maintaining that the civil magistrate had no
right over the speculative opinions of mankind.
These liberal men founded a city, called Providence,
which they governed by their own principles;
and such is the connection between justness of principle and external prosperity;
that the government of Rhode Island, though small,
is extremely populous and flourishing.`"
Guthrie.]

The treatment of a female, whose name was Ann Hutchinson, was even more severe,
and her fate more melancholy.
The account Neale gives of her case exhibits much of the invective style throughout,
being probably copied after the New England apologists,
and her imputed errors in the highest colouring to palliate
the severities of the persecuting priests and magistrates.
Yet we find no crime laid to her charge, only speculative opinions, which, if erroneous,
more properly demanded the labours of the ministers to confute and convince her,
than the power of the magistrate to chastise.
Her case is represented to be this:

The members of the church of Boston met once a week,
to repeat the sermons they had heard at their public worship,
and to debate upon the doctrines contained in them.
These meetings being peculiar to the men,
some zealous women thought it might be useful for them to hold such meetings among themselves;
accordingly this Ann Hutchinson set up one in her house,
grounding her practice on the apostle`'s direction,
for the elder women to teach the younger.
The novelty of the undertaking, the same of the woman,
quickly gained her a numerous audience,
to hear her pray and repeat John Cotton`'s sermons, and make her reflections upon them.
She adopted and propagated the devoted opinions of the Antinomians,
which (the aforenamed author saith) under a pretence of exalting
the free grace of God destroyed the practical part of religion,
and opened a door to all sorts of licentiousness.
But this was not all--she and her adherents insinuated themselves into families,
and under a shew of humility and self-denial,
craftily undermined the reputation of the best ministers in the country,
calling them legalists,^
footnote:[Yet this author represents her as a great admirer of John Cotton,
one of the best, if not the very best, minister at this time in New-England.]
Men that were not acquainted with the spirit of the gospel, nay,
that were unacquainted with Christ himself.^
footnote:[That there was too much truth in this description of these ministers,
we have reason to conclude from the foregoing abstract
of W. Coddington`'s letter to R. Fretwell, p. 332,
where we find the priests day after day exerting their efforts and earnest
solicitations to procure a majority to banish her and the forementioned,
which proceeding of theirs amounts to a demonstration that
they were not acquainted with the spirit of the gospel.]
For these offences she was summoned to appear before the court,
by which she was condemned to banishment,
being ordered to depart the jurisdiction within six months.
She was afterwards excommunicated, with eight or nine more.

Being thus driven from her habitation to seek a residence where she could find one,
she removed first to Rhode Island,
and thence to one of the Dutch plantations called Hebgate,
where soon after the Indians coming down, murdered her and her whole family,
to the number of sixteen persons.

In 1646 they made a law or order for uniformity in religion,
by imposing a penalty of 5s. a week upon such as came not to hear the established ministers,
thus intrenching themselves against any further discoveries
of truth and religion by this penal law.

But notwithstanding these harsh precautions to maintain an uniformity,
they found other men influenced by religious considerations,
to take the same liberty here they themselves had done in England,
to dissent from their established religion, as they had done from that of the bishops.
In the year 1650 some of the inhabitants adopted the opinion of the Anabaptisit,
withdrew from the established worship, and set up a separate meeting,
whereupon Obadiah Holmes, one of the principal dissenters, was excommunicated,
and then summoned to appear before the court at Plymouth,
by which he and his associates were commanded to desist from their separation,
and neither to ordain officers, nor to baptize, nor to break bread together,
nor to meet on the first days of the week;
but looking on this command as an arbitrary violation of their christian liberty,
they pleaded,
that in their separation they were actuated by the conviction of their own consciences,
and that it was better to obey God than man.

John Clarke from Rhode Island, Obadiah Holmes aforesaid, and John Crandall,
sometime after travelling into the jurisdiction of Massachusetts,
were apprehended in their meeting at the house of William Witters of Lynn,
on the first day of the week; and the constable who had them in custody,
in the afternoon carried them by compulsion to the public worship, where,
signifying they could not join with them in their service,
they were next day brought before a magistrate,
who committed them to Boston prison by the following mittimus:

[.embedded-content-document.legal]
--

By virtue hereof you are required to take into
your custody from the constable Lynn or his deputy,
the bodies of John John Clarke, Obadiah Holmes and John Crandall,
and them to keep until the next county prison court to be held at Boston,
that they may then and there answer to such complaints as may be alleged against them,
for being taken by the constable at a private meeting at Lynn on the Lord`'s day,
exercising among themselves, to whom divers of the town repaired, and joined with them,
and that in the time of public exercise of the worship of God;
as also for offensively disturbing the peace of the congregation,
at their coming into the public meeting in the time of prayer in the afternoon,
and for saying and manifesting that the church of Lynn was
not constituted according to the order of our Lord;
and for such other things as shall be alleged against them concerning their seducing
and drawing aside of others after their erroneous judgment and practices,
and for suspicion of having their hands in re-baptizing of one or more among us,
as also for neglecting or refusing to give in sufficient
security for their appearance at the said court.
Hereof fail not at your peril.

[.signed-section-context-close]
22nd of the 5th month, 1651

[.signed-section-signature]
Robert Bridges.

--

In a short time after their commitment they were brought before the court and fined,
viz. John Clarke 20£. John Crandall 5£. and Obadiah Holmes 30£+++.+++;
and in case of failure or refusal of payment to be whipped.
The prisoners agreed not to pay their fines,
but to abide the corporal punishment the court had sentenced them to;
but it is said some of Clarke`'s friends paid the fine, without his consent;
Crandall was released upon promise to appear at the next general court, and Holmes,
received thirty lashes at the whipping post.
After the execution of his sentence,
two of his friends who were attending him back to prison,
took him by the hand into the market place,
and praised the Almighty for his courage and constancy,
for which they were summoned before the general court the next day,
and fined each of them; 40s. or to be whipped; they also refused to pay their fines,
but these being paid for them they were dismissed.

I imagine those historians who have celebrated the Independents for originally
adopting the doctrine of toleration must have been unacquainted with,
or overlooked this part of their history.
If
their principles were really such as we have seen them described,
that every man had a right to direct his conscience,
and interpret the scriptures according to his own light,
we see their practice in England, and still more here,
as being more out of the reach of censure or controul,
evidently militating against these principles.
We see them, as well as others before them, for the sake of uniformity,
violating the natural rights of mankind, and punishing men, not for disturbing the state,
but merely for differing in their sentiments of religion, of which the following law,
enacted at this time and on this occasion, is a confirming evidence:

[.embedded-content-document.legal]
--

It is ordered by this court and authority thereof,
that if any person or persons within this jurisdiction shall
either openly condemn or oppose the baptizing of infants,
or go about secretly to seduce others from the approbation or use thereof,
or shall purposely depart the congregation at the administration of that ordinance,
or shall deny the ordinance of magistracy,
or their lawful right or authority to make war or
punish the outward breaches of the first table,
and shall appear to the court willfully and obstinately
to continue therein after due means of conviction,
every such person or persons shall be sentenced to banishment.

--
