== Chapter XIII. Ireland

[.chapter-synopsis]
* William Edmundson the first of the People called Quakers in Ireland
* Account of him
* Importuned to settle in Dublin, but removes from thence to Antrim
* Going to the North of England hears James Nayler preach, whereby he is fully convinced
* Refuses to swear
* Miles Halhead, Miles Bateman and James Lancaster visit Ireland
* William Edmundson removes to Lurgan, and settles a Meeting there
* Receives a Gift in the Ministry
* John Tiffin comes over from England, William Edmundson accompanies him to Belfast
* Richard Clayton and William Edmundson travel on foot
* Are refused Entertainment at Coleraine
* Several convinced, near Kilmore
* Several Friends from England visit Ireland
* First Meeting in Dublin
* Many convinced
* At Limerick Edward Burrough and Francis Howgill assaulted, and put out of the Gate
* Taken Prisoners at Cork, and sent under a Guard to Dublin, and banished
* Edward Burrough`'s Remonstrance against their Treatment* Barbara Blaugdon`'s Interview with the Lord Deputy
* William Edmundson quits Shop-keeping
* Removes to the County of Cavan,and settles a Meeting there
* Removes thence to Queen`'s County, and settles a Meeting at Mountmelick
* Barbara Blaugdon imprisoned
* William Edmundson set in the Stocks at Belturbet

The first of the people called quakers in lreland was William Edmundson,
who came over in the way of trade;
and being soon after convinced of the truth of the principles of this people,
and adhering to them, was instrumental to the convincement of some others,
before any of their ministers came over from England;
and as he fixed his residence in that kingdom,
and became a very reputable member and minister in this society there,
it seems proper to open this part of the history with an account of him.

He was born at little Musgrove in Westmoreland, in the year 1627,
and in his early minority was often seriously affected
with consideration about a future state;
and as his age and faculties advanced towards maturity,
his desires after everlasting felicity increased in proportion.
About the year 1650 he entered into the parliament`'s army,
but continued in it only for a short season,
for during the campaign in Scotland under Oliver Cromwell,
the subject which had before closely exercised the attention of his thoughts
(i. e. the salvation of his soul) fixing more deeply in his mind,
he soon grew weary of the military life, and laid down his arms,
in order to be more at liberty to engage in the spiritual warfare.
In the year 1651 he returned from Scotland into England, and was quartered in Derbyshire;
which being about the time of George Fox`'s release from Derby jail, he,
and the people who had there lately received the denomination of Quakers,
were become a general topic of conversation,
and variety of reports were propagated concerning them, some in their favour,
and many to their disadvantage: Upon the comparison, William, before he knew them,
found his heart inclined to the favourable side.

About this time he entered into the married state,
and quitted the army with a purpose to settle in Derbyshire;
but at the persuasion of his brother John, who was then a soldier in Ireland,
and come over to see his relations in England, he removed into Ireland,
taking with him such merchandize as might be like to be in demand there.
Landing in Dublin, he was strongly importuned to settle in that city,
and besides prevented, the solicitations of others,
he had the inviting prospect of a brisk trade and low rents,
it being soon after the plague had left many houses uninhabited.
But he writes that he was rescued by a secret hand, which he then knew not,
from the deceitfulness of riches, being by his following experience,
brought into the persuasion, that by closing in with the tempting prospect, he might,
in the acquisition and pursuit of wealth, have been diverted from the principal object,
a life of religious devotion to the service of his Creator,
as the means of securing future felicity; which pernicious effect,
he observed with regret, the acquisition of wealth and love of the world,
had on too many in that day.

From this settled persuasion of mind of the danger hereof,
we shall find him in the sequel exerting his zealous endeavours to preserve his
friends in that moderation and self-denial of which he set them a lively example,
both on this occasion, and at sundry future periods of his life.

From Dublin he removed to the North, and took up his residence in Antrim,
in or near which his brother was quartered; and quickly disposing of his goods,
he went over to England to lay in a fresh stock,
and in his travels through the North he heard that
George Fox and James Nayler were then in those parts,
which raised his desire to see and hear one or other of them.
Going to a meeting where Going to James Nayler was,
he heard him explain the nature of the kingdom of God, and the work of regeneration;
and though his words were not many, they were powerful,
reaching the divine witness in his conscience.
The subject was so clearly opened,
and concurred with so many scriptures brought to William Edmundson`'s remembrance,
that he was thereby fully convinced,
and thought all who heard his discourse must needs confess it was the real truth.
The impression on his spirit was deep and lasting,
and under the humbling and exercising effect thereof he returned home,
having accomplished his business in England.
Upon his arrival his brother received him with the customary salutation,
but under his present exercise he could not return it in like manner;
for being convinced of the necessity of being born
again in order to inherit the kingdom of heaven,
he was affected with earnest desire after this happy condition,
and impressed with inward anxiety, and that godly sorrow which works repentance,
with a mixture of consolation, in feeling the divine mercy awakening his understanding,
and strengthening his resolution to endeavour after this arduous attainment.
Under this humbling conflict of spirit he sat down,
his wife and brother sitting by in silent astonishment at his visible change.
320

His sincerity was soon brought to the test, When he came to the entry of his goods,
he was, according to custom, required to enter them upon oath,
but he being persuaded of the unlawfulness thereof, signified he could not swear,
because Christ had forbidden it.
This doctrine appeared strange to the officers, and no wonder, as it was the first time,
in all probability, they had ever heard such a scruple advanced;
and his deportment and plain address, standing covered before them,
and addressing them after the usual way of this people, with the singular, thou and thee,
was as offensive to them, as his refusal to swear appeared strange.
He was not insensible of the contempt and aversion,
he should expose himself to by a scrupulous adherence
to the imputed singularities of his profession;
and found it a strait path to tread,
and was therefore engaged in mental prayer to the Lord,
who (he writes) was pleased to administer strength and ability, to stand in the cross,
and despise the shame, whereby he was preserved steadfast in his testimony to the truth,
brought through the present trial without injuring his conscience, received his goods,
and went home.

It seems not improper here to remark,
that these peculiar scruples before-mentioned in the demeanour of this people,
contrary to the established customs of the nations at this day,
have been (I think) ignorantly imagined to originate
merely from an unmeaning affectation of singularity;
but whosoever hath been conversant in the memorials
these worthy men have left behind them,
of their spiritual exercises,
will find sufficient grounds to deduce them from a better original,
a conscientious conviction of rectitude and truth being in favour of them;
too sincere for affectation, and too honest for flattery;
intent (above all things) upon seeking the approbation of their Creator,
and the testimony of a good conscience,
by an unreserved conformity to his will in their actions, their words,
and the very thoughts of their hearts,
although as men they were not insensible to the feelings of humanity,
and were many of them, at first,
affected with the natural reluctance at the prospect of exposing themselves to the censure,
the ridicule, and even the abuse of their relations and fellow-citizens,
with whom they had before lived on good terms, by whom they had been respected,
and with whom they had kept up an intercourse of mutual complacency;
yet feeling no peace of mind but in adhering strictly to
that which was manifested to their understandings as right,
even to the jot and the tittle,
they preferred the inward testimony of divine approbation,
to human respect and every worldly consideration;
and in the steady pursuit of this important attainment they were
strengthened to take up the daily cross to that carnal disposition,
which would win human honour at the risk of solid peace of mind.
And apprehending their spirits divinely illuminated,
to behold the polluted source from which these modes
of complaisant adulation and address originated,
and the unmeaning abuse or deceitful purposes to which they were applied,
thought it their duty not to hide the candle under the bed of personal ease;
but to bear open testimony for truth and sincerity, at the risk of ease, reputation,
and the regard of man.

In this respect the situation of William Edmundson must be peculiarly trying,
circumstanced as he was, all alone,
and without a second in similarity of sentiment or deportment, the wonder, the scorn,
and gazing-stock to the world around him;
where the name of Quaker had but lately been heard of,
and where it was presented to the imagination under all the veil of obloquy,
which a precise and censorious age,
or interested and exasperated ecclesiastics thought proper to clothe it with.
Besides these external probations he was at this time agitated
with internal conflicts in his spiritual warfare,
under the work of sanctification,
and conviction in the sense of his being (although religiously
inclined from his youth) yet short of that perfection of
purity which by the divine light was discovered to his mind,
as the requisite duty of every Christian to aspire after,
and through the assistance of grace follow to the attainment thereof;
in which religious exercise he passed through a fight of afflictions,
wherein he could find none to speak a word of comfort,
or that had trodden in this strait path,
his only consolation being the continued inward sensation of divine mercy, thus visiting,
strengthening and animating his soul to the steady pursuit of its everlasting well-being.
Many professors of religion came to carp at, dispute with him,
and speak evil of the way he had embraced.
Miserable comforters these, adding trouble to his sorrow.
But even these things wrought for good.
For the censorious reflections of the self-righteous professors,
and the derision of the profane and irreligious,
to which this society was at that time exposed, raised a general curiosity,
and spirit of inquiry into their real principles and conduct,
whereby several of the sober enquirers were undeceived,
as to their mistaken notions of this people through misrepresentation;
and finding him and his friends neither deluded nor deceivers,
but men of sincerity and truth, joined with them in society.

In the year 1654, Miles Halhead,
James Lancaster and Miles Bateman travelled into Ireland,
where they published the truth by preaching to the people in the cities,
towns and villages, and before the magistrates,
as they were occasionally brought into their presence,
and many of the inhabitants hearkened to,
and became convinced of the doctrine of the divine light,
which they everywhere bore testimony to.

In the same year William Edmundson removing his habitation from Antrim to Lurgan,
a meeting was kept in his house there,
which was the first settled meeting of the people called Quakers in Ireland.
This meeting was but small at first, but their number increased, divers sober people,
who were seeking after the knowledge of God, joining with them.
They held their meeting for some time in silent waiting upon the Lord,
and felt his presence to comfort and strengthen them in their religious exercise,
having no member concerned in the ministry, nor being, since they had a regular meeting,
as yet visited by any from England.
But it was not long until William Edmundson received a part in the ministry of the gospel,
and was influenced, at times, to speak a few words for the ministry,
encouragement and edification of his friends, although in weakness and fear.
Shortly after he believed it his duty to bear a public
testimony to the truth in the public worship house,
for which he was severely beaten by Colonel Stewart;
but his testimony was effectual to the convincement of some of the auditory,
in particular two of them named Mark Wright and Mark
Sawyer followed him out of said worshiphouse,
and joined him in community.

Now John Tiffin came over from England,
sat with these friends in their meeting in Lurgan,
and sometimes spoke a few encouraging and edifying words amongst them.
William Edmundson and he joined as companions in traveling,
and in the exercise of successful ministerial labour,
through much opposition both from the priests and people.
The former taking the alarm at their doctrine, pointed against a hire ling ministry,
and the lawfulness of tithes,
or compulsory measures to extort antichristian demands under the gospel,
exerted themselves to incense the magistrates and
rulers to persecution against this people,
as holding damnable doctrines: The latter,
offended at the apprehended rusticity of their address,
frequently ill treated them not only with abusive expressions,
but often with blows and stoning them.

They went to Belfast (a town of great profession of religion,
but very deficient in hospitality) not an inn nor public
house in the town being willing to entertain them,
one excepted; here John Tiffin lodged,
and sought frequent opportunities to promulgate his doctrine there; but the inhabitants,
full of their own righteousness, and looking at them through the medium of prejudice,
shut their ears, their hearts and their houses against them.
Thus at the beginning the way was strait and difficult,
but the first of this people being men that truly loved and feared their Creator,
all things wrought together for their good:
For the general ignominy which the malevolence of their adversaries, who were many,
loaded them with, and who were watching for their halting,
was the means of increasing their circumspect care over their own words and actions,
and over one another for good, to take away all just occasion of reproach;
and as they were kept humble, walking in awful fear before the Almighty,
and blamelessly before men, preaching in their lives and conversation,
to the reaching the divine witness in many, by these means,
as well as their doctrinal labours, several converts were brought over to join them;
and this society gained ground,
and prospered (through divine blessing) notwithstanding
all the difficulties they laboured under.
John Tiffin, having spent five or six weeks here, returned to England.

The next minister who came out of England, was Richard Clayton,
who came directly to William Edmundson`'s, as he understood it, by the Lord`'s direction.
William joined him in his travels on foot, through the county of Antrim to Colerain,
where they preached through the street,
for the inhabitants would not admit them into their houses,
nor suffer them to lodge in the town;
so they were obliged to take up their lodging at a cabin in the mountains,
and next day they reached Londonderry,
where they were hospitably entertained by one Evans,
who with several of his family was convinced by them.
They had two meetings in that city, both of which were attended by the governor,
who with several others, acknowledged the truth of their doctrine,
and demeaned themselves with kindness and affectionate regard towards them.
From thence returning through the counties of Tyrone and Armagh,
they came to the house of Margery Atkinson near Kilmore,
where they had a meeting on the first day of the week,
at which meeting several sober people were convinced,
through the serviceable ministry of Richard Clayton,
receiving the truth in the love of it.
And having settled a meeting there (which in time
became large) they took leave of each other,
and soon after Richard Clayton returned to England.

Now the belief in the inward principle of light and grace began to spread,
and the professors thereof to increase in their number in the northern parts,
so that meetings begun to be settled in divers places hereaway.
One at Gabriel Clark`'s, at Grange in the county of Antrim,
and another at Archibald Scott`'s, at Toberhead, county of Londonderry.
Convincement spread;
and the resentment of the priests and high professors received
additional heat from the observation of several leaving them;
so that to avenge themselves, they procured the imprisonment of William Edmundson,
in Armagh jail.

This year James Lancaster and John Tiffin came over from England the second time:
They landed in the North, and came to Lurgan, where they had a meeting on the green,
near the marketplace; here they were set upon by the populace,
who beat the said friends and William Edmundson their townsman very severely,
and drove them to the town`'s end, with intention to drive them out of it entirely;
but the more sober part of the inhabitants rising to oppose them,
prevented their design.

As yet the profession of those called Quakers had been confined to the province of Ulster;
but now it began to extend to other parts,
principally through the ministerial labours of Elizabeth Fletcher and Elizabeth Smith;
Francis Howgill and Edward Burrough,
who went over to that nation in the course of this year;
the former are supposed to be the first of this society who had
a meeting in Dublin in the chamber of Richard Fowkes near Polegate,
and soon a meeting was settled at George Latham`'s, near the same place.
Their labours were also remarkably successful in the southern parts of that nation,
being effectual to the convincement of many in Dublin and in the province of Munster,
particularly William Ames who who had formerly been a military officer,
a bold and zealous man, and a teacher amongst the Baptists.

Francis Howgill and Edward Burrough also travelled forthward into Munster; at Badon,
Francis Howgill was kindly entertained by Edward Cook,^
footnote:[The said Edward Cook embraced the truth with his whole heart, and retained it,
was given up to serve the Lord, and lived and walked under the cross of Christ Jesus,
in great self-denial to the world and the glory and greatness of it to his dying day,
and laid down his head in peace with God, and sweet unity with true-hearted friends.
Rutty`'s [.book-title]#Rise and Progress,# p. 95.]
a man of good parts, a Cornet in Oliver Cromwell`'s own troop, and receiver to Lord Cork,
and being convinced,
he accompanied him on the first day of the week to the public worship,
where Francis declared truth to the congregation.
In conclusion Edward Cook invited them to come to
a meeting to be held at his house that evening,
to which accordingly a great concourse of people resorted,
to whom Francis preached the gospel, and expounded the way to life and salvation;
many confessed to the truth of his doctrine,
and joined in society with the Quakers so called.

From hence they went to Limerick, and attempting to speak in the public place of worship,
were prevented by an assault of the people,
and next morning were put forth through the gates.
Edward Burrough preached through the streets as they passed along,
and without the gates had an opportunity to preach to a great multitude,
several of whom were so reached by his testimony,
as to become proselytes to his doctrine and profession.

From Limerick, I apprehend, they returned to Cork; but these their successful labours,
and the number of those who thereby were brought to the
acknowledgement of the truth of their doctrines,
alarming the jealousy of the priests or public teachers, by an order of government,
at their instigation, these two eminent ministers of the gospel,
were taken prisoners in Cork, and sent under a guard from garrison to garrison to Dublin,
where they were committed to the custody of Edward Mortimer, Sergeant at Arms,
until an order was procured from Henry Cromwell, Lord Deputy,
to banish them out of the nation,
and a guard of soldiers was appointed to conduct them on shipboard,
and so to be transported to England.

As Edward Burrough had been a zealous advocate for the liberty of his
brethren in divers remonstrances to the ruling powers in England;
so in his own case his fortitude, founded on conscious integrity,
and internal conviction of innocence, did not desert him: With strength of reason,
and the manly spirit of evangelical liberty,
in a similar address to the present rulers of Ireland, he pleaded his own cause,
and that of his fellow-sufferer, against the arbitrary exertion of power,
in inflicting punishment without legal conviction of any crime.
Remonstrating, that they were men free born, fearing God, and working righteousness;
supporters of justice and true judgment in the earth, subject to all equal rule,
and every just ordinance of man for conscience sake.
That they had come into Ireland under the best impressions, and with the best views,
with the message of the Gospel of Christ Jesus, to turn men from darkness to light,
and to minister the word of reconciliation and salvation freely, without gift or reward:
That they had travelled for this purpose six months in sundry parts of the nation,
through many sufferings and reproaches, preaching the kingdom of God, in sobriety,
meekness, and the exercise of a pure conscience both in doctrine and conversation,
appealing to all who had heard the one or beheld the other,
as witnesses for them and their inoffensive and peaceable demeanour,
and challenging even their bitterest enemies to prove the contrary.
That notwithstanding their manifest innocence,
upon malicious suggestions and information, grounded upon no matter of fact,
a warrant had been issued against them, as disturbers of the public peace,
from the chief ruler and council of Ireland,
by virtue whereof they were apprehended in the city of Cork,
and transmitted under a guard through the country,
towns and cities like the vilest criminals to Dublin,
where also they were hauled by guards before the council as malefactors:
That upon their examination there,
none of these things whereof they were accused could be proved against them,
nor were they, nor could they be convicted of the transgression of any known law;
yet were they, without trial, without conviction, condemned to imprisonment,
in order to be transported out of the country as vagabonds,
a title applied to them by a gross misapplication and perversion of the term,
being men of sufficient property and estate: For, (says he) of whom have we begged?
to whom have we been burdensome?
or whose bread have we eaten for nothing?
or what evil have we done?
In fine,
making a solemn appeal to the reason and consciences of their persecutors for justice,
and boldly demanding their right and privilege, as freeborn subjects,
of their personal liberty,
until they should be proved guilty by the law of equity or that of the land,
to which they professed subjection, and that for conscience sake.^
footnote:[This remonstrance may be seen at large in Rutty`'s
[.book-title]#History of the Rise and Progress of the Quakers In Ireland,#
as also an excellent Epistle to his Friends in that kingdom.]

The same day that they were banished from Dublin,
Barbara Blaugdon landed there and went directly to the deputy`'s house,
and with some difficulty got admittance to him: being introduced into the drawing-room,
a scheme was laid to impose upon her, for as they knew she had never seen the deputy,
another person (a priest) came out of the deputy`'s chamber covered,
those that attended him standing bare headed; and as she did not immediately speak,
some of those standing by, asked her why she did not speak to their lord?
But she, having a sense of the intended deception, answered, When I see your lord,
I shall deliver my message to him: Soon after the deputy himself came forth,
and sat down on a couch, to whom she addressed herself, cautioning him,
to beware that he was not found fighting against God, in opposing the truth,
and persecuting the innocent; but, likewise Gamaliel, to let them alone;
for if it was of God, it would stand, but if of man it would fall.
Adding that the enmity was not so much in himself,
but that he was incited by evil magistrates and envious priests: But in the meantime,
in his name and under his authority, much injury was done to the people of God,
all over the nation, and that at last it would lie heavy upon him.
She spake so powerfully, that the deputy appeared under much concern.

Having now performed her service in Dublin, she went to Cork,
where she had some relations and acquaintance; but her sufferings were great,
for she was imprisoned almost wherever she came; and generally wheresoever she preached,
it was attended with demonstration,
and effectual to the convincement of some of the auditory.

In the year 1656 William Edmundson apprehended it
his duty to discontinue the business of shop-keeping,
and take a farm;
in order to strengthen and encourage his friends to faithfulness in the testimony
they had conscientiously to maintain against the antichristian yoke of oppression,
the enforcing the payment of tithes, under the dispensation of the gospel,
as apprehending his endeavours to preserve them steadfast under
their sufferings would be likely to have a more prevalent effect,
when by being a sharer therein he should give force to his advice and religious concern,
by his own example.
With this view, he and some other friends, leaving the meeting at Lurgan,
to which they belonged, well settled, and in a prosperous way,
removed with their families, and took land in the county of Cavan,
and settled a meeting in that county, and held meetings in divers places,
whereby their profession gained ground, and the society enlarged its numbers,
several being convinced, and associating with them.

In the succeeding year the meetings of this Thomas
people in Ireland were visited by Thomas Loe,
from Oxford, an able and eminent minister of the gospel,
endued with spiritual discernment to divide the word aright,
to the differing states of auditory.
He travelled (partly on foot) through the greatest part of the nation,
and by his powerful and prevailing ministry was instrumental
to confirm and edify his friends,
who were before gathered into the society,
and to increase their number by the convincement of others.

The next minister of note, who came from England was John Burnyeat from Cumberland,
a man from deep experience of the work of sanctification,
and the reception of an excellent gift in the ministry,
eminently qualified to promote the work of reformation,
and to publish the glad tidings of the gospel.
He landed at Donaghadee in the province of Ulster, and travelled on foot,
through divers parts of that province,
and by means of his ministry many were converted from the vanity and evil of their ways.
Thence he travelled southward into Munster, and back again into the North,
and at Lurgan met with Robert Lodge, who was lately come over from England,
and who was also an able minister of the gospel:
They joined in travelling and in ministerial labour, promulgating truth,
and convincing many.
At Londonderry they experienced a very different
reception from those who went thither before,
these being refused entertainment, when known to be Quakers, so called,
although they offered to pay for it.
They went to the place of public worship on the first day,
and had a good opportunity to publish their doctrine to the people;
but at length the mayor sent his officers and forced them out of the city.
They proceeded from thence to several other places in the province of Ulster,
and then travelled southward to Dublin, thence westward to Galway,
and from thence by Limerick to Cork and Bandon, and then returned to the North again.
Thus with diligence and laborious travels, through cold,
hunger and hardship many times (several parts of the country
being mostly uninhabited) and divers imprisonments,
as at Armagh, Dublin and Cork, for the space of twelve months,
they zealously exercised the talents they had received for the good of souls,
and the propagating truth and righteousness in this land;
without any view to other reward,
than the inward peace resulting from the conscientious
discharge of their duty in the sight of God,
who was pleased to bless their labours,
to the convincing and gathering many to the truth they promulgated.

This year several of the friends who had removed into the county or Cavan,
being disappointed by their landlord in not fulfilling his covenant with them, left it,
and settled in or near Mountmelick in the Queen`'s county, viz. William Edmundson,
Richard Jackson, John Edmundson, John Pim and sundry others;
and several having been convinced in these parts before,
a meeting was settled at Mountmelick, which is since become large.
The meeting which they left at Cavan continued there
until it was lost by means of the war,
friends who lived there being driven from their habitations,
and dispersed into other parts.

Although the way was difficult to our first friends in this nation,
and they had a share in the sufferings of their friends in England,
yet it doth not appear that persecution was either
so general or so violent as in the latter kingdom,
which I am ready to attribute to the moderation and humanity of Henry Cromwell,
at this time chief governor,
more especially as we have fewer accounts of imprisonments
and persecutions in the city of Dublin than in remoter parts,
not so immediately under the eye of the government.
The most remarkable cases that I meet with, besides those already mentioned,
are those which follow:

Barbara Blaugdon landing a second time in this country,
after narrowly escaping shipwreck off Dungarvan, came to Dublin,
where she felt herself concerned to go to the court of justice,
and exhort the judges to righteousness and equity in the discharge of their functions:
But her exhortation was so ill received,
that she was immediately shut up in a very dangerous and loathsome prison,
where she lay upon straw, and when it rained,
the wet and filth of the house of office ran in under her.
She was arraigned and required to plead guilty or not guilty; to which she answered,
"`there was no guilt upon anyone`'s conscience for what was
done in obedience to the Lord;`" which answer not satisfying,
she was sent back to prison, where she suffered much.
She was afterward imprisoned in Limerick, and when released thence returned to England;
but in her passage thither was robbed by a privateer of all she had on board.
Edward Cooke, a soldier in Oliver Cromwell`'s army,
being convinced of the principles of this people, was sent for before the general,
where nothing appeared against him, but that he refused to pull off his hat,
using the language of thee and thou, and declining the customary compliments;
for these causes he was dismissed from the army, and defrauded of his pay.
Thus those soldiers, who pretended once to fight for liberty of conscience,
became oppressors of other men`'s consciences,
as soon as they were thereby brought into any practice contrary to their general opinions.

William Edmundson travelling northward, came to a town called Finah,
where the innkeepers, when they perceived he was a Quaker,
refused him lodging upon which he applied to the
constable to provide him lodging as being a traveller,
and having money to pay for it,
and not without much entreaty obtained admittance into his house, being an ale-house;
into which when he entered, he found a company of troopers drinking,
who received him with scoffs and impertinence.
They afterward took great offence at his singular address,
one of them swearing if he thou`'d him again he would cleave his head.
And accordingly when in the course of conversation he used the term thou to him again,
the trooper drew his sword; but a corporal being present prevented him from mischief,
ordered him to put up his sword, and causing the troopers to go to their quarters,
he entered into discourse with him till late at night, was convinced,
and came to meetings.

He proceeded to Belturbet, and had a satisfactory meeting there,
but the provost of the town being invidiously disposed came with some rude people,
broke up the meeting, and imprisoned both men and women all night in a very cold place,
and it being a season of frost and snow, they were greatly pinched with the cold,
especially the women.
The next morning he set them all at liberty except William Edmundson,
whom he set in the stocks in the market-place, where, the people gathering about him,
furnished flocks at him with an opportunity to preach to them,
who heard him with attention and sobriety,
and reflected much upon the provost for abusing him.

The people in general appearing dissatisfied with
the provost`'s treatment of William Edmundson,
he sent his officer to let him out;
but as he had been thus made a public spectacle without the violation of any law,
he would not submit to a release from a petty officer,
till the provost who put him in came in person to take him out.

About this time Oliver Cromwell had published a declaration,
"`That such should be protected in their religion as owned God the Creator of all things,
and Christ Jesus the Saviour of men, and the scriptures, etc.`"
Wherefore when William Edmundson was set at liberty, the governor of the garrison,
officers and principal inhabitants,
had him brought before them to try him by the declaration,
whether he and his friends were under Oliver`'s protection or not.
The declaration being read, and William being called upon to answer to the particulars,
gave them such satisfaction, that the governor and company gave judgment,
they were under protection, and their religion was to be protected.
The provost being present,
was covered with shame and confusion at this oblique condemnation of his conduct.

By a general account published about this time,
it appears that for speaking the truth in steeple-houses, markets and other places,
ninety-four persons of this society had been sufferers by fines, whipping,
putting in the stocks, imprisonment and loss of goods.
That nineteen persons had been imprisoned for meeting to worship God in their own houses;
and that twelve had been stopped as they were passing
the streets and high ways about their lawful occasions,
and committed to prison.
