== Chapter XV.

[.chapter-synopsis]
* Anne Austin and Mary Fisher, two of the People called Quakers, arrive at Boston
* Order concerning them
* Their Books burned, and they themselves imprisoned
* Stripped and searched for Tokens of being Witches
* Eight more Friends arrive at Boston
* First Law against Quakers
* Nicholas Upsal testifies against it, for which he is fined and banished
* Anne Burdon, Mary Clarke, and three others whipped
* Addition to the Law
* Lawrence and Cassandra Southick and their Son Josiah whipped
* William Shattock sent to the House of Correction, whipped and banished
* Sarah Gibbons and Dorothy Waugh
* Thomas Harris imprisoned and cruelly whipped
* Second Law against Quakers
* Barbarous Treatment of William Brend
* The People discontented at this Cruelty
* The Magistrates endeavour to appease them
* Priest Norton takes the Jailers Part
* Samuel Shattock,
* Lawrence Southick and others committed to Prison
* Their Letter to the Magistrates

By this retrospective view of the first inhabitants of New England,
it is clearly manifest,
that a persecuting spirit had found admission amongst these refugees from persecution,
long before any of the people called Quakers came into those parts,
and did not originate from any necessity occasioned
by their extravagant principles or practices,
as the New England apologists represent them.

We have seen the inimical disposition of the priests and ruling powers in England,
and their inveterate prejudice toward this people;
these being many of them of the independent class,
doubtless kept up a correspondence with their brethren in New England,
and it is probable filled their letters of intelligence
with invectives against the Quakers;
for it is manifest they had received an unreasonable prejudice
against them before ever they saw their faces;
and had condemned their principles as heretical,
before they had any fair opportunity of knowing what these principles were.

But buoyed up as they were with the high notion of their own righteousness,
and the ultimate refinement of their religion,
they seemed fixed in the determination to give no admission to any other doctrines,
than those which their, magistrates, under the influence of their teachers and synods,
thought proper to establish.
No sooner was the intelligence given of two female Quakers, Anne Austin and Mary Fisher,
being arrived from Barbados, in the road before Boston, than Richard Bellingham,
the deputy governor, immediately ordered them to be detained on board,
and dispatched officers to search their trunks and chests,
who taking away about one hundred books, carried them ashore.
On this extraordinary occasion, as Neale terms it,
a council extraordinary was convened by the governor,
as if to provide for the security of the state against the alarming
danger threatening it from the arrival of two harmless women,
which issued the following order:

[.embedded-content-document.legal]
--

[.signed-section-context-open]
At a council held at Boston 11th July, 11th 1756.

Whereas there are several laws long since made and published in this jurisdiction,
bearing testimony against heretics and erroneous persons;
yet notwithstanding Simon Kempthorn of Charles-town,
master of the ship Swallow of Boston, hath brought into this jurisdiction,
from the island of Barbados, two women, who name themselves, Anne,
the wife of one Austin, and Mary Fisher,
being of that sort of people commonly known by the name of Quakers,
who upon examination are found not only to be transgressors of the former laws,
but to hold very dangerous, heretical and blasphemous opinions;
and they do also acknowledge that they came here
purposely to propagate their said errors and heresies,
bringing with them and spreading here sundry books, wherein are contained most corrupt,
heretical and blasphemous doctrines,
contrary to the truth of the gospel here professed amongst us.
The council therefore tendering the preservation of the peace and truth
enjoyed and professed among the churches of Christ in this country,
do hereby order:

[.numbered]
_First,_
That all such corrupt books as shall be found upon search
to be brought in and spread by the aforesaid persons,
be forthwith burned and destroyed by the common executioner.

[.numbered]
_Secondly,_ That the said Anne and Mary be kept in close prison,
and none admitted communication with them without leave from the governor,
deputy governor or two magistrates, to prevent the spreading their corrupt opinions,
until such time as they be delivered aboard of some vessel,
to be transported out of the country.

[.numbered]
_Thirdly,_ The said Simon Kempthorn is hereby enjoined, speedily and directly,
to transport or cause to be transported the said persons from hence to Barbados,
from whence they came,
he defraying all the charges of their imprisonment and for the effectual
performance hereof he is to give security in a bond of 100£. sterling,
and on his refusal to give such security he is to be committed to prison till he do it.

--

In consequence of this order their books were burned by the hangman,
and the said two women were committed to prison by the deputy governor as Quakers,
upon no other proof than that one of them said thee to him,
where their confinement was so rigorous that nobody was admitted to converse with them,
even through the window.
Their pens, ink and paper were taken from them,
and they were debarred the use of a candle by night.
Next, in violation of every rule of decency, modesty and humanity,
they stripped them naked,
under the pretence of searching for tokens of their being witches,^
footnote:[These people, so ready to load the Quakers with reproachful epithets,
and impute the original of their religion to a spirit of delusion,
were themselves given up to strong and fatal delusions in respect to witchcraft,
which some time after affected them so universally that the magistrates,
priests and people of all ranks contributed to spread the mischievious
deception so far as to introduce general confusion and dismay;
and after their hands were tied up from hanging of Quakers,
they hanged one another for witchcraft and sorcery on vague accusations.
Not by the misguided fury of a superstitious populace;
but with all the formalities of a solemn trial,
by the hands of the common executioner nineteen persons of both
sexes suffered death in little more than three months time;
eleven more lay under condemnation, and one hundred and fifty in prison untried.
Most of these unhappy persons asserted their innocence
of the matters laid to their charge to the last,
many of them appear to have been of reputable lives and circumstance in the world.
And the principal tokens of fascination recorded
in their history appear to be in the prosecutors,
the judges and the jury,
who could condemn to death so many innocent persons upon such idle tales
and senseless absurdities as were given in evidence against them;
and after all,
when the people were so far restored to their senses as
to make public recantation of their erroneous proceedings,
their justice went no farther than words.
The accused persons, being some of them people of property,
had all their effects seized by the officers, of which afterwards, even those,
whose innocency was acknowledged, could never recover any,
or but a very inconsiderable part. --Neale]
and misused them in this search in a shameful and barbarous manner.
They were not only debarred of light and conversation,
but in a great measure of sustenance also,
which exciting the compassion of Nicholas Upsal, an ancient inhabitant of Boston,
he purchased of the jailer the liberty of sending them provisions,
at the extravagant rate of 5s. per week, for fear they mould be starved.
After about five weeks confinement, one William Chicester, master of a vessel,
was bound in a bond of 100£. to carry them back to Barbados.
And the jailer kept their beds and their bible for his fees.

A few days after the departure of these women,
viz. on the 7th of the month called August, eight others of the same persuasion, namely,
Christopher Holder, Thomas Thurston, William Brend, John Copeland, Mary Prince,
Sarah Gibbons, Mary Witherhead and Dorothy Waugh, arrived at Boston from London,
in a ship whereof Robert Locke was master.
He would not suffer them to go on shore,
till he had delivered a list of their names to the governor,
who sent officers on board to search their boxes, chests and trunks for books,
and to bring those eight, together with Richard Smith, an inhabitant of Long Island,
before the court, then sitting at Boston.
After some examination they were sentenced to banishment,
and to be detained in prison till they might be sent back in the same ship,
the master whereof was required to give security to take them back at his own charge,
which he refusing, was committed to prison, but after some days confinement,
fearing the loss of his voyage, he complied.
They were detained in prison about eleven weeks,
the jailer being empowered to search their boxes, etc. as often as he saw meet, for pen,
ink and paper, papers and books, and take them away.
While they were in prison a law was made to punish them,
being the first general law made against Quakers.

By this law it was enacted, that if any master or commander of any ship, bark,
etc. should thenceforth bring into any harbour in their jurisdiction any Quakers,
he should pay the sum of 100£. to the treasurer of the country,
or be imprisoned '`till the payment should be made or secured.
That any Quaker coming Into the country should be committed to the house of correction,
severely whipped, constantly kept to hard labour,
and debarred of intercourse with any person whatever.
Importers of Quakers`' books or writings, or whoever should disperse or conceal such,
to be fined 5£. If any inhabitants of the Colony
defended the books or opinions of the Quakers,
they were to be fined 40s.; for the second offence 4£. and for the third to be banished.

The uncharitable and unchristian temper, which actuated these colonial legislators,
is not more obvious in the severity of the penalties
enacted against this body of people and their adherents,
than in the illiberal,
reviling expressions and opprobrious nicknames whereby
they are described as a cursed sect of heretics,
blasphemous heretics, who hold devilish opinions:
Such terms of reproach are by men of candour and moderation generally looked
upon not so much a picture of the qualities of those they are applied to,
as of the intemperate bitterness of their spirits,
who debase themselves so far as to make use thereof.

The law being proclaimed by beat of drum in the streets of Boston,
Nicholas Upshall aforesaid, being affected thereat,
publicly testified his disapprobation,
for which being next morning sent for to the general court, he told them,
The execution of that law would be a forerunner of a judgment upon the country,
and therefore in love and tenderness, which he bore to the people and place,
desired them to take heed, least they were found fighters against God.^
footnote:[Neale, notwithstanding his laying claim to the character as impartiality,
on this and many other occasions,
betrays a manifest partiality in favour of this government,
and thus apologizes for their cruel treatment of this ancient man.
"`This was looked upon as an attack upon the legislature,
which might be attended with fatal consequences;
for it people might arraign the laws of their country in such an open manner,
the authority of the government would be quickly destroyed.`"]
For this he, though one of their Church-members, and of a blameless conversation,
was fined twenty pounds, and three pounds more for not coming to church,
from which he had withdrawn,
out of a conscientious dissent from a religion without charity.

They next banished him their jurisdiction, allowing him, who was an infirm ancient man,
but one month for his departure, driving him into exile in the winter.
Application being made to Endicot for a mitigation of his fine, he rudely answered,
"`I will not '`bate him a groat.`"
He removed to Rhode-island,
where he met with that hospitality and compassion from an Indian Prince, and a Pagan,
which was refused from his country men, pretending to refined Christianity,
who kindly invited him to fix his residence with him, and he would make him a warm house,
adding his admiration at the Englishmen`'s notion of the divine being,
who dealt so cruelly with one another about their God.

[verse]
____
Pudet hac opprobria nobis,
Et dici potuisse, et non potuisse refelli.

That such reproaches stain the christian name,
And stain with reason, is the christian`'s shame.
____

The first of this people who came to New England, after the making of this law,
was Ann Burden, widow, who although no preacher,
nor administering any occasion of offence,
or any cause of being termed a disturber of church or state,
being an honest inoffensive woman,
coming over on the reasonable errand of recovering
or gathering in some debts due to her in that country;
yet she was taken up, and carried before Bellingham, the deputy governor,
who upon examining her, although it was manifest, she had lawful business,
and he could find no fault or occasion of offence in her, only as she was a Quaker,
he said that she must abide their law, and committed her to prison,
where she was detained a quarter of a year, though sick at the same time.
During her imprisonment,
some of her acquaintance had procured of her debts
in goods to the value of about forty pounds,
which, when she was ordered to be sent away,
she desired liberty to carry with her to Barbados, to be disposed of,
being not fit for the English market; this reasonable request was denied her,
and a master of a ship compelled to carry her to England,
against her will and without her goods.
And when he inquired who should pay for her passage,
the magistrates bade him take so much of her goods as would satisfy him:
which however he would not do, having so much dependence on her honesty,
that though he could not compel her to pay, as she was sent away without her own consent,
yet that she would not let him be a loser,
and he was not disappointed in his expectation.

But after her departure,
the officers took away from the person entrusted to convey her goods to Barbados,
as many as were worth 6£. 10s. for her passage, which not they, but herself had paid:
7s. for boat-hire, although the master had offered to take her in his own boat,
and 14s. for the jailer.
Thus banished, and spoiled of a considerable part of her property,
and deprived of the possession and disposing of the residue,
no part whereof had come to her hands several years after, if at all.

The next of the Quakers who came to Boston, and suffered the extremity of the law,
was Mary Clark, from London,
who came thither under a religious concern to warn
those persecutors to desist from their iniquity.
She delivered her message to merciless men,
who rewarded her with twenty stripes of a three corded whip on her naked back,^
footnote:[The cords of these whips were usually as thick as a man`'s little finger,
and the stick sometimes so long that the executioner
made use of both his hands to strike with it.]
and detained her in prison about twelve weeks.
Christopher Holder and Christopher John Copeland, with others who had been banished,
under a firm persuasion of duty and full assurance of faith in divine support,
under whatsoever suffering they might be permitted to pass through, having returned,
were whipped with thirty stripes each, the executioner measuring his ground,
and inflicting the strokes with all his strength, which cut their flesh so severely,
that a woman fainted away at the sight.
After this they were kept three days without food or water,
so close that none might speak with them, lodging on the bare boards,
without bed or straw.
In this miserable confinement, they remained nine weeks, without fire,
in the cold winter season.
Richard Dowdney was taken up at Dedham, and brought to Boston,
and though he had not been there before, was also punished with thirty cruel stripes,
and sent away with the former two,
with threats of cutting off their ears in case they returned,
which threats they afterwards made good.

At the general court held in Boston the 14th of October, this year,
they made the following addition to the former law:

[.embedded-content-document.legal]
--

That if any person should entertain any Quaker or Quakers or other blasphemous heretics,
knowing them so to be,
every such person should forfeit to the country 40s.
for every hour`'s entertaining or concealment,
and be committed to prison till the forfeiture be fully paid and satisfied.
If any Quakers should presume, after they had once suffered the law,
to return into their jurisdiction, if a male,
he should have one of his ears cut off for the first offence;
the other ear for the second offence;
if a female to be severely whipped for the first offence;
the like punishment to be repeated for the second.
Both male and female moreover to be sent to the house of correction,
and kept to hard labour till they can be sent away at their own charge.
For the third offence their tongues were to be bored through with an hot iron.
That every Quaker arising from among themselves should be dealt with,
and suffer the like punishments as the law provides against foreign Quakers.

--

These several persecuting laws were not suffered to lie as a dead letter,
but the same wrathful and vindictive spirit, which had dictated them,
was manifested in the unmerciful execution thereof: No age, no sex,
no circumstance could move these unmerciful persecutors to compassion;
but the objects of their spoiling,
imprisoning or whipping furnished them almost daily employ.
To recite at full length all the instances of their cruelty would be tedious and disgusting;
a summary review will evidence the truth of this description.

The severities already inflicted on the members of this society,
had so affected many of the inhabitants of this colony,
that they withdrew from their public assemblies,
and met on the first day of the week to worship quietly by themselves,
for which they were fined 5s. per week, and imprisoned.
Particularly Laurence and Cassandra Southick,
an aged couple (who in the last year had been imprisoned and fined for
entertaining Christopher Holder and John Copeland) with their son Josiah,
were sent to the house of correction,
whipped in like manner and fined as those before mentioned,
and had their goods taken to the value of 4£. 15s. for not coming to church.
For the same cause Edward Hamet, aged sixty-nine, and his wife,
seventy-three years of age, had 37s. taken from them,
without regard to their circumstances, which were but mean, or their age,
which would naturally excite tenderness.

William Shattock a shoe-maker, being found on a first day of the week,
quietly sitting alone in his own house, in the time of their worship,
house of and being too poor to pay the 5s. a week, was sent to the house of correction,
cruelly whipped, and then kept to hard labour,
the profits whereof the jailer detained to his own use, leaving his family,
a wife and four small children, who had nothing but their labour to subsist on, in want.
At last he had only three days time as signed him, to depart out of their jurisdiction,
to which hard condition he was necessitated,
in order to be in a capacity to support himself and family, to submit.
Sarah Gibbons and Dorothy Waugh,
for speaking a few words at one of their lectures in Boston,
were also sent to the house of correction, kept three days without any food;
they were then cruelly whipped, and kept three days longer without victuals,
although they offered to purchase them.
Sarah, when brought before Endicott and the court, at the end of the first three days,
remonstrating against the jailer`'s cruelty,
received no redress from this tyrannical governor, but an ill-natured reply,
that he mattered not.

Thomas Harris, of Barbados, in the public, prisoned meeting place at Boston,
after the priest had done, having warned the people of the dreadful;
terrible day of the Lord, which was coming upon that town and country,
was presently hauled out by the hair of the head, and sent to prison,
where he was shut up in a close room, excluded like the rest from all company.
Next day he was cruelly whipped, and then shut up eleven days more,
five of which he was kept without bread, because he refused to work for the jailer,
and probably had been starved,
had not some humane people privately conveyed him some food through the window by night.

Reduced to great weakness by long fasting and the torture of whipping,
the jailer inured to cruelty and unfeeling barbarity,
insisted on his working (although disabled by his abusive treatment) and upon his refusal,
gave him, weak as he was, twenty-two blows with a pitched rope,
and some days after fifteen stripes with a three corded whip.^
footnote:[I think Neale`'s relation of this poor man`'s case demands some animadversions.
"`Harris (says he) like the rest of his brethren, would not strike a stroke in prison,
he would suffer anything, but do nothing;
nay so stubborn were he and his friends that they
would neither pay the fines that were laid upon them,
nor be at the charge of transporting themselves out of the country.`"
This author professes to give an impartial account of the affairs of New England,
to treat the mistakes which the government fell into
with regard to the Quakers and Anabaptists with freedom.
But I think this and many other passages of his work,
nay the general turn of expression through the whole
narration of their treatment of the Quakers,
and Anabaptists also, betrays a partial bias.
Small blemishes (for argument`'s sake admitting them such) on one
side exaggerated with severe acrimoniousness of expression,
and the greatest enormities which human nature can be capable of,
barbarous cruelty and inhumanity, on the other, softened in palliative terms,
are no instances of impartiality;
but manifest the writer to be under the influence
of an undue prepossession in favour of a party.
The fore-cited reflections appear to me evidently partial and unfair.
These original Quakers moved in a sphere superior to the walk, or even the conception of,
the persecuting professors of religion, how ever ostentatious,
or that of the wise men of this world, how ever puffed up by their knowledge,
without charity:
It was their solicitous and unremitted endeavour to trace out the plain
way to heaven through all attendant afflictions and tribulations on earth,
even that way which the vulture`'s eye hath not seen nor any ravenous beast,
nor persecuting spirit trodden in;
but wherein the way-faring man though a fool shall not err.
Careful and circumspect to do no evil,
and sincerely disposed to do the will of God,
as the means of finding peace and acceptance with him; in obedience to his requirings,
as they in the sincerity of their hearts believed, they were engaged to go to and fro,
to propagate righteousness,
and to convince the professors of Christianity of the insecurity
of trusting in any profession of _religion without holiness._
Conscious of the purity and disinterestedness of their motive,
and in the discharge of duty,
endeavouring to keep a conscience void of offence toward God and toward man,
they justly thought these New- England laws founded in injustice,
and the penalties inflicted with inhumanity,
a palpable infringement of the universal laws of God and nature:
They knew themselves to be innocent of just offence to God or man;
in this view to be active in their own punishment,
they thought a tacit acquiescence and confession of guilt,
which their consciences witnessed they were free from:
As faithful martyrs they patiently _suffered anything,_
that unreasonable men invested with arbitrary power might lie permitted to lay upon them,
for their open testimony to the truth, or against error;
_but they would do nothing_ that might imply an acknowledgement of guiltiness of any crime,
which they believed themselves in no degree guilty of;
And what in this conduct is justly blameable?
It was the only way left them under the administration
of unequal rule to assert their innocence,
to keep the reputation of that truth they maintained,
their conversation and their consciences unspotted,
which was a concern nearer to their hearts, than to rescue their bodies from torture.
{footnote-paragraph-split}
This author should have
first demonstrated the laws to be reasonable and just,
before he censured these men for declining a voluntary submission thereto;
whereas the unreasonableness hereof was so palpable,
that he cannot help owning it in different places: Yet from his manner of expression,
it seems as if admitted of no dispute,
that it was both reasonable and equitable that they should pay the fines imposed
upon them for no other crime than their religious dissent from the establishment,
and absenting from their public worship, which to have voluntarily done,
would be a tacit acknowledgement of error in their dissent.
He should have proved this a crime,
before he condemned their non-compliance with the punishment but
he could not do this without condemning their persecutors also,
whom he justifies under the same circumstance.
To tax them with stubbornness in refusing so unjust a requisition
as to pay the charges of their own transportation out of the country,
is so absurd,
so contrary to reason and every natural and humane rule that it needs no refutation;
and yet he censures them for this, as if it were their indispensable moral duty.
He goes on, "`They were as perverse and obstinate in prison, as out of it,
insomuch that the jailer was forced to lay the case before the magistrates,
who ordered him to whip them twice a week, etc.
But Harris and his friends were not to be tamed by these methods,
but resolved to die rather than submit,
and one of them was almost whipped to death upon this order;
but when Harris had suffered a second whipping, some of his friends paid his charges,
and he was dismissed.
And this became afterwards the usual practice of the Quakers not to pay their own fees,
but to suffer others to do it for them.`"]

On the 20th of 3rd month this year, another law was made,
which as a specimen of the temper,
the measure of charity and urbanity actuating this legislature,
take at length as follows.

[.embedded-content-document.legal]
--

[.signed-section-context-open]
At a Court at Boston the 20th of May, 1658.

That Quakers and such accursed heretics, arising among ourselves,
may be dealt with according to their deserts, and their pestilent errors and practices^
footnote:[Pestilent errors and practices, diabolical doctrines.
These are no more than hard names, without application or other meaning,
than that the framers had imbibed an intemperate and undeserved
bitterness of spirit against this people,
without due examination into their principles or practices.
If they were so pestilent, pernicious and diabolical,
they were the more easily exposed and refuted.
And their pastors (so termed) had manifested a more becoming zeal,
in exercising christian endeavours to preserve their flocks from infection,
by pious exhortations, by exposing the ill consequence of their _pernicious ways,_
and refuting their diabolical doctrines,
than by applying to the secular power to repress by violence,
doctrines which they were unable or too idle to refute by argument.]
may be speedily prevented, it is hereby ordered,
as an addition to the former laws against Quakers,
That every such person or persons professing their pemicious ways, by speaking, writing,
or meeting on the Lord`'s day, or at any other time, to strengthen themselves,
or seduce others to their diabolical doctrines,
shall after due means of conviction incur the penalty ensuing, that is,
every person so meeting shall pay to the country for every time 10s.;
and every one speaking in such meeting shall pay 5£. A piece;
and in case any such persons had been punished by scourging or whipping the first time,
according to the former laws,
they shall still be kept at work in the house of correction till they put in security,
by two sufficient men, that they shall not vent their hateful errors,
nor use their sinful practices;
or else shall depart the jurisdiction at their own charges:
And if any of them return again,
then each such person shall incur the penalties of
the laws formerly made for strangers.

--

But of all the instances of barbarous cruelty that in the records
of this furious government disgust the tender feelings of humanity,
the treatment of William Brend is scarcely exceeded, if not unparalleled,
in the history of civilized government.
In the latter part of the 5th month this year,
William Brend and William Leddra at the house of Robert Adams in Newbury,
by desire of the inhabitants, had a conference with a priest,
in the presence of one captain Gerish,
who had promised them protection from suffering for that conference;
yet because they did not comply with his orders to depart the town immediately,^
footnote:[Query, How far was this different from the tenet,
held in abhorrence by all Protestants, That no faith is to be kept with heretics?]
he violated his engagement in sending them by a constable to Salem,
where being interrogated by the magistrates, Whether they were Quakers?
they answered, We are in scorn called so.
Then it was objected to them, that they held dangerous errors, as denying Christ,
who suffered death at Jerusalem, and the scriptures.
Boldly contradicting this charge, they asserted that, They owned Jesus Christ,
who suffered death at Jerusalem, and owned the scriptures also.
Notwithstanding their denial of this false accusation,
and the confession of the magistrates, that they found no evil in them,
they were committed to prison there,
and thence transmitted to the house of correction in Boston,
where they were required to work; but they being not free to submit to this requisition,
as being convicted of no crime, the jailer, who sought his gains from their labour,
would allow them no victuals, though they offered to pay for them, telling them,
it was not their money, but their work which he wanted.
Five days they were kept from food,
and then received twenty stripes with the three-corded whip.
Some time after he let them know, they were at liberty to depart, upon paying their fees,
and hiring the marshal to conduct them out of the country.
This unreasonable condition they were not free to comply with,
but signified their willingness to accept their liberty, if it were freely granted.

Next day this most cruel and inhuman jailer put William Brend, a man in years, in irons,
neck and heels so close together,
that there was only room for the lock that fastened them,
and kept him in this painful posture from five in the morning till after nine at night,
above sixteen hours.
Next morning he insisted on William`'s falling to work for him,
disabled by the preceding cruel treatment, which he refused to do,
whereupon this brutal jailer^
footnote:[What is most amazing, this jailer, so destitute of every symptom of humanity,
was a pretender to religion, and was careful that very morning,
after satiating his vengeance on this poor man, to address himself to his morning prayer;
but to what purpose, the prophet Isaiah, in the name of the Almighty,
in the following strong reproof, hath plainly declared, "`When you make many prayers,
I will not hear; your hands are full of blood.`"
Such a religion afforded just grounds for the following reproof of Humphrey Norton,
delivered at the close of one of their lectures: "`Verily,
this is the sacrifice which the Lord accepts not;
for while with the same spirit that ye sin, ye preach, and pray and sing,
that sacrifice is an abomination to the Lord;`" for
which he received his fifteen lashes instead of ten.]
took a pitched rope, about an inch thick,
and gave him twenty blows over his back and arms
with all his strength till the rope untwisted:
Then he fetched another rope thicker and stronger, and with the utmost violence,
foaming at the mouth with passion to distraction,
laid on his bruised body fourscore and seventeen blows more,
by the report of other prisoners,
who with grief and compassion beheld this cruel abuse of an honest man,
who had done nothing worthy of bonds, till his strength and his rope failed him,
and the poor man`'s back and arms were so reduced to one gore of blood,
that the sign of a particular blow could not be distinguished, he desisted not;
and even then desisted with passionate menaces of repeating equal cruelty the next day.
But he had already gone too far, an higher power, who limits the raging sea, saying,
"`Hitherto shalt thou go,
and no farther,`" here set bounds to the raging fury of this barbarous executor of vengeance,
by raising help from an unexpected quarter.

I have already apprised my readers, that in my remarks on the present ruling powers,
I mean not to throw reflections on any body of people;
but only persecutors and fomenters of persecution.
I am persuaded that, amidst too much insincerity in the profession of religion,
while the grasping at undue exercise of temporal authority was the end in view,
there were multitudes among the independents, who were more sincerely religious,
and secretly regretted the extremities, to which these rulers stretched their authority.
In the present case,
the persevering inhumanity of this jailer towards this inoffensive
sufferer had so far exhausted his natural strength,
that he fell down under his hands so extremely weakened,
that for some time he lost his sight, hearing and feeling, turned quite cold,
and had about him all the symptoms of a dying man.

The noise of this cruelty getting abroad,
the murmurs of the people broke out into a general outcry against it,
which caused the governor to send his surgeon to the prison to examine his condition,
who, despairing of his recovery, reported that the flesh would rot off his bones,
ere the bruised parts could be brought to digest.
This report exasperated the people to that degree, that the magistrates,
to appease them and prevent a tumult, set up a paper at the meeting-house doors them,
and other public places, signifying their dislike of this abominable cruelty;
and that the jailer should be dealt with at the next court day.
But this paper was soon after taken down at the instigation of their chief priest,
John Norton, a principal promoter of the persecution from the beginning,
who on this occasion manifested himself as destitute of common humanity,
as of christian charity, in the following cruel,
unjust and unmeaning parallel between the sufferer and the pretended cause of his suffering,
William Brend (said he) endeavoured to beat our gospel ordinances black and blue;
if then he be beaten black and blue, it is but just upon him,
and I will appear in his behalf that did it.
The ridiculous absurdity of this nonsensical reflection would only merit contempt,
if the inveterate bitterness thereof, exciting to cruelty upon cruelty,
did not extort abhorrence.
It is therefore no cause of admiration, that under such teachers the magistrates,
priest-ridden, and stimulated to rage by their inflammatory discourses,
were so prompt to persecution; that blind zealots, led by blind guides,
should with their leaders fall into the ditch of error,
in treating with avenging wrath the promulgators of truth.

In the meantime William Brend miraculously recovering,
the dissatisfaction of the people dying away,
and the magistrates recovering from the panic into which the apprehension
of his dying by the jailer`'s cruelty had thrown them,
persisted in the same line of cruelty;
instead of calling the jailer to account as they had promised,
they strengthened his hands by the following order: "`That the jailer,
if the Quakers refused to work, should whip them twice a week,
the first time with ten lashes, the next time with fifteen,
and so each time with three more till they would work;`" but to preserve
some appearance of disposition to moderate the jailer`'s fury,
they ordered that he should warn two constables to oversee the execution.
This order was executed and exceeded upon William Leddra, Thomas Hams,
Humphrey Norton and John Rouse,^
footnote:[Neale goes on,
(see note on T. Harris) "`They were as perverse and obstinate in prison as out of it,
insomuch that the jailer was forced to lay the case before the magistrates,
etc. etc.`" as in the note referred to.
{footnote-paragraph-split}
"`One of them was almost whipped to death.`"
This was William Brend, above mentioned,
whose particular grievous suffering he could hardly be ignorant of,
as he quotes Bishop`'s [.book-title]#New England Judged,# frequently,
and consequently had read it, whose account corresponds with the preceding recital:
Yet he briefly passes it over thus:
"`William Brend and William Leddra were sent to the house of correction at Boston;
and having received ten lashes, were told they might have their liberty,
paying their fees, and hiring the marshal to convey them out of we country;
but they refused to depart, and were therefore whipped more severely,
till some of their friends laid down the money, and so they were discharged.`"
{footnote-paragraph-split}
After reviewing my foregoing relation of the case of W. Brend,
as I find it related by W. Sewel, Jos. Besse,
and in [.book-title]#New England Judged,# which all in the general correspond,
and which last was published near the time of these transactions,
and the veracity thereof never called in question, that I have heard of:
On comparing this narration of Neale`'s therewith,
we plainly discover the partiality of his pen, pasting over in silence,
or slightly noticing in softened general terms,
all the instances of their barbarity which shock humanity,
to avoid exposing the memory of the perpetrators thereof
to the infamy naturally attendant on such actions,
or even to screen them from every imputation of guilt or blame,
his relation bearing a complexion as if the unhappy sufferers were alone blameable.
If his state of the case is not evidently very partial and unfair throughout,
let the reader judge upon the comparison thereof with the account in the treatise,
entitled New England judged,
which he quotes in marginal references almost from page to page as his authority.
Neale says,
"`after having received ten lashes they were told they might have their liberty,
etc.`" which leads us naturally to imagine this offer
was made them immediately after the whipping,
which was not the case as represented in that treatise: "`Having whipped them,
the jailer locked them up in a close room, dark and without air,
in the hot summer season, from food and friend, till the fourth day following,
(two days) then he told them they were clear,
paying their fees (who owed him none) and hiring the marshal to convey
them out of the country,`" (which they were not free to do,
as having done nothing worthy of bonds or banishment.) But if they were clear,
having suffered the penalty of their unauthorised inhospitable law,
what right had this hypocritical jailer to inflict further punishment upon them?
They were now in the most favourable light on his side, simply his debtors for a trifle,
and what right could he, or the most strenuous apologist for him,
claim beyond that of detaining them in prison for their debt unpunished,
untstrained from food, which they were willing to purchase but were not suffered.
But after this, his declaring them clear,
it was that William Brend was whipped almost to death, as before described.
Neale`'s mutilated account of this transaction is to me a plain evidence,
of his partiality: He says, "`one of them was almost whipped to death:
He had read Bishop`'s account, Why not tell who it was and how?
Why pass over the sufferings of William Brend,
when he undertakes to relate it in so cursory a manner,
but to cover the cruelty of his persecutors and endeavour to fix
a stigma on the poor man as the author of his own sufferings?
"`They refused to depart, and were therefore whipped more severely.`"
This, by our account, is a false state of the case: They did not refuse,
but signified their willingness to depart, if they might freely;
but this was refused them, except on unreasonable terms,
they could not in conscience comply with;
neither can I discover upon what authority (for he cites
none) he asserts "`that their friends laid down the money,
and so they were discharged.`"
The authority he generally quotes says no such thing as to William Brend,
and it is so contrary to the practise of these, I understand by his friends,
that I shall believe it a misrepresentation,
till I have stronger evidence of its truth than D. Neale`'s bare assertion.
{footnote-paragraph-split}
The like account we have in Harris`'s case;
"`Some of his friends paid his charges, and so he was dismissed.
And this became afterwards the usual practise of the Quakers, not to pay their own fees,
but to suffer others to do it for them.`"
And he quotes New-England judged for his authority;
but how justly will best appear from the transcript
of the passage in that treatise referred to,
which is as follows: "`Which bloody cruelty,
(viz. of repeated whipping) so affected the inhabitants of Boston,
to see new stripes on old sores, and some of the old sores upon them,
when they came to be whipped the second time;
that they paid the charge required for them, as they usually did,
as to all that were in prison, that they might be set free.`"
Now by the term, his friends, is generally understood,
and I suppose he would have us understand,
that others of the Quakers paid their charges to redeem them from prison;
whereas it is plain,
that George Bishop means some compassionate inhabitants
of Boston (not Quakers) of whom many were discontented,
and ashamed of the cruelty of their rulers,
and out of commiseration to the unhappy and innocent sufferers, paid their fees,
which they were not free to pay themselves,
to rescue them from under the hands of men insatiate in cruelty:
But the Quakers looking upon the payment thereof, as giving away the cause of innocency,
neither paid them for themselves, nor one for another,
although they sympathised in each others sufferings;
but indeed they shewed their sympathy but badly, if they could pay at all,
that they let them be whipped almost to death before they interfered in their favour.
Further, this representation of Neale`'s insinuates an appearance of insincerity,
the very reverse of their real character.]
who each of them received the first time fifteen stripes instead of ten;
but we have no account of either jailer or constable being called
to account for transgressing the limitation of their order.

About this time there was a meeting at the house of Nicholas Phelps, in the woods,
about five miles from Salem, and upon the information of one Butter,
the six following residents were taken up and committed to prison, Samuel Shattock,
Laurence Southick, and Cassandra Southick his wife, Josiah their son,
Samuel Gaskin and Joshua Buffum, who being kept close in their house of correction,
during the heat of the summer, from their husbandry, after three weeks confinement,
represented their case to the court in the following letter:

[.embedded-content-document.letter]
--

[.letter-heading]
This to the Magistrates at the Court in Salem.

[.salutation]
Friends,

Whereas it was your pleasure to commit us, whose names are under-written,
to the house of correction in Boston, although the Lord,
the righteous Judge of Heaven and Earth,
is our witness that we have done nothing worthy of stripes or of bonds;
and we being committed by your court to be dealt
withal as the law provides for foreign Quakers,
as ye please to term us; and having some of us suffered your law and pleasures,
now that which we do expect is, That whereas we have suffered your law,
so now to be set free by the same law, as your manner is with strangers,
and not to put us in upon the account of one law, and execute another law upon us,
of which according to your own manner we were never convicted, as the law expresses:
If you had sent us upon the account of your new law,
we should have expected the jailer`'s order to have been on that account,
which that it was not appears by the warrant which we have,
and the punishment which we bare, as four of us were whipped,
among whom was one that had formerly been whipped; so now, according to your former law,
friends, let it not be a small thing in your eyes, the exposing as much as in you lies,
our families to ruin.
It`'s not unknown to you, the season and the time of the year,
for those that live of husbandry, and what their cattle and families may be exposed unto;
and also such as live on trade: We know,
if the spirit of Christ did dwell and rule in you
these things would take impression on your spirits.
What our lives and conversations have been in that place is well known;
and what we now suffer for, is much for false reports,
and ungrounded jealousies of heresy and sedition.
These things lie upon us to lay before you: As for our parts,
we have true peace and rest in the Lord in all our sufferings,
and are made willing in the power and strength of God,
freely to offer up our lives in this cause of God, for which we suffer: Yea,
and we do find (through grace) the enlargements of God in our imprisoned state,
to whom alone we commit ourselves and families,
for the disposing of us according to his infinite wisdom and pleasure,
in whole love is our rest and life.

From the house of bondage in Boston, wherein we are made captives by the wills of men,
although made free by the Son. John 8:36.
In which we quietly rest, this 16th of the 5th mo 1658.

[.signed-section-signature]
Laurence Southick, Cassandra Southick, Josiah Southick, Samuel Shattock, Joshua Buffum.

--

Upon this representation Samuel Shattock Joshua Buffum were released,
but the other three arbitrarily detained in prison.
It was not long till those who had been released were sent
back to rejoin their former companions in prison,
for absenting from their public meetings, and meeting by themselves contrary to law;
for which they were each fined by the court at Ipswich 5s.
for absenting from their worship by the law of 1646,
and 10s. each for meeting by themselves.
After this they proceeded to condemn them to punishment
upon their last law against Quakers,
as being such.
Upon which they demanded a fair trial by a jury,
and evidence to prove them such as that law described, viz. cursed heretics,
who hold blasphemous opinions, and promulgate diabolical doctrines;
but this just demand would not be granted:
Broadstreet intimating the court would find out an
easier way to discover a Quaker than by blasphemy,
(a confession which it was easier to charge than to prove) so concluding
them Quakers from appearing with their hats on,
the court, without any further proof or inquiry,
sentenced them to be whipped with ten stripes a piece.
About three weeks after they were brought before the general court at Boston.
From which they repeated their demand of a fair trial, and received a second refusal;
they remonstrated against the unjust punishments, which had been inflicted upon them;
they refuted their charges; they maintained, beyond contradiction,
that they had already suffered the punishments prescribed by their laws,
and therefore had a just claim to their liberty:
Although the court was in no wise inclined to admit their just claim,
they were reduced to a nonplus,
to find a pretext of any plausible complexion for adding punishments
beyond law to the various penalties of their unrighteous laws.
Wherefore they continued them in prison,
to consider what further measures to take with them.

The next day was their lecture day at Boston, at which Charles Chauncey,
the president of their college or university,
preached an occasional lecture for the purpose of furnishing a
palliative for inflicting additional punishments upon them,
by the following savage and uncharitable comparison:
"`Suppose ye should catch six wolves in a trap,^
footnote:[Alluding to the six prisoners,
against whom they could prove no offence of any consequence,
much less any crime worthy of stripes or bonds.]
and ye cannot prove that they killed either sheep or lambs;
and now you have them they will neither bark nor bite;
yet they have the plain mark of wolves.
Now I leave it to your consideration (said he) whether you will let them go alive,
yea or nay?`"
Which strange reasoning applied, as intended, to the case of the prisoners,
amounts to this: "`You have six Quakers in your custody,
and you have already punished them as far as the law authorizes you;
you can prove nothing really criminal in their conduct,
and their demeanour in your hands is inculpable:
Yet they have the plain marks of Quakers, and therefore you are to consider,
whether it be expedient to let them go after suffering the punishment of former laws,
or hold them fast till some severer laws be enacted
to inflict heavier punishments upon them.`"
How inconsistent are the inferences naturally arising
from this strange parallel with the duty of his station,
as a tutor of youth or minister of the gospel.
And whatever his character might be as a scholar,
little credit can accrue to him as a lawyer or a minister:
To propose the punishing of men, not for what they had done, but what they might do,
is so evidently preposterous, so opposite to the spirit of law and gospel,
morality and religion,
that one might wonder how it could enter into any man`'s heart to conceive,
or how his tongue could be brought to utter it upon so solemn an occasion,
as that of a religious exercise.
But we have herein one instance among many of the spirit of these New-England priests,
ever ready to add fuel to the strange fire of persecution in the magistrates,
and not only to foment their sanguinary measures,
but often to be the first proposers and promoters of them.
This lecture, with other efforts of the priests,
prompted the magistrates soon after to go one step farther,
and enact a law to banish the Quakers on pain of death:
And these six persons will appear to be first upon whom it was enforced.
