== Chapter XVI.

[.chapter-synopsis]
* Christopher Holder, John Copeland and John Rouse have their right Ears cut off
* Their Appeal to England rejected
* Katharine Scot whipped
* Many join in Society with the People called Quakers
* The Priests petition for a Law to banish them on pain of Death
* Opposed by the Court of Deputies
* By the Instigation of the Priests carried by one Vote
* Two Deputies enter their Protest against it
* Laurence Southick, Samuel Shattock, etc. banished upon the Act
* Recapitulation of the Treatment of Laurence and Cassandra Southick
* Their Son and Daughter fined for absence from the Public Worship
* Ordered to be sold for bond Slaves to satisfy the Fine
* William Robinson, Marmaduke Stevenson, Mary Dyer and N. Davis banished on pain of Death
* The three former continue or return and are all condemned to Death
* Mary Dyer`'s Letter to the General Court
* They are led to execution with Drums beating
* Reflections on their Usage
* Mary Dyer reprieved
* Inhumanity to the dead Bodies
* People disgusted at these Executions

We come now to the execution of their law against such as should presume to return,
after they had suffered before.
Christopher Holder and John Copeland coming to Dedham, and lodging there one night,
were next day taken by a constable and carried to Boston,
where being brought before the governor,
he in a rage addressed them with this rough salutation,
You shall be sure to have your ears cut off.
Soon after John Rouse also coming to Boston was clapped into prison.
On the 10th of September these three were brought before the court of magistrates, where,
after some reflections cast upon them, Endicot, in fierce wrath,
pronounced the following sentence:
It is the sentence of this court that you three have
each his right ear cut off by the hangman;
which sentence was executed upon them the 16th. The deputy
marshal having admitted as many as he thought proper,
had the doors made fast, and the prisoners being brought into another room,
John Rouse told the marshal, We have appealed to the chief magistrate of England.^
footnote:[Humphry Morton, and the others whipped with him, appealed also to England;
but Endicot and Bellingham violently opposed it, crying out,
"`no appeal to England! no appeal to England!`"]
To which he answered, I have nothing to do with that.
Holder said, Such execution as this should be done publicly, and not in private;
for that was contrary to the law of England.
Captain Oliver replied, We do it in private, to keep you from tailing.
The executioner then proceeded to the execution of his office upon Holder; the marshal,
who was ordered to see the execution, turned his back,
upon which Rouse called to him to turn about, and see it, according to his order,
and then he turned again.
After Holder suffered the amputation of his ear, Rouse undauntedly suffered the like,
and after him Copeland, which being done, they said, "`Those who do it ignorantly,
we desire from our hearts the Lord to forgive them; but for them that do it maliciously,
let our blood be upon their heads; and such shall know in the day of account,
that each drop of our blood shall be heavier than a mill-stone.`"

Amongst others whom curiosity or compassionate sympathy had drawn
to see this execution was Katharine Scot from Providence,
who, upon observing it was to be done in private,
remarked that it was evident they were doing the work of darkness,
or else they would have brought them forth publicly, and have declared their offences,
that others might hear and fear.
For this sensible observation, she, who was a woman of blameless conversation,
good education and circumstances, was committed to prison,
and severely whipped with a three-fold cord knotted whip.
And, upon her examination, being threatened with hanging she came thither again,
she gravely replied, God calls us, woe be to us, if we come not;
and I question not but he whom we love will make us not to count our lives dear to ourselves,
for his name`'s sake; to which Endicot, from the malignity of his heart, rejoined,
And we shall be as ready to take away your lives, as you shall be to lay them down,
which savage expression his actions afterwards cruelly made good.

For notwithstanding all the sanguinary laws hitherto enacted by these rigid rulers,
and the more sanguinary punishment inflicted upon
this people in many cases without or beyond law,
under the full persuasion of duty several of them were still concerned,
notwithstanding all attending danger and difficulty,
to continue their travels for the fulfilling that
ministry they believed themselves called unto,
although they were sensible bonds and afflictions abode them; by the exercise whereof,
as well as the beholding of their patience under their sufferings,
many of the inhabitants of Boston,
Salem and other places had been brought over to join with them in gospel fellowship,
and many more to sentiments of compassion and good-will toward them.
The arbitrary rulers of this colony,
mortified to the last degree to find all the vindictive
measures they had adopted to suppress this new sect,
resulting in a general commiseration of the sufferers,
and a general dissatisfaction at their rigorous and persecuting proceedings;
that the society gained ground under all the difficulties
and disadvantages they were exposed to;
and the more barbarous severities they inflicted upon them,
the more the disgraceful employment grew upon their hands,
determined to resort to the last extremity,
and enact a law to banish them on pain of death.

This was not so easy a matter for them to get accomplished,
the tender feelings of the people being awakened
by the repeated instances of their former cruelty,
and the patience of the sufferers.
Many of the sober part of all ranks were very averse to this proposed measure,
and not backward to declare their aversion; but where the civil,
ecclesiastical and military powers are combined,^
footnote:[These magistrates, conscious where their strength lay,
viz. of the power being in their own hands,
were not ashamed to exercise it without regard to equity or morality.]
be their measures right or wrong, all opposition is ineffectual;
and in the present case the chiefs of these three orders, John Endicot governor,
Richard Bellingham deputy governor, John Norton and John Wilson chief priests of Boston,
and the majors-general Dennison and Adderton,
constantly appear amongst their determined foes, and most sanguine fomenters,
or administrators of persecution against them.
John Norton, in conjunction with others of the priesthood,
(who had been all along at the bottom of these persecuting
measures) pretended ministers of the gospel,
who came not to destroy men`'s lives but to save them, forgot their duty so far,
that they presented a petition to the magistrates,
to make some law to banish the Quakers upon pain of death,
thus prescribing to them the measures to pursue.
In consequence whereof the magistrates, in their general court held in Boston in October,^
footnote:[The general court is composed of the magistrates
and deputies elected by the freemen of the respective towns;
this court hath the power of judicature, as well as the supreme legislative power:
it is constituted of two houses, the court of magistrates and the court of deputies,
each fitting and acting a part.
The laws are to be transmitted from one house to the other,
and not to be in force till passed by a majority of both houses;
and if any disagreement or difference in judgment arise between the two houses,
it is to be decided by a majority of both houses met together.
Appendix to Neale`'s [.book-title]#History of New England, Vol. 2.# p. 336.]
at the instigation of the priests, and to gratify their own mortal hatred,
made no difficulty of passing an act to banish and
put them to death without a trial by jury,
agreeing it should be executed by a county court, consisting of three magistrates,
the majority of whom were to give judgment, and condemn to death at their pleasure;
but the court of deputies would by no means agree to it,
as being contrary to the laws of England to put men to death without a trial by a jury.
However the magistrates and priests were so fluence
of determinedly bent to gain their point,
that they the priests exerted all their influence with the deputies,
and at last prevailed upon two of them to change sides,
and even then their sanguinary law was carried by a majority of one voice only;
the speaker and eleven more being against, and thirteen for it.
One Wozel, a deacon of their church and a deputy, was affected so much on the occasion,
that being confined by indisposition, he desired to be sent for,
when the law should be put to the vote; but it was carried in his absence,
which when he heard, in the anxiety of his heart he went to the court,
and desired his vote might be taken,
with tears expressing his sorrow that his absence should occasion such a law to pass,
saying, That if he had not been able to go,
he would have crept on his hands and knees to prevent it.
Thus was the law carried to banish them on pain of death by a majority of three magistrates,
without the interposition of a jury; yet two of the deputies enter ties,
Captain Edward Hutchinson, and Thomas Clark of Boston, merchant,
being still dissatisfied, did enter their protest against the law;
because it was contrary to a standing law of the country, which was,
that none be sentenced to death and banishment but by a special jury and court of assistants.^
footnote:[Court of Assistants consists of the governor,
deputy governor and magistrates of Boston.]
And it seems that the law was amended, prescribing a legal trial,
(if it can be called a trial at all) consonant to this standing law.
Thus on the 20th of October, 1658, they passed the following act:

[.embedded-content-document.legal]
--

=== An act made at a general court held at Boston the 20th of October, 1658.

Whereas there is a pernicious sect, commonly called Quakers, lately arisen,
who by word and writing have published and maintained many dangerous and horrid tenets,^
footnote:[Dangerous and horrid tenets: What these dangerous and horrid tenets were,
is neither specified in this nor any other of their laws.]
and do take upon them to change and alter the received laudable customs of our nation,^
footnote:[Laudable customs, viz: The pulling off the hat.]
in giving civil respect to equals or reverence to superiors,
whose actions tend to undermine the civil government,^
footnote:[Whose actions tend to undermine the civil governments:
If any of their conduct had this tendency,
it is a wonder these rulers never specified these dangerous actions,
because a specification thereof would have been a better
apology for their severe laws than any they have published.]
and also to destroy the order of the churches,
by denying all established forms of worship,^
footnote:[Denying all established forms of worship: Turpe est doctori,
cum culpa redarguit ipsum.
What was the cause of these legislators leaving their native land,
but their dissent from the established forms of worship there.
Is not this law an apology for Laud and his associates,
in asserting a right to punish men for denying established forms,
particularly as they stopped short of the extremities
to which these precise barbarians proceeded;
they neither banished nor hanged any of their preachers, the hardships,
they had chiefly to complain of, being a deprivation of their ecclesiastical emoluments,
which the Quakers wanted not from them.]
and by withdrawing from orderly church-fellowship,
allowed and approved by all orthodox professors of truth, and instead thereof,
and in opposition thereunto, frequently meeting by themselves,
insinuating themselves into the minds of the simple,
or such as are least affected to the order and government of church and commonwealth,
whereby divers of our inhabitants have been infected,
notwithstanding all former laws made upon the experience
of their arrogant and bold obtrusions,
to disseminate their principles amongst us,
prohibiting their coming into this jurisdiction,
they have not been deterred from their impetuous attempts
to undermine our peace and hazard our ruin.

For prevention thereof, this court doth order and enact,
that every person or persons of the cursed sect of Quakers, who is not an inhabitant of,
but is found within this jurisdiction,
shall be apprehended without warrant where no magistrate is at hand, by any constable,
commissioner, or select man,
and conveyed from constable to constable to the next magistrate,
who shall commit the said person to close prison,
there to remain (without bail) unto the next court of assistants,
where they shall have a legal trial by a special jury;
and being convicted to be of the sect of the Quakers,^
footnote:[This conviction doth not appear to be by evidence of any matter of fact,
but their coming into the court covered, saying thee and thou;
and such like marks of their being Quakers so called,
were assumed by the court as sufficient evidence
to convict them upon even in case of life and death,
which proceeding drew from William Leddra this pertinent remark,
"`you will put me to death for speaking English, and for not putting off my clothes.`"]
shall be sentenced to be banished upon pain of death:
And that every inhabitant of this jurisdiction,
being convicted to be of the aforesaid sect, either by taking up,
publishing or defending the horrid opinions of the Quakers, or the stirring up mutiny,
sedition or rebellion against the government,
or by taking up their abusive and destructive practices,
viz. denying civil respect to equals and superiors,
and withdrawing from our church assemblies,
and instead thereof frequenting meetings of their own in opposition to our church order,
or by adhering to or approving of any known Quaker,
and the tenets and practices of the Quakers that are opposite
to the orthodox received opinions of the godly,
and endeavouring to disaffect others to civil government and church order,
or condemning the proceedings and practices of this court against the Quakers,
manifesting thereby their compliance with those whose design
is to overthrow the order established in church and state,
every such person,
upon conviction before the said court of assistants in manner aforesaid,
shall be committed to close for one month, and then,
unless they choose voluntarily to depart this jurisdiction,
shall give bond for their good behaviour, and appear at the next court,
where continuing obstinate, and refusing to retract and reform the aforesaid opinions,
they shall be sentenced to banishment upon pain of death; and any one magistrate,
upon information given him of any such person, shall cause him to be apprehended,
and shall commit any such person to prison, according to his discretion,
until he come to trial as aforesaid.

--

Such a sample of legislation is a monument of lasting infamy to the legislators.
To enact and inflict capital punishment from personal dislikes,
for mere personal offences, or a conscientious dissent to established forms,
even with a constitutional authority, is little short of murder;
but without it it is well nigh murder of malice prepense.
For as to the undermining or inciting to disaffection to the civil government,
to its ruin, these are no more than vague pretexts, unsupported by matter of fact.
The usual subterfuge of persecution, to strip itself of the odium of its real character,
is to clothe religious dissent with the robe of sedition in the state;
yet the preamble of this law points chiefly at religious scruple or inoffensive usages,
which mark it at first view with the stamp of downright persecution to death.
1659.

The first victims to this severe law were Laurence and Cassandra Southick,
their son Josiah, Samuel Shattock, Nicholas Phelps and Joshua Buffum.
They were called before the court the 11th of 3rd month, 1659,
and on their trial (such as it was) the same arbitrary spirit of tyranny
appeared in their manner of executing as in passing their laws.
The prisoners making a rational objection to their proceeding against them by this law,
as being in custody when it was made,
and therefore as to them a post facto law.--To their query,
whether it was for an offence against that law, which then had no existence,
they were committed to prison and banished, they received no reply;
then one of them desired the governor,
that he would be pleased to declare before the people the
real and true cause of their proceedings against them;
he answered, it was for contemning authority in not coming to the ordinances of God.^
footnote:[What he particularly meant by the ordinances of God I cannot determine;
if it was their public worship,
(for their absence from which they had before suffered by
fines and by whipping) I think it is a bold appellation,
and more blasphemous than anything objected to the Quakers,
as applied to that worship and that religion which produced no better fruits.
Such bitter waters never issued from a divine fountain.]
He further charged them with rebellion against the authority of the country,
in not departing according to their order; to which they answered,
They had no other place to go to, but had their wives, children,
families and estates to look after; nor had they done anything worthy of death,
banishment or bonds,
or any of the hardships or ignominious punishments
which they had suffered in their persons,
besides the loss of one hundred pounds worth of their
property taken from them for meeting together.
This remonstrance of their recent accumulated injuries silencing the governor,
Major-general Dennison made this unanswerable reply,
that they stood against the authority of the country in not submitting to their laws;
that he should not go about to speak much of the error of their judgments, but, added he,
you and we are not able well to live together: At present the power is in our hand,
and therefore the strongest must fend off.^
footnote:[Have we, in the history of that reign,
which these men and their partisans so freely represent
under the epithets of despotic and tyrannical,
so barefaced an assertion of arbitrary power as this?]
After this the prisoners were put forth for a while, and being called in again,
the sentence of banishment was pronounced against them,
and no more than a fortnight`'s time allowed for them to depart on pain of death;
and although they desired a respite to settle their affairs,
and till an opportunity of a convenient passage to England might occur,
the unrelenting malice of their persecutors would
not grant them even this small and reasonable request;
so Samuel Shattock,
N+++.+++ Phelps and Josiah Southick were obliged to take
an opportunity that presented four days after,
to pass for England by Barbados,
in order to seek redress from the parliament and council of state there,
but without success.^
footnote:[Neale is guilty of an unaccountable mistake in asserting
that none of these returned into the country any more,
whereas Samuel Shattock was the man, who, as king`'s commissioner,
carried over his mandamus to the governor of New England to put
a stop to their illicit proceedings in putting Quakers to death.
This mandamus he seems to have copied from New England judged,
where he must surely have seen it was carried over by said Shattock.
Josiah Southick and N. Phelps also returned in 1661, before the arrival of S. Shattock,
N+++.+++ Phelps being ancient died soon after,
and J. Southick was afterwards whipped through several towns.]
Laurence and Cassandra Southick went to Shelter Island,
where they soon after died within three days of each other;
and Joshua Buffum retired to Rhode Island.

The proceedings of these haughty rulers are strongly
marked throughout with the features of self-importance,
inhumanity and bitter malignity;
but I know of no instance of a more persevering malice and cruelty,
than that wherewith they persecuted the aforesaid
Laurence and Cassandra Southick and their family.
First, while members of their church,
they were both imprisoned for entertaining strangers,
Christopher Holder and John Copeland, a christian duty,
which the apostle to the Hebrews advises not to be unmindful of.
And after seven weeks imprisonment,
Cassandra was fined 40s. for owning a paper written by the aforesaid persons.
Next for absenting from the public worship and owning the Quakers`' doctrine,
on the information of one captain Hawthorn,
they with their son Josiah were sent to the house of correction,
and whipped in the coldest season of the year,
and at the same time Hawthorn issued his warrant to distrain
their goods for absence from their public worship,
whereby there were taken from them cattle to the value of 4£. 15s.
Again they were imprisoned with others for being at a meeting,
and Cassandra was again whipped,
and upon their joint letter to the magistrates before
recited the other appellants were released;
but this family,
although they with the rest had suffered the penalty of their cruel law fully,
were arbitrarily detained in prison to their great loss and damage,
being in the season of the year when their affairs most immediately demanded their attendance.^
footnote:[While they were in prison,
William Maston coming through Salem in his way to Boston,
brought them some provisions from home, for which he was committed to prison,
and kept there fourteen days in the cold winter season,
though about seventy years of age.]
And last of all were banished upon pain of death, as before recited,
by a law made while they were imprisoned,
and consequently against which they had not offended: Thus spoiled of their property,
deprived of their liberty, driven into banishment, and in jeopardy of their lives,
for no other crime than meeting apart, and dissenting from the established worship,
the sufferings of this inoffensive aged couple ended only with their lives.

But the multiplied injuries of this harmless pair were not sufficient
to gratify that thirst of vengeance which stimulated these persecutors,
while any member of the family remained unmolested:
During their detention in prisons they left at home
a son and daughter named Daniel and Provided;
these children, not deterred by the unchristian treatment of their parents and brother,
felt themselves rather encouraged to follow their steps,
and relinquish the assemblies of a people whose religion
was productive of such relentless persecution,
for their absence from which they were fined 10£.
though it was well known they had no estate,
their parents having been reduced to poverty by repeated fines and extravagant distraints;
wherefore to satisfy the fine,
they were ordered to be sold for bond-slaves by the following mandate:

[.embedded-content-document.legal]
--

Whereas Daniel Southick and Provided Southick, son and daughter of Laurence Southick,
absenting themselves from the public ordinances,
having been fined by the courts ordered of Salem and Ipswich,
pretending they have no estates, and resolving not to work: The court,
upon perusal of a law, which was made upon account of debts,
in answer to what should be done for the satisfaction of the fines resolves,
That the treasurers of the several counties,
are and shall be fully empowered to sell the said persons
to any of the English nation at Virginia or Barbados,
to answer the said fines.

--

Pursuant to this order Edward Butter, one of the treasurers,
sought out for a passage for them to Barbados for sale,
but could find none willing to take them thither.^
footnote:[Neale,
in the place of Butler`'s subsequent endeavours to execute the above-cited order,
substitutes the following palliating conjecture:
"`I am apt to think this order was made rather to terrify the Quakers,
than with a design to be put in execution;
for when Southick and his wife had been thoroughly frightened,
they were sent home without further punishment.`"
On what authority he founds this conjecture doth not appear, nor do I see room for it;
we find none of their orders which they could execute within themselves,
which were not executed fully up to, or beyond the letter of the law,
a bitter passionate spirit accompanying all their executions.
And in the present case,
the failure of execution doth not appear to be the result of any tenderness in them,
but of a more humane disposition in others not under their jurisdiction,
whose assistance was wanted, but who would have no concern in the business,
as appearing to them unreasonably cruel and unjust.]
One master of a ship to whom he applied, in order to evade a compliance,
pretended they would spoil the ship`'s company, Butter replied, No,
you need not fear that, for they are poor harmless creatures that will not hurt anybody.
The master rejoined, will you then offer to make slaves of such harmless creatures?
and declined the invidious office of transporting them, as well as the rest.
Disappointed in his designs, and at a loss how to dispose of them,
the winter approaching, he sent them home to shift for themselves,
till he could find a convenient opportunity to send them away.

We are now advanced to the period wherein persecution proceeded to the last extremity,
in prosecuting to death for religion William Robinson, a merchant of London,
Marmaduke Stevenson of Yorkshire, husbandman, and Mary Dyer, a woman fearing the Lord,
of good report, the mother of several children,
and wife of a reputable inhabitant of Rhode Island, with Nicholas Davis,
were by the Court of Assistants at Boston in the beginning of September, 1659,
sentenced to banishment on pain of death.
William Robinson attempting to speak for himself,
was first stopped by an handkerchief thrust into his mouth,
and afterwards severely whipped with twenty stripes with a threefold corded whip,
soon after which they were all released, and banished pursuant to their sentence,
being allowed no more than two days, from the 12th of September,
the day of their release, to the 14th of the same, to depart their jurisdiction,
to answer it at the peril of their lives,
if found within their precincts after the last mentioned day.^
footnote:[We have again an instance of Neale`'s unfair and partial representation of fact:
"`These three coming from Rhode Island in the month of June,
were apprehended and banished on pain of death,
and were allowed till the 4th of September to depart the jurisdiction.
The two men went to Piseataqua government, and the woman to Rhode Island, etc.`"
One would naturally conclude from hence, that they were banished in June,
and allowed till the 4th of September to depart,
and so conceive an idea of the lenity of this government,
to which it hath no better claim in this, than in its preceding transactions,
being marked with the same bitter spirit of unpitying animosity.
From [.book-title]#New England Judged# we learn;
"`That they came from Rhode Island in the then 4th month (June) to Boston,
where they were apprehended and sent to "`prison,
to remain there till the next Court of Assistants,`" which was held as above related:
The order for their release bears date the 12th of September, and concludes thus:
"`They must answer it on their peril,
if they or any of them after the 14th of this present month September,
are found within this jurisdiction.`"
So then they had no more than two days allowed them to escape their determined destruction;
This was certainly a very hard measure,
for no other crime than breathing the air of the country,
and too evident a symptom of implacable malignity,
rising to blood-thirstiness in their persecutors,
hardly reconcileable to Endicot`'s declaration, that he desired not their death.
But Neale in his relation conceals this aggravating circumstance,
which is a very material part of an honest and impartial account,
as it shews these governors in a proper light;
and there appears too much season to conclude it was done
with design to gloss over the cruelty of these proceedings,
by giving them a complection of lenity which they possessed not,
and to the conduct of the innocent sufferers, that of an unreasonable contumacy,
and being guilty of their own blood; of which they were no otherwise guilty,
than by continuing in the discharge of apprehended duty.]

Mary Dyer and Nicholas Davis left that jurisdiction at that time:
William Robinson and Marmaduke Stevenson only went from Boston,
but found themselves not at liberty to depart the jurisdiction,
though staying at the hazard of their lives,
apprehending their ministry there not finished;
so they departed to Salem and the adjacent parts
to visit their friends and confirm them in the faith,
to stand steadfast in these perilous times.
It was not long before they were taken up, imprisoned, and put in chains at Boston.
In the next month Mary Dyer also returned, and M. Dyer was taken into custody;
thus they had in their power three persons,
who by their sanguinary law had forfeited their lives.
On the 20th of October they were brought before the court, where John Endicot presided,
and being set to the bar, Endicot commanded the keeper to pull off their hats,
and without further process, without any other prefatory address,
to point out their errors,
than the following recapitulation of their own severities and crimes,
instead of those of the prisoners, proceeded to pass sentence of death as follows,
"`We have made many laws, and endeavoured by several ways to keep you from us,
and neither whipping nor imprisonment, nor cutting off of ears,
nor banishment on pain of death, will keep you from among us; I desire not your deaths.`"
Then added, "`Give ear and hearken to your sentence of death.`"
William Robinson, previous to passing the sentence, desiring liberty to read a paper,
shewing the reason why he had not departed that jurisdiction, his request was refused,
and the following sentence passed upon him:
"`You shall be had back to the place from whence you came,
and from thence to the place of execution, to be hanged on the gallows till you are dead.
After which Marmaduke Stevenson and Mary Dyer received the like sentence; these two,
observing the treatment of William Robinson, made no defence.
But the former, after the sentence,
was incited to warn the magistrates and others guilty of their death,
That the same day they put the Lord`'s servants to death,
the day of their visitation should pass over their heads, and they be cursed forevermore:
And therefore in love, desired them to take warning before it should be too late,
and thereby remove the fatal consequences of shedding innocent blood.
Mary Dyer, to her sentence, replied, The will of the Lord be done.
Upon which Endicot ordering the marshal to take her away, she rejoined, yea joyfully I go.
Being taken back to prison, she employed a part of the intermediate time in writing,
to the general court in Boston,
a letter of remonstrance against their last sanguinary law,
being a strong dissuasion from putting it in execution.
Of which, as a specimen of equanimity in the most trying circumstances,
and the good sense and christian temper that dictated it,
we lay before the reader the following abstract:

[.embedded-content-document.letter]
--

[.letter-heading]
To the general court at Boston.

Whereas I am charged by many with guiltiness of my own blood:
If you mean in my coming to Boston, I am therein clear, and justified by the Lord,
in whose will I came, who will require my blood of you, be sure,
who have made a law to take away the lives of the innocent servants of God,
if they come among you, who are called by you cursed Quakers; although I say,
and am a living witness for them and the Lord, that he hath blessed them,
and sent them unto you: Therefore be not found fighters against God,
but let my counsel and request be accepted with you, to repeal all such laws,
that the truth and servants of the Lord may have free passage amongst you,
and you be kept from shedding innocent blood,
which I know there are many among you would not do, if they knew it so to be.
I have no self-ends, the Lord knoweth,
for if my life were freely granted you would not avail me,
nor could I expect it of you so long as I daily hear
or see the sufferings of these people,
as I have done these two years, and now it is like to increase even unto death,
for no evil-doing but coming among you.
Were ever the like laws heard of among a people that profess Christ come in the flesh?
And have you no other weapons but such laws to fight with against spiritual wickedness,
as you call it?--Search with the light of Christ in you,
and it will shew you of whom you take counsel, as it has done me and many more,
who have been disobedient and deceived as now you are;
which light as you come into, and obey what is made manifest to you therein,
you will not repent that you were kept from shedding blood, though by a woman.
It is not my own life I seek, (for I choose rather to suffer with the people of God,
than to enjoy the pleasures of Egypt) but the life of the
seed which I know the Lord hath blessed;--And I know this,
that if you confirm your law, though it were to the taking away the life of but one of us,
that the Lord will overthrow both your law and you by his righteous judgments,
and plagues poured justly upon you; who now, whilst you are warned thereof,
and tenderly sought unto, may avoid the one by removing the other.--Oh!
Let none of you put the evil day far from you which verily, in the light of the Lord,
I see approaching even to many in and about Boston,
which is the bitterest and darkest professing place that I have ever heard of;
let the time past, therefore,
suffice for such profession as brings forth such fruits as these laws are.
In love, and in the spirit of meekness, I again beseech you,
for I have no enmity to the persons of any;
but you shall know that God will not be mocked,
but what you sow that shall ye reap from him,
that will render to everyone according to the deeds done in the body,
whether good or evil: Even so be it, saith

[.signed-section-signature]
Mary Dyer

--

The 27th of October, being the day appointed for their execution,
in the afternoon they were led to the gallows by Michaelson the Marshal,
and Captain Oliver, with a band of about two hundred armed men, besides many horsemen,
as if apprehensive some of the people might rescue the prisoners.
In the procession, the drummers were placed to march next before the condemned persons,
and when any of them attempted to speak,
the drums were beaten to prevent them being heard.
An indecency unprecedented amongst civilized nations
in the administration of legal justice,
to the vilest criminals:
This awful scene humanity directs to be attended with becoming solemnity,
and sympathy with the unhappy objects, who are going to lose their lives,
as a sacrifice to public justice;
and every sentiment of common decency revolts against the
idea of disturbing their recollection in their last moments.
But the treatment of these prisoners throughout,
marks the difference between justice reluctantly punishing
dangerous criminals to secure the public safety;
and despotism wantonly exercising unjust power over
innocence for the gratification of private animosity.
But if these prisoners were deprived of the decent solemnity and usual sympathy,
attendant on such occasions, they wanted them not; collected in themselves,
and supported by that which the power and inveteracy
of their persecutors could not reach,
the inward testimony of an approving conscience,
they rose superior to all the indignities, to which they were exposed.
With hands and hearts joined,
as companions in an invincible testimony to the truth they were brought to suffer for,
with countenances undismayed, and brightened with signs of heavenly joy and gladness,
they directed their steps to the place of execution.
Mary being in the middle, the Marshal said to her,
are you not ashamed to walk thus hand in hand between two young men?
She replied, No, this is to me an hour of the greatest joy I ever had in the world.
No ear can hear, no tongue can utter, and no heart can understand,
the sweet incomes and refreshings of the spirit of the Lord, which I now feel.
William Robinson said, This is your hour and the power of darkness,
upon which the drums were immediately beaten.
When they ceased Marmaduke Stevenson said, This is the day of your visitation,
wherein the Lord hath visited you; but although he expressed more,
the noise of the drums prevented his expressions being heard.
They went forward with great cheerfulness, as approaching everlasting felicity,
and rejoicing that the Lord had counted them worthy to suffer death for his name`'s sake.^
footnote:[I believe I should not have noticed Neale`'s cursory relation of these executions,
if he had introduced no reflections on the sufferers;
but although in his preface he asserts that, "`Where facts have been differently related,
or the justice of the government arraigned,
as in the sufferings of the Quakers and Anabaptists, etc.
I have consulted the writers on both sides,
and by comparing them together have set them in the best light I could.`"
Yet in this case his assertion is not true,
for he hath passed over in silence George Bishop`'s account
of the behaviour of these sufferers at their execution,
(from whence our accounts are taken, as from an authentic relation,
written by a contemporary author, and first published in 1661,
while the facts were recent, and all the parties concerned in being,
and not controverted that I know of) and hath adopted that of Cotton Mather,
a New England preacher and apologist, written many years after,
whose reflections on the Quakers have been fully answered by John Whiting,
in a piece entitled _Truth and Innocency Defended Against Falsehood and Envy,_
printed in 1702.
Which answer Neale also cites for his authority, page 325 vol. 1.
and consequently had read it, where he might have seen these aspersions refuted.
Now to suppress the most genuine and best authenticated accounts of their behaviour,
because written by their friends, and introduce the illiberal,
invidious reflections of an adversary, founded on vague and prejudiced report,
is not comparing the writers both sides to set the fads in the best light he could.
And as he hath chosen to revive Mather`'s invidious and refuted insinuations,
it seems proper after his respondent, John Whiting,
to make some animadversions upon them,
to supply Neale`'s failure of his specious profession,
in comparing the writers of both sides,
and leaving the reader to make what reflections he pleases.
Cotton Mather says, "`If any inquire with what spirit these men died,
he must sincerely say, that as far as he can learn,
they shewed little enough of the spirit of martyrdom,
they died not like the true martyrs of Jesus Christ,
with the glorious spirit of God resting upon them; but a fierce, a raging,
a revengeful spirit, and a degree of madness rather inspired them.`"
Rank malice this.
Mere unsupported partial opinion, founded in ill will, which speaks well of none,
to which hear John Whiting`'s reply.
"`I would fain knew wherein +++[+++they shewed little of the spirit of martyrdom+++]+++ and
beseech the reader to peruse, not only their examinations,
and speeches at their deaths;
but also their papers and epistles +++[+++recorded in the Appendix to _New England Judged,_
in Sewel`'s _History,_ page 228, etc.
or Besse`'s _Sufferings, Vol. 2._ page 238.+++]+++ and compare them with
the speeches and letters of the martyrs, in the book of martyrs,
and see whether they do not savour of the spirit of martyrdom,
and holy resignation in the case. -- "`What won`'t envy misrepresent?
They died so like the martyrs of Jesus Christ,
with the glorious spirit of God resting upon them; yea, and supporting them to the last,
as affected the hearts of many at the time,
so that several were convinced of the truth at their deaths--a fierce, a raging,
a revengeful spirit, etc.
I return upon him, as malicious slanders and calumnies,
and dare him to tell wherein they were fierce, raging, or revengeful:
Did they ever go about to revenge themselves, or offer violence to any?
No, they left vengeance to the Lord to whom it belongs, and who will repay it.`"
John Witing`'s Answers to Cotton Mather, page 74, 77, 78.]

Amongst the rest who attended this execution, John Wilson, priest of Boston,
and colleague of John Norton aforesaid, accompanied them,
but from motives very unbecoming of, and disgraceful to the sacerdotal character,
not to sympathize with, convince or console the suffering in their last moments,
but to enjoy the full gratification of his virulent disposition,
and disturb them with impotent insults,
shall such jacks as you come in before authority with their hats on?
was his contemptuous language:
A wonderful reason indeed to take away their lives!
which occasioned William Robinson to remark,
Mind you, mind you, it is for not putting off the hat we are put to death.
William Robinson was executed the first,
who on the ladder addressed the people to the following purport:
We suffer not as evil doers, but as those who have testified and manifested the truth:
This is the day of your visitation,
and therefore I desire you to mind the light of Christ which is in you,
to which I have born testimony, and am now going to seal my testimony with my blood.
Wilson, as divested of all sensation of charity and tenderness,
and unable to restrain the passion which inwardly agitated him,
in beholding the patience and fortitude of the sufferer,
bearing him up over all the terrors of death, vented his indignation,
in the following presumptuous interruption, hold thy tongue, be silent;
thou art going to die with a lie in thy mouth.
William Robinson being now ready to be turned off, his last expressions were,
I suffer for Christ in whom I live, and for whom I die.
After he was turned off, Marmaduke Stevenson ascended the ladder, and said,
Be it known unto you all this day, that we suffer not as evil doers,
but for conscience sake, and when he was about to be turned off, added,
This day shall we be at rest with the Lord.
Mary Dyer was reprieved at the gallows, for that time, at the intercession of her son.

The malice of their persecutors was not satisfied with taking away their lives,
but their inhumanity extended even to their dead bodies,
none holding them when they were cut down, they fell to the ground,
by which William Robinson`'s skull was fractured; then they were stripped,
their shirts were ripped off with a knife,
and their naked bodies rolled into a hole and left there uncovered,
And when some of their friends would have put their bodies in coffins,
they were not suffered to do it.
Neither when they brought pales to enclose the pit, would it be allowed:
So that they were lest exposed to the beasts of prey,
had not the pit been quickly filled with water.
To conclude the infamous scene,
Priest Wilson aforesaid vented the last effort of
his spleen in a song upon the deceased.

But many of the people more generous and humane than their magistrates and teachers,
beheld these executions with silent sorrow, and returned home with heavy hearts,
under disgust and discontent at the persevering cruelty
of their rulers in putting innocent men to death,
which the magistrates perceiving, in order to allay the ferment,
resolved to send Mary Dyer away.
So then caused her to be set on horseback,
and by four horsemen to be conveyed fifteen miles towards Rhode Island,
who left her there with a horse and man, to be conveyed the rest of the way,
which she soon sent back and went to her own home.

The pious speeches, christian demeanour,
constancy and innocence of these two martyrs at their execution, did not only excite,
in the spectators in general, compassion and sorrow,
but in several of them a spirit of inquiry into the causes thereof,
and in consequence an adoption of that religion, which, they saw,
was able to support its professors under so heavy a weight of afflictions.
John Chamberlain, an inhabitant of Boston, in particular, being present, was so affected,
that being convinced of the truth they died for,
he went to visit others of that persuasion then in prison,
which the magistrates resented so far as to imprison him also,
and cause him to be whipped several times most severely.
Edward Wharton, an inhabitant of Salem, having said,
The guilt of Robinson`'s and Stevenson`'s blood was so great, that he could not bear it,
was, for his pretended insolence,
whipped with twenty lashes and fined 20I. And Michael Shaflin, of Salem,
some years after, being interrogated by the court there,
How long he had absented from their worship answered,
Ever since you put the servants of the Lord to death.
But these severities failing of reconciling the people
to their arbitrary and unmerciful proceedings,
and finding them condemned by the generality of sober persons at home and abroad,
they published the following apology, in justification of their conduct.

[.embedded-content-document]
--

Though the justice of our proceedings^
footnote:[It requires more sagacity than I am master of,
to discover any regard to justice in their proceedings against these persons;
and I presume every dispassionate reader will be at a loss to discover it also.]
against William Robinson, Marmaduke Stevenson and Mary Dyer,
supported by the authority of this court, and the laws of this country,
and the laws of God,^
footnote:[By what divine law could they support inhumanity, cruelty and bloodshed?
It appears to me blasphemy to introduce the sacred name into such an apology,
and still more so to place his just laws, as in confederacy with their assumed authority,
and arbitrary and unjust decrees.]
may rather persuade us to expect encouragement and
commendation from all prudent and pious men,
than convince us of any necessity to apologize for the same;
yet for as much as men of weaker parts out of pity
and commiseration (a commendable and christian virtue,
yet easily abused,
and susceptible of sinister and dangerous impressions) for want of a full information,
may be less satisfied, and men of more perverse principles to calumniate us,
and render us as bloody persecutors, to satisfy one, and stop the mouths of the other,
we have thought fit to declare, that about three years since,
divers persons professing themselves Quakers (of whose pernicious
opinions and practices we had received intelligence from good hands,
both from Barbados and England^
footnote:[This is a plain confession,
that their persecuting measures were grounded upon no conviction of matters of fact;
but on bitter prejudice, on no better grounds, than the reports of men,
nighly as much prejudiced against this people as themselves.]
arrived at Boston,
whose persons were only secured to be sent away by
the first opportunity without censure or punishment,^
footnote:[This is not true,
it being manifest even the first that came were both
censured and punished in various ways:
closely imprisoned; their books seized and burnt by the hangman,
deprived of company and food several days;
stripped naked to search for tokens of witchcraft;
and their beds and bibles taken from them for the jailers fees.
If all this usage was not punishment, what was it?]
although their professed principles, turbulent and impetuous behaviour to authority,
would have justified a severer animadversion;
yet the prudence of this court was exercised only in making provision
to secure the peace and order here established against their attempts,
whose design (we were well assured by our experience,
as well as by the example of their predecessors in
Munster) was to undermine and ruin the same;^
footnote:[Equally untrue is it that they were assured, by their own experience,
that the design of these people was to undermine and ruin the peace and order established:
they interfered not with their civil government;
nor have these apologists advanced one matter of fact to
support the allegation--because they could not.
And their taking their estimate of them and their designs from the Anabaptists of Munster,
whom they term their predecessors, is unfair, ill-grounded, and mere venom.
Was there not as great a disparity between the Quakers and these Anabaptists,
as between the independents and them?
and might they not with equal or greater propriety be termed
the predecessors of the independents of New England?
"`By their fruits ye shall know them,`" Was the criterion
pointed out by the author of the christian religion,
to try pretences to religion by, and to discriminate the false prophet from the true.
Wherefore it may be no improper digression to take
a summary review of the conduct of these Anabaptists,
in an abstract from a late author, and inquire wherein the Quakers resembled them.
John Mathias, a baker of Harlem, and John Bocold, a taylor of Leyden,
were at the head of the disorders and delusions of these visionary impostors;
they settled in Munster, a city of Westphalia,
and gained many proselytes to their tenets, the principal of which,
and from which they obtained their name, was this,
that baptism ought to be administered only to adult persons, and should be performed,
not by sprinkling but dipping; condemning the baptizing of infants,
and rebaptizing all whom they admitted into their society.
This being a harmless speculative principle,
and having some appearance of reason and authority
from the practice of the primitive christians,
could expose them to little or no censure, if they had stopped here.
But to these,
they are represented to have added other principles inconsistent with moral rectitude,
and dangerous to the peace and order of society;
they pretended that magistracy was not only unnecessary among christians;
but an unlawful encroachment on their spiritual liberty:
They were for levelling all ranks; making all property common;
and reducing all men to a state of equality:
{footnote-paragraph-split}
But these levelling principles operated with these
men only while they were themselves necessarily among the lower orders of the people:
For their success in making proselytes discovered the unsoundness of their hearts,
and the extravagance of their ambition:
having gained some citizens of eminence to the adoption of their opinions,
they expanded their views,
and made several unsuccessful attempts to get possession of the town,
in order to gain an establishment there for their motley system of confused tenets;
and at last having secretly called in their associates from the neighbouring country,
they suddenly took possession of the arsenal and the senate house in the night time,
and running about the streets with drawn swords and horrible howlings,
cried out alternately, "`Repent and be baptized,`" and "`Depart, ye ungodly.`"
The citizens of all ranks and classes, terrified at their threats and outcries,
fled in confusion, and left the city under the dominion of a frantic multitude.
At first they kept up the form of the ancient constitution;
but all their proceedings were directed by Mathias, who was absolute in command,
whom it was instant death to disobey: Having thus got the city into his possession,
he commenced his plan of reformation by confiscating the estates of those that had fled,
ordering those that remained to bring in their gold, silver and precious effects,
and lay at his feet;
these he deposited in a public treasury and appointed
deacons to dispense them for the common use of all.
At last being besieged in the town by the bishop of Munster,
taking it into his head to finite the host of the enemy with a handful of men,
in imitation of Gideon, he sallied out with a chosen band of thirty men to the slaughter,
for they were all cut off to a man.
He was succeeded in his command by his associate Bocold,
who far out-stripped him in the wildness of his ambition, excess of cruelty,
and gross immorality.
Nothing would satisfy his ambitious soul short of the power and title of king,
which being conferred upon him, he immediately assumed all the state and pomp of royalty.
He indulged his cruelty in almost daily executions,
and his lust by disseminating among his deluded followers
the notion of the lawfulness of polygamy:
By his example as well as doctrine his disciples were led
into excesses of riot in violation of every rule of decency,
and into delusions no less pernicious to religion,
than the peace and security of civil society.
{footnote-paragraph-split}
Now if this description be just,
where lies the parallel between them and the Quakers?
These latter never perverted religion to serve the purposes of self-interest,
ambition or lust:
They constantly maintained that it led to self-denial
and the daily cross to the indulgence of these passions,
and these doctrines were exemplified in the strictness and circumspection of their lives:
They introduced no levelling principles,
they acknowledged magistracy necessary to the order of civil society,
and paid due submission to its authority in civil concerns;
they coveted no man`'s silver or gold or apparel; but wrought,
labouring with their own hands to supply their necessities.
They never made use of their influence over their
adherents to stir up sedition in the state,
or to overturn government, in order to fix themselves therein;
but ever asserted the use of arms to be inconsistent with Christianity,
and that universal peace and charity were the genuine productions of the gospel of Christ.
Wherein then lies the parallel between these Anabaptists and them?
Were I inclined to draw parallels,
I certainly might point out a nearer resemblance between
the proceedings of some other sects of that age,
and these disturbers of the public peace, than those of this harmless body of men.]
and accordingly a law was made and published,
prohibiting all masters of ships to bring any Quakers into this jurisdiction,
and themselves from coming in, on penalty of the house of correction,
until they could be sent away.
Notwithstanding which, by a back door, they found entrance,
and the penalty inflicted on them proving insufficient
to restrain their impudent and insolent obtrusions,
was increased by the loss of the ears of those who offended a second time;
which also being too weak a defence against their impetuous and fanatic fury,
necessitated us to endeavour our security; and upon serious consideration a law was made,
that such persons should be banished on pain of death,
according to the example of England, in their provision against Jesuits,
which sentence being regularly pronounced at the
last court of assistants against these parties,
and they either returning,
or continuing presumptuously in this jurisdiction after the time limited,
were apprehended, and owning themselves to be the persons banished,
were sentenced by the court to death, according to the law aforesaid,
which hath been executed on two of them.
Mary Dyer, upon petition of her son, and the mercy and clemency of this court,
had liberty to depart within two days, which she hath accepted of.
The consideration of our gradual proceedings will
vindicate us from the clamorous accusations of severity;
our own just and necessary defence calling upon us (other means failing) to offer
the point which these persons have violently and willfully rustled upon,
and thereby become Felones de se which, might it have been prevented,
and the sovereign law salus populi been preserved, our former proceedings,
as well as the sparing Mary Dyer, upon an inconsiderable intercession,
will evidently evince, we desire their lives absent, rather than their deaths present.

--

To conclude, this apology throughout proves a bad cause, the reasons advanced,
when stripped of falsehood and exaggeration,
are too futile to be admitted by reasonable and unprejudiced
persons as a plea for moderate punishment,
much less for putting men to death.

Mary Dyer finding herself under a necessity,
laid on her from the requirings of the spirit of the Lord, to go back again to Boston,
returned accordingly thither on the 21st of 3rd month this year;
and on the 31st of the same was sent for by the general court; being come, Endicott,
the governor, said, Are you the same Mary Dyer, that was here before?
And it seems he was preparing an evasion for her, there having been another,
of that name lately come from England.
But she, far from any disguise, undauntedly answered,
I am the same Mary Dyer that was here the last general court.
Then Endicot said, You will own yourself a Quaker, will you not?
To which she answered, I own myself to be reproachfully called so: Endicot said,
The sentence was passed upon her the last general court, and now likewise:

You must return to the prison, and there remain until tomorrow at nine o`'clock;
then from thence you must go to the gallows, and there be hanged until you are dead.
To which she answered, This is no more than what thou saidst before.
Endicot replied; but now it is to be executed,
therefore prepare yourself tomorrow at nine o`'clock.
She then spoke thus: I came in obedience to the will of God, the last general court,
desiring you to repeal your unrighteous laws for banishment on pain of death;
and that same is my work now, and earnest request; although I told you,
that if you refused to repeal them,
the Lord would send others of his servants to witness against them.
Here upon Endicot asked her, Whether she was a prophetess?
She answered, She spoke the words that the Lord spoke to her,
and now the thing was come to pass.
And beginning to speak of her call, Endicot cried, Away with her, away with her.
So she was brought to prison, and kept close till next day.

About the time appointed, the marshal Michaelson came,
and called for her to come hastily, and coming into the room where she was,
she desired him to flay a little, and, speaking mildly, said,
she would be ready presently: But he, being of a rough temper, said,
He could not wait upon her, but she should now wait upon him.
One Margaret Smith, her companion, being grieved to see such hard-heartedness,
spoke something against their unjust laws and proceedings: To which he said,
You shall have your share of the same.
Then Mary Dyer was brought forth, and with a band of soldiers led through the town,
the drums being beaten before and behind her, and so continued,
that none might hear her speaking all the way to the place of execution,
which was about a mile.
Thus guarded, she came to the gallows, and being gone up the ladder, some said to her,
that if she would return she might come down, and save her life.
To which she replied, Nay, I cannot, for in obedience to the will of the Lord I came,
and in his will I abide faithful to death.
Then Captain James Webb said, that she had been there before,
and had the sentence of banishment upon pain of death,
and had broken the law in coming again now; and therefore was guilty of her own blood.
To which she returned, Nay, I came to keep blood-guiltiness from you,
desiring you to repeal the unrighteous and unjust law of banishment upon pain of death,
made against the innocent servants of the Lord,
therefore my blood will be required at your hands who willfully do it;
but for those that do it in the simplicity of their hearts,
I desire the Lord to forgive them, I came to do the will of my Father,
and in obedience to his will, I stand even to death.
Then Priest Wilson said, Mary Dyer, O repent, O repent, and be not so deluded,
and carried away by the deceit of the devil.
To this she answered, Nay, man, I am not now to repent.
And being asked by some, whether she would have the elders pray for her?
She said, I know never an elder here.
Being farther asked, Whether she would have any of the people pray for her?
She said, I desire the prayers of all the people of God.
Thereupon some scoffingly said, It may be she thinks there are none here.
To which she replied, I know but few here.
Then they spoke to her again, that one of the elders might pray for her.
To which she replied, Nay, first a child, then a young man, then a strong man,
before an elder in Christ Jesus.
After this she was charged with something, which was not understood what it was;
but she seemed to hear it; for she said, It is false, it is false,
I never spoke those words.
Then one mentioned that she should have said, she had been in paradise.
To which she answered, Yea, I have been in paradise these several days.
And more she spoke of the eternal happiness, into which she was now to enter.
Thus Mary Dyer departed this life, a constant and faithful martyr to Christ,
having been twice led to death,
which the first time she expected with an entire resignation of mind to the will of God,
and now suffered with christian fortitude, being raised above the fear of death,
through a blessed hope, and glorious assurance of eternal life and immortality.

There were at this time eleven others prisoners in Boston,^
footnote:[Christopher Holder, Daniel Gould, Robert Harper, William King, Margaret Smith,
Mary Trask, Provided Southick, Hannah Phelps, Mary Scott and Hope Clifton.]
of whom Christopher Holder was sentenced to banishment upon pain of death,
six were sentenced to be whipped, and four ordered to depart the colony.

Having now brought up the transactions of the government of Massachusetts Bay,
in relation to the Quakers, to the present period of this history,
it is time to take a view of the proceedings against this people in other colonies.
The colony of New Plymouth copied after that of the Massachusetts,
as appears by a letter of James Cudworth,
who had borne the offices of a magistrate and a captain or commission officer there,
till he resigned the one, and was discharged from the other,
for discovering some humanity to the persecuted Quakers, of which letter to a friend,
in London, as from an impartial hand, I copy an abstract,
as an authentic relation of the measures pursued
by this government in their treatment of this people.

[.embedded-content-document.letter]
--

[.letter-heading]
Abstract of James Cudworth`'s letter.

As for the state and condition of things amongst us it is sad and like so to continue;
the antichristian, persecuting spirit is very active.
He that will not whip, persecute and punish men that differ in matters of religion,
must not sit on the bench, nor sustain any office in the commonwealth.
Last election Mr. Hatherly and myself left off the bench,
and I was discharged of my captainship because I
had entertained some of the Quakers at my house,
that I might be the better acquainted with their principles:
I thought it better to do so, than with the blind world to censure, condemn, rail at,
and revile them, when they neither saw their persons nor knew any of their principles;
but the Quakers and myself cannot close in divers things;
and so I signified to the court I was no Quaker--but withal told them,
that as I was no Quaker, so I would be no persecutor:
This spirit did work the two years that I was in the magistracy,
during which time I was on sundry occasions forced
to declare my dissent in sundry actings of that nature,
which though done with all moderation and due respect,
yet wrought great disaffection and prejudice in them against me,
and produced a petition to the court against me, signed with nineteen hands,
which was followed by another in my favour signed with fifty-four
hands--The court returned in answer to the last petition,
that they acknowledged my parts and gifts, and professed they had nothing against: me,
only in the thing of my giving entertainment to the Quakers,
though I broke no law in so doing, for our law then was, If any entertain a Quaker,
and keep him after be is warned by a magistrate to depart,
he shall pay 20s. a week for entertaining him.
But since that a law hath been made, That if any entertain a Quaker,
though but a quarter of an hour, he shall forfeit 5£. Another, That if any see a Quaker,
he is bound, though he live six miles or more from a constable,
to give immediate notice to him, or else be subject to the censure of the court.
Another--That if the constable know or hear of any Quaker in his precincts,
he is presently to apprehend him, and if he will not presently depart the town,
to whip and send him away.
Divers have been whipped within our patent; and truly to tell you plainly,
the whipping of them with that cruelty, as some of them have been whipped,
and their patience under it,
hath sometimes been the occasion of gaining more adherents to them,
than if they had suffered them openly to have preached a sermon.

Another law made against: the Quakers is,
That if there be a Quakers-meeting anywhere in this colony,
the party in whose house or on whose ground it is,
shall pay 40s. the preacher 40s. and every hearer 40s. Our
last law is--That the Quakers are to be apprehended,
and carried before a magistrate,
and by him committed to close prison till they will promise to depart,
and never come again,
and will also pay their fees (neither of which they will ever do)
and they must be kept only with the country allowance (which is
coarse bread and water.) No friend may bring them anything,
nor be permitted to speak to them; nay, if they have money of their own,
they may not make use of it to relieve themselves.

All these carnal and antichristian ways being not of God`'s appointment,
effect nothing as to the obstructing or hindering them in their way or course.
It is only the word and spirit of the Lord that is able to convince gainsayers;
these are the mighty weapons of a christian`'s warfare,
by which mighty things are done and accomplished.

The Quakers have many meetings and many adherents,
almost the whole town of Sandwich is adhering to them, Their sufferings are grievous to,
and sadden the hearts of most of the pious and virtuous part of this commonwealth,
it lies down and rises up with them,
and they cannot put it out of their minds -- The
Massachusets have banished six on pain of death,
and I wish that blood may not be shed:
Our poor people are pillaged and plundered of their goods,
and haply when they have no more to satisfy the insatiable, desire of their persecutors,
may be forced to fly, and glad to have their lives for a prey.

The means whereby they are impoverished, are their scrupling an oath,
and for their meetings:
It being found that they had a conscientious scruple against swearing,
all were called upon to take the oath of fidelity, which they refusing,
a clause was added, That if any man refused or neglected to take it by such a time,
he should pay 5£. or depart the colony:
They are required to take the oath again at every successive court, and as they cannot,
they are distrained over and over again.
On this account thirty-five head of cattle, as I have been credibly informed,
have been by the authority of our court taken from them the latter part of this summer.

The last court of assistants--the court was pleased to determine fines on Sandwich
men for meetings 150£. whereof William Newland is charged 24£. for himself and wife;
William Allen 46£. and a poor weaver 20£. Brother Cook told me,
one of the brethren was in the house, when the marshal came to demand the money,
when all that he was worth did not amount to 10£. What will be
the end of such courses or practices the Lord only knows!

Our civil powers are so exercised in matters of religion and conscience,
that we have no time to do anything that tends to
promote the civil prosperity of the place,
we must now have a state religion, such as the powers of this world will allow,
and no other; a state ministry and a state way of maintenance,
and we must worship and serve the Lord Jesus as the world shall appoint us;
we must all go to the public place of meeting in the parish where we dwell,
or be presented.
I am informed of three or fourscore last court presented for not coming to public meetings,
at ten shillings a time.

We are wrapped up in a labyrinth of confused laws,
that the freemen`'s power is quite gone, Sandwich men may not go to the bay,
lest they be taken up for Quakers.
William Newland was there about his occasions ten days ago,
and they put him in prison twenty-four hours, and sent for divers to witness against him,
but had not proof enough to make him a Quaker, which if they had,
he should have been whipped; nay,
they may not go about their occasions in other towns in our colony;
but warrants lie in ambush to apprehend and bring them before a magistrate,
to give an account of their business.

[.signed-section-signature]
James Cudworth

--

I do not find that during this period,
any of those called Quakers had as yet visited any
other of the American settlements on the continent,
except the Dutch colony of New Amsterdam, (now New York) where some of them,
particularly Robert Hodgson, underwent grievous sufferings from the Dutch governor,
by the instigation and example of the New England persecutors.
But the Dutch governor after some time relented, excused their imprisoning and banishing,
as being short of the cruelty of the Quakers own countrymen in New England:
And John Bound having been treated very hardly by him, imprisoned in a cold dungeon,
almost famished there, and banished to Holland,
where the states giving him his liberty he returned home again;
and some time after the governor meeting him in the street,
seemed ashamed of what he had done, and told him He was glad to see him safe home again;
adding, he hoped he should never do so any more to any of his friends:
A token of repentance, and of an ingenuous disposition, such as few, if any,
of the New England persecutors ever discovered.

Except also the province of Maryland,
where in or about the year 1658 several of the inhabitants,
being convinced of the principles of the people called Quakers,
were brought under suffering,
but in little degree of comparison with the sufferings in New England,
being mostly in fines for non-compliance with the military laws,
and their conscientious refusal to take an oath.
