== Chapter XVII. Europe and Asia.

[.chapter-synopsis]
* William Caton goes to Calais
* Afterwards to Holland with John Stubbs
* To Holland a second Time
* William Caton at Rotterdam and Amsterdam meets with little satisfaction
* Is imprisoned at Middleburgh, and sent back to England
* Christopher Birkhead goes to France
* Thence to Middleburgh in Zealand
* Accusation against him
* His Defence
* He is condemned to the Rasphouse for two Years
* George Bailey dies in Prison in France
* George Robinson, in a Journey to Jerusalem, meets with a Variety of Dangers
* Through which he was preserved to return home in safety
* Mary Fisher travels to Adrianople to visit Sultan Mahomet 4th
* By whom her Visit is favourably received

The divine light which the people called Quakers believed in and testified of,
they believed to be universal.
"`That true light, which lighteth every man that cometh into the world.`"
So was their good-will to mankind,
and desire to bring them to the acknowledgment of the truth,
and to turn the attention of their minds to this light, also universal.
They did not confine their labours and travels,
in this early day to the British dominions solely;
but from a convincing evidence of a divine impulse upon their spirits,
and a necessity of obedience thereunto, they were animated to travel,
even as with their lives in their hands,
into different states of the continent of Europe, and even into Asia,
to bear testimony to the truth, in the face of its greatest opposers;
for being supported by the inward consciousness of being engaged in a good cause,
they were borne up above the fear of man;
and feeling the divine presence accompanying them through the greatest difficulties,
some of them were enabled cheerfully to lay down their lives in his service, who,
they believed, had called them thereto;
and others were preserved by signal deliverances from imminent dangers,
to which they were exposed.

William Caton being at Dover, as before related, went over to Calais,
where his spirit was burdened in beholding the idolatry of their worship,
but he could not ease his spirit by pointing out to them a better way,
as he was not master of the French language;
and therefore was on the point of returning home
without finding any opportunity of service there;
yet afterwards it was ordered, that several of the principal inhabitants sought him out,
and gave him a favourable hearing at a large house in the town,
where a Scotch Lord interpreting for him,
he cleared his conscience in declaring the doctrines of truth,
and then departed without molestation.

Upon his return to Dover he found his companion Jonn Stubbs there,
with whom he passed over to Holland,
but they found little favourable reception for their ministry there at that time.

In the next year, 1656, William Ames,
John Stubbs and William Caton went over to Holland again.
At Amsterdam they met with some English people, who received the doctrine they preached,
but the impression it made upon them was not lasting.
William Caton travelled to Rotterdam,
where for want of an interpreter that understood English,
he was obliged to deliver himself in Latin.
Here he was much troubled in meeting with some wild and unruly persons,
who having been partly convinced by William Ames, went under the denomination of Quakers,
but ran out in such whimsical imaginations and unmeaning extravagancies in their expressions,
writings and conduct,
that the magistrates thought them not unfit objects for imprisonment in Bedlam.
The ringleader of these people was one Isaac Furnier, a passionate, capricious man,
placing holiness in absurd conduct, and incedent incivility of language,
with whom the genuine Quakers could have no unity,
although he had translated several of their writings into the Dutch language,
and thereby might seem to lay claim to the name.
At last he turned Papist, and fell into a dissolute, debauched life.

From Rotterdam William Caton returned to Amsterdam,
but met with little more satisfaction there.
For there were several professors, who were ready to approve the doctrine of the Quakers,
but being airy notionists, were more intent in comprehending it in theory,
than reducing it to practice, too wise for instruction,
and too full of their own wisdom and speculations to receive the truth in the love of it.
Amongst such opinionated professors seeing little probability of much service,
he left them, and returned by Rotterdam to Zealand;
arriving at Middleburgh in company with a young man,
who went to some of their meeting places in that city, he was apprehended.
William Caton hearing of his imprisonment, and going to visit him in prison,
was himself detained there some days; but being at that time indisposed,
the magistrates ordered them both to be sent to England.
In consequence whereof they were conducted by a guard of soldiers on board a ship of war,
where William Caton in his infirm state suffered great hardship,
the seamen being so ill-natured,
that they would not allow him so much as a piece of sail cloth,
but he was obliged to lie upon the bare boards in very cold and stormy weather;
yet through the merciful support of divine providence under this hard usage,
he recovered strength till he arrived in London,
where he was received with much cordiality by his friends.

Christopher Birkhead went over to France,
and was imprisoned at Rochelle for advancing some objections against the Romish religion,
where he was first examined by the bishop;
and some bigotted zealots wanted to have him condemned to the flames,
but the criminal judge absolved him.
After which in the beginning of thence to this year he travelled into Holland,
and arriving at Middleburgh, he went to the English congregation there,
and after their preacher William Spank had preached about three quarters of an hour,
he thus spake, "`Friends, the Apostles saith, That we may prophesy one by one,
that two or three prophets may speak, and the others judge,
and if any thing be revealed to him that sits by, let the first hold his peace.`"
This caused a great stir in the congregation, whereupon Birkhead,
instead of being further heard, was apprehended and detained in custody.
On the 19th 1 mo.
1657, the following charge was exhibited against him.

[.embedded-content-document.legal]
--

The bailiff of the city of Middleburgh demandeth, according to his office,
against Christopher Birkhead.

Whereas the said Christopher Birkhead is a maker of uproars, seditions,
and a blasphemer against the servants, ministers or preachers of the reformed churches,
Therefore it is demanded, that the ensuing punishments be inflicted on him; first,
that he be brought before the Stadthouse,
and there be put upon a scaffold and whipped with rods,
and burned with the mark of this city of Middleburgh,
and for some years to be put in the Rasp-house, and there to rasp and work,
the time left to the discretion of the Lords,
and afterwards to be banished out of the jurisdiction of these lands.

--

I regret that occasions occur so frequently in the progress of this work,
to remark the unchristian temper and vindictive spirit
which actuated those high professors of religion,
who assumed to themselves the title of reformed churches,
in different quarters of the world;
as the repetition of reflections naturally arising from my subject,
may be misconstrued to arise from a personal dislike to this body of men:
But as I trust I am disposed and desirous to pay
a proper regard to the reformed religion in its purity,
viz. sincerity of heart toward God, in my own conduct, so I highly respect it in all men,
and every society of men under whatever denomination they may be distinguished.
My reflections are not pointed so much at any body of men,
as at things disgraceful to every body of men.
Not at any profession of religion, but at things inconsistent with religion and morality;
cruelty, malice, injustice and revenge, being properties as opposite to Christianity,
as darkness to light.

It is evident that the punishments demanded against this man are
quite disproportionate to any just offence he had given,
by simply reminding an auditory of the apostolical order
established in the worship of the primitive church,
as an introduction to what he thought it his duty to declare unto them.
The charge and the requisition of punishment bear the plain marks of passion,
injustice and virulence, putting an offender, in so small an instance,
on a level with the basest criminals,
and incensing the magistrates to inflict on an honest man,
for an action simply religious,
the severest and most disgraceful punishments the
malice of his persecutors could contrive.

The prisoner put in his defence, in reply to the charges exhibited against him;
wherein he denies and confuses them all: that he made no uproar or sedition,
such a thing being the farthest from his disposition, thoughts or intention.
That he was no more a maker of uproars than Paul and Silas
at Thyatira (Acts 16:19) Or than Paul was at Ephesus,
when no small stir arose about that way (Acts 9:23, etc.) That if any uproar was made,
justice pointed out for punishment those who made it, who were the rude multitude,
that gave him much personal abuse, and cast him into prison,
when he neither did or thought evil against them.
As to the charge of his being a blasphemer^
footnote:[This word is used here in a very uncommon and unscriptural sense.]
against the servants, ministers or preachers of the reformed churches, he answered,
"`The servants of the church reformed by Christ are my brethren,
and the ministers and preachers thereof I honour in the Lord,
but if any profess to be reformed and live in iniquity, such I disown.`"

Next, in regard to the required punishments of whipping and branding,
he asserted himself no beggar nor infamous person,
having asked for nothing but what he paid for;
and had brought a sufficiency from home to bear his charges thither again,
if not restrained by them too long in a foreign land.

And as to the third punishment, of being committed to the Rasp-house, he signified,
he was not an idle person who had need to be forced to work,
but was a man diligent in his outward employments to maintain his family,
of which he could produce many witnesses, if he might have permission to write home:
and in this punishment that his suffering would not be single,
but that of his wife and children would be involved in it.

His defence prevented the inflicting of the more ignominious parts of the demanded punishments;
but the magistrates gratified his adversaries so far as
to sentence him to be put in tin Rasp-house for two years,
and then be banished, and pay all the charge.
Accordingly he was put into the Rasp-house, and continued there two years,
suffering much hardship.
And after the expiration of the time,
he was still detained under pretence of fees and other claims made by the keeper,
till at length he was set at liberty by the interposition of Heer Newport,
ambassador of the States General in England.
A very severe punishment for uttering a portion of scripture.

About the same time George Bailey coming into France and
zealoulsy testifying against popery and worshipping of images,
was apprehended and cast into prison, and there ended his days.

In this year also George Robinson, a young man of London, found himself constrained,
from an internal conviction of duty, to travel to Jerusalem,
to bear testimony against the idolatry of pilgrimages.
Accordingly he embarked for Leghorn, and from thence took shipping for St. John D`'acra,
so called, formerly Ptolemais in Asia, and from thence continued his course to Joppa,
and thence to Ramoth;
but the friars at Jerusalem having received intelligence of his approach,
and that his testimony struck at the superstition, whereby they were supported,
procured him here to be intercepted and confined.
After about twenty-four hours imprisonment,
an ancient Turk of reputation took him to his house,
and entertained him with much civility several days;
at length an Irish friar came from Jerusalem,
and informed him that he was sent by his fraternity there to propose to him three questions,
viz.

[.numbered-group]
====

[.numbered]
1+++.+++ Whether he would promise, when he came to Jerusalem, to visit the holy places,
as other pilgrims did?

[.numbered]
2+++.+++ Whether he would pay such sums of money as it was customary with pilgrims to pay?

[.numbered]
3+++.+++ Whether he would wear such a habit as pilgrims usually wear?

====

[.offset]
To which questions the following injunctions were added:

[.numbered-group]
====

[.numbered]
1+++.+++ Not to speak any thing against the Turkish laws.

[.numbered]
2+++.+++ When he should come to Jerusalem not to speak any thing about religion.

====

But steadfastly refusing to answer their questions, or to submit to their injunctions,
he was, by the said friar,
who had brought with him a guard of horse and foot for that purpose, taken forcibly away,
carried back to Joppa, and there embarked in a vessel,
which landed him again at St. John D`'acra;
here he was hospitably entertained by a French merchant, and by his assistance,
being still under an apprehension of duty to prosecute his journey,
he got an opportunity to return to Joppa, and from thence travelled on foot to Ramoth.
On the road he fell into the hands of three robbers, who plundered him,
but either by reason of his innocent behaviour moving them to compassion,
or the ordering of Divine Providence, they returned him what they had taken from him,
and conducted him a little on his way in a friendly manner.
Upon his arrival at Ramoth he was seized by the contrivance of the friars,
and forcibly carried into one of the Turkish mosques,
it being said to be a custom amongst the Turks,
that whosoever enters one of their mosques must either turn Mahometan or suffer death.
He was accordingly interrogated, Whether he would turn to the Mahometan religion?
And upon his refusing, they pressed him with much solicitation;
but he persisting in his refusal,
and letting them know he could not turn to their religion for all the world,
some of them at length grew angry,
and declared if he did not turn to their religion he should die; to which, replying,
"`He would rather choose the hard alternative of suffering death than violate
his conscience by turning to them,`" he was delivered to the executioner,
who dragged him away to the place, where it was expected, he should be burned to death.
Here they caused him to sit down on the ground, as a sheep amongst wolves.
As he sat, resigned in his mind, with inward supplication,
and trust in divine protection, the divine Providence interposed for his deliverance,
for some of the Turks having observed that his entrance into the mosque was not voluntary,
but by a crafty contrivance of the friars to ensnare him,
they began to differ in their opinions about him, when a grave ancient Turk came to him,
and told him, Whether he would turn to their religion or not, he should not die.
Then being brought before the priests again, and the query put to him, Will you turn?
and he answering, No, they recorded in a book, that he was no Roman Catholic,
but of another religion; for though he owned himself a Christian,
yet his declarations against their superstitions,
and the enmity of the friars against him,
plainly discovered he was not of their communion.
Next, the friars having exerted themselves to incense the Basha of Gaza against him,
and hoping that by their insinuations they had made him Robinson`'s enemy,
they hired a guard of horse men to conduct him to Gaza, where being arrived,
he found things had taken an unexpected turn in his favour;
for some of the Turks having informed the Basha of
the malice of the friars against the man,
he made them pay a considerable fine, and obliged them to convey him safely to Jerusalem.
Being come thither, he was, by the appointment of the friars, brought into their convent.

Here the friars used every artifice to prevail with him to conform
to the superstitious customs of the pilgrims of their communion,
in visiting the holy places, (as they termed them) offering, in that case,
to relinquish their usual demands,
and that whereas others paid great sums of money to see them,
he should see them for nothing; but believing his,
mission as to them was to bear testimony against
the superstitious veneration for those places,
propagated and up held by them for filthy lucre, he steadfastly resisted all their,
solicitations and flattering persuasions, alleged,
that in visiting those places in their manner he should sin against God;
That they under a pretence of doing service to God,
in visiting those places where the holy men of God dwelt, did oppose that way,
and resist that life, which the holy men of God walked and lived in;
upon which one of the friars said, "`What do you preach to us for?
To which he answered, That he would have them turn from those evil practices,
else the wrath of the Almighty would be kindled against them.
This doctrine being highly ungrateful they insisted
upon his paying five and twenty dollars,
under pretence that the Turks must be paid,
whether he would visit the usual places or not,
but if he would visit them they would pay for him; but he signified,
He could not comply with any such unreasonable demands.

Then they brought him before a Turk in authority in that place,
who asked him divers questions, to which he returned solid answers.
And entering into conversation about the worship of Christians, the Turk asked Robinson,
What was the cause of his coming to Jerusalem?
To which he answered,
It was by the command of the Lord God of heaven and earth he came thither;
and that the great and tender love of God was manifest in visiting them,
his compassionate mercies being such as that he would
gather them in this the day of his gathering.

Having borne his testimony against the superstition of the friars,
and discharged himself of the message he believed himself sent to deliver, he found,
as he declared, great peace with the Lord, magnifying his glorious name,
who had favoured him with his supporting power,
and signally preserved him through many trials and dangers; for the friars,
who had intended him a mischief, and meditated his destruction,
were restrained by the authority of the Turks,
and by them obliged to conduct him back again to Ramoth.
Thus delivered from the hands of his enemies he returned to his native country.

But the concern of Mary Fisher, a religious maiden,
whose sufferings in New England have been already related, is still more remarkable,
both for the extraordinary nature thereof, and the reception she met with.
Being returned to London, she felt a religious concern upon her mind,
to pay a visit to Sultan Mahomet IV. then encamped with his army near Adrianople.
Accordingly she proceeded on her way as far as Smyrna,
where she was stopped by the English consul and sent back to Venice,
from whence she made her way by land to Adrianople,
being preserved from any manner of abuse through
a long journey of five or six hundred miles.
Being come thither, she communicated her business to some of the citizens,
and requested them to accompany her to the camp,
but fearing the Sultan`'s displeasure they declined compliance,
wherefore she went to the camp alone,
and procured intelligence to be given to the Grand Vizier,
that there was an English woman who had something
to declare from the great God to the Sultan,
who sent her word that she should speak to him the next morning.
She returned to the city that night, and back to the camp at the time appointed,
when the Sultan, attended by his great officers of state, sent for her in, and asked her,
Whether what had been reported to him was fact, that she had a message from the Lord?
She answered in the affirmative; upon which he bid her speak on;
and as she stood silent a little, with her mind retired in inward supplication,
and waiting for the proper motion and power to give
weight and energy to what she had to deliver,
tile Sultan supposing she might be oppressed with awe, to utter herself before them all,
asked her whether she desired that any of the company might retire?
she answered, Nay; then he desired her to speak the word of the Lord to them,
and not to fear, for they had good hearts, and could hear it;
strictly charging her to speak the word she had to say from the Lord,
neither more nor less, for they were willing to hear it, be it what it would.
Upon her speaking they all gave attention with much
seriousness and gravity '`till she had concluded,
and then the Sultan inquired if she had any more to say.
She asked, if he understood what she had said?
He replied, Yea, every word, adding that it was truth,
and desired her to stay in the country,
for they could not but respect one who had taken
so much pains as to come so far with such a message,
and offered her a guard to escort her to Constantinople, whither she intended to go;
which kind offer she modestly declined,
confiding in that divine arm which had brought her
thither for her safe conduct home again.
He reminded her it was dangerous travelling alone, especially for such a one as her,
and seemed to admire she had passed safe so far, adding,
it was out of respectful concern for her safety he offered her a guard,
as he would not for any consideration she should suffer the least injury in his dominions.
Then they asked, What she thought of their prophet Mahomet?
She made a cautious reply, that she knew him not; but she knew Christ, the true prophet,
the son of God; who was the light of the world,
and enlighteneth every man that cometh into the world, adding,
If the word that the prophet speaketh cometh to pass,
then shall ye know that the Lord hath sent that prophet; but if it come not to pass,
then shall ye know the Lord never sent him; to which they assented,
and acknowledged it to be truth; and so she departed to Constantinople without a guard,
and arrived there in safety without the least injury or insult,
and afterwards in England.
When we contrast this candid reception which she met with from those we account infidels,
with that which she found amongst the self-opinionated
professors of christianity in New England,
we cannot but regret, that the best religion the world was ever blessed with,
and in its own purity so far surpassing in excellence, should,
on the comparison with human infidelity, be so tarnished,
through the degeneracy of its professors, who under the name of Christian, in morality,
generosity and humanity, fall short of those who name not the name of Christ.
Is not her remarkable preservation in this long and
tedious journey an argument of the truth of her mission,
and of divine Providence protecting her in the performance of her duty,
and in yielding obedience to divine requirings.
