== Chapter I.

[.chapter-synopsis]
* The Members of the Presbyterian Party restored to their Seats in Parliament
* A new Parliament elected
* The King restored
* Seven Hundred of the People called Quakers released from Prison
* The Mayor of Lancaster imprisons George Fox
* Margaret Fell`'s Narrative of his Apprehension
* She lays his Case before the King
* Habeas Corpus obtained to remove him to the King`'s Bench
* Referred to the King and Council
* He is set at liberty
* Richard Hubberthorn hath a Conference with the King

The convulsed state of the nation at this period inciting most men of moderation
and consequence to an earnest wish for some settled stable form of government,
paved the way for the exiled prince`'s restoration to the throne of his ancestors.
The members of the Presbyterian party, who were secluded in 1648,
being by Monk restored to their seats in parliament, upon their entrance,
the independent members finding themselves the minority, withdrew,
and left the management of affairs to their antagonists,
who soon after dissolved their assembly,
and issued writs for the election of a free parliament,
which meeting on the 25th of the month called April,
the house of lords received a letter from the king from Breda, expressing his hopes,
that as they were now restored to their privileges,
they would use their endeavours to appease the troubles of the kingdom,
reestablish himself in possession of his just prerogatives,
the parliament in that of their privileges, and the people of their liberties.
At the same time his declaration was delivered, wherein,
amongst other benefits to the subject,
he promised to indulge tender and scrupulous consciences in matters of religion.^
footnote:["`Because the passion and uncharitableness of
the times have produced several opinions in religion,
by which men are engaged in parties and animosities against each other,
which when they shall hereafter unite in a freedom of conversation,
will be composed or better understood, We do declare a liberty to tender consciences;
and that no man shall be disquieted or called in question
for differences of opinion in matters of religion,
which do not disturb the peace of the kingdom,
and that we shall be ready to consent to such an act of parliament,
as upon mature deliberation shall be offered to us for the full granting that indulgence.`"
King Charles`'s declaration from Breda.]
And a like letter and declaration being also delivered to the commons,
King Charles the second was in consequence restored to the sovereignty of these
kingdoms by the united consent of the other two estates of the nation,
and after an exile of twelve years,
in which he had suffered many slights and distresses;
after sundry ineffectual efforts of his partisans to restore him by the sword,
through the ordering hand of Divine Providence,
he was at last peaceably restored without bloodshed.

The society of those called Quakers, at least, (as appears by their writings) in general,
looked upon the restoration of the king as a signal instance of the interposition
of Divine Providence in restoring peace and order to the distracted nation,
of which they were not wanting repeatedly to remind both the king and people:
And if these had looked upon it in the same light with becoming gratitude and thankfulness,
they might have been preserved in a greater propriety of conduct;
but this revolution in the government was productive of
a scandalous alteration in the manners of the age.
This king, and many of his courtiers, having in their exile,
through a season of successive indolence,
and from their aversion to the precise formality of the authors of their humiliation,
contracted habits of voluptuousness, sensuality and libertinism in sentiment and morals;
by their example, and the propensity of human nature,
more sagacious to descry error than to investigate truth,
to transgress the limits of rectitude and to run from one extreme to another; the nation,
in too general a way,
became very corrupt and licentious in their way of thinking and conduct.
Because the late rulers appeared to have disguised
pernicious designs under a mask of religion,
it became fashionable to ridicule every appearance
of religion and of sobriety as mere hypocrisy;
and in this aversion to the appearance, the reality was lost.
The temper of the age was truly irreligious, and debauchery, riot and intemperance,
to a great degree,
took place of the apparent decorum and regard to
sobriety in the manners of the preceding age.^
footnote:[Neale gives the following description of the temper
of the people under this and the preceding governments:
"`The dress and conversation of the people was sober and virtuous,
and their manner of living remarkably frugal:
There was hardly a single bankruptcy to be heard of in a year,
and in such a case the bankrupt had a mark of infamy upon him,
that he could never wipe off.
Drunkenness, fornication, profane swearing,
and every kind of debauchery were justly deemed infamous,
and universally discountenanced.
The clergy were laborious to excess in preaching and praying, in catechising youth,
and visiting their parishes.
The magistrates did their duty in suppressing all kinds of games,
stage plays and abuses in public houses.
There was not a play acted on any theatre in England for almost twenty years.
But when the legal constitution was restored,
there returned with it a torrent of debauchery and wickedness.
The times which followed the restoration were the reverse of those that preceded it;
for the laws which had been enacted against vice
for the last twenty years being declared null,
and the magistrates changed, men set no bounds to their licentiousness.
There were two play-houses erected in the neighbourhood of the court.
Women actresses were introduced into the theatres,
which had not been known till that time;
the most lewd and obscene plays were brought on the stage,
and the more obscene the better was the king pleased,
who graced every new play with his royal presence.
Nothing was to be seen at court but feasting, hard drinking,
revelling and amorous intrigues, which engendered the most enormous vices.
From court the contagion spread like wildfire among the people,
insomuch that men threw off the very profession of virtue and piety.`"
Neale`'s [.book-title]#History of the Puritans, Vol. 2.# p. 564-565.]

In this interval of general joy and festivity the Quakers (so called)
enjoyed a good degree of quiet and respite from the grievous sufferings
to which they had been for many years exposed under the preceding governments;
their meetings in London and most other parts were large,
and held without molestation during the first six months after the King`'s restoration.
Cruelty was not reckoned amongst the vices to which this monarch was addicted,
the easiness of his temper inclining to lenity,
he appeared at this time well disposed to act up
to his professions in his declaration from Breda.
At the intercession of Margaret Fell and others he
released about seven hundred of this people,
Friends who had been imprisoned under the government of Oliver and Richard Cromwell,
and an order was drawn up for permitting them the free exercise of their worship;
but by some in authority, of less placable dispositions,
who disapproved of any toleration,
as being retentive of the injuries they conceived themselves
to have suffered from the dissenters during their rule,
and desirous of an opportunity to retaliate:
the ratification and issuing of this order was obstructed,
till the insurrection of the fifth monarchy-men furnished
them the opportunity they wanted,
and gave them a pretext to commence the oppressive
measures which they had in contemplation.

Yet in some parts they were greatly molested and abused
in their religious meetings during this interval.
Some of the inferior magistrates of the former class, who still retained their places,
and their inimical dispositions toward this body of people, continued to be vexatious to them;
in particular, Henry Porter, mayor of Lancaster, a weak temporizing man,
who had been a zealous partisan of the republicans,
and very active against the King`'s interest, in order, it is like,
to make an atonement for his past misdemeanours,
and to ingratiate himself commits with the present powers,
from a pretended zeal for the King, committed George Fox to prison,
very unjustly and illegally.
In the course of his travels he came to Skipton to a general meeting,
which had been several years established there,
(before the general establishment of meetings of discipline) for the charitable
purpose of assisting and making provision for the poor amongst them;
for many, as we have seen, were reduced to poverty by exorbitant fines,
severe distresses and imprisonments,
so that numbers were spoiled of the whole of their
property through the malice of unreasonable men.
It had frequently happened that justices and military
officers coming to break up this meeting,
when they saw their books, and accounts of their collections and disbursements,
and the care that was taken that one county should help another,
as circumstances might require, instead of executing their purpose,
have been obliged to commend their care,
and leave them undisturbed in the exercise of the laudable object of their meeting.
The poor of other societies frequently gathering in crowds
upon these occasions partook of their liberality,
it being their custom, after the meeting was over, to send to the bakers for bread,
and distribute a loaf to each, how many soever they were;
yet these are the men on whom the contemptuous epithet of fanatic was so freely bestowed,
by those who had no right to apply the appellation,
for their religion instructed them to do good to all,
but especially to the household of faith; and never to introduce disorder in the state,
or do injury to any man.

From this meeting he went over by Lancaster to Swarthmore to the house of Margaret Fell,
who was now a widow, her husband having been deceased about two years before:
This was about the time of the King`'s restoration, being in the month called June,
when four constables came to the said house with a warrant from the aforesaid Porter,
apprehended him, and took him that night to Ulverston,
where they kept him under a guard of fifteen or sixteen men,
some of whom kept centry at the chimney, for fear he should escape by that passage,
so darkened were they by superstitious imaginations.
Next morning they escorted him to Lancaster,
exposing him to much abusive and contumelious treatment;
causing him to ride on an horse behind the saddle,
and otherwise manifesting their malicious temper in their ill usage of him;
and brought him before the said Porter, to whom he complained of the unworthy treatment,
he had received from the constables after he was their prisoner, but without redress.
George then inquired by what authority he had issued out his warrant to take him?
To which Porter would give no further satisfaction, than that he had an order,
but would not let him see it, for he would not reveal the King`'s secrets, adding,
a prisoner was not to see for what he was committed;
a palpable instance of his want of qualification for his office:
George Fox signified that was not reasonable, for how should he make his defence then?
After some more discourse his mittimus was made out, the jailer sent for,
and commanded to put him in the dark house;
and though bail was offered for his appearance, it was refused,
and he committed close prisoner to Lancaster castle,
where he was treated with great incivility and rudeness,
being often debarred of provisions, but as he could get them under the door.
He then desired two of his friends to apply to the jailer for a copy of the mittimus,
who told them,
He could not give a copy of it for another had been fined for a similar offence;
but he gave them liberty to read it over,
and according to the best of their recollection, the charges advanced against him were,
that he was a person generally suspected to be a
common disturber of the peace of the nation,
an enemy to the King, and a chief upholder of the Quakers sect: That he,
together with others of his fanatic opinion,
have of late endeavoured to raise insurrections in these parts of the country,
and to embroil the whole kingdom in blood.
Wherefore the jailer was commanded to keep him in safe custody
till he should be released by order of the king and parliament.

Having thus got the substance of the charges contained in his mittimus,
he thought himself called upon, in vindication of his innocency,
to publish an immediate reply to every particular charge,
clearly proving them to be downright falsehoods.
That he was not generally suspected to be a common disturber of the nation`'s peace,
having given no cause for such suspicion,
his conduct having always been inoffensive and remote from disorder.
That he was not an enemy to the king, but loved him and all men,
neither had he any reason to be his enemy who had
treated him with no rigour or offered him no injury,
whereas he had been imprisoned and persecuted for eleven or twelve years by those men,
who were in open hostility both against the king and his father,
for whom Porter carried arms, and by whom he was advanced to the rank of a major,
but had suffered no injurious treatment from the king`'s friends.
And in reply to the charge, that he, together with "`others of his fanatic opinion,
have of late endeavoured to raise insurrections,
and to embroil the whole kingdom in blood,`' he says, this is altogether false, he being,
as to these things, as innocent as a child, and clear of any concern therein.
As for the term fanatic, Porter was not the man to apply it to him and his friends,
but might have considered himself and learned humility at this season,
in applying nearer home the fanatic opinions,
which raise insurrections and embroil the whole kingdom in blood.

Margaret Fell also, considering the forcible entry and searching of her house,
and arresting her guest there, as a violation or the liberty of the subject,
and an injury offered to her,
published the following brief narrative of his apprehension:

[.embedded-content-document.letter]
--

[.letter-heading]
To all Magistrates,
concerning the wrong taking up and imprisoning of George Fox at Lancaster.

I do inform the governors of this nation, that Henry Porter, mayor of Lancaster,
sent a warrant with four constables to my house, for which he had no authority nor order.
They searched my house, and apprehended George Fox in it,
who was not guilty of the breach of any law, or of any offence against any in the nation.
After they had taken him, and brought him before the said Henry Porter,
there was bail offered, what he would demand for his appearance,
to answer what could be laid to his charge: but he (contrary to law,
if he had taken him lawfully) denied to accept of any bail,
and clapped him up in close prison.
After he was in prison, a copy of his mittimus was demanded,
which ought not to be denied to any prisoner,
that so he may see what is laid to his charge: but it was denied him,
a copy he could not have, only they were suffered to read it over.
And everything there charged against him was utterly false;
he was not guilty of any one charge in it, as will be proved,
and manifested to the nation.
So let the governors consider of it.
I am concerned in this thing, inasmuch as he was apprehended in my house,
and if he be guilty I am so too.
So I desire to have this searched out.

[.signed-section-signature]
Margaret Fell.

--

Margaret Fell further determined to take a journey to London,
to solicit the King`'s protection,
and lay the circumstances of George Fox`'s imprisonment before him;
which when Porter understood he went also,
with a view to before frustrate her endeavours: but when he made his appearance at court,
having been a zealous partisan for the parliament,
and being charged by some of the courtiers with plundering their houses,
he thought it safest to make a speedy retreat, and return home.
So Margaret Fell being joined by Anne Curtis (whose father had been sheriff of Bristol,
and had suffered death for endeavouring to bring in the
King) on whose account they were favourably received,
laid the case of George Fox before the King, requesting his favourable interposition,
to cause him to he removed to London, and hear his cause himself;
which request he readily complied with,
and gave command to his secretary to send down an order for his removal accordingly;
upon their application to the secretary,
he informed them that according to law he must be
brought up by habeas corpus before the judges;
and writ to the judge of the King`'s-bench, that it was the King`'s pleasure,
that George Fox should be removed to London by habeas corpus,
which was accordingly procured and sent to the sheriff of Lancashire.
But as his persecutors were sensible,
that there were no grounds for the high insinuations of danger contained in his mittimus,
and that they could bring no shadow of proof against him, being conscious,
that their proceedings in his committal and detention could not bear the test,
they sought many evasions, objecting first to the informality of the writ,
next insisting on his bearing the charge of sending him up under a guard;
this unjust requisition he persisted, in regard of his innocence,
to refuse compliance with: at last, after two months hesitation,
they permitted him to go up in company with some of his friends without any guard,
on his verbal promise to appear before the judges
at Westminster upon a certain day of the term,
if the Lord permitted.
A clear demonstration that his imprisonment was the mere effect of malice,
and wanton despotism in the republican mayor,
and that his persecutors themselves did not really believe
him to be the man they endeavoured to represent him.

George Fox, whose promise was acknowledged to be a sufficient bond for his appearance,
presented himself in the court of King`'s-bench accordingly,
being accompanied by two of his friends, Richard Hubberthorn and Robert Withers,
together with esquire Marsh of the King`'s bedchamber.
The charge against him was read, the people were moderate,
and the judges dispassionate and favourable;
no accuser appearing to prove the charges against him,
esquire Marsh signified to the judges,
that it was the King`'s pleasure that George Fox should be set at liberty;
upon which the judges inquiring of him,
whether he would be willing to refer the matter to the king and council,
he readily consented.--Wherefore the judges caused the sheriffs
return of the habeas corpus to be laid before the King,
who upon consideration of the whole matter, and the futility of unsupported crimination,
gave directions to the secretary of state to send an order to Sir Thomas Mallet,
one of the justices of the King`'s-bench, for his release,
who in consequence issued his warrant to the marshal of that court to set him at liberty,
after an unjust and severe imprisonment for more than 20 weeks.

His liberty, thus honourably obtained, filled his antagonists with vexation and fear:
Porter in particular was greatly terrified,
under the apprehension that George would avail himself by law of the advantage,
which the temerity and illegality of his injurious treatment had given,
to the utter ruin of himself and family: and George Fox did not want incitement,
even from some in authority, to make him and the rest examples: but he,
esteeming it his duty as a christian forgive injuries, meekly replied,
"`I shall leave them to the Lord; if he forgive them,
I shall trouble myself no farther about them`"

It was just at this time that several of the late
King`'s judges were brought to their trials,
condemned and executed in an ignominious manner: when George Fox came to London,
he passed a multitude of people gathered at Charingcross,
to see the burning of the bowels of some of them, who had been hanged,
drawn and quartered pursuant to their sentence;
and when he went next morning to surrender himself to Sir Thomas Mallet,
he found him preparing to go to the court, to sit upon the trial of others of them.

Amongst the rest that suffered on this occasion, was Col.
Francis Hacker, who six years before had George Fox taken prisoner,
and sent up in custody to Oliver Cromwell, as hath been related in its course.
In this reverse of his fortune,
he had cause to reflect upon George`'s parting expressions,
"`When the day of his misery and trial should come upon him,
then to remember what he had said to him.`"
Margaret Fell, visiting him in prison a day or two before his execution,
reminded him of his maltreatment of the innocent in the day of his power:
he acknowledged that he perceived whom she meant, and felt trouble for it.

Hugh Peters also, a furious independent preacher, and chaplain to Oliver Cromwell,
suffered with the Regicides, and with equal justice,
as having by his inflammatory harangues incited the
army to demand the death of the late King.
When men assuming the character of ministers of the
gospel depart so far from their proper province,
as to excite tumult and bloodshed in the state,
they forfeit all just pretensions to the character they assume.
The fomenters of sedition,
ill-will and party animosity clearly manifest themselves
not to be messengers of the Prince of peace.

About this time Richard Hubberthorn obtained access to the King,
and upon laying before him the excessive sufferings of his friends under the late rulers,
and that the like were even now continued in some part of the nation under his rule;
the King was pleased to enter into a free conversation
with him concerning the principles of this people,
and was so well satisfied with his account thereof,
that he expressed his disposition to protect them, in the following terms;
"`Of this you may be assured,
that you shall none of you suffer for your opinions or religion,
so long as you live peaceably, and you have the word of a King for it;
and I have also given forth a declaration to the same purpose, that none shall wrong you,
or abuse you.`"
But this promise, ratified by the word of a King, was very unfaithfully kept.
