== Chapter II.

[.chapter-synopsis]
* Insurrection of the Fifth-monarchy Men
* Occasion taken from thence to bring Dissenters under suspicion of disloyalty
* Proclamation issued against Anabaptists, Quakers and Fifth-monarchy Men
* Great Sufferings, in consequence thereof, attend the People called Quakers
* The Prisons in many Places crowded with them
* George Fox and Richard Hubberthorn publish a Declaration of their Abhorrence of Plots
* Margaret Fell solicits the King on behalf of her imprisoned Friends
* Proclamation for their discharge
* Afterwards persecuted on obsolete laws against Recusants.

Thus encouraged,
they seemed to have a prospect of better times than they had experienced
since they were distinguished as a separate society;
their meetings were very large and quiet,
multitudes flocked to them from curiosity or better motives, many were convinced,
and their numbers greatly increased; but this calm was of no long duration.
For in the 11th month (called January) this year an insurrection
was made by the on of the Fifth-monarchy men (of whom mention
hath been made before) under the conduct of one:
Venner a wine-cooper,
who having animated his followers to the desperate attempt by a passionate harangue,
that the time was now come to establish the kingdom of Jesus upon earth,
before the new government should be fixed and established
under the dominion of the restored monarch,
issued forth from their meeting place, with fifty or sixty followers completely armed,
with a resolution to subvert the present government,
and to establish their imaginary kingdom in the place thereof.
At first everyone fled be fore them; they went triumphantly from street to street,
everywhere proclaiming King Jesus.
At length the magistrates having assembled the trained bands, made an attack upon them;
after defending themselves, and slaying several of the assailants,
they made a regular retreat to Canewood near Hampstead;
from which being dislodged the next morning by a detachment of the guards,
they returned again to the city, and took possession of an house,
in which they defended themselves against a body
of troops till the major part were killed.
The few survivors being taken prisoners, were tried, condemned and executed;
Venner and one of his officers, before their meeting-house door in Coleman-street,
and nine others in different parts of the city.

This wild attempt of a very few deluded individuals furnished the courtiers and bishops,
now returned into power, the pretext they wanted, to gratify their thirst of vengeance,
and let their former oppressors, with other dissenters, feel in disloyalty, their turn,
the rigours of persecution,
and to evade the force of the probable charge of violating
the King`'s declaration of indulgence to tender consciences,
but a few months old; this insurrection was made a handle of,
to throw a suspicion of disloyalty upon all sectaries, so called;
and this suspicion was by every effort kept alive by the ruling
powers and their abetters during most part of this reign;
wherein justice, mercy, and truth were frequently violated,
to promote the sinister purposes of prejudiced or ill-designing men.
The colour, therefore,
under which they palliated their sudden and open violation of the royal promise, was,
as not prosecuting nonconformists for their religious scruples,
but as persons dangerous to the state;
but the cover was too flimsy not to be seen through,
they only waited for the firmer establishment of
themselves till they threw off the mask.

During the time of the tumult,
on the second of the 11 month an order of council was issued
against the meetings of sectaries in great numbers,
and at unusual times: and on the 10th of the same month a proclamation was published,
whereby the King forbade the Anabaptists, Quakers,
and Fifth-monarchy men to assemble or meet together under pretence of worshipping God,
except in some parochial church or chapel,
or in private Quakers houses by persons therein inhabiting.
All meetings in any other places were declared to be unlawful and riotous.
And all mayors, and other peace officers were commanded to search for such conventicles,
and cause the persons therein to be bound over to the next sessions.

This proclamation appears to be drawn up with more
art and fallacy than found judgment or equity:
while it reaches all the different sects of dissenters,
all who do not assemble for worship in some parochial church or chapel, as rioters,
it distinguishes only those looked upon as the most insignificant,
and least formidable for their numbers or abilities.
The Presbyterians are passed over in silence, because they could not, as yet,
with any colour of decency, be pointed out specifically as foes to that government which,
through their resentment to the independents, and the cajolements of the royalists,
they had but just before been conducive to establishing:
The independents also are unnoticed, probably for fear,
till they were humbled into a greater degree of imbecility
of awakening the exertion of that vigour,
and those abilities,
the effects whereof were yet sufficiently recent in the memory of the present administration,
to produce a cautiousness in rousing them into action again.
The Anabaptists and Quakers, as new or weaker sects, are treated with less ceremony,
and without any occasion administered by them,
are ranked in one class with these wild disturbers of the public peace, wherein Justice,
the characteristic virtue of good government,
was designedly violated by involving the innocent with the guilty in one confused mass.
We have too many instances in history to excite a persuasion
that men in power esteem the rules of morality,
and regard to a good conscience, obligatory only upon the inferior classes of mankind;
but to be no tie upon them,
when they stand in the way of gratifying the impulse of their ambition, revenge,
or political projects.
Through the various revolutions marked in the course of this history,
how few of the rulers appear to have borne the sword uniformly,
for a terror to evil-doers, and the praise of them that do well.

In consequence of this proclamation,
the Quakers were again exposed to a fresh and severe persecution,^
footnote:[The most irreligious and profane sort of people were animated,
and took occasion against our religious and peace able meetings,
eagerly to endeavour to suppress them,
being encouraged by the new justices and magistrates then got into commission.
The most vile and profane, as drunkards, swearers, cursers, and most wicked of all sorts,
being lifted up, and exalted in their spirits upon the restoration of the King,
and his accession to the throne,
then were triumphant and insulting against all religious dissenters,
and especially threatening the Quakers and their meetings with ruin, etc.
And seeing what a great flood of wickedness and debauchery was broken forth,
and religion and virtue despised,
we then expected no other than severe and hard treatment from our persecutors,
whose hearts were set in them to endeavour our ruin,
or to root us out of the land.`"--George Whitehead`'s [.book-title]#Journal, Part 2.# p. 242.]
although by the dying testimony of the sufferers at their execution,
declared to have no part in, or knowledge of their plot; abused by the populace,
dragged from their employments;
their houses ransacked and their meetings broken up by soldiers;
sick men dragged out of their beds to prison, one of which, Thomas Patchen,
being in a fever, died there.^
footnote:[Among many others Thomas Patchen, a man of a considerable estate,
was taken when sick, and hurried away twenty-five miles to prison, where he was,
with the rest, put among the felons, who abused him sorely,
and would have stripped him of his clothes, to the endangering of his life,
had he not consented to let them have 3l. 5s. in money, which the jailer awarded them;
notwithstanding which they afterward took from him
two coats worth 2l. 10s. The fatigue of his journey,
and the cruel usage he met with in the jail, so increased his distemper,
that he died there a few days after his confinement.
The felons also rifled the other prisoners, taking from some their money,
from others their clothes and accessories.`"--Besse V.1 p. 690]

George Fox was still in London, and gives account that all was uproar and tumult:
The city and suburbs up in arms; the populace and military exceeding rude and abusive:
Henry Fell, going quietly to a friend`'s house, was knocked down by the soldiers,
and had been killed if the Duke of York`'s passing by had not prevented.
George was taken prisoner, but soon after,
by the interposition of his friend esquire Marsh, set at liberty.

Richard Brown, one of the numerous temporizers of this age,
who under the former powers had distinguished himself as a fierce adversary to the royalists,
particularly at Abingdon, being mayor of the city this year,
to compensate for his former misconduct, turned, with the temper of the times,
a no less distinguished persecutor of dissenters; discovering himself to be a forward,
intemperate zealot in executing all the rigorous measures of this reign.
He pursued the Quakers with peculiar acrimony and violence,
and committed them to Newgate in such numbers, that they had not room to sit or lie down,
nor scarce to stand one by another.
There were at one time in that jail of the mayor`'s
own committing three hundred and forty-six persons,
of whom about an hundred were crowded together in one room, and divers fell sick,
through the smell and closeness of the place; besides these,
were several others whom the officers and soldiers had carried, as above,
without any legal or regular warrant for that purpose.

This persecution was not confined to the city, but, with the proclamation,
spread with similar violence over all, or most parts of, the nation; from their meetings,
from their habitations and employments; out of their beds in the dead of the night,
they were, without conviction, without crimination, without any legal cause,
violently haled to prison, till in many places the prisons were crowded with them,
almost to the danger of suffocation, by the number stowed together in close, damp,
or unwholesome rooms.
To recount the particular circumstances of their hard and unmerited
treatment on this account would swell the work too much;
but those who desire a fuller information than the cases presented in the notes,^
footnote:[On the 31st of the 11th month (January) Roger
Milton was called out of his bed by officers with a warrant,
and kept, together with John Dudge and William Wyatt, under a guard all night,
and conducted next day to Twyford,
whence for refusing to take the oath of allegiance tendered by three justices,
they were committed to prison;
where the cruel treatment they received strongly marks the
virulent temper of the persecutors at this time.
They were thrust into a dungeon among felons to the number of twenty-two,
a place so close,
that the jailer acknowledged he thought it would breed an infection among them:
They would not be suffered to walk in the yard for air, nor their friends to visit them,
nor bring them food and other necessaries: Their ink,
paper and working tools were taken from them;
they were made the subject of the keeper`'s derision,
who bringing some of his companions to see them, scoffingly said,
There was not such another bed in Berkshire.
{footnote-paragraph-split}
Few or no counties escaped this general persecution;
but in consequence of the proclamation the Quakers
(so called) were everywhere taken up in crowds,
violently haled by soldiers or peace officers before the justices,
who generally tendered them the oath of allegiance,
+++[+++which they knew they had a religious scruple against taking+++]+++
and upon their conscientious refusal,
committed them to prison by fifty or sixty at a time.
In Bristol near one hundred and ninety were imprisoned:
Soldiers kept guard at the several prisons night and day,
with orders to admit nobody to them: Their servants were denied access,
what they brought was narrowly searched, and themselves rudely treated:
In Lancaster were two hundred and seventy prisoners,
in Westmoreland one hundred and sixteen,
in West Riding of Yorkshire the number committed
to prison was no less than two hundred and twenty-nine,
for refusing to swear, being taken, many of them, from their religious meetings;
some on the high-ways, others from their houses and lawful employments,
and some out of their beds; One hundred and twenty-six in the North-Riding,
in like manner and for the same cause; mostly for refusing to take the oaths,
and proportionately in other counties.
Whence it is apparent,
that this insurrection was made a handle to effect a preconcerted design,
for their fidelity appears not to have been called in question,
but most or all to be committed for their scrupling to take an oath.
And their treatment in prison was generally as inhuman as their commitment was unjust,
as appears by the following copy of a letter from Leicester jail,
dated the 20th of the 12th month (February), 1660.
{footnote-paragraph-split}
A copy of a letter from Leicester jail,
dated the 20th of the twelfth month,
1660
{footnote-paragraph-split}
Friends,
{footnote-paragraph-split}
It lieth upon us to give
an account of our sufferings we being in number twenty-five,
which are imprisoned because we cannot swear,
we expecting that more will be brought to prison.
We be under the oppression of a cruel jailer,
who refuseth to let us have necessary provision brought to us, and one who is a friend,
which we have employed for that purpose, when she hath made provision ready for us,
and brought it to the door,
the jailer hath several times turned it back with cruel threatning words, saying,
He would break her neck if he took her coming in at the door.
And many of us, being very poor men in the outward,
scarce able to provide for our families when at liberty,
and some of us being fifteen or sixteen miles from our outward beings,
and so unable to buy ourselves provisions at the jailer`'s excessive rates.
Some of us have been imprisoned five weeks: One,
his wife being near the time of her delivery of a child,
his friends desiring but a short time for him to go and speak to his wife,
his brother offering to stay in his room the time, was denied:
Another was brought to prison from his wife,
she being delivered of a child but two days before.
And some of our friends, being brought to prison,
had their coats taken off their backs by the soldiers, and not restored again:
Another friend`'s wife being very weak, and not likely to continue long,
she desiring much to see her husband, who desired, upon security,
so much liberty of the jailer to go and see her, but he denied it;
it lying much upon the friend to go and see his wife in that condition,
he acquainted one of the commissioners with it,
who sent his warrant to the jailer to set the friend at liberty,
and that should be his discharge; but the jailer kept the warrant,
and refused to let him go, except he would pay him a mark fees.
We are forced to hire rooms at excessive rates,
by reason that we cannot have a free prison to hold us so as that we might lie down,
there being so many debtors and felons in it.
Three of the friends imprisoned are Northamptonshire men: One,
whose name is William Vincent,
who had been imprisoned at Northampton near fourteen months,
it being but two weeks after he was put out, but he was brought to prison here,
he being a man in much bodily weakness,
with many running sores upon him and by outward appearance
is not likely to continue long;
his wife also being in the town, and bringing him some warm food,
which she had provided for him, was turned back, and not suffered to bring it to him.
Likewise the jailer denies to let him have a candle at his own charge,
whereby he might dress his sores, it being a dark place,
where he is locked up by day-light; likewise not suffering a few boards,
which were their own, to hold the straw up, but did take them from them.
{footnote-paragraph-split}
Subscribed by Edward Muggleston, Robert Cliffe,
John Evatt, John Swann, John Elliott, William Vincent, Richard Read, William Line,
George Power, George Almon, Thomas Orton, Robert Day, William Smith, Richard Farmer,
Thomas Marshall, Roger Sturgis, Robert Pimm, Thomas Falkner, Robert Bakewell,
William Gregory, William Perkins, William Horton, Peter Hinks, William Tomson,
Samuel Ward
{footnote-paragraph-split}
Many
people were now likewise in Ilchester jail;
the cause and manner of whose commitment is expressed in the following letter,
written by one of them, viz.
{footnote-paragraph-split}
Dear Friend,
{footnote-paragraph-split}
By reason of some rash,
unadvised enterprise of the Monarchy-men in London, which we hear of late hath happened,
which we are altogether unacquainted with,
and clear in our consciences and practices toward God and men,
from the least knowledge of, or hand in,
yet we are made as equally guilty with transgressors,
amongst whom we are numbered and confined in prison,
where we patiently wait until the Lord clear our innocency, and plead our cause.
We are in number already one hundred and forty, and expect more to be daily added,
and the cry of the innocent babes, who are left as it were fatherless,
and of the mournful women, that are deprived of the help of their husbands,
by such a sudden surprisal,
cannot but reach into the most secret corner of the King`'s palace
and pierce the hardest heart that hath any affection to nature:
The Lord plead our cause, and clear our innocency,
and reward them according to their works,
that have brought this distress upon the nation.
I hope the King knows, or will know, that the persecuted people called Quakers,
had no hand in the trespass which occasioned such a proclamation,
whereby and women much abused, beaten, blooded, dragged out of their houses,
and some out of their beds, and others from their ordinary employments,
and haled before magistrates, and so sent to prison, for not going to parish churches,
as they are called; and the oath tendered to them, and for refusing to swear, committed;
and on this account there are lent to the jail, some days thirty, some more,
and some less,
and daily we are in expectation to have friends brought so long
as there can be one found to go under the denomination of a Quaker,
unless there be a stop put to that spirit,
that takes this opportunity to strike at every appearance of truth.
The very worst of men in the prison, that suffer for felony and murder,
rejoicing to see us so persecuted,
and supposing themselves in better Condition than men of tender consciences;
and the rude, wild and ranting people in the country,
take occasion to rejoice that they have now the countenance and authority to apprehend,
persecute and im-prison the Quakers,
and some not satisfied that we are confined in prison, for blood is thirsted after,
without which some may hardly escape out of this place,
except the Lord restrain the wrath of man.
{footnote-paragraph-split}
Ilchester, the 22nd of the eleventh month, 1661.]
are referred to Besse`'s [.book-title]#Collection of the Sufferings# of this people,
where they may fully satisfy themselves of the truth of this representation.

Persecution being thus carried on throughout the nation
against a people who had administered no just occasion,
who were not in any degree chargeable with the insurrection or sedition;
but artfully brought under suspicion to palliate the faithless measures
and rigorous designs which were previously determined upon;
the Quakers, as well as other dissenters,
thought it necessary to clear themselves of these groundless surmises,
by a public disavowal of all plots and insurrections whatever,
in order to prepare the way for application for redress of the
various injuries they were unjustly exposed to in their persons,
reputations and properties.
George Fox and Richard Hubberthorn drew up a declaration
of their abhorrence of plots and warring,
in order to present it to the King and Council, but when finished and sent to the press,
it was there seized,
which looks like an arbitrary depriving them of the opportunity of vindicating themselves.
Upon which they quickly drew up another, got it printed,
sent some copies to the King and Council,
and published the rest in their justification to the nation at large.

Abstract of a declaration from the people called Quakers, against all sedition, plotters,
fighters, etc. presented to the king the 21st of 11th month, 1660.

[.embedded-content-document.address]
--

Our principle is, and our practice hath always been,
to seek peace and to follow after righteousness, and the knowledge of God;
seeking the good and welfare, and doing that which tends to the peace of all.
We know that wars and fightings proceed from the lusts of men, James 4:1-3.
out of which lusts the Lord hath redeemed us,
and therefore the ground and cause being taken away the effect ceaseth.
And all bloody principles and practices we (as to our own particular) do utterly deny;
with all outward wars and strife, and fightings with outward weapons, for any end,
or under any pretence whatsoever: And this is our testimony to the whole world.

And whereas it is objected:

Although you now say, that you cannot fight, nor take up arms at all;
yet if the spirit do move you, then you will change your principle,
and then you will sell your coat and buy a sword, and fight for the kingdom of Christ.

Answ.
We say Christ`'s command to Peter, "`Put up thy sword,
for he that taketh the sword shall perish by the sword, was posterior to that,
when for the fulfilling of the law, he said,
He that had no sword might sell his coat and buy one.
And further, the Spirit of Christ, by which we are guided, is not changeable,
so as once to command us from a thing as evil, and again to move unto it;
and we do certainly know, and so testify to the world, that the Spirit of Christ,
which leads us into all truth,
will never move us to fight and war against any man with outward weapons,
neither for the kingdom of Christ, nor for the kingdoms of this world.

[.numbered-group]
====

[.numbered]
_First,_ Because the kingdom of Christ, God will exalt, according to his promise,
and cause it to grow and flourish in righteousness;
Not by might nor by power (of outward sword) but by my spirit, saith the Lord, Zech. 4:6.
So those that use any weapon to fight for Christ,
or for the establishing of his kingdom or government, both the spirit,
principle and practice in that, we deny.

[.numbered]
_Secondly,_ We do earnestly desire and wait, that (by the word of God`'s power,
and its effectual operation in the hearts of men) the kingdoms
of this world may become the kingdoms of the Lord,
and of his Christ, that he might rule and reign in men by his Spirit and Truth;
that thereby all people out of all different judgments and professions,
might be brought into love and unity with God, and one with another;
and that they might all come to witness the prophet`'s words, who said,
Nation shall not lift up sword against nation, neither shall they learn war any more. Isa. 2:4.
Micah 4:3.

====

And whereas all manner of evil hath been falsely spoken of us,
we hereby speak forth the plain truth of our hearts,
to take away the occasion of that offence; that so we being innocent,
may not suffer for other men`'s offences,
nor be made a prey upon by the wills of men for that of which we were never guilty;
but in the uprightness of our hearts we may,
under the power ordained of God for the punishment of evil-doers,
and for the praise of them that do well, live a peaceable and godly life,
in all godliness and honesty.
For although we have always suffered, and do now more abundantly suffer,
yet we know that it is for righteousness sake: For our rejoicing is this,
the testimony of our consciences, that in simplicity and godly sincerity,
not with fleshly wisdom, but by the grace of God,
we have had our conversation in the world.
2 Cor. 1:12 which for us is a witness, for the convincing of our enemies.
For this we can say to all the world, we have wronged no man`'s person or possessions;
we have used no force nor violence against any man; we have been found in no plots,
nor guilty of sedition; when we have been wronged,
we have not sought to revenge ourselves; we have not made resistance against authority;
but wherein we could not obey for conscience-sake,
we have suffered even the most of any people in the nation.

Our weapons are spiritual, and not carnal, yet Mighty through God,
to the pulling down of the strong holds of sin and Satan, who is author of wars,
fighting, murder, and plots; and our swords are broken into plow-shares,
and spears into pruning-hooks,
as prophesied of in Micah 4. Therefore we cannot learn war any more,
neither rise up against nation or kingdom with outward weapons,
though you have numbered us amongst the transgressors and plotters:
the Lord knows our innocency herein,
and will plead our cause with all men and people upon earth,
at the day of their judgment,
when all men shall have a reward according to their works.`"

This is given forth from the people called Quakers, to satisfy the King and his council,
and all those that have any jealousy concerning us;
that all occasion of suspicion may be taken away, and our innocency cleared.

--

Every measure seems to have been pursued to fill the nation with alarm,
and consequently the ill-judging multitude with rage against dissenters,
the objects pointed out as dangerous to the state; the press was narrowly watched;
orders were given to stop and search all letters in the post office;^
footnote:[Of this we have a remarkable instance in
Thomas Ellwood`'s narrative of his own life.
Meeting with Thomas Loe at I. Penington`'s,
he proposed to him to appoint a meeting in the town where he dwelt.
To this proposal Thomas Loe signified, "`He was not at his own disposal,
but desired Thomas Ellwood, if the thing lay with weight on his mind,
and he could get a convenient place for a meeting,
to advise him thereof by letter to Oxford,
and then he might let him know how his freedom stood.`"
Thomas Ellwood accordingly having procured a suitable place,
writ account thereof to Thomas Loe, his letter was intercepted,
and brought to Lord Falkland, Lord Lieutenant of the county,
who ordered the two deputy lieutenants nearest him to send
a party of soldiers to fetch him in and examine him thereupon.
Upon examination, their endeavours, to wrest his letter to a criminal design,
affording no sufficient ground of punishment, they tendered him the oath of allegiance,
and on his refusal committed him prisoner to Oxford.]
soldiers let loose to drag to prison whom they pleased,
so that it was dangerous for them to walk the streets;
they were insulted and abused by the mobs; disturbed in their religious exercises;
taken from their trades and families, and thereby exposed to great hardships,
loss and damage, and their families, many of them, to want.

From the impulse of affection and sympathy,
at that time so remarkable amongst this people,
in addition to the endeavours used for their relief by the aforesaid declaration,
Margaret Fell several times waited personally upon the King
to solicit his indulgence and protection for them:
at her first admission she signified to him, "`they were an innocent, peaceable people,
who did no injury, and administered no occasion of offence,
except in keeping up their religious meetings, for no other purpose but worshipping God,
in that way, they were persuaded was most acceptable to him,
and edifying one another in his fear;
which being to them a conscientious matter of duty to God, they could not violate it,
in compliance with the ordinances or laws of man,
whatever they suffered,`" She waited upon him again,
to inform him how severely her friends,
who were not in the least concerned in insurrection or riot, were treated;
several thousands of them through the nation being cast into prison illegally,
in consequence of other men`'s crimes.
The King and council wondered how they gained the intelligence,
after the strict orders they had issued to intercept all letters,
so that none might pass unsearched.
However, in consequence of her application, and the declaration above-mentioned,
the King sent out a proclamation,
forbidding soldiers to search any house without a constable.
Afterward, when some of the unhappy insurgents were brought to suffer,
they were so just to this injured people,
as by their dying testimony to clear them of all guilt,
publicly declaring "`they had no hand in, or knowledge of their plot.`"
This with other evidences, and their continued intercessions,
prevailed upon the King to issue discharge, out a declaration,
ordering the Quakers to beset at liberty without paying fees.

But yet that spirit of riot and furious hatred, which had been, it is feared,
designedly stirred up in the populace towards this people,
continued to be very vexatious to them, especially in their religious assemblies;
for besides the interruption they suffered from the officers and soldiers,
they were exposed to the abuse and disturbance of many rude people,
who made it their business to come to their meetings
on purpose to molest and insult them;
and although for the present,
the fierce current of persecution was in some measure stopped by the King`'s proclamation,
and the prisoners confined in consequence of the
insurrection of the Millenarians set at liberty;
although cruelty was not reckoned amongst the King`'s vices,
yet being surrounded by counsellors, churchmen and courtiers, averse to toleration,
he too easily gave into their views;
and in violation of his solemn promise in his declaration from Breda,
suffered great numbers of his subjects to be continually
harrassed with spoil of their property,
even to reducing them from opulent or easy circumstances to indigence,
and the repeated deprivation of their personal liberty, and all the comforts of life.

After the Quakers were fully cleared of the plot of the Fifth-monarchy men,
and all pretences of punishing them on that account were removed,
it was not long till they were again grievously persecuted
by the revival of old laws made in the reigns of Henry VIII.
and Elizabeth, chiefly against popish recusants,
but now perverted to the punishment of this inoffensive body of people,
who had not in anything disturbed the peace of the kingdom,
while the Papists themselves were not only suffered to remain unmolested,
but through covert favour of the court, are generally reported to have promoted,
by all their interest, which was not inconsiderable,
the severe measures pursued against other dissenters in this reign.
The principal laws which were thus revived,
and distorted to the unreasonable and unjust punishment of this society at this period,
and during this reign, rigorous in themselves,
and made more so by the extreme severity exercised in the execution of them,
were these which follow.

First, the act passed in the thirty-second year of Henry VIII.
against the subtraction of tithes +++[+++as of divine right due to God and holy church+++]+++
whereby justices of peace were obliged to commit the contumacious defendant to prison,
till he should find sufficient surety to give due obedience to the process,
decrees or sentence of the ecclesiastical court.

[quote]
____
Although this act be a general one, pointed at no particular society,
and through the attachment of the clerical order to their secular interests and power,
through all revolutions of government prevented from growing obsolete:
yet how grievously great numbers of this society have suffered there by,
hath been shewn in numerous instances, and may in more hereafter.

For believing this law,
in its ground and tendency to be in direct contradiction to a superior Jaw,
the command of Christ Jesus himself, "`Freely ye have received,
freely give`" that the practice of the Apostles and the primitive church for three
successive centuries was a proof that tithes were no gospel maintenance,
but abolished with the Jewish law to which they belonged;
that in the dark ages of priestly dominion, laic superstition and implicit faith,
they were gradually introduced, and established in the manner they are now applied,
by the avarice, fraud and influence of selfish and popish ecclesiastics;
on these considerations, as christians, as protestants and reformers,
they believed themselves under an obligation of conscience neither to pay them,
nor actively comply with the law;
but to bear open testimony against the imposition as antichristian;
but the priests having by this law the power to imprison them,
and detain them in prison '`till the pretended debt,
and exorbitant cost of the ecclesiastical courts were fully paid and satisfied;
and they being restrained from paying such demands
in violation of their consciences and peace of mind,
points more tender with them than the security of their property,
liberty or natural lives; many of them were imprisoned several years,
and many laid down their lives in prison, in support of this their christian testimony.
____

Second,
the laws made in the reign of Queen Elizabeth for
uniformity of common prayer and public worship,
viz.

First, that enacting a forfeiture of one shilling to the use of the poor,
to be levied off every person who did not resort to their parish church, or some other,
every Sunday or Holyday.

The second establishing a forfeiture of twenty pounds a month for the like default.^
footnote:[At every quarter sessions several were fined for not coming to church;
some excommunicated,
and some fined "`in a sum much larger than all they were worth in the world.`"
Of this we have a remarkable instance in the case of John Shipman and Thomas Virtue,
both of the county of Suffolk,
(who were prosecuted on this act of Elizabeth) as presented
to the King and council on the 5th of November 1663.
{footnote-paragraph-split}
For the King and Council.
{footnote-paragraph-split}
A short relation of the
cruel usage of two of the King`'s peaceable subjects,
John Shipman, of Cretingham in the county of Suffolk,
and Thomas Virtue of Clopton in the same county, etc.
{footnote-paragraph-split}
The said persons
being informed against by the sheriff`'s bailiffs,
and by the bailiffs of the liberty where the said persons dwelt,
upon a statute made against popish recusants;
and for their not being at the public worship for eleven months past,
at a quarter sessions holden at Woodbridge in the said county, John Sicklemore judge,
judgment was passed against them by the justices there,
for each of them to pay 20l. a month for eleven months, eleven score pounds a piece;
and since,
the bailiffs aforesaid have taken away goods worth 68l. 15s. from John Shipman,
and 35l. worth from Thomas Virtue and do threaten to take more from them,
until they be satisfied for the fines of twice eleven score pounds,
although the whole estate of the said Thomas Virtue
is not judged to be worth half so much,
so that if the King shew not some kindness to these poor men, the said Thomas Virtue,
his wife and fix children, are like to be left destitute: and farther,
the said persons were for the same cause both kept in prison;
the one of them a year and a half,
the other a year and a quarter be fore their goods and cattle were taken away.
{footnote-paragraph-split}
Therefore our request to the King is,
that he would relieve the said sufferers;
and that they may not thus deeply suffer for conscience sake,
who wish well to King and government.
Besse`'s [.book-title]#Sufferings, Vol, 1# p.673]

A Third enabling the Queen to seize all the goods,
and two-thirds of the lands of every such offender,
for the sum then due for 20£. a month; and yearly after that to do the same,
for so long time as they shall forbear to come to church.

[quote]
____
By the first of these acts some few were prosecuted by magistrates
of moderation and lenity to obviate greater severities,
and by others to expedite severer punishment; but many more,
upon the latter and though the King, at the intercession of George Whitehead,
Gilbert Latey and others, ordered stay of process in divers counties;
yet afterwards the prosecutions were continued until after his death,
both to imprisonment and seizing of goods.
____

Fourth, And as if these laws were not severe enough, in the 35th year of the said reign,
an act was made to oblige offenders in the like case
to abjure the realm on pain of death.

[quote]
____
This law, made it may be supposed, chiefly against papists,
was endeavoured in some instances to be enforced against the Quakers;
but as it was well known they could not swear at all,
and therefore that they would not abjure the realm;
and of consequence prosecutions by this law must terminate in their death,
which might occasion an alarm in the nation, and a detestation of such severity,
prosecutions under this law were discouraged,
even by judges otherwise severe enough against the Quakers: yet we shall find,
on more occasions than the one following,
endeavours were used by some inveterate spirits to
bring them under the lash of this law.

William Alexander of Needham in Suffolk,
being with several others indicted upon this act, was called upon to plead,
guilty or not guilty; but not being hasty to answer, the judge said, why don`'t you plead?
Alexander said, what wouldst thou advise us to plead?
If you ask my advice, said the judge, you shall have it,
and I`'ll advise you to plead not guilty.
The prisoners pleading accordingly, the judge turning to the prosecutors, informed them,
that now they must prove these men, neither to have been at their own parish church,
nor any other church or chapel, else they were not within this act,
which is a sanguinary law.
Alexander and the rest were accordingly discharged.
____

Fifth,
The act made in the beginning of Queen Elizabeth`'s
reign for administering the oath of supremacy,
and that of the third of James (after the discovery of the
gun-powder plot) enjoining the taking the oath of allegiance,
afterwards distinguished by the name of the Test.

[quote]
____
Now albeit this last was enacted particularly as a security
against the dangerous machinations of the papists,
yet in this reign these met with shelter and protection,
and the edge of this law was turned against the Quakers very deceitfully and unjustly;
for as it was now generally known,
that they had a conscientious scruple against taking any oath,
apprehending the precept of Christ, swear not at all, a positive obligatory command,
which they ought not in any case to transgress,
and that no law or power upon earth could justify them in the breach of a divine law:
although they were willing to acknowledge their allegiance by any plain declaration,
short of an oath; yet on account of this conscientious scruple,
a preconcerted and unreasonable advantage was taken of this act.
But through divine support in all their afflictions,
they were actuated by an invincible constancy,
and preserved steadfast in their obedience and their faith, through bonds, premunires,
banishments, and even death itself.
____

In the late general imprisonment in pursuance of the proclamation
published on the rising of the fifth monarchy men,
when the innocence of this society appeared so clearly,
that there remained no shadow of reason to detain them on that account,
it was the usual method with the magistrates to tender them the oath of allegiance,
which they knew they would not take,
that by their refusal they might get a more plausible
pretext to commit and detain them in prison.
On this account many hundreds were imprisoned,
from the time of the insurrection till they were
liberated by the king`'s declaration aforementioned;
but it was not on this occasion only, they suffered by this act, but it continued,
when other means failed to supply the malevolence of their
adversaries a handle to ensnare and be vexatious to them,
through the greatest part of this reign,
as may more fully appear in the process of this work:
But to recite all the hardships and sufferings they were exposed
to on this single scruple were to write a large volume,
and therefore I can only cursorily take notice of
the most remarkable cases as they arise:
for the present, as it may be apprehended,
that in troublesome times it is but reasonable for the government
to require this security from the subject,
the following case will shew that they were not backward to demonstrate their allegiance,
as far as they could go, without disobeying the command of Christ, as they understood it,
which joined to their peaceable and unresisting demeanour,
chargeable with no disaffection, might safely have been accepted,
were the rulers of that time as indulgent to tenderness of conscience,
as they were bent upon singling out the members of this society to tender the oath to,
for the pure purpose of involving them in distress by subjecting
them to the penalties enacted by this law.

At the assizes of Bedford on the 13th of the month called March, 1660-1,
two and fifty per sons, then in prison for refusing the oath of allegiance,
were brought before judge Windham, who ordered the statutes of 35 Elizabeth and 7 James,
to be read; telling the prisoners, that many of them being but young,
might probably be ignorant of the penalties they were liable to for refusing the oath.
One of them, in the name of the rest, answered,
That the penalties had been fully considered by them:
That they thought it their duty actively to obey the laws of the land,
when consistent with the law of God, and when otherwise patiently to submit.
That the laws read appeared to them contrary to the precept of Christ,
which they durst not break.
They presented at the same time to the Judge, a paper in writing as follows, viz.

[.embedded-content-document.paper]
--

Though it be generally known through Christendom so called,
that the people called Quakers cannot swear at all,
because it is according to the command of Christ, our lawgiver, Judge and Saviour,
yet for taking away all jealousies and fears out of the mind of the king, his council,
and other his officers and subjects in this realm,
and other dominions belonging thereunto, that so under him we may live in a godly, holy,
honest, peaceable and quiet life, to serve God and the creation in our generation,
we give forth these lines,
concerning the oath of allegiance (obligatory to us) to the king, and all the nation,
whom it may concern, that we may not be made transgressors,
without a cause and exposed to suffer for keeping our consciences clear before the Lord.

First of all we do believe and declare,
that the immediate hand of the Lord hath brought in Charles Stuart,
now proclaimed king of England, Scotland,
etc. according to the laws and statutes of the nation; and that the Pope,
neither of himself, nor by any authority of the church or fee of Rome,
or by any other means with others, hath any power to depose the king,
or to dispossess him of any of his dominions,
or to authorize any foreign prince to invade or annoy him,
neither to discharge any of his subjects from their obedience to him,
or to give license or leave to any to take up arms,
or to offer any violence or hurt to the person of the king, state or government,
or to any of his subjects within his dominions: And likewise we declare,
and shall keep our words,
notwithstanding any declaration or sentence of excommunication or deprivation,
made or granted, or to be made or granted by the pope or his successors,
or by any authority derived, or pretended to be derived from him, against the king,
his lawful heirs and successors, or by any absolution of the said subjects to the king:
That we will not conspire, neither attempt any conspiracy against his person,
nor plot nor contrive anything against him, nor any of his subjects,
neither would we have any others to do it,
notwithstanding any sentence or declaration from the Pope;
and farther we do abhor and detest that position, as impious and heretical,
and a damnable doctrine, that princes which be excommunicated by the Pope,
may be deposed or murdered by their subjects, or otherwise.
And further we do believe in our hearts, that neither the Pope nor any other whatsoever,
have power to absolve us of this our acknowledgment and testimony, or any part thereof,
and do renounce all pardons and dispensations to the contrary.
And these things we do plainly and sincerely acknowledge and confess,
according to the plain common sense and understanding of the words herein, expressed,
without any equivocation, mental reservation, or secret evasion whatsoever,
and these things shall attest by words, and shall, if thereunto lawfully required,
set our hands.

So let us not be made a prey upon, seeing what we do is in a good conscience to God,
and in it these things we write, and shall keep in truth and righteousness,
which may satisfy you and all reasonable men.

--

On the next day the oath was tendered to six of the prisoners,
who insisted on the illegality of their commitment,
having been taken by violence out of their beds,
though innocent of the breach of any law.
The judge answered, if they had suffered any wrong, they might take their remedy at law,
but being now before him, he required them to take the oath, adding,
that an oath was a part of God`'s worship,
and that the scriptures had always been interpreted that men might swear.

The prisoners speaking in their own defence were interrupted and hurried away.
The grand jury found the bills of indictment,
and returning into the court one of them was read to the prisoners, who were told,
the rest were like it: And they not forward to plead, were sent back to prison.

The convention parliament, after having fixed the king on the throne,
and been pretty liberal in their grants, were dissolved,
probably because the number of Presbyterians therein were expected
to be a bar in the way of executing the projected measures:
And writs were issued for a new parliament to meet on the 8th of the month called May:
The tide of popular favour, by the artful rumour of fictitious plots and conspiracies,
carried on by the non-conformists,^
footnote:[The denomination of Puritans was now changed into that of non-conformists,
as a term that would comprehend every class of dissenters from the established religion.]
had been turned against them,
and ran violently on the side of the hierarchy and prerogative;
this temper in the people, under the influence of the court,
prevailed in carrying the elections in favour of a great
majority of the royalists and zealous churchmen,
the number of Presbyterians returned,
being too inconsiderable to oppose or retard their measures,
monarchy and episcopacy were restored to their former splendour and power,
which church (so called) and state jointly exercised with that avengement,
and want of moderation and justice,
which are generally the concomitants of a violent party spirit.

At the opening of this parliament, the king, in his speech, declared,
"`That he valued himself upon keeping his word,
and upon making good whatsoever he had promised to his subjects.`"
At the same time that the Chancellor +++[+++Clarendon+++]+++
by his succeeding comment,
in a virulent speech against seditious (which meant no more than dissenting) preachers,
was paving the way, by inflaming the parliament,
to an open violation of his solemn promise of liberty to tender consciences.
Oliver Cromwell hath been grievously censured by the reigning party of this time,
on account of his double dealing; but I recollect no instance of his management,
of a more barefaced duplicity than this, with this difference,
that much of his artifice was exerted in self-defence, against those,
he knew were plotting against him, to wrest his power out of his hands;
whereas in the projects carrying on at this time,
the plainest rules of morality were broken through without any necessity,
by the present rulers, for the mere purpose of exerting power over antagonists, who had,
as themselves now thought, with imprudent precipitation,
been principally instrumental to put the power into their hands,
to gratify a vindictive spirit, and display a wanton triumph in their fall,
by comprehending them and other dissenters, even those,
who having been always of inoffensive and pacific principles and demeanour,
whom they feared not, and knew they had no reason to fear,
under one common description of non-conformists,
and then pointing out these non-conformists as objects of suspicion,
detestation and abuse.
It is alleged the king did not voluntarily concur with these violent measures;
but that the zeal of Clarendon and the church party among the commons,
seconded by the intrigues of the catholics^
footnote:[The Catholics, though they had little interest in the nation,
were a considerable party at court.
These religionists dreaded an entire union among the protestants.
Were they the sole non-conformists in the nation,
the severe execution of the penal laws upon their sect, seemed an infallible consequence;
and they used all their influence against the Presbyterians.
The Earl of Bristol who had changed his religion in his exile,
was regarded as the head of this party.
Hume.]
extorted his consent.
But by whomsoever these arbitrary measures were originally concerted, Clarendon,
or the bishops; papists, or protestants; the breach of faith,
in the manifest violation of the royal promise,
was too flagrant for palliatives to excuse or vindicate;
so that even the writers on the side of the prerogative and episcopacy
are obliged to acknowledge them to be an evasion,
and breach of the king`'s declaration from Breda.

In order to promote their designs,
to animate the people and parliament against these devoted non-conformists,
the ministry filled the city with rumours of plots
and conspiracies against the king and government,
contriving by them.
Clarendon in a conference between the two houses,
positively asserted that a conspiracy had been formed
to interrupt the peace of the nation,
and though it had been disconcerted in the city,
it was still carrying on in the counties.
Writers generally agree that there was little or no foundation for these reports;
but that they were the mere invention of the reporters,
to facilitate the passing of the severe laws that were coming upon the carpet.

After this prelude, the parliament proceeded to pass that called the corporation-act,
whereby all non-conformists were excluded from offices of trust and magistracies;
and some time after the act of uniformity,
which deprived all the Presbyterian and other non-conforming ministers of their benefices,
and re-instated the episcopalians in the full possession of the power,
and the emoluments of the priesthood.
These acts did not in themselves materially affect the Quakers,
who aspired to no places of honour or profit, who testified against preaching for hire,
and sought for no more than a toleration and protection
in their religious and civil rights,
to lead a quiet and peaceable life in all godliness and honesty;
yet the corporation act in its consequences did affect them,
by filling the city and country with persecuting magistrates.

And it was not long until they were singled out,
as victims to fresh penal laws in addition to the old ones revived against them.
This parliament being most of them inclined to persecution and devotedly
resigned to the measures and influence of the ministry and episcopacy,
who seemed determined to leave no class of non-conformists unmolested,
brought in a bill directly levelled at this body,
enacting new penalties for refusing to take oaths,
and also to suppress their religious meetings.
