== Chapter III.

[.chapter-synopsis]
* Continuation of the Sufferings of the People called Quakers in America
* Sufferings of William Leddra
* He is brought to his trial
* Appeals to England
* His Appeal over-ruled
* Condemned to death
* The Manner of his Execution
* A Letter relating to his Death
* Edward Wharton`'s Examination
* Sentence of Banishment
* His Address to the People
* Trial of Wenlock Christison
* The Court divided, yet the Governor passes sentence of death upon him
* An Order for releasing the Quakers out of Prison
* Edward Burrough solicits the King to put a stop to the Persecution in New-England
* The King in compliance with his Solicitation orders a Mandamus to stop it
* He deputes Samuel Shattock to carry it over
* The Mandamus delivered, and Persecution in part stopped
* Second Order for the discharge of Prisoners

As it was about this time that the people called Quakers in England received
intelligence the severities against their friends in New England,
having been carried so far,
that the government had not only made a law to banish them on pain of death;
but had actually put some of them to death upon that sanguinary and unauthorized law,
as before related; Edward Burrough waited upon the king,
to solicit the interposition of his authority to
put a stop to the further effusion of innocent blood,
and was successful in his application.
This seems therefore a proper place to resume our narrative of
the further sufferings under the independent government there,
which was even surpassing in virulence and cruelty,
all the tyrannical proceedings on this side, towards this persecuted people;
while their brethren here were in some measure their companions in affliction.

William Leddra, of Barbados, was the fourth and last,
who sealed his testimony with his blood under their hands.
After much hardship, by imprisonment and many cruel stripes,
he had been banished from Boston on pain of death.
Returning soon after to visit his friends in prison there, he was apprehended,
and kept night and day in an open jail, chained to a log of wood,
during an extreme cold winter, exceeding in in clemency our severest seasons in Engiand.
This poor man seems to have been persecuted with peculiar inveteracy of malice.
In his former imprisonment, he was kept in a prison so close, without sustenance,
that it bore the appearance of a design to suffocate or famish him,
as the latter did of starving him through the inclemency of the weather:
but surviving all these hardships,
he was brought before the court of assistants the 9th of the first
month of this year with his chain and log at his heels:
being set to the bar he was told, that having returned from banishment,
he had incurred the penalty of death by the law.
Upon which he asked, why what evil have I done?
To this the court answered, he had owned those that were put to death,
had refused to put off his hat in court, and said Thee and Thou.
To which William aptly replied, then you put me to death for speaking English,
and for not putting off my clothes.
Major general Dennison absurdly remarked, a man might speak treason in English.
William asked, If it was treason to say Thee and Thou to a single person?
Next Simon Broadstreet, a violent persecutor, asked him, if he would go to England?
To whom William replied, I have no business there.
Then said Broadstreet, you shall go that way, pointing to the gallows.
The prisoner then appealed to England in the following terms,
Will you put me to death for breathing the air in your jurisdiction?
What have you against me?
I appeal to the laws of England for my trial, if by them I am found guilty,
I refuse not to die.
His appeal court, as usual, over-ruled his appeal,
and attempted to persuade him to a recantation,
and a conformity to the religion prescribed by their laws.
But the concern of his mind being to testify against that religion,
which without justice,
mercy or proper authority (for they were not authorized
by charter to make any laws inconsistent with those of England,
and for their transgression of their power,
lost their charter some time after) could produce laws to punish other men with rancour,
and put them to death for theirs, he consistently and boldly replied,
What! join with such murderers as you are; then let every man that meets me say,
lo! this is the man that hath forsaken the God of his salvation.

The court then passed sentence of death upon him,
and appointed the 14th of the same month for his execution.

That the spirit in which he died,
was very different from the representation of C. Mather, before recited,
the following extract from a letter written the day
before his death is a convincing proof.

[.embedded-content-document.letter]
--

[.letter-heading]
To the Society of the little flock of Christ, grace and peace be multiplied.

Most dear and inwardly beloved friends, The sweet influences of the morning star,
like a flood distilling into my innocent habitation,
hath so filled me with the joy of the Lord in the beauty of holiness,
that my spirit is as if it did not inhabit a tabernacle of clay;
but is wholly swallowed up in the bosom of eternity, from whence it had its being.

What can the wrath and spirit of man that lusteth to envy,
aggravated by the heat and strength of the king of the locusts,
which came out of the pit, do to one,
that is gathered under the healing wings of the prince of peace?
under whose armour of light they shall be able to stand in the day of trial,
having on the breast-plate of righteousness, and the sword of the spirit,
which is their weapon of war against spiritual wickedness,
and the rulers of the darkness of this world,
within and without.--I have stood still in that watch, which the master,
without whom I could do nothing, did at his coming reward with the fulness of his love,
wherein my heart did rejoice,
that I might in the love and life of God speak a few words to you,
which may be a savour of life to your life, and a testimony in you of my innocent death,
etc.

[.signed-section-signature]
William Leddra

--

The next day after the writing of this letter,
the unrighteous sentence pronounced against him was
put in execution in the following manner.
First a morning lecture was appointed,
in which the priest animated the magistrates to the execution of the intended tragedy.
Although I pay a regard to a sincere religious disposition under every profession,
yet I feel something exceeding disgusting, and even mocking,
at cloaking cruelty and injustice under the mask of sanctity,
and bringing in a shew of religion in aid of a conduct which
violates the plainest laws of humanity and morality.
The people called Quakers were reputed and represented by these persecutors,
as being under strong delusions;
but what delusion could be more absurd or more mischievous, than to think we serve God,
by injuring, persecuting and slaying our fellow creatures.

Their pretended worship being over,
the governor with a guard of soldiers came to the prison,
the prisoner`'s irons were knocked off,
and after taking a solemn leave of his fellow-prisoners for the same testimony,
being called, he came forth undismayed,
and was immediately surrounded by the guard to prevent any of his
friends from coming near to speak to or accompany him.
Being come to the place of execution, as he was ascending the ladder,
he took his leave of his friend Edward Wharton, with this expression,
All that will be Christ`'s disciples, must take up the cross.
While he stood upon the ladder some person called out, William,
have you any thing to say to the people?
upon which he said,
for bearing my testimony for the Lord against the deceivers
and deceived am I brought here to suffer.

These expressions awakened the tender feelings and commiseration of many of the spectators,
which being observed by one Allen, a priest then present,
in order to prevent the effects of such impressions, he cried out, "`People,
I would not have you think it strange to see a man so willing to die,
for it is no new thing: and "`you may read how the Apostle saith,
that some shall be given up to strong delusions,
and even dare to die for it;`" though the text saith no such thing;
but the blind zeal of the man hurried him into a perversion of the scripture,
that he might harden the people`'s hearts against the innocent;
who standing as a man gathered up to God, and in peace with him,
as the executioner was putting the halter about his neck, meekly said,
I commend my righteous cause to thee, O God! and as the ladder was turning, he cried out,
Lord Jesus, receive my spirit.
Being dead, when the executioner cut him down, four of his friends, Edward Wharton,
Robert Harper, John Chamberlain, and Philip Verrin, caught his body in their arms,
and laid it on the ground, till the executioner had stripped his clothes off, who,
when he had done it, said he was a comely man, and that Mary Dyer was a comely woman,
and the others well ordered men according to their years.
His body being stripped, his said friends were suffered to put it into a coffin,
and bury it where they thought meet.
A piece of humanity owing not to the inclinations of the persecutors,
but to the outcry of the people against the barbarity used to the
dead bodies of the two men who were put to death before.

There was present at his execution one Thomas Wilkie, a stranger,
who was much affected with his case,
of which he wrote the following account in a letter to a friend of his at Barbados,
viz.

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Boston, March the 26th, 1661

On the 14th of this instant, here was one William Leddra put to death.
The people of the town told me he might go away if he would:
but when I made further inquiry, I heard the marshal say, he was chained in prison,
from the time he was condemned to the day of his execution.
I am not of his opinion; but yet truly methought the Lord did mightily appear in the man.
I went to one of the magistrates at Cambridge,
who had been of the jury that condemned him, and I asked him by what rule he did it?
He answered me, that he was a rogue, a very rogue.
But what is this to the question, I said, where is your rule?
He said, he had abused authority.
Then I went after the man, and asked him,
Whether he did not look on it as a breach of rule to undervalue authority?
I saw then, when the man was on the ladder, he looked on me, and called me friend,
and said, "`Know that this day I am to offer up my life for the witness of Jesus.`"
Then I desired leave of the officers to speak, and said, "`Gentlemen,
I am a stranger both to your persons and country, and yet a friend to both.`"
And I cried aloud for the Lord`'s sake, take not away the man`'s life,
but remember Gamaliel`'s counsel to the Jews: If this be of man it will come to nought;
but if it be of God, you cannot overthrow it;
but be careful ye be not found fighters against God.
And the captain said, "`why had you not come to the prison?`"
The reason was because I heard the man might go if he would,
and therefore I called him down from the tree, and said, "`come down, William,
you may go if will.`"
Then Capt.
Oliver said, "`It was no such matter,`" and asked, what had I to do with it?
and bid me be gone.
And I told them I was willing, for I could not endure to see this.
And when I was in the town, some did seem to sympathize with me in my grief,
but I told them, that they had no warrant from the word of God,
nor precedent from our country, nor power from his Majesty, to hang the man.

[.signed-section-context-close]
To Mr. Geo.
Lad, master of the America of Dartmouth, now at Barbados.

[.signed-section-closing]
Your Friend,

[.signed-section-signature]
Thomas Wilkie

--

At the same court which William Leddra was condemned to death, Edward Wharton,
who had been imprisoned near a year, was brought before their tribunal, where,
when he appeared,
he very reasonably demanded the cause wherefore he was forced from his habitation,
while he was honestly following his lawful occupation, and here laid up as an evil-doer?
For which they had no better reason to assign than that his hair was too long,
and that he had disobeyed that commandment, which saith, honour thy father and mother;
which they by a violent misconstruction applied to
his not taking off his hat to the magistrates,
to which he replied, "`I love and honour all magistrates and rulers,
who are for the punishment of evil doers, and the praise of them that do well.`"
Then secretary Rawson called out, Edward Wharton come to the bar.

[.discourse-part]
_Edward Wharton._
Yea, and to the bench too, for thou hast no evil to lay to my charge.

[.discourse-part]
_Secretary._
Hold up your hand.

[.discourse-part]
_Edw. Wharton._
I will not, thou hast no evil to charge me with.

[.discourse-part]
_Secretary._
Edward Wharton, hear your sentence of banishment.

[.discourse-part]
_Edw. Wharton._
Have a care what you do, for if you murder me, my blood will lie heavy upon you.

[.discourse-part]
_Secretary._
Edward Wharton attend to your sentence of banishment:
You are upon pain of death to depart this jurisdiction,
it being the 11th of this instant March, by the one and twentieth of the same,
on the pain of death.

[.discourse-part]
_Edw. Wharton._
I am a single man, and I have dealings with some people;
it were good I had time to make clear with all, and then if you have power to murder me,
you may.

[.offset]
Then the governor and secretary laid their heads together.

[.discourse-part]
_Governor._
If we should give him a hundred days, it is all one.

[.discourse-part]
_Edw. Wharton._
Nay, I shall not go away, therefore be careful what you do.

Then addressing the people assembled in the court, he spoke audibly as followeth, viz.

"`All people, take notice, what horrible, wicked and unjust men these are;
for after they had unrighteously taken me from my house, where,
when the constable came in, I was following my honest calling in the fear of the Lord,
he forced me out, and led me along the country like some evil-doer,
to the governor`'s house, where I asked the governor what he had to charge me withal?
who said, you shall know hereafter.
And now, they have kept me almost a year close prisoner, night and day,
they have banished me on pain of death, and, for ought I know, they will murder me;
and yet they have nothing to charge me withal, but my hat and my hair.`"

Upon this Rawson the secretary, taking the book of records, read to the people,
how that contrary to law,
Edward Wharton had travelled up and down with W. Robinson and Marmaduke Stevenson.
To which Edward replied, "`What readest thou that for?
have you not plowed furrows on my back for that already, although you had no law for it?`"
For he had been cruelly whipped in 1659,
and fined 20£. for travelling in company with the said sufferers.

Edward was then threatened, and commanded to quit the court, which he did; but,
as he told them, continued in their jurisdiction,
and publicly attended the execution of William Leddra.
Which the persecuting priests and magistrates now thought best to overlook, finding,
that the more they condemned, the more the bloody work grew on their hands;
and that they had the further mortification to perceive that the
past executions had exposed them to severe censure and infamy,
with candid and unprejudiced minds in a general way.
Therefore the fierceness of their rage being in some measure damped thereby,
they were induced, though reluctantly, from these and other considerations,
to proceed more cautiously in enforcing their sanguinary law.
With the first three that suffered under it they used very little ceremony,
or form of trial,
but as far as appears condemned them to death almost as soon as brought to the bar,
without much apology or prefatory introduction to their sentence.
Nor did William Leddra meet with much better treatment;
yet he was allowed some semblance of a trial, but without a jury,
and some liberty to speak for himself (a privilege arbitrarily refused
to the former) and still greater liberty of vindicating his cause,
was permitted Wenlock Christison, the last who was tried for his life,
upon their act for banishment, on pain of death, and who,
with fortitude founded upon conscious integrity,
bravely maintained his cause and his innocence,
and clearly exposed the arbitrary measures of these persecutors;
undismayed at their menaces, and at the prospect of losing his life under their hands,
as his brethren had done, he steadfastly defended himself against power without right,
and with sound reasoning pleaded his cause, to the conviction of the audience,
and even some of his judges, in his favour:
so that although the intemperate governor in his passion condemned him to death, he,
and his associates, were discouraged by the current of popular odium,
or fear of the consequence, from putting the sentence in execution.

It was at the time, when they were passing sentence of death on William Leddra,
that Wenlock Christison, who had been also banished on pain of death,
not only returned to Boston, as with his life in his hand,
but came openly into the court.
His appearance there at that time struck the court with a sudden damp and dismay,
so that for some time there was a general silence.
But after a while recovering themselves, they ordered him to be brought to the bar;
when the marshal bade him pull off his hat, which he refused,
and a short dialogue ensued, as followeth:

[.discourse-part]
_Secretary Rawson._
Is not your name Wenlock Christison?

[.discourse-part]
_Wenlock._
Yes.

[.discourse-part]
_Endicot._
Wast not thou banished upon pain of death?

[.discourse-part]
_Wenlock._
Yea, I was.

[.discourse-part]
_Endicot._
What doest thou here then?

[.discourse-part]
_Wenlock._
I am come to warn you that you should shed no more innocent blood:
for the blood you have shed already cries to the Lord for vengeance.

Whereupon the governor ordered him into custody.
On the day that William Leddra was executed, the court sat again,
and thinking to terrify Wenlock by the example of William`'s death,
had him brought into court,
where both the governor Endicot and deputy Bellingham endeavoured, but in vain,
to daunt the valiant confessor with dreadful menaces, telling him,
that except he would renounce his religion, he should surely die.
But he, without the least hesitation, answered them, Nay, I shall not change my religion,
nor seek to save my life; neither do I in tend to deny my master,
but if I lose my life for Christ`'s sake, and the preaching of the gospel,
I shall save it.
This undaunted reply put a stop to their further procedure at present;
so they sent him back to prison, to be kept close prisoner till the next court,
which was to be held the latter end of the third month,
and the beginning of the fourth month succeeding;
at which he was again brought to the bar and put upon his trial.

The first question put to him by the governor was, What he had to say for himself,
why he should not die?

[.discourse-part]
_Wenlock._
I have done nothing worthy of death: if I had, I refuse not to die.

[.discourse-part]
_Governor._
Thou art come in among us in rebellion, which is as the sin of witchcraft,
and ought to be punished.

[.discourse-part]
_Wenlock._
I came not in among you in rebellion, but in obedience to the God of heaven;
not in contempt to any one of you, but in love to your souls and bodies;
and that you shall know one day,
when you and all men must give an account of the deeds done in the body.
Take heed, for you cannot escape the c righteous judgments of God.

[.discourse-part]
_Major-general Adderton._
You pronounce woes and judgments,
and those that are gone before you pronounced woes and judgments;
but the judgments of the Lord are not come upon us yet.

[.discourse-part]
_Wenlock._
Be not proud, neither let your spirits be lifted up;
God doth but wait till the measure of your iniquity be filled up,
and that you have run your ungodly race,
then the wrath of God come upon you to the uttermost.
And as for thy part, it hangs over thy head, and is near to be poured down upon thee,
and shall come as a thief in the night suddenly, when thou thinkest not of it.^
footnote:[It is very remarkable that some time after,
this officer who did thus in a manner bid defiance to heaven,
having been on a certain day exercising the soldiers with much ostentation,
as he was returning home in the evening,
near the place where they usually loosed the Quakers
from the cart after they had whipped them,
his horse suddenly affrighted threw him with such
violence that he instantly died a shocking spectacle,
his eyes being dashed out of his head, his brains forced out at his nose,
and the blood running out of his ears: Being taken up, and brought into the court-house,
where he had been active in sentencing innocent people to death,
his blood ran through the floor,
exhibiting to the spectators an affecting instance
of divine punishment of a daring and hardened persecutor,
made a frightful example of that judgment, which when warned of,
he had openly despised and treated with disdain, and which, as foretold,
overtook him as a thief in the night.]
By what law will you put me to death?

[.discourse-part]
_Court._
We have a law, and by our law, you are to die.

[.discourse-part]
_Wenlock._
So said the Jews of Christ, We have a law, and by our law he ought to die:
Who empowered you to make that law?

[.discourse-part]
_Court._
We have a patent and are patentees, judge whether we have not power to make laws?

[.discourse-part]
_Wenlock._
How! have you power to make laws repugnant to the laws of England?

[.discourse-part]
_Governor._
Nay.

[.discourse-part]
_Wenlock._
Then you are gone beyond your bounds, and have forfeited your patent,
and this is more than you can answer.
Are you subjects to the King, yea or nay?

[.discourse-part]
_Secretary Rawson._
What will you infer from that, what good will that do you?

[.discourse-part]
_Wenlock._
If you are, say so; for in your petition to the King,
you desire that he will protect you,
and that you may be worthy to kneel among his loyal subjects.

[.discourse-part]
_Court._
Yes.

[.discourse-part]
_Wenlock._
So am I, and for any thing I know am as good as you, if not better:
for if the King did but know your hearts, as God knows them,
he would see that your hearts are as rotten towards him as they are towards God.
Therefore seeing that you and I are subjects to the King,
I demand to be tried by the laws of my own nation.

[.discourse-part]
_Court._
You shall be tried by a bench and jury.^
footnote:[Those who had been condemned to death before him were deprived of this privilege;
but the government of England being changed by the King`'s restoration,
they began to be afraid to go on in the former course,
of condemning without a trial by jury,
as being subversive of the fundamental laws of England, and rights of Englishman.]

[.discourse-part]
_Wenlock._
That is not the law, but the manner of it; for if you will be as good as your word,
you must set me at liberty,
for I never heard or read of any law that was in England to hang Quakers.

[.discourse-part]
_Governor._
There is a law to hang Jesuits.

[.discourse-part]
_Wenlock._
If you put me to death, it is not be cause I go under the name of a Jesuit, but a Quaker,
therefore I appeal to the laws of my own nation.

[.discourse-part]
_Court._
You are in our hands and have broken our laws, and we will try you.

[.discourse-part]
_Wenlock._
Your will is your law, and what you have power to do, that you will do:
and seeing that the jury must go forth on my life,
this I have to say to you in the fear of the living God:
Jury, take heed what you do, for you swear by the living God,
that you will true trial make, and just verdict give, according to the evidence.
Jury, look for your evidence: what have I done to deserve death?
Keep your hands out of innocent blood.`'
This one of the jurymen acknowledged to be good counsel, yet the generality,
either prejudiced in their minds, or afraid of the displea sure of the court,
from which they had received their lesson, soon brought him in guilty.
Wenlock then said, I deny all guilt, for my conscience is clear in the sight of God.

[.discourse-part]
_Governor._
The jury hath condemned thee.

[.discourse-part]
_Wenlock._
The Lord doth justify me, who art thou that condemnest?

Then the court proceeded to vote as to the sentence of death,
to which several of them divided, would not consent,
being by his steadfastness in manifesting his innocence,
and the iniquity of their unsanctioned law,
convinced in their consciences that he had done nothing worthy of death.
This dissent provoked the governor to that unseemly degree, that in a rage,
throwing something down on the table, he cried, '`I could find in my heart to go home.`'

To which Wenlock replied, '`It were better for thee to be at home than here,
for thou art about a bloody piece of work.`'

[.discourse-part]
_Governor._
You that will not consent record it.
I thank God, I am not afraid to give judgment.
Wenlock Christison, hearken to your sentence:
You must return to the place from whence you came,
and from thence to the place of execution,
and there you must be hanged until you be dead, dead, dead, upon the 13th day of June,
being the fifth day of the week.

[.discourse-part]
_Wenlock._
The will of the Lord be done.
In whose will I came amongst you, and in whose counsel I stand,
feeling his eternal power, that will uphold me to the last gasp, I do not question it:
known be it to you all, that if you have power to take my life from me,
my soul shall enter into everlasting rest and peace with God,
where you yourselves shall never come: and if you have power to take my life from me,
the which I do question, I believe, you shall never more take Quakers lives from them.
Note my words.
Do not think to weary out the living God by taking away the lives of his servants:
what do you gain by it?
For the last man you put to death here are five come in his room.
And if you have power to take my life from me,
God can raise up the same principle of life in ten of his servants,
and send them among you in my room, that you may have torment upon torment,
which is your portion: for there is no peace to the wicked, saith my God.

[.discourse-part]
_Governor._
Take him away.

The holy confidence with which this concluding speech of Wenlock`'s was uttered,
considered with the sequel, seem sufficient to authorize the opinion,
that a supernatural influence suggested it,
notwithstanding the prevailing notion amongst the learned of this
world that all pretensions to inspiration are enthusiastic;
the scripture informs us that great men are not always wise,
neither do the aged understand judgment; but there is a spirit in man,
and the inspiration of the Almighty giveth them understanding.

According to the governor`'s order, Christison was taken back to prison,
where he continued in faith and patience, resigned to the will of God,
and to suffer death for the testimony of a good conscience.
But before the day appointed for his execution,
an order of court was issued for the enlargement of him,
and twenty seven others then in prison for their christian testimony.

When the marshal and constable came to set them at liberty,
they informed them it was in consequenqe of a new law:^
footnote:[This new law was for banishing them, and if they returned,
whipping them from town to town out of their jurisdiction.]
upon which Wenlock remarked that "`It was thought the gallows had been their last weapon,
that their magistrates had alleged that their law was a good and wholesome law,
made for their peace, and the safe-guard of their country,`" adding,
"`what! are your hands weakened?
the power of God is over you all`" The prison doors being set open,
the prisoners were by appointment of the court, by a guard armed with swords,
driven out of the jurisdiction into the wilderness-country, and there left.

This cessation of sanguinary proceedings, by the subsequent,
plainly appears not to be owing to any tenderness,
or recovery to a better mind in the persecutors;
but partly to the general odium and outcry of the more rational
and moderate part on both sides the Atlantic,
against their putting men to death for religion, whilst themselves and their party,
were not only stigmatizing, with every opprobrious epithet, that hierarchy,
from whom they had experienced far less severity; but had recourse to arms,
or to flight to get the power into their own hands, and abuse it,
even in a superior degree; yet chiefly, I apprehend,
owing to the change of government in England.
From the king and ministry, betwixt whom and them there was no cordiality,
they had no reason to expect any partiality in their favour,
and being convicted in their consciences,
that they had transgressed the bounds of their authority,
and the limitations of their charter,
fearfulness of being called to account at this time,
when their party had lost the power of screening them,
was I believe the most prevalent reason with them to drop
the execution of their illiberal and persecuting law;
but the spirit of malevolence and persecution continued to actuate them still.^
footnote:[In Thomas Chalkley`'s [.book-title]#Journal,# in his travels in New- England, in 1693,
we meet with the following passage,
"`I being a stranger and a traveller could not but observe
the barbarous and unchristian welcome I had into Boston,
the metropolis of New England, Oh what a pity,
said one that all your society were not hanged with the other four!`"
This shews that the spirit of persecution was alive in some of that people,
long after the power of gratifying it was restrained.
Besse.]
In imitation of their brethren here, they called the Quakers vagabonds,
and made a law to whip them as such through every town in their way out of their jurisdiction;
of the severe execution of this law,
we shall see many affecting instances in the succeeding parts of this history,
and that they finally ceased not their inhuman severities until the principal agents
were arrested to appear in judgment before an higher tribunal than theirs.

When the tidings of these severe executions reached their friends in England,
from the impulse of that fraternal sympathy and affection, chap.
which made them nearly feel for and with each other in their afflictions,
they thought it their duty to make immediate application to the king.
For this purpose Edward Burrough, who had on many former occasions,
solicited for the relief of his friends,
when under sufferings in the various changes of government, repaired to court,
to repeat his solicitations on behalf of the sufferers in New-England;
and having obtained access to the King`'s presence, informed him,
there was a vein of innocent blood opened in his dominions,
which if it were not stopped might over-run all: to which the king replied,
I will stop that vein.
It seems the king was predisposed to stop their career by a previous information
of their proceedings and disposition from George Bishop`'s book,
containing a narrative of the cruel persecution in New England,
wherein reading a passage of Major General Dennison`'s reply to
some that threatened to complain of their illegal proceedings,
which was this; this year you will go to complain to the parliament,
and the next year they will send to see how it is;
and the third year the government is changed: This passage immediately struck him,
so that calling to some of the lords to hear it, he said, "`Lo,
these are my good subjects of New-England, but I will put a stop to them.`"
The king being hereby prepossessed against them,
readily complied with Edward Burrough`'s solicitations,
who mandamus representing the case as urgent,
as not knowing how many more might suffer death, in case of delay,
he immediately gave orders to the secretary of state
to prepare a mandamus to stop their proceedings,
which being soon drawn and perfected, the king at the instance of Edward in- Burrough,
granted a deputation to Samuel Shattock, an inhabitant of New England,
and under sentence of banishment on pain of death, to carry over the mandamus,
a copy whereof followeth, viz.

[.embedded-content-document.legal]
--

[.letter-heading]
Charles R.

Trusty and well beloved, we greet you well.
having been informed, that several of our subjects amongst you, called Quakers,
have been and are imprisoned by you, whereof some have been executed,
and others (as hath been represented unto us) are in danger to undergo the like;
we have thought fit to signify our pleasure in that behalf for the future:
And do hereby require, that if there be any of those people called Quakers amongst you,
now already condemned to suffer death, or other corporal punishment;
or that are imprisoned, and obnoxious to the like condemnation,
you are to forbear to proceed any further therein;
but that you forthwith send the said persons (whether condemned
or imprisoned) over into their own kingdom of England,
together with their respective crimes or offences laid to their charge:
To the end such course may be taken with them here,
as shall be agreeable to our laws and their demerits.
And for so doing, these our letters shall be your sufficient warrant and discharge.

Given at our court at Whitehall, the 9th day of September, 1660,
in the thirteenth year of our reign.

Subscribed: To our trusty and well beloved John Endicot, Esq;
and to all and every other the governor or governors of our Plantations of New England,
and of all the Colonies thereunto belonging, that now are, or hereafter shall be;
and to all and every the ministers and officers of our Plantations and Colonies whatsoever,
within the continent of New England.

[.signed-section-closing]
By his Majesty`'s command,

[.signed-section-signature]
William Morris

--

In order to lose no time in expediting a matter of such consequence, Ralph Goldsmith,
a ship commander of a good ship, and one of their own society,
was engaged for three hundred pounds to sail in ten days,
who immediately prerparing and sailing accordingly, arrived at Boston in about six weeks.
On their arrival in the harbour,
some of the citizens coming on board to look for letters (which
would not be delivered that day) at their return on shore,
reported that the ship was full of Quakers, and amongst them was Shattock,
who was under sentence of banishment on pain of death;
but of his errand and authority they were ignorant.

Next morning Samuel Shattock went on shore, accompanied only by the master of the ship,
and going directly to the governor`'s house,
produced his commission with the King`'s mandamus to the governor,
who after the perusal thereof, and consulting the deputy governor, The man said,
We shall obey his Majejsty`'s command.
After this the passengers came ashore,
and had a religious meeting with their friends in the town,
to return thanksgivings to the God and Father of all their mercies,
for his signal mercy manifest in this admirable deliverance.
Not long after, the following order of the court at Boston was issued.

[.embedded-content-document.legal]
--

[.letter-heading]
To William Salter, keeper of the prison at Boston.

You are required, by authority and order of the general court,
to release and discharge the Quakers, who at present are in your custody:
See that you do not neglect this,

[.signed-section-closing]
By order of the court,

[.signed-section-signature]
Eward Rawson, Sec.

[.signed-section-context-close]
Boston, 9th Dec.
1661.

--
