== Chapter IV.

[.chapter-synopsis]
* The Rulers of New England send a Deputation to the King with an Address of Congratulation, and Accusation of the Quakers
* Interview between some of the People called Quakers and the New England Deputies
* The Deputies, being alarmed, returned home
* Act against the Quakers brought into the House of Commons
* Friends of London use endeavours to get it stopped
* Edward Burrough replies to the suggestion of danger to the public Peace
* Richard Hubberthorn to the danger of Insurrections from their Meetings
* George Whitehead to their Meetings being termed unlawful
* They assert their Right to the Benefit of the King`'s Declaration from Breda
* The Bill passed

The rulers of the province of New England, during the time of the Commonwealth,
and the succeeding revolutions of government in England,
seem to have considered themselves as independents in state, as well as church,
and we see had acted accordingly; making violent and arbitrary laws,
without paying any regard to the restrictions of their charter,
and executing them in as arbitrary a manner;
looking upon the power as established in their own hands there,
and those of their own party on this side, they would admit of no appeal to England,
while they had nothing to fear from England:

But after the king`'s restoration the case was altered,
and then they seemed to be really armed with fear of the
consequences of the undue exertion of unlicensed authority,
and their refusing to acknowledge the supremacy of England,
in refusing appeals for trial by its laws:
In order to avert the danger and ill consequences of their misrule,
they concluded to send a deputation to the king.
Colonel Temple was previously sent to acquaint him that
in submission to his commands the Quakers were set at liberty;
and not long after he was followed by Simon Broadstreet,
secretary of the Massachusetts colony, and John Norton, chief priest of Boston,
with an address of congratulation to the king on his accession to the throne.
This address introduced in a style of abject servility,
proceeds to apologize for the unlicensed severities against the Quakers,
by a most virulent and false accusation of them,
as a people not fit to live on the earth; and,
as if the king had not a better opportunity of knowing
their principles and practice in England,
where the body of them resided, they tell the king,
"`That the Quakers were open capital blasphemers;^
footnote:[This declamatory abuse proves nothing but that the penmen
were versed in bearing false witness and calling names,
and that their implacability to the Quakers retained its full strength
after their hands were tied up from putting them to death.]
open seducers from the glorious Trinity, the Lord Christ,
and from the scriptures as the rule of life; open enemies to government itself,^
footnote:[_Turpe eft doctori cum culpa redarguit ipsum._
This again is not only mere declamation without proof, but the most groundless assertion,
and most diametrically opposite to their real character, that could be imagined,
to which a series of conduct from their first rise had given the lie.
Men that by principle had been always submissive
to every government under which they lived;
sought after neither the emoluments, the honours,
nor the power of the kingdoms of this world,
but simply for protection in their religious and civil rights, were not,
nor could be either open or secret enemies to government;
neither did they ever discover even a wish to have the secular government in their hands.
But here they measure the Quakers by their own rule of action, having,
in purple characters, manifested themselves enemies to every government,
but in their own hands,
and stopped neither at deceitful nor violent measures to seize and retain it in them.]
established in the hands of any but men of their own principles;
malignant promoters of doctrines directly tending to subvert both
our church and state.--That after all other means used in vain,
they were at last constrained, for their own safety,
to pass sentence of banishment on pain of death.`"

After this notable apology for persecution,
and depriving their fellow-subjects of their civil and religious rights, their property,
liberty and lives,
they proceed to supplicate the king for his protection in
the continuance of their religious and civil liberties,
acquainting him, that for liberty to walk in the way of the gospel,
with all good conscience, they had chosen the wilderness, to which they removed,
before the pleasant land they had left behind,
rather than submit to the impositions of the then prevailing hierarchy,
which they could not do, without an evil conscience.
Who could imagine that these tender conscienced men,
should so soon lay aside all regard to the tender consciences of others,
all remains of tenderness and common humanity?
That voluntary exiles for religious liberty,
should almost immediately forget the value of it so far,
as to refuse the enjoyment thereof to all but themselves;
that those who could not submit to the impositions of the hierarchy,
without an evil conscience,
should surpass that hierarchy in the cruelty of punishing such
as would not violate their consciences in submitting to them;
or that any men should be so inconsistent as to justify
and deprecate persecution in the same address.

Whilst these New England deputies were in London, the Quakers, so called there,
had several interviews with them upon the subject of the putting their friends to death;
in which they endeavoured to palliate their proceedings,
and disguise the cruelty in which they were both deeply concerned: Norton,
who had been the principal promoter of all their sanguinary laws,
excused himself by saying he did not assist at the trial of those who were put to death,
nor had advised it; but John Copeland,
who had suffered the amputation of his ear at Boston, charged the contrary upon him.
Broadstreet could not help owning his being a party in condemning them to death;
and being, with his associates,
interrogated whether they would acknowledge themselves subject to the laws of England,
they answered in the affirmative: Being asked by what law they did it?
They replied, by the same law that Jesuits were put to death in England.
George Fox, upon this, demanded of them,
whether they believed that his friends whom they had executed were Jesuits,
or jesuitically inclined; they answered, Nay.
Then said he, ye have murdered them,
for it plainly appears you have put them to death arbitrarily without any law.
Upon which Broadstreet insinuated their aim was to ensnare them.
But George Fox observed they had caught themselves;
and if the father of William Robinson (who was not of their persuasion) were in town,
it was probable he would question them, and bring their lives into jeopardy.
And some of the royalists were earnest with the Quakers to prosecute them as
murderers of the king`'s subjects without any law or authority from him.
But their security lay in the pacific and forbearing
principles of those whom they had persecuted,
whereby they were directed not to avenge themselves,
but commit their cause to the righteous judge,
who will render to every man according to his works.

However, these deputies being alarmed, and fearing the danger of staying in England,
thought it safest to secure themselves by a precipitate retreat, and return home,
where it seems they met with a cool reception.

What they had in commission, besides delivering the address,
I meet with no clear account;
but Neale informs us the country was not satisfied with their conduct, he adds,
"`Whether they flattered the court too much,
or promised more for their country than they ought is uncertain;
but when Norton came home, his friends were shy of him,
and some of the people told him to his face that he had
laid the foundation of the ruin of their liberties,
which struck him to the heart, and brought him into such a melancholy habit of body,
as hastened his death.`"^
footnote:[His death was very sudden;
having been at his worship in the forepart of the day,
and intending to go thither again in the afternoon,
as he was walking in his own house he was observed to fetch a great groan;
and leaning his head against the chimney piece was heard to say, The hand,
or judgment of the Lord is upon me, and so sunk down, and spoke no more,
and had fallen into the fire, if an ancient man present had not prevented it.
He having been a principal instigator of the magistrates
to all their severe persecution of this innocent people,
even to put them to death,
it was natural for them to consider the manner of his death as a judgment upon him,
and to rank him with several others who had been
active promoters of cruelty against them,
many of whom died not a natural death, but were either cut off by a sudden stroke,
or died with disagreeable and loathsome symptoms about them.
Neale says, "`This reflection of the Quakers (upon Norton`'s death) is very unjust,
it being impossible for us to distinguish between a natural and judicial death;
yet I heartily wish that neither he nor any body else, by their unchristian severities,
had given them occasion to make it.`"]
William Sewel informs us that this Norton bowed to the
archbishop with no less reverence than to the king;
that by fawning upon the church party (whom they hated) they found
means to reserve a power to be vexatious to the Quakers so called,
although they were prohibited from putting them to death:
That many of the bishops and others entertained inimical dispositions to this society,
the severe persecutions soon after raised against them evidently demonstrate.

For they and their partisans at court and in parliament having now the ascendancy,
after excluding the Presbyterians from all offices
of trust or emolument in church or state,
proceeded to punish the Quakers, who affected neither,
nor had administered any just occasion of offence,
merely on account of their religious scruples and way of worship.
For this purpose a bill was brought into parliament,
entitled An act for preventing mischiefs and dangers,
that may arise from certain persons called Quakers, and others,
refusing to take lawful oaths.

Although the title of the bill mentions only the refusal to take oaths;
yet the bill itself takes in their religious assemblies,
enacting that if five or more Quakers of sixteen years of age or
upwards assemble under pretence of joining in religious worship,
as well as refusing to take an oath,
the party offending shall forfeit for the first offence a sum not exceeding five pounds,
or suffer three months imprisonment, for the second offence the penalty to be doubled,
and for the third they were to abjure the realm or be transported.

Some of this society in London getting early intelligence of this bill,
and the contents thereof,
thought their duty to themselves and their brethren demanded
their intercession with the parliament to stop its progress.
Edward Burrough, Richard Hubberthorn,
and George Whitehead attended the parliament to solicit
against passing the bill into an act:
When it was committed, they attended the committee sundry times;
but their solicitations were not followed with the like success
as Edward Burrough`'s late application to the king had been.
They were again admitted to give their reasons against the act, at the bar of the house.
But political considerations, party animosity,
and bigoted and exasperated zeal for the Church (so called)
were the moving causes of action with the majority:
Appeals to their reason and humanity were vain:
A resolution determined upon these motives deafened their
ears to the clearest arguments addressed to the one,
and deadened their hearts to the feelings of the other.
Their admission of these Quakers to plead their cause seems no more than matter of form,
and to save appearances;
for if they had not been predetermined to pass the bill at all events,
the weakness and futility of the charges brought in support thereof,
and the urgent reasons advanced against it,
appear sufficient to influence any rational and unprejudiced
body of men to lay it aside.

Their sentiments respecting oaths had been lately presented
to the king and council in writing by Edward Burrough,
in a paper he entitled a just and righteous plea,
wherein he exhibited at large the reasons why the
people called Quakers refused oaths in general,
and particularly the oath of allegiance;
that it was not from any disrespect or unfaithfulness to the king and his government,
but merely for conscience-sake, being afraid of disobeying Christ`'s command,
which was express and determinate swear not at all: That they are and shall be faithful,
innocent and peaceable in their respective stations and conditions,
under the government of king Charles II. whom they acknowledge
supreme magistrate and governor over this kingdom,
and are conscientiously obedient to him in all his commands,
either by doing what he justly requireth,
or patiently suffering whatever is inflicted upon them,
when anything is required which they apprehend inconsistent with the just law of God.
That it had ever been with them an established religious principle,
confirmed by a consonant practice, to enter into no plots,
combinations or rebellions against government,
nor to seek deliverance from injustice or oppression by any such means.

Having thus lately presented to the government their reasons for declining oaths;
their remonstrances to the parliament were principally confined to their religious meetings:
In the preamble to the bill it was recited that their meetings
were to the great endangering of the public peace and safety,
and to the terror of the people; this they denied,
Edward Burrough alledging they were in nowise to the terror of the people,
but peaceable and harmless, and purely for the worship of God in that manner and form,
which by his law in their hearts, they were persuaded he required of them;
that in this respect they endeavoured to copy after the example of the primitive christians;
that being convinced of the necessity of preserving a good
conscience inviolate and void of offence to God or man,
no human law or ordinance could dissolve the obligation
of the superior law of God in their consciences,
or exculpate them in disobeying thereof;
and that as the worship of God was an indispensable duty required by this law,
they could not refrain keeping up their meetings for that purpose,
whatever sufferings human laws might subject them to on that account; because if,
through fear of man, they should neglect this reasonable service of their maker,
they thereby violate this divine law in their consciences, and that peace of mind,
which they preferred to every temporary enjoyment; that, therefore,
they presume they ought not to pass a bill of this nature,
it being contrary to the law of God.

It being also suggested in the said preamble that being numerous
and holding a strict correspondence amongst themselves,
their meetings might be more dangerous to contrive and cause insurrections, etc.

To this Richard Hubberthorn made answer to this purport.
That there could be no such danger in their meetings as was implied,
because being public, and open for the reception of all persons,
who chose to resort to them, to see and hear all that was transacted therein,
there was no probability that they should plot or
contrive insurrections in the face of the world;
that the reducing of their meetings to the number of four or five, besides the family,
appeared to be a measure not calculated for the preventing of such pernicious designs,
if they were a people of such bad principles (which they were not) but
rather to furnish more convenient opportunities for promoting them,
for it would not break their correspondence,
but afford them the means of carrying it on more privately,
and in a manner better accommodated for forming and advancing a plot:
Wherefore it appeared more prudent and eligible to suffer their meetings to be public,
as they were, rather than to punish a numerous body of people,
on causeless suspicion of danger, supported by no matter of fact,
or the least occasion administered by them.

One of the members, called Sir John Goodrick,
being liberal in his invectives and commonplace calumnies against them and their meetings,
terming them unlawful or contrary to law,
and tending to seduce the people from the church;

George Whitehead replied to him, that if their meetings were contrary to law,
it implied to there exists some law already to which they are contrary;
and if there be a law already in force against them,
it seems quite superfluous and unnecessary for you to make a new one: But, we trust,
no such thing can be proved against us, as that our meetings, properly speaking,
are in themselves unlawful, being in obedience to the Lord, only for his worship,
and agreeable to the practice of the primitive christians,
and therefore not unlawful in the proper sense of the word.
He also observed, that if they suffered for keeping them up, under persuasion of duty,
they should suffer for the cause of God,
and so commit their cause to him who would judge
righteously between them and their persecutors,
exhorting the house to act in his fear; for they might as well make a law,
that the Quakers (so called) should not pray in the name of Jesus Christ,
as one that they should not assemble for divine worship,
which they dared no more to refrain, than Daniel did to pray to the true God,
although it was contrary to king Darius`'s decree.

He desired them to consider what guilt and disrepute they might bring upon themselves,
by making a law,
the execution whereof must produce grievous sufferings upon thousands
of innocent people in the nation (who in justice ought to be protected
by law) endanger the utter ruin of many families,
and the loss of many lives in prisons.

When mankind, from the illusions of party-heat,
come to recover found and dispassionate judgment,
what an indelible stain must it leave on the reputation or memory of those,
who deaf to every sentiment of justice and compassion,
could be instrumental to the oppression of an innocent
people! against whom no matter of fact,
or crime worthy of suffering, could be proved, or justly laid to their charge.

He observed further, that if the bill before them was passed into a law,
it would give encouragement to wicked,
rude and lawless persons to abuse them beyond the law,
as they had lately done upon the King`'s proclamation;
when several of their friends were by rude fellows taken out of their beds;
poor men dragged from their lawful employments, and their poor families,
whose subsistence depended on their daily labour;
others seized travelling about their lawful occasions on the King`'s highway,
and all hurried to prison illegally, without warrant, or authority,
even from the proclamation.
Therefore, in case the intended act was passed,
they had reason to apprehend the repetition of these abuses to a greater degree;
as such rude and unprincipled persons would look upon it as a licence,
to gratify their malicious dispositions with all
kinds of cruelty and injurious treatment of them.

Finally,
they assert their right to the indulgence to tender consciences
upon the King`'s solemn promise in his declaration,
that no man shall be called to account for differences of opinion in matter of religion,
which do not disturb the peace of the kingdom.
That their demeanour having been peaceable, inoffensive to their neighbours,
and submissive to the government,
they were within the description of those who were entitled to the indulgence;
and having never forfeited their right thereto,
they could not be restrained in matters of worship and conscience towards God,
without wounding the King`'s honour, and violating the public faith.

Conclusive as these arguments were,
although they had an effect upon several of the members,
so that they appeared serious and sober in their carriage towards the appellants,
and some of them owned, what they advanced was very reasonable,
and if the members had feared God, or regarded equity,
they would not have passed the act;
and although supported by the abilities of Edmund Waller,
(distinguished for his poetical performances) in
a candid and liberal speech on the occasion;
as also by Michael Mallet, Sir John Vaughan and others;
yet they were ineffectual with the majority of the house, composed of courtiers,
pensioners to the crown, and bigots to episcopal authority,
with whom the dictates of the court,
and the imagined interests and power of the episcopal church preponderated,
against reason, right and justice, so that the bill was passed into a law;
in consequence whereof, great persecutions and imprisonments ensued.
