== Chapter V.

[.chapter-synopsis]
* Account of Imprisonments
* Steadfastness of the People called Quakers
* Modelling the Magistracy in consequence of the Corporation Act
* Disposition of the Judges
* The People called Quakers the greatest Sufferers
* Conjectural Inquiry into the Causes. 1+++.+++ Their pacific Principles. 2+++.+++ Their Constancy in keeping up their Meetings openly. 3+++.+++ Their Plain-dealing
* Richard Brown`'s Proceedings
* Account of John Perrot
* Commencement of the Execution of the late Act
* Rude and illegal Behaviour of Philip Millar
* Trial of John Crook and others
* They are not prosecuted by the late Act; but by the 3rd. James I. for declining the Oath of Allegiance
* Third Day`'s Trial
* The first Jury discharged, and a new one picked for the Trial
* The Prisoners move for Time to traverse the Indictment, which is refused
* The Jury sworn and Evidence given out of the Hearing of the Prisoners
* Sentence of Premunire passed upon them
* Reflection on the Hardships attending the Society, and their Constancy
* Several others run to a Premunire for not swearing
* Robert Smith, Thomas Stordy, and Stephen Pearson, John King and others, Ambrose Rigge, Thomas Goodyear, and Benjamin Staples

Amongst the great number imprisoned upon this act were the
three before-mentioned advocates against the law,
Edward Burrough, Richard Hubberthorn and George Whitehead, the two former of whom,
with many others, finished their testimony to the truth,
by laying down their lives in prison for the conscientious discharge of their duty,
in obeying God in contradiction to the ordinances of men.
The sincerity of the members of this society was put to a severe test,
by the multiplied calamities that befell them by this and other persecuting laws,
of which this parliament are reckoned to have made more than any other since the reformation;
but the unwearied patience and fortitude with which they bore their sufferings,
to the loss of the substance, liberty and lives of many,
is an irrefragable proof of their integrity;
and that they were sustained by divine support,
to bear hardships above the power of mere humanity to endure, with a firmness,
which the persevering cruelty of their persecutors could not overcome; heartily disposed,
above all things, to please their Maker, and having an eye to the recompense of reward,
they were enabled, in the steady pursuit of future happiness,
patiently to endure the afflictions permitted to
befall them in their pilgrimage on earth.

In pursuance of the corporation act,
the corporations had been modelled by commissioners appointed by the parliament,
and invested with an absolute authority to deprive every officer or magistrate,
who was not entirely devoted to the King and church of England, of their offices.
This power was exercised with the greatest rigour,
so that few or none were continued in the magistracy,
or put into commission in corporations or elsewhere,
who were not of the same principles with the majority of the house of commons,
and determined to execute the penal laws with severity.

Not only the justices and inferior magistrates were chosen from men of this partial cast;
but judges and other administrators of the law,
who ought to be strict dispenser of justice without respect to persons,
seem to have been selected to fill the benches,
more in consideration of a passionate spirit against non-conformists,
than that jurisprudence or that conscientious reverence to equity and legal justice,
which are the peculiar ornaments and peculiar qualifications of that important station,
to which the security of life, liberty, and estate is entrusted: it is manifest that,
on many occasions, they paid little regard to equity or decorum,
but discovered an intemperate party spirit,
and palpable partiality in the seat of judgment,
influencing the juries by undue means to bring in unjust verdicts,
menacing and fining them, when they were too conscientious to do so:
loading the prisoners with abusive reproaches,
and passing sentence upon them in an insulting and passionate temper.

Of this combination of inimical dispositions all
the classes of non-conformists felt the severe effects;
but the heaviest weight of sufferings fell upon the Quakers,
who had administered least occasion.
The reason why they were marked out in particular as objects of such unrelenting cruelty,
were probably these; first, their pacific principles,
which ought to have secured them protection from equal government,
might encourage such magistrates, as were at this time in authority,
to prosecute them with the utmost rigour of the law, and frequently beyond the law,
as apprehending no danger of being called to account by by them,
or as depending upon the protection of their superiors.

Secondly,
while other dissenters could temporize so far as to disguise and conceal themselves,
and hold their meetings clandestinely to escape the enacted penalties; the Quakers,
perfect strangers to dissimulation,
and undaunted in bearing up their public testimony against the iniquity of human laws,
prohibiting them from their conscientious duty of worshipping God,
in the way they were persuaded was most acceptable to him,
thought it base and dishonourable, as not confessing Christ before men,
to desert their religious meetings for fear of suffering: therefore they valiantly,
and often singly,
kept them up in the hottest time of persecution at the appointed times and places,
as believing no law of man could exempt them from the obligation
they were under to obey the law of God,
of which his worship, according to the conviction of their own consciences,
and not according to the prescriptions of men, was an especial part;
nor rescue them from his righteous judgment for the violation of known duty.
This their persecutors would needs consider as flying in the face of law and government,
and being greatly provoked at their constancy (which they termed obstinacy)
as baffling their scheme of totally subduing all the dissenting sects,
they exerted every effort of their malice, and their power,
to make them more compliant to their wills.

Thirdly, believing it their duty to promote righteousness in the earth,
and testify against sin and iniquity wherever or in whomsoever it appeared, as they had,
under the former government,
borne plain testimonies against the hypocrisy and
outside sanctity of the formal professors of religion,
so they honestly testified against the open profanity,
debauchery and contempt of all religion of this age.

We have two epistles to King Charles,
long before Robert Barclay`'s dedication of his apology, written by the two George Foxs;
the first from George Fox the elder, so called for distinction,
as the elder member of the society, written soon after the King`'s restoration,
and the other some time after, a copy of each whereof I insert,
as a specimen of the honest plain-dealing of men, who, with Elihu, knew not to flatter,
lest in so doing their maker should take them away.

[.embedded-content-document.letter]
--

[.letter-heading]
To the King

[.salutation]
King Charles,

Thou camest not into this nation by sword, nor by victory of war;
but by the power of the Lord: now if thou dost not live in it, thou wilt not prosper.
And if the Lord hath shewed thee mercy, and forgiven thee, and thou dost not shew mercy,
and forgive; the Lord God will not hear thy prayers, nor them that pray for thee.
And if thou do not stop persecution, and persecutors, and take away all laws,
that do hold up persecution about religion; but if thou do persist in them,
and uphold persecution; that will make thee as blind as them that have gone before thee.
For persecution hath always blinded those, that have gone into it:
and such God by his power overthrows, and doth his valiant acts upon;
and bringeth salvation to his oppressed ones.
And if thou dost bear the sword in vain, and let drunkenness, oaths, plays, may-games,
(with fiddlers, drums, trumpets,
to play at them) with such like abominations and vanities, be encouraged,
or go unpunished; as setting up of may-poles, with the image of the crown a top of them,
etc. the nations will quickly turn like Sodom and Gomorrah,
and be as bad as the old world; who grieved the Lord, till he overthrew them:
and so he will you, if these things be not suddenly prevented.
Hardly was there so much wickedness at liberty before now, as there is at this day;
as though there was no terror, nor sword of magistracy;
which doth not grace a government, nor is a praise to them that do well.
Our prayers are for them that are in authority; that under them we may live a godly life,
in which we have peace: and that we may not be brought into ungodliness by them.
So hear, and consider, and do good in thy time, whilst thou hast power; and be merciful,
and forgive; that is the way to overcome, and obtain the kingdom of Christ.

[.signed-section-signature]
George Fox

--

[.embedded-content-document.letter]
--

[.letter-heading]
Extract of an Epistle of George Fox the younger to King Charles II.

The King of Kings hath beheld all thy actings in the dark,
and he hath traced thy walking in obscure places;
and thou hast not hid thy counsels from the Almighty,
but he hath seen all the intents of thy heart, and thy good words have not deceived him,
nor those that purely stood in his counsel: For he hath seen the snares and the pits,
which have been privily preparing for the innocent,
even in the time when smooth words have been given.
Oh! that thou wouldest have taken counsel of the Lord, and obeyed the same,
thou shouldest have been prospered;
but thou hast taken counsel of them that have caused thee to err;
Thou hast also sought to exalt and establish thyself and thy own honour,
and not the truth and honour of God only, which if thou hadst truly done,
God would have honoured thee.
Thou hast greatly dishonoured and grieved the Lord, by setting up ministers,
whom he approveth not, and by providing them a forced maintenance,
that so they may make a prey of his people,
who for conscience-sake cannot put into their mouths,
being spiritually gathered therefrom by the word of the Lord.--O friend,
it is not the person of any man which the Lord regards,
but it is righteousness which he hath regard to; and so far as man acts in righteousness,
so far only is he accepted of the Lord, whatever his station may be.

Thou hast also grieved the holy Spirit,
by thy suffering all these wicked and profane shows and sports,
which have abounded since thy coming in.
Thou hast highly displeased the Lord God,
by thy suffering persecution to be carried on in thy name,
even whilst thou in words hast promised liberty:
Yea many are this day confined in holes and prisons for the testimony of a good conscience.
The Lord is displeased with the pride and wickedness
that abounds both in thy dominions and in thy family;
and thou thyself hast not been such a pattern and example as thou oughtest to have been.
When I behold the wickedness, cruelty and oppression,
which abound in this nation in open view, besides the secret abominations,
which are committed, and are plotting and lurking in chambers,
what idolatry is intended in secret to be introduced,
I am ready to conclude it had been better for thee, thou hadst never come.
Although many men flatter and applaud thee for selfish ends,
yet I see the Lord is displeased with thy ways.
Such as thou sowest, such thou must reap.
This is the truth that must stand, and in love to thy soul it is declared by him,
who must deal uprightly with all men: Though for it I suffer outwardly,
yet I have a witness in thy conscience, to which I am made manifest,
and peace with the Lord is my portion, which is better than an earthly crown.

[.signed-section-signature]
George Fox, the younger.

--

This letter being delivered to the king,
it is said he seemed to be considerably affected with the contents;
but that his brother the duke of York, whose temper was more gloomy, reserved,
and vindictive, being greatly exasperated at the writer, advised the king to punish him;
but the king, with much propriety, replied, It were better for us to mend our lives.

The mayor, Richard Brown, continued his severity, and sent fifty-seven more to prison;
for such was his pride and passion,
that he could not endure the sight of a Quaker without wrath and resentment.
It happened on the 31st of the month called March this year, he espied Edward Gollin,
a pretty way from him in Guildhall, with his hat on,
inoffensively discoursing with some persons met there about business,
whereupon the mayor ordered him to be sent to Newgate: Another time,
as he was going to the same place, he saw two men near Blackwell-hall,
with their caps on, whereupon he sent for them, and committed them to the counter,
where they were detained till the expiration of his mayoralty.

As one Philip Harwood was coming up Fosterlane, the mayor riding by, stopped his horse,
and asked Philip whether he was not a Quaker?
He answered, I am so called: Upon which the mayor, without any more words,
ordered him to Newgate, where he lay about three months.
He gave many instances of the cruelty of his disposition, one of which was,
that when the wife of Nicholas Ridley had been sent by him to Bridewell,
and fell sick there, her husband came to the mayor, interceding for her liberty;
to whom he gave this churlish answer, Let her lie there and rot,
thee mayest get another wife the sooner; and instead of shewing mercy to the sick woman,
sent her husband to Newgate for asking it.

About this time, beside the heavy sufferings from the secular powers,
this people were affected with intestine troubles,
occasioned by the caprice and vanity of one John Perrot.

This man had joined in society with the people called Quakers pretty early,
and too early taken upon him the ministerial office:
Being puffed up with a vain opinion of his own abilities,
he must needs go to Rome to convert the pope;
and procuring one John Love to accompany Him,
when they arrived at Leghorn they were taken up and examined by the inquisition,
and are reported upon their examination to have given their answers in a manner so satisfactory,
as to obtain their dismission with impunity.
From thence they went to Venice, and afterwards to Rome,
where they had not been long till they were taken up and imprisoned; Love, as reported,
in the inquisition, and Perrot in their Bedlam or hospital, for madmen.
Love died in prison, not without well-grounded suspicion of his being murdered there.
The report divulged was, that he had fasted to death; but it is said,
some nuns confessed he was privately dispatched in the night,
for his testifying against the idolatry of their religion.
Perrot lay there sometime longer.
Sewel represents him as a man of great natural parts;
but Thomas Elwood as not very unfit for the prison in which he was confined,
because during his confinement he writ some epistles, to be printed in England,
in such an affected fantastical style as bespoke him scarce sound in mind.

At length, through the solicitation of friends to some person of note and interest there,
he was released, and returned to England.
If he was elevated with spiritual pride and vain conceit before he went abroad,
the report of his great sufferings, joined with a great appearance of sanctity,
gaining him the compassionate affection and esteem of many friends,
his imaginary consequence and exaltedness of mind was increased to that degree,
that he thought himself farther enlightened than George Fox, and the rest of his friends,
and as an evidence thereof maintained that the custom
of putting off their hats in joining in public prayer,
was only a piece of formality and custom of the world,
which ought not to be practised without an immediate motion thereto.
That regard, which the exaggerated report of his sufferings had procured him,
and the fondness for novelties natural to many,
attached a considerable number of adherents to him,
to the introducing confusion and disorder in worship.
The next extravagance he adopted, was to let his beard grow,
in which he was followed by several of his partisans.
George Fox and the principal body of friends,
foreseeing the danger of drawing off the mind from a proper
attention to the necessary work of inward sanctification,
into jangling and contention about outward observations of little importance,
exerted their endeavours to prevent the spreading of the deception,
which they could not effectually do for some years;
till Perrot manifested more plainly the error of his spirit, and depravity of his heart,
by the instability and enormity of his conduct.
He went to America,
and there his airy unstable notions led him into manifest sensualities and fleshly liberties,
fantastically putting on gaudy apparel, and wearing a sword;
and under the pretence of being above forms, went so far at last,
as to reckon meeting for worship a form;
and by his example and doctrine led many to forsake the assembling themselves together,
as we shall have occasion more particularly to specify,
when we come to treat of the state of this society in America,
where having obtained some post under the government,
he who had before professed that Christ had forbidden all swearing,
is reported to have distinguished himself as a most rigorous exacter of oaths.

About the time that George Fox was excited to establish
an orderly discipline in the society,
he felt a warm impression of duty on his mind to appoint a meeting in London with those
who had been seduced by the said Perrot into a separation from the society,
to endeavour to recover them to a sound understanding,
and restore them to that unity of the body,
which they had broken (in part at least) by their deviation;
and through the divine blessing and assistance attending
his and his friends labour of love,
they were generally recovered, acknowledged their error,
and returned into the unity of the society;
whereby an end was put to this separation in England.

It was with the commencement of this year that the
aforementioned act against the Quakers came in force,
and the same hostile spirit that dictated the framing and passing it,
discovered itself in the execution.
One Philip Millar appears to be the first that molested them in London; who,
although vested with no office or legal authority, without any order or warrant,
came to the meeting in John`'s-street, with a rabble of people attending him,
and having a cane in his hand, commanded the attendant rabble to seize whom he pleased:
He then applied to the constable, and with menaces obliged him to go with him:
Of those he had ordered to be seized he selected five,
and had them carried before a justice, who committed them to prison.
Some days after he came again to the same meeting place,
and because the persons assembled would not depart at his command,
he struck several of them with his cane, and then charged the constable,
whom he had brought with him, with as many of them as he thought proper,
amongst whom was John Crook, who before his convincement had been a justice of peace;
they being taken before a justice, he took their words to come to him next morning,
which they did, when he ordered them to appear before the justices,
then sitting at Hicks`'s-hall, who committed nine of them to Newgate.

Thus we see the apprehension of those of this society,
who appeared at the house of commons, against this law, that, if passed into an act,
rude and unprincipled persons might take occasion to abuse them beyond law,
was not visionary; and of such like illegal treatment we meet with numerous instances.
Next let us take a view what satisfaction they received for their false imprisonment,
as a specimen of the kind of justice dispensed in this reign.

John Crook and others being brought before the justices at Hick`'s-hall,
and on their examination pointing out the illegality of their apprehension without warrant,
and the proceedings there upon, were notwithstanding committed to prison.
An indictment was drawn up against them, upon the late act against Quakers;
after which they were removed to Newgate in order to their trial at the Old Bailey.
On the 25th of the month called June, three of them were selected to begin with,
viz. John Crook, termed gentleman, Isaac Grey, physician, and John Boston, goldsmith,
men of property and character, who notwithstanding,
as the first symptom of the disposition of the court,
were now ranked with the vilest criminals,
being thrust into the baledock amongst felons and murderers;
from whence John Crook bbeing called to the bar,
instead of being charged with any crime or any indictment upon the late act,
it seems a surer and severer method of crimination had been concerted.
The judge began with the following question:

[.discourse-part]
_Judge._
When did you take the oath of allegiance?

[.discourse-part]
_John Crook._
I have been six weeks in prison, and am I now called to accuse myself?
which you ought not to put me upon.
_Nemo debet seipsum accusare._
I am an Englishman, and by the law of England I ought not to be taken or imprisoned,
nor disseized of my freehold, nor called in question, nor put to answer,
but according to the law of the land.
I stand here at this bar as a delinquent,
and do desire that my accuser may be brought forth, and then I shall answer to my charge,
if any I be guilty of.

[.discourse-part]
_Judge._
You are here demanded to take the required to oath of allegiance,
and when you have done that, you shall be heard about the other,
for we have power to tender it to any man.

[.discourse-part]
_John Crook._
Not to me upon this occasion, in this place,
for I am brought thither as an offender already, and not to be made an offender here,
or be obliged to criminate myself.
I challenge the benefits of the laws of England;
for by them is a better inheritance derived to me as an Englishman,
than that which I received from my parents; for by the former the latter is secured:
This the 29th chapter of magna charta, the petition of right of Car. I.
and other good laws of England have confirmed; therefore,
in claiming the benefit of them, I demand no more than my right.
And you that are judges on the bench ought to be my council, and not my accusers,
but to instruct me in the benefit of the laws, that I may not, through ignorance,
lose any advantage, which the laws of my country afford me, as an Englishman.

[.discourse-part]
_C+++.+++ Judge._
We sit here to do justice, and are upon our oaths;^
footnote:[This chief judge would have done well seriously to consider,
while he was preparing and predetermined to punish honest men,
merely for a religious scruple to take an oath,
by the severest law he could take hold of;
and which without any real occasion he put to them,
because he knew for conscience-sake they could not take it, in order to criminate them,
and put it out of their power to seek justice for their false imprisonment,
if they had been so inclined: Whether was a greater enormity to refuse taking an oath,
or to take oaths, and afterwards pay no regard to the obligation thereof?
I suppose that taken by a judge must be to do justice, without favour or affection,
enmity or ill-will, without respect of persons; which,
how far this was regarded in this trial, let the reader judge.
Judge`'s Oath,--"`You shall do equal law and execution of right to all his subjects,
rich and poor, without having regard to any person.`"]
and we are to tell you what is law, and not you us: Therefore, sirrah, you are too bold.

[.discourse-part]
_John Crook._
Sirrah is not a word for a judge: I am no felon,
neither ought you to menace the prisoner at the bar.
For I stand here as arraigned for my life and liberty,
and the preservation of my wife and children and outward estate:
Therefore I have a right to be fully heard, what I can say in my own defence,
according to law; and I hope the court will bear with me,
if I take the freedom to assert my liberty as an Englishman and a christian;
if I speak loud, it is from zeal for the truth; and mine innocency makes me bold.
Let me see my accuser, that I may know for what cause I have been six weeks imprisoned,
and do not put me to accuse myself by asking me questions.
Let my accuser come forth, or else discharge me by proclamation, as you ought to do.

[.discourse-part]
_Judge Twisden._
We take no notice of your being here, otherwise than as of a straggler,
or as of any other person, or of the people that are here this day;
for we may tender the oath to any man.
This was seconded by another judge: And the chief judge, in the process of the trial,
expressed himself thus: We look not upon what you are here for; but finding you here,
we tender you the oath.

The judges persisting in the oath being administered,
John Crook inquired by what law they had power to tender it?
and was answered by the third of King James; John Crook demurring,
desired the statute might be read, that it might appear upon what occasion,
and against whom it was made, but this would not be admitted,
and his objection was over-ruled.

The prisoners were remanded to prison, and brought into court again next day,
when they were demanded again to take the oath;
but still insisting on the plea that they ought to be first
tried and convicted upon the cause of their imprisonment,
the judge was provoked to transgress the bounds of decency so far,
as to call John Crook a saucy and impudent fellow.

In the afternoon of the same day they were again brought to the bar,
and a new indictment for refusing to take the oath of allegiance having been drawn up,
they were required to plead to it, guilty, or not guilty; to which objecting,
as not being satisfied whether they ought to plead to a created offence,
and thereby acquiesce in the introduction of a precedent
of an unusual proceeding in courts of judicature,
and dangerous to the liberty of the subject;
as also whether their pleading would not deprive them of the benefit of the law,
and quashing the indictment, or making exceptions against it;
and being informed it would not,
they pleaded in such form as their scrupulous consciences would permit,
that they were not guilty of what was false in the indictment,
which was the substance thereof; which at last was accepted.

Next day being brought to their trial, the jury, who had been present,
and witnesses of the previous proceedings, were discharged;
a new jury was empannelled (as was said) on purpose for their trial.
In this jury were divers soldiers,
some of whom had been actually concerned in offering illegal violence to this society,
by haling some out of their meetings or out of their houses.
So that they had no better quarter to expect from their jury than their judges;
the indictment being read,
they moved to have the trial put off till next quarter sessions,
to traverse the indictment, it being long and in Latin, and like to be a precedent,
and that having no copy of the indictment till that morning,
and then suddenly hurried down to the sessions,
they were neither allowed time to advise with counsel,
nor to be prepared (as to matter of law) to plead in their own defence.
To this reasonable request the judge replied, We have given you time enough,
and you shall have no more, for we will try you at this time, therefore swear the jury.
The prisoners remonstrating against the swearing
of the jury till this point was properly discussed,
and they were heard in their own defence, the court fell into confusion,
during which the prisoners were hurried about in consequence
of the confused orders of the court to the officers;
some crying, take them away; others, stay, let them alone;
some to put them in the baledock; others within the farthest bar,
whither they were thrust accordingly: during this confusion and uproar some cried,
go on to swear the jury, which the crier seemed to be about;
but such was the tumult in court and distance of the prisoners,
that they could not distinctly tell what was doing:
during the confusion also the evidence (they supposed) was given,
that they refused to take the oath, which they had not positively done:
These arbitrary proceedings occasioning the prisoners, with just reason, to complain;
the executioner, as often as they attempted to speak, was ordered to stop their mouths,
which he repeatedly did with a dirty cloth; and having a gag in his hand,
endeavoured to gag John Crook and others.
Upon this they cried out, '`Will you not give us leave to speak?
we except against some of the jury, as being our enemies,
and of those who by force commanded us to be pulled out of our meetings,
and carried us to prison without warrant or legal process; and must these be our judges?
we except against them.`'

[.discourse-part]
_Judge._
It is too late now, you should have done it before they had been sworn jurymen.
Jury, go together, that which you have to find is,
whether they have refused to take the oath,
which hath been sworn before you that they did: you need not go from the bar.
The like said the recorder and others, the confusion and noise continuing,
and several speaking together.

The prisoners demanded their privilege to make their
defence before the jury brought in their verdict,
but this was refused them, the chief judge refused, having remarked,
that "`if the Quakers had liberty to speak, they would make themselves famous,
and their judges odious`" instead of guarding the subjects rights,
they had recourse to their usual exclamation, "`Stop their mouths,
executioner,`" which he did with his dirty cloth, as before.
Yet when the jury was ordered to give in their verdict,
John Crook took the opportunity to express himself finally thus,
"`Let me have liberty first to speak, it is but few words,
and I hope I shall do it with what brevity and pertinency
my understanding will give me leave,
and the occasion requires; it is to the point of these two heads, matter of law,
and matter of conscience.
To matter of law I have this to say,
the statute by which you proceed against us was made against papists,
occasioned by the gun-powder plot, and is entitled,
for the better discovery and suppressing of popish recusants; but they have liberty,
and we are destroyed,
what in you lies,`" (this pinch produced an interruption from the court) "`As to conscience,
I have something to say, it is a tender thing, and we have known what it is to offend it;
and therefore we dare not break Christ`'s command, who said, swear not at all;
as also the apostle James`'s, above all things, my brethren, swear not.`"
Interrupted again with executioner, "`stop his mouth.`"
Then the judge called to hear the jury,
who said something which the prisoners could not hear,
but was supposed to be giving in the verdict according to the judges`' orders,
for they were fit for the purpose, having seemingly agreed upon their verdict,
be fore they heard the prisoner`'s defence.

Then silence being proclaimed, the recorder taking a paper in his hand,
read to the following purpose, viz.

[.embedded-content-document.legal]
--

The jury for the king do find that John Crook, John Boston, and Isaac Grey,
are guilty of refusing to take the oath of allegiance,
for which you do incur a premunire, which is
the forfeiture of all your real estates during life, and your personal estates forever,
and you to be out of the king`'s protection, and to be imprisoned during his pleasure.
And this is your sentence.

--

John Crook replied, "`We are still under God`'s protection.`"

The Court was adjourned, and the prisoners, remanded to Newgate.

Such a mockery of justice as this trial exhibits, I trust,
for the reputation and honour of the nation,
our history affords few or no instances at this day.
It demonstrates, beyond the power of all apologies to palliate,
that the government of England at this era,
was as arbitrary to the dissenters in general, and particularly the Quakers,
as any other absolute government whatsoever.
We are here presented with an instance of natural-born subjects,
who had violated no duty, committed no crime, contrived no sedition,
neither broken the peace, nor disturbed the government,
deprived of their birth-right in the charters of the Englishman`'s liberty,
confirmed by the most binding ratifications,
as the perpetual and inviolable privileges of the people of England.
Magna charta and the petition of rights infringed;--subjects illegally imprisoned:
brought to trial, and no crime charged upon them:
The court of judicature turned into an inquisition to make them criminate themselves,
and to deprive them of the means of demanding legal satisfaction for injury sustained:
Persons of property abused, not allowed to speak in their own defence;
stripped at once of their personal liberty and all their property;
time to traverse the indictment till the next sessions
refused men upon trial for their liberty and property,
although ordinarily granted in case of trespass to the value
of 5s. the errors whereof were sufficient to quash it:
Just exceptions to jurymen evaded by artifice.
And all this only because they could not reverence
the devices of bishops and convocations as gospel,
or blindly devote themselves to the instructions of a priesthood, who were,
for the major part, themselves more devoted to the court, to a party,
and to their own interest and preferment, than to the pure ministry of the gospel;
and because they durst not disobey the command of Christ.

Immediately after the aforesaid unjust and severe sentence was passed,
the prisoners`' estates were seized on.
During their imprisonment, John crook drew up a narrative of their trial,
and committed it to the press,
that the king and nation might not be ignorant of the measures now pursued,
and their tendency to despotism and the ruin of the subject;
which narrative is preserved at length in Sewel`'s [.book-title]#History,# p. 358,
etc. and Besse`'s [.book-title]#Collection of Sufferings,# p. 369,
etc. from which the foregoing abridged account is abstracted.
On the 23rd of the following month (as was supposed by order
from the king) they were set at liberty by the jailer;
but two days afterward,
John Boston and Isaac Grey were taken again by the jailer`'s servants,
and carried back to prison;
(John Crook being gone to the country and not to
be found) how long they were detained there,
or how or when discharged, we have no account.

It was one argument advanced by George Whitehead, in his pleading against the late act,
that as, there were divers laws before,
whereby the Quakers were brought under grievous sufferings,
as this particularly of 3. Jac.
for the oath of allegiance etc. and that therefore to make a new law,
particularly pointed at them on that account, was not only superfluous,
but adding grievance to grievance upon a body of people already under heavy oppression,
against whom; nothing worthy of suffering had been proved.
And seeing in the first succeeding instance the new law was not enforced;
but an old law made against popish recusants, and them only,
perverted to the punishment of innocent men while those against whom it was made,
were left unmolested and encouraged.
It seems the legislature and ministers of the law had no meaning
by new laws to supersede the old or let them lie dormant;
but to keep them all in force,
in order to persecute in the severest manner all ranks of this people.

Such was the disposition of those who had power in their hands at this time, the bishops,
legislature, judges, justices, ecclesiastics and laics to extirpate this society;
that under the pressure of afflictions and calamities
the most feelingly distressing to mankind,
and the apprehension of more to come, these seemed for them no human help;
yet trusting in that divine Being,
for the serving and obeying of whom in the sincerity of their hearts,
they were persecuted,
and supported through all by the testimony of an approving conscience,
they firmly bore the utmost malice of their persecutors without shrinking;
by their constancy they even wearied them out,
and at last by patient suffering attained quietude;
but at present they were only at the beginning of sorrows;
they had many close trials of their faith, and a long fight of afflictions to sustain,
before their patience could get the better of the
resentments and virulence of their adversaries.

Neither is this a singular case, but seems, on account of the severity of the penalty,
a preconcerted mode of proceeding at present and several years after,
frequently adopted against such of this body as appeared
most considerable for their services or estates,
contrary to equity or reasonable construction of law,
to apply a partial law for the better discovery of popish recusants,
in consequence of a desperate enterprise concerted by some of that class only,
at the distance of two reigns to the punishment of men the most remote from that denomination,
and who neither had, nor, I believe,
were even suspected to have any concern in any plot whatever.

In the next month at the assizes of Worcester,
Robert Smith was likewise indicted for refusing to take the oath of allegiance,
having been imprisoned in like manner with those before mentioned;
and when he was brought to the Worcester bar,
demanded also the cause of his imprisonment for five or six weeks,
in reply to the judge`'s inquiry, "`When did you take the oath of allegiance?`"
The judge`'s answer was, "`I meddle not with your imprisonment, but finding you here,
I tender you the oath of allegiance; will you take it or no?
I tell you the danger that will follow: You will incur a premunire,
and forfeit your estate to the King.

[.discourse-part]
_R+++.+++ Smith._
Who was that law made for, the papists or us?

[.discourse-part]
_Judge._
For both.

[.discourse-part]
_R+++.+++ Smith._
Why then is it not tendered to them, as well as us?

[.discourse-part]
_Judge._
They have taken it already.

[.discourse-part]
_R+++.+++ Smith._
Suppose I find some papists, or popishly affected, on the bench,
shall it be done to them?

[.discourse-part]
_Judge._
They have done it already.

[.discourse-part]
_R+++.+++ Smith._
Let us and the people see, that we may be satisfied.

[.discourse-part]
_Judge._
Will you take the oath or not?
Otherwise we will record your refusal, and call you again tomorrow,
and on your second refusal record it also,
and pass sentence of premunire upon you.

Accordingly
the next day the like sentence was passed upon him,
as J. Crook and companions, to which he replied, "`The Lord gives,
and if he permits to take away, the will of the Lord be done.`"

Thus with christian meekness and patient resignation to the divine will,
R+++.+++ Smith received the severe sentence of premunire,
under which he lay close confined in prison near ten years.
About three days after sentence given,
the sheriff made a seizure of his personal estate for the king,
and took an inventory of the same to the minutest article.

Thomas Stordy being at Carlisle assizes,
went to visit some of his friends in prison there,
where he was illegally detained by the jailer; and the next day he, with Stephen Pearson,
then a prisoner, was taken to the sessions house,
where the oath of allegiance was tendered to them, which they refusing,
were sent back to jail among the felons.
Next day they were indicted on the aforesaid statute of 3. Jac.
and had the sentence of premunire past upon them.
Soon after the sheriff seized their corn, cattle and other goods,
and proclaimed a public sale of them, at which they were sold far below the value,
because few cared to buy them, as esteeming them no better than plunder: However,
they were disposed of and carried away,
without any regard to the prisoners or their families; nor would the sheriff,
upon application, even allow anything to the poor labourers,
who had been employed in gathering in the corn,
and the price of whose labour lay therein, as their employers,
now plundered of their all, were disabled from paying them.
Under this hard sentence, they were continued close prisoners several years,
enduring their heavy suffering with exemplary patience,
being under their afflictions supported by the testimony of a good conscience,
in their obedience to the precept of Christ, Swear not at all.

At the quarter sessions at Hertford in October John King, Richard Thomas,
Abraham Rutt and Henry Sweeting,
appeared to answer a process against them for absence from the national worship,
when one of the justices, a counsellor,
made an invective against the Quakers and their meetings, as dangerous and formidable,
whereupon the bench let the first process stop,
and tendered them the oath of allegiance on the first day of the sessions,
giving them time till next morning to consider whether they would take it or not;
telling them, that if they refused they would incur a premunire.
Next morning they appeared again, and refusing to take it,
they were immediately indicted, found guilty,
and had sentence of premunire passed upon them.--Under
this cruel sentence they were returned to prison,
and close confined during a sharp winter, whereby their health was much impaired.
At the same sessions, an order was issued to the sheriff to seize all the lands,
tenements, goods and chattels of the prisoners;
the execution of which was prevented by timely application to the King,
and the prisoners, after thirty-one weeks confinement,
were released by the King`'s warrant.

In Sussex, Ambrose Rigge was committed to prison, indicted next assizes,
tried immediately, and sentence of premunire passed upon him,
by which was adjudged to lose all his lands and tenements during life,
his good and chattels forever, and suffer imprisonment during the King`'s pleasure.
Upon that sentence he was kept in prison ten years and four months.

To recite all the hard and illicit treatment this
society met with by the misapplication of this law,
and how many of them suffered the loss of all their substance,
personal liberty and protection of law, by premunires during the present year,
would carry me far beyond my bounds,
and might disgust the reader in a tedious detail of similar cases.
But the treatment of Thomas Goodyear and Benjamin Staples at the quarter
sessions at Oxford in the preceding year demands particular notice.
After receiving the sentence of premunire on the like account, Thomas Goodyear,
who was brought like a common malefactor with bolts on his legs, asking the court,
"`Whether the jailer had orders to fetter him?`"
was answered, "`the jailer may do as he will with you,
for you are out of the King`'s protection.`"
The jailer, encouraged in obduracy (habitual, it is probable,
in him) by the example of his superiors, when he brought them back to prison,
told the other prisoners, that if they wanted clothes,
they might take theirs off their backs,
for they can have no law against you: But one of the prisoners humanely answered,
He would rather go naked than strip honest men of their clothes,
who were stripped of all they had beside.
