== Chapter VI.

[.chapter-synopsis]
* Several tried on the Act 35 Q. Elizabeth, in order to Banishment on pain of death
* George Fox presents an Address to the King, informing him of the Sufferings of his Friends
* Five hundred imprisoned in London, of whom many died
* Remarkable Petition to the Mayor
* Great Abuses of the Soldiers and Trained Bands
* Particularly at the Bull and Mouth
* Sessions at the Old Baily
* General Release of Prisoners by Order of the King
* Persecution continued
* Wheelerstreet Meeting broken up
* The Assembly at Bull and Mouth shamefully abused
* Many are grievously wounded
* John Trowell dies of his Wounds
* The Coroner`'s Inquest being empannelled to inquire into the Cause of his Death
* He declines bringing in a Verdict
* An Account of this Murder presented to the King
* And to the Lord Mayor (so called)
* The Author of the Narrative committed to Newgate

What measures more arbitrary and inhuman could the utmost malice of man invent,
short of capital punishment,
than those now vainly pursued to exterminate this body of people.
Nay, it may be a question whether at once taking away
their lives had not been a lighter punishment,
than condemning men of repute, who had been inured to a comfortable way of living,
on competent estates or by laudable industry,
to languish out their days in noisome jails; robbed of their property;
they and their families reduced to want; deprived of all company,
but the refuse of mankind, and of everything that makes life tolerable,
except the testimony of a good conscience,
which their persecutor`'s power could not reach.

Yet as if all this were not sufficient to gratify the ill will of their enemies,
it was even attempted at this time to bring their lives into danger.
As we have just described the mode adopted for making men
offenders against the first part of the late act,
viz. the case of oaths,
I proceed to the first trial I meet with upon the second part thereof,
the attendance of their religious assemblies.
These were not tried upon the late act, but upon that of 35 Elizabeth,
as the more severe, and the severest they could lay hold of,
because it gave power to proceed to banishment and to endanger life at once;
whereas by the banishment latter they could not have that power till the third offence.

Several persons,
taken from their religious meetings and committed to the White-Lyon prison, Southwark,
after about nine weeks imprisonment, were brought to their trial before Richard Onflow,
president of the sessions and others, and arraigned upon the following indictment.

[.embedded-content-document.legal]
--

The jurors for our lord the King do present upon their oath, that Arthur Fisher,
late of the parish of St. Olave in the borough of Southwark in the county of Surry,
yeoman; Nathaniel Robinson of the same, yeoman; John Chandler of the same yeoman,
and others, being wicked, dangerous and seditious sectaries, and disloyal persons,
and above the age of sixteen years, who,
on the 29th day of June in the year of our Lord Charles the second, by the grace of God,
King of England, Scotland, France and Ireland, etc. the fourteenth,
have obstinately refused;
and everyone of them hath obstinately refused to repair unto some church, chapel,
or usual place of common prayer,
according to the laws and statutes of this kingdom of England,
in the like case set forth and provided,
after forty days next after the end of the session of parliament
begun and holden at Westminster on the 19th day of February
in the year of our Lady Elizabeth late Queen of England,
the thirty fifth, and there continued until the dissolution of the same,
being the tenth day of April in the 35th year above said, to wit,
on the 3rd day of August in the year of the reign of the said Charles King of
England the fourteenth abovesaid in the parish of St. Olave aforesaid,
in the borough of Southwark aforesaid, in the county aforesaid;
of themselves did voluntarily and unlawfully join
in and were present at an unlawful assembly,
conventicle and meeting at the said parish of St. Olave in the county aforesaid,
under colour and pretence of the exercise of religion,
against the laws and statutes of this kingdom of England,
in contempt of our said Lord the King that now is,
his laws and to the evil and dangerous example of all others in the like case,
offending against the peace of our said Lord the King that now is, his crown and dignity,
and contrary to the form of the statute in the same case set forth and provided.

--

The indictment being read,
the prisoners desired to be tried by the late act of parliament against conventicles;
but were answered they, might try them by what law they would, that was in force.
Then the prisoners desired the act they were to be tried by might be read,
viz. that of 35 of Elizabeth, which was done only in part.
They observing, in regard thereto, that it was made in times of ignorance,
whilst the principles of the reformation, and of civil and religious rights,
were not yet well understood,
and that therefore they accounted themselves unjustly dealt with,
in having obsolete laws that had been long suffered to lie dormant,
revived for the mere purpose of subjecting them to
the heaviest punishment that could be devised.
The answer they received was a requisition to plead to the indictment,
and some not being hasty to answer, were haled out of court to prison,
as taken pro confessis.
The rest, being twenty in number, pleaded not guilty.
The jury was called over, and they excepted against two, one of which was set aside,
having openly expressed his ill-will towards the Quakers:
the witnesses testified at most that in such a place they took such persons,
whose names were specified in writing.
In their defence against the facts charged in the indictment, they asserted,
that whereas they were accused of being wicked, dangerous and seditious sectaries,
that was not true; for they were neither wicked nor seditious,
but such as endeavoured to lead a peaceable and quiet life in godliness and honesty.
For the truth whereof they durst appeal to themselves.
And the charge of not coming to hear the common prayer was highly preposterous,
as the service-book was not quite printed several weeks after the said 29th of June,
and what crime could it be, not to go hear that which at that time,
was not to be heard anywhere.
The court was considerably embarrassed by this,
and other pinching reasons advanced by the prisoners,
some of whom were men of abilities and literature,
to that degree that the judge was at a loss to answer them only by shifts and evasions.
When the jury went out to consider of their verdict:, one of them was heard to say,
as they were going up, Here is a deal to do indeed,
to condemn a company of innocent men.

After some time they returned, and brought in their verdict guilty in part,
and not guilty in part; but this verdict would not be accepted; so being sent out again,
prevailing upon one another, they soon returned and declared the prisoners guilty.
Whereupon judge Onflow pronounced the following sentence:
"`That they should return to prison,
and there continue three months without bail or mainprize, after which time,
if they recanted not, they must abjure the realm, or be proceeded against as felons.`"

Just before passing the sentence,
the judge signified there was a means to escape the penalty, viz. "`submission that is,
to come to common prayer, and refrain their meetings.`"
To which giving their reasons for the refusal of both, he said,
"`then you must abjure the land.`"
It being remarked that abjure meant to forswear, one of the justices scoffingly added,
"`and you can`'t swear at all;`" either barbarously sporting himself in other mens`' misery,
or wantonly exulting in the prospect,
that they must of course incur the penalties of felony.

At a sessions at the same place on the 11th of November,
thirteen more of the prisoners were brought to the bar, and indicted as before;
five of them pleading not guilty, were tried, convicted and sentenced as the former;
the other eight seeing the court so partial that a fair hearing could not be expected,
refused to plead and were sent back to prison.

It hath been before remarked, that the instances of enforcing this law were not many,
nor equally encouraged with other modes of prosecution,
as the full enforcing thereof must terminate in public executions, and it is likely,
the ministers and principal promoters of these severities did not choose to incur
the odium or the guilt of inflicting capital punishment merely for religion,
as there had been few precedents since the reformation,
except where some pretext of treason or sedition
could be picked up to palliate the severity:
Yet the justices and inferior magistrates,
being most of them invested with authority on account of their bitterness against nonconformists,
seemed disposed in some cases to put this statute fully in force,
but for the intervention of higher authority.
It was however kept alive, and repeated menaces thrown out of enforcing it in terrorem;
but the proceedings thereon generally terminated in arbitrary imprisonment,
frequently till a release came by proclamation or pardon; a punishment severe enough.

Such was the universality of party rage at this time against this people,
that they were left unmolested in few or no parts of the nation.
George Fox, in an address to the king,
acquaints him that three thousand and sixty-eight of their
friends had been imprisoned since his restoration;
that their meetings were daily broken up by men with clubs and arms,
their friends thrown into the water,^
footnote:[About the 3rd of October, 1660, a constable and others armed with pitchforks,
bills, staves and such like weapons, entered a meeting at Stevenson in Berkshire,
pulled out Thomas Curtis and threw him into a pond, tearing his coat in pieces:
With the like barbarity they used several others, sparing neither age nor sex.
One of them was trodden on and kept down in the water
till some of their own company cried out,
you`'ll drown the man.
After which they drove the innocent people along the highway,
inhumanly abusing and bemiring them.
This abuse was said to be given them at the instigation of a drunken priest,
who being told, that his weapons ought to be spiritual,
replied that he would fight the Quakers with such weapons as he had.]
and trampled under foot till the blood gushed out.
Another narrative was printed, signed by twelve witnesses,
relating that upwards of four thousand two hundred of those called Quakers,
both men and women, were in prison, specifying the number in each county,
and upon what account.
Many of these had been grievously abused with beatings, tearing their clothes,
and taking them away.
Some put into such noisome prisons as were owned not fit for dogs.
Some prisons so crowded that the prisoners had not room to sit down all together.
In Cheshire sixty-eight persons were thus locked up in a small room.
No age or sex found any commiseration from the ill-principled magistrates of this reign.
Men of sixty, seventy or more years of age,
were without pity or remorse subjected to all the rigours of such
imprisonments under the infirmities of a natural decline;
many times they were forced to lie on the cold ground,
without being permitted the use of straw, and kept many days without victuals.
No wonder that many grew sick and died by such barbarous imprisonments as these.

In London and its suburbs were no fewer than five hundred imprisoned at this time,
and some in such narrow holes that every person had scarcely convenient room to lie down;
and the felons were suffered to rob them of their clothes and money.
In consequence many grew sick, and some died.
Amongst them were many poor men, whose families were exposed to want,
their customers lost and their trades ruined; those multiplied hardships,
which moved little or no compassion in magistrates,
who seem steeled against all the feelings of men,
were so sensibly felt with true brotherly affection
and sympathy by several of their fellow-members,
that about thirty of them, who were at liberty,
presented a petition to the mayor and sheriffs of London, offering themselves,
if no other means of relief could be found,
to lie in prison instead of the sick and the poorest of the prisoners,
that they might have liberty to go about their necessary
occasions for a few weeks to retrieve their business,
and rescue themselves and families from impending ruin;
which though not so legal as to be accepted,
yet demonstrates the affection of those that made the offer,
and conveyed to the magistrates such a lively representation
of the disastrous consequences of their merciless usage,
as must have inclined men, who had the least remains of humanity left,
to mitigate the severity of their proceedings,
but with the men now in authority it had no such effect.

Those who were left at liberty had but a very precarious enjoyment thereof,
being daily in danger of following their friends to prison for the same cause,
keeping up their religious assemblies from a religious persuasion of duty to their Maker;
yet whilst they were at liberty, they were not suffered to be at ease,
the soldiers and trained-bands, by the encouragement of the magistracy,
were let loose upon them, to beat, to bruise, to wound them nigh unto,
and even quite unto death; so that in the city of London, and divers other parts,
the treatment of this people bore more the appearance
of the French dragoonings of those called Hugonots,
than the metropolis of England,
entitled to the privilege of a constitution limited to legal rule; and looks as if,
by accumulated abuses, they designed to provoke them to some act of resistance,
which might furnish a pretence for proceeding against them as rioters and seditious,
which when they could not do, they termed their peaceable meetings riots,
and thereupon indicted and punished the attenders as such.

The meeting, distinguished by the name of Bull and Mouth,
being near the center of the city,
was particularly exposed to the tumultuous intrusions of these
disturbers of the peace (for they were employed for no other purpose,
by magistrates who were bound by their office and oaths to preserve
it.) To this meeting the soldiers came several first days successively,
with muskets, lighted matches, pikes and halberts, conducted by a military officer,
with his sword drawn in one hand and a cane in the other;
they usually made their entrance with violent rushing and uproar to terrify the assembly,
commanding the people assembled to be gone; which when they were not hasty to do,
as believing themselves in the way of their duty,
and those who gave the command invested with no legal authority;
then they began the shameful attack with their canes
and clubs upon the unresisting people,
unmanfully beating women as well as men, for they spared no age nor sex,
but laid on their blows with great force,
not only wounding their bodies with their blows, but their ears with scoffs, menaces,
oaths and imprecations, and threatening to fire at them;
this treatment they continued at one time about two hours, striking them with swords,
staves and the buts of their muskets, and haling them out of doors;
by such violence many were grievously wounded, some fainted away,
and some survived it but a short time.

When they had wearied themselves by these acts of violence,
they generally added the preacher, if they found one,
and as many of the hearers as they thought fit, to the number already imprisoned.

On the 12th, 13th and 14th days of the sessions at month called August,
the sessions were held again at the Old Bailey, to which,
numbers of the Quakers were brought as malefactors through the streets,
sometimes twelve sometimes twenty in a company.
This seemed to turn the tide of the public temper into compassion,
the people exclaiming as they passed along,
Ah! what woeful days are these! what pity it is that such honest people with
such good countenances should be haled up and down to courts and prisons?`"

Their trials were conducted in the accustomed manner;
the bench and jury prepared to convict them, the witnesses,
those men who ought to have been substituted in their places for breach of the peace,
being mostly the officers who had commanded the party that had abused them,
called as witnesses against the very persons whom themselves also
had stricken and dragged out of their meetings with violence:
it was remarked that these witnesses hesitated, and even contradicted themselves:
one being asked by the judge,
"`Are you certain these are the persons you took at that meeting,`" replied, "`My lord,
I don`'t know the faces of the men, but these mens`' names I have in a note here.`"
Yet such was the temper of the court and of the jury,
that this defective evidence was accepted as sufficient to convict them;
upon which they were sentenced in fines, some one hundred marks, some twenty pounds,
and others in less sums, and committed again till they should pay the fines.
Against several no evidence appeared, yet they were not discharged,
but sent back to prison with the rest.

It was not long however before they met with an unexpected release,
for before the end of the month the King was pleased to grant them a general amnesty,
by an order to the mayor, to the following purport:
"`That whereas divers persons going under the name of Quakers,
and other names of separation, were imprisoned for being at unlawful meetings,
yet did profess all obedience to him,
and it was hoped that for the time to come some of the said people would conform themselves;
and upon the occasion of his royal consort`'s coming to his palace at Whitehall,
he would have them discharge and enlarge all the
said people out of the jails of London and Middlesex,
excepting such as had been indicted for refusing the oaths of allegiance,
or were ringleaders or preachers among them.`"

In pursuance of this order all that had been committed
by Sir Richard Brown and others were released,
and the jails of London and Middlesex almost entirely cleared of Quakers,
a few only excepted; but in a short time were filled again,
for the King`'s mandate for their release gave little or no interruption
to the persecuting measures carried on against them.
Their meetings continued to be disturbed in like manner as is before related,
even with an additional degree of violence.

The very next day after the publication the King`'s letter the meeting
at Wheeler-street was broken up in the same abusive manner,
and persons taken and sent to New-prison,
whence after a detention of twelve days they were released.
The same day Sir Richard Brown, in company with some military officers,
meeting a person in the street going about his lawful occasions,
who had been discharged from Newgate the day before by the King`'s letter, called out,
There`'s a Quaker, take him up and carry him to the counter,
which by his attendants was accordingly done; and he, thus arbitrarily committed,
was detained for some time.

On the last day of the month called August,
when the meeting at Bull and Mouth was near breaking up,
Major-general Brown with a party of men entered the meeting-house,
with their swords drawn, in a manner rude and terrifying beyond expression,
and ordering the doors to be made soft,
fell upon the assembly with their swords and cudgels
in such an unmerciful and unmanly manner,
without regard to age or sex, cutting, bruising and levelling those before them,
as carried an appearance of open hostility,
beyond what had ever been seen in a time of peace.
Six or eight together being knocked down were dragged out,
and lay in the kennels senseless, helpless,
and seemingly half dead with the wounds and bruises they had received,
their blood lying visible in the streets, so that the passengers and spectators,
compassionating this abuse of unoffending people, cried out, Shame upon the perpetrators,
that such a resemblance of massacre should be committed in the streets of London;
some of whom, for their compassionate expressions, felt their share of the treatment.
The soldiers being asked, why they could be so cruel to their neighbours?
One of them answered, Nay, we are more merciful than we ought to be,
for we have orders to kill; and that his musket was double charged,
as most of those of the party were to his knowledge.^
footnote:[This looks as if some of the persecutors had suffered their
spirits to be embittered to so intemperate a degree as to thirst for blood,
as intending by this cruel usage to provoke some of this body to some act of resistance,
and then make it a pretext for carnage and massacre.
But I own myself at a loss to conceive what motive (except insatiable
malice) any could have even to meditate such cruelty,
which no attempts of this body,
nor any security to government gave the least shadow of occasion for.]

In consequence of this barbarous treatment several
were ready to faint through loss of blood;
many so disabled as to keep their beds sometime;
one man so wounded in the head that his brains were said to be visible,
and being immediately taken to a surgeon,
his life was thought to be in the utmost danger;
and one John Trowel actually dying by the wounds and bruises he received there,
it was judged expedient that his dead body should
be conveyed to the meeting room at Bull and Mouth,
where he received the violence which occasioned his death, for public inspection.
The coroner being called, empanelled a jury of the neighbours,
and gave them the usual charge, to make true inquiry,
and present upon their oaths what they found to be the cause of his death.
The jury accordingly viewed the body, with a surgeon or two attending them.
It was evident the man was murdered by some or other of the trained bands;
but as in the confused crowd the particular man who
murdered him could not be pointed out,
the jury desired his friends to inter the corps,
and departed without bringing in a verdict, alledging as their reason,
that if they brought in a verdict of wilful murder, and the murderer could not be found,
the city would be liable to a fine; the verdict was therefore suspended,
and the business dropped.
An account of that day`'s barbarity and this person`'s murder
was presented to the king by one of those called Quakers,
to whom the king expressed,
"`I assure you it was not by my advice that any of your friends should be slain;
you must tell the magistrates of the city of it,
and prosecute the law against them;`" but to what purpose,
whilst the magistrates of the city and ministers of justice were
ranking themselves in the number of their professed enemies.
The mayor was by letter duly apprised of this transaction; but giving no redress,
the said letter, with a narrative of these grievous abuses, was printed and published,
for which the author was committed to Newgate by Brown, for dispersing scandalous papers,
as he was pleased to call them.

[.the-end]
End of the first volume
